#!/usr/bin/env python
import sys, os.path
from distutils.sysconfig import get_python_lib

from Arch import getArch

buildSystemDir = os.path.abspath(sys.path[0] or os.curdir)

sys.path.append(buildSystemDir)

import SCons.Script
import MyEnv

SCons.Script.main()
