/* Generated by Cython 0.10.3 on Sun Feb  8 13:36:55 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__h5py__h5r
#include "stdlib.h"
#include "string.h"
#include "time.h"
#include "unistd.h"
#include "stdint.h"
#include "compat.h"
#include "lzf_filter.h"
#include "hdf5.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name, PyObject* kw_name); /*proto*/

static void __Pyx_RaiseArgtupleInvalid(const char* func_name, int exact,
    Py_ssize_t num_min, Py_ssize_t num_max, Py_ssize_t num_found); /*proto*/

static int __Pyx_ParseOptionalKeywords(PyObject *kwds, PyObject **argnames[],     PyObject *kwds2, PyObject *values[], Py_ssize_t num_pos_args,     const char* function_name); /*proto*/

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed,
    const char *name, int exact); /*proto*/

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type); /*proto*/

static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(const char *name); /*proto*/

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/

static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */

/* "/home/tachyon/h5py/h5py/h5.pxd":21
 *     cpdef bint __enter__(self) except -1
 *     cpdef bint __exit__(self, a, b, c) except -1
 *     cpdef bint acquire(self, int blocking=*) except -1             # <<<<<<<<<<<<<<
 *     cpdef bint release(self) except -1
 * 
 */

struct __pyx_opt_args_4h5py_2h5_4PHIL_acquire {
  int __pyx_n;
  int blocking;
};

/* "/home/tachyon/h5py/h5py/h5r.pxd":15
 * include "defs.pxd"
 * 
 * cdef union ref_u:             # <<<<<<<<<<<<<<
 *     hobj_ref_t         obj_ref
 *     hdset_reg_ref_t    reg_ref
 */

union __pyx_t_4h5py_3h5r_ref_u {
  hobj_ref_t obj_ref;
  hdset_reg_ref_t reg_ref;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":39
 * cpdef H5PYConfig get_config()
 * 
 * cdef class ObjectID:             # <<<<<<<<<<<<<<
 * 
 *     cdef object __weakref__
 */

struct __pyx_obj_4h5py_2h5_ObjectID {
  PyObject_HEAD
  PyObject *__weakref__;
  hid_t id;
  int _locked;
  PyObject *_hash;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":46
 *     cdef object _hash
 * 
 * cdef class SmartStruct:             # <<<<<<<<<<<<<<
 *     cdef object __weakref__
 *     cdef object _title
 */

struct __pyx_obj_4h5py_2h5_SmartStruct {
  PyObject_HEAD
  PyObject *__weakref__;
  PyObject *_title;
};

/* "/home/tachyon/h5py/h5py/h5s.pxd":17
 * from h5 cimport class ObjectID
 * 
 * cdef class SpaceID(ObjectID):             # <<<<<<<<<<<<<<
 *     pass
 * 
 */

struct __pyx_obj_4h5py_3h5s_SpaceID {
  struct __pyx_obj_4h5py_2h5_ObjectID __pyx_base;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":26
 * cpdef PHIL get_phil()
 * 
 * cdef class H5PYConfig:             # <<<<<<<<<<<<<<
 * 
 *     cdef object _r_name
 */

struct __pyx_obj_4h5py_2h5_H5PYConfig {
  PyObject_HEAD
  PyObject *_r_name;
  PyObject *_i_name;
  PyObject *_f_name;
  PyObject *_t_name;
  PyObject *API_16;
  PyObject *API_18;
  PyObject *DEBUG;
  PyObject *THREADS;
};

/* "/home/tachyon/h5py/h5py/h5r.pxd":19
 *     hdset_reg_ref_t    reg_ref
 * 
 * cdef class Reference:             # <<<<<<<<<<<<<<
 * 
 *     cdef ref_u ref
 */

struct __pyx_obj_4h5py_3h5r_Reference {
  PyObject_HEAD
  union __pyx_t_4h5py_3h5r_ref_u ref;
  int typecode;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":15
 * include "defs.pxd"
 * 
 * cdef class PHIL:             # <<<<<<<<<<<<<<
 * 
 *     cdef object lock
 */

struct __pyx_obj_4h5py_2h5_PHIL {
  PyObject_HEAD
  struct __pyx_vtabstruct_4h5py_2h5_PHIL *__pyx_vtab;
  PyObject *lock;
};


struct __pyx_vtabstruct_4h5py_2h5_PHIL {
  int (*__enter__)(struct __pyx_obj_4h5py_2h5_PHIL *, int __pyx_skip_dispatch);
  int (*__exit__)(struct __pyx_obj_4h5py_2h5_PHIL *, PyObject *, PyObject *, PyObject *, int __pyx_skip_dispatch);
  int (*acquire)(struct __pyx_obj_4h5py_2h5_PHIL *, int __pyx_skip_dispatch, struct __pyx_opt_args_4h5py_2h5_4PHIL_acquire *__pyx_optional_args);
  int (*release)(struct __pyx_obj_4h5py_2h5_PHIL *, int __pyx_skip_dispatch);
};
static struct __pyx_vtabstruct_4h5py_2h5_PHIL *__pyx_vtabptr_4h5py_2h5_PHIL;
/* Module declarations from h5py.h5 */

static PyTypeObject *__pyx_ptype_4h5py_2h5_PHIL = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_H5PYConfig = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_ObjectID = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_SmartStruct = 0;
static struct __pyx_obj_4h5py_2h5_PHIL *(*__pyx_f_4h5py_2h5_get_phil)(int __pyx_skip_dispatch); /*proto*/
static struct __pyx_obj_4h5py_2h5_H5PYConfig *(*__pyx_f_4h5py_2h5_get_config)(int __pyx_skip_dispatch); /*proto*/
static int (*__pyx_f_4h5py_2h5_init_hdf5)(void); /*proto*/
/* Module declarations from h5py.h5i */

static struct __pyx_obj_4h5py_2h5_ObjectID *(*__pyx_f_4h5py_3h5i_wrap_identifier)(hid_t); /*proto*/
/* Module declarations from h5py.h5s */

static PyTypeObject *__pyx_ptype_4h5py_3h5s_SpaceID = 0;
/* Module declarations from h5py.h5r */

static PyTypeObject *__pyx_ptype_4h5py_3h5r_Reference = 0;


/* Implementation of h5py.h5r */
static char __pyx_k_217[] = "\n    H5R API for object and region references.\n";
static char __pyx_k_dereference[] = "dereference";
static PyObject *__pyx_kp_dereference;
static char __pyx_k_get_region[] = "get_region";
static PyObject *__pyx_kp_get_region;
static char __pyx_k_get_obj_type[] = "get_obj_type";
static PyObject *__pyx_kp_get_obj_type;
static char __pyx_k___str__[] = "__str__";
static PyObject *__pyx_kp___str__;
static char __pyx_k___repr__[] = "__repr__";
static PyObject *__pyx_kp___repr__;
static char __pyx_k_loc[] = "loc";
static PyObject *__pyx_kp_loc;
static char __pyx_k_name[] = "name";
static PyObject *__pyx_kp_name;
static char __pyx_k_ref_type[] = "ref_type";
static PyObject *__pyx_kp_ref_type;
static char __pyx_k_space[] = "space";
static PyObject *__pyx_kp_space;
static char __pyx_k_id[] = "id";
static PyObject *__pyx_kp_id;
static char __pyx_k___doc__[] = "__doc__";
static PyObject *__pyx_kp___doc__;
static char __pyx_k__sync[] = "_sync";
static PyObject *__pyx_kp__sync;
static char __pyx_k_sync[] = "sync";
static PyObject *__pyx_kp_sync;
static char __pyx_k_nosync[] = "nosync";
static PyObject *__pyx_kp_nosync;
static char __pyx_k_OBJECT[] = "OBJECT";
static PyObject *__pyx_kp_OBJECT;
static char __pyx_k_DATASET_REGION[] = "DATASET_REGION";
static PyObject *__pyx_kp_DATASET_REGION;
static char __pyx_k_create[] = "create";
static PyObject *__pyx_kp_create;
static PyObject *__pyx_kp_217;
static PyObject *__pyx_kp_218;
static PyObject *__pyx_kp_219;
static PyObject *__pyx_kp_220;
static char __pyx_k_218[] = "HDF5 object reference";
static char __pyx_k_219[] = "HDF5 dataset region reference";
static char __pyx_k_220[] = "Unknown HDF5 reference";

/* "/home/tachyon/h5py/h5py/h5r.pyx":39
 * 
 * @sync
 * def create(ObjectID loc not None, char* name, int ref_type, SpaceID space=None):             # <<<<<<<<<<<<<<
 *     """(ObjectID loc, STRING name, INT ref_type, SpaceID space=None)
 *     => ReferenceObject ref
 */

static PyObject *__pyx_pf_4h5py_3h5r_create(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds); /*proto*/
static char __pyx_doc_4h5py_3h5r_create[] = "(ObjectID loc, STRING name, INT ref_type, SpaceID space=None)\n    => ReferenceObject ref\n\n    Create a new reference. The value of ref_type detemines the kind\n    of reference created:\n\n    OBJECT\n        Reference to an object in an HDF5 file.  Parameters \"loc\"\n        and \"name\" identify the object; \"space\" is unused.\n\n    DATASET_REGION    \n        Reference to a dataset region.  Parameters \"loc\" and\n        \"name\" identify the dataset; the selection on \"space\"\n        identifies the region.\n    ";
static PyObject *__pyx_pf_4h5py_3h5r_create(PyObject *__pyx_self, PyObject *__pyx_args, PyObject *__pyx_kwds) {
  struct __pyx_obj_4h5py_2h5_ObjectID *__pyx_v_loc = 0;
  char *__pyx_v_name;
  int __pyx_v_ref_type;
  struct __pyx_obj_4h5py_3h5s_SpaceID *__pyx_v_space = 0;
  hid_t __pyx_v_space_id;
  struct __pyx_obj_4h5py_3h5r_Reference *__pyx_v_ref;
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  int __pyx_2;
  herr_t __pyx_3;
  static PyObject **__pyx_pyargnames[] = {&__pyx_kp_loc,&__pyx_kp_name,&__pyx_kp_ref_type,&__pyx_kp_space,0};
  __pyx_self = __pyx_self;
  __pyx_v_space = ((struct __pyx_obj_4h5py_3h5s_SpaceID *)Py_None);
  if (unlikely(__pyx_kwds)) {
    PyObject* values[4] = {0,0,0,0};
    Py_ssize_t kw_args = PyDict_Size(__pyx_kwds);
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  4: values[3] = PyTuple_GET_ITEM(__pyx_args, 3);
      case  3: values[2] = PyTuple_GET_ITEM(__pyx_args, 2);
      case  2: values[1] = PyTuple_GET_ITEM(__pyx_args, 1);
      case  1: values[0] = PyTuple_GET_ITEM(__pyx_args, 0);
      case  0: break;
      default: goto __pyx_L5_argtuple_error;
    }
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  0:
      values[0] = PyDict_GetItem(__pyx_kwds, __pyx_kp_loc);
      if (likely(values[0])) kw_args--;
      else goto __pyx_L5_argtuple_error;
      case  1:
      values[1] = PyDict_GetItem(__pyx_kwds, __pyx_kp_name);
      if (likely(values[1])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("create", 0, 3, 4, 1); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
      case  2:
      values[2] = PyDict_GetItem(__pyx_kwds, __pyx_kp_ref_type);
      if (likely(values[2])) kw_args--;
      else {
        __Pyx_RaiseArgtupleInvalid("create", 0, 3, 4, 2); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      }
    }
    if (unlikely(kw_args > 0)) {
      if (unlikely(__Pyx_ParseOptionalKeywords(__pyx_kwds, __pyx_pyargnames, 0, values, PyTuple_GET_SIZE(__pyx_args), "create") < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    }
    __pyx_v_loc = ((struct __pyx_obj_4h5py_2h5_ObjectID *)values[0]);
    __pyx_v_name = __Pyx_PyBytes_AsString(values[1]); if (unlikely((!__pyx_v_name) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    __pyx_v_ref_type = __pyx_PyInt_int(values[2]); if (unlikely((__pyx_v_ref_type == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
    if (values[3]) {
      __pyx_v_space = ((struct __pyx_obj_4h5py_3h5s_SpaceID *)values[3]);
    }
  } else {
    switch (PyTuple_GET_SIZE(__pyx_args)) {
      case  4:
      __pyx_v_space = ((struct __pyx_obj_4h5py_3h5s_SpaceID *)PyTuple_GET_ITEM(__pyx_args, 3));
      case  3:
      __pyx_v_ref_type = __pyx_PyInt_int(PyTuple_GET_ITEM(__pyx_args, 2)); if (unlikely((__pyx_v_ref_type == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      __pyx_v_name = __Pyx_PyBytes_AsString(PyTuple_GET_ITEM(__pyx_args, 1)); if (unlikely((!__pyx_v_name) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
      __pyx_v_loc = ((struct __pyx_obj_4h5py_2h5_ObjectID *)PyTuple_GET_ITEM(__pyx_args, 0));
      break;
      default: goto __pyx_L5_argtuple_error;
    }
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L5_argtuple_error:;
  __Pyx_RaiseArgtupleInvalid("create", 0, 3, 4, PyTuple_GET_SIZE(__pyx_args)); {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  __pyx_L3_error:;
  __Pyx_AddTraceback("h5py.h5r.create");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __pyx_v_ref = ((struct __pyx_obj_4h5py_3h5r_Reference *)Py_None); Py_INCREF(Py_None);
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_loc), __pyx_ptype_4h5py_2h5_ObjectID, 0, "loc", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_space), __pyx_ptype_4h5py_3h5s_SpaceID, 1, "space", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":57
 *     cdef hid_t space_id
 *     cdef Reference ref
 *     ref = Reference()             # <<<<<<<<<<<<<<
 *     if space is None:
 *         space_id = -1
 */
  __pyx_1 = PyObject_Call(((PyObject *)((PyObject*)__pyx_ptype_4h5py_3h5r_Reference)), ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (!(__Pyx_TypeTest(__pyx_1, __pyx_ptype_4h5py_3h5r_Reference))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_v_ref));
  __pyx_v_ref = ((struct __pyx_obj_4h5py_3h5r_Reference *)__pyx_1);
  __pyx_1 = 0;

  /* "/home/tachyon/h5py/h5py/h5r.pyx":58
 *     cdef Reference ref
 *     ref = Reference()
 *     if space is None:             # <<<<<<<<<<<<<<
 *         space_id = -1
 *     else:
 */
  __pyx_2 = (((PyObject *)__pyx_v_space) == Py_None);
  if (__pyx_2) {

    /* "/home/tachyon/h5py/h5py/h5r.pyx":59
 *     ref = Reference()
 *     if space is None:
 *         space_id = -1             # <<<<<<<<<<<<<<
 *     else:
 *         space_id = space.id
 */
    __pyx_v_space_id = -1;
    goto __pyx_L6;
  }
  /*else*/ {

    /* "/home/tachyon/h5py/h5py/h5r.pyx":61
 *         space_id = -1
 *     else:
 *         space_id = space.id             # <<<<<<<<<<<<<<
 * 
 *     H5Rcreate(&ref.ref, loc.id, name, <H5R_type_t>ref_type, space_id)
 */
    __pyx_v_space_id = __pyx_v_space->__pyx_base.id;
  }
  __pyx_L6:;

  /* "/home/tachyon/h5py/h5py/h5r.pyx":63
 *         space_id = space.id
 * 
 *     H5Rcreate(&ref.ref, loc.id, name, <H5R_type_t>ref_type, space_id)             # <<<<<<<<<<<<<<
 *     ref.typecode = ref_type
 * 
 */
  __pyx_3 = H5Rcreate((&__pyx_v_ref->ref), __pyx_v_loc->id, __pyx_v_name, ((H5R_type_t)__pyx_v_ref_type), __pyx_v_space_id); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":64
 * 
 *     H5Rcreate(&ref.ref, loc.id, name, <H5R_type_t>ref_type, space_id)
 *     ref.typecode = ref_type             # <<<<<<<<<<<<<<
 * 
 *     return ref
 */
  __pyx_v_ref->typecode = __pyx_v_ref_type;

  /* "/home/tachyon/h5py/h5py/h5r.pyx":66
 *     ref.typecode = ref_type
 * 
 *     return ref             # <<<<<<<<<<<<<<
 * 
 * cdef class Reference:
 */
  Py_INCREF(((PyObject *)__pyx_v_ref));
  __pyx_r = ((PyObject *)__pyx_v_ref);
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  __Pyx_AddTraceback("h5py.h5r.create");
  __pyx_r = NULL;
  __pyx_L0:;
  Py_DECREF(__pyx_v_ref);
  return __pyx_r;
}

/* "/home/tachyon/h5py/h5py/h5r.pyx":80
 * 
 *     @sync
 *     def dereference(self, ObjectID id not None):             # <<<<<<<<<<<<<<
 *         """(ObjectID id) => ObjectID
 * 
 */

static PyObject *__pyx_pf_4h5py_3h5r_9Reference_dereference(PyObject *__pyx_v_self, PyObject *__pyx_v_id); /*proto*/
static char __pyx_doc_4h5py_3h5r_9Reference_dereference[] = "(ObjectID id) => ObjectID\n\n        Open the object pointed to by this reference and return its\n        identifier.  The file identifier (or the identifier for any object\n        in the file) must also be provided.\n\n        The reference type may be either OBJECT or DATASET_REGION.\n        ";
static PyObject *__pyx_pf_4h5py_3h5r_9Reference_dereference(PyObject *__pyx_v_self, PyObject *__pyx_v_id) {
  PyObject *__pyx_r;
  hid_t __pyx_1;
  PyObject *__pyx_2 = 0;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_id), __pyx_ptype_4h5py_2h5_ObjectID, 0, "id", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":89
 *         The reference type may be either OBJECT or DATASET_REGION.
 *         """
 *         return wrap_identifier(H5Rdereference(id.id, <H5R_type_t>self.typecode, &self.ref))             # <<<<<<<<<<<<<<
 * 
 *     @sync
 */
  __pyx_1 = H5Rdereference(((struct __pyx_obj_4h5py_2h5_ObjectID *)__pyx_v_id)->id, ((H5R_type_t)((struct __pyx_obj_4h5py_3h5r_Reference *)__pyx_v_self)->typecode), (&((struct __pyx_obj_4h5py_3h5r_Reference *)__pyx_v_self)->ref)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = ((PyObject *)__pyx_f_4h5py_3h5i_wrap_identifier(__pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 89; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("h5py.h5r.Reference.dereference");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/tachyon/h5py/h5py/h5r.pyx":92
 * 
 *     @sync
 *     def get_region(self, ObjectID id not None):             # <<<<<<<<<<<<<<
 *         """(ObjectID id) => SpaceID
 * 
 */

static PyObject *__pyx_pf_4h5py_3h5r_9Reference_get_region(PyObject *__pyx_v_self, PyObject *__pyx_v_id); /*proto*/
static char __pyx_doc_4h5py_3h5r_9Reference_get_region[] = "(ObjectID id) => SpaceID\n\n        Retrieve the dataspace selection pointed to by this reference.\n        Returns a copy of the dataset's dataspace, with the appropriate\n        elements selected.  The file identifier or the identifier of any\n        object in the file (including the dataset itself) must also be\n        provided.\n\n        The reference object must be of type DATASET_REGION.\n        ";
static PyObject *__pyx_pf_4h5py_3h5r_9Reference_get_region(PyObject *__pyx_v_self, PyObject *__pyx_v_id) {
  PyObject *__pyx_r;
  hid_t __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_id), __pyx_ptype_4h5py_2h5_ObjectID, 0, "id", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":103
 *         The reference object must be of type DATASET_REGION.
 *         """
 *         return SpaceID(H5Rget_region(id.id, <H5R_type_t>self.typecode, &self.ref))             # <<<<<<<<<<<<<<
 * 
 *     @sync
 */
  __pyx_1 = H5Rget_region(((struct __pyx_obj_4h5py_2h5_ObjectID *)__pyx_v_id)->id, ((H5R_type_t)((struct __pyx_obj_4h5py_3h5r_Reference *)__pyx_v_self)->typecode), (&((struct __pyx_obj_4h5py_3h5r_Reference *)__pyx_v_self)->ref)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyInt_FromLong(__pyx_1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_Call(((PyObject *)((PyObject*)__pyx_ptype_4h5py_3h5s_SpaceID)), ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 103; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  __Pyx_AddTraceback("h5py.h5r.Reference.get_region");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/tachyon/h5py/h5py/h5r.pyx":106
 * 
 *     @sync
 *     def get_obj_type(self, ObjectID id not None):             # <<<<<<<<<<<<<<
 *         """(ObjectID id) => INT obj_code
 * 
 */

static PyObject *__pyx_pf_4h5py_3h5r_9Reference_get_obj_type(PyObject *__pyx_v_self, PyObject *__pyx_v_id); /*proto*/
static char __pyx_doc_4h5py_3h5r_9Reference_get_obj_type[] = "(ObjectID id) => INT obj_code\n\n        Determine what type of object this eference points to.  The\n        reference may be either type OBJECT or DATASET_REGION.  The file\n        identifier or the identifier of any object in the file must also\n        be provided.\n\n        The return value is one of:\n\n        - h5g.LINK\n        - h5g.GROUP\n        - h5g.DATASET\n        - h5g.TYPE\n        ";
static PyObject *__pyx_pf_4h5py_3h5r_9Reference_get_obj_type(PyObject *__pyx_v_self, PyObject *__pyx_v_id) {
  PyObject *__pyx_r;
  enum H5G_obj_t __pyx_1;
  PyObject *__pyx_2 = 0;
  if (unlikely(!__Pyx_ArgTypeTest(((PyObject *)__pyx_v_id), __pyx_ptype_4h5py_2h5_ObjectID, 0, "id", 0))) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":121
 *         - h5g.TYPE
 *         """
 *         return <int>H5Rget_obj_type(id.id, <H5R_type_t>self.typecode, &self.ref)             # <<<<<<<<<<<<<<
 * 
 *     @nosync
 */
  __pyx_1 = H5Rget_obj_type(((struct __pyx_obj_4h5py_2h5_ObjectID *)__pyx_v_id)->id, ((H5R_type_t)((struct __pyx_obj_4h5py_3h5r_Reference *)__pyx_v_self)->typecode), (&((struct __pyx_obj_4h5py_3h5r_Reference *)__pyx_v_self)->ref)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyInt_FromLong(((int)__pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 121; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("h5py.h5r.Reference.get_obj_type");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/tachyon/h5py/h5py/h5r.pyx":124
 * 
 *     @nosync
 *     def __str__(self):             # <<<<<<<<<<<<<<
 *         if self.typecode == H5R_OBJECT:
 *             return "HDF5 object reference"
 */

static PyObject *__pyx_pf_4h5py_3h5r_9Reference___str__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_pf_4h5py_3h5r_9Reference___str__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  int __pyx_1;

  /* "/home/tachyon/h5py/h5py/h5r.pyx":125
 *     @nosync
 *     def __str__(self):
 *         if self.typecode == H5R_OBJECT:             # <<<<<<<<<<<<<<
 *             return "HDF5 object reference"
 *         elif self.typecode == H5R_DATASET_REGION:
 */
  __pyx_1 = (((struct __pyx_obj_4h5py_3h5r_Reference *)__pyx_v_self)->typecode == H5R_OBJECT);
  if (__pyx_1) {

    /* "/home/tachyon/h5py/h5py/h5r.pyx":126
 *     def __str__(self):
 *         if self.typecode == H5R_OBJECT:
 *             return "HDF5 object reference"             # <<<<<<<<<<<<<<
 *         elif self.typecode == H5R_DATASET_REGION:
 *             return "HDF5 dataset region reference"
 */
    Py_INCREF(__pyx_kp_218);
    __pyx_r = __pyx_kp_218;
    goto __pyx_L0;
    goto __pyx_L5;
  }

  /* "/home/tachyon/h5py/h5py/h5r.pyx":127
 *         if self.typecode == H5R_OBJECT:
 *             return "HDF5 object reference"
 *         elif self.typecode == H5R_DATASET_REGION:             # <<<<<<<<<<<<<<
 *             return "HDF5 dataset region reference"
 * 
 */
  __pyx_1 = (((struct __pyx_obj_4h5py_3h5r_Reference *)__pyx_v_self)->typecode == H5R_DATASET_REGION);
  if (__pyx_1) {

    /* "/home/tachyon/h5py/h5py/h5r.pyx":128
 *             return "HDF5 object reference"
 *         elif self.typecode == H5R_DATASET_REGION:
 *             return "HDF5 dataset region reference"             # <<<<<<<<<<<<<<
 * 
 *         return "Unknown HDF5 reference"
 */
    Py_INCREF(__pyx_kp_219);
    __pyx_r = __pyx_kp_219;
    goto __pyx_L0;
    goto __pyx_L5;
  }
  __pyx_L5:;

  /* "/home/tachyon/h5py/h5py/h5r.pyx":130
 *             return "HDF5 dataset region reference"
 * 
 *         return "Unknown HDF5 reference"             # <<<<<<<<<<<<<<
 * 
 *     def __repr__(self):
 */
  Py_INCREF(__pyx_kp_220);
  __pyx_r = __pyx_kp_220;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/tachyon/h5py/h5py/h5r.pyx":132
 *         return "Unknown HDF5 reference"
 * 
 *     def __repr__(self):             # <<<<<<<<<<<<<<
 *         return self.__str__()
 * 
 */

static PyObject *__pyx_pf_4h5py_3h5r_9Reference___repr__(PyObject *__pyx_v_self); /*proto*/
static PyObject *__pyx_pf_4h5py_3h5r_9Reference___repr__(PyObject *__pyx_v_self) {
  PyObject *__pyx_r;
  PyObject *__pyx_1 = 0;
  PyObject *__pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5r.pyx":133
 * 
 *     def __repr__(self):
 *         return self.__str__()             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_1 = PyObject_GetAttr(__pyx_v_self, __pyx_kp___str__); if (unlikely(!__pyx_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyObject_Call(__pyx_1, ((PyObject *)__pyx_empty_tuple), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 133; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_1); __pyx_1 = 0;
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_1);
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("h5py.h5r.Reference.__repr__");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

static PyObject *__pyx_tp_new_4h5py_3h5r_Reference(PyTypeObject *t, PyObject *a, PyObject *k) {
  PyObject *o = (*t->tp_alloc)(t, 0);
  if (!o) return 0;
  return o;
}

static void __pyx_tp_dealloc_4h5py_3h5r_Reference(PyObject *o) {
  (*Py_TYPE(o)->tp_free)(o);
}

static struct PyMethodDef __pyx_methods_4h5py_3h5r_Reference[] = {
  {"dereference", (PyCFunction)__pyx_pf_4h5py_3h5r_9Reference_dereference, METH_O, __pyx_doc_4h5py_3h5r_9Reference_dereference},
  {"get_region", (PyCFunction)__pyx_pf_4h5py_3h5r_9Reference_get_region, METH_O, __pyx_doc_4h5py_3h5r_9Reference_get_region},
  {"get_obj_type", (PyCFunction)__pyx_pf_4h5py_3h5r_9Reference_get_obj_type, METH_O, __pyx_doc_4h5py_3h5r_9Reference_get_obj_type},
  {"__str__", (PyCFunction)__pyx_pf_4h5py_3h5r_9Reference___str__, METH_NOARGS|METH_COEXIST, 0},
  {"__repr__", (PyCFunction)__pyx_pf_4h5py_3h5r_9Reference___repr__, METH_NOARGS|METH_COEXIST, 0},
  {0, 0, 0, 0}
};

static struct PyMemberDef __pyx_members_4h5py_3h5r_Reference[] = {
  {"typecode", T_INT, offsetof(struct __pyx_obj_4h5py_3h5r_Reference, typecode), READONLY, 0},
  {0, 0, 0, 0, 0}
};

static PyNumberMethods __pyx_tp_as_number_Reference = {
  0, /*nb_add*/
  0, /*nb_subtract*/
  0, /*nb_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_divide*/
  #endif
  0, /*nb_remainder*/
  0, /*nb_divmod*/
  0, /*nb_power*/
  0, /*nb_negative*/
  0, /*nb_positive*/
  0, /*nb_absolute*/
  0, /*nb_nonzero*/
  0, /*nb_invert*/
  0, /*nb_lshift*/
  0, /*nb_rshift*/
  0, /*nb_and*/
  0, /*nb_xor*/
  0, /*nb_or*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_coerce*/
  #endif
  0, /*nb_int*/
  0, /*nb_long*/
  0, /*nb_float*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_oct*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*nb_hex*/
  #endif
  0, /*nb_inplace_add*/
  0, /*nb_inplace_subtract*/
  0, /*nb_inplace_multiply*/
  #if PY_MAJOR_VERSION < 3
  0, /*nb_inplace_divide*/
  #endif
  0, /*nb_inplace_remainder*/
  0, /*nb_inplace_power*/
  0, /*nb_inplace_lshift*/
  0, /*nb_inplace_rshift*/
  0, /*nb_inplace_and*/
  0, /*nb_inplace_xor*/
  0, /*nb_inplace_or*/
  0, /*nb_floor_divide*/
  0, /*nb_true_divide*/
  0, /*nb_inplace_floor_divide*/
  0, /*nb_inplace_true_divide*/
  #if (PY_MAJOR_VERSION >= 3) || (Py_TPFLAGS_DEFAULT & Py_TPFLAGS_HAVE_INDEX)
  0, /*nb_index*/
  #endif
};

static PySequenceMethods __pyx_tp_as_sequence_Reference = {
  0, /*sq_length*/
  0, /*sq_concat*/
  0, /*sq_repeat*/
  0, /*sq_item*/
  0, /*sq_slice*/
  0, /*sq_ass_item*/
  0, /*sq_ass_slice*/
  0, /*sq_contains*/
  0, /*sq_inplace_concat*/
  0, /*sq_inplace_repeat*/
};

static PyMappingMethods __pyx_tp_as_mapping_Reference = {
  0, /*mp_length*/
  0, /*mp_subscript*/
  0, /*mp_ass_subscript*/
};

static PyBufferProcs __pyx_tp_as_buffer_Reference = {
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getreadbuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getwritebuffer*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getsegcount*/
  #endif
  #if PY_MAJOR_VERSION < 3
  0, /*bf_getcharbuffer*/
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  0, /*bf_getbuffer*/
  #endif
  #if PY_VERSION_HEX >= 0x02060000
  0, /*bf_releasebuffer*/
  #endif
};

PyTypeObject __pyx_type_4h5py_3h5r_Reference = {
  PyVarObject_HEAD_INIT(0, 0)
  "h5py.h5r.Reference", /*tp_name*/
  sizeof(struct __pyx_obj_4h5py_3h5r_Reference), /*tp_basicsize*/
  0, /*tp_itemsize*/
  __pyx_tp_dealloc_4h5py_3h5r_Reference, /*tp_dealloc*/
  0, /*tp_print*/
  0, /*tp_getattr*/
  0, /*tp_setattr*/
  0, /*tp_compare*/
  __pyx_pf_4h5py_3h5r_9Reference___repr__, /*tp_repr*/
  &__pyx_tp_as_number_Reference, /*tp_as_number*/
  &__pyx_tp_as_sequence_Reference, /*tp_as_sequence*/
  &__pyx_tp_as_mapping_Reference, /*tp_as_mapping*/
  0, /*tp_hash*/
  0, /*tp_call*/
  __pyx_pf_4h5py_3h5r_9Reference___str__, /*tp_str*/
  0, /*tp_getattro*/
  0, /*tp_setattro*/
  &__pyx_tp_as_buffer_Reference, /*tp_as_buffer*/
  Py_TPFLAGS_DEFAULT|Py_TPFLAGS_CHECKTYPES|Py_TPFLAGS_BASETYPE|Py_TPFLAGS_HAVE_NEWBUFFER, /*tp_flags*/
  " \n        Represents an HDF5 reference.\n\n        Objects of this class are created exclusively by the library and \n        cannot be modified.  The read-only attribute \"typecode\" determines \n        whether the reference is to an object in an HDF5 file (OBJECT) \n        or a dataset region (DATASET_REGION).\n    ", /*tp_doc*/
  0, /*tp_traverse*/
  0, /*tp_clear*/
  0, /*tp_richcompare*/
  0, /*tp_weaklistoffset*/
  0, /*tp_iter*/
  0, /*tp_iternext*/
  __pyx_methods_4h5py_3h5r_Reference, /*tp_methods*/
  __pyx_members_4h5py_3h5r_Reference, /*tp_members*/
  0, /*tp_getset*/
  0, /*tp_base*/
  0, /*tp_dict*/
  0, /*tp_descr_get*/
  0, /*tp_descr_set*/
  0, /*tp_dictoffset*/
  0, /*tp_init*/
  0, /*tp_alloc*/
  __pyx_tp_new_4h5py_3h5r_Reference, /*tp_new*/
  0, /*tp_free*/
  0, /*tp_is_gc*/
  0, /*tp_bases*/
  0, /*tp_mro*/
  0, /*tp_cache*/
  0, /*tp_subclasses*/
  0, /*tp_weaklist*/
};

static struct PyMethodDef __pyx_methods[] = {
  {"create", (PyCFunction)__pyx_pf_4h5py_3h5r_create, METH_VARARGS|METH_KEYWORDS, __pyx_doc_4h5py_3h5r_create},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    "h5r",
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_dereference, __pyx_k_dereference, sizeof(__pyx_k_dereference), 1, 1, 1},
  {&__pyx_kp_get_region, __pyx_k_get_region, sizeof(__pyx_k_get_region), 1, 1, 1},
  {&__pyx_kp_get_obj_type, __pyx_k_get_obj_type, sizeof(__pyx_k_get_obj_type), 1, 1, 1},
  {&__pyx_kp___str__, __pyx_k___str__, sizeof(__pyx_k___str__), 1, 1, 1},
  {&__pyx_kp___repr__, __pyx_k___repr__, sizeof(__pyx_k___repr__), 1, 1, 1},
  {&__pyx_kp_loc, __pyx_k_loc, sizeof(__pyx_k_loc), 1, 1, 1},
  {&__pyx_kp_name, __pyx_k_name, sizeof(__pyx_k_name), 1, 1, 1},
  {&__pyx_kp_ref_type, __pyx_k_ref_type, sizeof(__pyx_k_ref_type), 1, 1, 1},
  {&__pyx_kp_space, __pyx_k_space, sizeof(__pyx_k_space), 1, 1, 1},
  {&__pyx_kp_id, __pyx_k_id, sizeof(__pyx_k_id), 1, 1, 1},
  {&__pyx_kp___doc__, __pyx_k___doc__, sizeof(__pyx_k___doc__), 1, 1, 1},
  {&__pyx_kp__sync, __pyx_k__sync, sizeof(__pyx_k__sync), 1, 1, 1},
  {&__pyx_kp_sync, __pyx_k_sync, sizeof(__pyx_k_sync), 1, 1, 1},
  {&__pyx_kp_nosync, __pyx_k_nosync, sizeof(__pyx_k_nosync), 1, 1, 1},
  {&__pyx_kp_OBJECT, __pyx_k_OBJECT, sizeof(__pyx_k_OBJECT), 1, 1, 1},
  {&__pyx_kp_DATASET_REGION, __pyx_k_DATASET_REGION, sizeof(__pyx_k_DATASET_REGION), 1, 1, 1},
  {&__pyx_kp_create, __pyx_k_create, sizeof(__pyx_k_create), 1, 1, 1},
  {&__pyx_kp_217, __pyx_k_217, sizeof(__pyx_k_217), 0, 0, 0},
  {&__pyx_kp_218, __pyx_k_218, sizeof(__pyx_k_218), 0, 0, 0},
  {&__pyx_kp_219, __pyx_k_219, sizeof(__pyx_k_219), 0, 0, 0},
  {&__pyx_kp_220, __pyx_k_220, sizeof(__pyx_k_220), 0, 0, 0},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  return 0;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inith5r(void); /*proto*/
PyMODINIT_FUNC inith5r(void)
#else
PyMODINIT_FUNC PyInit_h5r(void); /*proto*/
PyMODINIT_FUNC PyInit_h5r(void)
#endif
{
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Library function declarations ---*/
  __pyx_init_filenames();
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4("h5r", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  if (PyType_Ready(&__pyx_type_4h5py_3h5r_Reference) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttrString(__pyx_m, "Reference", (PyObject *)&__pyx_type_4h5py_3h5r_Reference) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_3h5r_Reference = &__pyx_type_4h5py_3h5r_Reference;
  /*--- Type import code ---*/
  __pyx_ptype_4h5py_2h5_PHIL = __Pyx_ImportType("h5py.h5", "PHIL", sizeof(struct __pyx_obj_4h5py_2h5_PHIL)); if (unlikely(!__pyx_ptype_4h5py_2h5_PHIL)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_GetVtable(__pyx_ptype_4h5py_2h5_PHIL->tp_dict, &__pyx_vtabptr_4h5py_2h5_PHIL) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_H5PYConfig = __Pyx_ImportType("h5py.h5", "H5PYConfig", sizeof(struct __pyx_obj_4h5py_2h5_H5PYConfig)); if (unlikely(!__pyx_ptype_4h5py_2h5_H5PYConfig)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_ObjectID = __Pyx_ImportType("h5py.h5", "ObjectID", sizeof(struct __pyx_obj_4h5py_2h5_ObjectID)); if (unlikely(!__pyx_ptype_4h5py_2h5_ObjectID)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_SmartStruct = __Pyx_ImportType("h5py.h5", "SmartStruct", sizeof(struct __pyx_obj_4h5py_2h5_SmartStruct)); if (unlikely(!__pyx_ptype_4h5py_2h5_SmartStruct)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_3h5s_SpaceID = __Pyx_ImportType("h5py.h5s", "SpaceID", sizeof(struct __pyx_obj_4h5py_3h5s_SpaceID)); if (unlikely(!__pyx_ptype_4h5py_3h5s_SpaceID)) {__pyx_filename = __pyx_f[2]; __pyx_lineno = 17; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Function import code ---*/
  __pyx_3 = __Pyx_ImportModule("h5py.h5"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_3, "get_phil", (void**)&__pyx_f_4h5py_2h5_get_phil, "struct __pyx_obj_4h5py_2h5_PHIL *(int __pyx_skip_dispatch)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_3, "get_config", (void**)&__pyx_f_4h5py_2h5_get_config, "struct __pyx_obj_4h5py_2h5_H5PYConfig *(int __pyx_skip_dispatch)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_3, "init_hdf5", (void**)&__pyx_f_4h5py_2h5_init_hdf5, "int (void)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  __pyx_3 = __Pyx_ImportModule("h5py.h5i"); if (!__pyx_3) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_3, "wrap_identifier", (void**)&__pyx_f_4h5py_3h5i_wrap_identifier, "struct __pyx_obj_4h5py_2h5_ObjectID *(hid_t)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  /*--- Execution code ---*/

  /* "/home/tachyon/h5py/h5py/h5r.pyx":13
 * #-
 * __doc__ = \
 * """             # <<<<<<<<<<<<<<
 *     H5R API for object and region references.
 * """
 */
  if (PyObject_SetAttr(__pyx_m, __pyx_kp___doc__, __pyx_kp_217) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 12; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":25
 * 
 * # Initialization
 * init_hdf5()             # <<<<<<<<<<<<<<
 * 
 * # Runtime imports
 */
  __pyx_1 = __pyx_f_4h5py_2h5_init_hdf5(); if (unlikely(__pyx_1 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":28
 * 
 * # Runtime imports
 * from _sync import sync, nosync             # <<<<<<<<<<<<<<
 * 
 * # === Public constants and data structures ====================================
 */
  __pyx_2 = PyList_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_kp_sync);
  PyList_SET_ITEM(__pyx_2, 0, __pyx_kp_sync);
  Py_INCREF(__pyx_kp_nosync);
  PyList_SET_ITEM(__pyx_2, 1, __pyx_kp_nosync);
  __pyx_3 = __Pyx_Import(__pyx_kp__sync, ((PyObject *)__pyx_2)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_kp_sync); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_sync, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_kp_nosync); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_nosync, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5r.pyx":32
 * # === Public constants and data structures ====================================
 * 
 * OBJECT = H5R_OBJECT             # <<<<<<<<<<<<<<
 * DATASET_REGION = H5R_DATASET_REGION
 * 
 */
  __pyx_3 = PyInt_FromLong(H5R_OBJECT); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_OBJECT, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5r.pyx":33
 * 
 * OBJECT = H5R_OBJECT
 * DATASET_REGION = H5R_DATASET_REGION             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_2 = PyInt_FromLong(H5R_DATASET_REGION); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_DATASET_REGION, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5r.pyx":38
 * # === Reference API ===========================================================
 * 
 * @sync             # <<<<<<<<<<<<<<
 * def create(ObjectID loc not None, char* name, int ref_type, SpaceID space=None):
 *     """(ObjectID loc, STRING name, INT ref_type, SpaceID space=None)
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_kp_sync); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":39
 * 
 * @sync
 * def create(ObjectID loc not None, char* name, int ref_type, SpaceID space=None):             # <<<<<<<<<<<<<<
 *     """(ObjectID loc, STRING name, INT ref_type, SpaceID space=None)
 *     => ReferenceObject ref
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_create); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_create, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5r.pyx":79
 *     """
 * 
 *     @sync             # <<<<<<<<<<<<<<
 *     def dereference(self, ObjectID id not None):
 *         """(ObjectID id) => ObjectID
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_kp_sync); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":80
 * 
 *     @sync
 *     def dereference(self, ObjectID id not None):             # <<<<<<<<<<<<<<
 *         """(ObjectID id) => ObjectID
 * 
 */
  __pyx_4 = __Pyx_GetName((PyObject *)__pyx_ptype_4h5py_3h5r_Reference, __pyx_kp_dereference); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_4 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  if (PyDict_SetItem((PyObject *)__pyx_ptype_4h5py_3h5r_Reference->tp_dict, __pyx_kp_dereference, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 80; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyType_Modified(__pyx_ptype_4h5py_3h5r_Reference);

  /* "/home/tachyon/h5py/h5py/h5r.pyx":91
 *         return wrap_identifier(H5Rdereference(id.id, <H5R_type_t>self.typecode, &self.ref))
 * 
 *     @sync             # <<<<<<<<<<<<<<
 *     def get_region(self, ObjectID id not None):
 *         """(ObjectID id) => SpaceID
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_kp_sync); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":92
 * 
 *     @sync
 *     def get_region(self, ObjectID id not None):             # <<<<<<<<<<<<<<
 *         """(ObjectID id) => SpaceID
 * 
 */
  __pyx_2 = __Pyx_GetName((PyObject *)__pyx_ptype_4h5py_3h5r_Reference, __pyx_kp_get_region); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 91; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  if (PyDict_SetItem((PyObject *)__pyx_ptype_4h5py_3h5r_Reference->tp_dict, __pyx_kp_get_region, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 92; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyType_Modified(__pyx_ptype_4h5py_3h5r_Reference);

  /* "/home/tachyon/h5py/h5py/h5r.pyx":105
 *         return SpaceID(H5Rget_region(id.id, <H5R_type_t>self.typecode, &self.ref))
 * 
 *     @sync             # <<<<<<<<<<<<<<
 *     def get_obj_type(self, ObjectID id not None):
 *         """(ObjectID id) => INT obj_code
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_kp_sync); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":106
 * 
 *     @sync
 *     def get_obj_type(self, ObjectID id not None):             # <<<<<<<<<<<<<<
 *         """(ObjectID id) => INT obj_code
 * 
 */
  __pyx_4 = __Pyx_GetName((PyObject *)__pyx_ptype_4h5py_3h5r_Reference, __pyx_kp_get_obj_type); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = PyTuple_New(1); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_2, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_4 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_2), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 105; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  if (PyDict_SetItem((PyObject *)__pyx_ptype_4h5py_3h5r_Reference->tp_dict, __pyx_kp_get_obj_type, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 106; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyType_Modified(__pyx_ptype_4h5py_3h5r_Reference);

  /* "/home/tachyon/h5py/h5py/h5r.pyx":123
 *         return <int>H5Rget_obj_type(id.id, <H5R_type_t>self.typecode, &self.ref)
 * 
 *     @nosync             # <<<<<<<<<<<<<<
 *     def __str__(self):
 *         if self.typecode == H5R_OBJECT:
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_kp_nosync); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5r.pyx":124
 * 
 *     @nosync
 *     def __str__(self):             # <<<<<<<<<<<<<<
 *         if self.typecode == H5R_OBJECT:
 *             return "HDF5 object reference"
 */
  __pyx_2 = __Pyx_GetName((PyObject *)__pyx_ptype_4h5py_3h5r_Reference, __pyx_kp___str__); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_2);
  __pyx_2 = 0;
  __pyx_2 = PyObject_Call(__pyx_3, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 123; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  if (PyDict_SetItem((PyObject *)__pyx_ptype_4h5py_3h5r_Reference->tp_dict, __pyx_kp___str__, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyType_Modified(__pyx_ptype_4h5py_3h5r_Reference);

  /* "/home/tachyon/h5py/h5py/h5r.pxd":1
 * #+             # <<<<<<<<<<<<<<
 * #
 * # This file is part of h5py, a low-level Python interface to the HDF5 library.
 */
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("h5py.h5r");
  #if PY_MAJOR_VERSION >= 3
  return NULL;
  #endif
}

static const char *__pyx_filenames[] = {
  "h5r.pyx",
  "h5.pxd",
  "h5s.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static void __Pyx_RaiseDoubleKeywordsError(
    const char* func_name,
    PyObject* kw_name)
{
    PyErr_Format(PyExc_TypeError,
        #if PY_MAJOR_VERSION >= 3
        "%s() got multiple values for keyword argument '%U'", func_name, kw_name);
        #else
        "%s() got multiple values for keyword argument '%s'", func_name,
        PyString_AS_STRING(kw_name));
        #endif
}

static void __Pyx_RaiseArgtupleInvalid(
    const char* func_name,
    int exact,
    Py_ssize_t num_min,
    Py_ssize_t num_max,
    Py_ssize_t num_found)
{
    Py_ssize_t num_expected;
    const char *number, *more_or_less;

    if (num_found < num_min) {
        num_expected = num_min;
        more_or_less = "at least";
    } else {
        num_expected = num_max;
        more_or_less = "at most";
    }
    if (exact) {
        more_or_less = "exactly";
    }
    number = (num_expected == 1) ? "" : "s";
    PyErr_Format(PyExc_TypeError,
        #if PY_VERSION_HEX < 0x02050000
            "%s() takes %s %d positional argument%s (%d given)",
        #else
            "%s() takes %s %zd positional argument%s (%zd given)",
        #endif
        func_name, more_or_less, num_expected, number, num_found);
}

static int __Pyx_ParseOptionalKeywords(
    PyObject *kwds,
    PyObject **argnames[],
    PyObject *kwds2,
    PyObject *values[],
    Py_ssize_t num_pos_args,
    const char* function_name)
{
    PyObject *key = 0, *value = 0;
    Py_ssize_t pos = 0;
    PyObject*** name;
    PyObject*** first_kw_arg = argnames + num_pos_args;

    while (PyDict_Next(kwds, &pos, &key, &value)) {
        #if PY_MAJOR_VERSION < 3
        if (unlikely(!PyString_CheckExact(key)) && unlikely(!PyString_Check(key))) {
        #else
        if (unlikely(!PyUnicode_CheckExact(key)) && unlikely(!PyUnicode_Check(key))) {
        #endif
            goto invalid_keyword_type;
        } else {
            name = argnames;
            while (*name && (**name != key)) name++;
            if (*name) {
                if (name < first_kw_arg) goto arg_passed_twice;
                values[name-argnames] = value;
            } else {
                for (name = first_kw_arg; *name; name++) {
                    #if PY_MAJOR_VERSION >= 3
                    if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                        PyUnicode_Compare(**name, key) == 0) break;
                    #else
                    if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                        strcmp(PyString_AS_STRING(**name),
                               PyString_AS_STRING(key)) == 0) break;
                    #endif
                }
                if (*name) {
                    values[name-argnames] = value;
                } else {
                    /* unexpected keyword found */
                    for (name=argnames; name != first_kw_arg; name++) {
                        if (**name == key) goto arg_passed_twice;
                        #if PY_MAJOR_VERSION >= 3
                        if (PyUnicode_GET_SIZE(**name) == PyUnicode_GET_SIZE(key) &&
                            PyUnicode_Compare(**name, key) == 0) goto arg_passed_twice;
                        #else
                        if (PyString_GET_SIZE(**name) == PyString_GET_SIZE(key) &&
                            strcmp(PyString_AS_STRING(**name),
                                   PyString_AS_STRING(key)) == 0) goto arg_passed_twice;
                        #endif
                    }
                    if (kwds2) {
                        if (unlikely(PyDict_SetItem(kwds2, key, value))) goto bad;
                    } else {
                        goto invalid_keyword;
                    }
                }
            }
        }
    }
    return 0;
arg_passed_twice:
    __Pyx_RaiseDoubleKeywordsError(function_name, **name);
    goto bad;
invalid_keyword_type:
    PyErr_Format(PyExc_TypeError,
        "%s() keywords must be strings", function_name);
    goto bad;
invalid_keyword:
    PyErr_Format(PyExc_TypeError,
    #if PY_MAJOR_VERSION < 3
        "%s() got an unexpected keyword argument '%s'",
        function_name, PyString_AsString(key));
    #else
        "%s() got an unexpected keyword argument '%U'",
        function_name, key);
    #endif
bad:
    return -1;
}

static int __Pyx_ArgTypeTest(PyObject *obj, PyTypeObject *type, int none_allowed,
    const char *name, int exact)
{
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (none_allowed && obj == Py_None) return 1;
    else if (exact) {
        if (Py_TYPE(obj) == type) return 1;
    }
    else {
        if (PyObject_TypeCheck(obj, type)) return 1;
    }
    PyErr_Format(PyExc_TypeError,
        "Argument '%s' has incorrect type (expected %s, got %s)",
        name, type->tp_name, Py_TYPE(obj)->tp_name);
    return 0;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

static int __Pyx_TypeTest(PyObject *obj, PyTypeObject *type) {
    if (!type) {
        PyErr_Format(PyExc_SystemError, "Missing type object");
        return 0;
    }
    if (obj == Py_None || PyObject_TypeCheck(obj, type))
        return 1;
    PyErr_Format(PyExc_TypeError, "Cannot convert %s to %s",
        Py_TYPE(obj)->tp_name, type->tp_name);
    return 0;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(class_name);
    #else
    py_name = PyUnicode_FromString(class_name);
    #endif
    if (!py_name)
        goto bad;
    result = PyObject_GetAttr(py_module, py_name);
    Py_DECREF(py_name);
    py_name = 0;
    Py_DECREF(py_module);
    py_module = 0;
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_module);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(const char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(name);
    #else
    py_name = PyUnicode_FromString(name);
    #endif
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr) {
    int result;
    PyObject *pycobj;
    
    pycobj = PyMapping_GetItemString(dict, "__pyx_vtable__");
    if (!pycobj)
        goto bad;
    *(void **)vtabptr = PyCObject_AsVoidPtr(pycobj);
    if (!*(void **)vtabptr)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    char *desc;
    
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%s does not export expected C function %s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    desc = (char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    if (strcmp(desc, sig) != 0) {
        PyErr_Format(PyExc_TypeError,
            "C function %s.%s has wrong signature (expected %s, got %s)",
                PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    *f = PyCObject_AsVoidPtr(cobj);
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

