/* Generated by Cython 0.10.3 on Sun Feb  8 13:36:44 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__h5py__h5z
#include "stdlib.h"
#include "string.h"
#include "time.h"
#include "unistd.h"
#include "stdint.h"
#include "compat.h"
#include "lzf_filter.h"
#include "hdf5.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list); /*proto*/

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name); /*proto*/

static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(const char *name); /*proto*/

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/

static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */

/* "/home/tachyon/h5py/h5py/h5.pxd":21
 *     cpdef bint __enter__(self) except -1
 *     cpdef bint __exit__(self, a, b, c) except -1
 *     cpdef bint acquire(self, int blocking=*) except -1             # <<<<<<<<<<<<<<
 *     cpdef bint release(self) except -1
 * 
 */

struct __pyx_opt_args_4h5py_2h5_4PHIL_acquire {
  int __pyx_n;
  int blocking;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":26
 * cpdef PHIL get_phil()
 * 
 * cdef class H5PYConfig:             # <<<<<<<<<<<<<<
 * 
 *     cdef object _r_name
 */

struct __pyx_obj_4h5py_2h5_H5PYConfig {
  PyObject_HEAD
  PyObject *_r_name;
  PyObject *_i_name;
  PyObject *_f_name;
  PyObject *_t_name;
  PyObject *API_16;
  PyObject *API_18;
  PyObject *DEBUG;
  PyObject *THREADS;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":15
 * include "defs.pxd"
 * 
 * cdef class PHIL:             # <<<<<<<<<<<<<<
 * 
 *     cdef object lock
 */

struct __pyx_obj_4h5py_2h5_PHIL {
  PyObject_HEAD
  struct __pyx_vtabstruct_4h5py_2h5_PHIL *__pyx_vtab;
  PyObject *lock;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":39
 * cpdef H5PYConfig get_config()
 * 
 * cdef class ObjectID:             # <<<<<<<<<<<<<<
 * 
 *     cdef object __weakref__
 */

struct __pyx_obj_4h5py_2h5_ObjectID {
  PyObject_HEAD
  PyObject *__weakref__;
  hid_t id;
  int _locked;
  PyObject *_hash;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":46
 *     cdef object _hash
 * 
 * cdef class SmartStruct:             # <<<<<<<<<<<<<<
 *     cdef object __weakref__
 *     cdef object _title
 */

struct __pyx_obj_4h5py_2h5_SmartStruct {
  PyObject_HEAD
  PyObject *__weakref__;
  PyObject *_title;
};


/* "/home/tachyon/h5py/h5py/h5.pxd":15
 * include "defs.pxd"
 * 
 * cdef class PHIL:             # <<<<<<<<<<<<<<
 * 
 *     cdef object lock
 */

struct __pyx_vtabstruct_4h5py_2h5_PHIL {
  int (*__enter__)(struct __pyx_obj_4h5py_2h5_PHIL *, int __pyx_skip_dispatch);
  int (*__exit__)(struct __pyx_obj_4h5py_2h5_PHIL *, PyObject *, PyObject *, PyObject *, int __pyx_skip_dispatch);
  int (*acquire)(struct __pyx_obj_4h5py_2h5_PHIL *, int __pyx_skip_dispatch, struct __pyx_opt_args_4h5py_2h5_4PHIL_acquire *__pyx_optional_args);
  int (*release)(struct __pyx_obj_4h5py_2h5_PHIL *, int __pyx_skip_dispatch);
};
static struct __pyx_vtabstruct_4h5py_2h5_PHIL *__pyx_vtabptr_4h5py_2h5_PHIL;
/* Module declarations from h5py.h5 */

static PyTypeObject *__pyx_ptype_4h5py_2h5_PHIL = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_H5PYConfig = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_ObjectID = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_SmartStruct = 0;
static struct __pyx_obj_4h5py_2h5_PHIL *(*__pyx_f_4h5py_2h5_get_phil)(int __pyx_skip_dispatch); /*proto*/
static struct __pyx_obj_4h5py_2h5_H5PYConfig *(*__pyx_f_4h5py_2h5_get_config)(int __pyx_skip_dispatch); /*proto*/
static int (*__pyx_f_4h5py_2h5_init_hdf5)(void); /*proto*/
/* Module declarations from h5py.h5z */



/* Implementation of h5py.h5z */
static char __pyx_k_206[] = "\n    Filter API and constants\n";
static char __pyx_k_filter_code[] = "filter_code";
static PyObject *__pyx_kp_filter_code;
static char __pyx_k___doc__[] = "__doc__";
static PyObject *__pyx_kp___doc__;
static char __pyx_k__sync[] = "_sync";
static PyObject *__pyx_kp__sync;
static char __pyx_k_sync[] = "sync";
static PyObject *__pyx_kp_sync;
static char __pyx_k_nosync[] = "nosync";
static PyObject *__pyx_kp_nosync;
static char __pyx_k_FILTER_LZF[] = "FILTER_LZF";
static PyObject *__pyx_kp_FILTER_LZF;
static char __pyx_k_FILTER_ERROR[] = "FILTER_ERROR";
static PyObject *__pyx_kp_FILTER_ERROR;
static char __pyx_k_FILTER_NONE[] = "FILTER_NONE";
static PyObject *__pyx_kp_FILTER_NONE;
static char __pyx_k_FILTER_ALL[] = "FILTER_ALL";
static PyObject *__pyx_kp_FILTER_ALL;
static char __pyx_k_FILTER_DEFLATE[] = "FILTER_DEFLATE";
static PyObject *__pyx_kp_FILTER_DEFLATE;
static char __pyx_k_FILTER_SHUFFLE[] = "FILTER_SHUFFLE";
static PyObject *__pyx_kp_FILTER_SHUFFLE;
static char __pyx_k_207[] = "FILTER_FLETCHER32";
static PyObject *__pyx_kp_207;
static char __pyx_k_FILTER_SZIP[] = "FILTER_SZIP";
static PyObject *__pyx_kp_FILTER_SZIP;
static char __pyx_k_FILTER_RESERVED[] = "FILTER_RESERVED";
static PyObject *__pyx_kp_FILTER_RESERVED;
static char __pyx_k_FILTER_MAX[] = "FILTER_MAX";
static PyObject *__pyx_kp_FILTER_MAX;
static char __pyx_k_FLAG_DEFMASK[] = "FLAG_DEFMASK";
static PyObject *__pyx_kp_FLAG_DEFMASK;
static char __pyx_k_FLAG_MANDATORY[] = "FLAG_MANDATORY";
static PyObject *__pyx_kp_FLAG_MANDATORY;
static char __pyx_k_FLAG_OPTIONAL[] = "FLAG_OPTIONAL";
static PyObject *__pyx_kp_FLAG_OPTIONAL;
static char __pyx_k_FLAG_INVMASK[] = "FLAG_INVMASK";
static PyObject *__pyx_kp_FLAG_INVMASK;
static char __pyx_k_FLAG_REVERSE[] = "FLAG_REVERSE";
static PyObject *__pyx_kp_FLAG_REVERSE;
static char __pyx_k_FLAG_SKIP_EDC[] = "FLAG_SKIP_EDC";
static PyObject *__pyx_kp_FLAG_SKIP_EDC;
static char __pyx_k_208[] = "SZIP_ALLOW_K13_OPTION_MASK";
static PyObject *__pyx_kp_208;
static char __pyx_k_209[] = "SZIP_CHIP_OPTION_MASK";
static PyObject *__pyx_kp_209;
static char __pyx_k_SZIP_EC_OPTION_MASK[] = "SZIP_EC_OPTION_MASK";
static PyObject *__pyx_kp_SZIP_EC_OPTION_MASK;
static char __pyx_k_SZIP_NN_OPTION_MASK[] = "SZIP_NN_OPTION_MASK";
static PyObject *__pyx_kp_SZIP_NN_OPTION_MASK;
static char __pyx_k_210[] = "SZIP_MAX_PIXELS_PER_BLOCK";
static PyObject *__pyx_kp_210;
static char __pyx_k_211[] = "FILTER_CONFIG_ENCODE_ENABLED";
static PyObject *__pyx_kp_211;
static char __pyx_k_212[] = "FILTER_CONFIG_DECODE_ENABLED";
static PyObject *__pyx_kp_212;
static char __pyx_k_ERROR_EDC[] = "ERROR_EDC";
static PyObject *__pyx_kp_ERROR_EDC;
static char __pyx_k_DISABLE_EDC[] = "DISABLE_EDC";
static PyObject *__pyx_kp_DISABLE_EDC;
static char __pyx_k_ENABLE_EDC[] = "ENABLE_EDC";
static PyObject *__pyx_kp_ENABLE_EDC;
static char __pyx_k_NO_EDC[] = "NO_EDC";
static PyObject *__pyx_kp_NO_EDC;
static char __pyx_k_filter_avail[] = "filter_avail";
static PyObject *__pyx_kp_filter_avail;
static char __pyx_k_get_filter_info[] = "get_filter_info";
static PyObject *__pyx_kp_get_filter_info;
static PyObject *__pyx_kp_206;

/* "/home/tachyon/h5py/h5py/h5z.pyx":68
 * 
 * @sync
 * def filter_avail(int filter_code):             # <<<<<<<<<<<<<<
 *     """(INT filter_code) => BOOL
 * 
 */

static PyObject *__pyx_pf_4h5py_3h5z_filter_avail(PyObject *__pyx_self, PyObject *__pyx_arg_filter_code); /*proto*/
static char __pyx_doc_4h5py_3h5z_filter_avail[] = "(INT filter_code) => BOOL\n\n    Determine if the given filter is available to the library. The\n    filter code should be one of:\n\n    - FILTER_DEFLATE\n    - FILTER_SHUFFLE\n    - FILTER_FLETCHER32\n    - FILTER_SZIP\n    ";
static PyObject *__pyx_pf_4h5py_3h5z_filter_avail(PyObject *__pyx_self, PyObject *__pyx_arg_filter_code) {
  int __pyx_v_filter_code;
  PyObject *__pyx_r;
  htri_t __pyx_1;
  PyObject *__pyx_2 = 0;
  __pyx_self = __pyx_self;
  assert(__pyx_arg_filter_code); {
    __pyx_v_filter_code = __pyx_PyInt_int(__pyx_arg_filter_code); if (unlikely((__pyx_v_filter_code == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L3_error:;
  __Pyx_AddTraceback("h5py.h5z.filter_avail");
  return NULL;
  __pyx_L4_argument_unpacking_done:;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":79
 *     - FILTER_SZIP
 *     """
 *     return <bint>H5Zfilter_avail(<H5Z_filter_t>filter_code)             # <<<<<<<<<<<<<<
 * 
 * @sync
 */
  __pyx_1 = H5Zfilter_avail(((H5Z_filter_t)__pyx_v_filter_code)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_2 = __Pyx_PyBool_FromLong(((int)__pyx_1)); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 79; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("h5py.h5z.filter_avail");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

/* "/home/tachyon/h5py/h5py/h5z.pyx":82
 * 
 * @sync
 * def get_filter_info(int filter_code):             # <<<<<<<<<<<<<<
 *     """(INT filter_code) => INT filter_flags
 * 
 */

static PyObject *__pyx_pf_4h5py_3h5z_get_filter_info(PyObject *__pyx_self, PyObject *__pyx_arg_filter_code); /*proto*/
static char __pyx_doc_4h5py_3h5z_get_filter_info[] = "(INT filter_code) => INT filter_flags\n\n    Retrieve a bitfield with information about the given filter. The\n    filter code should be one of:\n\n    - FILTER_DEFLATE\n    - FILTER_SHUFFLE\n    - FILTER_FLETCHER32\n    - FILTER_SZIP\n\n    Valid bitmasks for use with the returned bitfield are:\n\n    - FILTER_CONFIG_ENCODE_ENABLED\n    - FILTER_CONFIG_DECODE_ENABLED\n    ";
static PyObject *__pyx_pf_4h5py_3h5z_get_filter_info(PyObject *__pyx_self, PyObject *__pyx_arg_filter_code) {
  int __pyx_v_filter_code;
  unsigned int __pyx_v_flags;
  PyObject *__pyx_r;
  herr_t __pyx_1;
  PyObject *__pyx_2 = 0;
  __pyx_self = __pyx_self;
  assert(__pyx_arg_filter_code); {
    __pyx_v_filter_code = __pyx_PyInt_int(__pyx_arg_filter_code); if (unlikely((__pyx_v_filter_code == (int)-1) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L3_error:;
  __Pyx_AddTraceback("h5py.h5z.get_filter_info");
  return NULL;
  __pyx_L4_argument_unpacking_done:;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":99
 *     """
 *     cdef unsigned int flags
 *     H5Zget_filter_info(<H5Z_filter_t>filter_code, &flags)             # <<<<<<<<<<<<<<
 *     return flags
 * 
 */
  __pyx_1 = H5Zget_filter_info(((H5Z_filter_t)__pyx_v_filter_code), (&__pyx_v_flags)); if (unlikely(PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 99; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5z.pyx":100
 *     cdef unsigned int flags
 *     H5Zget_filter_info(<H5Z_filter_t>filter_code, &flags)
 *     return flags             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_2 = PyLong_FromUnsignedLong(__pyx_v_flags); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 100; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_2;
  __pyx_2 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; Py_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("h5py.h5z.get_filter_info");
  __pyx_r = NULL;
  __pyx_L0:;
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {"filter_avail", (PyCFunction)__pyx_pf_4h5py_3h5z_filter_avail, METH_O, __pyx_doc_4h5py_3h5z_filter_avail},
  {"get_filter_info", (PyCFunction)__pyx_pf_4h5py_3h5z_get_filter_info, METH_O, __pyx_doc_4h5py_3h5z_get_filter_info},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    "h5z",
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_filter_code, __pyx_k_filter_code, sizeof(__pyx_k_filter_code), 1, 1, 1},
  {&__pyx_kp___doc__, __pyx_k___doc__, sizeof(__pyx_k___doc__), 1, 1, 1},
  {&__pyx_kp__sync, __pyx_k__sync, sizeof(__pyx_k__sync), 1, 1, 1},
  {&__pyx_kp_sync, __pyx_k_sync, sizeof(__pyx_k_sync), 1, 1, 1},
  {&__pyx_kp_nosync, __pyx_k_nosync, sizeof(__pyx_k_nosync), 1, 1, 1},
  {&__pyx_kp_FILTER_LZF, __pyx_k_FILTER_LZF, sizeof(__pyx_k_FILTER_LZF), 1, 1, 1},
  {&__pyx_kp_FILTER_ERROR, __pyx_k_FILTER_ERROR, sizeof(__pyx_k_FILTER_ERROR), 1, 1, 1},
  {&__pyx_kp_FILTER_NONE, __pyx_k_FILTER_NONE, sizeof(__pyx_k_FILTER_NONE), 1, 1, 1},
  {&__pyx_kp_FILTER_ALL, __pyx_k_FILTER_ALL, sizeof(__pyx_k_FILTER_ALL), 1, 1, 1},
  {&__pyx_kp_FILTER_DEFLATE, __pyx_k_FILTER_DEFLATE, sizeof(__pyx_k_FILTER_DEFLATE), 1, 1, 1},
  {&__pyx_kp_FILTER_SHUFFLE, __pyx_k_FILTER_SHUFFLE, sizeof(__pyx_k_FILTER_SHUFFLE), 1, 1, 1},
  {&__pyx_kp_207, __pyx_k_207, sizeof(__pyx_k_207), 1, 1, 1},
  {&__pyx_kp_FILTER_SZIP, __pyx_k_FILTER_SZIP, sizeof(__pyx_k_FILTER_SZIP), 1, 1, 1},
  {&__pyx_kp_FILTER_RESERVED, __pyx_k_FILTER_RESERVED, sizeof(__pyx_k_FILTER_RESERVED), 1, 1, 1},
  {&__pyx_kp_FILTER_MAX, __pyx_k_FILTER_MAX, sizeof(__pyx_k_FILTER_MAX), 1, 1, 1},
  {&__pyx_kp_FLAG_DEFMASK, __pyx_k_FLAG_DEFMASK, sizeof(__pyx_k_FLAG_DEFMASK), 1, 1, 1},
  {&__pyx_kp_FLAG_MANDATORY, __pyx_k_FLAG_MANDATORY, sizeof(__pyx_k_FLAG_MANDATORY), 1, 1, 1},
  {&__pyx_kp_FLAG_OPTIONAL, __pyx_k_FLAG_OPTIONAL, sizeof(__pyx_k_FLAG_OPTIONAL), 1, 1, 1},
  {&__pyx_kp_FLAG_INVMASK, __pyx_k_FLAG_INVMASK, sizeof(__pyx_k_FLAG_INVMASK), 1, 1, 1},
  {&__pyx_kp_FLAG_REVERSE, __pyx_k_FLAG_REVERSE, sizeof(__pyx_k_FLAG_REVERSE), 1, 1, 1},
  {&__pyx_kp_FLAG_SKIP_EDC, __pyx_k_FLAG_SKIP_EDC, sizeof(__pyx_k_FLAG_SKIP_EDC), 1, 1, 1},
  {&__pyx_kp_208, __pyx_k_208, sizeof(__pyx_k_208), 1, 1, 1},
  {&__pyx_kp_209, __pyx_k_209, sizeof(__pyx_k_209), 1, 1, 1},
  {&__pyx_kp_SZIP_EC_OPTION_MASK, __pyx_k_SZIP_EC_OPTION_MASK, sizeof(__pyx_k_SZIP_EC_OPTION_MASK), 1, 1, 1},
  {&__pyx_kp_SZIP_NN_OPTION_MASK, __pyx_k_SZIP_NN_OPTION_MASK, sizeof(__pyx_k_SZIP_NN_OPTION_MASK), 1, 1, 1},
  {&__pyx_kp_210, __pyx_k_210, sizeof(__pyx_k_210), 1, 1, 1},
  {&__pyx_kp_211, __pyx_k_211, sizeof(__pyx_k_211), 1, 1, 1},
  {&__pyx_kp_212, __pyx_k_212, sizeof(__pyx_k_212), 1, 1, 1},
  {&__pyx_kp_ERROR_EDC, __pyx_k_ERROR_EDC, sizeof(__pyx_k_ERROR_EDC), 1, 1, 1},
  {&__pyx_kp_DISABLE_EDC, __pyx_k_DISABLE_EDC, sizeof(__pyx_k_DISABLE_EDC), 1, 1, 1},
  {&__pyx_kp_ENABLE_EDC, __pyx_k_ENABLE_EDC, sizeof(__pyx_k_ENABLE_EDC), 1, 1, 1},
  {&__pyx_kp_NO_EDC, __pyx_k_NO_EDC, sizeof(__pyx_k_NO_EDC), 1, 1, 1},
  {&__pyx_kp_filter_avail, __pyx_k_filter_avail, sizeof(__pyx_k_filter_avail), 1, 1, 1},
  {&__pyx_kp_get_filter_info, __pyx_k_get_filter_info, sizeof(__pyx_k_get_filter_info), 1, 1, 1},
  {&__pyx_kp_206, __pyx_k_206, sizeof(__pyx_k_206), 0, 0, 0},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  return 0;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inith5z(void); /*proto*/
PyMODINIT_FUNC inith5z(void)
#else
PyMODINIT_FUNC PyInit_h5z(void); /*proto*/
PyMODINIT_FUNC PyInit_h5z(void)
#endif
{
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  PyObject *__pyx_3 = 0;
  PyObject *__pyx_4 = 0;
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Library function declarations ---*/
  __pyx_init_filenames();
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4("h5z", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  __pyx_ptype_4h5py_2h5_PHIL = __Pyx_ImportType("h5py.h5", "PHIL", sizeof(struct __pyx_obj_4h5py_2h5_PHIL)); if (unlikely(!__pyx_ptype_4h5py_2h5_PHIL)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_GetVtable(__pyx_ptype_4h5py_2h5_PHIL->tp_dict, &__pyx_vtabptr_4h5py_2h5_PHIL) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_H5PYConfig = __Pyx_ImportType("h5py.h5", "H5PYConfig", sizeof(struct __pyx_obj_4h5py_2h5_H5PYConfig)); if (unlikely(!__pyx_ptype_4h5py_2h5_H5PYConfig)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_ObjectID = __Pyx_ImportType("h5py.h5", "ObjectID", sizeof(struct __pyx_obj_4h5py_2h5_ObjectID)); if (unlikely(!__pyx_ptype_4h5py_2h5_ObjectID)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_SmartStruct = __Pyx_ImportType("h5py.h5", "SmartStruct", sizeof(struct __pyx_obj_4h5py_2h5_SmartStruct)); if (unlikely(!__pyx_ptype_4h5py_2h5_SmartStruct)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Function import code ---*/
  __pyx_2 = __Pyx_ImportModule("h5py.h5"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_2, "get_phil", (void**)&__pyx_f_4h5py_2h5_get_phil, "struct __pyx_obj_4h5py_2h5_PHIL *(int __pyx_skip_dispatch)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_2, "get_config", (void**)&__pyx_f_4h5py_2h5_get_config, "struct __pyx_obj_4h5py_2h5_H5PYConfig *(int __pyx_skip_dispatch)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_2, "init_hdf5", (void**)&__pyx_f_4h5py_2h5_init_hdf5, "int (void)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  /*--- Execution code ---*/

  /* "/home/tachyon/h5py/h5py/h5z.pyx":14
 * 
 * __doc__ = \
 * """             # <<<<<<<<<<<<<<
 *     Filter API and constants
 * """
 */
  if (PyObject_SetAttr(__pyx_m, __pyx_kp___doc__, __pyx_kp_206) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 13; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5z.pyx":24
 * 
 * # Initialization
 * init_hdf5()             # <<<<<<<<<<<<<<
 * 
 * # Runtime imports
 */
  __pyx_1 = __pyx_f_4h5py_2h5_init_hdf5(); if (unlikely(__pyx_1 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5z.pyx":27
 * 
 * # Runtime imports
 * from _sync import sync, nosync             # <<<<<<<<<<<<<<
 * 
 * # === Public constants and data structures ====================================
 */
  __pyx_2 = PyList_New(2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_INCREF(__pyx_kp_sync);
  PyList_SET_ITEM(__pyx_2, 0, __pyx_kp_sync);
  Py_INCREF(__pyx_kp_nosync);
  PyList_SET_ITEM(__pyx_2, 1, __pyx_kp_nosync);
  __pyx_3 = __Pyx_Import(__pyx_kp__sync, ((PyObject *)__pyx_2)); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(((PyObject *)__pyx_2)); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_kp_sync); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_sync, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  __pyx_2 = PyObject_GetAttr(__pyx_3, __pyx_kp_nosync); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_nosync, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":31
 * # === Public constants and data structures ====================================
 * 
 * FILTER_LZF = H5PY_FILTER_LZF             # <<<<<<<<<<<<<<
 * 
 * FILTER_ERROR    = H5Z_FILTER_ERROR
 */
  __pyx_3 = PyInt_FromLong(H5PY_FILTER_LZF); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_LZF, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":33
 * FILTER_LZF = H5PY_FILTER_LZF
 * 
 * FILTER_ERROR    = H5Z_FILTER_ERROR             # <<<<<<<<<<<<<<
 * FILTER_NONE     = H5Z_FILTER_NONE
 * FILTER_ALL      = H5Z_FILTER_ALL
 */
  __pyx_2 = PyInt_FromLong(H5Z_FILTER_ERROR); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_ERROR, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 33; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":34
 * 
 * FILTER_ERROR    = H5Z_FILTER_ERROR
 * FILTER_NONE     = H5Z_FILTER_NONE             # <<<<<<<<<<<<<<
 * FILTER_ALL      = H5Z_FILTER_ALL
 * FILTER_DEFLATE  = H5Z_FILTER_DEFLATE
 */
  __pyx_3 = PyInt_FromLong(H5Z_FILTER_NONE); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_NONE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":35
 * FILTER_ERROR    = H5Z_FILTER_ERROR
 * FILTER_NONE     = H5Z_FILTER_NONE
 * FILTER_ALL      = H5Z_FILTER_ALL             # <<<<<<<<<<<<<<
 * FILTER_DEFLATE  = H5Z_FILTER_DEFLATE
 * FILTER_SHUFFLE  = H5Z_FILTER_SHUFFLE
 */
  __pyx_2 = PyInt_FromLong(H5Z_FILTER_ALL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_ALL, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":36
 * FILTER_NONE     = H5Z_FILTER_NONE
 * FILTER_ALL      = H5Z_FILTER_ALL
 * FILTER_DEFLATE  = H5Z_FILTER_DEFLATE             # <<<<<<<<<<<<<<
 * FILTER_SHUFFLE  = H5Z_FILTER_SHUFFLE
 * FILTER_FLETCHER32 = H5Z_FILTER_FLETCHER32
 */
  __pyx_3 = PyInt_FromLong(H5Z_FILTER_DEFLATE); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_DEFLATE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":37
 * FILTER_ALL      = H5Z_FILTER_ALL
 * FILTER_DEFLATE  = H5Z_FILTER_DEFLATE
 * FILTER_SHUFFLE  = H5Z_FILTER_SHUFFLE             # <<<<<<<<<<<<<<
 * FILTER_FLETCHER32 = H5Z_FILTER_FLETCHER32
 * FILTER_SZIP     = H5Z_FILTER_SZIP
 */
  __pyx_2 = PyInt_FromLong(H5Z_FILTER_SHUFFLE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_SHUFFLE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":38
 * FILTER_DEFLATE  = H5Z_FILTER_DEFLATE
 * FILTER_SHUFFLE  = H5Z_FILTER_SHUFFLE
 * FILTER_FLETCHER32 = H5Z_FILTER_FLETCHER32             # <<<<<<<<<<<<<<
 * FILTER_SZIP     = H5Z_FILTER_SZIP
 * FILTER_RESERVED = H5Z_FILTER_RESERVED
 */
  __pyx_3 = PyInt_FromLong(H5Z_FILTER_FLETCHER32); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_207, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":39
 * FILTER_SHUFFLE  = H5Z_FILTER_SHUFFLE
 * FILTER_FLETCHER32 = H5Z_FILTER_FLETCHER32
 * FILTER_SZIP     = H5Z_FILTER_SZIP             # <<<<<<<<<<<<<<
 * FILTER_RESERVED = H5Z_FILTER_RESERVED
 * FILTER_MAX      = H5Z_FILTER_MAX
 */
  __pyx_2 = PyInt_FromLong(H5Z_FILTER_SZIP); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_SZIP, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":40
 * FILTER_FLETCHER32 = H5Z_FILTER_FLETCHER32
 * FILTER_SZIP     = H5Z_FILTER_SZIP
 * FILTER_RESERVED = H5Z_FILTER_RESERVED             # <<<<<<<<<<<<<<
 * FILTER_MAX      = H5Z_FILTER_MAX
 * 
 */
  __pyx_3 = PyInt_FromLong(H5Z_FILTER_RESERVED); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_RESERVED, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":41
 * FILTER_SZIP     = H5Z_FILTER_SZIP
 * FILTER_RESERVED = H5Z_FILTER_RESERVED
 * FILTER_MAX      = H5Z_FILTER_MAX             # <<<<<<<<<<<<<<
 * 
 * FLAG_DEFMASK    = H5Z_FLAG_DEFMASK
 */
  __pyx_2 = PyInt_FromLong(H5Z_FILTER_MAX); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FILTER_MAX, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 41; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":43
 * FILTER_MAX      = H5Z_FILTER_MAX
 * 
 * FLAG_DEFMASK    = H5Z_FLAG_DEFMASK             # <<<<<<<<<<<<<<
 * FLAG_MANDATORY  = H5Z_FLAG_MANDATORY
 * FLAG_OPTIONAL   = H5Z_FLAG_OPTIONAL
 */
  __pyx_3 = PyInt_FromLong(H5Z_FLAG_DEFMASK); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_DEFMASK, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 43; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":44
 * 
 * FLAG_DEFMASK    = H5Z_FLAG_DEFMASK
 * FLAG_MANDATORY  = H5Z_FLAG_MANDATORY             # <<<<<<<<<<<<<<
 * FLAG_OPTIONAL   = H5Z_FLAG_OPTIONAL
 * FLAG_INVMASK    = H5Z_FLAG_INVMASK
 */
  __pyx_2 = PyInt_FromLong(H5Z_FLAG_MANDATORY); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_MANDATORY, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":45
 * FLAG_DEFMASK    = H5Z_FLAG_DEFMASK
 * FLAG_MANDATORY  = H5Z_FLAG_MANDATORY
 * FLAG_OPTIONAL   = H5Z_FLAG_OPTIONAL             # <<<<<<<<<<<<<<
 * FLAG_INVMASK    = H5Z_FLAG_INVMASK
 * FLAG_REVERSE    = H5Z_FLAG_REVERSE
 */
  __pyx_3 = PyInt_FromLong(H5Z_FLAG_OPTIONAL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_OPTIONAL, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":46
 * FLAG_MANDATORY  = H5Z_FLAG_MANDATORY
 * FLAG_OPTIONAL   = H5Z_FLAG_OPTIONAL
 * FLAG_INVMASK    = H5Z_FLAG_INVMASK             # <<<<<<<<<<<<<<
 * FLAG_REVERSE    = H5Z_FLAG_REVERSE
 * FLAG_SKIP_EDC   = H5Z_FLAG_SKIP_EDC
 */
  __pyx_2 = PyInt_FromLong(H5Z_FLAG_INVMASK); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_INVMASK, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":47
 * FLAG_OPTIONAL   = H5Z_FLAG_OPTIONAL
 * FLAG_INVMASK    = H5Z_FLAG_INVMASK
 * FLAG_REVERSE    = H5Z_FLAG_REVERSE             # <<<<<<<<<<<<<<
 * FLAG_SKIP_EDC   = H5Z_FLAG_SKIP_EDC
 * 
 */
  __pyx_3 = PyInt_FromLong(H5Z_FLAG_REVERSE); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_REVERSE, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":48
 * FLAG_INVMASK    = H5Z_FLAG_INVMASK
 * FLAG_REVERSE    = H5Z_FLAG_REVERSE
 * FLAG_SKIP_EDC   = H5Z_FLAG_SKIP_EDC             # <<<<<<<<<<<<<<
 * 
 * SZIP_ALLOW_K13_OPTION_MASK  = H5_SZIP_ALLOW_K13_OPTION_MASK   #1
 */
  __pyx_2 = PyInt_FromLong(H5Z_FLAG_SKIP_EDC); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FLAG_SKIP_EDC, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 48; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":50
 * FLAG_SKIP_EDC   = H5Z_FLAG_SKIP_EDC
 * 
 * SZIP_ALLOW_K13_OPTION_MASK  = H5_SZIP_ALLOW_K13_OPTION_MASK   #1             # <<<<<<<<<<<<<<
 * SZIP_CHIP_OPTION_MASK       = H5_SZIP_CHIP_OPTION_MASK        #2
 * SZIP_EC_OPTION_MASK         = H5_SZIP_EC_OPTION_MASK          #4
 */
  __pyx_3 = PyInt_FromLong(H5_SZIP_ALLOW_K13_OPTION_MASK); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_208, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":51
 * 
 * SZIP_ALLOW_K13_OPTION_MASK  = H5_SZIP_ALLOW_K13_OPTION_MASK   #1
 * SZIP_CHIP_OPTION_MASK       = H5_SZIP_CHIP_OPTION_MASK        #2             # <<<<<<<<<<<<<<
 * SZIP_EC_OPTION_MASK         = H5_SZIP_EC_OPTION_MASK          #4
 * SZIP_NN_OPTION_MASK         = H5_SZIP_NN_OPTION_MASK          #32
 */
  __pyx_2 = PyInt_FromLong(H5_SZIP_CHIP_OPTION_MASK); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_209, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":52
 * SZIP_ALLOW_K13_OPTION_MASK  = H5_SZIP_ALLOW_K13_OPTION_MASK   #1
 * SZIP_CHIP_OPTION_MASK       = H5_SZIP_CHIP_OPTION_MASK        #2
 * SZIP_EC_OPTION_MASK         = H5_SZIP_EC_OPTION_MASK          #4             # <<<<<<<<<<<<<<
 * SZIP_NN_OPTION_MASK         = H5_SZIP_NN_OPTION_MASK          #32
 * SZIP_MAX_PIXELS_PER_BLOCK   = H5_SZIP_MAX_PIXELS_PER_BLOCK    #32
 */
  __pyx_3 = PyInt_FromLong(H5_SZIP_EC_OPTION_MASK); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_SZIP_EC_OPTION_MASK, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":53
 * SZIP_CHIP_OPTION_MASK       = H5_SZIP_CHIP_OPTION_MASK        #2
 * SZIP_EC_OPTION_MASK         = H5_SZIP_EC_OPTION_MASK          #4
 * SZIP_NN_OPTION_MASK         = H5_SZIP_NN_OPTION_MASK          #32             # <<<<<<<<<<<<<<
 * SZIP_MAX_PIXELS_PER_BLOCK   = H5_SZIP_MAX_PIXELS_PER_BLOCK    #32
 * 
 */
  __pyx_2 = PyInt_FromLong(H5_SZIP_NN_OPTION_MASK); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_SZIP_NN_OPTION_MASK, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 53; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":54
 * SZIP_EC_OPTION_MASK         = H5_SZIP_EC_OPTION_MASK          #4
 * SZIP_NN_OPTION_MASK         = H5_SZIP_NN_OPTION_MASK          #32
 * SZIP_MAX_PIXELS_PER_BLOCK   = H5_SZIP_MAX_PIXELS_PER_BLOCK    #32             # <<<<<<<<<<<<<<
 * 
 * FILTER_CONFIG_ENCODE_ENABLED = H5Z_FILTER_CONFIG_ENCODE_ENABLED
 */
  __pyx_3 = PyInt_FromLong(H5_SZIP_MAX_PIXELS_PER_BLOCK); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_210, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 54; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":56
 * SZIP_MAX_PIXELS_PER_BLOCK   = H5_SZIP_MAX_PIXELS_PER_BLOCK    #32
 * 
 * FILTER_CONFIG_ENCODE_ENABLED = H5Z_FILTER_CONFIG_ENCODE_ENABLED             # <<<<<<<<<<<<<<
 * FILTER_CONFIG_DECODE_ENABLED = H5Z_FILTER_CONFIG_DECODE_ENABLED
 * 
 */
  __pyx_2 = PyInt_FromLong(H5Z_FILTER_CONFIG_ENCODE_ENABLED); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_211, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":57
 * 
 * FILTER_CONFIG_ENCODE_ENABLED = H5Z_FILTER_CONFIG_ENCODE_ENABLED
 * FILTER_CONFIG_DECODE_ENABLED = H5Z_FILTER_CONFIG_DECODE_ENABLED             # <<<<<<<<<<<<<<
 * 
 * ERROR_EDC   = H5Z_ERROR_EDC
 */
  __pyx_3 = PyInt_FromLong(H5Z_FILTER_CONFIG_DECODE_ENABLED); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_212, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":59
 * FILTER_CONFIG_DECODE_ENABLED = H5Z_FILTER_CONFIG_DECODE_ENABLED
 * 
 * ERROR_EDC   = H5Z_ERROR_EDC             # <<<<<<<<<<<<<<
 * DISABLE_EDC = H5Z_DISABLE_EDC
 * ENABLE_EDC  = H5Z_ENABLE_EDC
 */
  __pyx_2 = PyInt_FromLong(H5Z_ERROR_EDC); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_ERROR_EDC, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":60
 * 
 * ERROR_EDC   = H5Z_ERROR_EDC
 * DISABLE_EDC = H5Z_DISABLE_EDC             # <<<<<<<<<<<<<<
 * ENABLE_EDC  = H5Z_ENABLE_EDC
 * NO_EDC      = H5Z_NO_EDC
 */
  __pyx_3 = PyInt_FromLong(H5Z_DISABLE_EDC); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_DISABLE_EDC, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":61
 * ERROR_EDC   = H5Z_ERROR_EDC
 * DISABLE_EDC = H5Z_DISABLE_EDC
 * ENABLE_EDC  = H5Z_ENABLE_EDC             # <<<<<<<<<<<<<<
 * NO_EDC      = H5Z_NO_EDC
 * 
 */
  __pyx_2 = PyInt_FromLong(H5Z_ENABLE_EDC); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_ENABLE_EDC, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":62
 * DISABLE_EDC = H5Z_DISABLE_EDC
 * ENABLE_EDC  = H5Z_ENABLE_EDC
 * NO_EDC      = H5Z_NO_EDC             # <<<<<<<<<<<<<<
 * 
 * 
 */
  __pyx_3 = PyInt_FromLong(H5Z_NO_EDC); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_NO_EDC, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":67
 * # === Filter API  =============================================================
 * 
 * @sync             # <<<<<<<<<<<<<<
 * def filter_avail(int filter_code):
 *     """(INT filter_code) => BOOL
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_sync); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5z.pyx":68
 * 
 * @sync
 * def filter_avail(int filter_code):             # <<<<<<<<<<<<<<
 *     """(INT filter_code) => BOOL
 * 
 */
  __pyx_3 = __Pyx_GetName(__pyx_m, __pyx_kp_filter_avail); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_4 = PyTuple_New(1); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_4, 0, __pyx_3);
  __pyx_3 = 0;
  __pyx_3 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_4), NULL); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_4)); __pyx_4 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_filter_avail, __pyx_3) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_3); __pyx_3 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pyx":81
 *     return <bint>H5Zfilter_avail(<H5Z_filter_t>filter_code)
 * 
 * @sync             # <<<<<<<<<<<<<<
 * def get_filter_info(int filter_code):
 *     """(INT filter_code) => INT filter_flags
 */
  __pyx_2 = __Pyx_GetName(__pyx_m, __pyx_kp_sync); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5z.pyx":82
 * 
 * @sync
 * def get_filter_info(int filter_code):             # <<<<<<<<<<<<<<
 *     """(INT filter_code) => INT filter_flags
 * 
 */
  __pyx_4 = __Pyx_GetName(__pyx_m, __pyx_kp_get_filter_info); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_3 = PyTuple_New(1); if (unlikely(!__pyx_3)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  PyTuple_SET_ITEM(__pyx_3, 0, __pyx_4);
  __pyx_4 = 0;
  __pyx_4 = PyObject_Call(__pyx_2, ((PyObject *)__pyx_3), NULL); if (unlikely(!__pyx_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 81; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  Py_DECREF(((PyObject *)__pyx_3)); __pyx_3 = 0;
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_get_filter_info, __pyx_4) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 82; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_4); __pyx_4 = 0;

  /* "/home/tachyon/h5py/h5py/h5z.pxd":1
 * #+             # <<<<<<<<<<<<<<
 * #
 * # This file is part of h5py, a low-level Python interface to the HDF5 library.
 */
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  Py_XDECREF(__pyx_3);
  Py_XDECREF(__pyx_4);
  __Pyx_AddTraceback("h5py.h5z");
  #if PY_MAJOR_VERSION >= 3
  return NULL;
  #endif
}

static const char *__pyx_filenames[] = {
  "h5z.pyx",
  "h5.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static PyObject *__Pyx_Import(PyObject *name, PyObject *from_list) {
    PyObject *__import__ = 0;
    PyObject *empty_list = 0;
    PyObject *module = 0;
    PyObject *global_dict = 0;
    PyObject *empty_dict = 0;
    PyObject *list;
    __import__ = PyObject_GetAttrString(__pyx_b, "__import__");
    if (!__import__)
        goto bad;
    if (from_list)
        list = from_list;
    else {
        empty_list = PyList_New(0);
        if (!empty_list)
            goto bad;
        list = empty_list;
    }
    global_dict = PyModule_GetDict(__pyx_m);
    if (!global_dict)
        goto bad;
    empty_dict = PyDict_New();
    if (!empty_dict)
        goto bad;
    module = PyObject_CallFunction(__import__, "OOOO",
        name, global_dict, empty_dict, list);
bad:
    Py_XDECREF(empty_list);
    Py_XDECREF(__import__);
    Py_XDECREF(empty_dict);
    return module;
}

static PyObject *__Pyx_GetName(PyObject *dict, PyObject *name) {
    PyObject *result;
    result = PyObject_GetAttr(dict, name);
    if (!result)
        PyErr_SetObject(PyExc_NameError, name);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(class_name);
    #else
    py_name = PyUnicode_FromString(class_name);
    #endif
    if (!py_name)
        goto bad;
    result = PyObject_GetAttr(py_module, py_name);
    Py_DECREF(py_name);
    py_name = 0;
    Py_DECREF(py_module);
    py_module = 0;
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_module);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(const char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(name);
    #else
    py_name = PyUnicode_FromString(name);
    #endif
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr) {
    int result;
    PyObject *pycobj;
    
    pycobj = PyMapping_GetItemString(dict, "__pyx_vtable__");
    if (!pycobj)
        goto bad;
    *(void **)vtabptr = PyCObject_AsVoidPtr(pycobj);
    if (!*(void **)vtabptr)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    char *desc;
    
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%s does not export expected C function %s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    desc = (char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    if (strcmp(desc, sig) != 0) {
        PyErr_Format(PyExc_TypeError,
            "C function %s.%s has wrong signature (expected %s, got %s)",
                PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    *f = PyCObject_AsVoidPtr(cobj);
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

