/* Generated by Cython 0.10.3 on Sun Feb  8 13:37:56 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_LOCK 0x0002
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyBytes_Type
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define PyBytes_Type                 PyString_Type
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__h5py__h5fd
#include "stdlib.h"
#include "string.h"
#include "time.h"
#include "unistd.h"
#include "stdint.h"
#include "compat.h"
#include "lzf_filter.h"
#include "hdf5.h"


#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; long n; char is_unicode; char intern; char is_identifier;} __Pyx_StringTabEntry; /*proto*/



static int __pyx_skip_dispatch = 0;


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString PyString_FromString
#define __Pyx_PyBytes_AsString   PyString_AsString
#else
#define __Pyx_PyBytes_FromString PyBytes_FromString
#define __Pyx_PyBytes_AsString   PyBytes_AsString
#endif

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject* x);
static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x);
static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x);
static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b);

#define __pyx_PyInt_AsLong(x) (PyInt_CheckExact(x) ? PyInt_AS_LONG(x) : PyInt_AsLong(x))
#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))

static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x);
static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x);
static INLINE char __pyx_PyInt_char(PyObject* x);
static INLINE short __pyx_PyInt_short(PyObject* x);
static INLINE int __pyx_PyInt_int(PyObject* x);
static INLINE long __pyx_PyInt_long(PyObject* x);
static INLINE signed char __pyx_PyInt_signed_char(PyObject* x);
static INLINE signed short __pyx_PyInt_signed_short(PyObject* x);
static INLINE signed int __pyx_PyInt_signed_int(PyObject* x);
static INLINE signed long __pyx_PyInt_signed_long(PyObject* x);
static INLINE long double __pyx_PyInt_long_double(PyObject* x);
#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;

static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name, long size);  /*proto*/

static PyObject *__Pyx_ImportModule(const char *name); /*proto*/

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr); /*proto*/

static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/

/* Type declarations */

/* "/home/tachyon/h5py/h5py/h5.pxd":21
 *     cpdef bint __enter__(self) except -1
 *     cpdef bint __exit__(self, a, b, c) except -1
 *     cpdef bint acquire(self, int blocking=*) except -1             # <<<<<<<<<<<<<<
 *     cpdef bint release(self) except -1
 * 
 */

struct __pyx_opt_args_4h5py_2h5_4PHIL_acquire {
  int __pyx_n;
  int blocking;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":26
 * cpdef PHIL get_phil()
 * 
 * cdef class H5PYConfig:             # <<<<<<<<<<<<<<
 * 
 *     cdef object _r_name
 */

struct __pyx_obj_4h5py_2h5_H5PYConfig {
  PyObject_HEAD
  PyObject *_r_name;
  PyObject *_i_name;
  PyObject *_f_name;
  PyObject *_t_name;
  PyObject *API_16;
  PyObject *API_18;
  PyObject *DEBUG;
  PyObject *THREADS;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":15
 * include "defs.pxd"
 * 
 * cdef class PHIL:             # <<<<<<<<<<<<<<
 * 
 *     cdef object lock
 */

struct __pyx_obj_4h5py_2h5_PHIL {
  PyObject_HEAD
  struct __pyx_vtabstruct_4h5py_2h5_PHIL *__pyx_vtab;
  PyObject *lock;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":39
 * cpdef H5PYConfig get_config()
 * 
 * cdef class ObjectID:             # <<<<<<<<<<<<<<
 * 
 *     cdef object __weakref__
 */

struct __pyx_obj_4h5py_2h5_ObjectID {
  PyObject_HEAD
  PyObject *__weakref__;
  hid_t id;
  int _locked;
  PyObject *_hash;
};

/* "/home/tachyon/h5py/h5py/h5.pxd":46
 *     cdef object _hash
 * 
 * cdef class SmartStruct:             # <<<<<<<<<<<<<<
 *     cdef object __weakref__
 *     cdef object _title
 */

struct __pyx_obj_4h5py_2h5_SmartStruct {
  PyObject_HEAD
  PyObject *__weakref__;
  PyObject *_title;
};


/* "/home/tachyon/h5py/h5py/h5.pxd":15
 * include "defs.pxd"
 * 
 * cdef class PHIL:             # <<<<<<<<<<<<<<
 * 
 *     cdef object lock
 */

struct __pyx_vtabstruct_4h5py_2h5_PHIL {
  int (*__enter__)(struct __pyx_obj_4h5py_2h5_PHIL *, int __pyx_skip_dispatch);
  int (*__exit__)(struct __pyx_obj_4h5py_2h5_PHIL *, PyObject *, PyObject *, PyObject *, int __pyx_skip_dispatch);
  int (*acquire)(struct __pyx_obj_4h5py_2h5_PHIL *, int __pyx_skip_dispatch, struct __pyx_opt_args_4h5py_2h5_4PHIL_acquire *__pyx_optional_args);
  int (*release)(struct __pyx_obj_4h5py_2h5_PHIL *, int __pyx_skip_dispatch);
};
static struct __pyx_vtabstruct_4h5py_2h5_PHIL *__pyx_vtabptr_4h5py_2h5_PHIL;
/* Module declarations from h5py.h5 */

static PyTypeObject *__pyx_ptype_4h5py_2h5_PHIL = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_H5PYConfig = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_ObjectID = 0;
static PyTypeObject *__pyx_ptype_4h5py_2h5_SmartStruct = 0;
static struct __pyx_obj_4h5py_2h5_PHIL *(*__pyx_f_4h5py_2h5_get_phil)(int __pyx_skip_dispatch); /*proto*/
static struct __pyx_obj_4h5py_2h5_H5PYConfig *(*__pyx_f_4h5py_2h5_get_config)(int __pyx_skip_dispatch); /*proto*/
static int (*__pyx_f_4h5py_2h5_init_hdf5)(void); /*proto*/
/* Module declarations from h5py.h5fd */



/* Implementation of h5py.h5fd */
static char __pyx_k_MEM_DEFAULT[] = "MEM_DEFAULT";
static PyObject *__pyx_kp_MEM_DEFAULT;
static char __pyx_k_MEM_SUPER[] = "MEM_SUPER";
static PyObject *__pyx_kp_MEM_SUPER;
static char __pyx_k_MEM_BTREE[] = "MEM_BTREE";
static PyObject *__pyx_kp_MEM_BTREE;
static char __pyx_k_MEM_DRAW[] = "MEM_DRAW";
static PyObject *__pyx_kp_MEM_DRAW;
static char __pyx_k_MEM_GHEAP[] = "MEM_GHEAP";
static PyObject *__pyx_kp_MEM_GHEAP;
static char __pyx_k_MEM_LHEAP[] = "MEM_LHEAP";
static PyObject *__pyx_kp_MEM_LHEAP;
static char __pyx_k_MEM_OHDR[] = "MEM_OHDR";
static PyObject *__pyx_kp_MEM_OHDR;
static char __pyx_k_MEM_NTYPES[] = "MEM_NTYPES";
static PyObject *__pyx_kp_MEM_NTYPES;
static char __pyx_k_CORE[] = "CORE";
static PyObject *__pyx_kp_CORE;
static char __pyx_k_FAMILY[] = "FAMILY";
static PyObject *__pyx_kp_FAMILY;
static char __pyx_k_LOG[] = "LOG";
static PyObject *__pyx_kp_LOG;
static char __pyx_k_MPIO[] = "MPIO";
static PyObject *__pyx_kp_MPIO;
static char __pyx_k_MULTI[] = "MULTI";
static PyObject *__pyx_kp_MULTI;
static char __pyx_k_480[] = "SEC2";
static PyObject *__pyx_kp_480;
static char __pyx_k_STDIO[] = "STDIO";
static PyObject *__pyx_kp_STDIO;
static char __pyx_k_LOG_LOC_READ[] = "LOG_LOC_READ";
static PyObject *__pyx_kp_LOG_LOC_READ;
static char __pyx_k_LOG_LOC_WRITE[] = "LOG_LOC_WRITE";
static PyObject *__pyx_kp_LOG_LOC_WRITE;
static char __pyx_k_LOG_LOC_SEEK[] = "LOG_LOC_SEEK";
static PyObject *__pyx_kp_LOG_LOC_SEEK;
static char __pyx_k_LOG_LOC_IO[] = "LOG_LOC_IO";
static PyObject *__pyx_kp_LOG_LOC_IO;
static char __pyx_k_LOG_FILE_READ[] = "LOG_FILE_READ";
static PyObject *__pyx_kp_LOG_FILE_READ;
static char __pyx_k_LOG_FILE_WRITE[] = "LOG_FILE_WRITE";
static PyObject *__pyx_kp_LOG_FILE_WRITE;
static char __pyx_k_LOG_FILE_IO[] = "LOG_FILE_IO";
static PyObject *__pyx_kp_LOG_FILE_IO;
static char __pyx_k_LOG_FLAVOR[] = "LOG_FLAVOR";
static PyObject *__pyx_kp_LOG_FLAVOR;
static char __pyx_k_LOG_NUM_READ[] = "LOG_NUM_READ";
static PyObject *__pyx_kp_LOG_NUM_READ;
static char __pyx_k_LOG_NUM_WRITE[] = "LOG_NUM_WRITE";
static PyObject *__pyx_kp_LOG_NUM_WRITE;
static char __pyx_k_LOG_NUM_SEEK[] = "LOG_NUM_SEEK";
static PyObject *__pyx_kp_LOG_NUM_SEEK;
static char __pyx_k_LOG_NUM_IO[] = "LOG_NUM_IO";
static PyObject *__pyx_kp_LOG_NUM_IO;
static char __pyx_k_LOG_TIME_OPEN[] = "LOG_TIME_OPEN";
static PyObject *__pyx_kp_LOG_TIME_OPEN;
static char __pyx_k_LOG_TIME_READ[] = "LOG_TIME_READ";
static PyObject *__pyx_kp_LOG_TIME_READ;
static char __pyx_k_LOG_TIME_WRITE[] = "LOG_TIME_WRITE";
static PyObject *__pyx_kp_LOG_TIME_WRITE;
static char __pyx_k_LOG_TIME_SEEK[] = "LOG_TIME_SEEK";
static PyObject *__pyx_kp_LOG_TIME_SEEK;
static char __pyx_k_LOG_TIME_CLOSE[] = "LOG_TIME_CLOSE";
static PyObject *__pyx_kp_LOG_TIME_CLOSE;
static char __pyx_k_LOG_TIME_IO[] = "LOG_TIME_IO";
static PyObject *__pyx_kp_LOG_TIME_IO;
static char __pyx_k_LOG_ALLOC[] = "LOG_ALLOC";
static PyObject *__pyx_kp_LOG_ALLOC;
static char __pyx_k_LOG_ALL[] = "LOG_ALL";
static PyObject *__pyx_kp_LOG_ALL;

static struct PyMethodDef __pyx_methods[] = {
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    "h5fd",
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_MEM_DEFAULT, __pyx_k_MEM_DEFAULT, sizeof(__pyx_k_MEM_DEFAULT), 1, 1, 1},
  {&__pyx_kp_MEM_SUPER, __pyx_k_MEM_SUPER, sizeof(__pyx_k_MEM_SUPER), 1, 1, 1},
  {&__pyx_kp_MEM_BTREE, __pyx_k_MEM_BTREE, sizeof(__pyx_k_MEM_BTREE), 1, 1, 1},
  {&__pyx_kp_MEM_DRAW, __pyx_k_MEM_DRAW, sizeof(__pyx_k_MEM_DRAW), 1, 1, 1},
  {&__pyx_kp_MEM_GHEAP, __pyx_k_MEM_GHEAP, sizeof(__pyx_k_MEM_GHEAP), 1, 1, 1},
  {&__pyx_kp_MEM_LHEAP, __pyx_k_MEM_LHEAP, sizeof(__pyx_k_MEM_LHEAP), 1, 1, 1},
  {&__pyx_kp_MEM_OHDR, __pyx_k_MEM_OHDR, sizeof(__pyx_k_MEM_OHDR), 1, 1, 1},
  {&__pyx_kp_MEM_NTYPES, __pyx_k_MEM_NTYPES, sizeof(__pyx_k_MEM_NTYPES), 1, 1, 1},
  {&__pyx_kp_CORE, __pyx_k_CORE, sizeof(__pyx_k_CORE), 1, 1, 1},
  {&__pyx_kp_FAMILY, __pyx_k_FAMILY, sizeof(__pyx_k_FAMILY), 1, 1, 1},
  {&__pyx_kp_LOG, __pyx_k_LOG, sizeof(__pyx_k_LOG), 1, 1, 1},
  {&__pyx_kp_MPIO, __pyx_k_MPIO, sizeof(__pyx_k_MPIO), 1, 1, 1},
  {&__pyx_kp_MULTI, __pyx_k_MULTI, sizeof(__pyx_k_MULTI), 1, 1, 1},
  {&__pyx_kp_480, __pyx_k_480, sizeof(__pyx_k_480), 1, 1, 1},
  {&__pyx_kp_STDIO, __pyx_k_STDIO, sizeof(__pyx_k_STDIO), 1, 1, 1},
  {&__pyx_kp_LOG_LOC_READ, __pyx_k_LOG_LOC_READ, sizeof(__pyx_k_LOG_LOC_READ), 1, 1, 1},
  {&__pyx_kp_LOG_LOC_WRITE, __pyx_k_LOG_LOC_WRITE, sizeof(__pyx_k_LOG_LOC_WRITE), 1, 1, 1},
  {&__pyx_kp_LOG_LOC_SEEK, __pyx_k_LOG_LOC_SEEK, sizeof(__pyx_k_LOG_LOC_SEEK), 1, 1, 1},
  {&__pyx_kp_LOG_LOC_IO, __pyx_k_LOG_LOC_IO, sizeof(__pyx_k_LOG_LOC_IO), 1, 1, 1},
  {&__pyx_kp_LOG_FILE_READ, __pyx_k_LOG_FILE_READ, sizeof(__pyx_k_LOG_FILE_READ), 1, 1, 1},
  {&__pyx_kp_LOG_FILE_WRITE, __pyx_k_LOG_FILE_WRITE, sizeof(__pyx_k_LOG_FILE_WRITE), 1, 1, 1},
  {&__pyx_kp_LOG_FILE_IO, __pyx_k_LOG_FILE_IO, sizeof(__pyx_k_LOG_FILE_IO), 1, 1, 1},
  {&__pyx_kp_LOG_FLAVOR, __pyx_k_LOG_FLAVOR, sizeof(__pyx_k_LOG_FLAVOR), 1, 1, 1},
  {&__pyx_kp_LOG_NUM_READ, __pyx_k_LOG_NUM_READ, sizeof(__pyx_k_LOG_NUM_READ), 1, 1, 1},
  {&__pyx_kp_LOG_NUM_WRITE, __pyx_k_LOG_NUM_WRITE, sizeof(__pyx_k_LOG_NUM_WRITE), 1, 1, 1},
  {&__pyx_kp_LOG_NUM_SEEK, __pyx_k_LOG_NUM_SEEK, sizeof(__pyx_k_LOG_NUM_SEEK), 1, 1, 1},
  {&__pyx_kp_LOG_NUM_IO, __pyx_k_LOG_NUM_IO, sizeof(__pyx_k_LOG_NUM_IO), 1, 1, 1},
  {&__pyx_kp_LOG_TIME_OPEN, __pyx_k_LOG_TIME_OPEN, sizeof(__pyx_k_LOG_TIME_OPEN), 1, 1, 1},
  {&__pyx_kp_LOG_TIME_READ, __pyx_k_LOG_TIME_READ, sizeof(__pyx_k_LOG_TIME_READ), 1, 1, 1},
  {&__pyx_kp_LOG_TIME_WRITE, __pyx_k_LOG_TIME_WRITE, sizeof(__pyx_k_LOG_TIME_WRITE), 1, 1, 1},
  {&__pyx_kp_LOG_TIME_SEEK, __pyx_k_LOG_TIME_SEEK, sizeof(__pyx_k_LOG_TIME_SEEK), 1, 1, 1},
  {&__pyx_kp_LOG_TIME_CLOSE, __pyx_k_LOG_TIME_CLOSE, sizeof(__pyx_k_LOG_TIME_CLOSE), 1, 1, 1},
  {&__pyx_kp_LOG_TIME_IO, __pyx_k_LOG_TIME_IO, sizeof(__pyx_k_LOG_TIME_IO), 1, 1, 1},
  {&__pyx_kp_LOG_ALLOC, __pyx_k_LOG_ALLOC, sizeof(__pyx_k_LOG_ALLOC), 1, 1, 1},
  {&__pyx_kp_LOG_ALL, __pyx_k_LOG_ALL, sizeof(__pyx_k_LOG_ALL), 1, 1, 1},
  {0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  return 0;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC inith5fd(void); /*proto*/
PyMODINIT_FUNC inith5fd(void)
#else
PyMODINIT_FUNC PyInit_h5fd(void); /*proto*/
PyMODINIT_FUNC PyInit_h5fd(void)
#endif
{
  int __pyx_1;
  PyObject *__pyx_2 = 0;
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Library function declarations ---*/
  __pyx_init_filenames();
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4("h5fd", __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_BUILTIN_MODULE_NAME);
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (PyObject_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_skip_dispatch = 0;
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  __pyx_ptype_4h5py_2h5_PHIL = __Pyx_ImportType("h5py.h5", "PHIL", sizeof(struct __pyx_obj_4h5py_2h5_PHIL)); if (unlikely(!__pyx_ptype_4h5py_2h5_PHIL)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_GetVtable(__pyx_ptype_4h5py_2h5_PHIL->tp_dict, &__pyx_vtabptr_4h5py_2h5_PHIL) < 0) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 15; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_H5PYConfig = __Pyx_ImportType("h5py.h5", "H5PYConfig", sizeof(struct __pyx_obj_4h5py_2h5_H5PYConfig)); if (unlikely(!__pyx_ptype_4h5py_2h5_H5PYConfig)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_ObjectID = __Pyx_ImportType("h5py.h5", "ObjectID", sizeof(struct __pyx_obj_4h5py_2h5_ObjectID)); if (unlikely(!__pyx_ptype_4h5py_2h5_ObjectID)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_ptype_4h5py_2h5_SmartStruct = __Pyx_ImportType("h5py.h5", "SmartStruct", sizeof(struct __pyx_obj_4h5py_2h5_SmartStruct)); if (unlikely(!__pyx_ptype_4h5py_2h5_SmartStruct)) {__pyx_filename = __pyx_f[1]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Function import code ---*/
  __pyx_2 = __Pyx_ImportModule("h5py.h5"); if (!__pyx_2) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_2, "get_phil", (void**)&__pyx_f_4h5py_2h5_get_phil, "struct __pyx_obj_4h5py_2h5_PHIL *(int __pyx_skip_dispatch)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_2, "get_config", (void**)&__pyx_f_4h5py_2h5_get_config, "struct __pyx_obj_4h5py_2h5_H5PYConfig *(int __pyx_skip_dispatch)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__Pyx_ImportFunction(__pyx_2, "init_hdf5", (void**)&__pyx_f_4h5py_2h5_init_hdf5, "int (void)") < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;
  /*--- Execution code ---*/

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":19
 * 
 * from h5 cimport init_hdf5
 * init_hdf5()             # <<<<<<<<<<<<<<
 * 
 * # === Multi-file driver =======================================================
 */
  __pyx_1 = __pyx_f_4h5py_2h5_init_hdf5(); if (unlikely(__pyx_1 == -1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 19; __pyx_clineno = __LINE__; goto __pyx_L1_error;}

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":23
 * # === Multi-file driver =======================================================
 * 
 * MEM_DEFAULT = H5FD_MEM_DEFAULT             # <<<<<<<<<<<<<<
 * MEM_SUPER = H5FD_MEM_SUPER
 * MEM_BTREE = H5FD_MEM_BTREE
 */
  __pyx_2 = PyInt_FromLong(H5FD_MEM_DEFAULT); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MEM_DEFAULT, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 23; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":24
 * 
 * MEM_DEFAULT = H5FD_MEM_DEFAULT
 * MEM_SUPER = H5FD_MEM_SUPER             # <<<<<<<<<<<<<<
 * MEM_BTREE = H5FD_MEM_BTREE
 * MEM_DRAW = H5FD_MEM_DRAW
 */
  __pyx_2 = PyInt_FromLong(H5FD_MEM_SUPER); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MEM_SUPER, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 24; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":25
 * MEM_DEFAULT = H5FD_MEM_DEFAULT
 * MEM_SUPER = H5FD_MEM_SUPER
 * MEM_BTREE = H5FD_MEM_BTREE             # <<<<<<<<<<<<<<
 * MEM_DRAW = H5FD_MEM_DRAW
 * MEM_GHEAP = H5FD_MEM_GHEAP
 */
  __pyx_2 = PyInt_FromLong(H5FD_MEM_BTREE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MEM_BTREE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 25; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":26
 * MEM_SUPER = H5FD_MEM_SUPER
 * MEM_BTREE = H5FD_MEM_BTREE
 * MEM_DRAW = H5FD_MEM_DRAW             # <<<<<<<<<<<<<<
 * MEM_GHEAP = H5FD_MEM_GHEAP
 * MEM_LHEAP = H5FD_MEM_LHEAP
 */
  __pyx_2 = PyInt_FromLong(H5FD_MEM_DRAW); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MEM_DRAW, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 26; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":27
 * MEM_BTREE = H5FD_MEM_BTREE
 * MEM_DRAW = H5FD_MEM_DRAW
 * MEM_GHEAP = H5FD_MEM_GHEAP             # <<<<<<<<<<<<<<
 * MEM_LHEAP = H5FD_MEM_LHEAP
 * MEM_OHDR = H5FD_MEM_OHDR
 */
  __pyx_2 = PyInt_FromLong(H5FD_MEM_GHEAP); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MEM_GHEAP, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 27; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":28
 * MEM_DRAW = H5FD_MEM_DRAW
 * MEM_GHEAP = H5FD_MEM_GHEAP
 * MEM_LHEAP = H5FD_MEM_LHEAP             # <<<<<<<<<<<<<<
 * MEM_OHDR = H5FD_MEM_OHDR
 * MEM_NTYPES = H5FD_MEM_NTYPES
 */
  __pyx_2 = PyInt_FromLong(H5FD_MEM_LHEAP); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MEM_LHEAP, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":29
 * MEM_GHEAP = H5FD_MEM_GHEAP
 * MEM_LHEAP = H5FD_MEM_LHEAP
 * MEM_OHDR = H5FD_MEM_OHDR             # <<<<<<<<<<<<<<
 * MEM_NTYPES = H5FD_MEM_NTYPES
 * 
 */
  __pyx_2 = PyInt_FromLong(H5FD_MEM_OHDR); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MEM_OHDR, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":30
 * MEM_LHEAP = H5FD_MEM_LHEAP
 * MEM_OHDR = H5FD_MEM_OHDR
 * MEM_NTYPES = H5FD_MEM_NTYPES             # <<<<<<<<<<<<<<
 * 
 * # === Driver types ============================================================
 */
  __pyx_2 = PyInt_FromLong(H5FD_MEM_NTYPES); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MEM_NTYPES, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":34
 * # === Driver types ============================================================
 * 
 * CORE = H5FD_CORE             # <<<<<<<<<<<<<<
 * FAMILY = H5FD_FAMILY
 * LOG = H5FD_LOG
 */
  __pyx_2 = PyInt_FromLong(H5FD_CORE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_CORE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":35
 * 
 * CORE = H5FD_CORE
 * FAMILY = H5FD_FAMILY             # <<<<<<<<<<<<<<
 * LOG = H5FD_LOG
 * MPIO = H5FD_MPIO
 */
  __pyx_2 = PyInt_FromLong(H5FD_FAMILY); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_FAMILY, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":36
 * CORE = H5FD_CORE
 * FAMILY = H5FD_FAMILY
 * LOG = H5FD_LOG             # <<<<<<<<<<<<<<
 * MPIO = H5FD_MPIO
 * MULTI = H5FD_MULTI
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":37
 * FAMILY = H5FD_FAMILY
 * LOG = H5FD_LOG
 * MPIO = H5FD_MPIO             # <<<<<<<<<<<<<<
 * MULTI = H5FD_MULTI
 * SEC2 = H5FD_SEC2
 */
  __pyx_2 = PyInt_FromLong(H5FD_MPIO); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MPIO, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":38
 * LOG = H5FD_LOG
 * MPIO = H5FD_MPIO
 * MULTI = H5FD_MULTI             # <<<<<<<<<<<<<<
 * SEC2 = H5FD_SEC2
 * STDIO = H5FD_STDIO
 */
  __pyx_2 = PyInt_FromLong(H5FD_MULTI); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_MULTI, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":39
 * MPIO = H5FD_MPIO
 * MULTI = H5FD_MULTI
 * SEC2 = H5FD_SEC2             # <<<<<<<<<<<<<<
 * STDIO = H5FD_STDIO
 * 
 */
  __pyx_2 = PyInt_FromLong(H5FD_SEC2); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_480, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 39; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":40
 * MULTI = H5FD_MULTI
 * SEC2 = H5FD_SEC2
 * STDIO = H5FD_STDIO             # <<<<<<<<<<<<<<
 * 
 * # === Logging driver ==========================================================
 */
  __pyx_2 = PyInt_FromLong(H5FD_STDIO); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_STDIO, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 40; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":44
 * # === Logging driver ==========================================================
 * 
 * LOG_LOC_READ  = H5FD_LOG_LOC_READ   # 0x0001             # <<<<<<<<<<<<<<
 * LOG_LOC_WRITE = H5FD_LOG_LOC_WRITE  # 0x0002
 * LOG_LOC_SEEK  = H5FD_LOG_LOC_SEEK   # 0x0004
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_LOC_READ); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_LOC_READ, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 44; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":45
 * 
 * LOG_LOC_READ  = H5FD_LOG_LOC_READ   # 0x0001
 * LOG_LOC_WRITE = H5FD_LOG_LOC_WRITE  # 0x0002             # <<<<<<<<<<<<<<
 * LOG_LOC_SEEK  = H5FD_LOG_LOC_SEEK   # 0x0004
 * LOG_LOC_IO    = H5FD_LOG_LOC_IO     # (H5FD_LOG_LOC_READ|H5FD_LOG_LOC_WRITE|H5FD_LOG_LOC_SEEK)
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_LOC_WRITE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_LOC_WRITE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 45; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":46
 * LOG_LOC_READ  = H5FD_LOG_LOC_READ   # 0x0001
 * LOG_LOC_WRITE = H5FD_LOG_LOC_WRITE  # 0x0002
 * LOG_LOC_SEEK  = H5FD_LOG_LOC_SEEK   # 0x0004             # <<<<<<<<<<<<<<
 * LOG_LOC_IO    = H5FD_LOG_LOC_IO     # (H5FD_LOG_LOC_READ|H5FD_LOG_LOC_WRITE|H5FD_LOG_LOC_SEEK)
 * 
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_LOC_SEEK); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_LOC_SEEK, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 46; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":47
 * LOG_LOC_WRITE = H5FD_LOG_LOC_WRITE  # 0x0002
 * LOG_LOC_SEEK  = H5FD_LOG_LOC_SEEK   # 0x0004
 * LOG_LOC_IO    = H5FD_LOG_LOC_IO     # (H5FD_LOG_LOC_READ|H5FD_LOG_LOC_WRITE|H5FD_LOG_LOC_SEEK)             # <<<<<<<<<<<<<<
 * 
 * # Flags for tracking number of times each byte is read/written
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_LOC_IO); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_LOC_IO, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 47; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":50
 * 
 * # Flags for tracking number of times each byte is read/written
 * LOG_FILE_READ = H5FD_LOG_FILE_READ  # 0x0008             # <<<<<<<<<<<<<<
 * LOG_FILE_WRITE= H5FD_LOG_FILE_WRITE # 0x0010
 * LOG_FILE_IO   = H5FD_LOG_FILE_IO    # (H5FD_LOG_FILE_READ|H5FD_LOG_FILE_WRITE)
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_FILE_READ); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_FILE_READ, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 50; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":51
 * # Flags for tracking number of times each byte is read/written
 * LOG_FILE_READ = H5FD_LOG_FILE_READ  # 0x0008
 * LOG_FILE_WRITE= H5FD_LOG_FILE_WRITE # 0x0010             # <<<<<<<<<<<<<<
 * LOG_FILE_IO   = H5FD_LOG_FILE_IO    # (H5FD_LOG_FILE_READ|H5FD_LOG_FILE_WRITE)
 * 
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_FILE_WRITE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_FILE_WRITE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 51; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":52
 * LOG_FILE_READ = H5FD_LOG_FILE_READ  # 0x0008
 * LOG_FILE_WRITE= H5FD_LOG_FILE_WRITE # 0x0010
 * LOG_FILE_IO   = H5FD_LOG_FILE_IO    # (H5FD_LOG_FILE_READ|H5FD_LOG_FILE_WRITE)             # <<<<<<<<<<<<<<
 * 
 * # Flag for tracking "flavor" (type) of information stored at each byte
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_FILE_IO); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_FILE_IO, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 52; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":55
 * 
 * # Flag for tracking "flavor" (type) of information stored at each byte
 * LOG_FLAVOR    = H5FD_LOG_FLAVOR     # 0x0020             # <<<<<<<<<<<<<<
 * 
 * # Flags for tracking total number of reads/writes/seeks
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_FLAVOR); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_FLAVOR, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 55; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":58
 * 
 * # Flags for tracking total number of reads/writes/seeks
 * LOG_NUM_READ  = H5FD_LOG_NUM_READ   # 0x0040             # <<<<<<<<<<<<<<
 * LOG_NUM_WRITE = H5FD_LOG_NUM_WRITE  # 0x0080
 * LOG_NUM_SEEK  = H5FD_LOG_NUM_SEEK   # 0x0100
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_NUM_READ); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_NUM_READ, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":59
 * # Flags for tracking total number of reads/writes/seeks
 * LOG_NUM_READ  = H5FD_LOG_NUM_READ   # 0x0040
 * LOG_NUM_WRITE = H5FD_LOG_NUM_WRITE  # 0x0080             # <<<<<<<<<<<<<<
 * LOG_NUM_SEEK  = H5FD_LOG_NUM_SEEK   # 0x0100
 * LOG_NUM_IO    = H5FD_LOG_NUM_IO     # (H5FD_LOG_NUM_READ|H5FD_LOG_NUM_WRITE|H5FD_LOG_NUM_SEEK)
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_NUM_WRITE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_NUM_WRITE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":60
 * LOG_NUM_READ  = H5FD_LOG_NUM_READ   # 0x0040
 * LOG_NUM_WRITE = H5FD_LOG_NUM_WRITE  # 0x0080
 * LOG_NUM_SEEK  = H5FD_LOG_NUM_SEEK   # 0x0100             # <<<<<<<<<<<<<<
 * LOG_NUM_IO    = H5FD_LOG_NUM_IO     # (H5FD_LOG_NUM_READ|H5FD_LOG_NUM_WRITE|H5FD_LOG_NUM_SEEK)
 * 
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_NUM_SEEK); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_NUM_SEEK, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 60; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":61
 * LOG_NUM_WRITE = H5FD_LOG_NUM_WRITE  # 0x0080
 * LOG_NUM_SEEK  = H5FD_LOG_NUM_SEEK   # 0x0100
 * LOG_NUM_IO    = H5FD_LOG_NUM_IO     # (H5FD_LOG_NUM_READ|H5FD_LOG_NUM_WRITE|H5FD_LOG_NUM_SEEK)             # <<<<<<<<<<<<<<
 * 
 * # Flags for tracking time spent in open/read/write/seek/close
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_NUM_IO); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_NUM_IO, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":64
 * 
 * # Flags for tracking time spent in open/read/write/seek/close
 * LOG_TIME_OPEN = H5FD_LOG_TIME_OPEN  # 0x0200        # Not implemented yet             # <<<<<<<<<<<<<<
 * LOG_TIME_READ = H5FD_LOG_TIME_READ  # 0x0400        # Not implemented yet
 * LOG_TIME_WRITE= H5FD_LOG_TIME_WRITE # 0x0800        # Partially implemented (need to track total time)
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_TIME_OPEN); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_TIME_OPEN, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":65
 * # Flags for tracking time spent in open/read/write/seek/close
 * LOG_TIME_OPEN = H5FD_LOG_TIME_OPEN  # 0x0200        # Not implemented yet
 * LOG_TIME_READ = H5FD_LOG_TIME_READ  # 0x0400        # Not implemented yet             # <<<<<<<<<<<<<<
 * LOG_TIME_WRITE= H5FD_LOG_TIME_WRITE # 0x0800        # Partially implemented (need to track total time)
 * LOG_TIME_SEEK = H5FD_LOG_TIME_SEEK  # 0x1000        # Partially implemented (need to track total time & track time for seeks during reading)
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_TIME_READ); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_TIME_READ, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 65; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":66
 * LOG_TIME_OPEN = H5FD_LOG_TIME_OPEN  # 0x0200        # Not implemented yet
 * LOG_TIME_READ = H5FD_LOG_TIME_READ  # 0x0400        # Not implemented yet
 * LOG_TIME_WRITE= H5FD_LOG_TIME_WRITE # 0x0800        # Partially implemented (need to track total time)             # <<<<<<<<<<<<<<
 * LOG_TIME_SEEK = H5FD_LOG_TIME_SEEK  # 0x1000        # Partially implemented (need to track total time & track time for seeks during reading)
 * LOG_TIME_CLOSE= H5FD_LOG_TIME_CLOSE # 0x2000        # Fully implemented
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_TIME_WRITE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_TIME_WRITE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 66; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":67
 * LOG_TIME_READ = H5FD_LOG_TIME_READ  # 0x0400        # Not implemented yet
 * LOG_TIME_WRITE= H5FD_LOG_TIME_WRITE # 0x0800        # Partially implemented (need to track total time)
 * LOG_TIME_SEEK = H5FD_LOG_TIME_SEEK  # 0x1000        # Partially implemented (need to track total time & track time for seeks during reading)             # <<<<<<<<<<<<<<
 * LOG_TIME_CLOSE= H5FD_LOG_TIME_CLOSE # 0x2000        # Fully implemented
 * LOG_TIME_IO   = H5FD_LOG_TIME_IO    # (H5FD_LOG_TIME_OPEN|H5FD_LOG_TIME_READ|H5FD_LOG_TIME_WRITE|H5FD_LOG_TIME_SEEK|H5FD_LOG_TIME_CLOSE)
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_TIME_SEEK); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_TIME_SEEK, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 67; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":68
 * LOG_TIME_WRITE= H5FD_LOG_TIME_WRITE # 0x0800        # Partially implemented (need to track total time)
 * LOG_TIME_SEEK = H5FD_LOG_TIME_SEEK  # 0x1000        # Partially implemented (need to track total time & track time for seeks during reading)
 * LOG_TIME_CLOSE= H5FD_LOG_TIME_CLOSE # 0x2000        # Fully implemented             # <<<<<<<<<<<<<<
 * LOG_TIME_IO   = H5FD_LOG_TIME_IO    # (H5FD_LOG_TIME_OPEN|H5FD_LOG_TIME_READ|H5FD_LOG_TIME_WRITE|H5FD_LOG_TIME_SEEK|H5FD_LOG_TIME_CLOSE)
 * 
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_TIME_CLOSE); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_TIME_CLOSE, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 68; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":69
 * LOG_TIME_SEEK = H5FD_LOG_TIME_SEEK  # 0x1000        # Partially implemented (need to track total time & track time for seeks during reading)
 * LOG_TIME_CLOSE= H5FD_LOG_TIME_CLOSE # 0x2000        # Fully implemented
 * LOG_TIME_IO   = H5FD_LOG_TIME_IO    # (H5FD_LOG_TIME_OPEN|H5FD_LOG_TIME_READ|H5FD_LOG_TIME_WRITE|H5FD_LOG_TIME_SEEK|H5FD_LOG_TIME_CLOSE)             # <<<<<<<<<<<<<<
 * 
 * # Flag for tracking allocation of space in file
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_TIME_IO); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_TIME_IO, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 69; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":72
 * 
 * # Flag for tracking allocation of space in file
 * LOG_ALLOC     = H5FD_LOG_ALLOC      # 0x4000             # <<<<<<<<<<<<<<
 * LOG_ALL       = H5FD_LOG_ALL        # (H5FD_LOG_ALLOC|H5FD_LOG_TIME_IO|H5FD_LOG_NUM_IO|H5FD_LOG_FLAVOR|H5FD_LOG_FILE_IO|H5FD_LOG_LOC_IO)
 * 
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_ALLOC); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_ALLOC, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 72; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5fd.pyx":73
 * # Flag for tracking allocation of space in file
 * LOG_ALLOC     = H5FD_LOG_ALLOC      # 0x4000
 * LOG_ALL       = H5FD_LOG_ALL        # (H5FD_LOG_ALLOC|H5FD_LOG_TIME_IO|H5FD_LOG_NUM_IO|H5FD_LOG_FLAVOR|H5FD_LOG_FILE_IO|H5FD_LOG_LOC_IO)             # <<<<<<<<<<<<<<
 * 
 */
  __pyx_2 = PyInt_FromLong(H5FD_LOG_ALL); if (unlikely(!__pyx_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (PyObject_SetAttr(__pyx_m, __pyx_kp_LOG_ALL, __pyx_2) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 73; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  Py_DECREF(__pyx_2); __pyx_2 = 0;

  /* "/home/tachyon/h5py/h5py/h5.pxd":1
 * #+             # <<<<<<<<<<<<<<
 * #
 * # This file is part of h5py, a low-level Python interface to the HDF5 library.
 */
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
  __pyx_L1_error:;
  Py_XDECREF(__pyx_2);
  __Pyx_AddTraceback("h5py.h5fd");
  #if PY_MAJOR_VERSION >= 3
  return NULL;
  #endif
}

static const char *__pyx_filenames[] = {
  "h5fd.pyx",
  "h5.pxd",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

#ifndef __PYX_HAVE_RT_ImportType
#define __PYX_HAVE_RT_ImportType
static PyTypeObject *__Pyx_ImportType(const char *module_name, const char *class_name,
    long size)
{
    PyObject *py_module = 0;
    PyObject *result = 0;
    PyObject *py_name = 0;

    py_module = __Pyx_ImportModule(module_name);
    if (!py_module)
        goto bad;
    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(class_name);
    #else
    py_name = PyUnicode_FromString(class_name);
    #endif
    if (!py_name)
        goto bad;
    result = PyObject_GetAttr(py_module, py_name);
    Py_DECREF(py_name);
    py_name = 0;
    Py_DECREF(py_module);
    py_module = 0;
    if (!result)
        goto bad;
    if (!PyType_Check(result)) {
        PyErr_Format(PyExc_TypeError, 
            "%s.%s is not a type object",
            module_name, class_name);
        goto bad;
    }
    if (((PyTypeObject *)result)->tp_basicsize != size) {
        PyErr_Format(PyExc_ValueError, 
            "%s.%s does not appear to be the correct type object",
            module_name, class_name);
        goto bad;
    }
    return (PyTypeObject *)result;
bad:
    Py_XDECREF(py_module);
    Py_XDECREF(result);
    return 0;
}
#endif

#ifndef __PYX_HAVE_RT_ImportModule
#define __PYX_HAVE_RT_ImportModule
static PyObject *__Pyx_ImportModule(const char *name) {
    PyObject *py_name = 0;
    PyObject *py_module = 0;

    #if PY_MAJOR_VERSION < 3
    py_name = PyString_FromString(name);
    #else
    py_name = PyUnicode_FromString(name);
    #endif
    if (!py_name)
        goto bad;
    py_module = PyImport_Import(py_name);
    Py_DECREF(py_name);
    return py_module;
bad:
    Py_XDECREF(py_name);
    return 0;
}
#endif

static int __Pyx_GetVtable(PyObject *dict, void *vtabptr) {
    int result;
    PyObject *pycobj;
    
    pycobj = PyMapping_GetItemString(dict, "__pyx_vtable__");
    if (!pycobj)
        goto bad;
    *(void **)vtabptr = PyCObject_AsVoidPtr(pycobj);
    if (!*(void **)vtabptr)
        goto bad;
    result = 0;
    goto done;

bad:
    result = -1;
done:
    Py_XDECREF(pycobj);
    return result;
}

#ifndef __PYX_HAVE_RT_ImportFunction
#define __PYX_HAVE_RT_ImportFunction
static int __Pyx_ImportFunction(PyObject *module, char *funcname, void **f, char *sig) {
    PyObject *d = 0;
    PyObject *cobj = 0;
    char *desc;
    
    d = PyObject_GetAttrString(module, "__pyx_capi__");
    if (!d)
        goto bad;
    cobj = PyDict_GetItemString(d, funcname);
    if (!cobj) {
        PyErr_Format(PyExc_ImportError,
            "%s does not export expected C function %s",
                PyModule_GetName(module), funcname);
        goto bad;
    }
    desc = (char *)PyCObject_GetDesc(cobj);
    if (!desc)
        goto bad;
    if (strcmp(desc, sig) != 0) {
        PyErr_Format(PyExc_TypeError,
            "C function %s.%s has wrong signature (expected %s, got %s)",
                PyModule_GetName(module), funcname, sig, desc);
        goto bad;
    }
    *f = PyCObject_AsVoidPtr(cobj);
    Py_DECREF(d);
    return 0;
bad:
    Py_XDECREF(d);
    return -1;
}
#endif

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyObject *empty_string = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    #if PY_MAJOR_VERSION < 3
    empty_string = PyString_FromStringAndSize("", 0);
    #else
    empty_string = PyBytes_FromStringAndSize("", 0);
    #endif
    if (!empty_string) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        empty_string, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        empty_string  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(empty_string);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode && (!t->is_identifier)) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_identifier || (t->is_unicode && t->intern)) {
            *t->p = PyUnicode_InternFromString(t->s);
        } else if (t->is_unicode) {
            *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE Py_ssize_t __pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if (x == Py_False) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PY_LONG_LONG __pyx_PyInt_AsLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        return PyInt_AS_LONG(x);
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    if (PyInt_CheckExact(x)) {
        long val = PyInt_AS_LONG(x);
        if (unlikely(val < 0)) {
            PyErr_SetString(PyExc_TypeError, "Negative assignment to unsigned type.");
            return (unsigned PY_LONG_LONG)-1;
        }
        return val;
    }
    else if (PyLong_CheckExact(x)) {
        return PyLong_AsUnsignedLongLong(x);
    }
    else {
        PY_LONG_LONG val;
        PyObject* tmp = PyNumber_Int(x); if (!tmp) return (PY_LONG_LONG)-1;
        val = __pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}


static INLINE unsigned char __pyx_PyInt_unsigned_char(PyObject* x) {
    if (sizeof(unsigned char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned char val = (unsigned char)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned char");
            return (unsigned char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE unsigned short __pyx_PyInt_unsigned_short(PyObject* x) {
    if (sizeof(unsigned short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        unsigned short val = (unsigned short)long_val;
        if (unlikely((val != long_val)  || (long_val < 0))) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to unsigned short");
            return (unsigned short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE char __pyx_PyInt_char(PyObject* x) {
    if (sizeof(char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        char val = (char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to char");
            return (char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE short __pyx_PyInt_short(PyObject* x) {
    if (sizeof(short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        short val = (short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to short");
            return (short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE int __pyx_PyInt_int(PyObject* x) {
    if (sizeof(int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        int val = (int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to int");
            return (int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long __pyx_PyInt_long(PyObject* x) {
    if (sizeof(long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long val = (long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long");
            return (long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed char __pyx_PyInt_signed_char(PyObject* x) {
    if (sizeof(signed char) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed char val = (signed char)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed char");
            return (signed char)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed short __pyx_PyInt_signed_short(PyObject* x) {
    if (sizeof(signed short) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed short val = (signed short)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed short");
            return (signed short)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed int __pyx_PyInt_signed_int(PyObject* x) {
    if (sizeof(signed int) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed int val = (signed int)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed int");
            return (signed int)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE signed long __pyx_PyInt_signed_long(PyObject* x) {
    if (sizeof(signed long) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        signed long val = (signed long)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to signed long");
            return (signed long)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

static INLINE long double __pyx_PyInt_long_double(PyObject* x) {
    if (sizeof(long double) < sizeof(long)) {
        long long_val = __pyx_PyInt_AsLong(x);
        long double val = (long double)long_val;
        if (unlikely((val != long_val) )) {
            PyErr_SetString(PyExc_OverflowError, "value too large to convert to long double");
            return (long double)-1;
        }
        return val;
    }
    else {
        return __pyx_PyInt_AsLong(x);
    }
}

