Memosa-FVM: PhononConvectionDiscretization< X, Diag, OffDiag > Class Template Reference
PhononConvectionDiscretization< X, Diag, OffDiag > Class Template Reference
#include <PhononConvectionDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Gradient< X > XGrad
typedef Array< int > IntArray
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Array< XGrad > GradArray
Public Member Functions
PhononConvectionDiscretization (const MeshList &meshes, const GeomFields &geomFields, Field &varField, const VectorT3 groupvel, const bool useCentralDifference=false)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const VectorT3 _groupvel
const bool _useCentralDifference
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class PhononConvectionDiscretization< X, Diag, OffDiag >
Definition at line 18 of file PhononConvectionDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler PhononConvectionDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 25 of file PhononConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> PhononConvectionDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 23 of file PhononConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray PhononConvectionDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 24 of file PhononConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<XGrad> PhononConvectionDiscretization< X, Diag, OffDiag >::GradArray
Definition at line 35 of file PhononConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<int> PhononConvectionDiscretization< X, Diag, OffDiag >::IntArray
Definition at line 29 of file PhononConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar PhononConvectionDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 21 of file PhononConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> PhononConvectionDiscretization< X, Diag, OffDiag >::TArray
Definition at line 31 of file PhononConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> PhononConvectionDiscretization< X, Diag, OffDiag >::VectorT3
Definition at line 32 of file PhononConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> PhononConvectionDiscretization< X, Diag, OffDiag >::VectorT3Array
Definition at line 33 of file PhononConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> PhononConvectionDiscretization< X, Diag, OffDiag >::XArray
Definition at line 30 of file PhononConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Gradient<X> PhononConvectionDiscretization< X, Diag, OffDiag >::XGrad
Definition at line 27 of file PhononConvectionDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > PhononConvectionDiscretization< X, Diag, OffDiag >::PhononConvectionDiscretization (const MeshList & meshes, const GeomFields & geomFields, Field & varField, const VectorT3 groupvel, const bool useCentralDifference = false) inline
Definition at line 37 of file PhononConvectionDiscretization.h.
                                                                        :
   Discretization(meshes),
     _geomFields(geomFields),
     _varField(varField),
     _groupvel(groupvel),
     _useCentralDifference(useCentralDifference)
     {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void PhononConvectionDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 50 of file PhononConvectionDiscretization.h.
References PhononConvectionDiscretization< X, Diag, OffDiag >::_geomFields, PhononConvectionDiscretization< X, Diag, OffDiag >::_groupvel, PhononConvectionDiscretization< X, Diag, OffDiag >::_useCentralDifference, PhononConvectionDiscretization< X, Diag, OffDiag >::_varField, GeomFields::area, Mesh::getAllFaceCells(), Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), Mesh::getFaces(), MultiFieldMatrix::getMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), GeomFields::gridFlux, Field::hasArray(), GeomFields::ibType, Mesh::IBTYPE_BOUNDARY, and Mesh::IBTYPE_FLUID.
   {
     const StorageSite& cells = mesh.getCells();
     const StorageSite& faces = mesh.getFaces();
     // should there be some other checks ?
     //if (!_convectingFluxField.hasArray(faces))
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix =
       dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     const CRConnectivity& faceCells = mesh.getAllFaceCells();
     CCAssembler& assembler = matrix.getPairWiseAssembler(faceCells);
     DiagArray& diag = matrix.getDiag();
     const XArray& xCell = dynamic_cast<const XArray&>(xField[cVarIndex]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     //const GradArray& xGradCell = dynamic_cast<GradArray>(_varGradientField[cells]);
     const IntArray& ibType = dynamic_cast<const IntArray&>(_geomFields.ibType[cells]);
     const int nFaces = faces.getCount();
     const VectorT3Array& faceArea = dynamic_cast<const VectorT3Array&>(_geomFields.area[faces]);
     if (_geomFields.gridFlux.hasArray(faces))
     {
         shared_ptr<TArray> gridFluxPtr(new TArray(nFaces));
         TArray& gridFlux = *gridFluxPtr;
         gridFlux = dynamic_cast<const TArray&>(_geomFields.gridFlux[faces]);
         for(int f=0; f<nFaces; f++)
         {
             const int c0 = faceCells(f,0);
             const int c1 = faceCells(f,1);
             //const T_Scalar faceCFlux = convectingFlux[f] - gridFlux[f];
             const T_Scalar faceCFlux = faceArea[f][0]*_groupvel[0]
               +faceArea[f][1]*_groupvel[1]+faceArea[f][2]*_groupvel[2] - gridFlux[f];
             X varFlux;
             if (faceCFlux > T_Scalar(0))
             {
                 varFlux = faceCFlux*xCell[c0];
                 diag[c0] -= faceCFlux;
                 assembler.getCoeff10(f) += faceCFlux;
             }
             else
             {
                 varFlux = faceCFlux*xCell[c1];
                 diag[c1] += faceCFlux;
                 assembler.getCoeff01(f)-= faceCFlux;
             }
             rCell[c0] -= varFlux;
             rCell[c1] += varFlux;
         }
     }
     else
     {
       if (_useCentralDifference){
         for(int f=0; f<nFaces; f++)
           {
               const int c0 = faceCells(f,0);
               const int c1 = faceCells(f,1);
               const T_Scalar faceCFlux = faceArea[f][0]*_groupvel[0]
                 +faceArea[f][1]*_groupvel[1]+faceArea[f][2]*_groupvel[2];
               bool isIBFace = (((ibType[c0] == Mesh::IBTYPE_FLUID)
                                 && (ibType[c1] == Mesh::IBTYPE_BOUNDARY)) ||
                                ((ibType[c1] == Mesh::IBTYPE_FLUID)
                                 && (ibType[c0] == Mesh::IBTYPE_BOUNDARY)));
               X varFlux =0.5*faceCFlux*(xCell[c0] + xCell[c0]);
               rCell[c0] -= varFlux;
               rCell[c1] += varFlux;
               if (isIBFace)
               {
                   // linearize the actual flux as calculated
                   // above. this will ensure that the Ib
                   // discretization will be able to fix the value
                   // correctly using the ib face value
                   diag[c0] -= 0.5*faceCFlux;
                   assembler.getCoeff10(f) -= 0.5*faceCFlux;
                   diag[c1] += 0.5*faceCFlux;
                   assembler.getCoeff01(f) += 0.5*faceCFlux;
               }
               else
               {
                   // linearize as upwind flux so that linear system
                   // remains diagonally dominant
                   if (faceCFlux > T_Scalar(0))
                   {
                       diag[c0] -= faceCFlux;
                       assembler.getCoeff10(f) += faceCFlux;
                   }
                   else
                   {
                       diag[c1] += faceCFlux;
                       assembler.getCoeff01(f)-= faceCFlux;
                   }
               }
           }
        }
        else
           for(int f=0; f<nFaces; f++)
           {
               const int c0 = faceCells(f,0);
               const int c1 = faceCells(f,1);
               const T_Scalar faceCFlux = faceArea[f][0]*_groupvel[0]
                 +faceArea[f][1]*_groupvel[1]+faceArea[f][2]*_groupvel[2];
               X varFlux;
               if (faceCFlux > T_Scalar(0))
               {
                   varFlux = faceCFlux*xCell[c0];
                   diag[c0] -= faceCFlux;
                   assembler.getCoeff10(f) += faceCFlux;
               }
               else
               {
                   varFlux = faceCFlux*xCell[c1];
                   diag[c1] += faceCFlux;
                   assembler.getCoeff01(f)-= faceCFlux;
               }
               rCell[c0] -= varFlux;
               rCell[c1] += varFlux;
           }
     }
     //const int nCells = cells.getSelfCount();
     //for(int c=0;c<nCells;c++)
     //{
     //    const T_Scalar cImb = continuityResidual[c];
     //    diag[c] += cImb;
     //}
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const GeomFields& PhononConvectionDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 202 of file PhononConvectionDiscretization.h.
Referenced by PhononConvectionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const VectorT3 PhononConvectionDiscretization< X, Diag, OffDiag >::_groupvel private
Definition at line 204 of file PhononConvectionDiscretization.h.
Referenced by PhononConvectionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const bool PhononConvectionDiscretization< X, Diag, OffDiag >::_useCentralDifference private
Definition at line 205 of file PhononConvectionDiscretization.h.
Referenced by PhononConvectionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& PhononConvectionDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 203 of file PhononConvectionDiscretization.h.
Referenced by PhononConvectionDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
PhononConvectionDiscretization.h