Memosa-FVM: Gradient< T > Class Template Reference
Gradient< T > Class Template Reference
#include <Gradient.h>
Public Types
typedef Gradient< T > This_T
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef NumTypeTraits< T >
::T_BuiltIn T_BuiltIn
typedef Vector< T_Scalar, 3 > Coord
Public Member Functions
T & operator[] (int n)
const T & operator[] (int n) const
Gradient & operator= (const T_Scalar &o)
Gradient & operator= (const Gradient &o)
void accumulate (const Coord &wt, const T &v)
Gradient & operator+= (const Gradient &o)
Gradient & operator-= (const Gradient &o)
Gradient operator- () const
Gradient & operator*= (const T_Scalar &s)
Gradient & operator*= (const Gradient &o)
T operator*= (const Coord &v)
Gradient & operator/= (const T_Scalar &s)
Gradient & operator/= (const Gradient &o)
void zero ()
void print (ostream &os) const
T mag2 () const
bool operator< (const double tolerance) const
Static Public Member Functions
static string getTypeName ()
static int getDimension ()
static void getShape (int *shp)
static int getDataSize ()
static void accumulateOneNorm (Gradient &sum, const Gradient &v)
static void accumulateDotProduct (Gradient &sum, const Gradient &v0, const Gradient &v1)
static void reduceSum (T_Scalar &sum, const This_T &x)
static void safeDivide (Gradient &x, const Gradient &y)
static void normalize (Gradient &x, const Gradient &y)
static void setMax (Gradient &x, const Gradient &y)
static Gradient getZero ()
static void write (FILE *fp, const Gradient &x)
Private Attributes
T _data [3]
Detailed Description
template<class T>
class Gradient< T >
Definition at line 12 of file Gradient.h.
Member Typedef Documentation
template<class T> typedef Vector<T_Scalar,3> Gradient< T >::Coord
Definition at line 19 of file Gradient.h.
template<class T> typedef NumTypeTraits<T>::T_BuiltIn Gradient< T >::T_BuiltIn
Definition at line 17 of file Gradient.h.
template<class T> typedef NumTypeTraits<T>::T_Scalar Gradient< T >::T_Scalar
Definition at line 16 of file Gradient.h.
template<class T> typedef Gradient<T> Gradient< T >::This_T
Definition at line 15 of file Gradient.h.
Member Function Documentation
template<class T> void Gradient< T >::accumulate (const Coord & wt, const T & v) inline
Definition at line 57 of file Gradient.h.
References Gradient< T >::_data.
Referenced by GradientMatrix< T_Scalar >::computeFaceGradient(), and GradientMatrix< T_Scalar >::computeGradient().
   {
     for(int i=0;i<3;i++)
       _data[i] += wt[i]*v;
   }
template<class T> static void Gradient< T >::accumulateDotProduct (Gradient< T > & sum, const Gradient< T > & v0, const Gradient< T > & v1) inline static
Definition at line 133 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0; i<3; i++)
       NumTypeTraits<T>::accumulateDotProduct(sum._data[i],v0._data[i],v1._data[i]);
   }
template<class T> static void Gradient< T >::accumulateOneNorm (Gradient< T > & sum, const Gradient< T > & v) inline static
Definition at line 127 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0; i<3; i++)
       NumTypeTraits<T>::accumulateOneNorm(sum._data[i],v[i]);
   }
template<class T> static int Gradient< T >::getDataSize () inline static
Definition at line 34 of file Gradient.h.
   {
     return 3*NumTypeTraits<T>::getDataSize();
   }
template<class T> static int Gradient< T >::getDimension () inline static
Definition at line 26 of file Gradient.h.
 {return NumTypeTraits<T>::getDimension()+1;}
template<class T> static void Gradient< T >::getShape (int * shp) inline static
Definition at line 28 of file Gradient.h.
   {
     *shp = 3;
     NumTypeTraits<T>::getShape(shp+1);
   }
template<class T> static string Gradient< T >::getTypeName () inline static
Definition at line 21 of file Gradient.h.
   {
     return "Gradient<" + NumTypeTraits<T>::getTypeName() +      ">";
   }
template<class T> static Gradient Gradient< T >::getZero () inline static
Definition at line 162 of file Gradient.h.
References Gradient< T >::zero().
   {
     Gradient z;
     z.zero();
     return z;
   }
template<class T> T Gradient< T >::mag2 () const inline
Definition at line 186 of file Gradient.h.
References Gradient< T >::_data.
Referenced by Gradient< T >::operator<().
   {
     T r(NumTypeTraits<T>::getZero());
     for(int i=0; i<3; i++)
       r+=_data[i]*_data[i];
     return r;
   }
template<class T> static void Gradient< T >::normalize (Gradient< T > & x, const Gradient< T > & y) inline static
Definition at line 151 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0; i<3; i++)
       NumTypeTraits<T>::normalize(x._data[i],y._data[i]);
   }
template<class T> Gradient& Gradient< T >::operator*= (const T_Scalar & s) inline
Definition at line 85 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0;i<3;i++)
       _data[i] *= s;
     return *this;
   }
template<class T> Gradient& Gradient< T >::operator*= (const Gradient< T > & o) inline
Definition at line 92 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0;i<3;i++)
       _data[i] *= o._data[i];
     return *this;
   }
template<class T> T Gradient< T >::operator*= (const Coord & v) inline
Definition at line 99 of file Gradient.h.
References Gradient< T >::_data.
   {
     T r(NumTypeTraits<T>::getZero());
     for(int i=0;i<3;i++)
       r += _data[i]*v[i];
     return r;
   }
template<class T> Gradient& Gradient< T >::operator+= (const Gradient< T > & o) inline
Definition at line 63 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0;i<3;i++)
       _data[i] += o._data[i];
     return *this;
   }
template<class T> Gradient Gradient< T >::operator- () const inline
Definition at line 77 of file Gradient.h.
References Gradient< T >::_data.
   {
     Gradient r;
     for(int i=0;i<3;i++)
       r._data[i] = -_data[i];
     return r;
   }
template<class T> Gradient& Gradient< T >::operator-= (const Gradient< T > & o) inline
Definition at line 70 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0;i<3;i++)
       _data[i] -= o._data[i];
     return *this;
   }
template<class T> Gradient& Gradient< T >::operator/= (const T_Scalar & s) inline
Definition at line 107 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0;i<3;i++)
       _data[i] /= s;
     return *this;
   }
template<class T> Gradient& Gradient< T >::operator/= (const Gradient< T > & o) inline
Definition at line 115 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0;i<3;i++)
       _data[i] /= o._data[i];
     return *this;
   }
template<class T> bool Gradient< T >::operator< (const double tolerance) const inline
Definition at line 194 of file Gradient.h.
References Gradient< T >::mag2().
   {
     return mag2() < tolerance*tolerance;
   }
template<class T> Gradient& Gradient< T >::operator= (const T_Scalar & o) inline
Definition at line 43 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0;i<3;i++)
       _data[i] = o;
     return *this;
   }
template<class T> Gradient& Gradient< T >::operator= (const Gradient< T > & o) inline
Definition at line 50 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0;i<3;i++)
       _data[i] = o._data[i];
     return *this;
   }
template<class T> T& Gradient< T >::operator[] (int n) inline
Definition at line 39 of file Gradient.h.
References Gradient< T >::_data.
 {return _data[n];}
template<class T> const T& Gradient< T >::operator[] (int n) const inline
Definition at line 40 of file Gradient.h.
References Gradient< T >::_data.
 {return _data[n];}
template<class T> void Gradient< T >::print (ostream & os) const inline
Definition at line 169 of file Gradient.h.
References Gradient< T >::_data.
Referenced by operator<<().
   {
     os << "[ " ;
     for(int i=0;i<3;i++)
       os << _data[i] << " " ;
     os << "]";
   }
template<class T> static void Gradient< T >::reduceSum (T_Scalar & sum, const This_T & x) inline static
Definition at line 139 of file Gradient.h.
   {
     for(int i=0; i<3; i++)
       NumTypeTraits<T>::reduceSum(sum,x[i]);
   }
template<class T> static void Gradient< T >::safeDivide (Gradient< T > & x, const Gradient< T > & y) inline static
Definition at line 145 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0; i<3; i++)
       NumTypeTraits<T>::safeDivide(x._data[i],y._data[i]);
   }
template<class T> static void Gradient< T >::setMax (Gradient< T > & x, const Gradient< T > & y) inline static
Definition at line 157 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0; i<3; i++)
       NumTypeTraits<T>::setMax(x._data[i],y._data[i]);
   }
template<class T> static void Gradient< T >::write (FILE * fp, const Gradient< T > & x) inline static
Definition at line 177 of file Gradient.h.
References Gradient< T >::_data.
   {
     for(int i=0; i<3; i++)
     {
         NumTypeTraits<T>::write(fp,x._data[i]);
         fprintf(fp, " ");
     }
   }
template<class T> void Gradient< T >::zero () inline
Definition at line 122 of file Gradient.h.
Referenced by GradientMatrix< T_Scalar >::computeFaceGradient(), GradientMatrix< T_Scalar >::computeGradient(), and Gradient< T >::getZero().
   {
     for(int i=0;i<3;i++) _data[i] = NumTypeTraits<T>::getZero();
   }
Member Data Documentation
template<class T> T Gradient< T >::_data[3] private
Definition at line 199 of file Gradient.h.
Referenced by Gradient< T >::accumulate(), Gradient< T >::accumulateDotProduct(), Gradient< T >::accumulateOneNorm(), Gradient< T >::mag2(), Gradient< T >::normalize(), Gradient< T >::operator*=(), Gradient< T >::operator+=(), Gradient< T >::operator-(), Gradient< T >::operator-=(), Gradient< T >::operator/=(), Gradient< T >::operator=(), Gradient< T >::operator[](), Gradient< T >::print(), Gradient< T >::safeDivide(), Gradient< T >::setMax(), and Gradient< T >::write().
The documentation for this class was generated from the following file:
Gradient.h