Memosa-FVM: FluxJacobianMatrix< OffDiag, X > Class Template Reference
FluxJacobianMatrix< OffDiag, X > Class Template Reference
#include <FluxJacobianMatrix.h>
Public Types
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
Public Member Functions
FluxJacobianMatrix (const CRConnectivity &conn)
virtual ~FluxJacobianMatrix ()
DEFINE_TYPENAME ("FluxJacobianMatrix<"+NumTypeTraits< OffDiag >::getTypeName()+","+NumTypeTraits< X >::getTypeName()+">")
virtual void multiply (IContainer &yB, const IContainer &xB) const
virtual void transpose ()
virtual void multiplyAndAdd (IContainer &yB, const IContainer &xB) const
void setCoeffL (const int f, const OffDiag &c)
void setCoeffR (const int f, const OffDiag &c)
const OffDiag & getCoeffL (const int f) const
const OffDiag & getCoeffR (const int f) const
const CRConnectivity & getConnectivity () const
virtual void initAssembly ()
Public Member Functions inherited from Matrix
Matrix ()
virtual ~Matrix ()
DEFINE_TYPENAME ("Matrix")
virtual shared_ptr< ArrayBase > quadProduct (const IContainer &xB) const
virtual void forwardGS (IContainer &xB, IContainer &bB, IContainer &residual) const
virtual void reverseGS (IContainer &xB, IContainer &bB, IContainer &residual) const
virtual void Jacobi (IContainer &xnew, const IContainer &xold, const IContainer &b) const
virtual void iluSolve (IContainer &xB, const IContainer &bB, const IContainer &residual) const
virtual void spikeSolve (IContainer &xB, const IContainer &bB, const IContainer &residual, const SpikeStorage &spike_storage) const
virtual void solveBoundary (IContainer &xB, IContainer &bB, IContainer &residual) const
virtual void computeResidual (const IContainer &xB, const IContainer &bB, IContainer &residual) const
virtual int createCoarsening (IContainer &coarseIndex, const int groupSize, const double weighRatioThreshold)
virtual void eliminateBoundaryEquations (IContainer &xB)
virtual void printRow (const int nr) const
virtual void * getDiagData () const
virtual void * getOffDiagData () const
virtual int getDiagDataSize () const
virtual int getOffDiagDataSize () const
virtual shared_ptr< Matrix > createMergeMatrix (const LinearSystemMerger &mergeLS)
virtual void setFlatMatrix (Matrix &fmg) const
virtual shared_ptr
< CRConnectivity > createCoarseConnectivity (const IContainer &coarseIndex, const CRConnectivity &coarseToFine, const StorageSite &coarseRowSite, const StorageSite &coarseColSite)
virtual shared_ptr< Matrix > createCoarseMatrix (const IContainer &coarseIndex, const CRConnectivity &coarseToFine, const CRConnectivity &coarseConnectivity)
virtual bool isInvertible ()
Private Attributes
const CRConnectivity & _conn
Array< OffDiag > _coeffL
Array< OffDiag > _coeffR
Detailed Description
template<class OffDiag, class X>
class FluxJacobianMatrix< OffDiag, X >
Definition at line 14 of file FluxJacobianMatrix.h.
Member Typedef Documentation
template<class OffDiag , class X > typedef Array<OffDiag> FluxJacobianMatrix< OffDiag, X >::OffDiagArray
Definition at line 17 of file FluxJacobianMatrix.h.
template<class OffDiag , class X > typedef Array<X> FluxJacobianMatrix< OffDiag, X >::XArray
Definition at line 18 of file FluxJacobianMatrix.h.
Constructor & Destructor Documentation
template<class OffDiag , class X > FluxJacobianMatrix< OffDiag, X >::FluxJacobianMatrix (const CRConnectivity & conn) inline
Definition at line 20 of file FluxJacobianMatrix.h.
                                                  :
     Matrix(),
     _conn(conn),
     _coeffL(_conn.getRowDim()),
     _coeffR(_conn.getRowDim())
   {}
template<class OffDiag , class X > virtual FluxJacobianMatrix< OffDiag, X >::~FluxJacobianMatrix () inline virtual
Definition at line 28 of file FluxJacobianMatrix.h.
 {}
Member Function Documentation
template<class OffDiag , class X > FluxJacobianMatrix< OffDiag, X >::DEFINE_TYPENAME ("FluxJacobianMatrix<"+NumTypeTraits< OffDiag >::getTypeName()+","+NumTypeTraits< X >::getTypeName()+">")
template<class OffDiag , class X > const OffDiag& FluxJacobianMatrix< OffDiag, X >::getCoeffL (const int f) const inline
Definition at line 70 of file FluxJacobianMatrix.h.
References FluxJacobianMatrix< OffDiag, X >::_coeffL.
 {return _coeffL[f];}
template<class OffDiag , class X > const OffDiag& FluxJacobianMatrix< OffDiag, X >::getCoeffR (const int f) const inline
Definition at line 71 of file FluxJacobianMatrix.h.
References FluxJacobianMatrix< OffDiag, X >::_coeffR.
 {return _coeffR[f];}
template<class OffDiag , class X > const CRConnectivity& FluxJacobianMatrix< OffDiag, X >::getConnectivity () const inline virtual
Reimplemented from Matrix.
Definition at line 73 of file FluxJacobianMatrix.h.
References FluxJacobianMatrix< OffDiag, X >::_conn.
 {return _conn;}
template<class OffDiag , class X > virtual void FluxJacobianMatrix< OffDiag, X >::initAssembly () inline virtual
Implements Matrix.
Definition at line 75 of file FluxJacobianMatrix.h.
References FluxJacobianMatrix< OffDiag, X >::_coeffL, FluxJacobianMatrix< OffDiag, X >::_coeffR, and Array< T >::zero().
   {
     _coeffL.zero();
     _coeffR.zero();
   }
template<class OffDiag , class X > virtual void FluxJacobianMatrix< OffDiag, X >::multiply (IContainer & yB, const IContainer & xB) const inline virtual
Reimplemented from Matrix.
Definition at line 35 of file FluxJacobianMatrix.h.
References FluxJacobianMatrix< OffDiag, X >::_coeffL, FluxJacobianMatrix< OffDiag, X >::_coeffR, FluxJacobianMatrix< OffDiag, X >::_conn, and CRConnectivity::getRowDim().
   {
     XArray& y = dynamic_cast<XArray&>(yB);
     const XArray& x = dynamic_cast<const XArray&>(xB);
     const int nRows = _conn.getRowDim();
     for(int nr=0; nr<nRows; nr++)
     {
         const int c0=_conn(nr,0);
         const int c1=_conn(nr,1);
         y[nr] = _coeffL[nr]*x[c0] + _coeffR[nr]*x[c1];
     }
   }
template<class OffDiag , class X > virtual void FluxJacobianMatrix< OffDiag, X >::multiplyAndAdd (IContainer & yB, const IContainer & xB) const inline virtual
Reimplemented from Matrix.
Definition at line 52 of file FluxJacobianMatrix.h.
References FluxJacobianMatrix< OffDiag, X >::_coeffL, FluxJacobianMatrix< OffDiag, X >::_coeffR, FluxJacobianMatrix< OffDiag, X >::_conn, and CRConnectivity::getRowDim().
   {
     XArray& y = dynamic_cast<XArray&>(yB);
     const XArray& x = dynamic_cast<const XArray&>(xB);
     const int nRows = _conn.getRowDim();
     for(int nr=0; nr<nRows; nr++)
     {
         const int c0=_conn(nr,0);
         const int c1=_conn(nr,1);
         y[nr] += _coeffL[nr]*x[c0] + _coeffR[nr]*x[c1];
     }
   }
template<class OffDiag , class X > void FluxJacobianMatrix< OffDiag, X >::setCoeffL (const int f, const OffDiag & c) inline
Definition at line 67 of file FluxJacobianMatrix.h.
References FluxJacobianMatrix< OffDiag, X >::_coeffL.
Referenced by BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyConvectionBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyDielectricInterfaceBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyDirichletBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyExtrapolationBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyInterfaceBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyMixedBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyRadiationBC(), BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applySymmetryBC(), and GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::applySymmetryBC().
 {_coeffL[f]=c;}
template<class OffDiag , class X > void FluxJacobianMatrix< OffDiag, X >::setCoeffR (const int f, const OffDiag & c) inline
Definition at line 68 of file FluxJacobianMatrix.h.
References FluxJacobianMatrix< OffDiag, X >::_coeffR.
Referenced by BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyConvectionBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyDielectricInterfaceBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyDirichletBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyExtrapolationBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyInterfaceBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyMixedBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyRadiationBC(), BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applySymmetryBC(), and GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::applySymmetryBC().
 {_coeffR[f]=c;}
template<class OffDiag , class X > virtual void FluxJacobianMatrix< OffDiag, X >::transpose () inline virtual
Reimplemented from Matrix.
Definition at line 50 of file FluxJacobianMatrix.h.
 {}
Member Data Documentation
template<class OffDiag , class X > Array<OffDiag> FluxJacobianMatrix< OffDiag, X >::_coeffL private
Definition at line 83 of file FluxJacobianMatrix.h.
Referenced by FluxJacobianMatrix< OffDiag, X >::getCoeffL(), FluxJacobianMatrix< OffDiag, X >::initAssembly(), FluxJacobianMatrix< OffDiag, X >::multiply(), FluxJacobianMatrix< OffDiag, X >::multiplyAndAdd(), and FluxJacobianMatrix< OffDiag, X >::setCoeffL().
template<class OffDiag , class X > Array<OffDiag> FluxJacobianMatrix< OffDiag, X >::_coeffR private
Definition at line 84 of file FluxJacobianMatrix.h.
Referenced by FluxJacobianMatrix< OffDiag, X >::getCoeffR(), FluxJacobianMatrix< OffDiag, X >::initAssembly(), FluxJacobianMatrix< OffDiag, X >::multiply(), FluxJacobianMatrix< OffDiag, X >::multiplyAndAdd(), and FluxJacobianMatrix< OffDiag, X >::setCoeffR().
template<class OffDiag , class X > const CRConnectivity& FluxJacobianMatrix< OffDiag, X >::_conn private
Definition at line 82 of file FluxJacobianMatrix.h.
Referenced by FluxJacobianMatrix< OffDiag, X >::getConnectivity(), FluxJacobianMatrix< OffDiag, X >::multiply(), and FluxJacobianMatrix< OffDiag, X >::multiplyAndAdd().
The documentation for this class was generated from the following file:
FluxJacobianMatrix.h