Memosa-FVM: BatteryPC_BCS< X, Diag, OffDiag > Class Template Reference
BatteryPC_BCS< X, Diag, OffDiag > Class Template Reference
#include <BatteryPC_BCS.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Array< int > IntArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef FluxJacobianMatrix
< Diag, X > FMatrix
typedef DiagonalMatrix< Diag, X > BBMatrix
typedef Array< Diag > DiagArray
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
BatteryPC_BCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, Field &fluxField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
void applySingleEquationDirichletBC (int f, const T_Scalar &bValue, const int v) const
void applySingleEquationDirichletBC (const FloatValEvaluator< T_Scalar > &bValue, const int v) const
void applySingleEquationNeumannBC (const int f, const T_Scalar &specifiedFlux, const int v) const
void applySingleEquationNeumannBC (const T_Scalar &bFlux, const int v) const
Protected Attributes
const StorageSite & _faces
const StorageSite & _cells
const IntArray & _ibType
const CRConnectivity & _faceCells
const Field & _varField
const Field & _fluxField
const MultiField::ArrayIndex _xIndex
const MultiField::ArrayIndex _fluxIndex
CCMatrix & _dRdX
FMatrix & _dFluxdX
BBMatrix & _dFluxdFlux
CCAssembler & _assembler
DiagArray & _dRdXDiag
XArray & _x
XArray & _r
XArray & _flux
XArray & _rFlux
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
const bool _is2D
Detailed Description
template<class X, class Diag, class OffDiag>
class BatteryPC_BCS< X, Diag, OffDiag >
Definition at line 22 of file BatteryPC_BCS.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef DiagonalMatrix<Diag,X> BatteryPC_BCS< X, Diag, OffDiag >::BBMatrix
Definition at line 37 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler BatteryPC_BCS< X, Diag, OffDiag >::CCAssembler
Definition at line 34 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> BatteryPC_BCS< X, Diag, OffDiag >::CCMatrix
Definition at line 33 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef Array<Diag> BatteryPC_BCS< X, Diag, OffDiag >::DiagArray
Definition at line 39 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef FluxJacobianMatrix<Diag,X> BatteryPC_BCS< X, Diag, OffDiag >::FMatrix
Definition at line 36 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef Array<int> BatteryPC_BCS< X, Diag, OffDiag >::IntArray
Definition at line 29 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef Array<OffDiag> BatteryPC_BCS< X, Diag, OffDiag >::OffDiagArray
Definition at line 40 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar BatteryPC_BCS< X, Diag, OffDiag >::T_Scalar
Definition at line 26 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> BatteryPC_BCS< X, Diag, OffDiag >::TArray
Definition at line 28 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> BatteryPC_BCS< X, Diag, OffDiag >::VectorT3
Definition at line 31 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> BatteryPC_BCS< X, Diag, OffDiag >::VectorT3Array
Definition at line 43 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > typedef Array<X> BatteryPC_BCS< X, Diag, OffDiag >::XArray
Definition at line 42 of file BatteryPC_BCS.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > BatteryPC_BCS< X, Diag, OffDiag >::BatteryPC_BCS (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, Field & varField, Field & fluxField, MultiFieldMatrix & matrix, MultiField & xField, MultiField & rField) inline
Definition at line 46 of file BatteryPC_BCS.h.
                                                      :
     _faces(faces),
     _cells(mesh.getCells()),
     _ibType(dynamic_cast<const IntArray&>(geomFields.ibType[_cells])),
     _faceCells(mesh.getFaceCells(_faces)),
     _varField(varField),
     _fluxField(fluxField),
     _xIndex(&_varField,&_cells),
     _fluxIndex(&_fluxField,&_faces),
     _dRdX(dynamic_cast<CCMatrix&>(matrix.getMatrix(_xIndex,_xIndex))),
     _dFluxdX(dynamic_cast<FMatrix&>(matrix.getMatrix(_fluxIndex,_xIndex))),
     _dFluxdFlux(dynamic_cast<BBMatrix&>(matrix.getMatrix(_fluxIndex,_fluxIndex))),
     _assembler(_dRdX.getPairWiseAssembler(_faceCells)),
     _dRdXDiag(_dRdX.getDiag()),
     _x(dynamic_cast<XArray&>(xField[_xIndex])),
     _r(dynamic_cast<XArray&>(rField[_xIndex])),
     _flux(dynamic_cast<XArray&>(xField[_fluxIndex])),
     _rFlux(dynamic_cast<XArray&>(rField[_fluxIndex])),
     _areaMagField(geomFields.areaMag),
     _faceAreaMag(dynamic_cast<const TArray&>(_areaMagField[_faces])),
     _areaField(geomFields.area),
     _faceArea(dynamic_cast<const VectorT3Array&>(_areaField[_faces])),
     _is2D(mesh.getDimension()==2)
   {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC (int f, const T_Scalar & bValue, const int v) const inline
Definition at line 77 of file BatteryPC_BCS.h.
References BatteryPC_BCS< X, Diag, OffDiag >::_assembler, BatteryPC_BCS< X, Diag, OffDiag >::_dFluxdFlux, BatteryPC_BCS< X, Diag, OffDiag >::_dFluxdX, BatteryPC_BCS< X, Diag, OffDiag >::_dRdXDiag, BatteryPC_BCS< X, Diag, OffDiag >::_faceCells, BatteryPC_BCS< X, Diag, OffDiag >::_flux, BatteryPC_BCS< X, Diag, OffDiag >::_ibType, BatteryPC_BCS< X, Diag, OffDiag >::_r, BatteryPC_BCS< X, Diag, OffDiag >::_rFlux, BatteryPC_BCS< X, Diag, OffDiag >::_x, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), Mesh::IBTYPE_FLUID, FluxJacobianMatrix< OffDiag, X >::setCoeffL(), and FluxJacobianMatrix< OffDiag, X >::setCoeffR().
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     // the current value of flux and its Jacobians
     const T_Scalar fluxB = -(_r[c1])[v];
     //const T_Scalar dFluxdXC0 = -(_assembler.getCoeff10(f))(v,v);
     const OffDiag dFluxdXC0_orig = -_assembler.getCoeff10(f);
     const T_Scalar dFluxdXC1 = -(_dRdXDiag[c1])[v];
     OffDiag dRC0dXC1_orig = _assembler.getCoeff01(f);
     const T_Scalar dRC0dXC1 = dRC0dXC1_orig[v];
     // since we know the boundary value, compute the boundary
     // x correction and it's contribution to the residual for c0; we
     // can then eliminate the coefficient to the boundary cell
     const T_Scalar dXC1 = bValue - (_x[c1])[v];
     const T_Scalar dFlux = dFluxdXC1*dXC1;
     const T_Scalar dRC0 = dRC0dXC1*dXC1;
     (_r[c0])[v] += dRC0;
     (_assembler.getCoeff01(f))[v] = NumTypeTraits<T_Scalar>::getZero();
     // set the boundary value and make its correction equation an
     // identity
     (_x[c1])[v] = bValue;
     (_assembler.getCoeff10(f))[v] = NumTypeTraits<T_Scalar>::getZero();
     (_r[c1])[v] = NumTypeTraits<T_Scalar>::getZero();
     (_dRdXDiag[c1])[v] = NumTypeTraits<T_Scalar>::getNegativeUnity();
     //setup the equation for the boundary flux correction
     _dFluxdX.setCoeffL(f,dFluxdXC0_orig);
     dRC0dXC1_orig[v] = NumTypeTraits<T_Scalar>::getZero();
     _dFluxdX.setCoeffR(f,dRC0dXC1_orig);
     (_flux[f])[v] = fluxB;
     (_rFlux[f])[v] = dFlux;
     Diag _dFluxdFlux_orig = _dFluxdFlux[f];
     _dFluxdFlux_orig[v] = NumTypeTraits<T_Scalar>::getNegativeUnity();
     _dFluxdFlux[f] = _dFluxdFlux_orig;
   }
template<class X , class Diag , class OffDiag > void BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC (const FloatValEvaluator< T_Scalar > & bValue, const int v) const inline
Definition at line 122 of file BatteryPC_BCS.h.
References BatteryPC_BCS< X, Diag, OffDiag >::_faces, BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applySingleEquationDirichletBC(i,bValue[i],v);
   }
template<class X , class Diag , class OffDiag > void BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC (const int f, const T_Scalar & specifiedFlux, const int v) const inline
Definition at line 128 of file BatteryPC_BCS.h.
References BatteryPC_BCS< X, Diag, OffDiag >::_dFluxdFlux, BatteryPC_BCS< X, Diag, OffDiag >::_dRdX, BatteryPC_BCS< X, Diag, OffDiag >::_faceAreaMag, BatteryPC_BCS< X, Diag, OffDiag >::_faceCells, BatteryPC_BCS< X, Diag, OffDiag >::_flux, BatteryPC_BCS< X, Diag, OffDiag >::_ibType, BatteryPC_BCS< X, Diag, OffDiag >::_r, Mesh::IBTYPE_FLUID, and CRMatrix< T_Diag, T_OffDiag, X >::setBoundary().
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     // the current value of flux and its Jacobians
     const T_Scalar fluxB = -(_r[c1])[v];
     // since we know the boundary flux, compute the boundary flux
     // correction and add it to the c0 residual; also eliminate
     // coeff to the boundary cell and remove it from the ap coeff
     const T_Scalar dFlux = specifiedFlux*_faceAreaMag[f] - fluxB;
     // setup the equation for the boundary value; the coefficients
     // are already computed so just need to set the rhs
     (_r[c1])[v] = dFlux;
     // mark this row as a "boundary" row so that we will update it
     // after the overall system is solved
     _dRdX.setBoundary(c1);
     // fix the boundary flux to the specified value
     (_flux[f])[v] = specifiedFlux*_faceAreaMag[f];
     Diag _dFluxdFlux_orig = _dFluxdFlux[f];
     _dFluxdFlux_orig[v] = NumTypeTraits<T_Scalar>::getNegativeUnity();
     _dFluxdFlux[f] = _dFluxdFlux_orig;
   }
template<class X , class Diag , class OffDiag > void BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC (const T_Scalar & bFlux, const int v) const inline
Definition at line 161 of file BatteryPC_BCS.h.
References BatteryPC_BCS< X, Diag, OffDiag >::_faces, BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC(), and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applySingleEquationNeumannBC(i,bFlux,v);
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const Field& BatteryPC_BCS< X, Diag, OffDiag >::_areaField protected
Definition at line 187 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > const Field& BatteryPC_BCS< X, Diag, OffDiag >::_areaMagField protected
Definition at line 185 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > CCAssembler& BatteryPC_BCS< X, Diag, OffDiag >::_assembler protected
Definition at line 179 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC().
template<class X , class Diag , class OffDiag > const StorageSite& BatteryPC_BCS< X, Diag, OffDiag >::_cells protected
Definition at line 169 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > BBMatrix& BatteryPC_BCS< X, Diag, OffDiag >::_dFluxdFlux protected
Definition at line 178 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), and BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC().
template<class X , class Diag , class OffDiag > FMatrix& BatteryPC_BCS< X, Diag, OffDiag >::_dFluxdX protected
Definition at line 177 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC().
template<class X , class Diag , class OffDiag > CCMatrix& BatteryPC_BCS< X, Diag, OffDiag >::_dRdX protected
Definition at line 176 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC().
template<class X , class Diag , class OffDiag > DiagArray& BatteryPC_BCS< X, Diag, OffDiag >::_dRdXDiag protected
Definition at line 180 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC().
template<class X , class Diag , class OffDiag > const VectorT3Array& BatteryPC_BCS< X, Diag, OffDiag >::_faceArea protected
Definition at line 188 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > const TArray& BatteryPC_BCS< X, Diag, OffDiag >::_faceAreaMag protected
Definition at line 186 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC().
template<class X , class Diag , class OffDiag > const CRConnectivity& BatteryPC_BCS< X, Diag, OffDiag >::_faceCells protected
Definition at line 171 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), and BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC().
template<class X , class Diag , class OffDiag > const StorageSite& BatteryPC_BCS< X, Diag, OffDiag >::_faces protected
Definition at line 168 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), and BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC().
template<class X , class Diag , class OffDiag > XArray& BatteryPC_BCS< X, Diag, OffDiag >::_flux protected
Definition at line 183 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), and BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC().
template<class X , class Diag , class OffDiag > const Field& BatteryPC_BCS< X, Diag, OffDiag >::_fluxField protected
Definition at line 173 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > const MultiField::ArrayIndex BatteryPC_BCS< X, Diag, OffDiag >::_fluxIndex protected
Definition at line 175 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > const IntArray& BatteryPC_BCS< X, Diag, OffDiag >::_ibType protected
Definition at line 170 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), and BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC().
template<class X , class Diag , class OffDiag > const bool BatteryPC_BCS< X, Diag, OffDiag >::_is2D protected
Definition at line 189 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > XArray& BatteryPC_BCS< X, Diag, OffDiag >::_r protected
Definition at line 182 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), and BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC().
template<class X , class Diag , class OffDiag > XArray& BatteryPC_BCS< X, Diag, OffDiag >::_rFlux protected
Definition at line 184 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC().
template<class X , class Diag , class OffDiag > const Field& BatteryPC_BCS< X, Diag, OffDiag >::_varField protected
Definition at line 172 of file BatteryPC_BCS.h.
template<class X , class Diag , class OffDiag > XArray& BatteryPC_BCS< X, Diag, OffDiag >::_x protected
Definition at line 181 of file BatteryPC_BCS.h.
Referenced by BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC().
template<class X , class Diag , class OffDiag > const MultiField::ArrayIndex BatteryPC_BCS< X, Diag, OffDiag >::_xIndex protected
Definition at line 174 of file BatteryPC_BCS.h.
The documentation for this class was generated from the following file:
BatteryPC_BCS.h