Memosa-FVM: DiagonalMatrix< Diag, X > Class Template Reference
DiagonalMatrix< Diag, X > Class Template Reference
#include <DiagonalMatrix.h>
Public Types
typedef Array< Diag > DiagArray
typedef Array< X > XArray
Public Member Functions
DiagonalMatrix (const int length)
virtual ~DiagonalMatrix ()
DEFINE_TYPENAME ("DiagonalMatrix<"+NumTypeTraits< Diag >::getTypeName()+","+NumTypeTraits< X >::getTypeName()+">")
virtual void multiply (IContainer &yB, const IContainer &xB) const
virtual void multiplyAndAdd (IContainer &yB, const IContainer &xB) const
virtual void forwardGS (IContainer &xB, IContainer &bB, IContainer &) const
virtual void reverseGS (IContainer &xB, IContainer &bB, IContainer &r) const
virtual void solveBoundary (IContainer &xB, IContainer &bB, IContainer &r) const
virtual void computeResidual (const IContainer &xB, const IContainer &bB, IContainer &rB) const
virtual void transpose ()
Diag & operator[] (int n)
const Diag & operator[] (int n) const
void addToDiag (const int i, const Diag &d)
void unitize ()
void unitize (const int i)
virtual shared_ptr
< CRConnectivity > createCoarseConnectivity (const IContainer &gCoarseIndex, const CRConnectivity &coarseToFine, const StorageSite &coarseRowSite, const StorageSite &coarseColSite)
virtual shared_ptr< Matrix > createCoarseMatrix (const IContainer &gCoarseIndex, const CRConnectivity &coarseToFine, const CRConnectivity &)
virtual void initAssembly ()
virtual bool isInvertible ()
Public Member Functions inherited from Matrix
Matrix ()
virtual ~Matrix ()
DEFINE_TYPENAME ("Matrix")
virtual shared_ptr< ArrayBase > quadProduct (const IContainer &xB) const
virtual void Jacobi (IContainer &xnew, const IContainer &xold, const IContainer &b) const
virtual void iluSolve (IContainer &xB, const IContainer &bB, const IContainer &residual) const
virtual void spikeSolve (IContainer &xB, const IContainer &bB, const IContainer &residual, const SpikeStorage &spike_storage) const
virtual int createCoarsening (IContainer &coarseIndex, const int groupSize, const double weighRatioThreshold)
virtual const CRConnectivity & getConnectivity () const
virtual void eliminateBoundaryEquations (IContainer &xB)
virtual void printRow (const int nr) const
virtual void * getDiagData () const
virtual void * getOffDiagData () const
virtual int getDiagDataSize () const
virtual int getOffDiagDataSize () const
virtual shared_ptr< Matrix > createMergeMatrix (const LinearSystemMerger &mergeLS)
virtual void setFlatMatrix (Matrix &fmg) const
Private Attributes
const int _length
Array< Diag > _diag
Detailed Description
template<class Diag, class X>
class DiagonalMatrix< Diag, X >
Definition at line 16 of file DiagonalMatrix.h.
Member Typedef Documentation
template<class Diag , class X > typedef Array<Diag> DiagonalMatrix< Diag, X >::DiagArray
Definition at line 19 of file DiagonalMatrix.h.
template<class Diag , class X > typedef Array<X> DiagonalMatrix< Diag, X >::XArray
Definition at line 20 of file DiagonalMatrix.h.
Constructor & Destructor Documentation
template<class Diag , class X > DiagonalMatrix< Diag, X >::DiagonalMatrix (const int length) inline
Definition at line 22 of file DiagonalMatrix.h.
References logCtor.
Referenced by DiagonalMatrix< Diag, X >::createCoarseMatrix().
                                    :
     Matrix(),
     _length(length),
     _diag(_length)
   {
     logCtor();
   }
template<class Diag , class X > virtual DiagonalMatrix< Diag, X >::~DiagonalMatrix () inline virtual
Definition at line 30 of file DiagonalMatrix.h.
 {}
Member Function Documentation
template<class Diag , class X > void DiagonalMatrix< Diag, X >::addToDiag (const int i, const Diag & d) inline
Definition at line 93 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag.
   {
     _diag[i] += d;
   }
template<class Diag , class X > virtual void DiagonalMatrix< Diag, X >::computeResidual (const IContainer & xB, const IContainer & bB, IContainer & rB) const inline virtual
Reimplemented from Matrix.
Definition at line 75 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag, and DiagonalMatrix< Diag, X >::_length.
   {
     const XArray& x = dynamic_cast<const XArray&>(xB);
     const XArray& b = dynamic_cast<const XArray&>(bB);
     XArray& r = dynamic_cast<XArray&>(rB);
     for(int nr=0; nr<_length; nr++)
     {
         r[nr] = b[nr] + _diag[nr]*x[nr];
     }
   }
template<class Diag , class X > virtual shared_ptr<CRConnectivity> DiagonalMatrix< Diag, X >::createCoarseConnectivity (const IContainer & gCoarseIndex, const CRConnectivity & coarseToFine, const StorageSite & coarseRowSite, const StorageSite & coarseColSite) inline virtual
Reimplemented from Matrix.
Definition at line 109 of file DiagonalMatrix.h.
   {
     // we don't really need one but all matrices are supposed to supply one
     return shared_ptr<CRConnectivity>(new CRConnectivity(coarseRowSite,coarseColSite));
   }
template<class Diag , class X > virtual shared_ptr<Matrix> DiagonalMatrix< Diag, X >::createCoarseMatrix (const IContainer & gCoarseIndex, const CRConnectivity & coarseToFine, const CRConnectivity &) inline virtual
Reimplemented from Matrix.
Definition at line 119 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag, DiagonalMatrix< Diag, X >::DiagonalMatrix(), CRConnectivity::getCount(), CRConnectivity::getRowDim(), and Array< T >::zero().
   {
     const int nCoarseRows = coarseToFine.getRowDim();
     shared_ptr<DiagonalMatrix> coarseMatrix(new DiagonalMatrix(nCoarseRows));
     Array<Diag>& coarseDiag = coarseMatrix->_diag;
     coarseDiag.zero();
     for(int nrCoarse=0; nrCoarse<nCoarseRows; nrCoarse++)
     {
         // loop over the fine rows that make up this coarse row
         const int nFine = coarseToFine.getCount(nrCoarse);
         for(int nfr=0; nfr<nFine; nfr++)
         {
             const int nrFine = coarseToFine(nrCoarse,nfr);
             coarseDiag[nrCoarse] += _diag[nrFine];
         }
     }
     return coarseMatrix;
   }
template<class Diag , class X > DiagonalMatrix< Diag, X >::DEFINE_TYPENAME ("DiagonalMatrix<"+NumTypeTraits< Diag >::getTypeName()+","+NumTypeTraits< X >::getTypeName()+">")
template<class Diag , class X > virtual void DiagonalMatrix< Diag, X >::forwardGS (IContainer & xB, IContainer & bB, IContainer &) const inline virtual
Reimplemented from Matrix.
Definition at line 57 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag, and DiagonalMatrix< Diag, X >::_length.
Referenced by DiagonalMatrix< Diag, X >::reverseGS(), and DiagonalMatrix< Diag, X >::solveBoundary().
   {
     XArray& x = dynamic_cast<XArray&>(xB);
     const XArray& b = dynamic_cast<const XArray&>(bB);
     for(int i=0; i<_length; i++)
       x[i] = -b[i]/_diag[i];
   }
template<class Diag , class X > virtual void DiagonalMatrix< Diag, X >::initAssembly () inline virtual
Implements Matrix.
Definition at line 146 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag, and Array< T >::zero().
   {
     _diag.zero();
   }
template<class Diag , class X > virtual bool DiagonalMatrix< Diag, X >::isInvertible () inline virtual
Reimplemented from Matrix.
Definition at line 151 of file DiagonalMatrix.h.
 {return true;}
template<class Diag , class X > virtual void DiagonalMatrix< Diag, X >::multiply (IContainer & yB, const IContainer & xB) const inline virtual
Reimplemented from Matrix.
Definition at line 37 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag, and DiagonalMatrix< Diag, X >::_length.
   {
     XArray& y = dynamic_cast<XArray&>(yB);
     const XArray& x = dynamic_cast<const XArray&>(xB);
     for(int i=0; i<_length; i++)
     {
         y[i] = _diag[i]*x[i];
     }
   }
template<class Diag , class X > virtual void DiagonalMatrix< Diag, X >::multiplyAndAdd (IContainer & yB, const IContainer & xB) const inline virtual
Reimplemented from Matrix.
Definition at line 47 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag, and DiagonalMatrix< Diag, X >::_length.
   {
     XArray& y = dynamic_cast<XArray&>(yB);
     const XArray& x = dynamic_cast<const XArray&>(xB);
     for(int i=0; i<_length; i++)
     {
         y[i] += _diag[i]*x[i];
     }
   }
template<class Diag , class X > Diag& DiagonalMatrix< Diag, X >::operator[] (int n) inline
Definition at line 90 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag.
 {return _diag[n];}
template<class Diag , class X > const Diag& DiagonalMatrix< Diag, X >::operator[] (int n) const inline
Definition at line 91 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag.
 {return _diag[n];}
template<class Diag , class X > virtual void DiagonalMatrix< Diag, X >::reverseGS (IContainer & xB, IContainer & bB, IContainer & r) const inline virtual
Reimplemented from Matrix.
Definition at line 65 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::forwardGS().
   {
     forwardGS(xB,bB,r);
   }
template<class Diag , class X > virtual void DiagonalMatrix< Diag, X >::solveBoundary (IContainer & xB, IContainer & bB, IContainer & r) const inline virtual
Reimplemented from Matrix.
Definition at line 70 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::forwardGS().
   {
     forwardGS(xB,bB,r);
   }
template<class Diag , class X > virtual void DiagonalMatrix< Diag, X >::transpose () inline virtual
Reimplemented from Matrix.
Definition at line 88 of file DiagonalMatrix.h.
 {}
template<class Diag , class X > void DiagonalMatrix< Diag, X >::unitize () inline
Definition at line 98 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag.
Referenced by FlowModel< T >::Impl::linearizeContinuity().
   {
     _diag = NumTypeTraits<Diag>::getNegativeUnity();
   }
template<class Diag , class X > void DiagonalMatrix< Diag, X >::unitize (const int i) inline
Definition at line 103 of file DiagonalMatrix.h.
References DiagonalMatrix< Diag, X >::_diag.
   {
     _diag[i] = NumTypeTraits<Diag>::getNegativeUnity();
   }
Member Data Documentation
template<class Diag , class X > Array<Diag> DiagonalMatrix< Diag, X >::_diag private
Definition at line 155 of file DiagonalMatrix.h.
Referenced by DiagonalMatrix< Diag, X >::addToDiag(), DiagonalMatrix< Diag, X >::computeResidual(), DiagonalMatrix< Diag, X >::createCoarseMatrix(), DiagonalMatrix< Diag, X >::forwardGS(), DiagonalMatrix< Diag, X >::initAssembly(), DiagonalMatrix< Diag, X >::multiply(), DiagonalMatrix< Diag, X >::multiplyAndAdd(), DiagonalMatrix< Diag, X >::operator[](), and DiagonalMatrix< Diag, X >::unitize().
template<class Diag , class X > const int DiagonalMatrix< Diag, X >::_length private
Definition at line 154 of file DiagonalMatrix.h.
Referenced by DiagonalMatrix< Diag, X >::computeResidual(), DiagonalMatrix< Diag, X >::forwardGS(), DiagonalMatrix< Diag, X >::multiply(), and DiagonalMatrix< Diag, X >::multiplyAndAdd().
The documentation for this class was generated from the following file:
DiagonalMatrix.h