Memosa-FVM: Underrelaxer< X, Diag, OffDiag > Class Template Reference
Underrelaxer< X, Diag, OffDiag > Class Template Reference
#include <Underrelaxer.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
Public Member Functions
Underrelaxer (const MeshList &meshes, Field &varField, const T_Scalar urf)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &, MultiField &)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const Field & _varField
const T_Scalar _urf
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class Underrelaxer< X, Diag, OffDiag >
Definition at line 18 of file Underrelaxer.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> Underrelaxer< X, Diag, OffDiag >::CCMatrix
Definition at line 24 of file Underrelaxer.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray Underrelaxer< X, Diag, OffDiag >::DiagArray
Definition at line 25 of file Underrelaxer.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar Underrelaxer< X, Diag, OffDiag >::T_Scalar
Definition at line 22 of file Underrelaxer.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> Underrelaxer< X, Diag, OffDiag >::TArray
Definition at line 29 of file Underrelaxer.h.
template<class X , class Diag , class OffDiag > typedef Array<X> Underrelaxer< X, Diag, OffDiag >::XArray
Definition at line 28 of file Underrelaxer.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > Underrelaxer< X, Diag, OffDiag >::Underrelaxer (const MeshList & meshes, Field & varField, const T_Scalar urf) inline
Definition at line 31 of file Underrelaxer.h.
                                    :
     Discretization(meshes),
     _varField(varField),
     _urf(urf)
   {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void Underrelaxer< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & , MultiField &) inline virtual
Implements Discretization.
Definition at line 39 of file Underrelaxer.h.
References Underrelaxer< X, Diag, OffDiag >::_urf, Underrelaxer< X, Diag, OffDiag >::_varField, Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), MultiFieldMatrix::getMatrix(), and StorageSite::getSelfCount().
   {
     const StorageSite& cells = mesh.getCells();
     const MultiField::ArrayIndex cIndex(&_varField,&cells);
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cIndex,cIndex));
     DiagArray& diag = matrix.getDiag();
     const int nCells = cells.getSelfCount();
     for(int c=0; c<nCells; c++)
     {
         diag[c] /= _urf;
     }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const T_Scalar Underrelaxer< X, Diag, OffDiag >::_urf private
Definition at line 56 of file Underrelaxer.h.
Referenced by Underrelaxer< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& Underrelaxer< X, Diag, OffDiag >::_varField private
Definition at line 55 of file Underrelaxer.h.
Referenced by Underrelaxer< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
Underrelaxer.h