Memosa-FVM: GenericBCS< X, Diag, OffDiag > Class Template Reference
GenericBCS< X, Diag, OffDiag > Class Template Reference
#include <GenericBCS.h>
Public Types
typedef BaseGenericBCS< X,
Diag, OffDiag > T_Parent
Public Types inherited from BaseGenericBCS< X, Diag, OffDiag >
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Array< int > IntArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef FluxJacobianMatrix
< Diag, X > FMatrix
typedef DiagonalMatrix< Diag, X > BBMatrix
typedef Array< Diag > DiagArray
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
GenericBCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, Field &fluxField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
void applySymmetryBC () const
Public Member Functions inherited from BaseGenericBCS< X, Diag, OffDiag >
BaseGenericBCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, Field &fluxField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
void applyDirichletBC (int f, const X &bValue) const
void applyDirichletBC (const X &bValue) const
void applyDirichletBC (const FloatValEvaluator< X > &bValue) const
void applyNeumannBC (const int f, const X &specifiedFlux) const
void applyNeumannBC (const X &bFlux) const
void applyNeumannBC (const FloatValEvaluator< X > &bFlux) const
void applyExtrapolationBC () const
void applyExtrapolationBC (const int f) const
void applyConvectionBC (const int f, const X &hCoeff, const X &Xinf) const
void applyConvectionBC (const X &hCoeff, const X &Xinf) const
void applyRadiationBC (const int f, const X &emissivity, const X &Xinf) const
void applyMixedBC (const int f, const X &hCoeff, const X &emissivity, const X &Xinf) const
void applyInterfaceBC (const int f) const
void applyInterfaceBC () const
void applyDielectricInterfaceBC (const int f, const X &hCoeff, const X &Xinf, const X &source) const
void applyDielectricInterfaceBC (const X &hCoeff, const X &Xinf, const X &source) const
void applyFlowBC (const TArray &convFlux, const X &bValue) const
void applyNonzeroDiagBC () const
void applyNonzeroDiagBC (int f) const
Additional Inherited Members
Protected Attributes inherited from BaseGenericBCS< X, Diag, OffDiag >
const StorageSite & _faces
const StorageSite & _cells
const IntArray & _ibType
const CRConnectivity & _faceCells
const Field & _varField
const Field & _fluxField
const MultiField::ArrayIndex _xIndex
const MultiField::ArrayIndex _fluxIndex
CCMatrix & _dRdX
FMatrix & _dFluxdX
BBMatrix & _dFluxdFlux
CCAssembler & _assembler
DiagArray & _dRdXDiag
XArray & _x
XArray & _r
XArray & _flux
XArray & _rFlux
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
const bool _is2D
Detailed Description
template<class X, class Diag, class OffDiag>
class GenericBCS< X, Diag, OffDiag >
Definition at line 473 of file GenericBCS.h.
Member Typedef Documentation
template<class X, class Diag, class OffDiag> typedef BaseGenericBCS<X,Diag,OffDiag> GenericBCS< X, Diag, OffDiag >::T_Parent
Definition at line 477 of file GenericBCS.h.
Constructor & Destructor Documentation
template<class X, class Diag, class OffDiag> GenericBCS< X, Diag, OffDiag >::GenericBCS (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, Field & varField, Field & fluxField, MultiFieldMatrix & matrix, MultiField & xField, MultiField & rField) inline
Definition at line 479 of file GenericBCS.h.
                                                      :
     T_Parent(faces,mesh,geomFields,varField,fluxField,matrix,xField,rField)
   {}
Member Function Documentation
template<class X, class Diag, class OffDiag> void GenericBCS< X, Diag, OffDiag >::applySymmetryBC () const inline
Definition at line 491 of file GenericBCS.h.
References BaseGenericBCS< X, Diag, OffDiag >::_assembler, BaseGenericBCS< X, Diag, OffDiag >::_dFluxdFlux, BaseGenericBCS< X, Diag, OffDiag >::_dRdX, BaseGenericBCS< X, Diag, OffDiag >::_dRdXDiag, BaseGenericBCS< X, Diag, OffDiag >::_faceCells, BaseGenericBCS< X, Diag, OffDiag >::_faces, BaseGenericBCS< X, Diag, OffDiag >::_flux, BaseGenericBCS< X, Diag, OffDiag >::_r, BaseGenericBCS< X, Diag, OffDiag >::_rFlux, BaseGenericBCS< X, Diag, OffDiag >::_x, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), and CRMatrix< T_Diag, T_OffDiag, X >::setBoundary().
   {
     for(int f=0; f<this->_faces.getCount(); f++)
     {
         const int c0 = this->_faceCells(f,0);
         const int c1 = this->_faceCells(f,1);
         // the current value of flux and its Jacobians
         //const X fluxB = -this->_r[c1];
         //const OffDiag dFluxdXC0 = -this->_assembler.getCoeff10(f);
         const Diag dFluxdXC1 = -this->_dRdXDiag[c1];
         const X xB = this->_x[c0];
         const X xc1mxB = this->_x[c1]-xB;
         this->_x[c1] = xB;
         // eliminate boundary dependency from cell equation
         this->_dRdXDiag[c0] += dFluxdXC1;
         this->_r[c0] -= dFluxdXC1*xc1mxB;
         this->_assembler.getCoeff01(f) = 0;
         // boundary value equation
         this->_dRdXDiag[c1] = NumTypeTraits<Diag>::getNegativeUnity();
         this->_assembler.getCoeff10(f) = NumTypeTraits<Diag>::getUnity();
         this->_r[c1] = X(0);//xc0mxB;
         this->_dRdX.setBoundary(c1);
         //setup the equation for the boundary flux correction
         this->_flux[f] = X(0);
         this->_rFlux[f] = X(0);
         this->_dFluxdFlux[f] = NumTypeTraits<Diag>::getNegativeUnity();
     }
   }
The documentation for this class was generated from the following file:
GenericBCS.h