Memosa-FVM: MultiFieldReduction Class Reference
MultiFieldReduction Class Reference
#include <MultiFieldReduction.h>
Public Types
typedef map< const Field
*, shared_ptr< ArrayBase > > ArrayMap
Public Member Functions
MultiFieldReduction ()
virtual ~MultiFieldReduction ()
DEFINE_TYPENAME ("MultiFieldReduction")
ArrayBase & operator[] (const Field &)
const ArrayBase & operator[] (const Field &) const
MultiFieldReduction & operator+= (const MultiFieldReduction &ofield)
void addArray (const Field &aIndex, shared_ptr< ArrayBase > a)
bool hasArray (const Field &aIndex) const
shared_ptr< ArrayBase > getArrayPtr (const Field &)
void reduceSum ()
bool operator< (const double tolerance) const
shared_ptr< MultiFieldReduction > operator/ (const MultiFieldReduction &o)
shared_ptr< MultiFieldReduction > normalize (const MultiFieldReduction &o)
shared_ptr< MultiFieldReduction > operator* (const MultiFieldReduction &o)
shared_ptr< MultiFieldReduction > operator- () const
void setMax (const MultiFieldReduction &o)
void limit (const double min, const double max)
void print (ostream &os) const
void sync ()
Private Attributes
ArrayMap _arrays
Detailed Description
Definition at line 11 of file MultiFieldReduction.h.
Member Typedef Documentation
typedef map<const Field*,shared_ptr<ArrayBase> > MultiFieldReduction::ArrayMap
Definition at line 14 of file MultiFieldReduction.h.
Constructor & Destructor Documentation
MultiFieldReduction::MultiFieldReduction ()
Definition at line 15 of file MultiFieldReduction.cpp.
References logCtor.
Referenced by normalize(), operator*(), operator-(), and operator/().
                                         :
   _arrays()
 {
   logCtor();
 }
MultiFieldReduction::~MultiFieldReduction () virtual
Definition at line 21 of file MultiFieldReduction.cpp.
References logDtor.
 {
   logDtor();
 }
Member Function Documentation
void MultiFieldReduction::addArray (const Field & aIndex, shared_ptr< ArrayBase > a)
Definition at line 194 of file MultiFieldReduction.cpp.
References _arrays.
Referenced by operator*().
 {
   _arrays[&i]=a;
 }
MultiFieldReduction::DEFINE_TYPENAME ("MultiFieldReduction")
shared_ptr< ArrayBase > MultiFieldReduction::getArrayPtr (const Field & i)
Definition at line 41 of file MultiFieldReduction.cpp.
References _arrays.
 {
   ArrayMap::const_iterator pos = _arrays.find(&i);
   if (pos != _arrays.end())
   {
       return pos->second;
   }
   ostringstream e;
   e << "MultiFieldReduction::operator[] No array found";
   throw CException(e.str());
 }
bool MultiFieldReduction::hasArray (const Field & aIndex) const
Definition at line 188 of file MultiFieldReduction.cpp.
References _arrays.
 {
   return  _arrays.find(&i) != _arrays.end();
 }
void MultiFieldReduction::limit (const double min, const double max)
Definition at line 157 of file MultiFieldReduction.cpp.
References _arrays.
 {
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       pos.second->limit(min,max);
   }
 }
MFRPtr MultiFieldReduction::normalize (const MultiFieldReduction & o)
Definition at line 134 of file MultiFieldReduction.cpp.
References _arrays, MultiFieldReduction(), and ArrayBase::normalize().
 {
   MFRPtr r(new MultiFieldReduction());
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       shared_ptr<ArrayBase> aptr = dynamic_pointer_cast<ArrayBase>(pos.second->newCopy());
       aptr->normalize(o[*pos.first]);
       r->addArray(*pos.first,aptr);
   }
   return r;
 }
MFRPtr MultiFieldReduction::operator* (const MultiFieldReduction & o)
Definition at line 93 of file MultiFieldReduction.cpp.
References _arrays, addArray(), and MultiFieldReduction().
 {
   MFRPtr r(new MultiFieldReduction());
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       shared_ptr<ArrayBase> aptr = dynamic_pointer_cast<ArrayBase>(pos.second->newCopy());
       *aptr *= o[*pos.first];
       r->addArray(*pos.first,aptr);
   }
   return r;
 }
MultiFieldReduction & MultiFieldReduction::operator+= (const MultiFieldReduction & ofield)
Definition at line 69 of file MultiFieldReduction.cpp.
References _arrays, and operator[]().
 {
   for(ArrayMap::const_iterator pos=_arrays.begin();
       pos!=_arrays.end();
       ++pos)
   {
       ArrayBase& myArray = operator[](*pos->first);
       const ArrayBase& oArray = ofield[*pos->first];
       myArray += oArray;
   }
   return *this;
 }
MFRPtr MultiFieldReduction::operator- () const
Definition at line 121 of file MultiFieldReduction.cpp.
References _arrays, and MultiFieldReduction().
 {
   MFRPtr r(new MultiFieldReduction());
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       shared_ptr<ArrayBase> aptr = -(*pos.second);
       r->addArray(*pos.first,aptr);
   }
   return r;
 }
MFRPtr MultiFieldReduction::operator/ (const MultiFieldReduction & o)
Definition at line 107 of file MultiFieldReduction.cpp.
References _arrays, MultiFieldReduction(), and ArrayBase::safeDivide().
 {
   MFRPtr r(new MultiFieldReduction());
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       shared_ptr<ArrayBase> aptr = dynamic_pointer_cast<ArrayBase>(pos.second->newCopy());
       aptr->safeDivide(o[*pos.first]);
       r->addArray(*pos.first,aptr);
   }
   return r;
 }
bool MultiFieldReduction::operator< (const double tolerance) const
Definition at line 83 of file MultiFieldReduction.cpp.
References _arrays.
 {
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       if (! (*pos.second < tolerance)) return false;
   }
   return true;
 }
ArrayBase & MultiFieldReduction::operator[] (const Field & i)
Definition at line 27 of file MultiFieldReduction.cpp.
References _arrays.
Referenced by operator+=().
 {
   ArrayMap::const_iterator pos = _arrays.find(&i);
   if (pos != _arrays.end())
   {
       return *pos->second;
   }
   ostringstream e;
   e << "MultiFieldReduction::operator[] No array found";
   throw CException(e.str());
 }
const ArrayBase & MultiFieldReduction::operator[] (const Field & i) const
Definition at line 55 of file MultiFieldReduction.cpp.
References _arrays.
 {
   ArrayMap::const_iterator pos = _arrays.find(&i);
   if (pos != _arrays.end())
   {
       return *pos->second;
   }
   ostringstream e;
   e << "MultiFieldReduction::operator[] No array found";
   throw CException(e.str());
 }
void MultiFieldReduction::print (ostream & os) const
Definition at line 200 of file MultiFieldReduction.cpp.
References _arrays.
Referenced by operator<<().
 {
   os << "[";
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       os << pos.first->getName() << " : ";
       pos.second->print(os);
   }
   os << "]";
 }
void MultiFieldReduction::reduceSum ()
Definition at line 166 of file MultiFieldReduction.cpp.
References _arrays.
 {
   shared_ptr<ArrayBase> sum;
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       shared_ptr<ArrayBase> thisSum = pos.second->reduceSum();
       if (sum)
         *sum += *thisSum;
       else
         sum = thisSum;
   }
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       pos.second->setSum(*sum);
   }
 }
void MultiFieldReduction::setMax (const MultiFieldReduction & o)
Definition at line 148 of file MultiFieldReduction.cpp.
References _arrays.
 {
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       pos.second->setMax(o[*pos.first]);
   }
 }
void MultiFieldReduction::sync ()
Definition at line 214 of file MultiFieldReduction.cpp.
References _arrays, ArrayBase::getData(), and ArrayBase::getDataSize().
 {
 #ifdef FVM_PARALLEL
    ArrayMap::const_iterator it;
    for ( it = _arrays.begin(); it != _arrays.end(); it++ ){
          ArrayBase&  myArray = *(it->second);
          int count = myArray.getDataSize() / sizeof(double);
          MPI::COMM_WORLD.Allreduce( MPI::IN_PLACE, myArray.getData(), count, MPI::DOUBLE, MPI::SUM);
    }
 #endif
 }
Member Data Documentation
ArrayMap MultiFieldReduction::_arrays private
Definition at line 46 of file MultiFieldReduction.h.
Referenced by addArray(), getArrayPtr(), hasArray(), limit(), normalize(), operator*(), operator+=(), operator-(), operator/(), operator<(), operator[](), print(), reduceSum(), setMax(), and sync().
The documentation for this class was generated from the following files:
MultiFieldReduction.h
MultiFieldReduction.cpp