Memosa-FVM: Vector< T, N > Class Template Reference
Vector< T, N > Class Template Reference
#include <Vector.h>
Public Types
enum { Length = N }
typedef Vector< T, N > This_T
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef NumTypeTraits< T >
::T_BuiltIn T_BuiltIn
typedef Vector< T_BuiltIn, N > VBuiltIn
typedef T T_NumType
Public Member Functions
Vector ()
Vector (const Vector &o)
void * getData ()
T & operator[] (int n)
const T & operator[] (int n) const
void printFromC (ostream &os) const
Vector & operator= (const T &o)
Vector & operator= (const Vector &o)
Vector operator- ()
Vector & operator+= (const Vector &o)
Vector & operator-= (const Vector &o)
Vector & operator/= (const T s)
Vector & operator/= (const Vector &o)
Vector & operator*= (const T s)
Vector & operator*= (const Vector &o)
void zero ()
T mag2 () const
bool operator< (const double tolerance) const
bool greaterThanElementwise (const Vector &y) const
Static Public Member Functions
static string getTypeName ()
static int getDimension ()
static void getShape (int *shp)
static int getDataSize ()
static void write (FILE *fp, const Vector &x)
static Vector getZero ()
static void accumulateOneNorm (Vector &sum, const Vector &v)
static void accumulateDotProduct (Vector &sum, const Vector &v0, const Vector &v1)
static void reduceSum (T_Scalar &sum, const This_T &x)
static void safeDivide (Vector &x, const Vector &y)
static void normalize (Vector &x, const Vector &y)
static void setMax (Vector &x, const Vector &y)
Private Attributes
T _data [N]
Detailed Description
template<class T, int N>
class Vector< T, N >
Definition at line 19 of file Vector.h.
Member Typedef Documentation
template<class T, int N> typedef NumTypeTraits<T>::T_BuiltIn Vector< T, N >::T_BuiltIn
Definition at line 25 of file Vector.h.
template<class T, int N> typedef T Vector< T, N >::T_NumType
Definition at line 28 of file Vector.h.
template<class T, int N> typedef NumTypeTraits<T>::T_Scalar Vector< T, N >::T_Scalar
Definition at line 24 of file Vector.h.
template<class T, int N> typedef Vector<T,N> Vector< T, N >::This_T
Definition at line 22 of file Vector.h.
template<class T, int N> typedef Vector<T_BuiltIn,N> Vector< T, N >::VBuiltIn
Definition at line 26 of file Vector.h.
Member Enumeration Documentation
template<class T, int N> anonymous enum
Enumerator
Length
Definition at line 30 of file Vector.h.
 {Length = N};
Constructor & Destructor Documentation
template<class T, int N> Vector< T, N >::Vector () inline
Definition at line 33 of file Vector.h.
 {}
template<class T, int N> Vector< T, N >::Vector (const Vector< T, N > & o) inline
Definition at line 35 of file Vector.h.
   {
     for(int i=0;i<N;i++)
       _data[i] = o[i];
   }
Member Function Documentation
template<class T, int N> static void Vector< T, N >::accumulateDotProduct (Vector< T, N > & sum, const Vector< T, N > & v0, const Vector< T, N > & v1) inline static
Definition at line 195 of file Vector.h.
Referenced by VectorTranspose< X, K >::accumulateDotProduct().
   {
     for(int i=0; i<N; i++)
       sum[i]+=v0[i]*v1[i];
   }
template<class T, int N> static void Vector< T, N >::accumulateOneNorm (Vector< T, N > & sum, const Vector< T, N > & v) inline static
Definition at line 189 of file Vector.h.
Referenced by VectorTranspose< X, K >::accumulateOneNorm().
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::accumulateOneNorm(sum[i],v[i]);
   }
template<class T, int N> void* Vector< T, N >::getData () inline
Definition at line 51 of file Vector.h.
Referenced by FlowModel< T >::Impl::getPressureIntegralonIBFaces().
   {
      return _data;
   }
template<class T, int N> static int Vector< T, N >::getDataSize () inline static
Definition at line 55 of file Vector.h.
   {
     return N*NumTypeTraits<T>::getDataSize();
   }
template<class T, int N> static int Vector< T, N >::getDimension () inline static
Definition at line 47 of file Vector.h.
 {return NumTypeTraits<T>::getDimension()+1;}
template<class T, int N> static void Vector< T, N >::getShape (int * shp) inline static
Definition at line 49 of file Vector.h.
 { *shp = N; NumTypeTraits<T>::getShape(shp+1);}
template<class T, int N> static string Vector< T, N >::getTypeName () inline static
Definition at line 41 of file Vector.h.
   {
     return "Vector<" + NumTypeTraits<T>::getTypeName() +
       "," + intAsString(N) +
       ">";
   }
template<class T, int N> static Vector Vector< T, N >::getZero () inline static
Definition at line 182 of file Vector.h.
   {
     Vector z;
     z.zero();
     return z;
   }
template<class T, int N> bool Vector< T, N >::greaterThanElementwise (const Vector< T, N > & y) const inline
Definition at line 174 of file Vector.h.
   {
     for(int i=0; i<N; i++)
       if (_data[i] <= y[i])
         return false;
     return true;
   }
template<class T, int N> T Vector< T, N >::mag2 () const inline
Definition at line 161 of file Vector.h.
Referenced by Vector< int, 2 >::normalize(), Vector< int, 2 >::operator<(), and Vector< int, 2 >::setMax().
   {
     T r(NumTypeTraits<T>::getZero());
     for(int i=0; i<N; i++)
       r+=_data[i]*_data[i];
     return r;
   }
template<class T, int N> static void Vector< T, N >::normalize (Vector< T, N > & x, const Vector< T, N > & y) inline static
Definition at line 213 of file Vector.h.
Referenced by VectorTranspose< X, K >::normalize().
   {
     const T ymag = sqrt(y.mag2());
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::safeDivide(x[i],ymag);
   }
template<class T, int N> Vector& Vector< T, N >::operator*= (const T s) inline
Definition at line 141 of file Vector.h.
   {
     for(int i=0;i<N;i++)
       _data[i] *= s;
     return *this;
   }
template<class T, int N> Vector& Vector< T, N >::operator*= (const Vector< T, N > & o) inline
Definition at line 149 of file Vector.h.
   {
     for(int i=0;i<N;i++)
       _data[i] *= o[i];
     return *this;
   }
template<class T, int N> Vector& Vector< T, N >::operator+= (const Vector< T, N > & o) inline
Definition at line 112 of file Vector.h.
   {
     for(int i=0;i<N;i++)
       _data[i] += o[i];
     return *this;
   }
template<class T, int N> Vector Vector< T, N >::operator- () inline
Definition at line 104 of file Vector.h.
   {
     Vector r;
     for(int i=0;i<N;i++)
       r[i]=-_data[i];
     return r;
   }
template<class T, int N> Vector& Vector< T, N >::operator-= (const Vector< T, N > & o) inline
Definition at line 119 of file Vector.h.
   {
     for(int i=0;i<N;i++)
       _data[i] -= o[i];
     return *this;
   }
template<class T, int N> Vector& Vector< T, N >::operator/= (const T s) inline
Definition at line 126 of file Vector.h.
   {
     for(int i=0;i<N;i++)
       _data[i] /= s;
     return *this;
   }
template<class T, int N> Vector& Vector< T, N >::operator/= (const Vector< T, N > & o) inline
Definition at line 134 of file Vector.h.
   {
     for(int i=0;i<N;i++)
       _data[i] /= o[i];
     return *this;
   }
template<class T, int N> bool Vector< T, N >::operator< (const double tolerance) const inline
Definition at line 169 of file Vector.h.
   {
     return mag2() < tolerance*tolerance;
   }
template<class T, int N> Vector& Vector< T, N >::operator= (const T & o) inline
Definition at line 81 of file Vector.h.
   {
     for(int i=0;i<N;i++)
       _data[i] = o;
     return *this;
   }
template<class T, int N> Vector& Vector< T, N >::operator= (const Vector< T, N > & o) inline
Definition at line 97 of file Vector.h.
   {
     for(int i=0;i<N;i++)
       _data[i] = o[i];
     return *this;
   }
template<class T, int N> T& Vector< T, N >::operator[] (int n) inline
Definition at line 60 of file Vector.h.
 {return _data[n];}
template<class T, int N> const T& Vector< T, N >::operator[] (int n) const inline
Definition at line 61 of file Vector.h.
 {return _data[n];}
template<class T, int N> void Vector< T, N >::printFromC (ostream & os) const inline
Definition at line 63 of file Vector.h.
Referenced by operator<<().
   {
     os << "[ " ;
     os << scientific;
     for(int i=0;i<N;i++)
       os << _data[i] << " " ;
     os << "]";
   }
template<class T, int N> static void Vector< T, N >::reduceSum (T_Scalar & sum, const This_T & x) inline static
Definition at line 201 of file Vector.h.
Referenced by VectorTranspose< X, K >::reduceSum().
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::reduceSum(sum,x[i]);
   }
template<class T, int N> static void Vector< T, N >::safeDivide (Vector< T, N > & x, const Vector< T, N > & y) inline static
Definition at line 207 of file Vector.h.
Referenced by VectorTranspose< X, K >::safeDivide().
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::safeDivide(x[i],y[i]);
   }
template<class T, int N> static void Vector< T, N >::setMax (Vector< T, N > & x, const Vector< T, N > & y) inline static
Definition at line 221 of file Vector.h.
Referenced by VectorTranspose< X, K >::setMax().
   {
     if (x.mag2() < y.mag2())
       for(int i=0; i<N; i++)
         x[i]=y[i];
   }
template<class T, int N> static void Vector< T, N >::write (FILE * fp, const Vector< T, N > & x) inline static
Definition at line 72 of file Vector.h.
   {
     for(int i=0; i<N; i++)
     {
         NumTypeTraits<T>::write(fp,x[i]);
         fprintf(fp, " ");
     }
   }
template<class T, int N> void Vector< T, N >::zero () inline
Definition at line 156 of file Vector.h.
Referenced by ArrowHeadMatrix< X, K >::ArrowHeadMatrix(), Vector< int, 2 >::getZero(), COMETModel< T >::init(), and COMETDiscretizer< T >::updateeShifted().
   {
     for(int i=0;i<N;i++) _data[i] = NumTypeTraits<T>::getZero();
   }
Member Data Documentation
template<class T, int N> T Vector< T, N >::_data[N] private
Definition at line 229 of file Vector.h.
Referenced by Vector< int, 2 >::getData(), Vector< int, 2 >::greaterThanElementwise(), Vector< int, 2 >::mag2(), Vector< int, 2 >::operator*=(), Vector< int, 2 >::operator+=(), Vector< int, 2 >::operator-(), Vector< int, 2 >::operator-=(), Vector< int, 2 >::operator/=(), Vector< int, 2 >::operator=(), Vector< int, 2 >::operator[](), Vector< int, 2 >::printFromC(), and Vector< int, 2 >::Vector().
The documentation for this class was generated from the following file:
Vector.h