Memosa-FVM: CollisionTermDiscretization< X, Diag, OffDiag > Class Template Reference
CollisionTermDiscretization< X, Diag, OffDiag > Class Template Reference
#include <CollisionTermDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
Public Member Functions
CollisionTermDiscretization (const MeshList &meshes, const GeomFields &geomFields, const Field &varField, const Field &sourceField, const Field &collisionFrequency)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const Field & _sourceField
const Field & _collisionFrequency
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class CollisionTermDiscretization< X, Diag, OffDiag >
Definition at line 19 of file CollisionTermDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler CollisionTermDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 27 of file CollisionTermDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> CollisionTermDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 25 of file CollisionTermDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray CollisionTermDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 26 of file CollisionTermDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar CollisionTermDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 23 of file CollisionTermDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> CollisionTermDiscretization< X, Diag, OffDiag >::TArray
Definition at line 30 of file CollisionTermDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> CollisionTermDiscretization< X, Diag, OffDiag >::XArray
Definition at line 29 of file CollisionTermDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > CollisionTermDiscretization< X, Diag, OffDiag >::CollisionTermDiscretization (const MeshList & meshes, const GeomFields & geomFields, const Field & varField, const Field & sourceField, const Field & collisionFrequency) inline
Definition at line 32 of file CollisionTermDiscretization.h.
                                                          :
     Discretization(meshes),
     _geomFields(geomFields),
     _varField(varField),
       _sourceField(sourceField),
       _collisionFrequency(collisionFrequency)
    {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void CollisionTermDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & , MultiField & rField) inline virtual
Implements Discretization.
Definition at line 45 of file CollisionTermDiscretization.h.
References CollisionTermDiscretization< X, Diag, OffDiag >::_collisionFrequency, CollisionTermDiscretization< X, Diag, OffDiag >::_geomFields, CollisionTermDiscretization< X, Diag, OffDiag >::_sourceField, CollisionTermDiscretization< X, Diag, OffDiag >::_varField, Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), MultiFieldMatrix::getMatrix(), StorageSite::getSelfCount(), and GeomFields::volume.
   {
     const StorageSite& cells = mesh.getCells();
     const TArray& cellVolume = dynamic_cast<const TArray&>(_geomFields.volume[cells]);
     const XArray& source = dynamic_cast<const XArray&>(_sourceField[cells]);
     const MultiField::ArrayIndex cVarIndex(&_varField, &cells);
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     DiagArray& diag = matrix.getDiag();
     const XArray& x = dynamic_cast<const XArray&>(_varField[cells]);
     TArray& rCell = dynamic_cast<TArray&>(rField[cVarIndex]);
     const XArray& nue = dynamic_cast<const XArray&>(_collisionFrequency[cells]);
     const int nCells = cells.getSelfCount(); //getSelfCount()
     //cout << nue[0] << " " << nue[100] << " " << nue[50] << endl ;
     for(int c=0; c<nCells; c++)
     {
       rCell[c] -= cellVolume[c]*nue[c]*(x[c]-source[c]);
       diag[c]-=cellVolume[c]*nue[c];
     }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const Field& CollisionTermDiscretization< X, Diag, OffDiag >::_collisionFrequency private
Definition at line 78 of file CollisionTermDiscretization.h.
Referenced by CollisionTermDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& CollisionTermDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 75 of file CollisionTermDiscretization.h.
Referenced by CollisionTermDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& CollisionTermDiscretization< X, Diag, OffDiag >::_sourceField private
Definition at line 77 of file CollisionTermDiscretization.h.
Referenced by CollisionTermDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& CollisionTermDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 76 of file CollisionTermDiscretization.h.
Referenced by CollisionTermDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
CollisionTermDiscretization.h