Memosa-FVM: ConvectionDiscretization_Kmodel< X, Diag, OffDiag > Class Template Reference
ConvectionDiscretization_Kmodel< X, Diag, OffDiag > Class Template Reference
#include <ConvectionDiscretization_Kmodel.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Gradient< X > XGrad
typedef Array< int > IntArray
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Array< XGrad > GradArray
Public Member Functions
ConvectionDiscretization_Kmodel (const MeshList &meshes, const GeomFields &geomFields, Field &varField, const double cx, const double cy, const double cz, bool useCentralDifference)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const double _cx
const double _cy
const double _cz
const bool _useCentralDifference
KineticModelOptions< X > _options
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class ConvectionDiscretization_Kmodel< X, Diag, OffDiag >
Definition at line 18 of file ConvectionDiscretization_Kmodel.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::CCAssembler
Definition at line 25 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::CCMatrix
Definition at line 23 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::DiagArray
Definition at line 24 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef Array<XGrad> ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::GradArray
Definition at line 35 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef Array<int> ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::IntArray
Definition at line 29 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::T_Scalar
Definition at line 21 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::TArray
Definition at line 31 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::VectorT3
Definition at line 32 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::VectorT3Array
Definition at line 33 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef Array<X> ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::XArray
Definition at line 30 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef Gradient<X> ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::XGrad
Definition at line 27 of file ConvectionDiscretization_Kmodel.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::ConvectionDiscretization_Kmodel (const MeshList & meshes, const GeomFields & geomFields, Field & varField, const double cx, const double cy, const double cz, bool useCentralDifference) inline
Definition at line 37 of file ConvectionDiscretization_Kmodel.h.
                                                              :
     //const bool useCentralDifference=false) :
   Discretization(meshes),
     _geomFields(geomFields),
     _varField(varField),
     _cx(cx),
     _cy(cy),
     _cz(cz),
     _useCentralDifference(useCentralDifference)
   {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 59 of file ConvectionDiscretization_Kmodel.h.
References ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_cx, ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_cy, ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_cz, ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_geomFields, ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_useCentralDifference, ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_varField, GeomFields::area, Mesh::getAllFaceCells(), Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), Mesh::getFaces(), MultiFieldMatrix::getMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), GeomFields::gridFlux, Field::hasArray(), GeomFields::ibType, Mesh::IBTYPE_BOUNDARY, and Mesh::IBTYPE_FLUID.
   {
     const StorageSite& cells = mesh.getCells();
     const StorageSite& faces = mesh.getFaces();
     // should there be some other checks ?
     //if (!_convectingFluxField.hasArray(faces))
     //  return;
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix =
       dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     const CRConnectivity& faceCells = mesh.getAllFaceCells();
     CCAssembler& assembler = matrix.getPairWiseAssembler(faceCells);
     DiagArray& diag = matrix.getDiag();
     const XArray& xCell = dynamic_cast<const XArray&>(xField[cVarIndex]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     //const GradArray& xGradCell = dynamic_cast<GradArray>(_varGradientField[cells]);
     const IntArray& ibType = dynamic_cast<const IntArray&>(_geomFields.ibType[cells]);
     const int nFaces = faces.getCount();
     const VectorT3Array& faceArea = dynamic_cast<const VectorT3Array&>(_geomFields.area[faces]);
     //const X nondim_length=_options["nonDimLt"];
     //const X Lx=_options["nonDimLx"];
     //const X Ly=_options["nonDimLy"];
     //const X Lz=_options["nonDimLz"];
     if (_geomFields.gridFlux.hasArray(faces))
     {
         shared_ptr<TArray> gridFluxPtr(new TArray(nFaces));
         TArray& gridFlux = *gridFluxPtr;
         gridFlux = dynamic_cast<const TArray&>(_geomFields.gridFlux[faces]);
         for(int f=0; f<nFaces; f++)
         {
             const int c0 = faceCells(f,0);
             const int c1 = faceCells(f,1);
             //const T_Scalar faceCFlux = convectingFlux[f] - gridFlux[f];
             const T_Scalar faceCFlux = faceArea[f][0]*_cx+faceArea[f][1]*_cy+faceArea[f][2]*_cz - gridFlux[f];
             //const T_Scalar faceCFlux = faceArea[f][0]*_cx*nondim_length/Lx+faceArea[f][1]*_cy*nondim_length/Ly+faceArea[f][2]*_cz*nondim_length/Lz - gridFlux[f];
             X varFlux;
             if (faceCFlux > T_Scalar(0))
             {
                 varFlux = faceCFlux*xCell[c0];
                 diag[c0] -= faceCFlux;
                 assembler.getCoeff10(f) += faceCFlux;
             }
             else
             {
                 varFlux = faceCFlux*xCell[c1];
                 diag[c1] += faceCFlux;
                 assembler.getCoeff01(f)-= faceCFlux;
             }
             rCell[c0] -= varFlux;
             rCell[c1] += varFlux;
         }
     }
     else
     {
       if (_useCentralDifference){
         for(int f=0; f<nFaces; f++)
           {
               const int c0 = faceCells(f,0);
               const int c1 = faceCells(f,1);
               const T_Scalar faceCFlux = faceArea[f][0]*_cx+faceArea[f][1]*_cy+faceArea[f][2]*_cz;
               //const T_Scalar faceCFlux = faceArea[f][0]*_cx*nondim_length/Lx+faceArea[f][1]*_cy*nondim_length/Ly+faceArea[f][2]*_cz*nondim_length/Lz;
               bool isIBFace = (((ibType[c0] == Mesh::IBTYPE_FLUID)
                                 && (ibType[c1] == Mesh::IBTYPE_BOUNDARY)) ||
                                ((ibType[c1] == Mesh::IBTYPE_FLUID)
                                 && (ibType[c0] == Mesh::IBTYPE_BOUNDARY)));
               X varFlux =0.5*faceCFlux*(xCell[c0] + xCell[c1]);
               rCell[c0] -= varFlux;
               rCell[c1] += varFlux;
               if (isIBFace)
               {
                   // linearize the actual flux as calculated
                   // above. this will ensure that the Ib
                   // discretization will be able to fix the value
                   // correctly using the ib face value
                   diag[c0] -= 0.5*faceCFlux;
                   assembler.getCoeff10(f) -= 0.5*faceCFlux;
                   diag[c1] += 0.5*faceCFlux;
                   assembler.getCoeff01(f) += 0.5*faceCFlux;
               }
               else
               {
                   // linearize as upwind flux so that linear system
                   // remains diagonally dominant
                   if (faceCFlux > T_Scalar(0))
                   {
                       diag[c0] -= faceCFlux;
                       assembler.getCoeff10(f) += faceCFlux;
                   }
                   else
                   {
                       diag[c1] += faceCFlux;
                       assembler.getCoeff01(f)-= faceCFlux;
                   }
               }
           }
        }
        else
           for(int f=0; f<nFaces; f++)
           {
               const int c0 = faceCells(f,0);
               const int c1 = faceCells(f,1);
               const T_Scalar faceCFlux = faceArea[f][0]*_cx+faceArea[f][1]*_cy+faceArea[f][2]*_cz;
               //const T_Scalar faceCFlux = faceArea[f][0]*_cx*nondim_length/Lx+faceArea[f][1]*_cy*nondim_length/Ly+faceArea[f][2]*_cz*nondim_length/Lz;
               X varFlux;
               if (faceCFlux > T_Scalar(0))
               {
                   varFlux = faceCFlux*xCell[c0];
                   diag[c0] -= faceCFlux;
                   assembler.getCoeff10(f) += faceCFlux;
               }
               else
               {
                   varFlux = faceCFlux*xCell[c1];
                   diag[c1] += faceCFlux;
                   assembler.getCoeff01(f)-= faceCFlux;
               }
               rCell[c0] -= varFlux;
               rCell[c1] += varFlux;
           }
     }
     //const int nCells = cells.getSelfCount();
     //for(int c=0;c<nCells;c++)
     //{
     //    const T_Scalar cImb = continuityResidual[c];
     //    diag[c] += cImb;
     //}
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const double ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_cx private
Definition at line 216 of file ConvectionDiscretization_Kmodel.h.
Referenced by ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const double ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_cy private
Definition at line 217 of file ConvectionDiscretization_Kmodel.h.
Referenced by ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const double ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_cz private
Definition at line 218 of file ConvectionDiscretization_Kmodel.h.
Referenced by ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_geomFields private
Definition at line 214 of file ConvectionDiscretization_Kmodel.h.
Referenced by ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > KineticModelOptions<X> ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_options private
Definition at line 220 of file ConvectionDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > const bool ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_useCentralDifference private
Definition at line 219 of file ConvectionDiscretization_Kmodel.h.
Referenced by ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::_varField private
Definition at line 215 of file ConvectionDiscretization_Kmodel.h.
Referenced by ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
ConvectionDiscretization_Kmodel.h