Memosa-FVM: GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > > Class Template Reference
GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > > Class Template Reference
#include <GenericBCS.h>
Public Types
typedef BaseGenericBCS< Vector
< T, N >, DiagonalTensor< T, N >
, DiagonalTensor< T, N > > T_Parent
typedef Vector< T, N > X
typedef DiagonalTensor< T, N > Diag
typedef DiagonalTensor< T, N > OffDiag
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef FluxJacobianMatrix
< OffDiag, X > FMatrix
typedef DiagonalMatrix< Diag, X > BBMatrix
typedef Array< Diag > DiagArray
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
typedef Array< VectorT3 > VectorT3Array
Public Types inherited from BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >
typedef NumTypeTraits< Vector
< T, N > >::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Array< int > IntArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef CRMatrix
< DiagonalTensor< T, N >
, DiagonalTensor< T, N >
, Vector< T, N > > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef FluxJacobianMatrix
< DiagonalTensor< T, N >
, Vector< T, N > > FMatrix
typedef DiagonalMatrix
< DiagonalTensor< T, N >
, Vector< T, N > > BBMatrix
typedef Array< DiagonalTensor
< T, N > > DiagArray
typedef Array< DiagonalTensor
< T, N > > OffDiagArray
typedef Array< Vector< T, N > > XArray
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
GenericBCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, Field &fluxField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
void applySymmetryBC () const
Public Member Functions inherited from BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >
BaseGenericBCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, Field &fluxField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
void applyDirichletBC (int f, const Vector< T, N > &bValue) const
void applyDirichletBC (const Vector< T, N > &bValue) const
void applyDirichletBC (const FloatValEvaluator< Vector< T, N > > &bValue) const
void applyNeumannBC (const int f, const Vector< T, N > &specifiedFlux) const
void applyNeumannBC (const Vector< T, N > &bFlux) const
void applyNeumannBC (const FloatValEvaluator< Vector< T, N > > &bFlux) const
void applyExtrapolationBC () const
void applyExtrapolationBC (const int f) const
void applyConvectionBC (const int f, const Vector< T, N > &hCoeff, const Vector< T, N > &Xinf) const
void applyConvectionBC (const Vector< T, N > &hCoeff, const Vector< T, N > &Xinf) const
void applyRadiationBC (const int f, const Vector< T, N > &emissivity, const Vector< T, N > &Xinf) const
void applyMixedBC (const int f, const Vector< T, N > &hCoeff, const Vector< T, N > &emissivity, const Vector< T, N > &Xinf) const
void applyInterfaceBC (const int f) const
void applyInterfaceBC () const
void applyDielectricInterfaceBC (const int f, const Vector< T, N > &hCoeff, const Vector< T, N > &Xinf, const Vector< T, N > &source) const
void applyDielectricInterfaceBC (const Vector< T, N > &hCoeff, const Vector< T, N > &Xinf, const Vector< T, N > &source) const
void applyFlowBC (const TArray &convFlux, const Vector< T, N > &bValue) const
void applyNonzeroDiagBC () const
void applyNonzeroDiagBC (int f) const
Additional Inherited Members
Protected Attributes inherited from BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >
const StorageSite & _faces
const StorageSite & _cells
const IntArray & _ibType
const CRConnectivity & _faceCells
const Field & _varField
const Field & _fluxField
const MultiField::ArrayIndex _xIndex
const MultiField::ArrayIndex _fluxIndex
CCMatrix & _dRdX
FMatrix & _dFluxdX
BBMatrix & _dFluxdFlux
CCAssembler & _assembler
DiagArray & _dRdXDiag
XArray & _x
XArray & _r
XArray & _flux
XArray & _rFlux
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
const bool _is2D
Detailed Description
template<class T, int N>
class GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >
Definition at line 620 of file GenericBCS.h.
Member Typedef Documentation
template<class T , int N> typedef DiagonalMatrix<Diag,X> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::BBMatrix
Definition at line 638 of file GenericBCS.h.
template<class T , int N> typedef CCMatrix::PairWiseAssembler GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::CCAssembler
Definition at line 635 of file GenericBCS.h.
template<class T , int N> typedef CRMatrix<Diag,OffDiag,X> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::CCMatrix
Definition at line 634 of file GenericBCS.h.
template<class T , int N> typedef DiagonalTensor<T,N> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::Diag
Definition at line 626 of file GenericBCS.h.
template<class T , int N> typedef Array<Diag> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::DiagArray
Definition at line 640 of file GenericBCS.h.
template<class T , int N> typedef FluxJacobianMatrix<OffDiag,X> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::FMatrix
Definition at line 637 of file GenericBCS.h.
template<class T , int N> typedef DiagonalTensor<T,N> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::OffDiag
Definition at line 627 of file GenericBCS.h.
template<class T , int N> typedef Array<OffDiag> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::OffDiagArray
Definition at line 641 of file GenericBCS.h.
template<class T , int N> typedef BaseGenericBCS<Vector<T,N>, DiagonalTensor<T,N>, DiagonalTensor<T,N> > GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::T_Parent
Definition at line 624 of file GenericBCS.h.
template<class T , int N> typedef NumTypeTraits<X>::T_Scalar GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::T_Scalar
Definition at line 629 of file GenericBCS.h.
template<class T , int N> typedef Array<T_Scalar> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::TArray
Definition at line 631 of file GenericBCS.h.
template<class T , int N> typedef Vector<T_Scalar,3> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::VectorT3
Definition at line 632 of file GenericBCS.h.
template<class T , int N> typedef Array<VectorT3> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::VectorT3Array
Definition at line 644 of file GenericBCS.h.
template<class T , int N> typedef Vector<T,N> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::X
Definition at line 625 of file GenericBCS.h.
template<class T , int N> typedef Array<X> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::XArray
Definition at line 643 of file GenericBCS.h.
Constructor & Destructor Documentation
template<class T , int N> GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::GenericBCS (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, Field & varField, Field & fluxField, MultiFieldMatrix & matrix, MultiField & xField, MultiField & rField) inline
Definition at line 647 of file GenericBCS.h.
                                                      :
     T_Parent(faces,mesh,geomFields,varField,fluxField,matrix,xField,rField)
   {}
Member Function Documentation
template<class T , int N> void GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::applySymmetryBC () const inline
Definition at line 658 of file GenericBCS.h.
References BaseGenericBCS< X, Diag, OffDiag >::_assembler, BaseGenericBCS< X, Diag, OffDiag >::_dFluxdFlux, BaseGenericBCS< X, Diag, OffDiag >::_dFluxdX, BaseGenericBCS< X, Diag, OffDiag >::_dRdX, BaseGenericBCS< X, Diag, OffDiag >::_dRdXDiag, BaseGenericBCS< X, Diag, OffDiag >::_faceArea, BaseGenericBCS< X, Diag, OffDiag >::_faceAreaMag, BaseGenericBCS< X, Diag, OffDiag >::_faceCells, BaseGenericBCS< X, Diag, OffDiag >::_faces, BaseGenericBCS< X, Diag, OffDiag >::_r, BaseGenericBCS< X, Diag, OffDiag >::_x, dot(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), CRMatrix< T_Diag, T_OffDiag, X >::setBoundary(), FluxJacobianMatrix< OffDiag, X >::setCoeffL(), and FluxJacobianMatrix< OffDiag, X >::setCoeffR().
   {
     for(int f=0; f<this->_faces.getCount(); f++)
     {
         const int c0 = this->_faceCells(f,0);
         const int c1 = this->_faceCells(f,1);
         // the current value of flux and its Jacobians
         const X fluxB = -this->_r[c1];
         const OffDiag dFluxdXC0 = -this->_assembler.getCoeff10(f);
         const Diag dFluxdXC1 = -this->_dRdXDiag[c1];
         const OffDiag dRC0dXC1 = this->_assembler.getCoeff01(f);
         const VectorT3 en = this->_faceArea[f]/this->_faceAreaMag[f];
         const T xC0_dotn = dot(this->_x[c0],en);
         const X xB = this->_x[c0] - 2.0*xC0_dotn * en;
         const X dXC1 = xB-this->_x[c1];
         const X dFlux = dFluxdXC1*dXC1;
         this->_x[c1] = xB;
         // eliminate boundary dependency from cell equation
         this->_r[c0] += dRC0dXC1*dXC1;
         this->_assembler.getCoeff01(f) = 0;
         // boundary value equation
         this->_dRdXDiag[c1] = this->_dRdXDiag[c0];
         this->_assembler.getCoeff10(f) = 0;
         this->_r[c1] = T(0);
         this->_dRdX.setBoundary(c1);
         this->_dFluxdX.setCoeffL(f,dFluxdXC0);
         this->_dFluxdX.setCoeffR(f,dFluxdXC1);
         this->_dFluxdFlux[f] = NumTypeTraits<Diag>::getNegativeUnity();
     }
   }
The documentation for this class was generated from the following file:
GenericBCS.h