Memosa-FVM: IdealGasDensityModel< T >::Impl Class Reference
IdealGasDensityModel< T >::Impl Class Reference
#include <IdealGasDensityModel_impl.h>
Public Types
typedef Array< T > TArray
Public Member Functions
Impl (const GeomFields &geomFields, FlowFields &flowFields, const MeshList &meshes)
VCMap & getVCMap ()
void init ()
bool advance (const int niter, bool init=false)
Private Attributes
const MeshList _meshes
const GeomFields & _geomFields
FlowFields & _flowFields
VCMap _vcMap
Detailed Description
template<class T>
class IdealGasDensityModel< T >::Impl
Definition at line 13 of file IdealGasDensityModel_impl.h.
Member Typedef Documentation
template<class T> typedef Array<T> IdealGasDensityModel< T >::Impl::TArray
Definition at line 16 of file IdealGasDensityModel_impl.h.
Constructor & Destructor Documentation
template<class T> IdealGasDensityModel< T >::Impl::Impl (const GeomFields & geomFields, FlowFields & flowFields, const MeshList & meshes) inline
Definition at line 18 of file IdealGasDensityModel_impl.h.
References Model::_meshes, and Mesh::getID().
                                :
     _meshes(meshes),
     _geomFields(geomFields),
     _flowFields(flowFields)
   {
     const int numMeshes = _meshes.size();
     for (int n=0; n<numMeshes; n++)
     {
         const Mesh& mesh = *_meshes[n];
         IdealGasVC<T> *vc(new IdealGasVC<T>());
         _vcMap[mesh.getID()] = vc;
     }
   }
Member Function Documentation
template<class T> bool IdealGasDensityModel< T >::Impl::advance (const int niter, bool init = false) inline
Definition at line 39 of file IdealGasDensityModel_impl.h.
References Model::_meshes, Mesh::getCells(), StorageSite::getCount(), Mesh::getID(), FloatVarDict< T >::getVal(), and IdealGasDensityModel< T >::init().
   {
     const int numMeshes = _meshes.size();
     for (int n=0; n<numMeshes; n++)
     {
         const Mesh& mesh = *_meshes[n];
         const IdealGasVC<T>& vc = *_vcMap[mesh.getID()];
         const StorageSite& cells = mesh.getCells();
         TArray& density = dynamic_cast<TArray&>(_flowFields.density[cells]);
         FloatValEvaluator<T>  cellP(vc.getVal("pressure"),cells);
         FloatValEvaluator<T>  cellT(vc.getVal("temperature"),cells);
         const T operatingPressure = vc["operatingPressure"];
         const T molWt = vc["molecularWeight"];
         const T Rgas = 8314.472/molWt;
         const int nCells = cells.getCount();
         const T pMin(1000);
         const T TMin(1);
         const T urf = init ? T(1) : T(vc["urf"]);
         for(int c=0; c<nCells; c++)
         {
             T absP = (cellP[c] + operatingPressure);
             T temp = cellT[c];
             if (absP < pMin) absP  = pMin;
             if (temp < TMin) temp  = TMin;
             if (init)
               density[c] = absP/(Rgas*temp);
             else
               density[c] = urf*absP/(Rgas*temp) + (1.0-urf)*density[c];
         }
     }
     return true;
   }
template<class T> VCMap& IdealGasDensityModel< T >::Impl::getVCMap () inline
Definition at line 35 of file IdealGasDensityModel_impl.h.
 {return _vcMap;}
template<class T> void IdealGasDensityModel< T >::Impl::init () inline
Definition at line 37 of file IdealGasDensityModel_impl.h.
References IdealGasDensityModel< T >::advance().
 { advance(1,true); }
Member Data Documentation
template<class T> FlowFields& IdealGasDensityModel< T >::Impl::_flowFields private
Definition at line 85 of file IdealGasDensityModel_impl.h.
template<class T> const GeomFields& IdealGasDensityModel< T >::Impl::_geomFields private
Definition at line 84 of file IdealGasDensityModel_impl.h.
template<class T> const MeshList IdealGasDensityModel< T >::Impl::_meshes private
Definition at line 83 of file IdealGasDensityModel_impl.h.
template<class T> VCMap IdealGasDensityModel< T >::Impl::_vcMap private
Definition at line 87 of file IdealGasDensityModel_impl.h.
The documentation for this class was generated from the following file:
IdealGasDensityModel_impl.h