Memosa-FVM: KineticBoundaryConditions< X, Diag, OffDiag > Class Template Reference
KineticBoundaryConditions< X, Diag, OffDiag > Class Template Reference
#include <KineticBoundaryConditions.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< int > IntArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Array< X > XArray
typedef Vector< X, 3 > VectorX3
typedef Array< VectorX3 > VectorX3Array
typedef StressTensor< X > StressTensorX6
typedef Array< StressTensorX6 > StressTensorArray
Public Member Functions
KineticBoundaryConditions (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, const Quadrature< X > &quadrature, MacroFields &macroFields, DistFunctFields< X > &dsfPtr)
KineticModelOptions< X > & getOptions ()
void applyDiffuseWallBC (int f, const VectorX3 &WallVelocity, const X &WallTemperature) const
void applyDiffuseWallBC (const VectorX3 &bVelocity, const X &bTemperature) const
void applyDiffuseWallBC (const FloatValEvaluator< VectorX3 > &bVelocity, const FloatValEvaluator< X > &bTemperature) const
void applyRealWallBC (int f, const VectorX3 &WallVelocity, const X &WallTemperature, const X &accommodationCoefficient, const vector< int > &vecReflection) const
void applyRealWallBC (const VectorX3 &bVelocity, const X &bTemperature, const X &accomCoeff, const vector< int > &vecReflection) const
void applyRealWallBC (const FloatValEvaluator< VectorX3 > &bVelocity, const FloatValEvaluator< X > &bTemperature, const FloatValEvaluator< X > &accomCoeff, const vector< int > &vecReflection) const
void applySpecularWallBC (int f, const vector< int > &vecReflection) const
void applySpecularWallBC (const vector< int > &vecReflection) const
void applySpecularWallBC_Cartesian (int f) const
void applyZeroGradientBC (int f) const
void applyZeroGradientBC () const
void applyPressureInletBC (int f, const X &inletTemperature, const X &inletPressure) const
void applyPressureInletBC (const FloatValEvaluator< X > &bTemperature, const FloatValEvaluator< X > &bPresssure) const
void applyInletBC (int f, const VectorX3 &InletVelocity, const X &InletTemperature, const X &InletMdot, const vector< int > &vecReflection) const
void applyInletBC (const VectorX3 &bVelocity, const X &bTemperature, const X &Mdot, const vector< int > &vecReflection) const
void applyInletBC (const FloatValEvaluator< VectorX3 > &bVelocity, const FloatValEvaluator< X > &bTemperature, const FloatValEvaluator< X > &Mdot, const vector< int > &vecReflection) const
void applyPressureOutletBC (int f, const X &outletTemperature, const X &outletPressure) const
void applyPressureOutletBC (const X &bTemperature, const X &bPressure) const
void applyPressureOutletBC (const FloatValEvaluator< X > &bTemperature, const FloatValEvaluator< X > &bPresssure) const
void applyNSInterfaceBC () const
void applyNSInterfaceBC (int f) const
Protected Attributes
const StorageSite & _faces
const StorageSite & _cells
const Array< int > & _ibType
const Quadrature< X > & _quadrature
MacroFields & _macroFields
const DistFunctFields< X > & _dsfPtr
const CRConnectivity & _faceCells
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
KineticModelOptions< X > _options
Detailed Description
template<class X, class Diag, class OffDiag>
class KineticBoundaryConditions< X, Diag, OffDiag >
Definition at line 24 of file KineticBoundaryConditions.h.
Member Typedef Documentation
template<class X, class Diag, class OffDiag> typedef Array<int> KineticBoundaryConditions< X, Diag, OffDiag >::IntArray
Definition at line 30 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> typedef Array<StressTensorX6> KineticBoundaryConditions< X, Diag, OffDiag >::StressTensorArray
Definition at line 40 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> typedef StressTensor<X> KineticBoundaryConditions< X, Diag, OffDiag >::StressTensorX6
Definition at line 39 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> typedef NumTypeTraits<X>::T_Scalar KineticBoundaryConditions< X, Diag, OffDiag >::T_Scalar
Definition at line 28 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> typedef Array<T_Scalar> KineticBoundaryConditions< X, Diag, OffDiag >::TArray
Definition at line 32 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> typedef Vector<T_Scalar,3> KineticBoundaryConditions< X, Diag, OffDiag >::VectorT3
Definition at line 33 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> typedef Array<VectorT3> KineticBoundaryConditions< X, Diag, OffDiag >::VectorT3Array
Definition at line 34 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> typedef Vector<X,3> KineticBoundaryConditions< X, Diag, OffDiag >::VectorX3
Definition at line 37 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> typedef Array<VectorX3> KineticBoundaryConditions< X, Diag, OffDiag >::VectorX3Array
Definition at line 38 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> typedef Array<X> KineticBoundaryConditions< X, Diag, OffDiag >::XArray
Definition at line 36 of file KineticBoundaryConditions.h.
Constructor & Destructor Documentation
template<class X, class Diag, class OffDiag> KineticBoundaryConditions< X, Diag, OffDiag >::KineticBoundaryConditions (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, const Quadrature< X > & quadrature, MacroFields & macroFields, DistFunctFields< X > & dsfPtr) inline
Definition at line 43 of file KineticBoundaryConditions.h.
                                                        :
     _faces(faces),
     _cells(mesh.getCells()),
     _ibType(dynamic_cast<const IntArray&>(geomFields.ibType[_cells])),
     _quadrature(quadrature),
     _macroFields(macroFields),
     _dsfPtr(dsfPtr),
     _faceCells(mesh.getFaceCells(_faces)),
     _areaMagField(geomFields.areaMag),
     _faceAreaMag(dynamic_cast<const TArray&>(_areaMagField[_faces])),
     _areaField(geomFields.area),
     _faceArea(dynamic_cast<const VectorT3Array&>(_areaField[_faces]))
   {}
Member Function Documentation
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC (int f, const VectorX3 & WallVelocity, const X & WallTemperature) const inline
changed
Definition at line 65 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_cells, KineticBoundaryConditions< X, Diag, OffDiag >::_dsfPtr, KineticBoundaryConditions< X, Diag, OffDiag >::_faceArea, KineticBoundaryConditions< X, Diag, OffDiag >::_faceAreaMag, KineticBoundaryConditions< X, Diag, OffDiag >::_faceCells, KineticBoundaryConditions< X, Diag, OffDiag >::_ibType, KineticBoundaryConditions< X, Diag, OffDiag >::_macroFields, KineticBoundaryConditions< X, Diag, OffDiag >::_options, KineticBoundaryConditions< X, Diag, OffDiag >::_quadrature, Quadrature< T >::cxPtr, Quadrature< T >::cyPtr, Quadrature< T >::czPtr, Quadrature< T >::dcxyzPtr, MacroFields::density, DistFunctFields< T >::dsf, epsilon, KineticModelOptions< T >::epsilon_ES, Quadrature< T >::getDirCount(), Mesh::IBTYPE_FLUID, KineticModelOptions< T >::pi, MacroFields::temperature, and MacroFields::velocity.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), and KineticModel< T >::callBoundaryConditions().
   {
     const double pi=_options.pi;
     const double epsilon=_options.epsilon_ES;
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     const int numDirections = _quadrature.getDirCount();
     const XArray& cx = dynamic_cast<const XArray&>(*_quadrature.cxPtr);
     const XArray& cy = dynamic_cast<const XArray&>(*_quadrature.cyPtr);
     const XArray& cz = dynamic_cast<const XArray&>(*_quadrature.czPtr);
     const XArray& wts= dynamic_cast<const XArray&>(*_quadrature.dcxyzPtr);
     VectorX3Array& v = dynamic_cast<VectorX3Array&>(_macroFields.velocity[_cells]);
     XArray& density  = dynamic_cast<XArray&>(_macroFields.density[_cells]);
     //XArray& pressure  = dynamic_cast<XArray&>(_macroFields.pressure[_cells]);
     XArray& temperature  = dynamic_cast<XArray&>(_macroFields.temperature[_cells]);
     const X uwall = WallVelocity[0];
     const X vwall = WallVelocity[1];
     const X wwall = WallVelocity[2];
     //cout << "uwall " << uwall << endl;
     const X Twall = WallTemperature;
     v[c1][0]=uwall;
     v[c1][1]=vwall;
     v[c1][2]=wwall;
     temperature[c1]=Twall;
     X Nmr(0.0) ;
     X Dmr(0.0) ;
     X incomFlux(0.0);
     for (int j=0; j<numDirections; j++)
       {
         Field& fnd = *_dsfPtr.dsf[j];
         XArray& dsf = dynamic_cast< XArray&>(fnd[_cells]);
         const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
         const X c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         const X wallV_dot_en = uwall*en[0]+vwall*en[1]+wwall*en[2];
         const X fwall = 1.0/pow(pi*Twall,1.5)*exp(-(pow(cx[j]-uwall,2.0)+pow(cy[j]-vwall,2.0)+pow(cz[j]-wwall,2.0))/Twall);
         if (c_dot_en -wallV_dot_en < T_Scalar(epsilon)) //incoming
           {
             Dmr = Dmr - fwall*wts[j]*(c_dot_en-wallV_dot_en);
             incomFlux=incomFlux-dsf[c0]*wts[j]*(c_dot_en -wallV_dot_en);
           }
         else
           {
             Nmr = Nmr + dsf[c0]*wts[j]*(c_dot_en -wallV_dot_en);
           }
       }
     const X nwall = Nmr/Dmr; // wall number density for initializing Maxwellian
     density[c1]=nwall;
     //if (c0==80)cout <<"incoming" << incomFlux <<" outgoing" <<Nmr <<endl;
     for (int j=0; j<numDirections; j++)
       {
         Field& fnd = *_dsfPtr.dsf[j];
         XArray& dsf = dynamic_cast< XArray&>(fnd[_cells]);
         const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
         const X c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         const X wallV_dot_en = uwall*en[0]+vwall*en[1]+wwall*en[2];
         if (c_dot_en-wallV_dot_en < T_Scalar(epsilon))
           {
             dsf[c1] = nwall/pow(pi*Twall,1.5)*exp(-(pow(cx[j]-uwall,2.0)+pow(cy[j]-vwall,2.0)+pow(cz[j]-wwall,2.0))/Twall);
             //dsf[c0]=dsf[c1];  // change value of fluid boundary-cell
           }
         else
           dsf[c1]=dsf[c0];
       }
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC (const VectorX3 & bVelocity, const X & bTemperature) const inline
Definition at line 143 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
     applyDiffuseWallBC(i,bVelocity,bTemperature);
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC (const FloatValEvaluator< VectorX3 > & bVelocity, const FloatValEvaluator< X > & bTemperature) const inline
Definition at line 150 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyDiffuseWallBC(i,bVelocity[i],bTemperature[i]);
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC (int f, const VectorX3 & InletVelocity, const X & InletTemperature, const X & InletMdot, const vector< int > & vecReflection) const inline
Definition at line 522 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_cells, KineticBoundaryConditions< X, Diag, OffDiag >::_dsfPtr, KineticBoundaryConditions< X, Diag, OffDiag >::_faceArea, KineticBoundaryConditions< X, Diag, OffDiag >::_faceAreaMag, KineticBoundaryConditions< X, Diag, OffDiag >::_faceCells, KineticBoundaryConditions< X, Diag, OffDiag >::_ibType, KineticBoundaryConditions< X, Diag, OffDiag >::_macroFields, KineticBoundaryConditions< X, Diag, OffDiag >::_options, KineticBoundaryConditions< X, Diag, OffDiag >::_quadrature, Quadrature< T >::cxPtr, Quadrature< T >::cyPtr, Quadrature< T >::czPtr, Quadrature< T >::dcxyzPtr, MacroFields::density, DistFunctFields< T >::dsf, Quadrature< T >::getDirCount(), Mesh::IBTYPE_FLUID, KineticModelOptions< T >::pi, MacroFields::temperature, and MacroFields::velocity.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), and KineticModel< T >::callBoundaryConditions().
   {
     const double pi=_options.pi;
     //const double epsilon=_options.epsilon_ES;
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     const int numDirections = _quadrature.getDirCount();
     const XArray& cx = dynamic_cast<const XArray&>(*_quadrature.cxPtr);
     const XArray& cy = dynamic_cast<const XArray&>(*_quadrature.cyPtr);
     const XArray& cz = dynamic_cast<const XArray&>(*_quadrature.czPtr);
     const XArray& wts= dynamic_cast<const XArray&>(*_quadrature.dcxyzPtr);
     VectorX3Array& v = dynamic_cast<VectorX3Array&>(_macroFields.velocity[_cells]);
     XArray& density  = dynamic_cast<XArray&>(_macroFields.density[_cells]);
     XArray& temperature  = dynamic_cast<XArray&>(_macroFields.temperature[_cells]);
     const X uin = InletVelocity[0];
     const X vin = InletVelocity[1];
     const X win = InletVelocity[2];
     const X Tin = InletTemperature;
     const X mdot = InletMdot;
     v[c1][0]=uin;
     v[c1][1]=vin;
     v[c1][2]=win;
     temperature[c1]=Tin;
     X Nmr(0.0) ;
     X Dmr(0.0);
     const X rho_init=_options["rho_init"];
     const X T_init= _options["T_init"];
     const X R=8314.0/_options["molecularWeight"];
     const X u_init=pow(2.0*R*T_init,0.5);
     // find the number density corressponding to the inlet Maxwellian
     for (int j=0; j<numDirections; j++)
       {
         const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
         const X c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         const X fwall = 1.0/pow(pi*Tin,1.5)*exp(-(pow(cx[j]-uin,2.0)+pow(cy[j]-vin,2.0)+pow(cz[j]-win,2.0))/Tin);
         if (c_dot_en < T_Scalar(0.0)){Dmr = Dmr + fwall*wts[j]*c_dot_en;}
         Nmr=mdot/(rho_init*u_init);
       }
     const X nin = Nmr/Dmr; // wall number density for initializing Maxwellian
     density[c1]=nin;
     for (int j=0; j<numDirections; j++)
       {
         Field& fnd = *_dsfPtr.dsf[j];
         XArray& dsf = dynamic_cast< XArray&>(fnd[_cells]);
         const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
         const X c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         if (c_dot_en < T_Scalar(0.0))
           {
             const int direction_incident = vecReflection[j];
             Field& fndi = *_dsfPtr.dsf[direction_incident];
             const XArray& dsfi = dynamic_cast<const XArray&>(fndi[_cells]);
             dsf[c1] = nin/pow(pi*Tin,1.5)*exp(-(pow(cx[j]-uin,2.0)+pow(cy[j]-vin,2.0)+pow(cz[j]-win,2.0))/Tin)+dsfi[c0]; //inlet Maxwellian +reflected
           }
         else
           dsf[c1]=dsf[c0];
       }
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC (const VectorX3 & bVelocity, const X & bTemperature, const X & Mdot, const vector< int > & vecReflection) const inline
Definition at line 593 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyInletBC(i,bVelocity,bTemperature,Mdot,vecReflection);
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC (const FloatValEvaluator< VectorX3 > & bVelocity, const FloatValEvaluator< X > & bTemperature, const FloatValEvaluator< X > & Mdot, const vector< int > & vecReflection) const inline
Definition at line 600 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyInletBC(i,bVelocity[i],bTemperature[i],Mdot[i],vecReflection);
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC () const inline
Definition at line 693 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, and StorageSite::getCount().
Referenced by KineticModel< T >::callBoundaryConditions().
    {
      for (int i=0; i<_faces.getCount();i++)
        applyNSInterfaceBC(i); //,bTemperature[i],bPressure[i],bVelocity[i],bStress[i]);
    }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC (int f) const inline
Definition at line 706 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_cells, KineticBoundaryConditions< X, Diag, OffDiag >::_dsfPtr, KineticBoundaryConditions< X, Diag, OffDiag >::_faceArea, KineticBoundaryConditions< X, Diag, OffDiag >::_faceAreaMag, KineticBoundaryConditions< X, Diag, OffDiag >::_faceCells, KineticBoundaryConditions< X, Diag, OffDiag >::_faces, KineticBoundaryConditions< X, Diag, OffDiag >::_ibType, KineticBoundaryConditions< X, Diag, OffDiag >::_macroFields, KineticBoundaryConditions< X, Diag, OffDiag >::_options, KineticBoundaryConditions< X, Diag, OffDiag >::_quadrature, Quadrature< T >::cxPtr, Quadrature< T >::cyPtr, Quadrature< T >::czPtr, DistFunctFields< T >::dsf, Quadrature< T >::getDirCount(), Mesh::IBTYPE_FLUID, MacroFields::InterfacePressure, MacroFields::InterfaceStress, MacroFields::InterfaceVelocity, KineticModelOptions< T >::pi, MacroFields::temperature, and MacroFields::viscosity.
   {
    const double pi=_options.pi;
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     const int numDirections = _quadrature.getDirCount();
     const XArray& cx = dynamic_cast<const XArray&>(*_quadrature.cxPtr);
     const XArray& cy = dynamic_cast<const XArray&>(*_quadrature.cyPtr);
     const XArray& cz = dynamic_cast<const XArray&>(*_quadrature.czPtr);
     //XArray& density  = dynamic_cast<XArray&>(_macroFields.density[_cells]);
     //XArray& pressure  = dynamic_cast<XArray&>(_macroFields.pressure[_cells]);
     XArray& temperature  = dynamic_cast<XArray&>(_macroFields.temperature[_cells]);
     //VectorX3Array& v = dynamic_cast<VectorX3Array&>(_macroFields.velocity[_cells]);
     XArray& viscosity  = dynamic_cast<XArray&>(_macroFields.viscosity[_cells]);
     VectorX3Array& IntVel = dynamic_cast<VectorX3Array&>(_macroFields.InterfaceVelocity[_faces]);
     XArray& IntPress  = dynamic_cast<XArray&>(_macroFields.InterfacePressure[_faces]);
     //XArray& IntDens  = dynamic_cast<XArray&>(_macroFields.InterfaceDensity[_faces]);
     StressTensorArray& tau  = dynamic_cast<StressTensorArray&>(_macroFields.InterfaceStress[_faces]);
     const X Tin = temperature[c0];
     const X Pin = IntPress[f];
     const X nin = Pin/Tin; // wall number density for initializing Maxwellian
     const X u_in=IntVel[f][0];
     const X v_in=IntVel[f][1];
     const X w_in=IntVel[f][2];
     const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
     // Extra for CE expression
     const X rho_init=_options["rho_init"];
     const X T_init= _options["T_init"];
     const X R=8314.0/_options["molecularWeight"];
     const X nondim_length=_options["nonDimLt"];
     const X mu0=rho_init*R* T_init*nondim_length/pow(2*R* T_init,0.5);
     //update f to Maxwellian
     for (int j=0; j<numDirections; j++)
       {
         Field& fnd = *_dsfPtr.dsf[j];
         XArray& dsf = dynamic_cast< XArray&>(fnd[_cells]);
         //const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
         //const X c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         //if (c_dot_en< T_Scalar(0.0))
           {
             //cout << "nin " <<nin <<endl;
             dsf[c1] = nin/pow(pi*Tin,1.5)*exp(-(pow(cx[j]-u_in,2.0)+pow(cy[j]-v_in,2.0)+pow(cz[j]-w_in,2.0))/Tin)
             *(1-viscosity[c0]/mu0/(nin*pow(Tin,2.0))*(pow(cx[j]-u_in,2.0)*tau[f][0]+pow(cy[j]-v_in,2.0)*tau[f][1]+pow(cz[j]-w_in,2.0)*tau[f][2])
               +2.0*(cx[j]-u_in)*(cy[j]-v_in)*tau[f][3]+2.0*(cy[j]-v_in)*(cz[j]-w_in)*tau[f][4]+2.0*(cz[j]-w_in)*(cx[j]-u_in)*tau[f][5]); //update f to ChapmannEnskog
           }
         //else{dsf[c1]=dsf[c0];}//outgoing
       }
     //update f to ChapmannEnskog
 //dsf[c1]=dsf[c1]*(1-2*cx[j]*cy[j]*slopeL*viscosity[c]/mu0) //velocity tangential only
 //C2=pow(cx[j]-u_in,2.0)+pow(cy[j]-v_in,2.0)+pow(cz[j]-w_in,2.0)
 //dsf[c1]=dsf[c1]*(1+viscosity[c1]/(mu0*Pr*nin*pow(Tin,2.0))*((cx[j]-u_in)*dtbdx+(cy[j]-v_in)*dtbdy+(cz[j]-w_in)*dtbdz)*(C2-2.5))
 //temperature difference too
  }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC (int f, const X & inletTemperature, const X & inletPressure) const inline
Definition at line 408 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_cells, KineticBoundaryConditions< X, Diag, OffDiag >::_dsfPtr, KineticBoundaryConditions< X, Diag, OffDiag >::_faceArea, KineticBoundaryConditions< X, Diag, OffDiag >::_faceAreaMag, KineticBoundaryConditions< X, Diag, OffDiag >::_faceCells, KineticBoundaryConditions< X, Diag, OffDiag >::_ibType, KineticBoundaryConditions< X, Diag, OffDiag >::_macroFields, KineticBoundaryConditions< X, Diag, OffDiag >::_options, KineticBoundaryConditions< X, Diag, OffDiag >::_quadrature, Quadrature< T >::cxPtr, Quadrature< T >::cyPtr, Quadrature< T >::czPtr, Quadrature< T >::dcxyzPtr, MacroFields::density, DistFunctFields< T >::dsf, Quadrature< T >::getDirCount(), Mesh::IBTYPE_FLUID, KineticModelOptions< T >::pi, MacroFields::pressure, MacroFields::temperature, and MacroFields::velocity.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), and KineticModel< T >::callBoundaryConditions().
   {
    const double pi=_options.pi;
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     const int numDirections = _quadrature.getDirCount();
     const XArray& cx = dynamic_cast<const XArray&>(*_quadrature.cxPtr);
     const XArray& cy = dynamic_cast<const XArray&>(*_quadrature.cyPtr);
     const XArray& cz = dynamic_cast<const XArray&>(*_quadrature.czPtr);
     const XArray& wts = dynamic_cast<const XArray&>(*_quadrature.dcxyzPtr);
     XArray& density  = dynamic_cast<XArray&>(_macroFields.density[_cells]);
     XArray& pressure  = dynamic_cast<XArray&>(_macroFields.pressure[_cells]);
     XArray& temperature  = dynamic_cast<XArray&>(_macroFields.temperature[_cells]);
     VectorX3Array& v = dynamic_cast<VectorX3Array&>(_macroFields.velocity[_cells]);
      X uwallnew = 0.0;
     const X Tin = inletTemperature;
     const X Pin = inletPressure;
     const X nin = Pin/Tin; // wall number density for initializing Maxwellian
     //store boundary values
     temperature[c1]=inletTemperature;
     pressure[c1]=inletPressure;
     density[c1]=nin;
     v[c1][0]=0.0;
     v[c1][1]=0.0;
     v[c1][2]=0.0;
     const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
     //update velocity
     for (int j=0; j<numDirections; j++)
       {
         Field& fnd = *_dsfPtr.dsf[j];
         XArray& dsf = dynamic_cast< XArray&>(fnd[_cells]);
         dsf[c1] = nin/pow(pi*Tin,1.5)*exp(-(pow(cx[j]-v[c1][0],2.0)+pow(cy[j]-v[c1][1],2.0)+pow(cz[j]-v[c1][2],2.0))/Tin);
            const X c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
            if (abs(en[0]) == T_Scalar(1.0))
              {
                if( c_dot_en > T_Scalar(0.0))
                  {
                    uwallnew=uwallnew+cx[j]*dsf[c0]*wts[j];
                  }
                else {uwallnew=uwallnew+cx[j]*dsf[c1]*wts[j];}
              }
            else if (abs(en[1]) == T_Scalar(1.0))
              {
                if( c_dot_en > T_Scalar(0.0))
                  {
                    uwallnew=uwallnew+cy[j]*dsf[c0]*wts[j];
                  }
                else {uwallnew=uwallnew+cy[j]*dsf[c1]*wts[j];}
              }
            else if (abs(en[2]) == T_Scalar(1.0))
              {
                if( c_dot_en > T_Scalar(0.0))
                  {
                    uwallnew=uwallnew+cz[j]*dsf[c0]*wts[j];
                  }
                else {uwallnew=uwallnew+cz[j]*dsf[c1]*wts[j];}
              }
       }
     /*
     if (abs(en[0]) == T_Scalar(1.0))
       v[c1][0]=uwallnew/nin;
     else if (abs(en[1]) == T_Scalar(1.0)) //incoming  {vwallnew=vwallnew+cy[j]*dsf[c1]*wts[j];}
       v[c1][1]=uwallnew/nin;
     else if(abs(en[2]) == T_Scalar(1.0))
       v[c1][2]=uwallnew/nin;//uwall=uwall+relax*(uwallnew-uwall);
     */
     //update f
     for (int j=0; j<numDirections; j++)
       {
         Field& fnd = *_dsfPtr.dsf[j];
         XArray& dsf = dynamic_cast< XArray&>(fnd[_cells]);
         const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
         const X c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         if (c_dot_en< T_Scalar(0.0))
           {
             dsf[c1] = nin/pow(pi*Tin,1.5)*exp(-(pow(cx[j]-v[c1][0],2.0)+pow(cy[j]-v[c1][1],2.0)+pow(cz[j]-v[c1][2],2.0))/Tin);
             // dsf[c0]=dsf[c1];// change value of fluid boundary-cell
           }
         else{dsf[c1]=dsf[c0];}//outgoing
       }
 }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC (const FloatValEvaluator< X > & bTemperature, const FloatValEvaluator< X > & bPresssure) const inline
Definition at line 512 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyPressureInletBC(i,bTemperature[i],bPresssure[i]);
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC (int f, const X & outletTemperature, const X & outletPressure) const inline
Definition at line 611 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_cells, KineticBoundaryConditions< X, Diag, OffDiag >::_dsfPtr, KineticBoundaryConditions< X, Diag, OffDiag >::_faceArea, KineticBoundaryConditions< X, Diag, OffDiag >::_faceAreaMag, KineticBoundaryConditions< X, Diag, OffDiag >::_faceCells, KineticBoundaryConditions< X, Diag, OffDiag >::_ibType, KineticBoundaryConditions< X, Diag, OffDiag >::_macroFields, KineticBoundaryConditions< X, Diag, OffDiag >::_options, KineticBoundaryConditions< X, Diag, OffDiag >::_quadrature, Quadrature< T >::cxPtr, Quadrature< T >::cyPtr, Quadrature< T >::czPtr, MacroFields::density, DistFunctFields< T >::dsf, Quadrature< T >::getDirCount(), Mesh::IBTYPE_FLUID, KineticModelOptions< T >::pi, MacroFields::pressure, KineticModelOptions< T >::SpHeatRatio, MacroFields::temperature, and MacroFields::velocity.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), and KineticModel< T >::callBoundaryConditions().
   {
     const double pi=_options.pi;
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     const int numDirections = _quadrature.getDirCount();
     const XArray& cx = dynamic_cast<const XArray&>(*_quadrature.cxPtr);
     const XArray& cy = dynamic_cast<const XArray&>(*_quadrature.cyPtr);
     const XArray& cz = dynamic_cast<const XArray&>(*_quadrature.czPtr);
     XArray& density  = dynamic_cast<XArray&>(_macroFields.density[_cells]);
     VectorX3Array& v = dynamic_cast<VectorX3Array&>(_macroFields.velocity[_cells]);
     XArray& pressure  = dynamic_cast<XArray&>(_macroFields.pressure[_cells]);
     XArray& temperature  = dynamic_cast<XArray&>(_macroFields.temperature[_cells]);
     // X Tout = outletTemperature;
     const X Pout = outletPressure;
     X Pcell= pressure[c0];
     X gamma =_options.SpHeatRatio;
     const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
     X nout =density[c0];
     if (Pcell > Pout){
       const X avel2 =gamma*Pcell/density[c0]; //velcotiy of sound square
       nout =density[c0]-(Pcell-Pout)/avel2;
       X ubulk=pow(pow(v[c0][0],2.0)+pow(v[c0][1],2.0)+pow(v[c0][2],2.0),0.5);
       X ucoeff=1.0/ubulk*(ubulk+(Pcell-Pout)/(pow(2.0*avel2,0.5)*density[c0]));
       if(abs(en[0])==T_Scalar(1.0))
         v[c1][0] = v[c0][0]*ucoeff;
       //v[c1][0]=v[c0][0]+(pressure[c0]-Pout)/(pow(2.0*avel2,0.5)*density[c0]); //exit velocity
       else if(abs(en[1])==T_Scalar(1.0))
         v[c1][1] = v[c0][1]*ucoeff;
       else if(abs(en[2])==T_Scalar(1.0))
         v[c1][2] = v[c0][2]*ucoeff;
       density[c1]=nout; pressure[c1]=Pout; //update macroPr
       temperature[c1]=Pout/nout;
     }
     else{
       density[c1]=density[c0];
       pressure[c1]=pressure[c0];
       temperature[c1]=temperature[c0];
     }
     for (int j=0; j<numDirections; j++)
       {
         Field& fnd = *_dsfPtr.dsf[j];
         XArray& dsf = dynamic_cast< XArray&>(fnd[_cells]);
         const X c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         if (c_dot_en < T_Scalar(0.0))
           {
             dsf[c1] = nout/pow(pi*temperature[c1],1.5)*exp(-(pow(cx[j]-v[c1][0],2.0)+pow(cy[j]-v[c1][1],2.0)+pow(cz[j]-v[c1][2],2.0))/temperature[c1]);
             // dsf[c0]=dsf[c1];// change value of fluid boundary-cell
           }
         else{dsf[c1]=dsf[c0];}
       }
 }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC (const X & bTemperature, const X & bPressure) const inline
Definition at line 678 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyPressureOutletWallBC(i,bTemperature,bPressure);
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC (const FloatValEvaluator< X > & bTemperature, const FloatValEvaluator< X > & bPresssure) const inline
Definition at line 685 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyPressureOutletBC(i,bTemperature[i],bPresssure[i]);
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC (int f, const VectorX3 & WallVelocity, const X & WallTemperature, const X & accommodationCoefficient, const vector< int > & vecReflection) const inline
Definition at line 158 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_cells, KineticBoundaryConditions< X, Diag, OffDiag >::_dsfPtr, KineticBoundaryConditions< X, Diag, OffDiag >::_faceArea, KineticBoundaryConditions< X, Diag, OffDiag >::_faceAreaMag, KineticBoundaryConditions< X, Diag, OffDiag >::_faceCells, KineticBoundaryConditions< X, Diag, OffDiag >::_ibType, KineticBoundaryConditions< X, Diag, OffDiag >::_macroFields, KineticBoundaryConditions< X, Diag, OffDiag >::_options, KineticBoundaryConditions< X, Diag, OffDiag >::_quadrature, Quadrature< T >::cxPtr, Quadrature< T >::cyPtr, Quadrature< T >::czPtr, Quadrature< T >::dcxyzPtr, MacroFields::density, DistFunctFields< T >::dsf, Quadrature< T >::getDirCount(), Mesh::IBTYPE_FLUID, KineticModelOptions< T >::pi, MacroFields::temperature, and MacroFields::velocity.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), and KineticModel< T >::callBoundaryConditions().
   {
     const double pi=_options.pi;
     //const double epsilon=_options.epsilon_ES;
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     const int numDirections = _quadrature.getDirCount();
     const XArray& cx = dynamic_cast<const XArray&>(*_quadrature.cxPtr);
     const XArray& cy = dynamic_cast<const XArray&>(*_quadrature.cyPtr);
     const XArray& cz = dynamic_cast<const XArray&>(*_quadrature.czPtr);
     const XArray& wts= dynamic_cast<const XArray&>(*_quadrature.dcxyzPtr);
     VectorX3Array& v = dynamic_cast<VectorX3Array&>(_macroFields.velocity[_cells]);
     XArray& density  = dynamic_cast<XArray&>(_macroFields.density[_cells]);
     XArray& temperature  = dynamic_cast<XArray&>(_macroFields.temperature[_cells]);
     const X uwall = WallVelocity[0];
     const X vwall = WallVelocity[1];
     const X wwall = WallVelocity[2];
     const X Twall = WallTemperature;
     const X alpha = accommodationCoefficient;
     X m1alpha=1.0-alpha;
     v[c1][0]=uwall;
     v[c1][1]=vwall;
     v[c1][2]=wwall;
     temperature[c1]=Twall;
     X Nmr(0.0) ;
     X Dmr(0.0) ;
     X incomFlux(0.0);
     for (int j=0; j<numDirections; j++)
       {
         Field& fnd = *_dsfPtr.dsf[j];
         XArray& dsf = dynamic_cast< XArray&>(fnd[_cells]);
         const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
         const X c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         const X wallV_dot_en = uwall*en[0]+vwall*en[1]+wwall*en[2];
         const X fwall = 1.0/pow(pi*Twall,1.5)*exp(-(pow(cx[j]-uwall,2.0)+pow(cy[j]-vwall,2.0)+pow(cz[j]-wwall,2.0))/Twall);
         if (c_dot_en -wallV_dot_en < T_Scalar(0.0)) //incoming
           {
             Dmr = Dmr - fwall*wts[j]*(c_dot_en-wallV_dot_en);
             incomFlux=incomFlux-dsf[c0]*wts[j]*(c_dot_en-wallV_dot_en);
           }
         else
           {
            Nmr = Nmr + dsf[c0]*wts[j]*(c_dot_en-wallV_dot_en);
           }
       }
     const X nwall = Nmr/Dmr; // wall number density for initializing Maxwellian
     density[c1]=nwall;
     //if (c0==80)cout <<"incoming " << incomFlux <<" outgoing " <<Nmr << " dens " << nwall<< endl;
     //update f in boundary cell =alpha*f_wall+(1-alpha)*f_reflection
     //c.en-vwall.en=vwall.en-c_incident.en
     for (int j=0; j<numDirections; j++)
       {
         Field& fnd = *_dsfPtr.dsf[j];
         XArray& dsf = dynamic_cast< XArray&>(fnd[_cells]);
         const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
         const X c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         const X wallV_dot_en = uwall*en[0]+vwall*en[1]+wwall*en[2];
         // needed for method 1
         /*
         const int N2 = _quadrature.getNthetaCount();
         const int N3 = _quadrature.getNphiCount();
         const X dcx =  _quadrature.get_dcx();
         const X dcy = _quadrature.get_dcy();
         const X dcz = _quadrature.get_dcz();
         */
         if (c_dot_en-wallV_dot_en < T_Scalar(0.0))
           {
             /*
             const X cx_incident = cx[j] - 2.0*(c_dot_en-wallV_dot_en)*en[0];
             const X cy_incident = cy[j] - 2.0*(c_dot_en-wallV_dot_en)*en[1];
             const X cz_incident = cz[j] - 2.0*(c_dot_en-wallV_dot_en)*en[2];
             //method 1
             const X i_incident = int((cx_incident-cx[0])/dcx+0.5);
             const X j_incident = int((cy_incident-cy[0])/dcy+0.5);
             const X k_incident = int((cz_incident-cz[0])/dcz+0.5);
             const int direction_incident = k_incident+N3*j_incident+N3*N2*i_incident;
             //method 2
             int direction_incident=0;
             X Rdotprod=1e54;
             X dotprod=0.0;
             for (int js=0; js<numDirections; js++){
               dotprod=pow(cx_incident-cx[js],2)+pow(cy_incident-cy[js],2)+pow(cz_incident-cz[js],2);
                 if (dotprod< Rdotprod){
                   Rdotprod =dotprod;
                   direction_incident=js;}
             }
             */
             const int direction_incident = vecReflection[j];
             Field& fndi = *_dsfPtr.dsf[direction_incident];
             const XArray& dsfi = dynamic_cast<const XArray&>(fndi[_cells]);
             dsf[c1] = alpha*nwall/pow(pi*Twall,1.5)*exp(-(pow(cx[j]-uwall,2.0)+pow(cy[j]-vwall,2.0)+pow(cz[j]-wwall,2.0))/Twall)+m1alpha*dsfi[c0]; //write into boundary;
             //dsf[c0]=dsf[c1]; //write into boundary cell
           }
         else
           dsf[c1]=dsf[c0];
       }
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC (const VectorX3 & bVelocity, const X & bTemperature, const X & accomCoeff, const vector< int > & vecReflection) const inline
Definition at line 273 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyRealWallBC(i,bVelocity,bTemperature,accomCoeff,vecReflection);
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC (const FloatValEvaluator< VectorX3 > & bVelocity, const FloatValEvaluator< X > & bTemperature, const FloatValEvaluator< X > & accomCoeff, const vector< int > & vecReflection) const inline
Definition at line 280 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyRealWallBC(i,bVelocity[i],bTemperature[i],accomCoeff[i],vecReflection);
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC (int f, const vector< int > & vecReflection) const inline
Definition at line 287 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_cells, KineticBoundaryConditions< X, Diag, OffDiag >::_dsfPtr, KineticBoundaryConditions< X, Diag, OffDiag >::_faceArea, KineticBoundaryConditions< X, Diag, OffDiag >::_faceAreaMag, KineticBoundaryConditions< X, Diag, OffDiag >::_faceCells, KineticBoundaryConditions< X, Diag, OffDiag >::_ibType, KineticBoundaryConditions< X, Diag, OffDiag >::_quadrature, Quadrature< T >::cxPtr, Quadrature< T >::cyPtr, Quadrature< T >::czPtr, DistFunctFields< T >::dsf, Quadrature< T >::getDirCount(), and Mesh::IBTYPE_FLUID.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), and KineticModel< T >::callBoundaryConditions().
   {
     const int c0 = _faceCells(f,0); //interior
     const int c1 = _faceCells(f,1); //boundary cell
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     const int numDirections = _quadrature.getDirCount();
     const XArray& cx = dynamic_cast<const XArray&>(*_quadrature.cxPtr);
     const XArray& cy = dynamic_cast<const XArray&>(*_quadrature.cyPtr);
     const XArray& cz = dynamic_cast<const XArray&>(*_quadrature.czPtr);
     for (int j=0; j<numDirections; j++)
       {
         // Find incident molecule directions
         const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
         const X  c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         Field& fndw = *_dsfPtr.dsf[j];
         XArray& dsfw = dynamic_cast<XArray&>(fndw[_cells]);
         if(c_dot_en < T_Scalar(0.0)) //incoming molecules to interior
           {
             const int direction_incident = vecReflection[j];
             Field& fnd = *_dsfPtr.dsf[direction_incident];
             const XArray& dsf = dynamic_cast<const XArray&>(fnd[_cells]);
             dsfw[c1] = dsf[c0]; //write into boundary
           }
         else{
           dsfw[c1]=dsfw[c0];}
       }
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC (const vector< int > & vecReflection) const inline
Definition at line 323 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++){
       applySpecularWallBC(i,vecReflection);
       // applySpecularWallBC_Cartesian(i);
     }
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC_Cartesian (int f) const inline
Definition at line 332 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_cells, KineticBoundaryConditions< X, Diag, OffDiag >::_dsfPtr, KineticBoundaryConditions< X, Diag, OffDiag >::_faceArea, KineticBoundaryConditions< X, Diag, OffDiag >::_faceAreaMag, KineticBoundaryConditions< X, Diag, OffDiag >::_faceCells, KineticBoundaryConditions< X, Diag, OffDiag >::_ibType, KineticBoundaryConditions< X, Diag, OffDiag >::_quadrature, Quadrature< T >::cxPtr, Quadrature< T >::cyPtr, Quadrature< T >::czPtr, DistFunctFields< T >::dsf, Quadrature< T >::get_dcx(), Quadrature< T >::get_dcy(), Quadrature< T >::get_dcz(), Quadrature< T >::getDirCount(), Quadrature< T >::getNphiCount(), Quadrature< T >::getNthetaCount(), and Mesh::IBTYPE_FLUID.
   {
     const int c0 = _faceCells(f,0); //interior
     const int c1 = _faceCells(f,1); //boundary cell
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     const int numDirections = _quadrature.getDirCount();
     const XArray& cx = dynamic_cast<const XArray&>(*_quadrature.cxPtr);
     const XArray& cy = dynamic_cast<const XArray&>(*_quadrature.cyPtr);
     const XArray& cz = dynamic_cast<const XArray&>(*_quadrature.czPtr);
     const int N2 = _quadrature.getNthetaCount();
     const int N3 = _quadrature.getNphiCount();
     const X dcx =  _quadrature.get_dcx();
     const X dcy = _quadrature.get_dcy();
     const X dcz = _quadrature.get_dcz();
     for (int j=0; j<numDirections; j++)
       {
         // Find incident molecule directions
         const VectorT3 en = _faceArea[f]/_faceAreaMag[f];
         const X  c_dot_en = cx[j]*en[0]+cy[j]*en[1]+cz[j]*en[2];
         Field& fndw = *_dsfPtr.dsf[j];
         XArray& dsfw = dynamic_cast<XArray&>(fndw[_cells]);
         if(c_dot_en < T_Scalar(0.0)) //incoming molecules to interior
           {
             const X cx_incident = cx[j] - 2.0*c_dot_en*en[0];
             const X cy_incident = cy[j] - 2.0*c_dot_en*en[1];
             const X cz_incident = cz[j] - 2.0*c_dot_en*en[2];
             const X i_incident = int((cx_incident-cx[0])/dcx+0.5);
             const X j_incident = int((cy_incident-cy[0])/dcy+0.5);
             const X k_incident = int((cz_incident-cz[0])/dcz+0.5);
             const int direction_incident = k_incident+N3*j_incident+N3*N2*i_incident;
             Field& fnd = *_dsfPtr.dsf[direction_incident];
             const XArray& dsf = dynamic_cast<const XArray&>(fnd[_cells]);
             dsfw[c1] = dsf[c0]; //write into boundary
           }
         else{
           dsfw[c1]=dsfw[c0];}
       }
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC (int f) const inline
Definition at line 385 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_cells, KineticBoundaryConditions< X, Diag, OffDiag >::_dsfPtr, KineticBoundaryConditions< X, Diag, OffDiag >::_faceCells, KineticBoundaryConditions< X, Diag, OffDiag >::_ibType, KineticBoundaryConditions< X, Diag, OffDiag >::_quadrature, DistFunctFields< T >::dsf, Quadrature< T >::getDirCount(), and Mesh::IBTYPE_FLUID.
Referenced by KineticModel< T >::callBoundaryConditions().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     const int numDirections = _quadrature.getDirCount();
     for (int j=0; j<numDirections; j++)
       {
         Field& fnd = *_dsfPtr.dsf[j];
         XArray& dsf = dynamic_cast< XArray&>(fnd[_cells]);
         dsf[c1]=dsf[c0];
       }
   }
template<class X, class Diag, class OffDiag> void KineticBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC () const inline
Definition at line 402 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_faces, and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyZeroGradientBC(i);
   }
template<class X, class Diag, class OffDiag> KineticModelOptions<X>& KineticBoundaryConditions< X, Diag, OffDiag >::getOptions () inline
Definition at line 63 of file KineticBoundaryConditions.h.
References KineticBoundaryConditions< X, Diag, OffDiag >::_options.
 {return _options;}
Member Data Documentation
template<class X, class Diag, class OffDiag> const Field& KineticBoundaryConditions< X, Diag, OffDiag >::_areaField protected
Definition at line 794 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> const Field& KineticBoundaryConditions< X, Diag, OffDiag >::_areaMagField protected
Definition at line 792 of file KineticBoundaryConditions.h.
template<class X, class Diag, class OffDiag> const StorageSite& KineticBoundaryConditions< X, Diag, OffDiag >::_cells protected
Definition at line 786 of file KineticBoundaryConditions.h.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC_Cartesian(), and KineticBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC().
template<class X, class Diag, class OffDiag> const DistFunctFields<X>& KineticBoundaryConditions< X, Diag, OffDiag >::_dsfPtr protected
Definition at line 790 of file KineticBoundaryConditions.h.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC_Cartesian(), and KineticBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC().
template<class X, class Diag, class OffDiag> const VectorT3Array& KineticBoundaryConditions< X, Diag, OffDiag >::_faceArea protected
Definition at line 795 of file KineticBoundaryConditions.h.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), and KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC_Cartesian().
template<class X, class Diag, class OffDiag> const TArray& KineticBoundaryConditions< X, Diag, OffDiag >::_faceAreaMag protected
Definition at line 793 of file KineticBoundaryConditions.h.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), and KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC_Cartesian().
template<class X, class Diag, class OffDiag> const CRConnectivity& KineticBoundaryConditions< X, Diag, OffDiag >::_faceCells protected
Definition at line 791 of file KineticBoundaryConditions.h.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC_Cartesian(), and KineticBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC().
template<class X, class Diag, class OffDiag> const StorageSite& KineticBoundaryConditions< X, Diag, OffDiag >::_faces protected
Definition at line 785 of file KineticBoundaryConditions.h.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), and KineticBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC().
template<class X, class Diag, class OffDiag> const Array<int>& KineticBoundaryConditions< X, Diag, OffDiag >::_ibType protected
Definition at line 787 of file KineticBoundaryConditions.h.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC_Cartesian(), and KineticBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC().
template<class X, class Diag, class OffDiag> MacroFields& KineticBoundaryConditions< X, Diag, OffDiag >::_macroFields protected
Definition at line 789 of file KineticBoundaryConditions.h.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), and KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC().
template<class X, class Diag, class OffDiag> KineticModelOptions<X> KineticBoundaryConditions< X, Diag, OffDiag >::_options protected
Definition at line 796 of file KineticBoundaryConditions.h.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), and KineticBoundaryConditions< X, Diag, OffDiag >::getOptions().
template<class X, class Diag, class OffDiag> const Quadrature<X>& KineticBoundaryConditions< X, Diag, OffDiag >::_quadrature protected
Definition at line 788 of file KineticBoundaryConditions.h.
Referenced by KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC_Cartesian(), and KineticBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC().
The documentation for this class was generated from the following file:
KineticBoundaryConditions.h