Memosa-FVM: UnorderedSet Class Reference
UnorderedSet Class Reference
#include <MultiFieldMatrix.h>
Public Member Functions
UnorderedSet ()
~UnorderedSet ()
void insert (int x)
const vector< int > & getData () const
int size () const
Private Attributes
vector< int > _data
set< int > _dataSet
Detailed Description
Definition at line 19 of file MultiFieldMatrix.h.
Constructor & Destructor Documentation
UnorderedSet::UnorderedSet () inline
Definition at line 22 of file MultiFieldMatrix.h.
 {};
UnorderedSet::~UnorderedSet () inline
Definition at line 23 of file MultiFieldMatrix.h.
 {};
Member Function Documentation
const vector<int>& UnorderedSet::getData () const inline
Definition at line 33 of file MultiFieldMatrix.h.
References _data.
Referenced by MultiFieldMatrix::syncGhostCoarsening(), and COMETModel< T >::syncGhostCoarsening().
 { return _data;};
void UnorderedSet::insert (int x) inline
Definition at line 25 of file MultiFieldMatrix.h.
References _data, and _dataSet.
Referenced by MultiFieldMatrix::syncGhostCoarsening(), and COMETModel< T >::syncGhostCoarsening().
{
           if ( _dataSet.count(x) == 0 ){
              _data.push_back(x);
              _dataSet.insert(x);
           }
        };
int UnorderedSet::size () const inline
Definition at line 34 of file MultiFieldMatrix.h.
References _data.
Referenced by MultiFieldMatrix::syncGhostCoarsening(), and COMETModel< T >::syncGhostCoarsening().
 { return  _data.size(); };
Member Data Documentation
vector<int> UnorderedSet::_data private
Definition at line 34 of file MultiFieldMatrix.h.
Referenced by getData(), insert(), and size().
set<int> UnorderedSet::_dataSet private
Definition at line 38 of file MultiFieldMatrix.h.
Referenced by insert().
The documentation for this class was generated from the following file:
MultiFieldMatrix.h