Memosa-FVM: Array2D< T > Class Template Reference
Array2D< T > Class Template Reference
#include <Array2D.h>
Public Member Functions
Array2D (const int row_size, const int col_size)
~Array2D ()
int getRow () const
int getCol () const
T & operator() (const int i, const int j)
const T & operator() (const int i, const int j) const
void operator= (const T &x)
void partialCopyFrom (const Array2D &aij)
void partialCopyTo (Array2D &aij)
void zeros ()
void setIdentity ()
void * getData ()
int getDataSize () const
void print (ostream &os) const
Private Member Functions
Array2D (const Array2D &)
void init ()
Private Attributes
Array2D & _self
int _rowSize
int _colSize
int _length
T * _data
Detailed Description
template<class T>
class Array2D< T >
Definition at line 14 of file Array2D.h.
Constructor & Destructor Documentation
template<class T> Array2D< T >::Array2D (const int row_size, const int col_size) inline explicit
Definition at line 20 of file Array2D.h.
                                                           :
     _self(*this),
     _rowSize(row_size),
     _colSize(col_size),
     _length(row_size*col_size),
     _data(new T[_length])
   {
     init();
   }
template<class T> Array2D< T >::~Array2D () inline
Definition at line 31 of file Array2D.h.
   {
      delete [] _data;
   }
template<class T> Array2D< T >::Array2D (const Array2D< T > &) private
Member Function Documentation
template<class T> int Array2D< T >::getCol () const inline
Definition at line 38 of file Array2D.h.
Referenced by Array2D< Diag >::partialCopyFrom(), and Array2D< Diag >::partialCopyTo().
 { return _colSize; }
template<class T> void* Array2D< T >::getData () inline
Definition at line 97 of file Array2D.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchangeSpikeMtrx().
 { return _data;}
template<class T> int Array2D< T >::getDataSize () const inline
Definition at line 98 of file Array2D.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchangeSpikeMtrx().
   {
     return  _length*NumTypeTraits<T>::getDataSize();
   }
template<class T> int Array2D< T >::getRow () const inline
Definition at line 37 of file Array2D.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::denseLUsolve(), SpikeMatrix< T_Diag, T_OffDiag, X >::denseMtrxLU(), Array2D< Diag >::partialCopyFrom(), and Array2D< Diag >::partialCopyTo().
 { return _rowSize; }
template<class T> void Array2D< T >::init () inline private
Definition at line 117 of file Array2D.h.
Referenced by Array2D< Diag >::Array2D().
   {
     for ( int i = 0; i < _length; i++ )
         _data[i] =  NumTypeTraits<T>::getZero();//NumTypeTraits<T>::getNegativeUnity();
   }
template<class T> T& Array2D< T >::operator() (const int i, const int j) inline
returns the index of the j'th non zero column for row i
Definition at line 46 of file Array2D.h.
Referenced by Array2D< Diag >::print().
   {
     return _data[i*_colSize+j];
   }
template<class T> const T& Array2D< T >::operator() (const int i, const int j) const inline
Definition at line 51 of file Array2D.h.
   {
     return _data[i*_colSize+j];
   }
template<class T> void Array2D< T >::operator= (const T & x) inline
Definition at line 55 of file Array2D.h.
{
      for ( int i = 0; i < _length; i++ )
          _data[i] = x;
   }
template<class T> void Array2D< T >::partialCopyFrom (const Array2D< T > & aij) inline
Definition at line 60 of file Array2D.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
{
       const int nrow = aij.getRow();
       const int ncol = aij.getCol();
       for ( int i = 0; i < nrow; i++ ){
           for ( int j = 0; j < ncol; j++){
                _self(i,j) = aij(i,j);
           }
       }
   }
template<class T> void Array2D< T >::partialCopyTo (Array2D< T > & aij) inline
Definition at line 70 of file Array2D.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
{
       const int nrow = aij.getRow();
       const int ncol = aij.getCol();
       for ( int i = 0; i < nrow; i++ ){
           for ( int j = 0; j < ncol; j++){
                aij(i,j) = _self(i,j);
           }
       }
   }
template<class T> void Array2D< T >::print (ostream & os) const inline
Definition at line 104 of file Array2D.h.
   {
       for ( int i = 0; i < _rowSize; i++){
          for ( int j = 0; j < _colSize; j++ ){
             os << std::setprecision(14) << this->operator()(i,j) << "    ";
          }
          os << "\n";
       }
       os << endl;
   }
template<class T> void Array2D< T >::setIdentity () inline
Definition at line 85 of file Array2D.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx().
   {
       for ( int i = 0; i < _rowSize; i++ ){
           for ( int j = 0; j < _colSize; j++){
               if ( i == j )
                  _self(i,j) = NumTypeTraits<T>::getUnity();
           }
       }
   }
template<class T> void Array2D< T >::zeros () inline
Definition at line 80 of file Array2D.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
   {
      for ( int i = 0; i < _length; i++ )
          _data[i] =  NumTypeTraits<T>::getZero();
   }
Member Data Documentation
template<class T> int Array2D< T >::_colSize private
Definition at line 126 of file Array2D.h.
Referenced by Array2D< Diag >::getCol(), Array2D< Diag >::operator()(), Array2D< Diag >::print(), and Array2D< Diag >::setIdentity().
template<class T> T* Array2D< T >::_data private
Definition at line 128 of file Array2D.h.
Referenced by Array2D< Diag >::getData(), Array2D< Diag >::init(), Array2D< Diag >::operator()(), Array2D< Diag >::operator=(), Array2D< Diag >::zeros(), and Array2D< Diag >::~Array2D().
template<class T> int Array2D< T >::_length private
Definition at line 127 of file Array2D.h.
Referenced by Array2D< Diag >::getDataSize(), Array2D< Diag >::init(), Array2D< Diag >::operator=(), and Array2D< Diag >::zeros().
template<class T> int Array2D< T >::_rowSize private
Definition at line 125 of file Array2D.h.
Referenced by Array2D< Diag >::getRow(), Array2D< Diag >::print(), and Array2D< Diag >::setIdentity().
template<class T> Array2D& Array2D< T >::_self private
Definition at line 123 of file Array2D.h.
Referenced by Array2D< Diag >::partialCopyFrom(), Array2D< Diag >::partialCopyTo(), and Array2D< Diag >::setIdentity().
The documentation for this class was generated from the following file:
Array2D.h