Memosa-FVM: CRConnectivity Class Reference
CRConnectivity Class Reference
#include <CRConnectivity.h>
Public Types
enum CRTYPE { CELLCELL1 = 1, CELLCELL2 = 2 }
typedef Array< Vector< int, 2 > > PairToColMapping
Public Member Functions
CRConnectivity (const StorageSite &rowSite, const StorageSite &colSite)
~CRConnectivity ()
DEFINE_TYPENAME ("CRConnectivity")
int getRowDim () const
int getColDim () const
const StorageSite & getRowSite () const
const StorageSite & getColSite () const
shared_ptr< CRConnectivity > getTranspose () const
shared_ptr< CRConnectivity > getMultiTranspose (const int varSize) const
shared_ptr< CRConnectivity > multiply (const CRConnectivity &b, const bool implicitDiagonal) const
shared_ptr< CRConnectivity > createOffset (const StorageSite &newRowSite, const int offset, const int size) const
shared_ptr< CRConnectivity > getSubset (const StorageSite &site, const Array< int > &indices) const
void reorder (const Array< int > &indices)
shared_ptr< CRConnectivity > getLocalizedSubset (const StorageSite &newRowSite, StorageSite &newColSite, const Array< int > &indices) const
shared_ptr< CRConnectivity > getLocalizedSubsetOfFaceCells (const StorageSite &newRowSite, StorageSite &newColSite, const Array< int > &indices, const CRConnectivity &faceCells, const CRConnectivity &cellCells) const
shared_ptr< CRConnectivity > getLocalizedSubsetOfFaceCells (const StorageSite &newRowSite, StorageSite &newColSite, const Array< int > &indices, const CRConnectivity &cellParts, const int partID) const
void localize (const Array< int > &globalToLocal, const StorageSite &newColSite)
int operator() (const int i, const int j) const
int & operator() (const int i, const int j)
int getCoeffPosition (const int i, const int j) const
int getCount (const int i) const
const Array< int > & getGlobalToLocalMap () const
const Array< int > & getLocalToGlobalMap () const
const map< int, int > & getGlobalToLocalMapper () const
map< int, int > & getGlobalToLocalMapper ()
shared_ptr< Array< int > > getGlobalToLocalMapPtr ()
shared_ptr< Array< int > > getLocalToGlobalMapPtr ()
const PairToColMapping & getPairToColMapping (const CRConnectivity &pairs) const
void clearPairToColMapping (const CRConnectivity &pairs) const
void setConnType (CRTYPE type)
const CRTYPE & getConnType () const
void initCount ()
void addCount (const int index, const int count)
void finishCount ()
int add (const int index, const int val)
void finishAdd ()
void resizeLocalToGlobalMap (int size)
const Array< int > & getRow () const
const Array< int > & getCol () const
Array< int > & getCol ()
Private Member Functions
CRConnectivity (const CRConnectivity &)
Private Attributes
StorageSite const * _rowSite
StorageSite const * _colSite
int _rowDim
int _colDim
shared_ptr< Array< int > > _row
shared_ptr< Array< int > > _col
shared_ptr< Array< int > > _globalToLocalMap
map< int, int > _globalToLocalMapper
shared_ptr< Array< int > > _localToGlobalMap
map< const CRConnectivity
*, PairToColMapping * > _pairToColMappings
CRTYPE _connType
Detailed Description
Stores connectivity information using a compressed row format. Basically this means that we have a (integer) row array that stores the indices into col array (also integer) where the non zero entries for a particular row begin. Thus col[row[i]] through col[row[i+1]] store the column indices j where a sparse matrix based on this connectivity would have non zero entries.
Objects of this class can be used to store connectivities between mesh elements such as the faces of a cell or the cells surrounding a node etc. It can also be used to represent the fill pattern of an arbitrary sparse matrix (see CRMatrix).
This class provides support for constructing the connectivity in a two step fashion but is not usable for dynamically changing the connectivity. Typical usage is
– construct by specifying rowSite and colSite. Thus the dimensions are known but not the number of nonzero entries
– call initCount to start the process of counting non zeros
– call addCount to specify the number of non zeros for each row i (this can be in any order and multiple calls for same row are allowed)
– call finishCount - this allocates the col array and resets row array so that it is ready for entries to be added
– call add to specify the nonzero location j for each row i (this can also be in any order but each i,j must be specified only once)
Since we treat this connectivity as a matrix we can perform operations like transpose (to get node - cell connectvity from cell
node connectivity, for example) and multiplication (multiplying cell - faces with face - nodes to get cell nodes, for example)
Definition at line 52 of file CRConnectivity.h.
Member Typedef Documentation
typedef Array<Vector<int,2> > CRConnectivity::PairToColMapping
Definition at line 55 of file CRConnectivity.h.
Member Enumeration Documentation
enum CRConnectivity::CRTYPE
Enumerator
CELLCELL1
CELLCELL2
Definition at line 57 of file CRConnectivity.h.
     {
       CELLCELL1 = 1,
       CELLCELL2 = 2
     };
Constructor & Destructor Documentation
CRConnectivity::CRConnectivity (const StorageSite & rowSite, const StorageSite & colSite)
Definition at line 11 of file CRConnectivity.cpp.
References _colDim, _rowDim, and logCtorVerbose.
Referenced by createOffset(), getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), getMultiTranspose(), getSubset(), getTranspose(), and multiply().
                                                            :
   _rowSite(&rowSite),
   _colSite(&colSite),
   _rowDim(_rowSite->getCountLevel1()),
   _colDim(_colSite->getCountLevel1()),
   _row(),
   _col(),
   _globalToLocalMap(),
   _localToGlobalMap(),
   _pairToColMappings(),
   _connType(CELLCELL1)
 {
   logCtorVerbose("from rowSite and colSite of dimensions (%dx%d)" ,
                  _rowDim,_colDim);
 }
CRConnectivity::~CRConnectivity ()
Definition at line 29 of file CRConnectivity.cpp.
References _colDim, _pairToColMappings, _rowDim, and logDtorVerbose.
 {
   for(map<const CRConnectivity*,PairToColMapping*>::iterator p
         = _pairToColMappings.begin();
       p != _pairToColMappings.end();
       ++p)
     delete p->second;
   logDtorVerbose("of dimensions (%dx%d)" , _rowDim,_colDim);
 }
CRConnectivity::CRConnectivity (const CRConnectivity &) private
Member Function Documentation
int CRConnectivity::add (const int index, const int val) inline
Definition at line 123 of file CRConnectivity.h.
Referenced by Mesh::addCRConn(), KSConnectivity< T >::addOther(), KSConnectivity< T >::addSelf(), CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), getMultiTranspose(), getSubset(), getTranspose(), multiply(), and FluentReader::readFaces().
   {
     int pos = (*_row)[index];
     (*_col)[pos] = val;
     (*_row)[index]++;
     return pos;
   }
void CRConnectivity::addCount (const int index, const int count) inline
Definition at line 116 of file CRConnectivity.h.
Referenced by KSConnectivity< T >::addCountOther(), KSConnectivity< T >::addCountSelf(), CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), Mesh::countCRConn(), getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), getMultiTranspose(), getSubset(), getTranspose(), multiply(), and FluentReader::readFaces().
   {
     (*_row)[index] += count;
   }
void CRConnectivity::clearPairToColMapping (const CRConnectivity & pairs) const
Definition at line 807 of file CRConnectivity.cpp.
References _pairToColMappings.
 {
   if (_pairToColMappings.find(&pairs) != _pairToColMappings.end())
   {
       Array<Vector<int,2> > *pairToCol = _pairToColMappings[&pairs];
       delete pairToCol;
       _pairToColMappings.erase(&pairs);
   }
 }
shared_ptr< CRConnectivity > CRConnectivity::createOffset (const StorageSite & newRowSite, const int offset, const int size) const
Definition at line 796 of file CRConnectivity.cpp.
References _col, _colSite, _row, and CRConnectivity().
Referenced by Mesh::getFaceCells(), and Mesh::getFaceNodes().
 {
   shared_ptr<CRConnectivity> offPtr(new CRConnectivity(newRowSite,*_colSite));
   shared_ptr<ArrayBase> rowOffset(_row->createOffsetArray(offset,size+1));
   offPtr->_row = dynamic_pointer_cast<Array<int> >(rowOffset);
   offPtr->_col = _col;
   return offPtr;
 }
CRConnectivity::DEFINE_TYPENAME ("CRConnectivity")
void CRConnectivity::finishAdd ()
Definition at line 64 of file CRConnectivity.cpp.
References _row, and _rowDim.
Referenced by Mesh::addCRConn(), CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), KSConnectivity< T >::finishAddOther(), KSConnectivity< T >::finishAddSelf(), getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), getMultiTranspose(), getSubset(), getTranspose(), and multiply().
 {
   Array<int>& row = *_row;
   for(int i=_rowDim; i>0; i--)
     row[i] = row[i-1];
   row[0] = 0;
 }
void CRConnectivity::finishCount ()
Definition at line 47 of file CRConnectivity.cpp.
References _col, _row, and _rowDim.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), Mesh::countCRConn(), KSConnectivity< T >::finishCountOther(), KSConnectivity< T >::finishCountSelf(), getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), getMultiTranspose(), getSubset(), getTranspose(), and multiply().
 {
   Array<int>& row = *_row;
   for(int i=0; i<_rowDim; i++)
     row[i+1] += row[i];
   const int colSize = (_rowDim == 0) ? 0 : row[_rowDim-1];
     for(int i=_rowDim; i>0; i--)
     row[i] = row[i-1];
   row[0] = 0;
   _col = shared_ptr<Array<int> >(new Array<int>(colSize));
 }
int CRConnectivity::getCoeffPosition (const int i, const int j) const inline
Definition at line 150 of file CRConnectivity.h.
References _col, and _row.
Referenced by setFlatCoeffs().
   {
     for (int nnb = (*_row)[i]; nnb<(*_row)[i+1]; nnb++)
     {
         if ((*_col)[nnb] == j)
           return nnb;
     }
     throw CException("invalid indices");
   }
const Array<int>& CRConnectivity::getCol () const inline
Definition at line 183 of file CRConnectivity.h.
References _col.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), MeshMetricsCalculator< T >::computeSolidInterpolationMatrices(), ElectricModel< T >::Impl::computeSolidSurfaceForce(), FlowModel< T >::Impl::computeSolidSurfaceForce(), KineticModel< T >::computeSurfaceForce(), COMETModel< T >::computeSurfaceForce(), NcDataWriter::connectivities(), MeshPartitioner::CRConnectivityPrint(), Mesh::CRConnectivityPrint(), IBManager::CRConnectivityPrintFile(), MeshPartitioner::CRConnectivityPrintFile(), Mesh::CRConnectivityPrintFile(), Mesh::createAndGetBNglobalToLocal(), CRMatrixRect< T_Coeff, X, B >::createCoarseMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix(), FluentReader::createMesh(), debug_mesh(), IbmDiscretization< X, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), FlowModel< T >::Impl::dumpContinuityMatrix(), ThermalModel< T >::Impl::dumpMatrix(), VacancyModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), KSConnectivity< T >::expandMySelfOther(), KSConnectivity< T >::expandMySelfSelf(), Mesh::getCellCells2(), KSConnectivity< T >::getOtherCol(), getPairToColMapping(), KSConnectivity< T >::getSelfCol(), KSConnectivity< T >::multiplyOther(), KSConnectivity< T >::multiplySelf(), setFlatCoeffs(), SpikeMatrix< T_Diag, T_OffDiag, X >::setMatrix(), SpikeStorage::setOffDiagPtr(), and Mesh::uniqueFaceCells().
 {return *_col;}
Array<int>& CRConnectivity::getCol () inline
Definition at line 184 of file CRConnectivity.h.
References _col.
 {return *_col;}
int CRConnectivity::getColDim () const inline
Definition at line 69 of file CRConnectivity.h.
References _colDim.
Referenced by debug_mesh().
 {return _colDim;}
const StorageSite& CRConnectivity::getColSite () const inline
Definition at line 72 of file CRConnectivity.h.
References _colSite.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0().
 {return *_colSite;}
const CRTYPE& CRConnectivity::getConnType () const inline
Definition at line 208 of file CRConnectivity.h.
References _connType.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::eliminateBoundaryEquations().
{
       return _connType;
   }
int CRConnectivity::getCount (const int i) const inline
returns the number of non zeroes for row i
Definition at line 165 of file CRConnectivity.h.
References _row.
Referenced by AABB::AABB(), Mesh::addCRConn(), addFluidNeighbors(), MovingMeshModel< T >::advance(), COMETBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), COMETBoundary< T >::applyTemperatureWallFine(), COMETBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC(), MeshMetricsCalculator< T >::calculateBoundaryNodeNormal(), MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateFaceAreas(), MeshMetricsCalculator< T >::calculateFaceCentroids(), StructureDeformationModel< T >::calculateNodeDisplacement(), PlateDeformationModel< T >::calculateNodeDisplacement(), MeshPartitioner::cellcells_global_extension(), CellMark_Impl(), COMETModel< T >::coarsenInterfaceCells(), COMETModel< T >::coarsenInterior(), COMETESBGKDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETESBGKDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::correctInterface(), COMETModel< T >::correctSolution(), Mesh::countCRConn(), MeshAssembler::countInterfaceNodes(), CRMatrixRect< T_Coeff, X, B >::createCoarseConnectivity(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseConnectivity(), DiagonalMatrix< Diag, X >::createCoarseMatrix(), CRMatrixRect< T_Coeff, X, B >::createCoarseMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix(), IBManager::createIBInterpolationStencil(), Mesh::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), Mesh::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), GradientMatrix< T_Scalar >::createScatterGatherValuesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), IBManager::createSolidInterpolationStencil(), MeshDismantler::debug_face_cells(), MeshDismantler::debug_face_nodes(), TrapBandTunnelingDiscretization< X, Diag, OffDiag >::discretize(), LinearizeDielectric< X, Diag, OffDiag >::discretize(), InjectionDiscretization< X, Diag, OffDiag >::discretize(), TunnelingDiscretization< X, Diag, OffDiag >::discretize(), PartMesh::dumpTecplot(), MeshPartitioner::extractBoundaryMesh(), Mesh::extractBoundaryMesh(), Mesh::extrude(), MeshDismantler::faceNodesAddBoundaryInterfaces(), MeshDismantler::faceNodesAddInteriorFaces(), MeshDismantler::faceNodesAddMeshInterfaces(), MeshDismantler::faceNodesAddPartitionInterfaces(), MeshDismantler::faceNodesInit(), Mesh::findCommonNodes(), Grid::findNeighborsByCells(), MeshPartitioner::get_local_nodes(), Mesh::getCellCells2(), MeshAssembler::getInnerNodesCount(), getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), KSConnectivity< T >::getOtherCount(), getPairToColMapping(), KSConnectivity< T >::getSelfCount(), getSubset(), MeshPartitioner::globalCellID_procID_map(), inCell(), COMETModel< T >::injectResid(), MeshPartitioner::level1_scatter_gather_cells(), PartMesh::local_nodes(), COMETModel< T >::makeCellColors(), COMETModel< T >::MakeCoarseMesh1(), COMETModel< T >::MakeInteriorCoarseMesh(), markCell(), IBManager::markFluid(), IBManager::markIntersections(), PartMesh::mesh_tecplot(), MeshPartitioner::mesh_tecplot(), PartMesh::mesh_xdmfplot(), MeshPartitioner::mesh_xdmfplot(), AABB::meshIntersections(), Cell< CellTrait >::orderCellFacesAndNodes(), orderCellFacesAndNodes(), COMETDiscretizer< T >::ScatterPhonons(), MeshPartitioner::set_cellcells_global(), PartMesh::set_eptr_eind(), MeshPartitioner::set_eptr_eind(), MeshDismantler::set_local_global(), MeshPartitioner::set_local_global(), COMETESBGKDiscretizer< T >::setBoundaryValFine(), Mesh::setCommonFacesMap(), MeshAssembler::setFaceNodes(), setibFaceCells(), setibFaceParticles(), MeshAssembler::setInterfaceNodes(), MeshAssembler::setNodesMapper(), MeshDismantler::setNodesMapper(), MeshDismantler::setNodesSite(), FVMParticles::setParticles(), StructureDeformationModel< T >::updateBoundaryMesh(), PlateDeformationModel< T >::updateBoundaryMesh(), COMETDiscretizer< T >::updateGhostCoarse(), COMETDiscretizer< T >::updateGhostFine(), MovingMeshModel< T >::volChange(), and VTKWriter< T >::VTKWriter().
   {
     return ((*_row)[i+1] - (*_row)[i]);
   }
const Array<int>& CRConnectivity::getGlobalToLocalMap () const inline
Definition at line 189 of file CRConnectivity.h.
References _globalToLocalMap.
Referenced by getLocalizedSubsetOfFaceCells(), and MeshPartitioner::preserve_cell_order().
 {return *_globalToLocalMap;}
const map<int,int>& CRConnectivity::getGlobalToLocalMapper () const inline
Definition at line 192 of file CRConnectivity.h.
References _globalToLocalMapper.
 {return _globalToLocalMapper;}
map<int,int>& CRConnectivity::getGlobalToLocalMapper () inline
Definition at line 193 of file CRConnectivity.h.
References _globalToLocalMapper.
 {return _globalToLocalMapper;}
shared_ptr<Array<int> > CRConnectivity::getGlobalToLocalMapPtr () inline
Definition at line 195 of file CRConnectivity.h.
References _globalToLocalMap.
 {return _globalToLocalMap;}
shared_ptr< CRConnectivity > CRConnectivity::getLocalizedSubset (const StorageSite & newRowSite, StorageSite & newColSite, const Array< int > & indices) const
Definition at line 621 of file CRConnectivity.cpp.
References _col, _colDim, _globalToLocalMap, _localToGlobalMap, _row, add(), addCount(), CRConnectivity(), finishAdd(), finishCount(), getCount(), Array< T >::getLength(), initCount(), and StorageSite::setCount().
Referenced by debug_mesh().
 {
   const Array<int>& myRow = *_row;
   const Array<int>& myCol = *_col;
   shared_ptr<Array<int> > globalToLocalPtr(new Array<int>(_colDim));
   Array<int>& globalToLocal = *globalToLocalPtr;
   globalToLocal = -1;
   int nLocal=0;
   for(int ii=0;ii<indices.getLength();ii++)
   {
       const int i = indices[ii];
       for(int ip=myRow[i];ip<myRow[i+1]; ip++)
       {
           const int j = myCol[ip];
           if (globalToLocal[j] == -1)
             globalToLocal[j] = nLocal++;
       }
   }
   shared_ptr<Array<int> > localToGlobalPtr(new Array<int>(nLocal));
   Array<int>& localToGlobal = *localToGlobalPtr;
   newColSite.setCount(nLocal);
   shared_ptr<CRConnectivity> subPtr(new CRConnectivity(newRowSite,newColSite));
   CRConnectivity& sub = *subPtr;
   sub.initCount();
   for(int ii=0;ii<indices.getLength();ii++)
   {
       const int i = indices[ii];
       sub.addCount(ii,getCount(i));
   }
   sub.finishCount();
   for(int ii=0;ii<indices.getLength();ii++)
   {
       const int i = indices[ii];
       for(int ip=myRow[i];ip<myRow[i+1]; ip++)
       {
           const int j = myCol[ip];
           const int jLocal = globalToLocal[j];
           sub.add(ii,jLocal);
       }
   }
   for(int i=0; i<_colDim; i++)
     if (globalToLocal[i] != -1)
       localToGlobal[globalToLocal[i]] = i;
   sub.finishAdd();
   sub._globalToLocalMap=globalToLocalPtr;
   sub._localToGlobalMap=localToGlobalPtr;
   return subPtr;
 }
shared_ptr< CRConnectivity > CRConnectivity::getLocalizedSubsetOfFaceCells (const StorageSite & newRowSite, StorageSite & newColSite, const Array< int > & indices, const CRConnectivity & faceCells, const CRConnectivity & cellCells) const
Definition at line 311 of file CRConnectivity.cpp.
References _col, _colDim, _globalToLocalMap, _localToGlobalMap, _row, add(), addCount(), CRConnectivity(), finishAdd(), finishCount(), getCount(), getGlobalToLocalMap(), Array< T >::getLength(), getRowDim(), initCount(), max(), and StorageSite::setCount().
 {
   const Array<int>& myRow = *_row;
   const Array<int>& myCol = *_col;
   map<int, int>  localToGlobalMap;
   map<int, vector<int> > faceToGlobalCellsMap;
   map<int, vector<int> > faceToLocalCellsMap;
   shared_ptr<Array<int> > globalToLocalPtr(new Array<int>(_colDim));
   Array<int>& globalToLocal = *globalToLocalPtr;
   globalToLocal = -1;
    int max_sur_cells = 0;
    for ( int elem = 0; elem < cellCells.getRowDim(); elem++ )
         max_sur_cells = std::max( max_sur_cells, cellCells.getCount(elem) );
   int nLocal=0;
 //loop over inner elements
   for(int ii=0;ii<indices.getLength();ii++)
   {
       bool inner_face  = true;
       const int i = indices[ii];
       vector<int> localConn ( myRow[i+1] - myRow[i], -1 );
       vector<int> globalConn( myRow[i+1] - myRow[i], -1 );
       int indx = 0;
       for(int ip=myRow[i];ip<myRow[i+1]; ip++)
       {
           const int j = myCol[ip];
           const int local_elem = faceCells.getGlobalToLocalMap()[j];
           globalConn.at(indx) = j;
          if ( cellCells.getCount(local_elem) != max_sur_cells )
                inner_face = false;
          if ( cellCells.getCount(local_elem)  == max_sur_cells  ){ //if it is a inner element
             if( globalToLocal[j] == -1  ){
              localToGlobalMap.insert( pair<int,int>(nLocal, j) );
              localConn.at(indx)  = nLocal;
              globalToLocal[j] = nLocal++;
             } else {
              localConn.at(indx) = globalToLocal[j];
             }
          }
           indx++;
       }
       if ( inner_face ){
          faceToGlobalCellsMap[ii] = globalConn;
          faceToLocalCellsMap[ii]  = localConn;
       }
   }
   //outer faces (interface  + boundary)
   for(int ii=0;ii<indices.getLength();ii++)
   {
       bool outer_face = false;
       const int i = indices[ii];
       vector<int> localConn ( myRow[i+1] - myRow[i], -1 );
       vector<int> globalConn( myRow[i+1] - myRow[i], -1 );
       int indx = 0;
       for(int ip=myRow[i];ip<myRow[i+1]; ip++)
       {
           const int j = myCol[ip];
           const int local_elem = faceCells.getGlobalToLocalMap()[j];
            globalConn.at(indx) = j;
           if ( cellCells.getCount(local_elem) != max_sur_cells )
                outer_face = true;
           if ( cellCells.getCount(local_elem) != max_sur_cells ){ //if it is a boundary or interface cells
               localToGlobalMap.insert( pair<int,int>(nLocal, j) );
               localConn.at(indx)  = nLocal;
               globalToLocal[j]    = nLocal++;  //we still use globalToLocal for only inner and boundary (one-to-one mapping)
           } else {
                assert( globalToLocal[j] != -1 );
                localConn.at(indx) = globalToLocal[j];
           }
           indx++;
       }
       if ( outer_face ){
          faceToGlobalCellsMap[ii] = globalConn;
          faceToLocalCellsMap[ii]  = localConn;
       }
   }
   shared_ptr<Array<int> > localToGlobalPtr(new Array<int>(nLocal));
   Array<int>& localToGlobal = *localToGlobalPtr;
   newColSite.setCount(nLocal);
   shared_ptr<CRConnectivity> subPtr(new CRConnectivity(newRowSite,newColSite));
   CRConnectivity& sub = *subPtr;
   sub.initCount();
   for(int ii=0;ii<indices.getLength();ii++)
   {
       const int i = indices[ii];
       sub.addCount(ii,getCount(i));
   }
   sub.finishCount();
   map<int,int>::const_iterator it;
   for ( it = localToGlobalMap.begin(); it != localToGlobalMap.end(); it++ ){
      int local_id  = it->first;
      int global_id = it->second;
      localToGlobal[ local_id ] =  global_id;
    }
  for(int ii=0;ii<indices.getLength();ii++)
   {
       const int i = indices[ii];
       int indx = 0;
       for(int ip=myRow[i];ip<myRow[i+1]; ip++)
       {
           const int jLocal = faceToLocalCellsMap[ii].at(indx);
           sub.add(ii,jLocal);
           indx++;
       }
   }
   sub.finishAdd();
   sub._globalToLocalMap=globalToLocalPtr;
   sub._localToGlobalMap=localToGlobalPtr;
   return subPtr;
 }
shared_ptr< CRConnectivity > CRConnectivity::getLocalizedSubsetOfFaceCells (const StorageSite & newRowSite, StorageSite & newColSite, const Array< int > & indices, const CRConnectivity & cellParts, const int partID) const
Definition at line 457 of file CRConnectivity.cpp.
References _col, _globalToLocalMap, _localToGlobalMap, _row, add(), addCount(), CRConnectivity(), finishAdd(), finishCount(), StorageSite::getCount(), getCount(), Array< T >::getLength(), getRowSite(), StorageSite::getSelfCount(), initCount(), and StorageSite::setCount().
 {
   const Array<int>& myRow = *_row;
   const Array<int>& myCol = *_col;
   map<int, int>  localToGlobalMap;
   map<int, vector<int> > faceToLocalCellsMap;
   const StorageSite& rowSite = cellParts.getRowSite();
   const int cellSelfCount = rowSite.getSelfCount();
   const int cellCount     = rowSite.getCount();
   shared_ptr<Array<int> > globalToLocalPtr(new Array<int>(cellCount));
   Array<int>& globalToLocal = *globalToLocalPtr;
   globalToLocal = -1;
   int nLocal=0;
 //loop over faces (sub)
   for(int ii=0;ii<indices.getLength();ii++)
   {
       bool inner_face  = true;
       const int i = indices[ii];
       //check if it is interface, pick one cell partition id, then compare connected cells if they are anot equal
       const int compID =  cellParts( myCol[myRow[i]], 0 );
       for(int ip=myRow[i];ip<myRow[i+1]; ip++){
           const int j = myCol[ip];
           if ( cellParts(j,0) != compID ) //interface if it is true
              inner_face = false;
       }
       //first check if it is boundary cell, then it is boundary interface
       for(int ip=myRow[i];ip<myRow[i+1]; ip++){
           const int j = myCol[ip];
           if ( j  >= cellSelfCount ) //either interface or boundary
              inner_face = false;
       }
       vector<int> localConn ( myRow[i+1] - myRow[i], -1 );
       //looping over cell around faces
       if ( inner_face ){ //if it is a inner element
           int indx = 0;
           for(int ip=myRow[i];ip<myRow[i+1]; ip++)
           {
              const int j = myCol[ip];
              if( globalToLocal[j] == -1  ){
                 localToGlobalMap.insert( pair<int,int>(nLocal, j) );
                 localConn.at(indx)  = nLocal;
                 globalToLocal[j] = nLocal++;
              } else {
                 localConn.at(indx) = globalToLocal[j];
              }
              indx++;
          }
       }
       if ( inner_face ){
          faceToLocalCellsMap[ii]  = localConn;
       }
   }
   //now there might be cells which is inner cell but surrounded by all boundary/interfaces faces, we have to renumber it before ghost cells
   for(int ii=0;ii<indices.getLength();ii++){
       const int i = indices[ii];
       for(int ip=myRow[i];ip<myRow[i+1]; ip++){
           const int j = myCol[ip];
           // these cells should be inner cell (j<..), never visited (glb..=-1), and staying in current partition (cellParts... == partID)
           if ( j  < cellSelfCount && globalToLocal[j] == -1 &&  cellParts(j,0) == partID ){
              localToGlobalMap.insert( pair<int,int>(nLocal, j) );
              globalToLocal[j] = nLocal++;
           }
       }
   }
   //outer faces (interface  + boundary)
   for(int ii=0;ii<indices.getLength();ii++)
   {
       bool outer_face = false;
       const int i = indices[ii];
       //check if it is interface, pick one cell partition id, then compare connected cells if they are anot equal
       const int compID =  cellParts( myCol[myRow[i]], 0 );
       for(int ip=myRow[i];ip<myRow[i+1]; ip++){
           const int j = myCol[ip];
           if ( cellParts(j,0) != compID ) //either interface or boundary
              outer_face = true;
       }
       //first check if it is boundary cell, then it is boundary interface
       for(int ip=myRow[i];ip<myRow[i+1]; ip++){
           const int j = myCol[ip];
           if ( j  >= cellSelfCount ) //either interface or boundary
              outer_face = true;
       }
       vector<int> localConn ( myRow[i+1] - myRow[i], -1 );
       if ( outer_face ){ //if it is a boundary or interface cells
          int indx = 0;
          for(int ip=myRow[i];ip<myRow[i+1]; ip++){
              const int j = myCol[ip];
              if ( globalToLocal[j] == -1 ){
                localToGlobalMap.insert( pair<int,int>(nLocal, j) );
                localConn.at(indx) = nLocal++;
              } else {
                localConn.at(indx) = globalToLocal[j];
              }
              indx++;
          }
       }
       if ( outer_face ){
          faceToLocalCellsMap[ii]  = localConn;
       }
   }
   shared_ptr<Array<int> > localToGlobalPtr(new Array<int>(nLocal));
   Array<int>& localToGlobal = *localToGlobalPtr;
   newColSite.setCount(nLocal);
   shared_ptr<CRConnectivity> subPtr(new CRConnectivity(newRowSite,newColSite));
   CRConnectivity& sub = *subPtr;
   sub.initCount();
   for(int ii=0;ii<indices.getLength();ii++)
   {
       const int i = indices[ii];
       sub.addCount(ii,getCount(i));
   }
   sub.finishCount();
   map<int,int>::const_iterator it;
   for ( it = localToGlobalMap.begin(); it != localToGlobalMap.end(); it++ ){
      int local_id  = it->first;
      int global_id = it->second;
      localToGlobal[ local_id ] =  global_id;
    }
  for(int ii=0;ii<indices.getLength();ii++)
   {
       const int i = indices[ii];
       int indx = 0;
       for(int ip=myRow[i];ip<myRow[i+1]; ip++)
       {
           const int jLocal = faceToLocalCellsMap[ii].at(indx);
           sub.add(ii,jLocal);
           indx++;
       }
   }
   sub.finishAdd();
   sub._globalToLocalMap=globalToLocalPtr;
   sub._localToGlobalMap=localToGlobalPtr;
   return subPtr;
 }
const Array<int>& CRConnectivity::getLocalToGlobalMap () const inline
Definition at line 190 of file CRConnectivity.h.
References _localToGlobalMap.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), and MeshPartitioner::preserve_cell_order().
 {return *_localToGlobalMap;}
shared_ptr<Array<int> > CRConnectivity::getLocalToGlobalMapPtr () inline
Definition at line 196 of file CRConnectivity.h.
References _localToGlobalMap.
 {return _localToGlobalMap;}
shared_ptr< CRConnectivity > CRConnectivity::getMultiTranspose (const int varSize) const
Definition at line 101 of file CRConnectivity.cpp.
References _col, _colDim, _colSite, _row, _rowDim, _rowSite, add(), addCount(), CRConnectivity(), finishAdd(), finishCount(), and initCount().
Referenced by DirectSolver::solve().
 {
   shared_ptr<CRConnectivity> trPtr(new CRConnectivity(*_colSite,*_rowSite));
   CRConnectivity& tr = *trPtr;
   tr._rowDim *= varSize;
   tr._colDim *= varSize;
   tr.initCount();
   const Array<int>& myRow = *_row;
   const Array<int>& myCol = *_col;
   for(int i=0; i<_rowDim; i++)
   {
       for(int ndr=0; ndr<varSize; ndr++)
       {
           const int nfr = i*varSize + ndr;
           tr.addCount(nfr, varSize);
       }
       for(int jp=myRow[i]; jp<myRow[i+1]; jp++)
       {
           const int j = myCol[jp];
           for(int ndr=0; ndr<varSize; ndr++)
             for(int ndc=0; ndc<varSize; ndc++)
             {
                 //const int nfr = i*varSize + ndr;
                 const int nfc = j*varSize + ndc;
                 tr.addCount(nfc, 1);
             }
       }
   }
   tr.finishCount();
   for(int i=0; i<_rowDim; i++)
   {
       for(int ndr=0; ndr<varSize; ndr++)
         for(int ndc=0; ndc<varSize; ndc++)
         {
             const int nfr = i*varSize + ndr;
             const int nfc = i*varSize + ndc;
             tr.add(nfc, nfr);
         }
       for(int jp=myRow[i]; jp<myRow[i+1]; jp++)
       {
           const int j = myCol[jp];
           for(int ndr=0; ndr<varSize; ndr++)
             for(int ndc=0; ndc<varSize; ndc++)
             {
                 const int nfr = i*varSize + ndr;
                 const int nfc = j*varSize + ndc;
                 tr.add(nfc, nfr);
             }
       }
   }
   tr.finishAdd();
   return trPtr;
 }
const Array< Vector< int, 2 > > & CRConnectivity::getPairToColMapping (const CRConnectivity & pairs) const
Definition at line 730 of file CRConnectivity.cpp.
References _pairToColMappings, getCol(), getCount(), getRow(), and getRowDim().
Referenced by CRMatrixRect< T_Coeff, X, B >::getPairWiseAssembler(), and CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler().
 {
   if (_pairToColMappings.find(&pairs) == _pairToColMappings.end())
   {
       const Array<int>& crRow = getRow();
       const Array<int>& crCol = getCol();
       const int pairCount = pairs.getRowDim();
       Array<Vector<int,2> > *pairToCol = new Array<Vector<int,2> >(pairCount);
       _pairToColMappings[&pairs] = pairToCol;
       for(int np=0; np<pairCount; np++)
       {
           if (pairs.getCount(np) == 2)
           {
               int n0 = pairs(np,0);
               int n1 = pairs(np,1);
               bool found = false;
               for(int r0=crRow[n0]; r0<crRow[n0+1]; r0++)
                 if (crCol[r0] == n1)
                 {
                     (*pairToCol)[np][0] = r0;
                     found = true;
                     break;
                 }
               ostringstream e;
               if (!found)
               {
                   e << "did not find col pos for ( " << n0 << "," << n1 << ")";
                   throw CException(e.str());
               }
               found = false;
               for(int r1=crRow[n1]; r1<crRow[n1+1]; r1++)
                 if (crCol[r1] == n0)
                 {
                     (*pairToCol)[np][1] = r1;
                     found = true;
                     break;
                 }
               if (!found)
               {
                   e << "did not find col pos for ( " << n1 << "," << n0 << ")";
                   throw CException(e.str());
               }
           }
           else
           {
               ostringstream e;
               e << "invalid count for pairs connectivity" << endl;
               throw CException(e.str());
           }
       }
   }
   return *_pairToColMappings[&pairs];
 }
const Array<int>& CRConnectivity::getRow () const inline
Definition at line 182 of file CRConnectivity.h.
References _row.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), MeshMetricsCalculator< T >::computeSolidInterpolationMatrices(), ElectricModel< T >::Impl::computeSolidSurfaceForce(), FlowModel< T >::Impl::computeSolidSurfaceForce(), KineticModel< T >::computeSurfaceForce(), COMETModel< T >::computeSurfaceForce(), NcDataWriter::connectivities(), MeshPartitioner::CRConnectivityPrint(), Mesh::CRConnectivityPrint(), IBManager::CRConnectivityPrintFile(), MeshPartitioner::CRConnectivityPrintFile(), Mesh::CRConnectivityPrintFile(), Mesh::createAndGetBNglobalToLocal(), CRMatrixRect< T_Coeff, X, B >::createCoarseMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix(), FluentReader::createMesh(), debug_mesh(), IbmDiscretization< X, Diag, OffDiag >::discretize(), MomentumPressureGradientDiscretization< X >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), FlowModel< T >::Impl::dumpContinuityMatrix(), VacancyModel< T >::Impl::dumpMatrix(), ThermalModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), KSConnectivity< T >::expandMySelfOther(), KSConnectivity< T >::expandMySelfSelf(), Mesh::getCellCells2(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D(), KSConnectivity< T >::getOtherRow(), getPairToColMapping(), KSConnectivity< T >::getSelfRow(), KSConnectivity< T >::multiplyOther(), KSConnectivity< T >::multiplySelf(), FlowModel< T >::Impl::setDirichlet(), MeshAssembler::setFaceNodes(), setFlatCoeffs(), SpikeMatrix< T_Diag, T_OffDiag, X >::setMatrix(), SpikeStorage::setOffDiagPtr(), and Mesh::uniqueFaceCells().
 {return *_row;}
int CRConnectivity::getRowDim () const inline
Definition at line 68 of file CRConnectivity.h.
References _rowDim.
Referenced by Mesh::createAndGetBNglobalToLocal(), DiagonalMatrix< Diag, X >::createCoarseMatrix(), CRMatrixRect< T_Coeff, X, B >::createCoarseMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix(), debug_mesh(), getLocalizedSubsetOfFaceCells(), getPairToColMapping(), PartMesh::mesh_tecplot(), MeshPartitioner::mesh_tecplot(), FluxJacobianMatrix< OffDiag, X >::multiply(), FluxJacobianMatrix< OffDiag, X >::multiplyAndAdd(), and setFlatCoeffs().
 {return _rowDim;}
const StorageSite& CRConnectivity::getRowSite () const inline
Definition at line 71 of file CRConnectivity.h.
References _rowSite.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), CRMatrix< T_Diag, T_OffDiag, X >::computeResidual(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateBoundaryEquations(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), CRMatrix< T_Diag, T_OffDiag, X >::forwardGS(), SpikeStorage::gatherCellSizes(), CRMatrix< T_Diag, T_OffDiag, X >::get_request_size(), Mesh::getCellCells2(), GradientMatrix< T_Scalar >::getGradient(), getLocalizedSubsetOfFaceCells(), SpikeStorage::init(), CRMatrix< T_Diag, T_OffDiag, X >::Jacobi(), CRMatrix< T_Diag, T_OffDiag, X >::lowerSolve(), CRMatrixRect< T_Coeff, X, B >::multiply(), CRMatrix< T_Diag, T_OffDiag, X >::multiply(), CRMatrixTranspose< T_Coeff, X, B >::multiplyAndAdd(), CRMatrixRect< T_Coeff, X, B >::multiplyAndAdd(), CRMatrix< T_Diag, T_OffDiag, X >::multiplyAndAdd(), orderCellFacesAndNodes(), CRMatrix< T_Diag, T_OffDiag, X >::quadProduct(), CRMatrix< T_Diag, T_OffDiag, X >::reverseGS(), SpikeStorage::setGlobalIndices(), CRMatrix< T_Diag, T_OffDiag, X >::solveBoundary(), SpikeStorage::syncCellIDs(), CRMatrix< T_Diag, T_OffDiag, X >::syncCounts(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx(), CRMatrix< T_Diag, T_OffDiag, X >::transpose(), Mesh::uniqueFaceCells(), and CRMatrix< T_Diag, T_OffDiag, X >::upperSolve().
 {return *_rowSite;}
shared_ptr< CRConnectivity > CRConnectivity::getSubset (const StorageSite & site, const Array< int > & indices) const
Definition at line 274 of file CRConnectivity.cpp.
References _col, _colSite, _row, add(), addCount(), CRConnectivity(), finishAdd(), finishCount(), getCount(), Array< T >::getLength(), and initCount().
Referenced by debug_mesh().
 {
   shared_ptr<CRConnectivity> subPtr(new CRConnectivity(site,*_colSite));
   CRConnectivity& sub = *subPtr;
   const Array<int>& myRow = *_row;
   const Array<int>& myCol = *_col;
   sub.initCount();
   for(int ii=0;ii<indices.getLength();ii++)
   {
       const int i = indices[ii];
       sub.addCount(ii,getCount(i));
   }
   sub.finishCount();
   for(int ii=0;ii<indices.getLength();ii++)
   {
       const int i = indices[ii];
       for(int ip=myRow[i];ip<myRow[i+1]; ip++)
       {
           const int j = myCol[ip];
           sub.add(ii,j);
       }
   }
   sub.finishAdd();
   return subPtr;
 }
shared_ptr< CRConnectivity > CRConnectivity::getTranspose () const
Definition at line 74 of file CRConnectivity.cpp.
References _col, _colSite, _row, _rowDim, _rowSite, add(), addCount(), CRConnectivity(), finishAdd(), finishCount(), and initCount().
Referenced by StructureDeformationModel< T >::calculateNodeDisplacement(), PlateDeformationModel< T >::calculateNodeDisplacement(), COMETModel< T >::coarsenInterfaceCells(), Mesh::getCellFaces(), FluentReader::getNodeCells(), MeshDismantler::init(), COMETModel< T >::makeFinestToCoarseConn(), COMETModel< T >::MakeInteriorCoarseMesh(), and Mesh::setCommonFacesMap().
 {
   shared_ptr<CRConnectivity> trPtr(new CRConnectivity(*_colSite,*_rowSite));
   CRConnectivity& tr = *trPtr;
   tr.initCount();
   const Array<int>& myRow = *_row;
   const Array<int>& myCol = *_col;
   for(int i=0; i<_rowDim; i++){
     for(int j=myRow[i]; j<myRow[i+1]; j++)
       tr.addCount(myCol[j],1);
   }
   tr.finishCount();
   for(int i=0; i<_rowDim; i++)
     for(int j=myRow[i]; j<myRow[i+1]; j++)
       tr.add(myCol[j],i);
   tr.finishAdd();
   return trPtr;
 }
void CRConnectivity::initCount ()
see comments above
Definition at line 41 of file CRConnectivity.cpp.
References _row, and _rowDim.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), Mesh::countCRConn(), getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), getMultiTranspose(), getSubset(), getTranspose(), KSConnectivity< T >::initOtherCount(), KSConnectivity< T >::initSelfCount(), and multiply().
 {
   _row = shared_ptr<Array<int> >(new Array<int>(_rowDim+1));
   *_row = 0;
 }
void CRConnectivity::localize (const Array< int > & globalToLocal, const StorageSite & newColSite)
Definition at line 697 of file CRConnectivity.cpp.
References _col, _colDim, _colSite, StorageSite::getCount(), and Array< T >::getLength().
 {
   const int newColDim = newColSite.getCount();
   if (globalToLocal.getLength() != _colDim)
   {
       ostringstream e;
       e << "global to local mapping is of wrong size ("  <<
         globalToLocal.getLength() << "); should be " << _colDim;
       throw CException(e.str());
   }
   Array<int>& myCol = *_col;
   for(int i=0; i<myCol.getLength(); i++)
   {
       const int localIndex = globalToLocal[myCol[i]];
       if (localIndex >=0 && localIndex < newColDim)
         myCol[i] = localIndex;
       else
       {
           ostringstream e;
           e << "invalid global to local mapping at index "  <<
             myCol[i];
           throw CException(e.str());
       }
   }
   _colDim = newColDim;
   _colSite = &newColSite;
 }
shared_ptr< CRConnectivity > CRConnectivity::multiply (const CRConnectivity & b, const bool implicitDiagonal) const
Definition at line 168 of file CRConnectivity.cpp.
References _col, _colDim, _colSite, _row, _rowDim, _rowSite, add(), addCount(), CRConnectivity(), finishAdd(), finishCount(), and initCount().
Referenced by COMETModel< T >::coarsenInterfaceCells(), Mesh::getCellCells(), Mesh::getCellCells2(), FluentReader::getCellNodes(), Mesh::getFaceCells2(), and COMETModel< T >::MakeInteriorCoarseMesh().
 {
   const bool isSquared = (&b == this);
   if (_colDim != b._rowDim)
     cerr << "invalid connectivity multiplication" << endl;
   shared_ptr<CRConnectivity> prPtr(new CRConnectivity(*_rowSite,*b._colSite));
   CRConnectivity& pr = *prPtr;
   pr.initCount();
   const Array<int>& myRow = *_row;
   const Array<int>& myCol = *_col;
   const Array<int>& bRow = *b._row;
   const Array<int>& bCol = *b._col;
   Array<bool> marker(b._colDim);
   Array<int> marked(b._colDim);
   for(int i=0; i<b._colDim; i++)
   {
       marker[i] = false;
       marked[i] = 0;
   }
   for(int i=0; i<_rowDim; i++)
   {
       int nMarked = 0;
       for(int ir = myRow[i]; ir<myRow[i+1]; ir++)
       {
           const int ja = myCol[ir];
           if (isSquared)
           {
               if (!marker[ja])
               {
                   marker[ja] = true;
                   if (ja  != i || !implicitDiagonal)
                     pr.addCount(i,1);
                   marked[nMarked++] = ja;
               }
           }
           for (int rb = bRow[ja]; rb<bRow[ja+1];  rb++)
           {
               const int jb = bCol[rb];
               if (!marker[jb])
               {
                   marker[jb] = true;
                   if (jb  != i || !implicitDiagonal)
                     pr.addCount(i,1);
                   marked[nMarked++] = jb;
               }
           }
       }
       for(int n=0; n<nMarked; n++)
         marker[marked[n]] = false;
   }
   // for(int i=0; i<pr._rowDim;i++)
   //  cerr << i << " " << (*pr._row)[i] << endl;
   pr.finishCount();
   for(int i=0; i<_rowDim; i++)
   {
       int nMarked = 0;
       for(int ir = myRow[i]; ir<myRow[i+1]; ir++)
       {
           const int ja = myCol[ir];
           if (isSquared)
           {
               if (!marker[ja])
               {
                   marker[ja] = true;
                   if (ja  != i || !implicitDiagonal)
                     pr.add(i,ja);
                   marked[nMarked++] = ja;
               }
           }
           for (int rb = bRow[ja]; rb<bRow[ja+1];  rb++)
           {
               const int jb = bCol[rb];
               if (!marker[jb])
               {
                   marker[jb] = true;
                   if (jb  != i || !implicitDiagonal)
                     pr.add(i,jb);
                   marked[nMarked++] = jb;
               }
           }
       }
       for(int n=0; n<nMarked; n++)
         marker[marked[n]] = false;
   }
   pr.finishAdd();
   return prPtr;
 }
int CRConnectivity::operator() (const int i, const int j) const inline
Definition at line 135 of file CRConnectivity.h.
References _col.
   {
     return (*_col)[(*_row)[i]+j];
   }
int& CRConnectivity::operator() (const int i, const int j) inline
returns the index of the j'th non zero column for row i
Definition at line 145 of file CRConnectivity.h.
References _col.
   {
     return (*_col)[(*_row)[i]+j];
   }
void CRConnectivity::reorder (const Array< int > & indices)
Definition at line 687 of file CRConnectivity.cpp.
References _col, and Array< T >::getLength().
Referenced by MeshPartitioner::fiedler_partition().
 {
   Array<int>& myCol       = *_col;
   for ( int i = 0; i < myCol.getLength(); i++ )
        myCol[i]   = indices[ myCol[i] ];
 }
void CRConnectivity::resizeLocalToGlobalMap (int size) inline
direct access to row and col array
Definition at line 177 of file CRConnectivity.h.
References _localToGlobalMap.
   {
      _localToGlobalMap = shared_ptr< Array<int> > ( new Array<int>(size) );
   }
void CRConnectivity::setConnType (CRTYPE type) inline
Definition at line 204 of file CRConnectivity.h.
References _connType.
{
       _connType = type;
   }
Member Data Documentation
shared_ptr<Array<int> > CRConnectivity::_col private
Definition at line 220 of file CRConnectivity.h.
Referenced by createOffset(), finishCount(), getCoeffPosition(), getCol(), getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), getMultiTranspose(), getSubset(), getTranspose(), localize(), multiply(), operator()(), and reorder().
int CRConnectivity::_colDim mutable private
Definition at line 218 of file CRConnectivity.h.
Referenced by CRConnectivity(), getColDim(), getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), getMultiTranspose(), localize(), multiply(), and ~CRConnectivity().
StorageSite const* CRConnectivity::_colSite mutable private
Definition at line 216 of file CRConnectivity.h.
Referenced by createOffset(), getColSite(), getMultiTranspose(), getSubset(), getTranspose(), localize(), and multiply().
CRTYPE CRConnectivity::_connType private
Definition at line 225 of file CRConnectivity.h.
Referenced by getConnType(), and setConnType().
shared_ptr<Array<int> > CRConnectivity::_globalToLocalMap private
Definition at line 221 of file CRConnectivity.h.
Referenced by getGlobalToLocalMap(), getGlobalToLocalMapPtr(), getLocalizedSubset(), and getLocalizedSubsetOfFaceCells().
map<int,int> CRConnectivity::_globalToLocalMapper private
Definition at line 222 of file CRConnectivity.h.
Referenced by getGlobalToLocalMapper().
shared_ptr<Array<int> > CRConnectivity::_localToGlobalMap private
Definition at line 223 of file CRConnectivity.h.
Referenced by getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), getLocalToGlobalMap(), getLocalToGlobalMapPtr(), and resizeLocalToGlobalMap().
map<const CRConnectivity*, PairToColMapping*> CRConnectivity::_pairToColMappings mutable private
Definition at line 224 of file CRConnectivity.h.
Referenced by clearPairToColMapping(), getPairToColMapping(), and ~CRConnectivity().
shared_ptr<Array<int> > CRConnectivity::_row private
Definition at line 219 of file CRConnectivity.h.
Referenced by createOffset(), finishAdd(), finishCount(), getCoeffPosition(), getCount(), getLocalizedSubset(), getLocalizedSubsetOfFaceCells(), getMultiTranspose(), getRow(), getSubset(), getTranspose(), initCount(), and multiply().
int CRConnectivity::_rowDim mutable private
Definition at line 217 of file CRConnectivity.h.
Referenced by CRConnectivity(), finishAdd(), finishCount(), getMultiTranspose(), getRowDim(), getTranspose(), initCount(), multiply(), and ~CRConnectivity().
StorageSite const* CRConnectivity::_rowSite mutable private
Definition at line 215 of file CRConnectivity.h.
Referenced by getMultiTranspose(), getRowSite(), getTranspose(), and multiply().
The documentation for this class was generated from the following files:
CRConnectivity.h
CRConnectivity.cpp