Memosa-FVM: DiffusionDiscretization< X, Diag, OffDiag > Class Template Reference
DiffusionDiscretization< X, Diag, OffDiag > Class Template Reference
#include <DiffusionDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Gradient< X > XGrad
typedef Array< int > IntArray
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Array< XGrad > GradArray
Public Member Functions
DiffusionDiscretization (const MeshList &meshes, const GeomFields &geomFields, Field &varField, const Field &diffusivityField, const Field &varGradientField, const T_Scalar thickness=0.0)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
Field & _varField
const Field & _diffusivityField
const Field & _varGradientField
const T_Scalar _thickness
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class DiffusionDiscretization< X, Diag, OffDiag >
Definition at line 31 of file DiffusionDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler DiffusionDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 39 of file DiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> DiffusionDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 37 of file DiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray DiffusionDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 38 of file DiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<XGrad> DiffusionDiscretization< X, Diag, OffDiag >::GradArray
Definition at line 49 of file DiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<int> DiffusionDiscretization< X, Diag, OffDiag >::IntArray
Definition at line 42 of file DiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar DiffusionDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 35 of file DiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> DiffusionDiscretization< X, Diag, OffDiag >::TArray
Definition at line 45 of file DiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> DiffusionDiscretization< X, Diag, OffDiag >::VectorT3
Definition at line 46 of file DiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> DiffusionDiscretization< X, Diag, OffDiag >::VectorT3Array
Definition at line 47 of file DiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> DiffusionDiscretization< X, Diag, OffDiag >::XArray
Definition at line 44 of file DiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Gradient<X> DiffusionDiscretization< X, Diag, OffDiag >::XGrad
Definition at line 41 of file DiffusionDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > DiffusionDiscretization< X, Diag, OffDiag >::DiffusionDiscretization (const MeshList & meshes, const GeomFields & geomFields, Field & varField, const Field & diffusivityField, const Field & varGradientField, const T_Scalar thickness = 0.0) inline
Definition at line 51 of file DiffusionDiscretization.h.
                                                         :
       Discretization(meshes),
       _geomFields(geomFields),
       _varField(varField),
       _diffusivityField(diffusivityField),
       _varGradientField(varGradientField),
       _thickness(thickness)
   {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void DiffusionDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 65 of file DiffusionDiscretization.h.
References DiffusionDiscretization< X, Diag, OffDiag >::_diffusivityField, DiffusionDiscretization< X, Diag, OffDiag >::_geomFields, DiffusionDiscretization< X, Diag, OffDiag >::_thickness, DiffusionDiscretization< X, Diag, OffDiag >::_varField, DiffusionDiscretization< X, Diag, OffDiag >::_varGradientField, GeomFields::area, GeomFields::areaMag, GeomFields::coordinate, dot(), Mesh::getAllFaceGroups(), Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), Mesh::getFaceCells(), MultiFieldMatrix::getMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), FaceGroup::groupType, harmonicAverage(), GeomFields::ibType, Mesh::IBTYPE_BOUNDARY, Mesh::IBTYPE_FLUID, mag(), FaceGroup::site, and GeomFields::volume.
   {
     const StorageSite& cells = mesh.getCells();
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,
                                                              cVarIndex));
     const VectorT3Array& cellCentroid =
       dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[cells]);
     const TArray& cellVolume =
       dynamic_cast<const TArray&>(_geomFields.volume[cells]);
     DiagArray& diag = matrix.getDiag();
     const XArray& xCell = dynamic_cast<const XArray&>(xField[cVarIndex]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     const GradArray& xGradCell =
       dynamic_cast<const GradArray&>(_varGradientField[cells]);
     const TArray& diffCell =
       dynamic_cast<const TArray&>(_diffusivityField[cells]);
     const IntArray& ibType = dynamic_cast<const IntArray&>(_geomFields.ibType[cells]);
     foreach(const FaceGroupPtr fgPtr, mesh.getAllFaceGroups())
       {
         const FaceGroup& fg = *fgPtr;
         if (fg.groupType == "dielectric interface")
           {
             const StorageSite& faces = fg.site;
             const int nFaces = faces.getCount();
             const CRConnectivity& faceCells = mesh.getFaceCells(faces);
             const VectorT3Array& faceArea =
               dynamic_cast<const VectorT3Array&>(_geomFields.area[faces]);
             const TArray& faceAreaMag =
               dynamic_cast<const TArray&>(_geomFields.areaMag[faces]);
             //const VectorT3Array& faceCentroid =
             //  dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[faces]);
             CCAssembler& assembler = matrix.getPairWiseAssembler(faceCells);
             //cout << "doing dielectric interface " << endl;
             for(int f=0; f<nFaces; f++)
               {
                 const int c0 = faceCells(f,0);
                 const int c1 = faceCells(f,1);
                 //T_Scalar vol0 = cellVolume[c0];
                 //T_Scalar vol1 = cellVolume[c1];
                 VectorT3 ds=cellCentroid[c1]-cellCentroid[c0];
                 T_Scalar dsMag = mag(ds);
                 T_Scalar faceDiffusivity = harmonicAverage(diffCell[c0],diffCell[c1]);
                 T_Scalar sign(NumTypeTraits<T_Scalar>::getUnity());
                 if (dot(faceArea[f],ds) < 0.0)
                   sign *= -1.0;
                 const T_Scalar diffMetric = sign * faceAreaMag[f] / (dsMag + 0.5* _thickness);
                 const T_Scalar diffCoeff = faceDiffusivity*diffMetric;
                 //const T_Scalar volume = faceAreaMag[f] * _thickness;
                 //const T_Scalar src = 1.0;
                 const X dFlux = diffCoeff*(xCell[c1]-xCell[c0]);
                 rCell[c0] += dFlux;
                 rCell[c1] -= dFlux;
                 assembler.getCoeff01(f) +=diffCoeff;
                 assembler.getCoeff10(f) +=diffCoeff;
                 diag[c0] -= diffCoeff;
                 diag[c1] -= diffCoeff;
                 /*
                 cout << " c0 and c1 " << c0 << " " << c1 << endl;
                 cout << " diffcell " << diffCell[c0] << " " << diffCell[c1] << " " << faceDiffusivity << endl;
                 cout << " diffmetric  " << diffMetric << endl;
                 cout << "diffCoeff  " << diffCoeff << endl;
                 */
               }
           }
         else
           {
             const StorageSite& faces = fg.site;
             const int nFaces = faces.getCount();
             const CRConnectivity& faceCells = mesh.getFaceCells(faces);
             const VectorT3Array& faceArea =
               dynamic_cast<const VectorT3Array&>(_geomFields.area[faces]);
             const TArray& faceAreaMag =
               dynamic_cast<const TArray&>(_geomFields.areaMag[faces]);
             const VectorT3Array& faceCentroid =
               dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[faces]);
             CCAssembler& assembler = matrix.getPairWiseAssembler(faceCells);
             for(int f=0; f<nFaces; f++)
               {
                 const int c0 = faceCells(f,0);
                 const int c1 = faceCells(f,1);
                 T_Scalar vol0 = cellVolume[c0];
                 T_Scalar vol1 = cellVolume[c1];
                 VectorT3 ds=cellCentroid[c1]-cellCentroid[c0];
                 // for ib faces ignore the solid cell and use the face centroid for diff metric
                 if (((ibType[c0] == Mesh::IBTYPE_FLUID)
                      && (ibType[c1] == Mesh::IBTYPE_BOUNDARY)) ||
                     ((ibType[c1] == Mesh::IBTYPE_FLUID)
                      && (ibType[c0] == Mesh::IBTYPE_BOUNDARY)))
                   {
                     if (ibType[c0] == Mesh::IBTYPE_FLUID)
                       {
                         vol1 = 0.;
                         ds = faceCentroid[f]-cellCentroid[c0];
                       }
                     else
                       {
                         vol0 = 0.;
                         ds = cellCentroid[c1]-faceCentroid[f];
                       }
                   }
                 T_Scalar faceDiffusivity(1.0);
                 if (vol0 == 0.)
                   faceDiffusivity = diffCell[c1];
                 else if (vol1 == 0.)
                   faceDiffusivity = diffCell[c0];
                 else
                   faceDiffusivity = harmonicAverage(diffCell[c0],diffCell[c1]);
                 const T_Scalar diffMetric = faceAreaMag[f]*faceAreaMag[f]/dot(faceArea[f],ds);
                 const T_Scalar diffCoeff = faceDiffusivity*diffMetric;
                 const VectorT3 secondaryCoeff = faceDiffusivity*(faceArea[f]-ds*diffMetric);
                 const XGrad gradF = (xGradCell[c0]*vol0+xGradCell[c1]*vol1)/(vol0+vol1);
                 const X dFluxSecondary = gradF*secondaryCoeff;
                 const X dFlux = diffCoeff*(xCell[c1]-xCell[c0]) + dFluxSecondary;
                 rCell[c0] += dFlux;
                 rCell[c1] -= dFlux;
                 assembler.getCoeff01(f) +=diffCoeff;
                 assembler.getCoeff10(f) +=diffCoeff;
                 diag[c0] -= diffCoeff;
                 diag[c1] -= diffCoeff;
                 //cout <<"dflux" << dFlux << endl;
 /*
                 cout << " c0 and c1 " << c0 << " " << c1 << endl;
                 cout << " diffcell " << diffCell[c0] << " " << diffCell[c1] << " " << faceDiffusivity << endl;
                 cout << " diffmetric  " << diffMetric << endl;
                 cout << "diffCoeff  " << diffCoeff << endl;
 */
               }
           }
       }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const Field& DiffusionDiscretization< X, Diag, OffDiag >::_diffusivityField private
Definition at line 236 of file DiffusionDiscretization.h.
Referenced by DiffusionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& DiffusionDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 234 of file DiffusionDiscretization.h.
Referenced by DiffusionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const T_Scalar DiffusionDiscretization< X, Diag, OffDiag >::_thickness private
Definition at line 238 of file DiffusionDiscretization.h.
Referenced by DiffusionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > Field& DiffusionDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 235 of file DiffusionDiscretization.h.
Referenced by DiffusionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& DiffusionDiscretization< X, Diag, OffDiag >::_varGradientField private
Definition at line 237 of file DiffusionDiscretization.h.
Referenced by DiffusionDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
DiffusionDiscretization.h