Memosa-FVM: SchemeReader Class Reference
SchemeReader Class Reference
#include <SchemeReader.h>
Public Member Functions
SchemeReader (const string &fileName)
virtual ~SchemeReader ()
Public Member Functions inherited from Reader
Reader (const string &fileName)
virtual ~Reader ()
void resetFilePtr ()
string readLine ()
void close ()
Protected Member Functions
int getNextSection ()
void closeSection ()
int closeSectionBinary (const int currentId)
int readInt (const bool isBinary)
void skipInt (const int n, const bool isBinary)
char getNextChar ()
int moveToListOpen ()
void moveToListClose ()
void moveToListCloseBinary ()
void readHeader (int &i1, int &i2, int &i3, int &i4, int &i5)
int readListLength ()
void readList (char *buffer)
Additional Inherited Members
Protected Attributes inherited from Reader
const string _fileName
FILE * _fp
Detailed Description
Definition at line 13 of file SchemeReader.h.
Constructor & Destructor Documentation
SchemeReader::SchemeReader (const string & fileName)
Definition at line 7 of file SchemeReader.cpp.
                                                  :
   Reader(fileName)
 {}
SchemeReader::~SchemeReader () virtual
Definition at line 11 of file SchemeReader.cpp.
 {}
Member Function Documentation
void SchemeReader::closeSection () protected
Definition at line 148 of file SchemeReader.cpp.
References moveToListClose().
Referenced by FluentReader::read(), FluentReader::readCells(), FluentReader::readFacePairs(), FluentReader::readFaces(), and FluentReader::readNodes().
 {
   moveToListClose();
 }
int SchemeReader::closeSectionBinary (const int currentId) protected
Definition at line 154 of file SchemeReader.cpp.
References Reader::_fp.
Referenced by FluentReader::read(), FluentReader::readCells(), FluentReader::readFacePairs(), FluentReader::readFaces(), and FluentReader::readNodes().
 {
   //  char c;
   int id;
   //  moveToListOpen();
   //moveToListClose();
   //moveToListOpen();
   do
   {
       getc(_fp);
 //       while ((c = getc(_fp)) != '\n')
 //      if (EOF == c)
 //         {
 //             cerr << "error closing binary section: expected " << currentId
 //                  << " , found EOF " << endl;
 //             return EOF;
 //         }
     }
   while (1 != fscanf(_fp,"End of Binary Section %d",&id));
   if (currentId != id)
     cerr << "error closing binary section: expected " << currentId
          << " , found " << id << endl;
   return id;
 }
char SchemeReader::getNextChar () protected
Definition at line 15 of file SchemeReader.cpp.
References Reader::_fp.
Referenced by moveToListOpen().
 {
   char c;
   while ((c = getc(_fp)) != EOF)
     if (isprint(c) && !isspace(c))
       break;
   return(c);
 }
int SchemeReader::getNextSection () protected
Definition at line 132 of file SchemeReader.cpp.
References Reader::_fp, and moveToListOpen().
Referenced by FluentReader::read().
 {
   if (moveToListOpen() == EOF)
     return EOF;
   int id;
   if (fscanf(_fp,"%d", &id) != 1)
   {
       cerr << "error reading id "<< endl;
   }
   return id;
 }
void SchemeReader::moveToListClose () protected
Definition at line 43 of file SchemeReader.cpp.
References Reader::_fp.
Referenced by closeSection(), FluentReader::read(), and readHeader().
 {
   char c;
   while ((c = getc(_fp)) != EOF)
     switch (c)
       {
       case '(':
         moveToListClose();
         break;
       case ')':
         return;
       }
 }
void SchemeReader::moveToListCloseBinary () protected
Definition at line 116 of file SchemeReader.cpp.
References Reader::_fp, and moveToListOpen().
 {
   char c;
   int id;
   moveToListOpen();
   do
     {
       while ((c = getc(_fp)) != '\n')
         if (EOF == c)
           return;
     }
   while (1 != fscanf(_fp,"End of Binary Section %6d",&id));
 }
int SchemeReader::moveToListOpen () protected
Definition at line 28 of file SchemeReader.cpp.
References getNextChar().
Referenced by getNextSection(), moveToListCloseBinary(), FluentReader::read(), FluentReader::readFacePairs(), FluentReader::readFaces(), readHeader(), FluentReader::readNodes(), and FluentReader::readVectorData().
 {
   char c;
   while ((c = getNextChar()))
     if ((char) c == '(')
       return 0;
     else if (c == EOF)
       return EOF;
   return EOF;
 }
void SchemeReader::readHeader (int & i1, int & i2, int & i3, int & i4, int & i5) protected
Definition at line 182 of file SchemeReader.cpp.
References Reader::_fp, moveToListClose(), and moveToListOpen().
Referenced by FluentReader::readCells(), FluentReader::readFacePairs(), FluentReader::readFaces(), and FluentReader::readNodes().
 {
   moveToListOpen();
   if (fscanf(_fp, "%x%x%x%x",&i1,&i2,&i3,&i4) != 4)
   {
       cerr << "error reading header" << endl;
       //      readerError("Error reading the mesh header", DBG_HERE);
   }
   /* read shape, not always availabe */
   if (fscanf(_fp,"%x",&i5) != 1)
     i5 = -1;
   moveToListClose();
 }
int SchemeReader::readInt (const bool isBinary) protected
Definition at line 200 of file SchemeReader.cpp.
References Reader::_fp.
Referenced by FluentReader::readFacePairs(), and FluentReader::readFaces().
 {
   int i;
   if (isBinary ?
       (1 != fread(&i, sizeof(int), 1, _fp)) :
       (1 != fscanf(_fp,"%x",&i)))
     cerr << "Error reading int " << endl;
   return i;
 }
void SchemeReader::readList (char * buffer) protected
Definition at line 88 of file SchemeReader.cpp.
References Reader::_fp.
Referenced by FluentReader::read().
 {
   char c;
   int parenLevel=0;
   int buffSize=0;
   while ((c = getc(_fp)) != EOF)
   {
       if (c == '(')
         parenLevel++;
       if (parenLevel > 0)
       {
           buffer[buffSize] = c;
           buffSize++;
       }
       if (c == ')')
         parenLevel--;
       if (parenLevel == 0  && buffSize > 0)
         return;
   }
   throw CException("EOF reached while reading list");
 }
int SchemeReader::readListLength () protected
Definition at line 59 of file SchemeReader.cpp.
References Reader::_fp.
Referenced by FluentReader::read().
 {
   char c;
   int parenLevel=0;
   int buffSize=0;
   while ((c = getc(_fp)) != EOF)
   {
       if (c == '(')
         parenLevel++;
       if (parenLevel > 0)
       {
           buffSize++;
       }
       if (c == ')')
         parenLevel--;
       if (parenLevel == 0  && buffSize > 0)
         return buffSize;
   }
   throw CException("EOF reached while reading list");
 }
void SchemeReader::skipInt (const int n, const bool isBinary) protected
Definition at line 211 of file SchemeReader.cpp.
References Reader::_fp.
Referenced by FluentReader::readFaces().
 {
   int i;
   for (int n=0; n<count; n++)
   {
       if (isBinary ?
           (1 != fread(&i, sizeof(int), 1, _fp)) :
           (1 != fscanf(_fp,"%x",&i)))
         cerr << "Error reading int " << endl;
   }
 }
The documentation for this class was generated from the following files:
SchemeReader.h
SchemeReader.cpp