Memosa-FVM: CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler Class Reference
CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler Class Reference
#include <CRMatrix.h>
Public Member Functions
PairWiseAssembler (Array< OffDiag > &coeffs, const Array< Vector< int, 2 > > &pairToCol)
OffDiag & getCoeff01 (const int np)
OffDiag & getCoeff10 (const int np)
void addCoeffsSymmetric (const int np, const OffDiag &c)
void addCoeffs (const int np, const OffDiag &c01, const OffDiag &c10)
void addCoeff01 (const int np, const OffDiag &c01)
void addCoeff10 (const int np, const OffDiag &c10)
Private Attributes
Array< OffDiag > & _coeffs
const Array< Vector< int, 2 > > & _pairToCol
Detailed Description
template<class T_Diag, class T_OffDiag, class X>
class CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler
Embedded class used for easy (ie. no search) access to matrix entries for the special case of face based finite volume discretizations. Works in conjunction with a pairwise access mapping provided by CRConnectivity
Definition at line 117 of file CRMatrix.h.
Constructor & Destructor Documentation
template<class T_Diag, class T_OffDiag, class X> CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::PairWiseAssembler (Array< OffDiag > & coeffs, const Array< Vector< int, 2 > > & pairToCol) inline
Definition at line 120 of file CRMatrix.h.
                                                               :
       _coeffs(coeffs),
       _pairToCol(pairToCol)
     {}
Member Function Documentation
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeff01 (const int np, const OffDiag & c01) inline
Definition at line 148 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_coeffs, and CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_pairToCol.
     {
       _coeffs[_pairToCol[np][0]] += c01;
     }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeff10 (const int np, const OffDiag & c10) inline
Definition at line 153 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_coeffs, and CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_pairToCol.
     {
       _coeffs[_pairToCol[np][1]] += c10;
     }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeffs (const int np, const OffDiag & c01, const OffDiag & c10) inline
Definition at line 142 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_coeffs, and CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_pairToCol.
     {
       _coeffs[_pairToCol[np][0]] += c01;
       _coeffs[_pairToCol[np][1]] += c10;
     }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeffsSymmetric (const int np, const OffDiag & c) inline
Definition at line 136 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_coeffs, and CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_pairToCol.
     {
       _coeffs[_pairToCol[np][0]] += c;
       _coeffs[_pairToCol[np][1]] += c;
     }
template<class T_Diag, class T_OffDiag, class X> OffDiag& CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01 (const int np) inline
Definition at line 126 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_coeffs, and CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_pairToCol.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyDirichletBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyExtrapolationBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC(), StructureBCS< X, Diag, OffDiag >::applyInterfaceBC(), PlateBCS< X, Diag, OffDiag >::applyInterfaceBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyInterfaceBC(), BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), GenericBCS< X, Diag, OffDiag >::applySymmetryBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applySymmetryBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::applySymmetryBC(), GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::applySymmetryBC(), DriftDiscretization< X, Diag, OffDiag >::discretize(), GenericIBDiscretization< X, Diag, OffDiag >::discretize(), PhononConvectionDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization< X, Diag, OffDiag >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), ElecDiffusionDiscretization< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), and PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces().
     {
       return _coeffs[_pairToCol[np][0]];
     }
template<class T_Diag, class T_OffDiag, class X> OffDiag& CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10 (const int np) inline
Definition at line 131 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_coeffs, and CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_pairToCol.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyDirichletBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyExtrapolationBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC(), StructureBCS< X, Diag, OffDiag >::applyInterfaceBC(), PlateBCS< X, Diag, OffDiag >::applyInterfaceBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyInterfaceBC(), BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), StructureBCS< X, Diag, OffDiag >::applySymmetryBC(), PlateBCS< X, Diag, OffDiag >::applySymmetryBC(), GenericBCS< X, Diag, OffDiag >::applySymmetryBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applySymmetryBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::applySymmetryBC(), GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::applySymmetryBC(), StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC(), PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC(), DriftDiscretization< X, Diag, OffDiag >::discretize(), GenericIBDiscretization< X, Diag, OffDiag >::discretize(), PhononConvectionDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization< X, Diag, OffDiag >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), ElecDiffusionDiscretization< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize(), WallDiscretization< X, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), and PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces().
     {
       return _coeffs[_pairToCol[np][1]];
     }
Member Data Documentation
template<class T_Diag, class T_OffDiag, class X> Array<OffDiag>& CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_coeffs private
Definition at line 158 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeff10(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeffs(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeffsSymmetric(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), and CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10().
template<class T_Diag, class T_OffDiag, class X> const Array<Vector<int,2> >& CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::_pairToCol private
Definition at line 159 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeff10(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeffs(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::addCoeffsSymmetric(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), and CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10().
The documentation for this class was generated from the following file:
CRMatrix.h