Memosa-FVM: SourceDiscretizationforFracture< T, Diag, OffDiag > Class Template Reference
SourceDiscretizationforFracture< T, Diag, OffDiag > Class Template Reference
#include <SourceDiscretizationforFracture.h>
Public Types
typedef Array< T > TArray
typedef Vector< T, 3 > VectorT3
typedef CRMatrix< Diag,
OffDiag, T > CCMatrix
typedef CCMatrix::DiagArray DiagArray
Public Member Functions
SourceDiscretizationforFracture (const MeshList &meshes, const GeomFields &geomFields, const Field &varField, const Field &sourceField, const Field &sourcecoefField)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const Field & _sourceField
const Field & _sourcecoefField
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class T, class Diag, class OffDiag>
class SourceDiscretizationforFracture< T, Diag, OffDiag >
Definition at line 19 of file SourceDiscretizationforFracture.h.
Member Typedef Documentation
template<class T , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,T> SourceDiscretizationforFracture< T, Diag, OffDiag >::CCMatrix
Definition at line 31 of file SourceDiscretizationforFracture.h.
template<class T , class Diag , class OffDiag > typedef CCMatrix::DiagArray SourceDiscretizationforFracture< T, Diag, OffDiag >::DiagArray
Definition at line 33 of file SourceDiscretizationforFracture.h.
template<class T , class Diag , class OffDiag > typedef Array<T> SourceDiscretizationforFracture< T, Diag, OffDiag >::TArray
Definition at line 27 of file SourceDiscretizationforFracture.h.
template<class T , class Diag , class OffDiag > typedef Vector<T,3> SourceDiscretizationforFracture< T, Diag, OffDiag >::VectorT3
Definition at line 29 of file SourceDiscretizationforFracture.h.
Constructor & Destructor Documentation
template<class T , class Diag , class OffDiag > SourceDiscretizationforFracture< T, Diag, OffDiag >::SourceDiscretizationforFracture (const MeshList & meshes, const GeomFields & geomFields, const Field & varField, const Field & sourceField, const Field & sourcecoefField) inline
Definition at line 35 of file SourceDiscretizationforFracture.h.
                                                       :
     Discretization(meshes),
     _geomFields(geomFields),
     _varField(varField),
     _sourceField(sourceField),
     _sourcecoefField(sourcecoefField)
    {}
Member Function Documentation
template<class T , class Diag , class OffDiag > void SourceDiscretizationforFracture< T, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & , MultiField & rField) inline virtual
Implements Discretization.
Definition at line 48 of file SourceDiscretizationforFracture.h.
References SourceDiscretizationforFracture< T, Diag, OffDiag >::_geomFields, SourceDiscretizationforFracture< T, Diag, OffDiag >::_sourcecoefField, SourceDiscretizationforFracture< T, Diag, OffDiag >::_sourceField, SourceDiscretizationforFracture< T, Diag, OffDiag >::_varField, Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), MultiFieldMatrix::getMatrix(), StorageSite::getSelfCount(), and GeomFields::volume.
   {
     const StorageSite& cells = mesh.getCells();
     const TArray& cellVolume = dynamic_cast<const TArray&>(_geomFields.volume[cells]);
     const TArray& source = dynamic_cast<const TArray&>(_sourceField[cells]);
     const TArray& sourcecoef = dynamic_cast<const TArray&>(_sourcecoefField[cells]);
     const MultiField::ArrayIndex cVarIndex(&_varField, &cells);
     TArray& rCell = dynamic_cast<TArray&>(rField[cVarIndex]);
     const int nCells = cells.getSelfCount();
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     DiagArray& diag = matrix.getDiag();
     for(int c=0; c<nCells; c++)
     {
         rCell[c] += cellVolume[c]*(1.0+source[c]);
                 diag[c] += cellVolume[c]*sourcecoef[c];
           //if (c >= 400){
           //cout << c << ": " << cellVolume[c] << " " << diag[c] << "\n" << endl;}
     }
   }
Member Data Documentation
template<class T , class Diag , class OffDiag > const GeomFields& SourceDiscretizationforFracture< T, Diag, OffDiag >::_geomFields private
Definition at line 81 of file SourceDiscretizationforFracture.h.
Referenced by SourceDiscretizationforFracture< T, Diag, OffDiag >::discretize().
template<class T , class Diag , class OffDiag > const Field& SourceDiscretizationforFracture< T, Diag, OffDiag >::_sourcecoefField private
Definition at line 84 of file SourceDiscretizationforFracture.h.
Referenced by SourceDiscretizationforFracture< T, Diag, OffDiag >::discretize().
template<class T , class Diag , class OffDiag > const Field& SourceDiscretizationforFracture< T, Diag, OffDiag >::_sourceField private
Definition at line 83 of file SourceDiscretizationforFracture.h.
Referenced by SourceDiscretizationforFracture< T, Diag, OffDiag >::discretize().
template<class T , class Diag , class OffDiag > const Field& SourceDiscretizationforFracture< T, Diag, OffDiag >::_varField private
Definition at line 82 of file SourceDiscretizationforFracture.h.
Referenced by SourceDiscretizationforFracture< T, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
SourceDiscretizationforFracture.h