Memosa-FVM: TimeDerivativeDiscretization< X, Diag, OffDiag > Class Template Reference
TimeDerivativeDiscretization< X, Diag, OffDiag > Class Template Reference
#include <TimeDerivativeDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Array< int > IntArray
Public Member Functions
TimeDerivativeDiscretization (const MeshList &meshes, const GeomFields &geomFields, Field &varField, Field &varN1Field, Field &varN2Field, const Field &densityField, const T_Scalar dT)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const Field & _varN1Field
const Field & _varN2Field
const Field & _densityField
const T_Scalar _dT
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class TimeDerivativeDiscretization< X, Diag, OffDiag >
Definition at line 18 of file TimeDerivativeDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler TimeDerivativeDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 25 of file TimeDerivativeDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> TimeDerivativeDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 23 of file TimeDerivativeDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray TimeDerivativeDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 24 of file TimeDerivativeDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<int> TimeDerivativeDiscretization< X, Diag, OffDiag >::IntArray
Definition at line 29 of file TimeDerivativeDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar TimeDerivativeDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 21 of file TimeDerivativeDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> TimeDerivativeDiscretization< X, Diag, OffDiag >::TArray
Definition at line 28 of file TimeDerivativeDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> TimeDerivativeDiscretization< X, Diag, OffDiag >::XArray
Definition at line 27 of file TimeDerivativeDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > TimeDerivativeDiscretization< X, Diag, OffDiag >::TimeDerivativeDiscretization (const MeshList & meshes, const GeomFields & geomFields, Field & varField, Field & varN1Field, Field & varN2Field, const Field & densityField, const T_Scalar dT) inline
Definition at line 31 of file TimeDerivativeDiscretization.h.
                                                   :
       Discretization(meshes),
       _geomFields(geomFields),
       _varField(varField),
       _varN1Field(varN1Field),
       _varN2Field(varN2Field),
       _densityField(densityField),
       _dT(dT)
       {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 47 of file TimeDerivativeDiscretization.h.
References TimeDerivativeDiscretization< X, Diag, OffDiag >::_densityField, TimeDerivativeDiscretization< X, Diag, OffDiag >::_dT, TimeDerivativeDiscretization< X, Diag, OffDiag >::_geomFields, TimeDerivativeDiscretization< X, Diag, OffDiag >::_varField, TimeDerivativeDiscretization< X, Diag, OffDiag >::_varN1Field, TimeDerivativeDiscretization< X, Diag, OffDiag >::_varN2Field, Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), MultiFieldMatrix::getMatrix(), StorageSite::getSelfCount(), Field::hasArray(), GeomFields::ibType, Mesh::IBTYPE_FLUID, GeomFields::ibTypeN1, GeomFields::volume, GeomFields::volumeN1, and GeomFields::volumeN2.
   {
     const StorageSite& cells = mesh.getCells();
     const TArray& density =
       dynamic_cast<const TArray&>(_densityField[cells]);
     const TArray& cellVolume =
       dynamic_cast<const TArray&>(_geomFields.volume[cells]);
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix =
       dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     DiagArray& diag = matrix.getDiag();
     const XArray& x = dynamic_cast<const XArray&>(_varField[cells]);
     const XArray& xN1 = dynamic_cast<const XArray&>(_varN1Field[cells]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     const int nCells = cells.getSelfCount();
     if (_varN2Field.hasArray(cells))
     {
         // second order
         const XArray& xN2 = dynamic_cast<const XArray&>(_varN2Field[cells]);
         T_Scalar onePointFive(1.5);
         T_Scalar two(2.0);
         T_Scalar pointFive(0.5);
         if (_geomFields.volumeN1.hasArray(cells))
         {
             const TArray& cellVolumeN1 =
               dynamic_cast<const TArray&>(_geomFields.volumeN1[cells]);
             const TArray& cellVolumeN2 =
               dynamic_cast<const TArray&>(_geomFields.volumeN2[cells]);
             for(int c=0; c<nCells; c++)
             {
                 const T_Scalar rhoVbydT = density[c]*cellVolume[c]/_dT;
                 const T_Scalar rhobydT = density[c]/_dT;
                 const T_Scalar term1 = onePointFive*cellVolume[c];
                 const T_Scalar term2 = two*cellVolumeN1[c];
                 const T_Scalar term3 = pointFive*cellVolumeN2[c];
                 rCell[c] -= rhobydT*(term1*x[c]- term2*xN1[c]
                                       + term3*xN2[c]);
                 diag[c] -= rhoVbydT*onePointFive;
             }
         }
         else
         {
             for(int c=0; c<nCells; c++)
             {
                 const T_Scalar rhoVbydT = density[c]*cellVolume[c]/_dT;
                 rCell[c] -= rhoVbydT*(onePointFive*x[c]- two*xN1[c]
                                       + pointFive*xN2[c]);
                 diag[c] -= rhoVbydT*onePointFive;
             }
         }
     }
     else
     {
         if (_geomFields.volumeN1.hasArray(cells))
         {
             const TArray& cellVolumeN1 =
               dynamic_cast<const TArray&>(_geomFields.volumeN1[cells]);
             for(int c=0; c<nCells; c++)
             {
                 const T_Scalar rhoVbydT = density[c]*cellVolume[c]/_dT;
                 const T_Scalar rhobydT = density[c]/_dT;
                 rCell[c] -= rhobydT*(cellVolume[c]*x[c]
                                      - cellVolumeN1[c]*xN1[c]);
                 diag[c] -= rhoVbydT;
             }
         }
         else if (_geomFields.ibTypeN1.hasArray(cells))
         {
             const IntArray& ibTypeN1 =
               dynamic_cast<const IntArray&>(_geomFields.ibTypeN1[cells]);
             const IntArray& ibType =
               dynamic_cast<const IntArray&>(_geomFields.ibType[cells]);
             for(int c=0; c<nCells; c++)
             {
                 const T_Scalar rhoVbydT = density[c]*cellVolume[c]/_dT;
                 if (ibTypeN1[c] == Mesh::IBTYPE_FLUID &&
                     (ibType[c] == Mesh::IBTYPE_FLUID))
                   rCell[c] -= rhoVbydT*(x[c]  - xN1[c]);
                 else if (ibType[c] == Mesh::IBTYPE_FLUID)
                   rCell[c] -= rhoVbydT*(x[c] );
                 diag[c] -= rhoVbydT;
             }
         }
         else
         {
             for(int c=0; c<nCells; c++)
             {
                 const T_Scalar rhoVbydT = density[c]*cellVolume[c]/_dT;
                 rCell[c] -= rhoVbydT*(x[c]- xN1[c]);
                 diag[c] -= rhoVbydT;
             }
         }
     }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const Field& TimeDerivativeDiscretization< X, Diag, OffDiag >::_densityField private
Definition at line 168 of file TimeDerivativeDiscretization.h.
Referenced by TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const T_Scalar TimeDerivativeDiscretization< X, Diag, OffDiag >::_dT private
Definition at line 169 of file TimeDerivativeDiscretization.h.
Referenced by TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& TimeDerivativeDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 164 of file TimeDerivativeDiscretization.h.
Referenced by TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& TimeDerivativeDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 165 of file TimeDerivativeDiscretization.h.
Referenced by TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& TimeDerivativeDiscretization< X, Diag, OffDiag >::_varN1Field private
Definition at line 166 of file TimeDerivativeDiscretization.h.
Referenced by TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& TimeDerivativeDiscretization< X, Diag, OffDiag >::_varN2Field private
Definition at line 167 of file TimeDerivativeDiscretization.h.
Referenced by TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
TimeDerivativeDiscretization.h