Memosa-FVM: FluentDataExporter< T > Class Template Reference
FluentDataExporter< T > Class Template Reference
#include <FluentDataExporter.h>
Public Types
typedef Array< T > TArray
Public Member Functions
FluentDataExporter (FluentReader &reader, const string fileName, const bool binary, const int atypeComponent)
void init ()
void closeSection ()
void writeScalarField (const Field &field, const int fluentFieldId)
void writeVectorField (const Field &field, const int fluentFieldId)
void finish ()
Private Attributes
FluentReader & _reader
FILE * _fp
const bool _binary
const int _atypeComponent
const int _sectionID
Detailed Description
template<class T>
class FluentDataExporter< T >
Definition at line 14 of file FluentDataExporter.h.
Member Typedef Documentation
template<class T > typedef Array<T> FluentDataExporter< T >::TArray
Definition at line 17 of file FluentDataExporter.h.
Constructor & Destructor Documentation
template<class T > FluentDataExporter< T >::FluentDataExporter (FluentReader & reader, const string fileName, const bool binary, const int atypeComponent) inline
Definition at line 19 of file FluentDataExporter.h.
References FluentDataExporter< T >::_fp.
                                                :
     _reader(reader),
     _fp(fopen(fileName.c_str(),"wb")),
     _binary(binary),
     _atypeComponent(atypeComponent),
     _sectionID(_binary ? 3300 : 300)
   {
     if (!_fp)
       throw CException("FluentDataExporter: cannot open file " + fileName +
                        "for writing");
   }
Member Function Documentation
template<class T > void FluentDataExporter< T >::closeSection () inline
Definition at line 39 of file FluentDataExporter.h.
References FluentDataExporter< T >::_binary, and FluentDataExporter< T >::_fp.
Referenced by FluentDataExporter< T >::writeScalarField(), and FluentDataExporter< T >::writeVectorField().
   {
     if (_binary)
       fprintf(_fp,"\nEnd of Binary Section   3300");
     fprintf(_fp,"))\n");
   }
template<class T > void FluentDataExporter< T >::finish () inline
Definition at line 177 of file FluentDataExporter.h.
References FluentDataExporter< T >::_fp.
   {
     fclose(_fp);
   }
template<class T > void FluentDataExporter< T >::init () inline
Definition at line 34 of file FluentDataExporter.h.
References FluentDataExporter< T >::_fp.
   {
     fprintf(_fp,"(4 (60 0 0 1 2 4 4 4 8 8 4))\n");
   }
template<class T > void FluentDataExporter< T >::writeScalarField (const Field & field, const int fluentFieldId) inline
Definition at line 46 of file FluentDataExporter.h.
References FluentDataExporter< T >::_atypeComponent, FluentDataExporter< T >::_binary, FluentDataExporter< T >::_fp, FluentDataExporter< T >::_reader, FluentDataExporter< T >::_sectionID, FluentDataExporter< T >::closeSection(), Mesh::getBoundaryFaceGroups(), Mesh::getCells(), FluentReader::getCellZones(), Mesh::getFaceCells(), Mesh::getFaces(), FluentReader::getFaceZones(), StorageSite::getOffset(), StorageSite::getSelfCount(), Field::hasArray(), FluentZone::iBeg, FluentZone::ID, FaceGroup::id, FluentZone::iEnd, FluentCellZone::interiorZoneIds, FluentCellZone::mesh, FaceGroup::site, and ScalarArrayWriter< T >::write().
   {
     FaceZonesMap& faceZones = _reader.getFaceZones();
     CellZonesMap& cellZones = _reader.getCellZones();
     ScalarArrayWriter<T> writer(_binary,0,_atypeComponent);
     foreach(const CellZonesMap::value_type& pos, cellZones)
     {
         const FluentCellZone& cz = *pos.second;
         const Mesh& mesh = *cz.mesh;
         const StorageSite& cells = mesh.getCells();
         const StorageSite& faces = mesh.getFaces();
         if (field.hasArray(cells))
         {
             const TArray& aCell = dynamic_cast<const TArray&>(field[cells]);
             fprintf(_fp,"(%d (%d %d 1 0 1 %d %d)\n(",
                     _sectionID, fluentFieldId, cz.ID,
                     cz.iBeg+1,cz.iEnd+1);
             writer.write(_fp,aCell,0,cells.getSelfCount());
             closeSection();
             foreach(const FaceGroupPtr fgPtr, mesh.getBoundaryFaceGroups())
             {
                 const FaceGroup& fg = *fgPtr;
                 const StorageSite& faces = fg.site;
                 const FluentFaceZone& fz = *faceZones[fg.id];
                 const CRConnectivity& faceCells = mesh.getFaceCells(faces);
                 fprintf(_fp,"(%d (%d %d 1 0 1 %d %d)\n(",
                         _sectionID, fluentFieldId, fz.ID,
                         fz.iBeg+1,fz.iEnd+1);
                 int cbeg = faceCells(0,1);
                 writer.write(_fp,aCell,cbeg,faces.getSelfCount());
                 closeSection();
             }
         }
         if (field.hasArray(faces))
         {
             const TArray& aFaces = dynamic_cast<const TArray&>(field[faces]);
             int faceOffset =0;
             foreach(int fzId, cz.interiorZoneIds)
             {
                 const FluentFaceZone& fz = *faceZones[fzId];
                 const int count = fz.iEnd-fz.iBeg+1;
                 fprintf(_fp,"(%d (%d %d 1 0 1 %d %d)\n(",
                         _sectionID, fluentFieldId, fz.ID,
                         fz.iBeg+1,fz.iEnd+1);
                 writer.write(_fp,aFaces,faceOffset,count);
                 closeSection();
                 faceOffset += count;
             }
             foreach(const FaceGroupPtr fgPtr, mesh.getBoundaryFaceGroups())
             {
                 const FaceGroup& fg = *fgPtr;
                 const StorageSite& faces = fg.site;
                 const FluentFaceZone& fz = *faceZones[fg.id];
                 fprintf(_fp,"(%d (%d %d 1 0 1 %d %d)\n(",
                         _sectionID, fluentFieldId, fz.ID,
                         fz.iBeg+1,fz.iEnd+1);
                 writer.write(_fp,aFaces,faces.getOffset(),faces.getSelfCount());
                 closeSection();
             }
         }
     }
   }
template<class T > void FluentDataExporter< T >::writeVectorField (const Field & field, const int fluentFieldId) inline
Definition at line 125 of file FluentDataExporter.h.
References FluentDataExporter< T >::_atypeComponent, FluentDataExporter< T >::_binary, FluentDataExporter< T >::_fp, FluentDataExporter< T >::_reader, FluentDataExporter< T >::_sectionID, FluentDataExporter< T >::closeSection(), Mesh::getBoundaryFaceGroups(), Mesh::getCells(), FluentReader::getCellZones(), Mesh::getFaceCells(), FluentReader::getFaceZones(), StorageSite::getSelfCount(), Field::hasArray(), FluentZone::iBeg, FluentZone::ID, FaceGroup::id, FluentZone::iEnd, FluentCellZone::mesh, FaceGroup::site, and VectorArrayWriter< T, N >::write().
   {
     typedef Array<Vector<T,3> > VectorT3Array;
     FaceZonesMap& faceZones = _reader.getFaceZones();
     CellZonesMap& cellZones = _reader.getCellZones();
     for(int nd=0; nd<3; nd++)
     {
         VectorArrayWriter<T,3> writer(_binary,nd,_atypeComponent);
         foreach(const CellZonesMap::value_type& pos, cellZones)
         {
             const FluentCellZone& cz = *pos.second;
             const Mesh& mesh = *cz.mesh;
             const StorageSite& cells = mesh.getCells();
             if (field.hasArray(cells))
             {
                 const VectorT3Array& aCell = dynamic_cast<const VectorT3Array&>(field[cells]);
                 fprintf(_fp,"(%d (%d %d 1 0 1 %d %d)\n(",
                         _sectionID, fluentFieldId+nd, cz.ID,
                         cz.iBeg+1,cz.iEnd+1);
                 writer.write(_fp,aCell,0,cells.getSelfCount());
                 closeSection();
                 foreach(const FaceGroupPtr fgPtr, mesh.getBoundaryFaceGroups())
                 {
                     const FaceGroup& fg = *fgPtr;
                     const StorageSite& faces = fg.site;
                     const FluentFaceZone& fz = *faceZones[fg.id];
                     const CRConnectivity& faceCells = mesh.getFaceCells(faces);
                     fprintf(_fp,"(%d (%d %d 1 0 1 %d %d)\n(",
                             _sectionID, fluentFieldId+nd, fz.ID,
                             fz.iBeg+1,fz.iEnd+1);
                     int cbeg = faceCells(0,1);
                     writer.write(_fp,aCell,cbeg,faces.getSelfCount());
                     closeSection();
                 }
             }
         }
     }
   }
Member Data Documentation
template<class T > const int FluentDataExporter< T >::_atypeComponent private
Definition at line 186 of file FluentDataExporter.h.
Referenced by FluentDataExporter< T >::writeScalarField(), and FluentDataExporter< T >::writeVectorField().
template<class T > const bool FluentDataExporter< T >::_binary private
Definition at line 185 of file FluentDataExporter.h.
Referenced by FluentDataExporter< T >::closeSection(), FluentDataExporter< T >::writeScalarField(), and FluentDataExporter< T >::writeVectorField().
template<class T > FILE* FluentDataExporter< T >::_fp private
Definition at line 184 of file FluentDataExporter.h.
Referenced by FluentDataExporter< T >::closeSection(), FluentDataExporter< T >::finish(), FluentDataExporter< T >::FluentDataExporter(), FluentDataExporter< T >::init(), FluentDataExporter< T >::writeScalarField(), and FluentDataExporter< T >::writeVectorField().
template<class T > FluentReader& FluentDataExporter< T >::_reader private
Definition at line 183 of file FluentDataExporter.h.
Referenced by FluentDataExporter< T >::writeScalarField(), and FluentDataExporter< T >::writeVectorField().
template<class T > const int FluentDataExporter< T >::_sectionID private
Definition at line 187 of file FluentDataExporter.h.
Referenced by FluentDataExporter< T >::writeScalarField(), and FluentDataExporter< T >::writeVectorField().
The documentation for this class was generated from the following file:
FluentDataExporter.h