Memosa-FVM: KSConnectivity< T > Class Template Reference
KSConnectivity< T > Class Template Reference
#include <KSConnectivity.h>
Public Types
typedef Array< int > IntArray
typedef Array< T > TArray
typedef pair< IntArray
*, TArray * > CouplingPair
typedef vector< CouplingPair * > SelfToOther
typedef vector< CouplingPair * > SelfToSelf
Public Member Functions
KSConnectivity (const int selfLength, const int otherLength)
void emptyConnections ()
void initSelfCount ()
void initOtherCount ()
void addCountSelf (const int index, const int count)
void addCountOther (const int index, const int count)
void finishCountSelf ()
void finishCountOther ()
void addSelf (const int i, const int j, const T val)
void addOther (const int i, const int j, const T val)
void finishAddSelf ()
void finishAddOther ()
int getSelfCount (const int i)
int getOtherCount (const int i)
const IntArray & getSelfRow ()
const IntArray & getOtherRow ()
const IntArray & getSelfCol ()
const IntArray & getOtherCol ()
const TArray & getSelfCoeffs ()
const TArray & getOtherCoeffs ()
TArray & getNonConstOtherCoeffs ()
int getSelfNNZ ()
int getOtherNNZ ()
void multiplySelf (const TArray &x, TArray &b, const T scale) const
void multiplyOther (const TArray &x, TArray &b, const T scale) const
int getSelfSize ()
int getOtherSize ()
void copyFrom (KSConnectivity &from)
void multiplySelf (const T x)
void multiplyOther (const T x)
void addToSelf (KSConnectivity &added)
void addToOther (KSConnectivity &added)
void expandMySelfSelf (const int i, TArray &ExpCoeff)
void expandMySelfOther (const int i, TArray &ExpCoeff)
Private Member Functions
KSConnectivity (const KSConnectivity &)
Private Attributes
StorageSite _selfSite
StorageSite _otherSite
TArray _SelfToOtherCoeffs
TArray _SelfToSelfCoeffs
CRConnectivity _SelfToOtherConn
CRConnectivity _SelfToSelfConn
int _selfNNZ
int _otherNNZ
Detailed Description
template<class T>
class KSConnectivity< T >
Definition at line 11 of file KSConnectivity.h.
Member Typedef Documentation
template<class T> typedef pair<IntArray*,TArray*> KSConnectivity< T >::CouplingPair
Definition at line 17 of file KSConnectivity.h.
template<class T> typedef Array<int> KSConnectivity< T >::IntArray
Definition at line 15 of file KSConnectivity.h.
template<class T> typedef vector<CouplingPair*> KSConnectivity< T >::SelfToOther
Definition at line 18 of file KSConnectivity.h.
template<class T> typedef vector<CouplingPair*> KSConnectivity< T >::SelfToSelf
Definition at line 19 of file KSConnectivity.h.
template<class T> typedef Array<T> KSConnectivity< T >::TArray
Definition at line 16 of file KSConnectivity.h.
Constructor & Destructor Documentation
template<class T> KSConnectivity< T >::KSConnectivity (const int selfLength, const int otherLength) inline
Definition at line 21 of file KSConnectivity.h.
                                                             :
   _selfSite(selfLength),
     _otherSite(otherLength),
     _SelfToOtherCoeffs(0),
     _SelfToSelfCoeffs(0),
     _SelfToOtherConn(_selfSite,_otherSite),
     _SelfToSelfConn(_selfSite,_selfSite),
     _selfNNZ(0),
     _otherNNZ(0)
       {}
template<class T> KSConnectivity< T >::KSConnectivity (const KSConnectivity< T > &) private
Member Function Documentation
template<class T> void KSConnectivity< T >::addCountOther (const int index, const int count) inline
Definition at line 45 of file KSConnectivity.h.
References KSConnectivity< T >::_otherNNZ, KSConnectivity< T >::_SelfToOtherConn, and CRConnectivity::addCount().
Referenced by KSConnectivity< T >::addToOther(), KSConnectivity< T >::copyFrom(), COMETInterface< T >::makeDMMcoeffs(), and COMETInterface< T >::makeNoInterfaceCoeffs().
   {
     _SelfToOtherConn.addCount(index, count);
     _otherNNZ+=count;
   }
template<class T> void KSConnectivity< T >::addCountSelf (const int index, const int count) inline
Definition at line 40 of file KSConnectivity.h.
References KSConnectivity< T >::_selfNNZ, KSConnectivity< T >::_SelfToSelfConn, and CRConnectivity::addCount().
Referenced by KSConnectivity< T >::addToSelf(), KSConnectivity< T >::copyFrom(), COMETInterface< T >::makeDMMcoeffs(), and COMETInterface< T >::makeNoInterfaceCoeffs().
   {
     _SelfToSelfConn.addCount(index, count);
     _selfNNZ+=count;
   }
template<class T> void KSConnectivity< T >::addOther (const int i, const int j, const T val) inline
Definition at line 64 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherCoeffs, KSConnectivity< T >::_SelfToOtherConn, and CRConnectivity::add().
Referenced by KSConnectivity< T >::addToOther(), KSConnectivity< T >::copyFrom(), COMETInterface< T >::makeDMMcoeffs(), and COMETInterface< T >::makeNoInterfaceCoeffs().
   {_SelfToOtherCoeffs[_SelfToOtherConn.add(i,j)]=val;}
template<class T> void KSConnectivity< T >::addSelf (const int i, const int j, const T val) inline
Definition at line 62 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToSelfCoeffs, KSConnectivity< T >::_SelfToSelfConn, and CRConnectivity::add().
Referenced by KSConnectivity< T >::addToSelf(), KSConnectivity< T >::copyFrom(), COMETInterface< T >::makeDMMcoeffs(), and COMETInterface< T >::makeNoInterfaceCoeffs().
   {_SelfToSelfCoeffs[_SelfToSelfConn.add(i,j)]=val;}
template<class T> void KSConnectivity< T >::addToOther (KSConnectivity< T > & added) inline
Definition at line 237 of file KSConnectivity.h.
References KSConnectivity< T >::addCountOther(), KSConnectivity< T >::addOther(), KSConnectivity< T >::copyFrom(), KSConnectivity< T >::expandMySelfOther(), fabs(), KSConnectivity< T >::finishAddOther(), KSConnectivity< T >::finishCountOther(), KSConnectivity< T >::getOtherSize(), KSConnectivity< T >::getSelfSize(), and KSConnectivity< T >::initOtherCount().
   {
     const int selfSize=getSelfSize();
     if(selfSize==added.getSelfSize())
       {
         if(getOtherSize()==added.getOtherSize())
           {
             KSConnectivity<T> myCopy(getSelfSize(),getOtherSize());
             myCopy.copyFrom(*this);
             //start the counting
             initOtherCount();
             for(int i=0;i<selfSize;i++)
               {
                 TArray myExpand(1);
                 myCopy.expandMySelfOther(i, myExpand);
                 TArray addExpand(1);
                 added.expandMySelfOther(i, addExpand);
                 myExpand+=addExpand;
                 int newSize(0);
                 for(int j=0;j<getOtherSize();j++)
                   {
                     if(fabs(myExpand[j])>0.)
                       newSize++;
                   }
                 addCountOther(i,newSize);
               }
             finishCountOther();
             //put in values
             for(int i=0;i<selfSize;i++)
               {
                 TArray myExpand(1);
                 myCopy.expandMySelfOther(i, myExpand);
                 TArray addExpand(1);
                 added.expandMySelfOther(i, addExpand);
                 myExpand+=addExpand;
                 for(int j=0;j<getOtherSize();j++)
                   {
                     if(fabs(myExpand[j])>0.)
                         addOther(i,j,myExpand[j]);
                   }
               }
             finishAddOther();
           }
         else
           throw CException("addToOther: Columns not the same size!");
       }
     else
       throw CException("addToOther: Rows not the same size!");
   }
template<class T> void KSConnectivity< T >::addToSelf (KSConnectivity< T > & added) inline
Definition at line 184 of file KSConnectivity.h.
References KSConnectivity< T >::addCountSelf(), KSConnectivity< T >::addSelf(), KSConnectivity< T >::copyFrom(), KSConnectivity< T >::expandMySelfSelf(), fabs(), KSConnectivity< T >::finishAddSelf(), KSConnectivity< T >::finishCountSelf(), KSConnectivity< T >::getSelfSize(), and KSConnectivity< T >::initSelfCount().
   {
     const int selfSize=getSelfSize();
     if(selfSize==added.getSelfSize())
       {
         KSConnectivity<T> myCopy(getSelfSize(),getSelfSize());
         myCopy.copyFrom(*this);
         //start the counting
         initSelfCount();
         for(int i=0;i<selfSize;i++)
           {
             TArray myExpand(1);
             myCopy.expandMySelfSelf(i, myExpand);
             TArray addExpand(1);
             added.expandMySelfSelf(i, addExpand);
             myExpand+=addExpand;
             int newSize(0);
             for(int j=0;j<selfSize;j++)
               {
                 if(fabs(myExpand[j])>0.)
                   newSize++;
               }
             addCountSelf(i,newSize);
           }
         finishCountSelf();
         //put in values
         for(int i=0;i<selfSize;i++)
           {
             TArray myExpand(1);
             myCopy.expandMySelfSelf(i, myExpand);
             TArray addExpand(1);
             added.expandMySelfSelf(i, addExpand);
             myExpand+=addExpand;
             for(int j=0;j<selfSize;j++)
               {
                 if(fabs(myExpand[j])>0.)
                     addSelf(i,j,myExpand[j]);
               }
           }
         finishAddSelf();
       }
     else
       throw CException("addToSelf: Rows not the same size!");
   }
template<class T> void KSConnectivity< T >::copyFrom (KSConnectivity< T > & from) inline
Definition at line 121 of file KSConnectivity.h.
References KSConnectivity< T >::addCountOther(), KSConnectivity< T >::addCountSelf(), KSConnectivity< T >::addOther(), KSConnectivity< T >::addSelf(), KSConnectivity< T >::finishAddOther(), KSConnectivity< T >::finishAddSelf(), KSConnectivity< T >::finishCountOther(), KSConnectivity< T >::finishCountSelf(), KSConnectivity< T >::getOtherCoeffs(), KSConnectivity< T >::getOtherCol(), KSConnectivity< T >::getOtherCount(), KSConnectivity< T >::getOtherRow(), KSConnectivity< T >::getSelfCoeffs(), KSConnectivity< T >::getSelfCol(), KSConnectivity< T >::getSelfCount(), KSConnectivity< T >::getSelfRow(), KSConnectivity< T >::getSelfSize(), KSConnectivity< T >::initOtherCount(), and KSConnectivity< T >::initSelfCount().
Referenced by KSConnectivity< T >::addToOther(), KSConnectivity< T >::addToSelf(), and COMETInterface< T >::makeCoarseCoeffs().
   {
     //Copy SelfToSelf connections first
     initSelfCount();
     int Arows=from.getSelfSize();
     for(int i=0;i<Arows;i++)
       addCountSelf(i,from.getSelfCount(i));
     finishCountSelf();
     for(int i=0;i<Arows;i++)
       {
         const IntArray& row=from.getSelfRow();
         const IntArray& col=from.getSelfCol();
         const TArray& coeff=from.getSelfCoeffs();
         for(int pos=row[i];pos<row[i+1];pos++)
           {
             const T fromCoeff=coeff[pos];
             const int j=col[pos];
             addSelf(i,j,fromCoeff);
           }
       }
     finishAddSelf();
     //Copy SelfToOther connections now
     initOtherCount();
     for(int i=0;i<Arows;i++)
       addCountOther(i,from.getOtherCount(i));
     finishCountOther();
     for(int i=0;i<Arows;i++)
       {
         const IntArray& row=from.getOtherRow();
         const IntArray& col=from.getOtherCol();
         const TArray& coeff=from.getOtherCoeffs();
         for(int pos=row[i];pos<row[i+1];pos++)
           {
             const T fromCoeff=coeff[pos];
             const int j=col[pos];
             addOther(i,j,fromCoeff);
           }
       }
     finishAddOther();
   }
template<class T> void KSConnectivity< T >::emptyConnections () inline
Definition at line 32 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherCoeffs, KSConnectivity< T >::_SelfToSelfCoeffs, and Array< T >::zero().
   {
     _SelfToOtherCoeffs.zero();
     _SelfToSelfCoeffs.zero();
   }
template<class T> void KSConnectivity< T >::expandMySelfOther (const int i, TArray & ExpCoeff) inline
Definition at line 310 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherCoeffs, KSConnectivity< T >::_SelfToOtherConn, CRConnectivity::getCol(), KSConnectivity< T >::getOtherSize(), CRConnectivity::getRow(), Array< T >::resize(), and Array< T >::zero().
Referenced by KSConnectivity< T >::addToOther().
   {
     const int mysize=getOtherSize();
     ExpCoeff.resize(mysize);
     ExpCoeff.zero();
     const IntArray& row=_SelfToOtherConn.getRow();
     const IntArray& col=_SelfToOtherConn.getCol();
     for(int pos=row[i];pos<row[i+1];pos++)
       {
         const int j=col[pos];
         ExpCoeff[j]=_SelfToOtherCoeffs[pos];
       }
   }
template<class T> void KSConnectivity< T >::expandMySelfSelf (const int i, TArray & ExpCoeff) inline
Definition at line 294 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToSelfCoeffs, KSConnectivity< T >::_SelfToSelfConn, CRConnectivity::getCol(), CRConnectivity::getRow(), KSConnectivity< T >::getSelfSize(), Array< T >::resize(), and Array< T >::zero().
Referenced by KSConnectivity< T >::addToSelf().
   {
     const int mysize=getSelfSize();
     ExpCoeff.resize(mysize);
     ExpCoeff.zero();
     const IntArray& row=_SelfToSelfConn.getRow();
     const IntArray& col=_SelfToSelfConn.getCol();
     for(int pos=row[i];pos<row[i+1];pos++)
       {
         const int j=col[pos];
         ExpCoeff[j]=_SelfToSelfCoeffs[pos];
       }
   }
template<class T> void KSConnectivity< T >::finishAddOther () inline
Definition at line 67 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherConn, and CRConnectivity::finishAdd().
Referenced by KSConnectivity< T >::addToOther(), KSConnectivity< T >::copyFrom(), COMETInterface< T >::makeDMMcoeffs(), and COMETInterface< T >::makeNoInterfaceCoeffs().
 {_SelfToOtherConn.finishAdd();}
template<class T> void KSConnectivity< T >::finishAddSelf () inline
Definition at line 66 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToSelfConn, and CRConnectivity::finishAdd().
Referenced by KSConnectivity< T >::addToSelf(), KSConnectivity< T >::copyFrom(), COMETInterface< T >::makeDMMcoeffs(), and COMETInterface< T >::makeNoInterfaceCoeffs().
 {_SelfToSelfConn.finishAdd();}
template<class T> void KSConnectivity< T >::finishCountOther () inline
Definition at line 56 of file KSConnectivity.h.
References KSConnectivity< T >::_otherNNZ, KSConnectivity< T >::_SelfToOtherCoeffs, KSConnectivity< T >::_SelfToOtherConn, CRConnectivity::finishCount(), Array< T >::resize(), and Array< T >::zero().
Referenced by KSConnectivity< T >::addToOther(), KSConnectivity< T >::copyFrom(), COMETInterface< T >::makeDMMcoeffs(), and COMETInterface< T >::makeNoInterfaceCoeffs().
   {
     _SelfToOtherConn.finishCount();
     _SelfToOtherCoeffs.resize(_otherNNZ);
     _SelfToOtherCoeffs.zero();
   }
template<class T> void KSConnectivity< T >::finishCountSelf () inline
Definition at line 50 of file KSConnectivity.h.
References KSConnectivity< T >::_selfNNZ, KSConnectivity< T >::_SelfToSelfCoeffs, KSConnectivity< T >::_SelfToSelfConn, CRConnectivity::finishCount(), Array< T >::resize(), and Array< T >::zero().
Referenced by KSConnectivity< T >::addToSelf(), KSConnectivity< T >::copyFrom(), COMETInterface< T >::makeDMMcoeffs(), and COMETInterface< T >::makeNoInterfaceCoeffs().
   {
     _SelfToSelfConn.finishCount();
     _SelfToSelfCoeffs.resize(_selfNNZ);
     _SelfToSelfCoeffs.zero();
   }
template<class T> TArray& KSConnectivity< T >::getNonConstOtherCoeffs () inline
Definition at line 76 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherCoeffs.
 {return _SelfToOtherCoeffs;}
template<class T> const TArray& KSConnectivity< T >::getOtherCoeffs () inline
Definition at line 75 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherCoeffs.
Referenced by KSConnectivity< T >::copyFrom().
 {return _SelfToOtherCoeffs;}
template<class T> const IntArray& KSConnectivity< T >::getOtherCol () inline
Definition at line 73 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherConn, and CRConnectivity::getCol().
Referenced by KSConnectivity< T >::copyFrom().
 {return _SelfToOtherConn.getCol();}
template<class T> int KSConnectivity< T >::getOtherCount (const int i) inline
Definition at line 69 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherConn, and CRConnectivity::getCount().
Referenced by KSConnectivity< T >::copyFrom().
 {return _SelfToOtherConn.getCount(i);}
template<class T> int KSConnectivity< T >::getOtherNNZ () inline
Definition at line 78 of file KSConnectivity.h.
References KSConnectivity< T >::_otherNNZ.
 {return _otherNNZ;}
template<class T> const IntArray& KSConnectivity< T >::getOtherRow () inline
Definition at line 71 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherConn, and CRConnectivity::getRow().
Referenced by KSConnectivity< T >::copyFrom().
 {return _SelfToOtherConn.getRow();}
template<class T> int KSConnectivity< T >::getOtherSize () inline
Definition at line 119 of file KSConnectivity.h.
References KSConnectivity< T >::_otherSite, and StorageSite::getSelfCount().
Referenced by KSConnectivity< T >::addToOther(), and KSConnectivity< T >::expandMySelfOther().
 {return _otherSite.getSelfCount();}
template<class T> const TArray& KSConnectivity< T >::getSelfCoeffs () inline
Definition at line 74 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToSelfCoeffs.
Referenced by KSConnectivity< T >::copyFrom().
 {return _SelfToSelfCoeffs;}
template<class T> const IntArray& KSConnectivity< T >::getSelfCol () inline
Definition at line 72 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToSelfConn, and CRConnectivity::getCol().
Referenced by KSConnectivity< T >::copyFrom().
 {return _SelfToSelfConn.getCol();}
template<class T> int KSConnectivity< T >::getSelfCount (const int i) inline
Definition at line 68 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToSelfConn, and CRConnectivity::getCount().
Referenced by KSConnectivity< T >::copyFrom().
 {return _SelfToSelfConn.getCount(i);}
template<class T> int KSConnectivity< T >::getSelfNNZ () inline
Definition at line 77 of file KSConnectivity.h.
References KSConnectivity< T >::_selfNNZ.
 {return _selfNNZ;}
template<class T> const IntArray& KSConnectivity< T >::getSelfRow () inline
Definition at line 70 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToSelfConn, and CRConnectivity::getRow().
Referenced by KSConnectivity< T >::copyFrom().
 {return _SelfToSelfConn.getRow();}
template<class T> int KSConnectivity< T >::getSelfSize () inline
Definition at line 118 of file KSConnectivity.h.
References KSConnectivity< T >::_selfSite, and StorageSite::getSelfCount().
Referenced by KSConnectivity< T >::addToOther(), KSConnectivity< T >::addToSelf(), KSConnectivity< T >::copyFrom(), and KSConnectivity< T >::expandMySelfSelf().
 {return _selfSite.getSelfCount();}
template<class T> void KSConnectivity< T >::initOtherCount () inline
Definition at line 39 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherConn, and CRConnectivity::initCount().
Referenced by KSConnectivity< T >::addToOther(), KSConnectivity< T >::copyFrom(), COMETInterface< T >::makeDMMcoeffs(), and COMETInterface< T >::makeNoInterfaceCoeffs().
 {_SelfToOtherConn.initCount();}
template<class T> void KSConnectivity< T >::initSelfCount () inline
Definition at line 38 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToSelfConn, and CRConnectivity::initCount().
Referenced by KSConnectivity< T >::addToSelf(), KSConnectivity< T >::copyFrom(), COMETInterface< T >::makeDMMcoeffs(), and COMETInterface< T >::makeNoInterfaceCoeffs().
 {_SelfToSelfConn.initCount();}
template<class T> void KSConnectivity< T >::multiplyOther (const TArray & x, TArray & b, const T scale) const inline
Definition at line 99 of file KSConnectivity.h.
References KSConnectivity< T >::_otherSite, KSConnectivity< T >::_SelfToOtherCoeffs, KSConnectivity< T >::_SelfToOtherConn, CRConnectivity::getCol(), Array< T >::getLength(), CRConnectivity::getRow(), StorageSite::getSelfCount(), and Array< T >::zero().
Referenced by COMETInterface< T >::makeCoarseCoeffs(), COMETInterface< T >::updateOtherGhost(), and COMETInterface< T >::updateResid().
   {//b=this*x
     const int Arows=_otherSite.getSelfCount();
     b.zero();
     if(Arows==x.getLength() && Arows==b.getLength())
       {
         for(int i=0;i<Arows;i++)
           {
             const IntArray& row=_SelfToOtherConn.getRow();
             const IntArray& col=_SelfToOtherConn.getCol();
             for(int pos=row[i];pos<row[i+1];pos++)
               b[i]+=(x[col[pos]]*_SelfToOtherCoeffs[pos])/scale;
             b[i]*=scale;
           }
       }
     else
       throw CException("Matrix size does not agree with vectors!");
   }
template<class T> void KSConnectivity< T >::multiplyOther (const T x) inline
Definition at line 178 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToOtherCoeffs, and Array< T >::getLength().
   {
     for(int i=0;i<_SelfToOtherCoeffs.getLength();i++)
       _SelfToOtherCoeffs[i]*=x;
   }
template<class T> void KSConnectivity< T >::multiplySelf (const TArray & x, TArray & b, const T scale) const inline
Definition at line 80 of file KSConnectivity.h.
References KSConnectivity< T >::_selfSite, KSConnectivity< T >::_SelfToSelfCoeffs, KSConnectivity< T >::_SelfToSelfConn, CRConnectivity::getCol(), Array< T >::getLength(), CRConnectivity::getRow(), StorageSite::getSelfCount(), and Array< T >::zero().
Referenced by COMETDiscretizer< T >::correctInterface(), COMETInterface< T >::makeCoarseCoeffs(), COMETInterface< T >::updateOtherGhost(), and COMETInterface< T >::updateResid().
   {//b=this*x
     const int Arows=_selfSite.getSelfCount();
     b.zero();
     if(Arows==x.getLength() && Arows==b.getLength())
       {
         const IntArray& row=_SelfToSelfConn.getRow();
         const IntArray& col=_SelfToSelfConn.getCol();
         for(int i=0;i<Arows;i++)
           {
             for(int pos=row[i];pos<row[i+1];pos++)
               b[i]+=(x[col[pos]]*_SelfToSelfCoeffs[pos])/scale;
             b[i]*=scale;
           }
       }
     else
       throw CException("Matrix size does not agree with vectors!");
   }
template<class T> void KSConnectivity< T >::multiplySelf (const T x) inline
Definition at line 172 of file KSConnectivity.h.
References KSConnectivity< T >::_SelfToSelfCoeffs, and Array< T >::getLength().
   {
     for(int i=0;i<_SelfToSelfCoeffs.getLength();i++)
       _SelfToSelfCoeffs[i]*=x;
   }
Member Data Documentation
template<class T> int KSConnectivity< T >::_otherNNZ private
Definition at line 336 of file KSConnectivity.h.
Referenced by KSConnectivity< T >::addCountOther(), KSConnectivity< T >::finishCountOther(), and KSConnectivity< T >::getOtherNNZ().
template<class T> StorageSite KSConnectivity< T >::_otherSite private
Definition at line 330 of file KSConnectivity.h.
Referenced by KSConnectivity< T >::getOtherSize(), and KSConnectivity< T >::multiplyOther().
template<class T> int KSConnectivity< T >::_selfNNZ private
Definition at line 335 of file KSConnectivity.h.
Referenced by KSConnectivity< T >::addCountSelf(), KSConnectivity< T >::finishCountSelf(), and KSConnectivity< T >::getSelfNNZ().
template<class T> StorageSite KSConnectivity< T >::_selfSite private
Definition at line 329 of file KSConnectivity.h.
Referenced by KSConnectivity< T >::getSelfSize(), and KSConnectivity< T >::multiplySelf().
template<class T> TArray KSConnectivity< T >::_SelfToOtherCoeffs private
Definition at line 331 of file KSConnectivity.h.
Referenced by KSConnectivity< T >::addOther(), KSConnectivity< T >::emptyConnections(), KSConnectivity< T >::expandMySelfOther(), KSConnectivity< T >::finishCountOther(), KSConnectivity< T >::getNonConstOtherCoeffs(), KSConnectivity< T >::getOtherCoeffs(), and KSConnectivity< T >::multiplyOther().
template<class T> CRConnectivity KSConnectivity< T >::_SelfToOtherConn private
Definition at line 333 of file KSConnectivity.h.
Referenced by KSConnectivity< T >::addCountOther(), KSConnectivity< T >::addOther(), KSConnectivity< T >::expandMySelfOther(), KSConnectivity< T >::finishAddOther(), KSConnectivity< T >::finishCountOther(), KSConnectivity< T >::getOtherCol(), KSConnectivity< T >::getOtherCount(), KSConnectivity< T >::getOtherRow(), KSConnectivity< T >::initOtherCount(), and KSConnectivity< T >::multiplyOther().
template<class T> TArray KSConnectivity< T >::_SelfToSelfCoeffs private
Definition at line 332 of file KSConnectivity.h.
Referenced by KSConnectivity< T >::addSelf(), KSConnectivity< T >::emptyConnections(), KSConnectivity< T >::expandMySelfSelf(), KSConnectivity< T >::finishCountSelf(), KSConnectivity< T >::getSelfCoeffs(), and KSConnectivity< T >::multiplySelf().
template<class T> CRConnectivity KSConnectivity< T >::_SelfToSelfConn private
Definition at line 334 of file KSConnectivity.h.
Referenced by KSConnectivity< T >::addCountSelf(), KSConnectivity< T >::addSelf(), KSConnectivity< T >::expandMySelfSelf(), KSConnectivity< T >::finishAddSelf(), KSConnectivity< T >::finishCountSelf(), KSConnectivity< T >::getSelfCol(), KSConnectivity< T >::getSelfCount(), KSConnectivity< T >::getSelfRow(), KSConnectivity< T >::initSelfCount(), and KSConnectivity< T >::multiplySelf().
The documentation for this class was generated from the following file:
KSConnectivity.h