Memosa-FVM: FloatVarDict< T > Class Template Reference
FloatVarDict< T > Class Template Reference
#include <FloatVarDict.h>
Inherits map< string, FloatVal< T > >.
Inherited by BatteryModelOptions< T >, BatteryPotentialBC< T >, BatteryPotentialVC< T >, BatterySpeciesBC< T >, BatterySpeciesVC< T >, BatteryThermalBC< T >, BatteryThermalVC< T >, COMETBC< T >, COMETBC< T >, COMETModelOptions< T >, COMETModelOptions< T >, COMETVC< T >, ContactModelConstants< T >, ElectricBC< T >, ElectricModelConstants< T >, ElectricModelOptions< T >, ElectricVC< T >, FlowBC< T >, FlowModelOptions< T >, FlowVC< T >, FractureBC< T >, FractureModelOptions< T >, FractureVC< T >, IdealGasVC< T >, KeBC< T >, KeModelOptions< T >, KeVC< T >, KineticBC< T >, KineticModelOptions< T >, KineticVC< T >, MovingMeshModelOptions< T >, PhononBC< T >, PhononModelOptions< T >, PlateBC< T >, PlateModelOptions< T >, PlateVC< T >, RosselandVC< T >, SpeciesBC< T >, SpeciesModelOptions< T >, SpeciesVC< T >, StructureBC< T >, StructureModelOptions< T >, StructureVC< T >, ThermalBC< T >, ThermalModelOptions< T >, ThermalVC< T >, VacancyBC< T >, VacancyModelOptions< T >, and VacancyVC< T >.
Public Types
typedef map< string, FloatVal
< T > > T_Parent
Public Member Functions
bool hasVar (const string varName) const
T operator[] (const string varName) const
bool isField (const string varName) const
Field & getField (const string varName) const
FloatVal< T > getVal (const string varName) const
Protected Member Functions
void defineVar (const string varName, const T defaultValue)
Detailed Description
template<typename T>
class FloatVarDict< T >
A dictionary for specifying floating point inputs – used for boundary conditions as well as model inputs. Derived classes define the keys and default values.
Definition at line 45 of file FloatVarDict.h.
Member Typedef Documentation
template<typename T> typedef map<string,FloatVal<T> > FloatVarDict< T >::T_Parent
Definition at line 49 of file FloatVarDict.h.
Member Function Documentation
template<typename T> void FloatVarDict< T >::defineVar (const string varName, const T defaultValue) inline protected
Definition at line 94 of file FloatVarDict.h.
Referenced by BatteryModelOptions< T >::BatteryModelOptions(), BatteryPotentialBC< T >::BatteryPotentialBC(), BatteryPotentialVC< T >::BatteryPotentialVC(), BatterySpeciesBC< T >::BatterySpeciesBC(), BatterySpeciesVC< T >::BatterySpeciesVC(), BatteryThermalBC< T >::BatteryThermalBC(), BatteryThermalVC< T >::BatteryThermalVC(), COMETBC< T >::COMETBC(), COMETModelOptions< X >::COMETModelOptions(), COMETVC< T >::COMETVC(), ContactModelConstants< T >::ContactModelConstants(), ElectricBC< T >::ElectricBC(), ElectricModelConstants< T_Scalar >::ElectricModelConstants(), ElectricModelOptions< T >::ElectricModelOptions(), ElectricVC< T >::ElectricVC(), FlowBC< T >::FlowBC(), FlowModelOptions< double >::FlowModelOptions(), FlowVC< T >::FlowVC(), FractureBC< T >::FractureBC(), FractureModelOptions< T >::FractureModelOptions(), FractureVC< T >::FractureVC(), IdealGasVC< T >::IdealGasVC(), KeBC< T >::KeBC(), KeModelOptions< T_Scalar >::KeModelOptions(), KeVC< T >::KeVC(), KineticBC< T >::KineticBC(), KineticModelOptions< X >::KineticModelOptions(), KineticVC< T >::KineticVC(), MovingMeshModelOptions< T >::MovingMeshModelOptions(), PhononBC< T >::PhononBC(), PhononModelOptions< X >::PhononModelOptions(), PlateBC< T >::PlateBC(), PlateModelOptions< T >::PlateModelOptions(), PlateVC< T >::PlateVC(), RosselandVC< T >::RosselandVC(), SpeciesBC< T >::SpeciesBC(), SpeciesModelOptions< T >::SpeciesModelOptions(), SpeciesVC< T >::SpeciesVC(), StructureBC< T >::StructureBC(), StructureModelOptions< T >::StructureModelOptions(), StructureVC< T >::StructureVC(), ThermalBC< T >::ThermalBC(), ThermalModelOptions< T >::ThermalModelOptions(), ThermalVC< T >::ThermalVC(), VacancyBC< T >::VacancyBC(), VacancyModelOptions< T >::VacancyModelOptions(), and VacancyVC< T >::VacancyVC().
   {
     this->insert(make_pair(varName,defaultValue));
   }
template<typename T> Field& FloatVarDict< T >::getField (const string varName) const inline
Definition at line 77 of file FloatVarDict.h.
   {
     typename T_Parent::const_iterator pos = this->find(varName);
     if (pos != this->end())
       return *(pos->second.field);
     throw CException("uknown var " + varName);
   }
template<typename T> FloatVal<T> FloatVarDict< T >::getVal (const string varName) const inline
Definition at line 85 of file FloatVarDict.h.
Referenced by IdealGasDensityModel< T >::Impl::advance(), RosselandModel< T >::Impl::advance(), StructureModel< T >::Impl::applyBC(), COMETModel< T >::applyTemperatureBoundaries(), PhononModel< T >::callBoundaryConditions(), KineticModel< T >::callBoundaryConditions(), COMETModel< T >::callCOMETBoundaryConditions(), fixedFluxContinuityBC(), COMETModel< T >::initializeTemperatureBoundaries(), ThermalModel< T >::Impl::linearize(), FractureModel< T >::Impl::linearize(), VacancyModel< T >::Impl::linearize(), SpeciesModel< T >::Impl::linearize(), PlateModel< T >::Impl::linearizeDeformation(), KeModel< T >::Impl::linearizedissipation(), ElectricModel< T >::Impl::linearizeElectroStatics(), KeModel< T >::Impl::linearizeenergy(), KineticModel< T >::linearizeKineticModel(), FlowModel< T >::Impl::linearizeMomentum(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), and BatteryModel< T >::Impl::linearizeThermal().
   {
     typename T_Parent::const_iterator pos = this->find(varName);
     if (pos != this->end())
       return pos->second;
     throw CException("uknown var " + varName);
   }
template<typename T> bool FloatVarDict< T >::hasVar (const string varName) const inline
Definition at line 51 of file FloatVarDict.h.
   {
     typename T_Parent::const_iterator pos = this->find(varName);
     return pos != this->end();
   }
template<typename T> bool FloatVarDict< T >::isField (const string varName) const inline
Definition at line 69 of file FloatVarDict.h.
   {
     typename T_Parent::const_iterator pos = this->find(varName);
     if (pos != this->end())
       return (pos->second.field!=0);
     throw CException("uknown var " + varName);
   }
template<typename T> T FloatVarDict< T >::operator[] (const string varName) const inline
Definition at line 57 of file FloatVarDict.h.
   {
     typename T_Parent::const_iterator pos = this->find(varName);
     if (pos != this->end())
     {
         if (pos->second.field)
           throw CException(varName + " value is a Field");
         return pos->second.constant;
     }
     throw CException("uknown var " + varName);
   }
The documentation for this class was generated from the following file:
FloatVarDict.h