Memosa-FVM: Matrix Class Reference
Matrix Class Reference abstract
#include <Matrix.h>
Public Member Functions
Matrix ()
virtual ~Matrix ()
DEFINE_TYPENAME ("Matrix")
virtual void initAssembly ()=0
virtual void multiply (IContainer &yB, const IContainer &xB) const
virtual void multiplyAndAdd (IContainer &yB, const IContainer &xB) const
virtual shared_ptr< ArrayBase > quadProduct (const IContainer &xB) const
virtual void forwardGS (IContainer &xB, IContainer &bB, IContainer &residual) const
virtual void reverseGS (IContainer &xB, IContainer &bB, IContainer &residual) const
virtual void Jacobi (IContainer &xnew, const IContainer &xold, const IContainer &b) const
virtual void iluSolve (IContainer &xB, const IContainer &bB, const IContainer &residual) const
virtual void spikeSolve (IContainer &xB, const IContainer &bB, const IContainer &residual, const SpikeStorage &spike_storage) const
virtual void solveBoundary (IContainer &xB, IContainer &bB, IContainer &residual) const
virtual void computeResidual (const IContainer &xB, const IContainer &bB, IContainer &residual) const
virtual int createCoarsening (IContainer &coarseIndex, const int groupSize, const double weighRatioThreshold)
virtual const CRConnectivity & getConnectivity () const
virtual void eliminateBoundaryEquations (IContainer &xB)
virtual void printRow (const int nr) const
virtual void * getDiagData () const
virtual void * getOffDiagData () const
virtual int getDiagDataSize () const
virtual int getOffDiagDataSize () const
virtual shared_ptr< Matrix > createMergeMatrix (const LinearSystemMerger &mergeLS)
virtual void setFlatMatrix (Matrix &fmg) const
virtual void transpose ()
virtual shared_ptr
< CRConnectivity > createCoarseConnectivity (const IContainer &coarseIndex, const CRConnectivity &coarseToFine, const StorageSite &coarseRowSite, const StorageSite &coarseColSite)
virtual shared_ptr< Matrix > createCoarseMatrix (const IContainer &coarseIndex, const CRConnectivity &coarseToFine, const CRConnectivity &coarseConnectivity)
virtual bool isInvertible ()
Detailed Description
Definition at line 16 of file Matrix.h.
Constructor & Destructor Documentation
Matrix::Matrix ()
Definition at line 8 of file Matrix.cpp.
 {}
Matrix::~Matrix () virtual
Definition at line 11 of file Matrix.cpp.
 {}
Member Function Documentation
void Matrix::computeResidual (const IContainer & xB, const IContainer & bB, IContainer & residual) const virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >, and DiagonalMatrix< Diag, X >.
Definition at line 87 of file Matrix.cpp.
 {
   throw CException("computeResidual not implemented");
 }
shared_ptr< CRConnectivity > Matrix::createCoarseConnectivity (const IContainer & coarseIndex, const CRConnectivity & coarseToFine, const StorageSite & coarseRowSite, const StorageSite & coarseColSite) virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >, CRMatrixRect< T_Coeff, X, B >, and DiagonalMatrix< Diag, X >.
Definition at line 23 of file Matrix.cpp.
Referenced by MultiFieldMatrix::createCoarseConnectivity().
 {
   throw CException("createCoarseConnectivity not implemented");
 }
shared_ptr< Matrix > Matrix::createCoarseMatrix (const IContainer & coarseIndex, const CRConnectivity & coarseToFine, const CRConnectivity & coarseConnectivity) virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >, CRMatrixRect< T_Coeff, X, B >, and DiagonalMatrix< Diag, X >.
Definition at line 32 of file Matrix.cpp.
Referenced by MultiFieldMatrix::createCoarseMatrices().
 {
   throw CException("createCoarseMatrix not implemented");
 }
int Matrix::createCoarsening (IContainer & coarseIndex, const int groupSize, const double weighRatioThreshold) virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 16 of file Matrix.cpp.
Referenced by MultiFieldMatrix::createCoarsening().
 {
   throw CException("createCoarsening not implemented");
 }
virtual shared_ptr<Matrix> Matrix::createMergeMatrix (const LinearSystemMerger & mergeLS) inline virtual
Definition at line 57 of file Matrix.h.
 { throw;}
Matrix::DEFINE_TYPENAME ("Matrix")
virtual void Matrix::eliminateBoundaryEquations (IContainer & xB) inline virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 50 of file Matrix.h.
Referenced by LinearSystem::initSolve().
 {throw;}
void Matrix::forwardGS (IContainer & xB, IContainer & bB, IContainer & residual) const virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >, and DiagonalMatrix< Diag, X >.
Definition at line 51 of file Matrix.cpp.
Referenced by MultiFieldMatrix::forwardGS().
 {
   throw CException("forwardGS not implemented");
 }
virtual const CRConnectivity& Matrix::getConnectivity () const inline virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >, CRMatrixRect< T_Coeff, X, B >, CRMatrixTranspose< T_Coeff, X, B >, and FluxJacobianMatrix< OffDiag, X >.
Definition at line 48 of file Matrix.h.
Referenced by DirectSolver::solve().
 {throw;}
virtual void* Matrix::getDiagData () const inline virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 53 of file Matrix.h.
 {throw;}
virtual int Matrix::getDiagDataSize () const inline virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 55 of file Matrix.h.
 {throw;}
virtual void* Matrix::getOffDiagData () const inline virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 54 of file Matrix.h.
 {throw;}
virtual int Matrix::getOffDiagDataSize () const inline virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 56 of file Matrix.h.
 {throw;}
void Matrix::iluSolve (IContainer & xB, const IContainer & bB, const IContainer & residual) const virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 69 of file Matrix.cpp.
Referenced by MultiFieldMatrix::iluSolve().
 {
   throw CException("iluSolve not implemented");
 }
virtual void Matrix::initAssembly () pure virtual
Implemented in CRMatrix< T_Diag, T_OffDiag, X >, DiagonalMatrix< Diag, X >, CRMatrixRect< T_Coeff, X, B >, SpikeMatrix< T_Diag, T_OffDiag, X >, CRMatrixTranspose< T_Coeff, X, B >, and FluxJacobianMatrix< OffDiag, X >.
virtual bool Matrix::isInvertible () inline virtual
Reimplemented in DiagonalMatrix< Diag, X >.
Definition at line 73 of file Matrix.h.
Referenced by LinearSystem::initSolve().
 {return false;}
void Matrix::Jacobi (IContainer & xnew, const IContainer & xold, const IContainer & b) const virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 63 of file Matrix.cpp.
Referenced by MultiFieldMatrix::Jacobi().
 {
   throw CException("Jacobi not implemented");
 }
void Matrix::multiply (IContainer & yB, const IContainer & xB) const virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >, CRMatrixRect< T_Coeff, X, B >, CRMatrixTranspose< T_Coeff, X, B >, DiagonalMatrix< Diag, X >, and FluxJacobianMatrix< OffDiag, X >.
Definition at line 40 of file Matrix.cpp.
 {
   throw CException("multiply not implemented");
 }
void Matrix::multiplyAndAdd (IContainer & yB, const IContainer & xB) const virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >, CRMatrixRect< T_Coeff, X, B >, CRMatrixTranspose< T_Coeff, X, B >, FluxJacobianMatrix< OffDiag, X >, and DiagonalMatrix< Diag, X >.
Definition at line 46 of file Matrix.cpp.
Referenced by MultiFieldMatrix::computeResidual(), MultiFieldMatrix::forwardGS(), MultiFieldMatrix::Jacobi(), MultiFieldMatrix::multiply(), MultiFieldMatrix::multiplyAndAdd(), MultiFieldMatrix::reverseGS(), and MultiFieldMatrix::solveBoundary().
 {
   throw CException("multiplyAndAdd not implemented");
 }
virtual void Matrix::printRow (const int nr) const inline virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 51 of file Matrix.h.
 {throw;}
virtual shared_ptr<ArrayBase> Matrix::quadProduct (const IContainer & xB) const inline virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 28 of file Matrix.h.
Referenced by MultiFieldMatrix::quadProduct().
 {throw;}
void Matrix::reverseGS (IContainer & xB, IContainer & bB, IContainer & residual) const virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >, and DiagonalMatrix< Diag, X >.
Definition at line 57 of file Matrix.cpp.
Referenced by MultiFieldMatrix::reverseGS().
 {
   throw CException("reverseGS not implemented");
 }
virtual void Matrix::setFlatMatrix (Matrix & fmg) const inline virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 59 of file Matrix.h.
Referenced by DirectSolver::solve().
 {throw;}
void Matrix::solveBoundary (IContainer & xB, IContainer & bB, IContainer & residual) const virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >, and DiagonalMatrix< Diag, X >.
Definition at line 81 of file Matrix.cpp.
Referenced by MultiFieldMatrix::solveBoundary().
 {
   throw CException("solveBoundary not implemented");
 }
void Matrix::spikeSolve (IContainer & xB, const IContainer & bB, const IContainer & residual, const SpikeStorage & spike_storage) const virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >.
Definition at line 74 of file Matrix.cpp.
Referenced by MultiFieldMatrix::spikeSolve().
 {
    throw CException("spikeSolve not imlemented");
 }
virtual void Matrix::transpose () inline virtual
Reimplemented in CRMatrix< T_Diag, T_OffDiag, X >, DiagonalMatrix< Diag, X >, and FluxJacobianMatrix< OffDiag, X >.
Definition at line 61 of file Matrix.h.
 {throw;}
The documentation for this class was generated from the following files:
Matrix.h
Matrix.cpp