Memosa-FVM: kvol< T > Class Template Reference
kvol< T > Class Template Reference
#include <kvol.h>
Public Types
typedef kvol< T > Tkvol
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef Vector< T_Scalar, 3 > Tvec
typedef pmode< T > Tmode
typedef shared_ptr< Tmode > Tmodeptr
typedef vector< Tmodeptr > Modes
Public Member Functions
kvol (Tmodeptr mode, T dk3)
kvol ()
kvol (const int modes)
Tvec getkvec ()
void setkvec (Tvec K)
void setdk3 (T dk3)
T getdk3 ()
int getmodenum ()
Tmode & getmode (int n) const
Modes & getModes ()
Tkvol & operator= (Tkvol &o)
void copyKvol (Tkvol &inKvol)
Private Member Functions
kvol (const kvol &)
Private Attributes
T _dk3
Tvec _Kvector
int _modenum
Modes _modes
Detailed Description
template<class T>
class kvol< T >
Definition at line 14 of file kvol.h.
Member Typedef Documentation
template<class T > typedef vector<Tmodeptr> kvol< T >::Modes
Definition at line 24 of file kvol.h.
template<class T > typedef NumTypeTraits<T>::T_Scalar kvol< T >::T_Scalar
Definition at line 20 of file kvol.h.
template<class T > typedef kvol<T> kvol< T >::Tkvol
Definition at line 19 of file kvol.h.
template<class T > typedef pmode<T> kvol< T >::Tmode
Definition at line 22 of file kvol.h.
template<class T > typedef shared_ptr<Tmode> kvol< T >::Tmodeptr
Definition at line 23 of file kvol.h.
template<class T > typedef Vector<T_Scalar,3> kvol< T >::Tvec
Definition at line 21 of file kvol.h.
Constructor & Destructor Documentation
template<class T > kvol< T >::kvol (Tmodeptr mode, T dk3) inline
Definition at line 26 of file kvol.h.
                           :     //used in gray approx.
   _dk3(dk3),
     _modenum(1),
     _modes(1,mode)
       {}
template<class T > kvol< T >::kvol () inline
Definition at line 32 of file kvol.h.
     {}
template<class T > kvol< T >::kvol (const int modes) inline
Definition at line 35 of file kvol.h.
                       :
   _modenum(modes)
     {}
template<class T > kvol< T >::kvol (const kvol< T > &) private
Member Function Documentation
template<class T > void kvol< T >::copyKvol (Tkvol< T > & inKvol) inline
Definition at line 59 of file kvol.h.
References kvol< T >::_dk3, kvol< T >::_modenum, kvol< T >::_modes, kvol< T >::getdk3(), kvol< T >::getmode(), and kvol< T >::getmodenum().
   {
     const int m=inKvol.getmodenum();
     _modenum=m;
     _dk3=inKvol.getdk3();
     _modes.clear();
     for(int i=0;i<m;i++)
       {
         Tmodeptr newPmode=Tmodeptr(new Tmode());
         newPmode->copyPmode(inKvol.getmode(i));
         _modes.push_back(newPmode);
       }
   }
template<class T > T kvol< T >::getdk3 () inline
Definition at line 42 of file kvol.h.
References kvol< T >::_dk3.
Referenced by PhononInterface< X >::applyInterfaceCondition(), PhononBoundary< X >::applyReflectingWall(), COMETModel< T >::binwiseHeatFluxIntegral(), Kspace< T >::calcBallisticInterface(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), Kspace< T >::calcBandTemp(), COMETModel< T >::calcBandTemps(), DensityOfStates< T >::calcBinFlux(), Kspace< T >::calcDiffuseE(), Kspace< T >::calcDK3(), Kspace< T >::calcLatTemp(), COMETModel< T >::calcModeFlux(), COMETModel< T >::calcModeTemps(), Kspace< T >::calcSpecificHeat(), Kspace< T >::calcTauTot(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETEquilibrium(), kvol< T >::copyKvol(), Kspace< T >::FindBallisticHeatRate(), Kspace< T >::findKnStats(), COMETInterface< T >::findWallTemp(), Kspace< T >::getde0taudT(), Kspace< T >::gete0(), Kspace< T >::gete0_tau(), Kspace< T >::gete0CellVars(), Kspace< T >::gete0v(), Kspace< T >::getHollandConductivity(), Kspace< T >::getModewiseBallisticConductance(), Kspace< T >::getModewiseHollandConductivity(), Kspace< T >::getRTAsources(), ScatteringKernel< T >::getTypeIIsource(), ScatteringKernel< T >::getTypeIsource(), PhononModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), PhononModel< T >::init(), ScatteringKernel< T >::IterateToEquilibrium(), COMETInterface< T >::makeDMMcoeffs(), COMETModel< T >::modewiseHeatFluxIntegral(), DensityOfStates< T >::setDensity(), DensityOfStates< T >::sumOutgoing(), COMETDiscretizer< T >::updateeShifted(), COMETDiscretizer< T >::updateGhostCoarse(), PhononModel< T >::updateHeatFlux(), ScatteringKernel< T >::updateSource(), ScatteringKernel< T >::updateSource2(), ScatteringKernel< T >::updateSourceTermTest(), PhononModel< T >::updateTL(), and Kspace< T >::weightArray().
 {return _dk3;}
template<class T > Tvec kvol< T >::getkvec () inline
Definition at line 39 of file kvol.h.
References kvol< T >::_Kvector.
Referenced by Kspace< T >::getWaveVectors(), and COMETDiscretizer< T >::updateeShifted().
 {return _Kvector;}
template<class T > Tmode& kvol< T >::getmode (int n) const inline
Definition at line 44 of file kvol.h.
References kvol< T >::_modes.
Referenced by COMETInterface< T >::addFAS(), PhononModel< T >::advance(), PhononInterface< X >::applyInterfaceCondition(), PhononBoundary< X >::applyReflectingWall(), PhononBoundary< X >::applyTemperatureWall(), COMETBoundary< T >::applyTemperatureWallCoarse(), COMETBoundary< T >::applyTemperatureWallFine(), DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::binMode(), COMETModel< T >::binwiseHeatFluxIntegral(), Kspace< T >::calcBallisticInterface(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), Kspace< T >::calcBandTemp(), COMETModel< T >::calcBandTemps(), DensityOfStates< T >::calcBinFlux(), Kspace< T >::calcDiffuseE(), COMETModel< T >::calcModeFlux(), COMETModel< T >::calcModeTemps(), Kspace< T >::calcPhononTemp(), Kspace< T >::calcSpecificHeat(), Kspace< T >::calcTauTot(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETFullScatt(), COMETDiscretizer< T >::COMETShifted(), kvol< T >::copyKvol(), COMETDiscretizer< T >::Distribute(), COMETModel< T >::equilibrate(), Kspace< T >::FindBallisticHeatRate(), Kspace< T >::findKnStats(), Kspace< T >::findSpecs(), COMETInterface< T >::findWallTemp(), COMETDiscretizer< T >::gatherResid(), Kspace< T >::getde0taudT(), Kspace< T >::gete0(), Kspace< T >::gete0_tau(), Kspace< T >::gete0v(), Kspace< T >::getEquilibriumArray(), Kspace< T >::getHollandConductivity(), Kspace< T >::getModewiseBallisticConductance(), Kspace< T >::getModewiseHollandConductivity(), Kspace< T >::getReflectionArray(), Kspace< T >::getRTAsources(), Kspace< T >::getTauArrayPy(), ScatteringKernel< T >::getTypeIIsource(), ScatteringKernel< T >::getTypeIsource(), COMETModel< T >::getValueArray(), Kspace< T >::getVelocities(), PhononModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), PhononModel< T >::init(), COMETModel< T >::init(), COMETModel< T >::initCoarse(), ScatteringKernel< T >::IterateToEquilibrium(), Kspace< T >::Kspace(), Kspace< T >::makeDegenerate(), COMETInterface< T >::makeDMMcoeffs(), COMETInterface< T >::makeEquilibriumArray(), Kspace< T >::makeFreqArray(), COMETDiscretizer< T >::makeValueArray(), DensityOfStates< T >::mergeBins(), COMETModel< T >::modewiseHeatFluxIntegral(), kvol< T >::operator=(), COMETDiscretizer< T >::ScatterPhonons(), Kspace< T >::setCp(), Kspace< T >::setCpNonGray(), COMETModel< T >::sete0(), Kspace< T >::setTref(), DensityOfStates< T >::sumOutgoing(), PhononModel< T >::updatee0(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateeShifted(), COMETDiscretizer< T >::updateGhostCoarse(), COMETDiscretizer< T >::updateGhostFine(), PhononModel< T >::updateHeatFlux(), ScatteringKernel< T >::updateSource(), ScatteringKernel< T >::updateSource2(), PhononModel< T >::updateTL(), and COMETInterface< T >::ZeroGhost().
 {return *_modes[n];}
template<class T > int kvol< T >::getmodenum () inline
Definition at line 43 of file kvol.h.
References kvol< T >::_modenum.
Referenced by COMETInterface< T >::addFAS(), PhononModel< T >::advance(), PhononInterface< X >::applyInterfaceCondition(), PhononBoundary< X >::applyReflectingWall(), PhononBoundary< X >::applyTemperatureWall(), COMETBoundary< T >::applyTemperatureWallCoarse(), COMETBoundary< T >::applyTemperatureWallFine(), DensityOfStates< T >::binEntireKspace(), Kspace< T >::calcBallisticInterface(), COMETModel< T >::calcBandRelEnergy(), Kspace< T >::calcDiffuseE(), Kspace< T >::calcLatTemp(), COMETModel< T >::calcModeFlux(), Kspace< T >::calcPhononTemp(), Kspace< T >::calcSpecificHeat(), Kspace< T >::calcTauTot(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETFullScatt(), COMETDiscretizer< T >::COMETShifted(), kvol< T >::copyKvol(), COMETModel< T >::correctSolution(), COMETDiscretizer< T >::Distribute(), COMETModel< T >::equilibrate(), Kspace< T >::FindBallisticHeatRate(), Kspace< T >::findKnStats(), COMETInterface< T >::findWallTemp(), COMETDiscretizer< T >::gatherResid(), Kspace< T >::getde0taudT(), Kspace< T >::gete0(), Kspace< T >::gete0_tau(), Kspace< T >::gete0CellVars(), Kspace< T >::gete0v(), Kspace< T >::getEquilibriumArray(), Kspace< T >::getHollandConductivity(), Kspace< T >::getModewiseBallisticConductance(), Kspace< T >::getModewiseHollandConductivity(), Kspace< T >::getReflectionArray(), Kspace< T >::getRTAsources(), Kspace< T >::getTauArrayPy(), ScatteringKernel< T >::getTypeIIsource(), ScatteringKernel< T >::getTypeIsource(), COMETModel< T >::getValueArray(), Kspace< T >::getVelocities(), PhononModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), PhononModel< T >::init(), COMETModel< T >::init(), COMETModel< T >::initCoarse(), COMETModel< T >::injectResid(), ScatteringKernel< T >::IterateToEquilibrium(), Kspace< T >::Kspace(), Kspace< T >::makeDegenerate(), COMETInterface< T >::makeEquilibriumArray(), Kspace< T >::makeFreqArray(), COMETDiscretizer< T >::makeValueArray(), DensityOfStates< T >::mergeBins(), COMETModel< T >::modewiseHeatFluxIntegral(), kvol< T >::operator=(), COMETDiscretizer< T >::ScatterPhonons(), Kspace< T >::setCp(), Kspace< T >::setCpNonGray(), COMETModel< T >::sete0(), Kspace< T >::setTref(), PhononModel< T >::updatee0(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateeShifted(), COMETDiscretizer< T >::updateGhostCoarse(), COMETDiscretizer< T >::updateGhostFine(), PhononModel< T >::updateHeatFlux(), ScatteringKernel< T >::updateSource(), ScatteringKernel< T >::updateSource2(), ScatteringKernel< T >::updateSourceTermTest(), PhononModel< T >::updateTL(), Kspace< T >::weightArray(), and COMETInterface< T >::ZeroGhost().
 {return _modenum;}
template<class T > Modes& kvol< T >::getModes () inline
Definition at line 45 of file kvol.h.
References kvol< T >::_modes.
 {return _modes;}
template<class T > Tkvol& kvol< T >::operator= (Tkvol< T > & o) inline
Definition at line 46 of file kvol.h.
References kvol< T >::_modes, kvol< T >::getmode(), and kvol< T >::getmodenum().
     {
       const int m=o.getmodenum();
       _modes.clear();
       _modes.resize(m);
       for(int i=0;i<m;i++)
         {
           Tmodeptr newPmode=Tmodeptr(new Tmode());
           _modes[i]=newPmode;
           (*(_modes[i]))=o.getmode(i);
         }
       return *this;
     }
template<class T > void kvol< T >::setdk3 (T dk3) inline
Definition at line 41 of file kvol.h.
References kvol< T >::_dk3.
 {_dk3=dk3;}
template<class T > void kvol< T >::setkvec (Tvec K) inline
Definition at line 40 of file kvol.h.
References kvol< T >::_Kvector.
 {_Kvector=K;}
Member Data Documentation
template<class T > T kvol< T >::_dk3 private
Definition at line 78 of file kvol.h.
Referenced by kvol< T >::copyKvol(), kvol< T >::getdk3(), and kvol< T >::setdk3().
template<class T > Tvec kvol< T >::_Kvector private
Definition at line 81 of file kvol.h.
Referenced by kvol< T >::getkvec(), and kvol< T >::setkvec().
template<class T > int kvol< T >::_modenum private
Definition at line 84 of file kvol.h.
Referenced by kvol< T >::copyKvol(), and kvol< T >::getmodenum().
template<class T > Modes kvol< T >::_modes private
Definition at line 87 of file kvol.h.
Referenced by kvol< T >::copyKvol(), kvol< T >::getmode(), kvol< T >::getModes(), and kvol< T >::operator=().
The documentation for this class was generated from the following file:
kvol.h