Memosa-FVM: GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > > Class Template Reference
GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > > Class Template Reference
#include <GenericBCS.h>
Public Types
typedef BaseGenericBCS< Vector
< T, N >, SquareTensor< T, N >
, SquareTensor< T, N > > T_Parent
typedef Vector< T, N > X
typedef SquareTensor< T, N > Diag
typedef SquareTensor< T, N > OffDiag
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef FluxJacobianMatrix
< OffDiag, X > FMatrix
typedef DiagonalMatrix< Diag, X > BBMatrix
typedef Array< Diag > DiagArray
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
typedef Array< VectorT3 > VectorT3Array
Public Types inherited from BaseGenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >
typedef NumTypeTraits< Vector
< T, N > >::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Array< int > IntArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef CRMatrix< SquareTensor
< T, N >, SquareTensor< T, N >
, Vector< T, N > > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef FluxJacobianMatrix
< SquareTensor< T, N >, Vector
< T, N > > FMatrix
typedef DiagonalMatrix
< SquareTensor< T, N >, Vector
< T, N > > BBMatrix
typedef Array< SquareTensor< T,
N > > DiagArray
typedef Array< SquareTensor< T,
N > > OffDiagArray
typedef Array< Vector< T, N > > XArray
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
GenericBCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, Field &fluxField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
void applySymmetryBC () const
Public Member Functions inherited from BaseGenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >
BaseGenericBCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, Field &fluxField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
void applyDirichletBC (int f, const Vector< T, N > &bValue) const
void applyDirichletBC (const Vector< T, N > &bValue) const
void applyDirichletBC (const FloatValEvaluator< Vector< T, N > > &bValue) const
void applyNeumannBC (const int f, const Vector< T, N > &specifiedFlux) const
void applyNeumannBC (const Vector< T, N > &bFlux) const
void applyNeumannBC (const FloatValEvaluator< Vector< T, N > > &bFlux) const
void applyExtrapolationBC () const
void applyExtrapolationBC (const int f) const
void applyConvectionBC (const int f, const Vector< T, N > &hCoeff, const Vector< T, N > &Xinf) const
void applyConvectionBC (const Vector< T, N > &hCoeff, const Vector< T, N > &Xinf) const
void applyRadiationBC (const int f, const Vector< T, N > &emissivity, const Vector< T, N > &Xinf) const
void applyMixedBC (const int f, const Vector< T, N > &hCoeff, const Vector< T, N > &emissivity, const Vector< T, N > &Xinf) const
void applyInterfaceBC (const int f) const
void applyInterfaceBC () const
void applyDielectricInterfaceBC (const int f, const Vector< T, N > &hCoeff, const Vector< T, N > &Xinf, const Vector< T, N > &source) const
void applyDielectricInterfaceBC (const Vector< T, N > &hCoeff, const Vector< T, N > &Xinf, const Vector< T, N > &source) const
void applyFlowBC (const TArray &convFlux, const Vector< T, N > &bValue) const
void applyNonzeroDiagBC () const
void applyNonzeroDiagBC (int f) const
Additional Inherited Members
Protected Attributes inherited from BaseGenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >
const StorageSite & _faces
const StorageSite & _cells
const IntArray & _ibType
const CRConnectivity & _faceCells
const Field & _varField
const Field & _fluxField
const MultiField::ArrayIndex _xIndex
const MultiField::ArrayIndex _fluxIndex
CCMatrix & _dRdX
FMatrix & _dFluxdX
BBMatrix & _dFluxdFlux
CCAssembler & _assembler
DiagArray & _dRdXDiag
XArray & _x
XArray & _r
XArray & _flux
XArray & _rFlux
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
const bool _is2D
Detailed Description
template<class T, int N>
class GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >
Definition at line 701 of file GenericBCS.h.
Member Typedef Documentation
template<class T , int N> typedef DiagonalMatrix<Diag,X> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::BBMatrix
Definition at line 719 of file GenericBCS.h.
template<class T , int N> typedef CCMatrix::PairWiseAssembler GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::CCAssembler
Definition at line 716 of file GenericBCS.h.
template<class T , int N> typedef CRMatrix<Diag,OffDiag,X> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::CCMatrix
Definition at line 715 of file GenericBCS.h.
template<class T , int N> typedef SquareTensor<T,N> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::Diag
Definition at line 707 of file GenericBCS.h.
template<class T , int N> typedef Array<Diag> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::DiagArray
Definition at line 721 of file GenericBCS.h.
template<class T , int N> typedef FluxJacobianMatrix<OffDiag,X> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::FMatrix
Definition at line 718 of file GenericBCS.h.
template<class T , int N> typedef SquareTensor<T,N> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::OffDiag
Definition at line 708 of file GenericBCS.h.
template<class T , int N> typedef Array<OffDiag> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::OffDiagArray
Definition at line 722 of file GenericBCS.h.
template<class T , int N> typedef BaseGenericBCS<Vector<T,N>, SquareTensor<T,N>, SquareTensor<T,N> > GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::T_Parent
Definition at line 705 of file GenericBCS.h.
template<class T , int N> typedef NumTypeTraits<X>::T_Scalar GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::T_Scalar
Definition at line 710 of file GenericBCS.h.
template<class T , int N> typedef Array<T_Scalar> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::TArray
Definition at line 712 of file GenericBCS.h.
template<class T , int N> typedef Vector<T_Scalar,3> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::VectorT3
Definition at line 713 of file GenericBCS.h.
template<class T , int N> typedef Array<VectorT3> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::VectorT3Array
Definition at line 725 of file GenericBCS.h.
template<class T , int N> typedef Vector<T,N> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::X
Definition at line 706 of file GenericBCS.h.
template<class T , int N> typedef Array<X> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::XArray
Definition at line 724 of file GenericBCS.h.
Constructor & Destructor Documentation
template<class T , int N> GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::GenericBCS (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, Field & varField, Field & fluxField, MultiFieldMatrix & matrix, MultiField & xField, MultiField & rField) inline
Definition at line 728 of file GenericBCS.h.
                                                      :
     T_Parent(faces,mesh,geomFields,varField,fluxField,matrix,xField,rField)
   {}
Member Function Documentation
template<class T , int N> void GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::applySymmetryBC () const inline
Definition at line 739 of file GenericBCS.h.
References BaseGenericBCS< X, Diag, OffDiag >::_assembler, BaseGenericBCS< X, Diag, OffDiag >::_dFluxdFlux, BaseGenericBCS< X, Diag, OffDiag >::_dRdX, BaseGenericBCS< X, Diag, OffDiag >::_dRdXDiag, BaseGenericBCS< X, Diag, OffDiag >::_faceArea, BaseGenericBCS< X, Diag, OffDiag >::_faceAreaMag, BaseGenericBCS< X, Diag, OffDiag >::_faceCells, BaseGenericBCS< X, Diag, OffDiag >::_faces, BaseGenericBCS< X, Diag, OffDiag >::_flux, BaseGenericBCS< X, Diag, OffDiag >::_r, BaseGenericBCS< X, Diag, OffDiag >::_rFlux, BaseGenericBCS< X, Diag, OffDiag >::_x, dot(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), and CRMatrix< T_Diag, T_OffDiag, X >::setBoundary().
   {
     for(int f=0; f<this->_faces.getCount(); f++)
     {
         const int c0 = this->_faceCells(f,0);
         const int c1 = this->_faceCells(f,1);
         // the current value of flux and its Jacobians
         const X fluxB = -this->_r[c1];
         const OffDiag dFluxdXC0 = -this->_assembler.getCoeff10(f);
         const Diag dFluxdXC1 = -this->_dRdXDiag[c1];
         const VectorT3 en = this->_faceArea[f]/this->_faceAreaMag[f];
         const T xC0_dotn = dot(this->_x[c0],en);
         const X xB = this->_x[c0] - xC0_dotn * en;
         Diag dxBdxC0(Diag::getZero());
         dxBdxC0(0,0) =  1.0 - en[0]*en[0];
         dxBdxC0(0,1) =  - en[0]*en[1];
         dxBdxC0(0,2) =  - en[0]*en[2];
         dxBdxC0(1,0) =  - en[1]*en[0];
         dxBdxC0(1,1) =  1.0 - en[1]*en[1];
         dxBdxC0(1,2) =  - en[1]*en[2];
         dxBdxC0(2,0) =  - en[2]*en[0];
         dxBdxC0(2,1) =  - en[2]*en[1];
         dxBdxC0(2,2) =  1.0 - en[2]*en[2];
         const X xc1mxB = this->_x[c1]-xB;
         this->_x[c1] = xB;
         // eliminate boundary dependency from cell equation
         this->_dRdXDiag[c0] += dFluxdXC1*dxBdxC0;
         this->_r[c0] += dFluxdXC1*xc1mxB;
         this->_assembler.getCoeff01(f) = NumTypeTraits<OffDiag>::getZero();
         // boundary value equation
         this->_dRdXDiag[c1] = NumTypeTraits<Diag>::getNegativeUnity();
         this->_assembler.getCoeff10(f) = dxBdxC0;
         this->_r[c1] = NumTypeTraits<X>::getZero();//xc0mxB;
         this->_dRdX.setBoundary(c1);
         //setup the equation for the boundary flux correction
         //this->_dFluxdX.setCoeffL(f,dFluxdXC0);
         //this->_dFluxdX.setCoeffR(f,dFluxdXC1);
         this->_flux[f] = fluxB - dFluxdXC1*xc1mxB;
         this->_rFlux[f] = T_Scalar(0);
         this->_dFluxdFlux[f] = NumTypeTraits<Diag>::getNegativeUnity();
     }
   }
The documentation for this class was generated from the following file:
GenericBCS.h