Memosa-FVM: GradientMatrix< T_Scalar > Class Template Reference
GradientMatrix< T_Scalar > Class Template Reference
#include <GradientMatrix.h>
Classes
class PairWiseAssembler
Public Types
typedef Vector< T_Scalar, 3 > Coord
Public Types inherited from GradientMatrixBase
typedef pair< const
StorageSite *, const
StorageSite * > EntryIndex
typedef map< EntryIndex,
shared_ptr< ArrayBase > > GhostArrayMap
Public Member Functions
GradientMatrix (const Mesh &mesh)
virtual ~GradientMatrix ()
template<class X >
shared_ptr< Array< Gradient< X > > > getGradient (const Array< X > &x) const
template<class X >
void computeGradient (Gradient< X > &g, const Array< X > &x, int i) const
template<class X >
X computeR (const Gradient< X > &g, const Array< X > &x, const Coord dist, int i, int j) const
template<class X >
void computeFaceGradient (Gradient< X > &g, const Array< X > &x, int i) const
const CRConnectivity & getConnectivity () const
Array< Coord > & getCoeffs ()
const Array< Coord > & getCoeffs () const
Coord & getCoeff (const int i, const int j)
const Coord & getCoeff (const int i, const int j) const
PairWiseAssembler & getPairWiseAssembler (const CRConnectivity &pairs)
void createScatterGatherValuesBuffer ()
void recvScatterGatherValuesBufferLocal ()
void syncValues ()
Public Member Functions inherited from GradientMatrixBase
GradientMatrixBase ()
virtual void syncLocal ()
virtual ~GradientMatrixBase ()
Private Member Functions
int get_request_size ()
virtual void printRow (const int i) const
Private Attributes
const Mesh & _mesh
const CRConnectivity & _conn
const Array< int > & _row
const Array< int > & _col
Array< Coord > _coeffs
map< const CRConnectivity
*, PairWiseAssembler * > _pairWiseAssemblers
Detailed Description
template<class T_Scalar>
class GradientMatrix< T_Scalar >
Definition at line 31 of file GradientMatrix.h.
Member Typedef Documentation
template<class T_Scalar> typedef Vector<T_Scalar,3> GradientMatrix< T_Scalar >::Coord
Definition at line 34 of file GradientMatrix.h.
Constructor & Destructor Documentation
template<class T_Scalar> GradientMatrix< T_Scalar >::GradientMatrix (const Mesh & mesh) inline
Definition at line 36 of file GradientMatrix.h.
                                    :
     _mesh(mesh),
 #ifdef FVM_PARALLEL
     _conn(mesh.getCellCellsGhostExt()),
     _row(_conn.getRow() ),
     _col(_conn.getCol() ),
 #else
     _conn(mesh.getCellCells()),
     _row(_conn.getRow()),
     _col(_conn.getCol()),
 #endif
     _coeffs(_col.getLength()),
     _pairWiseAssemblers()
   {
   }
template<class T_Scalar> virtual GradientMatrix< T_Scalar >::~GradientMatrix () inline virtual
Definition at line 52 of file GradientMatrix.h.
   {}
Member Function Documentation
template<class T_Scalar> template<class X > void GradientMatrix< T_Scalar >::computeFaceGradient (Gradient< X > & g, const Array< X > & x, int i) const inline
Definition at line 109 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_coeffs, GradientMatrix< T_Scalar >::_col, GradientMatrix< T_Scalar >::_row, Gradient< T >::accumulate(), and Gradient< T >::zero().
     {
       g.zero();
     // for boundaries use the adjacent cell
     if (_row[i+1] - _row[i]  == 1)
       i = _col[_row[i]];
     for (int nb = _row[i]; nb<_row[i+1]; nb++)
     {
         const int j = _col[nb];
         g.accumulate(_coeffs[nb],x[j]);
     }
   }
template<class T_Scalar> template<class X > void GradientMatrix< T_Scalar >::computeGradient (Gradient< X > & g, const Array< X > & x, int i) const inline
Definition at line 80 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_coeffs, GradientMatrix< T_Scalar >::_col, GradientMatrix< T_Scalar >::_row, Gradient< T >::accumulate(), and Gradient< T >::zero().
   {
     g.zero();
     // for boundaries use the adjacent cell
     if (_row[i+1] - _row[i]  == 1)
       i = _col[_row[i]];
     for (int nb = _row[i]; nb<_row[i+1]; nb++)
     {
         const int j = _col[nb];
         g.accumulate(_coeffs[nb],x[j]-x[i]);
     }
   }
template<class T_Scalar> template<class X > X GradientMatrix< T_Scalar >::computeR (const Gradient< X > & g, const Array< X > & x, const Coord dist, int i, int j) const inline
Definition at line 97 of file GradientMatrix.h.
Referenced by COMETBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC(), COMETESBGKDiscretizer< T >::COMETConvectionFine(), and COMETESBGKDiscretizer< T >::setBoundaryValFine().
     {//Darwish and Moukalled, Int. J. H. M. T., 46 (2003) 599-611
       X den=x[j]-x[i];
       X num=2.*(g*dist);
       if (den!=0.)
         return num/den-1.;
       return 0;
     }
template<class T_Scalar> void GradientMatrix< T_Scalar >::createScatterGatherValuesBuffer () inline
Definition at line 192 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_mesh, Mesh::getCellCells(), Mesh::getCells(), GradientMatrix< T_Scalar >::getCoeff(), CRConnectivity::getCount(), StorageSite::getGatherMap(), Array< T >::getLength(), Mesh::getRecvCounts(), and StorageSite::getScatterMap().
Referenced by GradientModel< Vector< T, 3 > >::compute().
     {
 #ifdef FVM_PARALLEL
        //SENDING allocation and filling
        const StorageSite& site     = _mesh.getCells();
        const CRConnectivity& cellCells = _mesh.getCellCells();
        const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
        foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
            const StorageSite&  oSite = *mpos.first;
            const Array<int>& scatterArray = *mpos.second;
            //loop over surround indices and itself for sizing
            EntryIndex e(&site,&oSite);
            int sendSize = 0;
            for ( int i = 0; i < scatterArray.getLength(); i++ ){
               sendSize += cellCells.getCount( scatterArray[i] );
            }
            //allocate array
            _sendValues[e]  = shared_ptr< Array<Coord> > ( new Array<Coord> (sendSize) );
            //fill send array
            Array<Coord>& valueArray = dynamic_cast< Array<Coord>& > ( *_sendValues[e]  );
            int indx = 0;
            for( int i = 0; i < scatterArray.getLength(); i++ ){
               const int ii = scatterArray[i];
               for ( int j = 0; j < cellCells.getCount(ii); j++ ){
                  const int jj = cellCells(ii,j);
                  valueArray[indx] = getCoeff(ii,jj);
                  indx++;
               }
            }
        }
        //RECIEVING allocation (filling will be done by MPI Communication)
        const StorageSite::GatherMap& gatherMap = site.getGatherMap();
        foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
           const StorageSite&  oSite = *mpos.first;
           EntryIndex e(&oSite,&site);
           //get recvSize
           const Array<int>& recvCounts   =  dynamic_cast< const Array<int>& > (_mesh.getRecvCounts(e));
           int recvSize = 0;
           for ( int i = 0; i < recvCounts.getLength(); i++ ){
              recvSize += recvCounts[i];
            }
           //allocate array
           _recvValues [e] = shared_ptr< Array<Coord> > ( new Array<Coord> (recvSize) );
        }
 #endif
     }
template<class T_Scalar> int GradientMatrix< T_Scalar >::get_request_size () inline private
Definition at line 343 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_mesh, Mesh::getCells(), StorageSite::getGatherProcID(), and StorageSite::getScatterMap().
Referenced by GradientMatrix< T_Scalar >::syncValues().
   {
       int indx =  0;
       const StorageSite& site = _mesh.getCells();
       const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
       foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
          const StorageSite&  oSite = *mpos.first;
          //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
          if ( oSite.getGatherProcID() != -1 )
             indx++;
       }
       return indx;
   }
template<class T_Scalar> Coord& GradientMatrix< T_Scalar >::getCoeff (const int i, const int j) inline
Definition at line 129 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_coeffs, GradientMatrix< T_Scalar >::_col, and GradientMatrix< T_Scalar >::_row.
Referenced by COMETBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), COMETBoundary< T >::applyTemperatureWallFine(), COMETBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC(), COMETESBGKDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETConvectionFine(), GradientMatrix< T_Scalar >::createScatterGatherValuesBuffer(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), COMETESBGKDiscretizer< T >::setBoundaryValFine(), GradientMatrix< T_Scalar >::syncValues(), and COMETDiscretizer< T >::updateGhostFine().
   {
     for (int nnb = _row[i]; nnb<_row[i+1]; nnb++)
     {
         if (_col[nnb] == j)
           return _coeffs[nnb];
     }
     throw CException("invalid indices");
   }
template<class T_Scalar> const Coord& GradientMatrix< T_Scalar >::getCoeff (const int i, const int j) const inline
Definition at line 141 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_coeffs, GradientMatrix< T_Scalar >::_col, and GradientMatrix< T_Scalar >::_row.
   {
     for (int nnb = _row[i]; nnb<_row[i+1]; nnb++)
     {
         if (_col[nnb] == j)
           return _coeffs[nnb];
     }
     throw CException("invalid indices");
   }
template<class T_Scalar> Array<Coord>& GradientMatrix< T_Scalar >::getCoeffs () inline
Definition at line 126 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_coeffs.
Referenced by MomentumPressureGradientDiscretization< X >::discretize(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), and GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D().
 {return _coeffs;}
template<class T_Scalar> const Array<Coord>& GradientMatrix< T_Scalar >::getCoeffs () const inline
Definition at line 127 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_coeffs.
 {return _coeffs;}
template<class T_Scalar> const CRConnectivity& GradientMatrix< T_Scalar >::getConnectivity () const inline
Definition at line 124 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_conn.
Referenced by StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), GradientMatrix< T_Scalar >::getGradient(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D(), and GradientMatrix< T_Scalar >::getPairWiseAssembler().
 {return _conn;}
template<class T_Scalar> template<class X > shared_ptr<Array<Gradient<X> > > GradientMatrix< T_Scalar >::getGradient (const Array< X > & x) const inline
Definition at line 57 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_coeffs, GradientMatrix< T_Scalar >::_col, GradientMatrix< T_Scalar >::_row, GradientMatrix< T_Scalar >::getConnectivity(), Array< T >::getLength(), CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
Referenced by GradientModel< Vector< T, 3 > >::compute().
   {
     typedef Gradient<X> GradType;
     typedef Array<GradType> GradArray;
     shared_ptr<GradArray> gradXPtr(new GradArray(x.getLength()));
     GradArray& gradX = *gradXPtr;
     const int nRows = getConnectivity().getRowSite().getSelfCount();
     for(int nr=0; nr<nRows; nr++)
     {
         gradX[nr].zero();
         for (int nb = _row[nr]; nb<_row[nr+1]; nb++)
         {
             const int j = _col[nb];
             gradX[nr].accumulate(_coeffs[nb],x[j]-x[nr]);
         }
     }
     return gradXPtr;
   }
template<class T_Scalar> PairWiseAssembler& GradientMatrix< T_Scalar >::getPairWiseAssembler (const CRConnectivity & pairs) inline
Definition at line 179 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_coeffs, GradientMatrix< T_Scalar >::_pairWiseAssemblers, and GradientMatrix< T_Scalar >::getConnectivity().
Referenced by GradientModel< Vector< T, 3 > >::compute(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), and GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D().
   {
     if (_pairWiseAssemblers.find(&pairs) == _pairWiseAssemblers.end())
     {
         _pairWiseAssemblers[&pairs] =
           new PairWiseAssembler(_coeffs,
                                 getConnectivity().getPairToColMapping(pairs));
     }
     return *_pairWiseAssemblers[&pairs];
   }
template<class T_Scalar> virtual void GradientMatrix< T_Scalar >::printRow (const int i) const inline private virtual
Definition at line 358 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_coeffs, GradientMatrix< T_Scalar >::_col, and GradientMatrix< T_Scalar >::_row.
   {
     for (int nb = _row[i]; nb<_row[i+1]; nb++)
     {
         const int j = _col[nb];
         cout << "coeff (" <<  i << "," << j << ") = " << _coeffs[nb] << endl;
     }
   }
template<class T_Scalar> void GradientMatrix< T_Scalar >::recvScatterGatherValuesBufferLocal () inline
Definition at line 240 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_mesh, Mesh::getCells(), StorageSite::getGatherMap(), and StorageSite::getGatherProcID().
Referenced by GradientModel< Vector< T, 3 > >::compute().
     {
 #ifdef FVM_PARALLEL
        //RECIEVING allocation (filling will be done by MPI Communication)
        const StorageSite& site     = _mesh.getCells();
        const StorageSite::GatherMap& gatherMap = site.getGatherMap();
        foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
           const StorageSite&  oSite = *mpos.first;
           EntryIndex e(&oSite,&site);
           //get recvSize
           //mesh interface can be done know
           if ( oSite.getGatherProcID() == - 1) {
              *_recvValues[e] = *_sendValues [e];
           }
        }
 #endif
     }
template<class T_Scalar> void GradientMatrix< T_Scalar >::syncValues () inline
Definition at line 259 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::_mesh, GradientMatrix< T_Scalar >::get_request_size(), Mesh::getCells(), GradientMatrix< T_Scalar >::getCoeff(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMap(), StorageSite::getGatherProcID(), Mesh::getGlobalToLocal(), Array< T >::getLength(), Mesh::getRecvCounts(), Mesh::getRecvIndices(), StorageSite::getScatterMap(), and StorageSite::getTag().
Referenced by GradientModel< Vector< T, 3 > >::compute().
     {
 #ifdef FVM_PARALLEL
           //SENDING
           const int  request_size = get_request_size();
           MPI::Request   request_send[ request_size ];
           MPI::Request   request_recv[ request_size ];
           int indxSend = 0;
           int indxRecv = 0;
           const StorageSite&    site      = _mesh.getCells();
           const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
           foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
              const StorageSite&  oSite = *mpos.first;
              EntryIndex e(&site,&oSite);
              //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              ArrayBase& sendArray = *_sendValues[e];
              //loop over surround indices and itself
              int to_where  = oSite.getGatherProcID();
              if ( to_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_send[indxSend++] =
                     MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
              }
           }
           //RECIEVING
           //getting values from other meshes to fill g
           const StorageSite::GatherMap& gatherMap = site.getGatherMap();
           foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
              const StorageSite&  oSite = *mpos.first;
              //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              EntryIndex e(&oSite,&site);
              ArrayBase& recvArray = *_recvValues[e];
              int from_where       = oSite.getGatherProcID();
              if ( from_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_recv[indxRecv++] =
                       MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
              }
           }
           int count  = get_request_size();
           MPI::Request::Waitall( count, request_recv );
           MPI::Request::Waitall( count, request_send );
 //           const StorageSite&    site      = _mesh.getCells();
 //           const StorageSite::GatherMap& gatherMap = site.getGatherMap();
           //replacing values
           const map<int,int>&   globalToLocal = _mesh.getGlobalToLocal();
           foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
              const StorageSite&  oSite = *mpos.first;
              const Array<int>& gatherArray = dynamic_cast< const Array<int>& > (*mpos.second);
              //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              int from_where       = oSite.getGatherProcID();
              if ( from_where != -1 ){
                 EntryIndex e(&oSite,&site);
                 const Array<int>  & recv_counts  = dynamic_cast< const Array<int>&   > (_mesh.getRecvCounts(e) );
                 const Array<int>  & recv_indices = dynamic_cast< const Array<int>&   > (_mesh.getRecvIndices(e));
                 const Array<Coord>& recv_values  = dynamic_cast< const Array<Coord>& > (*_recvValues [e]);
                 //loop over gatherArray
                 int indx = 0;
                 for ( int i = 0; i < gatherArray.getLength(); i++ ){
                    const int ii  = gatherArray[i];
                    const int nnb = recv_counts[i]; //give getCount()
                    for ( int nb = 0; nb < nnb; nb++ ){
                       const int jj = globalToLocal.find( recv_indices[indx] )->second;
                        Coord& matrix_entry = getCoeff(ii,jj);
                        matrix_entry = recv_values[indx];
                        indx++;
                    }
                 }
              }
           }
 #endif
     }
Member Data Documentation
template<class T_Scalar> Array<Coord> GradientMatrix< T_Scalar >::_coeffs private
Definition at line 374 of file GradientMatrix.h.
Referenced by GradientMatrix< T_Scalar >::computeFaceGradient(), GradientMatrix< T_Scalar >::computeGradient(), GradientMatrix< T_Scalar >::getCoeff(), GradientMatrix< T_Scalar >::getCoeffs(), GradientMatrix< T_Scalar >::getGradient(), GradientMatrix< T_Scalar >::getPairWiseAssembler(), and GradientMatrix< T_Scalar >::printRow().
template<class T_Scalar> const Array<int>& GradientMatrix< T_Scalar >::_col private
Definition at line 371 of file GradientMatrix.h.
Referenced by GradientMatrix< T_Scalar >::computeFaceGradient(), GradientMatrix< T_Scalar >::computeGradient(), GradientMatrix< T_Scalar >::getCoeff(), GradientMatrix< T_Scalar >::getGradient(), and GradientMatrix< T_Scalar >::printRow().
template<class T_Scalar> const CRConnectivity& GradientMatrix< T_Scalar >::_conn private
Definition at line 369 of file GradientMatrix.h.
Referenced by GradientMatrix< T_Scalar >::getConnectivity().
template<class T_Scalar> const Mesh& GradientMatrix< T_Scalar >::_mesh private
Definition at line 368 of file GradientMatrix.h.
Referenced by GradientMatrix< T_Scalar >::createScatterGatherValuesBuffer(), GradientMatrix< T_Scalar >::get_request_size(), GradientMatrix< T_Scalar >::recvScatterGatherValuesBufferLocal(), and GradientMatrix< T_Scalar >::syncValues().
template<class T_Scalar> map<const CRConnectivity*,PairWiseAssembler*> GradientMatrix< T_Scalar >::_pairWiseAssemblers mutable private
Definition at line 375 of file GradientMatrix.h.
Referenced by GradientMatrix< T_Scalar >::getPairWiseAssembler().
template<class T_Scalar> const Array<int>& GradientMatrix< T_Scalar >::_row private
Definition at line 370 of file GradientMatrix.h.
Referenced by GradientMatrix< T_Scalar >::computeFaceGradient(), GradientMatrix< T_Scalar >::computeGradient(), GradientMatrix< T_Scalar >::getCoeff(), GradientMatrix< T_Scalar >::getGradient(), and GradientMatrix< T_Scalar >::printRow().
The documentation for this class was generated from the following file:
GradientMatrix.h