Memosa-FVM: DriftDiscretization< X, Diag, OffDiag > Class Template Reference
DriftDiscretization< X, Diag, OffDiag > Class Template Reference
#include <DriftDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Array< int > IntArray
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
DriftDiscretization (const MeshList &meshes, const GeomFields &geomFields, Field &varField, const Field &convectingFluxField, const int nTrap, const bool useCentralDifference=false)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const Field & _convectingFluxField
const int _nTrap
const bool _useCentralDifference
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class DriftDiscretization< X, Diag, OffDiag >
Definition at line 18 of file DriftDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler DriftDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 24 of file DriftDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> DriftDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 22 of file DriftDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray DriftDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 23 of file DriftDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<int> DriftDiscretization< X, Diag, OffDiag >::IntArray
Definition at line 25 of file DriftDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar DriftDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 21 of file DriftDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> DriftDiscretization< X, Diag, OffDiag >::TArray
Definition at line 28 of file DriftDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> DriftDiscretization< X, Diag, OffDiag >::VectorT3
Definition at line 29 of file DriftDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> DriftDiscretization< X, Diag, OffDiag >::VectorT3Array
Definition at line 30 of file DriftDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> DriftDiscretization< X, Diag, OffDiag >::XArray
Definition at line 26 of file DriftDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > DriftDiscretization< X, Diag, OffDiag >::DriftDiscretization (const MeshList & meshes, const GeomFields & geomFields, Field & varField, const Field & convectingFluxField, const int nTrap, const bool useCentralDifference = false) inline
Definition at line 33 of file DriftDiscretization.h.
                                                               :
   Discretization(meshes),
     _geomFields(geomFields),
     _varField(varField),
     _convectingFluxField(convectingFluxField),
     _nTrap(nTrap),
     _useCentralDifference(useCentralDifference)
   {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void DriftDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 47 of file DriftDiscretization.h.
References DriftDiscretization< X, Diag, OffDiag >::_convectingFluxField, DriftDiscretization< X, Diag, OffDiag >::_nTrap, DriftDiscretization< X, Diag, OffDiag >::_varField, Mesh::getAllFaceCells(), Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), Mesh::getFaces(), MultiFieldMatrix::getMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), and Field::hasArray().
   {
     const StorageSite& cells = mesh.getCells();
     const StorageSite& faces = mesh.getFaces();
     // should there be some other checks ?
     if (!_convectingFluxField.hasArray(faces))
       return;
     const TArray& convectingFlux =
       dynamic_cast<const TArray&>(_convectingFluxField[faces]);
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix =
       dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     const CRConnectivity& faceCells = mesh.getAllFaceCells();
     CCAssembler& assembler = matrix.getPairWiseAssembler(faceCells);
     DiagArray& diag = matrix.getDiag();
     const XArray& xCell = dynamic_cast<const XArray&>(xField[cVarIndex]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     //const IntArray& ibType = dynamic_cast<const IntArray&>(_geomFields.ibType[cells]);
     const int nTrap = _nTrap;
     const int nFaces = faces.getCount();
     //drift only applies to conductance charge.
     for(int f=0; f<nFaces; f++)
         {
           const int c0 = faceCells(f,0);
           const int c1 = faceCells(f,1);
           const T_Scalar faceCFlux = convectingFlux[f];
           T_Scalar varFlux;
           if (faceCFlux > T_Scalar(0))
             {
               varFlux = faceCFlux*xCell[c0][nTrap];
               diag[c0](nTrap,nTrap) -= faceCFlux;
               assembler.getCoeff10(f)(nTrap,nTrap) += faceCFlux;
               //diag[c0][3*nTrap] -= faceCFlux;
               //assembler.getCoeff10(f)[3*nTrap] += faceCFlux;
               //assembler.getCoeff10(f) += faceCFlux;
             }
           else
             {
               varFlux = faceCFlux*xCell[c1][nTrap];
               diag[c1](nTrap,nTrap) += faceCFlux;
               assembler.getCoeff01(f)(nTrap,nTrap) -= faceCFlux;
               //diag[c1][3*nTrap] += faceCFlux;
               //assembler.getCoeff01(f)[3*nTrap] -= faceCFlux;
               //assembler.getCoeff01(f) -= faceCFlux;
             }
           rCell[c0][nTrap] -= varFlux;
           rCell[c1][nTrap] += varFlux;
         }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const Field& DriftDiscretization< X, Diag, OffDiag >::_convectingFluxField private
Definition at line 119 of file DriftDiscretization.h.
Referenced by DriftDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& DriftDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 117 of file DriftDiscretization.h.
template<class X , class Diag , class OffDiag > const int DriftDiscretization< X, Diag, OffDiag >::_nTrap private
Definition at line 120 of file DriftDiscretization.h.
Referenced by DriftDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const bool DriftDiscretization< X, Diag, OffDiag >::_useCentralDifference private
Definition at line 121 of file DriftDiscretization.h.
template<class X , class Diag , class OffDiag > const Field& DriftDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 118 of file DriftDiscretization.h.
Referenced by DriftDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
DriftDiscretization.h