Memosa-FVM: VectorArrayWriter< T, N > Class Template Reference
VectorArrayWriter< T, N > Class Template Reference
#include <ArrayWriter.h>
Public Types
typedef Vector< T, N > ElementType
typedef Array< ElementType > ArrayType
typedef NumTypeTraits< T >
::T_BuiltIn T_BuiltIn
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
Public Member Functions
VectorArrayWriter (const bool binary, const int vectorComponent, const int atypeComponent)
virtual void write (FILE *fp, const ArrayType &array, const int iBeg, int count, const Array< bool > *mask=0)
Public Member Functions inherited from ArrayWriter
ArrayWriter (const bool binary, const int vectorComponent, const int atypeComponent)
virtual ~ArrayWriter ()
template<class T >
void writeFloats (FILE *fp, const T *data, const int count, const int stride, const Array< bool > *mask=0)
Additional Inherited Members
Protected Attributes inherited from ArrayWriter
const bool _binary
const int _vectorComponent
const int _atypeComponent
Detailed Description
template<class T, int N>
class VectorArrayWriter< T, N >
Definition at line 92 of file ArrayWriter.h.
Member Typedef Documentation
template<class T, int N> typedef Array<ElementType> VectorArrayWriter< T, N >::ArrayType
Definition at line 96 of file ArrayWriter.h.
template<class T, int N> typedef Vector<T,N> VectorArrayWriter< T, N >::ElementType
Definition at line 95 of file ArrayWriter.h.
template<class T, int N> typedef NumTypeTraits<T>::T_BuiltIn VectorArrayWriter< T, N >::T_BuiltIn
Definition at line 97 of file ArrayWriter.h.
template<class T, int N> typedef NumTypeTraits<T>::T_Scalar VectorArrayWriter< T, N >::T_Scalar
Definition at line 98 of file ArrayWriter.h.
Constructor & Destructor Documentation
template<class T, int N> VectorArrayWriter< T, N >::VectorArrayWriter (const bool binary, const int vectorComponent, const int atypeComponent) inline
Definition at line 100 of file ArrayWriter.h.
                                               :
     ArrayWriter(binary,vectorComponent,atypeComponent)
   {}
Member Function Documentation
template<class T, int N> virtual void VectorArrayWriter< T, N >::write (FILE * fp, const ArrayType & array, const int iBeg, int count, const Array< bool > * mask = 0) inline virtual
Definition at line 105 of file ArrayWriter.h.
References ArrayWriter::_atypeComponent, ArrayWriter::_vectorComponent, Array< T >::getData(), Array< T >::getLength(), and ArrayWriter::writeFloats().
Referenced by FluentDataExporter< T >::writeVectorField().
   {
     const int length = array.getLength();
     if (count == -1)
       count = length;
     else if (count+iBeg > length)
       throw CException("invalid count ");
     ElementType *dataArray = (ElementType*)(array.getData());
     T_Scalar *dataScalar = (T_Scalar*)(dataArray+iBeg);
     int stride = 1;
     if (_vectorComponent == -2)
     {
         T_BuiltIn *data = (T_BuiltIn*)(dataScalar);
         // write all components in coupled order
 #ifdef USING_ATYPE_TANGENT
         if ((_atypeComponent == 0) || (_atypeComponent == 1))
         {
             data += _atypeComponent;
             stride = 2;
         }
         else
           throw CException("invalid component for Tangent");
 #endif
         if (mask)
           throw CException("masked write not implemented");
         writeFloats(fp,data,count*N,stride,0);
     }
     else
     {
         // write all components in sequential order
         int ndBeg=0;
         int ndEnd=N;
         if (_vectorComponent >= 0 && _vectorComponent <N)
         {
             // restrict to just one component
             ndBeg=_vectorComponent;
             ndEnd=ndBeg+1;
         }
         else if (_vectorComponent != -1)
         {
             throw CException("invalid vector component");
         }
         stride = N;
         for(int nd=ndBeg; nd<ndEnd; nd++)
         {
             T_BuiltIn *nddata = (T_BuiltIn*) (dataScalar+nd);
 #ifdef USING_ATYPE_TANGENT
             if ((_atypeComponent == 0) || (_atypeComponent == 1))
             {
                 nddata += _atypeComponent;
                 stride = N*2;
             }
             else
               throw CException("invalid component for Tangent");
 #endif
             writeFloats(fp,nddata,count,stride,mask);
         }
     }
   }
The documentation for this class was generated from the following file:
ArrayWriter.h