Memosa-FVM: CaptureDiscretization< X, Diag, OffDiag > Class Template Reference
CaptureDiscretization< X, Diag, OffDiag > Class Template Reference
#include <CaptureDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::OffDiagArray OffDiagArray
typedef Array< X > XArray
typedef Array< Vector
< T_Scalar, 3 > > VectorTNArray
Public Member Functions
CaptureDiscretization (const MeshList &meshes, const GeomFields &geomFields, const Field &varField, const Field &capturecrossField, const ElectricModelConstants< T_Scalar > &constants)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const Field & _capturecrossField
const ElectricModelConstants
< T_Scalar > & _constants
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class CaptureDiscretization< X, Diag, OffDiag >
Definition at line 41 of file CaptureDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> CaptureDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 47 of file CaptureDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray CaptureDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 48 of file CaptureDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::OffDiagArray CaptureDiscretization< X, Diag, OffDiag >::OffDiagArray
Definition at line 49 of file CaptureDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar CaptureDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 45 of file CaptureDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> CaptureDiscretization< X, Diag, OffDiag >::TArray
Definition at line 46 of file CaptureDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<Vector<T_Scalar, 3> > CaptureDiscretization< X, Diag, OffDiag >::VectorTNArray
Definition at line 51 of file CaptureDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> CaptureDiscretization< X, Diag, OffDiag >::XArray
Definition at line 50 of file CaptureDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > CaptureDiscretization< X, Diag, OffDiag >::CaptureDiscretization (const MeshList & meshes, const GeomFields & geomFields, const Field & varField, const Field & capturecrossField, const ElectricModelConstants< T_Scalar > & constants) inline
Definition at line 53 of file CaptureDiscretization.h.
                                                                           :
     Discretization(meshes),
     _geomFields(geomFields),
     _varField(varField),
     _capturecrossField(capturecrossField),
     _constants(constants)
       {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void CaptureDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 65 of file CaptureDiscretization.h.
References CaptureDiscretization< X, Diag, OffDiag >::_capturecrossField, CaptureDiscretization< X, Diag, OffDiag >::_constants, CaptureDiscretization< X, Diag, OffDiag >::_geomFields, CaptureDiscretization< X, Diag, OffDiag >::_varField, ElectricModelConstants< T >::electron_trapdensity, Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), MultiFieldMatrix::getMatrix(), StorageSite::getSelfCount(), K_SI, ME, PI, sqrt(), and GeomFields::volume.
   {
     const StorageSite& cells = mesh.getCells();
     const int nCells = cells.getSelfCount();
     const TArray& cellVolume = dynamic_cast<const TArray&>(_geomFields.volume[cells]);
     const VectorTNArray& free_electron_capture_cross = dynamic_cast<const VectorTNArray&> (_capturecrossField[cells]);
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     const XArray& xCell = dynamic_cast<const XArray&>(xField[cVarIndex]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     DiagArray& diag = matrix.getDiag();
     //OffDiagArray& offdiag = matrix.getOffDiag();
     const T_Scalar electron_effmass = _constants["electron_effmass"];
     const T_Scalar temperature = _constants["OP_temperature"];
     const int nTrap = _constants["nTrap"];
     vector<T_Scalar> electron_trapdensity = _constants.electron_trapdensity;
     const T_Scalar velocity = sqrt(8.0 * K_SI * temperature / (PI * ME * electron_effmass));
     for(int c=0; c<nCells; c++){
       for (int i=0; i<nTrap; i++){
         T_Scalar fluxCoeff = cellVolume[c] * velocity * free_electron_capture_cross[c][i];
         rCell[c][i] += fluxCoeff * xCell[c][nTrap] * (electron_trapdensity[i] - xCell[c][i]);
         diag[c](i,i) -= fluxCoeff * xCell[c][nTrap];
         //diag[c][i] -= fluxCoeff * xCell[c][nTrap];
         diag[c](i,nTrap) += fluxCoeff * (electron_trapdensity[i]-xCell[c][i]);
         //diag[c][i+nTrap] += fluxCoeff * (electron_trapdensity[i]-xCell[c][i]);
         rCell[c][nTrap] -= fluxCoeff * xCell[c][nTrap] * (electron_trapdensity[i] - xCell[c][i]);
         diag[c](nTrap,nTrap) -= fluxCoeff * (electron_trapdensity[i]-xCell[c][i]);
         //diag[c][3*nTrap] -= fluxCoeff * (electron_trapdensity[i]-xCell[c][i]);
         diag[c](nTrap,i) += fluxCoeff * xCell[c][nTrap];
         //diag[c][2*nTrap+i] += fluxCoeff * xCell[c][nTrap];
       }
     }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const Field& CaptureDiscretization< X, Diag, OffDiag >::_capturecrossField private
Definition at line 123 of file CaptureDiscretization.h.
Referenced by CaptureDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const ElectricModelConstants<T_Scalar>& CaptureDiscretization< X, Diag, OffDiag >::_constants private
Definition at line 124 of file CaptureDiscretization.h.
Referenced by CaptureDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& CaptureDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 121 of file CaptureDiscretization.h.
Referenced by CaptureDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& CaptureDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 122 of file CaptureDiscretization.h.
Referenced by CaptureDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
CaptureDiscretization.h