Memosa-FVM: SpikeMatrix< T_Diag, T_OffDiag, X > Class Template Reference
SpikeMatrix< T_Diag, T_OffDiag, X > Class Template Reference
#include <SpikeMatrix.h>
Public Types
typedef T_Diag Diag
typedef T_OffDiag OffDiag
typedef Array< Diag > DiagArray
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
Public Member Functions
SpikeMatrix (const CRConnectivity &conn, const Array< T_Diag > &diag, const Array< T_OffDiag > &off_diag, const SpikeStorage &spike_storage)
void solve (const XArray &f, XArray &x)
virtual ~SpikeMatrix ()
Public Member Functions inherited from Matrix
Matrix ()
virtual ~Matrix ()
DEFINE_TYPENAME ("Matrix")
virtual void multiply (IContainer &yB, const IContainer &xB) const
virtual void multiplyAndAdd (IContainer &yB, const IContainer &xB) const
virtual shared_ptr< ArrayBase > quadProduct (const IContainer &xB) const
virtual void forwardGS (IContainer &xB, IContainer &bB, IContainer &residual) const
virtual void reverseGS (IContainer &xB, IContainer &bB, IContainer &residual) const
virtual void Jacobi (IContainer &xnew, const IContainer &xold, const IContainer &b) const
virtual void iluSolve (IContainer &xB, const IContainer &bB, const IContainer &residual) const
virtual void spikeSolve (IContainer &xB, const IContainer &bB, const IContainer &residual, const SpikeStorage &spike_storage) const
virtual void solveBoundary (IContainer &xB, IContainer &bB, IContainer &residual) const
virtual void computeResidual (const IContainer &xB, const IContainer &bB, IContainer &residual) const
virtual int createCoarsening (IContainer &coarseIndex, const int groupSize, const double weighRatioThreshold)
virtual const CRConnectivity & getConnectivity () const
virtual void eliminateBoundaryEquations (IContainer &xB)
virtual void printRow (const int nr) const
virtual void * getDiagData () const
virtual void * getOffDiagData () const
virtual int getDiagDataSize () const
virtual int getOffDiagDataSize () const
virtual shared_ptr< Matrix > createMergeMatrix (const LinearSystemMerger &mergeLS)
virtual void setFlatMatrix (Matrix &fmg) const
virtual void transpose ()
virtual shared_ptr
< CRConnectivity > createCoarseConnectivity (const IContainer &coarseIndex, const CRConnectivity &coarseToFine, const StorageSite &coarseRowSite, const StorageSite &coarseColSite)
virtual shared_ptr< Matrix > createCoarseMatrix (const IContainer &coarseIndex, const CRConnectivity &coarseToFine, const CRConnectivity &coarseConnectivity)
virtual bool isInvertible ()
Private Member Functions
void initAssembly ()
void setMatrix ()
void setLMtrx ()
void lu ()
void setRMtrx ()
void setLSpikeMtrx ()
void setRSpikeMtrxFull ()
void setRSpikeMtrx ()
void exchangeSpikeMtrx ()
void setReducedMtrx ()
void denseMtrxLU (Array2D< Diag > &A, Array< int > &pp)
void luSolver (const Array< X > &f, Array< X > &x, bool negate_rhs=false)
void setgBgT ()
void exchange_gTgB ()
void setReducedRHS ()
void solveReducedSystem ()
void denseLUsolve (const Array2D< Diag > &A, const Array< int > &pp, Array< X > &rhs)
void exchange_reducedSol ()
void setRHS (const Array< X > &f, bool negate_rhs=false)
Private Attributes
const CRConnectivity & _conn
const Array< Diag > & _diag
const Array< OffDiag > & _offDiag
const SpikeStorage & _spikeStorage
const int _bandwidth
const int _ncells
int _procID
int _nprocs
Array2D< Diag > _A
Array2D< Diag > _LL
Array2D< Diag > _L
Array2D< Diag > _RR
Array2D< Diag > _R
Array2D< Diag > _LSpike
Array2D< Diag > _LSpikeT
Array2D< Diag > _RSpike
Array2D< Diag > _RSpikeB
Array2D< Diag > _JokerSpikeT
Array2D< Diag > _JokerSpikeB
Array2D< Diag > _reducedA1
Array2D< Diag > _reducedA2
Array< X > _reducedRHS1
Array< X > _reducedRHS2
Array< X > _JokerZ1
Array< X > _JokerZ2
Array< X > _RHS
Array< X > _g
Array< X > _gB
Array< X > _gT
Array< X > _JokergB
Array< X > _JokergT
Array2D< Diag > _yL
Array2D< Diag > _yR
Array< X > _y
Array< int > _pp1
Array< int > _pp2
Detailed Description
template<typename T_Diag, typename T_OffDiag, typename X>
class SpikeMatrix< T_Diag, T_OffDiag, X >
Definition at line 20 of file SpikeMatrix.h.
Member Typedef Documentation
template<typename T_Diag , typename T_OffDiag , typename X > typedef T_Diag SpikeMatrix< T_Diag, T_OffDiag, X >::Diag
Definition at line 26 of file SpikeMatrix.h.
template<typename T_Diag , typename T_OffDiag , typename X > typedef Array<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::DiagArray
Definition at line 28 of file SpikeMatrix.h.
template<typename T_Diag , typename T_OffDiag , typename X > typedef T_OffDiag SpikeMatrix< T_Diag, T_OffDiag, X >::OffDiag
Definition at line 27 of file SpikeMatrix.h.
template<typename T_Diag , typename T_OffDiag , typename X > typedef Array<OffDiag> SpikeMatrix< T_Diag, T_OffDiag, X >::OffDiagArray
Definition at line 29 of file SpikeMatrix.h.
template<typename T_Diag , typename T_OffDiag , typename X > typedef Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::XArray
Definition at line 30 of file SpikeMatrix.h.
Constructor & Destructor Documentation
template<typename T_Diag , typename T_OffDiag , typename X > SpikeMatrix< T_Diag, T_OffDiag, X >::SpikeMatrix (const CRConnectivity & conn, const Array< T_Diag > & diag, const Array< T_OffDiag > & off_diag, const SpikeStorage & spike_storage) inline
Definition at line 32 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly(), and logCtor.
                                                                                                                                              :
    Matrix(),
    _conn(conn),
    _diag(diag),
    _offDiag(off_diag),
    _spikeStorage(spike_storage),
    _bandwidth(spike_storage.getBandWidth()),
    _ncells(conn.getRowSite().getSelfCount()),
    _procID(0),
    _nprocs(1),
    _A(2*_bandwidth+1,_ncells),
    _LL(_ncells, _bandwidth),
    _L(_bandwidth,_bandwidth),
    _RR(_ncells, _bandwidth),
    _R(_bandwidth,_bandwidth),
    _LSpike (_ncells,_bandwidth),
    _LSpikeT(_bandwidth,_bandwidth),
    _RSpike (_ncells,_bandwidth),
    _RSpikeB(_bandwidth,_bandwidth),
    _JokerSpikeT(_bandwidth,_bandwidth),
    _JokerSpikeB(_bandwidth,_bandwidth),
    _reducedA1(_bandwidth,_bandwidth),
    _reducedA2(_bandwidth,_bandwidth),
    _reducedRHS1(_bandwidth),
    _reducedRHS2(_bandwidth),
    _JokerZ1(_bandwidth),
    _JokerZ2(_bandwidth),
    _RHS(_ncells),
    _g(_ncells),
    _gB(_bandwidth),
    _gT(_bandwidth),
    _JokergB(_bandwidth),
    _JokergT(_bandwidth),
    _yL(_ncells,_bandwidth),
    _yR(_bandwidth,_bandwidth),
    _y(_ncells),
    _pp1(_bandwidth),
    _pp2(_bandwidth)
   {
     initAssembly();
     logCtor();
   }
template<typename T_Diag , typename T_OffDiag , typename X > virtual SpikeMatrix< T_Diag, T_OffDiag, X >::~SpikeMatrix () inline virtual
Definition at line 96 of file SpikeMatrix.h.
References logDtor.
   {
     logDtor();
   }
Member Function Documentation
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::denseLUsolve (const Array2D< Diag > & A, const Array< int > & pp, Array< X > & rhs) inline private
Definition at line 533 of file SpikeMatrix.h.
References Array2D< T >::getRow().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem().
   {
           /*rhs.print(cout);*/
      const int n = A.getRow();
      //forward solve
      for ( int i = 0; i < n-1; i++ ){
         //swap components of y: y(i) <---> y(pp(i))
         if ( pp[i] > i ){
             X tmp = rhs[i];
             rhs[i] = rhs[pp[i]];
             rhs[pp[i]]=tmp;
         }
         for ( int j = i+1; j < n; j++ ){
            rhs[j] -= A(j,i) * rhs[i];
         }
      }
      //back solve (later =/ might be useful to define)
      if ( n >= 1 ) //prevent accessing arrays if n=0 size
         rhs[n-1] = rhs[n-1] /  A(n-1,n-1);
      for ( int i = n-2; i >=0; i-- ){
         for ( int j = i+1; j < n; j++ ){
            rhs[i] -= A(i,j) * rhs[j];
         }
         rhs[i] = rhs[i] /  A(i,i);
      }
      /*cout << endl;*/
      /*rhs.print(cout);*/
      /*cout << endl;*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::denseMtrxLU (Array2D< Diag > & A, Array< int > & pp) inline private
Definition at line 371 of file SpikeMatrix.h.
References Array< T >::getLength(), and Array2D< T >::getRow().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly().
 {
         /*A.print(cout);*/
     //fill permutation
     for( int i = 0; i < pp.getLength(); i++ )
        pp[i] = i;
     const int n = A.getRow();
     for ( int i = 0; i < n-1; i++ ){
        //doing paritial (column) pivoting
        Diag pivot = A(i,i);
        int jj = i;
        for ( int j = i+1; j < n; j++){
            if ( NumTypeTraits<Diag>::doubleMeasure( A(j,i) ) > NumTypeTraits<Diag>::doubleMeasure( pivot ) ){
                jj = j;
                pivot = A(j,i);
            }
        }
        //explicitly swap A(i,i:n-1) and A(jj,i:n-1)
        if ( jj > i ){
          for ( int j = i; j < n; j++){
             const Diag tmp = A(i,j);
             A(i,j) = A(jj,j);
             A(jj,j) = tmp;
          }
          pp[i] = jj;
        }
        pivot = A(i,i);
        for ( int j = i+1; j < n; j++ ){
            const Diag m = A(j,i) / pivot;
            A(j,i) = m;
            for ( int k = i+1; k < n; k++ ){
                A(j,k) -= m * A(i,k);
            }
        }
     }
     /*pp.print(cout);*/
     /*A.print(cout);*/
 }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB () inline private
Definition at line 481 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_gB, SpikeMatrix< T_Diag, T_OffDiag, X >::_gT, SpikeMatrix< T_Diag, T_OffDiag, X >::_JokergB, SpikeMatrix< T_Diag, T_OffDiag, X >::_JokergT, SpikeMatrix< T_Diag, T_OffDiag, X >::_nprocs, SpikeMatrix< T_Diag, T_OffDiag, X >::_procID, Array< T >::getData(), Array< T >::getDataSize(), and Array< T >::zero().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::solve().
   {
      _JokergB.zero();
      _JokergT.zero();
      #ifdef FVM_PARALLEL
      //send-recv single call since each process is involving send and recv
      MPI::Status status;
      if (_procID != _nprocs-1)
      MPI::COMM_WORLD.Sendrecv(_gB.getData()     , _gB.getDataSize()     , MPI::BYTE, _procID+1, 3199,
                               _JokergT.getData(), _JokergT.getDataSize(), MPI::BYTE, _procID+1, 4199, status );
      if ( _procID != 0 )
      MPI::COMM_WORLD.Sendrecv(_gT.getData()    , _gT.getDataSize()      , MPI::BYTE, _procID-1, 4199,
                               _JokergB.getData(), _JokergB.getDataSize(), MPI::BYTE, _procID-1, 3199, status );
      #endif
      /*_JokergB.print(cout);*/
      /*_JokergT.print(cout);*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol () inline private
Definition at line 566 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerZ1, SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerZ2, SpikeMatrix< T_Diag, T_OffDiag, X >::_nprocs, SpikeMatrix< T_Diag, T_OffDiag, X >::_procID, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedRHS1, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedRHS2, Array< T >::getData(), Array< T >::getDataSize(), and Array< T >::zero().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::solve().
   {
      _JokerZ1.zero();
      _JokerZ2.zero();
      #ifdef FVM_PARALLEL
      //send-recv single call since each process is involving send and recv
      MPI::Status status;
      if (_procID != _nprocs-1)
      MPI::COMM_WORLD.Sendrecv(_reducedRHS1.getData(), _reducedRHS1.getDataSize(), MPI::BYTE, _procID+1, 3199,
                               _JokerZ2.getData(), _JokerZ2.getDataSize(), MPI::BYTE, _procID+1, 4199, status );
      if ( _procID != 0 )
      MPI::COMM_WORLD.Sendrecv(_reducedRHS2.getData(), _reducedRHS2.getDataSize(), MPI::BYTE, _procID-1, 4199,
                               _JokerZ1.getData(), _JokerZ1.getDataSize(), MPI::BYTE, _procID-1, 3199, status );
      #endif
      /*cout << endl;*/
      /*_JokerZ1.print(cout);*/
      /*cout << endl;*/
      /*_JokerZ2.print(cout);*/
      /*cout << endl;*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::exchangeSpikeMtrx () inline private
Definition at line 322 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerSpikeB, SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerSpikeT, SpikeMatrix< T_Diag, T_OffDiag, X >::_LSpikeT, SpikeMatrix< T_Diag, T_OffDiag, X >::_nprocs, SpikeMatrix< T_Diag, T_OffDiag, X >::_procID, SpikeMatrix< T_Diag, T_OffDiag, X >::_RSpikeB, Array2D< T >::getData(), and Array2D< T >::getDataSize().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly().
  {
  #ifdef FVM_PARALLEL
    //send-recv single call since each process is involving send and recv
    MPI::Status status;
    if ( _procID != _nprocs-1)
    MPI::COMM_WORLD.Sendrecv(_RSpikeB.getData()    , _RSpikeB.getDataSize()    , MPI::BYTE, _procID+1, 1199,
                             _JokerSpikeT.getData(), _JokerSpikeT.getDataSize(), MPI::BYTE, _procID+1, 2199, status );
    if ( _procID != 0 )
    MPI::COMM_WORLD.Sendrecv(_LSpikeT.getData()    , _LSpikeT.getDataSize()    , MPI::BYTE, _procID-1, 2199,
                    _JokerSpikeB.getData(), _JokerSpikeB.getDataSize(), MPI::BYTE, _procID-1, 1199, status );
    /*_JokerSpikeB.print(cout);*/
    /*_JokerSpikeT.print(cout);*/
 #endif
  }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly () inline private virtual
Implements Matrix.
Definition at line 104 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_nprocs, SpikeMatrix< T_Diag, T_OffDiag, X >::_pp1, SpikeMatrix< T_Diag, T_OffDiag, X >::_pp2, SpikeMatrix< T_Diag, T_OffDiag, X >::_procID, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedA1, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedA2, SpikeMatrix< T_Diag, T_OffDiag, X >::denseMtrxLU(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchangeSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::lu(), SpikeMatrix< T_Diag, T_OffDiag, X >::setLMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setMatrix(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrx().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::SpikeMatrix().
   {
 #ifdef FVM_PARALLEL
      _procID = MPI::COMM_WORLD.Get_rank();
      _nprocs = MPI::COMM_WORLD.Get_size();
 #endif
      setMatrix();
      setLMtrx();
      setRMtrx();
      lu();
      setLSpikeMtrx();
      setRSpikeMtrx();
      exchangeSpikeMtrx();
      setReducedMtrx();
      //setRSpikeMtrxFull();
      if (_procID != _nprocs-1)
         denseMtrxLU (_reducedA1, _pp1);
      if ( _procID != 0 )
         denseMtrxLU (_reducedA2, _pp2);
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::lu () inline private
Definition at line 167 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_A, SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_ncells, and min().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly().
   {
      const int b = _bandwidth;
      for ( int i = 0; i < _ncells-1; i++ ){
         const Diag pivot = _A(b,i);
         for ( int j = i+1;  j <= min(_ncells-1,i+b); j++ ){
            const int j2 = b+j-i;
            const Diag m = _A(j2,i) / pivot; //Division(/) should be defined as _A * pivot^-1 for matrix ops.
            _A(j2,i) = m;
            for ( int k = i+1; k <= min(_ncells-1,i+b); k++ ){
               const int j2 = b+j-k;
               const int i2 = b+i-k;
               _A(j2,k) -= m * _A(i2,k);
            }
        }
     }
      /*_A.print(cout);*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::luSolver (const Array< X > & f, Array< X > & x, bool negate_rhs = false) inline private
Definition at line 416 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_A, SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_ncells, SpikeMatrix< T_Diag, T_OffDiag, X >::_y, max(), min(), and Array< T >::zero().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::solve().
   {
       x.zero();
      //zeros y
      _y.zero();
       const int b = _bandwidth;
      if ( negate_rhs ){
         _y[0] = -f[0];
         for ( int i = 1; i < _ncells; i++ ){
            X yi = -f[i];
            for ( int j = max(0,i-b); j <= i-1; j++ ){
               const int i2 = b+i-j;
               yi -=  _A(i2,j) * _y[j];
            }
            _y[i] = yi;
         }
     } else {
         _y[0] = f[0];
         for ( int i = 1; i < _ncells; i++ ){
            X yi = f[i];
            for ( int j = max(0,i-b); j <= i-1; j++ ){
               const int i2 = b+i-j;
               yi -=  _A(i2,j) * _y[j];
            }
            _y[i] = yi;
         }
     }
      /*_y.print(cout);*/
     //backward solve
     x.zero();
     x[_ncells-1] = _y[_ncells-1] / _A(b,_ncells-1);
     for ( int i = _ncells-2; i >= 0; i-- ){
         X soli = _y[i];
         for ( int j = i+1; j <= min(_ncells-1,i+b); j++ ){
             const int i2 = b+i-j;
             soli -=  _A(i2,j)*x[j];
         }
         x[i] = soli / _A(b,i);
     }
     /*f.print(cout);*/
     /*cout << endl;*/
     /*_y.print(cout);*/
     /*cout << endl;*/
     /*x.print(cout);*/
     /*cout << endl;*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::setgBgT () inline private
Definition at line 464 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_g, SpikeMatrix< T_Diag, T_OffDiag, X >::_gB, SpikeMatrix< T_Diag, T_OffDiag, X >::_gT, SpikeMatrix< T_Diag, T_OffDiag, X >::_ncells, and Array< T >::zero().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::solve().
   {
       //top part of g
       _gT.zero();
       for ( int i = 0; i < _bandwidth; i++ )
           _gT[i] = _g[i];
       //bottom part of g
       _gB.zero();
       int indx = 0;
       for ( int i = _ncells-_bandwidth; i < _ncells; i++ )
           _gB[indx++] = _g[i];
       /*_g.print(cout);*/
       /*_gT.print(cout);*/
       /*_gB.print(cout);*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::setLMtrx () inline private
Definition at line 148 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_L, SpikeMatrix< T_Diag, T_OffDiag, X >::_offDiag, SpikeMatrix< T_Diag, T_OffDiag, X >::_spikeStorage, SpikeStorage::getLSPKCountGhost(), SpikeStorage::getLSPKIndexI(), SpikeStorage::getLSPKIndexJ(), and SpikeStorage::getLSPKOffDiagPtr().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly().
   {
      const vector<int>& vecI = _spikeStorage.getLSPKIndexI();
      const vector<int>& vecJ = _spikeStorage.getLSPKIndexJ();
      const vector<int>& offDiagPtr = _spikeStorage.getLSPKOffDiagPtr();
      const vector<int>& countGhost = _spikeStorage.getLSPKCountGhost();
      int indx = 0;
      for ( int n = 0; n < _bandwidth; n++ ){
         int ncount = countGhost[n];
         for ( int c = 0; c < ncount; c++){
           int i = vecI[indx];
           int j = vecJ[indx];
           _L(i,j) = _offDiag[offDiagPtr[indx++]];
         }
      }
      /*_L.print(cout);*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx () inline private
Definition at line 206 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_A, SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_L, SpikeMatrix< T_Diag, T_OffDiag, X >::_LL, SpikeMatrix< T_Diag, T_OffDiag, X >::_LSpike, SpikeMatrix< T_Diag, T_OffDiag, X >::_LSpikeT, SpikeMatrix< T_Diag, T_OffDiag, X >::_ncells, SpikeMatrix< T_Diag, T_OffDiag, X >::_yL, max(), min(), Array2D< T >::partialCopyFrom(), Array2D< T >::partialCopyTo(), and Array2D< T >::zeros().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly().
   {
      //copy _L to LSpike
      _LL.partialCopyFrom(_L);
      /*_LL.print(cout);*/
      //zeros yL
      _yL.zeros();
      const int b = _bandwidth;
      for ( int n = 0; n < b; n++ ){
         _yL(0,n) = _LL(0,n);
         for ( int i = 1; i < _ncells; i++ ){
             Diag yi = _LL(i,n);
             for ( int j = max(0,i-b); j <= i-1; j++ ){
                 const int i2 = b+i-j;
                 yi -=  _A(i2,j) * _yL(j,n);
             }
             _yL(i,n) = yi;
         }
     }
      /*_yL.print(cout);*/
     //backward solve
     for ( int n = 0; n < b; n++ ){
        _LSpike(_ncells-1,n) = _yL(_ncells-1,n) / _A(b,_ncells-1);
        for ( int i = _ncells-2; i >= 0; i-- ){
           Diag soli = _yL(i,n);
           for ( int j = i+1; j <= min(_ncells-1,i+b); j++ ){
              const int i2 = b+i-j;
               soli -=  _A(i2,j)*_LSpike(j,n);
           }
           _LSpike(i,n) = soli / _A(b,i);
       }
    }
     /*_LSpike.print(cout);*/
    _LSpike.partialCopyTo(_LSpikeT);
    /*_LSpikeT.print(cout);*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::setMatrix () inline private
Definition at line 125 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_A, SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_conn, SpikeMatrix< T_Diag, T_OffDiag, X >::_diag, SpikeMatrix< T_Diag, T_OffDiag, X >::_ncells, SpikeMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRConnectivity::getCol(), and CRConnectivity::getRow().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly().
   {
      //forming A
      //const int  nr = 2 * _bandwidth + 1;
      const int  nc = _ncells;
      //diagonal filling
      for ( int i = 0; i < nc; i++ )
          _A(_bandwidth,i) = _diag[i];
      const Array<int>& row = _conn.getRow();
      const Array<int>& col = _conn.getCol();
      for ( int i = 0; i < nc; i++ ){
          for (int n = row[i]; n < row[i+1]; n++ ){
              int j =  col[n];
              //check if it is in bandwidth and inner coefficient
              if ( abs(j-i) <= _bandwidth && j < nc ){
                _A(_bandwidth-(j-i),j) = _offDiag[n];
              }
          }
      }
      /*_A.print(cout);*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx () inline private
Definition at line 341 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerSpikeB, SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerSpikeT, SpikeMatrix< T_Diag, T_OffDiag, X >::_LSpikeT, SpikeMatrix< T_Diag, T_OffDiag, X >::_nprocs, SpikeMatrix< T_Diag, T_OffDiag, X >::_procID, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedA1, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedA2, SpikeMatrix< T_Diag, T_OffDiag, X >::_RSpikeB, and Array2D< T >::setIdentity().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly().
 {
     //system above the processor line
     if ( _procID != _nprocs-1 ){
         _reducedA1.setIdentity();
         for ( int i = 0; i < _bandwidth; i++ ){
            for ( int j = 0; j < _bandwidth; j++ ){
               for ( int k = 0; k < _bandwidth; k++ ){
                  _reducedA1(i,j) -=  _RSpikeB(i,k) * _JokerSpikeT(k,j);
               }
            }
         }
    }
     /*_reducedA1.print(cout);*/
     //system above the processor line
     if ( _procID != 0 ){
         _reducedA2.setIdentity();
         for ( int i = 0; i < _bandwidth; i++ ){
            for ( int j = 0; j < _bandwidth; j++ ){
               for ( int k = 0; k < _bandwidth; k++ ){
                  _reducedA2(i,j) -=  _LSpikeT(i,k) * _JokerSpikeB(k,j);
               }
            }
         }
    }
     /*_reducedA2.print(cout);*/
 }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS () inline private
Definition at line 501 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_gB, SpikeMatrix< T_Diag, T_OffDiag, X >::_gT, SpikeMatrix< T_Diag, T_OffDiag, X >::_JokergB, SpikeMatrix< T_Diag, T_OffDiag, X >::_JokergT, SpikeMatrix< T_Diag, T_OffDiag, X >::_LSpikeT, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedRHS1, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedRHS2, SpikeMatrix< T_Diag, T_OffDiag, X >::_RSpikeB, and Array< T >::zero().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::solve().
   {
       //rhs1
       _reducedRHS1.zero();
       for ( int i = 0; i < _bandwidth; i++ ){
           X dot_product = NumTypeTraits<X>::getZero();
           for ( int j = 0; j < _bandwidth; j++ ){
                dot_product +=   _RSpikeB(i,j) * _JokergT[j];
           }
           _reducedRHS1[i] = _gB[i] - dot_product;
       }
       /*_reducedRHS1.print(cout);*/
       //rhs2
       _reducedRHS2.zero();
       for ( int i = 0; i < _bandwidth; i++ ){
           X dot_product = NumTypeTraits<X>::getZero();
           for ( int j = 0; j < _bandwidth; j++ ){
                dot_product += _LSpikeT(i,j) * _JokergB[j];
           }
           _reducedRHS2[i] = _gT[i] - dot_product;
       }
       /*_reducedRHS2.print(cout);*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::setRHS (const Array< X > & f, bool negate_rhs = false) inline private
Definition at line 588 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerZ1, SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerZ2, SpikeMatrix< T_Diag, T_OffDiag, X >::_L, SpikeMatrix< T_Diag, T_OffDiag, X >::_ncells, SpikeMatrix< T_Diag, T_OffDiag, X >::_R, SpikeMatrix< T_Diag, T_OffDiag, X >::_RHS, and Array< T >::zero().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::solve().
   {
       _RHS.zero();
       if ( negate_rhs == true ){
          for ( int i = 0; i < _ncells; i++ )
              _RHS[i] = -f[i];
       } else {
          for ( int i = 0; i < _ncells; i++ )
              _RHS[i] = f[i];
       }
       //top part
       for ( int i = 0; i < _bandwidth; i++ ){
          X dot_product = NumTypeTraits<X>::getZero();
          for ( int j = 0; j < _bandwidth; j++ ){
                  dot_product +=   _L(i,j) * _JokerZ1[j];
          }
          _RHS[i] -=  dot_product;
       }
       //bottom part
       for ( int i = 0; i < _bandwidth; i++ ){
          X dot_product = NumTypeTraits<X>::getZero();
          const int indx = _ncells-_bandwidth+i;
          for ( int j = 0; j < _bandwidth; j++ ){
                  dot_product +=  _R(i,j) * _JokerZ2[j];
          }
          _RHS[indx] -=  dot_product;
       }
       /*_RHS.print(cout);*/
       /*cout << endl;*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx () inline private
Definition at line 187 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_ncells, SpikeMatrix< T_Diag, T_OffDiag, X >::_offDiag, SpikeMatrix< T_Diag, T_OffDiag, X >::_R, SpikeMatrix< T_Diag, T_OffDiag, X >::_spikeStorage, SpikeStorage::getRSPKCountGhost(), SpikeStorage::getRSPKIndexI(), SpikeStorage::getRSPKIndexJ(), and SpikeStorage::getRSPKOffDiagPtr().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly().
   {
      const vector<int>& vecI = _spikeStorage.getRSPKIndexI();
      const vector<int>& vecJ = _spikeStorage.getRSPKIndexJ();
      const vector<int>& offDiagPtr = _spikeStorage.getRSPKOffDiagPtr();
      const vector<int>& countGhost = _spikeStorage.getRSPKCountGhost();
      int indx = 0;
      for ( int n = _ncells-_bandwidth; n < _ncells; n++ ){
         int ncount = countGhost[n];
         for ( int c = 0; c < ncount; c++){
           int i = _bandwidth - _ncells +  vecI[indx];
           int j = vecJ[indx];
           _R(i,j) = _offDiag[offDiagPtr[indx++]];
         }
      }
      /*_R.print(cout);*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrx () inline private
Definition at line 284 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_A, SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_ncells, SpikeMatrix< T_Diag, T_OffDiag, X >::_R, SpikeMatrix< T_Diag, T_OffDiag, X >::_RSpikeB, SpikeMatrix< T_Diag, T_OffDiag, X >::_yR, and Array2D< T >::zeros().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly().
   {
      //forward solve
      //zeros yR
      _yR.zeros();
      const int b = _bandwidth;
      for ( int n = 0; n < b; n++ ){
         _yR(0,n) = _R(0,n);
         for ( int i = 1; i < b; i++ ){
             const int ii =  _ncells-b+i;
             Diag yi = _R(i,n);
             for ( int j = 0; j < i; j++ ){
                 const int jj = _ncells-b + j;
                 const int i2 = b+ii-jj;
                 yi -=  _A(i2,jj) * _yR(j,n);
             }
             _yR(i,n) = yi;
         }
     }
      /*_yR.print(cout);*/
     //backward solve
     for ( int n = 0; n < b; n++ ){
        _RSpikeB(b-1,n) = _yR(b-1,n) / _A(b,_ncells-1);
        for ( int i = b-2; i >= 0; i-- ){
           Diag soli = _yR(i,n);
           const int ii = _ncells-b+i;
           for ( int j = b-1; j > i; j-- ){
              const int jj = _ncells-b+j;
              const int i2 = b+ii-jj;
               soli -=  _A(i2,jj)*_RSpikeB(j,n);
           }
           _RSpikeB(i,n) = soli / _A(b,ii);
       }
    }
     /*_RSpikeB.print(cout);*/
  }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull () inline private
Definition at line 244 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_A, SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth, SpikeMatrix< T_Diag, T_OffDiag, X >::_ncells, SpikeMatrix< T_Diag, T_OffDiag, X >::_R, SpikeMatrix< T_Diag, T_OffDiag, X >::_RR, SpikeMatrix< T_Diag, T_OffDiag, X >::_RSpike, SpikeMatrix< T_Diag, T_OffDiag, X >::_RSpikeB, SpikeMatrix< T_Diag, T_OffDiag, X >::_yR, max(), min(), Array2D< T >::partialCopyFrom(), Array2D< T >::partialCopyTo(), and Array2D< T >::zeros().
   {
      //copy _R to RSpike
      _RR.partialCopyFrom(_R);
      /*_RR.print(cout);*/
      //zeros yR
      _yR.zeros();
      const int b = _bandwidth;
      for ( int n = 0; n < b; n++ ){
         _yR(0,n) = _RR(0,n);
         for ( int i = 1; i < _ncells; i++ ){
             Diag yi = _RR(i,n);
             for ( int j = max(0,i-b); j <= i-1; j++ ){
                 const int i2 = b+i-j;
                 yi -=  _A(i2,j) * _yR(j,n);
             }
             _yR(i,n) = yi;
         }
     }
      /*_yR.print(cout);*/
     //backward solve
     for ( int n = 0; n < b; n++ ){
        _RSpike(_ncells-1,n) = _yR(_ncells-1,n) / _A(b,_ncells-1);
        for ( int i = _ncells-2; i >= 0; i-- ){
           Diag soli = _yR(i,n);
           for ( int j = i+1; j <= min(_ncells-1,i+b); j++ ){
              const int i2 = b+i-j;
               soli -=  _A(i2,j)*_RSpike(j,n);
           }
           _RSpike(i,n) = soli / _A(b,i);
       }
    }
     /*_RSpike.print(cout);*/
    _RSpike.partialCopyTo(_RSpikeB);
    /*_RSpikeB.print(cout);*/
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::solve (const XArray & f, XArray & x) inline
Definition at line 75 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_g, SpikeMatrix< T_Diag, T_OffDiag, X >::_RHS, SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol(), SpikeMatrix< T_Diag, T_OffDiag, X >::luSolver(), SpikeMatrix< T_Diag, T_OffDiag, X >::setgBgT(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRHS(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem().
   {
       //negate rhs (f) for x
       luSolver(f, _g, true);
       //set gB, gT from
       setgBgT();
       //communicate gB and gT to neighbourhood processors
       exchange_gTgB();
       //setting rhs for reduced system
       setReducedRHS();
       //solve reduced system
       solveReducedSystem();
       //exchange reduced system solutions
       exchange_reducedSol();
       //setting final system rhs
       setRHS(f, true);
       //get solution
       luSolver( _RHS, x,  false);
   }
template<typename T_Diag , typename T_OffDiag , typename X > void SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem () inline private
Definition at line 525 of file SpikeMatrix.h.
References SpikeMatrix< T_Diag, T_OffDiag, X >::_nprocs, SpikeMatrix< T_Diag, T_OffDiag, X >::_pp1, SpikeMatrix< T_Diag, T_OffDiag, X >::_pp2, SpikeMatrix< T_Diag, T_OffDiag, X >::_procID, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedA1, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedA2, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedRHS1, SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedRHS2, and SpikeMatrix< T_Diag, T_OffDiag, X >::denseLUsolve().
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::solve().
   {
      if (_procID != _nprocs-1)
         denseLUsolve(_reducedA1, _pp1, _reducedRHS1); //solution z1 is stored in reducedRHS1
      if ( _procID != 0 )
         denseLUsolve(_reducedA2, _pp2, _reducedRHS2);//solution z2 is stored in reducedRHS2
   }
Member Data Documentation
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_A private
Definition at line 629 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::lu(), SpikeMatrix< T_Diag, T_OffDiag, X >::luSolver(), SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setMatrix(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
template<typename T_Diag , typename T_OffDiag , typename X > const int SpikeMatrix< T_Diag, T_OffDiag, X >::_bandwidth private
Definition at line 625 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::lu(), SpikeMatrix< T_Diag, T_OffDiag, X >::luSolver(), SpikeMatrix< T_Diag, T_OffDiag, X >::setgBgT(), SpikeMatrix< T_Diag, T_OffDiag, X >::setLMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setMatrix(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRHS(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
template<typename T_Diag , typename T_OffDiag , typename X > const CRConnectivity& SpikeMatrix< T_Diag, T_OffDiag, X >::_conn private
Definition at line 621 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setMatrix().
template<typename T_Diag , typename T_OffDiag , typename X > const Array<Diag>& SpikeMatrix< T_Diag, T_OffDiag, X >::_diag private
Definition at line 622 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setMatrix().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_g private
Definition at line 647 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setgBgT(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solve().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_gB private
Definition at line 648 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB(), SpikeMatrix< T_Diag, T_OffDiag, X >::setgBgT(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_gT private
Definition at line 649 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB(), SpikeMatrix< T_Diag, T_OffDiag, X >::setgBgT(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_JokergB private
Definition at line 650 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_JokergT private
Definition at line 651 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerSpikeB private
Definition at line 639 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchangeSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerSpikeT private
Definition at line 638 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchangeSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerZ1 private
Definition at line 644 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRHS().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_JokerZ2 private
Definition at line 645 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRHS().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_L private
Definition at line 631 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRHS().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_LL private
Definition at line 630 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_LSpike private
Definition at line 634 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_LSpikeT private
Definition at line 635 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchangeSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS().
template<typename T_Diag , typename T_OffDiag , typename X > const int SpikeMatrix< T_Diag, T_OffDiag, X >::_ncells private
Definition at line 626 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::lu(), SpikeMatrix< T_Diag, T_OffDiag, X >::luSolver(), SpikeMatrix< T_Diag, T_OffDiag, X >::setgBgT(), SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setMatrix(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRHS(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
template<typename T_Diag , typename T_OffDiag , typename X > int SpikeMatrix< T_Diag, T_OffDiag, X >::_nprocs private
Definition at line 628 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchangeSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem().
template<typename T_Diag , typename T_OffDiag , typename X > const Array<OffDiag>& SpikeMatrix< T_Diag, T_OffDiag, X >::_offDiag private
Definition at line 623 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setMatrix(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx().
template<typename T_Diag , typename T_OffDiag , typename X > Array<int> SpikeMatrix< T_Diag, T_OffDiag, X >::_pp1 private
Definition at line 656 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem().
template<typename T_Diag , typename T_OffDiag , typename X > Array<int> SpikeMatrix< T_Diag, T_OffDiag, X >::_pp2 private
Definition at line 657 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem().
template<typename T_Diag , typename T_OffDiag , typename X > int SpikeMatrix< T_Diag, T_OffDiag, X >::_procID private
Definition at line 627 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchangeSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_R private
Definition at line 633 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setRHS(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedA1 private
Definition at line 640 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedA2 private
Definition at line 641 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::initAssembly(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedRHS1 private
Definition at line 642 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_reducedRHS2 private
Definition at line 643 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solveReducedSystem().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_RHS private
Definition at line 646 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setRHS(), and SpikeMatrix< T_Diag, T_OffDiag, X >::solve().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_RR private
Definition at line 632 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_RSpike private
Definition at line 636 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_RSpikeB private
Definition at line 637 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchangeSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
template<typename T_Diag , typename T_OffDiag , typename X > const SpikeStorage& SpikeMatrix< T_Diag, T_OffDiag, X >::_spikeStorage private
Definition at line 624 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx().
template<typename T_Diag , typename T_OffDiag , typename X > Array<X> SpikeMatrix< T_Diag, T_OffDiag, X >::_y private
Definition at line 655 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::luSolver().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_yL private
Definition at line 652 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx().
template<typename T_Diag , typename T_OffDiag , typename X > Array2D<Diag> SpikeMatrix< T_Diag, T_OffDiag, X >::_yR private
Definition at line 653 of file SpikeMatrix.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrx(), and SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull().
The documentation for this class was generated from the following file:
SpikeMatrix.h