Memosa-FVM: Array< T > Class Template Reference
Array< T > Class Template Reference
#include <Array.h>
Public Types
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef NumTypeTraits< T >
::T_BuiltIn T_BuiltIn
Public Member Functions
Array (const int length)
Array (Array &parent, const int offset, const int length)
virtual ~Array ()
void resize (const int newLength)
DEFINE_TYPENAME ("Array<"+NumTypeTraits< T >::getTypeName()+">")
virtual int getDimension () const
int getLength () const
virtual PrimType getPrimType () const
virtual void getShape (int *shp) const
T & operator[] (int n)
const T & operator[] (int n) const
void operator= (const T &x)
void operator= (const Array &o)
virtual ArrayBase & operator+= (const ArrayBase &obase)
virtual ArrayBase & operator-= (const ArrayBase &obase)
virtual ArrayBase & operator/= (const ArrayBase &obase)
virtual void setMax (const ArrayBase &obase)
virtual ArrayBase & safeDivide (const ArrayBase &obase)
virtual ArrayBase & normalize (const ArrayBase &obase)
virtual ArrayBase & operator*= (const ArrayBase &obase)
virtual bool operator< (const double tolerance) const
virtual void print (ostream &os) const
virtual ArrayBase & saxpy (const ArrayBase &alphabase, const ArrayBase &xbase)
virtual ArrayBase & msaxpy (const ArrayBase &alphabase, const ArrayBase &xbase)
virtual void * getData () const
virtual int getDataSize () const
virtual void zero ()
void disownData () const
virtual shared_ptr< ArrayBase > dotWith (const ArrayBase &abase, const int lengthToUse) const
virtual shared_ptr< ArrayBase > getOneNorm (const int lengthToUse) const
virtual shared_ptr< ArrayBase > reduceSum () const
virtual void setSum (const ArrayBase &sumBase)
virtual void scatter (ArrayBase &other_, const ArrayBase &indices_, const int offset=0) const
virtual void gather (const ArrayBase &other_, const ArrayBase &indices_, const int offset=0)
virtual shared_ptr< Array > getSubset (const Array< int > &indices)
virtual void setSubsetFromSubset (const ArrayBase &other_, const ArrayBase &fromIndices_, const ArrayBase &toIndices_)
virtual void copyFrom (const IContainer &oc)
virtual void copyPartial (const IContainer &oc, const int iBeg, const int iEnd)
virtual void zeroPartial (const int iBeg, const int iEnd)
virtual void limit (const double min, const double max)
virtual shared_ptr< ArrayBase > operator- () const
virtual void inject (IContainer &coarseI, const IContainer &coarseIndexI, const int length) const
virtual void correct (const IContainer &coarseI, const IContainer &coarseIndexI, const IContainer *scaleI, const int length)
virtual shared_ptr< IContainer > newClone () const
virtual shared_ptr< ArrayBase > newSizedClone (const int size) const
virtual shared_ptr< IContainer > newCopy () const
virtual shared_ptr< ArrayBase > createOffsetArray (const int offset, const int length)
Public Member Functions inherited from ArrayBase
ArrayBase ()
virtual ~ArrayBase ()
Public Member Functions inherited from IContainer
IContainer ()
virtual ~IContainer ()
IContainer & operator= (const IContainer &oc)
Private Member Functions
Array (const Array &)
Private Attributes
int _length
T * _data
bool _ownData
Detailed Description
template<class T>
class Array< T >
Definition at line 14 of file Array.h.
Member Typedef Documentation
template<class T> typedef NumTypeTraits<T>::T_BuiltIn Array< T >::T_BuiltIn
Definition at line 20 of file Array.h.
template<class T> typedef NumTypeTraits<T>::T_Scalar Array< T >::T_Scalar
Definition at line 19 of file Array.h.
Constructor & Destructor Documentation
template<class T> Array< T >::Array (const int length) inline explicit
Definition at line 22 of file Array.h.
Referenced by Array< Vector< int, 2 > >::createOffsetArray(), Array< Vector< int, 2 > >::dotWith(), Array< Vector< int, 2 > >::getOneNorm(), Array< Vector< int, 2 > >::getSubset(), Array< Vector< int, 2 > >::newClone(), Array< Vector< int, 2 > >::newCopy(), Array< Vector< int, 2 > >::newSizedClone(), and Array< Vector< int, 2 > >::operator-().
                                    :
     ArrayBase(),
     _length(length),
     _data(new T[length]),
     _ownData(true)
   {
     logCtorVerbose("of   length %d" , _length);
   }
template<class T> Array< T >::Array (Array< T > & parent, const int offset, const int length) inline
Definition at line 33 of file Array.h.
                                                            :
     ArrayBase(),
     _length(length),
     _data(parent._data+offset),
     _ownData(false)
   {
     logCtorVerbose("with offset %d and length %d" , offset, _length);
   }
template<class T> virtual Array< T >::~Array () inline virtual
Definition at line 43 of file Array.h.
   {
     if (_ownData)
     {
         logDtorVerbose("of length %d with own data" , _length);
         delete [] _data;
     }
     else
     {
         logDtorVerbose("of length %d with offset data" , _length);
     }
   }
template<class T> Array< T >::Array (const Array< T > &) private
Member Function Documentation
template<class T> virtual void Array< T >::copyFrom (const IContainer & oc) inline virtual
Implements ArrayBase.
Definition at line 383 of file Array.h.
Referenced by DensityOfStates< T >::addMode(), DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::copyDOS(), DensityOfStates< T >::mergeBins(), and DensityOfStates< T >::refineBins().
   {
     const Array& other = dynamic_cast<const Array&>(oc);
     operator=(other);
   }
template<class T> virtual void Array< T >::copyPartial (const IContainer & oc, const int iBeg, const int iEnd) inline virtual
Implements ArrayBase.
Definition at line 390 of file Array.h.
   {
     const Array& other = dynamic_cast<const Array&>(oc);
     for(int i=iBeg;i<iEnd;i++)
       _data[i] = other._data[i];
   }
template<class T> virtual void Array< T >::correct (const IContainer & coarseI, const IContainer & coarseIndexI, const IContainer * scaleI, const int length) inline virtual
Implements ArrayBase.
Definition at line 439 of file Array.h.
   {
     const Array& coarse = dynamic_cast<const Array&>(coarseI);
     const Array<int>& coarseIndex = dynamic_cast<const Array<int>& >(coarseIndexI);
     if (scaleI)
     {
         const Array& scaleArray =
           dynamic_cast<const Array&>(*scaleI);
         if (scaleArray.getLength() == 1)
         {
             const T& scale = scaleArray[0];
             //cout << "correction scale" << scale << endl;
             for(int i=0; i<length; i++)
               _data[i] += coarse[coarseIndex[i]]*scale;
         }
         else
           throw CException("invalid scale array");
     }
     else
     {
         for(int i=0; i<length; i++)
           if (coarseIndex[i]>=0)
             _data[i] += coarse[coarseIndex[i]];
     }
   }
template<class T> virtual shared_ptr<ArrayBase> Array< T >::createOffsetArray (const int offset, const int length) inline virtual
Implements ArrayBase.
Definition at line 491 of file Array.h.
   {
     return shared_ptr<Array>(new Array(*this,offset,length));
   }
template<class T> Array< T >::DEFINE_TYPENAME ("Array<"+NumTypeTraits< T >::getTypeName()+">")
template<class T> void Array< T >::disownData () const inline
Definition at line 286 of file Array.h.
 {_ownData = false;}
template<class T> virtual shared_ptr<ArrayBase> Array< T >::dotWith (const ArrayBase & abase, const int lengthToUse) const inline virtual
Implements ArrayBase.
Definition at line 291 of file Array.h.
   {
     const Array& a = dynamic_cast<const Array&>(abase);
     T sum(NumTypeTraits<T>::getZero());
     for(int i=0; i<lengthToUse; i++)
       NumTypeTraits<T>::accumulateDotProduct(sum,_data[i],a._data[i]);
     shared_ptr<Array> nPtr(new Array(1));
     (*nPtr)[0] = sum;
     return nPtr;
   }
template<class T> virtual void Array< T >::gather (const ArrayBase & other_, const ArrayBase & indices_, const int offset = 0) inline virtual
Implements ArrayBase.
Definition at line 347 of file Array.h.
   {
     const Array<int>& indices = dynamic_cast<const Array<int>& >(indices_);
     const Array& other = dynamic_cast<const Array& >(other_);
     for(int ii=0; ii<indices.getLength(); ii++)
       _data[indices[ii]] = other[offset+ii];
   }
template<class T> virtual void* Array< T >::getData () const inline virtual
Implements ArrayBase.
Definition at line 275 of file Array.h.
Referenced by KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), KineticModel< T >::computeSolidFacePressure(), COMETModel< T >::computeSolidFacePressure(), NcDataWriter::connectivities(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol(), COMETESBGKDiscretizer< T >::findResid(), COMETESBGKDiscretizer< T >::findResidFine(), CRMatrix< T_Diag, T_OffDiag, X >::getDiagData(), CRMatrix< T_Diag, T_OffDiag, X >::getOffDiagData(), MeshPartitioner::level1_scatter_gather_cells(), FluentReader::readVectorData(), DirectSolver::solve(), ScalarArrayWriter< T >::write(), and VectorArrayWriter< T, N >::write().
 {return  _data;}
template<class T> virtual int Array< T >::getDataSize () const inline virtual
Implements ArrayBase.
Definition at line 276 of file Array.h.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol(), CRMatrix< T_Diag, T_OffDiag, X >::getDiagDataSize(), CRMatrix< T_Diag, T_OffDiag, X >::getOffDiagDataSize(), and Array< Vector< int, 2 > >::zero().
   {
     return  _length*NumTypeTraits<T>::getDataSize();
   }
template<class T> virtual int Array< T >::getDimension () const inline virtual
Implements ArrayBase.
Definition at line 82 of file Array.h.
   {
     return NumTypeTraits<T>::getDimension() + 1;
   };
template<class T> int Array< T >::getLength () const inline virtual
Implements ArrayBase.
Definition at line 87 of file Array.h.
Referenced by Mesh::addCRConn(), COMETInterface< T >::addFAS(), ScatteringKernel< T >::addFreqs(), DensityOfStates< T >::addMode(), COMETDiscretizer< T >::ArrayAbs(), COMETESBGKDiscretizer< T >::ArrayAbs(), COMETModel< T >::binwiseHeatFluxIntegral(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), Kspace< T >::calcBandTemp(), COMETModel< T >::calcBandTemps(), DensityOfStates< T >::calcBinFlux(), COMETModel< T >::calcModeFlux(), checkIBFaces(), Mesh::COMETfindCommonFaces(), CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), NcDataWriter::connectivities(), DensityOfStates< T >::copyDOS(), Array< Vector< int, 2 > >::correct(), ScatteringKernel< T >::correctDetailedBalance(), COMETModel< T >::correctSingleNeighbor(), Mesh::countCRConn(), MeshAssembler::countInterfaceNodes(), MeshPartitioner::CRConnectivityPrint(), Mesh::CRConnectivityPrint(), IBManager::CRConnectivityPrintFile(), MeshPartitioner::CRConnectivityPrintFile(), Mesh::CRConnectivityPrintFile(), FluentReader::createMesh(), Mesh::createRowColSiteCRConn(), Mesh::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), Mesh::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), GradientMatrix< T_Scalar >::createScatterGatherValuesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), Kspace< T >::createSyncGather(), Field::createSyncGatherArrays(), MultiField::createSyncGatherArrays(), Field::createSyncGatherArraysLevel1(), MultiField::createSyncGatherArraysLevel1(), Field::createSyncGatherArraysVectorFields(), Field::createSyncGatherArraysVectorFieldsLevel1(), MeshPartitioner::DEBUG_faceCells_faceNodes(), MeshDismantler::debug_gather_mappers(), MeshPartitioner::DEBUG_level1_scatter_gather_cells(), MeshPartitioner::DEBUG_local_global(), MeshAssembler::debug_localNodeToGlobal(), MeshAssembler::debug_localToGlobal_mappers(), PartMesh::debug_print(), MeshDismantler::debug_scatter_mappers(), MeshAssembler::debug_sync_localToGlobal_mappers(), SpikeMatrix< T_Diag, T_OffDiag, X >::denseMtrxLU(), COMETInterface< T >::Distribute(), COMETInterface< T >::DistributeResid(), PartMesh::dumpTecplot(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), DensityOfStates< T >::findBin(), Grid::findNeighbors(), Kspace< T >::findTransmission(), COMETModel< T >::FinishCoarseMesh(), Array< Vector< int, 2 > >::gather(), Mesh::getCellCells2(), FluentReader::getCommonNodeMap(), MeshDismantler::getGatherArrays(), FluentReader::getGhostCellMap(), GradientMatrix< T_Scalar >::getGradient(), MeshAssembler::getInnerNodesCount(), CRConnectivity::getLocalizedSubset(), CRConnectivity::getLocalizedSubsetOfFaceCells(), MeshDismantler::getScatterArrays(), FlowModel< T >::Impl::getStressTensor(), CRConnectivity::getSubset(), Array< Vector< int, 2 > >::getSubset(), ScatteringKernel< T >::getTypeIIsource(), ScatteringKernel< T >::getTypeIsource(), KSearchTree::KSearchTree(), CRConnectivity::localize(), COMETInterface< T >::makeDMMcoeffs(), DensityOfStates< T >::makeDMMreflection(), DensityOfStates< T >::makeDMMtransmission(), COMETInterface< T >::makeEquilibriumArray(), COMETInterface< T >::makeValueArray(), DensityOfStates< T >::mergeBins(), Mesh::Mesh(), PartMesh::mesh_tecplot(), MeshPartitioner::mesh_tecplot(), PartMesh::mesh_xdmfplot(), MeshPartitioner::mesh_xdmfplot(), ArrowHeadMatrix< X, K >::multiply(), SquareMatrix< T, N >::multiply(), KSConnectivity< T >::multiplyOther(), KSConnectivity< T >::multiplySelf(), MeshPartitioner::preserve_cell_order(), DensityOfStates< T >::refineBins(), CRConnectivity::reorder(), DensityOfStates< T >::saveNormDOS(), COMETDiscretizer< T >::scaledResid(), Array< Vector< int, 2 > >::scatter(), MeshAssembler::setCellsSite(), DensityOfStates< T >::setDensity(), SpikeStorage::setGlobalIndices(), DensityOfStates< T >::setMids(), FVMParticles::setParticles(), Array< Vector< int, 2 > >::setSubsetFromSubset(), Array< Vector< int, 2 > >::setSum(), COMETModel< T >::smooth(), DensityOfStates< T >::sumOutgoing(), Kspace< T >::syncGather(), Field::syncGatherVectorFields(), Field::syncGatherVectorFieldsLevel1(), MultiFieldMatrix::syncGhostCoarsening(), COMETModel< T >::syncGhostCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), Field::syncScatter(), MultiField::syncScatter(), Kspace< T >::syncScatter(), Field::syncScatterLevel1(), MultiField::syncScatterLevel1(), Field::syncScatterVectorFields(), Field::syncScatterVectorFieldsLevel1(), GradientMatrix< T_Scalar >::syncValues(), TDMA(), StructureDeformationModel< T >::updateBoundaryMesh(), ScatteringKernel< T >::updateSource(), ScatteringKernel< T >::updateSource2(), ScatteringKernel< T >::updateSourceTerm(), ScatteringKernel< T >::updateSourceTermTest(), Kspace< T >::weightArray(), ScalarArrayWriter< T >::write(), and VectorArrayWriter< T, N >::write().
 {return _length;}
template<class T> virtual shared_ptr<ArrayBase> Array< T >::getOneNorm (const int lengthToUse) const inline virtual
Implements ArrayBase.
Definition at line 303 of file Array.h.
   {
     T sum(NumTypeTraits<T>::getZero());
     for(int i=0; i<lengthToUse; i++)
       NumTypeTraits<T>::accumulateOneNorm(sum,_data[i]);
     shared_ptr<Array> nPtr(new Array(1));
     (*nPtr)[0] = sum;
     return nPtr;
   }
template<class T> virtual PrimType Array< T >::getPrimType () const inline virtual
Implements ArrayBase.
Definition at line 89 of file Array.h.
   {
     return NumTypeTraits<T>::getPrimType();
   }
template<class T> virtual void Array< T >::getShape (int * shp) const inline virtual
Implements ArrayBase.
Definition at line 94 of file Array.h.
   {
     *shp = _length;
     NumTypeTraits<T>::getShape(shp+1);
   }
template<class T> virtual shared_ptr<Array> Array< T >::getSubset (const Array< int > & indices) inline virtual
Definition at line 356 of file Array.h.
   {
     shared_ptr<Array> subPtr(new Array(indices.getLength()));
     Array& sub = *subPtr;
     for(int ii=0; ii<indices.getLength(); ii++)
     {
         sub[ii] = _data[indices[ii]];
     }
     return subPtr;
   }
template<class T> virtual void Array< T >::inject (IContainer & coarseI, const IContainer & coarseIndexI, const int length) const inline virtual
Implements ArrayBase.
Definition at line 428 of file Array.h.
   {
     Array& coarse = dynamic_cast<Array&>(coarseI);
     const Array<int>& coarseIndex = dynamic_cast<const Array<int>& >(coarseIndexI);
     for(int i=0; i<length; i++)
       if (coarseIndex[i]>=0)
         coarse[coarseIndex[i]] += _data[i];
   }
template<class T> virtual void Array< T >::limit (const double min, const double max) inline virtual
Reimplemented from ArrayBase.
Definition at line 404 of file Array.h.
   {
     if (_length == 1)
     {
         ArrayScalarTraits<T>::limit(_data[0],min, max);
     }
     else
       throw CException("invalid array for limit");
   }
template<class T> virtual ArrayBase& Array< T >::msaxpy (const ArrayBase & alphabase, const ArrayBase & xbase) inline virtual
Implements ArrayBase.
Definition at line 260 of file Array.h.
   {
     const Array& alpha = dynamic_cast<const Array& >(alphabase);
     const Array& x = dynamic_cast<const Array& >(xbase);
     if (alpha._length == 1 && x._length == _length)
     {
         for(int i=0;i<_length;i++)
           _data[i] -= alpha._data[0]*x._data[i];
     }
     else
       throw CException("invalid arrays for msaxpy");
     return *this;
   }
template<class T> virtual shared_ptr<IContainer> Array< T >::newClone () const inline virtual
Implements IContainer.
Definition at line 470 of file Array.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::iluSolve().
   {
     return shared_ptr<Array>(new Array(_length));
   }
template<class T> virtual shared_ptr<IContainer> Array< T >::newCopy () const inline virtual
Implements IContainer.
Definition at line 483 of file Array.h.
Referenced by MovingMeshModel< T >::advance(), PlateDeformationModel< T >::init(), StructureDeformationModel< T >::init(), MovingMeshModel< T >::init(), and FlowModel< T >::Impl::solveMomentum().
   {
     shared_ptr<Array> c(new Array(_length));
     *c = *this;
     return c;
   }
template<class T> virtual shared_ptr<ArrayBase> Array< T >::newSizedClone (const int size) const inline virtual
Implements ArrayBase.
Definition at line 476 of file Array.h.
   {
     return shared_ptr<Array>(new Array(size));
   }
template<class T> virtual ArrayBase& Array< T >::normalize (const ArrayBase & obase) inline virtual
Implements ArrayBase.
Definition at line 186 of file Array.h.
   {
     const Array& o = dynamic_cast<const Array& >(obase);
     if (_length == 1 && o._length==1)
     {
         for(int i=0;i<_length;i++)
           NumTypeTraits<T>::normalize(_data[i], o._data[i]);
     }
     else
       throw CException("invalid array for normalize");
     return *this;
   }
template<class T> virtual ArrayBase& Array< T >::operator*= (const ArrayBase & obase) inline virtual
Implements ArrayBase.
Definition at line 200 of file Array.h.
   {
     const Array& o = dynamic_cast<const Array& >(obase);
     if (o._length == 1)
     {
         for(int i=0;i<_length;i++)
           _data[i] *= o._data[0];
     }
     else if (o._length == _length)
     {
         for(int i=0;i<_length;i++)
           _data[i] *= o._data[i];
     }
     else
       throw CException("invalid array for operator *=");
     return *this;
   }
template<class T> virtual ArrayBase& Array< T >::operator+= (const ArrayBase & obase) inline virtual
Implements ArrayBase.
Definition at line 117 of file Array.h.
   {
     const Array& o = dynamic_cast<const Array& >(obase);
     if (o._length == _length)
     {
         for(int i=0;i<_length;i++)
           _data[i] += o._data[i];
     }
     else
       throw CException("invalid array for operator +=");
     return *this;
   }
template<class T> virtual shared_ptr<ArrayBase> Array< T >::operator- () const inline virtual
Reimplemented from ArrayBase.
Definition at line 415 of file Array.h.
   {
     if (_length == 1)
     {
         Array* nPtr(new Array(1));
         (*nPtr)[0] = -_data[0];
         return shared_ptr<ArrayBase>(nPtr);
     }
     throw CException("invalid  array for operator-");
   }
template<class T> virtual ArrayBase& Array< T >::operator-= (const ArrayBase & obase) inline virtual
Implements ArrayBase.
Definition at line 130 of file Array.h.
   {
     const Array& o = dynamic_cast<const Array& >(obase);
     if (o._length == _length)
     {
         for(int i=0;i<_length;i++)
           _data[i] -= o._data[i];
     }
     else
       throw CException("invalid array for operator -=");
     return *this;
   }
template<class T> virtual ArrayBase& Array< T >::operator/= (const ArrayBase & obase) inline virtual
Implements ArrayBase.
Definition at line 143 of file Array.h.
   {
     const Array& o = dynamic_cast<const Array& >(obase);
     if (o._length == 1)
     {
         for(int i=0;i<_length;i++)
           _data[i] /= o._data[0];
     }
     else if (o._length == _length)
     {
         for(int i=0;i<_length;i++)
           _data[i] /= o._data[i];
     }
     else
       throw CException("invalid array for operator /=");
     return *this;
   }
template<class T> virtual bool Array< T >::operator< (const double tolerance) const inline virtual
Implements ArrayBase.
Definition at line 218 of file Array.h.
   {
     if (_length == 1)
     {
         return (_data[0] <tolerance);
     }
     else
       throw CException("invalid array for operator<");
   }
template<class T> void Array< T >::operator= (const T & x) inline
Definition at line 104 of file Array.h.
Referenced by Array< Vector< int, 2 > >::copyFrom().
   {
     for(int i=0;i<_length;i++)
       _data[i] = x;
   }
template<class T> void Array< T >::operator= (const Array< T > & o) inline
Definition at line 110 of file Array.h.
   {
     for(int i=0;i<_length;i++)
       _data[i] = o._data[i];
   }
template<class T> T& Array< T >::operator[] (int n) inline
Definition at line 101 of file Array.h.
 {return _data[n];}
template<class T> const T& Array< T >::operator[] (int n) const inline
Definition at line 102 of file Array.h.
 {return _data[n];}
template<class T> virtual void Array< T >::print (ostream & os) const inline virtual
Implements ArrayBase.
Definition at line 228 of file Array.h.
   {
     if (_length > 0)
     {
        for ( int i = 0; i < _length; i++ )
          if ( i < _length-1)
             os <<_data[i] << endl;
          else
             os <<_data[i];
     }
     else
       throw CException("invalid array for print");
   }
template<class T> virtual shared_ptr<ArrayBase> Array< T >::reduceSum () const inline virtual
Implements ArrayBase.
Definition at line 314 of file Array.h.
   {
     T_Scalar sum(NumTypeTraits<T_Scalar>::getZero());
     for(int i=0; i<_length; i++)
       NumTypeTraits<T>::reduceSum(sum,_data[i]);
     shared_ptr<Array<T_Scalar> > nPtr(new Array<T_Scalar>(1));
     (*nPtr)[0] = sum;
     return nPtr;
   }
template<class T> void Array< T >::resize (const int newLength) inline
Definition at line 56 of file Array.h.
Referenced by DensityOfStates< T >::addMode(), DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::copyDOS(), KSConnectivity< T >::expandMySelfOther(), KSConnectivity< T >::expandMySelfSelf(), KSConnectivity< T >::finishCountOther(), KSConnectivity< T >::finishCountSelf(), Kspace< T >::getVelocities(), Kspace< T >::Kspace(), COMETInterface< T >::makeCoarseCoeffs(), Kspace< T >::makeFreqArray(), DensityOfStates< T >::mergeBins(), DensityOfStates< T >::refineBins(), DensityOfStates< T >::setDensity(), MeshPartitioner::setMeshColors(), and DensityOfStates< T >::setMids().
   {
     if (_ownData)
     {
         T* newData = new T[newLength];
         if (_data)
         {
           int len;
           if(newLength<_length)
             len=newLength;
           else
             len=_length;
           for(int i=0; i<len; i++)
             newData[i] = _data[i];
           delete [] _data;
         }
         _data = newData;
         _length = newLength;
     }
     else
       throw CException("cannot resize offset array");
   }
template<class T> virtual ArrayBase& Array< T >::safeDivide (const ArrayBase & obase) inline virtual
Implements ArrayBase.
Definition at line 173 of file Array.h.
   {
     const Array& o = dynamic_cast<const Array& >(obase);
     if (_length == 1 && o._length==1)
     {
         for(int i=0;i<_length;i++)
           NumTypeTraits<T>::safeDivide(_data[i], o._data[i]);
     }
     else
       throw CException("invalid array for safeDivide");
     return *this;
   }
template<class T> virtual ArrayBase& Array< T >::saxpy (const ArrayBase & alphabase, const ArrayBase & xbase) inline virtual
Implements ArrayBase.
Definition at line 243 of file Array.h.
   {
     const Array& alpha = dynamic_cast<const Array& >(alphabase);
     const Array& x = dynamic_cast<const Array& >(xbase);
     if (alpha._length == 1 && x._length == _length)
     {
         for(int i=0;i<_length;i++)
           _data[i] += alpha._data[0]*x._data[i];
     }
     else
       throw CException("invalid arrays for saxpy");
     return *this;
   }
template<class T> virtual void Array< T >::scatter (ArrayBase & other_, const ArrayBase & indices_, const int offset = 0) const inline virtual
Implements ArrayBase.
Definition at line 338 of file Array.h.
   {
     const Array<int>& indices = dynamic_cast<const Array<int>& >(indices_);
     Array& other = dynamic_cast<Array& >(other_);
     for(int ii=0; ii<indices.getLength(); ii++)
         other[offset+ii] = _data[indices[ii]];
   }
template<class T> virtual void Array< T >::setMax (const ArrayBase & obase) inline virtual
Implements ArrayBase.
Definition at line 161 of file Array.h.
   {
     const Array& o = dynamic_cast<const Array& >(obase);
     if (_length == 1 && o._length==1)
     {
         for(int i=0;i<_length;i++)
           NumTypeTraits<T>::setMax(_data[i], o._data[i]);
     }
     else
       throw CException("invalid array for setMax");
   }
template<class T> virtual void Array< T >::setSubsetFromSubset (const ArrayBase & other_, const ArrayBase & fromIndices_, const ArrayBase & toIndices_) inline virtual
Implements ArrayBase.
Definition at line 370 of file Array.h.
   {
     const Array<int>& toIndices = dynamic_cast<const Array<int>& >(toIndices_);
     const Array<int>& fromIndices = dynamic_cast<const Array<int>& >(fromIndices_);
     const Array& other = dynamic_cast<const Array& >(other_);
     for(int ii=0; ii<fromIndices.getLength(); ii++)
     {
       _data[toIndices[ii]] = other[fromIndices[ii]];
     }
   }
template<class T> virtual void Array< T >::setSum (const ArrayBase & sumBase) inline virtual
Implements ArrayBase.
Definition at line 325 of file Array.h.
   {
     const Array<T_Scalar>& sum =
       dynamic_cast<const Array<T_Scalar>& >(sumBase);
     if (sum.getLength() == 1)
     {
         const T_Scalar& s = sum[0];
         for(int i=0; i<_length; i++)
           _data[i]=s;
     }
   }
template<class T> virtual void Array< T >::zero () inline virtual
Implements IContainer.
Definition at line 281 of file Array.h.
Referenced by DensityOfStates< T >::addMode(), MovingMeshModel< T >::advance(), COMETBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), COMETBoundary< T >::applyTemperatureWallFine(), COMETBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC(), ArrowHeadMatrix< X, K >::ArrowHeadMatrix(), DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::binMode(), COMETModel< T >::binwiseHeatFluxIntegral(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), COMETModel< T >::calcBandTemps(), COMETModel< T >::calcDomainStats(), COMETModel< T >::calcModeFlux(), COMETModel< T >::calcModeTemps(), MeshMetricsCalculator< T >::calculateBoundaryNodeNormal(), MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), MeshMetricsCalculator< T >::calculateFaceAreas(), ScatteringKernel< T >::calculatePsi(), COMETModel< T >::coarsenInterfaceCells(), COMETESBGKDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETConvectionFine(), COMETESBGKDiscretizer< T >::COMETSolve(), COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETESBGKDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), FlowModel< T >::Impl::computeContinuityResidual(), VacancyModel< T >::Impl::computeIBFaceConcentration(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), ElectricModel< T >::Impl::computeIBFacePotential(), ThermalModel< T >::Impl::computeIBFaceTemperature(), FlowModel< T >::Impl::computeIBFaceVelocity(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), KineticModel< T >::computeSolidFacePressure(), COMETModel< T >::computeSolidFacePressure(), ContactModel< T >::Impl::computeSolidSurfaceForce(), ElectricModel< T >::Impl::computeSolidSurfaceForce(), FlowModel< T >::Impl::computeSolidSurfaceForce(), KineticModel< T >::computeSurfaceForce(), COMETModel< T >::computeSurfaceForce(), COMETDiscretizer< T >::correctInterface(), DiagonalMatrix< Diag, X >::createCoarseMatrix(), CRMatrixRect< T_Coeff, X, B >::createCoarseMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix(), GenericIBDiscretization< X, Diag, OffDiag >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), MomentumPressureGradientDiscretization< X >::discretize(), KSConnectivity< T >::emptyConnections(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_gTgB(), SpikeMatrix< T_Diag, T_OffDiag, X >::exchange_reducedSol(), KSConnectivity< T >::expandMySelfOther(), KSConnectivity< T >::expandMySelfSelf(), COMETESBGKDiscretizer< T >::findResid(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETESBGKDiscretizer< T >::findResidFine(), COMETDiscretizer< T >::findResidFull(), COMETModel< T >::FinishCoarseMesh(), KSConnectivity< T >::finishCountOther(), KSConnectivity< T >::finishCountSelf(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D(), FlowModel< T >::Impl::getPersistenceData(), PlateModel< T >::Impl::getPersistenceData(), KineticModel< T >::getPersistenceData(), ElectricModel< T >::Impl::getPersistenceData(), COMETModel< T >::getPersistenceData(), ScatteringKernel< T >::getTypeIIsource(), ScatteringKernel< T >::getTypeIsource(), Mesh::getUpdatedNodesCoordCoupling(), Kspace< T >::getVelocities(), COMETModel< T >::init(), FluxJacobianMatrix< OffDiag, X >::initAssembly(), CRMatrixTranspose< T_Coeff, X, B >::initAssembly(), CRMatrixRect< T_Coeff, X, B >::initAssembly(), DiagonalMatrix< Diag, X >::initAssembly(), CRMatrix< T_Diag, T_OffDiag, X >::initAssembly(), COMETModel< T >::initFromOld(), COMETModel< T >::injectResid(), ScatteringKernel< T >::IterateToEquilibrium(), SpikeMatrix< T_Diag, T_OffDiag, X >::luSolver(), KineticModel< T >::MacroparameterIBCell(), COMETInterface< T >::makeCoarseCoeffs(), COMETModel< T >::MakeInteriorCoarseMesh(), DensityOfStates< T >::mergeBins(), COMETModel< T >::modewiseHeatFluxIntegral(), ArrowHeadMatrix< X, K >::multiply(), SquareMatrix< T, N >::multiply(), KSConnectivity< T >::multiplyOther(), KSConnectivity< T >::multiplySelf(), COMETDiscretizer< T >::ScatterPhonons(), ScatteringKernel< T >::scatterPhonons(), COMETESBGKDiscretizer< T >::setBoundaryValFine(), DensityOfStates< T >::setDensity(), SpikeMatrix< T_Diag, T_OffDiag, X >::setgBgT(), SpikeMatrix< T_Diag, T_OffDiag, X >::setReducedRHS(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRHS(), ShockTube< T >::solve(), SquareMatrix< T, N >::SquareMatrix(), SquareMatrixESBGK< T >::SquareMatrixESBGK(), SpikeStorage::syncCellIDs(), ElectricModel< T >::Impl::updateConvectionFlux(), COMETDiscretizer< T >::updateGhostFine(), COMETInterface< T >::updateOtherGhost(), COMETInterface< T >::updateResid(), ScatteringKernel< T >::updateSource(), ScatteringKernel< T >::updateSource2(), ScatteringKernel< T >::updateSourceTerm(), ScatteringKernel< T >::updateSourceTermTest(), MovingMeshModel< T >::volChange(), SquareMatrix< T, N >::zero(), SquareMatrixESBGK< T >::zero(), and ArrowHeadMatrix< X, K >::zero().
   {
     memset(_data,0,getDataSize());
   }
template<class T> virtual void Array< T >::zeroPartial (const int iBeg, const int iEnd) inline virtual
Implements ArrayBase.
Definition at line 398 of file Array.h.
   {
     for(int i=iBeg;i<iEnd;i++)
       _data[i] = NumTypeTraits<T>::getZero();
   }
Member Data Documentation
template<class T> T* Array< T >::_data private
Definition at line 500 of file Array.h.
Referenced by Array< Vector< int, 2 > >::copyPartial(), Array< Vector< int, 2 > >::correct(), Array< Vector< int, 2 > >::dotWith(), Array< Vector< int, 2 > >::gather(), Array< Vector< int, 2 > >::getData(), Array< Vector< int, 2 > >::getOneNorm(), Array< Vector< int, 2 > >::getSubset(), Array< Vector< int, 2 > >::inject(), Array< Vector< int, 2 > >::limit(), main(), Array< Vector< int, 2 > >::msaxpy(), Array< Vector< int, 2 > >::normalize(), Array< Vector< int, 2 > >::operator*=(), Array< Vector< int, 2 > >::operator+=(), Array< Vector< int, 2 > >::operator-(), Array< Vector< int, 2 > >::operator-=(), Array< Vector< int, 2 > >::operator/=(), Array< Vector< int, 2 > >::operator<(), Array< Vector< int, 2 > >::operator=(), Array< Vector< int, 2 > >::operator[](), Array< Vector< int, 2 > >::print(), Array< Vector< int, 2 > >::reduceSum(), Array< Vector< int, 2 > >::resize(), Array< Vector< int, 2 > >::safeDivide(), Array< Vector< int, 2 > >::saxpy(), Array< Vector< int, 2 > >::scatter(), Array< Vector< int, 2 > >::setMax(), Array< Vector< int, 2 > >::setSubsetFromSubset(), Array< Vector< int, 2 > >::setSum(), Array< Vector< int, 2 > >::zero(), Array< Vector< int, 2 > >::zeroPartial(), and Array< Vector< int, 2 > >::~Array().
template<class T> int Array< T >::_length private
Definition at line 499 of file Array.h.
Referenced by Array< Vector< int, 2 > >::Array(), Array< Vector< int, 2 > >::getDataSize(), Array< Vector< int, 2 > >::getLength(), Array< Vector< int, 2 > >::getShape(), Array< Vector< int, 2 > >::limit(), Array< Vector< int, 2 > >::msaxpy(), Array< Vector< int, 2 > >::newClone(), Array< Vector< int, 2 > >::newCopy(), Array< Vector< int, 2 > >::normalize(), Array< Vector< int, 2 > >::operator*=(), Array< Vector< int, 2 > >::operator+=(), Array< Vector< int, 2 > >::operator-(), Array< Vector< int, 2 > >::operator-=(), Array< Vector< int, 2 > >::operator/=(), Array< Vector< int, 2 > >::operator<(), Array< Vector< int, 2 > >::operator=(), Array< Vector< int, 2 > >::print(), Array< Vector< int, 2 > >::reduceSum(), Array< Vector< int, 2 > >::resize(), Array< Vector< int, 2 > >::safeDivide(), Array< Vector< int, 2 > >::saxpy(), Array< Vector< int, 2 > >::setMax(), Array< Vector< int, 2 > >::setSum(), and Array< Vector< int, 2 > >::~Array().
template<class T> bool Array< T >::_ownData mutable private
Definition at line 501 of file Array.h.
Referenced by Array< Vector< int, 2 > >::disownData(), Array< Vector< int, 2 > >::resize(), and Array< Vector< int, 2 > >::~Array().
The documentation for this class was generated from the following file:
Array.h