Memosa-FVM: BaseGenericPhononBCS< X, Diag, OffDiag > Class Template Reference
BaseGenericPhononBCS< X, Diag, OffDiag > Class Template Reference
#include <GenericPhononBCS.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Array< int > IntArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef FluxJacobianMatrix
< Diag, X > FMatrix
typedef DiagonalMatrix< Diag, X > BBMatrix
typedef Array< Diag > DiagArray
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
BaseGenericPhononBCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
void applyDirichletBC (int f, const X &bValue) const
void applyDirichletBC (const X &bValue) const
void applyDirichletBC (const FloatValEvaluator< X > &bValue) const
void applyExtrapolationBC () const
void applyExtrapolationBC (const int f) const
void applyInterfaceBC () const
void applyFlowBC (const TArray &convFlux, const X &bValue) const
void applyNonzeroDiagBC () const
void applyNonzeroDiagBC (int f) const
Protected Attributes
const StorageSite & _faces
const StorageSite & _cells
const IntArray & _ibType
const CRConnectivity & _faceCells
const Field & _varField
const MultiField::ArrayIndex _xIndex
CCMatrix & _dRdX
CCAssembler & _assembler
DiagArray & _dRdXDiag
XArray & _x
XArray & _r
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
Detailed Description
template<class X, class Diag, class OffDiag>
class BaseGenericPhononBCS< X, Diag, OffDiag >
Definition at line 22 of file GenericPhononBCS.h.
Member Typedef Documentation
template<class X, class Diag, class OffDiag> typedef DiagonalMatrix<Diag,X> BaseGenericPhononBCS< X, Diag, OffDiag >::BBMatrix
Definition at line 37 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef CCMatrix::PairWiseAssembler BaseGenericPhononBCS< X, Diag, OffDiag >::CCAssembler
Definition at line 34 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef CRMatrix<Diag,OffDiag,X> BaseGenericPhononBCS< X, Diag, OffDiag >::CCMatrix
Definition at line 33 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<Diag> BaseGenericPhononBCS< X, Diag, OffDiag >::DiagArray
Definition at line 39 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef FluxJacobianMatrix<Diag,X> BaseGenericPhononBCS< X, Diag, OffDiag >::FMatrix
Definition at line 36 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<int> BaseGenericPhononBCS< X, Diag, OffDiag >::IntArray
Definition at line 29 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<OffDiag> BaseGenericPhononBCS< X, Diag, OffDiag >::OffDiagArray
Definition at line 40 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef NumTypeTraits<X>::T_Scalar BaseGenericPhononBCS< X, Diag, OffDiag >::T_Scalar
Definition at line 26 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<T_Scalar> BaseGenericPhononBCS< X, Diag, OffDiag >::TArray
Definition at line 28 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef Vector<T_Scalar,3> BaseGenericPhononBCS< X, Diag, OffDiag >::VectorT3
Definition at line 31 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<VectorT3> BaseGenericPhononBCS< X, Diag, OffDiag >::VectorT3Array
Definition at line 43 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<X> BaseGenericPhononBCS< X, Diag, OffDiag >::XArray
Definition at line 42 of file GenericPhononBCS.h.
Constructor & Destructor Documentation
template<class X, class Diag, class OffDiag> BaseGenericPhononBCS< X, Diag, OffDiag >::BaseGenericPhononBCS (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, Field & varField, MultiFieldMatrix & matrix, MultiField & xField, MultiField & rField) inline
Definition at line 46 of file GenericPhononBCS.h.
                                                               :
   _faces(faces),
     _cells(mesh.getCells()),
     _ibType(dynamic_cast<const IntArray&>(geomFields.ibType[_cells])),
     _faceCells(mesh.getFaceCells(_faces)),
     _varField(varField),
     _xIndex(&_varField,&_cells),
     _dRdX(dynamic_cast<CCMatrix&>(matrix.getMatrix(_xIndex,_xIndex))),
     _assembler(_dRdX.getPairWiseAssembler(_faceCells)),
     _dRdXDiag(_dRdX.getDiag()),
     _x(dynamic_cast<XArray&>(xField[_xIndex])),
     _r(dynamic_cast<XArray&>(rField[_xIndex])),
     _areaMagField(geomFields.areaMag),
     _faceAreaMag(dynamic_cast<const TArray&>(_areaMagField[_faces])),
     _areaField(geomFields.area),
     _faceArea(dynamic_cast<const VectorT3Array&>(_areaField[_faces]))
       {}
Member Function Documentation
template<class X, class Diag, class OffDiag> void BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC (int f, const X & bValue) const inline
Definition at line 69 of file GenericPhononBCS.h.
References BaseGenericPhononBCS< X, Diag, OffDiag >::_assembler, BaseGenericPhononBCS< X, Diag, OffDiag >::_dRdXDiag, BaseGenericPhononBCS< X, Diag, OffDiag >::_faceCells, BaseGenericPhononBCS< X, Diag, OffDiag >::_ibType, BaseGenericPhononBCS< X, Diag, OffDiag >::_r, BaseGenericPhononBCS< X, Diag, OffDiag >::_x, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), and Mesh::IBTYPE_FLUID.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), and BaseGenericPhononBCS< X, Diag, OffDiag >::applyFlowBC().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     const OffDiag dRC0dXC1 = _assembler.getCoeff01(f);
     // since we know the boundary value, compute the boundary
     // x correction and it's contribution to the residual for c0; we
     // can then eliminate the coefficient to the boundary cell
     const X dXC1 = bValue - _x[c1];
     const X dRC0 = dRC0dXC1*dXC1;
     _r[c0] += dRC0;
     _assembler.getCoeff01(f) = NumTypeTraits<OffDiag>::getZero();
     // set the boundary value and make its correction equation an
     // identity
     _x[c1] = bValue;
     _assembler.getCoeff10(f) = NumTypeTraits<OffDiag>::getZero();
     _r[c1] = NumTypeTraits<X>::getZero();
     _dRdXDiag[c1] = NumTypeTraits<Diag>::getNegativeUnity();
  }
template<class X, class Diag, class OffDiag> void BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC (const X & bValue) const inline
Definition at line 98 of file GenericPhononBCS.h.
References BaseGenericPhononBCS< X, Diag, OffDiag >::_faces, BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applyDirichletBC(i,bValue);
   }
template<class X, class Diag, class OffDiag> void BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC (const FloatValEvaluator< X > & bValue) const inline
Definition at line 104 of file GenericPhononBCS.h.
References BaseGenericPhononBCS< X, Diag, OffDiag >::_faces, BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applyDirichletBC(i,bValue[i]);
   }
template<class X, class Diag, class OffDiag> void BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC () const inline
Definition at line 111 of file GenericPhononBCS.h.
References BaseGenericPhononBCS< X, Diag, OffDiag >::_faces, and StorageSite::getCount().
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyFlowBC().
   {
     for(int i=0; i<_faces.getCount(); i++)
         applyExtrapolationBC(i);
   }
template<class X, class Diag, class OffDiag> void BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC (const int f) const inline
Definition at line 119 of file GenericPhononBCS.h.
References BaseGenericPhononBCS< X, Diag, OffDiag >::_assembler, BaseGenericPhononBCS< X, Diag, OffDiag >::_dRdX, BaseGenericPhononBCS< X, Diag, OffDiag >::_dRdXDiag, BaseGenericPhononBCS< X, Diag, OffDiag >::_faceCells, BaseGenericPhononBCS< X, Diag, OffDiag >::_ibType, BaseGenericPhononBCS< X, Diag, OffDiag >::_r, BaseGenericPhononBCS< X, Diag, OffDiag >::_x, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), Mesh::IBTYPE_FLUID, and CRMatrix< T_Diag, T_OffDiag, X >::setBoundary().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     // the current value of flux and its Jacobians
     const Diag dFluxdXC1 = -_dRdXDiag[c1];
     const X xc0mxc1 = _x[c0]-_x[c1];
     // eliminate boundary dependency from cell equation
     _dRdXDiag[c0] += dFluxdXC1;
     _r[c0] += dFluxdXC1*xc0mxc1;
     _assembler.getCoeff01(f) = 0;
     // boundary value equation
     _dRdXDiag[c1] = NumTypeTraits<Diag>::getNegativeUnity();
     _assembler.getCoeff10(f) = NumTypeTraits<OffDiag>::getUnity();
     _r[c1] = xc0mxc1;
     _dRdX.setBoundary(c1);
  }
template<class X, class Diag, class OffDiag> void BaseGenericPhononBCS< X, Diag, OffDiag >::applyFlowBC (const TArray & convFlux, const X & bValue) const inline
Definition at line 152 of file GenericPhononBCS.h.
References BaseGenericPhononBCS< X, Diag, OffDiag >::_faces, BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC(), and StorageSite::getCount().
   {
     for(int f=0; f<_faces.getCount(); f++)
       if (convFlux[f] < 0)
         applyDirichletBC(f,bValue);
       else
         applyExtrapolationBC(f);
   }
template<class X, class Diag, class OffDiag> void BaseGenericPhononBCS< X, Diag, OffDiag >::applyInterfaceBC () const inline
Definition at line 146 of file GenericPhononBCS.h.
References BaseGenericPhononBCS< X, Diag, OffDiag >::_faces, and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applyInterfaceBC(i);
   }
template<class X, class Diag, class OffDiag> void BaseGenericPhononBCS< X, Diag, OffDiag >::applyNonzeroDiagBC () const inline
Definition at line 161 of file GenericPhononBCS.h.
References BaseGenericPhononBCS< X, Diag, OffDiag >::_faces, and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applyNonzeroDiagBC(i);
   }
template<class X, class Diag, class OffDiag> void BaseGenericPhononBCS< X, Diag, OffDiag >::applyNonzeroDiagBC (int f) const inline
Definition at line 167 of file GenericPhononBCS.h.
References BaseGenericPhononBCS< X, Diag, OffDiag >::_dRdXDiag, BaseGenericPhononBCS< X, Diag, OffDiag >::_faceCells, BaseGenericPhononBCS< X, Diag, OffDiag >::_ibType, and Mesh::IBTYPE_FLUID.
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     _dRdXDiag[c1][0] = T_Scalar(-1.0);
   }
Member Data Documentation
template<class X, class Diag, class OffDiag> const Field& BaseGenericPhononBCS< X, Diag, OffDiag >::_areaField protected
Definition at line 193 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> const Field& BaseGenericPhononBCS< X, Diag, OffDiag >::_areaMagField protected
Definition at line 191 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> CCAssembler& BaseGenericPhononBCS< X, Diag, OffDiag >::_assembler protected
Definition at line 187 of file GenericPhononBCS.h.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), and BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC().
template<class X, class Diag, class OffDiag> const StorageSite& BaseGenericPhononBCS< X, Diag, OffDiag >::_cells protected
Definition at line 181 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> CCMatrix& BaseGenericPhononBCS< X, Diag, OffDiag >::_dRdX protected
Definition at line 186 of file GenericPhononBCS.h.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC().
template<class X, class Diag, class OffDiag> DiagArray& BaseGenericPhononBCS< X, Diag, OffDiag >::_dRdXDiag protected
Definition at line 188 of file GenericPhononBCS.h.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC(), and BaseGenericPhononBCS< X, Diag, OffDiag >::applyNonzeroDiagBC().
template<class X, class Diag, class OffDiag> const VectorT3Array& BaseGenericPhononBCS< X, Diag, OffDiag >::_faceArea protected
Definition at line 194 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> const TArray& BaseGenericPhononBCS< X, Diag, OffDiag >::_faceAreaMag protected
Definition at line 192 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> const CRConnectivity& BaseGenericPhononBCS< X, Diag, OffDiag >::_faceCells protected
Definition at line 183 of file GenericPhononBCS.h.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC(), and BaseGenericPhononBCS< X, Diag, OffDiag >::applyNonzeroDiagBC().
template<class X, class Diag, class OffDiag> const StorageSite& BaseGenericPhononBCS< X, Diag, OffDiag >::_faces protected
Definition at line 180 of file GenericPhononBCS.h.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyFlowBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyInterfaceBC(), and BaseGenericPhononBCS< X, Diag, OffDiag >::applyNonzeroDiagBC().
template<class X, class Diag, class OffDiag> const IntArray& BaseGenericPhononBCS< X, Diag, OffDiag >::_ibType protected
Definition at line 182 of file GenericPhononBCS.h.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC(), and BaseGenericPhononBCS< X, Diag, OffDiag >::applyNonzeroDiagBC().
template<class X, class Diag, class OffDiag> XArray& BaseGenericPhononBCS< X, Diag, OffDiag >::_r protected
Definition at line 190 of file GenericPhononBCS.h.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), and BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC().
template<class X, class Diag, class OffDiag> const Field& BaseGenericPhononBCS< X, Diag, OffDiag >::_varField protected
Definition at line 184 of file GenericPhononBCS.h.
template<class X, class Diag, class OffDiag> XArray& BaseGenericPhononBCS< X, Diag, OffDiag >::_x protected
Definition at line 189 of file GenericPhononBCS.h.
Referenced by BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), and BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC().
template<class X, class Diag, class OffDiag> const MultiField::ArrayIndex BaseGenericPhononBCS< X, Diag, OffDiag >::_xIndex protected
Definition at line 185 of file GenericPhononBCS.h.
The documentation for this class was generated from the following file:
GenericPhononBCS.h