Memosa-FVM: ConvectionDiscretization< X, Diag, OffDiag > Class Template Reference
ConvectionDiscretization< X, Diag, OffDiag > Class Template Reference
#include <ConvectionDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Gradient< X > XGrad
typedef Array< int > IntArray
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Array< XGrad > GradArray
Public Member Functions
ConvectionDiscretization (const MeshList &meshes, const GeomFields &geomFields, Field &varField, const Field &convectingFluxField, const Field &continuityResidualField, const Field &varGradientField, const bool useCentralDifference=false)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const Field & _convectingFluxField
const Field & _continuityResidualField
const Field & _varGradientField
const bool _useCentralDifference
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class ConvectionDiscretization< X, Diag, OffDiag >
Definition at line 18 of file ConvectionDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler ConvectionDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 25 of file ConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> ConvectionDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 23 of file ConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray ConvectionDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 24 of file ConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<XGrad> ConvectionDiscretization< X, Diag, OffDiag >::GradArray
Definition at line 35 of file ConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<int> ConvectionDiscretization< X, Diag, OffDiag >::IntArray
Definition at line 29 of file ConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar ConvectionDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 21 of file ConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> ConvectionDiscretization< X, Diag, OffDiag >::TArray
Definition at line 31 of file ConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> ConvectionDiscretization< X, Diag, OffDiag >::VectorT3
Definition at line 32 of file ConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> ConvectionDiscretization< X, Diag, OffDiag >::VectorT3Array
Definition at line 33 of file ConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> ConvectionDiscretization< X, Diag, OffDiag >::XArray
Definition at line 30 of file ConvectionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Gradient<X> ConvectionDiscretization< X, Diag, OffDiag >::XGrad
Definition at line 27 of file ConvectionDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > ConvectionDiscretization< X, Diag, OffDiag >::ConvectionDiscretization (const MeshList & meshes, const GeomFields & geomFields, Field & varField, const Field & convectingFluxField, const Field & continuityResidualField, const Field & varGradientField, const bool useCentralDifference = false) inline
Definition at line 37 of file ConvectionDiscretization.h.
                                                                   :
     Discretization(meshes),
     _geomFields(geomFields),
     _varField(varField),
     _convectingFluxField(convectingFluxField),
     _continuityResidualField(continuityResidualField),
     _varGradientField(varGradientField),
     _useCentralDifference(useCentralDifference)
   {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void ConvectionDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 53 of file ConvectionDiscretization.h.
References ConvectionDiscretization< X, Diag, OffDiag >::_continuityResidualField, ConvectionDiscretization< X, Diag, OffDiag >::_convectingFluxField, ConvectionDiscretization< X, Diag, OffDiag >::_geomFields, ConvectionDiscretization< X, Diag, OffDiag >::_useCentralDifference, ConvectionDiscretization< X, Diag, OffDiag >::_varField, Mesh::getAllFaceCells(), Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), Mesh::getFaces(), MultiFieldMatrix::getMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), StorageSite::getSelfCount(), GeomFields::gridFlux, Field::hasArray(), GeomFields::ibType, Mesh::IBTYPE_BOUNDARY, and Mesh::IBTYPE_FLUID.
   {
     const StorageSite& cells = mesh.getCells();
     const StorageSite& faces = mesh.getFaces();
     // should there be some other checks ?
     if (!_convectingFluxField.hasArray(faces))
       return;
     const TArray& convectingFlux =
       dynamic_cast<const TArray&>(_convectingFluxField[faces]);
     const TArray& continuityResidual =
       dynamic_cast<const TArray&>(_continuityResidualField[cells]);
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix =
       dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     const CRConnectivity& faceCells = mesh.getAllFaceCells();
     CCAssembler& assembler = matrix.getPairWiseAssembler(faceCells);
     DiagArray& diag = matrix.getDiag();
     const XArray& xCell = dynamic_cast<const XArray&>(xField[cVarIndex]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     //const GradArray& xGradCell = dynamic_cast<GradArray>(_varGradientField[cells]);
     const IntArray& ibType = dynamic_cast<const IntArray&>(_geomFields.ibType[cells]);
     const int nFaces = faces.getCount();
     if (_geomFields.gridFlux.hasArray(faces))
     {
         shared_ptr<TArray> gridFluxPtr(new TArray(nFaces));
         TArray& gridFlux = *gridFluxPtr;
         gridFlux = dynamic_cast<const TArray&>(_geomFields.gridFlux[faces]);
         for(int f=0; f<nFaces; f++)
         {
             const int c0 = faceCells(f,0);
             const int c1 = faceCells(f,1);
             const T_Scalar faceCFlux = convectingFlux[f] - gridFlux[f];
             X varFlux;
             if (faceCFlux > T_Scalar(0))
             {
                 varFlux = faceCFlux*xCell[c0];
                 diag[c0] -= faceCFlux;
                 assembler.getCoeff10(f) += faceCFlux;
             }
             else
             {
                 varFlux = faceCFlux*xCell[c1];
                 diag[c1] += faceCFlux;
                 assembler.getCoeff01(f)-= faceCFlux;
             }
             rCell[c0] -= varFlux;
             rCell[c1] += varFlux;
         }
     }
     else
     {
       if (_useCentralDifference){
         for(int f=0; f<nFaces; f++)
           {
               const int c0 = faceCells(f,0);
               const int c1 = faceCells(f,1);
               const T_Scalar faceCFlux = convectingFlux[f];
               bool isIBFace = (((ibType[c0] == Mesh::IBTYPE_FLUID)
                                 && (ibType[c1] == Mesh::IBTYPE_BOUNDARY)) ||
                                ((ibType[c1] == Mesh::IBTYPE_FLUID)
                                 && (ibType[c0] == Mesh::IBTYPE_BOUNDARY)));
               X varFlux =0.5*faceCFlux*(xCell[c0] + xCell[c0]);
               rCell[c0] -= varFlux;
               rCell[c1] += varFlux;
               if (isIBFace)
               {
                   // linearize the actual flux as calculated
                   // above. this will ensure that the Ib
                   // discretization will be able to fix the value
                   // correctly using the ib face value
                   diag[c0] -= 0.5*faceCFlux;
                   assembler.getCoeff10(f) -= 0.5*faceCFlux;
                   diag[c1] += 0.5*faceCFlux;
                   assembler.getCoeff01(f) += 0.5*faceCFlux;
               }
               else
               {
                   // linearize as upwind flux so that linear system
                   // remains diagonally dominant
                   if (faceCFlux > T_Scalar(0))
                   {
                       diag[c0] -= faceCFlux;
                       assembler.getCoeff10(f) += faceCFlux;
                   }
                   else
                   {
                       diag[c1] += faceCFlux;
                       assembler.getCoeff01(f)-= faceCFlux;
                   }
               }
           }
        }
        else
           for(int f=0; f<nFaces; f++)
           {
               const int c0 = faceCells(f,0);
               const int c1 = faceCells(f,1);
               const T_Scalar faceCFlux = convectingFlux[f];
               X varFlux;
               if (faceCFlux > T_Scalar(0))
               {
                   varFlux = faceCFlux*xCell[c0];
                   diag[c0] -= faceCFlux;
                   assembler.getCoeff10(f) += faceCFlux;
               }
               else
               {
                   varFlux = faceCFlux*xCell[c1];
                   diag[c1] += faceCFlux;
                   assembler.getCoeff01(f)-= faceCFlux;
               }
               rCell[c0] -= varFlux;
               rCell[c1] += varFlux;
               //cout << "convflux" << varFlux << endl;
           }
     }
     const int nCells = cells.getSelfCount();
     for(int c=0;c<nCells;c++)
     {
         const T_Scalar cImb = continuityResidual[c];
         diag[c] += cImb;
     }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const Field& ConvectionDiscretization< X, Diag, OffDiag >::_continuityResidualField private
Definition at line 206 of file ConvectionDiscretization.h.
Referenced by ConvectionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& ConvectionDiscretization< X, Diag, OffDiag >::_convectingFluxField private
Definition at line 205 of file ConvectionDiscretization.h.
Referenced by ConvectionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& ConvectionDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 203 of file ConvectionDiscretization.h.
Referenced by ConvectionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const bool ConvectionDiscretization< X, Diag, OffDiag >::_useCentralDifference private
Definition at line 208 of file ConvectionDiscretization.h.
Referenced by ConvectionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& ConvectionDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 204 of file ConvectionDiscretization.h.
Referenced by ConvectionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& ConvectionDiscretization< X, Diag, OffDiag >::_varGradientField private
Definition at line 207 of file ConvectionDiscretization.h.
The documentation for this class was generated from the following file:
ConvectionDiscretization.h