Memosa-FVM: MMReader Class Reference
MMReader Class Reference
#include <MMReader.h>
Public Types
typedef CRMatrix< double,
double, double > MatrixType
Public Member Functions
MMReader (const string &matrixFileName, const string &rhsFileName)
virtual ~MMReader ()
DEFINE_TYPENAME ("MMReader")
shared_ptr< LinearSystem > getLS ()
Public Member Functions inherited from Reader
Reader (const string &fileName)
virtual ~Reader ()
void resetFilePtr ()
string readLine ()
void close ()
Private Member Functions
void readHeader (int &nRows, int &nCols, int &nNonZeroes, bool &isSymmetric)
Private Attributes
const string _rhsFileName
Field _field
shared_ptr< StorageSite > _site
shared_ptr< CRConnectivity > _cm
Additional Inherited Members
Protected Attributes inherited from Reader
const string _fileName
FILE * _fp
Detailed Description
Definition at line 16 of file MMReader.h.
Member Typedef Documentation
typedef CRMatrix<double,double,double> MMReader::MatrixType
Definition at line 20 of file MMReader.h.
Constructor & Destructor Documentation
MMReader::MMReader (const string & matrixFileName, const string & rhsFileName)
Definition at line 11 of file MMReader.cpp.
                                                                           :
   Reader(matrixFileName),
   _rhsFileName(rhsFileName),
   _field("test"),
   _site(),
   _cm()
 {}
MMReader::~MMReader () virtual
Definition at line 19 of file MMReader.cpp.
 {}
Member Function Documentation
MMReader::DEFINE_TYPENAME ("MMReader")
shared_ptr< LinearSystem > MMReader::getLS ()
Definition at line 80 of file MMReader.cpp.
References _cm, _field, Reader::_fp, _rhsFileName, _site, Reader::close(), readHeader(), and Reader::resetFilePtr().
Referenced by main().
 {
   int nRows, nCols, nNonZeroes;
   bool isSymmetric;
   readHeader(nRows,nCols,nNonZeroes,isSymmetric);
   cout << " nRow " << nRows << " x " << nCols
        << " matrix with " << nNonZeroes << " entries "
        << endl;
   cout << "reading sizes" << endl;
   _site = shared_ptr<StorageSite>(new StorageSite(nRows,0));
   _cm = shared_ptr<CRConnectivity>(new CRConnectivity(*_site,*_site));
   _cm->initCount();
   for(int nr=0; nr<nNonZeroes; nr++)
   {
       int i, j;
       double c;
       fscanf(_fp,"%d %d %lf",&i,&j,&c);
       i-=1;
       j-=1;
       if (i!=j)
       {
           _cm->addCount(i,1);
           if (isSymmetric)
             _cm->addCount(j,1);
       }
   }
   _cm->finishCount();
   shared_ptr<MatrixType> m(new MatrixType(*_cm));
   MultiField::ArrayIndex rowI(&_field,_site.get());
   shared_ptr<Array<double> > xPtr(new Array<double>(nRows));
   xPtr->zero();
   shared_ptr<LinearSystem> ls(new LinearSystem());
   ls->getX().addArray(rowI,xPtr);
   ls->getMatrix().addMatrix(rowI,rowI,m);
   ls->initAssembly();
   Array<double>& diag = m->getDiag();
   Array<double>& offDiag = m->getOffDiag();
   // rewind file
   cout << "rewinding and reading coeffs" << endl;
   resetFilePtr();
   readHeader(nRows,nCols,nNonZeroes,isSymmetric);
   for(int nr=0; nr<nNonZeroes; nr++)
   {
       int i, j;
       double c;
       fscanf(_fp,"%d %d %lf",&i,&j,&c);
       i-=1;
       j-=1;
       if (i!=j)
       {
           int pos = _cm->add(i,j);
           offDiag[pos] = c;
           if (isSymmetric)
           {
               pos = _cm->add(j,i);
               offDiag[pos] = c;
           }
       }
       else
         diag[i] = c;
   }
   _cm->finishAdd();
   cout << "finished reading " << endl;
   close();
   //ls->getB().addArray(rowI,bPtr);
   Array<double>& b = dynamic_cast<Array<double>&>(ls->getB()[rowI]);
   FILE *bFile = fopen(_rhsFileName.c_str(), "rb");
   for(int i=0; i<nRows; i++)
   {
       double r;
       fscanf(bFile,"%lf",&r);
       b[i]=-r;
   }
   ls->initSolve();
   return ls;
 }
void MMReader::readHeader (int & nRows, int & nCols, int & nNonZeroes, bool & isSymmetric) private
Definition at line 23 of file MMReader.cpp.
References Reader::_fp.
Referenced by getLS().
 {
   if (_fp==0)
     throw CException("cannot open matrix file ");
   char buf[32];
   fscanf(_fp,"%s",buf);
   string h1(buf);
   if (h1 == "%%")
   {
       fscanf(_fp,"%s",buf);
       string h2(buf);
       if (h2 != "MatrixMarket")
         throw CException("not a MatrixMarket file");
   }
   else if (h1 != "%%MatrixMarket")
     throw CException("not a MatrixMarket file");
   fscanf(_fp,"%s",buf);
   string matrixType(buf);
   fscanf(_fp,"%s",buf);
   string coordinate(buf);
   fscanf(_fp,"%s",buf);
   string ftype(buf);
   fscanf(_fp,"%s",buf);
   string symm(buf);
   isSymmetric = false;
   if (matrixType != "matrix")
     throw CException("not a MatrixMarket file");
   if (coordinate != "coordinate")
     throw CException("not a sparse matrix");
   if (ftype != "real")
     throw CException("not a real matrix");
   if (symm == "symmetric")
     isSymmetric = true;
   else if (symm != "general")
     throw CException("not symmetric or general matrix");
   fscanf(_fp, "%d %d %d", &nRows, &nCols, &nNonZeroes);
   if (nRows != nCols)
     throw CException("not a square matrix");
 }
Member Data Documentation
shared_ptr<CRConnectivity> MMReader::_cm private
Definition at line 33 of file MMReader.h.
Referenced by getLS().
Field MMReader::_field private
Definition at line 31 of file MMReader.h.
Referenced by getLS().
const string MMReader::_rhsFileName private
Definition at line 30 of file MMReader.h.
Referenced by getLS().
shared_ptr<StorageSite> MMReader::_site private
Definition at line 32 of file MMReader.h.
Referenced by getLS().
The documentation for this class was generated from the following files:
MMReader.h
MMReader.cpp