Memosa-FVM: LinearizeInterfaceJump< X, Diag, OffDiag > Class Template Reference
LinearizeInterfaceJump< X, Diag, OffDiag > Class Template Reference
#include <LinearizeInterfaceJump.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef Array< T_Scalar > TArray
typedef Array< X > XArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef SquareTensor< T_Scalar, 2 > SquareTensorT2
Public Member Functions
LinearizeInterfaceJump (const T_Scalar A_coeff, const X B_coeff, Field &varField)
void discretize (const Mesh &mesh, const Mesh &parentMesh, const Mesh &otherMesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Private Attributes
Field & _varField
const T_Scalar _A_coeff
const X _B_coeff
Detailed Description
template<class X, class Diag, class OffDiag>
class LinearizeInterfaceJump< X, Diag, OffDiag >
Definition at line 24 of file LinearizeInterfaceJump.h.
Member Typedef Documentation
template<class X, class Diag, class OffDiag> typedef CRMatrix<Diag,OffDiag,X> LinearizeInterfaceJump< X, Diag, OffDiag >::CCMatrix
Definition at line 28 of file LinearizeInterfaceJump.h.
template<class X, class Diag, class OffDiag> typedef CCMatrix::DiagArray LinearizeInterfaceJump< X, Diag, OffDiag >::DiagArray
Definition at line 29 of file LinearizeInterfaceJump.h.
template<class X, class Diag, class OffDiag> typedef SquareTensor<T_Scalar,2> LinearizeInterfaceJump< X, Diag, OffDiag >::SquareTensorT2
Definition at line 34 of file LinearizeInterfaceJump.h.
template<class X, class Diag, class OffDiag> typedef NumTypeTraits<X>::T_Scalar LinearizeInterfaceJump< X, Diag, OffDiag >::T_Scalar
Definition at line 27 of file LinearizeInterfaceJump.h.
template<class X, class Diag, class OffDiag> typedef Array<T_Scalar> LinearizeInterfaceJump< X, Diag, OffDiag >::TArray
Definition at line 30 of file LinearizeInterfaceJump.h.
template<class X, class Diag, class OffDiag> typedef Vector<T_Scalar,3> LinearizeInterfaceJump< X, Diag, OffDiag >::VectorT3
Definition at line 32 of file LinearizeInterfaceJump.h.
template<class X, class Diag, class OffDiag> typedef Array<VectorT3> LinearizeInterfaceJump< X, Diag, OffDiag >::VectorT3Array
Definition at line 33 of file LinearizeInterfaceJump.h.
template<class X, class Diag, class OffDiag> typedef Array<X> LinearizeInterfaceJump< X, Diag, OffDiag >::XArray
Definition at line 31 of file LinearizeInterfaceJump.h.
Constructor & Destructor Documentation
template<class X, class Diag, class OffDiag> LinearizeInterfaceJump< X, Diag, OffDiag >::LinearizeInterfaceJump (const T_Scalar A_coeff, const X B_coeff, Field & varField) inline
Definition at line 37 of file LinearizeInterfaceJump.h.
                                            :
     _varField(varField),
     _A_coeff(A_coeff),
     _B_coeff(B_coeff)
     {}
Member Function Documentation
template<class X, class Diag, class OffDiag> void LinearizeInterfaceJump< X, Diag, OffDiag >::discretize (const Mesh & mesh, const Mesh & parentMesh, const Mesh & otherMesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline
Definition at line 46 of file LinearizeInterfaceJump.h.
References LinearizeInterfaceJump< X, Diag, OffDiag >::_A_coeff, LinearizeInterfaceJump< X, Diag, OffDiag >::_B_coeff, LinearizeInterfaceJump< X, Diag, OffDiag >::_varField, Mesh::getCellCells(), Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::getCoeff(), StorageSite::getCount(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), Mesh::getFaceCells(), MultiFieldMatrix::getMatrix(), Mesh::getOtherFaceGroupSite(), Mesh::getParentFaceGroupSite(), and StorageSite::getSelfCount().
Referenced by SpeciesModel< T >::Impl::linearize(), ElectricModel< T >::Impl::linearizeElectroStatics(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), and BatteryModel< T >::Impl::linearizeThermal().
   {
     const StorageSite& cells = mesh.getCells();
     const StorageSite& faces = mesh.getParentFaceGroupSite();
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     const XArray& xCell = dynamic_cast<const XArray&>(xField[cVarIndex]);
     const CRConnectivity& cellCells = mesh.getCellCells();
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     DiagArray& diag = matrix.getDiag();
     // In the following, parent is assumed to be on the left, and
     // the other mesh is assumed to be on the right when implimenting
     // the (Phi_R = A*Phi_L + B) equation
     // parent mesh info
     const CRConnectivity& parentFaceCells = parentMesh.getFaceCells(faces);
     const StorageSite& parentCells = parentMesh.getCells();
     const MultiField::ArrayIndex cVarIndexParent(&_varField,&parentCells);
     XArray& rParentCell = dynamic_cast<XArray&>(rField[cVarIndexParent]);
     CCMatrix& parentmatrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndexParent,cVarIndexParent));
     DiagArray& parentdiag = parentmatrix.getDiag();
     // other mesh info
     const StorageSite& otherFaces = mesh.getOtherFaceGroupSite();
     const CRConnectivity& otherFaceCells = otherMesh.getFaceCells(otherFaces);
     const StorageSite& otherCells = otherMesh.getCells();
     const MultiField::ArrayIndex cVarIndexOther(&_varField,&otherCells);
     XArray& rOtherCell = dynamic_cast<XArray&>(rField[cVarIndexOther]);
     CCMatrix& othermatrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndexOther,cVarIndexOther));
     DiagArray& otherdiag = othermatrix.getDiag();
     for (int f=0; f<faces.getCount(); f++)
     {
        //get parent mesh fluxes and coeffs
        int c0p = parentFaceCells(f,0);
        int c1p = parentFaceCells(f,1);
        if (c1p < parentCells.getSelfCount())
        {
          // c0 is ghost cell and c1 is boundry cell, so swap cell numbers
          // so that c1p refers to the ghost cell in the following
          int temp = c0p;
          c0p = c1p;
          c1p = temp;
          }
        const X leftFlux = rParentCell[c1p]; // inward shell flux on the left
        const OffDiag dRC0dXC3 = parentmatrix.getCoeff(c1p,  c0p);
        const Diag dRC0dXC0 = parentdiag[c1p];
        //get other mesh fluxes and coeffs
        int c0o = otherFaceCells(f,0);
        int c1o = otherFaceCells(f,1);
        if (c1o < otherCells.getSelfCount())
        {
          // c0 is ghost cell and c1 is boundry cell, so swap cell numbers
          // so that c1o refers to the ghost cell in the following
          int temp = c0o;
          c0o = c1o;
          c1o = temp;
          }
        const X rightFlux = rOtherCell[c1o]; // inward shell flux on the right
        const OffDiag dRC0dXC2 = othermatrix.getCoeff(c1o,  c0o);
        const OffDiag dRC0dXC1 = otherdiag[c1o];
        //now put flux information from meshes into shell cells
        const int c0 = f;
        const int c1 = cellCells(f,0);
        const int c2 = cellCells(f,1);
        const int c3 = cellCells(f,2);
        // left shell cell - 3 neighbors
        OffDiag& offdiagC0_C1 = matrix.getCoeff(c0,  c1);
        OffDiag& offdiagC0_C2 = matrix.getCoeff(c0,  c2);
        OffDiag& offdiagC0_C3 = matrix.getCoeff(c0,  c3);
        rCell[c0] = rightFlux + leftFlux;
        offdiagC0_C1 = dRC0dXC1;
        offdiagC0_C3 = dRC0dXC3;
        offdiagC0_C2 = dRC0dXC2;
        diag[c0] = dRC0dXC0;
        // right shell cell - 1 neighbor
        OffDiag& offdiagC1_C0 = matrix.getCoeff(c1,  c0);
        rCell[c1] = _A_coeff*xCell[c0] + _B_coeff - xCell[c1];
        offdiagC1_C0 = _A_coeff*NumTypeTraits<OffDiag>::getUnity();
        diag[c1] = NumTypeTraits<Diag>::getNegativeUnity();
        // set other coeffs to zero for right shell cell
        OffDiag& offdiagC1_C2 = matrix.getCoeff(c1,  c2);
        OffDiag& offdiagC1_C3 = matrix.getCoeff(c1,  c3);
        offdiagC1_C2 = NumTypeTraits<OffDiag>::getZero();
        offdiagC1_C3 = NumTypeTraits<OffDiag>::getZero();
        if (c0==0)
          {
            cout << xCell[c0] << " " << xCell[c1] << " " << xCell[c2] << " " << xCell[c3] << endl;
          }
    }
   }
Member Data Documentation
template<class X, class Diag, class OffDiag> const T_Scalar LinearizeInterfaceJump< X, Diag, OffDiag >::_A_coeff private
Definition at line 161 of file LinearizeInterfaceJump.h.
Referenced by LinearizeInterfaceJump< X, Diag, OffDiag >::discretize().
template<class X, class Diag, class OffDiag> const X LinearizeInterfaceJump< X, Diag, OffDiag >::_B_coeff private
Definition at line 162 of file LinearizeInterfaceJump.h.
Referenced by LinearizeInterfaceJump< X, Diag, OffDiag >::discretize().
template<class X, class Diag, class OffDiag> Field& LinearizeInterfaceJump< X, Diag, OffDiag >::_varField private
Definition at line 160 of file LinearizeInterfaceJump.h.
Referenced by LinearizeInterfaceJump< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
LinearizeInterfaceJump.h