Memosa-FVM: SpikeStorage Class Reference
SpikeStorage Class Reference
#include <SpikeStorage.h>
Public Member Functions
SpikeStorage (const CRConnectivity &conn, int semi_bandwidth)
~SpikeStorage ()
const vector< int > & getLSPKInterior () const
const vector< int > & getRSPKInterior () const
const vector< int > & getLSPKGhost () const
const vector< int > & getRSPKGhost () const
const vector< int > & getLSPKOffDiagPtr () const
const vector< int > & getRSPKOffDiagPtr () const
const vector< int > & getLSPKIndexI () const
const vector< int > & getLSPKIndexJ () const
const vector< int > & getRSPKIndexI () const
const vector< int > & getRSPKIndexJ () const
const vector< int > & getLSPKCountGhost () const
const vector< int > & getRSPKCountGhost () const
int getBandWidth () const
Private Member Functions
void init ()
void gatherCellSizes ()
void syncCellIDs ()
void setGlobalIndices ()
void setOffDiagPtr ()
Private Attributes
const CRConnectivity & _conn
int _bandwidth
int _procID
int _localCellSelfCount
map< int, int > _ghostMap
vector< int > _cellSelfCounts
vector< int > _LSPK_INTERIOR
vector< int > _LSPK_GHOST
vector< int > _LSPK_OFFD_PTR
vector< int > _RSPK_INTERIOR
vector< int > _RSPK_GHOST
vector< int > _RSPK_OFFD_PTR
vector< int > _LSPK_I
vector< int > _LSPK_J
vector< int > _RSPK_I
vector< int > _RSPK_J
vector< int > _glblIndices
vector< int > _LSPKCountGhost
vector< int > _RSPKCountGhost
Detailed Description
Definition at line 15 of file SpikeStorage.h.
Constructor & Destructor Documentation
SpikeStorage::SpikeStorage (const CRConnectivity & conn, int semi_bandwidth)
Definition at line 17 of file SpikeStorage.cpp.
References init().
                                                                         :
 _conn(conn), _bandwidth(semi_bandwidth)
 {
         //logCtor();
   init();
 }
SpikeStorage::~SpikeStorage ()
Definition at line 25 of file SpikeStorage.cpp.
 {
         //logDtor();
 }
Member Function Documentation
void SpikeStorage::gatherCellSizes () private
Definition at line 67 of file SpikeStorage.cpp.
References _cellSelfCounts, _conn, _localCellSelfCount, CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
Referenced by init().
 {
    const StorageSite& cellSite = _conn.getRowSite();
    _localCellSelfCount = cellSite.getSelfCount();
 #ifdef FVM_PARALLEL
    MPI::COMM_WORLD.Allgather(&_localCellSelfCount, 1, MPI::INT, &_cellSelfCounts[0], 1, MPI::INT);
 #endif
 }
int SpikeStorage::getBandWidth () const inline
Definition at line 39 of file SpikeStorage.h.
References _bandwidth.
 { return _bandwidth;}
const vector<int>& SpikeStorage::getLSPKCountGhost () const inline
Definition at line 36 of file SpikeStorage.h.
References _LSPKCountGhost.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLMtrx().
 { return _LSPKCountGhost;}
const vector<int>& SpikeStorage::getLSPKGhost () const inline
Definition at line 25 of file SpikeStorage.h.
References _LSPK_GHOST.
 {return _LSPK_GHOST;}
const vector<int>& SpikeStorage::getLSPKIndexI () const inline
Definition at line 31 of file SpikeStorage.h.
References _LSPK_I.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLMtrx().
 { return _LSPK_I;}
const vector<int>& SpikeStorage::getLSPKIndexJ () const inline
Definition at line 32 of file SpikeStorage.h.
References _LSPK_J.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLMtrx().
 { return _LSPK_J;}
const vector<int>& SpikeStorage::getLSPKInterior () const inline
Definition at line 22 of file SpikeStorage.h.
References _LSPK_INTERIOR.
 {return _LSPK_INTERIOR;}
const vector<int>& SpikeStorage::getLSPKOffDiagPtr () const inline
Definition at line 28 of file SpikeStorage.h.
References _LSPK_OFFD_PTR.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setLMtrx().
 {return _LSPK_OFFD_PTR;}
const vector<int>& SpikeStorage::getRSPKCountGhost () const inline
Definition at line 37 of file SpikeStorage.h.
References _RSPKCountGhost.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx().
 { return _RSPKCountGhost;}
const vector<int>& SpikeStorage::getRSPKGhost () const inline
Definition at line 26 of file SpikeStorage.h.
References _RSPK_GHOST.
 {return _RSPK_GHOST;}
const vector<int>& SpikeStorage::getRSPKIndexI () const inline
Definition at line 33 of file SpikeStorage.h.
References _RSPK_I.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx().
 { return _RSPK_I;}
const vector<int>& SpikeStorage::getRSPKIndexJ () const inline
Definition at line 34 of file SpikeStorage.h.
References _RSPK_J.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx().
 { return _RSPK_J;}
const vector<int>& SpikeStorage::getRSPKInterior () const inline
Definition at line 23 of file SpikeStorage.h.
References _RSPK_INTERIOR.
 {return _RSPK_INTERIOR;}
const vector<int>& SpikeStorage::getRSPKOffDiagPtr () const inline
Definition at line 29 of file SpikeStorage.h.
References _RSPK_OFFD_PTR.
Referenced by SpikeMatrix< T_Diag, T_OffDiag, X >::setRMtrx().
 {return _RSPK_OFFD_PTR;}
void SpikeStorage::init () private
Definition at line 32 of file SpikeStorage.cpp.
References _bandwidth, _cellSelfCounts, _conn, _LSPK_GHOST, _LSPK_I, _LSPK_INTERIOR, _LSPK_J, _LSPK_OFFD_PTR, _LSPKCountGhost, _procID, _RSPK_GHOST, _RSPK_I, _RSPK_INTERIOR, _RSPK_J, _RSPK_OFFD_PTR, _RSPKCountGhost, gatherCellSizes(), CRConnectivity::getRowSite(), StorageSite::getSelfCount(), setGlobalIndices(), setOffDiagPtr(), and syncCellIDs().
Referenced by SpikeStorage().
 {
    //reserve minumum space for data structures
    _LSPK_INTERIOR.reserve(_bandwidth);
    _LSPK_GHOST.reserve   (_bandwidth);
    _LSPK_OFFD_PTR.reserve(_bandwidth);
    _RSPK_INTERIOR.reserve(_bandwidth);
    _RSPK_GHOST.reserve   (_bandwidth);
    _RSPK_OFFD_PTR.reserve(_bandwidth);
    _LSPK_I.reserve(_bandwidth);
    _LSPK_J.reserve(_bandwidth);
    _RSPK_I.reserve(_bandwidth);
    _RSPK_J.reserve(_bandwidth);
    //keeping left and right spike matrices counter, we will know if there is more than one ghost cell
     int ncells = _conn.getRowSite().getSelfCount();
    _LSPKCountGhost.resize(ncells,0);
    _RSPKCountGhost.resize(ncells,0);
 #ifdef FVM_PARALLEL
    _cellSelfCounts.resize( MPI::COMM_WORLD.Get_size() );
    _procID = MPI::COMM_WORLD.Get_rank();
 #endif
    //get size of cells from other process
    gatherCellSizes();
    //syn operation to get neighbour local indices to this ghost cells
    syncCellIDs();
    //create local array to store global indices
    setGlobalIndices();
    //spk_offd_ptr
    setOffDiagPtr();
 }
void SpikeStorage::setGlobalIndices () private
Definition at line 109 of file SpikeStorage.cpp.
References _bandwidth, _cellSelfCounts, _conn, _ghostMap, _LSPK_GHOST, _LSPK_I, _LSPK_INTERIOR, _LSPK_J, _LSPKCountGhost, _procID, _RSPK_GHOST, _RSPK_I, _RSPK_INTERIOR, _RSPK_J, _RSPKCountGhost, StorageSite::getGatherMap(), StorageSite::getGatherProcID(), Array< T >::getLength(), and CRConnectivity::getRowSite().
Referenced by init().
 {
   int indx_base = 0;
   for ( int i = 1; i <= _procID; i++)
      indx_base += _cellSelfCounts[i-1];
   const StorageSite& cellSite = _conn.getRowSite();
   const StorageSite::GatherMap& gatherMap = cellSite.getGatherMap();
   //loop over gather maps
   foreach( const StorageSite::GatherMap::value_type& mpos, gatherMap ){
      const StorageSite& oSite = *mpos.first;
      const int oRank = oSite.getGatherProcID();
      const Array<int>& ghostIndices = *(mpos.second);
      //get inner indices
      Array<int> innerIndices( ghostIndices.getLength() );
      for ( int n = 0; n < ghostIndices.getLength(); n++ ){
          innerIndices[n] = _conn( ghostIndices[n], 0 );
      }
      //finding base for neighbour
      int indx_base_other = 0;
      for (  int i = 1; i <= oRank; i++)
          indx_base_other += _cellSelfCounts[i-1];
      //check
      for ( int n = 0; n < ghostIndices.getLength(); n++ ){
          const int iGlbIndx = indx_base + innerIndices[n];
          const int jGlbIndx = indx_base_other + _ghostMap[ ghostIndices[n] ];
          //check left or right
          if ( (iGlbIndx > jGlbIndx) && ((iGlbIndx - jGlbIndx) <= _bandwidth) ){
             _LSPK_INTERIOR.push_back( innerIndices[n] );
             _LSPK_GHOST.push_back   ( ghostIndices[n] );
             _LSPK_I.push_back( innerIndices[n] );
             _LSPK_J.push_back( _bandwidth + jGlbIndx - indx_base );
             _LSPKCountGhost[innerIndices[n]] += 1;
          } else if ( (iGlbIndx < jGlbIndx) && (jGlbIndx - iGlbIndx) <= _bandwidth ) {
             _RSPK_INTERIOR.push_back( innerIndices[n] );
             _RSPK_GHOST.push_back   ( ghostIndices[n] );
             _RSPK_I.push_back( innerIndices[n] );
             _RSPK_J.push_back( jGlbIndx - indx_base_other );
             _RSPKCountGhost[innerIndices[n]] += 1;
          }
      }
   }
 }
void SpikeStorage::setOffDiagPtr () private
Definition at line 156 of file SpikeStorage.cpp.
References _conn, _LSPK_GHOST, _LSPK_INTERIOR, _LSPK_OFFD_PTR, _RSPK_GHOST, _RSPK_INTERIOR, _RSPK_OFFD_PTR, CRConnectivity::getCol(), and CRConnectivity::getRow().
Referenced by init().
 {
     //loop over LSPK
     const Array<int>& row = _conn.getRow();
     const Array<int>& col = _conn.getCol();
     for( unsigned int i = 0; i < _LSPK_INTERIOR.size(); i++ ){
         const int rowIndx = _LSPK_INTERIOR[i];
         for ( int j = row[rowIndx]; j < row[rowIndx+1]; j++ ){
            const int neighCellID = col[j];
            if ( neighCellID == _LSPK_GHOST[i] )
               _LSPK_OFFD_PTR.push_back( j );
         }
     }
     //loop over RSPK
     for( unsigned int i = 0; i < _RSPK_INTERIOR.size(); i++ ){
         const int rowIndx = _RSPK_INTERIOR[i];
         for ( int j = row[rowIndx]; j < row[rowIndx+1]; j++ ){
            const int neighCellID = col[j];
            if ( neighCellID == _RSPK_GHOST[i] )
               _RSPK_OFFD_PTR.push_back( j );
         }
     }
 }
void SpikeStorage::syncCellIDs () private
Definition at line 77 of file SpikeStorage.cpp.
References _conn, _ghostMap, StorageSite::getCount(), CRConnectivity::getRowSite(), StorageSite::getSelfCount(), and Array< T >::zero().
Referenced by init().
 {
    shared_ptr<Field> cellIndicesField( new Field("cellID") );
    const StorageSite& cells = _conn.getRowSite();
    const int cellCount = cells.getCount();
    shared_ptr< Array<int> > indPtr( new Array<int>(cellCount) );
    Array<int>& indices = *indPtr;
    Array<int>  indicesOld( cellCount ); //keep original indices
    //zeroing
    indices.zero();
    //filling indices
    for ( int n = 0; n < cells.getCount(); n++ ){
        indices[n] = n;
        indicesOld[n] = n;
    }
    //volume add
    cellIndicesField->addArray(cells, indPtr);
    //synLocal to get neighbourhood
    cellIndicesField->syncLocal();
    //create mapping between old and new ghost ids
    int ibeg = cells.getSelfCount();
    int iend = cells.getCount();
    for ( int i = ibeg; i < iend; i++ ){
        _ghostMap[ indicesOld[i] ] = indices[i];
    }
 }
Member Data Documentation
int SpikeStorage::_bandwidth private
Definition at line 50 of file SpikeStorage.h.
Referenced by getBandWidth(), init(), and setGlobalIndices().
vector<int> SpikeStorage::_cellSelfCounts private
Definition at line 56 of file SpikeStorage.h.
Referenced by gatherCellSizes(), init(), and setGlobalIndices().
const CRConnectivity& SpikeStorage::_conn private
Definition at line 49 of file SpikeStorage.h.
Referenced by gatherCellSizes(), init(), setGlobalIndices(), setOffDiagPtr(), and syncCellIDs().
map<int,int> SpikeStorage::_ghostMap private
Definition at line 54 of file SpikeStorage.h.
Referenced by setGlobalIndices(), and syncCellIDs().
vector<int> SpikeStorage::_glblIndices private
Definition at line 67 of file SpikeStorage.h.
int SpikeStorage::_localCellSelfCount private
Definition at line 53 of file SpikeStorage.h.
Referenced by gatherCellSizes().
vector<int> SpikeStorage::_LSPK_GHOST private
Definition at line 58 of file SpikeStorage.h.
Referenced by getLSPKGhost(), init(), setGlobalIndices(), and setOffDiagPtr().
vector<int> SpikeStorage::_LSPK_I private
Definition at line 63 of file SpikeStorage.h.
Referenced by getLSPKIndexI(), init(), and setGlobalIndices().
vector<int> SpikeStorage::_LSPK_INTERIOR private
Definition at line 57 of file SpikeStorage.h.
Referenced by getLSPKInterior(), init(), setGlobalIndices(), and setOffDiagPtr().
vector<int> SpikeStorage::_LSPK_J private
Definition at line 64 of file SpikeStorage.h.
Referenced by getLSPKIndexJ(), init(), and setGlobalIndices().
vector<int> SpikeStorage::_LSPK_OFFD_PTR private
Definition at line 59 of file SpikeStorage.h.
Referenced by getLSPKOffDiagPtr(), init(), and setOffDiagPtr().
vector<int> SpikeStorage::_LSPKCountGhost private
Definition at line 68 of file SpikeStorage.h.
Referenced by getLSPKCountGhost(), init(), and setGlobalIndices().
int SpikeStorage::_procID private
Definition at line 52 of file SpikeStorage.h.
Referenced by init(), and setGlobalIndices().
vector<int> SpikeStorage::_RSPK_GHOST private
Definition at line 61 of file SpikeStorage.h.
Referenced by getRSPKGhost(), init(), setGlobalIndices(), and setOffDiagPtr().
vector<int> SpikeStorage::_RSPK_I private
Definition at line 65 of file SpikeStorage.h.
Referenced by getRSPKIndexI(), init(), and setGlobalIndices().
vector<int> SpikeStorage::_RSPK_INTERIOR private
Definition at line 60 of file SpikeStorage.h.
Referenced by getRSPKInterior(), init(), setGlobalIndices(), and setOffDiagPtr().
vector<int> SpikeStorage::_RSPK_J private
Definition at line 66 of file SpikeStorage.h.
Referenced by getRSPKIndexJ(), init(), and setGlobalIndices().
vector<int> SpikeStorage::_RSPK_OFFD_PTR private
Definition at line 62 of file SpikeStorage.h.
Referenced by getRSPKOffDiagPtr(), init(), and setOffDiagPtr().
vector<int> SpikeStorage::_RSPKCountGhost private
Definition at line 69 of file SpikeStorage.h.
Referenced by getRSPKCountGhost(), init(), and setGlobalIndices().
The documentation for this class was generated from the following files:
SpikeStorage.h
SpikeStorage.cpp