Memosa-FVM: KSearchTree Class Reference
KSearchTree Class Reference
#include <KSearchTree.h>
Public Types
typedef Vector< double, 3 > Vec3D
typedef Array< Vec3D > Vec3DArray
typedef Array< int > IntArray
Public Member Functions
KSearchTree ()
KSearchTree (const Vec3DArray &points)
void insert (const Vec3D &v, const int n)
void findNeighbors (const Vec3D &p, const int k, Array< int > &neighbors)
Private Types
typedef CGAL::Search_traits
< double, MyPoint, const
double
*, Construct_coord_iterator > Traits
typedef
CGAL::Orthogonal_k_neighbor_search
< Traits > K_neighbor_search
typedef K_neighbor_search::Tree Tree
Private Attributes
boost::shared_ptr< Tree > _tree
Detailed Description
A wrapper for CGAL's K_neighbor_search
Definition at line 121 of file KSearchTree.h.
Member Typedef Documentation
typedef Array<int> KSearchTree::IntArray
Definition at line 126 of file KSearchTree.h.
typedef CGAL::Orthogonal_k_neighbor_search<Traits> KSearchTree::K_neighbor_search private
Definition at line 139 of file KSearchTree.h.
typedef CGAL::Search_traits<double, MyPoint, const double*, Construct_coord_iterator> KSearchTree::Traits private
Definition at line 138 of file KSearchTree.h.
typedef K_neighbor_search::Tree KSearchTree::Tree private
Definition at line 140 of file KSearchTree.h.
typedef Vector<double,3> KSearchTree::Vec3D
Definition at line 124 of file KSearchTree.h.
typedef Array<Vec3D> KSearchTree::Vec3DArray
Definition at line 125 of file KSearchTree.h.
Constructor & Destructor Documentation
KSearchTree::KSearchTree ()
Definition at line 17 of file KSearchTree.cpp.
References _tree.
 {
   _tree = boost::shared_ptr<Tree>(new Tree());
 }
KSearchTree::KSearchTree (const Vec3DArray & points)
Definition at line 8 of file KSearchTree.cpp.
References _tree, and Array< T >::getLength().
 {
   _tree = boost::shared_ptr<Tree>(new Tree());
   const int nPoints = points.getLength();
   for(int n=0; n<nPoints; n++)
     _tree->insert(MyPoint(points[n],n));
 }
Member Function Documentation
void KSearchTree::findNeighbors (const Vec3D & p, const int k, Array< int > & neighbors)
Definition at line 30 of file KSearchTree.cpp.
References _tree.
Referenced by IBManager::createIBInterpolationStencil(), IBManager::createSolidInterpolationStencil(), Mesh::findCommonNodes(), and IBManager::findNearestCellForSolidFaces().
 {
   MyPoint query(p, -1);
   if ( _tree->size() == 0 ){
      return;
   }
   K_neighbor_search search(*_tree, query, k);
   int i=0;
   for(K_neighbor_search::iterator it = search.begin();
       it != search.end();
       it++)
   {
       neighbors[i++] = it->first.index;
   }
 }
void KSearchTree::insert (const Vec3D & v, const int n)
Definition at line 23 of file KSearchTree.cpp.
References _tree.
Referenced by IBManager::createIBInterpolationStencil(), IBManager::createSolidInterpolationStencil(), Mesh::findCommonNodes(), and IBManager::update().
 {
   _tree->insert(MyPoint(v,n));
 }
Member Data Documentation
boost::shared_ptr<Tree> KSearchTree::_tree private
Definition at line 142 of file KSearchTree.h.
Referenced by findNeighbors(), insert(), and KSearchTree().
The documentation for this class was generated from the following files:
KSearchTree.h
KSearchTree.cpp