Memosa-FVM: Field Class Reference
Field Class Reference
#include <Field.h>
Public Types
typedef map< const StorageSite
*, shared_ptr< ArrayBase > > ArrayMap
typedef map< const StorageSite
*, vector< const StorageSite * > * > ChildSitesMap
typedef pair< const
StorageSite *, const
StorageSite * > EntryIndex
typedef map< EntryIndex,
shared_ptr< ArrayBase > > GhostArrayMap
Public Member Functions
Field (const string &name)
virtual ~Field ()
DEFINE_TYPENAME ("Field")
Field & operator= (const Field &oField)
const ArrayBase & operator[] (const StorageSite &) const
ArrayBase & operator[] (const StorageSite &)
shared_ptr< ArrayBase > getArrayPtr (const StorageSite &)
void addArray (const StorageSite &, shared_ptr< ArrayBase > a)
void removeArray (const StorageSite &)
void removeArrays (const StorageSiteList &sites)
virtual void copyFrom (const IContainer &a)
virtual void zero ()
virtual shared_ptr< IContainer > newCopy () const
virtual shared_ptr< IContainer > newClone () const
bool hasArray (const StorageSite &s) const
void syncLocal ()
ArrayMap & getArrayMap ()
GhostArrayMap & getGhostArrayMap ()
GhostArrayMap & getGhostArrayMapLevel1 ()
const string getName () const
void clear ()
Public Member Functions inherited from IContainer
IContainer ()
virtual ~IContainer ()
IContainer & operator= (const IContainer &oc)
Static Public Member Functions
static void syncLocalVectorFields (std::vector< Field * > &dsf)
Private Member Functions
Field (const Field &)
void createSyncGatherArrays (const StorageSite &site)
void syncScatter (const StorageSite &site)
void syncGather (const StorageSite &site)
void createSyncGatherArraysLevel1 (const StorageSite &site)
void syncScatterLevel1 (const StorageSite &site)
void syncGatherLevel1 (const StorageSite &site)
int get_request_size ()
int get_request_size_scatter_level1 ()
int get_request_size_gather_level1 ()
void syncLocalLevel1 ()
ArrayBase & _create (const StorageSite &site)
Static Private Member Functions
static void createSyncGatherArraysVectorFields (const StorageSite &site, Field &field, const size_t numDir)
static void syncScatterVectorFields (const StorageSite &site, std::vector< Field * > &dsf)
static void syncGatherVectorFields (const StorageSite &site, std::vector< Field * > &dsf)
static void createSyncGatherArraysVectorFieldsLevel1 (const StorageSite &site, Field &field, const size_t numDir)
static void syncScatterVectorFieldsLevel1 (const StorageSite &site, std::vector< Field * > &dsf)
static void syncGatherVectorFieldsLevel1 (const StorageSite &site, std::vector< Field * > &dsf)
static int get_request_size (Field &field)
static int get_request_size_level1 (Field &field)
static void syncLocalVectorFieldsLevel1 (std::vector< Field * > &dsf)
Private Attributes
const string _name
ArrayMap _arrays
GhostArrayMap _ghostArrays
GhostArrayMap _ghostArraysLevel1
ChildSitesMap _childSitesMap
Detailed Description
Definition at line 14 of file Field.h.
Member Typedef Documentation
typedef map<const StorageSite*, shared_ptr<ArrayBase> > Field::ArrayMap
Definition at line 17 of file Field.h.
typedef map<const StorageSite*, vector<const StorageSite*>* > Field::ChildSitesMap
Definition at line 18 of file Field.h.
typedef pair<const StorageSite*, const StorageSite*> Field::EntryIndex
Definition at line 19 of file Field.h.
typedef map<EntryIndex, shared_ptr<ArrayBase> > Field::GhostArrayMap
Definition at line 20 of file Field.h.
Constructor & Destructor Documentation
Field::Field (const string & name)
Definition at line 22 of file Field.cpp.
References logCtor.
Referenced by newClone(), and newCopy().
                               :
   IContainer(),
   _name(name),
   _arrays()
 {
   logCtor();
 }
Field::~Field () virtual
Definition at line 30 of file Field.cpp.
References logDtor.
 {
   logDtor();
 }
Field::Field (const Field &) private
Member Function Documentation
ArrayBase & Field::_create (const StorageSite & site) private
Definition at line 114 of file Field.cpp.
References _arrays, _childSitesMap, ArrayBase::createOffsetArray(), StorageSite::getCount(), StorageSite::getOffset(), StorageSite::getParent(), and operator[]().
Referenced by getArrayPtr(), and operator[]().
 {
   const StorageSite* parentSite = s.getParent();
   if (parentSite)
   {
       ArrayBase& parentArray = operator[](*parentSite);
       shared_ptr<ArrayBase> anew = parentArray.createOffsetArray(s.getOffset(),
                                                                  s.getCount());
       _arrays[&s]=anew;
       if (_childSitesMap.find(parentSite) == _childSitesMap.end())
         _childSitesMap[parentSite] = new vector<const StorageSite*>();
       vector<const StorageSite*>& childSites = *_childSitesMap[parentSite];
       childSites.push_back(&s);
       return *anew;
   }
   else
   {
       ostringstream e;
       e << "Field::operator[] No array found and no creator defined for "
         << &s << endl;
       throw CException(e.str());
   }
 }
void Field::addArray (const StorageSite & s, shared_ptr< ArrayBase > a)
Definition at line 72 of file Field.cpp.
References _arrays, and removeArray().
Referenced by GradientModel< Vector< T, 3 > >::compute(), COMETModel< T >::ComputeCoarseMacroparameters(), COMETModel< T >::ComputeFineMacroparameters(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), KineticModel< T >::computeSolidFacePressure(), COMETModel< T >::computeSolidFacePressure(), KineticModel< T >::computeSurfaceForce(), COMETModel< T >::computeSurfaceForce(), KineticModel< T >::ConservationofMFSolid(), DistFunctFields< X >::DistFunctFields(), COMETModel< T >::FinishCoarseMesh(), Grid::Grid(), SpeciesModel< T >::Impl::init(), PhononModel< T >::init(), KineticModel< T >::init(), BatteryModel< T >::Impl::init(), COMETModel< T >::init(), PlateDeformationModel< T >::init(), StructureDeformationModel< T >::init(), MovingMeshModel< T >::init(), COMETModel< T >::initCoarse(), COMETModel< T >::makeCellColors(), COMETModel< T >::MakeCoarseIndex(), COMETModel< T >::MakeCoarseMesh2(), COMETModel< T >::MakeIBCoarseModel(), COMETModel< T >::makePlotColors(), StructureDeformationModel< T >::updateBoundaryMesh(), PlateDeformationModel< T >::updateBoundaryMesh(), PhononModel< T >::updateHeatFlux(), and VTKWriter< T >::VTKWriter().
 {
   removeArray(s);
   _arrays[&s]=a;
 }
void Field::clear ()
Definition at line 105 of file Field.cpp.
References _arrays, _childSitesMap, _ghostArrays, and _ghostArraysLevel1.
 {
   _arrays.clear();
   _childSitesMap.clear();
   _ghostArrays.clear();
   _ghostArraysLevel1.clear();
 }
void Field::copyFrom (const IContainer & a) virtual
Implements IContainer.
Definition at line 187 of file Field.cpp.
References operator=().
 {
   const Field& other = dynamic_cast<const Field&>(oc);
   operator=(other);
 }
void Field::createSyncGatherArrays (const StorageSite & site) private
Definition at line 195 of file Field.cpp.
References _ghostArrays, StorageSite::getGatherMap(), Array< T >::getLength(), ArrayBase::newSizedClone(), and operator[]().
Referenced by syncLocal().
 {
   ArrayBase& thisArray = operator[](site);
   const StorageSite::GatherMap& gatherMap = site.getGatherMap();
   foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
   {
       const StorageSite& oSite = *mpos.first;
       EntryIndex e(&oSite, &site);
       const Array<int>& toIndices = *(mpos.second);
       if (_ghostArrays.find(e) == _ghostArrays.end())
       {
           _ghostArrays[e] = thisArray.newSizedClone(toIndices.getLength());
       }
   }
 }
void Field::createSyncGatherArraysLevel1 (const StorageSite & site) private
Definition at line 214 of file Field.cpp.
References _ghostArraysLevel1, StorageSite::getGatherMapLevel1(), Array< T >::getLength(), ArrayBase::newSizedClone(), and operator[]().
Referenced by syncLocalLevel1().
 {
   ArrayBase& thisArray = operator[](site);
   const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
   foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
   {
       const StorageSite& oSite = *mpos.first;
       EntryIndex e(&oSite, &site);
       const Array<int>& toIndices = *(mpos.second);
       if (_ghostArraysLevel1.find(e) == _ghostArraysLevel1.end())
       {
           _ghostArraysLevel1[e] = thisArray.newSizedClone(toIndices.getLength());
       }
   }
 }
void Field::createSyncGatherArraysVectorFields (const StorageSite & site, Field & field, const size_t numDir) static private
Definition at line 528 of file Field.cpp.
References StorageSite::getGatherMap(), getGhostArrayMap(), Array< T >::getLength(), and ArrayBase::newSizedClone().
Referenced by syncLocalVectorFields().
 {
   ArrayBase& thisArray = field[site];
   GhostArrayMap& ghostArrays = field.getGhostArrayMap();
   const StorageSite::GatherMap& gatherMap = site.getGatherMap();
   foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
   {
       const StorageSite& oSite = *mpos.first;
       EntryIndex e(&oSite, &site);
       const Array<int>& toIndices = *(mpos.second);
       if (ghostArrays.find(e) == ghostArrays.end())
       {
           ghostArrays[e] = thisArray.newSizedClone(toIndices.getLength() * numDir);
       }
   }
 }
void Field::createSyncGatherArraysVectorFieldsLevel1 (const StorageSite & site, Field & field, const size_t numDir) static private
Definition at line 548 of file Field.cpp.
References StorageSite::getGatherMapLevel1(), getGhostArrayMapLevel1(), Array< T >::getLength(), and ArrayBase::newSizedClone().
Referenced by syncLocalVectorFieldsLevel1().
 {
   ArrayBase& thisArray = field[site];
   GhostArrayMap& ghostArrays = field.getGhostArrayMapLevel1();
   const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
   foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
   {
       const StorageSite& oSite = *mpos.first;
       EntryIndex e(&oSite, &site);
       const Array<int>& toIndices = *(mpos.second);
       if (ghostArrays.find(e) == ghostArrays.end())
       {
           ghostArrays[e] = thisArray.newSizedClone(toIndices.getLength() * numDir);
       }
   }
 }
Field::DEFINE_TYPENAME ("Field")
int Field::get_request_size () private
Definition at line 397 of file Field.cpp.
References _arrays, StorageSite::getGatherProcID(), and StorageSite::getScatterMap().
Referenced by syncLocal(), and syncLocalVectorFields().
 {
    int indx =  0;
    foreach(ArrayMap::value_type& pos, _arrays){
       const StorageSite& site = *pos.first;
       const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
       foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
           const StorageSite&  oSite = *mpos.first;
           //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
           if ( oSite.getGatherProcID() != -1 )
              indx++;
       }
    }
    return indx;
 }
int Field::get_request_size (Field & field) static private
Definition at line 843 of file Field.cpp.
References getArrayMap(), StorageSite::getGatherProcID(), and StorageSite::getScatterMap().
 {
    ArrayMap& arrays = field.getArrayMap();
    int indx =  0;
    foreach(ArrayMap::value_type& pos, arrays){
       const StorageSite& site = *pos.first;
       const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
       foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
           const StorageSite&  oSite = *mpos.first;
           //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
           if ( oSite.getGatherProcID() != -1 )
              indx++;
       }
    }
    return indx;
 }
int Field::get_request_size_gather_level1 () private
Definition at line 506 of file Field.cpp.
References _arrays, StorageSite::getGatherMapLevel1(), and StorageSite::getGatherProcID().
Referenced by syncLocalLevel1().
 {
    int indx =  0;
    foreach(ArrayMap::value_type& pos, _arrays){
       const StorageSite& site = *pos.first;
       const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
       if ( pos.second->getLength() == pos.first->getCountLevel1() ){
          foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
             const StorageSite&  oSite = *mpos.first;
             //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
             if ( oSite.getGatherProcID() != -1 )
                indx++;
          }
       }
    }
    return indx;
 }
int Field::get_request_size_level1 (Field & field) static private
Definition at line 863 of file Field.cpp.
References getArrayMap(), StorageSite::getGatherProcID(), and StorageSite::getScatterMapLevel1().
Referenced by syncLocalVectorFieldsLevel1().
 {
    ArrayMap& arrays = field.getArrayMap();
    int indx =  0;
    foreach(ArrayMap::value_type& pos, arrays){
       const StorageSite& site = *pos.first;
       const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
       foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
           const StorageSite&  oSite = *mpos.first;
           //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
           if ( oSite.getGatherProcID() != -1 )
              indx++;
       }
    }
    return indx;
 }
int Field::get_request_size_scatter_level1 () private
Definition at line 486 of file Field.cpp.
References _arrays, StorageSite::getGatherProcID(), and StorageSite::getScatterMapLevel1().
Referenced by syncLocalLevel1().
 {
    int indx =  0;
    foreach(ArrayMap::value_type& pos, _arrays){
       const StorageSite& site = *pos.first;
       const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
       if ( pos.second->getLength() == pos.first->getCountLevel1() ){
          foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
             const StorageSite&  oSite = *mpos.first;
             //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
             if ( oSite.getGatherProcID() != -1 )
                indx++;
          }
       }
     }
    return indx;
 }
ArrayMap& Field::getArrayMap () inline
Definition at line 48 of file Field.h.
References _arrays.
Referenced by get_request_size(), get_request_size_level1(), syncLocalVectorFields(), and syncLocalVectorFieldsLevel1().
 { return _arrays;}
shared_ptr< ArrayBase > Field::getArrayPtr (const StorageSite & s)
Definition at line 63 of file Field.cpp.
References _arrays, and _create().
Referenced by FloatValEvaluator< T >::FloatValEvaluator(), FloatValEvaluator< Vector< T, 3 > >::FloatValEvaluator(), KineticModel< T >::initKineticModelLinearization(), SpeciesModel< T >::Impl::initLinearization(), PhononModel< T >::initPhononModelLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), and TractionValEvaluator< T >::TractionValEvaluator().
 {
   if (_arrays.find(&s) == _arrays.end())
     _create(s);
   return _arrays[&s];
 }
GhostArrayMap& Field::getGhostArrayMap () inline
Definition at line 50 of file Field.h.
References _ghostArrays.
Referenced by createSyncGatherArraysVectorFields(), syncGatherVectorFields(), syncLocalVectorFields(), and syncScatterVectorFields().
 { return _ghostArrays;}
GhostArrayMap& Field::getGhostArrayMapLevel1 () inline
Definition at line 51 of file Field.h.
References _ghostArraysLevel1.
Referenced by createSyncGatherArraysVectorFieldsLevel1(), syncGatherVectorFieldsLevel1(), syncLocalVectorFieldsLevel1(), and syncScatterVectorFieldsLevel1().
 { return _ghostArraysLevel1;}
const string Field::getName () const inline
Definition at line 57 of file Field.h.
References _name.
 {return _name;}
bool Field::hasArray (const StorageSite & s) const
Definition at line 37 of file Field.cpp.
References _arrays, and StorageSite::getParent().
Referenced by COMETESBGKDiscretizer< T >::COMETESBGKDiscretizer(), DriftDiscretization< X, Diag, OffDiag >::discretize(), TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCTimeDerivativeDiscretization< X, Diag, OffDiag >::discretize(), PhononConvectionDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization< X, Diag, OffDiag >::discretize(), TimeDerivativeStructureDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), TimeDerivativePlateDiscretization< X, Diag, OffDiag >::discretize(), TimeDerivativeStructureDiscretization< X, Diag, OffDiag >::explicitAdvance(), SpeciesModel< T >::Impl::linearize(), BatteryModel< T >::Impl::linearizeSpecies(), MovingMeshModel< T >::volChange(), FluentDataExporter< T >::writeScalarField(), and FluentDataExporter< T >::writeVectorField().
 {
   return ((_arrays.find(&s) != _arrays.end()) ||
           (s.getParent() && (_arrays.find(s.getParent()) != _arrays.end())));
 }
shared_ptr< IContainer > Field::newClone () const virtual
Implements IContainer.
Definition at line 141 of file Field.cpp.
References _arrays, _name, and Field().
 {
   shared_ptr<Field> c(new Field(_name));
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       c->addArray(*(pos.first),
                   dynamic_pointer_cast<ArrayBase>(pos.second->newClone()));
   }
   return c;
 }
shared_ptr< IContainer > Field::newCopy () const virtual
Implements IContainer.
Definition at line 155 of file Field.cpp.
References _arrays, _name, and Field().
 {
   shared_ptr<Field> c(new Field(_name));
   foreach(const ArrayMap::value_type& pos, _arrays)
   {
       c->addArray(*(pos.first),
                   dynamic_pointer_cast<ArrayBase>(pos.second->newCopy()));
   }
   return c;
 }
Field & Field::operator= (const Field & oField)
Definition at line 177 of file Field.cpp.
References _arrays.
Referenced by copyFrom().
 {
   foreach(ArrayMap::value_type& pos, _arrays)
   {
       *pos.second = oField[*pos.first];
   }
   return *this;
 }
const ArrayBase & Field::operator[] (const StorageSite & s) const
Definition at line 44 of file Field.cpp.
References _arrays.
Referenced by _create(), createSyncGatherArrays(), createSyncGatherArraysLevel1(), syncGather(), syncGatherLevel1(), syncScatter(), and syncScatterLevel1().
 {
   ArrayMap::const_iterator pos = _arrays.find(&s);
   if (pos != _arrays.end())
     return *pos->second;
   return const_cast<Field&>(*this)._create(s);
 }
ArrayBase & Field::operator[] (const StorageSite & s)
Definition at line 53 of file Field.cpp.
References _arrays, and _create().
 {
   ArrayMap::iterator pos = _arrays.find(&s);
   if (pos != _arrays.end())
     return *pos->second;
   return _create(s);
 }
void Field::removeArray (const StorageSite & s)
Definition at line 79 of file Field.cpp.
References _arrays, and _childSitesMap.
Referenced by addArray(), and removeArrays().
 {
   if (_childSitesMap.find(&s) != _childSitesMap.end())
   {
       vector<const StorageSite*>& childSites = *_childSitesMap[&s];
       foreach (const StorageSite* site,childSites)
       {
           removeArray(*site);
       }
       delete &childSites;
       _childSitesMap.erase(&s);
   }
   _arrays.erase(&s);
 }
void Field::removeArrays (const StorageSiteList & sites)
Definition at line 96 of file Field.cpp.
References removeArray().
 {
   foreach(const StorageSite* s, sites)
   {
       removeArray(*s);
   }
 }
void Field::syncGather (const StorageSite & site) private
Definition at line 280 of file Field.cpp.
References _ghostArrays, ArrayBase::gather(), StorageSite::getGatherMap(), and operator[]().
Referenced by syncLocal().
 {
   ArrayBase& thisArray = operator[](site);
   const StorageSite::GatherMap& gatherMap = site.getGatherMap();
   foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
   {
       const StorageSite& oSite = *mpos.first;
       const Array<int>& toIndices = *(mpos.second);
       EntryIndex e(&oSite, &site);
       if (_ghostArrays.find(e) == _ghostArrays.end())
       {
          ostringstream e;
          e << "Field::syncScatter: ghost array not found for"
            << &oSite << endl;
          throw CException(e.str());
       }
       const ArrayBase& ghostArray = *_ghostArrays[e];
       thisArray.gather(ghostArray,toIndices);
   }
 }
void Field::syncGatherLevel1 (const StorageSite & site) private
Definition at line 307 of file Field.cpp.
References _ghostArraysLevel1, ArrayBase::gather(), StorageSite::getGatherMapLevel1(), and operator[]().
Referenced by syncLocalLevel1().
 {
   ArrayBase& thisArray = operator[](site);
   const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
   foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
   {
       const StorageSite& oSite = *mpos.first;
       const Array<int>& toIndices = *(mpos.second);
       EntryIndex e(&oSite, &site);
       if (_ghostArraysLevel1.find(e) == _ghostArraysLevel1.end())
       {
          ostringstream e;
          e << "Field::syncScatter: ghost array not found for"
            << &oSite << endl;
          throw CException(e.str());
       }
       const ArrayBase& ghostArray = *_ghostArraysLevel1[e];
       thisArray.gather(ghostArray,toIndices);
   }
 }
void Field::syncGatherVectorFields (const StorageSite & site, std::vector< Field * > & dsf) static private
Definition at line 633 of file Field.cpp.
References ArrayBase::gather(), StorageSite::getGatherMap(), getGhostArrayMap(), and Array< T >::getLength().
Referenced by syncLocalVectorFields().
 {
   const size_t  numDir = dsf.size();
   Field& field0 = *dsf[0];
   GhostArrayMap& ghostArrays = field0.getGhostArrayMap();
   const StorageSite::GatherMap& gatherMap = site.getGatherMap();
   foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
   {
       const StorageSite& oSite = *mpos.first;
       const Array<int>& toIndices = *(mpos.second);
       EntryIndex e(&oSite, &site);
       if (ghostArrays.find(e) == ghostArrays.end())
       {
          ostringstream e;
          e << "Field::syncScatter: ghost array not found for"
            << &oSite << endl;
          throw CException(e.str());
       }
       const ArrayBase& ghostArray = *ghostArrays[e];
       const int chunkSize = toIndices.getLength();
       for (size_t dir = 0; dir < numDir; dir++){
          Field& field = *dsf[dir];
          ArrayBase& thisArray = field[site];
          const size_t offset = dir * chunkSize;
          thisArray.gather(ghostArray,toIndices, offset);
      }
   }
 }
void Field::syncGatherVectorFieldsLevel1 (const StorageSite & site, std::vector< Field * > & dsf) static private
Definition at line 668 of file Field.cpp.
References ArrayBase::gather(), StorageSite::getGatherMapLevel1(), getGhostArrayMapLevel1(), and Array< T >::getLength().
Referenced by syncLocalVectorFieldsLevel1().
 {
   const size_t  numDir = dsf.size();
   Field& field0 = *dsf[0];
   GhostArrayMap& ghostArrays = field0.getGhostArrayMapLevel1();
   const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
   foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
   {
       const StorageSite& oSite = *mpos.first;
       const Array<int>& toIndices = *(mpos.second);
       EntryIndex e(&oSite, &site);
       if (ghostArrays.find(e) == ghostArrays.end())
       {
          ostringstream e;
          e << "Field::syncScatter: ghost array not found for"
            << &oSite << endl;
          throw CException(e.str());
       }
       const ArrayBase& ghostArray = *ghostArrays[e];
       const int chunkSize = toIndices.getLength();
       for (size_t dir = 0; dir < numDir; dir++){
          Field& field = *dsf[dir];
          ArrayBase& thisArray = field[site];
          const size_t offset = dir * chunkSize;
          thisArray.gather(ghostArray,toIndices, offset);
      }
   }
 }
void Field::syncLocal ()
Definition at line 334 of file Field.cpp.
References _arrays, _ghostArrays, createSyncGatherArrays(), get_request_size(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMap(), StorageSite::getGatherProcID(), StorageSite::getScatterMap(), StorageSite::getTag(), syncGather(), syncLocalLevel1(), and syncScatter().
Referenced by GradientModel< Vector< T, 3 > >::compute(), SpeciesModel< T >::Impl::init(), BatteryModel< T >::Impl::init(), COMETModel< T >::init(), BatteryModel< T >::Impl::linearizeSpecies(), COMETModel< T >::MakeCoarseModel(), COMETModel< T >::MakeIBCoarseModel(), COMETModel< T >::MakeParallel(), and IBManager::update().
 {
    // scatter first (prepare ship packages)
    foreach(ArrayMap::value_type& pos, _arrays)
       syncScatter(*pos.first);
    foreach(ArrayMap::value_type& pos, _arrays)
       createSyncGatherArrays(*pos.first);
 #ifdef FVM_PARALLEL
    //SENDING
    MPI::Request   request_send[ get_request_size() ];
    MPI::Request   request_recv[ get_request_size() ];
    int indxSend = 0;
    int indxRecv = 0;
    foreach(ArrayMap::value_type& pos, _arrays){
       const StorageSite& site = *pos.first;
       const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
       foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
           const StorageSite&  oSite = *mpos.first;
           //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              EntryIndex e(&site,&oSite);
              ArrayBase& sendArray = *_ghostArrays[e];
              int to_where  = oSite.getGatherProcID();
              if ( to_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_send[indxSend++] =
                      MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
              }
       }
       //RECIEVING
       //getting values from other meshes to fill g
       const StorageSite::GatherMap& gatherMap = site.getGatherMap();
       foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
          const StorageSite&  oSite = *mpos.first;
          //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
          EntryIndex e(&oSite,&site);
          ArrayBase& recvArray = *_ghostArrays[e];
          int from_where       = oSite.getGatherProcID();
          if ( from_where != -1 ){
              int mpi_tag = oSite.getTag();
              request_recv[indxRecv++] =
                     MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
          }
       }
    }
    int count  = get_request_size();
    MPI::Request::Waitall( count, request_recv );
    MPI::Request::Waitall( count, request_send );
 #endif
   // gather
   foreach(ArrayMap::value_type& pos, _arrays)
     syncGather(*pos.first);
    //sycnLocal1
    syncLocalLevel1();
 }
void Field::syncLocalLevel1 () private
Definition at line 417 of file Field.cpp.
References _arrays, _ghostArraysLevel1, createSyncGatherArraysLevel1(), get_request_size_gather_level1(), get_request_size_scatter_level1(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), StorageSite::getScatterMapLevel1(), StorageSite::getTag(), syncGatherLevel1(), and syncScatterLevel1().
Referenced by syncLocal().
 {
    // scatter first (prepare ship packages)
    foreach(ArrayMap::value_type& pos, _arrays){
       if ( pos.second->getLength() == pos.first->getCountLevel1() )
          syncScatterLevel1(*pos.first);
   }
    foreach(ArrayMap::value_type& pos, _arrays){
       if ( pos.second->getLength() == pos.first->getCountLevel1() )
          createSyncGatherArraysLevel1(*pos.first);
    }
 #ifdef FVM_PARALLEL
    //SENDING
    int countScatter   = get_request_size_scatter_level1();
    int countGather    = get_request_size_gather_level1();
    MPI::Request   request_send[ countScatter ];
    MPI::Request   request_recv[ countGather  ];
    int indxSend = 0;
    int indxRecv = 0;
    foreach(ArrayMap::value_type& pos, _arrays){
       const StorageSite& site = *pos.first;
       if ( pos.second->getLength() == pos.first->getCountLevel1() ){
          const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
          foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
              const StorageSite&  oSite = *mpos.first;
              //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              EntryIndex e(&site,&oSite);
              ArrayBase& sendArray = *_ghostArraysLevel1[e];
              int to_where  = oSite.getGatherProcID();
              if ( to_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_send[indxSend++] =
                      MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
              }
          }
          //RECIEVING
          //getting values from other meshes to fill g
          const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
          foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
             const StorageSite&  oSite = *mpos.first;
             //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
             EntryIndex e(&oSite,&site);
             ArrayBase& recvArray = *_ghostArraysLevel1[e];
             int from_where       = oSite.getGatherProcID();
             if ( from_where != -1 ){
                int mpi_tag = oSite.getTag();
                request_recv[indxRecv++] =
                    MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
             }
          }
       }
    }
    MPI::Request::Waitall( countGather, request_recv );
    MPI::Request::Waitall( countScatter, request_send );
 #endif
    // gather
    foreach(ArrayMap::value_type& pos, _arrays){
       if ( pos.second->getLength() == pos.first->getCountLevel1() )
         syncGatherLevel1(*pos.first);
    }
 }
void Field::syncLocalVectorFields (std::vector< Field * > & dsf) static
Definition at line 702 of file Field.cpp.
References createSyncGatherArraysVectorFields(), get_request_size(), getArrayMap(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMap(), StorageSite::getGatherProcID(), getGhostArrayMap(), StorageSite::getScatterMap(), StorageSite::getTag(), syncGatherVectorFields(), syncLocalVectorFieldsLevel1(), and syncScatterVectorFields().
Referenced by COMETModel< T >::MakeParallel().
 {
        // scatter first (prepare ship packages)
    Field& field0 = *dsf[0];
    ArrayMap& arrays = field0.getArrayMap();
    foreach(ArrayMap::value_type& pos, arrays)
       Field::syncScatterVectorFields(*pos.first, dsf);
    const size_t numDir = dsf.size();
    foreach(ArrayMap::value_type& pos, arrays)
       Field::createSyncGatherArraysVectorFields(*pos.first, field0, numDir );
    GhostArrayMap& ghostArrays = field0.getGhostArrayMap();
 #ifdef FVM_PARALLEL
    //SENDING
    MPI::Request   request_send[ Field::get_request_size(field0) ];
    MPI::Request   request_recv[ Field::get_request_size(field0) ];
    int indxSend = 0;
    int indxRecv = 0;
    foreach(ArrayMap::value_type& pos, arrays){
       const StorageSite& site = *pos.first;
       const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
       foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
           const StorageSite&  oSite = *mpos.first;
           //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              EntryIndex e(&site,&oSite);
              ArrayBase& sendArray = *ghostArrays[e];
              int to_where  = oSite.getGatherProcID();
              if ( to_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_send[indxSend++] =
                      MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
              }
       }
       //RECIEVING
       //getting values from other meshes to fill g
       const StorageSite::GatherMap& gatherMap = site.getGatherMap();
       foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
          const StorageSite&  oSite = *mpos.first;
          //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
          EntryIndex e(&oSite,&site);
          ArrayBase& recvArray = *ghostArrays[e];
          int from_where       = oSite.getGatherProcID();
          if ( from_where != -1 ){
              int mpi_tag = oSite.getTag();
              request_recv[indxRecv++] =
                     MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
          }
       }
    }
    int count  = Field::get_request_size(field0);
    MPI::Request::Waitall( count, request_recv );
    MPI::Request::Waitall( count, request_send );
 #endif
   // gather
   foreach(ArrayMap::value_type& pos, arrays)
     Field::syncGatherVectorFields(*pos.first, dsf);
    //sycnLocal1
   Field::syncLocalVectorFieldsLevel1(dsf);
 }
void Field::syncLocalVectorFieldsLevel1 (std::vector< Field * > & dsf) static private
Definition at line 770 of file Field.cpp.
References createSyncGatherArraysVectorFieldsLevel1(), get_request_size_level1(), getArrayMap(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), getGhostArrayMapLevel1(), StorageSite::getScatterMapLevel1(), StorageSite::getTag(), syncGatherVectorFieldsLevel1(), and syncScatterVectorFieldsLevel1().
Referenced by syncLocalVectorFields().
 {
    // scatter first (prepare ship packages)
    Field& field0 = *dsf[0];
    ArrayMap& arrays = field0.getArrayMap();
    foreach(ArrayMap::value_type& pos, arrays){
       if ( pos.second->getLength() == pos.first->getCountLevel1() )
           Field::syncScatterVectorFieldsLevel1(*pos.first, dsf);
    }
    const size_t numDir = dsf.size();
    foreach(ArrayMap::value_type& pos, arrays){
       if ( pos.second->getLength() == pos.first->getCountLevel1() )
          Field::createSyncGatherArraysVectorFieldsLevel1(*pos.first, field0, numDir );
    }
    GhostArrayMap& ghostArrays = field0.getGhostArrayMapLevel1();
 #ifdef FVM_PARALLEL
    //SENDING
    MPI::Request   request_send[ Field::get_request_size_level1(field0) ];
    MPI::Request   request_recv[ Field::get_request_size_level1(field0) ];
    int indxSend = 0;
    int indxRecv = 0;
    foreach(ArrayMap::value_type& pos, arrays){
       const StorageSite& site = *pos.first;
       const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
       foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
           const StorageSite&  oSite = *mpos.first;
           //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              EntryIndex e(&site,&oSite);
              ArrayBase& sendArray = *ghostArrays[e];
              int to_where  = oSite.getGatherProcID();
              if ( to_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_send[indxSend++] =
                      MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
              }
       }
       //RECIEVING
       //getting values from other meshes to fill g
       const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
       foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
          const StorageSite&  oSite = *mpos.first;
          //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
          EntryIndex e(&oSite,&site);
          ArrayBase& recvArray = *ghostArrays[e];
          int from_where       = oSite.getGatherProcID();
          if ( from_where != -1 ){
              int mpi_tag = oSite.getTag();
              request_recv[indxRecv++] =
                     MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
          }
       }
    }
    int count  = Field::get_request_size_level1(field0);
    MPI::Request::Waitall( count, request_recv );
    MPI::Request::Waitall( count, request_send );
 #endif
   // gather
   foreach(ArrayMap::value_type& pos, arrays){
      if ( pos.second->getLength() == pos.first->getCountLevel1() )
          Field::syncGatherVectorFieldsLevel1(*pos.first, dsf);
   }
 }
void Field::syncScatter (const StorageSite & site) private
Definition at line 234 of file Field.cpp.
References _ghostArrays, Array< T >::getLength(), StorageSite::getScatterMap(), ArrayBase::newSizedClone(), operator[](), and ArrayBase::scatter().
Referenced by syncLocal().
 {
   const ArrayBase& thisArray = operator[](site);
   const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
   foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap)
   {
       const StorageSite& oSite = *mpos.first;
       EntryIndex e(&site, &oSite);
       const Array<int>& fromIndices = *(mpos.second);
       if (_ghostArrays.find(e) == _ghostArrays.end()){
         _ghostArrays[e] = thisArray.newSizedClone( fromIndices.getLength() );
       }
       ArrayBase& ghostArray = *_ghostArrays[e];
       thisArray.scatter(ghostArray,fromIndices);
   }
 }
void Field::syncScatterLevel1 (const StorageSite & site) private
Definition at line 257 of file Field.cpp.
References _ghostArraysLevel1, Array< T >::getLength(), StorageSite::getScatterMapLevel1(), ArrayBase::newSizedClone(), operator[](), and ArrayBase::scatter().
Referenced by syncLocalLevel1().
 {
   const ArrayBase& thisArray = operator[](site);
   const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
   foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap)
   {
       const StorageSite& oSite = *mpos.first;
       EntryIndex e(&site, &oSite);
       const Array<int>& fromIndices = *(mpos.second);
       if (_ghostArraysLevel1.find(e) == _ghostArraysLevel1.end()){
         _ghostArraysLevel1[e] = thisArray.newSizedClone( fromIndices.getLength() );
       }
       ArrayBase& ghostArray = *_ghostArraysLevel1[e];
       thisArray.scatter(ghostArray,fromIndices);
   }
 }
void Field::syncScatterVectorFields (const StorageSite & site, std::vector< Field * > & dsf) static private
Definition at line 569 of file Field.cpp.
References getGhostArrayMap(), Array< T >::getLength(), StorageSite::getScatterMap(), ArrayBase::newSizedClone(), and ArrayBase::scatter().
Referenced by syncLocalVectorFields().
 {
   const size_t numDir = dsf.size();
   Field& field0 = *dsf[0];
   ArrayBase& thisArray0 = field0[site];
   GhostArrayMap& ghostArrays = field0.getGhostArrayMap();
   const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
   foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap)
   {
       const StorageSite& oSite = *mpos.first;
       EntryIndex e(&site, &oSite);
       const Array<int>& fromIndices = *(mpos.second);
       if (ghostArrays.find(e) == ghostArrays.end()){
         ghostArrays[e] = thisArray0.newSizedClone( fromIndices.getLength() * numDir );
       }
       const int chunkSize = fromIndices.getLength();
       ArrayBase& ghostArray = *ghostArrays[e];
       for (size_t dir=0; dir < numDir; dir++){
         Field& field = *dsf[dir];
         const ArrayBase& thisArray = field[site];
         const int offset = chunkSize * dir;
         thisArray.scatter(ghostArray,fromIndices, offset);
       }
   }
 }
void Field::syncScatterVectorFieldsLevel1 (const StorageSite & site, std::vector< Field * > & dsf) static private
Definition at line 600 of file Field.cpp.
References getGhostArrayMapLevel1(), Array< T >::getLength(), StorageSite::getScatterMapLevel1(), ArrayBase::newSizedClone(), and ArrayBase::scatter().
Referenced by syncLocalVectorFieldsLevel1().
 {
   const size_t numDir = dsf.size();
   Field& field0 = *dsf[0];
   ArrayBase& thisArray0 = field0[site];
   GhostArrayMap& ghostArrays = field0.getGhostArrayMapLevel1();
   const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
   foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap)
   {
       const StorageSite& oSite = *mpos.first;
       EntryIndex e(&site, &oSite);
       const Array<int>& fromIndices = *(mpos.second);
       if (ghostArrays.find(e) == ghostArrays.end()){
         ghostArrays[e] = thisArray0.newSizedClone( fromIndices.getLength() * numDir );
       }
       const int chunkSize = fromIndices.getLength();
       ArrayBase& ghostArray = *ghostArrays[e];
       for (size_t dir=0; dir < numDir; dir++){
         Field& field = *dsf[dir];
         const ArrayBase& thisArray = field[site];
         const int offset = chunkSize * dir;
         thisArray.scatter(ghostArray,fromIndices, offset);
       }
   }
 }
void Field::zero () virtual
Implements IContainer.
Definition at line 168 of file Field.cpp.
References _arrays.
 {
   foreach(ArrayMap::value_type& pos, _arrays)
   {
       pos.second->zero();
   }
 }
Member Data Documentation
ArrayMap Field::_arrays private
Definition at line 91 of file Field.h.
Referenced by _create(), addArray(), clear(), get_request_size(), get_request_size_gather_level1(), get_request_size_scatter_level1(), getArrayMap(), getArrayPtr(), hasArray(), newClone(), newCopy(), operator=(), operator[](), removeArray(), syncLocal(), syncLocalLevel1(), and zero().
ChildSitesMap Field::_childSitesMap private
Definition at line 95 of file Field.h.
Referenced by _create(), clear(), and removeArray().
GhostArrayMap Field::_ghostArrays private
Definition at line 92 of file Field.h.
Referenced by clear(), createSyncGatherArrays(), getGhostArrayMap(), syncGather(), syncLocal(), and syncScatter().
GhostArrayMap Field::_ghostArraysLevel1 private
Definition at line 93 of file Field.h.
Referenced by clear(), createSyncGatherArraysLevel1(), getGhostArrayMapLevel1(), syncGatherLevel1(), syncLocalLevel1(), and syncScatterLevel1().
const string Field::_name private
Definition at line 90 of file Field.h.
Referenced by getName(), newClone(), and newCopy().
The documentation for this class was generated from the following files:
Field.h
Field.cpp