Memosa-FVM: Linearizer Class Reference
Linearizer Class Reference
#include <Linearizer.h>
Public Member Functions
Linearizer ()
virtual void linearize (DiscrList &discretizations, const MeshList &meshes, MultiFieldMatrix &matrix, MultiField &x, MultiField &b)
Detailed Description
Definition at line 16 of file Linearizer.h.
Constructor & Destructor Documentation
Linearizer::Linearizer ()
Definition at line 13 of file Linearizer.cpp.
 {}
Member Function Documentation
void Linearizer::linearize (DiscrList & discretizations, const MeshList & meshes, MultiFieldMatrix & matrix, MultiField & x, MultiField & b) virtual
Definition at line 17 of file Linearizer.cpp.
References Mesh::isShell().
Referenced by ThermalModel< T >::Impl::linearize(), FractureModel< T >::Impl::linearize(), VacancyModel< T >::Impl::linearize(), SpeciesModel< T >::Impl::linearize(), ElectricModel< T >::Impl::linearizeChargeTransport(), PlateModel< T >::Impl::linearizeDeformation(), StructureModel< T >::Impl::linearizeDeformation(), KeModel< T >::Impl::linearizedissipation(), ElectricModel< T >::Impl::linearizeElectroStatics(), KeModel< T >::Impl::linearizeenergy(), KineticModel< T >::linearizeKineticModel(), FlowModel< T >::Impl::linearizeMomentum(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), PhononModel< T >::linearizePhononModel(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), and BatteryModel< T >::Impl::linearizeThermal().
 {
   const int nMeshes = meshes.size();
   const int nDiscretizations = discretizations.size();
   //#pragma omp parallel for
   for(int n=0; n<nMeshes; n++)
   {
       const Mesh& mesh = *meshes[n];
       if (mesh.isShell() == false){
         for(int nd=0; nd<nDiscretizations; nd++)
           discretizations[nd]->discretize(mesh,matrix,x,r);
       }
   }
 }
The documentation for this class was generated from the following files:
Linearizer.h
Linearizer.cpp