Memosa-FVM: EmissionDiscretization< X, Diag, OffDiag > Class Template Reference
EmissionDiscretization< X, Diag, OffDiag > Class Template Reference
#include <EmissionDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Array< Vector
< T_Scalar, 3 > > VectorT3Array
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::OffDiagArray OffDiagArray
typedef Array< X > XArray
Public Member Functions
EmissionDiscretization (const MeshList &meshes, const GeomFields &geomFields, const Field &varField, const Field &electricField, const ElectricModelConstants< T_Scalar > &constants)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const Field & _electricField
const ElectricModelConstants
< T_Scalar > & _constants
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class EmissionDiscretization< X, Diag, OffDiag >
Definition at line 41 of file EmissionDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> EmissionDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 48 of file EmissionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray EmissionDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 49 of file EmissionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::OffDiagArray EmissionDiscretization< X, Diag, OffDiag >::OffDiagArray
Definition at line 50 of file EmissionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar EmissionDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 45 of file EmissionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> EmissionDiscretization< X, Diag, OffDiag >::TArray
Definition at line 46 of file EmissionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<Vector<T_Scalar,3> > EmissionDiscretization< X, Diag, OffDiag >::VectorT3Array
Definition at line 47 of file EmissionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> EmissionDiscretization< X, Diag, OffDiag >::XArray
Definition at line 51 of file EmissionDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > EmissionDiscretization< X, Diag, OffDiag >::EmissionDiscretization (const MeshList & meshes, const GeomFields & geomFields, const Field & varField, const Field & electricField, const ElectricModelConstants< T_Scalar > & constants) inline
Definition at line 53 of file EmissionDiscretization.h.
                                                                            :
     Discretization(meshes),
     _geomFields(geomFields),
     _varField(varField),
     _electricField(electricField),
     _constants(constants)
     {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void EmissionDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 66 of file EmissionDiscretization.h.
References EmissionDiscretization< X, Diag, OffDiag >::_constants, EmissionDiscretization< X, Diag, OffDiag >::_electricField, EmissionDiscretization< X, Diag, OffDiag >::_geomFields, EmissionDiscretization< X, Diag, OffDiag >::_varField, E0_SI, ElectricModelConstants< T >::electron_trapdepth, Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), MultiFieldMatrix::getMatrix(), StorageSite::getSelfCount(), K_SI, mag(), PI, QE, sqrt(), and GeomFields::volume.
   {
     const StorageSite& cells = mesh.getCells();
     const int nCells = cells.getSelfCount();
     const VectorT3Array& electric_field = dynamic_cast<const VectorT3Array&> (_electricField[cells]);
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     const XArray& xCell = dynamic_cast<const XArray&>(_varField[cells]);
     const TArray& cellVolume =
       dynamic_cast<const TArray&>(_geomFields.volume[cells]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     DiagArray& diag = matrix.getDiag();
     //OffDiagArray& offdiag = matrix.getOffDiag();
     const T_Scalar optical_dielectric_constant = _constants["optical_dielectric_constant"];
     const T_Scalar temperature = _constants["OP_temperature"];
     const T_Scalar poole_frenkel_emission_frequency = _constants["poole_frenkel_emission_frequency"];
     const int nTrap = _constants["nTrap"];
     vector<T_Scalar> electron_trapdepth = _constants.electron_trapdepth;
     const T_Scalar beta = sqrt( QE / (PI * E0_SI * optical_dielectric_constant) );
     for(int c=0; c<nCells; c++){
       for (int i=0; i<nTrap; i++){
         T_Scalar expt = (electron_trapdepth[i] - beta * sqrt(mag(electric_field[c]))) * QE / (K_SI * temperature);
         //if (expt < 0.0)
         //throw CException("exponential error in Emission model");
         if (expt > 0.0)
         {
             T_Scalar fluxCoeff = cellVolume[c] * poole_frenkel_emission_frequency * exp(-expt);
             rCell[c][i] -= (fluxCoeff * xCell[c][i]);
             diag[c](i,i) -= fluxCoeff;
             //diag[c][i] -= fluxCoeff;
             rCell[c][nTrap] += fluxCoeff * xCell[c][i];
         }
       }
     }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const ElectricModelConstants<T_Scalar>& EmissionDiscretization< X, Diag, OffDiag >::_constants private
Definition at line 125 of file EmissionDiscretization.h.
Referenced by EmissionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& EmissionDiscretization< X, Diag, OffDiag >::_electricField private
Definition at line 124 of file EmissionDiscretization.h.
Referenced by EmissionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& EmissionDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 122 of file EmissionDiscretization.h.
Referenced by EmissionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& EmissionDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 123 of file EmissionDiscretization.h.
Referenced by EmissionDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
EmissionDiscretization.h