Memosa-FVM: RosselandModel< T >::Impl Class Reference
RosselandModel< T >::Impl Class Reference
#include <RosselandModel_impl.h>
Public Types
typedef Array< T > TArray
Public Member Functions
Impl (const GeomFields &geomFields, ThermalFields &thermalFields, const MeshList &meshes)
VCMap & getVCMap ()
void init ()
bool advance (const int niter, bool init=false)
Private Attributes
const MeshList _meshes
const GeomFields & _geomFields
ThermalFields & _thermalFields
VCMap _vcMap
Detailed Description
template<class T>
class RosselandModel< T >::Impl
Definition at line 13 of file RosselandModel_impl.h.
Member Typedef Documentation
template<class T> typedef Array<T> RosselandModel< T >::Impl::TArray
Definition at line 16 of file RosselandModel_impl.h.
Constructor & Destructor Documentation
template<class T> RosselandModel< T >::Impl::Impl (const GeomFields & geomFields, ThermalFields & thermalFields, const MeshList & meshes) inline
Definition at line 18 of file RosselandModel_impl.h.
References Model::_meshes, and Mesh::getID().
                                :
     _meshes(meshes),
     _geomFields(geomFields),
     _thermalFields(thermalFields)
   {
     const int numMeshes = _meshes.size();
     for (int n=0; n<numMeshes; n++)
     {
         const Mesh& mesh = *_meshes[n];
         RosselandVC<T> *vc(new RosselandVC<T>());
         _vcMap[mesh.getID()] = vc;
     }
   }
Member Function Documentation
template<class T> bool RosselandModel< T >::Impl::advance (const int niter, bool init = false) inline
Definition at line 39 of file RosselandModel_impl.h.
References Model::_meshes, Mesh::getCells(), StorageSite::getCount(), Mesh::getID(), and FloatVarDict< T >::getVal().
   {
     const int numMeshes = _meshes.size();
     for (int n=0; n<numMeshes; n++)
     {
         const Mesh& mesh = *_meshes[n];
         const RosselandVC<T>& vc = *_vcMap[mesh.getID()];
         const StorageSite& cells = mesh.getCells();
         TArray& conductivity= dynamic_cast<TArray&>(_thermalFields.conductivity[cells]);
         FloatValEvaluator<T>  cellT(vc.getVal("temperature"),cells);
         const int nCells = cells.getCount();
         const float stefan = 0.0000000567;
         const T index(1.);
         const T a(1.);
         const T sigmas(0.);
         const T C(1.0);
         const T gamma = 1/(3*(a+sigmas) - C*sigmas);
         for(int c=0; c<nCells; c++)
         {
             T temp = cellT[c];
             conductivity[c] = 16*stefan*gamma*index*index*temp*temp*temp;
         }
     }
     return true;
   }
template<class T> VCMap& RosselandModel< T >::Impl::getVCMap () inline
Definition at line 35 of file RosselandModel_impl.h.
 {return _vcMap;}
template<class T> void RosselandModel< T >::Impl::init () inline
Definition at line 37 of file RosselandModel_impl.h.
References RosselandModel< T >::advance().
 { advance(1,true); }
Member Data Documentation
template<class T> const GeomFields& RosselandModel< T >::Impl::_geomFields private
Definition at line 75 of file RosselandModel_impl.h.
template<class T> const MeshList RosselandModel< T >::Impl::_meshes private
Definition at line 74 of file RosselandModel_impl.h.
template<class T> ThermalFields& RosselandModel< T >::Impl::_thermalFields private
Definition at line 76 of file RosselandModel_impl.h.
template<class T> VCMap RosselandModel< T >::Impl::_vcMap private
Definition at line 78 of file RosselandModel_impl.h.
The documentation for this class was generated from the following file:
RosselandModel_impl.h