Memosa-FVM: GlobalFields Class Reference
GlobalFields Class Reference
#include <GlobalFields.h>
Public Types
typedef map< const FieldLabel
*, shared_ptr< Field > > FieldMap
Static Public Member Functions
static Field & createField (const FieldLabel &fieldLabel)
static const Field & getField (const FieldLabel &fieldLabel)
Static Private Member Functions
static FieldMap & getFieldMap ()
Static Private Attributes
static FieldMap * _fieldMap = 0
Detailed Description
Definition at line 12 of file GlobalFields.h.
Member Typedef Documentation
typedef map<const FieldLabel*, shared_ptr<Field> > GlobalFields::FieldMap
Definition at line 15 of file GlobalFields.h.
Member Function Documentation
Field & GlobalFields::createField (const FieldLabel & fieldLabel) static
Definition at line 10 of file GlobalFields.cpp.
References getFieldMap(), and FieldLabel::getName().
 {
   FieldMap& fMap = getFieldMap();
   FieldMap::iterator p = fMap.find(&fieldLabel);
   if (p == fMap.end())
   {
       shared_ptr<Field> f(new Field(fieldLabel.getName()));
       fMap[&fieldLabel] = f;
       return *f;
   }
   else
     return *p->second;
 }
const Field & GlobalFields::getField (const FieldLabel & fieldLabel) static
Definition at line 25 of file GlobalFields.cpp.
References getFieldMap(), and FieldLabel::getName().
 {
   FieldMap& fMap = getFieldMap();
   FieldMap::iterator p = fMap.find(&fieldLabel);
   if (p != fMap.end()) return *p->second;
   throw CException("No such field " + fieldLabel.getName());
 }
GlobalFields::FieldMap & GlobalFields::getFieldMap () static private
Definition at line 34 of file GlobalFields.cpp.
References _fieldMap.
Referenced by createField(), and getField().
 {
   if (!_fieldMap)
   {
       _fieldMap = new FieldMap();
   }
   return *_fieldMap;
 }
Member Data Documentation
GlobalFields::FieldMap * GlobalFields::_fieldMap = 0 static private
Definition at line 22 of file GlobalFields.h.
Referenced by getFieldMap().
The documentation for this class was generated from the following files:
GlobalFields.h
GlobalFields.cpp