Memosa-FVM: SpikeSolver Class Reference
SpikeSolver Class Reference
#include <SpikeSolver.h>
Public Member Functions
SpikeSolver (const SpikeStorage &spike_storage)
virtual ~SpikeSolver ()
virtual MFRPtr solve (LinearSystem &ls)
virtual void cleanup ()
virtual void smooth (LinearSystem &ls)
DEFINE_TYPENAME ("SpikeSolver")
Public Member Functions inherited from LinearSolver
LinearSolver ()
Private Member Functions
void doSweeps (LinearSystem &ls, const int nSweeps)
SpikeSolver (const SpikeSolver &)
Private Attributes
const SpikeStorage & _spikeStorage
Additional Inherited Members
Public Attributes inherited from LinearSolver
int nMaxIterations
int verbosity
double relativeTolerance
double absoluteTolerance
Detailed Description
Solve a linear system using Jacobi iterations
Definition at line 21 of file SpikeSolver.h.
Constructor & Destructor Documentation
SpikeSolver::SpikeSolver (const SpikeStorage & spike_storage)
Definition at line 16 of file SpikeSolver.cpp.
References logCtor.
                                                          :
 _spikeStorage(spike_storage)
 {
   logCtor();
 }
SpikeSolver::~SpikeSolver () virtual
Definition at line 23 of file SpikeSolver.cpp.
References logDtor.
 {
   logDtor();
 }
SpikeSolver::SpikeSolver (const SpikeSolver &) private
Member Function Documentation
void SpikeSolver::cleanup () virtual
Implements LinearSolver.
Definition at line 44 of file SpikeSolver.cpp.
 {
 }
SpikeSolver::DEFINE_TYPENAME ("SpikeSolver")
void SpikeSolver::doSweeps (LinearSystem & ls, const int nSweeps) private
Definition at line 29 of file SpikeSolver.cpp.
References _spikeStorage, LinearSystem::getB(), LinearSystem::getDelta(), LinearSystem::getMatrix(), LinearSystem::getResidual(), and MultiFieldMatrix::spikeSolve().
Referenced by smooth(), and solve().
 {
   const MultiFieldMatrix& m = ls.getMatrix();
   MultiField& delta = ls.getDelta();
   const MultiField& b = ls.getB();
   MultiField& r = ls.getResidual();
   for(int i=0; i<nSweeps; i++)
   {
       m.spikeSolve(delta,b,r,_spikeStorage);
   }
 }
void SpikeSolver::smooth (LinearSystem & ls) virtual
Implements LinearSolver.
Definition at line 100 of file SpikeSolver.cpp.
References doSweeps().
 {
   doSweeps(ls,1);
 }
MFRPtr SpikeSolver::solve (LinearSystem & ls) virtual
Implements LinearSolver.
Definition at line 49 of file SpikeSolver.cpp.
References LinearSolver::absoluteTolerance, MultiFieldMatrix::computeResidual(), doSweeps(), LinearSystem::getB(), LinearSystem::getDelta(), LinearSystem::getMatrix(), MultiField::getOneNorm(), LinearSystem::getResidual(), LinearSolver::nMaxIterations, LinearSolver::relativeTolerance, and LinearSolver::verbosity.
 {
   ls.getMatrix().computeResidual(ls.getDelta(),
                                  ls.getB(),
                                  ls.getResidual());
   MFRPtr rNorm0(ls.getResidual().getOneNorm());
 #ifdef FVM_PARALLEL
   if (verbosity >0 && MPI::COMM_WORLD.Get_rank() == 0 )
     cout << "0: " << *rNorm0 << "procID = " << MPI::COMM_WORLD.Get_rank() << endl;
 #endif
 #ifndef FVM_PARALLEL
    if ( verbosity > 0 )
       cout << "0: " << *rNorm0 << endl;
 #endif
   if (*rNorm0 < absoluteTolerance )
     return rNorm0;
   for(int i=1; i<nMaxIterations; i++)
   {
       doSweeps(ls,1);
       ls.getMatrix().computeResidual(ls.getDelta(),
                                      ls.getB(),
                                      ls.getResidual());
       MFRPtr rNorm(ls.getResidual().getOneNorm());
       MFRPtr normRatio((*rNorm)/(*rNorm0));
 #ifndef FVM_PARALLEL
       if (verbosity >0  )
         cout << i << ": " <<  *rNorm << endl;
 #endif
 #ifdef FVM_PARALLEL
      if (*rNorm < absoluteTolerance || *normRatio < relativeTolerance || i == nMaxIterations-1)
         if (verbosity >0 && MPI::COMM_WORLD.Get_rank() == 0  )
         cout <<i << ": " << "procID = " << MPI::COMM_WORLD.Get_rank() <<  *rNorm << endl;
 #endif
       if (*rNorm < absoluteTolerance || *normRatio < relativeTolerance)
          break;
   }
   return rNorm0;
 }
Member Data Documentation
const SpikeStorage& SpikeSolver::_spikeStorage private
Definition at line 36 of file SpikeSolver.h.
Referenced by doSweeps().
The documentation for this class was generated from the following files:
SpikeSolver.h
SpikeSolver.cpp