Memosa-FVM: BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag > Class Template Reference
BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag > Class Template Reference
#include <BatteryBinaryElectrolyteDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Gradient< X > XGrad
typedef Array< int > IntArray
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Array< XGrad > GradArray
Public Member Functions
BatteryBinaryElectrolyteDiscretization (const MeshList &meshes, const GeomFields &geomFields, Field &varField, const Field &diffusivityField, const Field &concField, const Field &concGradientField, const Field &tempField, const int ElectrolyteMeshID)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
Field & _varField
const Field & _diffusivityField
const Field & _concField
const Field & _concGradientField
const Field & _tempField
const int _ElectrolyteMeshID
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >
Definition at line 27 of file BatteryBinaryElectrolyteDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 35 of file BatteryBinaryElectrolyteDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 33 of file BatteryBinaryElectrolyteDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 34 of file BatteryBinaryElectrolyteDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<XGrad> BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::GradArray
Definition at line 45 of file BatteryBinaryElectrolyteDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<int> BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::IntArray
Definition at line 38 of file BatteryBinaryElectrolyteDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 31 of file BatteryBinaryElectrolyteDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::TArray
Definition at line 41 of file BatteryBinaryElectrolyteDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::VectorT3
Definition at line 42 of file BatteryBinaryElectrolyteDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::VectorT3Array
Definition at line 43 of file BatteryBinaryElectrolyteDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::XArray
Definition at line 40 of file BatteryBinaryElectrolyteDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Gradient<X> BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::XGrad
Definition at line 37 of file BatteryBinaryElectrolyteDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::BatteryBinaryElectrolyteDiscretization (const MeshList & meshes, const GeomFields & geomFields, Field & varField, const Field & diffusivityField, const Field & concField, const Field & concGradientField, const Field & tempField, const int ElectrolyteMeshID) inline
Definition at line 47 of file BatteryBinaryElectrolyteDiscretization.h.
                                                                       :
     Discretization(meshes),
       _geomFields(geomFields),
       _varField(varField),
       _diffusivityField(diffusivityField),
       _concField(concField),
       _concGradientField(concGradientField),
       _tempField(tempField),
       _ElectrolyteMeshID(ElectrolyteMeshID)
       {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 65 of file BatteryBinaryElectrolyteDiscretization.h.
References BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_concField, BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_concGradientField, BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_diffusivityField, BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_ElectrolyteMeshID, BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_geomFields, BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_tempField, BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_varField, GeomFields::area, GeomFields::areaMag, GeomFields::coordinate, dot(), Mesh::getAllFaceGroups(), Mesh::getCells(), StorageSite::getCount(), Mesh::getFaceCells(), Mesh::getID(), harmonicAverage(), GeomFields::ibType, Mesh::IBTYPE_BOUNDARY, Mesh::IBTYPE_FLUID, FaceGroup::site, and GeomFields::volume.
     {
       if (mesh.getID() == _ElectrolyteMeshID)
         {
           // electric potential variables
           const StorageSite& cells = mesh.getCells();
           const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
           //CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
           const VectorT3Array& cellCentroid =
             dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[cells]);
           const TArray& cellVolume =
             dynamic_cast<const TArray&>(_geomFields.volume[cells]);
           //DiagArray& diag = matrix.getDiag();
           //const XArray& xCell = dynamic_cast<const XArray&>(xField[cVarIndex]); // may not need here
           XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
           // lnspeciesConcentration variables
           const TArray& lnSpecConcCell = dynamic_cast<const TArray&>(_concField[cells]);
           const GradArray& lnSpecConcGradCell =
             dynamic_cast<const GradArray&>(_concGradientField[cells]);
           const TArray& diffCell =
             dynamic_cast<const TArray&>(_diffusivityField[cells]);
           const TArray& tempCell =
             dynamic_cast<const TArray&>(_tempField[cells]);
           const IntArray& ibType = dynamic_cast<const IntArray&>(_geomFields.ibType[cells]);
           foreach(const FaceGroupPtr fgPtr, mesh.getAllFaceGroups())
             {
               const FaceGroup& fg = *fgPtr;
               const StorageSite& faces = fg.site;
               const int nFaces = faces.getCount();
               const CRConnectivity& faceCells = mesh.getFaceCells(faces);
               const VectorT3Array& faceArea =
                 dynamic_cast<const VectorT3Array&>(_geomFields.area[faces]);
               const TArray& faceAreaMag =
                 dynamic_cast<const TArray&>(_geomFields.areaMag[faces]);
               const VectorT3Array& faceCentroid =
                 dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[faces]);
               //CCAssembler& assembler = matrix.getPairWiseAssembler(faceCells);
               for(int f=0; f<nFaces; f++)
                 {
                   const int c0 = faceCells(f,0);
                   const int c1 = faceCells(f,1);
                   T_Scalar vol0 = cellVolume[c0];
                   T_Scalar vol1 = cellVolume[c1];
                   VectorT3 ds=cellCentroid[c1]-cellCentroid[c0];
                   // for ib faces ignore the solid cell and use the face centroid for diff metric
                   if (((ibType[c0] == Mesh::IBTYPE_FLUID)
                        && (ibType[c1] == Mesh::IBTYPE_BOUNDARY)) ||
                       ((ibType[c1] == Mesh::IBTYPE_FLUID)
                        && (ibType[c0] == Mesh::IBTYPE_BOUNDARY)))
                     {
                       if (ibType[c0] == Mesh::IBTYPE_FLUID)
{
                           vol1 = 0.;
                           ds = faceCentroid[f]-cellCentroid[c0];
                         }
                       else
{
                           vol0 = 0.;
                           ds = cellCentroid[c1]-faceCentroid[f];
                         }
                     }
                   T_Scalar faceDiffusivity(1.0);
                   if (vol0 == 0.)
                     faceDiffusivity = diffCell[c1];
                   else if (vol1 == 0.)
                     faceDiffusivity = diffCell[c0];
                   else
                     faceDiffusivity = harmonicAverage(diffCell[c0],diffCell[c1]);
                   T_Scalar faceTemp(300.0);
                   if (vol0 == 0.)
                     faceTemp = tempCell[c1];
                   else if (vol1 == 0.)
                     faceTemp = tempCell[c0];
                   else
                     faceTemp = harmonicAverage(tempCell[c0],tempCell[c1]);
                   //convert diffusivity for ln term in battery equation
                   const T_Scalar transportNumber = 0.4;
                   const T_Scalar R = 8.314;
                   const T_Scalar F = 96485.0;
                   faceDiffusivity = faceDiffusivity*(-2.0)*R*faceTemp/F*(1.0-transportNumber);
                   const T_Scalar diffMetric = faceAreaMag[f]*faceAreaMag[f]/dot(faceArea[f],ds);
                   const T_Scalar diffCoeff = faceDiffusivity*diffMetric;
                   const VectorT3 secondaryCoeff = faceDiffusivity*(faceArea[f]-ds*diffMetric);
                   const XGrad gradF = (lnSpecConcGradCell[c0]*vol0+lnSpecConcGradCell[c1]*vol1)/(vol0+vol1);
                   const X dFluxSecondary = gradF*secondaryCoeff;
                   const X dFlux = diffCoeff*(lnSpecConcCell[c1]-lnSpecConcCell[c0]) + dFluxSecondary;
                   rCell[c0] += dFlux;
                   rCell[c1] -= dFlux;
                   //assembler.getCoeff01(f) +=diffCoeff;
                   //assembler.getCoeff10(f) +=diffCoeff;
                   //diag[c0] -= diffCoeff;
                   //diag[c1] -= diffCoeff;
                   //cout <<"dflux" << dFlux << endl;
                   /*
                     cout << " c0 and c1 " << c0 << " " << c1 << endl;
                     cout << " diffcell " << diffCell[c0] << " " << diffCell[c1] << " " << faceDiffusivity << endl;
                     cout << " diffmetric  " << diffMetric << endl;
                     cout << "diffCoeff  " << diffCoeff << endl;
                   */
                 }
             }
         }
     }
Member Data Documentation
template<class X , class Diag , class OffDiag > const Field& BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_concField private
Definition at line 205 of file BatteryBinaryElectrolyteDiscretization.h.
Referenced by BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_concGradientField private
Definition at line 206 of file BatteryBinaryElectrolyteDiscretization.h.
Referenced by BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_diffusivityField private
Definition at line 204 of file BatteryBinaryElectrolyteDiscretization.h.
Referenced by BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const int BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_ElectrolyteMeshID private
Definition at line 208 of file BatteryBinaryElectrolyteDiscretization.h.
Referenced by BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 202 of file BatteryBinaryElectrolyteDiscretization.h.
Referenced by BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_tempField private
Definition at line 207 of file BatteryBinaryElectrolyteDiscretization.h.
Referenced by BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > Field& BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 203 of file BatteryBinaryElectrolyteDiscretization.h.
Referenced by BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
BatteryBinaryElectrolyteDiscretization.h