Memosa-FVM: ArrowHeadMatrix< X, K > Class Template Reference
ArrowHeadMatrix< X, K > Class Template Reference
#include <ArrowHeadMatrix.h>
Public Types
typedef Array< X > XArray
typedef Array< Vector< X, K > > VectorXKArray
typedef Array< VectorTranspose
< X, K > > TVectorXKArray
typedef SquareTensor< X, K > TensorXK
typedef Vector< X, K > VectorXK
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T > TArray
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
Public Types inherited from MatrixJML< T >
typedef Array< T > TArray
Public Member Functions
ArrowHeadMatrix (const int order)
T_Scalar & getElement (const int i, const int j)
void Solve (XArray &bVec)
void zero ()
T_Scalar getTraceAbs ()
void multiply (const XArray &x, XArray &b)
ArrowHeadMatrix (const int order)
T & operator() (const int i, const int j)
T & getElement (const int i, const int j)
void printElement (const int &i, const int &j)
void print ()
void Solve (TArray &bVec)
void SolveDiag (TArray &bVec)
void smoothGS (TArray &bVec)
void DummySolve ()
void SolveBotCol (TArray &bVec)
void zero ()
void ones ()
T getTraceAbs ()
void multiply (const TArray &x, TArray &b)
Public Member Functions inherited from MatrixJML< T >
MatrixJML ()
virtual ~MatrixJML ()
MatrixJML ()
virtual ~MatrixJML ()
Private Attributes
const int _order
const int _numDir
XArray _d
VectorXKArray _r
TVectorXKArray _c
TensorXK _l
VectorXK _bl
VectorXK _xl
int _elements
TArray _values
int _order
Detailed Description
template<class X, int K>
class ArrowHeadMatrix< X, K >
Definition at line 21 of file esbgkbase/ArrowHeadMatrix.h.
Member Typedef Documentation
template<class X , int K> typedef NumTypeTraits<T>::T_Scalar ArrowHeadMatrix< X, K >::T_Scalar
Definition at line 19 of file phononbase/ArrowHeadMatrix.h.
template<class X , int K> typedef NumTypeTraits<X>::T_Scalar ArrowHeadMatrix< X, K >::T_Scalar
Definition at line 30 of file esbgkbase/ArrowHeadMatrix.h.
template<class X , int K> typedef Array<T> ArrowHeadMatrix< X, K >::TArray
Definition at line 18 of file phononbase/ArrowHeadMatrix.h.
template<class X , int K> typedef SquareTensor<X,K> ArrowHeadMatrix< X, K >::TensorXK
Definition at line 28 of file esbgkbase/ArrowHeadMatrix.h.
template<class X , int K> typedef Array<VectorTranspose<X,K> > ArrowHeadMatrix< X, K >::TVectorXKArray
Definition at line 27 of file esbgkbase/ArrowHeadMatrix.h.
template<class X , int K> typedef Vector<X,K> ArrowHeadMatrix< X, K >::VectorXK
Definition at line 29 of file esbgkbase/ArrowHeadMatrix.h.
template<class X , int K> typedef Array<Vector<X,K> > ArrowHeadMatrix< X, K >::VectorXKArray
Definition at line 26 of file esbgkbase/ArrowHeadMatrix.h.
template<class X , int K> typedef Array<X> ArrowHeadMatrix< X, K >::XArray
Definition at line 25 of file esbgkbase/ArrowHeadMatrix.h.
Constructor & Destructor Documentation
template<class X , int K> ArrowHeadMatrix< X, K >::ArrowHeadMatrix (const int order) inline
Definition at line 32 of file esbgkbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_bl, ArrowHeadMatrix< X, K >::_c, ArrowHeadMatrix< X, K >::_d, ArrowHeadMatrix< X, K >::_l, ArrowHeadMatrix< X, K >::_r, ArrowHeadMatrix< X, K >::_xl, Vector< T, N >::zero(), SquareTensor< T, N >::zero(), and Array< T >::zero().
                                    :
     _order(order),
     _numDir(order-3),
     _d(_numDir),
     _r(_numDir),
     _c(_numDir),
     _l(3),
     _bl(),
     _xl()
   {
     _d.zero();
     _r.zero();
     _c.zero();
     _l.zero();
     _bl.zero();
     _xl.zero();
   }
template<class X , int K> ArrowHeadMatrix< X, K >::ArrowHeadMatrix (const int order) inline
Definition at line 21 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_values.
                                  :
   _elements(3*order-2),
     _values(_elements),
     _order(order)
     {
       _values=0.;
     }
Member Function Documentation
template<class X , int K> void ArrowHeadMatrix< X, K >::DummySolve () inline
Definition at line 182 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order.
   {
     TArray bVec(_order);
     bVec=1.;
     //Replaces bVec with solution vector.
     T ani;
     T ain;
     T aii;
     T alpha;
     T beta;
     alpha=0.;
     beta=0.;
     for(int i=1;i<_order;i++)
       {
         ani=(*this)(_order,i);
         aii=(*this)(i,i);
         ain=(*this)(i,_order);
         alpha+=ani*bVec[i-1]/aii;
         beta+=ani*ain/aii;
       }
     T bn;
     bn=(bVec[_order-1]-alpha)/((*this)(_order,_order)-beta);
     for(int i=1;i<_order;i++)
       {
         ain=(*this)(i,_order);
         aii=(*this)(i,i);
         bVec[i-1]=(bVec[i-1]-ain*bn)/aii;
       }
     bVec[_order-1]=bn;
   }
template<class X , int K> T_Scalar& ArrowHeadMatrix< X, K >::getElement (const int i, const int j) inline virtual
Implements MatrixJML< T >.
Definition at line 50 of file esbgkbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_c, ArrowHeadMatrix< X, K >::_d, ArrowHeadMatrix< X, K >::_l, ArrowHeadMatrix< X, K >::_numDir, ArrowHeadMatrix< X, K >::_order, and ArrowHeadMatrix< X, K >::_r.
Referenced by COMETESBGKDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETESBGKDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETConvectionFine(), and ArrowHeadMatrix< X, K >::SolveBotCol().
   {
       int index;
       if(i<=_numDir)
       {
           index=(i-1);
           if(i==j)
               return _d[index];
           else
               return _c[index][j-_order+2];
       }
       else
       {
           index=(j-1);
           if(j<=_order-3)
               return (_r[index])[i-_order+2];
           else
             return _l(i-_order+2,j-_order+2);
       }
   }
template<class X , int K> T& ArrowHeadMatrix< X, K >::getElement (const int i, const int j) inline virtual
Implements MatrixJML< T >.
Definition at line 54 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order, and ArrowHeadMatrix< X, K >::_values.
     {
       int index;
       if(i==j)
         {
           index=(i-1);
           return _values[index];
         }
       else if(j==_order)
         {
           index=i-1+_order;
           return _values[index];
         }
       else if(i==_order)
         {
           index=2*_order+j-2;
           return _values[index];
         }
       else
         {
           throw CException("Invalid index: Arrowhead matrix");
           return _values[0];
         }
     }
template<class X , int K> T_Scalar ArrowHeadMatrix< X, K >::getTraceAbs () inline
Definition at line 99 of file esbgkbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_d, ArrowHeadMatrix< X, K >::_l, ArrowHeadMatrix< X, K >::_order, and fabs().
Referenced by COMETESBGKDiscretizer< T >::findResid(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETESBGKDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
   {
     T_Scalar trace=0.;
     for(int i=0;i<_order-3;i++)
       trace+=fabs(_d[i]);
     trace+=(fabs(_l(0,0))+fabs(_l(1,1))+fabs(_l(2,2)));
     return trace;
   }
template<class X , int K> T ArrowHeadMatrix< X, K >::getTraceAbs () inline
Definition at line 242 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order, ArrowHeadMatrix< X, K >::_values, and fabs().
   {
     T trace=0.;
     for(int i=0;i<_order;i++)
       trace+=fabs(_values[i]);
     return trace;
   }
template<class X , int K> void ArrowHeadMatrix< X, K >::multiply (const XArray & x, XArray & b) inline
Definition at line 108 of file esbgkbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_c, ArrowHeadMatrix< X, K >::_d, ArrowHeadMatrix< X, K >::_l, ArrowHeadMatrix< X, K >::_order, ArrowHeadMatrix< X, K >::_r, Array< T >::getLength(), and Array< T >::zero().
Referenced by COMETESBGKDiscretizer< T >::findResid(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETESBGKDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
   {
       int len=x.getLength();
       if(len==_order)
       {
           b.zero();
           for(int i=0;i<_order-3;i++)
             b[i]=_d[i]*x[i]+_c[i][0]*x[_order-3]+_c[i][1]*x[_order-2]+_c[i][2]*x[_order-1];
           b[_order-3]+=_l(0,0)*x[_order-3];
           b[_order-2]+=_l(1,1)*x[_order-2];
           b[_order-1]+=_l(2,2)*x[_order-1];
           for(int i=0;i<_order-3;i++)
           {
               b[_order-3]+=_r[i][0]*x[i];
               b[_order-2]+=_r[i][1]*x[i];
               b[_order-1]+=_r[i][2]*x[i];
           }
       }
       else
         throw CException("Array length does not match matrix order!");
   }
template<class X , int K> void ArrowHeadMatrix< X, K >::multiply (const TArray & x, TArray & b) inline virtual
Implements MatrixJML< T >.
Definition at line 250 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order, ArrowHeadMatrix< X, K >::_values, Array< T >::getLength(), and Array< T >::zero().
   { //Ax=b
       int len=x.getLength();
       if(len==_order)
         {
           b.zero();
           for(int i=0;i<_order-1;i++)
             b[i]=_values[i]*x[i]+_values[i-1+_order]*x[_order-1];
           b[_order-1]+=_values[_order-1]*x[_order-1];
           for(int i=0;i<_order-1;i++)
             b[_order-1]+=_values[2*_order+i-2]*x[i];
         }
       else
         throw CException("Array length does not match matrix order!");
     }
template<class X , int K> void ArrowHeadMatrix< X, K >::ones () inline
Definition at line 236 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_elements, and ArrowHeadMatrix< X, K >::_values.
   {
     for(int i=0;i<_elements;i++)
       _values[i]=T_Scalar(1);
   }
template<class X , int K> T& ArrowHeadMatrix< X, K >::operator() (const int i, const int j) inline
Definition at line 29 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order, and ArrowHeadMatrix< X, K >::_values.
     {
       int index;
       if(i==j)
         {
           index=(i-1);
           return _values[index];
         }
       else if(j==_order)
         {
           index=i-1+_order;
           return _values[index];
         }
       else if(i==_order)
         {
           index=2*_order+j-2;
           return _values[index];
         }
       else
         {
           throw CException("Invalid index: Arrowhead matrix");
           return _values[0];
         }
     }
template<class X , int K> void ArrowHeadMatrix< X, K >::print () inline
Definition at line 103 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order, and ArrowHeadMatrix< X, K >::printElement().
   {
     for(int i=1;i<_order+1;i++)
       {
         for(int j=1;j<_order+1;j++)
           {
             if((i==j)||(i==_order)||(j==_order))
               {
                 printElement(i,j);
                 cout<<" ";
               }
             else
               cout<<0<<" ";
           }
         cout<<endl;
       }
   }
template<class X , int K> void ArrowHeadMatrix< X, K >::printElement (const int & i, const int & j) inline
Definition at line 79 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order, and ArrowHeadMatrix< X, K >::_values.
Referenced by ArrowHeadMatrix< X, K >::print().
     {
       int index;
       if(i==j)
         {
           index=(i-1);
           cout<<_values[index];
         }
       else if(j==_order)
         {
           index=i-1+_order;
           cout<<_values[index];
         }
       else if(i==_order)
         {
           index=2*_order+j-2;
           cout<<_values[index];
         }
       else
         {
           throw CException("Invalid index for Arrowhead matrix");
         }
     }
template<class X , int K> void ArrowHeadMatrix< X, K >::smoothGS (TArray & bVec) inline
Definition at line 167 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order.
   {
     T& dT=bVec[_order-1];
     T sum(0);
     for(int i=1;i<_order;i++)
       {
         bVec[i-1]=(bVec[i-1]-(*this)(i,_order)*dT)/(*this)(i,i);
         sum+=(*this)(i,i)*bVec[i-1];
       }
     dT=(bVec[_order-1]-sum)/(*this)(_order,_order);
   }
template<class X , int K> void ArrowHeadMatrix< X, K >::Solve (XArray & bVec) inline
Definition at line 71 of file esbgkbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_bl, ArrowHeadMatrix< X, K >::_c, ArrowHeadMatrix< X, K >::_d, ArrowHeadMatrix< X, K >::_l, ArrowHeadMatrix< X, K >::_numDir, ArrowHeadMatrix< X, K >::_order, ArrowHeadMatrix< X, K >::_r, and ArrowHeadMatrix< X, K >::_xl.
Referenced by COMETESBGKDiscretizer< T >::COMETSolve(), COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETESBGKDiscretizer< T >::COMETSolveFine(), and COMETDiscretizer< T >::COMETSolveFull().
   {
     _bl[0]=bVec[_order-3];
     _bl[1]=bVec[_order-2];
     _bl[2]=bVec[_order-1];
     for(int i=0; i<_numDir; i++)
     {
         _l-=((_c[i]).getTensor(_r[i]))/_d[i];
         _bl-=_r[i]*bVec[i]/_d[i];
     }
     _xl=_bl/_l;
     for(int i=0; i<_order-3; i++)
       bVec[i]=(bVec[i]-_c[i]*_xl)/_d[i];
     bVec[_order-3]=_xl[0];
     bVec[_order-2]=_xl[1];
     bVec[_order-1]=_xl[2];
   }
template<class X , int K> void ArrowHeadMatrix< X, K >::Solve (TArray & bVec) inline
Definition at line 121 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order.
   {
     //Replaces bVec with solution vector.
     T ani;
     T ain;
     T aii;
     T alpha;
     T beta;
     alpha=0.;
     beta=0.;
     for(int i=1;i<_order;i++)
       {
         ani=(*this)(_order,i);
         aii=(*this)(i,i);
         ain=(*this)(i,_order);
         alpha+=ani*bVec[i-1]/aii;
         beta+=ani*ain/aii;
       }
     T bn;
     bn=(bVec[_order-1]-alpha)/((*this)(_order,_order)-beta);
     for(int i=1;i<_order;i++)
       {
         ain=(*this)(i,_order);
         aii=(*this)(i,i);
         bVec[i-1]=(bVec[i-1]-ain*bn)/aii;
       }
     bVec[_order-1]=bn;
   }
template<class X , int K> void ArrowHeadMatrix< X, K >::SolveBotCol (TArray & bVec) inline
Definition at line 219 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order, and ArrowHeadMatrix< X, K >::getElement().
   {
     T sum(0);
     for(int i=1;i<_order+1;i++)
       sum+=getElement(_order,i);
     bVec[_order-1]/=sum;
   }
template<class X , int K> void ArrowHeadMatrix< X, K >::SolveDiag (TArray & bVec) inline
Definition at line 159 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_order.
   {
     for(int i=1;i<_order;i++)
       bVec[i-1]/=(*this)(i,i);
     bVec[_order-1]=0;
   }
template<class X , int K> void ArrowHeadMatrix< X, K >::zero () inline virtual
Implements MatrixJML< T >.
Definition at line 91 of file esbgkbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_c, ArrowHeadMatrix< X, K >::_d, ArrowHeadMatrix< X, K >::_l, ArrowHeadMatrix< X, K >::_r, SquareTensor< T, N >::zero(), and Array< T >::zero().
Referenced by COMETESBGKDiscretizer< T >::COMETSolve(), COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETESBGKDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), COMETESBGKDiscretizer< T >::findResid(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETESBGKDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
   {
     _d.zero();
     _r.zero();
     _c.zero();
     _l.zero();
   }
template<class X , int K> void ArrowHeadMatrix< X, K >::zero () inline virtual
Implements MatrixJML< T >.
Definition at line 230 of file phononbase/ArrowHeadMatrix.h.
References ArrowHeadMatrix< X, K >::_elements, and ArrowHeadMatrix< X, K >::_values.
   {
     for(int i=0;i<_elements;i++)
       _values[i]=T_Scalar(0);
   }
Member Data Documentation
template<class X , int K> VectorXK ArrowHeadMatrix< X, K >::_bl private
Definition at line 140 of file esbgkbase/ArrowHeadMatrix.h.
Referenced by ArrowHeadMatrix< X, K >::ArrowHeadMatrix(), and ArrowHeadMatrix< X, K >::Solve().
template<class X , int K> TVectorXKArray ArrowHeadMatrix< X, K >::_c private
Definition at line 138 of file esbgkbase/ArrowHeadMatrix.h.
Referenced by ArrowHeadMatrix< X, K >::ArrowHeadMatrix(), ArrowHeadMatrix< X, K >::getElement(), ArrowHeadMatrix< X, K >::multiply(), ArrowHeadMatrix< X, K >::Solve(), and ArrowHeadMatrix< X, K >::zero().
template<class X , int K> XArray ArrowHeadMatrix< X, K >::_d private
Definition at line 136 of file esbgkbase/ArrowHeadMatrix.h.
Referenced by ArrowHeadMatrix< X, K >::ArrowHeadMatrix(), ArrowHeadMatrix< X, K >::getElement(), ArrowHeadMatrix< X, K >::getTraceAbs(), ArrowHeadMatrix< X, K >::multiply(), ArrowHeadMatrix< X, K >::Solve(), and ArrowHeadMatrix< X, K >::zero().
template<class X , int K> int ArrowHeadMatrix< X, K >::_elements private
Definition at line 268 of file phononbase/ArrowHeadMatrix.h.
Referenced by ArrowHeadMatrix< X, K >::ones(), and ArrowHeadMatrix< X, K >::zero().
template<class X , int K> TensorXK ArrowHeadMatrix< X, K >::_l private
Definition at line 139 of file esbgkbase/ArrowHeadMatrix.h.
Referenced by ArrowHeadMatrix< X, K >::ArrowHeadMatrix(), ArrowHeadMatrix< X, K >::getElement(), ArrowHeadMatrix< X, K >::getTraceAbs(), ArrowHeadMatrix< X, K >::multiply(), ArrowHeadMatrix< X, K >::Solve(), and ArrowHeadMatrix< X, K >::zero().
template<class X , int K> const int ArrowHeadMatrix< X, K >::_numDir private
Definition at line 135 of file esbgkbase/ArrowHeadMatrix.h.
Referenced by ArrowHeadMatrix< X, K >::getElement(), and ArrowHeadMatrix< X, K >::Solve().
template<class X , int K> const int ArrowHeadMatrix< X, K >::_order private
Definition at line 134 of file esbgkbase/ArrowHeadMatrix.h.
Referenced by ArrowHeadMatrix< X, K >::DummySolve(), ArrowHeadMatrix< X, K >::getElement(), ArrowHeadMatrix< X, K >::getTraceAbs(), ArrowHeadMatrix< X, K >::multiply(), ArrowHeadMatrix< X, K >::operator()(), ArrowHeadMatrix< X, K >::print(), ArrowHeadMatrix< X, K >::printElement(), ArrowHeadMatrix< X, K >::smoothGS(), ArrowHeadMatrix< X, K >::Solve(), ArrowHeadMatrix< X, K >::SolveBotCol(), and ArrowHeadMatrix< X, K >::SolveDiag().
template<class X , int K> int ArrowHeadMatrix< X, K >::_order private
Definition at line 270 of file phononbase/ArrowHeadMatrix.h.
template<class X , int K> VectorXKArray ArrowHeadMatrix< X, K >::_r private
Definition at line 137 of file esbgkbase/ArrowHeadMatrix.h.
Referenced by ArrowHeadMatrix< X, K >::ArrowHeadMatrix(), ArrowHeadMatrix< X, K >::getElement(), ArrowHeadMatrix< X, K >::multiply(), ArrowHeadMatrix< X, K >::Solve(), and ArrowHeadMatrix< X, K >::zero().
template<class X , int K> TArray ArrowHeadMatrix< X, K >::_values private
Definition at line 269 of file phononbase/ArrowHeadMatrix.h.
Referenced by ArrowHeadMatrix< X, K >::ArrowHeadMatrix(), ArrowHeadMatrix< X, K >::getElement(), ArrowHeadMatrix< X, K >::getTraceAbs(), ArrowHeadMatrix< X, K >::multiply(), ArrowHeadMatrix< X, K >::ones(), ArrowHeadMatrix< X, K >::operator()(), ArrowHeadMatrix< X, K >::printElement(), and ArrowHeadMatrix< X, K >::zero().
template<class X , int K> VectorXK ArrowHeadMatrix< X, K >::_xl private
Definition at line 141 of file esbgkbase/ArrowHeadMatrix.h.
Referenced by ArrowHeadMatrix< X, K >::ArrowHeadMatrix(), and ArrowHeadMatrix< X, K >::Solve().
The documentation for this class was generated from the following file:
esbgkbase/ArrowHeadMatrix.h