Memosa-FVM: GradientMatrix< T_Scalar >::PairWiseAssembler Class Reference
GradientMatrix< T_Scalar >::PairWiseAssembler Class Reference
#include <GradientMatrix.h>
Public Member Functions
PairWiseAssembler (Array< Coord > &coeffs, const Array< Vector< int, 2 > > &pairToCol)
Coord & getCoeff01 (const int np)
Coord & getCoeff10 (const int np)
Private Attributes
Array< Coord > & _coeffs
const Array< Vector< int, 2 > > & _pairToCol
Detailed Description
template<class T_Scalar>
class GradientMatrix< T_Scalar >::PairWiseAssembler
Definition at line 154 of file GradientMatrix.h.
Constructor & Destructor Documentation
template<class T_Scalar> GradientMatrix< T_Scalar >::PairWiseAssembler::PairWiseAssembler (Array< Coord > & coeffs, const Array< Vector< int, 2 > > & pairToCol) inline
Definition at line 157 of file GradientMatrix.h.
                                                               :
       _coeffs(coeffs),
       _pairToCol(pairToCol)
     {}
Member Function Documentation
template<class T_Scalar> Coord& GradientMatrix< T_Scalar >::PairWiseAssembler::getCoeff01 (const int np) inline
Definition at line 163 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::PairWiseAssembler::_coeffs, and GradientMatrix< T_Scalar >::PairWiseAssembler::_pairToCol.
Referenced by GradientModel< Vector< T, 3 > >::compute(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), and GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D().
     {
       return _coeffs[_pairToCol[np][0]];
     }
template<class T_Scalar> Coord& GradientMatrix< T_Scalar >::PairWiseAssembler::getCoeff10 (const int np) inline
Definition at line 168 of file GradientMatrix.h.
References GradientMatrix< T_Scalar >::PairWiseAssembler::_coeffs, and GradientMatrix< T_Scalar >::PairWiseAssembler::_pairToCol.
Referenced by GradientModel< Vector< T, 3 > >::compute(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), and GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D().
     {
       return _coeffs[_pairToCol[np][1]];
     }
Member Data Documentation
template<class T_Scalar> Array<Coord>& GradientMatrix< T_Scalar >::PairWiseAssembler::_coeffs private
Definition at line 175 of file GradientMatrix.h.
Referenced by GradientMatrix< T_Scalar >::PairWiseAssembler::getCoeff01(), and GradientMatrix< T_Scalar >::PairWiseAssembler::getCoeff10().
template<class T_Scalar> const Array<Vector<int,2> >& GradientMatrix< T_Scalar >::PairWiseAssembler::_pairToCol private
Definition at line 176 of file GradientMatrix.h.
Referenced by GradientMatrix< T_Scalar >::PairWiseAssembler::getCoeff01(), and GradientMatrix< T_Scalar >::PairWiseAssembler::getCoeff10().
The documentation for this class was generated from the following file:
GradientMatrix.h