Memosa-FVM: PhononInterface< X > Class Template Reference
PhononInterface< X > Class Template Reference
#include <PhononInterface.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< int > IntArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Array< X > XArray
typedef Vector< X, 3 > VectorX3
typedef Array< VectorX3 > VectorX3Array
typedef Kspace< X > Xkspace
typedef kvol< X > Xkvol
typedef pmode< X > Xmode
typedef Xmode::Refl_pair Refl_pair
Public Member Functions
PhononInterface (const FaceGroup &fg, const Mesh &mesh, const Mesh &otherMesh, const GeomFields &geomFields, const Xkspace &kspace, const Xkspace &kspaceOther, PhononModelOptions< X > &opts)
PhononModelOptions< X > & getOptions ()
void applyInterfaceCondition (int f, const X refl, const X trans) const
void applyInterfaceCondition (T_Scalar bRefl, T_Scalar bTrans) const
Protected Attributes
const FaceGroup & _fg
const StorageSite & _faces
const StorageSite & _cells
const StorageSite & _otherCells
const Array< int > & _ibType
const CRConnectivity & _faceCells
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
PhononModelOptions< X > & _options
const Xkspace & _kspace
const Xkspace & _kspaceOther
const int _fg_id
const FaceGroup & _otherfg
const StorageSite & _otherFaces
const CRConnectivity & _otherFaceCells
const TArray & _faceAreaMagOther
const VectorT3Array & _faceAreaOther
Detailed Description
template<class X>
class PhononInterface< X >
Definition at line 26 of file PhononInterface.h.
Member Typedef Documentation
template<class X> typedef Array<int> PhononInterface< X >::IntArray
Definition at line 32 of file PhononInterface.h.
template<class X> typedef Xmode::Refl_pair PhononInterface< X >::Refl_pair
Definition at line 44 of file PhononInterface.h.
template<class X> typedef NumTypeTraits<X>::T_Scalar PhononInterface< X >::T_Scalar
Definition at line 30 of file PhononInterface.h.
template<class X> typedef Array<T_Scalar> PhononInterface< X >::TArray
Definition at line 34 of file PhononInterface.h.
template<class X> typedef Vector<T_Scalar,3> PhononInterface< X >::VectorT3
Definition at line 35 of file PhononInterface.h.
template<class X> typedef Array<VectorT3> PhononInterface< X >::VectorT3Array
Definition at line 36 of file PhononInterface.h.
template<class X> typedef Vector<X,3> PhononInterface< X >::VectorX3
Definition at line 39 of file PhononInterface.h.
template<class X> typedef Array<VectorX3> PhononInterface< X >::VectorX3Array
Definition at line 40 of file PhononInterface.h.
template<class X> typedef Array<X> PhononInterface< X >::XArray
Definition at line 38 of file PhononInterface.h.
template<class X> typedef Kspace<X> PhononInterface< X >::Xkspace
Definition at line 41 of file PhononInterface.h.
template<class X> typedef kvol<X> PhononInterface< X >::Xkvol
Definition at line 42 of file PhononInterface.h.
template<class X> typedef pmode<X> PhononInterface< X >::Xmode
Definition at line 43 of file PhononInterface.h.
Constructor & Destructor Documentation
template<class X> PhononInterface< X >::PhononInterface (const FaceGroup & fg, const Mesh & mesh, const Mesh & otherMesh, const GeomFields & geomFields, const Xkspace & kspace, const Xkspace & kspaceOther, PhononModelOptions< X > & opts) inline
Definition at line 46 of file PhononInterface.h.
                                             :
     _fg(fg),
     _faces(fg.site),
     _cells(mesh.getCells()),
     _otherCells(otherMesh.getCells()),
     _ibType(dynamic_cast<const IntArray&>(geomFields.ibType[_cells])),
     _faceCells(mesh.getFaceCells(_faces)),
     _areaMagField(geomFields.areaMag),
     _faceAreaMag(dynamic_cast<const TArray&>(_areaMagField[_faces])),
     _areaField(geomFields.area),
     _faceArea(dynamic_cast<const VectorT3Array&>(_areaField[_faces])),
     _options(opts),
     _kspace(kspace),
     _kspaceOther(kspaceOther),
     _fg_id(fg.id),
     _otherfg(otherMesh.getFaceGroup(fg.id)),
     _otherFaces(_otherfg.site),
     _otherFaceCells(otherMesh.getFaceCells(_otherFaces)),
     _faceAreaMagOther(dynamic_cast<const TArray&>(_areaMagField[_otherFaces])),
     _faceAreaOther(dynamic_cast<const VectorT3Array&>(_areaField[_otherFaces]))
   {}
Member Function Documentation
template<class X> void PhononInterface< X >::applyInterfaceCondition (int f, const X refl, const X trans) const inline
Definition at line 79 of file PhononInterface.h.
References PhononInterface< X >::_cells, PhononInterface< X >::_faceArea, PhononInterface< X >::_faceAreaMag, PhononInterface< X >::_faceAreaMagOther, PhononInterface< X >::_faceAreaOther, PhononInterface< X >::_faceCells, PhononInterface< X >::_ibType, PhononInterface< X >::_kspace, PhononInterface< X >::_kspaceOther, PhononInterface< X >::_otherCells, PhononInterface< X >::_otherFaceCells, kvol< T >::getdk3(), pmode< T >::getfield(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), StorageSite::getSelfCount(), pmode< T >::getv(), Mesh::IBTYPE_FLUID, and sqrt().
Referenced by PhononInterface< X >::applyInterfaceCondition(), and PhononModel< T >::callBoundaryConditions().
   {
     int c0 = _faceCells(f,0);
     int c1 = _faceCells(f,1);
     T_Scalar sign(NumTypeTraits<T_Scalar>::getUnity());
     if (c1 < _cells.getSelfCount())
        {
          // c0 is ghost cell and c1 is boundry cell, so swap cell numbers
          // so that c1p refers to the ghost cell in the following
          int temp = c0;
          c0 = c1;
          c1 = temp;
          sign *= -1.0;
        }
     X tot_in = 0.;  //total incoming energy (to wall)
     X tot_dk3 = 0.; //total weight of incoming energy
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     // current mesh
     // sum up energy incoming to boundary (from domain)
     int numK=_kspace.getlength();
     for (int k=0;k<numK;k++)
       {
         Xkvol& kv=_kspace.getkvol(k);
         X dk3=kv.getdk3();
         int numM=kv.getmodenum();
         for (int m=0;m<numM;m++) //mode loop beg
           {
             Xmode& mode=kv.getmode(m);
             Field& efield=mode.getfield();
             VectorT3 vg = mode.getv();     // phonon group velocity
             XArray& e_val = dynamic_cast< XArray&>(efield[_cells]);  // e"
             const VectorT3 en = sign*(_faceArea[f]/_faceAreaMag[f]);  //outward normal unit vector to face
             const VectorT3 sn = vg/sqrt(pow(vg[0],2)+pow(vg[1],2)+pow(vg[2],2));
             const X sn_dot_en = sn[0]*en[0]+sn[1]*en[1]+sn[2]*en[2];
             const X vg_dot_en = vg[0]*en[0]+vg[1]*en[1]+vg[2]*en[2];
             if (sn_dot_en > T_Scalar(0.0))
               {
                 tot_in+=e_val[c0]*dk3*vg_dot_en;
                 tot_dk3+=vg_dot_en*dk3;
               }
             else
               {
                 e_val[c1]=0.;
               }
           } //mode loop end
       }
     const X diff_refl = tot_in/tot_dk3; // value for e" leaving the wall
     // other mesh
     int c0other = _otherFaceCells(f,0);
     int c1other = _otherFaceCells(f,1);
     T_Scalar sign2(NumTypeTraits<T_Scalar>::getUnity());
     if (c1other < _otherCells.getSelfCount())
        {
          // c0 is ghost cell and c1 is boundry cell, so swap cell numbers
          // so that c1p refers to the ghost cell in the following
          int temp = c0other;
          c0other = c1other;
          c1other = temp;
          sign2 *= -1.0;
        }
     X tot_in_other = 0.;  //total incoming energy (to wall)
     X tot_dk3_other = 0.; //total weight of incoming energy
     // sum up energy incoming to boundary (from domain)
     int numKOther=_kspaceOther.getlength();
     for (int k=0;k<numKOther;k++)
       {
         Xkvol& kv=_kspaceOther.getkvol(k);
         X dk3=kv.getdk3();
         int numM=kv.getmodenum();
         for (int m=0;m<numM;m++) //mode loop beg
           {
             Xmode& mode=kv.getmode(m);
             Field& efield=mode.getfield();
             VectorT3 vg = mode.getv();     // phonon group velocity
             XArray& e_val = dynamic_cast< XArray&>(efield[_otherCells]);  // e"
             const VectorT3 en = sign2*(_faceAreaOther[f]/_faceAreaMagOther[f]);  //outward normal unit vector to face
             const VectorT3 sn = vg/sqrt(pow(vg[0],2)+pow(vg[1],2)+pow(vg[2],2));
             const X sn_dot_en = sn[0]*en[0]+sn[1]*en[1]+sn[2]*en[2];
             const X vg_dot_en = vg[0]*en[0]+vg[1]*en[1]+vg[2]*en[2];
             if (sn_dot_en > T_Scalar(0.0))
               {
                 tot_in_other+=e_val[c0other]*dk3*vg_dot_en;
                 tot_dk3_other+=vg_dot_en*dk3;
               }
             else
               {
                 //e_val[c1]=0.;
               }
           } //mode loop end
       }
     const X diff_trans = tot_in_other/tot_dk3; // value for e" leaving the wall
     // assign values for incoming (upwinded) and outgoing (reflected) to/from wall
     for (int k=0;k<numK;k++)
       {
         Xkvol& kv=_kspace.getkvol(k);
         int numM=kv.getmodenum();
         for (int m=0;m<numM;m++) //mode loop beg
           {
             Xmode& mode=kv.getmode(m);
             Field& efield=mode.getfield();
             VectorT3 vg = mode.getv();     // phonon group velocity
             XArray& e_val = dynamic_cast<XArray&>(efield[_cells]);  // e"
             const VectorT3 en = sign*(_faceArea[f]/_faceAreaMag[f]);  //normal unit vector to face
             const X vg_dot_en = vg[0]*en[0]+vg[1]*en[1]+vg[2]*en[2];
             if (vg_dot_en > T_Scalar(0.0))
               {
                 /*Refl_pair& rpairs=mode.getReflpair(_fg_id);
                 X w1=rpairs.first.first;
                 X w2=rpairs.second.first;
                 int k1=rpairs.first.second;
                 int k2=rpairs.second.second;
                 Xmode& mode1=_kspace.getkvol(k1).getmode(m);
                 Xmode& mode2=_kspace.getkvol(k2).getmode(m);
                 Field& field1=mode1.getfield();
                 Field& field2=mode2.getfield();
                 XArray& e_val1=dynamic_cast<XArray&>(field1[_cells]);
                 XArray& e_val2=dynamic_cast<XArray&>(field2[_cells]);
                 e_val1[c1]+=refl*w1*e_val[c0];
                 e_val2[c1]+=refl*w2*e_val[c0];*/
                 e_val[c1]=e_val[c0];    // upwinded value
               }
             else
               {
                 e_val[c1]+=refl*diff_refl;  // diffusely reflected value
                 e_val[c1]+=trans*diff_trans; // diffusely transmitted value
               }
           } //mode loop end
       }
   }
template<class X> void PhononInterface< X >::applyInterfaceCondition (T_Scalar bRefl, T_Scalar bTrans) const inline
Definition at line 240 of file PhononInterface.h.
References PhononInterface< X >::_faces, PhononInterface< X >::applyInterfaceCondition(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyInterfaceCondition(i,bRefl,bTrans);
   }
template<class X> PhononModelOptions<X>& PhononInterface< X >::getOptions () inline
Definition at line 76 of file PhononInterface.h.
References PhononInterface< X >::_options.
 {return _options;}
Member Data Documentation
template<class X> const Field& PhononInterface< X >::_areaField protected
Definition at line 257 of file PhononInterface.h.
template<class X> const Field& PhononInterface< X >::_areaMagField protected
Definition at line 255 of file PhononInterface.h.
template<class X> const StorageSite& PhononInterface< X >::_cells protected
Definition at line 251 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const VectorT3Array& PhononInterface< X >::_faceArea protected
Definition at line 258 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const TArray& PhononInterface< X >::_faceAreaMag protected
Definition at line 256 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const TArray& PhononInterface< X >::_faceAreaMagOther protected
Definition at line 266 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const VectorT3Array& PhononInterface< X >::_faceAreaOther protected
Definition at line 267 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const CRConnectivity& PhononInterface< X >::_faceCells protected
Definition at line 254 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const StorageSite& PhononInterface< X >::_faces protected
Definition at line 250 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const FaceGroup& PhononInterface< X >::_fg protected
Definition at line 249 of file PhononInterface.h.
template<class X> const int PhononInterface< X >::_fg_id protected
Definition at line 262 of file PhononInterface.h.
template<class X> const Array<int>& PhononInterface< X >::_ibType protected
Definition at line 253 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const Xkspace& PhononInterface< X >::_kspace protected
Definition at line 260 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const Xkspace& PhononInterface< X >::_kspaceOther protected
Definition at line 261 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> PhononModelOptions<X>& PhononInterface< X >::_options protected
Definition at line 259 of file PhononInterface.h.
Referenced by PhononInterface< X >::getOptions().
template<class X> const StorageSite& PhononInterface< X >::_otherCells protected
Definition at line 252 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const CRConnectivity& PhononInterface< X >::_otherFaceCells protected
Definition at line 265 of file PhononInterface.h.
Referenced by PhononInterface< X >::applyInterfaceCondition().
template<class X> const StorageSite& PhononInterface< X >::_otherFaces protected
Definition at line 264 of file PhononInterface.h.
template<class X> const FaceGroup& PhononInterface< X >::_otherfg protected
Definition at line 263 of file PhononInterface.h.
The documentation for this class was generated from the following file:
PhononInterface.h