Memosa-FVM: PlateBCS< X, Diag, OffDiag > Class Template Reference
PlateBCS< X, Diag, OffDiag > Class Template Reference
#include <PlateModel_impl.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef FluxJacobianMatrix
< Diag, X > FMatrix
typedef DiagonalMatrix< Diag, X > BBMatrix
typedef Array< Diag > DiagArray
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
PlateBCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
X applyDirichletBC (int f, const X &bValue) const
X applyDirichletBC (const X &bValue) const
X applyDirichletBC (const FloatValEvaluator< X > &bValue) const
X applyCantileverBC (const int f, const X &specifiedFlux) const
X applyNeumannBC (const int f, const X &specifiedFlux) const
X applyNeumannBC (const X &bFlux) const
X applyZeroDerivativeBC () const
X applyNeumannBC (const FloatValEvaluator< X > &bFlux) const
void applyInterfaceBC (const int f) const
void applyInterfaceBC () const
void applySymmetryBC () const
Protected Attributes
const StorageSite & _faces
const StorageSite & _cells
const CRConnectivity & _faceCells
const Field & _varField
const MultiField::ArrayIndex _xIndex
CCMatrix & _dRdX
CCAssembler & _assembler
DiagArray & _dRdXDiag
XArray & _x
XArray & _r
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
const VectorT3Array & _faceCoord
const VectorT3Array & _cellCoord
Detailed Description
template<class X, class Diag, class OffDiag>
class PlateBCS< X, Diag, OffDiag >
Definition at line 38 of file PlateModel_impl.h.
Member Typedef Documentation
template<class X, class Diag, class OffDiag> typedef DiagonalMatrix<Diag,X> PlateBCS< X, Diag, OffDiag >::BBMatrix
Definition at line 51 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> typedef CCMatrix::PairWiseAssembler PlateBCS< X, Diag, OffDiag >::CCAssembler
Definition at line 48 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> typedef CRMatrix<Diag,OffDiag,X> PlateBCS< X, Diag, OffDiag >::CCMatrix
Definition at line 47 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Array<Diag> PlateBCS< X, Diag, OffDiag >::DiagArray
Definition at line 53 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> typedef FluxJacobianMatrix<Diag,X> PlateBCS< X, Diag, OffDiag >::FMatrix
Definition at line 50 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Array<OffDiag> PlateBCS< X, Diag, OffDiag >::OffDiagArray
Definition at line 54 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> typedef NumTypeTraits<X>::T_Scalar PlateBCS< X, Diag, OffDiag >::T_Scalar
Definition at line 42 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Array<T_Scalar> PlateBCS< X, Diag, OffDiag >::TArray
Definition at line 44 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Vector<T_Scalar,3> PlateBCS< X, Diag, OffDiag >::VectorT3
Definition at line 45 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Array<VectorT3> PlateBCS< X, Diag, OffDiag >::VectorT3Array
Definition at line 57 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Array<X> PlateBCS< X, Diag, OffDiag >::XArray
Definition at line 56 of file PlateModel_impl.h.
Constructor & Destructor Documentation
template<class X, class Diag, class OffDiag> PlateBCS< X, Diag, OffDiag >::PlateBCS (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, Field & varField, MultiFieldMatrix & matrix, MultiField & xField, MultiField & rField) inline
Definition at line 60 of file PlateModel_impl.h.
                                                      :
     _faces(faces),
     _cells(mesh.getCells()),
     _faceCells(mesh.getFaceCells(_faces)),
     _varField(varField),
     _xIndex(&_varField,&_cells),
     _dRdX(dynamic_cast<CCMatrix&>(matrix.getMatrix(_xIndex,_xIndex))),
     _assembler(_dRdX.getPairWiseAssembler(_faceCells)),
     _dRdXDiag(_dRdX.getDiag()),
     _x(dynamic_cast<XArray&>(xField[_xIndex])),
     _r(dynamic_cast<XArray&>(rField[_xIndex])),
     _areaMagField(geomFields.areaMag),
     _faceAreaMag(dynamic_cast<const TArray&>(_areaMagField[_faces])),
     _areaField(geomFields.area),
     _faceArea(dynamic_cast<const VectorT3Array&>(_areaField[_faces])),
     _faceCoord(dynamic_cast<const VectorT3Array&>(geomFields.coordinate[_faces])),
     _cellCoord(dynamic_cast<const VectorT3Array&>(geomFields.coordinate[_cells]))
   {}
Member Function Documentation
template<class X, class Diag, class OffDiag> X PlateBCS< X, Diag, OffDiag >::applyCantileverBC (const int f, const X & specifiedFlux) const inline
Definition at line 115 of file PlateModel_impl.h.
References PlateBCS< X, Diag, OffDiag >::_cellCoord, PlateBCS< X, Diag, OffDiag >::_dRdX, PlateBCS< X, Diag, OffDiag >::_faceArea, PlateBCS< X, Diag, OffDiag >::_faceCells, PlateBCS< X, Diag, OffDiag >::_faceCoord, PlateBCS< X, Diag, OffDiag >::_r, and CRMatrix< T_Diag, T_OffDiag, X >::setBoundary().
Referenced by PlateModel< T >::Impl::linearizeDeformation().
   {
     //const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     const X fluxB = -_r[c1];
     VectorT3 dzeta1 = _faceCoord[f]-_cellCoord[c1];
     // the current value of flux and its Jacobians
     X dFlux;
     dFlux[0]= (-(specifiedFlux[0]*_faceArea[f][0] +
                  specifiedFlux[1]*_faceArea[f][1])*dzeta1[0])
       - fluxB[0];
     dFlux[1]= (-(specifiedFlux[0]*_faceArea[f][0] +
                  specifiedFlux[1]*_faceArea[f][1])*dzeta1[1])
       - fluxB[1];
     dFlux[2]= (specifiedFlux[0]*_faceArea[f][0] +
                specifiedFlux[1]*_faceArea[f][1])
       - fluxB[2];
     // setup the equation for the boundary value; the coefficients
     // are already computed so just need to set the rhs
     _r[c1] = dFlux;
     // _dRdX.eliminate(c1,_r);
     // mark this row as a "boundary" row so that we will update it
     // after the overall system is solved
     _dRdX.setBoundary(c1);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> X PlateBCS< X, Diag, OffDiag >::applyDirichletBC (int f, const X & bValue) const inline
Definition at line 84 of file PlateModel_impl.h.
References PlateBCS< X, Diag, OffDiag >::_dRdX, PlateBCS< X, Diag, OffDiag >::_faceCells, PlateBCS< X, Diag, OffDiag >::_r, PlateBCS< X, Diag, OffDiag >::_x, and CRMatrix< T_Diag, T_OffDiag, X >::eliminateDirichlet().
Referenced by PlateBCS< X, Diag, OffDiag >::applyDirichletBC(), and PlateModel< T >::Impl::linearizeDeformation().
   {
     const int c1 = _faceCells(f,1);
     const X fluxB = -_r[c1];
     const X dXC1 = bValue - _x[c1];
     _dRdX.eliminateDirichlet(c1,_r,dXC1);
     _x[c1] = bValue;
     _r[c1] = NumTypeTraits<X>::getZero();
     return fluxB;
   }
template<class X, class Diag, class OffDiag> X PlateBCS< X, Diag, OffDiag >::applyDirichletBC (const X & bValue) const inline
Definition at line 99 of file PlateModel_impl.h.
References PlateBCS< X, Diag, OffDiag >::_faces, PlateBCS< X, Diag, OffDiag >::applyDirichletBC(), and StorageSite::getCount().
   {
     X fluxB(NumTypeTraits<X>::getZero());
     for(int i=0; i<_faces.getCount(); i++)
       fluxB += applyDirichletBC(i,bValue);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> X PlateBCS< X, Diag, OffDiag >::applyDirichletBC (const FloatValEvaluator< X > & bValue) const inline
Definition at line 107 of file PlateModel_impl.h.
References PlateBCS< X, Diag, OffDiag >::_faces, PlateBCS< X, Diag, OffDiag >::applyDirichletBC(), and StorageSite::getCount().
   {
     X fluxB(NumTypeTraits<X>::getZero());
     for(int i=0; i<_faces.getCount(); i++)
       fluxB += applyDirichletBC(i,bValue[i]);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> void PlateBCS< X, Diag, OffDiag >::applyInterfaceBC (const int f) const inline
Definition at line 210 of file PlateModel_impl.h.
References PlateBCS< X, Diag, OffDiag >::_assembler, PlateBCS< X, Diag, OffDiag >::_cells, PlateBCS< X, Diag, OffDiag >::_faceCells, PlateBCS< X, Diag, OffDiag >::_r, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), and StorageSite::getSelfCount().
   {
     // do nothing
     // the boundary cell could be either c0 or c1 at an interface
     int cb = _faceCells(f,1);
     T_Scalar sign(NumTypeTraits<T_Scalar>::getUnity());
     if (cb < _cells.getSelfCount())
     {
         cb = _faceCells(f,0);
         sign *= -1.0;
     }
     _r[cb] = T_Scalar(0);
     if (sign>0)
       _assembler.getCoeff10(f) = NumTypeTraits<OffDiag>::getZero();
     else
       _assembler.getCoeff01(f) = NumTypeTraits<OffDiag>::getZero();
   }
template<class X, class Diag, class OffDiag> void PlateBCS< X, Diag, OffDiag >::applyInterfaceBC () const inline
Definition at line 232 of file PlateModel_impl.h.
   {
     // do nothing
   }
template<class X, class Diag, class OffDiag> X PlateBCS< X, Diag, OffDiag >::applyNeumannBC (const int f, const X & specifiedFlux) const inline
Definition at line 147 of file PlateModel_impl.h.
References PlateBCS< X, Diag, OffDiag >::_dRdX, PlateBCS< X, Diag, OffDiag >::_faceAreaMag, PlateBCS< X, Diag, OffDiag >::_faceCells, PlateBCS< X, Diag, OffDiag >::_r, and CRMatrix< T_Diag, T_OffDiag, X >::setBoundary().
Referenced by PlateBCS< X, Diag, OffDiag >::applyNeumannBC(), and PlateModel< T >::Impl::linearizeDeformation().
   {
     //const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     const X fluxB = -_r[c1];
     // the current value of flux and its Jacobians
     const X dFlux = specifiedFlux*_faceAreaMag[f] - fluxB;
     // setup the equation for the boundary value; the coefficients
     // are already computed so just need to set the rhs
     _r[c1] = dFlux;
     // _dRdX.eliminate(c1,_r);
     // mark this row as a "boundary" row so that we will update it
     // after the overall system is solved
     _dRdX.setBoundary(c1);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> X PlateBCS< X, Diag, OffDiag >::applyNeumannBC (const X & bFlux) const inline
Definition at line 169 of file PlateModel_impl.h.
References PlateBCS< X, Diag, OffDiag >::_faces, PlateBCS< X, Diag, OffDiag >::applyNeumannBC(), and StorageSite::getCount().
   {
     X fluxB(NumTypeTraits<X>::getZero());
     for(int i=0; i<_faces.getCount(); i++)
       fluxB += applyNeumannBC(i,bFlux);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> X PlateBCS< X, Diag, OffDiag >::applyNeumannBC (const FloatValEvaluator< X > & bFlux) const inline
Definition at line 202 of file PlateModel_impl.h.
References PlateBCS< X, Diag, OffDiag >::_faces, PlateBCS< X, Diag, OffDiag >::applyNeumannBC(), and StorageSite::getCount().
   {
     X fluxB(NumTypeTraits<X>::getZero());
     for(int i=0; i<_faces.getCount(); i++)
       fluxB += applyNeumannBC(i,bFlux[i]);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> void PlateBCS< X, Diag, OffDiag >::applySymmetryBC () const inline
Definition at line 237 of file PlateModel_impl.h.
References PlateBCS< X, Diag, OffDiag >::_assembler, PlateBCS< X, Diag, OffDiag >::_dRdX, PlateBCS< X, Diag, OffDiag >::_faceArea, PlateBCS< X, Diag, OffDiag >::_faceAreaMag, PlateBCS< X, Diag, OffDiag >::_faceCells, PlateBCS< X, Diag, OffDiag >::_faces, PlateBCS< X, Diag, OffDiag >::_r, PlateBCS< X, Diag, OffDiag >::_x, dot(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), and CRMatrix< T_Diag, T_OffDiag, X >::setDirichlet().
   {
     for(int f=0; f<this->_faces.getCount(); f++)
     {
         const int c0 = this->_faceCells(f,0);
         const int c1 = this->_faceCells(f,1);
         const VectorT3 en = this->_faceArea[f]/this->_faceAreaMag[f];
         const T_Scalar xC0_dotn = dot(this->_x[c0],en);
         const X xB = this->_x[c0] - 2.*xC0_dotn * en;
         Diag dxBdxC0(Diag::getZero());
         dxBdxC0(0,0) =  1.0 - 2.*en[0]*en[0];
         dxBdxC0(0,1) =  - 2.*en[0]*en[1];
         dxBdxC0(0,2) =  - 2.*en[0]*en[2];
         dxBdxC0(1,0) =  - 2.*en[1]*en[0];
         dxBdxC0(1,1) =  1.0 - 2.*en[1]*en[1];
         dxBdxC0(1,2) =  - 2.*en[1]*en[2];
         dxBdxC0(2,0) =  - 2.*en[2]*en[0];
         dxBdxC0(2,1) =  - 2.*en[2]*en[1];
         dxBdxC0(2,2) =  1.0 - 2.*en[2]*en[2];
         const X xc1mxB = xB-this->_x[c1];
         // boundary value equation
         // set all neighbour coeffs to zero first and ap to  -1
         this->_dRdX.setDirichlet(c1);
         // dependance on c0
         this->_assembler.getCoeff10(f) = dxBdxC0;
         this->_r[c1] = xc1mxB;
     }
   }
template<class X, class Diag, class OffDiag> X PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC () const inline
Definition at line 178 of file PlateModel_impl.h.
References PlateBCS< X, Diag, OffDiag >::_assembler, PlateBCS< X, Diag, OffDiag >::_dRdX, PlateBCS< X, Diag, OffDiag >::_dRdXDiag, PlateBCS< X, Diag, OffDiag >::_faceCells, PlateBCS< X, Diag, OffDiag >::_faces, PlateBCS< X, Diag, OffDiag >::_r, PlateBCS< X, Diag, OffDiag >::_x, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), and CRMatrix< T_Diag, T_OffDiag, X >::setBoundary().
   {
     X fluxTotal(NumTypeTraits<X>::getZero());
     for(int f=0; f<_faces.getCount(); f++)
     {
         const int c0 = _faceCells(f,0);
         const int c1 = _faceCells(f,1);
         const X fluxB = -_r[c1];
         // setup the equation for the boundary value; we want xb to be equal to xc
         _r[c1] = _x[c0] - _x[c1];
         _dRdXDiag[c1]  = -NumTypeTraits<Diag>::getUnity();
         this->_assembler.getCoeff10(f)  = NumTypeTraits<OffDiag>::getUnity();
         // mark this row as a "boundary" row so that we will update it
         // after the overall system is solved
         _dRdX.setBoundary(c1);
         fluxTotal += fluxB;
     }
     return fluxTotal;
   }
Member Data Documentation
template<class X, class Diag, class OffDiag> const Field& PlateBCS< X, Diag, OffDiag >::_areaField protected
Definition at line 291 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> const Field& PlateBCS< X, Diag, OffDiag >::_areaMagField protected
Definition at line 289 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> CCAssembler& PlateBCS< X, Diag, OffDiag >::_assembler protected
Definition at line 285 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyInterfaceBC(), PlateBCS< X, Diag, OffDiag >::applySymmetryBC(), and PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> const VectorT3Array& PlateBCS< X, Diag, OffDiag >::_cellCoord protected
Definition at line 294 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyCantileverBC().
template<class X, class Diag, class OffDiag> const StorageSite& PlateBCS< X, Diag, OffDiag >::_cells protected
Definition at line 280 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyInterfaceBC().
template<class X, class Diag, class OffDiag> CCMatrix& PlateBCS< X, Diag, OffDiag >::_dRdX protected
Definition at line 284 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyCantileverBC(), PlateBCS< X, Diag, OffDiag >::applyDirichletBC(), PlateBCS< X, Diag, OffDiag >::applyNeumannBC(), PlateBCS< X, Diag, OffDiag >::applySymmetryBC(), and PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> DiagArray& PlateBCS< X, Diag, OffDiag >::_dRdXDiag protected
Definition at line 286 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> const VectorT3Array& PlateBCS< X, Diag, OffDiag >::_faceArea protected
Definition at line 292 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyCantileverBC(), and PlateBCS< X, Diag, OffDiag >::applySymmetryBC().
template<class X, class Diag, class OffDiag> const TArray& PlateBCS< X, Diag, OffDiag >::_faceAreaMag protected
Definition at line 290 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyNeumannBC(), and PlateBCS< X, Diag, OffDiag >::applySymmetryBC().
template<class X, class Diag, class OffDiag> const CRConnectivity& PlateBCS< X, Diag, OffDiag >::_faceCells protected
Definition at line 281 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyCantileverBC(), PlateBCS< X, Diag, OffDiag >::applyDirichletBC(), PlateBCS< X, Diag, OffDiag >::applyInterfaceBC(), PlateBCS< X, Diag, OffDiag >::applyNeumannBC(), PlateBCS< X, Diag, OffDiag >::applySymmetryBC(), and PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> const VectorT3Array& PlateBCS< X, Diag, OffDiag >::_faceCoord protected
Definition at line 293 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyCantileverBC().
template<class X, class Diag, class OffDiag> const StorageSite& PlateBCS< X, Diag, OffDiag >::_faces protected
Definition at line 279 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyDirichletBC(), PlateBCS< X, Diag, OffDiag >::applyNeumannBC(), PlateBCS< X, Diag, OffDiag >::applySymmetryBC(), and PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> XArray& PlateBCS< X, Diag, OffDiag >::_r protected
Definition at line 288 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyCantileverBC(), PlateBCS< X, Diag, OffDiag >::applyDirichletBC(), PlateBCS< X, Diag, OffDiag >::applyInterfaceBC(), PlateBCS< X, Diag, OffDiag >::applyNeumannBC(), PlateBCS< X, Diag, OffDiag >::applySymmetryBC(), and PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> const Field& PlateBCS< X, Diag, OffDiag >::_varField protected
Definition at line 282 of file PlateModel_impl.h.
template<class X, class Diag, class OffDiag> XArray& PlateBCS< X, Diag, OffDiag >::_x protected
Definition at line 287 of file PlateModel_impl.h.
Referenced by PlateBCS< X, Diag, OffDiag >::applyDirichletBC(), PlateBCS< X, Diag, OffDiag >::applySymmetryBC(), and PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> const MultiField::ArrayIndex PlateBCS< X, Diag, OffDiag >::_xIndex protected
Definition at line 283 of file PlateModel_impl.h.
The documentation for this class was generated from the following file:
PlateModel_impl.h