Memosa-FVM: BatteryPCDiffusionDiscretization< X, Diag, OffDiag > Class Template Reference
BatteryPCDiffusionDiscretization< X, Diag, OffDiag > Class Template Reference
#include <BatteryPCDiffusionDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Gradient< X > XGrad
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Array< XGrad > GradArray
typedef Gradient< T_Scalar > TGrad
Public Member Functions
BatteryPCDiffusionDiscretization (const MeshList &meshes, const GeomFields &geomFields, Field &varField, const Field &diffusivityField, const Field &varGradientField)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
Field & _varField
const Field & _diffusivityField
const Field & _varGradientField
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class BatteryPCDiffusionDiscretization< X, Diag, OffDiag >
Definition at line 35 of file BatteryPCDiffusionDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 43 of file BatteryPCDiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 41 of file BatteryPCDiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 42 of file BatteryPCDiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<XGrad> BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::GradArray
Definition at line 53 of file BatteryPCDiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 39 of file BatteryPCDiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::TArray
Definition at line 49 of file BatteryPCDiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Gradient<T_Scalar> BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::TGrad
Definition at line 67 of file BatteryPCDiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::VectorT3
Definition at line 50 of file BatteryPCDiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::VectorT3Array
Definition at line 51 of file BatteryPCDiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::XArray
Definition at line 48 of file BatteryPCDiffusionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Gradient<X> BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::XGrad
Definition at line 45 of file BatteryPCDiffusionDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::BatteryPCDiffusionDiscretization (const MeshList & meshes, const GeomFields & geomFields, Field & varField, const Field & diffusivityField, const Field & varGradientField) inline
Definition at line 69 of file BatteryPCDiffusionDiscretization.h.
                                                          :
       Discretization(meshes),
       _geomFields(geomFields),
       _varField(varField),
       _diffusivityField(diffusivityField),
       _varGradientField(varGradientField)
   {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 81 of file BatteryPCDiffusionDiscretization.h.
References BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::_diffusivityField, BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::_geomFields, BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::_varField, BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::_varGradientField, GeomFields::area, GeomFields::areaMag, GeomFields::coordinate, dot(), Mesh::getAllFaceGroups(), Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), Mesh::getDimension(), Mesh::getFaceCells(), MultiFieldMatrix::getMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), harmonicAverageVector(), FaceGroup::site, and GeomFields::volume.
   {
     const StorageSite& cells = mesh.getCells();
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,
                                                              cVarIndex));
     const VectorT3Array& cellCentroid =
       dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[cells]);
     const TArray& cellVolume =
       dynamic_cast<const TArray&>(_geomFields.volume[cells]);
     DiagArray& diag = matrix.getDiag();
     const XArray& xCell = dynamic_cast<const XArray&>(xField[cVarIndex]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     const GradArray& xGradCell =
       dynamic_cast<const GradArray&>(_varGradientField[cells]);
     const XArray& diffCell =
       dynamic_cast<const XArray&>(_diffusivityField[cells]);
     foreach(const FaceGroupPtr fgPtr, mesh.getAllFaceGroups())
       {
         const FaceGroup& fg = *fgPtr;
         const StorageSite& faces = fg.site;
         const int nFaces = faces.getCount();
         const CRConnectivity& faceCells = mesh.getFaceCells(faces);
         const VectorT3Array& faceArea =
           dynamic_cast<const VectorT3Array&>(_geomFields.area[faces]);
         const TArray& faceAreaMag =
           dynamic_cast<const TArray&>(_geomFields.areaMag[faces]);
         //const VectorT3Array& faceCentroid = dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[faces]);
         CCAssembler& assembler = matrix.getPairWiseAssembler(faceCells);
         int XLength = 0;
         NumTypeTraits<X>::getShape(&XLength);
         for(int f=0; f<nFaces; f++)
           {
             const int c0 = faceCells(f,0);
             const int c1 = faceCells(f,1);
             T_Scalar vol0 = cellVolume[c0];
             T_Scalar vol1 = cellVolume[c1];
             VectorT3 ds=cellCentroid[c1]-cellCentroid[c0];
             // for ib faces ignore the solid cell and use the face centroid for diff metric
             /*
               if (((ibType[c0] == Mesh::IBTYPE_FLUID)
               && (ibType[c1] == Mesh::IBTYPE_BOUNDARY)) ||
               ((ibType[c1] == Mesh::IBTYPE_FLUID)
               && (ibType[c0] == Mesh::IBTYPE_BOUNDARY)))
               {
               if (ibType[c0] == Mesh::IBTYPE_FLUID)
               {
               vol1 = 0.;
               ds = faceCentroid[f]-cellCentroid[c0];
               }
               else
               {
               vol0 = 0.;
               ds = cellCentroid[c1]-faceCentroid[f];
               }
               }*/
             //for(int v=0; v<XLength; v++)
             X faceDiffusivity(NumTypeTraits<X>::getZero());
             if (vol0 == 0.)
               faceDiffusivity = (diffCell[c1]);
             else if (vol1 == 0.)
               faceDiffusivity = (diffCell[c0]);
             else
               {
                 faceDiffusivity = harmonicAverageVector(diffCell[c0],diffCell[c1]);
               }
             const T_Scalar diffMetric = faceAreaMag[f]*faceAreaMag[f]/dot(faceArea[f],ds);
             //do things element-wise manually
             // Each 'v' below is on equation
             // first equation is potential, followed by species equation, then thermal
             for(int v=0; v<XLength; v++)
               {
                 const T_Scalar diffCoeff = (faceDiffusivity[v])*diffMetric;
                 const VectorT3 secondaryCoeff = (faceDiffusivity[v])*(faceArea[f]-ds*diffMetric);
                 //extract this v's gradient
                 const XGrad gradF_X = ((xGradCell[c0]*vol0+xGradCell[c1]*vol1)/(vol0+vol1));
                 TGrad gradF(NumTypeTraits<TGrad>::getZero());
                 gradF[0] = gradF_X[0][v];
                 gradF[1] = gradF_X[1][v];
                 if (mesh.getDimension() == 3)
                   gradF[2] = gradF_X[2][v];
                 const T_Scalar dFluxSecondary = gradF*secondaryCoeff;
                 const T_Scalar dFlux = diffCoeff*((xCell[c1])[v]-(xCell[c0])[v]) + dFluxSecondary;
                 (rCell[c0])[v] += dFlux;
                 (rCell[c1])[v] -= dFlux;
                 (assembler.getCoeff01(f))[v] +=diffCoeff;
                 (assembler.getCoeff10(f))[v] +=diffCoeff;
                 (diag[c0])[v] -= diffCoeff;
                 (diag[c1])[v] -= diffCoeff;
               }
           }
       }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const Field& BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::_diffusivityField private
Definition at line 204 of file BatteryPCDiffusionDiscretization.h.
Referenced by BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 202 of file BatteryPCDiffusionDiscretization.h.
Referenced by BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > Field& BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 203 of file BatteryPCDiffusionDiscretization.h.
Referenced by BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::_varGradientField private
Definition at line 205 of file BatteryPCDiffusionDiscretization.h.
Referenced by BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
BatteryPCDiffusionDiscretization.h