Memosa-FVM: LinearizeDielectric< X, Diag, OffDiag > Class Template Reference
LinearizeDielectric< X, Diag, OffDiag > Class Template Reference
#include <LinearizeDielectric.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef Array< T_Scalar > TArray
typedef Array< X > XArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
LinearizeDielectric (const GeomFields &geomFields, const Field &dielectric_constant, const T_Scalar dielectric_thickness, Field &varField, const T_Scalar source=0.0)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Private Attributes
const GeomFields & _geomFields
Field & _varField
const Field & _dielectric_constant
const T_Scalar _dielectric_thickness
const T_Scalar _source
Detailed Description
template<class X, class Diag, class OffDiag>
class LinearizeDielectric< X, Diag, OffDiag >
Definition at line 24 of file LinearizeDielectric.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> LinearizeDielectric< X, Diag, OffDiag >::CCMatrix
Definition at line 28 of file LinearizeDielectric.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray LinearizeDielectric< X, Diag, OffDiag >::DiagArray
Definition at line 29 of file LinearizeDielectric.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar LinearizeDielectric< X, Diag, OffDiag >::T_Scalar
Definition at line 27 of file LinearizeDielectric.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> LinearizeDielectric< X, Diag, OffDiag >::TArray
Definition at line 30 of file LinearizeDielectric.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> LinearizeDielectric< X, Diag, OffDiag >::VectorT3
Definition at line 32 of file LinearizeDielectric.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> LinearizeDielectric< X, Diag, OffDiag >::VectorT3Array
Definition at line 33 of file LinearizeDielectric.h.
template<class X , class Diag , class OffDiag > typedef Array<X> LinearizeDielectric< X, Diag, OffDiag >::XArray
Definition at line 31 of file LinearizeDielectric.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > LinearizeDielectric< X, Diag, OffDiag >::LinearizeDielectric (const GeomFields & geomFields, const Field & dielectric_constant, const T_Scalar dielectric_thickness, Field & varField, const T_Scalar source = 0.0) inline
Definition at line 36 of file LinearizeDielectric.h.
                                                 :
     _geomFields(geomFields),
     _varField(varField),
     _dielectric_constant(dielectric_constant),
     _dielectric_thickness(dielectric_thickness),
     _source(source)
     {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void LinearizeDielectric< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline
Definition at line 49 of file LinearizeDielectric.h.
References LinearizeDielectric< X, Diag, OffDiag >::_dielectric_constant, LinearizeDielectric< X, Diag, OffDiag >::_dielectric_thickness, LinearizeDielectric< X, Diag, OffDiag >::_geomFields, LinearizeDielectric< X, Diag, OffDiag >::_varField, GeomFields::areaMag, GeomFields::coordinate, Mesh::getCellCells(), Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::getCoeff(), CRConnectivity::getCount(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), MultiFieldMatrix::getMatrix(), Mesh::getParentFaceGroupSite(), StorageSite::getSelfCount(), harmonicAverage(), and mag().
   {
     const StorageSite& cells = mesh.getCells();
     const StorageSite& faces = mesh.getParentFaceGroupSite();
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     const TArray& faceAreaMag =
       dynamic_cast<const TArray&>(_geomFields.areaMag[faces]);
     const XArray& xCell = dynamic_cast<const XArray&>(xField[cVarIndex]);
     const VectorT3Array& cellCentroid =
       dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[cells]);
     const CRConnectivity& cellCells = mesh.getCellCells();
     const TArray& dcCell =
       dynamic_cast<const TArray&>(_dielectric_constant[cells]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     DiagArray& diag = matrix.getDiag();
     const int nCells = cells.getSelfCount();
     for (int c=0; c<nCells; c++)
       {
         const int c0 = c;
         const int nb = cellCells.getCount(c);
         if (nb!=2)
           throw CException("invalid connectivity in shellMesh");
         //source term
         const T_Scalar volume = faceAreaMag[c0] * _dielectric_thickness;
         const T_Scalar src = 0.0;
         rCell[c0] += src*volume;
         //diffusion term
         for (int i=0; i<nb; i++){
           const int c1 = cellCells(c,i);
           OffDiag& offdiag = matrix.getCoeff(c0,  c1);
           VectorT3 ds=cellCentroid[c1]-cellCentroid[c0];
           T_Scalar dsMag = mag(ds);
           const T_Scalar dc = harmonicAverage(dcCell[c0], dcCell[c1]);
           const T_Scalar diffCoeff = dc*faceAreaMag[c0]/(dsMag + 0.5*_dielectric_thickness);
           const X dFlux = diffCoeff*(xCell[c1]-xCell[c0]);
           rCell[c0] += dFlux;
           offdiag = diffCoeff;
           diag[c0] -= diffCoeff;
         }
       }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const Field& LinearizeDielectric< X, Diag, OffDiag >::_dielectric_constant private
Definition at line 119 of file LinearizeDielectric.h.
Referenced by LinearizeDielectric< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const T_Scalar LinearizeDielectric< X, Diag, OffDiag >::_dielectric_thickness private
Definition at line 120 of file LinearizeDielectric.h.
Referenced by LinearizeDielectric< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& LinearizeDielectric< X, Diag, OffDiag >::_geomFields private
Definition at line 117 of file LinearizeDielectric.h.
Referenced by LinearizeDielectric< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const T_Scalar LinearizeDielectric< X, Diag, OffDiag >::_source private
Definition at line 121 of file LinearizeDielectric.h.
template<class X , class Diag , class OffDiag > Field& LinearizeDielectric< X, Diag, OffDiag >::_varField private
Definition at line 118 of file LinearizeDielectric.h.
Referenced by LinearizeDielectric< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
LinearizeDielectric.h