Memosa-FVM: ScalarArrayWriter< T > Class Template Reference
ScalarArrayWriter< T > Class Template Reference
#include <ArrayWriter.h>
Public Types
typedef T ElementType
typedef Array< ElementType > ArrayType
typedef NumTypeTraits< T >
::T_BuiltIn T_BuiltIn
Public Member Functions
ScalarArrayWriter (const bool binary, const int vectorComponent, const int atypeComponent)
void write (FILE *fp, const Array< T > &array, const int iBeg, int count, const Array< bool > *mask=0)
Public Member Functions inherited from ArrayWriter
ArrayWriter (const bool binary, const int vectorComponent, const int atypeComponent)
virtual ~ArrayWriter ()
template<class T >
void writeFloats (FILE *fp, const T *data, const int count, const int stride, const Array< bool > *mask=0)
Additional Inherited Members
Protected Attributes inherited from ArrayWriter
const bool _binary
const int _vectorComponent
const int _atypeComponent
Detailed Description
template<class T>
class ScalarArrayWriter< T >
Definition at line 48 of file ArrayWriter.h.
Member Typedef Documentation
template<class T> typedef Array<ElementType> ScalarArrayWriter< T >::ArrayType
Definition at line 52 of file ArrayWriter.h.
template<class T> typedef T ScalarArrayWriter< T >::ElementType
Definition at line 51 of file ArrayWriter.h.
template<class T> typedef NumTypeTraits<T>::T_BuiltIn ScalarArrayWriter< T >::T_BuiltIn
Definition at line 53 of file ArrayWriter.h.
Constructor & Destructor Documentation
template<class T> ScalarArrayWriter< T >::ScalarArrayWriter (const bool binary, const int vectorComponent, const int atypeComponent) inline
Definition at line 55 of file ArrayWriter.h.
                                               :
     ArrayWriter(binary,vectorComponent,atypeComponent)
   {}
Member Function Documentation
template<class T> void ScalarArrayWriter< T >::write (FILE * fp, const Array< T > & array, const int iBeg, int count, const Array< bool > * mask = 0) inline
Definition at line 60 of file ArrayWriter.h.
References ArrayWriter::_atypeComponent, Array< T >::getData(), Array< T >::getLength(), and ArrayWriter::writeFloats().
Referenced by FluentDataExporter< T >::writeScalarField().
   {
     const int length = array.getLength();
     if (count == -1)
       count = length;
     else if (count+iBeg > length)
       throw CException("invalid count ");
     ElementType *dataArray = (ElementType*)(array.getData());
     T_BuiltIn *data = (T_BuiltIn*)(dataArray+iBeg);
     int stride = 1;
 #ifdef USING_ATYPE_TANGENT
     if ((_atypeComponent == 0) || (_atypeComponent == 1))
     {
         data += _atypeComponent;
         stride = 2;
     }
     else
       throw CException("invalid component for Tangent");
 #endif
     writeFloats(fp,data,count,stride,mask);
   }
The documentation for this class was generated from the following file:
ArrayWriter.h