Memosa-FVM: AMG Class Reference
AMG Class Reference
#include <AMG.h>
Public Types
enum CycleType { V_CYCLE, W_CYCLE, F_CYCLE }
enum SmootherType { GAUSS_SEIDEL, JACOBI }
Public Member Functions
AMG ()
virtual ~AMG ()
DEFINE_TYPENAME ("AMG")
virtual MFRPtr solve (LinearSystem &ls)
virtual void smooth (LinearSystem &ls)
virtual void setMergeLevelSize (int ls_size)
void redirectPrintToFile (const string &fname)
void redirectPrintToScreen ()
int getTotalIterations () const
virtual void cleanup ()
Public Member Functions inherited from LinearSolver
LinearSolver ()
Public Attributes
int maxCoarseLevels
int nPreSweeps
int nPostSweeps
int coarseGroupSize
double weightRatioThreshold
CycleType cycleType
SmootherType smootherType
bool scaleCorrections
Public Attributes inherited from LinearSolver
int nMaxIterations
int verbosity
double relativeTolerance
double absoluteTolerance
Private Member Functions
AMG (const AMG &)
void createCoarseLevels ()
void doSweeps (const int nSweeps, const int level)
void cycle (CycleType cycleType, const int level)
void flipComm ()
Private Attributes
LinearSystem * _finestLinearSystem
vector< shared_ptr
< LinearSystem > > _coarseLinearSystems
shared_ptr< LinearSystemMerger > _mergeLS
int _mergeLevelSize
int _mergeLevel
bool _isMerge
int _totalIterations
streambuf * m_psbuf
streambuf * m_backup
ofstream m_filestr
bool _isCOMMWORLD
Static Private Attributes
static int amg_indx = 0
Detailed Description
Solve a linear system using algebraic multigrid.
Definition at line 27 of file AMG.h.
Member Enumeration Documentation
enum AMG::CycleType
Enumerator
V_CYCLE
W_CYCLE
F_CYCLE
Definition at line 31 of file AMG.h.
     {
       V_CYCLE,
       W_CYCLE,
       F_CYCLE
     };
enum AMG::SmootherType
Enumerator
GAUSS_SEIDEL
JACOBI
Definition at line 38 of file AMG.h.
     {
       GAUSS_SEIDEL,
       JACOBI
     };
Constructor & Destructor Documentation
AMG::AMG ()
Definition at line 15 of file AMG.cpp.
References logCtor.
          :
   maxCoarseLevels(30),
   nPreSweeps(0),
   nPostSweeps(1),
   coarseGroupSize(2),
   weightRatioThreshold(0.65),
   cycleType(V_CYCLE),
   smootherType(GAUSS_SEIDEL),
   scaleCorrections(true),
   _finestLinearSystem(0),
   _mergeLevelSize(0),
   _mergeLevel(-1),
   _isMerge(false),
   _totalIterations(0),
 #ifdef FVM_PARALLEL
   _commTarget(MPI::COMM_WORLD),
 #endif
   _isCOMMWORLD(true)
 {
   logCtor();
 }
AMG::~AMG () virtual
Definition at line 38 of file AMG.cpp.
References logDtor.
 {
   logDtor();
 }
AMG::AMG (const AMG &) private
Member Function Documentation
void AMG::cleanup () virtual
Implements LinearSolver.
Definition at line 213 of file AMG.cpp.
References _coarseLinearSystems, and _finestLinearSystem.
 {
   _finestLinearSystem = 0;
   _coarseLinearSystems.clear();
 }
void AMG::createCoarseLevels () private
Definition at line 150 of file AMG.cpp.
References _coarseLinearSystems, _finestLinearSystem, _isMerge, _mergeLevel, _mergeLevelSize, _mergeLS, coarseGroupSize, LinearSystem::createCoarse(), flipComm(), MultiFieldMatrix::getLocalSize(), LinearSystem::getMatrix(), LinearSystem::isSymmetric, maxCoarseLevels, LinearSolver::verbosity, and weightRatioThreshold.
Referenced by smooth(), and solve().
 {
   _coarseLinearSystems.clear();
   for(int n=0; n<maxCoarseLevels; n++)
   {
       LinearSystem& fineLS = (n == 0) ?
         *_finestLinearSystem : *_coarseLinearSystems[n-1];
       shared_ptr<LinearSystem>
         coarseLS(fineLS.createCoarse(coarseGroupSize,weightRatioThreshold));
       coarseLS->isSymmetric = fineLS.isSymmetric;
      int isContinue =  int( fineLS.getMatrix().getLocalSize() != coarseLS->getMatrix().getLocalSize() );
 #ifdef FVM_PARALLEL
      _commTarget.Allreduce(MPI::IN_PLACE, &isContinue, 1, MPI::INT, MPI::SUM);
 #endif
      if ( isContinue == 0 )
             break;
 #ifdef FVM_PARALLEL
      _coarseLinearSystems.push_back(coarseLS);
       int min_size = coarseLS->getMatrix().getMinSize( _commTarget );
       if ( verbosity > 1 && MPI::COMM_WORLD.Get_rank() == 0 )
         cout << " proc_id = " << MPI::COMM_WORLD.Get_rank() << "  Created coarse level " << n << " of size "
              << min_size  << endl;
       if ( min_size <= 3  )
         break;
       if ( coarseLS->getMatrix().getMergeSize( _commTarget ) < _mergeLevelSize &&  _mergeLevel == -1  && _isMerge ){
          _mergeLevel = n+1;
          set<int> group;
          int size = MPI::COMM_WORLD.Get_size();
          for ( int i = 0; i < size; i++ )
             group.insert(i);
          _mergeLS = shared_ptr<LinearSystemMerger> ( new LinearSystemMerger( 0, group, *coarseLS ) );
          _mergeLS->gatherMatrix();
          _coarseLinearSystems.push_back( _mergeLS->getLS() );
           n++;
           flipComm(); //this change to COMM_WORLD to one-processedGROUP
       }
 #endif
 #ifndef FVM_PARALLEL
     if ( coarseLS->getMatrix().getSize() <= 3 )
        break;
     if ( verbosity > 1 )
         cout << "Created coarse level " << n << " of size " << coarseLS->getMatrix().getSize() << endl;
     _coarseLinearSystems.push_back(coarseLS);
 #endif
   }
 }
void AMG::cycle (CycleType cycleType, const int level) private
Definition at line 71 of file AMG.cpp.
References _coarseLinearSystems, _finestLinearSystem, _mergeLevel, _mergeLS, MultiFieldMatrix::computeResidual(), MultiFieldMatrix::correctSolution(), doSweeps(), MultiField::dotWith(), F_CYCLE, LinearSystem::getB(), LinearSystem::getCoarseIndex(), LinearSystem::getDelta(), LinearSystem::getMatrix(), LinearSystem::getResidual(), MultiFieldMatrix::injectResidual(), LinearSystem::isSymmetric, nPostSweeps, nPreSweeps, MultiFieldMatrix::quadProduct(), scaleCorrections, V_CYCLE, W_CYCLE, and MultiField::zero().
Referenced by smooth(), and solve().
 {
   doSweeps(nPreSweeps,level);
   if (level < (int)_coarseLinearSystems.size())
   {
       LinearSystem& fineLS = (level == 0) ?
         *_finestLinearSystem : *_coarseLinearSystems[level-1];
       LinearSystem& coarseLS = *_coarseLinearSystems[level];
       MultiFieldMatrix& fineMatrix = fineLS.getMatrix();
       fineMatrix.computeResidual(fineLS.getDelta(),fineLS.getB(),fineLS.getResidual());
       coarseLS.getB().zero();
       coarseLS.getDelta().zero();
       fineMatrix.injectResidual(fineLS.getCoarseIndex(),
                                 fineLS.getResidual(),
                                 coarseLS.getB());
       int nextLevel = level+1;
 #ifdef  FVM_PARALLEL
       if ( nextLevel == _mergeLevel )
       {
           _mergeLS->gatherB();
           nextLevel++;
       }
 #endif
      //if ( level == 4 )
      //   cycleType = W_CYCLE;
      cycle(cycleType,nextLevel);
       if (cycleType == W_CYCLE)
         cycle(W_CYCLE,nextLevel);
       else if (cycleType == F_CYCLE)
         cycle(V_CYCLE,nextLevel);
 #ifdef  FVM_PARALLEL
       if ( level+1 == _mergeLevel ) {
           _mergeLS->scatterDelta();
       }
 #endif
       MFRPtr scale;
       if (coarseLS.isSymmetric && scaleCorrections)
       {
           const MultiField& x = coarseLS.getDelta();
           const MultiField& b = coarseLS.getB();
           const MultiFieldMatrix& A = coarseLS.getMatrix();
           MFRPtr xb =  x.dotWith(b);
           xb->reduceSum();
           MFRPtr mxb = -(*xb);
           MFRPtr xTAx = A.quadProduct(x);
           xTAx->reduceSum();
           scale = (*mxb)/(*xTAx);
           scale->limit(1.0, 1.0);
       }
       fineMatrix.correctSolution(fineLS.getCoarseIndex(),
                                  fineLS.getDelta(),
                                  scale,
                                  coarseLS.getDelta())   ;
   }
 doSweeps(nPostSweeps,level);
 }
AMG::DEFINE_TYPENAME ("AMG")
void AMG::doSweeps (const int nSweeps, const int level) private
Definition at line 44 of file AMG.cpp.
References _coarseLinearSystems, _finestLinearSystem, MultiFieldMatrix::forwardGS(), GAUSS_SEIDEL, LinearSystem::getB(), LinearSystem::getDelta(), LinearSystem::getMatrix(), LinearSystem::getResidual(), MultiFieldMatrix::Jacobi(), MultiFieldMatrix::reverseGS(), and smootherType.
Referenced by cycle().
 {
   LinearSystem& ls = (level == 0) ?
     *_finestLinearSystem : *_coarseLinearSystems[level-1];
   const MultiFieldMatrix& m = ls.getMatrix();
   MultiField& delta = ls.getDelta();
   const MultiField& b = ls.getB();
   MultiField& r = ls.getResidual();
   for(int i=0; i<nSweeps; i++)
   {
       if (smootherType == GAUSS_SEIDEL)
       {
           m.forwardGS(delta,b,r);
           m.reverseGS(delta,b,r);
       }
       else
       {
           m.Jacobi(delta,b,r);
           m.Jacobi(delta,b,r);
       }
   }
 }
void AMG::flipComm () private
Definition at line 303 of file AMG.cpp.
References _isCOMMWORLD.
Referenced by createCoarseLevels().
 {
 #ifdef FVM_PARALLEL
    if ( _isCOMMWORLD ){
       int color   = ( MPI::COMM_WORLD.Get_rank() == 0 );
       int key     = MPI::COMM_WORLD.Get_rank();
       _commTarget = MPI::COMM_WORLD.Split( color, key );
       _isCOMMWORLD = !_isCOMMWORLD;
    } else {
       _commTarget = MPI::COMM_WORLD;
       _isCOMMWORLD = !_isCOMMWORLD;
    }
 #endif
 }
int AMG::getTotalIterations () const inline
Definition at line 69 of file AMG.h.
 { return _totalIterations;}
void AMG::redirectPrintToFile (const string & fname)
Definition at line 325 of file AMG.cpp.
References m_backup, m_filestr, and m_psbuf.
{
     m_filestr.open ( fname.c_str() );
     m_backup = cout.rdbuf();     // back up cout's streambuf
     m_psbuf = m_filestr.rdbuf();   // get file's streambuf
     cout.rdbuf(m_psbuf);
 }
void AMG::redirectPrintToScreen ()
Definition at line 334 of file AMG.cpp.
References m_backup, and m_filestr.
{
    cout.rdbuf(m_backup);        // restore cout's original streambuf
    m_filestr.close();
 }
virtual void AMG::setMergeLevelSize (int ls_size) inline virtual
Definition at line 53 of file AMG.h.
{
 #ifdef FVM_PARALLEL
       //_mergeLevelSize = ceil(  double(ls_size) / double(MPI::COMM_WORLD.Get_size()) );
        _mergeLevelSize = ls_size;
       _isMerge = true;
 #endif
 #ifndef FVM_PARALLEL
       _mergeLevelSize = ls_size;
       cout << " you can not set mergeLevelSize in serial version !!!!!!!!!!! " << endl;
       abort();
 #endif
 }
void AMG::smooth (LinearSystem & ls) virtual
Implements LinearSolver.
Definition at line 286 of file AMG.cpp.
References _finestLinearSystem, createCoarseLevels(), cycle(), and cycleType.
 {
   if (_finestLinearSystem != &ls)
   {
       _finestLinearSystem = &ls;
       createCoarseLevels( );
   }
   _finestLinearSystem = &ls;
   {
       cycle(cycleType,0);
   }
 }
MFRPtr AMG::solve (LinearSystem & ls) virtual
Implements LinearSolver.
Definition at line 220 of file AMG.cpp.
References _finestLinearSystem, _totalIterations, LinearSolver::absoluteTolerance, MultiFieldMatrix::computeResidual(), createCoarseLevels(), cycle(), cycleType, LinearSystem::getB(), LinearSystem::getDelta(), LinearSystem::getMatrix(), MultiField::getOneNorm(), LinearSystem::getResidual(), LinearSolver::nMaxIterations, LinearSolver::relativeTolerance, MultiField::sync(), and LinearSolver::verbosity.
Referenced by main().
 {
     if (_finestLinearSystem != &ls)
      {
        _finestLinearSystem = &ls;
        createCoarseLevels();
      }
     _finestLinearSystem = &ls;
   const MultiFieldMatrix& finestMatrix = _finestLinearSystem->getMatrix();
   finestMatrix.computeResidual(_finestLinearSystem->getDelta(),
                                _finestLinearSystem->getB(),
                                _finestLinearSystem->getResidual());
   MFRPtr rNorm0(_finestLinearSystem->getResidual().getOneNorm());
 #ifdef FVM_PARALLEL
   if (verbosity >0 && MPI::COMM_WORLD.Get_rank() == 0 )
     cout << "0: " << *rNorm0 <<  endl;
 #endif
 #ifndef FVM_PARALLEL
    if ( verbosity > 0 )
       cout << "0: " << *rNorm0 << endl;
 #endif
   if (*rNorm0 < absoluteTolerance )
     return rNorm0;
   for(int i=1; i<nMaxIterations; i++)
   {
       _totalIterations++;
       cycle(cycleType,0);
       finestMatrix.computeResidual(_finestLinearSystem->getDelta(),
                                    _finestLinearSystem->getB(),
                                    _finestLinearSystem->getResidual());
       MFRPtr rNorm(_finestLinearSystem->getResidual().getOneNorm());
       MFRPtr normRatio(rNorm->normalize(*rNorm0));
 #ifndef FVM_PARALLEL
     if (verbosity >0  )
         cout << i << ": " <<  *rNorm << endl;
 #endif
 #ifdef FVM_PARALLEL
      if (*rNorm < absoluteTolerance || *normRatio < relativeTolerance || i == nMaxIterations-1)
         if (verbosity >0 && MPI::COMM_WORLD.Get_rank() == 0  )
         cout <<i << ": " <<   *rNorm << endl;
 #endif
       if (*rNorm < absoluteTolerance || *normRatio < relativeTolerance)
          break;
   }
   _finestLinearSystem->getDelta().sync();
   return rNorm0;
 }
Member Data Documentation
vector<shared_ptr<LinearSystem> > AMG::_coarseLinearSystems private
Definition at line 87 of file AMG.h.
Referenced by cleanup(), createCoarseLevels(), cycle(), and doSweeps().
LinearSystem* AMG::_finestLinearSystem private
Definition at line 86 of file AMG.h.
Referenced by cleanup(), createCoarseLevels(), cycle(), doSweeps(), smooth(), and solve().
bool AMG::_isCOMMWORLD private
Definition at line 109 of file AMG.h.
Referenced by flipComm().
bool AMG::_isMerge private
Definition at line 99 of file AMG.h.
Referenced by createCoarseLevels().
int AMG::_mergeLevel private
Definition at line 98 of file AMG.h.
Referenced by createCoarseLevels(), and cycle().
int AMG::_mergeLevelSize private
Definition at line 97 of file AMG.h.
Referenced by createCoarseLevels().
shared_ptr<LinearSystemMerger> AMG::_mergeLS private
Definition at line 88 of file AMG.h.
Referenced by createCoarseLevels(), and cycle().
int AMG::_totalIterations private
Definition at line 100 of file AMG.h.
Referenced by solve().
int AMG::amg_indx = 0 static private
Definition at line 95 of file AMG.h.
int AMG::coarseGroupSize
Definition at line 77 of file AMG.h.
Referenced by createCoarseLevels().
CycleType AMG::cycleType
Definition at line 79 of file AMG.h.
Referenced by smooth(), and solve().
streambuf* AMG::m_backup private
Definition at line 107 of file AMG.h.
Referenced by redirectPrintToFile(), and redirectPrintToScreen().
ofstream AMG::m_filestr private
Definition at line 108 of file AMG.h.
Referenced by redirectPrintToFile(), and redirectPrintToScreen().
streambuf* AMG::m_psbuf private
Definition at line 106 of file AMG.h.
Referenced by redirectPrintToFile().
int AMG::maxCoarseLevels
Definition at line 74 of file AMG.h.
Referenced by createCoarseLevels().
int AMG::nPostSweeps
Definition at line 76 of file AMG.h.
Referenced by cycle().
int AMG::nPreSweeps
Definition at line 75 of file AMG.h.
Referenced by cycle().
bool AMG::scaleCorrections
Definition at line 81 of file AMG.h.
Referenced by cycle().
SmootherType AMG::smootherType
Definition at line 80 of file AMG.h.
Referenced by doSweeps().
double AMG::weightRatioThreshold
Definition at line 78 of file AMG.h.
Referenced by createCoarseLevels().
The documentation for this class was generated from the following files:
AMG.h
AMG.cpp