Memosa-FVM: PhononBoundary< X > Class Template Reference
PhononBoundary< X > Class Template Reference
#include <PhononBoundary.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< int > IntArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Array< X > XArray
typedef Vector< X, 3 > VectorX3
typedef Array< VectorX3 > VectorX3Array
typedef Kspace< X > Xkspace
typedef kvol< X > Xkvol
typedef pmode< X > Xmode
typedef Xmode::Refl_pair Refl_pair
Public Member Functions
PhononBoundary (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, const Xkspace &kspace, PhononModelOptions< X > &opts, const int fg_id)
PhononModelOptions< X > & getOptions ()
void applyReflectingWall (int f, const X refl) const
void applyReflectingWall (FloatValEvaluator< X > &bRefl) const
void applyTemperatureWall (int f, const X Twall) const
void applyTemperatureWall (FloatValEvaluator< X > &bTemp) const
Protected Attributes
const StorageSite & _faces
const StorageSite & _cells
const Array< int > & _ibType
const CRConnectivity & _faceCells
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
PhononModelOptions< X > & _options
const Xkspace & _kspace
const int _fg_id
Detailed Description
template<class X>
class PhononBoundary< X >
Definition at line 26 of file PhononBoundary.h.
Member Typedef Documentation
template<class X> typedef Array<int> PhononBoundary< X >::IntArray
Definition at line 32 of file PhononBoundary.h.
template<class X> typedef Xmode::Refl_pair PhononBoundary< X >::Refl_pair
Definition at line 44 of file PhononBoundary.h.
template<class X> typedef NumTypeTraits<X>::T_Scalar PhononBoundary< X >::T_Scalar
Definition at line 30 of file PhononBoundary.h.
template<class X> typedef Array<T_Scalar> PhononBoundary< X >::TArray
Definition at line 34 of file PhononBoundary.h.
template<class X> typedef Vector<T_Scalar,3> PhononBoundary< X >::VectorT3
Definition at line 35 of file PhononBoundary.h.
template<class X> typedef Array<VectorT3> PhononBoundary< X >::VectorT3Array
Definition at line 36 of file PhononBoundary.h.
template<class X> typedef Vector<X,3> PhononBoundary< X >::VectorX3
Definition at line 39 of file PhononBoundary.h.
template<class X> typedef Array<VectorX3> PhononBoundary< X >::VectorX3Array
Definition at line 40 of file PhononBoundary.h.
template<class X> typedef Array<X> PhononBoundary< X >::XArray
Definition at line 38 of file PhononBoundary.h.
template<class X> typedef Kspace<X> PhononBoundary< X >::Xkspace
Definition at line 41 of file PhononBoundary.h.
template<class X> typedef kvol<X> PhononBoundary< X >::Xkvol
Definition at line 42 of file PhononBoundary.h.
template<class X> typedef pmode<X> PhononBoundary< X >::Xmode
Definition at line 43 of file PhononBoundary.h.
Constructor & Destructor Documentation
template<class X> PhononBoundary< X >::PhononBoundary (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, const Xkspace & kspace, PhononModelOptions< X > & opts, const int fg_id) inline
Definition at line 46 of file PhononBoundary.h.
                                 :
   _faces(faces),
     _cells(mesh.getCells()),
     _ibType(dynamic_cast<const IntArray&>(geomFields.ibType[_cells])),
     _faceCells(mesh.getFaceCells(_faces)),
     _areaMagField(geomFields.areaMag),
     _faceAreaMag(dynamic_cast<const TArray&>(_areaMagField[_faces])),
     _areaField(geomFields.area),
     _faceArea(dynamic_cast<const VectorT3Array&>(_areaField[_faces])),
     _options(opts),
     _kspace(kspace),
     _fg_id(fg_id)
   {}
Member Function Documentation
template<class X> void PhononBoundary< X >::applyReflectingWall (int f, const X refl) const inline
changed
Definition at line 68 of file PhononBoundary.h.
References PhononBoundary< X >::_cells, PhononBoundary< X >::_faceArea, PhononBoundary< X >::_faceAreaMag, PhononBoundary< X >::_faceCells, PhononBoundary< X >::_fg_id, PhononBoundary< X >::_ibType, PhononBoundary< X >::_kspace, kvol< T >::getdk3(), pmode< T >::getfield(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getReflpair(), pmode< T >::getv(), Mesh::IBTYPE_FLUID, and sqrt().
Referenced by PhononBoundary< X >::applyReflectingWall(), and PhononModel< T >::callBoundaryConditions().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     X tot_in = 0.;  //total incoming energy (to wall)
     X tot_dk3 = 0.; //total weight of incoming energy
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     // sum up energy incoming to boundary (from domain)
     int numK=_kspace.getlength();
     for (int k=0;k<numK;k++)
       {
         Xkvol& kv=_kspace.getkvol(k);
         X dk3=kv.getdk3();
         int numM=kv.getmodenum();
         for (int m=0;m<numM;m++) //mode loop beg
           {
             Xmode& mode=kv.getmode(m);
             Field& efield=mode.getfield();
             VectorT3 vg = mode.getv();     // phonon group velocity
             XArray& e_val = dynamic_cast< XArray&>(efield[_cells]);  // e"
             const VectorT3 en = _faceArea[f]/_faceAreaMag[f];  //normal unit vector to face
             const VectorT3 sn = vg/sqrt(pow(vg[0],2)+pow(vg[1],2)+pow(vg[2],2));
             const X sn_dot_en = sn[0]*en[0]+sn[1]*en[1]+sn[2]*en[2];
             const X vg_dot_en = vg[0]*en[0]+vg[1]*en[1]+vg[2]*en[2];
             if (sn_dot_en > T_Scalar(0.0))
               {
                 tot_in+=e_val[c0]*dk3*vg_dot_en;
                 tot_dk3+=vg_dot_en*dk3;
               }
             else
               {
                 e_val[c1]=0.;
               }
           } //mode loop end
       }
     const X diff_refl = tot_in/tot_dk3; // value for e" leaving the wall
     // assign values for incoming (upwinded) and outgoing (reflected) to/from wall
     for (int k=0;k<numK;k++)
       {
         Xkvol& kv=_kspace.getkvol(k);
         int numM=kv.getmodenum();
         for (int m=0;m<numM;m++) //mode loop beg
           {
             Xmode& mode=kv.getmode(m);
             Field& efield=mode.getfield();
             VectorT3 vg = mode.getv();     // phonon group velocity
             XArray& e_val = dynamic_cast<XArray&>(efield[_cells]);  // e"
             const VectorT3 en = _faceArea[f]/_faceAreaMag[f];  //normal unit vector to face
             const X vg_dot_en = vg[0]*en[0]+vg[1]*en[1]+vg[2]*en[2];
             if (vg_dot_en > T_Scalar(0.0))
               {
                 Refl_pair& rpairs=mode.getReflpair(_fg_id);
                 //X w1=rpairs.first.first;
                 //X w2=rpairs.second.first;
                 int k1=rpairs.first.second;
                 //int k2=rpairs.second.second;
                 Xmode& mode1=_kspace.getkvol(k1).getmode(m);
                 //Xmode& mode2=_kspace.getkvol(k2).getmode(m);
                 Field& field1=mode1.getfield();
                 //Field& field2=mode2.getfield();
                 XArray& e_val1=dynamic_cast<XArray&>(field1[_cells]);
                 //XArray& e_val2=dynamic_cast<XArray&>(field2[_cells]);
                 e_val1[c1]+=refl*e_val[c0];
                 //e_val2[c1]+=refl*w2*e_val[c0];
                 e_val[c1]=e_val[c0];    // upwinded value
               }
             else
               {
                 e_val[c1]+=(1-refl)*diff_refl;  // diffusely reflected value
               }
           } //mode loop end
       }
   }
template<class X> void PhononBoundary< X >::applyReflectingWall (FloatValEvaluator< X > & bRefl) const inline
Definition at line 158 of file PhononBoundary.h.
References PhononBoundary< X >::_faces, PhononBoundary< X >::applyReflectingWall(), and StorageSite::getCount().
   {
     for (int i=0; i<_faces.getCount();i++)
       applyReflectingWall(i,bRefl[i]);
   }
template<class X> void PhononBoundary< X >::applyTemperatureWall (int f, const X Twall) const inline
changed
Definition at line 165 of file PhononBoundary.h.
References PhononBoundary< X >::_cells, PhononBoundary< X >::_faceArea, PhononBoundary< X >::_faceAreaMag, PhononBoundary< X >::_faceCells, PhononBoundary< X >::_ibType, PhononBoundary< X >::_kspace, pmode< T >::calce0(), pmode< T >::getfield(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getv(), and Mesh::IBTYPE_FLUID.
Referenced by PhononBoundary< X >::applyTemperatureWall(), and PhononModel< T >::callBoundaryConditions().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     // sum up energy incoming to boundary (from domain)
     int numK=_kspace.getlength();
     for (int k=0;k<numK;k++)
       {
         Xkvol& kv=_kspace.getkvol(k);
         int numM=kv.getmodenum();
         for (int m=0;m<numM;m++) //mode loop beg
           {
             Xmode& mode=kv.getmode(m);
             Field& efield=mode.getfield();
             VectorX3 vg = mode.getv();
             XArray& e_val = dynamic_cast< XArray&>(efield[_cells]);  // e"
             const VectorX3 en = _faceArea[f]/_faceAreaMag[f];  //normal unit vector to face
             const X vg_dot_en = vg[0]*en[0]+vg[1]*en[1]+vg[2]*en[2];
             if (vg_dot_en > T_Scalar(0.0))
               {
                 e_val[c1]=e_val[c0];
               }
             else
               {
                 e_val[c1]=mode.calce0(Twall);
               }
           } //mode loop end
       }
   }
template<class X> void PhononBoundary< X >::applyTemperatureWall (FloatValEvaluator< X > & bTemp) const inline
Definition at line 204 of file PhononBoundary.h.
References PhononBoundary< X >::_faces, PhononBoundary< X >::applyTemperatureWall(), and StorageSite::getCount().
   {
     for (int j=0; j<_faces.getCount();j++)
       {
         applyTemperatureWall(j,bTemp[j]);
       }
   }
template<class X> PhononModelOptions<X>& PhononBoundary< X >::getOptions () inline
Definition at line 66 of file PhononBoundary.h.
References PhononBoundary< X >::_options.
 {return _options;}
Member Data Documentation
template<class X> const Field& PhononBoundary< X >::_areaField protected
Definition at line 359 of file PhononBoundary.h.
template<class X> const Field& PhononBoundary< X >::_areaMagField protected
Definition at line 357 of file PhononBoundary.h.
template<class X> const StorageSite& PhononBoundary< X >::_cells protected
Definition at line 354 of file PhononBoundary.h.
Referenced by PhononBoundary< X >::applyReflectingWall(), and PhononBoundary< X >::applyTemperatureWall().
template<class X> const VectorT3Array& PhononBoundary< X >::_faceArea protected
Definition at line 360 of file PhononBoundary.h.
Referenced by PhononBoundary< X >::applyReflectingWall(), and PhononBoundary< X >::applyTemperatureWall().
template<class X> const TArray& PhononBoundary< X >::_faceAreaMag protected
Definition at line 358 of file PhononBoundary.h.
Referenced by PhononBoundary< X >::applyReflectingWall(), and PhononBoundary< X >::applyTemperatureWall().
template<class X> const CRConnectivity& PhononBoundary< X >::_faceCells protected
Definition at line 356 of file PhononBoundary.h.
Referenced by PhononBoundary< X >::applyReflectingWall(), and PhononBoundary< X >::applyTemperatureWall().
template<class X> const StorageSite& PhononBoundary< X >::_faces protected
Definition at line 353 of file PhononBoundary.h.
Referenced by PhononBoundary< X >::applyReflectingWall(), and PhononBoundary< X >::applyTemperatureWall().
template<class X> const int PhononBoundary< X >::_fg_id protected
Definition at line 363 of file PhononBoundary.h.
Referenced by PhononBoundary< X >::applyReflectingWall().
template<class X> const Array<int>& PhononBoundary< X >::_ibType protected
Definition at line 355 of file PhononBoundary.h.
Referenced by PhononBoundary< X >::applyReflectingWall(), and PhononBoundary< X >::applyTemperatureWall().
template<class X> const Xkspace& PhononBoundary< X >::_kspace protected
Definition at line 362 of file PhononBoundary.h.
Referenced by PhononBoundary< X >::applyReflectingWall(), and PhononBoundary< X >::applyTemperatureWall().
template<class X> PhononModelOptions<X>& PhononBoundary< X >::_options protected
Definition at line 361 of file PhononBoundary.h.
Referenced by PhononBoundary< X >::getOptions().
The documentation for this class was generated from the following file:
PhononBoundary.h