Memosa-FVM: ArrayBase Class Reference
ArrayBase Class Reference abstract
#include <ArrayBase.h>
Public Member Functions
ArrayBase ()
virtual ~ArrayBase ()
virtual shared_ptr< ArrayBase > createOffsetArray (const int offset, const int size)=0
virtual void correct (const IContainer &coarseI, const IContainer &coarseIndexI, const IContainer *scaleI, const int length)=0
virtual void inject (IContainer &coarseI, const IContainer &coarseIndexI, const int length) const =0
virtual void scatter (ArrayBase &other_, const ArrayBase &indices, const int offset=0) const =0
virtual void gather (const ArrayBase &other_, const ArrayBase &indices, const int offset=0)=0
virtual void setSubsetFromSubset (const ArrayBase &other, const ArrayBase &fromIndices, const ArrayBase &toIndices)=0
virtual void copyPartial (const IContainer &oc, const int iBeg, const int iEnd)=0
virtual void zeroPartial (const int iBeg, const int iEnd)=0
virtual shared_ptr< ArrayBase > newSizedClone (const int size) const =0
virtual void copyFrom (const IContainer &a)=0
virtual ArrayBase & operator+= (const ArrayBase &a)=0
virtual ArrayBase & operator-= (const ArrayBase &a)=0
virtual ArrayBase & operator/= (const ArrayBase &a)=0
virtual ArrayBase & operator*= (const ArrayBase &a)=0
virtual shared_ptr< ArrayBase > operator- () const
virtual void limit (const double min, const double max)
virtual ArrayBase & safeDivide (const ArrayBase &a)=0
virtual ArrayBase & normalize (const ArrayBase &a)=0
virtual bool operator< (const double tolerance) const =0
virtual void setMax (const ArrayBase &a)=0
virtual void print (ostream &os) const =0
virtual ArrayBase & saxpy (const ArrayBase &alphabase, const ArrayBase &xbase)=0
virtual ArrayBase & msaxpy (const ArrayBase &alphabase, const ArrayBase &xbase)=0
virtual shared_ptr< ArrayBase > getOneNorm (const int lengthToUse) const =0
virtual shared_ptr< ArrayBase > dotWith (const ArrayBase &a, const int lengthToUse) const =0
virtual shared_ptr< ArrayBase > reduceSum () const =0
virtual void setSum (const ArrayBase &sumBase)=0
virtual int getDimension () const =0
virtual void getShape (int *shape) const =0
virtual void * getData () const =0
virtual int getDataSize () const =0
virtual int getLength () const =0
virtual PrimType getPrimType () const =0
Public Member Functions inherited from IContainer
IContainer ()
virtual ~IContainer ()
virtual void zero ()=0
IContainer & operator= (const IContainer &oc)
virtual shared_ptr< IContainer > newCopy () const =0
virtual shared_ptr< IContainer > newClone () const =0
Detailed Description
Definition at line 13 of file ArrayBase.h.
Constructor & Destructor Documentation
ArrayBase::ArrayBase () inline
Definition at line 17 of file ArrayBase.h.
 {}
virtual ArrayBase::~ArrayBase () inline virtual
Definition at line 18 of file ArrayBase.h.
 {}
Member Function Documentation
virtual void ArrayBase::copyFrom (const IContainer & a) pure virtual
Implements IContainer.
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiField::copyFrom(), and MultiFieldMatrix::solveBoundary().
virtual void ArrayBase::copyPartial (const IContainer & oc, const int iBeg, const int iEnd) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiFieldMatrix::computeResidual(), MultiFieldMatrix::forwardGS(), MultiFieldMatrix::Jacobi(), and MultiFieldMatrix::reverseGS().
virtual void ArrayBase::correct (const IContainer & coarseI, const IContainer & coarseIndexI, const IContainer * scaleI, const int length) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiFieldMatrix::correctSolution().
virtual shared_ptr<ArrayBase> ArrayBase::createOffsetArray (const int offset, const int size) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by Field::_create().
virtual shared_ptr<ArrayBase> ArrayBase::dotWith (const ArrayBase & a, const int lengthToUse) const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiField::dotWith().
virtual void ArrayBase::gather (const ArrayBase & other_, const ArrayBase & indices, const int offset = 0) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by Field::syncGather(), MultiField::syncGather(), Field::syncGatherLevel1(), MultiField::syncGatherLevel1(), Field::syncGatherVectorFields(), and Field::syncGatherVectorFieldsLevel1().
virtual void* ArrayBase::getData () const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by SpeciesModel< T >::Impl::getMassFractionResidual(), BatteryModel< T >::Impl::getPCResidual(), BatteryModel< T >::Impl::getPotentialResidual(), BatteryModel< T >::Impl::getSpeciesResidual(), BatteryModel< T >::Impl::getThermalResidual(), DirectSolver::solve(), MultiFieldReduction::sync(), MultiField::sync(), Mesh::syncCounts(), CRMatrix< T_Diag, T_OffDiag, X >::syncCounts(), Mesh::syncIndices(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), MultiField::syncLevel1(), Field::syncLocal(), Kspace< T >::syncLocal(), Field::syncLocalLevel1(), Field::syncLocalVectorFields(), Field::syncLocalVectorFieldsLevel1(), GradientMatrix< T_Scalar >::syncValues(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx().
virtual int ArrayBase::getDataSize () const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by DirectSolver::solve(), MultiFieldReduction::sync(), MultiField::sync(), Mesh::syncCounts(), CRMatrix< T_Diag, T_OffDiag, X >::syncCounts(), Mesh::syncIndices(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), MultiField::syncLevel1(), Field::syncLocal(), Kspace< T >::syncLocal(), Field::syncLocalLevel1(), Field::syncLocalVectorFields(), Field::syncLocalVectorFieldsLevel1(), GradientMatrix< T_Scalar >::syncValues(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx().
virtual int ArrayBase::getDimension () const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual int ArrayBase::getLength () const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by LinearSystem::createCoarse(), MultiField::createSyncGatherArraysLevel1(), MultiField::get_request_size_gather_level1(), MultiField::get_request_size_scatter_level1(), DirectSolver::solve(), MultiField::syncGatherLevel1(), MultiField::syncLevel1(), and MultiField::syncScatterLevel1().
virtual shared_ptr<ArrayBase> ArrayBase::getOneNorm (const int lengthToUse) const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiField::getOneNorm().
virtual PrimType ArrayBase::getPrimType () const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual void ArrayBase::getShape (int * shape) const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual void ArrayBase::inject (IContainer & coarseI, const IContainer & coarseIndexI, const int length) const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiFieldMatrix::injectResidual().
virtual void ArrayBase::limit (const double min, const double max) inline virtual
Reimplemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Definition at line 55 of file ArrayBase.h.
 {throw;}
virtual ArrayBase& ArrayBase::msaxpy (const ArrayBase & alphabase, const ArrayBase & xbase) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiField::msaxpy().
virtual shared_ptr<ArrayBase> ArrayBase::newSizedClone (const int size) const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by Field::createSyncGatherArrays(), MultiField::createSyncGatherArrays(), Field::createSyncGatherArraysLevel1(), MultiField::createSyncGatherArraysLevel1(), Field::createSyncGatherArraysVectorFields(), Field::createSyncGatherArraysVectorFieldsLevel1(), Field::syncScatter(), MultiField::syncScatter(), Field::syncScatterLevel1(), MultiField::syncScatterLevel1(), Field::syncScatterVectorFields(), and Field::syncScatterVectorFieldsLevel1().
virtual ArrayBase& ArrayBase::normalize (const ArrayBase & a) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiFieldReduction::normalize().
virtual ArrayBase& ArrayBase::operator*= (const ArrayBase & a) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual ArrayBase& ArrayBase::operator+= (const ArrayBase & a) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual shared_ptr<ArrayBase> ArrayBase::operator- () const inline virtual
Reimplemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Definition at line 54 of file ArrayBase.h.
 {throw;}
virtual ArrayBase& ArrayBase::operator-= (const ArrayBase & a) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual ArrayBase& ArrayBase::operator/= (const ArrayBase & a) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual bool ArrayBase::operator< (const double tolerance) const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual void ArrayBase::print (ostream & os) const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual shared_ptr<ArrayBase> ArrayBase::reduceSum () const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual ArrayBase& ArrayBase::safeDivide (const ArrayBase & a) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiFieldReduction::operator/().
virtual ArrayBase& ArrayBase::saxpy (const ArrayBase & alphabase, const ArrayBase & xbase) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiField::saxpy().
virtual void ArrayBase::scatter (ArrayBase & other_, const ArrayBase & indices, const int offset = 0) const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by Field::syncScatter(), MultiField::syncScatter(), Field::syncScatterLevel1(), MultiField::syncScatterLevel1(), Field::syncScatterVectorFields(), and Field::syncScatterVectorFieldsLevel1().
virtual void ArrayBase::setMax (const ArrayBase & a) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual void ArrayBase::setSubsetFromSubset (const ArrayBase & other, const ArrayBase & fromIndices, const ArrayBase & toIndices) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual void ArrayBase::setSum (const ArrayBase & sumBase) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
virtual void ArrayBase::zeroPartial (const int iBeg, const int iEnd) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, and Array< Vector< int, 2 > >.
Referenced by MultiFieldMatrix::computeResidual().
The documentation for this class was generated from the following file:
ArrayBase.h