Memosa-FVM: TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag > Class Template Reference
TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag > Class Template Reference
#include <TimeDerivativeDiscretization_Kmodel.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
Public Member Functions
TimeDerivativeDiscretization_Kmodel (const MeshList &meshes, const GeomFields &geomFields, Field &varField, Field &varN1Field, Field &varN2Field, const T_Scalar dT, const T_Scalar nonDimLength, const int Order)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const Field & _varN1Field
const Field & _varN2Field
const T_Scalar _dT
const T_Scalar _nonDimLength
const int _Order
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >
Definition at line 21 of file TimeDerivativeDiscretization_Kmodel.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::CCAssembler
Definition at line 28 of file TimeDerivativeDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::CCMatrix
Definition at line 26 of file TimeDerivativeDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::DiagArray
Definition at line 27 of file TimeDerivativeDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::T_Scalar
Definition at line 24 of file TimeDerivativeDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::TArray
Definition at line 31 of file TimeDerivativeDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > typedef Array<X> TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::XArray
Definition at line 30 of file TimeDerivativeDiscretization_Kmodel.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::TimeDerivativeDiscretization_Kmodel (const MeshList & meshes, const GeomFields & geomFields, Field & varField, Field & varN1Field, Field & varN2Field, const T_Scalar dT, const T_Scalar nonDimLength, const int Order) inline
Definition at line 34 of file TimeDerivativeDiscretization_Kmodel.h.
                                                      :
   Discretization(meshes),
     _geomFields(geomFields),
     _varField(varField),
     _varN1Field(varN1Field),
     _varN2Field(varN2Field),
     _dT(dT),
     _nonDimLength(nonDimLength),
     _Order(Order)
   {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 51 of file TimeDerivativeDiscretization_Kmodel.h.
References TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_dT, TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_geomFields, TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_Order, TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_varField, TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_varN1Field, TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_varN2Field, Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), MultiFieldMatrix::getMatrix(), StorageSite::getSelfCount(), and GeomFields::volume.
   {
     const StorageSite& cells = mesh.getCells();
     //const TArray& dsff =
     //  dynamic_cast<const TArray&>(_dsff[cells]);
     const TArray& cellVolume =
       dynamic_cast<const TArray&>(_geomFields.volume[cells]);
     // Field& _varField =  *_dsff.dsf[_direction];
     //Field& _varN1Field =  *_dsffN1.dsf[_direction];
     //Field& _varN2Field =  *_dsffN2.dsf[_direction];
     const MultiField::ArrayIndex cVarIndex(&_varField,&cells);
     CCMatrix& matrix =
       dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
     DiagArray& diag = matrix.getDiag();
     const XArray& x = dynamic_cast<const XArray&>(_varField[cells]);
     const XArray& xN1 = dynamic_cast<const XArray&>(_varN1Field[cells]);
     XArray& rCell = dynamic_cast<XArray&>(rField[cVarIndex]);
     const int nCells = cells.getSelfCount();//getSelfCount();
     //cout << "cellVolume" << cellVolume[0] << endl ;
     if (_Order > 1)
       {
         // second order
         const XArray& xN2 = dynamic_cast<const XArray&>(_varN2Field[cells]);
         T_Scalar onePointFive(1.5);
         T_Scalar two(2.0);
         T_Scalar pointFive(0.5);
         for(int c=0; c<nCells; c++)
           {
             const T_Scalar fbydT = cellVolume[c]/_dT; //pow(_nonDimLength,3);
             rCell[c] -= fbydT*(onePointFive*x[c]- two*xN1[c]
                                + pointFive*xN2[c]);
             diag[c] -= fbydT*onePointFive;
           }
         //cout << "Second diag[0] = " << diag[0] << endl ;
       }
     else
       {
         for(int c=0; c<nCells; c++)
           {
             const T_Scalar fbydT = cellVolume[c]/_dT; //pow(_nonDimLength,3);
             rCell[c] -= fbydT*(x[c]- xN1[c]);
             diag[c] -= fbydT;
           }
         //cout << "First diag[0] = " << diag[0] << endl ;
       }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const T_Scalar TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_dT private
Definition at line 123 of file TimeDerivativeDiscretization_Kmodel.h.
Referenced by TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_geomFields private
Definition at line 115 of file TimeDerivativeDiscretization_Kmodel.h.
Referenced by TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const T_Scalar TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_nonDimLength private
Definition at line 124 of file TimeDerivativeDiscretization_Kmodel.h.
template<class X , class Diag , class OffDiag > const int TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_Order private
Definition at line 125 of file TimeDerivativeDiscretization_Kmodel.h.
Referenced by TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_varField private
Definition at line 116 of file TimeDerivativeDiscretization_Kmodel.h.
Referenced by TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_varN1Field private
Definition at line 117 of file TimeDerivativeDiscretization_Kmodel.h.
Referenced by TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::_varN2Field private
Definition at line 118 of file TimeDerivativeDiscretization_Kmodel.h.
Referenced by TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
TimeDerivativeDiscretization_Kmodel.h