Memosa-FVM: StressTensor< T > Class Template Reference
StressTensor< T > Class Template Reference
#include <StressTensor.h>
Public Types
typedef StressTensor< T > This_T
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef NumTypeTraits< T >
::T_BuiltIn T_BuiltIn
Public Member Functions
T & operator[] (int n)
const T & operator[] (int n) const
StressTensor & operator= (const T &o)
StressTensor & operator= (const StressTensor &o)
StressTensor operator- ()
StressTensor & operator+= (const StressTensor &o)
StressTensor & operator+= (const T s)
StressTensor & operator-= (const StressTensor &o)
StressTensor & operator-= (const T s)
StressTensor & operator/= (const T s)
StressTensor & operator/= (const StressTensor &o)
StressTensor & operator*= (const T s)
StressTensor & operator*= (const StressTensor &o)
void zero ()
T mag2 () const
bool operator< (const double tolerance) const
Static Public Member Functions
static string getTypeName ()
static int getDimension ()
static void getShape (int *shp)
static int getDataSize ()
static StressTensor getZero ()
static double doubleMeasure (const StressTensor &x)
static StressTensor getNegativeUnity ()
static StressTensor getUnity ()
static void accumulateOneNorm (StressTensor &sum, const StressTensor &v)
static void accumulateDotProduct (StressTensor &sum, const StressTensor &v0, const StressTensor &v1)
static void reduceSum (T_Scalar &sum, const This_T &x)
static void safeDivide (StressTensor &x, const StressTensor &y)
static void normalize (StressTensor &x, const StressTensor &y)
static void setMax (StressTensor &x, const StressTensor &y)
Private Attributes
T _data [6]
Detailed Description
template<class T>
class StressTensor< T >
Symmetric 3x3 tensor to store stresses. Components are stored in the following order: xx, yy, zz, xy, yz, zx
Only used for exporting the stresses to MPM so most of the algebra operations aren't currently implemented.
Definition at line 23 of file StressTensor.h.
Member Typedef Documentation
template<class T> typedef NumTypeTraits<T>::T_BuiltIn StressTensor< T >::T_BuiltIn
Definition at line 28 of file StressTensor.h.
template<class T> typedef NumTypeTraits<T>::T_Scalar StressTensor< T >::T_Scalar
Definition at line 27 of file StressTensor.h.
template<class T> typedef StressTensor<T> StressTensor< T >::This_T
Definition at line 26 of file StressTensor.h.
Member Function Documentation
template<class T> static void StressTensor< T >::accumulateDotProduct (StressTensor< T > & sum, const StressTensor< T > & v0, const StressTensor< T > & v1) inline static
Definition at line 165 of file StressTensor.h.
   {
     throw;
   }
template<class T> static void StressTensor< T >::accumulateOneNorm (StressTensor< T > & sum, const StressTensor< T > & v) inline static
Definition at line 160 of file StressTensor.h.
   {
     throw;
   }
template<class T> static double StressTensor< T >::doubleMeasure (const StressTensor< T > & x) inline static
Definition at line 145 of file StressTensor.h.
   {
     throw;
   }
template<class T> static int StressTensor< T >::getDataSize () inline static
Definition at line 41 of file StressTensor.h.
   {
     return 6*NumTypeTraits<T>::getDataSize();
   }
template<class T> static int StressTensor< T >::getDimension () inline static
Definition at line 37 of file StressTensor.h.
 {return 1;}
template<class T> static StressTensor StressTensor< T >::getNegativeUnity () inline static
Definition at line 150 of file StressTensor.h.
   {
     throw;
   }
template<class T> static void StressTensor< T >::getShape (int * shp) inline static
Definition at line 39 of file StressTensor.h.
 { *shp = 6;}
template<class T> static string StressTensor< T >::getTypeName () inline static
Definition at line 30 of file StressTensor.h.
   {
     return "StressTensor<" + NumTypeTraits<T>::getTypeName() +
       ">";
   }
template<class T> static StressTensor StressTensor< T >::getUnity () inline static
Definition at line 155 of file StressTensor.h.
   {
     throw;
   }
template<class T> static StressTensor StressTensor< T >::getZero () inline static
Definition at line 138 of file StressTensor.h.
References StressTensor< T >::zero().
   {
     StressTensor z;
     z.zero();
     return z;
   }
template<class T> T StressTensor< T >::mag2 () const inline
Definition at line 128 of file StressTensor.h.
Referenced by StressTensor< T >::operator<().
   {
     throw;
   }
template<class T> static void StressTensor< T >::normalize (StressTensor< T > & x, const StressTensor< T > & y) inline static
Definition at line 181 of file StressTensor.h.
   {
     throw;
   }
template<class T> StressTensor& StressTensor< T >::operator*= (const T s) inline
Definition at line 111 of file StressTensor.h.
References StressTensor< T >::_data.
   {
     for(int i=0;i<6;i++)
       _data[i] *= s;
     return *this;
   }
template<class T> StressTensor& StressTensor< T >::operator*= (const StressTensor< T > & o) inline
Definition at line 118 of file StressTensor.h.
   {
     throw;
   }
template<class T> StressTensor& StressTensor< T >::operator+= (const StressTensor< T > & o) inline
Definition at line 71 of file StressTensor.h.
References StressTensor< T >::_data.
   {
     for(int i=0;i<6;i++)
       _data[i] += o[i];
     return *this;
   }
template<class T> StressTensor& StressTensor< T >::operator+= (const T s) inline
Definition at line 78 of file StressTensor.h.
References StressTensor< T >::_data.
   {
     for(int i=0;i<6;i++)
       _data[i] += s;
     return *this;
   }
template<class T> StressTensor StressTensor< T >::operator- () inline
Definition at line 63 of file StressTensor.h.
References StressTensor< T >::_data.
   {
     StressTensor r;
     for(int i=0;i<6;i++)
       r[i]=-_data[i];
     return r;
   }
template<class T> StressTensor& StressTensor< T >::operator-= (const StressTensor< T > & o) inline
Definition at line 85 of file StressTensor.h.
References StressTensor< T >::_data.
   {
     for(int i=0;i<6;i++)
       _data[i] -= o[i];
     return *this;
   }
template<class T> StressTensor& StressTensor< T >::operator-= (const T s) inline
Definition at line 92 of file StressTensor.h.
References StressTensor< T >::_data.
   {
     for(int i=0;i<6;i++)
       _data[i] -= s;
     return *this;
   }
template<class T> StressTensor& StressTensor< T >::operator/= (const T s) inline
Definition at line 99 of file StressTensor.h.
References StressTensor< T >::_data.
   {
     for(int i=0;i<6;i++)
       _data[i] /= s;
     return *this;
   }
template<class T> StressTensor& StressTensor< T >::operator/= (const StressTensor< T > & o) inline
Definition at line 106 of file StressTensor.h.
   {
     throw;
   }
template<class T> bool StressTensor< T >::operator< (const double tolerance) const inline
Definition at line 133 of file StressTensor.h.
References StressTensor< T >::mag2().
   {
     return mag2() < tolerance*tolerance;
   }
template<class T> StressTensor& StressTensor< T >::operator= (const T & o) inline
Definition at line 49 of file StressTensor.h.
References StressTensor< T >::_data.
   {
     for(int i=0;i<6;i++)
       _data[i] = o;
     return *this;
   }
template<class T> StressTensor& StressTensor< T >::operator= (const StressTensor< T > & o) inline
Definition at line 56 of file StressTensor.h.
References StressTensor< T >::_data.
   {
     for(int i=0;i<6;i++)
       _data[i] = o[i];
     return *this;
   }
template<class T> T& StressTensor< T >::operator[] (int n) inline
Definition at line 46 of file StressTensor.h.
References StressTensor< T >::_data.
 {return _data[n];}
template<class T> const T& StressTensor< T >::operator[] (int n) const inline
Definition at line 47 of file StressTensor.h.
References StressTensor< T >::_data.
 {return _data[n];}
template<class T> static void StressTensor< T >::reduceSum (T_Scalar & sum, const This_T & x) inline static
Definition at line 171 of file StressTensor.h.
   {
     throw;
   }
template<class T> static void StressTensor< T >::safeDivide (StressTensor< T > & x, const StressTensor< T > & y) inline static
Definition at line 176 of file StressTensor.h.
   {
     throw;
   }
template<class T> static void StressTensor< T >::setMax (StressTensor< T > & x, const StressTensor< T > & y) inline static
Definition at line 186 of file StressTensor.h.
   {
     throw;
   }
template<class T> void StressTensor< T >::zero () inline
Definition at line 123 of file StressTensor.h.
Referenced by StressTensor< T >::getZero().
   {
     for(int i=0;i<6;i++) _data[i] = NumTypeTraits<T>::getZero();
   }
Member Data Documentation
template<class T> T StressTensor< T >::_data[6] private
Definition at line 192 of file StressTensor.h.
Referenced by StressTensor< T >::operator*=(), StressTensor< T >::operator+=(), StressTensor< T >::operator-(), StressTensor< T >::operator-=(), StressTensor< T >::operator/=(), StressTensor< T >::operator=(), and StressTensor< T >::operator[]().
The documentation for this class was generated from the following file:
StressTensor.h