Memosa-FVM: BaseGenericKineticBCS< X, Diag, OffDiag > Class Template Reference
BaseGenericKineticBCS< X, Diag, OffDiag > Class Template Reference
#include <GenericKineticBCS.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Array< int > IntArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef FluxJacobianMatrix
< Diag, X > FMatrix
typedef DiagonalMatrix< Diag, X > BBMatrix
typedef Array< Diag > DiagArray
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
BaseGenericKineticBCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
void applyDirichletBC (int f, const X &bValue) const
void applyDirichletBC (const X &bValue) const
void applyDirichletBC (const FloatValEvaluator< X > &bValue) const
void applyExtrapolationBC () const
void applyExtrapolationBC (const int f) const
void applyInterfaceBC (const int f) const
void applyInterfaceBC () const
void applyFlowBC (const TArray &convFlux, const X &bValue) const
void applyNonzeroDiagBC () const
void applyNonzeroDiagBC (int f) const
Protected Attributes
const StorageSite & _faces
const StorageSite & _cells
const IntArray & _ibType
const CRConnectivity & _faceCells
const Field & _varField
const MultiField::ArrayIndex _xIndex
CCMatrix & _dRdX
CCAssembler & _assembler
DiagArray & _dRdXDiag
XArray & _x
XArray & _r
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
Detailed Description
template<class X, class Diag, class OffDiag>
class BaseGenericKineticBCS< X, Diag, OffDiag >
Definition at line 22 of file GenericKineticBCS.h.
Member Typedef Documentation
template<class X, class Diag, class OffDiag> typedef DiagonalMatrix<Diag,X> BaseGenericKineticBCS< X, Diag, OffDiag >::BBMatrix
Definition at line 37 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef CCMatrix::PairWiseAssembler BaseGenericKineticBCS< X, Diag, OffDiag >::CCAssembler
Definition at line 34 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef CRMatrix<Diag,OffDiag,X> BaseGenericKineticBCS< X, Diag, OffDiag >::CCMatrix
Definition at line 33 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<Diag> BaseGenericKineticBCS< X, Diag, OffDiag >::DiagArray
Definition at line 39 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef FluxJacobianMatrix<Diag,X> BaseGenericKineticBCS< X, Diag, OffDiag >::FMatrix
Definition at line 36 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<int> BaseGenericKineticBCS< X, Diag, OffDiag >::IntArray
Definition at line 29 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<OffDiag> BaseGenericKineticBCS< X, Diag, OffDiag >::OffDiagArray
Definition at line 40 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef NumTypeTraits<X>::T_Scalar BaseGenericKineticBCS< X, Diag, OffDiag >::T_Scalar
Definition at line 26 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<T_Scalar> BaseGenericKineticBCS< X, Diag, OffDiag >::TArray
Definition at line 28 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef Vector<T_Scalar,3> BaseGenericKineticBCS< X, Diag, OffDiag >::VectorT3
Definition at line 31 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<VectorT3> BaseGenericKineticBCS< X, Diag, OffDiag >::VectorT3Array
Definition at line 43 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> typedef Array<X> BaseGenericKineticBCS< X, Diag, OffDiag >::XArray
Definition at line 42 of file GenericKineticBCS.h.
Constructor & Destructor Documentation
template<class X, class Diag, class OffDiag> BaseGenericKineticBCS< X, Diag, OffDiag >::BaseGenericKineticBCS (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, Field & varField, MultiFieldMatrix & matrix, MultiField & xField, MultiField & rField) inline
Definition at line 46 of file GenericKineticBCS.h.
                                                      :
     _faces(faces),
     _cells(mesh.getCells()),
     _ibType(dynamic_cast<const IntArray&>(geomFields.ibType[_cells])),
     _faceCells(mesh.getFaceCells(_faces)),
     _varField(varField),
     //_fluxField(fluxField),
     _xIndex(&_varField,&_cells),
    // _fluxIndex(&_fluxField,&_faces),
     _dRdX(dynamic_cast<CCMatrix&>(matrix.getMatrix(_xIndex,_xIndex))),
     //_dFluxdX(dynamic_cast<FMatrix&>(matrix.getMatrix(_fluxIndex,_xIndex))),
     //_dFluxdFlux(dynamic_cast<BBMatrix&>(matrix.getMatrix(_fluxIndex,_fluxIndex))),
     _assembler(_dRdX.getPairWiseAssembler(_faceCells)),
     _dRdXDiag(_dRdX.getDiag()),
     _x(dynamic_cast<XArray&>(xField[_xIndex])),
     _r(dynamic_cast<XArray&>(rField[_xIndex])),
    // _flux(dynamic_cast<XArray&>(xField[_fluxIndex])),
    // _rFlux(dynamic_cast<XArray&>(rField[_fluxIndex])),
     _areaMagField(geomFields.areaMag),
     _faceAreaMag(dynamic_cast<const TArray&>(_areaMagField[_faces])),
     _areaField(geomFields.area),
     _faceArea(dynamic_cast<const VectorT3Array&>(_areaField[_faces]))
   {}
Member Function Documentation
template<class X, class Diag, class OffDiag> void BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC (int f, const X & bValue) const inline
Definition at line 76 of file GenericKineticBCS.h.
References BaseGenericKineticBCS< X, Diag, OffDiag >::_assembler, BaseGenericKineticBCS< X, Diag, OffDiag >::_dRdXDiag, BaseGenericKineticBCS< X, Diag, OffDiag >::_faceCells, BaseGenericKineticBCS< X, Diag, OffDiag >::_ibType, BaseGenericKineticBCS< X, Diag, OffDiag >::_r, BaseGenericKineticBCS< X, Diag, OffDiag >::_x, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), and Mesh::IBTYPE_FLUID.
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), and BaseGenericKineticBCS< X, Diag, OffDiag >::applyFlowBC().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     // the current value of flux and its Jacobians
     // const X fluxB = -_r[c1];
     //const OffDiag dFluxdXC0 = -_assembler.getCoeff10(f);
     // const Diag dFluxdXC1 = -_dRdXDiag[c1];
     const OffDiag dRC0dXC1 = _assembler.getCoeff01(f);
     // since we know the boundary value, compute the boundary
     // x correction and it's contribution to the residual for c0; we
     // can then eliminate the coefficient to the boundary cell
     const X dXC1 = bValue - _x[c1];
     // const X dFlux = dFluxdXC1*dXC1;
     const X dRC0 = dRC0dXC1*dXC1;
     _r[c0] += dRC0;
     _assembler.getCoeff01(f) = NumTypeTraits<OffDiag>::getZero();
     // set the boundary value and make its correction equation an
     // identity
     _x[c1] = bValue;
     _assembler.getCoeff10(f) = NumTypeTraits<OffDiag>::getZero();
     _r[c1] = NumTypeTraits<X>::getZero();
     _dRdXDiag[c1] = NumTypeTraits<Diag>::getNegativeUnity();
    /*
     //setup the equation for the boundary flux correction
     _dFluxdX.setCoeffL(f,dFluxdXC0);
     _dFluxdX.setCoeffR(f,NumTypeTraits<OffDiag>::getZero());
     _flux[f] = fluxB;
     _rFlux[f] = dFlux;
     _dFluxdFlux[f] = NumTypeTraits<Diag>::getNegativeUnity();
    */
  }
template<class X, class Diag, class OffDiag> void BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC (const X & bValue) const inline
Definition at line 118 of file GenericKineticBCS.h.
References BaseGenericKineticBCS< X, Diag, OffDiag >::_faces, BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applyDirichletBC(i,bValue);
   }
template<class X, class Diag, class OffDiag> void BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC (const FloatValEvaluator< X > & bValue) const inline
Definition at line 124 of file GenericKineticBCS.h.
References BaseGenericKineticBCS< X, Diag, OffDiag >::_faces, BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applyDirichletBC(i,bValue[i]);
   }
template<class X, class Diag, class OffDiag> void BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC () const inline
Definition at line 131 of file GenericKineticBCS.h.
References BaseGenericKineticBCS< X, Diag, OffDiag >::_faces, and StorageSite::getCount().
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyFlowBC().
   {
     for(int i=0; i<_faces.getCount(); i++)
         applyExtrapolationBC(i);
   }
template<class X, class Diag, class OffDiag> void BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC (const int f) const inline
Definition at line 139 of file GenericKineticBCS.h.
References BaseGenericKineticBCS< X, Diag, OffDiag >::_assembler, BaseGenericKineticBCS< X, Diag, OffDiag >::_dRdX, BaseGenericKineticBCS< X, Diag, OffDiag >::_dRdXDiag, BaseGenericKineticBCS< X, Diag, OffDiag >::_faceCells, BaseGenericKineticBCS< X, Diag, OffDiag >::_ibType, BaseGenericKineticBCS< X, Diag, OffDiag >::_r, BaseGenericKineticBCS< X, Diag, OffDiag >::_x, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), Mesh::IBTYPE_FLUID, and CRMatrix< T_Diag, T_OffDiag, X >::setBoundary().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     // the current value of flux and its Jacobians
     //const X fluxB = -_r[c1];
     // const OffDiag dFluxdXC0 = -_assembler.getCoeff10(f);
     const Diag dFluxdXC1 = -_dRdXDiag[c1];
     const X xc0mxc1 = _x[c0]-_x[c1];
     // eliminate boundary dependency from cell equation
     _dRdXDiag[c0] += dFluxdXC1;
     _r[c0] += dFluxdXC1*xc0mxc1;
     _assembler.getCoeff01(f) = 0;
     // boundary value equation
     _dRdXDiag[c1] = NumTypeTraits<Diag>::getNegativeUnity();
     _assembler.getCoeff10(f) = NumTypeTraits<OffDiag>::getUnity();
     _r[c1] = xc0mxc1;
     _dRdX.setBoundary(c1);
     /*
     //setup the equation for the boundary flux correction
     _dFluxdX.setCoeffL(f,dFluxdXC0);
     _dFluxdX.setCoeffR(f,dFluxdXC0); // should really be dFluxdXC1
     _flux[f] = fluxB;
     _rFlux[f] = T_Scalar(0);
     _dFluxdFlux[f] = NumTypeTraits<Diag>::getNegativeUnity();
     */
  }
template<class X, class Diag, class OffDiag> void BaseGenericKineticBCS< X, Diag, OffDiag >::applyFlowBC (const TArray & convFlux, const X & bValue) const inline
Definition at line 215 of file GenericKineticBCS.h.
References BaseGenericKineticBCS< X, Diag, OffDiag >::_faces, BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), and StorageSite::getCount().
   {
     for(int f=0; f<_faces.getCount(); f++)
       if (convFlux[f] < 0)
         applyDirichletBC(f,bValue);
       else
         applyExtrapolationBC(f);
   }
template<class X, class Diag, class OffDiag> void BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC (const int f) const inline
Definition at line 175 of file GenericKineticBCS.h.
References BaseGenericKineticBCS< X, Diag, OffDiag >::_assembler, BaseGenericKineticBCS< X, Diag, OffDiag >::_cells, BaseGenericKineticBCS< X, Diag, OffDiag >::_faceCells, BaseGenericKineticBCS< X, Diag, OffDiag >::_r, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), and StorageSite::getSelfCount().
Referenced by KineticModel< T >::linearizeKineticModel().
   {
     // the boundary cell could be either c0 or c1 at an interface
     int cb = _faceCells(f,1);
     T_Scalar sign(NumTypeTraits<T_Scalar>::getUnity());
     if (cb < _cells.getSelfCount())
     {
         cb = _faceCells(f,0);
         sign *= -1.0;
     }
     // the current value of flux and its Jacobians
     // const X fluxInterior = -_r[cb];
     //const OffDiag dFluxdXC0 = -sign*_assembler.getCoeff10(f);
     //const OffDiag dFluxdXC1 = sign*_assembler.getCoeff01(f);
     _r[cb] = T_Scalar(0);
     if (sign>0)
       _assembler.getCoeff10(f) = NumTypeTraits<OffDiag>::getZero();
     else
       _assembler.getCoeff01(f) = NumTypeTraits<OffDiag>::getZero();
     //setup the equation for the boundary flux correction
     /*
     _dFluxdX.setCoeffL(f,dFluxdXC0);
     _dFluxdX.setCoeffR(f,dFluxdXC1);
     _flux[f] = fluxInterior;
     _rFlux[f] = T_Scalar(0);
     _dFluxdFlux[f] = NumTypeTraits<Diag>::getNegativeUnity();
     */
   }
template<class X, class Diag, class OffDiag> void BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC () const inline
Definition at line 209 of file GenericKineticBCS.h.
References BaseGenericKineticBCS< X, Diag, OffDiag >::_faces, and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applyInterfaceBC(i);
   }
template<class X, class Diag, class OffDiag> void BaseGenericKineticBCS< X, Diag, OffDiag >::applyNonzeroDiagBC () const inline
Definition at line 224 of file GenericKineticBCS.h.
References BaseGenericKineticBCS< X, Diag, OffDiag >::_faces, and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applyNonzeroDiagBC(i);
   }
template<class X, class Diag, class OffDiag> void BaseGenericKineticBCS< X, Diag, OffDiag >::applyNonzeroDiagBC (int f) const inline
Definition at line 230 of file GenericKineticBCS.h.
References BaseGenericKineticBCS< X, Diag, OffDiag >::_dRdXDiag, BaseGenericKineticBCS< X, Diag, OffDiag >::_faceCells, BaseGenericKineticBCS< X, Diag, OffDiag >::_ibType, and Mesh::IBTYPE_FLUID.
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     if (_ibType[c0] != Mesh::IBTYPE_FLUID)
       return;
     _dRdXDiag[c1][0] = T_Scalar(-1.0);
   }
Member Data Documentation
template<class X, class Diag, class OffDiag> const Field& BaseGenericKineticBCS< X, Diag, OffDiag >::_areaField protected
Definition at line 262 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> const Field& BaseGenericKineticBCS< X, Diag, OffDiag >::_areaMagField protected
Definition at line 260 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> CCAssembler& BaseGenericKineticBCS< X, Diag, OffDiag >::_assembler protected
Definition at line 254 of file GenericKineticBCS.h.
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), and BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC().
template<class X, class Diag, class OffDiag> const StorageSite& BaseGenericKineticBCS< X, Diag, OffDiag >::_cells protected
Definition at line 244 of file GenericKineticBCS.h.
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC().
template<class X, class Diag, class OffDiag> CCMatrix& BaseGenericKineticBCS< X, Diag, OffDiag >::_dRdX protected
Definition at line 251 of file GenericKineticBCS.h.
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC().
template<class X, class Diag, class OffDiag> DiagArray& BaseGenericKineticBCS< X, Diag, OffDiag >::_dRdXDiag protected
Definition at line 255 of file GenericKineticBCS.h.
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), and BaseGenericKineticBCS< X, Diag, OffDiag >::applyNonzeroDiagBC().
template<class X, class Diag, class OffDiag> const VectorT3Array& BaseGenericKineticBCS< X, Diag, OffDiag >::_faceArea protected
Definition at line 263 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> const TArray& BaseGenericKineticBCS< X, Diag, OffDiag >::_faceAreaMag protected
Definition at line 261 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> const CRConnectivity& BaseGenericKineticBCS< X, Diag, OffDiag >::_faceCells protected
Definition at line 246 of file GenericKineticBCS.h.
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC(), and BaseGenericKineticBCS< X, Diag, OffDiag >::applyNonzeroDiagBC().
template<class X, class Diag, class OffDiag> const StorageSite& BaseGenericKineticBCS< X, Diag, OffDiag >::_faces protected
Definition at line 243 of file GenericKineticBCS.h.
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyFlowBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC(), and BaseGenericKineticBCS< X, Diag, OffDiag >::applyNonzeroDiagBC().
template<class X, class Diag, class OffDiag> const IntArray& BaseGenericKineticBCS< X, Diag, OffDiag >::_ibType protected
Definition at line 245 of file GenericKineticBCS.h.
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), and BaseGenericKineticBCS< X, Diag, OffDiag >::applyNonzeroDiagBC().
template<class X, class Diag, class OffDiag> XArray& BaseGenericKineticBCS< X, Diag, OffDiag >::_r protected
Definition at line 257 of file GenericKineticBCS.h.
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), and BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC().
template<class X, class Diag, class OffDiag> const Field& BaseGenericKineticBCS< X, Diag, OffDiag >::_varField protected
Definition at line 247 of file GenericKineticBCS.h.
template<class X, class Diag, class OffDiag> XArray& BaseGenericKineticBCS< X, Diag, OffDiag >::_x protected
Definition at line 256 of file GenericKineticBCS.h.
Referenced by BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), and BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC().
template<class X, class Diag, class OffDiag> const MultiField::ArrayIndex BaseGenericKineticBCS< X, Diag, OffDiag >::_xIndex protected
Definition at line 249 of file GenericKineticBCS.h.
The documentation for this class was generated from the following file:
GenericKineticBCS.h