Memosa-FVM: StructureBCS< X, Diag, OffDiag > Class Template Reference
StructureBCS< X, Diag, OffDiag > Class Template Reference
#include <StructureModel_impl.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef FluxJacobianMatrix
< Diag, X > FMatrix
typedef DiagonalMatrix< Diag, X > BBMatrix
typedef Array< Diag > DiagArray
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
StructureBCS (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Field &varField, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField, const bool explicitMode)
X applyDirichletBC (int f, const X &bValue) const
X applyDirichletBC (const X &bValue) const
X applyDirichletBC (const FloatValEvaluator< X > &bValue) const
X applyNeumannBC (const int f, const X &specifiedFlux) const
X applyNeumannBC (const X &bFlux) const
X applyZeroDerivativeBC () const
X applyNeumannBC (const FloatValEvaluator< X > &bFlux) const
void applyInterfaceBC (const int f) const
void applyInterfaceBC () const
void applySymmetryBC () const
Protected Attributes
const StorageSite & _faces
const StorageSite & _cells
const CRConnectivity & _faceCells
const Field & _varField
const MultiField::ArrayIndex _xIndex
CCMatrix & _dRdX
CCAssembler & _assembler
DiagArray & _dRdXDiag
XArray & _x
XArray & _r
const Field & _areaMagField
const TArray & _faceAreaMag
const Field & _areaField
const VectorT3Array & _faceArea
const bool _explicitMode
Detailed Description
template<class X, class Diag, class OffDiag>
class StructureBCS< X, Diag, OffDiag >
Definition at line 40 of file StructureModel_impl.h.
Member Typedef Documentation
template<class X, class Diag, class OffDiag> typedef DiagonalMatrix<Diag,X> StructureBCS< X, Diag, OffDiag >::BBMatrix
Definition at line 53 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> typedef CCMatrix::PairWiseAssembler StructureBCS< X, Diag, OffDiag >::CCAssembler
Definition at line 50 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> typedef CRMatrix<Diag,OffDiag,X> StructureBCS< X, Diag, OffDiag >::CCMatrix
Definition at line 49 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Array<Diag> StructureBCS< X, Diag, OffDiag >::DiagArray
Definition at line 55 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> typedef FluxJacobianMatrix<Diag,X> StructureBCS< X, Diag, OffDiag >::FMatrix
Definition at line 52 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Array<OffDiag> StructureBCS< X, Diag, OffDiag >::OffDiagArray
Definition at line 56 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> typedef NumTypeTraits<X>::T_Scalar StructureBCS< X, Diag, OffDiag >::T_Scalar
Definition at line 44 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Array<T_Scalar> StructureBCS< X, Diag, OffDiag >::TArray
Definition at line 46 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Vector<T_Scalar,3> StructureBCS< X, Diag, OffDiag >::VectorT3
Definition at line 47 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Array<VectorT3> StructureBCS< X, Diag, OffDiag >::VectorT3Array
Definition at line 59 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> typedef Array<X> StructureBCS< X, Diag, OffDiag >::XArray
Definition at line 58 of file StructureModel_impl.h.
Constructor & Destructor Documentation
template<class X, class Diag, class OffDiag> StructureBCS< X, Diag, OffDiag >::StructureBCS (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, Field & varField, MultiFieldMatrix & matrix, MultiField & xField, MultiField & rField, const bool explicitMode) inline
Definition at line 62 of file StructureModel_impl.h.
                  :
     _faces(faces),
     _cells(mesh.getCells()),
     _faceCells(mesh.getFaceCells(_faces)),
     _varField(varField),
     _xIndex(&_varField,&_cells),
     _dRdX(dynamic_cast<CCMatrix&>(matrix.getMatrix(_xIndex,_xIndex))),
     _assembler(_dRdX.getPairWiseAssembler(_faceCells)),
     _dRdXDiag(_dRdX.getDiag()),
     _x(dynamic_cast<XArray&>(xField[_xIndex])),
     _r(dynamic_cast<XArray&>(rField[_xIndex])),
     _areaMagField(geomFields.areaMag),
     _faceAreaMag(dynamic_cast<const TArray&>(_areaMagField[_faces])),
     _areaField(geomFields.area),
     _faceArea(dynamic_cast<const VectorT3Array&>(_areaField[_faces])),
     _explicitMode(explicitMode)
   {}
Member Function Documentation
template<class X, class Diag, class OffDiag> X StructureBCS< X, Diag, OffDiag >::applyDirichletBC (int f, const X & bValue) const inline
Definition at line 88 of file StructureModel_impl.h.
References StructureBCS< X, Diag, OffDiag >::_dRdX, StructureBCS< X, Diag, OffDiag >::_explicitMode, StructureBCS< X, Diag, OffDiag >::_faceCells, StructureBCS< X, Diag, OffDiag >::_r, StructureBCS< X, Diag, OffDiag >::_x, CRMatrix< T_Diag, T_OffDiag, X >::eliminateDirichlet(), and CRMatrix< T_Diag, T_OffDiag, X >::setDirichlet().
Referenced by StructureModel< T >::Impl::applyBC(), and StructureBCS< X, Diag, OffDiag >::applyDirichletBC().
   {
     const int c1 = _faceCells(f,1);
     const X fluxB = -_r[c1];
     const X dXC1 = bValue - _x[c1];
     _dRdX.eliminateDirichlet(c1,_r,dXC1, _explicitMode);
     _x[c1] = bValue;
     _r[c1] = NumTypeTraits<X>::getZero();
     if (!_explicitMode)
       _dRdX.setDirichlet(c1);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> X StructureBCS< X, Diag, OffDiag >::applyDirichletBC (const X & bValue) const inline
Definition at line 104 of file StructureModel_impl.h.
References StructureBCS< X, Diag, OffDiag >::_faces, StructureBCS< X, Diag, OffDiag >::applyDirichletBC(), and StorageSite::getCount().
   {
     X fluxB(NumTypeTraits<X>::getZero());
     for(int i=0; i<_faces.getCount(); i++)
       fluxB += applyDirichletBC(i,bValue);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> X StructureBCS< X, Diag, OffDiag >::applyDirichletBC (const FloatValEvaluator< X > & bValue) const inline
Definition at line 112 of file StructureModel_impl.h.
References StructureBCS< X, Diag, OffDiag >::_faces, StructureBCS< X, Diag, OffDiag >::applyDirichletBC(), and StorageSite::getCount().
   {
     X fluxB(NumTypeTraits<X>::getZero());
     for(int i=0; i<_faces.getCount(); i++)
       fluxB += applyDirichletBC(i,bValue[i]);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> void StructureBCS< X, Diag, OffDiag >::applyInterfaceBC (const int f) const inline
Definition at line 183 of file StructureModel_impl.h.
References StructureBCS< X, Diag, OffDiag >::_assembler, StructureBCS< X, Diag, OffDiag >::_cells, StructureBCS< X, Diag, OffDiag >::_faceCells, StructureBCS< X, Diag, OffDiag >::_r, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), and StorageSite::getSelfCount().
   {
     // the boundary cell could be either c0 or c1 at an interface
     int cb = _faceCells(f,1);
     T_Scalar sign(NumTypeTraits<T_Scalar>::getUnity());
     if (cb < _cells.getSelfCount())
     {
         cb = _faceCells(f,0);
         sign *= -1.0;
     }
     _r[cb] = T_Scalar(0);
     if (sign>0)
       _assembler.getCoeff10(f) = NumTypeTraits<OffDiag>::getZero();
     else
       _assembler.getCoeff01(f) = NumTypeTraits<OffDiag>::getZero();
   }
template<class X, class Diag, class OffDiag> void StructureBCS< X, Diag, OffDiag >::applyInterfaceBC () const inline
Definition at line 204 of file StructureModel_impl.h.
References StructureBCS< X, Diag, OffDiag >::_faces, and StorageSite::getCount().
   {
     for(int i=0; i<_faces.getCount(); i++)
       applyInterfaceBC(i);
   }
template<class X, class Diag, class OffDiag> X StructureBCS< X, Diag, OffDiag >::applyNeumannBC (const int f, const X & specifiedFlux) const inline
Definition at line 120 of file StructureModel_impl.h.
References StructureBCS< X, Diag, OffDiag >::_dRdX, StructureBCS< X, Diag, OffDiag >::_faceAreaMag, StructureBCS< X, Diag, OffDiag >::_faceCells, StructureBCS< X, Diag, OffDiag >::_r, and CRMatrix< T_Diag, T_OffDiag, X >::setBoundary().
Referenced by StructureModel< T >::Impl::applyBC(), and StructureBCS< X, Diag, OffDiag >::applyNeumannBC().
   {
     //const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     const X fluxB = -_r[c1];
     // the current value of flux and its Jacobians
     const X dFlux = specifiedFlux*_faceAreaMag[f] - fluxB;
     // setup the equation for the boundary value; the coefficients
     // are already computed so just need to set the rhs
     _r[c1] = dFlux;
     // _dRdX.eliminate(c1,_r);
     // mark this row as a "boundary" row so that we will update it
     // after the overall system is solved
     _dRdX.setBoundary(c1);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> X StructureBCS< X, Diag, OffDiag >::applyNeumannBC (const X & bFlux) const inline
Definition at line 142 of file StructureModel_impl.h.
References StructureBCS< X, Diag, OffDiag >::_faces, StructureBCS< X, Diag, OffDiag >::applyNeumannBC(), and StorageSite::getCount().
   {
     X fluxB(NumTypeTraits<X>::getZero());
     for(int i=0; i<_faces.getCount(); i++)
       fluxB += applyNeumannBC(i,bFlux);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> X StructureBCS< X, Diag, OffDiag >::applyNeumannBC (const FloatValEvaluator< X > & bFlux) const inline
Definition at line 175 of file StructureModel_impl.h.
References StructureBCS< X, Diag, OffDiag >::_faces, StructureBCS< X, Diag, OffDiag >::applyNeumannBC(), and StorageSite::getCount().
   {
     X fluxB(NumTypeTraits<X>::getZero());
     for(int i=0; i<_faces.getCount(); i++)
       fluxB += applyNeumannBC(i,bFlux[i]);
     return fluxB;
   }
template<class X, class Diag, class OffDiag> void StructureBCS< X, Diag, OffDiag >::applySymmetryBC () const inline
Definition at line 210 of file StructureModel_impl.h.
References StructureBCS< X, Diag, OffDiag >::_assembler, StructureBCS< X, Diag, OffDiag >::_dRdX, StructureBCS< X, Diag, OffDiag >::_faceArea, StructureBCS< X, Diag, OffDiag >::_faceAreaMag, StructureBCS< X, Diag, OffDiag >::_faceCells, StructureBCS< X, Diag, OffDiag >::_faces, StructureBCS< X, Diag, OffDiag >::_r, StructureBCS< X, Diag, OffDiag >::_x, dot(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), and CRMatrix< T_Diag, T_OffDiag, X >::setDirichlet().
   {
     for(int f=0; f<this->_faces.getCount(); f++)
     {
         const int c0 = this->_faceCells(f,0);
         const int c1 = this->_faceCells(f,1);
         const VectorT3 en = this->_faceArea[f]/this->_faceAreaMag[f];
         const T_Scalar xC0_dotn = dot(this->_x[c0],en);
         const X xB = this->_x[c0] - 2.*xC0_dotn * en;
         Diag dxBdxC0(Diag::getZero());
         dxBdxC0(0,0) =  1.0 - 2.*en[0]*en[0];
         dxBdxC0(0,1) =  - 2.*en[0]*en[1];
         dxBdxC0(0,2) =  - 2.*en[0]*en[2];
         dxBdxC0(1,0) =  - 2.*en[1]*en[0];
         dxBdxC0(1,1) =  1.0 - 2.*en[1]*en[1];
         dxBdxC0(1,2) =  - 2.*en[1]*en[2];
         dxBdxC0(2,0) =  - 2.*en[2]*en[0];
         dxBdxC0(2,1) =  - 2.*en[2]*en[1];
         dxBdxC0(2,2) =  1.0 - 2.*en[2]*en[2];
         const X xc1mxB = xB-this->_x[c1];
         // boundary value equation
         // set all neighbour coeffs to zero first and ap to  -1
         this->_dRdX.setDirichlet(c1);
         // dependance on c0
         this->_assembler.getCoeff10(f) = dxBdxC0;
         this->_r[c1] = xc1mxB;
     }
   }
template<class X, class Diag, class OffDiag> X StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC () const inline
Definition at line 151 of file StructureModel_impl.h.
References StructureBCS< X, Diag, OffDiag >::_assembler, StructureBCS< X, Diag, OffDiag >::_dRdX, StructureBCS< X, Diag, OffDiag >::_dRdXDiag, StructureBCS< X, Diag, OffDiag >::_faceCells, StructureBCS< X, Diag, OffDiag >::_faces, StructureBCS< X, Diag, OffDiag >::_r, StructureBCS< X, Diag, OffDiag >::_x, CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), and CRMatrix< T_Diag, T_OffDiag, X >::setBoundary().
   {
     X fluxTotal(NumTypeTraits<X>::getZero());
     for(int f=0; f<_faces.getCount(); f++)
     {
         const int c0 = _faceCells(f,0);
         const int c1 = _faceCells(f,1);
         const X fluxB = -_r[c1];
         // setup the equation for the boundary value; we want xb to be equal to xc
         _r[c1] = _x[c0] - _x[c1];
         _dRdXDiag[c1]  = -NumTypeTraits<Diag>::getUnity();
         this->_assembler.getCoeff10(f)  = NumTypeTraits<OffDiag>::getUnity();
         // mark this row as a "boundary" row so that we will update it
         // after the overall system is solved
         _dRdX.setBoundary(c1);
         fluxTotal += fluxB;
     }
     return fluxTotal;
   }
Member Data Documentation
template<class X, class Diag, class OffDiag> const Field& StructureBCS< X, Diag, OffDiag >::_areaField protected
Definition at line 264 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> const Field& StructureBCS< X, Diag, OffDiag >::_areaMagField protected
Definition at line 262 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> CCAssembler& StructureBCS< X, Diag, OffDiag >::_assembler protected
Definition at line 258 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applyInterfaceBC(), StructureBCS< X, Diag, OffDiag >::applySymmetryBC(), and StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> const StorageSite& StructureBCS< X, Diag, OffDiag >::_cells protected
Definition at line 253 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applyInterfaceBC().
template<class X, class Diag, class OffDiag> CCMatrix& StructureBCS< X, Diag, OffDiag >::_dRdX protected
Definition at line 257 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applyDirichletBC(), StructureBCS< X, Diag, OffDiag >::applyNeumannBC(), StructureBCS< X, Diag, OffDiag >::applySymmetryBC(), and StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> DiagArray& StructureBCS< X, Diag, OffDiag >::_dRdXDiag protected
Definition at line 259 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> const bool StructureBCS< X, Diag, OffDiag >::_explicitMode protected
Definition at line 266 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applyDirichletBC().
template<class X, class Diag, class OffDiag> const VectorT3Array& StructureBCS< X, Diag, OffDiag >::_faceArea protected
Definition at line 265 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applySymmetryBC().
template<class X, class Diag, class OffDiag> const TArray& StructureBCS< X, Diag, OffDiag >::_faceAreaMag protected
Definition at line 263 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applyNeumannBC(), and StructureBCS< X, Diag, OffDiag >::applySymmetryBC().
template<class X, class Diag, class OffDiag> const CRConnectivity& StructureBCS< X, Diag, OffDiag >::_faceCells protected
Definition at line 254 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applyDirichletBC(), StructureBCS< X, Diag, OffDiag >::applyInterfaceBC(), StructureBCS< X, Diag, OffDiag >::applyNeumannBC(), StructureBCS< X, Diag, OffDiag >::applySymmetryBC(), and StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> const StorageSite& StructureBCS< X, Diag, OffDiag >::_faces protected
Definition at line 252 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applyDirichletBC(), StructureBCS< X, Diag, OffDiag >::applyInterfaceBC(), StructureBCS< X, Diag, OffDiag >::applyNeumannBC(), StructureBCS< X, Diag, OffDiag >::applySymmetryBC(), and StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> XArray& StructureBCS< X, Diag, OffDiag >::_r protected
Definition at line 261 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applyDirichletBC(), StructureBCS< X, Diag, OffDiag >::applyInterfaceBC(), StructureBCS< X, Diag, OffDiag >::applyNeumannBC(), StructureBCS< X, Diag, OffDiag >::applySymmetryBC(), and StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> const Field& StructureBCS< X, Diag, OffDiag >::_varField protected
Definition at line 255 of file StructureModel_impl.h.
template<class X, class Diag, class OffDiag> XArray& StructureBCS< X, Diag, OffDiag >::_x protected
Definition at line 260 of file StructureModel_impl.h.
Referenced by StructureBCS< X, Diag, OffDiag >::applyDirichletBC(), StructureBCS< X, Diag, OffDiag >::applySymmetryBC(), and StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
template<class X, class Diag, class OffDiag> const MultiField::ArrayIndex StructureBCS< X, Diag, OffDiag >::_xIndex protected
Definition at line 256 of file StructureModel_impl.h.
The documentation for this class was generated from the following file:
StructureModel_impl.h