Memosa-FVM: DensityOfStates< T > Class Template Reference
DensityOfStates< T > Class Template Reference
#include <DensityOfStates.h>
Public Types
typedef Array< T > TArray
typedef Vector< T, 3 > VectorT3
typedef shared_ptr< TArray > TArrPtr
typedef vector< TArrPtr > TArrList
typedef Array< int > IntArray
typedef shared_ptr< IntArray > IntArrayPtr
typedef vector< IntArrayPtr > IntArrList
typedef Kspace< T > Tkspace
typedef kvol< T > Tkvol
typedef pmode< T > Tmode
Public Member Functions
DensityOfStates (const Tkspace &kspace)
void binMode (const int mode, const int noBins, const T minw, const T maxw)
void binEntireKspace (const int noBins, const T minw, const T maxw)
void copyDOS (DensityOfStates &otherDOS)
void setDensity ()
const Tkspace & getKspace ()
void saveNormDOS (const char *filename)
ArrayBase * getFreqMids ()
ArrayBase * getFreqBins ()
TArray & getFreqMidsT ()
TArray & getFreqBinsT ()
int findBin (const TArray &bounds, const T freq)
const int findBin (const T freq) const
IntArray & getKIndices (const int fBin)
IntArray & getMIndices (const int fBin)
IntArrList & getKptsList ()
IntArrList & getMList ()
TArray & getModeFractions (const int fBin)
T sumOutgoing (const VectorT3 &n, const int fBin, const T Temp)
ArrayBase * makeDMMtransmission (DensityOfStates &otherDOS, const T Temp, const bool merge)
T calcBinFlux (const T Temp, const int fBin, const T tau)
void mergeBins (DensityOfStates &otherDOS, const bool original)
void refineBins ()
ArrayBase * makeDMMreflection (ArrayBase *trans)
Private Member Functions
void addMode (const TArray &mBounds, const TArray &mMids, const IntArrList &mKlist, const int mode)
void setMids ()
Private Attributes
TArray _FreqMids
TArray _FreqBounds
TArray _Density
IntArrList _BinKpts
IntArrList _BinModes
TArrList _ModeFractions
const Tkspace & _kspace
Detailed Description
template<class T>
class DensityOfStates< T >
Definition at line 12 of file DensityOfStates.h.
Member Typedef Documentation
template<class T> typedef Array<int> DensityOfStates< T >::IntArray
Definition at line 20 of file DensityOfStates.h.
template<class T> typedef shared_ptr<IntArray> DensityOfStates< T >::IntArrayPtr
Definition at line 21 of file DensityOfStates.h.
template<class T> typedef vector<IntArrayPtr> DensityOfStates< T >::IntArrList
Definition at line 22 of file DensityOfStates.h.
template<class T> typedef Array<T> DensityOfStates< T >::TArray
Definition at line 16 of file DensityOfStates.h.
template<class T> typedef vector<TArrPtr> DensityOfStates< T >::TArrList
Definition at line 19 of file DensityOfStates.h.
template<class T> typedef shared_ptr<TArray> DensityOfStates< T >::TArrPtr
Definition at line 18 of file DensityOfStates.h.
template<class T> typedef Kspace<T> DensityOfStates< T >::Tkspace
Definition at line 23 of file DensityOfStates.h.
template<class T> typedef kvol<T> DensityOfStates< T >::Tkvol
Definition at line 24 of file DensityOfStates.h.
template<class T> typedef pmode<T> DensityOfStates< T >::Tmode
Definition at line 25 of file DensityOfStates.h.
template<class T> typedef Vector<T,3> DensityOfStates< T >::VectorT3
Definition at line 17 of file DensityOfStates.h.
Constructor & Destructor Documentation
template<class T> DensityOfStates< T >::DensityOfStates (const Tkspace & kspace) inline
Definition at line 27 of file DensityOfStates.h.
                                        :
   _FreqMids(0),
     _FreqBounds(0),
     _Density(0),
     _BinKpts(),
     _BinModes(),
     _ModeFractions(),
     _kspace(kspace)
     {}
Member Function Documentation
template<class T> void DensityOfStates< T >::addMode (const TArray & mBounds, const TArray & mMids, const IntArrList & mKlist, const int mode) inline private
Definition at line 567 of file DensityOfStates.h.
References DensityOfStates< T >::_BinKpts, DensityOfStates< T >::_BinModes, DensityOfStates< T >::_FreqBounds, DensityOfStates< T >::_FreqMids, DensityOfStates< T >::_ModeFractions, Array< T >::copyFrom(), Array< T >::getLength(), min(), Array< T >::resize(), DensityOfStates< T >::setMids(), and Array< T >::zero().
Referenced by DensityOfStates< T >::binMode().
   {
     if(_BinKpts.empty())
       {
         _FreqMids.resize(mMids.getLength());
         _FreqMids.copyFrom(mMids);
         _FreqBounds.resize(mBounds.getLength());
         _FreqBounds.copyFrom(mBounds);
         _BinKpts=mKlist;
         _BinModes.resize(mMids.getLength());
         _ModeFractions.resize(mMids.getLength());
         for(int i=0;i<mMids.getLength();i++)
           {
             IntArray& Karray=*_BinKpts[i];
             IntArrayPtr MarrayPtr=IntArrayPtr(new IntArray(Karray.getLength()));
             TArrPtr FracArrPtr=TArrPtr(new TArray(Karray.getLength()));
             *MarrayPtr=mode;
             *FracArrPtr=1.;
             _BinModes[i]=MarrayPtr;
             _ModeFractions[i]=FracArrPtr;
           }
       }
     else
       {
         TArray old(_FreqBounds.getLength());
         old.copyFrom(_FreqBounds);
         int newBinCount(0);
         int i(0), j(0);
         T ceil=min(old[0], mBounds[0]);
         T o,m;
         while(i<old.getLength() || j<mBounds.getLength())
           {
             if(i<old.getLength())
               o=old[i];
             else
               o=mBounds[j]+1.;
             if(j<mBounds.getLength())
               m=mBounds[j];
             else
               m=old[i]+1.;
             if(o==m)
               {
                 if(o>ceil)
                   {
                     newBinCount++;
                     ceil=o;
                   }
                 i++;
                 j++;
               }
             else if( o>=ceil && o<m)
               {
                 if(o>ceil)
                   {
                     ceil=o;
                     newBinCount++;
                   }
                 i++;
               }
             else if(m>=ceil && m<o)
               {
                 if(m>ceil)
                   {
                     ceil=m;
                     newBinCount++;
                   }
                 j++;
               }
           }
         TArray newBounds(newBinCount+1);
         ceil=min(old[0], mBounds[0]);
         i=0;
         j=0;
         newBinCount=1;
         newBounds[0]=ceil;
         while(i<old.getLength() || j<mBounds.getLength())
           {
             if(i<old.getLength())
               o=old[i];
             else
               o=mBounds[j]+1.;
             if(j<mBounds.getLength())
               m=mBounds[j];
             else
               m=old[i]+1.;
             if(o==m)
               {
                 if(o>ceil)
                   {
                     newBounds[newBinCount]=o;
                     newBinCount++;
                   }
                 i++;
                 j++;
               }
             else if( o>=ceil && o<m)
               {
                 if(o>ceil)
                   {
                     ceil=o;
                     newBounds[newBinCount]=o;
                     newBinCount++;
                   }
                 i++;
               }
             else if(m>=ceil && m<o)
               {
                 if(m>ceil)
                   {
                     ceil=m;
                     newBounds[newBinCount]=m;
                     newBinCount++;
                   }
                 j++;
               }
           }
         _FreqBounds.resize(newBounds.getLength());
         _FreqBounds.copyFrom(newBounds);
         setMids();
         IntArray BinPop(_FreqMids.getLength());
         BinPop.zero();
         int searchStart(0);
         for(int k=0; k<mBounds.getLength()-1;k++)
           {
             const T mTop=mBounds[k+1];
             const T mBot=mBounds[k];
             IntArray& klist=*mKlist[k];
             const int plusKs=klist.getLength();
             for(int l=searchStart;l<_FreqBounds.getLength();l++)
               {
                 if(_FreqBounds[l]>=mBot && _FreqBounds[l]<mTop)
                   BinPop[l]+=plusKs;
                 if(_FreqBounds[l]==mTop)
                   {
                     searchStart=l;
                     break;
                   }
               }
           }
         searchStart=0;
         for(int k=0; k<old.getLength()-1;k++)
           {
             const T oTop=old[k+1];
             const T oBot=old[k];
             IntArray& klist=*_BinKpts[k];
             const int plusKs=klist.getLength();
             for(int l=searchStart;l<_FreqBounds.getLength();l++)
               {
                 if(_FreqBounds[l]>=oBot && _FreqBounds[l]<oTop)
                   BinPop[l]+=plusKs;
                 if(_FreqBounds[l]>=oTop)
                   {
                     searchStart=l;
                     break;
                   }
               }
           }
         IntArrList oldBinKpts=_BinKpts;
         IntArrList oldBinModes=_BinModes;
         TArrList oldModeFractions=_ModeFractions;
         _BinKpts.resize(_FreqMids.getLength());
         _BinModes.resize(_FreqMids.getLength());
         _ModeFractions.resize(_FreqMids.getLength());
         for(int fInd=0;fInd<_FreqMids.getLength();fInd++)
           {
             const int len=BinPop[fInd];
             IntArrayPtr newKArray=IntArrayPtr(new IntArray(len));
             IntArrayPtr newMArray=IntArrayPtr(new IntArray(len));
             TArrPtr newFArray=TArrPtr(new TArray(len));
             _BinKpts[fInd]=newKArray;
             _BinModes[fInd]=newMArray;
             _ModeFractions[fInd]=newFArray;
           }
         searchStart=0;
         BinPop.zero();
         for(int k=0; k<mBounds.getLength()-1;k++)
           {
             const T mTop=mBounds[k+1];
             const T mBot=mBounds[k];
             const T dif=mTop-mBot;
             IntArray& klist=*mKlist[k];
             for(int l=searchStart;l<_FreqBounds.getLength();l++)
               {
                 if(_FreqBounds[l]>=mBot && _FreqBounds[l]<mTop)
                   {
                     const T masterDif=_FreqBounds[l+1]-_FreqBounds[l];
                     const T coeff=masterDif/dif;
                     IntArray& newKArray=*_BinKpts[l];
                     IntArray& newMArray=*_BinModes[l];
                     TArray& newFArray=*_ModeFractions[l];
                     for(int addInd=0;addInd<klist.getLength();addInd++)
                       {
                         newKArray[BinPop[l]]=klist[addInd];
                         newMArray[BinPop[l]]=mode;
                         newFArray[BinPop[l]]=coeff;
                         BinPop[l]++;
                       }
                   }
                 if(_FreqBounds[l]==mTop)
                   {
                     searchStart=l;
                     break;
                   }
               }
           }
         searchStart=0;
         for(int k=0; k<old.getLength()-1;k++)
           {
             const T oTop=old[k+1];
             const T oBot=old[k];
             const T dif=oTop-oBot;
             IntArray& klist=*oldBinKpts[k];
             IntArray& mlist=*oldBinModes[k];
             TArray& fraclist=*oldModeFractions[k];
             for(int l=searchStart;l<_FreqBounds.getLength();l++)
               {
                 if(_FreqBounds[l]>=oBot && _FreqBounds[l]<oTop)
                   {
                     const T masterDif=_FreqBounds[l+1]-_FreqBounds[l];
                     const T coeff=masterDif/dif;
                     IntArray& newKArray=*_BinKpts[l];
                     IntArray& newMArray=*_BinModes[l];
                     TArray& newFArray=*_ModeFractions[l];
                     for(int addInd=0;addInd<klist.getLength();addInd++)
                       {
                         newKArray[BinPop[l]]=klist[addInd];
                         newMArray[BinPop[l]]=mlist[addInd];
                         newFArray[BinPop[l]]=coeff*fraclist[addInd];
                         BinPop[l]++;
                       }
                   }
                 if(_FreqBounds[l]==oTop)
                   {
                     searchStart=l;
                     break;
                   }
               }
           }
       }
   }
template<class T> void DensityOfStates< T >::binEntireKspace (const int noBins, const T minw, const T maxw) inline
Definition at line 91 of file DensityOfStates.h.
References DensityOfStates< T >::_BinKpts, DensityOfStates< T >::_BinModes, DensityOfStates< T >::_FreqBounds, DensityOfStates< T >::_FreqMids, DensityOfStates< T >::_kspace, Array< T >::copyFrom(), DensityOfStates< T >::findBin(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getomega(), Array< T >::resize(), and Array< T >::zero().
   {
     const T dwStar=1./T(noBins);
     T Deltaw;
     if(minw==0.)
       Deltaw=maxw;
     else
       {
         T ratio=minw/maxw;
         Deltaw=(1-ratio)*maxw;
       }
     TArray modeBounds(noBins+1);
     TArray modeMids(noBins);
     IntArray BinKcount(noBins);
     IntArray BinMcount(noBins);
     BinKcount.zero();
     BinMcount.zero();
     IntArrList modeKpts;
     IntArrList Mpts;
     for(int i=0;i<noBins+1;i++)
       modeBounds[i]=floor(i*dwStar*Deltaw+minw);
     for(int i=0;i<noBins;i++)
       modeMids[i]=(modeBounds[i]+modeBounds[i+1])/2.;
     const int klen=_kspace.getlength();
     for(int k=0;k<klen;k++)
       {
         Tkvol& kv=_kspace.getkvol(k);
         const int modeNum=kv.getmodenum();
         for(int m=0;m<modeNum;m++)
           {
             T omega=kv.getmode(m).getomega();
             int bin=findBin(modeBounds, omega);
             BinKcount[bin]++;
             BinMcount[bin]++;
           }
       }
     for(int i=0;i<noBins;i++)
       {
         IntArrayPtr newArrPtr=IntArrayPtr(new IntArray(BinKcount[i]));
         IntArrayPtr newArrPtr1=IntArrayPtr(new IntArray(BinKcount[i]));
         newArrPtr->zero();
         newArrPtr1->zero();
         modeKpts.push_back(newArrPtr);
         Mpts.push_back(newArrPtr1);
       }
     BinKcount.zero();
     BinMcount.zero();
     for(int k=0;k<klen;k++)
       {
         Tkvol& kv=_kspace.getkvol(k);
         const int modeNum=kv.getmodenum();
         for(int m=0;m<modeNum;m++)
           {
             T omega=kv.getmode(m).getomega();
             int bin=findBin(modeBounds, omega);
             IntArray& binArray=*modeKpts[bin];
             IntArray& mbinArray=*Mpts[bin];
             binArray[BinKcount[bin]]=k;
             mbinArray[BinKcount[bin]]=m;
             BinKcount[bin]++;
           }
       }
     _FreqMids.resize(noBins);
     _FreqMids.copyFrom(modeMids);
     _FreqBounds.resize(noBins+1);
     _FreqBounds.copyFrom(modeBounds);
     _BinKpts=modeKpts;
     _BinModes=Mpts;
   }
template<class T> void DensityOfStates< T >::binMode (const int mode, const int noBins, const T minw, const T maxw) inline
Definition at line 37 of file DensityOfStates.h.
References DensityOfStates< T >::_kspace, DensityOfStates< T >::addMode(), DensityOfStates< T >::findBin(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), pmode< T >::getomega(), and Array< T >::zero().
   {
     const T dwStar=1./T(noBins);
     T Deltaw;
     if(minw==0.)
       Deltaw=maxw;
     else
       {
         T ratio=minw/maxw;
         Deltaw=(1-ratio)*maxw;
       }
     TArray modeBounds(noBins+1);
     TArray modeMids(noBins);
     IntArray BinKcount(noBins);
     BinKcount.zero();
     IntArrList modeKpts;
     for(int i=0;i<noBins+1;i++)
       modeBounds[i]=floor(i*dwStar*Deltaw+minw);
     for(int i=0;i<noBins;i++)
       modeMids[i]=(modeBounds[i]+modeBounds[i+1])/2.;
     const int klen=_kspace.getlength();
     for(int k=0;k<klen;k++)
       {
         T omega=_kspace.getkvol(k).getmode(mode).getomega();
         int bin=findBin(modeBounds, omega);
         BinKcount[bin]++;
       }
     for(int i=0;i<noBins;i++)
       {
         IntArrayPtr newArrPtr=IntArrayPtr(new IntArray(BinKcount[i]));
         newArrPtr->zero();
         modeKpts.push_back(newArrPtr);
       }
     BinKcount.zero();
     for(int k=0;k<klen;k++)
       {
         T omega=_kspace.getkvol(k).getmode(mode).getomega();
         int bin=findBin(modeBounds, omega);
         IntArray& binArray=*modeKpts[bin];
         binArray[BinKcount[bin]]=k;
         BinKcount[bin]++;
       }
     addMode(modeBounds, modeMids, modeKpts, mode);
   }
template<class T> T DensityOfStates< T >::calcBinFlux (const T Temp, const int fBin, const T tau) inline
Definition at line 327 of file DensityOfStates.h.
References DensityOfStates< T >::_kspace, pmode< T >::calce0(), kvol< T >::getdk3(), DensityOfStates< T >::getKIndices(), Kspace< T >::getkvol(), Array< T >::getLength(), DensityOfStates< T >::getMIndices(), kvol< T >::getmode(), and pmode< T >::getv().
   {
     T outSum(0.);
     VectorT3 n;
     n[0]=1.;
     n[1]=0.;
     n[2]=0.;
     if(fBin>=0)
       {
         const IntArray& Kpts=getKIndices(fBin);
         const IntArray& Mpts=getMIndices(fBin);
         for(int i=0;i<Kpts.getLength();i++)
           {
             const int k=Kpts[i];
             const int m=Mpts[i];
             const VectorT3 vg=_kspace.getkvol(k).getmode(m).getv();
             const T vdot=vg[0]*n[0]+vg[1]*n[1]+vg[2]*n[2];
             const T e0=_kspace.getkvol(k).getmode(m).calce0(Temp);
             if(vdot>0.)
               {
                 const T dk3=_kspace.getkvol(k).getdk3();
                 outSum+=dk3*vdot*e0*tau;
               }
           }
       }
     return outSum;
   }
template<class T> void DensityOfStates< T >::copyDOS (DensityOfStates< T > & otherDOS) inline
Definition at line 170 of file DensityOfStates.h.
References DensityOfStates< T >::_BinKpts, DensityOfStates< T >::_BinModes, DensityOfStates< T >::_FreqBounds, DensityOfStates< T >::_FreqMids, Array< T >::copyFrom(), DensityOfStates< T >::getFreqBinsT(), DensityOfStates< T >::getFreqMidsT(), DensityOfStates< T >::getKptsList(), Array< T >::getLength(), DensityOfStates< T >::getMList(), Array< T >::resize(), and DensityOfStates< T >::setDensity().
Referenced by DensityOfStates< T >::mergeBins().
   {
     _FreqMids.resize(otherDOS.getFreqMidsT().getLength());
     _FreqMids.copyFrom(otherDOS.getFreqMidsT());
     _FreqBounds.resize(otherDOS.getFreqBinsT().getLength());
     _FreqBounds.copyFrom(otherDOS.getFreqBinsT());
     _BinKpts=otherDOS.getKptsList();
     _BinModes=otherDOS.getMList();
     setDensity();
   }
template<class T> int DensityOfStates< T >::findBin (const TArray & bounds, const T freq) inline
Definition at line 223 of file DensityOfStates.h.
References Array< T >::getLength().
Referenced by DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::binMode(), DensityOfStates< T >::makeDMMtransmission(), and DensityOfStates< T >::mergeBins().
   {
     for(int i=0;i<bounds.getLength()-1;i++)
       {
         if(freq>bounds[i] && freq<=bounds[i+1])
           return i;
       }
     throw CException("Frequency not in given discretization!");
   }
template<class T> const int DensityOfStates< T >::findBin (const T freq) const inline
Definition at line 233 of file DensityOfStates.h.
References DensityOfStates< T >::_FreqBounds, and Array< T >::getLength().
   {
     for(int i=0;i<_FreqBounds.getLength()-1;i++)
       {
         if(freq>_FreqBounds[i] && freq<=_FreqBounds[i+1])
           return i;
       }
     return -1;
   }
template<class T> ArrayBase* DensityOfStates< T >::getFreqBins () inline
Definition at line 219 of file DensityOfStates.h.
References DensityOfStates< T >::_FreqBounds.
 {return &_FreqBounds;}
template<class T> TArray& DensityOfStates< T >::getFreqBinsT () inline
Definition at line 221 of file DensityOfStates.h.
References DensityOfStates< T >::_FreqBounds.
Referenced by DensityOfStates< T >::copyDOS(), and DensityOfStates< T >::mergeBins().
 {return _FreqBounds;}
template<class T> ArrayBase* DensityOfStates< T >::getFreqMids () inline
Definition at line 218 of file DensityOfStates.h.
References DensityOfStates< T >::_FreqMids.
 {return &_FreqMids;}
template<class T> TArray& DensityOfStates< T >::getFreqMidsT () inline
Definition at line 220 of file DensityOfStates.h.
References DensityOfStates< T >::_FreqMids.
Referenced by COMETModel< T >::binwiseHeatFluxIntegral(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), COMETModel< T >::calcBandTemps(), DensityOfStates< T >::copyDOS(), and COMETInterface< T >::makeDMMcoeffs().
 {return _FreqMids;}
template<class T> IntArray& DensityOfStates< T >::getKIndices (const int fBin) inline
Definition at line 243 of file DensityOfStates.h.
References DensityOfStates< T >::_BinKpts.
Referenced by COMETModel< T >::binwiseHeatFluxIntegral(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), COMETModel< T >::calcBandTemps(), DensityOfStates< T >::calcBinFlux(), COMETInterface< T >::makeDMMcoeffs(), and DensityOfStates< T >::sumOutgoing().
 {return *_BinKpts[fBin];}
template<class T> IntArrList& DensityOfStates< T >::getKptsList () inline
Definition at line 245 of file DensityOfStates.h.
References DensityOfStates< T >::_BinKpts.
Referenced by DensityOfStates< T >::copyDOS().
 {return _BinKpts;}
template<class T> const Tkspace& DensityOfStates< T >::getKspace () inline
Definition at line 196 of file DensityOfStates.h.
References DensityOfStates< T >::_kspace.
Referenced by DensityOfStates< T >::mergeBins().
 {return _kspace;}
template<class T> IntArray& DensityOfStates< T >::getMIndices (const int fBin) inline
Definition at line 244 of file DensityOfStates.h.
References DensityOfStates< T >::_BinModes.
Referenced by COMETModel< T >::binwiseHeatFluxIntegral(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), COMETModel< T >::calcBandTemps(), DensityOfStates< T >::calcBinFlux(), COMETInterface< T >::makeDMMcoeffs(), and DensityOfStates< T >::sumOutgoing().
 {return *_BinModes[fBin];}
template<class T> IntArrList& DensityOfStates< T >::getMList () inline
Definition at line 246 of file DensityOfStates.h.
References DensityOfStates< T >::_BinModes.
Referenced by DensityOfStates< T >::copyDOS().
 {return _BinModes;}
template<class T> TArray& DensityOfStates< T >::getModeFractions (const int fBin) inline
Definition at line 247 of file DensityOfStates.h.
References DensityOfStates< T >::_ModeFractions.
 {return *_ModeFractions[fBin];}
template<class T> ArrayBase* DensityOfStates< T >::makeDMMreflection (ArrayBase * trans) inline
Definition at line 556 of file DensityOfStates.h.
References Array< T >::getLength().
   {
     TArray* Ttrans=dynamic_cast<TArray*>(trans);
     TArray* refl=new TArray(Ttrans->getLength());
     for(int i=0;i<Ttrans->getLength();i++)
       (*refl)[i]=1.-(*Ttrans)[i];
     return refl;
   }
template<class T> ArrayBase* DensityOfStates< T >::makeDMMtransmission (DensityOfStates< T > & otherDOS, const T Temp, const bool merge) inline
Definition at line 300 of file DensityOfStates.h.
References DensityOfStates< T >::_FreqMids, DensityOfStates< T >::findBin(), Array< T >::getLength(), DensityOfStates< T >::mergeBins(), and DensityOfStates< T >::sumOutgoing().
   {
     if(merge)
       mergeBins(otherDOS, true);
     const int freqCount=_FreqMids.getLength();
     TArray* trans=new TArray(freqCount);
     VectorT3 n;
     n[0]=1.;
     n[1]=0.;
     n[2]=0.;
     for(int f0=0;f0<freqCount;f0++)
       {
         T w0=_FreqMids[f0];
         const int f1=otherDOS.findBin(w0);
         const T mat0sum=sumOutgoing(n,f0,Temp);
         const T mat1sum=otherDOS.sumOutgoing(-n,f1,Temp);
         if(mat1sum==0. && mat0sum==0.)
           (*trans)[f0]=0.;
         else
           (*trans)[f0]=1./(1.+mat0sum/mat1sum);
       }
     return trans;
   }
template<class T> void DensityOfStates< T >::mergeBins (DensityOfStates< T > & otherDOS, const bool original) inline
Definition at line 358 of file DensityOfStates.h.
References DensityOfStates< T >::_BinKpts, DensityOfStates< T >::_BinModes, DensityOfStates< T >::_FreqBounds, DensityOfStates< T >::_FreqMids, DensityOfStates< T >::_kspace, DensityOfStates< T >::_ModeFractions, DensityOfStates< T >::copyDOS(), Array< T >::copyFrom(), DensityOfStates< T >::findBin(), DensityOfStates< T >::getFreqBinsT(), DensityOfStates< T >::getKspace(), Kspace< T >::getkvol(), Array< T >::getLength(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getomega(), DensityOfStates< T >::mergeBins(), min(), Array< T >::resize(), DensityOfStates< T >::setDensity(), DensityOfStates< T >::setMids(), and Array< T >::zero().
Referenced by DensityOfStates< T >::makeDMMtransmission(), and DensityOfStates< T >::mergeBins().
   {
     DensityOfStates oldSelf(getKspace());
     oldSelf.copyDOS(*this);
     TArray old(_FreqBounds.getLength());
     TArray& mBounds=otherDOS.getFreqBinsT();
     old.copyFrom(_FreqBounds);
     int newBinCount(0);
     int i(0), j(0);
     T ceil=min(old[0], mBounds[0]);
     T o,m;
     while(i<old.getLength() || j<mBounds.getLength())
       {
         if(i<old.getLength())
           o=old[i];
         else
           o=mBounds[j]+1.;
         if(j<mBounds.getLength())
           m=mBounds[j];
         else
           m=old[i]+1.;
         if(o==m)
           {
             if(o>ceil)
               {
                 newBinCount++;
                 ceil=o;
               }
             i++;
             j++;
           }
         else if( o>=ceil && o<m)
           {
             if(o>ceil)
               {
                 ceil=o;
                 newBinCount++;
               }
             i++;
           }
         else if(m>=ceil && m<o)
           {
             if(m>ceil)
               {
                 ceil=m;
                 newBinCount++;
               }
             j++;
           }
       }
     TArray newBounds(newBinCount+1);
     ceil=min(old[0], mBounds[0]);
     i=0;
     j=0;
     newBinCount=1;
     newBounds[0]=ceil;
     while(i<old.getLength() || j<mBounds.getLength())
       {
         if(i<old.getLength())
           o=old[i];
         else
           o=mBounds[j]+1.;
         if(j<mBounds.getLength())
           m=mBounds[j];
         else
           m=old[i]+1.;
         if(o==m)
           {
             if(o>ceil)
               {
                 newBounds[newBinCount]=o;
                 newBinCount++;
               }
             i++;
             j++;
           }
         else if( o>=ceil && o<m)
           {
             if(o>ceil)
               {
                 ceil=o;
                 newBounds[newBinCount]=o;
                 newBinCount++;
               }
             i++;
           }
         else if(m>=ceil && m<o)
           {
             if(m>ceil)
               {
                 ceil=m;
                 newBounds[newBinCount]=m;
                 newBinCount++;
               }
             j++;
           }
       }
     _FreqBounds.resize(newBounds.getLength());
     _FreqBounds.copyFrom(newBounds);
     //refineBins();
     setMids();
     IntArray BinPop(_FreqMids.getLength());
     BinPop.zero();
     //int searchStart(0);
     const int klen=_kspace.getlength();
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         const int modenum=kvol.getmodenum();
         for(int mode=0;mode<modenum;mode++)
           {
             T omega=_kspace.getkvol(k).getmode(mode).getomega();
             int bin=findBin(_FreqBounds, omega);
             BinPop[bin]++;
           }
       }
     _BinKpts.resize(_FreqMids.getLength());
     _BinModes.resize(_FreqMids.getLength());
     _ModeFractions.resize(_FreqMids.getLength());
     for(int fInd=0;fInd<_FreqMids.getLength();fInd++)
       {
         const int len=BinPop[fInd];
         IntArrayPtr newKArray=IntArrayPtr(new IntArray(len));
         IntArrayPtr newMArray=IntArrayPtr(new IntArray(len));
         TArrPtr newFArray=TArrPtr(new TArray(len));
         _BinKpts[fInd]=newKArray;
         _BinModes[fInd]=newMArray;
         _ModeFractions[fInd]=newFArray;
       }
     BinPop.zero();
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         const int modenum=kvol.getmodenum();
         for(int mode=0;mode<modenum;mode++)
           {
             T omega=_kspace.getkvol(k).getmode(mode).getomega();
             int bin=findBin(_FreqBounds, omega);
             IntArray& binKArray=*_BinKpts[bin];
             IntArray& binMArray=*_BinModes[bin];
             binKArray[BinPop[bin]]=k;
             binMArray[BinPop[bin]]=mode;
             BinPop[bin]++;
           }
       }
     setDensity();
     if(original)
       otherDOS.mergeBins(oldSelf,false);
   }
template<class T> void DensityOfStates< T >::refineBins () inline
Definition at line 525 of file DensityOfStates.h.
References DensityOfStates< T >::_FreqBounds, Array< T >::copyFrom(), Array< T >::getLength(), and Array< T >::resize().
   {
     int newBinCount(0);
     const T eps=1.e-9;
     TArray old(_FreqBounds.getLength());
     old.copyFrom(_FreqBounds);
     int i(0);
     while(i<_FreqBounds.getLength()-1)
       {
         T dif=1.-_FreqBounds[i+1]/_FreqBounds[i];
         if(dif<eps)
           {
             old[newBinCount]=_FreqBounds[i];
             newBinCount++;
             i+=2;
           }
         else
           {
             old[newBinCount]=_FreqBounds[i];
             newBinCount++;
             i++;
           }
       }
     old[newBinCount]=_FreqBounds[_FreqBounds.getLength()-1];
     _FreqBounds.resize(newBinCount+1);
     for(int j=0;j<newBinCount+1;j++)
       _FreqBounds[j]=old[j];
   }
template<class T> void DensityOfStates< T >::saveNormDOS (const char * filename) inline
Definition at line 198 of file DensityOfStates.h.
References DensityOfStates< T >::_Density, DensityOfStates< T >::_FreqBounds, DensityOfStates< T >::_FreqMids, and Array< T >::getLength().
   {
     const T wMax=_FreqBounds[_FreqBounds.getLength()-1];
     const T wMin=_FreqBounds[0];
     const T freqDif=wMax-wMin;
     T maxDen=0.0;
     for(int i=0;i<_FreqMids.getLength();i++)
       if(_Density[i]>maxDen)
         maxDen=_Density[i];
     ofstream DOSfile;
     DOSfile.open(filename);
     for(int i=0;i<_FreqMids.getLength();i++)
       DOSfile<<(_FreqMids[i]-wMin)/freqDif<<" "<<_Density[i]/maxDen<<endl;
     DOSfile.close();
   }
template<class T> void DensityOfStates< T >::setDensity () inline
Definition at line 181 of file DensityOfStates.h.
References DensityOfStates< T >::_BinKpts, DensityOfStates< T >::_Density, DensityOfStates< T >::_FreqMids, DensityOfStates< T >::_kspace, kvol< T >::getdk3(), Kspace< T >::getkvol(), Array< T >::getLength(), Array< T >::resize(), and Array< T >::zero().
Referenced by DensityOfStates< T >::copyDOS(), and DensityOfStates< T >::mergeBins().
   {
     _Density.resize(_FreqMids.getLength());
     _Density.zero();
     for(int i=0;i<_Density.getLength();i++)
       {
         IntArray& Kpts=*_BinKpts[i];
         for(int j=0;j<Kpts.getLength();j++)
           {
             const T dk3=_kspace.getkvol(Kpts[j]).getdk3();
             _Density[i]+=dk3;
           }
       }
   }
template<class T> void DensityOfStates< T >::setMids () inline private
Definition at line 831 of file DensityOfStates.h.
References DensityOfStates< T >::_FreqBounds, DensityOfStates< T >::_FreqMids, Array< T >::getLength(), and Array< T >::resize().
Referenced by DensityOfStates< T >::addMode(), and DensityOfStates< T >::mergeBins().
   {
     _FreqMids.resize(_FreqBounds.getLength()-1);
     for(int i=0;i<_FreqBounds.getLength()-1;i++)
       _FreqMids[i]=(_FreqBounds[i]+_FreqBounds[i+1])/2.;
   }
template<class T> T DensityOfStates< T >::sumOutgoing (const VectorT3 & n, const int fBin, const T Temp) inline
Definition at line 249 of file DensityOfStates.h.
References DensityOfStates< T >::_kspace, pmode< T >::calce0(), kvol< T >::getdk3(), DensityOfStates< T >::getKIndices(), Kspace< T >::getkvol(), Array< T >::getLength(), DensityOfStates< T >::getMIndices(), kvol< T >::getmode(), and pmode< T >::getv().
Referenced by DensityOfStates< T >::makeDMMtransmission().
   {
     T outSum(0.);
     if(fBin>=0)
       {
         const IntArray& Kpts=getKIndices(fBin);
         const IntArray& Mpts=getMIndices(fBin);
         for(int i=0;i<Kpts.getLength();i++)
           {
             const int k=Kpts[i];
             const int m=Mpts[i];
             const VectorT3 vg=_kspace.getkvol(k).getmode(m).getv();
             const T vdot=vg[0]*n[0]+vg[1]*n[1]+vg[2]*n[2];
             if(vdot>0.)
               {
                 const T dk3=_kspace.getkvol(k).getdk3();
                 outSum+=dk3*vdot*_kspace.getkvol(k).getmode(m).calce0(Temp);
               }
           }
       }
     return outSum;
   }
Member Data Documentation
template<class T> IntArrList DensityOfStates< T >::_BinKpts private
Definition at line 841 of file DensityOfStates.h.
Referenced by DensityOfStates< T >::addMode(), DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::copyDOS(), DensityOfStates< T >::getKIndices(), DensityOfStates< T >::getKptsList(), DensityOfStates< T >::mergeBins(), and DensityOfStates< T >::setDensity().
template<class T> IntArrList DensityOfStates< T >::_BinModes private
Definition at line 842 of file DensityOfStates.h.
Referenced by DensityOfStates< T >::addMode(), DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::copyDOS(), DensityOfStates< T >::getMIndices(), DensityOfStates< T >::getMList(), and DensityOfStates< T >::mergeBins().
template<class T> TArray DensityOfStates< T >::_Density private
Definition at line 840 of file DensityOfStates.h.
Referenced by DensityOfStates< T >::saveNormDOS(), and DensityOfStates< T >::setDensity().
template<class T> TArray DensityOfStates< T >::_FreqBounds private
Definition at line 839 of file DensityOfStates.h.
Referenced by DensityOfStates< T >::addMode(), DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::copyDOS(), DensityOfStates< T >::findBin(), DensityOfStates< T >::getFreqBins(), DensityOfStates< T >::getFreqBinsT(), DensityOfStates< T >::mergeBins(), DensityOfStates< T >::refineBins(), DensityOfStates< T >::saveNormDOS(), and DensityOfStates< T >::setMids().
template<class T> TArray DensityOfStates< T >::_FreqMids private
Definition at line 838 of file DensityOfStates.h.
Referenced by DensityOfStates< T >::addMode(), DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::copyDOS(), DensityOfStates< T >::getFreqMids(), DensityOfStates< T >::getFreqMidsT(), DensityOfStates< T >::makeDMMtransmission(), DensityOfStates< T >::mergeBins(), DensityOfStates< T >::saveNormDOS(), DensityOfStates< T >::setDensity(), and DensityOfStates< T >::setMids().
template<class T> const Tkspace& DensityOfStates< T >::_kspace private
Definition at line 844 of file DensityOfStates.h.
Referenced by DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::binMode(), DensityOfStates< T >::calcBinFlux(), DensityOfStates< T >::getKspace(), DensityOfStates< T >::mergeBins(), DensityOfStates< T >::setDensity(), and DensityOfStates< T >::sumOutgoing().
template<class T> TArrList DensityOfStates< T >::_ModeFractions private
Definition at line 843 of file DensityOfStates.h.
Referenced by DensityOfStates< T >::addMode(), DensityOfStates< T >::getModeFractions(), and DensityOfStates< T >::mergeBins().
The documentation for this class was generated from the following file:
DensityOfStates.h