Memosa-FVM: COMETBoundary< T > Class Template Reference
COMETBoundary< T > Class Template Reference
#include <COMETBoundary.h>
Public Types
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef Array< int > IntArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Kspace< T > Tkspace
typedef kvol< T > Tkvol
typedef pmode< T > Tmode
typedef Tmode::Refl_pair Refl_pair
typedef Gradient< T > GradType
typedef Array< GradType > GradArray
typedef GradientModel< T > GradModelType
typedef
GradModelType::GradMatrixType GradMatrix
Public Member Functions
COMETBoundary (const StorageSite &faces, const Mesh &mesh, const GeomFields &geomFields, Tkspace &kspace, COMETModelOptions< T > &opts, const int fg_id)
void applyTemperatureWallFine (FloatValEvaluator< T > &bTemp) const
void applyTemperatureWallCoarse (FloatValEvaluator< T > &bTemp) const
void applyTemperatureWallFine (int f, const T Twall, const GradMatrix &gMat) const
void applyTemperatureWallCoarse (int f, const T Twall) const
Protected Attributes
const StorageSite & _faces
const StorageSite & _cells
const CRConnectivity & _faceCells
const CRConnectivity & _cellCells
const VectorT3Array & _faceArea
const VectorT3Array & _cellCoords
Tkspace & _kspace
TArray & _eArray
const GeomFields & _geomFields
const Mesh & _mesh
Detailed Description
template<class T>
class COMETBoundary< T >
Definition at line 25 of file COMETBoundary.h.
Member Typedef Documentation
template<class T> typedef Array<GradType> COMETBoundary< T >::GradArray
Definition at line 39 of file COMETBoundary.h.
template<class T> typedef GradModelType::GradMatrixType COMETBoundary< T >::GradMatrix
Definition at line 41 of file COMETBoundary.h.
template<class T> typedef GradientModel<T> COMETBoundary< T >::GradModelType
Definition at line 40 of file COMETBoundary.h.
template<class T> typedef Gradient<T> COMETBoundary< T >::GradType
Definition at line 38 of file COMETBoundary.h.
template<class T> typedef Array<int> COMETBoundary< T >::IntArray
Definition at line 30 of file COMETBoundary.h.
template<class T> typedef Tmode::Refl_pair COMETBoundary< T >::Refl_pair
Definition at line 37 of file COMETBoundary.h.
template<class T> typedef NumTypeTraits<T>::T_Scalar COMETBoundary< T >::T_Scalar
Definition at line 29 of file COMETBoundary.h.
template<class T> typedef Array<T_Scalar> COMETBoundary< T >::TArray
Definition at line 31 of file COMETBoundary.h.
template<class T> typedef Kspace<T> COMETBoundary< T >::Tkspace
Definition at line 34 of file COMETBoundary.h.
template<class T> typedef kvol<T> COMETBoundary< T >::Tkvol
Definition at line 35 of file COMETBoundary.h.
template<class T> typedef pmode<T> COMETBoundary< T >::Tmode
Definition at line 36 of file COMETBoundary.h.
template<class T> typedef Vector<T_Scalar,3> COMETBoundary< T >::VectorT3
Definition at line 32 of file COMETBoundary.h.
template<class T> typedef Array<VectorT3> COMETBoundary< T >::VectorT3Array
Definition at line 33 of file COMETBoundary.h.
Constructor & Destructor Documentation
template<class T> COMETBoundary< T >::COMETBoundary (const StorageSite & faces, const Mesh & mesh, const GeomFields & geomFields, Tkspace & kspace, COMETModelOptions< T > & opts, const int fg_id) inline
Definition at line 43 of file COMETBoundary.h.
                                 :
   _faces(faces),
     _cells(mesh.getCells()),
     _faceCells(mesh.getFaceCells(_faces)),
     _cellCells(mesh.getCellCells()),
     _faceArea(dynamic_cast<const VectorT3Array&>(geomFields.area[_faces])),
     _cellCoords(dynamic_cast<const VectorT3Array&>(geomFields.coordinate[_cells])),
     _kspace(kspace),
     _eArray(kspace.geteArray()),
     _geomFields(geomFields),
     _mesh(mesh)
       {}
Member Function Documentation
template<class T> void COMETBoundary< T >::applyTemperatureWallCoarse (FloatValEvaluator< T > & bTemp) const inline
Definition at line 72 of file COMETBoundary.h.
References COMETBoundary< T >::_faces, and StorageSite::getCount().
Referenced by COMETModel< T >::applyTemperatureBoundaries(), and COMETModel< T >::initializeTemperatureBoundaries().
   {
     for (int j=0; j<_faces.getCount();j++)
       {
         applyTemperatureWallCoarse(j, bTemp[j]);
       }
   }
template<class T> void COMETBoundary< T >::applyTemperatureWallCoarse (int f, const T Twall) const inline
Definition at line 190 of file COMETBoundary.h.
References COMETBoundary< T >::_eArray, COMETBoundary< T >::_faceArea, COMETBoundary< T >::_faceCells, COMETBoundary< T >::_kspace, pmode< T >::calce0(), Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), and pmode< T >::getv().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     int numK=_kspace.getlength();
     for (int k=0;k<numK;k++)
       {
         Tkvol& kv=_kspace.getkvol(k);
         int numM=kv.getmodenum();
         for (int m=0;m<numM;m++)
           {
             Tmode& mode=kv.getmode(m);
             VectorT3 vg = mode.getv();
             const int index=mode.getIndex()-1;
             const VectorT3 en = _faceArea[f];
             const T vg_dot_en = vg[0]*en[0]+vg[1]*en[1]+vg[2]*en[2];
             const int c0ind=_kspace.getGlobalIndex(c0,index);
             const int c1ind=_kspace.getGlobalIndex(c1,index);
             if (vg_dot_en > T_Scalar(0.0))
               {
                 _eArray[c1ind]=_eArray[c0ind];
               }
             else
               _eArray[c1ind]=mode.calce0(Twall);
           }
       }
   }
template<class T> void COMETBoundary< T >::applyTemperatureWallFine (FloatValEvaluator< T > & bTemp) const inline
Definition at line 61 of file COMETBoundary.h.
References COMETBoundary< T >::_faces, COMETBoundary< T >::_geomFields, COMETBoundary< T >::_mesh, StorageSite::getCount(), and GradientModel< T >::getGradientMatrix().
Referenced by COMETModel< T >::initializeTemperatureBoundaries().
   {
     const GradMatrix& gradMatrix=GradModelType::getGradientMatrix(_mesh,_geomFields);
     for (int j=0; j<_faces.getCount();j++)
       {
         applyTemperatureWallFine(j, bTemp[j], gradMatrix);
       }
   }
template<class T> void COMETBoundary< T >::applyTemperatureWallFine (int f, const T Twall, const GradMatrix & gMat) const inline
Definition at line 80 of file COMETBoundary.h.
References COMETBoundary< T >::_cellCells, COMETBoundary< T >::_cellCoords, COMETBoundary< T >::_eArray, COMETBoundary< T >::_faceArea, COMETBoundary< T >::_faceCells, COMETBoundary< T >::_faces, COMETBoundary< T >::_geomFields, COMETBoundary< T >::_kspace, COMETBoundary< T >::_mesh, pmode< T >::calce0(), GeomFields::coordinate, Mesh::getCellFaces(), GradientMatrix< T_Scalar >::getCoeff(), CRConnectivity::getCount(), Mesh::getFaces(), Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::gettotmodes(), pmode< T >::getv(), and Array< T >::zero().
   {
     const int c0 = _faceCells(f,0);
     const int c1 = _faceCells(f,1);
     const int neibcount=_cellCells.getCount(c0);
     const VectorT3Array& faceCoords=
       dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[_faces]);
     GradArray Grads(_kspace.gettotmodes());
     Grads.zero();
     TArray pointMin(_kspace.gettotmodes());
     pointMin=-1;
     TArray pointMax(_kspace.gettotmodes());
     pointMax.zero();
     TArray pointLim(_kspace.gettotmodes());
     pointLim=100;
     VectorT3 Gcoeff;
     for(int j=0;j<neibcount;j++)    //first loop to get grad and max/min vals
       {
         const int cell1=_cellCells(c0,j);
         const VectorT3 Gcoeff=gMat.getCoeff(c0, cell1);
         int c0ind=_kspace.getGlobalIndex(c0,0);
         int c1ind=_kspace.getGlobalIndex(cell1,0);
         for(int k=0;k<_kspace.gettotmodes();k++)
           {
             const T e1=_eArray[c1ind];
             const T e0=_eArray[c0ind];
             T& curMax=pointMax[k];
             T& curMin=pointMin[k];
             Grads[k].accumulate(Gcoeff, e1-e0);
             if(e1>curMax)
               curMax=e1;
             if(curMin==-1)
               curMin=e1;
             else
               {
                 if(e1<curMin)
                   curMin=e1;
               }
             c0ind++;
             c1ind++;
           }
       }
     const StorageSite& allFaces(_mesh.getFaces());
     const VectorT3Array& allFaceCoords=
       dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[allFaces]);
     const CRConnectivity& cellFaces(_mesh.getCellFaces());
     for(int j=0;j<neibcount;j++)    //second loop to calculate limiting coeff
       {
         const int f1(cellFaces(c0,j));
         const VectorT3 dr0(allFaceCoords[f1]-_cellCoords[c0]);
         int c0ind=_kspace.getGlobalIndex(c0,0);
         //vanLeer lf;
         for(int k=0;k<_kspace.gettotmodes();k++)
           {
             const T minVal=pointMin[k];
             const T maxVal=pointMax[k];
             const T de0(Grads[k]*dr0);
             T& cl=pointLim[k];
             //computeLimitCoeff(cl, _eArray[c0ind], de0, minVal, maxVal, lf);
             c0ind++;
           }
       }
     int numK=_kspace.getlength();
     VectorT3 rVec=_cellCoords[c1]-_cellCoords[c0];
     VectorT3 fVec=faceCoords[f]-_cellCoords[c0];
     for (int k=0;k<numK;k++)
       {
         Tkvol& kv=_kspace.getkvol(k);
         int numM=kv.getmodenum();
         for (int m=0;m<numM;m++)
           {
             Tmode& mode=kv.getmode(m);
             VectorT3 vg = mode.getv();
             const int index=mode.getIndex()-1;
             const VectorT3 en = _faceArea[f];
             const T vg_dot_en = vg[0]*en[0]+vg[1]*en[1]+vg[2]*en[2];
             const int c0ind=_kspace.getGlobalIndex(c0,index);
             const int c1ind=_kspace.getGlobalIndex(c1,index);
             const GradType& grad=Grads[index];
             if (vg_dot_en > T_Scalar(0.0))
               {
                 const T SOU=(fVec[0]*grad[0]+fVec[1]*grad[1]+
                            fVec[2]*grad[2])*pointLim[index];
                 _eArray[c1ind]=_eArray[c0ind]+SOU;
               }
             else
               _eArray[c1ind]=mode.calce0(Twall);
           }
       }
   }
Member Data Documentation
template<class T> const CRConnectivity& COMETBoundary< T >::_cellCells protected
Definition at line 228 of file COMETBoundary.h.
Referenced by COMETBoundary< T >::applyTemperatureWallFine().
template<class T> const VectorT3Array& COMETBoundary< T >::_cellCoords protected
Definition at line 230 of file COMETBoundary.h.
Referenced by COMETBoundary< T >::applyTemperatureWallFine().
template<class T> const StorageSite& COMETBoundary< T >::_cells protected
Definition at line 226 of file COMETBoundary.h.
template<class T> TArray& COMETBoundary< T >::_eArray protected
Definition at line 232 of file COMETBoundary.h.
Referenced by COMETBoundary< T >::applyTemperatureWallCoarse(), and COMETBoundary< T >::applyTemperatureWallFine().
template<class T> const VectorT3Array& COMETBoundary< T >::_faceArea protected
Definition at line 229 of file COMETBoundary.h.
Referenced by COMETBoundary< T >::applyTemperatureWallCoarse(), and COMETBoundary< T >::applyTemperatureWallFine().
template<class T> const CRConnectivity& COMETBoundary< T >::_faceCells protected
Definition at line 227 of file COMETBoundary.h.
Referenced by COMETBoundary< T >::applyTemperatureWallCoarse(), and COMETBoundary< T >::applyTemperatureWallFine().
template<class T> const StorageSite& COMETBoundary< T >::_faces protected
Definition at line 225 of file COMETBoundary.h.
Referenced by COMETBoundary< T >::applyTemperatureWallCoarse(), and COMETBoundary< T >::applyTemperatureWallFine().
template<class T> const GeomFields& COMETBoundary< T >::_geomFields protected
Definition at line 233 of file COMETBoundary.h.
Referenced by COMETBoundary< T >::applyTemperatureWallFine().
template<class T> Tkspace& COMETBoundary< T >::_kspace protected
Definition at line 231 of file COMETBoundary.h.
Referenced by COMETBoundary< T >::applyTemperatureWallCoarse(), and COMETBoundary< T >::applyTemperatureWallFine().
template<class T> const Mesh& COMETBoundary< T >::_mesh protected
Definition at line 234 of file COMETBoundary.h.
Referenced by COMETBoundary< T >::applyTemperatureWallFine().
The documentation for this class was generated from the following file:
COMETBoundary.h