Memosa-FVM: Mesh Class Reference
Mesh Class Reference
#include <Mesh.h>
Public Types
enum {
CELL_BAR2, CELL_TRI3, CELL_QUAD4, CELL_TETRA4,
CELL_HEX8, CELL_PYRAMID, CELL_PRISM, CELL_TYPE_MAX
}
enum {
IBTYPE_FLUID =-1, IBTYPE_BOUNDARY =-2, IBTYPE_SOLID =-3, IBTYPE_REALBOUNDARY =-4,
IBTYPE_UNKNOWN =-5
}
typedef Vector< double, 3 > VecD3
typedef Array< int > IntArray
typedef vector< int > vecList
typedef multimap< int, int > multiMap
typedef map< int, int > mapInt
typedef pair< const
StorageSite *, const
StorageSite * > SSPair
typedef map< SSPair,
shared_ptr< CRConnectivity > > ConnectivityMap
typedef pair< int, int > PartIDMeshIDPair
typedef map< PartIDMeshIDPair,
shared_ptr< StorageSite > > GhostCellSiteMap
typedef pair< const
StorageSite *, const
StorageSite * > EntryIndex
typedef map< EntryIndex,
shared_ptr< ArrayBase > > GhostArrayMap
typedef map< int, int > PeriodicFacePairs
Public Member Functions
Mesh (const int dimension)
Mesh (const int dimension, const Array< VecD3 > &faceNodesCoord)
Mesh (const int dimension, const int nCells, const Array< VecD3 > &nodesCoord, const Array< int > &faceCellIndices, const Array< int > &faceNodeIndices, const Array< int > &faceNodeCount, const Array< int > &faceGroupSize)
~Mesh ()
DEFINE_TYPENAME ("Mesh")
int getDimension () const
int getID () const
const StorageSite & getFaces () const
const StorageSite & getCells () const
const StorageSite & getNodes () const
const StorageSite & getIBFaces () const
const StorageSite * getGhostCellSiteScatter (const PartIDMeshIDPair &id) const
const GhostCellSiteMap & getGhostCellSiteScatterMap () const
GhostCellSiteMap & getGhostCellSiteScatterMap ()
const StorageSite * getGhostCellSiteGather (const PartIDMeshIDPair &id) const
GhostCellSiteMap & getGhostCellSiteGatherMap ()
const GhostCellSiteMap & getGhostCellSiteGatherMap () const
const StorageSite * getGhostCellSiteScatterLevel1 (const PartIDMeshIDPair &id) const
const GhostCellSiteMap & getGhostCellSiteScatterMapLevel1 () const
GhostCellSiteMap & getGhostCellSiteScatterMapLevel1 ()
const StorageSite * getGhostCellSiteGatherLevel1 (const PartIDMeshIDPair &id) const
GhostCellSiteMap & getGhostCellSiteGatherMapLevel1 ()
const GhostCellSiteMap & getGhostCellSiteGatherMapLevel1 () const
StorageSite & getFaces ()
StorageSite & getCells ()
StorageSite & getNodes ()
StorageSite & getIBFaces ()
const CRConnectivity & getConnectivity (const StorageSite &from, const StorageSite &to) const
const CRConnectivity & getAllFaceNodes () const
const CRConnectivity & getAllFaceCells () const
const CRConnectivity & getCellNodes () const
const CRConnectivity & getFaceCells (const StorageSite &site) const
const CRConnectivity & getFaceNodes (const StorageSite &site) const
const CRConnectivity & getCellFaces () const
const CRConnectivity & getCellCells () const
const CRConnectivity & getCellCells2 () const
const CRConnectivity & getFaceCells2 () const
CRConnectivity & getAllFaceCells ()
const FaceGroup & getInteriorFaceGroup () const
int getFaceGroupCount () const
int getBoundaryGroupCount () const
int getInterfaceGroupCount () const
const FaceGroupList & getBoundaryFaceGroups () const
const FaceGroupList & getInterfaceGroups () const
const FaceGroupList & getAllFaceGroups () const
const FaceGroup & getFaceGroup (const int fgId) const
const StorageSite & createInteriorFaceGroup (const int size)
const StorageSite & createInterfaceGroup (const int size, const int offset, const int id)
const StorageSite & createBoundaryFaceGroup (const int size, const int offset, const int id, const string &boundaryType)
void setCoordinates (shared_ptr< Array< VecD3 > > x)
void setFaceNodes (shared_ptr< CRConnectivity > faceNodes)
void setFaceCells (shared_ptr< CRConnectivity > faceCells)
void setConnectivity (const StorageSite &rowSite, const StorageSite &colSite, shared_ptr< CRConnectivity > conn)
void eraseConnectivity (const StorageSite &rowSite, const StorageSite &colSite) const
shared_ptr< Array< int > > createAndGetBNglobalToLocal () const
const ArrayBase & getBNglobalToLocal () const
const StorageSite & getBoundaryNodes () const
const Array< VecD3 > & getNodeCoordinates () const
Array< VecD3 > & getNodeCoordinates ()
shared_ptr< ArrayBase > getNodeCoordinatesPtr ()
void setNumOfAssembleMesh (int nmesh)
const Array< int > & getIBFaceList () const
Array< int > & getCellColors ()
const Array< int > & getCellColors () const
Array< int > & getCellColorsOther ()
const Array< int > & getCellColorsOther () const
shared_ptr< Array< int > > getLocalToGlobalNodesPtr ()
const map< int, int > getGlobalToLocalNodes () const
map< int, int > getGlobalToLocalNodes ()
shared_ptr< ArrayBase > getLocalToGlobalPtr ()
Array< int > & getLocalToGlobal ()
const Array< int > & getLocalToGlobal () const
map< int, int > & getGlobalToLocal ()
const map< int, int > & getGlobalToLocal () const
multiMap & getCellCellsGlobal ()
const multiMap & getCellCellsGlobal () const
bool isMergedMesh () const
int getNumOfAssembleMesh () const
const set< int > & getBoundaryNodesSet () const
set< int > & getBoundaryNodesSet ()
const map< int, int > & getCommonFacesMap () const
const map< int, int > & getCommonFacesMapOther () const
void createScatterGatherCountsBuffer ()
void recvScatterGatherCountsBufferLocal ()
void syncCounts ()
void createScatterGatherIndicesBuffer ()
void recvScatterGatherIndicesBufferLocal ()
void syncIndices ()
const CRConnectivity & getCellCellsGhostExt () const
const ArrayBase & getSendCounts (const EntryIndex &e) const
const ArrayBase & getSendIndices (const EntryIndex &e) const
const ArrayBase & getRecvCounts (const EntryIndex &e) const
const ArrayBase & getRecvIndices (const EntryIndex &e) const
void createCellCellsGhostExt ()
void uniqueFaceCells ()
void setIBFaces (shared_ptr< Array< int > > faceList)
void createGhostCellSiteScatter (const PartIDMeshIDPair &id, shared_ptr< StorageSite > site)
void createGhostCellSiteGather (const PartIDMeshIDPair &id, shared_ptr< StorageSite > site)
void createGhostCellSiteScatterLevel1 (const PartIDMeshIDPair &id, shared_ptr< StorageSite > site)
void createGhostCellSiteGatherLevel1 (const PartIDMeshIDPair &id, shared_ptr< StorageSite > site)
void createCellColor ()
void createLocalGlobalArray ()
void createLocalToGlobalNodesArray ()
void setNodeRepeationArrayCoupling (const Mesh &bMesh)
shared_ptr< ArrayBase > getUpdatedNodesCoordCoupling (const GeomFields &geomField, const Mesh &bMesh)
void setCommonFacesMap (const Mesh &bMesh)
void findCommonNodes (Mesh &other)
void findCommonFaces (StorageSite &faces, StorageSite &otherFaces, const GeomFields &geomFields)
bool COMETfindCommonFaces (StorageSite &faces, StorageSite &otherFaces, const GeomFields &geomFields)
Mesh * extractBoundaryMesh ()
Mesh * extrude (int nz, double zmax, bool boundaryOnly=false)
Mesh * createShell (const int fgId, Mesh &otherMesh, const int otherFgId)
Mesh * createDoubleShell (const int fgId, Mesh &otherMesh, const int otherFgId, const bool connectedShell)
int getCellZoneID () const
void setCellZoneID (const int id)
void setID (const int id)
bool isShell () const
bool isDoubleShell () const
bool isConnectedShell () const
int getParentMeshID () const
int getOtherMeshID () const
const StorageSite & getParentFaceGroupSite () const
const StorageSite & getOtherFaceGroupSite () const
ConnectivityMap & getConnectivityMap ()
PeriodicFacePairs & getPeriodicFacePairs ()
const PeriodicFacePairs & getPeriodicFacePairs () const
void CRConnectivityPrint (const CRConnectivity &conn, int procID, const string &name)
void CRConnectivityPrintFile (const CRConnectivity &conn, const string &name, const int procID) const
void InterfaceToBoundary ()
Public Attributes
enum Mesh:: { ... } CellType
Protected Attributes
const int _dimension
int _id
int _cellZoneID
StorageSite _cells
StorageSite _faces
StorageSite _nodes
StorageSite _ibFaces
StorageSite * _boundaryNodes
shared_ptr< FaceGroup > _interiorFaceGroup
FaceGroupList _faceGroups
FaceGroupList _boundaryGroups
FaceGroupList _interfaceGroups
ConnectivityMap _connectivityMap
shared_ptr< Array< VecD3 > > _coordinates
shared_ptr< Array< int > > _boundaryNodeGlobalToLocalPtr
shared_ptr< Array< int > > _ibFaceList
shared_ptr< Array< int > > _cellColor
shared_ptr< Array< int > > _cellColorOther
int _numOfAssembleMesh
bool _isAssembleMesh
GhostCellSiteMap _ghostCellSiteScatterMap
GhostCellSiteMap _ghostCellSiteGatherMap
GhostCellSiteMap _ghostCellSiteScatterMapLevel1
GhostCellSiteMap _ghostCellSiteGatherMapLevel1
GhostArrayMap _sendCounts
GhostArrayMap _recvCounts
GhostArrayMap _sendIndices
GhostArrayMap _recvIndices
shared_ptr< StorageSite > _cellSiteGhostExt
shared_ptr< CRConnectivity > _cellCellsGhostExt
map< int, int > _commonFacesMap
map< int, int > _commonFacesMapOther
set< int > _boundaryNodesSet
shared_ptr< Array< int > > _repeatNodes
shared_ptr< Array< int > > _localToGlobalNodes
shared_ptr< Array< int > > _localToGlobal
map< int, int > _globalToLocal
map< int, int > _globalToLocalNodes
multiMap _cellCellsGlobal
shared_ptr< CRConnectivity > _cellCells2
shared_ptr< CRConnectivity > _faceCells2
bool _isShell
bool _isDoubleShell
bool _isConnectedShell
const StorageSite * _parentFaceGroupSite
const StorageSite * _otherFaceGroupSite
int _parentMeshID
int _otherMeshID
PeriodicFacePairs _periodicFacePairs
Static Protected Attributes
static int _lastID = 0
Private Member Functions
void createRowColSiteCRConn ()
void countCRConn ()
void addCRConn ()
int getNumBounCells ()
int get_request_size ()
Detailed Description
Definition at line 49 of file Mesh.h.
Member Typedef Documentation
typedef map<SSPair,shared_ptr<CRConnectivity> > Mesh::ConnectivityMap
Definition at line 61 of file Mesh.h.
typedef pair<const StorageSite*, const StorageSite*> Mesh::EntryIndex
Definition at line 64 of file Mesh.h.
typedef map<EntryIndex, shared_ptr<ArrayBase> > Mesh::GhostArrayMap
Definition at line 65 of file Mesh.h.
typedef map< PartIDMeshIDPair, shared_ptr<StorageSite> > Mesh::GhostCellSiteMap
Definition at line 63 of file Mesh.h.
typedef Array<int> Mesh::IntArray
Definition at line 54 of file Mesh.h.
typedef map<int,int> Mesh::mapInt
Definition at line 58 of file Mesh.h.
typedef multimap<int,int> Mesh::multiMap
Definition at line 57 of file Mesh.h.
typedef pair<int,int> Mesh::PartIDMeshIDPair
Definition at line 62 of file Mesh.h.
typedef map<int,int> Mesh::PeriodicFacePairs
Definition at line 67 of file Mesh.h.
typedef pair<const StorageSite*, const StorageSite*> Mesh::SSPair
Definition at line 60 of file Mesh.h.
typedef Vector<double,3> Mesh::VecD3
Definition at line 53 of file Mesh.h.
typedef vector<int> Mesh::vecList
Definition at line 56 of file Mesh.h.
Member Enumeration Documentation
anonymous enum
Enumerator
CELL_BAR2
CELL_TRI3
CELL_QUAD4
CELL_TETRA4
CELL_HEX8
CELL_PYRAMID
CELL_PRISM
CELL_TYPE_MAX
Definition at line 69 of file Mesh.h.
     {
       CELL_BAR2,
       CELL_TRI3,
       CELL_QUAD4,
       CELL_TETRA4,
       CELL_HEX8,
       CELL_PYRAMID,
       CELL_PRISM,
       CELL_TYPE_MAX
     } CellType;
anonymous enum
Enumerator
IBTYPE_FLUID
IBTYPE_BOUNDARY
IBTYPE_SOLID
IBTYPE_REALBOUNDARY
IBTYPE_UNKNOWN
Definition at line 82 of file Mesh.h.
     {
       IBTYPE_FLUID=-1,
       IBTYPE_BOUNDARY=-2,
       IBTYPE_SOLID=-3,
       IBTYPE_REALBOUNDARY=-4,
       IBTYPE_UNKNOWN=-5
     };
Constructor & Destructor Documentation
Mesh::Mesh (const int dimension)
Definition at line 21 of file Mesh.cpp.
References _cells, logCtor, and StorageSite::setMesh().
Referenced by createDoubleShell(), createShell(), extractBoundaryMesh(), and extrude().
                              :
   _dimension(dimension),
   _id(_lastID++),
   _cellZoneID(-1),
   _cells(0),
   _faces(0),
   _nodes(0),
   _ibFaces(0),
   _boundaryNodes(0),
   _interiorFaceGroup(),
   _faceGroups(),
   _boundaryGroups(),
   _interfaceGroups(),
   _connectivityMap(),
   _coordinates(),
   _boundaryNodeGlobalToLocalPtr(),
   _ibFaceList(),
   _numOfAssembleMesh(1),
   _isAssembleMesh(false),
   _isShell(false),
   _isDoubleShell(false),
   _isConnectedShell(false),
   _parentFaceGroupSite(0),
   _otherFaceGroupSite(0),
   _parentMeshID(0),
   _otherMeshID(0)
 {
   _cells.setMesh(this);
   logCtor();
 }
Mesh::Mesh (const int dimension, const Array< VecD3 > & faceNodesCoord)
Definition at line 52 of file Mesh.cpp.
References _connectivityMap, _dimension, createBoundaryFaceGroup(), getFaces(), Array< T >::getLength(), getNodes(), logCtor, setCoordinates(), and StorageSite::setCount().
                                                  :
   _dimension(dimension),
   _id(_lastID++),
   _cellZoneID(-1),
   _cells(0),
   _faces(0),
   _nodes(0),
   _ibFaces(0),
   _boundaryNodes(0),
   _interiorFaceGroup(),
   _faceGroups(),
   _boundaryGroups(),
   _interfaceGroups(),
   _connectivityMap(),
   _coordinates(),
   _boundaryNodeGlobalToLocalPtr(),
   _ibFaceList(),
   _numOfAssembleMesh(1),
   _isAssembleMesh(false),
   _isShell(false),
   _isDoubleShell(false),
   _isConnectedShell(false),
   _parentFaceGroupSite(0),
   _otherFaceGroupSite(0),
   _parentMeshID(0),
   _otherMeshID(0)
 {
   int faceNodeCount = _dimension == 2 ? 2 :4;
   int totNodes      = faceNodesCoord.getLength();
   // counting duplicate nodes as well for 3d
   int totFaces      = totNodes / faceNodeCount;
   //check if this is corect integer division
   assert( (faceNodeCount*totFaces) == totNodes );
   //set sites
   StorageSite& faceSite = getFaces();
   StorageSite& nodeSite = getNodes();
   faceSite.setCount( totFaces );
   nodeSite.setCount( totNodes );
   //interior face group (we have only one interface for this
   createBoundaryFaceGroup(totFaces,0,0,"wall");
   //setting coordinates
   shared_ptr< Array<VecD3> > coord( new Array< VecD3 > ( totNodes ) );
   *coord = faceNodesCoord;
   setCoordinates( coord );
   //faceNodes constructor
   shared_ptr<CRConnectivity> faceNodes( new CRConnectivity(faceSite,
                                                            nodeSite) );
   faceNodes->initCount();
   //addCount
   for ( int i = 0; i < totFaces; i++ )
     faceNodes->addCount(i, faceNodeCount);
   //finish count
   faceNodes->finishCount();
   //add operation
   int face     = 0;
   int nodeIndx = 0;
   for( int i = 0; i < totFaces; i++ )
   {
       for( int j =0; j < faceNodeCount; j++ )
       {
           faceNodes->add(face, nodeIndx++);
       }
       face++;
   }
   //finish add
   faceNodes->finishAdd();
   //setting faceNodes
   SSPair key(&faceSite,&nodeSite);
   _connectivityMap[key] = faceNodes;
   logCtor();
 }
Mesh::Mesh (const int dimension, const int nCells, const Array< VecD3 > & nodesCoord, const Array< int > & faceCellIndices, const Array< int > & faceNodeIndices, const Array< int > & faceNodeCount, const Array< int > & faceGroupSize)
Definition at line 132 of file Mesh.cpp.
References _connectivityMap, createBoundaryFaceGroup(), createInteriorFaceGroup(), getCells(), getFaces(), Array< T >::getLength(), getNodes(), logCtor, setCoordinates(), and StorageSite::setCount().
              :
   _dimension(dimension),
   _id(_lastID++),
   _cellZoneID(-1),
   _cells(0),
   _faces(0),
   _nodes(0),
   _ibFaces(0),
   _boundaryNodes(0),
   _interiorFaceGroup(),
   _faceGroups(),
   _boundaryGroups(),
   _interfaceGroups(),
   _connectivityMap(),
   _coordinates(),
   _boundaryNodeGlobalToLocalPtr(),
   _ibFaceList(),
   _numOfAssembleMesh(1),
   _isAssembleMesh(false),
   _isShell(false),
   _isDoubleShell(false),
   _isConnectedShell(false),
   _parentFaceGroupSite(0),
   _otherFaceGroupSite(0),
   _parentMeshID(0),
   _otherMeshID(0)
 {
   int nFaces = faceNodeCount.getLength();
   int nNodes      = nodesCoord.getLength();
   StorageSite& faceSite = getFaces();
   StorageSite& nodeSite = getNodes();
   StorageSite& cellSite = getCells();
   faceSite.setCount( nFaces );
   nodeSite.setCount( nNodes );
   //interior face group (we have only one interface for this
   createInteriorFaceGroup(faceGroupSize[0]);
   int nFaceGroups = faceGroupSize.getLength();
   int offset = faceGroupSize[0];
   int nBoundaryFaces =0;
   for(int nfg=1; nfg<nFaceGroups; nfg++)
   {
       createBoundaryFaceGroup(faceGroupSize[nfg], offset, nfg, "wall");
       offset += faceGroupSize[nfg];
       nBoundaryFaces += faceGroupSize[nfg];
   }
   cellSite.setCount( nCells, nBoundaryFaces );
   //setting coordinates
   shared_ptr< Array<VecD3> > coord( new Array< VecD3 > ( nNodes ) );
   *coord = nodesCoord;
   setCoordinates( coord );
   //faceNodes constructor
   shared_ptr<CRConnectivity> faceNodes( new CRConnectivity(faceSite,
                                                            nodeSite) );
   faceNodes->initCount();
   shared_ptr<CRConnectivity> faceCells( new CRConnectivity(faceSite,
                                                            cellSite) );
   faceCells->initCount();
   //addCount
   for ( int f = 0; f < nFaces; f++ )
   {
       faceNodes->addCount(f, faceNodeCount[f]);
       faceCells->addCount(f, 2);
   }
   //finish count
   faceNodes->finishCount();
   faceCells->finishCount();
   //add operation
   int nfn=0;
   int nfc=0;
   for( int f = 0; f < nFaces; f++ )
   {
       for( int j =0; j < faceNodeCount[f]; j++ )
       {
           faceNodes->add(f, faceNodeIndices[nfn++]);
       }
       faceCells->add(f,faceCellIndices[nfc++]);
       faceCells->add(f,faceCellIndices[nfc++]);
   }
   //finish add
   faceNodes->finishAdd();
   faceCells->finishAdd();
   //setting faceNodes
   SSPair key(&faceSite,&nodeSite);
   _connectivityMap[key] = faceNodes;
   SSPair key2(&faceSite,&cellSite);
   _connectivityMap[key2] = faceCells;
   logCtor();
 }
Mesh::~Mesh ()
Definition at line 250 of file Mesh.cpp.
References logDtor.
 {
   logDtor();
 }
Member Function Documentation
void Mesh::addCRConn () private
Definition at line 2309 of file Mesh.cpp.
References _cellCellsGhostExt, _recvCounts, _recvIndices, CRConnectivity::add(), CRConnectivity::finishAdd(), getCellCells(), getCells(), CRConnectivity::getCount(), StorageSite::getGatherMap(), getGlobalToLocal(), Array< T >::getLength(), getNumBounCells(), and StorageSite::getSelfCount().
Referenced by createCellCellsGhostExt().
 {
     CRConnectivity& conn = *_cellCellsGhostExt;
     const StorageSite& site = this->getCells();
     const CRConnectivity& cellCells =this->getCellCells();
     int ncount = site.getSelfCount() + getNumBounCells();
     //first inner
     //loop over olde connectivity (inner + boundary)
     for ( int i = 0; i < ncount; i++ ){
        for ( int j = 0; j < cellCells.getCount(i); j++ ){
           conn.add(i, cellCells(i,j));
         }
     }
     //CRConnectivityPrint( cellCells, 0, "cellCellsBeforeGhostExt");
     // now interfaces
     const map<int,int>& globalToLocal = this->getGlobalToLocal();
     const StorageSite::GatherMap& gatherMap = site.getGatherMap();
     foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
        const StorageSite&  oSite = *mpos.first;
        const Array<int>& gatherArray = dynamic_cast< const Array<int>& > (*mpos.second);
        EntryIndex e(&oSite,&site);
        const Array<int>& recv_counts  = dynamic_cast< const Array<int>& > (*_recvCounts [e]);
        const Array<int>& recv_indices = dynamic_cast< const Array<int>& > (*_recvIndices[e]);
        //loop over gatherArray
        int indx = 0;
        for ( int i = 0; i < gatherArray.getLength(); i++ ){
           const int ncount = recv_counts[i];
           for ( int j = 0; j < ncount; j++ ){
              const int addCell = globalToLocal.find( recv_indices[indx] )->second;
              conn.add(gatherArray[i], addCell);
              indx++;
           }
        }
     }
     //finish add
     conn.finishAdd();
 }
bool Mesh::COMETfindCommonFaces (StorageSite & faces, StorageSite & otherFaces, const GeomFields & geomFields)
Definition at line 1053 of file Mesh.cpp.
References GeomFields::area, GeomFields::coordinate, cross(), epsilon, StorageSite::getCommonMap(), StorageSite::getCount(), Array< T >::getLength(), mag(), mag2(), and sqrt().
Referenced by COMETModel< T >::init(), and COMETModel< T >::initFromOld().
 {
   const int count(faces.getCount());
   if (count != otherFaces.getCount())
     return false;
   const Array<VecD3>& coords =
     dynamic_cast<const Array<VecD3>& >(geomFields.coordinate[faces]);
   const Array<VecD3>& otherCoords =
     dynamic_cast<const Array<VecD3>& >(geomFields.coordinate[otherFaces]);
   const Array<VecD3>& area =
     dynamic_cast<const Array<VecD3>& >(geomFields.area[faces]);
   const Array<VecD3>& otherArea =
     dynamic_cast<const Array<VecD3>& >(geomFields.area[otherFaces]);
   KSearchTree thisFacesTree(coords);
   int neibs;
   if(otherCoords.getLength()>1)
     neibs=2;
   else
     neibs=1;
   Array<int> closest(neibs);
   shared_ptr<IntArray> myCommonFaces(new IntArray(count));
   shared_ptr<IntArray> otherCommonFaces(new IntArray(count));
   for(int f=0; f<count; f++)
   {
       thisFacesTree.findNeighbors(otherCoords[f],neibs,closest);
       const int closestFace = closest[0];
       double dist0 = mag(otherCoords[f] - coords[closestFace]);
       // distance between the two closest point used as scale
       double distScale;
       if(neibs==2)
         distScale=mag(coords[closest[0]] - coords[closest[1]])*epsilon;
       else
         distScale=sqrt(sqrt((area[f].mag2())))*0.00001;
       if (dist0 < distScale)
       {
           double crossProductMag(mag2(cross(otherArea[f],area[closestFace])));
           if (crossProductMag > mag2(otherArea[f])*epsilon)
             return false;
           (*otherCommonFaces)[f] = closestFace;
           (*myCommonFaces)[closestFace] = f;
       }
       else
         return false;
   }
   faces.getCommonMap()[&otherFaces] = myCommonFaces;
   otherFaces.getCommonMap()[&faces] = otherCommonFaces;
   return true;
 }
void Mesh::countCRConn () private
Definition at line 2281 of file Mesh.cpp.
References _cellCellsGhostExt, _recvCounts, CRConnectivity::addCount(), CRConnectivity::finishCount(), getCellCells(), getCells(), CRConnectivity::getCount(), StorageSite::getGatherMap(), Array< T >::getLength(), getNumBounCells(), StorageSite::getSelfCount(), and CRConnectivity::initCount().
Referenced by createCellCellsGhostExt().
 {
     CRConnectivity& conn = *_cellCellsGhostExt;
     conn.initCount();
     const StorageSite& site = this->getCells();
     const CRConnectivity& cellCells = this->getCellCells();
     int ncount = site.getSelfCount() + getNumBounCells();
     //loop over old connectivity (inner + boundary)
     for ( int i = 0; i < ncount; i++ ){
        conn.addCount(i, cellCells.getCount(i) );
     }
     // now interfaces
     const StorageSite::GatherMap& gatherMap = site.getGatherMap();
     foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
        const StorageSite&  oSite = *mpos.first;
        const Array<int>& gatherArray = dynamic_cast< const Array<int>& > (*mpos.second);
        EntryIndex e(&oSite,&site);
        const Array<int>& recv_counts = dynamic_cast< const Array<int>& > (*_recvCounts [e]);
        //loop over gatherArray
        for ( int i = 0; i < gatherArray.getLength(); i++ ){
           conn.addCount(gatherArray[i], recv_counts[i] );
        }
     }
     //finishCount
     conn.finishCount();
 }
void Mesh::CRConnectivityPrint (const CRConnectivity & conn, int procID, const string & name)
Definition at line 2379 of file Mesh.cpp.
References CRConnectivity::getCol(), Array< T >::getLength(), and CRConnectivity::getRow().
 {
 #ifdef FVM_PARALLEL
     if ( MPI::COMM_WORLD.Get_rank() == procID ){
         cout <<  name << " :" << endl;
         const Array<int>& row = conn.getRow();
         const Array<int>& col = conn.getCol();
         for ( int i = 0; i < row.getLength()-1; i++ ){
            cout << " i = " << i << ",    ";
            for ( int j = row[i]; j < row[i+1]; j++ )
               cout << col[j] << "  ";
            cout << endl;
         }
     }
 #endif
 }
void Mesh::CRConnectivityPrintFile (const CRConnectivity & conn, const string & name, const int procID) const
Definition at line 2397 of file Mesh.cpp.
References CRConnectivity::getCol(), Array< T >::getLength(), and CRConnectivity::getRow().
 {
 #ifdef FVM_PARALLEL
     if ( MPI::COMM_WORLD.Get_rank() == procID ){
        ofstream   debugFile;
        stringstream ss(stringstream::in | stringstream::out);
        ss <<  procID;
        string  fname = name +  ss.str() + ".dat";
        debugFile.open( fname.c_str() );
        ss.str("");
       debugFile <<  name << " :" << endl;
       debugFile << endl;
       const Array<int>& row = conn.getRow();
       const Array<int>& col = conn.getCol();
       for ( int i = 0; i < row.getLength()-1; i++ ){
          debugFile << " i = " << i << ",    ";
          for ( int j = row[i]; j < row[i+1]; j++ )
             debugFile << col[j] << "  ";
          debugFile << endl;
       }
       debugFile << endl;
       debugFile.close();
    }
 #endif
 }
shared_ptr< Array< int > > Mesh::createAndGetBNglobalToLocal () const
Definition at line 288 of file Mesh.cpp.
References _boundaryNodeGlobalToLocalPtr, _nodes, getAllFaceGroups(), CRConnectivity::getCol(), StorageSite::getCount(), getFaceNodes(), CRConnectivity::getRow(), CRConnectivity::getRowDim(), FaceGroup::groupType, and FaceGroup::site.
Referenced by MovingMeshModel< T >::advance(), MeshMetricsCalculator< T >::calculateBoundaryNodeNormal(), getBNglobalToLocal(), and getBoundaryNodes().
 {
   if(!_boundaryNodeGlobalToLocalPtr)
   {
       const int nNodes = _nodes.getCount();
       _boundaryNodeGlobalToLocalPtr = shared_ptr<Array<int> >(new Array<int>(nNodes));
       Array<int>& globalToLocal = *_boundaryNodeGlobalToLocalPtr;
       globalToLocal = -1;
       int BoundaryNodeCount=0;
       int nLocal=0;
       foreach(const FaceGroupPtr fgPtr, getAllFaceGroups())
       {
           const FaceGroup& fg = *fgPtr;
           if (fg.groupType != "interior")
           {
               const StorageSite& BoundaryFaces = fg.site;
               const CRConnectivity& BoundaryFaceNodes = getFaceNodes(BoundaryFaces);
               const Array<int>& BFArray = BoundaryFaceNodes.getRow();
               const Array<int>& BNArray = BoundaryFaceNodes.getCol();
               const int nBFaces = BoundaryFaceNodes.getRowDim();
               for(int i=0;i<nBFaces;i++)
               {
                   for(int ip=BFArray[i];ip<BFArray[i+1];ip++)
                   {
                       const int j = BNArray[ip];
                       if (globalToLocal[j] == -1)
                         globalToLocal[j] = nLocal++;
                   }
               }
           }
       }
       BoundaryNodeCount = nLocal;
   }
   return _boundaryNodeGlobalToLocalPtr;
 }
const StorageSite & Mesh::createBoundaryFaceGroup (const int size, const int offset, const int id, const string & boundaryType)
Definition at line 278 of file Mesh.cpp.
References _boundaryGroups, _faceGroups, and _faces.
Referenced by FluentReader::createMesh(), MeshPartitioner::extractBoundaryMesh(), extractBoundaryMesh(), extrude(), COMETModel< T >::FinishCoarseMesh(), COMETModel< T >::MakeCoarseMesh2(), and Mesh().
 {
   shared_ptr<FaceGroup> fg(new FaceGroup(size,offset,_faces,id,boundaryType));
   _faceGroups.push_back(fg);
   _boundaryGroups.push_back(fg);
   return fg->site;
 }
void Mesh::createCellCellsGhostExt ()
Definition at line 1999 of file Mesh.cpp.
References addCRConn(), countCRConn(), and createRowColSiteCRConn().
Referenced by MeshDismantler::setCellCellsGhostExt().
 {
 #ifdef FVM_PARALLEL
    createRowColSiteCRConn();
    countCRConn();
    addCRConn();
    //CRConnectivityPrint(this->getCellCellsGhostExt(), 0, "cellCells");
 #endif
 }
void Mesh::createCellColor ()
Definition at line 724 of file Mesh.cpp.
References _cellColor, _cellColorOther, _cells, _isAssembleMesh, and StorageSite::getCount().
 {
     //cellColor color ghost cells respect to self-inner cells
    _cellColor      = shared_ptr< Array<int> > ( new Array<int>( _cells.getCount() ) );
     //cellColorOther color ghost cells in respect to other partition,
     //if partition interface has aligned with mesh interface this will be different than _cellColor
    _cellColorOther = shared_ptr< Array<int> > ( new Array<int>( _cells.getCount() ) );
    *_cellColor = -1;
    *_cellColorOther = -1;
    _isAssembleMesh = true;
 }
Mesh * Mesh::createDoubleShell (const int fgId, Mesh & otherMesh, const int otherFgId, const bool connectedShell)
Definition at line 1772 of file Mesh.cpp.
References _connectivityMap, _dimension, _isConnectedShell, _isDoubleShell, _isShell, _otherFaceGroupSite, _otherMeshID, _parentFaceGroupSite, _parentMeshID, arrayFromVector(), getCells(), getFaceCells(), getFaceGroup(), StorageSite::getGatherMap(), getID(), StorageSite::getScatterMap(), StorageSite::getSelfCount(), Mesh(), StorageSite::setCount(), and FaceGroup::site.
 {
   typedef Array<int> IntArray;
   const FaceGroup& fg = getFaceGroup(fgId);
   const StorageSite& fgSite = fg.site;
   StorageSite& cells = getCells();
   const FaceGroup& fgOther = otherMesh.getFaceGroup(otherFgId);
   const StorageSite& fgSiteOther = fgOther.site;
   StorageSite& otherCells = otherMesh.getCells();
   const CRConnectivity& faceCells = getFaceCells(fgSite);
   const CRConnectivity& otherFaceCells = otherMesh.getFaceCells(fgSiteOther);
   const int count = fgSite.getSelfCount();
   Mesh* shellMesh = new Mesh(_dimension);
   shellMesh->_isShell = true;
   shellMesh->_isDoubleShell = true;
   shellMesh->_parentFaceGroupSite = &fgSite;
   shellMesh->_parentMeshID = getID();
   shellMesh->_otherMeshID = otherMesh.getID();
   shellMesh->_otherFaceGroupSite = &fgSiteOther;
   if (connectedShell)
     shellMesh->_isConnectedShell = true;
   StorageSite& sMeshCells = shellMesh->getCells();
   // twice as many cells as there are faces, plus twice the number of ghost cells
   sMeshCells.setCount( 2*count, 2*count);
   // we will number the left cells in the shell mesh in the same order as
   // the faces on the left mesh
   // create a mapping from the cells in the left mesh to the smesh
   // cells using the faceCell connectivity
   map<int, int> leftCellsToSCells;
   map<int, int> rightCellsToSCells;
   // If we are splitting an interior face, one mesh will have correct
   // (f,0) and (f,1) orientations and one will not, meaning that
   // faceCells(f,1) will return the interior cell instead of the
   // ghost cell.  Here we check for orientation and switch if needed.
   int lDirection = 1;
   int rDirection = 1;
   if (faceCells(0,1) < cells.getSelfCount())
     {
       lDirection = 0;
     }
   if (otherFaceCells(0,1) < otherCells.getSelfCount())
     {
       rDirection = 0;
     }
   for(int f=0; f<count; f++)
   {
     // add ghost(gather) cells to map
       const int lc1 = faceCells(f,lDirection);
       const int rc1 = otherFaceCells(f,rDirection);
       leftCellsToSCells[lc1] = f;
       rightCellsToSCells[rc1] = f;
   }
   // since there can be more than one face group in common between the
   // two meshes, we need to split up the existing gather scatter index
   // arrays into two sets, one for the cells that are connected
   // through the faces in the current face group and one for the rest.
   if (connectedShell)
     {
   StorageSite::ScatterMap& lScatterMap = cells.getScatterMap();
   StorageSite::ScatterMap& rScatterMap = otherCells.getScatterMap();
   shared_ptr<IntArray> L2RScatterOrigPtr = lScatterMap[&otherCells];
   shared_ptr<IntArray> R2LScatterOrigPtr = rScatterMap[&cells];
   StorageSite::GatherMap& lGatherMap = cells.getGatherMap();
   StorageSite::GatherMap& rGatherMap = otherCells.getGatherMap();
   shared_ptr<IntArray> R2LGatherOrigPtr = lGatherMap[&otherCells];
   shared_ptr<IntArray> L2RGatherOrigPtr = rGatherMap[&cells];
   vector<int> L2SScatterVector;
   vector<int> R2SScatterVector;
   vector<int> S2LScatterVector;
   vector<int> S2RScatterVector;
   vector<int> L2SGatherVector;
   vector<int> R2SGatherVector;
   vector<int> S2LGatherVector;
   vector<int> S2RGatherVector;
   vector<int> L2RScatterNewVector;
   vector<int> R2LScatterNewVector;
   vector<int> L2RGatherNewVector;
   vector<int> R2LGatherNewVector;
   for(int i=0; i<L2RScatterOrigPtr->getLength(); i++)
   {
       const int lcs = (*L2RScatterOrigPtr)[i];
       const int rcg = (*L2RGatherOrigPtr)[i];
       if (rightCellsToSCells.find(rcg) != rightCellsToSCells.end())
       {
           //left shell cell is sCell
           const int sCell = rightCellsToSCells[rcg];
           L2SScatterVector.push_back(lcs);
           L2SGatherVector.push_back(sCell+3*count);
           S2RScatterVector.push_back(sCell+count);
           S2RGatherVector.push_back(rcg);
       }
       else
       {
           L2RScatterNewVector.push_back(lcs);
           L2RGatherNewVector.push_back(rcg);
       }
   }
   for(int i=0; i<R2LGatherOrigPtr->getLength(); i++)
   {
       const int lcg = (*R2LGatherOrigPtr)[i];
       const int rcs = (*R2LScatterOrigPtr)[i];
       // if the left cell is in the current face groups neighbours it goes into the new1
       if (leftCellsToSCells.find(lcg) != leftCellsToSCells.end())
       {
           const int sCell = leftCellsToSCells[lcg];
           S2LGatherVector.push_back(lcg);
           S2LScatterVector.push_back(sCell);
           R2SGatherVector.push_back(sCell+2*count);
           R2SScatterVector.push_back(rcs);
       }
       else
       {
           R2LGatherNewVector.push_back(lcg);
           R2LScatterNewVector.push_back(rcs);
       }
   }
   // set the gather scatter arrays in the smesh cells
   sMeshCells.getScatterMap()[&cells] = arrayFromVector(S2LScatterVector);
   sMeshCells.getScatterMap()[&otherCells] = arrayFromVector(S2RScatterVector);
   sMeshCells.getGatherMap()[&cells] = arrayFromVector(L2SGatherVector);
   sMeshCells.getGatherMap()[&otherCells] = arrayFromVector(R2SGatherVector);
   // replace the existing arrays in left and right maps and add the
   // new ones
   lScatterMap.erase(&otherCells);
   if (L2RScatterNewVector.size() > 0)
     lScatterMap[&otherCells] = arrayFromVector(L2RScatterNewVector);
   lScatterMap[&sMeshCells] = arrayFromVector(L2SScatterVector);
   lGatherMap.erase(&otherCells);
   if (R2LGatherNewVector.size() > 0)
     lGatherMap[&otherCells] = arrayFromVector(R2LGatherNewVector);
   lGatherMap[&sMeshCells] = arrayFromVector(S2LGatherVector);
   rScatterMap.erase(&cells);
   if (R2LScatterNewVector.size() > 0)
     rScatterMap[&cells] = arrayFromVector(R2LScatterNewVector);
   rScatterMap[&sMeshCells] = arrayFromVector(R2SScatterVector);
   rGatherMap.erase(&cells);
   if (L2RGatherNewVector.size() > 0)
     rGatherMap[&cells] = arrayFromVector(L2RGatherNewVector);
   rGatherMap[&sMeshCells] = arrayFromVector(S2RGatherVector);
     }
   // create the cell cell connectivity for the shell mesh
   shared_ptr<CRConnectivity> sCellCells(new CRConnectivity(sMeshCells,sMeshCells));
   sCellCells->initCount();
   // three neighbours for interior cells, two for ghost, due to
   // potentially abnormal interface conditions
   for(int i=0; i<count; i++)
   {
       sCellCells->addCount(i,3);
       sCellCells->addCount(i+count,3);
       sCellCells->addCount(i+2*count,2);
       sCellCells->addCount(i+3*count,2);
   }
   sCellCells->finishCount();
   for(int i=0; i<count; i++)
   {
       // left shell cells
       sCellCells->add(i,i+count);
       sCellCells->add(i,i+2*count);
       sCellCells->add(i,i+3*count);
       // right shell cells
       sCellCells->add(i+count,i);
       sCellCells->add(i+count,i+2*count);
       sCellCells->add(i+count,i+3*count);
       // right ghost cells
       sCellCells->add(i+2*count,i);
       sCellCells->add(i+2*count,i+count);
       // left ghost cells
       sCellCells->add(i+3*count,i);
       sCellCells->add(i+3*count,i+count);
   }
   sCellCells->finishAdd();
   SSPair key(&sMeshCells,&sMeshCells);
   shellMesh->_connectivityMap[key] = sCellCells;
   return shellMesh;
 }
void Mesh::createGhostCellSiteGather (const PartIDMeshIDPair & id, shared_ptr< StorageSite > site)
Definition at line 701 of file Mesh.cpp.
References _ghostCellSiteGatherMap.
 {
   _ghostCellSiteGatherMap.insert( pair<PartIDMeshIDPair, shared_ptr<StorageSite> >( id, site ) );
 }
void Mesh::createGhostCellSiteGatherLevel1 (const PartIDMeshIDPair & id, shared_ptr< StorageSite > site)
Definition at line 715 of file Mesh.cpp.
References _ghostCellSiteGatherMapLevel1.
 {
   _ghostCellSiteGatherMapLevel1.insert( pair<PartIDMeshIDPair, shared_ptr<StorageSite> >( id, site ) );
 }
void Mesh::createGhostCellSiteScatter (const PartIDMeshIDPair & id, shared_ptr< StorageSite > site)
Definition at line 694 of file Mesh.cpp.
References _ghostCellSiteScatterMap.
 {
   _ghostCellSiteScatterMap.insert( pair<PartIDMeshIDPair, shared_ptr<StorageSite> >( id, site ) );
 }
void Mesh::createGhostCellSiteScatterLevel1 (const PartIDMeshIDPair & id, shared_ptr< StorageSite > site)
Definition at line 708 of file Mesh.cpp.
References _ghostCellSiteScatterMapLevel1.
 {
   _ghostCellSiteScatterMapLevel1.insert( pair<PartIDMeshIDPair, shared_ptr<StorageSite> >( id, site ) );
 }
const StorageSite & Mesh::createInterfaceGroup (const int size, const int offset, const int id)
Definition at line 268 of file Mesh.cpp.
References _faceGroups, _faces, and _interfaceGroups.
Referenced by FluentReader::createMesh(), COMETModel< T >::FinishCoarseMesh(), and COMETModel< T >::MakeCoarseMesh2().
 {
   shared_ptr<FaceGroup> fg(new FaceGroup(size,offset,_faces,id,"interface"));
   _faceGroups.push_back(fg);
   _interfaceGroups.push_back(fg);
   return fg->site;
 }
const StorageSite & Mesh::createInteriorFaceGroup (const int size)
Definition at line 259 of file Mesh.cpp.
References _faceGroups, _faces, and _interiorFaceGroup.
Referenced by FluentReader::createMesh(), extrude(), COMETModel< T >::FinishCoarseMesh(), COMETModel< T >::MakeCoarseMesh2(), and Mesh().
 {
   _interiorFaceGroup = shared_ptr<FaceGroup>(new FaceGroup(size,0,_faces,0,"interior"));
   _faceGroups.push_back(_interiorFaceGroup);
   return _interiorFaceGroup->site;
 }
void Mesh::createLocalGlobalArray ()
Definition at line 738 of file Mesh.cpp.
References _cells, _localToGlobal, and StorageSite::getCountLevel1().
Referenced by MeshDismantler::set_local_global(), and MeshPartitioner::set_local_global().
 {
    _localToGlobal      = shared_ptr< Array<int> > ( new Array<int>( _cells.getCountLevel1() ) );
    *_localToGlobal  = -1;
 }
void Mesh::createLocalToGlobalNodesArray ()
Definition at line 745 of file Mesh.cpp.
References _localToGlobalNodes, _nodes, and StorageSite::getCount().
 {
    _localToGlobalNodes = shared_ptr< Array<int> > ( new Array<int>( _nodes.getCount() ) );
    *_localToGlobalNodes  = -1;
 }
void Mesh::createRowColSiteCRConn () private
Definition at line 2239 of file Mesh.cpp.
References _cellCellsGhostExt, _cellSiteGhostExt, _recvCounts, _recvIndices, getCells(), StorageSite::getCount(), StorageSite::getGatherMap(), getGlobalToLocal(), Array< T >::getLength(), getNumBounCells(), and StorageSite::getSelfCount().
Referenced by createCellCellsGhostExt().
 {
     //counting interface counts
     //counting interfaces
     set<int> interfaceCells;
     //const Array<int>& localToGlobal = this->getLocalToGlobal();
     const map<int,int>& globalToLocal = this->getGlobalToLocal();
     const StorageSite& site = this->getCells();
     const int originalCount = site.getCount();
     const StorageSite::GatherMap& gatherMap = site.getGatherMap();
     int countLevel0 = 0;
     foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
        const StorageSite&  oSite = *mpos.first;
        const Array<int>& gatherArray = dynamic_cast< const Array<int>& > (*mpos.second);
        countLevel0 += gatherArray.getLength();
        EntryIndex e(&oSite,&site);
        const Array<int>  & recv_indices = dynamic_cast< const Array<int>& > (*_recvIndices[e]);
        const Array<int>  & recv_counts  = dynamic_cast< const Array<int>& > (*_recvCounts [e]);
        //loop over gatherArray
        int indx = 0;
        for ( int i = 0; i < gatherArray.getLength(); i++ ){
           const int nnb = recv_counts[i]; //give getCount()
           for ( int nb = 0; nb < nnb; nb++ ){
               const int localID = globalToLocal.find( recv_indices[indx] )->second;
               if ( localID >= originalCount ){
                  interfaceCells.insert( recv_indices[indx] );
               }
               indx++;
            }
         }
      }
      const int selfCount   = site.getSelfCount();
      const int countLevel1 = int(interfaceCells.size());
      //ghost cells = sum of boundary and interfaces
      const int nghost = getNumBounCells() +  countLevel0 + countLevel1;
      _cellSiteGhostExt  = shared_ptr<StorageSite> ( new StorageSite(selfCount, nghost) );
      //constructing new CRConnecitvity;
      _cellCellsGhostExt = shared_ptr< CRConnectivity> ( new CRConnectivity( *_cellSiteGhostExt, *_cellSiteGhostExt) );
 }
void Mesh::createScatterGatherCountsBuffer ()
Definition at line 2011 of file Mesh.cpp.
References _recvCounts, _sendCounts, getCellCells(), getCells(), CRConnectivity::getCount(), StorageSite::getGatherMap(), Array< T >::getLength(), and StorageSite::getScatterMap().
Referenced by MeshDismantler::setCellCellsGhostExt().
 {
 #ifdef FVM_PARALLEL
     //SENDING allocation and filling
     const StorageSite& site     = this->getCells();
     const CRConnectivity& cellCells = this->getCellCells();
     const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
     foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
         const StorageSite&  oSite = *mpos.first;
         //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
         const Array<int>& scatterArray = *mpos.second;
         //key site
         EntryIndex e(&site,&oSite);
         //allocate array
         _sendCounts[e] = shared_ptr< Array<int>   > ( new Array<int> (scatterArray.getLength()) );
         //fill send array
         Array<int>& sendArray = dynamic_cast< Array<int>& > ( *_sendCounts[e] );
         for( int i = 0; i < scatterArray.getLength(); i++ ){
             const int cellID = scatterArray[i];
             sendArray[i] = cellCells.getCount(cellID);
         }
     }
     //RECIEVING allocation (filling will be done by MPI Communication)
     const StorageSite::GatherMap& gatherMap = site.getGatherMap();
     foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
     const StorageSite&  oSite = *mpos.first;
     const Array<int>& gatherArray = *mpos.second;
     //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
     EntryIndex e(&oSite,&site);
     //allocate array
        _recvCounts[e] = shared_ptr< Array<int> > ( new Array<int> (gatherArray.getLength()) );
     }
 #endif
  }
void Mesh::createScatterGatherIndicesBuffer ()
Definition at line 2124 of file Mesh.cpp.
References _recvCounts, _recvIndices, _sendIndices, getCellCells(), getCells(), CRConnectivity::getCount(), StorageSite::getGatherMap(), Array< T >::getLength(), getLocalToGlobal(), and StorageSite::getScatterMap().
Referenced by MeshDismantler::setCellCellsGhostExt().
 {
 #ifdef FVM_PARALLEL
     //SENDING allocation and filling
     const StorageSite& site     = this->getCells();
     const CRConnectivity& cellCells = this->getCellCells();
     const Array<int>&   localToGlobal = this->getLocalToGlobal();
     const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
     foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
         const StorageSite&  oSite = *mpos.first;
         const Array<int>& scatterArray = *mpos.second;
         //loop over surround indices and itself for sizing
         EntryIndex e(&site,&oSite);
         //allocate array
         int sendSize = 0;
         for ( int i = 0; i < scatterArray.getLength(); i++ ){
            sendSize += cellCells.getCount( scatterArray[i] );
         }
         _sendIndices[e] = shared_ptr< Array<int>   > ( new Array<int> (sendSize) );
         //fill send array
         Array<int>& sendArray = dynamic_cast< Array<int>&   > ( *_sendIndices[e] );
         int indx = 0;
         for( int i = 0; i < scatterArray.getLength(); i++ ){
            const int cellID = scatterArray[i];
            for ( int j = 0; j < cellCells.getCount(cellID); j++ ){
               sendArray[indx] = localToGlobal[ cellCells(cellID,j) ];
               indx++;
            }
         }
     }
     //RECIEVING allocation (filling will be done by MPI Communication)
     const StorageSite::GatherMap& gatherMap = site.getGatherMap();
     foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
        const StorageSite&  oSite = *mpos.first;
        EntryIndex e(&oSite,&site);
        const Array<int>& recvCounts   =  dynamic_cast< const Array<int>& > (*_recvCounts[e]);
        int recvSize = 0;
        for ( int i = 0; i < recvCounts.getLength(); i++ ){
            recvSize += recvCounts[i];
        }
        //allocate array
        _recvIndices[e] = shared_ptr< Array<int> > ( new Array<int>     (recvSize) );
     }
 #endif
 }
Mesh * Mesh::createShell (const int fgId, Mesh & otherMesh, const int otherFgId)
Definition at line 1582 of file Mesh.cpp.
References _connectivityMap, _dimension, _isShell, _parentFaceGroupSite, arrayFromVector(), getCells(), getFaceCells(), getFaceGroup(), StorageSite::getGatherMap(), StorageSite::getScatterMap(), StorageSite::getSelfCount(), Mesh(), StorageSite::setCount(), and FaceGroup::site.
 {
   typedef Array<int> IntArray;
   const FaceGroup& fg = getFaceGroup(fgId);
   const StorageSite& fgSite = fg.site;
   const FaceGroup& otherfg = otherMesh.getFaceGroup(otherFgId);
   const StorageSite& otherfgSite = otherfg.site;
   StorageSite& cells = getCells();
   StorageSite& otherCells = otherMesh.getCells();
   const CRConnectivity& faceCells = getFaceCells(fgSite);
   const CRConnectivity& otherFaceCells = otherMesh.getFaceCells(otherfgSite);
   const int count = fgSite.getSelfCount();
   Mesh* shellMesh = new Mesh(_dimension);
   shellMesh->_isShell = true;
   shellMesh->_parentFaceGroupSite = &fgSite;
   StorageSite& sMeshCells = shellMesh->getCells();
   // as many cells as there are faces, plus twice the number of ghost cells
   sMeshCells.setCount( count, 2*count);
   // we will number the cells in the shell mesh in the same order as
   // the faces on the left mesh
   // create a mapping from the cells in the left mesh to the smesh
   // cells using the faceCell connectivity
   map<int, int> leftCellsToSCells;
   map<int, int> rightCellsToSCells;
   for(int f=0; f<count; f++)
   {
       const int lc1 = faceCells(f,1);
       const int rc1 = otherFaceCells(f,1);
       leftCellsToSCells[lc1] = f;
       rightCellsToSCells[rc1] = f;
   }
   // since there can be more than one face group in common between the
   // two meshes, we need to split up the existing gather scatter index
   // arrays into two sets, one for the cells that are connected
   // through the faces in the current face group and one for the rest.
   StorageSite::ScatterMap& lScatterMap = cells.getScatterMap();
   StorageSite::ScatterMap& rScatterMap = otherCells.getScatterMap();
   shared_ptr<IntArray> L2RScatterOrigPtr = lScatterMap[&otherCells];
   shared_ptr<IntArray> R2LScatterOrigPtr = rScatterMap[&cells];
   StorageSite::GatherMap& lGatherMap = cells.getGatherMap();
   StorageSite::GatherMap& rGatherMap = otherCells.getGatherMap();
   shared_ptr<IntArray> R2LGatherOrigPtr = lGatherMap[&otherCells];
   shared_ptr<IntArray> L2RGatherOrigPtr = rGatherMap[&cells];
   vector<int> L2SScatterVector;
   vector<int> R2SScatterVector;
   vector<int> S2LScatterVector;
   vector<int> S2RScatterVector;
   vector<int> L2SGatherVector;
   vector<int> R2SGatherVector;
   vector<int> S2LGatherVector;
   vector<int> S2RGatherVector;
   vector<int> L2RScatterNewVector;
   vector<int> R2LScatterNewVector;
   vector<int> L2RGatherNewVector;
   vector<int> R2LGatherNewVector;
   for(int i=0; i<L2RScatterOrigPtr->getLength(); i++)
   {
       const int lcs = (*L2RScatterOrigPtr)[i];
       const int rcg = (*L2RGatherOrigPtr)[i];
       // if the left cell is in the current face groups neighbours it goes into the new1
       if (rightCellsToSCells.find(rcg) != rightCellsToSCells.end())
       {
           const int sCell = rightCellsToSCells[rcg];
           L2SScatterVector.push_back(lcs);
           L2SGatherVector.push_back(sCell+count);
           S2RScatterVector.push_back(sCell);
           S2RGatherVector.push_back(rcg);
       }
       else
       {
           L2RScatterNewVector.push_back(lcs);
           L2RGatherNewVector.push_back(rcg);
       }
   }
   for(int i=0; i<R2LGatherOrigPtr->getLength(); i++)
   {
       const int lcg = (*R2LGatherOrigPtr)[i];
       const int rcs = (*R2LScatterOrigPtr)[i];
       // if the left cell is in the current face groups neighbours it goes into the new1
       if (leftCellsToSCells.find(lcg) != leftCellsToSCells.end())
       {
           const int sCell = leftCellsToSCells[lcg];
           S2LGatherVector.push_back(lcg);
           S2LScatterVector.push_back(sCell);
           R2SGatherVector.push_back(sCell+2*count);
           R2SScatterVector.push_back(rcs);
       }
       else
       {
           R2LGatherNewVector.push_back(lcg);
           R2LScatterNewVector.push_back(rcs);
       }
   }
   // set the gather scatter arrays in the smesh cells
   sMeshCells.getScatterMap()[&cells] = arrayFromVector(S2LScatterVector);
   sMeshCells.getScatterMap()[&otherCells] = arrayFromVector(S2RScatterVector);
   sMeshCells.getGatherMap()[&cells] = arrayFromVector(L2SGatherVector);
   sMeshCells.getGatherMap()[&otherCells] = arrayFromVector(R2SGatherVector);
   // replace the existing arrays in left and right maps and add the
   // new ones
   lScatterMap.erase(&otherCells);
   if (L2RScatterNewVector.size() > 0)
     lScatterMap[&otherCells] = arrayFromVector(L2RScatterNewVector);
   lScatterMap[&sMeshCells] = arrayFromVector(L2SScatterVector);
   lGatherMap.erase(&otherCells);
   if (R2LGatherNewVector.size() > 0)
     lGatherMap[&otherCells] = arrayFromVector(R2LGatherNewVector);
   lGatherMap[&sMeshCells] = arrayFromVector(S2LGatherVector);
   rScatterMap.erase(&cells);
   if (R2LScatterNewVector.size() > 0)
     rScatterMap[&cells] = arrayFromVector(R2LScatterNewVector);
   rScatterMap[&sMeshCells] = arrayFromVector(R2SScatterVector);
   rGatherMap.erase(&cells);
   if (L2RGatherNewVector.size() > 0)
     rGatherMap[&cells] = arrayFromVector(L2RGatherNewVector);
   rGatherMap[&sMeshCells] = arrayFromVector(S2RGatherVector);
   // create the cell cell connectivity for the shell mesh
   shared_ptr<CRConnectivity> sCellCells(new CRConnectivity(sMeshCells,sMeshCells));
   sCellCells->initCount();
   // two neighbours for the first count cells, one for the rest
   for(int i=0; i<count; i++)
   {
       sCellCells->addCount(i,2);
       sCellCells->addCount(i+count,1);
       sCellCells->addCount(i+2*count,1);
   }
   sCellCells->finishCount();
   for(int i=0; i<count; i++)
   {
       sCellCells->add(i,i+count);
       sCellCells->add(i,i+2*count);
       sCellCells->add(i+count,i);
       sCellCells->add(i+2*count,i);
   }
   sCellCells->finishAdd();
   SSPair key(&sMeshCells,&sMeshCells);
   shellMesh->_connectivityMap[key] = sCellCells;
   return shellMesh;
 }
Mesh::DEFINE_TYPENAME ("Mesh")
void Mesh::eraseConnectivity (const StorageSite & rowSite, const StorageSite & colSite) const
Definition at line 359 of file Mesh.cpp.
References _connectivityMap.
Referenced by MeshMetricsCalculator< T >::eraseIBInterpolationMatrices(), getCellCells2(), and uniqueFaceCells().
 {
   SSPair key(&rowSite,&colSite);
   _connectivityMap.erase(key);
 }
Mesh * Mesh::extractBoundaryMesh ()
Definition at line 1122 of file Mesh.cpp.
References _connectivityMap, _dimension, _nodes, createBoundaryFaceGroup(), getAllFaceGroups(), StorageSite::getCommonMap(), StorageSite::getCount(), CRConnectivity::getCount(), getFaceNodes(), getFaces(), getNodeCoordinates(), getNodes(), FaceGroup::groupType, Mesh(), setCoordinates(), StorageSite::setCount(), and FaceGroup::site.
 {
   StorageSite& nodes = _nodes;
   const Array<VecD3>& coords = getNodeCoordinates();
   const int nodeCount = nodes.getCount();
   Array<int> globalToLocalNodes(nodeCount);
   globalToLocalNodes = -1;
   int bMeshNodeCount=0;
   int bMeshFaceCount=0;
   foreach(const FaceGroupPtr fgPtr, getAllFaceGroups())
   {
       const FaceGroup& fg = *fgPtr;
       const StorageSite& faces = fg.site;
       if (fg.groupType!="interior")
       {
           const int nFaces = faces.getCount();
           const CRConnectivity& faceNodes = getFaceNodes(faces);
           for(int f=0; f<nFaces; f++)
           {
               const int nFaceNodes = faceNodes.getCount(f);
               for(int nn=0; nn<nFaceNodes; nn++)
               {
                   const int n=faceNodes(f,nn);
                   if (globalToLocalNodes[n] == -1)
                   {
                       globalToLocalNodes[n] = bMeshNodeCount++;
                   }
               }
           }
           bMeshFaceCount += nFaces;
       }
   }
   Mesh *bMesh = new Mesh(_dimension);
   StorageSite& bMeshFaces = bMesh->getFaces();
   StorageSite& bMeshNodes = bMesh->getNodes();
   bMeshFaces.setCount( bMeshFaceCount );
   bMeshNodes.setCount( bMeshNodeCount );
   bMesh->createBoundaryFaceGroup(bMeshFaceCount,0,0,"wall");
   //setting coordinates
   shared_ptr< Array<VecD3> > bMeshCoordPtr( new Array< VecD3 > ( bMeshNodeCount ) );
   shared_ptr<IntArray> myCommonNodes(new IntArray(bMeshNodeCount));
   shared_ptr<IntArray> otherCommonNodes(new IntArray(bMeshNodeCount));
   for(int n=0; n<nodeCount; n++)
   {
       const int nLocal = globalToLocalNodes[n];
       if (nLocal >=0)
       {
           (*bMeshCoordPtr)[nLocal] = coords[n];
           (*myCommonNodes)[nLocal] = nLocal;
           (*otherCommonNodes)[nLocal] = n;
       }
   }
   nodes.getCommonMap()[&bMeshNodes] = myCommonNodes;
   bMeshNodes.getCommonMap()[&nodes] = otherCommonNodes;
   bMesh->setCoordinates( bMeshCoordPtr );
   //faceNodes constructor
   shared_ptr<CRConnectivity> bFaceNodes( new CRConnectivity(bMeshFaces,
                                                             bMeshNodes) );
   bFaceNodes->initCount();
   bMeshFaceCount=0;
   foreach(FaceGroupPtr fgPtr, getAllFaceGroups())
   {
       FaceGroup& fg = *fgPtr;
       StorageSite& faces = const_cast<StorageSite&>(fg.site);
       if (fg.groupType!="interior")
       {
           const int nFaces = faces.getCount();
           const CRConnectivity& faceNodes = getFaceNodes(faces);
           shared_ptr<IntArray> myCommonFaces(new IntArray(nFaces));
           shared_ptr<IntArray> otherCommonFaces(new IntArray(nFaces));
           for(int f=0; f<nFaces; f++)
           {
               const int nFaceNodes = faceNodes.getCount(f);
               bFaceNodes->addCount(bMeshFaceCount,nFaceNodes);
               (*myCommonFaces)[f] = bMeshFaceCount;
               (*otherCommonFaces)[f] = f;
               bMeshFaceCount++;
           }
           faces.getCommonMap()[&bMeshFaces] = myCommonFaces;
           bMeshFaces.getCommonMap()[&faces] = otherCommonFaces;
       }
   }
   bFaceNodes->finishCount();
   bMeshFaceCount=0;
   foreach(const FaceGroupPtr fgPtr, getAllFaceGroups())
   {
       const FaceGroup& fg = *fgPtr;
       const StorageSite& faces = fg.site;
       if (fg.groupType!="interior")
       {
           const int nFaces = faces.getCount();
           const CRConnectivity& faceNodes = getFaceNodes(faces);
           for(int f=0; f<nFaces; f++)
           {
               const int nFaceNodes = faceNodes.getCount(f);
               for(int nn=0; nn<nFaceNodes; nn++)
               {
                   const int n=faceNodes(f,nn);
                   const int nLocal = globalToLocalNodes[n];
                   bFaceNodes->add(bMeshFaceCount,nLocal);
               }
               bMeshFaceCount++;
           }
       }
   }
   bFaceNodes->finishAdd();
   //setting faceNodes
   SSPair key(&bMeshFaces,&bMeshNodes);
   bMesh->_connectivityMap[key] = bFaceNodes;
   return bMesh;
 }
Mesh * Mesh::extrude (int nz, double zmax, bool boundaryOnly = false)
Definition at line 1258 of file Mesh.cpp.
References _cells, _connectivityMap, _dimension, _faces, _interiorFaceGroup, _nodes, createBoundaryFaceGroup(), createInteriorFaceGroup(), getAllFaceCells(), getAllFaceGroups(), getAllFaceNodes(), getCellNodes(), getCells(), StorageSite::getCount(), CRConnectivity::getCount(), getFaceCells(), getFaceNodes(), getFaces(), getNodeCoordinates(), getNodes(), StorageSite::getSelfCount(), FaceGroup::groupType, FaceGroup::id, Mesh(), setCoordinates(), StorageSite::setCount(), and FaceGroup::site.
 {
   if (boundaryOnly)
     nz = 1;
   if (_dimension != 2)
     throw CException("can only extrude two dimensional mesh");
   const int myNCells = _cells.getSelfCount();
   const int myNFaces = _faces.getSelfCount();
   const int myNInteriorFaces = _interiorFaceGroup->site.getCount();
   const int myNBoundaryFaces = myNFaces - myNInteriorFaces;
   const int myNNodes = _nodes.getSelfCount();
   const CRConnectivity& myCellNodes = getCellNodes();
   const int eNInteriorFaces_rib = boundaryOnly ? 0 : nz*myNInteriorFaces;
   const int eNInteriorFaces_cap = (nz-1)*myNCells;
   const int eNInteriorFaces = eNInteriorFaces_rib + eNInteriorFaces_cap;
   const int eNBoundaryFaces = nz*myNBoundaryFaces + 2*myNCells;
   const int eNFaces = eNInteriorFaces + eNBoundaryFaces;
   const int eNInteriorCells = boundaryOnly ? 0 : nz*myNCells;
   const int eNBoundaryCells = boundaryOnly ? 0 : eNBoundaryFaces;
   const int eNNodes = (nz+1)*myNNodes;
   Mesh *eMesh = new Mesh(3);
   // set nodes
   StorageSite& eMeshNodes = eMesh->getNodes();
   eMeshNodes.setCount( eNNodes );
   const Array<VecD3>& myCoords = getNodeCoordinates();
   shared_ptr< Array<VecD3> > eMeshCoordPtr( new Array< VecD3 > ( eNNodes ) );
   Array<VecD3>& eCoords = *eMeshCoordPtr;
   const double dz = zmax/nz;
   const double z0 = -zmax/2.0;
   for(int k=0, en=0; k<=nz; k++)
   {
       const double z = z0 + dz*k;
       for(int n=0; n<myNNodes; n++)
       {
           eCoords[en][0] = myCoords[n][0];
           eCoords[en][1] = myCoords[n][1];
           eCoords[en][2] = z;
           en++;
       }
   }
   eMesh->setCoordinates( eMeshCoordPtr );
   // set cells
   StorageSite& eMeshCells = eMesh->getCells();
   eMeshCells.setCount( eNInteriorCells, eNBoundaryCells);
   // set faces
   StorageSite& eMeshFaces = eMesh->getFaces();
   eMeshFaces.setCount(eNFaces);
   shared_ptr<CRConnectivity> eFaceNodes( new CRConnectivity(eMeshFaces,
                                                             eMeshNodes) );
   shared_ptr<CRConnectivity> eFaceCells( new CRConnectivity(eMeshFaces,
                                                             eMeshCells) );
   // set counts for face cells and face nodes
   eFaceNodes->initCount();
   eFaceCells->initCount();
   int f = 0;
   if (!boundaryOnly)
   {
       // rib faces first
       for(; f<eNInteriorFaces_rib; f++)
       {
           eFaceNodes->addCount(f,4);
           eFaceCells->addCount(f,2);
       }
       // interior cap faces
       for(int k=1; k<nz; k++)
       {
           for(int c=0; c<myNCells; c++)
           {
               eFaceNodes->addCount(f, myCellNodes.getCount(c));
               eFaceCells->addCount(f, 2);
               f++;
           }
       }
       eMesh->createInteriorFaceGroup(eNInteriorFaces);
   }
   // z = 0 faces
   eMesh->createBoundaryFaceGroup(myNCells,  f, 10000, "wall");
   for(int c=0; c<myNCells; c++)
   {
       eFaceNodes->addCount(f, myCellNodes.getCount(c));
       eFaceCells->addCount(f, 2);
       f++;
   }
   // z = zmax faces
   eMesh->createBoundaryFaceGroup(myNCells,  f, 10001, "wall");
   for(int c=0; c<myNCells; c++)
   {
       eFaceNodes->addCount(f, myCellNodes.getCount(c));
       eFaceCells->addCount(f, 2);
       f++;
   }
   foreach(const FaceGroupPtr fgPtr, getAllFaceGroups())
   {
       const FaceGroup& fg = *fgPtr;
       const StorageSite& faces = fg.site;
       if (fg.groupType!="interior")
       {
           const int nBFaces = faces.getCount();
           eMesh->createBoundaryFaceGroup(nBFaces*nz,  f, fg.id, fg.groupType);
           for(int k=0;  k<nz; k++)
             for(int bf=0; bf<nBFaces; bf++)
             {
                 eFaceNodes->addCount(f,4);
                 eFaceCells->addCount(f,2);
                 f++;
             }
       }
   }
   eFaceNodes->finishCount();
   eFaceCells->finishCount();
   // now set the indices of face cells and nodes
   f = 0;
   // rib faces first
   const CRConnectivity& myFaceNodes = getAllFaceNodes();
   const CRConnectivity& myFaceCells = getAllFaceCells();
   if (!boundaryOnly)
   {
       for(int k=0; k<nz; k++)
       {
           const int eCellOffset = k*myNCells;
           const int eNodeOffset = k*myNNodes;
           for(int myf=0; myf<myNInteriorFaces; myf++)
           {
               const int myNode0 = myFaceNodes(myf,0);
               const int myNode1 = myFaceNodes(myf,1);
               const int myCell0 = myFaceCells(myf,0);
               const int myCell1 = myFaceCells(myf,1);
               eFaceNodes->add(f, myNode0 + eNodeOffset);
               eFaceNodes->add(f, myNode1 + eNodeOffset );
               eFaceNodes->add(f, myNode1 + eNodeOffset + myNNodes);
               eFaceNodes->add(f, myNode0 + eNodeOffset + myNNodes);
               eFaceCells->add(f, myCell0 + eCellOffset);
               eFaceCells->add(f, myCell1 + eCellOffset);
               f++;
           }
       }
       // interior cap faces
       for(int k=1; k<nz; k++)
       {
           const int eCellOffset = k*myNCells;
           const int eNodeOffset = k*myNNodes;
           for(int c=0; c<myNCells; c++)
           {
               const int nCellNodes = myCellNodes.getCount(c);
               for(int nnc=0; nnc<nCellNodes; nnc++)
               {
                   eFaceNodes->add(f, myCellNodes(c,nnc) + eNodeOffset);
               }
               eFaceCells->add(f, c + eCellOffset - myNCells);
               eFaceCells->add(f, c + eCellOffset);
               f++;
           }
       }
   }
   // counter for boundary faces
   int ebf = 0;
   // z = 0 faces
   {
       const int eCellOffset = 0;
       const int eNodeOffset = 0;
       for(int c=0; c<myNCells; c++)
       {
           const int nCellNodes = myCellNodes.getCount(c);
           // reverse order of face nodes
           for(int nnc=nCellNodes-1; nnc>=0; nnc--)
           {
               eFaceNodes->add(f, myCellNodes(c,nnc) + eNodeOffset);
           }
           eFaceCells->add(f, c + eCellOffset);
           eFaceCells->add(f, ebf + eNInteriorCells);
           f++;
           ebf++;
       }
   }
   // z = zmax faces
   {
       const int eCellOffset = (nz-1)*myNCells;
       const int eNodeOffset = nz*myNNodes;
       for(int c=0; c<myNCells; c++)
       {
           const int nCellNodes = myCellNodes.getCount(c);
           // reverse order of face nodes
           for(int nnc=0; nnc<nCellNodes; nnc++)
           {
               eFaceNodes->add(f, myCellNodes(c,nnc) + eNodeOffset);
           }
           eFaceCells->add(f, c + eCellOffset);
           eFaceCells->add(f, ebf + eNInteriorCells);
           f++;
           ebf++;
       }
   }
   // rib boundary faces
   foreach(const FaceGroupPtr fgPtr, getAllFaceGroups())
   {
       const FaceGroup& fg = *fgPtr;
       const StorageSite& faces = fg.site;
       if (fg.groupType!="interior")
       {
           const int nBFaces = faces.getCount();
           const CRConnectivity& bFaceNodes = getFaceNodes(faces);
           const CRConnectivity& bFaceCells = getFaceCells(faces);
           for(int k=0;  k<nz; k++)
           {
               const int eCellOffset = k*myNCells;
               const int eNodeOffset = k*myNNodes;
               for(int bf=0; bf<nBFaces; bf++)
               {
                   const int myNode0 = bFaceNodes(bf,0);
                   const int myNode1 = bFaceNodes(bf,1);
                   const int myCell0 = bFaceCells(bf,0);
                   eFaceNodes->add(f, myNode0 + eNodeOffset);
                   eFaceNodes->add(f, myNode1 + eNodeOffset);
                   eFaceNodes->add(f, myNode1 + eNodeOffset + myNNodes);
                   eFaceNodes->add(f, myNode0 + eNodeOffset + myNNodes);
                   eFaceCells->add(f, myCell0 + eCellOffset);
                   eFaceCells->add(f, ebf + eNInteriorCells);
                   f++;
                   ebf++;
               }
           }
       }
   }
   eFaceNodes->finishAdd();
   eFaceCells->finishAdd();
  //setting faceNodes
   SSPair key1(&eMeshFaces,&eMeshNodes);
   eMesh->_connectivityMap[key1] = eFaceNodes;
   if (!boundaryOnly)
   {
       SSPair key2(&eMeshFaces,&eMeshCells);
       eMesh->_connectivityMap[key2] = eFaceCells;
   }
   return eMesh;
 }
void Mesh::findCommonFaces (StorageSite & faces, StorageSite & otherFaces, const GeomFields & geomFields)
Definition at line 996 of file Mesh.cpp.
References GeomFields::area, GeomFields::coordinate, cross(), epsilon, StorageSite::getCommonMap(), StorageSite::getCount(), mag(), and mag2().
 {
   const int count(faces.getCount());
   if (count != otherFaces.getCount())
     throw CException("face groups are not of the same length");
   const Array<VecD3>& coords =
     dynamic_cast<const Array<VecD3>& >(geomFields.coordinate[faces]);
   const Array<VecD3>& otherCoords =
     dynamic_cast<const Array<VecD3>& >(geomFields.coordinate[otherFaces]);
   const Array<VecD3>& area =
     dynamic_cast<const Array<VecD3>& >(geomFields.area[faces]);
   const Array<VecD3>& otherArea =
     dynamic_cast<const Array<VecD3>& >(geomFields.area[otherFaces]);
   KSearchTree thisFacesTree(coords);
   Array<int> closest(2);
   shared_ptr<IntArray> myCommonFaces(new IntArray(count));
   shared_ptr<IntArray> otherCommonFaces(new IntArray(count));
   for(int f=0; f<count; f++)
   {
       thisFacesTree.findNeighbors(otherCoords[f],2,closest);
       const int closestFace = closest[0];
       double dist0 = mag(otherCoords[f] - coords[closestFace]);
       // distance between the two closest point used as scale
       double distScale = mag(coords[closest[0]] - coords[closest[1]]);
       if (dist0 < distScale*epsilon)
       {
           double crossProductMag(mag2(cross(otherArea[f],area[closestFace])));
           if (crossProductMag > mag2(otherArea[f])*epsilon)
             throw CException("cross product is not small");
           (*otherCommonFaces)[f] = closestFace;
           (*myCommonFaces)[closestFace] = f;
       }
       else
         throw CException("Not a match");
   }
   faces.getCommonMap()[&otherFaces] = myCommonFaces;
   otherFaces.getCommonMap()[&faces] = otherCommonFaces;
 }
void Mesh::findCommonNodes (Mesh & other)
Definition at line 877 of file Mesh.cpp.
References _nodes, epsilon, KSearchTree::findNeighbors(), getAllFaceGroups(), StorageSite::getCommonMap(), StorageSite::getCount(), CRConnectivity::getCount(), getFaceNodes(), getNodeCoordinates(), FaceGroup::groupType, KSearchTree::insert(), mag(), and FaceGroup::site.
 {
   StorageSite& nodes = _nodes;
   StorageSite& otherNodes = other._nodes;
   const int nNodes = nodes.getCount();
   const int nOtherNodes = otherNodes.getCount();
   const Array<VecD3>& coords = getNodeCoordinates();
   const Array<VecD3>& otherCoords = other.getNodeCoordinates();
   KSearchTree bNodeTree;
   // add all boundary nodes of this mesh to the tree
   {
       Array<bool> nodeMark(nNodes);
       nodeMark = false;
       foreach(const FaceGroupPtr fgPtr, getAllFaceGroups())
       {
           const FaceGroup& fg = *fgPtr;
           const StorageSite& faces = fg.site;
           if (fg.groupType!="interior")
           {
               const int nFaces = faces.getCount();
               const CRConnectivity& faceNodes = getFaceNodes(faces);
               for(int f=0; f<nFaces; f++)
               {
                   const int nFaceNodes = faceNodes.getCount(f);
                   for(int nn=0; nn<nFaceNodes; nn++)
                   {
                       const int n=faceNodes(f,nn);
                       if (!nodeMark[n])
                       {
                           nodeMark[n] = true;
                           bNodeTree.insert(coords[n],n);
                       }
                   }
               }
           }
       }
   }
   // loop over all the boundary nodes of the other mesh to find possible common ones
   Array<bool> nodeMark(nOtherNodes);
   typedef map<int,int> CommonNodesMap;
   CommonNodesMap commonNodesMap;
   Array<int> closest(2);
   nodeMark = false;
   foreach(const FaceGroupPtr fgPtr, other.getAllFaceGroups())
   {
       const FaceGroup& fg = *fgPtr;
       const StorageSite& faces = fg.site;
       if (fg.groupType!="interior")
       {
           const int nFaces = faces.getCount();
           const CRConnectivity& faceNodes = other.getFaceNodes(faces);
           for(int f=0; f<nFaces; f++)
           {
               const int nFaceNodes = faceNodes.getCount(f);
               for(int nn=0; nn<nFaceNodes; nn++)
               {
                   const int n=faceNodes(f,nn);
                   if (!nodeMark[n])
                   {
                       bNodeTree.findNeighbors(otherCoords[n],2,closest);
                       double dist0 = mag(otherCoords[n] - coords[closest[0]]);
                       // distance between the two closest point used as scale
                       double distScale = mag(coords[closest[0]] - coords[closest[1]]);
                       if (dist0 < distScale*epsilon)
                       {
                           // if another node has already been found as the
                           // closest for this one we have something wrong
                           if (commonNodesMap.find(closest[0]) != commonNodesMap.end())
{
                               throw CException("duplicate nodes on the mesh ?");
                           }
                           commonNodesMap.insert(make_pair(closest[0], n));
                       }
                       nodeMark[n] = true;
                   }
               }
           }
       }
   }
   const int nCommon = commonNodesMap.size();
   if (nCommon == 0)
     return;
   cout << "found " << nCommon << " common nodes " << endl;
   shared_ptr<IntArray> myCommonNodes(new IntArray(nCommon));
   shared_ptr<IntArray> otherCommonNodes(new IntArray(nCommon));
   int nc=0;
   foreach(CommonNodesMap::value_type& pos, commonNodesMap)
   {
       (*myCommonNodes)[nc] = pos.first;
       (*otherCommonNodes)[nc] = pos.second;
       nc++;
   }
   nodes.getCommonMap()[&otherNodes] = myCommonNodes;
   otherNodes.getCommonMap()[&nodes] = otherCommonNodes;
 }
int Mesh::get_request_size () private
Definition at line 2363 of file Mesh.cpp.
References getCells(), StorageSite::getGatherProcID(), and StorageSite::getScatterMap().
Referenced by syncCounts(), and syncIndices().
 {
     int indx =  0;
     const StorageSite& site = this->getCells();
     const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
     foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
         const StorageSite&  oSite = *mpos.first;
         //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
         if ( oSite.getGatherProcID() != -1 )
            indx++;
     }
     return indx;
 }
const CRConnectivity & Mesh::getAllFaceCells () const
Definition at line 378 of file Mesh.cpp.
References _cells, _connectivityMap, and _faces.
Referenced by MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), MeshPartitioner::cellcells_global_extension(), CellMark_Impl(), COMETModel< T >::coarsenInterfaceCells(), GradientModel< Vector< T, 3 > >::compute(), FlowModel< T >::Impl::computeContinuityResidual(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), NcDataWriter::connectivities(), KineticModel< T >::ConservationofMassCheck(), COMETModel< T >::ConservationofMassCheck(), KineticModel< T >::correctMassDeficit(), COMETModel< T >::correctMassDeficit(), IBManager::createIBFaces(), FluentReader::createMesh(), DriftDiscretization< X, Diag, OffDiag >::discretize(), GenericIBDiscretization< X, Diag, OffDiag >::discretize(), PhononConvectionDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization< X, Diag, OffDiag >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), MomentumPressureGradientDiscretization< X >::discretize(), ElecDiffusionDiscretization< X, Diag, OffDiag >::discretize(), extrude(), MeshDismantler::faceCellsAddBoundaryInterfaces(), MeshDismantler::faceCellsAddInteriorFaces(), MeshDismantler::faceCellsAddMeshInterfaces(), MeshDismantler::faceCellsAddPartitionInterfaces(), MeshDismantler::faceNodesAddBoundaryInterfaces(), MeshDismantler::faceNodesAddInteriorFaces(), MeshDismantler::faceNodesAddMeshInterfaces(), MeshDismantler::faceNodesAddPartitionInterfaces(), MeshDismantler::faceNodesInit(), MeshPartitioner::gatherCellsLevel1_partID_map(), getCellCells(), getCellFaces(), getCellNodes(), getFaceCells(), getFaceCells2(), MeshDismantler::getGatherArrays(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D(), MeshDismantler::getScatterArrays(), MeshMetricsCalculator< T >::init(), MeshDismantler::init(), KineticModel< T >::MacroparameterIBCell(), IBManager::markIntersections(), MeshDismantler::set_local_global(), MeshPartitioner::set_local_global(), MeshDismantler::setCellsSite(), MeshAssembler::setFaceCells(), MeshDismantler::setFacesSite(), MeshAssembler::setMeshCellColor(), ElectricModel< T >::Impl::updateConvectionFlux(), and MovingMeshModel< T >::volChange().
 {
   SSPair key(&_faces,&_cells);
   ConnectivityMap::const_iterator pos = _connectivityMap.find(key);
   if (pos != _connectivityMap.end())
     return *pos->second;
   throw CException("face cells not defined");
 }
CRConnectivity & Mesh::getAllFaceCells ()
Definition at line 469 of file Mesh.cpp.
References _cells, _connectivityMap, and _faces.
 {
   SSPair key(&_faces,&_cells);
   ConnectivityMap::const_iterator pos = _connectivityMap.find(key);
   if (pos != _connectivityMap.end())
     return *pos->second;
   throw CException("face cells not defined");
 }
const FaceGroupList& Mesh::getAllFaceGroups () const inline
Definition at line 193 of file Mesh.h.
References _faceGroups.
Referenced by StructureModel< T >::Impl::applyBC(), MeshMetricsCalculator< T >::calculateBoundaryNodeNormal(), MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), GradientModel< Vector< T, 3 > >::compute(), createAndGetBNglobalToLocal(), BatteryElectricDiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretize(), BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize(), WallDiscretization< X, Diag, OffDiag >::discretize(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretize(), PlateSourceDiscretization< T, Diag, OffDiag >::discretize(), extractBoundaryMesh(), extrude(), findCommonNodes(), getFaceGroup(), BatteryModel< T >::Impl::getFaceGroupArea(), BatteryModel< T >::Impl::getFaceGroupVoltage(), StructureModel< T >::Impl::Impl(), PlateModel< T >::Impl::Impl(), StructureModel< T >::Impl::init(), PlateModel< T >::Impl::init(), PlateModel< T >::Impl::linearizeDeformation(), StructureDeformationModel< T >::updateBoundaryMesh(), MovingMeshModel< T >::volChange(), VTKWriter< T >::VTKWriter(), VTKWriter< T >::writeScalarField(), and VTKWriter< T >::writeVectorField().
   {return _faceGroups;}
const CRConnectivity & Mesh::getAllFaceNodes () const
Definition at line 368 of file Mesh.cpp.
References _connectivityMap, _faces, and _nodes.
Referenced by MeshMetricsCalculator< T >::calculateFaceAreas(), MeshMetricsCalculator< T >::calculateFaceCentroids(), NcDataWriter::connectivities(), extrude(), MeshDismantler::faceNodesAddBoundaryInterfaces(), MeshDismantler::faceNodesAddInteriorFaces(), MeshDismantler::faceNodesAddMeshInterfaces(), MeshDismantler::faceNodesAddPartitionInterfaces(), MeshDismantler::faceNodesInit(), getCellNodes(), getFaceNodes(), MeshAssembler::getInnerNodesCount(), IBManager::markIntersections(), AABB::meshIntersections(), setCommonFacesMap(), MeshAssembler::setFaceNodes(), MeshAssembler::setInterfaceNodes(), and MovingMeshModel< T >::volChange().
 {
   SSPair key(&_faces,&_nodes);
   ConnectivityMap::const_iterator pos = _connectivityMap.find(key);
   if (pos != _connectivityMap.end())
     return *pos->second;
   throw CException("face nodes not defined");
 }
const ArrayBase & Mesh::getBNglobalToLocal () const
Definition at line 346 of file Mesh.cpp.
References createAndGetBNglobalToLocal().
 {
   return *(createAndGetBNglobalToLocal());
 }
const FaceGroupList& Mesh::getBoundaryFaceGroups () const inline
Definition at line 187 of file Mesh.h.
References _boundaryGroups.
Referenced by AABB::AABB(), COMETModel< T >::applyTemperatureBoundaries(), COMETModel< T >::binwiseHeatFluxIntegral(), COMETModel< T >::calcDomainStats(), PhononModel< T >::callBoundaryConditions(), KineticModel< T >::callBoundaryConditions(), COMETModel< T >::callCOMETBoundaryConditions(), COMETModel< T >::COMETModel(), BatteryModel< T >::Impl::copyCoupledToSeparate(), BatteryModel< T >::Impl::copySeparateToCoupled(), COMETModel< T >::correctSingleNeighbor(), FlowModel< T >::Impl::correctVelocityExplicit(), Octree::Create(), debug_mesh(), MomentumPressureGradientDiscretization< X >::discretize(), InjectionDiscretization< X, Diag, OffDiag >::discretize(), TunnelingDiscretization< X, Diag, OffDiag >::discretize(), MeshPartitioner::extractBoundaryMesh(), MeshDismantler::faceCellsAddBoundaryInterfaces(), MeshDismantler::faceNodesAddBoundaryInterfaces(), MeshDismantler::faceNodesInit(), COMETModel< T >::FinishCoarseMesh(), ThermalModel< T >::Impl::getHeatFluxIntegral(), BatteryModel< T >::Impl::getHeatFluxIntegral(), SpeciesModel< T >::Impl::getMassFluxIntegral(), BatteryModel< T >::Impl::getMassFluxIntegral(), FlowModel< T >::Impl::getMomentumFluxIntegral(), getNumBounCells(), ElectricModel< T >::Impl::getPotentialFluxIntegral(), BatteryModel< T >::Impl::getPotentialFluxIntegral(), FlowModel< T >::Impl::getPressureIntegral(), VacancyModel< T >::Impl::getVacaFluxIntegral(), COMETModel< T >::getWallArea(), COMETModel< T >::getWallAreaVector(), MeshDismantler::global_offset(), MeshPartitioner::global_offset(), MeshPartitioner::globalCellID_procID_map(), PhononModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegral(), ThermalModel< T >::Impl::Impl(), VacancyModel< T >::Impl::Impl(), SpeciesModel< T >::Impl::Impl(), FractureModel< T >::Impl::Impl(), KeModel< T >::Impl::Impl(), BatteryModel< T >::Impl::Impl(), ElectricModel< T >::Impl::Impl(), FlowModel< T >::Impl::Impl(), ThermalModel< T >::Impl::init(), FractureModel< T >::Impl::init(), VacancyModel< T >::Impl::init(), SpeciesModel< T >::Impl::init(), KeModel< T >::Impl::init(), PhononModel< T >::init(), KineticModel< T >::init(), ElectricModel< T >::Impl::init(), BatteryModel< T >::Impl::init(), COMETModel< T >::init(), ElectricModel< T >::Impl::initChargeTransportLinearization(), COMETModel< T >::initCoarse(), FlowModel< T >::Impl::initContinuityLinearization(), ElectricModel< T >::Impl::initElectroStaticsLinearization(), COMETModel< T >::initFromOld(), COMETModel< T >::initializeTemperatureBoundaries(), ThermalModel< T >::Impl::initLinearization(), FractureModel< T >::Impl::initLinearization(), VacancyModel< T >::Impl::initLinearization(), SpeciesModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearizationk(), FlowModel< T >::Impl::initMomentumLinearization(), BatteryModel< T >::Impl::initPCLinearization(), BatteryModel< T >::Impl::initPotentialLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), BatteryModel< T >::Impl::initThermalLinearization(), ThermalModel< T >::Impl::linearize(), FractureModel< T >::Impl::linearize(), VacancyModel< T >::Impl::linearize(), SpeciesModel< T >::Impl::linearize(), ElectricModel< T >::Impl::linearizeChargeTransport(), FlowModel< T >::Impl::linearizeContinuity(), KeModel< T >::Impl::linearizedissipation(), ElectricModel< T >::Impl::linearizeElectroStatics(), KeModel< T >::Impl::linearizeenergy(), KineticModel< T >::linearizeKineticModel(), FlowModel< T >::Impl::linearizeMomentum(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), PhononModel< T >::linearizePhononModel(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), BatteryModel< T >::Impl::linearizeThermal(), COMETModel< T >::MakeCoarseMesh1(), COMETModel< T >::MakeCoarseMesh2(), COMETModel< T >::MakeInteriorCoarseMesh(), IBManager::markIntersections(), COMETModel< T >::modewiseHeatFluxIntegral(), PhononModel< T >::PhononModel(), FlowModel< T >::Impl::postContinuitySolve(), FlowModel< T >::Impl::printMassFluxIntegrals(), FlowModel< T >::Impl::printMomentumFluxIntegrals(), FlowModel< T >::Impl::printPressureIntegrals(), COMETModel< T >::sameFaceGroup(), MeshDismantler::set_local_global(), MeshPartitioner::set_local_global(), KineticModel< T >::SetBoundaryConditions(), COMETModel< T >::SetBoundaryConditions(), MeshAssembler::setBoundaryFaceGroup(), setCommonFacesMap(), MeshAssembler::setFaceCells(), MeshAssembler::setFaceNodes(), COMETDiscretizer< T >::setfgFinder(), COMETESBGKDiscretizer< T >::setfgFinder(), MeshAssembler::setMeshCellColor(), COMETModel< T >::syncGhostCoarsening(), StructureDeformationModel< T >::updateBoundaryMesh(), ElectricModel< T >::Impl::updateConvectionFlux(), FluentDataExporter< T >::writeScalarField(), and FluentDataExporter< T >::writeVectorField().
   {return _boundaryGroups;}
int Mesh::getBoundaryGroupCount () const inline
Definition at line 184 of file Mesh.h.
References _boundaryGroups.
Referenced by debug_mesh(), MeshDismantler::faceCellsAddBoundaryInterfaces(), MeshDismantler::faceNodesAddBoundaryInterfaces(), MeshDismantler::faceNodesInit(), MeshDismantler::global_offset(), MeshPartitioner::global_offset(), MeshPartitioner::globalCellID_procID_map(), MeshDismantler::set_local_global(), MeshPartitioner::set_local_global(), MeshAssembler::setBoundaryFaceGroup(), MeshAssembler::setFaceCells(), MeshAssembler::setFaceNodes(), and MeshAssembler::setMeshCellColor().
 {return _boundaryGroups.size();}
const StorageSite & Mesh::getBoundaryNodes () const
Definition at line 325 of file Mesh.cpp.
References _boundaryNodes, _nodes, createAndGetBNglobalToLocal(), and StorageSite::getCount().
Referenced by MovingMeshModel< T >::advance(), and MeshMetricsCalculator< T >::calculateBoundaryNodeNormal().
 {
   if(!_boundaryNodes)
   {
       const int nNodes = _nodes.getCount();
       shared_ptr<Array<int> > GlobalToLocalPtr = createAndGetBNglobalToLocal();
       Array<int>& GlobalToLocal = *GlobalToLocalPtr;
       int BoundaryNodeCount = 0;
       int nLocal = 0;
       for(int i=0;i<nNodes;i++)
       {
           if(GlobalToLocal[i] != -1)
             nLocal++;
       }
       BoundaryNodeCount = nLocal;
       _boundaryNodes = new StorageSite(BoundaryNodeCount,0,0,0);
   }
   return *_boundaryNodes;
 }
const set<int>& Mesh::getBoundaryNodesSet () const inline
Definition at line 253 of file Mesh.h.
References _boundaryNodesSet.
 { return _boundaryNodesSet;}
set<int>& Mesh::getBoundaryNodesSet () inline
Definition at line 254 of file Mesh.h.
References _boundaryNodesSet.
 { return _boundaryNodesSet;}
const CRConnectivity & Mesh::getCellCells () const
Definition at line 480 of file Mesh.cpp.
References _cells, _connectivityMap, getAllFaceCells(), getCellFaces(), and CRConnectivity::multiply().
Referenced by addCRConn(), MeshPartitioner::cellcells_global_extension(), CellMark_Impl(), COMETModel< T >::coarsenInterfaceCells(), countCRConn(), createScatterGatherCountsBuffer(), createScatterGatherIndicesBuffer(), GradientMatrix< T_Scalar >::createScatterGatherValuesBuffer(), TrapBandTunnelingDiscretization< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJump< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), LinearizeDielectric< X, Diag, OffDiag >::discretize(), BatteryLinearizeThermalInterface< X, Diag, OffDiag >::discretize(), BatteryLinearizePotentialInterface< X, Diag, OffDiag >::discretize(), LinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryPCLinearizeInterface_BV< X, Diag, OffDiag, otherMeshDiag >::discretize(), BatteryLinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), LinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), InjectionDiscretization< X, Diag, OffDiag >::discretize(), TunnelingDiscretization< X, Diag, OffDiag >::discretize(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), getCellCells2(), getCellCellsGhostExt(), getFaceCells2(), MeshPartitioner::globalCellID_procID_map(), ElectricModel< T >::Impl::initChargeTransportLinearization(), FlowModel< T >::Impl::initContinuityLinearization(), ElectricModel< T >::Impl::initElectroStaticsLinearization(), KineticModel< T >::initKineticModelLinearization(), ThermalModel< T >::Impl::initLinearization(), FractureModel< T >::Impl::initLinearization(), VacancyModel< T >::Impl::initLinearization(), SpeciesModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearizationk(), FlowModel< T >::Impl::initMomentumLinearization(), BatteryModel< T >::Impl::initPCLinearization(), PhononModel< T >::initPhononModelLinearization(), BatteryModel< T >::Impl::initPotentialLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), BatteryModel< T >::Impl::initThermalLinearization(), COMETModel< T >::makeCellColors(), COMETInterface< T >::makeDMMcoeffs(), IBManager::markFluid(), MeshPartitioner::set_cellcells_global(), and BatteryModel< T >::Impl::updateShellGhosts().
 {
   SSPair key(&_cells,&_cells);
   ConnectivityMap::const_iterator pos = _connectivityMap.find(key);
   if (pos != _connectivityMap.end())
     return *pos->second;
   const CRConnectivity& faceCells = getAllFaceCells();
   const CRConnectivity& cellFaces = getCellFaces();
   shared_ptr<CRConnectivity> cellCells = cellFaces.multiply(faceCells,true);
   _connectivityMap[key] = cellCells;
   return *cellCells;
 }
const CRConnectivity & Mesh::getCellCells2 () const
Definition at line 495 of file Mesh.cpp.
References _cellCells2, _cellCellsGlobal, _globalToLocal, CRConnectivity::CELLCELL2, eraseConnectivity(), getCellCells(), getCells(), CRConnectivity::getCol(), StorageSite::getCount(), CRConnectivity::getCount(), StorageSite::getCountLevel1(), Array< T >::getLength(), CRConnectivity::getRow(), CRConnectivity::getRowSite(), StorageSite::getSelfCount(), and CRConnectivity::multiply().
Referenced by IBManager::createIBInterpolationStencil(), IBManager::createSolidInterpolationStencil(), PlateModel< T >::Impl::initDeformationLinearization(), and StructureModel< T >::Impl::initDeformationLinearization().
 {
   if (!_cellCells2)
   {
 #ifdef FVM_PARALLEL
     if ( MPI::COMM_WORLD.Get_size() > 1 ) {
       //CRConnectivity constructor
       _cellCells2 = shared_ptr<CRConnectivity> ( new CRConnectivity(this->getCells(), this->getCells()) );
       //initCount
       _cellCells2->initCount();
       const int ncells = this->getCells().getCountLevel1();
       const int selfCount = this->getCells().getSelfCount();
       const CRConnectivity& cellCells = this->getCellCells();
       multimap<int,int>::const_iterator it0;
       multimap<int,int>::const_iterator it1;
        //loop over  cells
       for ( int n = 0; n < ncells; n++ ){
          set<int> setCells;
          for ( int k = 0; k < cellCells.getCount(n); k++ ){
              const int cellID1 = cellCells(n,k);
              setCells.insert( cellID1 );
              if ( cellID1 < selfCount ){ //it means inner cells use cellCells
                 for ( int i = 0; i < cellCells.getCount(cellID1); i++ ){
                     const int cellID2 = cellCells(cellID1,i);
                     setCells.insert(cellID2);
                 }
              } else {
                 for (  it1 = _cellCellsGlobal.equal_range(cellID1).first; it1 != _cellCellsGlobal.equal_range(cellID1).second; it1++ ){
                    const int globalCellID2 = it1->second;
                    const int localID2 = _globalToLocal.find(globalCellID2)->second;
                    if ( _globalToLocal.count(globalCellID2) > 0 )
                       setCells.insert(localID2);
                 }
              }
          }
          //erase itself
          setCells.erase(n);
          _cellCells2->addCount(n,setCells.size());
       }
       //finish count
       _cellCells2->finishCount();
       //add cellcells2
       //loop over  cells
       for ( int n = 0; n < ncells; n++ ){
          set<int> setCells;
          for ( int k = 0; k < cellCells.getCount(n); k++ ){
              const int cellID1 = cellCells(n,k);
              setCells.insert( cellID1 );
              if ( cellID1 < selfCount ){ //it means inner cells use cellCells
                 for ( int i = 0; i < cellCells.getCount(cellID1); i++ ){
                     const int cellID2 = cellCells(cellID1,i);
                     setCells.insert(cellID2);
                 }
              } else {
                 for (  it1 = _cellCellsGlobal.equal_range(cellID1).first; it1 != _cellCellsGlobal.equal_range(cellID1).second; it1++ ){
                    const int globalCellID2 = it1->second;
                    const int localID2 = _globalToLocal.find(globalCellID2)->second;
                    if ( _globalToLocal.count(globalCellID2) > 0 )
                       setCells.insert(localID2);
                 }
              }
          }
          //erase itself
          setCells.erase(n);
          foreach ( const set<int>::value_type cellID, setCells ){
              _cellCells2->add(n, cellID);
          }
       }
       //finish add
       _cellCells2->finishAdd();
      //unique numbering for cells to
     {
        const int ncount = _cellCells2->getRowSite().getCountLevel1();
        const Array<int>& row = _cellCells2->getRow();
        Array<int>& col = _cellCells2->getCol();
        for( int i = 0; i < ncount; i++ ){
           for ( int j = row[i]; j < row[i+1]; j++ ){
              const int globalID = (*_localToGlobal)[ col[j] ];
              col[j] = _globalToLocal[globalID];
           }
        }
      }
      //uniqing numberinf for face cells
      {
         CRConnectivity& faceCells = (const_cast<Mesh *>(this))->getAllFaceCells();
         const int nfaces = faceCells.getRowSite().getCount();
         const Array<int>& row = faceCells.getRow();
         Array<int>& col = faceCells.getCol();
         for( int i = 0; i < nfaces; i++ ){
            for ( int j = row[i]; j < row[i+1]; j++ ){
               const int globalID = (*_localToGlobal)[ col[j] ];
               col[j] = _globalToLocal[globalID];
            }
         }
         const StorageSite& cellSite = this->getCells();
         this->eraseConnectivity(cellSite,cellSite);
      }
       //get mappers to update cellCell2 localToGlobalMap and globalToLocalMapper
       map<int,int>& globalToLocalMapper = _cellCells2->getGlobalToLocalMapper();
       foreach( const  mapInt::value_type& mpos, _globalToLocal ){
          globalToLocalMapper[mpos.first] = mpos.second;
       }
       //localToGlobal need to be first created
       _cellCells2->resizeLocalToGlobalMap( this->getCells().getCountLevel1() );
       Array<int>& localToGlobal = *(_cellCells2->getLocalToGlobalMapPtr());
       for ( int i = 0; i < localToGlobal.getLength(); i++ ){
          localToGlobal[i] = (*_localToGlobal)[i];
       }
   } else {  //if it is a one processor, we want to call this version, otherwise, couplingplate has trouble
        const CRConnectivity& cellCells = getCellCells();
        _cellCells2 = cellCells.multiply(cellCells, true);
   }
    //set enum as CELLCELL2
   _cellCells2->setConnType(CRConnectivity::CELLCELL2);
 #endif
 #ifndef FVM_PARALLEL
        const CRConnectivity& cellCells = getCellCells();
        _cellCells2 = cellCells.multiply(cellCells, true);
 #endif
   }
   return *_cellCells2;
 }
const CRConnectivity& Mesh::getCellCellsGhostExt () const inline
Definition at line 267 of file Mesh.h.
References _cellCellsGhostExt, and getCellCells().
{
 #ifdef FVM_PARALLEL
       int numProcs = MPI::COMM_WORLD.Get_size();
       if ( numProcs > 1 )
           return *_cellCellsGhostExt;
       else
 #endif
         return this->getCellCells();
   }
multiMap& Mesh::getCellCellsGlobal () inline
Definition at line 247 of file Mesh.h.
References _cellCellsGlobal.
Referenced by MeshPartitioner::cellcells_global_extension(), MeshPartitioner::DEBUG_cellcells_global(), MeshPartitioner::gatherCellsLevel1_partID_map(), MeshPartitioner::set_cellcells_global(), and MeshDismantler::setCellsSite().
 { return _cellCellsGlobal;}
const multiMap& Mesh::getCellCellsGlobal () const inline
Definition at line 248 of file Mesh.h.
References _cellCellsGlobal.
 { return _cellCellsGlobal;}
Array<int>& Mesh::getCellColors () inline
Definition at line 228 of file Mesh.h.
References _cellColor.
Referenced by MeshDismantler::getGatherArrays(), MeshDismantler::getScatterArrays(), MeshDismantler::setCellsMapper(), MeshDismantler::setCellsSite(), MeshDismantler::setFacesSite(), MeshDismantler::setNodesMapper(), and MeshDismantler::setNodesSite().
 { return *_cellColor;}
const Array<int>& Mesh::getCellColors () const inline
Definition at line 229 of file Mesh.h.
References _cellColor.
 { return *_cellColor;}
Array<int>& Mesh::getCellColorsOther () inline
Definition at line 231 of file Mesh.h.
References _cellColorOther.
Referenced by MeshDismantler::getGatherArrays(), and MeshDismantler::getScatterArrays().
 { return *_cellColorOther;}
const Array<int>& Mesh::getCellColorsOther () const inline
Definition at line 232 of file Mesh.h.
References _cellColorOther.
 { return *_cellColorOther;}
const CRConnectivity & Mesh::getCellFaces () const
Definition at line 454 of file Mesh.cpp.
References _cells, _connectivityMap, _faces, getAllFaceCells(), and CRConnectivity::getTranspose().
Referenced by COMETBoundary< T >::applyTemperatureWallFine(), CellMark_Impl(), COMETModel< T >::coarsenInterfaceCells(), COMETModel< T >::coarsenInterior(), COMETModel< T >::correctSolution(), MeshAssembler::countInterfaceNodes(), getCellCells(), COMETModel< T >::MakeCoarseMesh1(), COMETModel< T >::MakeCoarseMesh2(), and COMETInterface< T >::makeDMMcoeffs().
 {
   SSPair key(&_cells,&_faces);
   ConnectivityMap::const_iterator pos = _connectivityMap.find(key);
   if (pos != _connectivityMap.end())
     return *pos->second;
   const CRConnectivity& faceCells = getAllFaceCells();
   shared_ptr<CRConnectivity> cellFaces = faceCells.getTranspose();
   _connectivityMap[key] = cellFaces;
   return *cellFaces;
 }
const CRConnectivity & Mesh::getCellNodes () const
Definition at line 426 of file Mesh.cpp.
References _cells, _connectivityMap, _coordinates, _faces, _nodes, getAllFaceCells(), getAllFaceNodes(), and orderCellFacesAndNodes().
Referenced by MovingMeshModel< T >::advance(), StructureDeformationModel< T >::calculateNodeDisplacement(), PlateDeformationModel< T >::calculateNodeDisplacement(), debug_mesh(), extrude(), MeshPartitioner::get_local_nodes(), PartMesh::local_nodes(), IBManager::markIntersections(), AABB::meshIntersections(), PartMesh::set_eptr_eind(), MeshPartitioner::set_eptr_eind(), MeshDismantler::setNodesMapper(), MeshDismantler::setNodesSite(), PlateDeformationModel< T >::updateBoundaryMesh(), and VTKWriter< T >::VTKWriter().
 {
   SSPair key(&_cells,&_nodes);
   ConnectivityMap::const_iterator pos = _connectivityMap.find(key);
   if (pos != _connectivityMap.end())
     return *pos->second;
   const CRConnectivity& faceCells = getAllFaceCells();
   const CRConnectivity& faceNodes = getAllFaceNodes();
   SSPair keycf(&_cells,&_faces);
   shared_ptr<CRConnectivity> cellFaces = faceCells.getTranspose();
   shared_ptr<CRConnectivity> cellNodes = cellFaces->multiply(faceNodes,false);
   _connectivityMap[keycf] = cellFaces;
   _connectivityMap[key] = cellNodes;
   orderCellFacesAndNodes(*cellFaces, *cellNodes, faceNodes,
                          faceCells, *_coordinates);
   return *cellNodes;
 }
const StorageSite& Mesh::getCells () const inline
Definition at line 109 of file Mesh.h.
References _cells.
Referenced by addCRConn(), COMETInterface< T >::addFAS(), IdealGasDensityModel< T >::Impl::advance(), RosselandModel< T >::Impl::advance(), StructureModel< T >::Impl::applyBC(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), COMETModel< T >::calcBandTemps(), COMETModel< T >::calcDomainStats(), COMETModel< T >::calcModeFlux(), COMETModel< T >::calcModeTemps(), MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), ElectricModel< T >::Impl::calculateEquilibriumParameters(), StructureDeformationModel< T >::calculateNodeDisplacement(), PlateDeformationModel< T >::calculateNodeDisplacement(), PlateModel< T >::Impl::calculatePlateAcceleration(), PlateModel< T >::Impl::calculatePlateVelocity(), MeshPartitioner::cellcells_global_extension(), CellMark_Impl(), COMETModel< T >::coarsenInterfaceCells(), COMETModel< T >::coarsenInterior(), COMETModel< T >::COMETModel(), PhononModel< T >::COMETupdateTL(), GradientModel< Vector< T, 3 > >::compute(), COMETModel< T >::ComputeCoarseMacroparameters(), KineticModel< T >::ComputeCollisionfrequency(), COMETModel< T >::ComputeCollisionfrequency(), COMETModel< T >::ComputeCOMETMacroparameters(), FlowModel< T >::Impl::computeContinuityResidual(), COMETModel< T >::ComputeFineMacroparameters(), MeshMetricsCalculator< T >::computeIBandSolidInterpolationMatrices(), VacancyModel< T >::Impl::computeIBFaceConcentration(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), ElectricModel< T >::Impl::computeIBFacePotential(), ThermalModel< T >::Impl::computeIBFaceTemperature(), FlowModel< T >::Impl::computeIBFaceVelocity(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), KineticModel< T >::ComputeMacroparameters(), COMETModel< T >::ComputeMacroparameters(), KineticModel< T >::ComputeMacroparametersESBGK(), COMETModel< T >::ComputeMacroparametersESBGK(), VacancyModel< T >::Impl::computePlasticStrainRate(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), KineticModel< T >::computeSolidFacePressure(), COMETModel< T >::computeSolidFacePressure(), MeshMetricsCalculator< T >::computeSolidInterpolationMatrices(), ElectricModel< T >::Impl::computeSolidSurfaceForce(), FlowModel< T >::Impl::computeSolidSurfaceForce(), FlowModel< T >::Impl::ComputeStressTensorES(), KineticModel< T >::computeSurfaceForce(), COMETModel< T >::computeSurfaceForce(), StructureModel< T >::Impl::computeVMStress(), KineticModel< T >::ConservationofMassCheck(), COMETModel< T >::ConservationofMassCheck(), BatteryModel< T >::Impl::copyCoupledToSeparate(), BatteryModel< T >::Impl::copyPCDiffusivity(), BatteryModel< T >::Impl::copySeparateToCoupled(), KineticModel< T >::correctMassDeficit(), COMETModel< T >::correctMassDeficit(), KineticModel< T >::correctMassDeficit2(), COMETModel< T >::correctMassDeficit2(), correctMassFluxInterior(), FlowModel< T >::Impl::correctPressure(), COMETModel< T >::correctSingleNeighbor(), COMETModel< T >::correctSolution(), FlowModel< T >::Impl::correctVelocityBoundary(), FlowModel< T >::Impl::correctVelocityExplicit(), correctVelocityInterior(), countCRConn(), createDoubleShell(), IBManager::createIBFaces(), IBManager::createIBInterpolationStencil(), NcDataReader::createMappers(), FluentReader::createMesh(), createRowColSiteCRConn(), createScatterGatherCountsBuffer(), createScatterGatherIndicesBuffer(), GradientMatrix< T_Scalar >::createScatterGatherValuesBuffer(), createShell(), IBManager::createSolidInterpolationStencil(), StructureModel< T >::Impl::creepInit(), MeshPartitioner::DEBUG_cellcells_global(), MeshPartitioner::DEBUG_level1_scatter_gather_cells(), debug_mesh(), SourceDiscretization< X >::discretize(), Underrelaxer< X, Diag, OffDiag >::discretize(), BatteryPCHeatSourceDiscretization< X >::discretize(), PhononCollisionDiscretization< X, Diag, OffDiag >::discretize(), CollisionTermDiscretization< X, Diag, OffDiag >::discretize(), TrapBandTunnelingDiscretization< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJump< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize(), DriftDiscretization< X, Diag, OffDiag >::discretize(), SourceDiscretizationforFracture< T, Diag, OffDiag >::discretize(), GenericIBDiscretization< X, Diag, OffDiag >::discretize(), LinearizeDielectric< X, Diag, OffDiag >::discretize(), BatteryPCTimeDerivativeDiscretization< X, Diag, OffDiag >::discretize(), PhononConvectionDiscretization< X, Diag, OffDiag >::discretize(), TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), IbmDiscretization< X, Diag, OffDiag >::discretize(), BatteryLinearizeThermalInterface< X, Diag, OffDiag >::discretize(), BatteryLinearizePotentialInterface< X, Diag, OffDiag >::discretize(), ConvectionDiscretization< X, Diag, OffDiag >::discretize(), LinearizePotentialInterface< X, Diag, OffDiag >::discretize(), SourceDiscretizationene< X >::discretize(), BatteryPCLinearizeInterface_BV< X, Diag, OffDiag, otherMeshDiag >::discretize(), TimeDerivativeStructureDiscretization< X, Diag, OffDiag >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), BatteryLinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), LinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), MomentumPressureGradientDiscretization< X >::discretize(), TimeDerivativePlateDiscretization< X, Diag, OffDiag >::discretize(), BatteryElectricDiffusionDiscretization< X, Diag, OffDiag >::discretize(), ElecDiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), CaptureDiscretization< X, Diag, OffDiag >::discretize(), BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), EmissionDiscretization< X, Diag, OffDiag >::discretize(), SourceDiscretizationdissi< X, Diag, OffDiag >::discretize(), InjectionDiscretization< X, Diag, OffDiag >::discretize(), TunnelingDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize(), WallDiscretization< X, Diag, OffDiag >::discretize(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretize(), PlateSourceDiscretization< T, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), discretizeMassFluxInterior(), DistFunctFields< X >::DistFunctFields(), COMETInterface< T >::Distribute(), FlowModel< T >::Impl::dumpContinuityMatrix(), ThermalModel< T >::Impl::dumpMatrix(), VacancyModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), KineticModel< T >::EntropyGeneration(), COMETModel< T >::EntropyGeneration(), COMETModel< T >::equilibrate(), KineticModel< T >::EquilibriumDistributionBGK(), COMETModel< T >::EquilibriumDistributionBGK(), KineticModel< T >::EquilibriumDistributionESBGK(), COMETModel< T >::EquilibriumDistributionESBGK(), MeshMetricsCalculator< T >::eraseIBInterpolationMatrices(), TimeDerivativeStructureDiscretization< X, Diag, OffDiag >::explicitAdvance(), extrude(), MeshDismantler::faceCellsAddBoundaryInterfaces(), MeshDismantler::faceCellsAddPartitionInterfaces(), IBManager::findNearestCellForSolidFaces(), COMETInterface< T >::findWallTemp(), COMETModel< T >::FinishCoarseMesh(), fixedFluxContinuityBC(), fixedPressureContinuityBC(), fixedPressureMomentumBC(), BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), ElectricModel< T >::Impl::generateBandDiagram(), GradientMatrix< T_Scalar >::get_request_size(), get_request_size(), BatteryModel< T >::Impl::getAverageConcentration(), SpeciesModel< T >::Impl::getAverageMassFraction(), COMETModel< T >::getAverageTemperature(), getCellCells2(), BatteryModel< T >::Impl::getFaceGroupVoltage(), COMETModel< T >::getLatticeTemp(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D(), FluentReader::getMeshList(), BatteryModel< T >::Impl::getMeshVolume(), PlateModel< T >::Impl::getMoment(), FlowModel< T >::Impl::getMomentumDerivativeIntegral(), StructureModel< T >::Impl::getPlasticDiagStrain(), FlowModel< T >::Impl::getPressureIntegralonIBFaces(), StructureModel< T >::Impl::getStrain(), FlowModel< T >::Impl::getStressTensor(), StructureModel< T >::Impl::getTraction(), FlowModel< T >::Impl::getTraction(), COMETModel< T >::getValueArray(), KeModel< T >::Impl::getViscosity(), MeshDismantler::global_offset(), MeshPartitioner::global_offset(), MeshPartitioner::globalCellID_procID_map(), PhononModel< T >::HeatFluxIntegral(), Octree::Impl(), MeshMetricsCalculator< T >::init(), ThermalModel< T >::Impl::init(), FractureModel< T >::Impl::init(), VacancyModel< T >::Impl::init(), SpeciesModel< T >::Impl::init(), KeModel< T >::Impl::init(), PhononModel< T >::init(), KineticModel< T >::init(), ElectricModel< T >::Impl::init(), FlowModel< T >::Impl::init(), BatteryModel< T >::Impl::init(), COMETModel< T >::init(), StructureModel< T >::Impl::init(), PlateModel< T >::Impl::init(), MovingMeshModel< T >::init(), ElectricModel< T >::Impl::initChargeTransportLinearization(), COMETModel< T >::initCoarse(), FlowModel< T >::Impl::initContinuityLinearization(), PlateModel< T >::Impl::initDeformationLinearization(), StructureModel< T >::Impl::initDeformationLinearization(), ElectricModel< T >::Impl::initElectroStaticsLinearization(), COMETModel< T >::initializeCoarseMaxwellian(), KineticModel< T >::InitializeFgammaCoefficients(), COMETModel< T >::InitializeFgammaCoefficients(), COMETModel< T >::initializeFineMaxwellian(), KineticModel< T >::InitializeMacroparameters(), COMETModel< T >::InitializeMacroparameters(), DistFunctFields< X >::initializeMaxwellian(), KineticModel< T >::initializeMaxwellian(), COMETModel< T >::initializeMaxwellian(), KineticModel< T >::initializeMaxwellianEq(), COMETModel< T >::initializeMaxwellianEq(), KineticModel< T >::initKineticModelLinearization(), ThermalModel< T >::Impl::initLinearization(), FractureModel< T >::Impl::initLinearization(), VacancyModel< T >::Impl::initLinearization(), SpeciesModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearizationk(), FlowModel< T >::Impl::initMomentumLinearization(), BatteryModel< T >::Impl::initPCLinearization(), PhononModel< T >::initPhononModelLinearization(), BatteryModel< T >::Impl::initPotentialLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), BatteryModel< T >::Impl::initThermalLinearization(), COMETModel< T >::injectResid(), FlowModel< T >::Impl::interfaceContinuityBC(), FlowModel< T >::Impl::linearizeContinuity(), PlateModel< T >::Impl::linearizeDeformation(), KeModel< T >::Impl::linearizedissipation(), ElectricModel< T >::Impl::linearizeElectroStatics(), KineticModel< T >::linearizeKineticModel(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), PhononModel< T >::linearizePhononModel(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeThermal(), KineticModel< T >::MacroparameterIBCell(), COMETModel< T >::makeCellColors(), COMETModel< T >::MakeCoarseIndex(), COMETModel< T >::MakeCoarseMesh1(), COMETModel< T >::MakeCoarseMesh2(), COMETModel< T >::MakeCoarseModel(), COMETModel< T >::makeCoarseScatGath(), COMETInterface< T >::makeDMMcoeffs(), COMETModel< T >::makeFAS(), COMETModel< T >::makeFinestToCoarseConn(), COMETModel< T >::MakeIBCoarseModel(), COMETModel< T >::MakeInteriorCoarseMesh(), COMETModel< T >::makeNonEqTemp(), COMETModel< T >::makePlotColors(), IBManager::markFluid(), IBManager::markIBTypePlus(), IBManager::markIntersections(), IBManager::markSolid(), Mesh(), AABB::meshIntersections(), KineticModel< T >::MomentHierarchy(), COMETModel< T >::MomentHierarchy(), KineticModel< T >::NewtonsMethodBGK(), COMETModel< T >::NewtonsMethodBGK(), KineticModel< T >::NewtonsMethodESBGK(), COMETModel< T >::NewtonsMethodESBGK(), DistFunctFields< X >::OutputDistributionFunction(), COMETModel< T >::OutputDsfBLOCK(), KineticModel< T >::OutputDsfBLOCK(), KineticModel< T >::OutputDsfPOINT(), COMETModel< T >::OutputDsfPOINT(), MeshDismantler::partitionInterfaceMappers(), PhononModel< T >::PhononModel(), FlowModel< T >::Impl::postContinuitySolve(), PlateModel< T >::Impl::postPlateSolve(), pressureBoundaryPostContinuitySolve(), BatteryModel< T >::Impl::printMatrixElementsOnFace(), PhononModel< T >::printTemp(), BatteryModel< T >::Impl::recoverLastTimestep(), recvScatterGatherCountsBufferLocal(), recvScatterGatherIndicesBufferLocal(), GradientMatrix< T_Scalar >::recvScatterGatherValuesBufferLocal(), MeshPartitioner::set_cellcells_global(), MeshDismantler::setCellsMapper(), MeshDismantler::setCellsSite(), FlowModel< T >::Impl::setDirichlet(), COMETModel< T >::sete0(), MeshAssembler::setFaceCells(), MeshDismantler::setNodesMapper(), MeshDismantler::setNodesSite(), FlowModel< T >::Impl::setReferencePP(), COMETModel< T >::setStraightLine(), slipJumpMomentumBC(), FlowModel< T >::Impl::solveMomentum(), COMETModel< T >::swapGhostInfo(), syncCounts(), COMETModel< T >::syncGhostCoarsening(), syncIndices(), GradientMatrix< T_Scalar >::syncValues(), uniqueFaceCells(), IBManager::update(), PlateDeformationModel< T >::updateBoundaryMesh(), ElectricModel< T >::Impl::updateConvectionFlux(), PhononModel< T >::updatee0(), ElectricModel< T >::Impl::updateElectricField(), ElectricModel< T >::Impl::updateElectronVelocity(), updateFacePressureBoundary(), updateFacePressureInterior(), PhononModel< T >::updateHeatFlux(), BatteryModel< T >::Impl::updateShellGhosts(), MeshMetricsCalculator< T >::updateTime(), ElectricModel< T >::Impl::updateTime(), SpeciesModel< T >::Impl::updateTime(), FlowModel< T >::Impl::updateTime(), MovingMeshModel< T >::updateTime(), FractureModel< T >::Impl::updateTime(), StructureModel< T >::Impl::updateTime(), ThermalModel< T >::Impl::updateTime(), VacancyModel< T >::Impl::updateTime(), PlateModel< T >::Impl::updateTime(), BatteryModel< T >::Impl::updateTime(), COMETModel< T >::updateTime(), KineticModel< T >::updateTime(), KeModel< T >::Impl::updateTimee(), KeModel< T >::Impl::updateTimek(), PhononModel< T >::updateTL(), COMETModel< T >::updateTL(), MovingMeshModel< T >::volChange(), VTKWriter< T >::VTKWriter(), DistFunctFields< X >::weightedMaxwellian(), KineticModel< T >::weightedMaxwellian(), COMETModel< T >::weightedMaxwellian(), FluentDataExporter< T >::writeScalarField(), VTKWriter< T >::writeScalarField(), FluentDataExporter< T >::writeVectorField(), VTKWriter< T >::writeVectorField(), and COMETInterface< T >::ZeroGhost().
 {return _cells;}
StorageSite& Mesh::getCells () inline
Definition at line 157 of file Mesh.h.
References _cells.
 {return _cells;}
int Mesh::getCellZoneID () const inline
Definition at line 319 of file Mesh.h.
References _cellZoneID.
 { return _cellZoneID;}
const map<int,int>& Mesh::getCommonFacesMap () const inline
Definition at line 255 of file Mesh.h.
References _commonFacesMap.
 { return _commonFacesMap;}
const map<int,int>& Mesh::getCommonFacesMapOther () const inline
Definition at line 256 of file Mesh.h.
References _commonFacesMapOther.
 { return _commonFacesMapOther;}
const CRConnectivity & Mesh::getConnectivity (const StorageSite & from, const StorageSite & to) const
Definition at line 416 of file Mesh.cpp.
References _connectivityMap.
Referenced by CellMark_Impl(), MeshMetricsCalculator< T >::computeGridInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBandSolidInterpolationMatrices(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), MeshMetricsCalculator< T >::computeSolidInterpolationMatrices(), ElectricModel< T >::Impl::computeSolidSurfaceForce(), FlowModel< T >::Impl::computeSolidSurfaceForce(), KineticModel< T >::computeSurfaceForce(), COMETModel< T >::computeSurfaceForce(), COMETModel< T >::correctSolution(), COMETModel< T >::injectResid(), COMETModel< T >::makeFinestToCoarseConn(), and COMETModel< T >::makePlotColors().
 {
   SSPair key(&from,&to);
   ConnectivityMap::const_iterator pos = _connectivityMap.find(key);
   if (pos != _connectivityMap.end())
     return *pos->second;
   throw CException("connectivity not defined");
 }
ConnectivityMap& Mesh::getConnectivityMap () inline
Definition at line 335 of file Mesh.h.
References _connectivityMap.
Referenced by MeshPartitioner::extractBoundaryMesh().
 {return _connectivityMap;}
int Mesh::getDimension () const inline
Definition at line 105 of file Mesh.h.
References _dimension.
Referenced by AABB::AABB(), MeshMetricsCalculator< T >::calculateCellVolumes(), MeshPartitioner::cellcells_global_extension(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), MeshMetricsCalculator< T >::computeSolidInterpolationMatrices(), StructureModel< T >::Impl::computeVMStress(), StructureModel< T >::Impl::creepInit(), debug_mesh(), BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), MeshPartitioner::extractBoundaryMesh(), GradientModel< Vector< T, 3 > >::getGradientMatrix(), StructureModel< T >::Impl::getTraction(), MeshDismantler::init(), COMETModel< T >::MakeCoarseMesh1(), COMETModel< T >::MakeCoarseMesh2(), COMETModel< T >::MakeInteriorCoarseMesh(), IBManager::markIntersections(), COMETModel< T >::syncGhostCoarsening(), MovingMeshModel< T >::volChange(), and VTKWriter< T >::VTKWriter().
 {return _dimension;}
const CRConnectivity & Mesh::getFaceCells (const StorageSite & site) const
Definition at line 388 of file Mesh.cpp.
References _cells, _connectivityMap, CRConnectivity::createOffset(), getAllFaceCells(), StorageSite::getCount(), and StorageSite::getOffset().
Referenced by COMETModel< T >::binwiseHeatFluxIntegral(), MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), COMETModel< T >::coarsenInterfaceCells(), COMETModel< T >::coarsenInterior(), GradientModel< Vector< T, 3 > >::compute(), FlowModel< T >::Impl::ComputeStressTensorES(), correctMassFluxInterior(), COMETModel< T >::correctSingleNeighbor(), FlowModel< T >::Impl::correctVelocityBoundary(), correctVelocityInterior(), createDoubleShell(), createShell(), LinearizeInterfaceJump< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), BatteryLinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryLinearizeThermalInterface< X, Diag, OffDiag >::discretize(), LinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryPCLinearizeInterface_BV< X, Diag, OffDiag, otherMeshDiag >::discretize(), BatteryLinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), LinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), MomentumPressureGradientDiscretization< X >::discretize(), BatteryElectricDiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), InjectionDiscretization< X, Diag, OffDiag >::discretize(), TunnelingDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize(), WallDiscretization< X, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), discretizeMassFluxInterior(), extrude(), COMETModel< T >::FinishCoarseMesh(), fixedFluxContinuityBC(), fixedPressureContinuityBC(), fixedPressureMomentumBC(), BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), BatteryModel< T >::Impl::getFaceGroupVoltage(), FlowModel< T >::Impl::getPressureIntegralonIBFaces(), PhononModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), PhononModel< T >::init(), COMETModel< T >::init(), ElectricModel< T >::Impl::initChargeTransportLinearization(), COMETModel< T >::initCoarse(), FlowModel< T >::Impl::initContinuityLinearization(), ElectricModel< T >::Impl::initElectroStaticsLinearization(), COMETModel< T >::initFromOld(), ThermalModel< T >::Impl::initLinearization(), FractureModel< T >::Impl::initLinearization(), VacancyModel< T >::Impl::initLinearization(), SpeciesModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearizationk(), FlowModel< T >::Impl::initMomentumLinearization(), BatteryModel< T >::Impl::initPCLinearization(), BatteryModel< T >::Impl::initPotentialLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), BatteryModel< T >::Impl::initThermalLinearization(), FlowModel< T >::Impl::interfaceContinuityBC(), FlowModel< T >::Impl::linearizeContinuity(), KeModel< T >::Impl::linearizedissipation(), KineticModel< T >::linearizeKineticModel(), PhononModel< T >::linearizePhononModel(), COMETModel< T >::MakeCoarseMesh1(), COMETModel< T >::MakeCoarseMesh2(), COMETInterface< T >::makeDMMcoeffs(), COMETModel< T >::MakeInteriorCoarseMesh(), IBManager::markIntersections(), COMETModel< T >::modewiseHeatFluxIntegral(), pressureBoundaryPostContinuitySolve(), BatteryModel< T >::Impl::printMatrixElementsOnFace(), COMETModel< T >::setLocalScatterMaps(), slipJumpMomentumBC(), COMETModel< T >::syncGhostCoarsening(), updateFacePressureBoundary(), updateFacePressureInterior(), COMETInterface< T >::updateOtherGhost(), COMETInterface< T >::updateResid(), BatteryModel< T >::Impl::updateShellGhosts(), MovingMeshModel< T >::volChange(), FluentDataExporter< T >::writeScalarField(), and FluentDataExporter< T >::writeVectorField().
 {
   SSPair key(&faces,&_cells);
   ConnectivityMap::const_iterator pos = _connectivityMap.find(key);
   if (pos != _connectivityMap.end())
     return *pos->second;
   shared_ptr<CRConnectivity> thisFaceCells =
     getAllFaceCells().createOffset(faces,faces.getOffset(),faces.getCount());
   _connectivityMap[key] = thisFaceCells;
   return *thisFaceCells;
 }
const CRConnectivity & Mesh::getFaceCells2 () const
Definition at line 633 of file Mesh.cpp.
References _faceCells2, getAllFaceCells(), getCellCells(), and CRConnectivity::multiply().
 {
   if (!_faceCells2)
   {
       const CRConnectivity& cellCells = getCellCells();
       const CRConnectivity& faceCells = getAllFaceCells();
       _faceCells2 = faceCells.multiply(cellCells, false);
   }
   return *_faceCells2;
 }
const FaceGroup & Mesh::getFaceGroup (const int fgId) const
Definition at line 1570 of file Mesh.cpp.
References getAllFaceGroups(), and FaceGroup::id.
Referenced by COMETModel< T >::coarsenInterfaceCells(), COMETDiscretizer< T >::correctInterface(), createDoubleShell(), FluentReader::createMesh(), createShell(), COMETModel< T >::initCoarse(), COMETInterface< T >::makeCoarseCoeffs(), COMETInterface< T >::makeDMMcoeffs(), COMETModel< T >::MakeInteriorCoarseMesh(), COMETInterface< T >::makeNoInterfaceCoeffs(), BatteryModel< T >::Impl::printMatrixElementsOnFace(), COMETInterface< T >::updateOtherGhost(), and COMETInterface< T >::updateResid().
 {
   foreach(const FaceGroupPtr fgPtr, getAllFaceGroups())
   {
       const FaceGroup& fg = *fgPtr;
       if (fg.id == fgId)
         return fg;
   }
   throw CException("no face group with given id");
 }
int Mesh::getFaceGroupCount () const inline
Definition at line 183 of file Mesh.h.
References _faceGroups.
Referenced by debug_mesh().
 {return _faceGroups.size();}
const CRConnectivity & Mesh::getFaceNodes (const StorageSite & site) const
Definition at line 402 of file Mesh.cpp.
References _connectivityMap, _nodes, CRConnectivity::createOffset(), getAllFaceNodes(), StorageSite::getCount(), and StorageSite::getOffset().
Referenced by AABB::AABB(), MeshMetricsCalculator< T >::calculateBoundaryNodeNormal(), createAndGetBNglobalToLocal(), MeshPartitioner::extractBoundaryMesh(), extractBoundaryMesh(), extrude(), findCommonNodes(), StructureDeformationModel< T >::updateBoundaryMesh(), and VTKWriter< T >::VTKWriter().
 {
   SSPair key(&faces,&_nodes);
   ConnectivityMap::const_iterator pos = _connectivityMap.find(key);
   if (pos != _connectivityMap.end())
     return *pos->second;
   shared_ptr<CRConnectivity> thisFaceNodes =
     getAllFaceNodes().createOffset(faces,faces.getOffset(),faces.getCount());
   _connectivityMap[key] = thisFaceNodes;
   return *thisFaceNodes;
 }
const StorageSite& Mesh::getFaces () const inline
Definition at line 108 of file Mesh.h.
References _faces.
Referenced by COMETBoundary< T >::applyTemperatureWallFine(), MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), MeshMetricsCalculator< T >::calculateFaceAreaMag(), MeshMetricsCalculator< T >::calculateFaceAreas(), MeshMetricsCalculator< T >::calculateFaceCentroids(), CellMark_Impl(), COMETModel< T >::coarsenInterfaceCells(), COMETModel< T >::coarsenInterior(), COMETModel< T >::COMETModel(), FlowModel< T >::Impl::computeContinuityResidual(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), FlowModel< T >::Impl::computeIBFaceVelocity(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), KineticModel< T >::ConservationofMassCheck(), COMETModel< T >::ConservationofMassCheck(), KineticModel< T >::correctMassDeficit(), COMETModel< T >::correctMassDeficit(), COMETModel< T >::correctSingleNeighbor(), MeshAssembler::countInterfaceNodes(), IBManager::createIBFaces(), IBManager::createIBInterpolationStencil(), FluentReader::createMesh(), IBManager::createSolidInterpolationStencil(), debug_mesh(), DriftDiscretization< X, Diag, OffDiag >::discretize(), GenericIBDiscretization< X, Diag, OffDiag >::discretize(), PhononConvectionDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization< X, Diag, OffDiag >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), MomentumPressureGradientDiscretization< X >::discretize(), ElecDiffusionDiscretization< X, Diag, OffDiag >::discretize(), MeshPartitioner::extractBoundaryMesh(), extractBoundaryMesh(), extrude(), IBManager::findNearestCellForSolidFaces(), COMETModel< T >::FinishCoarseMesh(), MeshAssembler::getInnerNodesCount(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D(), FlowModel< T >::Impl::getMomentumFluxIntegralonIBFaces(), FlowModel< T >::Impl::getPressureIntegralonIBFaces(), MeshMetricsCalculator< T >::init(), ThermalModel< T >::Impl::init(), VacancyModel< T >::Impl::init(), SpeciesModel< T >::Impl::init(), ElectricModel< T >::Impl::init(), FlowModel< T >::Impl::init(), BatteryModel< T >::Impl::init(), COMETModel< T >::init(), MovingMeshModel< T >::init(), KineticModel< T >::MacroparameterIBCell(), COMETModel< T >::MakeCoarseMesh1(), COMETModel< T >::MakeCoarseMesh2(), COMETModel< T >::MakeInteriorCoarseMesh(), IBManager::markIntersections(), Mesh(), AABB::meshIntersections(), PhononModel< T >::PhononModel(), MeshDismantler::setFacesSite(), IBManager::update(), StructureDeformationModel< T >::updateBoundaryMesh(), PlateDeformationModel< T >::updateBoundaryMesh(), ElectricModel< T >::Impl::updateConvectionFlux(), MovingMeshModel< T >::updateTime(), MovingMeshModel< T >::volChange(), FluentDataExporter< T >::writeScalarField(), VTKWriter< T >::writeScalarField(), and VTKWriter< T >::writeVectorField().
 {return _faces;}
StorageSite& Mesh::getFaces () inline
Definition at line 156 of file Mesh.h.
References _faces.
 {return _faces;}
const StorageSite* Mesh::getGhostCellSiteGather (const PartIDMeshIDPair & id) const inline
Definition at line 122 of file Mesh.h.
References _ghostCellSiteGatherMap.
Referenced by NcDataReader::createMappers().
   { return _ghostCellSiteGatherMap.find(id)->second.get(); }
const StorageSite* Mesh::getGhostCellSiteGatherLevel1 (const PartIDMeshIDPair & id) const inline
Definition at line 145 of file Mesh.h.
References _ghostCellSiteGatherMapLevel1.
   { return _ghostCellSiteGatherMapLevel1.find(id)->second.get(); }
GhostCellSiteMap& Mesh::getGhostCellSiteGatherMap () inline
Definition at line 125 of file Mesh.h.
References _ghostCellSiteGatherMap.
   { return _ghostCellSiteGatherMap; }
const GhostCellSiteMap& Mesh::getGhostCellSiteGatherMap () const inline
Definition at line 128 of file Mesh.h.
References _ghostCellSiteGatherMap.
   { return _ghostCellSiteGatherMap; }
GhostCellSiteMap& Mesh::getGhostCellSiteGatherMapLevel1 () inline
Definition at line 148 of file Mesh.h.
References _ghostCellSiteGatherMapLevel1.
Referenced by MeshPartitioner::DEBUG_level1_scatter_gather_cells().
   { return _ghostCellSiteGatherMapLevel1; }
const GhostCellSiteMap& Mesh::getGhostCellSiteGatherMapLevel1 () const inline
Definition at line 151 of file Mesh.h.
References _ghostCellSiteGatherMapLevel1.
   { return _ghostCellSiteGatherMapLevel1; }
const StorageSite* Mesh::getGhostCellSiteScatter (const PartIDMeshIDPair & id) const inline
Definition at line 113 of file Mesh.h.
References _ghostCellSiteScatterMap.
Referenced by NcDataReader::createMappers(), and MeshDismantler::partitionInterfaceMappers().
   { return _ghostCellSiteScatterMap.find(id)->second.get(); }
const StorageSite* Mesh::getGhostCellSiteScatterLevel1 (const PartIDMeshIDPair & id) const inline
Definition at line 136 of file Mesh.h.
References _ghostCellSiteScatterMapLevel1.
   { return _ghostCellSiteScatterMapLevel1.find(id)->second.get(); }
const GhostCellSiteMap& Mesh::getGhostCellSiteScatterMap () const inline
Definition at line 116 of file Mesh.h.
References _ghostCellSiteScatterMap.
Referenced by MeshPartitioner::globalCellID_procID_map().
   { return _ghostCellSiteScatterMap; }
GhostCellSiteMap& Mesh::getGhostCellSiteScatterMap () inline
Definition at line 119 of file Mesh.h.
References _ghostCellSiteScatterMap.
   { return _ghostCellSiteScatterMap; }
const GhostCellSiteMap& Mesh::getGhostCellSiteScatterMapLevel1 () const inline
Definition at line 139 of file Mesh.h.
References _ghostCellSiteScatterMapLevel1.
Referenced by MeshPartitioner::DEBUG_level1_scatter_gather_cells().
   { return _ghostCellSiteScatterMapLevel1; }
GhostCellSiteMap& Mesh::getGhostCellSiteScatterMapLevel1 () inline
Definition at line 142 of file Mesh.h.
References _ghostCellSiteScatterMapLevel1.
   { return _ghostCellSiteScatterMapLevel1; }
map<int,int>& Mesh::getGlobalToLocal () inline
Definition at line 243 of file Mesh.h.
References _globalToLocal.
Referenced by addCRConn(), createRowColSiteCRConn(), MeshPartitioner::DEBUG_local_global(), MeshDismantler::set_local_global(), MeshPartitioner::set_local_global(), MeshDismantler::setCellsSite(), FlowModel< T >::Impl::setDirichlet(), FlowModel< T >::Impl::setReferencePP(), and GradientMatrix< T_Scalar >::syncValues().
 { return _globalToLocal;}
const map<int,int>& Mesh::getGlobalToLocal () const inline
Definition at line 244 of file Mesh.h.
References _globalToLocal.
 { return _globalToLocal;}
const map<int,int> Mesh::getGlobalToLocalNodes () const inline
Definition at line 235 of file Mesh.h.
References _globalToLocalNodes.
 { return _globalToLocalNodes;}
map<int,int> Mesh::getGlobalToLocalNodes () inline
Definition at line 236 of file Mesh.h.
References _globalToLocalNodes.
 { return _globalToLocalNodes;}
const Array< int > & Mesh::getIBFaceList () const
Definition at line 686 of file Mesh.cpp.
References _ibFaceList.
Referenced by CellMark_Impl(), GradientModel< Vector< T, 3 > >::compute(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), FlowModel< T >::Impl::computeIBFaceVelocity(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), IBManager::createIBInterpolationStencil(), IBManager::createSolidInterpolationStencil(), FlowModel< T >::Impl::getMomentumFluxIntegralonIBFaces(), FlowModel< T >::Impl::getPressureIntegralonIBFaces(), and IBManager::update().
 {
   if (_ibFaceList)  return (*_ibFaceList);
   throw CException("ib face list not defined");
 }
const StorageSite& Mesh::getIBFaces () const inline
Definition at line 111 of file Mesh.h.
References _ibFaces.
Referenced by CellMark_Impl(), COMETESBGKDiscretizer< T >::COMETConvection(), COMETESBGKDiscretizer< T >::COMETConvectionFine(), GradientModel< Vector< T, 3 > >::compute(), VacancyModel< T >::Impl::computeIBFaceConcentration(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), ElectricModel< T >::Impl::computeIBFacePotential(), ThermalModel< T >::Impl::computeIBFaceTemperature(), FlowModel< T >::Impl::computeIBFaceVelocity(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), KineticModel< T >::computeSolidFacePressure(), COMETModel< T >::computeSolidFacePressure(), KineticModel< T >::correctMassDeficit(), COMETModel< T >::correctMassDeficit(), IBManager::createIBFaces(), IBManager::createIBInterpolationStencil(), IBManager::createSolidInterpolationStencil(), GenericIBDiscretization< X, Diag, OffDiag >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), discretizeMassFluxInterior(), MeshMetricsCalculator< T >::eraseIBInterpolationMatrices(), FlowModel< T >::Impl::getMomentumFluxIntegralonIBFaces(), FlowModel< T >::Impl::getPressureIntegralonIBFaces(), KineticModel< T >::MacroparameterIBCell(), COMETModel< T >::MakeCoarseMesh2(), COMETModel< T >::MakeIBCoarseModel(), markIBFaces(), COMETESBGKDiscretizer< T >::setBoundaryValFine(), and IBManager::update().
 {return _ibFaces;}
StorageSite& Mesh::getIBFaces () inline
Definition at line 159 of file Mesh.h.
References _ibFaces.
 {return _ibFaces;}
int Mesh::getID () const inline
Definition at line 106 of file Mesh.h.
References _id.
Referenced by IdealGasDensityModel< T >::Impl::advance(), RosselandModel< T >::Impl::advance(), COMETModel< T >::binwiseHeatFluxIntegral(), ElectricModel< T >::Impl::calculateEquilibriumParameters(), COMETModel< T >::COMETModel(), ElectricModel< T >::Impl::computeSolidSurfaceForce(), createDoubleShell(), debug_mesh(), BatteryElectricDiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), ElectricModel< T >::Impl::generateBandDiagram(), COMETModel< T >::getValueArray(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), RosselandModel< T >::Impl::Impl(), IdealGasDensityModel< T >::Impl::Impl(), ThermalModel< T >::Impl::Impl(), VacancyModel< T >::Impl::Impl(), SpeciesModel< T >::Impl::Impl(), FractureModel< T >::Impl::Impl(), KeModel< T >::Impl::Impl(), BatteryModel< T >::Impl::Impl(), ElectricModel< T >::Impl::Impl(), FlowModel< T >::Impl::Impl(), StructureModel< T >::Impl::Impl(), PlateModel< T >::Impl::Impl(), ThermalModel< T >::Impl::init(), FractureModel< T >::Impl::init(), VacancyModel< T >::Impl::init(), SpeciesModel< T >::Impl::init(), KeModel< T >::Impl::init(), KineticModel< T >::init(), ElectricModel< T >::Impl::init(), FlowModel< T >::Impl::init(), BatteryModel< T >::Impl::init(), COMETModel< T >::init(), StructureModel< T >::Impl::init(), PlateModel< T >::Impl::init(), COMETModel< T >::initFromOld(), KineticModel< T >::KineticModel(), COMETModel< T >::modewiseHeatFluxIntegral(), FlowModel< T >::Impl::printMassFluxIntegrals(), BatteryModel< T >::Impl::printMatrixElementsOnFace(), FlowModel< T >::Impl::printMomentumFluxIntegrals(), FlowModel< T >::Impl::printPressureIntegrals(), KineticModel< T >::SetBoundaryConditions(), COMETModel< T >::SetBoundaryConditions(), IBManager::update(), ElectricModel< T >::Impl::updateTime(), and MovingMeshModel< T >::volChange().
 {return _id;}
int Mesh::getInterfaceGroupCount () const inline
Definition at line 185 of file Mesh.h.
References _interfaceGroups.
Referenced by MeshPartitioner::cellcells_global_extension(), debug_mesh(), MeshDismantler::faceCellsAddPartitionInterfaces(), MeshDismantler::faceNodesAddPartitionInterfaces(), MeshDismantler::faceNodesInit(), MeshPartitioner::gatherCellsLevel1_partID_map(), MeshAssembler::getInnerNodesCount(), MeshAssembler::getInterfaceNodesCount(), MeshAssembler::getInterfaceNodesDuplicatedCount(), MeshDismantler::partitionInterfaceMappers(), MeshAssembler::setFaceCells(), MeshAssembler::setFaceNodes(), and MeshAssembler::setInterfaceNodes().
 {return _interfaceGroups.size();}
const FaceGroupList& Mesh::getInterfaceGroups () const inline
Definition at line 190 of file Mesh.h.
References _interfaceGroups.
Referenced by PhononModel< T >::callBoundaryConditions(), KineticModel< T >::callBoundaryConditions(), COMETModel< T >::callCOMETBoundaryConditions(), MeshPartitioner::cellcells_global_extension(), BatteryModel< T >::Impl::copyCoupledToSeparate(), BatteryModel< T >::Impl::copySeparateToCoupled(), COMETModel< T >::correctSingleNeighbor(), MeshDismantler::faceCellsAddPartitionInterfaces(), MeshDismantler::faceNodesAddPartitionInterfaces(), MeshDismantler::faceNodesInit(), MeshPartitioner::gatherCellsLevel1_partID_map(), BatteryModel< T >::Impl::getHeatFluxIntegral(), MeshAssembler::getInnerNodesCount(), MeshAssembler::getInterfaceNodesCount(), MeshAssembler::getInterfaceNodesDuplicatedCount(), SpeciesModel< T >::Impl::getMassFluxIntegral(), BatteryModel< T >::Impl::getMassFluxIntegral(), ElectricModel< T >::Impl::getPotentialFluxIntegral(), BatteryModel< T >::Impl::getPotentialFluxIntegral(), ThermalModel< T >::Impl::init(), FractureModel< T >::Impl::init(), VacancyModel< T >::Impl::init(), SpeciesModel< T >::Impl::init(), KeModel< T >::Impl::init(), KineticModel< T >::init(), ElectricModel< T >::Impl::init(), BatteryModel< T >::Impl::init(), COMETModel< T >::init(), ElectricModel< T >::Impl::initChargeTransportLinearization(), COMETModel< T >::initCoarse(), FlowModel< T >::Impl::initContinuityLinearization(), ElectricModel< T >::Impl::initElectroStaticsLinearization(), ThermalModel< T >::Impl::initLinearization(), FractureModel< T >::Impl::initLinearization(), VacancyModel< T >::Impl::initLinearization(), SpeciesModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearizationk(), FlowModel< T >::Impl::initMomentumLinearization(), BatteryModel< T >::Impl::initPCLinearization(), BatteryModel< T >::Impl::initPotentialLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), BatteryModel< T >::Impl::initThermalLinearization(), ThermalModel< T >::Impl::linearize(), FractureModel< T >::Impl::linearize(), VacancyModel< T >::Impl::linearize(), SpeciesModel< T >::Impl::linearize(), ElectricModel< T >::Impl::linearizeChargeTransport(), FlowModel< T >::Impl::linearizeContinuity(), KeModel< T >::Impl::linearizedissipation(), ElectricModel< T >::Impl::linearizeElectroStatics(), KeModel< T >::Impl::linearizeenergy(), KineticModel< T >::linearizeKineticModel(), FlowModel< T >::Impl::linearizeMomentum(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), BatteryModel< T >::Impl::linearizeThermal(), COMETModel< T >::MakeCoarseMesh2(), MeshDismantler::partitionInterfaceMappers(), FlowModel< T >::Impl::postContinuitySolve(), MeshAssembler::setFaceCells(), MeshAssembler::setFaceNodes(), and MeshAssembler::setInterfaceNodes().
   {return _interfaceGroups;}
const FaceGroup& Mesh::getInteriorFaceGroup () const inline
Definition at line 181 of file Mesh.h.
References _interiorFaceGroup.
Referenced by debug_mesh(), StructureSourceDiscretization< T, Diag, OffDiag >::discretize(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretize(), PlateSourceDiscretization< T, Diag, OffDiag >::discretize(), MeshDismantler::faceCellsAddInteriorFaces(), MeshDismantler::faceCellsAddMeshInterfaces(), MeshDismantler::faceNodesAddInteriorFaces(), MeshDismantler::faceNodesAddMeshInterfaces(), MeshDismantler::faceNodesInit(), COMETModel< T >::HeatFluxIntegralFace(), FlowModel< T >::Impl::linearizeContinuity(), FlowModel< T >::Impl::postContinuitySolve(), MeshDismantler::setCellsSite(), MeshAssembler::setFaceCells(), MeshAssembler::setFaceNodes(), and MeshAssembler::setMeshCellColor().
 {return *_interiorFaceGroup;}
Array<int>& Mesh::getLocalToGlobal () inline
Definition at line 240 of file Mesh.h.
References _localToGlobal.
Referenced by MeshPartitioner::cellcells_global_extension(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), createScatterGatherIndicesBuffer(), MeshPartitioner::DEBUG_local_global(), MeshPartitioner::gatherCellsLevel1_partID_map(), MeshPartitioner::globalCellID_procID_map(), IBManager::markIBTypePlus(), MeshPartitioner::set_cellcells_global(), MeshDismantler::set_local_global(), MeshPartitioner::set_local_global(), and FlowModel< T >::Impl::setDirichlet().
 { return *_localToGlobal;}
const Array<int>& Mesh::getLocalToGlobal () const inline
Definition at line 241 of file Mesh.h.
References _localToGlobal.
 { return *_localToGlobal;}
shared_ptr< Array<int> > Mesh::getLocalToGlobalNodesPtr () inline
Definition at line 234 of file Mesh.h.
References _localToGlobalNodes.
 { return _localToGlobalNodes;}
shared_ptr< ArrayBase > Mesh::getLocalToGlobalPtr () inline
Definition at line 239 of file Mesh.h.
References _localToGlobal.
 { return _localToGlobal;}
const Array<VecD3>& Mesh::getNodeCoordinates () const inline
Definition at line 218 of file Mesh.h.
References _coordinates.
Referenced by AABB::AABB(), MeshMetricsCalculator< T >::calculateNodeCoordinates(), PartMesh::coordinates(), MeshPartitioner::coordinates(), PartMesh::dumpTecplot(), MeshPartitioner::extractBoundaryMesh(), extractBoundaryMesh(), extrude(), findCommonNodes(), NcDataWriter::get_coords(), MeshAssembler::getInterfaceNodesCount(), IBManager::markIntersections(), AABB::meshIntersections(), MeshAssembler::setCoord(), MeshDismantler::setCoord(), StructureDeformationModel< T >::updateBoundaryMesh(), and PlateDeformationModel< T >::updateBoundaryMesh().
 {return *_coordinates;}
Array<VecD3>& Mesh::getNodeCoordinates () inline
Definition at line 219 of file Mesh.h.
References _coordinates.
 {return *_coordinates;}
shared_ptr<ArrayBase> Mesh::getNodeCoordinatesPtr () inline
Definition at line 220 of file Mesh.h.
References _coordinates.
 {return _coordinates;}
const StorageSite& Mesh::getNodes () const inline
Definition at line 110 of file Mesh.h.
References _nodes.
Referenced by MovingMeshModel< T >::advance(), MeshMetricsCalculator< T >::calculateFaceAreas(), MeshMetricsCalculator< T >::calculateFaceCentroids(), MeshMetricsCalculator< T >::calculateNodeCoordinates(), StructureDeformationModel< T >::calculateNodeDisplacement(), PlateDeformationModel< T >::calculateNodeDisplacement(), FluentReader::createMesh(), debug_mesh(), StructureDeformationModel< T >::deformMeshStructure(), PlateDeformationModel< T >::deformMeshStructure(), PlateDeformationModel< T >::deformPlate(), StructureDeformationModel< T >::deformStructure(), MeshPartitioner::extractBoundaryMesh(), extractBoundaryMesh(), extrude(), FluentReader::getMeshList(), getUpdatedNodesCoordCoupling(), PlateDeformationModel< T >::init(), StructureDeformationModel< T >::init(), MovingMeshModel< T >::init(), Mesh(), setCommonFacesMap(), MeshAssembler::setCoord(), MeshDismantler::setCoord(), setNodeRepeationArrayCoupling(), MeshDismantler::setNodesMapper(), MeshDismantler::setNodesSite(), StructureDeformationModel< T >::updateBoundaryMesh(), PlateDeformationModel< T >::updateBoundaryMesh(), PlateDeformationModel< T >::updateTime(), StructureDeformationModel< T >::updateTime(), MovingMeshModel< T >::updateTime(), MovingMeshModel< T >::volChange(), and VTKWriter< T >::VTKWriter().
 {return _nodes;}
StorageSite& Mesh::getNodes () inline
Definition at line 158 of file Mesh.h.
References _nodes.
 {return _nodes;}
int Mesh::getNumBounCells () private
Definition at line 2350 of file Mesh.cpp.
References getBoundaryFaceGroups().
Referenced by addCRConn(), countCRConn(), and createRowColSiteCRConn().
 {
     //boundary information has been stored
     const FaceGroupList&  boundaryFaceGroups = this->getBoundaryFaceGroups();
     int nBounElm = 0;
     for ( int bounID = 0; bounID < int(boundaryFaceGroups.size()); bounID++){
         nBounElm += boundaryFaceGroups.at(bounID)->site.getCount();
     }
     return nBounElm;
 }
int Mesh::getNumOfAssembleMesh () const inline
Definition at line 251 of file Mesh.h.
References _numOfAssembleMesh.
Referenced by MeshDismantler::init().
 { return _numOfAssembleMesh;}
const StorageSite& Mesh::getOtherFaceGroupSite () const inline
Definition at line 332 of file Mesh.h.
References _otherFaceGroupSite.
Referenced by LinearizeInterfaceJump< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), BatteryLinearizeThermalInterface< X, Diag, OffDiag >::discretize(), BatteryLinearizePotentialInterface< X, Diag, OffDiag >::discretize(), LinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryPCLinearizeInterface_BV< X, Diag, OffDiag, otherMeshDiag >::discretize(), BatteryLinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), LinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), and BatteryModel< T >::Impl::updateShellGhosts().
   {return *_otherFaceGroupSite;}
int Mesh::getOtherMeshID () const inline
Definition at line 327 of file Mesh.h.
References _otherMeshID.
Referenced by BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), SpeciesModel< T >::Impl::init(), BatteryModel< T >::Impl::init(), SpeciesModel< T >::Impl::linearize(), ElectricModel< T >::Impl::linearizeElectroStatics(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), BatteryModel< T >::Impl::linearizeThermal(), and BatteryModel< T >::Impl::updateShellGhosts().
 {return _otherMeshID;}
const StorageSite& Mesh::getParentFaceGroupSite () const inline
Definition at line 329 of file Mesh.h.
References _parentFaceGroupSite.
Referenced by MeshMetricsCalculator< T >::calculateCellCentroids(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJump< X, Diag, OffDiag >::discretize(), LinearizeDielectric< X, Diag, OffDiag >::discretize(), BatteryLinearizeThermalInterface< X, Diag, OffDiag >::discretize(), BatteryLinearizePotentialInterface< X, Diag, OffDiag >::discretize(), LinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryPCLinearizeInterface_BV< X, Diag, OffDiag, otherMeshDiag >::discretize(), BatteryLinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), LinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), and BatteryModel< T >::Impl::updateShellGhosts().
   {return *_parentFaceGroupSite;}
int Mesh::getParentMeshID () const inline
Definition at line 326 of file Mesh.h.
References _parentMeshID.
Referenced by BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), SpeciesModel< T >::Impl::init(), BatteryModel< T >::Impl::init(), SpeciesModel< T >::Impl::linearize(), ElectricModel< T >::Impl::linearizeElectroStatics(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), BatteryModel< T >::Impl::linearizeThermal(), and BatteryModel< T >::Impl::updateShellGhosts().
 {return _parentMeshID;}
PeriodicFacePairs& Mesh::getPeriodicFacePairs () inline
Definition at line 337 of file Mesh.h.
References _periodicFacePairs.
Referenced by FluentReader::createMesh(), and MeshMetricsCalculator< T >::init().
 { return _periodicFacePairs;}
const PeriodicFacePairs& Mesh::getPeriodicFacePairs () const inline
Definition at line 338 of file Mesh.h.
References _periodicFacePairs.
 { return _periodicFacePairs;}
const ArrayBase& Mesh::getRecvCounts (const EntryIndex & e) const inline
Definition at line 280 of file Mesh.h.
References _recvCounts.
Referenced by GradientMatrix< T_Scalar >::createScatterGatherValuesBuffer(), and GradientMatrix< T_Scalar >::syncValues().
 { return *_recvCounts[e];}
const ArrayBase& Mesh::getRecvIndices (const EntryIndex & e) const inline
Definition at line 281 of file Mesh.h.
References _recvIndices.
Referenced by GradientMatrix< T_Scalar >::syncValues().
 { return *_recvIndices[e];}
const ArrayBase& Mesh::getSendCounts (const EntryIndex & e) const inline
Definition at line 277 of file Mesh.h.
References _sendCounts.
Referenced by recvScatterGatherCountsBufferLocal().
 { return *_sendCounts[e];}
const ArrayBase& Mesh::getSendIndices (const EntryIndex & e) const inline
Definition at line 278 of file Mesh.h.
References _sendIndices.
Referenced by recvScatterGatherIndicesBufferLocal().
 { return *_sendIndices[e];}
shared_ptr< ArrayBase > Mesh::getUpdatedNodesCoordCoupling (const GeomFields & geomField, const Mesh & bMesh)
Definition at line 784 of file Mesh.cpp.
References _boundaryNodesSet, _repeatNodes, GeomFields::coordinate, StorageSite::getCount(), getNodes(), StorageSite::getScatterIndex(), and Array< T >::zero().
 {
     const StorageSite& nodes = this->getNodes();
     const StorageSite& boundaryNodes = bMesh.getNodes();
     const map<int,int>&  globalToLocal = nodes.getScatterIndex().find(&boundaryNodes)->second;
     const Array<VecD3>& fieldCoord = dynamic_cast< const Array<VecD3>& > (geomField.coordinate[nodes]);
     shared_ptr< ArrayBase> returnCoord = geomField.coordinate[nodes].newSizedClone( boundaryNodes.getCount() );
     Array<VecD3>& coord = dynamic_cast< Array<VecD3>& > ( *returnCoord );
     coord.zero();
     foreach( const set<int>::value_type node, _boundaryNodesSet ){
        const int globalNodeID = (*_localToGlobalNodes)[node];
        const int localNodeID  = globalToLocal.find(globalNodeID)->second;
        coord[localNodeID]   = fieldCoord[node] / double( (*_repeatNodes)[localNodeID] );  //this fill local partitionin mesh
     }
    //global reduction to find repeating nodes
 // #ifdef FVM_PARALLEL
 //    const int count = coord.getLength() * 3;
 //    MPI::COMM_WORLD.Allreduce(MPI::IN_PLACE, coord.getData(), count, MPI::DOUBLE, MPI::SUM);
 // #endif
     return returnCoord;
 }
void Mesh::InterfaceToBoundary ()
Definition at line 2424 of file Mesh.cpp.
References _boundaryGroups, and _interfaceGroups.
 {
   foreach(FaceGroupPtr fgPtr, _interfaceGroups)
     {
       _boundaryGroups.push_back(fgPtr);
     }
   _interfaceGroups.clear();
 }
bool Mesh::isConnectedShell () const inline
Definition at line 325 of file Mesh.h.
References _isConnectedShell.
Referenced by BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), BatteryModel< T >::Impl::initSpeciesLinearization(), BatteryModel< T >::Impl::linearizeSpecies(), and BatteryModel< T >::Impl::updateShellGhosts().
 {return _isConnectedShell;}
bool Mesh::isDoubleShell () const inline
Definition at line 324 of file Mesh.h.
References _isDoubleShell.
Referenced by MeshMetricsCalculator< T >::calculateCellCentroids(), BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), SpeciesModel< T >::Impl::init(), BatteryModel< T >::Impl::init(), BatteryModel< T >::Impl::initPCLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), SpeciesModel< T >::Impl::linearize(), ElectricModel< T >::Impl::linearizeElectroStatics(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), BatteryModel< T >::Impl::linearizeThermal(), and BatteryModel< T >::Impl::updateShellGhosts().
 {return _isDoubleShell;}
bool Mesh::isMergedMesh () const inline
Definition at line 250 of file Mesh.h.
References _isAssembleMesh.
 { return _isAssembleMesh;}
bool Mesh::isShell () const inline
Definition at line 323 of file Mesh.h.
References _isShell.
Referenced by MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), GradientModel< Vector< T, 3 > >::compute(), VacancyModel< T >::Impl::computeIBFaceConcentration(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), ElectricModel< T >::Impl::computeIBFacePotential(), ThermalModel< T >::Impl::computeIBFaceTemperature(), FlowModel< T >::Impl::computeIBFaceVelocity(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), KineticModel< T >::computeSolidFacePressure(), COMETModel< T >::computeSolidFacePressure(), MeshMetricsCalculator< T >::computeSolidInterpolationMatrices(), ElectricModel< T >::Impl::computeSolidSurfaceForce(), IBManager::createIBFaces(), MeshMetricsCalculator< T >::init(), Linearizer::linearize(), IBManager::markIntersections(), MeshMetricsCalculator< T >::recalculate(), MeshMetricsCalculator< T >::recalculate_deform(), and IBManager::update().
 {return _isShell;}
void Mesh::recvScatterGatherCountsBufferLocal ()
Definition at line 2050 of file Mesh.cpp.
References _recvCounts, getCells(), StorageSite::getGatherMap(), StorageSite::getGatherProcID(), StorageSite::getMesh(), and getSendCounts().
Referenced by MeshDismantler::setCellCellsGhostExt().
 {
 #ifdef FVM_PARALLEL
    const StorageSite& site     = this->getCells();
    const StorageSite::GatherMap& gatherMap = site.getGatherMap();
    foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
       const StorageSite&  oSite = *mpos.first;
       //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
       EntryIndex e(&oSite,&site);
       //allocate array
       //mesh interface can be done know
       if ( oSite.getGatherProcID() == - 1) {
            const Mesh& otherMesh = oSite.getMesh();
           *_recvCounts[e] = otherMesh.getSendCounts(e);
       }
    }
 #endif
 }
void Mesh::recvScatterGatherIndicesBufferLocal ()
Definition at line 2172 of file Mesh.cpp.
References _recvIndices, getCells(), StorageSite::getGatherMap(), StorageSite::getGatherProcID(), StorageSite::getMesh(), and getSendIndices().
Referenced by MeshDismantler::setCellCellsGhostExt().
 {
 #ifdef FVM_PARALLEL
     //RECIEVING allocation (filling will be done by MPI Communication)
     const StorageSite& site     = this->getCells();
     const StorageSite::GatherMap& gatherMap = site.getGatherMap();
     foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
        const StorageSite&  oSite = *mpos.first;
        EntryIndex e(&oSite,&site);
        //mesh interface can be done know
        if ( oSite.getGatherProcID() == - 1) {
           const Mesh& otherMesh = oSite.getMesh();
           *_recvIndices[e] = otherMesh.getSendIndices(e);
        }
     }
 #endif
 }
void Mesh::setCellZoneID (const int id) inline
Definition at line 320 of file Mesh.h.
References _cellZoneID.
Referenced by MeshPartitioner::construct_mesh(), and FluentReader::createMesh().
 {_cellZoneID = id;}
void Mesh::setCommonFacesMap (const Mesh & bMesh)
Definition at line 810 of file Mesh.cpp.
References _commonFacesMap, _commonFacesMapOther, getAllFaceNodes(), getBoundaryFaceGroups(), StorageSite::getCount(), CRConnectivity::getCount(), getNodes(), StorageSite::getOffset(), StorageSite::getScatterIndex(), CRConnectivity::getTranspose(), and FaceGroup::site.
 {
   //loop over local faces
   const StorageSite& nodes = this->getNodes();
   const StorageSite& boundaryNodes = bMesh.getNodes();
   const map<int,int>&  globalToLocal = nodes.getScatterIndex().find(&boundaryNodes)->second;
    const CRConnectivity& faceNodes = this->getAllFaceNodes();
    const CRConnectivity& faceNodesBMesh = bMesh.getAllFaceNodes();
    shared_ptr<CRConnectivity> nodeFacesBMeshPtr = faceNodesBMesh.getTranspose();
    const CRConnectivity& nodeFacesBMesh = *nodeFacesBMeshPtr;
    foreach(const FaceGroupPtr fgPtr, this->getBoundaryFaceGroups()){
       const FaceGroup& fg = *fgPtr;
       const StorageSite& faces = fg.site;
       const int nFaces = faces.getCount();
       for(int f=0; f<nFaces; f++){
          const int faceID = f + faces.getOffset();
          const int nFaceNodes = faceNodes.getCount(faceID);
          set<int> comp; //vector to store localIds of bMesh
          vector<int> nodeList(nFaceNodes,0);
          for(int nn=0; nn<nFaceNodes; nn++){
             //get local node number
             const int n=faceNodes(faceID,nn);
             const int globalNodeID = (*_localToGlobalNodes)[n];
             const int localNodeID  = globalToLocal.find(globalNodeID)->second;   //localID boundary mesh
             comp.insert(localNodeID);
             nodeList[nn] = localNodeID;
          }
          //now get corresponding faceID to boundaryMeshFaceID
          //loop over nodeFaces on boundaryMesh
          for( int i = 0; i < nFaceNodes; i++ ){
             bool breakUpperLoop = false;
             const int nfaces = nodeFacesBMesh.getCount(nodeList[i]);
             //loop over faces around nodes of boundary mesh
             for ( int j = 0; j < nfaces; j++ ){
                const int localFaceID  = nodeFacesBMesh(nodeList[i],j); //localFaceID boundary mesh
                //check if this face is connected to our comp vector
                const int nnodes = faceNodesBMesh.getCount(localFaceID);
                vector<bool> matchingNodes(nFaceNodes,false);
                for ( int k = 0; k < nnodes; k++ ){
                   const int nodeID = faceNodesBMesh(localFaceID,j);
                   if ( comp.count(nodeID) == 1 ){ //this means if this node is in search sets
                      matchingNodes[k] = true;
                   }
                }
                //checking if matchinNodes bools are all true
                if ( find(matchingNodes.begin(), matchingNodes.end(), false) == matchingNodes.end() ){
                   _commonFacesMap[faceID] = localFaceID;
                   _commonFacesMapOther[localFaceID] = faceID;
                   breakUpperLoop = true;
                   break;
                }
             }
             if ( breakUpperLoop ){
                break;
             }
          }
       }
    }
 }
void Mesh::setConnectivity (const StorageSite & rowSite, const StorageSite & colSite, shared_ptr< CRConnectivity > conn)
Definition at line 352 of file Mesh.cpp.
References _connectivityMap.
Referenced by CellMark_Impl(), IBManager::createIBInterpolationStencil(), IBManager::createSolidInterpolationStencil(), COMETModel< T >::FinishCoarseMesh(), COMETModel< T >::MakeCoarseMesh2(), COMETModel< T >::makeFinestToCoarseConn(), and Grid::setConnFaceToGrid().
 {
   SSPair key(&rowSite,&colSite);
   _connectivityMap[key] = conn;
 }
void Mesh::setCoordinates (shared_ptr< Array< VecD3 > > x) inline
Definition at line 204 of file Mesh.h.
References _coordinates.
Referenced by FluentReader::createMesh(), MeshPartitioner::extractBoundaryMesh(), extractBoundaryMesh(), extrude(), and Mesh().
 {_coordinates = x;}
void Mesh::setFaceCells (shared_ptr< CRConnectivity > faceCells)
Definition at line 654 of file Mesh.cpp.
References _cells, _connectivityMap, and _faces.
Referenced by FluentReader::createMesh().
 {
   SSPair key(&_faces,&_cells);
   _connectivityMap[key] = faceCells;
 }
void Mesh::setFaceNodes (shared_ptr< CRConnectivity > faceNodes)
Definition at line 646 of file Mesh.cpp.
References _connectivityMap, _faces, and _nodes.
Referenced by FluentReader::createMesh().
 {
   SSPair key(&_faces,&_nodes);
   _connectivityMap[key] = faceNodes;
 }
void Mesh::setIBFaces (shared_ptr< Array< int > > faceList) inline
Definition at line 290 of file Mesh.h.
References _ibFaceList.
Referenced by IBManager::createIBFaces().
 {_ibFaceList = faceList;}
void Mesh::setID (const int id) inline
Definition at line 321 of file Mesh.h.
References _id.
Referenced by PartMesh::construct_mesh(), MeshPartitioner::construct_mesh(), and COMETModel< T >::MakeInteriorCoarseMesh().
 {_id = id;}
void Mesh::setNodeRepeationArrayCoupling (const Mesh & bMesh)
Definition at line 753 of file Mesh.cpp.
References _boundaryNodesSet, _repeatNodes, StorageSite::getCount(), getNodes(), and StorageSite::getScatterIndex().
 {
    const StorageSite& nodes = this->getNodes();
    const StorageSite& boundaryNodes = bMesh.getNodes();
    const map<int,int>&  globalToLocal = nodes.getScatterIndex().find(&boundaryNodes)->second;
    //create repeatNodes array
    _repeatNodes = shared_ptr< Array<int> > ( new Array<int> ( boundaryNodes.getCount() ) );
    *_repeatNodes = 0;
    foreach( const set<int>::value_type& node, _boundaryNodesSet ){
       const int globalNodeID = (*_localToGlobalNodes)[node]; //from local parition mesh to global number
       const int localNodeID  = globalToLocal.find(globalNodeID)->second; //from global node id to local id in boundary mesh
       (*_repeatNodes)[localNodeID] = 1;  //this fill local partitionin mesh
    }
    //global reduction to find repeating nodes
 #ifdef FVM_PARALLEL
    MPI::COMM_WORLD.Allreduce(MPI::IN_PLACE, _repeatNodes->getData(),_repeatNodes->getLength(), MPI::INT, MPI::SUM);
 #endif
 //    if ( MPI::COMM_WORLD.Get_rank() == 0 )
 //    for( int i = 0; i < _repeatNodes->getLength(); i++ ){
 //       if ( (*_repeatNodes)[i] > 1 )
 //       cout << "repeatNodes[" << i << "] = " << (*_repeatNodes)[i] << endl;
 //    }
 }
void Mesh::setNumOfAssembleMesh (int nmesh) inline
Definition at line 222 of file Mesh.h.
References _numOfAssembleMesh.
 { _numOfAssembleMesh = nmesh; }
void Mesh::syncCounts ()
Definition at line 2072 of file Mesh.cpp.
References _recvCounts, _sendCounts, get_request_size(), getCells(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMap(), StorageSite::getGatherProcID(), StorageSite::getScatterMap(), and StorageSite::getTag().
Referenced by MeshDismantler::setCellCellsGhostExt().
 {
 #ifdef FVM_PARALLEL
     //SENDING
     const int  request_size = get_request_size();
     MPI::Request   request_send[ request_size ];
     MPI::Request   request_recv[ request_size ];
     int indxSend = 0;
     int indxRecv = 0;
     const StorageSite&    site      = this->getCells();
     const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
     foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
         const StorageSite&  oSite = *mpos.first;
         EntryIndex e(&site,&oSite);
         //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
         ArrayBase& sendArray = *_sendCounts[e];
         //loop over surround indices and itself
         int to_where  = oSite.getGatherProcID();
         if ( to_where != -1 ){
            int mpi_tag = oSite.getTag();
            request_send[indxSend++] =
                  MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
         }
      }
      //RECIEVING
      //getting values from other meshes to fill g
      const StorageSite::GatherMap& gatherMap = site.getGatherMap();
      foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
         const StorageSite&  oSite = *mpos.first;
         //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
         EntryIndex e(&oSite,&site);
         ArrayBase& recvArray = *_recvCounts[e];
         int from_where       = oSite.getGatherProcID();
         if ( from_where != -1 ){
            int mpi_tag = oSite.getTag();
            request_recv[indxRecv++] =
                   MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
         }
      }
      int count  = get_request_size();
      MPI::Request::Waitall( count, request_recv );
      MPI::Request::Waitall( count, request_send );
 #endif
 }
void Mesh::syncIndices ()
Definition at line 2191 of file Mesh.cpp.
References _recvIndices, _sendIndices, get_request_size(), getCells(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMap(), StorageSite::getGatherProcID(), StorageSite::getScatterMap(), and StorageSite::getTag().
Referenced by MeshDismantler::setCellCellsGhostExt().
 {
 #ifdef FVM_PARALLEL
     //SENDING
     const int  request_size = get_request_size();
     MPI::Request   request_send[ request_size ];
     MPI::Request   request_recv[ request_size ];
     int indxSend = 0;
     int indxRecv = 0;
     const StorageSite&    site      = this->getCells();
     const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
     foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
         const StorageSite&  oSite = *mpos.first;
         EntryIndex e(&site,&oSite);
         //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
         ArrayBase& sendArray = *_sendIndices[e];
         //loop over surround indices and itself
         int to_where  = oSite.getGatherProcID();
         if ( to_where != -1 ){
            int mpi_tag = oSite.getTag();
            request_send[indxSend++] =
                 MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
         }
     }
     //RECIEVING
     //getting values from other meshes to fill g
     const StorageSite::GatherMap& gatherMap = site.getGatherMap();
     foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
         const StorageSite&  oSite = *mpos.first;
         EntryIndex e(&oSite,&site);
         ArrayBase& recvArray = *_recvIndices[e];
         int from_where       = oSite.getGatherProcID();
         if ( from_where != -1 ){
            int mpi_tag = oSite.getTag();
            request_recv[indxRecv++] =
                   MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
         }
      }
      int count  = get_request_size();
      MPI::Request::Waitall( count, request_recv );
      MPI::Request::Waitall( count, request_send );
 #endif
 }
void Mesh::uniqueFaceCells ()
Definition at line 666 of file Mesh.cpp.
References _globalToLocal, eraseConnectivity(), getCells(), CRConnectivity::getCol(), StorageSite::getCount(), CRConnectivity::getRow(), and CRConnectivity::getRowSite().
 {
      //uniqing numberinf for face cells
      {
         CRConnectivity& faceCells = (const_cast<Mesh *>(this))->getAllFaceCells();
         const int nfaces = faceCells.getRowSite().getCount();
         const Array<int>& row = faceCells.getRow();
         Array<int>& col = faceCells.getCol();
         for( int i = 0; i < nfaces; i++ ){
            for ( int j = row[i]; j < row[i+1]; j++ ){
               const int globalID = (*_localToGlobal)[ col[j] ];
               col[j] = _globalToLocal[globalID];
            }
         }
         const StorageSite& cellSite = this->getCells();
         this->eraseConnectivity(cellSite,cellSite);
      }
 }
Member Data Documentation
FaceGroupList Mesh::_boundaryGroups protected
Definition at line 363 of file Mesh.h.
Referenced by createBoundaryFaceGroup(), getBoundaryFaceGroups(), getBoundaryGroupCount(), and InterfaceToBoundary().
shared_ptr<Array<int> > Mesh::_boundaryNodeGlobalToLocalPtr mutable protected
Definition at line 367 of file Mesh.h.
Referenced by createAndGetBNglobalToLocal().
StorageSite* Mesh::_boundaryNodes mutable protected
Definition at line 359 of file Mesh.h.
Referenced by getBoundaryNodes().
set<int> Mesh::_boundaryNodesSet protected
Definition at line 394 of file Mesh.h.
Referenced by getBoundaryNodesSet(), getUpdatedNodesCoordCoupling(), and setNodeRepeationArrayCoupling().
shared_ptr<CRConnectivity> Mesh::_cellCells2 mutable protected
Definition at line 405 of file Mesh.h.
Referenced by getCellCells2().
shared_ptr<CRConnectivity> Mesh::_cellCellsGhostExt protected
Definition at line 389 of file Mesh.h.
Referenced by addCRConn(), countCRConn(), createRowColSiteCRConn(), and getCellCellsGhostExt().
multiMap Mesh::_cellCellsGlobal protected
Definition at line 400 of file Mesh.h.
Referenced by getCellCells2(), and getCellCellsGlobal().
shared_ptr< Array<int> > Mesh::_cellColor protected
Definition at line 371 of file Mesh.h.
Referenced by createCellColor(), and getCellColors().
shared_ptr< Array<int> > Mesh::_cellColorOther protected
Definition at line 372 of file Mesh.h.
Referenced by createCellColor(), and getCellColorsOther().
StorageSite Mesh::_cells protected
Definition at line 354 of file Mesh.h.
Referenced by createCellColor(), createLocalGlobalArray(), extrude(), getAllFaceCells(), getCellCells(), getCellFaces(), getCellNodes(), getCells(), getFaceCells(), Mesh(), and setFaceCells().
shared_ptr<StorageSite> Mesh::_cellSiteGhostExt protected
Definition at line 388 of file Mesh.h.
Referenced by createRowColSiteCRConn().
int Mesh::_cellZoneID protected
Definition at line 352 of file Mesh.h.
Referenced by getCellZoneID(), and setCellZoneID().
map<int,int> Mesh::_commonFacesMap protected
Definition at line 392 of file Mesh.h.
Referenced by getCommonFacesMap(), and setCommonFacesMap().
map<int,int> Mesh::_commonFacesMapOther protected
Definition at line 393 of file Mesh.h.
Referenced by getCommonFacesMapOther(), and setCommonFacesMap().
ConnectivityMap Mesh::_connectivityMap mutable protected
Definition at line 365 of file Mesh.h.
Referenced by createDoubleShell(), createShell(), eraseConnectivity(), extractBoundaryMesh(), extrude(), getAllFaceCells(), getAllFaceNodes(), getCellCells(), getCellFaces(), getCellNodes(), getConnectivity(), getConnectivityMap(), getFaceCells(), getFaceNodes(), Mesh(), setConnectivity(), setFaceCells(), and setFaceNodes().
shared_ptr<Array<VecD3> > Mesh::_coordinates protected
Definition at line 366 of file Mesh.h.
Referenced by getCellNodes(), getNodeCoordinates(), getNodeCoordinatesPtr(), and setCoordinates().
const int Mesh::_dimension protected
Definition at line 346 of file Mesh.h.
Referenced by createDoubleShell(), createShell(), extractBoundaryMesh(), extrude(), getDimension(), and Mesh().
shared_ptr<CRConnectivity> Mesh::_faceCells2 mutable protected
Definition at line 406 of file Mesh.h.
Referenced by getFaceCells2().
FaceGroupList Mesh::_faceGroups protected
Definition at line 362 of file Mesh.h.
Referenced by createBoundaryFaceGroup(), createInterfaceGroup(), createInteriorFaceGroup(), getAllFaceGroups(), and getFaceGroupCount().
StorageSite Mesh::_faces protected
Definition at line 355 of file Mesh.h.
Referenced by createBoundaryFaceGroup(), createInterfaceGroup(), createInteriorFaceGroup(), extrude(), getAllFaceCells(), getAllFaceNodes(), getCellFaces(), getCellNodes(), getFaces(), setFaceCells(), and setFaceNodes().
GhostCellSiteMap Mesh::_ghostCellSiteGatherMap protected
Definition at line 378 of file Mesh.h.
Referenced by createGhostCellSiteGather(), getGhostCellSiteGather(), and getGhostCellSiteGatherMap().
GhostCellSiteMap Mesh::_ghostCellSiteGatherMapLevel1 protected
Definition at line 381 of file Mesh.h.
Referenced by createGhostCellSiteGatherLevel1(), getGhostCellSiteGatherLevel1(), and getGhostCellSiteGatherMapLevel1().
GhostCellSiteMap Mesh::_ghostCellSiteScatterMap protected
Definition at line 377 of file Mesh.h.
Referenced by createGhostCellSiteScatter(), getGhostCellSiteScatter(), and getGhostCellSiteScatterMap().
GhostCellSiteMap Mesh::_ghostCellSiteScatterMapLevel1 protected
Definition at line 380 of file Mesh.h.
Referenced by createGhostCellSiteScatterLevel1(), getGhostCellSiteScatterLevel1(), and getGhostCellSiteScatterMapLevel1().
map<int,int> Mesh::_globalToLocal mutable protected
Definition at line 398 of file Mesh.h.
Referenced by getCellCells2(), getGlobalToLocal(), and uniqueFaceCells().
map<int,int> Mesh::_globalToLocalNodes mutable protected
Definition at line 399 of file Mesh.h.
Referenced by getGlobalToLocalNodes().
shared_ptr<Array<int> > Mesh::_ibFaceList mutable protected
Definition at line 369 of file Mesh.h.
Referenced by getIBFaceList(), and setIBFaces().
StorageSite Mesh::_ibFaces protected
Definition at line 358 of file Mesh.h.
Referenced by getIBFaces().
int Mesh::_id protected
Definition at line 349 of file Mesh.h.
Referenced by getID(), and setID().
FaceGroupList Mesh::_interfaceGroups protected
Definition at line 364 of file Mesh.h.
Referenced by createInterfaceGroup(), getInterfaceGroupCount(), getInterfaceGroups(), and InterfaceToBoundary().
shared_ptr<FaceGroup> Mesh::_interiorFaceGroup protected
Definition at line 361 of file Mesh.h.
Referenced by createInteriorFaceGroup(), extrude(), and getInteriorFaceGroup().
bool Mesh::_isAssembleMesh protected
Definition at line 374 of file Mesh.h.
Referenced by createCellColor(), and isMergedMesh().
bool Mesh::_isConnectedShell protected
Definition at line 410 of file Mesh.h.
Referenced by createDoubleShell(), and isConnectedShell().
bool Mesh::_isDoubleShell protected
Definition at line 409 of file Mesh.h.
Referenced by createDoubleShell(), and isDoubleShell().
bool Mesh::_isShell protected
Definition at line 408 of file Mesh.h.
Referenced by createDoubleShell(), createShell(), and isShell().
int Mesh::_lastID = 0 static protected
Definition at line 421 of file Mesh.h.
shared_ptr< Array<int> > Mesh::_localToGlobal protected
Definition at line 397 of file Mesh.h.
Referenced by createLocalGlobalArray(), getLocalToGlobal(), and getLocalToGlobalPtr().
shared_ptr< Array<int> > Mesh::_localToGlobalNodes protected
Definition at line 396 of file Mesh.h.
Referenced by createLocalToGlobalNodesArray(), and getLocalToGlobalNodesPtr().
StorageSite Mesh::_nodes protected
Definition at line 356 of file Mesh.h.
Referenced by createAndGetBNglobalToLocal(), createLocalToGlobalNodesArray(), extractBoundaryMesh(), extrude(), findCommonNodes(), getAllFaceNodes(), getBoundaryNodes(), getCellNodes(), getFaceNodes(), getNodes(), and setFaceNodes().
int Mesh::_numOfAssembleMesh protected
Definition at line 373 of file Mesh.h.
Referenced by getNumOfAssembleMesh(), and setNumOfAssembleMesh().
const StorageSite* Mesh::_otherFaceGroupSite protected
Definition at line 417 of file Mesh.h.
Referenced by createDoubleShell(), and getOtherFaceGroupSite().
int Mesh::_otherMeshID protected
Definition at line 419 of file Mesh.h.
Referenced by createDoubleShell(), and getOtherMeshID().
const StorageSite* Mesh::_parentFaceGroupSite protected
Definition at line 416 of file Mesh.h.
Referenced by createDoubleShell(), createShell(), and getParentFaceGroupSite().
int Mesh::_parentMeshID protected
Definition at line 418 of file Mesh.h.
Referenced by createDoubleShell(), and getParentMeshID().
PeriodicFacePairs Mesh::_periodicFacePairs protected
Definition at line 423 of file Mesh.h.
Referenced by getPeriodicFacePairs().
GhostArrayMap Mesh::_recvCounts mutable protected
Definition at line 384 of file Mesh.h.
Referenced by addCRConn(), countCRConn(), createRowColSiteCRConn(), createScatterGatherCountsBuffer(), createScatterGatherIndicesBuffer(), getRecvCounts(), recvScatterGatherCountsBufferLocal(), and syncCounts().
GhostArrayMap Mesh::_recvIndices mutable protected
Definition at line 386 of file Mesh.h.
Referenced by addCRConn(), createRowColSiteCRConn(), createScatterGatherIndicesBuffer(), getRecvIndices(), recvScatterGatherIndicesBufferLocal(), and syncIndices().
shared_ptr< Array<int> > Mesh::_repeatNodes protected
Definition at line 395 of file Mesh.h.
Referenced by getUpdatedNodesCoordCoupling(), and setNodeRepeationArrayCoupling().
GhostArrayMap Mesh::_sendCounts mutable protected
Definition at line 383 of file Mesh.h.
Referenced by createScatterGatherCountsBuffer(), getSendCounts(), and syncCounts().
GhostArrayMap Mesh::_sendIndices mutable protected
Definition at line 385 of file Mesh.h.
Referenced by createScatterGatherIndicesBuffer(), getSendIndices(), and syncIndices().
enum { ... } Mesh::CellType
The documentation for this class was generated from the following files:
Mesh.h
Mesh.cpp