Memosa-FVM: pmode< T > Class Template Reference
pmode< T > Class Template Reference
#include <pmode.h>
Public Types
typedef pmode< T > Tmode
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef Vector< T_Scalar, 3 > Tvec
typedef shared_ptr< pmode< T > > Mode_ptr
typedef pair< T, int > Reflection
typedef shared_ptr< Reflection > Reflptr
typedef pair< Reflection,
Reflection > Refl_pair
typedef map< int, Refl_pair > Refl_Map
Public Member Functions
pmode (Tvec vg, T omega, T tau)
pmode ()
Tvec getv ()
T getcp ()
T gettau ()
T gettauN ()
T getomega ()
Tvec & getVRef ()
T & getTauRef ()
T & getTauNRef ()
T & getOmegaRef ()
T & getcpRef ()
Refl_Map & getreflmap ()
Refl_Map getreflmapValue ()
Refl_pair & getReflpair (int i)
void setIndex (int index)
int getIndex ()
Field & getfield ()
Field & geteShifted ()
Field & gete0field ()
Field & getInjected ()
Field & getresid ()
Field & getFASfield ()
void setTref (const T Tref)
T calce0 (T Tl)
T calce0tau (T Tl)
T calcde0taudT (T Tl)
T calcde0dT (T Tl)
Tmode & operator= (Tmode &o)
T getTref ()
void copyPmode (Tmode &inMode)
Private Member Functions
pmode (const pmode &)
Private Attributes
Tvec _vg
T _cp
T _tau
T _tauN
T _omega
Field _efield
Field _eShifted
Field _e0field
Field _injected
Field _residual
Field _FASCorrection
Refl_Map _reflections
int _index
T _Tref
Detailed Description
template<class T>
class pmode< T >
Definition at line 18 of file pmode.h.
Member Typedef Documentation
template<class T > typedef shared_ptr<pmode<T> > pmode< T >::Mode_ptr
Definition at line 26 of file pmode.h.
template<class T > typedef map<int,Refl_pair> pmode< T >::Refl_Map
Definition at line 30 of file pmode.h.
template<class T > typedef pair<Reflection,Reflection> pmode< T >::Refl_pair
Definition at line 29 of file pmode.h.
template<class T > typedef pair<T,int> pmode< T >::Reflection
Definition at line 27 of file pmode.h.
template<class T > typedef shared_ptr<Reflection> pmode< T >::Reflptr
Definition at line 28 of file pmode.h.
template<class T > typedef NumTypeTraits<T>::T_Scalar pmode< T >::T_Scalar
Definition at line 24 of file pmode.h.
template<class T > typedef pmode<T> pmode< T >::Tmode
Definition at line 23 of file pmode.h.
template<class T > typedef Vector<T_Scalar,3> pmode< T >::Tvec
Definition at line 25 of file pmode.h.
Constructor & Destructor Documentation
template<class T > pmode< T >::pmode (Tvec vg, T omega, T tau) inline
Definition at line 32 of file pmode.h.
                              :
   _vg(vg),
     _tau(tau),
     _omega(omega),
     _efield("edoubleprime"),
     _eShifted("eShifted"),
     _e0field("e0"),
     _injected("injected"),
     _residual("residual"),
     _FASCorrection("FASCorrection"),
     _reflections(),
     _index(),
     _Tref(299.)
       {}
template<class T > pmode< T >::pmode () inline
Definition at line 47 of file pmode.h.
         :
   _efield("edoubleprime"),
     _eShifted("eShifted"),
     _e0field("e0"),
     _injected("injected"),
     _residual("residual"),
     _FASCorrection("FASCorrection"),
     _reflections(),
     _index(),
     _Tref(299.)
       {};
template<class T > pmode< T >::pmode (const pmode< T > &) private
Member Function Documentation
template<class T > T pmode< T >::calcde0dT (T Tl) inline
Definition at line 126 of file pmode.h.
Referenced by Kspace< T >::calcBandTemp(), Kspace< T >::calcPhononTemp(), Kspace< T >::calcSpecificHeat(), COMETDiscretizer< T >::COMETCollision(), Kspace< T >::getde0taudT(), Kspace< T >::gete0(), Kspace< T >::gete0v(), Kspace< T >::getHollandConductivity(), Kspace< T >::getModewiseBallisticConductance(), Kspace< T >::getModewiseHollandConductivity(), and ScatteringKernel< T >::updateSource().
     {
     const T hbar=6.582119e-16;  // (eV s)
     const T kb=8.617343e-5;  // (eV/K)
     T e0kp;
     e0kp=kb*pow((hbar*_omega/kb/Tl),2)*exp(hbar*_omega/kb/Tl)/
     pow((exp(hbar*_omega/kb/Tl)-1),2);
     //e0kp=pow(Tl,-2)*hbar*_omega/kb*exp(hbar*_omega/kb/Tl)/
     // pow((exp(hbar*_omega/kb/Tl)-1),2);
     return e0kp;
     }
template<class T > T pmode< T >::calcde0taudT (T Tl) inline
Definition at line 112 of file pmode.h.
Referenced by Kspace< T >::gete0_tau().
     {
     const T hbar=6.582119e-16;  // (eV s)
     const T kb=8.617343e-5;  // (eV/K)
     T e0kp;
     e0kp=(kb/_tau)*pow((hbar*_omega/kb/Tl),2)*exp(hbar*_omega/kb/Tl)/
     pow((exp(hbar*_omega/kb/Tl)-1),2);
     //e0kp=pow(Tl,-2)/_tau*hbar*_omega/kb*exp(hbar*_omega/kb/Tl)/
     // pow((exp(hbar*_omega/kb/Tl)-1),2);
     return e0kp;
     }
template<class T > T pmode< T >::calce0 (T Tl) inline
Definition at line 88 of file pmode.h.
Referenced by PhononBoundary< X >::applyTemperatureWall(), COMETBoundary< T >::applyTemperatureWallCoarse(), COMETBoundary< T >::applyTemperatureWallFine(), Kspace< T >::calcBallisticInterface(), Kspace< T >::calcBandTemp(), DensityOfStates< T >::calcBinFlux(), Kspace< T >::calcDiffuseE(), Kspace< T >::calcPhononTemp(), COMETModel< T >::equilibrate(), Kspace< T >::FindBallisticHeatRate(), Kspace< T >::gete0(), Kspace< T >::gete0v(), Kspace< T >::getEquilibriumArray(), ScatteringKernel< T >::getTypeIIsource(), ScatteringKernel< T >::getTypeIsource(), PhononModel< T >::init(), COMETModel< T >::init(), COMETModel< T >::initCoarse(), ScatteringKernel< T >::IterateToEquilibrium(), COMETInterface< T >::makeDMMcoeffs(), COMETInterface< T >::makeEquilibriumArray(), COMETModel< T >::sete0(), DensityOfStates< T >::sumOutgoing(), PhononModel< T >::updatee0(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateGhostCoarse(), ScatteringKernel< T >::updateSource(), and ScatteringKernel< T >::updateSource2().
     {
     const T hbar=6.582119e-16;  // (eV s)
     const T kb=8.617343e-5;  // (eV/K)
     T e0kp;
     e0kp=hbar*_omega/(exp(hbar*_omega/kb/Tl)-1);
     //e0kp=1./(exp(hbar*_omega/kb/Tl)-1);
     //T eref=1./(exp(hbar*_omega/kb/300)-1);
     return e0kp;
     }
template<class T > T pmode< T >::calce0tau (T Tl) inline
Definition at line 100 of file pmode.h.
Referenced by Kspace< T >::gete0_tau().
     {
     const T hbar=6.582119e-16;  // (eV s)
     const T kb=8.617343e-5;  // (eV/K)
     T e0kp;
     e0kp=hbar*_omega/(exp(hbar*_omega/kb/Tl)-1)/_tau;
     //e0kp=1./(exp(hbar*_omega/kb/Tl)-1)/_tau;
     //T eref=1./(exp(hbar*_omega/kb/300)-1)/_tau;
     return e0kp;
     }
template<class T > void pmode< T >::copyPmode (Tmode & inMode) inline
Definition at line 216 of file pmode.h.
References pmode< T >::getcp(), pmode< T >::getIndex(), pmode< T >::getomega(), pmode< T >::getreflmap(), pmode< T >::gettau(), pmode< T >::getTref(), and pmode< T >::getv().
   {
     Tvec newVg=inMode.getv();
     T newCp=inMode.getcp();
     T newTau=inMode.gettau();
     T newOmega=inMode.getomega();
     Refl_Map& newMap=inMode.getreflmap();
     int newIndex=inMode.getIndex();
     T newTref=inMode.getTref();
     _vg=newVg;
     _cp=newCp;
     _tau=newTau;
     _omega=newOmega;
     _reflections=newMap;
     _index=newIndex;
     _Tref=newTref;
   }
template<class T > T pmode< T >::getcp () inline
Definition at line 60 of file pmode.h.
Referenced by pmode< T >::copyPmode(), and pmode< T >::operator=().
 {return _cp;}
template<class T > T& pmode< T >::getcpRef () inline
Definition at line 68 of file pmode.h.
Referenced by Kspace< T >::makeDegenerate(), Kspace< T >::setCp(), and Kspace< T >::setCpNonGray().
 {return _cp;}
template<class T > Field& pmode< T >::gete0field () inline
Definition at line 76 of file pmode.h.
Referenced by PhononModel< T >::init(), PhononModel< T >::linearizePhononModel(), and PhononModel< T >::updatee0().
 {return _e0field;}
template<class T > Field& pmode< T >::geteShifted () inline
Definition at line 75 of file pmode.h.
Referenced by COMETDiscretizer< T >::COMETShifted(), and COMETDiscretizer< T >::updateeShifted().
 {return _eShifted;}
template<class T > Field& pmode< T >::getFASfield () inline
Definition at line 79 of file pmode.h.
Referenced by COMETInterface< T >::addFAS().
 {return _FASCorrection;}
template<class T > Field& pmode< T >::getfield () inline
Definition at line 74 of file pmode.h.
Referenced by PhononModel< T >::advance(), PhononInterface< X >::applyInterfaceCondition(), PhononBoundary< X >::applyReflectingWall(), PhononBoundary< X >::applyTemperatureWall(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETShifted(), COMETModel< T >::equilibrate(), COMETModel< T >::getValueArray(), PhononModel< T >::HeatFluxIntegral(), PhononModel< T >::init(), PhononModel< T >::initPhononModelLinearization(), PhononModel< T >::linearizePhononModel(), COMETDiscretizer< T >::updateeShifted(), PhononModel< T >::updateHeatFlux(), PhononModel< T >::updateTL(), and COMETInterface< T >::ZeroGhost().
 {return _efield;}
template<class T > int pmode< T >::getIndex () inline
Definition at line 73 of file pmode.h.
Referenced by COMETInterface< T >::addFAS(), COMETBoundary< T >::applyTemperatureWallCoarse(), COMETBoundary< T >::applyTemperatureWallFine(), COMETModel< T >::binwiseHeatFluxIntegral(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), COMETModel< T >::calcBandTemps(), COMETModel< T >::calcModeFlux(), COMETModel< T >::calcModeTemps(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETFullScatt(), COMETDiscretizer< T >::COMETShifted(), pmode< T >::copyPmode(), COMETDiscretizer< T >::Distribute(), COMETInterface< T >::findWallTemp(), COMETDiscretizer< T >::gatherResid(), Kspace< T >::getEquilibriumArray(), Kspace< T >::getReflectionArray(), Kspace< T >::getVelocities(), Kspace< T >::Kspace(), COMETInterface< T >::makeDMMcoeffs(), COMETInterface< T >::makeEquilibriumArray(), COMETDiscretizer< T >::makeValueArray(), COMETModel< T >::modewiseHeatFluxIntegral(), COMETDiscretizer< T >::ScatterPhonons(), COMETDiscretizer< T >::updateGhostCoarse(), and COMETDiscretizer< T >::updateGhostFine().
 {return _index;}
template<class T > Field& pmode< T >::getInjected () inline
Definition at line 77 of file pmode.h.
 {return _injected;}
template<class T > T pmode< T >::getomega () inline
Definition at line 63 of file pmode.h.
Referenced by DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::binMode(), Kspace< T >::calcBallisticInterface(), Kspace< T >::calcDiffuseE(), pmode< T >::copyPmode(), Kspace< T >::Kspace(), Kspace< T >::makeFreqArray(), DensityOfStates< T >::mergeBins(), pmode< T >::operator=(), and Kspace< T >::setCpNonGray().
 {return _omega;}
template<class T > T& pmode< T >::getOmegaRef () inline
Definition at line 67 of file pmode.h.
 {return _omega;}
template<class T > Refl_Map& pmode< T >::getreflmap () inline
Definition at line 69 of file pmode.h.
Referenced by pmode< T >::copyPmode(), PhononModel< T >::init(), COMETModel< T >::init(), and pmode< T >::operator=().
 {return _reflections;}
template<class T > Refl_Map pmode< T >::getreflmapValue () inline
Definition at line 70 of file pmode.h.
 {return _reflections;}
template<class T > Refl_pair& pmode< T >::getReflpair (int i) inline
Definition at line 71 of file pmode.h.
Referenced by PhononBoundary< X >::applyReflectingWall(), COMETDiscretizer< T >::COMETConvection(), Kspace< T >::getReflectionArray(), COMETDiscretizer< T >::updateGhostCoarse(), and COMETDiscretizer< T >::updateGhostFine().
 {return _reflections[i];}
template<class T > Field& pmode< T >::getresid () inline
Definition at line 78 of file pmode.h.
Referenced by COMETDiscretizer< T >::gatherResid(), and PhononModel< T >::init().
 {return _residual;}
template<class T > T pmode< T >::gettau () inline
Definition at line 61 of file pmode.h.
Referenced by Kspace< T >::calcTauTot(), pmode< T >::copyPmode(), Kspace< T >::findKnStats(), Kspace< T >::getHollandConductivity(), Kspace< T >::getModewiseHollandConductivity(), Kspace< T >::getRTAsources(), Kspace< T >::getTauArrayPy(), COMETModel< T >::init(), COMETModel< T >::initCoarse(), ScatteringKernel< T >::IterateToEquilibrium(), PhononModel< T >::linearizePhononModel(), pmode< T >::operator=(), ScatteringKernel< T >::updateSource(), ScatteringKernel< T >::updateSource2(), and PhononModel< T >::updateTL().
 {return _tau;}
template<class T > T pmode< T >::gettauN () inline
Definition at line 62 of file pmode.h.
Referenced by COMETDiscretizer< T >::COMETShifted().
 {return _tauN;}
template<class T > T& pmode< T >::getTauNRef () inline
Definition at line 66 of file pmode.h.
 {return _tauN;}
template<class T > T& pmode< T >::getTauRef () inline
Definition at line 65 of file pmode.h.
 {return _tau;}
template<class T > T pmode< T >::getTref () inline
Definition at line 214 of file pmode.h.
Referenced by pmode< T >::copyPmode().
 {return _Tref;}
template<class T > Tvec pmode< T >::getv () inline
Definition at line 59 of file pmode.h.
Referenced by PhononInterface< X >::applyInterfaceCondition(), PhononBoundary< X >::applyReflectingWall(), PhononBoundary< X >::applyTemperatureWall(), COMETBoundary< T >::applyTemperatureWallCoarse(), COMETBoundary< T >::applyTemperatureWallFine(), COMETModel< T >::binwiseHeatFluxIntegral(), Kspace< T >::calcBallisticInterface(), COMETModel< T >::calcBandFlux(), DensityOfStates< T >::calcBinFlux(), Kspace< T >::calcDiffuseE(), COMETModel< T >::calcModeFlux(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), pmode< T >::copyPmode(), Kspace< T >::FindBallisticHeatRate(), Kspace< T >::findKnStats(), Kspace< T >::findSpecs(), COMETInterface< T >::findWallTemp(), Kspace< T >::gete0(), Kspace< T >::gete0v(), Kspace< T >::getHollandConductivity(), Kspace< T >::getModewiseBallisticConductance(), Kspace< T >::getModewiseHollandConductivity(), Kspace< T >::getVelocities(), PhononModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), PhononModel< T >::init(), COMETModel< T >::init(), PhononModel< T >::linearizePhononModel(), COMETInterface< T >::makeDMMcoeffs(), COMETModel< T >::modewiseHeatFluxIntegral(), pmode< T >::operator=(), COMETDiscretizer< T >::ScatterPhonons(), DensityOfStates< T >::sumOutgoing(), COMETDiscretizer< T >::updateGhostCoarse(), COMETDiscretizer< T >::updateGhostFine(), and PhononModel< T >::updateHeatFlux().
 {return _vg;}
template<class T > Tvec& pmode< T >::getVRef () inline
Definition at line 64 of file pmode.h.
 {return _vg;}
template<class T > Tmode& pmode< T >::operator= (Tmode & o) inline
Definition at line 203 of file pmode.h.
References pmode< T >::getcp(), pmode< T >::getomega(), pmode< T >::getreflmap(), pmode< T >::gettau(), and pmode< T >::getv().
     {
       _vg=o.getv();
       _cp=o.getcp();
       _tau=o.gettau();
       _omega=o.getomega();
       _reflections=o.getreflmap();
       return *this;
     }
template<class T > void pmode< T >::setIndex (int index) inline
Definition at line 72 of file pmode.h.
 {_index=index;}
template<class T > void pmode< T >::setTref (const T Tref) inline
Definition at line 80 of file pmode.h.
Referenced by Kspace< T >::setTref().
 {_Tref=Tref;}
Member Data Documentation
template<class T > T pmode< T >::_cp private
Definition at line 242 of file pmode.h.
template<class T > Field pmode< T >::_e0field private
Definition at line 260 of file pmode.h.
template<class T > Field pmode< T >::_efield private
Definition at line 254 of file pmode.h.
template<class T > Field pmode< T >::_eShifted private
Definition at line 257 of file pmode.h.
template<class T > Field pmode< T >::_FASCorrection private
Definition at line 269 of file pmode.h.
template<class T > int pmode< T >::_index private
Definition at line 275 of file pmode.h.
template<class T > Field pmode< T >::_injected private
Definition at line 263 of file pmode.h.
template<class T > T pmode< T >::_omega private
Definition at line 251 of file pmode.h.
template<class T > Refl_Map pmode< T >::_reflections private
Definition at line 272 of file pmode.h.
template<class T > Field pmode< T >::_residual private
Definition at line 266 of file pmode.h.
template<class T > T pmode< T >::_tau private
Definition at line 245 of file pmode.h.
template<class T > T pmode< T >::_tauN private
Definition at line 248 of file pmode.h.
template<class T > T pmode< T >::_Tref private
Definition at line 277 of file pmode.h.
template<class T > Tvec pmode< T >::_vg private
Definition at line 239 of file pmode.h.
The documentation for this class was generated from the following file:
pmode.h