Memosa-FVM: GenericKineticIBDiscretization< X, Diag, OffDiag > Class Template Reference
GenericKineticIBDiscretization< X, Diag, OffDiag > Class Template Reference
#include <GenericKineticIBDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::OffDiagArray OffDiagArray
typedef Array< int > IntArray
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
GenericKineticIBDiscretization (const MeshList &meshes, const GeomFields &geomFields, Field &varField, const double cx, const double cy, const double cz, MacroFields &macroFields)
void discretize (const Mesh &mesh, MultiFieldMatrix &matrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
Field & _varField
const double _cx
const double _cy
const double _cz
MacroFields & _macroFields
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class GenericKineticIBDiscretization< X, Diag, OffDiag >
Definition at line 24 of file GenericKineticIBDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler GenericKineticIBDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 31 of file GenericKineticIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> GenericKineticIBDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 30 of file GenericKineticIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray GenericKineticIBDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 32 of file GenericKineticIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<int> GenericKineticIBDiscretization< X, Diag, OffDiag >::IntArray
Definition at line 35 of file GenericKineticIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::OffDiagArray GenericKineticIBDiscretization< X, Diag, OffDiag >::OffDiagArray
Definition at line 33 of file GenericKineticIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar GenericKineticIBDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 28 of file GenericKineticIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> GenericKineticIBDiscretization< X, Diag, OffDiag >::TArray
Definition at line 37 of file GenericKineticIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> GenericKineticIBDiscretization< X, Diag, OffDiag >::VectorT3
Definition at line 38 of file GenericKineticIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> GenericKineticIBDiscretization< X, Diag, OffDiag >::VectorT3Array
Definition at line 39 of file GenericKineticIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> GenericKineticIBDiscretization< X, Diag, OffDiag >::XArray
Definition at line 36 of file GenericKineticIBDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > GenericKineticIBDiscretization< X, Diag, OffDiag >::GenericKineticIBDiscretization (const MeshList & meshes, const GeomFields & geomFields, Field & varField, const double cx, const double cy, const double cz, MacroFields & macroFields) inline
Definition at line 41 of file GenericKineticIBDiscretization.h.
                                                             :
   Discretization(meshes),
     _geomFields(geomFields),
     _varField(varField),
     _cx(cx),
     _cy(cy),
     _cz(cz),
     _macroFields(macroFields)
 {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & matrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 57 of file GenericKineticIBDiscretization.h.
References GenericKineticIBDiscretization< X, Diag, OffDiag >::_cx, GenericKineticIBDiscretization< X, Diag, OffDiag >::_cy, GenericKineticIBDiscretization< X, Diag, OffDiag >::_cz, GenericKineticIBDiscretization< X, Diag, OffDiag >::_geomFields, GenericKineticIBDiscretization< X, Diag, OffDiag >::_macroFields, GenericKineticIBDiscretization< X, Diag, OffDiag >::_varField, GeomFields::area, GeomFields::areaMag, Mesh::getAllFaceCells(), Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), StorageSite::getCountLevel1(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), Mesh::getFaces(), Mesh::getIBFaces(), MultiFieldMatrix::getMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), GeomFields::ibFaceIndex, GeomFields::ibType, Mesh::IBTYPE_BOUNDARY, Mesh::IBTYPE_FLUID, CRMatrix< T_Diag, T_OffDiag, X >::setDirichlet(), MacroFields::velocity, and Array< T >::zero().
   {
     const StorageSite& ibFaces = mesh.getIBFaces();
      if (ibFaces.getCount() == 0)
       return;
     VectorT3Array& v = dynamic_cast<VectorT3Array&>(_macroFields.velocity[ibFaces]);
     const StorageSite& cells = mesh.getCells();
     const StorageSite& faces = mesh.getFaces();
     const CRConnectivity& faceCells = mesh.getAllFaceCells();
     const MultiField::ArrayIndex xIndex(&_varField,&cells);
     CCMatrix& dRdX = dynamic_cast<CCMatrix&>(matrix.getMatrix(xIndex,xIndex));
     CCAssembler& assembler = dRdX.getPairWiseAssembler(faceCells);
     DiagArray& dRdXDiag=dRdX.getDiag();
     XArray& xcell =
       dynamic_cast<XArray&> (xField[xIndex]);
     XArray& varcell =
       dynamic_cast<XArray&> (_varField[cells]);
     XArray& rCell = dynamic_cast<XArray&>(rField[xIndex]);
     const XArray& xib =
       dynamic_cast<const XArray&>(_varField[mesh.getIBFaces()]);
     const IntArray& ibType = dynamic_cast<const IntArray&>(_geomFields.ibType[cells]);
    const IntArray& ibFaceIndex = dynamic_cast<const IntArray&>(_geomFields.ibFaceIndex[faces]);
    const Field& areaMagField = _geomFields.areaMag;
    const XArray& faceAreaMag = dynamic_cast<const XArray&>(areaMagField[faces]);
    const Field& areaField = _geomFields.area;
    const VectorT3Array& faceArea=dynamic_cast<const VectorT3Array&>(areaField[faces]);
     // used for computing the average value in IBTYPE_BOUNDARY cells.
     // we can't use the xcell storage during the loop below since a
     // cell may have more than one ib face and the current value of
     // x in the cell is required to correctly impose the dirichlet
     // condition. so we accumulate the boundary cell value and counts
     // in the following arrays and after all the faces have been
     // visited, overwrite any boundary cell values with the average of
     // all the ib faces
     const int nCells = cells.getCountLevel1();
     XArray xB(nCells);
     Array<int> wB(nCells);
     xB.zero();
     wB.zero();
     const int nFaces = faces.getCount();
     for(int f=0; f<nFaces; f++)
     {
         const int c0 = faceCells(f,0);
         const int c1 = faceCells(f,1);
         if (((ibType[c0] == Mesh::IBTYPE_FLUID) && (ibType[c1] == Mesh::IBTYPE_BOUNDARY)) ||
             ((ibType[c1] == Mesh::IBTYPE_FLUID) && (ibType[c0] == Mesh::IBTYPE_BOUNDARY)))
         {
             // this is an iBFace, determine which cell is interior and which boundary
             const int ibFace = ibFaceIndex[f];
             if (ibFace < 0)
               throw CException("invalid ib face index");
             const X& xface = xib[ibFace];
             const X uwall = v[ibFace][0];
             const X vwall = v[ibFace][1];
             const X wwall = v[ibFace][2];
             if (ibType[c0] == Mesh::IBTYPE_FLUID)
             {
                 const VectorT3 en = faceArea[f]/faceAreaMag[f];
                 const X c_dot_en = _cx*en[0]+_cy*en[1]+_cz*en[2];
                 const X wallv_dot_en = uwall*en[0]+vwall*en[1]+wwall*en[2];
                 if(c_dot_en - wallv_dot_en <0 ){
                   rCell[c0] += assembler.getCoeff01(f)*(xface-varcell[c1]);
                   rCell[c1] = NumTypeTraits<X>::getZero();
                   assembler.getCoeff01(f) = OffDiag(0);
                   dRdX.setDirichlet(c1);
                   xB[c1] += xface;
                   wB[c1]++;
                 }
             }
             else
               {
                 const VectorT3 en = faceArea[f]/faceAreaMag[f];
                 const X c_dot_en = _cx*en[0]+_cy*en[1]+_cz*en[2];
                 const X wallv_dot_en = uwall*en[0]+vwall*en[1]+wwall*en[2];
                 if(c_dot_en - wallv_dot_en> 0){
                   rCell[c1] += assembler.getCoeff10(f)*(xface-varcell[c0]);
                   rCell[c0] = NumTypeTraits<X>::getZero();
                   assembler.getCoeff10(f) = OffDiag(0);
                   dRdX.setDirichlet(c0);
                   xB[c0] += xface;
                   wB[c0]++;
                 }
               }
         }
         else if ((ibType[c0] == Mesh::IBTYPE_FLUID) &&
             (ibType[c1] == Mesh::IBTYPE_FLUID))
         {
             // leave as  is
         }
         else
         {
             // setup to get zero corrections
             rCell[c0] = NumTypeTraits<X>::getZero();
             rCell[c1] = NumTypeTraits<X>::getZero();
             assembler.getCoeff01(f)=NumTypeTraits<OffDiag>::getZero();
             dRdXDiag[c0]=NumTypeTraits<Diag>::getNegativeUnity();
             assembler.getCoeff10(f)=NumTypeTraits<OffDiag>::getZero();
             dRdXDiag[c1]=NumTypeTraits<Diag>::getNegativeUnity();
         }
     }
     // set the phi for boundary cells as average of the ib face values
     for(int c=0; c<nCells; c++)
     {
         if (wB[c] > 0)
           varcell[c] =  xB[c] / T_Scalar(wB[c]);
     }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const double GenericKineticIBDiscretization< X, Diag, OffDiag >::_cx private
Definition at line 186 of file GenericKineticIBDiscretization.h.
Referenced by GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const double GenericKineticIBDiscretization< X, Diag, OffDiag >::_cy private
Definition at line 187 of file GenericKineticIBDiscretization.h.
Referenced by GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const double GenericKineticIBDiscretization< X, Diag, OffDiag >::_cz private
Definition at line 188 of file GenericKineticIBDiscretization.h.
Referenced by GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& GenericKineticIBDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 184 of file GenericKineticIBDiscretization.h.
Referenced by GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > MacroFields& GenericKineticIBDiscretization< X, Diag, OffDiag >::_macroFields private
Definition at line 189 of file GenericKineticIBDiscretization.h.
Referenced by GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > Field& GenericKineticIBDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 185 of file GenericKineticIBDiscretization.h.
Referenced by GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
GenericKineticIBDiscretization.h