Memosa-FVM: Kspace< T > Class Template Reference
Kspace< T > Class Template Reference
#include <Kspace.h>
Public Types
typedef Kspace< T > Tkspace
typedef vector< Tkspace * > TkspList
typedef Array< T > TArray
typedef shared_ptr< TArray > TArrPtr
typedef Vector< T, 3 > Tvec
typedef Array< Tvec > TvecArray
typedef Array< int > IntArray
typedef pmode< T > Tmode
typedef shared_ptr< Tmode > Tmodeptr
typedef vector< Tmodeptr > Modes
typedef kvol< T > Tkvol
typedef shared_ptr< Tkvol > Kvolptr
typedef vector< Kvolptr > Volvec
typedef SquareTensor< T, 3 > T3Tensor
typedef Tmode::Reflection Reflection
typedef Tmode::Reflptr Reflptr
typedef Tmode::Refl_pair Refl_pair
typedef Tmode::Refl_Map Refl_Map
typedef pair< TArray *, TArray * > BinAndTrans
typedef map< Tkspace *, pair
< TArray *, TArray * > > TransmissionMap
typedef
Tkspace::TransmissionMap::iterator TransIt
typedef pair< const
StorageSite *, const
StorageSite * > EntryIndex
typedef map< EntryIndex,
shared_ptr< ArrayBase > > GhostArrayMap
Public Member Functions
Kspace (T a, T tau, T vgmag, T omega, int ntheta, int nphi, const bool full)
Kspace ()
void setCp (const T cp)
void setCpNonGray (const T Tl)
void makeDegenerate (const int m)
void makeFreqArray ()
Kspace (const char *filename, const int dimension)
Kspace (const char *filename, const int dimension, const bool normal)
Tkvol & getkvol (int n) const
int getlength () const
T gethbar ()
int gettotmodes ()
T calcDK3 ()
T getDK3 () const
T calcTauTot ()
void NewtonSolve (T &guess, const T e_sum)
void calcTemp (T &guess, const T e_sum, const Tvec An)
T calcLatTemp (const int c)
void calcTemp (T &guess, const T e_sum)
T calcModeTemp (T guess, const T e_sum, const T m)
T calcPhononTemp (const int c, const int index, T guess)
void gete0_tau (T &Tguess, T &e0tau, T &de0taudT)
void gete0 (const T Tguess, T &e0, T &de0dT, const Tvec An)
void gete0v (const T Tguess, T &e0, T &de0dT, const Tvec An)
void gete0 (const T Tguess, T &e0, T &de0dT)
void gete0 (const T Tguess, T &e0, T &de0dT, const T m)
T getde0taudT (const int c, T Tl)
T calcSpecificHeat (T Tl)
T calcSpecificHeat (T Tl, const int m)
T findKnStats (const T length)
void findSpecs (const Tvec n, const int m, const int k, Refl_pair &refls)
void CopyKspace (Tkspace &copyFromKspace)
T FindBallisticHeatRate (const Tvec An, const T T1, const T T2)
ArrayBase * getVelocities ()
void getVelocities (TvecArray &v)
ArrayBase * getVelocities (const int M)
ArrayBase * getReflectionArray (const Mesh &mesh, const int FgId)
ArrayBase * getHollandConductivity (const T Tl)
ArrayBase * getModewiseHollandConductivity (const T Tl)
ArrayBase * getModewiseBallisticConductance (const T Tl)
void outerProduct (const Tvec &v1, const Tvec &v2, T3Tensor &out)
void setTransmission (Tkspace &toKspace, ArrayBase *freqBins, ArrayBase *transArray)
T findTransmission (Tkspace &toKspace, const T freq)
TArray & getTransArray (Tkspace &toKspace)
T calcBallisticInterface (Tkspace &kspace1, const Tvec &An, const T T0, const T T1)
T calcBandTemp (const T guess, const T eSum, const IntArray &kpts, const IntArray &mpts)
T calcDiffuseE (Tkspace &kspace1, const Tvec &An, const T T0, const T T1)
void giveTransmissions ()
void setDOS (DensityOfStates< T > &DOS)
void setScattKernel (ScatteringKernel< T > &Sk)
DensityOfStates< T > * getDOSptr ()
void setCoarseKspace (Tkspace *cK)
Tkspace * getCoarseKspace ()
TransmissionMap & getTransMap ()
T & gete (const int cell, const int count)
T & gete0 (const int cell, const int count)
T & getInj (const int cell, const int count)
T & getRes (const int cell, const int count)
T & getFas (const int cell, const int count)
int getGlobalIndex (const int cell, const int count)
void seteArray (TArrPtr ePtr)
void sete0Array (TArrPtr e0Ptr)
void setSourceArray (TArrPtr SPtr)
void setInjArray (TArrPtr InjPtr)
void setResArray (TArrPtr ResPtr)
void setFASArray (TArrPtr FASPtr)
void setTauArray (TArrPtr TauPtr)
TArray & geteArray ()
TArray & gete0Array ()
TArray & getSourceArray ()
TArray & getInjArray ()
TArray & getResArray ()
TArray & getFASArray ()
TArray & getTauArray ()
const T getTau (const int index)
void geteCellVals (const int c, TArray &o)
void gete0CellVals (const int c, TArray &o)
void getnCellVals (const int c, TArray &o)
void seteCellVals (const int c, const TArray &o)
void setResidCell (const int c, const TArray &o)
void addFAS (const int c, TArray &Bvec)
void addFASint (const int c, TArray &Bvec)
void makeFAS ()
void syncLocal (const StorageSite &site)
void syncScatter (const StorageSite &site)
void createSyncGather (const StorageSite &site)
void syncGather (const StorageSite &site)
int get_request_size (const StorageSite &site)
void getEquilibriumArray (TArray &vals, const T Tl)
TArray & getFreqArray ()
void getSourceTerm (const int c, TArray &s, TArray &ds)
void ScatterPhonons (const int c, const int totIts, TArray &C, TArray &B, const TArray &V, TArray &newE, const T cv)
void setRelTimeFunction (const T A, const T B, const T C)
void updateTau (const int c, const T Tl)
ArrayBase * getRTAsources (const int c)
ArrayBase * getFullsources (const int c)
ArrayBase * getIsources (const int c, const bool correct)
ArrayBase * getIIsources (const int c, const bool correct)
ArrayBase * getSourceDeriv (const int c)
ArrayBase * getWaveVectors ()
ArrayBase * geteCellValsPy (const int c)
ArrayBase * gete0CellVars (const int c)
ArrayBase * gete0CellValsPy (const T Tl)
ArrayBase * getFreqArrayPy ()
ArrayBase * getTauArrayPy ()
void weightArray (TArray &e)
void weightArray (ArrayBase *ep)
ArrayBase * getEmptyArray (const int length)
void setTref (const T Tref)
ArrayBase * getSourceArrayPy ()
void addSource (const int c, TArray &BVec, const T cv)
Private Member Functions
Kspace (const Kspace &)
Private Attributes
int _length
Volvec _Kmesh
T _totvol
TransmissionMap _transMap
DensityOfStates< T > * _DOS
ScatteringKernel< T > * _ScattKernel
Tkspace * _coarseKspace
TArrPtr _e
TArrPtr _e0
TArrPtr _Source
TArrPtr _injected
TArrPtr _residual
TArrPtr _FASCorrection
TArrPtr _Tau
GhostArrayMap _ghostArrays
TArray _freqArray
RelTimeFun< T > _relFun
Detailed Description
template<class T>
class Kspace< T >
Definition at line 28 of file Kspace.h.
Member Typedef Documentation
template<class T> typedef pair<TArray*, TArray*> Kspace< T >::BinAndTrans
Definition at line 51 of file Kspace.h.
template<class T> typedef pair<const StorageSite*, const StorageSite*> Kspace< T >::EntryIndex
Definition at line 54 of file Kspace.h.
template<class T> typedef map<EntryIndex, shared_ptr<ArrayBase> > Kspace< T >::GhostArrayMap
Definition at line 55 of file Kspace.h.
template<class T> typedef Array<int> Kspace< T >::IntArray
Definition at line 39 of file Kspace.h.
template<class T> typedef shared_ptr<Tkvol> Kspace< T >::Kvolptr
Definition at line 44 of file Kspace.h.
template<class T> typedef vector<Tmodeptr> Kspace< T >::Modes
Definition at line 42 of file Kspace.h.
template<class T> typedef Tmode::Refl_Map Kspace< T >::Refl_Map
Definition at line 50 of file Kspace.h.
template<class T> typedef Tmode::Refl_pair Kspace< T >::Refl_pair
Definition at line 49 of file Kspace.h.
template<class T> typedef Tmode::Reflection Kspace< T >::Reflection
Definition at line 47 of file Kspace.h.
template<class T> typedef Tmode::Reflptr Kspace< T >::Reflptr
Definition at line 48 of file Kspace.h.
template<class T> typedef SquareTensor<T,3> Kspace< T >::T3Tensor
Definition at line 46 of file Kspace.h.
template<class T> typedef Array<T> Kspace< T >::TArray
Definition at line 35 of file Kspace.h.
template<class T> typedef shared_ptr<TArray> Kspace< T >::TArrPtr
Definition at line 36 of file Kspace.h.
template<class T> typedef Kspace<T> Kspace< T >::Tkspace
Definition at line 33 of file Kspace.h.
template<class T> typedef vector<Tkspace*> Kspace< T >::TkspList
Definition at line 34 of file Kspace.h.
template<class T> typedef kvol<T> Kspace< T >::Tkvol
Definition at line 43 of file Kspace.h.
template<class T> typedef pmode<T> Kspace< T >::Tmode
Definition at line 40 of file Kspace.h.
template<class T> typedef shared_ptr<Tmode> Kspace< T >::Tmodeptr
Definition at line 41 of file Kspace.h.
template<class T> typedef Tkspace::TransmissionMap::iterator Kspace< T >::TransIt
Definition at line 53 of file Kspace.h.
template<class T> typedef map<Tkspace*,pair<TArray*,TArray*> > Kspace< T >::TransmissionMap
Definition at line 52 of file Kspace.h.
template<class T> typedef Vector<T,3> Kspace< T >::Tvec
Definition at line 37 of file Kspace.h.
template<class T> typedef Array<Tvec> Kspace< T >::TvecArray
Definition at line 38 of file Kspace.h.
template<class T> typedef vector<Kvolptr> Kspace< T >::Volvec
Definition at line 45 of file Kspace.h.
Constructor & Destructor Documentation
template<class T> Kspace< T >::Kspace (T a, T tau, T vgmag, T omega, int ntheta, int nphi, const bool full) inline
Definition at line 57 of file Kspace.h.
References Kspace< T >::_freqArray, Kspace< T >::_Kmesh, Kspace< T >::_totvol, Kspace< T >::makeFreqArray(), Array< T >::resize(), and sin().
                                                                              :
   _length(ntheta*nphi),
     _Kmesh(),
     _totvol(0.),
     _freqArray(0)
       { //makes gray, isotropic kspace
         const long double pi=3.141592653589793238462643383279502884197169399;
         //long double sumX(0);
         //long double sumY(0);
         //long double sumZ(0);
         long double theta;
         long double phi;
         long double dtheta=pi/T(ntheta)/2.;
         long double dphi=2.*pi/T(nphi);
         long double dk3;
         const long double Kmax=pi/a;
         const long double Ktot=pi*pow(Kmax,3.)*4./3./pow((2.*pi),3.);
         Tvec vg;
         int count=1;
         T W=2.;
         if(full)
           {
             W=1.;
             dtheta*=2;
           }
         _freqArray.resize(ntheta*nphi);
         _freqArray=omega;
         for(int t=0;t<ntheta;t++)
           {
             theta=dtheta*(T(t)+.5);
             for(int p=0;p<nphi;p++)
               {
                 phi=dphi*(T(p)+.5);
                 const T xyFac=dtheta-cos(2*theta)*sin(dtheta);
                 dk3=(sin(theta)*sin(dtheta/2.)*(dphi/pi/2.))*Ktot*W;
                 vg[0]=vgmag*xyFac*sin(phi)*sin(dphi/2.)/dk3*pow(Kmax,3.)/3./pow((2.*pi),3.)*W;
                 vg[1]=vgmag*xyFac*cos(phi)*sin(dphi/2.)/dk3*pow(Kmax,3.)/3./pow((2.*pi),3.)*W;
                 vg[2]=vgmag*dphi/2.*sin(2*theta)*sin(dphi)/dk3*pow(Kmax,3.)/3./pow((2.*pi),3.)*W;
                 //vg[0]=vgmag*sin(theta)*sin(phi);
                 //vg[1]=vgmag*sin(theta)*cos(phi);
                 //vg[2]=vgmag*cos(theta);
                 Tmodeptr modeptr=shared_ptr<Tmode>(new Tmode(vg,omega,tau));
                 modeptr->setIndex(count);
                 count++;
                 Kvolptr volptr=shared_ptr<Tkvol>(new Tkvol(modeptr,dk3));
                 volptr->setkvec(vg);
                 _Kmesh.push_back(volptr);
                 _totvol+=dk3;
               }
           }
         makeFreqArray();
       }
template<class T> Kspace< T >::Kspace () inline
Definition at line 113 of file Kspace.h.
          :
   _freqArray(0),
     _coarseKspace(NULL)
       {}
template<class T> Kspace< T >::Kspace (const char * filename, const int dimension) inline
Definition at line 181 of file Kspace.h.
References Kspace< T >::_Kmesh, Kspace< T >::_length, Kspace< T >::calcDK3(), and Kspace< T >::makeFreqArray().
                                                  :
   _freqArray(0),
     _coarseKspace(NULL)
       {
         ifstream fp_in;
         fp_in.open(filename,ifstream::in);
         int modeNum;
         int kPoints;
         int directions;
         cout<<endl<<"Reading BZ file"<<endl;
         fp_in>>modeNum;
         cout<<"Number of Polarizations: "<<modeNum<<endl;
         fp_in>>kPoints;
         cout<<"Number of Wave Vector Magnitude Discretizations: "<<kPoints<<endl;
         fp_in>>directions;
         cout<<"Number of Angular Discretizations: "<<directions<<endl;
         cout<<"Total Number of K-Space Points: "<<modeNum*kPoints*directions<<endl;
         _length=kPoints*directions;
         int count=1;
         for(int k=0;k<_length;k++)
           {
             Kvolptr volptr=shared_ptr<Tkvol>(new Tkvol(modeNum));
             Modes& modes=volptr->getModes();
             for(int m=0;m<modeNum;m++)
               {
                 T Tdummy(0.);
                 T omega(0.);
                 T tau(0.);
                 Tvec vg;
                 Tvec K;
                 T weight(0.);
                 Tmodeptr modeptr=shared_ptr<Tmode>(new Tmode());
                 fp_in>>Tdummy;
                 fp_in>>weight;
                 fp_in>>omega;
                 fp_in>>Tdummy;
                 K[0]=Tdummy;
                 if(dimension==2)
                   {
                     fp_in>>Tdummy;
                     K[1]=Tdummy;
                     K[2]=0.;
                   }
                 if(dimension==3)
                   {
                     fp_in>>Tdummy;
                     K[1]=Tdummy;
                     fp_in>>Tdummy;
                     K[2]=Tdummy;
                   }
                 fp_in>>Tdummy;
                 vg[0]=Tdummy;
                 if(dimension==2)
                   {
                     fp_in>>Tdummy;
                     vg[1]=Tdummy;
                     vg[2]=0.;
                   }
                 if(dimension==3)
                   {
                     fp_in>>Tdummy;
                     vg[1]=Tdummy;
                     fp_in>>Tdummy;
                     vg[2]=Tdummy;
                   }
                 fp_in>>tau;
                 modeptr->getVRef()=vg;
                 modeptr->getTauRef()=tau;
                 modeptr->getOmegaRef()=omega;
                 modeptr->setIndex(count);
                 count++;
                 modes.push_back(modeptr);
                 volptr->setkvec(K);
                 volptr->setdk3(weight);
               }
             _Kmesh.push_back(volptr);
           }
         fp_in.close();
         calcDK3();
         makeFreqArray();
       }
template<class T> Kspace< T >::Kspace (const char * filename, const int dimension, const bool normal) inline
Definition at line 276 of file Kspace.h.
References Kspace< T >::_freqArray, Kspace< T >::_Kmesh, Kspace< T >::_length, Kspace< T >::calcDK3(), pmode< T >::getIndex(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getomega(), Kspace< T >::gettotmodes(), and Array< T >::resize().
                                                                    :
   _freqArray(0),
     _coarseKspace(NULL)
       {
         ifstream fp_in;
         fp_in.open(filename,ifstream::in);
         int modeNum;
         int kPoints;
         int directions;
         cout<<endl<<"Using Shifted Normal Scattering"<<endl;
         cout<<"Reading BZ file"<<endl;
         fp_in>>modeNum;
         cout<<"Number of Polarizations: "<<modeNum<<endl;
         fp_in>>kPoints;
         cout<<"Number of Wave Vector Magnitude Discretizations: "<<kPoints<<endl;
         fp_in>>directions;
         cout<<"Number of Angular Discretizations: "<<directions<<endl;
         cout<<"Total Number of K-Space Points: "<<modeNum*kPoints*directions<<endl;
         _length=kPoints*directions;
         int count=1;
         for(int k=0;k<_length;k++)
           {
             Kvolptr volptr=shared_ptr<Tkvol>(new Tkvol(modeNum));
             Modes& modes=volptr->getModes();
             for(int m=0;m<modeNum;m++)
               {
                 T Tdummy(0.);
                 T omega(0.);
                 T tau(0.);
                 T tauN(0.);
                 Tvec vg;
                 Tvec K;
                 T weight(0.);
                 Tmodeptr modeptr=shared_ptr<Tmode>(new Tmode());
                 fp_in>>Tdummy;
                 fp_in>>weight;
                 fp_in>>omega;
                 fp_in>>Tdummy;
                 K[0]=Tdummy;
                 if(dimension==2)
                   {
                     fp_in>>Tdummy;
                     K[1]=Tdummy;
                     K[2]=0.;
                   }
                 if(dimension==3)
                   {
                     fp_in>>Tdummy;
                     K[1]=Tdummy;
                     fp_in>>Tdummy;
                     K[2]=Tdummy;
                   }
                 fp_in>>Tdummy;
                 vg[0]=Tdummy;
                 if(dimension==2)
                   {
                     fp_in>>Tdummy;
                     vg[1]=Tdummy;
                     vg[2]=0.;
                   }
                 if(dimension==3)
                   {
                     fp_in>>Tdummy;
                     vg[1]=Tdummy;
                     fp_in>>Tdummy;
                     vg[2]=Tdummy;
                   }
                 fp_in>>tau;
                 fp_in>>tauN;
                 modeptr->getVRef()=vg;
                 modeptr->getTauRef()=tau;
                 modeptr->getTauNRef()=tauN;
                 modeptr->getOmegaRef()=omega;
                 modeptr->setIndex(count);
                 count++;
                 modes.push_back(modeptr);
                 volptr->setkvec(K);
                 volptr->setdk3(weight);
               }
             _Kmesh.push_back(volptr);
           }
         fp_in.close();
         calcDK3();
         _freqArray.resize(gettotmodes());
         for(int k=0;k<_length;k++)
           {
             Tkvol& kv=getkvol(k);
             const int modenum=kv.getmodenum();
             for(int m=0;m<modenum;m++)
               {
                 Tmode& mode=kv.getmode(m);
                 const int index=mode.getIndex()-1;
                 _freqArray[index]=mode.getomega();
               }
           }
       }
template<class T> Kspace< T >::Kspace (const Kspace< T > &) private
Member Function Documentation
template<class T> void Kspace< T >::addFAS (const int c, TArray & Bvec) inline
Definition at line 1273 of file Kspace.h.
References Kspace< T >::_FASCorrection, Kspace< T >::getGlobalIndex(), and Kspace< T >::gettotmodes().
Referenced by COMETDiscretizer< T >::addFAS().
   {
     int start=getGlobalIndex(c,0);
     int end=start+gettotmodes();
     for(int i=start; i<end; i++)
       Bvec[i-start]-=(*_FASCorrection)[i];
   }
template<class T> void Kspace< T >::addFASint (const int c, TArray & Bvec) inline
Definition at line 1281 of file Kspace.h.
References Kspace< T >::_FASCorrection, Kspace< T >::getGlobalIndex(), and Kspace< T >::gettotmodes().
Referenced by COMETInterface< T >::updateOtherGhost(), and COMETInterface< T >::updateResid().
   {
     int start=getGlobalIndex(c,0);
     int end=start+gettotmodes();
     for(int i=start; i<end; i++)
       Bvec[i-start]+=(*_FASCorrection)[i];
   }
template<class T> void Kspace< T >::addSource (const int c, TArray & BVec, const T cv) inline
Definition at line 1693 of file Kspace.h.
References Kspace< T >::_Source, and Kspace< T >::getGlobalIndex().
Referenced by COMETDiscretizer< T >::COMETSource().
   {
     if(!(_Source==NULL))
       {
         const int beg=getGlobalIndex(c,0);
         const int fin=getGlobalIndex(c+1,0);
         int index(0);
         for(int i=beg;i<fin;i++)
           {
             BVec[index]+=(*_Source)[i]*cv;
             index++;
           }
       }
   }
template<class T> T Kspace< T >::calcBallisticInterface (Tkspace & kspace1, const Tvec & An, const T T0, const T T1) inline
Definition at line 1049 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calce0(), Kspace< T >::findTransmission(), kvol< T >::getdk3(), Kspace< T >::getDK3(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getomega(), and pmode< T >::getv().
   {
     T heatRate0(0.);
     T heatRate1(0.);
     const int k1len=kspace1.getlength();
     const T DK0=getDK3();
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         T dk3=kvol.getdk3();
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             Tvec vg=mode.getv();
             const T VdotA=An[0]*vg[0]+An[1]*vg[1]+An[2]*vg[2];
             if(VdotA>0.)
               {
                 const T e0=mode.calce0(T0);
                 const T t01=findTransmission(kspace1,mode.getomega());
                 heatRate0+=t01*VdotA*dk3*e0/DK0;
               }
           }
       }
     for(int k=0;k<k1len;k++)
       {
         Tkvol& kvol=kspace1.getkvol(k);
         T dk3=kvol.getdk3();
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             Tvec vg=mode.getv();
             const T VdotA=An[0]*vg[0]+An[1]*vg[1]+An[2]*vg[2];
             if(VdotA<0.)
               {
                 const T e0=mode.calce0(T1);
                 const T t10=kspace1.findTransmission(*this,mode.getomega());
                 heatRate1+=t10*VdotA*dk3*e0/DK0;
               }
           }
       }
     heatRate1/=heatRate0;
     heatRate1=1+heatRate1;
     heatRate1*=heatRate0*DK0;
     return heatRate1;
   }
template<class T> T Kspace< T >::calcBandTemp (const T guess, const T eSum, const IntArray & kpts, const IntArray & mpts) inline
Definition at line 1103 of file Kspace.h.
References pmode< T >::calcde0dT(), pmode< T >::calce0(), fabs(), kvol< T >::getdk3(), Kspace< T >::getkvol(), Array< T >::getLength(), and kvol< T >::getmode().
Referenced by COMETModel< T >::calcBandTemps().
   {
     T newguess(guess);
     T deltaT=1.;
     int iters=0;
     if(kpts.getLength()>0)
       {
         while((deltaT>1e-6)&&(iters<10))
           {
             T e0sum(0);
             T de0sum(0);
             for(int i=0;i<kpts.getLength();i++)
               {
                 const int k=kpts[i];
                 const int m=mpts[i];
                 T dk3=getkvol(k).getdk3();
                 Tmode& mode=getkvol(k).getmode(m);
                 e0sum+=mode.calce0(newguess)*dk3;
                 de0sum+=mode.calcde0dT(newguess)*dk3;
               }
             deltaT=(e0sum-eSum)/de0sum;
             newguess-=deltaT;
             deltaT=fabs(deltaT)/newguess;
             iters++;
           }
         return newguess;
       }
     else
       return 0;
   }
template<class T> T Kspace< T >::calcDiffuseE (Tkspace & kspace1, const Tvec & An, const T T0, const T T1) inline
Definition at line 1134 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calce0(), Kspace< T >::findTransmission(), kvol< T >::getdk3(), Kspace< T >::getDK3(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getomega(), and pmode< T >::getv().
   {
     T heatRate0(0.);
     T heatRate1(0.);
     const int k1len=kspace1.getlength();
     const T DK0=getDK3();
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         T dk3=kvol.getdk3();
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             Tvec vg=mode.getv();
             const T VdotA=An[0]*vg[0]+An[1]*vg[1]+An[2]*vg[2];
             if(VdotA>0.)
               {
                 const T e0=mode.calce0(T0);
                 const T t01=findTransmission(kspace1,mode.getomega());
                 heatRate0+=t01*VdotA*dk3*e0/DK0;
               }
           }
       }
     T sumVdotA(0.);
     for(int k=0;k<k1len;k++)
       {
         Tkvol& kvol=kspace1.getkvol(k);
         T dk3=kvol.getdk3();
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             Tvec vg=mode.getv();
             const T VdotA=An[0]*vg[0]+An[1]*vg[1]+An[2]*vg[2];
             if(VdotA<0.)
               {
                 const T e0=mode.calce0(T1);
                 const T t10=kspace1.findTransmission(*this,mode.getomega());
                 heatRate1-=(1.-t10)*VdotA*dk3*e0/DK0;
               }
             else
               sumVdotA+=VdotA*dk3/DK0;
           }
       }
     heatRate1=heatRate0/sumVdotA+heatRate1/sumVdotA;
     return heatRate1;
   }
template<class T> T Kspace< T >::calcDK3 () inline
Definition at line 397 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, kvol< T >::getdk3(), and Kspace< T >::getkvol().
Referenced by Kspace< T >::Kspace().
   {
     T r(0.0);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         r+=kv.getdk3();
       }
     _totvol=r;
     return r;
   }
template<class T> T Kspace< T >::calcLatTemp (const int c) inline
Definition at line 461 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, Kspace< T >::calcTemp(), kvol< T >::getdk3(), Kspace< T >::getGlobalIndex(), Kspace< T >::getkvol(), and kvol< T >::getmodenum().
Referenced by COMETModel< T >::makeNonEqTemp().
   {
     int cInd(getGlobalIndex(c,0));
     T esum(0);
     T guess(300);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         T dk3=kv.getdk3();
         for(int m=0;m<modenum;m++)
           {
             esum+=(*_e)[cInd]*dk3/_totvol;
             cInd++;
           }
       }
     esum*=_totvol;
     calcTemp(guess,esum);
     return guess;
   }
template<class T> T Kspace< T >::calcModeTemp (T guess, const T e_sum, const T m) inline
Definition at line 501 of file Kspace.h.
References fabs(), and Kspace< T >::gete0().
Referenced by COMETModel< T >::calcModeTemps().
   {
     T e0;
     T de0dT;
     T deltaT=1.;
     T newguess;
     int iters=0;
     while((deltaT>1e-6)&&(iters<10))
       {
         gete0(guess, e0, de0dT,m);
         deltaT=(e0-e_sum)/de0dT;
         newguess=guess-deltaT;
         deltaT=fabs(deltaT/guess);
         guess=newguess;
         iters++;
       }
     return guess;
   }
template<class T> T Kspace< T >::calcPhononTemp (const int c, const int index, T guess) inline
Definition at line 520 of file Kspace.h.
References pmode< T >::calcde0dT(), pmode< T >::calce0(), fabs(), Kspace< T >::gete(), Kspace< T >::getkvol(), kvol< T >::getmode(), and kvol< T >::getmodenum().
   {
     const int modenum=getkvol(0).getmodenum();
     const int m=index%modenum;
     const int k=floor(index/modenum);
     Tkvol& kv=getkvol(k);
     Tmode& mode=kv.getmode(m);
     const T e=gete(c,index);
     T deltaT=1.;
     int iters=0;
     T inguess=guess;
     while((deltaT>1e-6)&&(iters<10))
       {
         T e0=mode.calce0(inguess);
         T de0dT=mode.calcde0dT(inguess);
         deltaT=(e0-e)/de0dT;
         inguess=guess-deltaT;
         deltaT=fabs(deltaT/guess);
         guess=inguess;
         iters++;
       }
     return guess;
   }
template<class T> T Kspace< T >::calcSpecificHeat (T Tl) inline
Definition at line 668 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calcde0dT(), kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), and kvol< T >::getmodenum().
   {
     T r(0.0);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         T dk3=kv.getdk3();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             r+=mode.calcde0dT(Tl)*dk3;
           }
       }
     return r;
   }
template<class T> T Kspace< T >::calcSpecificHeat (T Tl, const int m) inline
Definition at line 685 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calcde0dT(), kvol< T >::getdk3(), Kspace< T >::getkvol(), and kvol< T >::getmode().
   {
     T r(0.0);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         T dk3=kv.getdk3();
         Tmode& mode=kv.getmode(m);
         r+=mode.calcde0dT(Tl)*dk3;
       }
     return r;
   }
template<class T> T Kspace< T >::calcTauTot () inline
Definition at line 409 of file Kspace.h.
References Kspace< T >::_length, kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), and pmode< T >::gettau().
Referenced by COMETModel< T >::updateTL().
   {   // returns sum(dk3/tau)
     T tauTot=0.;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         T dk3=kv.getdk3();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             tauTot+=dk3/mode.gettau();
           }
       }
     return tauTot;
   }
template<class T> void Kspace< T >::calcTemp (T & guess, const T e_sum, const Tvec An) inline
Definition at line 443 of file Kspace.h.
References fabs(), and Kspace< T >::gete0v().
Referenced by Kspace< T >::calcLatTemp(), COMETInterface< T >::findWallTemp(), and COMETDiscretizer< T >::updateGhostCoarse().
   {
     T e0;
     T de0dT;
     T deltaT=1.;
     T newguess;
     int iters=0;
     while((deltaT>1e-6)&&(iters<10))
       {
         gete0v(guess, e0, de0dT,An);
         deltaT=e0/de0dT-e_sum/de0dT;
         newguess=guess-deltaT;
         deltaT=fabs(deltaT/guess);
         guess=newguess;
         iters++;
       }
   }
template<class T> void Kspace< T >::calcTemp (T & guess, const T e_sum) inline
Definition at line 483 of file Kspace.h.
References fabs(), and Kspace< T >::gete0().
   {
     T e0;
     T de0dT;
     T deltaT=1.;
     T newguess;
     int iters=0;
     while((deltaT>1e-20)&&(iters<100))
       {
         gete0(guess, e0, de0dT);
         deltaT=e0/de0dT-e_sum/de0dT;
         newguess=guess-deltaT;
         deltaT=fabs(deltaT/guess);
         guess=newguess;
         iters++;
       }
   }
template<class T> void Kspace< T >::CopyKspace (Tkspace & copyFromKspace) inline
Definition at line 781 of file Kspace.h.
References Kspace< T >::_Kmesh, Kspace< T >::_length, Kspace< T >::_totvol, Kspace< T >::getDK3(), Kspace< T >::getDOSptr(), Kspace< T >::getkvol(), Kspace< T >::getlength(), and Kspace< T >::setDOS().
Referenced by COMETModel< T >::MakeNewKspaces().
   {
     _length=copyFromKspace.getlength();
     _totvol=copyFromKspace.getDK3();
     _Kmesh.clear();
     for(int i=0;i<_length;i++)
       {
         Kvolptr newKvol=Kvolptr(new Tkvol());
         newKvol->copyKvol(copyFromKspace.getkvol(i));
         _Kmesh.push_back(newKvol);
       }
     setDOS(*copyFromKspace.getDOSptr());
   }
template<class T> void Kspace< T >::createSyncGather (const StorageSite & site) inline
Definition at line 1382 of file Kspace.h.
References Kspace< T >::_e, Kspace< T >::_ghostArrays, StorageSite::getGatherMap(), Array< T >::getLength(), and Kspace< T >::gettotmodes().
Referenced by Kspace< T >::syncLocal().
   {
     const StorageSite::GatherMap& gatherMap = site.getGatherMap();
     foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
       {
         const StorageSite& oSite = *mpos.first;
         EntryIndex e(&oSite, &site);
         const Array<int>& toIndices = *(mpos.second);
         if (_ghostArrays.find(e) == _ghostArrays.end())
           _ghostArrays[e] = _e->newSizedClone(toIndices.getLength()*gettotmodes());
       }
   }
template<class T> T Kspace< T >::FindBallisticHeatRate (const Tvec An, const T T1, const T T2) inline
Definition at line 797 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calce0(), kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), and pmode< T >::getv().
   {
     T q=0.;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         const T dk3=kvol.getdk3();
         const int modes=kvol.getmodenum();
         for(int m=0;m<modes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             Tvec vg=mode.getv();
             T flux=vg[0]*An[0]+vg[1]*An[1]+vg[2]*An[2];
             T e0;
             if(flux>0.)
               e0=mode.calce0(T2);
             else
               e0=mode.calce0(T1);
             q+=flux*e0*dk3;
           }
       }
     return q;
   }
template<class T> T Kspace< T >::findKnStats (const T length) inline
Definition at line 698 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::gettau(), pmode< T >::getv(), and sqrt().
   {
     T AveKn(0.0);
     T maxKn(0.0);
     T minKn;
     Tvec vg1=getkvol(0).getmode(0).getv();
     T vmag1=sqrt(pow(vg1[0],2)+pow(vg1[1],2)+pow(vg1[2],2));
     T tau1=getkvol(0).getmode(0).gettau();
     T npol(getkvol(0).getmodenum());
     minKn=vmag1*tau1;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         T dk3=kv.getdk3();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             Tvec vg=mode.getv();
             T vmag=sqrt(pow(vg[0],2)+pow(vg[1],2)+pow(vg[2],2));
             T tau=mode.gettau();
             AveKn+=vmag*tau*dk3/_totvol;
             if(vmag*tau>maxKn)
               maxKn=vmag*tau;
             if(vmag*tau<minKn)
               minKn=vmag*tau;
           }
       }
     AveKn/=length;
     AveKn/=npol;
     maxKn/=length;
     minKn/=length;
     cout<<"Average Kn: "<<AveKn<<endl;
     cout<<"Maximum Kn: "<<maxKn<<endl;
     cout<<"Minimum Kn: "<<minKn<<endl;
     return AveKn;
   }
template<class T> void Kspace< T >::findSpecs (const Tvec n, const int m, const int k, Refl_pair & refls) inline
Definition at line 742 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::getkvol(), kvol< T >::getmode(), and pmode< T >::getv().
Referenced by PhononModel< T >::init(), and COMETModel< T >::init().
   {
     Tkvol& kvol=getkvol(k);
     Tmode& mode=kvol.getmode(m);
     Tvec kvec=mode.getv();
     const T kmag=pow(kvec[0]*kvec[0]+
                      kvec[1]*kvec[1]+kvec[2]*kvec[2],.5);
     Tvec nk(kvec);
     nk/=kmag;
     const T kdotn(kvec[0]*n[0]+kvec[1]*n[1]+kvec[2]*n[2]);
     Tvec target=kvec-n*(2.*kdotn);
     T minDif(1e50);
     int m1;
     for(int k1=0;k1<_length;k1++)
       {
         Tkvol& kvol1=getkvol(k1);
         Tmode& mode1=kvol1.getmode(m);
         const Tvec kvec1=mode1.getv();
         const Tvec dif(target-kvec1);
         const T difMag=pow(dif[0]*dif[0]+dif[1]*dif[1]+dif[2]*dif[2],.5);
         if(difMag<minDif)
           {
             m1=k1;
             minDif=difMag;
           }
       }
     refls.first.first=1.;
     refls.second.first=1.;
     refls.first.second=m1; //refls.first-- to whom the mode dumps energy
     refls.second.second=-1;  //refls.second-- from whom the mode receices energy
   }
template<class T> T Kspace< T >::findTransmission (Tkspace & toKspace, const T freq) inline
Definition at line 1008 of file Kspace.h.
References Kspace< T >::_transMap, and Array< T >::getLength().
Referenced by Kspace< T >::calcBallisticInterface(), and Kspace< T >::calcDiffuseE().
   {
     TArray& freqBins=*_transMap[&toKspace].first;
     TArray& trans=*_transMap[&toKspace].second;
     int minInd=0;
     int maxInd=freqBins.getLength()-1;
     if(freq<freqBins[minInd] || freq>freqBins[maxInd])
       throw CException("Frequency not in the given range!");
     while(1)
       {
         int mid=floor((minInd+maxInd)/2.);
         T midFreq=freqBins[mid];
         if(freq>midFreq)
           {
             minInd=mid;
             if(freq<=freqBins[minInd+1])
               return trans[minInd];
           }
         else
           {
             maxInd=mid;
             if(freq>freqBins[maxInd-1])
               return trans[maxInd-1];
           }
       }
   }
template<class T> int Kspace< T >::get_request_size (const StorageSite & site) inline
Definition at line 1437 of file Kspace.h.
References StorageSite::getGatherProcID(), and StorageSite::getScatterMap().
Referenced by Kspace< T >::syncLocal().
   {
     int indx(0);
     const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
     foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap)
       {
         const StorageSite&  oSite = *mpos.first;
         //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
         if ( oSite.getGatherProcID() != -1 )
           indx++;
       }
     return indx++;
   }
template<class T> Tkspace* Kspace< T >::getCoarseKspace () inline
Definition at line 1209 of file Kspace.h.
References Kspace< T >::_coarseKspace.
Referenced by Kspace< T >::giveTransmissions().
 {return _coarseKspace;}
template<class T> T Kspace< T >::getde0taudT (const int c, T Tl) inline
Definition at line 646 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, pmode< T >::calcde0dT(), kvol< T >::getdk3(), Kspace< T >::getGlobalIndex(), Kspace< T >::getkvol(), kvol< T >::getmode(), and kvol< T >::getmodenum().
Referenced by COMETDiscretizer< T >::COMETEquilibrium(), and COMETDiscretizer< T >::COMETShifted().
   {
     const T hbar=6.582119e-16;  // (eV s)
     T de0taudT=0.;
     int index=getGlobalIndex(c,0);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         T dk3=kv.getdk3();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             //T energy=hbar*mode.getomega();
             de0taudT+=mode.calcde0dT(Tl)*dk3/_totvol/(*_Tau)[index];
             index++;
           }
       }
     return de0taudT;
   }
template<class T> T Kspace< T >::getDK3 () const inline
Definition at line 408 of file Kspace.h.
References Kspace< T >::_totvol.
Referenced by Kspace< T >::calcBallisticInterface(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), Kspace< T >::calcDiffuseE(), COMETModel< T >::calcModeFlux(), COMETDiscretizer< T >::COMETEquilibrium(), Kspace< T >::CopyKspace(), COMETDiscretizer< T >::correctInterface(), PhononModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), PhononModel< T >::init(), COMETDiscretizer< T >::updateGhostCoarse(), COMETInterface< T >::updateOtherGhost(), and COMETInterface< T >::updateResid().
 {return _totvol;}
template<class T> DensityOfStates<T>* Kspace< T >::getDOSptr () inline
Definition at line 1207 of file Kspace.h.
References Kspace< T >::_DOS.
Referenced by COMETModel< T >::binwiseHeatFluxIntegral(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), COMETModel< T >::calcBandTemps(), Kspace< T >::CopyKspace(), and COMETInterface< T >::makeDMMcoeffs().
 {return _DOS;}
template<class T> T& Kspace< T >::gete (const int cell, const int count) inline
Definition at line 1211 of file Kspace.h.
References Kspace< T >::_e, and Kspace< T >::gettotmodes().
Referenced by COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), COMETModel< T >::calcBandTemps(), COMETModel< T >::calcModeFlux(), COMETModel< T >::calcModeTemps(), and Kspace< T >::calcPhononTemp().
 {return (*_e)[cell*gettotmodes()+count];}
template<class T> void Kspace< T >::gete0 (const T Tguess, T & e0, T & de0dT, const Tvec An) inline
Definition at line 564 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, pmode< T >::calcde0dT(), pmode< T >::calce0(), kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), and pmode< T >::getv().
Referenced by Kspace< T >::calcModeTemp(), and Kspace< T >::calcTemp().
   {
     e0=0.;
     de0dT=0.;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         T dk3=kv.getdk3();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             Tvec vg=mode.getv();
             T vdota=vg[0]*An[0]+vg[1]*An[1]+vg[2]*An[2];
             if(vdota>0)
               {
                 e0+=mode.calce0(Tguess)*dk3/_totvol;
                 de0dT+=mode.calcde0dT(Tguess)*dk3/_totvol;
               }
           }
       }
     e0*=_totvol;
     de0dT*=_totvol;
   }
template<class T> void Kspace< T >::gete0 (const T Tguess, T & e0, T & de0dT) inline
Definition at line 614 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calcde0dT(), pmode< T >::calce0(), kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), and kvol< T >::getmodenum().
   {
     e0=0.;
     de0dT=0.;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         T dk3=kv.getdk3();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             e0+=mode.calce0(Tguess)*dk3;
             de0dT+=mode.calcde0dT(Tguess)*dk3;
           }
       }
   }
template<class T> void Kspace< T >::gete0 (const T Tguess, T & e0, T & de0dT, const T m) inline
Definition at line 632 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calcde0dT(), pmode< T >::calce0(), kvol< T >::getdk3(), Kspace< T >::getkvol(), and kvol< T >::getmode().
   {
     e0=0.;
     de0dT=0.;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         T dk3=kv.getdk3();
         Tmode& mode=kv.getmode(m);
         e0+=mode.calce0(Tguess)*dk3;
         de0dT+=mode.calcde0dT(Tguess)*dk3;
       }
   }
template<class T> T& Kspace< T >::gete0 (const int cell, const int count) inline
Definition at line 1212 of file Kspace.h.
References Kspace< T >::_e0, and Kspace< T >::gettotmodes().
 {return (*_e0)[cell*gettotmodes()+count];}
template<class T> void Kspace< T >::gete0_tau (T & Tguess, T & e0tau, T & de0taudT) inline
Definition at line 546 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calcde0taudT(), pmode< T >::calce0tau(), kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), and kvol< T >::getmodenum().
Referenced by Kspace< T >::NewtonSolve().
   {
     e0tau=0.;
     de0taudT=0.;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         T dk3=kv.getdk3();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             e0tau+=mode.calce0tau(Tguess)*dk3;
             de0taudT+=mode.calcde0taudT(Tguess)*dk3;
           }
       }
   }
template<class T> TArray& Kspace< T >::gete0Array () inline
Definition at line 1225 of file Kspace.h.
References Kspace< T >::_e0.
Referenced by COMETModel< T >::sete0().
 {return *_e0;}
template<class T> void Kspace< T >::gete0CellVals (const int c, TArray & o) inline
Definition at line 1240 of file Kspace.h.
References Kspace< T >::_e0, Kspace< T >::getGlobalIndex(), and Kspace< T >::gettotmodes().
   {
     int start=getGlobalIndex(c,0);
     int end=start+gettotmodes();
     for(int i=start; i<end; i++)
       o[i-start]=(*_e0)[i];
   }
template<class T> ArrayBase* Kspace< T >::gete0CellValsPy (const T Tl) inline
Definition at line 1603 of file Kspace.h.
References Kspace< T >::getEquilibriumArray(), Kspace< T >::gettotmodes(), and Kspace< T >::weightArray().
   {
     TArray* e=new TArray(gettotmodes());
     getEquilibriumArray(*e,Tl);
     weightArray(*e);
     return e;
   }
template<class T> ArrayBase* Kspace< T >::gete0CellVars (const int c) inline
Definition at line 1583 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, kvol< T >::getdk3(), Kspace< T >::getGlobalIndex(), Kspace< T >::getkvol(), kvol< T >::getmodenum(), and Kspace< T >::gettotmodes().
   {
     TArray* e=new TArray(gettotmodes());
     int cnt=getGlobalIndex(c,0);
     int index=0;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const T dk3=kv.getdk3();
         const int modenum=kv.getmodenum();
         for(int m=0;m<modenum;m++)
           {
             (*e)[index]=(*_e0)[cnt]*(dk3/_totvol);
             index++;
             cnt++;
           }
       }
     return e;
   }
template<class T> void Kspace< T >::gete0v (const T Tguess, T & e0, T & de0dT, const Tvec An) inline
Definition at line 589 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, pmode< T >::calcde0dT(), pmode< T >::calce0(), kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), and pmode< T >::getv().
Referenced by Kspace< T >::calcTemp().
   {
     e0=0.;
     de0dT=0.;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         T dk3=kv.getdk3();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             Tvec vg=mode.getv();
             T vdota=vg[0]*An[0]+vg[1]*An[1]+vg[2]*An[2];
             if(vdota>0)
               {
                 e0+=mode.calce0(Tguess)*dk3/_totvol*vdota;
                 de0dT+=mode.calcde0dT(Tguess)*dk3/_totvol*vdota;
               }
           }
       }
     e0*=_totvol;
     de0dT*=_totvol;
   }
template<class T> TArray& Kspace< T >::geteArray () inline
Definition at line 1224 of file Kspace.h.
References Kspace< T >::_e.
Referenced by COMETModel< T >::binwiseHeatFluxIntegral(), COMETModel< T >::correctSolution(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), COMETModel< T >::injectResid(), and COMETModel< T >::modewiseHeatFluxIntegral().
 {return *_e;}
template<class T> void Kspace< T >::geteCellVals (const int c, TArray & o) inline
Definition at line 1232 of file Kspace.h.
References Kspace< T >::_e, Kspace< T >::getGlobalIndex(), and Kspace< T >::gettotmodes().
Referenced by COMETInterface< T >::findWallTemp(), Kspace< T >::geteCellValsPy(), and COMETInterface< T >::makeValueArray().
   {
     int start=getGlobalIndex(c,0);
     int end=start+gettotmodes();
     for(int i=start; i<end; i++)
       o[i-start]=(*_e)[i];
   }
template<class T> ArrayBase* Kspace< T >::geteCellValsPy (const int c) inline
Definition at line 1575 of file Kspace.h.
References Kspace< T >::geteCellVals(), Kspace< T >::gettotmodes(), and Kspace< T >::weightArray().
   {
     TArray* e=new TArray(gettotmodes());
     geteCellVals(c,*e);
     weightArray(*e);
     return e;
   }
template<class T> ArrayBase* Kspace< T >::getEmptyArray (const int length) inline
Definition at line 1676 of file Kspace.h.
   {return new TArray(length);}
template<class T> void Kspace< T >::getEquilibriumArray (TArray & vals, const T Tl) inline
Definition at line 1451 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calce0(), pmode< T >::getIndex(), Kspace< T >::getkvol(), kvol< T >::getmode(), and kvol< T >::getmodenum().
Referenced by Kspace< T >::gete0CellValsPy().
   {
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             const int index=mode.getIndex()-1;
             vals[index]=mode.calce0(Tl);
           }
       }
   }
template<class T> T& Kspace< T >::getFas (const int cell, const int count) inline
Definition at line 1215 of file Kspace.h.
References Kspace< T >::_FASCorrection, and Kspace< T >::gettotmodes().
 {return (*_FASCorrection)[cell*gettotmodes()+count];}
template<class T> TArray& Kspace< T >::getFASArray () inline
Definition at line 1229 of file Kspace.h.
References Kspace< T >::_FASCorrection.
Referenced by COMETModel< T >::injectResid().
 {return *_FASCorrection;}
template<class T> TArray& Kspace< T >::getFreqArray () inline
Definition at line 1466 of file Kspace.h.
References Kspace< T >::_freqArray.
 {return _freqArray;}
template<class T> ArrayBase* Kspace< T >::getFreqArrayPy () inline
Definition at line 1611 of file Kspace.h.
References Kspace< T >::_freqArray, and Kspace< T >::gettotmodes().
   {
     TArray* e=new TArray(gettotmodes());
     (*e)=_freqArray;
     return e;
   }
template<class T> ArrayBase* Kspace< T >::getFullsources (const int c) inline
Definition at line 1528 of file Kspace.h.
References Kspace< T >::_ScattKernel, Kspace< T >::gettotmodes(), and Kspace< T >::weightArray().
   {
     TArray* S=new TArray(gettotmodes());
     TArray ds(gettotmodes());
     _ScattKernel->updateSource2(c,*S,ds);
     weightArray(*S);
     return S;
   }
template<class T> int Kspace< T >::getGlobalIndex (const int cell, const int count) inline
Definition at line 1216 of file Kspace.h.
References Kspace< T >::gettotmodes().
Referenced by Kspace< T >::addFAS(), Kspace< T >::addFASint(), Kspace< T >::addSource(), COMETBoundary< T >::applyTemperatureWallCoarse(), COMETBoundary< T >::applyTemperatureWallFine(), COMETModel< T >::binwiseHeatFluxIntegral(), Kspace< T >::calcLatTemp(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETFullScatt(), COMETModel< T >::correctSolution(), COMETDiscretizer< T >::Distribute(), Kspace< T >::getde0taudT(), Kspace< T >::gete0CellVals(), Kspace< T >::gete0CellVars(), Kspace< T >::geteCellVals(), Kspace< T >::getnCellVals(), Kspace< T >::getRTAsources(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), COMETModel< T >::init(), COMETModel< T >::initCoarse(), COMETModel< T >::injectResid(), COMETDiscretizer< T >::makeValueArray(), COMETModel< T >::modewiseHeatFluxIntegral(), COMETDiscretizer< T >::scaledResid(), COMETDiscretizer< T >::ScatterPhonons(), COMETModel< T >::sete0(), Kspace< T >::seteCellVals(), Kspace< T >::setResidCell(), Kspace< T >::syncGather(), Kspace< T >::syncScatter(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateGhostCoarse(), COMETDiscretizer< T >::updateGhostFine(), and Kspace< T >::updateTau().
 {return cell*gettotmodes()+count;}
template<class T> T Kspace< T >::gethbar () inline
Definition at line 392 of file Kspace.h.
 {return 6.582119e-16;}
template<class T> ArrayBase* Kspace< T >::getHollandConductivity (const T Tl) inline
Definition at line 906 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calcde0dT(), kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::gettau(), pmode< T >::getv(), Kspace< T >::outerProduct(), and SquareTensor< T, N >::zero().
   {//returns the thermal conductivity tensor in row major order
     T3Tensor KTensor;
     T3Tensor Dummy;
     KTensor.zero();
     Dummy.zero();
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         const T dk3=kvol.getdk3();
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             Tvec vg=mode.getv();
             T tau=mode.gettau();
             T de0dT=mode.calcde0dT(Tl);
             outerProduct(vg, vg, Dummy);
             KTensor+=Dummy*tau*de0dT*dk3;
             Dummy.zero();
           }
       }
     TArray* Kptr=new TArray(9);
     int count=0;
     for(int j=0;j<3;j++)
       {
         for(int i=0;i<3;i++)
           {
             (*Kptr)[count]=KTensor(i,j);
             count++;
           }
       }
     return Kptr;
   }
template<class T> ArrayBase* Kspace< T >::getIIsources (const int c, const bool correct) inline
Definition at line 1546 of file Kspace.h.
References Kspace< T >::_ScattKernel, Kspace< T >::gettotmodes(), and Kspace< T >::weightArray().
   {
     TArray* S=new TArray(gettotmodes());
     TArray ds(gettotmodes());
     _ScattKernel->getTypeIIsource(c,*S,ds,correct);
     weightArray(*S);
     return S;
   }
template<class T> T& Kspace< T >::getInj (const int cell, const int count) inline
Definition at line 1213 of file Kspace.h.
References Kspace< T >::_injected, and Kspace< T >::gettotmodes().
 {return (*_injected)[cell*gettotmodes()+count];}
template<class T> TArray& Kspace< T >::getInjArray () inline
Definition at line 1227 of file Kspace.h.
References Kspace< T >::_injected.
Referenced by COMETModel< T >::correctSolution(), and COMETModel< T >::injectResid().
 {return *_injected;}
template<class T> ArrayBase* Kspace< T >::getIsources (const int c, const bool correct) inline
Definition at line 1537 of file Kspace.h.
References Kspace< T >::_ScattKernel, Kspace< T >::gettotmodes(), and Kspace< T >::weightArray().
   {
     TArray* S=new TArray(gettotmodes());
     TArray ds(gettotmodes());
     _ScattKernel->getTypeIsource(c,*S,ds,correct);
     weightArray(*S);
     return S;
   }
template<class T> Tkvol& Kspace< T >::getkvol (int n) const inline
Definition at line 390 of file Kspace.h.
References Kspace< T >::_Kmesh.
Referenced by COMETInterface< T >::addFAS(), PhononModel< T >::advance(), PhononInterface< X >::applyInterfaceCondition(), PhononBoundary< X >::applyReflectingWall(), PhononBoundary< X >::applyTemperatureWall(), COMETBoundary< T >::applyTemperatureWallCoarse(), COMETBoundary< T >::applyTemperatureWallFine(), DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::binMode(), COMETModel< T >::binwiseHeatFluxIntegral(), Kspace< T >::calcBallisticInterface(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), Kspace< T >::calcBandTemp(), COMETModel< T >::calcBandTemps(), DensityOfStates< T >::calcBinFlux(), Kspace< T >::calcDiffuseE(), Kspace< T >::calcDK3(), Kspace< T >::calcLatTemp(), COMETModel< T >::calcModeFlux(), COMETModel< T >::calcModeTemps(), Kspace< T >::calcPhononTemp(), Kspace< T >::calcSpecificHeat(), Kspace< T >::calcTauTot(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETFullScatt(), COMETDiscretizer< T >::COMETShifted(), Kspace< T >::CopyKspace(), COMETModel< T >::correctSolution(), COMETDiscretizer< T >::Distribute(), COMETModel< T >::equilibrate(), Kspace< T >::FindBallisticHeatRate(), Kspace< T >::findKnStats(), Kspace< T >::findSpecs(), COMETInterface< T >::findWallTemp(), COMETDiscretizer< T >::gatherResid(), Kspace< T >::getde0taudT(), Kspace< T >::gete0(), Kspace< T >::gete0_tau(), Kspace< T >::gete0CellVars(), Kspace< T >::gete0v(), Kspace< T >::getEquilibriumArray(), Kspace< T >::getHollandConductivity(), Kspace< T >::getModewiseBallisticConductance(), Kspace< T >::getModewiseHollandConductivity(), Kspace< T >::getReflectionArray(), Kspace< T >::getRTAsources(), Kspace< T >::getTauArrayPy(), COMETModel< T >::getValueArray(), Kspace< T >::getVelocities(), Kspace< T >::getWaveVectors(), PhononModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), PhononModel< T >::init(), COMETModel< T >::init(), COMETModel< T >::initCoarse(), COMETModel< T >::injectResid(), Kspace< T >::Kspace(), Kspace< T >::makeDegenerate(), COMETInterface< T >::makeDMMcoeffs(), COMETInterface< T >::makeEquilibriumArray(), Kspace< T >::makeFreqArray(), COMETDiscretizer< T >::makeValueArray(), DensityOfStates< T >::mergeBins(), COMETModel< T >::modewiseHeatFluxIntegral(), COMETDiscretizer< T >::ScatterPhonons(), Kspace< T >::setCp(), Kspace< T >::setCpNonGray(), DensityOfStates< T >::setDensity(), COMETModel< T >::sete0(), Kspace< T >::setTref(), DensityOfStates< T >::sumOutgoing(), PhononModel< T >::updatee0(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateeShifted(), COMETDiscretizer< T >::updateGhostCoarse(), COMETDiscretizer< T >::updateGhostFine(), PhononModel< T >::updateHeatFlux(), PhononModel< T >::updateTL(), Kspace< T >::weightArray(), and COMETInterface< T >::ZeroGhost().
 {return *_Kmesh[n];}
template<class T> int Kspace< T >::getlength () const inline
Definition at line 391 of file Kspace.h.
References Kspace< T >::_length.
Referenced by COMETInterface< T >::addFAS(), PhononModel< T >::advance(), PhononInterface< X >::applyInterfaceCondition(), PhononBoundary< X >::applyReflectingWall(), PhononBoundary< X >::applyTemperatureWall(), COMETBoundary< T >::applyTemperatureWallCoarse(), COMETBoundary< T >::applyTemperatureWallFine(), DensityOfStates< T >::binEntireKspace(), DensityOfStates< T >::binMode(), Kspace< T >::calcBallisticInterface(), COMETModel< T >::calcBandRelEnergy(), Kspace< T >::calcDiffuseE(), COMETModel< T >::calcModeFlux(), COMETModel< T >::calcModeTemps(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETFullScatt(), COMETDiscretizer< T >::COMETShifted(), Kspace< T >::CopyKspace(), COMETModel< T >::correctSolution(), COMETDiscretizer< T >::Distribute(), COMETModel< T >::equilibrate(), COMETInterface< T >::findWallTemp(), COMETDiscretizer< T >::gatherResid(), COMETModel< T >::getValueArray(), PhononModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegralFace(), PhononModel< T >::init(), COMETModel< T >::init(), COMETModel< T >::initCoarse(), COMETModel< T >::injectResid(), COMETInterface< T >::makeEquilibriumArray(), COMETDiscretizer< T >::makeValueArray(), DensityOfStates< T >::mergeBins(), COMETModel< T >::modewiseHeatFluxIntegral(), COMETDiscretizer< T >::ScatterPhonons(), COMETModel< T >::sete0(), PhononModel< T >::updatee0(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateeShifted(), COMETDiscretizer< T >::updateGhostCoarse(), COMETDiscretizer< T >::updateGhostFine(), PhononModel< T >::updateHeatFlux(), PhononModel< T >::updateTL(), and COMETInterface< T >::ZeroGhost().
 {return _length;}
template<class T> ArrayBase* Kspace< T >::getModewiseBallisticConductance (const T Tl) inline
Definition at line 969 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calcde0dT(), kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::gettotmodes(), and pmode< T >::getv().
   {
     TArray* Kptr=new TArray(gettotmodes());
     TArray& K=*Kptr;
     int count=0;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         const T dk3=kvol.getdk3();
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             Tvec vg=mode.getv();
             T de0dT=mode.calcde0dT(Tl);
             K[count]=vg[0]*de0dT*dk3;
             count++;
           }
       }
     return Kptr;
   }
template<class T> ArrayBase* Kspace< T >::getModewiseHollandConductivity (const T Tl) inline
Definition at line 944 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::calcde0dT(), kvol< T >::getdk3(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::gettau(), Kspace< T >::gettotmodes(), and pmode< T >::getv().
   {
     TArray* Kptr=new TArray(gettotmodes());
     TArray& K=*Kptr;
     int count=0;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         const T dk3=kvol.getdk3();
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             Tvec vg=mode.getv();
             T tau=mode.gettau();
             T de0dT=mode.calcde0dT(Tl);
             K[count]=vg[0]*vg[0]*tau*de0dT*dk3;
             count++;
           }
       }
     return Kptr;
   }
template<class T> void Kspace< T >::getnCellVals (const int c, TArray & o) inline
Definition at line 1248 of file Kspace.h.
References Kspace< T >::_e, Kspace< T >::_freqArray, Kspace< T >::getGlobalIndex(), and Kspace< T >::gettotmodes().
   {
     const T hbar(6.582119e-16);
     int start=getGlobalIndex(c,0);
     int end=start+gettotmodes();
     for(int i=start; i<end; i++)
       o[i-start]=(*_e)[i]/hbar/_freqArray[i-start];
   }
template<class T> ArrayBase* Kspace< T >::getReflectionArray (const Mesh & mesh, const int FgId) inline
Definition at line 871 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::getIndex(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getReflpair(), and Kspace< T >::gettotmodes().
   {
     const int allModes=gettotmodes();
     IntArray* reflInd=new IntArray(allModes);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         const int modes=kvol.getmodenum();
         for(int m=0;m<modes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             const int count=mode.getIndex()-1;
             Refl_pair& refls=mode.getReflpair(FgId);
             if(refls.second.second!=-1)  //v dot A < 0
               {
                 const int kk=refls.second.second;
                 Tmode& FromMode=getkvol(kk).getmode(m);
                 const int indx=FromMode.getIndex();
                 (*reflInd)[count]=indx;
               }
             else if(refls.first.second!=-1)//v dot A > 0
               {
                 const int kk=refls.first.second;
                 Tmode& ToMode=getkvol(kk).getmode(m);
                 const int indx=ToMode.getIndex();
                 (*reflInd)[count]=indx;
               }
             else
               throw CException("Not a reflecting wall!");
           }
       }
     return reflInd;
   }
template<class T> T& Kspace< T >::getRes (const int cell, const int count) inline
Definition at line 1214 of file Kspace.h.
References Kspace< T >::_residual, and Kspace< T >::gettotmodes().
 {return (*_residual)[cell*gettotmodes()+count];}
template<class T> TArray& Kspace< T >::getResArray () inline
Definition at line 1228 of file Kspace.h.
References Kspace< T >::_residual.
Referenced by COMETModel< T >::injectResid().
 {return *_residual;}
template<class T> ArrayBase* Kspace< T >::getRTAsources (const int c) inline
Definition at line 1504 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, kvol< T >::getdk3(), Kspace< T >::getGlobalIndex(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::gettau(), and Kspace< T >::gettotmodes().
   {
     TArray* S=new TArray(gettotmodes());
     int ind=getGlobalIndex(c,0);
     int cnt(0);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         const int modes=kvol.getmodenum();
         const T dk3=kvol.getdk3();
         for(int m=0;m<modes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             T tau=mode.gettau();
             (*S)[cnt]=((*_e0)[ind]-(*_e)[ind])/tau*(dk3/_totvol);
             cnt++;
             ind++;
           }
       }
     return S;
   }
template<class T> TArray& Kspace< T >::getSourceArray () inline
Definition at line 1226 of file Kspace.h.
References Kspace< T >::_Source.
 {return *_Source;}
template<class T> ArrayBase* Kspace< T >::getSourceArrayPy () inline
Definition at line 1690 of file Kspace.h.
References Kspace< T >::_Source.
   {return _Source.get();}
template<class T> ArrayBase* Kspace< T >::getSourceDeriv (const int c) inline
Definition at line 1555 of file Kspace.h.
References Kspace< T >::_ScattKernel, Kspace< T >::gettotmodes(), and Kspace< T >::weightArray().
   {
     TArray s(gettotmodes());
     TArray* ds=new TArray(gettotmodes());
     _ScattKernel->updateSource2(c,s,*ds);
     weightArray(*ds);
     return ds;
   }
template<class T> void Kspace< T >::getSourceTerm (const int c, TArray & s, TArray & ds) inline
Definition at line 1468 of file Kspace.h.
References Kspace< T >::_ScattKernel.
Referenced by COMETDiscretizer< T >::findResidFull().
   {
     _ScattKernel->updateSource2(c,s,ds);
   }
template<class T> const T Kspace< T >::getTau (const int index) inline
Definition at line 1231 of file Kspace.h.
References Kspace< T >::_Tau.
Referenced by COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETEquilibrium(), and COMETDiscretizer< T >::COMETFullScatt().
 {return (*_Tau)[index];}
template<class T> TArray& Kspace< T >::getTauArray () inline
Definition at line 1230 of file Kspace.h.
References Kspace< T >::_Tau.
 {return *_Tau;}
template<class T> ArrayBase* Kspace< T >::getTauArrayPy () inline
Definition at line 1618 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::gettau(), and Kspace< T >::gettotmodes().
   {
     TArray* e=new TArray(gettotmodes());
     int index(0);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         //const T dk3=kv.getdk3();
         const int modenum=kv.getmodenum();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             (*e)[index]=mode.gettau();
             index++;
           }
       }
     return e;
   }
template<class T> int Kspace< T >::gettotmodes () inline
Definition at line 393 of file Kspace.h.
References Kspace< T >::_Kmesh, and Kspace< T >::_length.
Referenced by COMETInterface< T >::addFAS(), Kspace< T >::addFAS(), COMETDiscretizer< T >::addFAS(), Kspace< T >::addFASint(), COMETBoundary< T >::applyTemperatureWallFine(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETFullScatt(), COMETDiscretizer< T >::COMETShifted(), COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::correctInterface(), Kspace< T >::createSyncGather(), COMETInterface< T >::Distribute(), COMETDiscretizer< T >::Distribute(), COMETInterface< T >::DistributeResid(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETDiscretizer< T >::findResidFull(), COMETInterface< T >::findWallTemp(), COMETDiscretizer< T >::gatherResid(), Kspace< T >::gete(), Kspace< T >::gete0(), Kspace< T >::gete0CellVals(), Kspace< T >::gete0CellValsPy(), Kspace< T >::gete0CellVars(), Kspace< T >::geteCellVals(), Kspace< T >::geteCellValsPy(), Kspace< T >::getFas(), Kspace< T >::getFreqArrayPy(), Kspace< T >::getFullsources(), Kspace< T >::getGlobalIndex(), Kspace< T >::getIIsources(), Kspace< T >::getInj(), Kspace< T >::getIsources(), Kspace< T >::getModewiseBallisticConductance(), Kspace< T >::getModewiseHollandConductivity(), Kspace< T >::getnCellVals(), Kspace< T >::getReflectionArray(), Kspace< T >::getRes(), Kspace< T >::getRTAsources(), Kspace< T >::getSourceDeriv(), Kspace< T >::getTauArrayPy(), COMETModel< T >::getValueArray(), Kspace< T >::getVelocities(), COMETModel< T >::init(), COMETModel< T >::initCoarse(), Kspace< T >::Kspace(), COMETInterface< T >::makeCoarseCoeffs(), COMETInterface< T >::makeDMMcoeffs(), COMETInterface< T >::makeEquilibriumArray(), Kspace< T >::makeFreqArray(), COMETInterface< T >::makeNoInterfaceCoeffs(), COMETInterface< T >::makeValueArray(), COMETDiscretizer< T >::makeValueArray(), COMETModel< T >::modewiseHeatFluxIntegral(), COMETDiscretizer< T >::ScatterPhonons(), Kspace< T >::seteCellVals(), Kspace< T >::setResidCell(), Kspace< T >::syncGather(), Kspace< T >::syncScatter(), COMETDiscretizer< T >::updateGhostFine(), COMETInterface< T >::updateOtherGhost(), COMETInterface< T >::updateResid(), and Kspace< T >::weightArray().
   {
     return (_Kmesh[0]->getmodenum())*_length;
   }
template<class T> TArray& Kspace< T >::getTransArray (Tkspace & toKspace) inline
Definition at line 1040 of file Kspace.h.
References Kspace< T >::_transMap.
Referenced by COMETInterface< T >::makeDMMcoeffs().
     {
       typename TransmissionMap::const_iterator pos=_transMap.find(&toKspace);
       if(pos!=_transMap.end())
         return *((pos->second).second);
       else
         throw CException("getTransArray: Transmission not set!");
     }
template<class T> TransmissionMap& Kspace< T >::getTransMap () inline
Definition at line 1210 of file Kspace.h.
References Kspace< T >::_transMap.
Referenced by Kspace< T >::giveTransmissions().
 {return _transMap;}
template<class T> ArrayBase* Kspace< T >::getVelocities () inline
Definition at line 821 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::getIndex(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::gettotmodes(), and pmode< T >::getv().
   {
     const int allModes=gettotmodes();
     TvecArray* Velocities=new TvecArray(allModes);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         const int modes=kvol.getmodenum();
         for(int m=0;m<modes;m++)
           {
             const int count=kvol.getmode(m).getIndex()-1;
             (*Velocities)[count]=kvol.getmode(m).getv();
           }
       }
     return Velocities;
   }
template<class T> void Kspace< T >::getVelocities (TvecArray & v) inline
Definition at line 839 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::getIndex(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::gettotmodes(), pmode< T >::getv(), Array< T >::resize(), and Array< T >::zero().
   {
     const int allModes=gettotmodes();
     v.resize(allModes);
     v.zero();
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         const int modes=kvol.getmodenum();
         for(int m=0;m<modes;m++)
           {
             const int count=kvol.getmode(m).getIndex()-1;
             v[count]=kvol.getmode(m).getv();
           }
       }
   }
template<class T> ArrayBase* Kspace< T >::getVelocities (const int M) inline
Definition at line 857 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::getkvol(), kvol< T >::getmode(), and pmode< T >::getv().
   {
     TvecArray* Velocities=new TvecArray(_length);
     int count(0);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         //const int modes=kvol.getmodenum();
         (*Velocities)[count]=kvol.getmode(M).getv();
         count++;
       }
     return Velocities;
   }
template<class T> ArrayBase* Kspace< T >::getWaveVectors () inline
Definition at line 1564 of file Kspace.h.
References Kspace< T >::_length, kvol< T >::getkvec(), and Kspace< T >::getkvol().
   {
     TvecArray* Kpts=new TvecArray(_length);
     for(int k=0;k<_length;k++)
       {
         Tkvol& kvol=getkvol(k);
         (*Kpts)[k]=kvol.getkvec();
       }
     return Kpts;
   }
template<class T> void Kspace< T >::giveTransmissions () inline
Definition at line 1190 of file Kspace.h.
References Kspace< T >::_coarseKspace, Kspace< T >::_transMap, Kspace< T >::getCoarseKspace(), and Kspace< T >::getTransMap().
   {
     TransmissionMap& coarseTrans=_coarseKspace->getTransMap();
     for(TransIt it=_transMap.begin();it!=_transMap.end();it++)
       {
         Tkspace* fineToKspace=it->first;
         if(fineToKspace!=NULL)
           {
             Tkspace* coarseToKspace=fineToKspace->getCoarseKspace();
             coarseTrans[coarseToKspace]=(it->second);
           }
       }
   }
template<class T> void Kspace< T >::makeDegenerate (const int m) inline
Definition at line 152 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::getcpRef(), Kspace< T >::getkvol(), kvol< T >::getmode(), and kvol< T >::getmodenum().
   {
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         Tmode& mode=kv.getmode(m);
         mode.getcpRef()*=2.;
       }
   }
template<class T> void Kspace< T >::makeFAS () inline
Definition at line 1289 of file Kspace.h.
Referenced by COMETModel< T >::makeFAS().
 {(*_FASCorrection)-=(*_residual);}
template<class T> void Kspace< T >::makeFreqArray () inline
Definition at line 163 of file Kspace.h.
References Kspace< T >::_freqArray, Kspace< T >::_length, Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getomega(), Kspace< T >::gettotmodes(), and Array< T >::resize().
Referenced by Kspace< T >::Kspace().
   {
     _freqArray.resize(gettotmodes());
     int count=0;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             const T omega=mode.getomega();
             _freqArray[count]=omega;
             count++;
           }
       }
   }
template<class T> void Kspace< T >::NewtonSolve (T & guess, const T e_sum) inline
Definition at line 425 of file Kspace.h.
References fabs(), and Kspace< T >::gete0_tau().
Referenced by PhononModel< T >::COMETupdateTL(), PhononModel< T >::updateTL(), and COMETModel< T >::updateTL().
   {
     T e0_tau;
     T de0_taudT;
     T deltaT=1.;
     T newguess;
     int iters=0;
     while((deltaT>1e-6)&&(iters<10))
       {
         gete0_tau(guess,e0_tau,de0_taudT);
         deltaT=(e0_tau-e_sum)/de0_taudT;
         newguess=guess-deltaT;
         deltaT=fabs(deltaT/guess);
         guess=newguess;
         iters++;
       }
   }
template<class T> void Kspace< T >::outerProduct (const Tvec & v1, const Tvec & v2, T3Tensor & out) inline
Definition at line 993 of file Kspace.h.
Referenced by Kspace< T >::getHollandConductivity().
   {
     for(int i=0;i<3;i++)
       for(int j=0;j<3;j++)
         out(i,j)=v1[i]*v2[j];
   }
template<class T> void Kspace< T >::ScatterPhonons (const int c, const int totIts, TArray & C, TArray & B, const TArray & V, TArray & newE, const T cv) inline
Definition at line 1476 of file Kspace.h.
References Kspace< T >::_ScattKernel, and Kspace< T >::seteCellVals().
Referenced by COMETDiscretizer< T >::ScatterPhonons().
   {
     _ScattKernel->scatterPhonons(c, totIts, C, B, V, newE, cv);
     seteCellVals(c,newE);
   }
template<class T> void Kspace< T >::setCoarseKspace (Tkspace * cK) inline
Definition at line 1208 of file Kspace.h.
References Kspace< T >::_coarseKspace.
 {_coarseKspace=cK;}
template<class T> void Kspace< T >::setCp (const T cp) inline
Definition at line 118 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, pmode< T >::getcpRef(), Kspace< T >::getkvol(), kvol< T >::getmode(), and kvol< T >::getmodenum().
   {//input the total specific heat in eV/m^3/K
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             mode.getcpRef()=cp/_totvol;
           }
       }
   }
template<class T> void Kspace< T >::setCpNonGray (const T Tl) inline
Definition at line 133 of file Kspace.h.
References Kspace< T >::_length, pmode< T >::getcpRef(), Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), and pmode< T >::getomega().
   {
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         for(int m=0;m<modenum;m++)
           {
             Tmode& mode=kv.getmode(m);
             const T omega=mode.getomega();
             const T hbar=6.582119e-16;  // (eV s)
             const T kb=8.617343e-5;  // (eV/K)
             mode.getcpRef()=kb*pow((hbar*omega/kb/Tl),2)*
               exp(hbar*omega/kb/Tl)/pow((exp(hbar*omega/kb/Tl)-1),2);
           }
       }
   }
template<class T> void Kspace< T >::setDOS (DensityOfStates< T > & DOS) inline
Definition at line 1205 of file Kspace.h.
References Kspace< T >::_DOS.
Referenced by Kspace< T >::CopyKspace().
 {_DOS=&DOS;}
template<class T> void Kspace< T >::sete0Array (TArrPtr e0Ptr) inline
Definition at line 1218 of file Kspace.h.
References Kspace< T >::_e0.
Referenced by COMETModel< T >::init(), and COMETModel< T >::initCoarse().
 {_e0=e0Ptr;}
template<class T> void Kspace< T >::seteArray (TArrPtr ePtr) inline
Definition at line 1217 of file Kspace.h.
References Kspace< T >::_e.
Referenced by COMETModel< T >::init(), and COMETModel< T >::initCoarse().
 {_e=ePtr;}
template<class T> void Kspace< T >::seteCellVals (const int c, const TArray & o) inline
Definition at line 1257 of file Kspace.h.
References Kspace< T >::_e, Kspace< T >::getGlobalIndex(), and Kspace< T >::gettotmodes().
Referenced by COMETInterface< T >::Distribute(), and Kspace< T >::ScatterPhonons().
   {
     int start=getGlobalIndex(c,0);
     int end=start+gettotmodes();
     for(int i=start; i<end; i++)
       (*_e)[i]=o[i-start];
   }
template<class T> void Kspace< T >::setFASArray (TArrPtr FASPtr) inline
Definition at line 1222 of file Kspace.h.
References Kspace< T >::_FASCorrection.
Referenced by COMETModel< T >::initCoarse().
 {_FASCorrection=FASPtr;}
template<class T> void Kspace< T >::setInjArray (TArrPtr InjPtr) inline
Definition at line 1220 of file Kspace.h.
References Kspace< T >::_injected.
Referenced by COMETModel< T >::initCoarse().
 {_injected=InjPtr;}
template<class T> void Kspace< T >::setRelTimeFunction (const T A, const T B, const T C) inline
Definition at line 1483 of file Kspace.h.
References Kspace< T >::_relFun.
   {
     _relFun._A=A;
     _relFun._B=B;
     _relFun._C=C;
     _relFun._constTau=false;
   }
template<class T> void Kspace< T >::setResArray (TArrPtr ResPtr) inline
Definition at line 1221 of file Kspace.h.
References Kspace< T >::_residual.
Referenced by COMETModel< T >::init(), and COMETModel< T >::initCoarse().
 {_residual=ResPtr;}
template<class T> void Kspace< T >::setResidCell (const int c, const TArray & o) inline
Definition at line 1265 of file Kspace.h.
References Kspace< T >::_residual, Kspace< T >::getGlobalIndex(), and Kspace< T >::gettotmodes().
Referenced by COMETInterface< T >::DistributeResid().
   {
     int start=getGlobalIndex(c,0);
     int end=start+gettotmodes();
     for(int i=start; i<end; i++)
       (*_residual)[i]=o[i-start];
   }
template<class T> void Kspace< T >::setScattKernel (ScatteringKernel< T > & Sk) inline
Definition at line 1206 of file Kspace.h.
References Kspace< T >::_ScattKernel.
 {_ScattKernel=&Sk;}
template<class T> void Kspace< T >::setSourceArray (TArrPtr SPtr) inline
Definition at line 1219 of file Kspace.h.
References Kspace< T >::_Source.
Referenced by COMETModel< T >::init(), and COMETModel< T >::initCoarse().
 {_Source=SPtr;}
template<class T> void Kspace< T >::setTauArray (TArrPtr TauPtr) inline
Definition at line 1223 of file Kspace.h.
References Kspace< T >::_Tau.
Referenced by COMETModel< T >::init(), and COMETModel< T >::initCoarse().
 {_Tau=TauPtr;}
template<class T> void Kspace< T >::setTransmission (Tkspace & toKspace, ArrayBase * freqBins, ArrayBase * transArray) inline
Definition at line 1000 of file Kspace.h.
References Kspace< T >::_transMap.
   {
     BinAndTrans* BTPtr=new BinAndTrans;
     BTPtr->first=dynamic_cast<TArray*>(freqBins);
     BTPtr->second=dynamic_cast<TArray*>(transArray);
     _transMap[&toKspace]=*BTPtr;
   }
template<class T> void Kspace< T >::setTref (const T Tref) inline
Definition at line 1679 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::getkvol(), kvol< T >::getmode(), kvol< T >::getmodenum(), and pmode< T >::setTref().
   {
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const int modenum=kv.getmodenum();
         for(int m=0;m<modenum;m++)
           kv.getmode(m).setTref(Tref);
       }
   }
template<class T> void Kspace< T >::syncGather (const StorageSite & site) inline
Definition at line 1397 of file Kspace.h.
References Kspace< T >::_ghostArrays, StorageSite::getGatherMap(), Kspace< T >::getGlobalIndex(), Array< T >::getLength(), and Kspace< T >::gettotmodes().
Referenced by Kspace< T >::syncLocal().
   {
     const StorageSite::GatherMap& gatherMap = site.getGatherMap();
     const int totModes=gettotmodes();
     foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
       {
         const StorageSite& oSite = *mpos.first;
         const Array<int>& toIndices = *(mpos.second);
         EntryIndex e(&oSite, &site);
         if (_ghostArrays.find(e) == _ghostArrays.end())
           {
             ostringstream err;
             err << "Kspace::syncScatter: ghost array not found for"
                 << &oSite << endl;
             throw CException(err.str());
           }
         const TArray& ghostArray=dynamic_cast<const TArray&>(*_ghostArrays[e]);
         const int cellCount=toIndices.getLength();
         int ghostIndex(0);
         for(int index=0;index<cellCount;index++)
           {
             const int c=toIndices[index];
             for(int cKindex=getGlobalIndex(c,0);
                 cKindex<getGlobalIndex(c,0)+totModes;
                 cKindex++)
               {
                 (*_e)[cKindex]=ghostArray[ghostIndex];
                 ghostIndex++;
               }
           }
       }
   }
template<class T> void Kspace< T >::syncLocal (const StorageSite & site) inline
Definition at line 1291 of file Kspace.h.
References Kspace< T >::_ghostArrays, Kspace< T >::createSyncGather(), Kspace< T >::get_request_size(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMap(), StorageSite::getGatherProcID(), StorageSite::getScatterMap(), StorageSite::getTag(), Kspace< T >::syncGather(), and Kspace< T >::syncScatter().
Referenced by COMETModel< T >::swapGhostInfo().
   {
     //package values to be sent/received
     syncScatter(site);
     createSyncGather(site);
 #ifdef FVM_PARALLEL
     //SENDING
     MPI::Request   request_send[get_request_size(site)];
     MPI::Request   request_recv[get_request_size(site)];
     int indxSend = 0;
     int indxRecv = 0;
     const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
     foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap)
       {
         const StorageSite&  oSite = *mpos.first;
         //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
         EntryIndex e(&site,&oSite);
         ArrayBase& sendArray = *_ghostArrays[e];
         int to_where  = oSite.getGatherProcID();
         if ( to_where != -1 )
           {
             int mpi_tag = oSite.getTag();
             request_send[indxSend++] =
               MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
           }
       }
     //RECIEVING
     //getting values from other meshes to fill g
     const StorageSite::GatherMap& gatherMap = site.getGatherMap();
     foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
       {
         const StorageSite&  oSite = *mpos.first;
         //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
         EntryIndex e(&oSite,&site);
         ArrayBase& recvArray = *_ghostArrays[e];
         int from_where       = oSite.getGatherProcID();
         if ( from_where != -1 )
           {
             int mpi_tag = oSite.getTag();
             request_recv[indxRecv++] =
               MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
           }
       }
     int count  = get_request_size(site);
     MPI::Request::Waitall( count, request_recv );
     MPI::Request::Waitall( count, request_send );
 #endif
     syncGather(site);
   }
template<class T> void Kspace< T >::syncScatter (const StorageSite & site) inline
Definition at line 1348 of file Kspace.h.
References Kspace< T >::_e, Kspace< T >::_ghostArrays, Kspace< T >::getGlobalIndex(), Array< T >::getLength(), StorageSite::getScatterMap(), and Kspace< T >::gettotmodes().
Referenced by Kspace< T >::syncLocal().
   {
     const StorageSite::ScatterMap& scatterMap = site.getScatterMap();
     const int totModes=gettotmodes();
     foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap)
       {
         const StorageSite& oSite = *mpos.first;
         EntryIndex e(&site, &oSite);
         const Array<int>& fromIndices = *(mpos.second);
         if (_ghostArrays.find(e) == _ghostArrays.end())
           _ghostArrays[e] = _e->newSizedClone( fromIndices.getLength()*totModes);
         const int cellCount = fromIndices.getLength();
         TArray& ghostArray = dynamic_cast<TArray&>(*_ghostArrays[e]);
         int ghostIndex(0);
         for(int index=0;index<cellCount;index++)
           {
             const int c=fromIndices[index];
             for(int cKindex=getGlobalIndex(c,0);
                 cKindex<getGlobalIndex(c,0)+totModes;
                 cKindex++)
               {
                 ghostArray[ghostIndex]=(*_e)[cKindex];
                 ghostIndex++;
               }
           }
       }
   }
template<class T> void Kspace< T >::updateTau (const int c, const T Tl) inline
Definition at line 1491 of file Kspace.h.
References Kspace< T >::_freqArray, Kspace< T >::_relFun, Kspace< T >::_Tau, and Kspace< T >::getGlobalIndex().
Referenced by COMETModel< T >::init(), COMETModel< T >::initCoarse(), COMETModel< T >::sete0(), and COMETDiscretizer< T >::updatee0().
   {
     const int beg=getGlobalIndex(c,0);
     const int fin=getGlobalIndex(c+1,0);
     int index(0);
     for(int i=beg;i<fin;i++)
       {
         _relFun.update(_freqArray[index],Tl,(*_Tau)[i]);
         index++;
       }
   }
template<class T> void Kspace< T >::weightArray (TArray & e) inline
Definition at line 1637 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, kvol< T >::getdk3(), Kspace< T >::getkvol(), Array< T >::getLength(), kvol< T >::getmodenum(), and Kspace< T >::gettotmodes().
Referenced by Kspace< T >::gete0CellValsPy(), Kspace< T >::geteCellValsPy(), Kspace< T >::getFullsources(), Kspace< T >::getIIsources(), Kspace< T >::getIsources(), and Kspace< T >::getSourceDeriv().
   {
     if(e.getLength()==gettotmodes())
       {
         int cnt=0;
         for(int k=0;k<_length;k++)
           {
             Tkvol& kv=getkvol(k);
             const T dk3=kv.getdk3();
             const int modenum=kv.getmodenum();
             for(int m=0;m<modenum;m++)
               {
                 e[cnt]*=dk3/_totvol;
                 cnt++;
               }
           }
       }
     else
       throw CException("Array not same length: weightArray");
   }
template<class T> void Kspace< T >::weightArray (ArrayBase * ep) inline
Definition at line 1659 of file Kspace.h.
References Kspace< T >::_length, Kspace< T >::_totvol, kvol< T >::getdk3(), Kspace< T >::getkvol(), and kvol< T >::getmodenum().
   {
     TArray& e=dynamic_cast<TArray&>(*ep);
     int cnt=0;
     for(int k=0;k<_length;k++)
       {
         Tkvol& kv=getkvol(k);
         const T dk3=kv.getdk3();
         const int modenum=kv.getmodenum();
         for(int m=0;m<modenum;m++)
           {
             e[cnt]*=dk3/_totvol;
             cnt++;
           }
       }
   }
Member Data Documentation
template<class T> Tkspace* Kspace< T >::_coarseKspace private
Definition at line 1718 of file Kspace.h.
Referenced by Kspace< T >::getCoarseKspace(), Kspace< T >::giveTransmissions(), and Kspace< T >::setCoarseKspace().
template<class T> DensityOfStates<T>* Kspace< T >::_DOS private
Definition at line 1716 of file Kspace.h.
Referenced by Kspace< T >::getDOSptr(), and Kspace< T >::setDOS().
template<class T> TArrPtr Kspace< T >::_e private
Definition at line 1719 of file Kspace.h.
Referenced by Kspace< T >::createSyncGather(), Kspace< T >::gete(), Kspace< T >::geteArray(), Kspace< T >::geteCellVals(), Kspace< T >::getnCellVals(), Kspace< T >::seteArray(), Kspace< T >::seteCellVals(), and Kspace< T >::syncScatter().
template<class T> TArrPtr Kspace< T >::_e0 private
Definition at line 1720 of file Kspace.h.
Referenced by Kspace< T >::gete0(), Kspace< T >::gete0Array(), Kspace< T >::gete0CellVals(), and Kspace< T >::sete0Array().
template<class T> TArrPtr Kspace< T >::_FASCorrection private
Definition at line 1724 of file Kspace.h.
Referenced by Kspace< T >::addFAS(), Kspace< T >::addFASint(), Kspace< T >::getFas(), Kspace< T >::getFASArray(), and Kspace< T >::setFASArray().
template<class T> TArray Kspace< T >::_freqArray private
Definition at line 1727 of file Kspace.h.
Referenced by Kspace< T >::getFreqArray(), Kspace< T >::getFreqArrayPy(), Kspace< T >::getnCellVals(), Kspace< T >::Kspace(), Kspace< T >::makeFreqArray(), and Kspace< T >::updateTau().
template<class T> GhostArrayMap Kspace< T >::_ghostArrays private
Definition at line 1726 of file Kspace.h.
Referenced by Kspace< T >::createSyncGather(), Kspace< T >::syncGather(), Kspace< T >::syncLocal(), and Kspace< T >::syncScatter().
template<class T> TArrPtr Kspace< T >::_injected private
Definition at line 1722 of file Kspace.h.
Referenced by Kspace< T >::getInj(), Kspace< T >::getInjArray(), and Kspace< T >::setInjArray().
template<class T> Volvec Kspace< T >::_Kmesh private
Definition at line 1713 of file Kspace.h.
Referenced by Kspace< T >::CopyKspace(), Kspace< T >::getkvol(), Kspace< T >::gettotmodes(), and Kspace< T >::Kspace().
template<class T> int Kspace< T >::_length private
Definition at line 1712 of file Kspace.h.
Referenced by Kspace< T >::calcBallisticInterface(), Kspace< T >::calcDiffuseE(), Kspace< T >::calcDK3(), Kspace< T >::calcLatTemp(), Kspace< T >::calcSpecificHeat(), Kspace< T >::calcTauTot(), Kspace< T >::CopyKspace(), Kspace< T >::FindBallisticHeatRate(), Kspace< T >::findKnStats(), Kspace< T >::findSpecs(), Kspace< T >::getde0taudT(), Kspace< T >::gete0(), Kspace< T >::gete0_tau(), Kspace< T >::gete0CellVars(), Kspace< T >::gete0v(), Kspace< T >::getEquilibriumArray(), Kspace< T >::getHollandConductivity(), Kspace< T >::getlength(), Kspace< T >::getModewiseBallisticConductance(), Kspace< T >::getModewiseHollandConductivity(), Kspace< T >::getReflectionArray(), Kspace< T >::getRTAsources(), Kspace< T >::getTauArrayPy(), Kspace< T >::gettotmodes(), Kspace< T >::getVelocities(), Kspace< T >::getWaveVectors(), Kspace< T >::Kspace(), Kspace< T >::makeDegenerate(), Kspace< T >::makeFreqArray(), Kspace< T >::setCp(), Kspace< T >::setCpNonGray(), Kspace< T >::setTref(), and Kspace< T >::weightArray().
template<class T> RelTimeFun<T> Kspace< T >::_relFun private
Definition at line 1728 of file Kspace.h.
Referenced by Kspace< T >::setRelTimeFunction(), and Kspace< T >::updateTau().
template<class T> TArrPtr Kspace< T >::_residual private
Definition at line 1723 of file Kspace.h.
Referenced by Kspace< T >::getRes(), Kspace< T >::getResArray(), Kspace< T >::setResArray(), and Kspace< T >::setResidCell().
template<class T> ScatteringKernel<T>* Kspace< T >::_ScattKernel private
Definition at line 1717 of file Kspace.h.
Referenced by Kspace< T >::getFullsources(), Kspace< T >::getIIsources(), Kspace< T >::getIsources(), Kspace< T >::getSourceDeriv(), Kspace< T >::getSourceTerm(), Kspace< T >::ScatterPhonons(), and Kspace< T >::setScattKernel().
template<class T> TArrPtr Kspace< T >::_Source private
Definition at line 1721 of file Kspace.h.
Referenced by Kspace< T >::addSource(), Kspace< T >::getSourceArray(), Kspace< T >::getSourceArrayPy(), and Kspace< T >::setSourceArray().
template<class T> TArrPtr Kspace< T >::_Tau private
Definition at line 1725 of file Kspace.h.
Referenced by Kspace< T >::getTau(), Kspace< T >::getTauArray(), Kspace< T >::setTauArray(), and Kspace< T >::updateTau().
template<class T> T Kspace< T >::_totvol private
Definition at line 1714 of file Kspace.h.
Referenced by Kspace< T >::calcDK3(), Kspace< T >::calcLatTemp(), Kspace< T >::CopyKspace(), Kspace< T >::findKnStats(), Kspace< T >::getde0taudT(), Kspace< T >::getDK3(), Kspace< T >::gete0(), Kspace< T >::gete0CellVars(), Kspace< T >::gete0v(), Kspace< T >::getRTAsources(), Kspace< T >::Kspace(), Kspace< T >::setCp(), and Kspace< T >::weightArray().
template<class T> TransmissionMap Kspace< T >::_transMap private
Definition at line 1715 of file Kspace.h.
Referenced by Kspace< T >::findTransmission(), Kspace< T >::getTransArray(), Kspace< T >::getTransMap(), Kspace< T >::giveTransmissions(), and Kspace< T >::setTransmission().
The documentation for this class was generated from the following file:
Kspace.h