Memosa-FVM: MultiField Class Reference
MultiField Class Reference
#include <MultiField.h>
Public Types
typedef pair< const Field
*, const StorageSite * > ArrayIndex
typedef map< ArrayIndex, int > ArrayMap
typedef vector< shared_ptr
< ArrayBase > > ArrayList
typedef vector< ArrayIndex > ArrayIndexList
typedef pair< ArrayIndex,
ArrayIndex > EntryIndex
typedef map< EntryIndex,
shared_ptr< ArrayBase > > GhostArrayMap
Public Member Functions
MultiField ()
virtual ~MultiField ()
DEFINE_TYPENAME ("MultiField")
const ArrayBase & operator[] (const ArrayIndex &) const
ArrayBase & operator[] (const ArrayIndex &)
shared_ptr< ArrayBase > getArrayPtr (const ArrayIndex &)
const ArrayBase & operator[] (const int i) const
ArrayBase & operator[] (const int i)
bool hasArray (const ArrayIndex &) const
virtual void zero ()
virtual void copyFrom (const IContainer &oc)
virtual MultiField & operator+= (const MultiField &o)
virtual MultiField & operator-= (const MultiField &o)
virtual MultiField & operator/= (const MultiFieldReduction &alpha)
virtual MultiField & operator*= (const MultiFieldReduction &alpha)
virtual shared_ptr< IContainer > newCopy () const
virtual shared_ptr< IContainer > newClone () const
int getLength () const
const ArrayIndex getArrayIndex (const int i) const
void addArray (const ArrayIndex &aIndex, shared_ptr< ArrayBase > a)
void removeArray (const ArrayIndex &aIndex)
MultiField & saxpy (const MultiFieldReduction &alphaMF, const MultiField &xMF)
MultiField & msaxpy (const MultiFieldReduction &alphaMF, const MultiField &xMF)
shared_ptr< MultiFieldReduction > reduceSum () const
shared_ptr< MultiFieldReduction > getOneNorm () const
shared_ptr< MultiFieldReduction > dotWith (const MultiField &ofield) const
const ArrayIndexList & getArrayIndices () const
shared_ptr< MultiField > extract (const ArrayIndexList &indices)
void merge (const MultiField &other)
void syncScatter (const ArrayIndex &i)
void syncGather (const ArrayIndex &i)
void sync ()
Public Member Functions inherited from IContainer
IContainer ()
virtual ~IContainer ()
IContainer & operator= (const IContainer &oc)
Private Member Functions
void createSyncGatherArrays (const ArrayIndex &i)
void syncScatterLevel1 (const ArrayIndex &i)
void createSyncGatherArraysLevel1 (const ArrayIndex &i)
void syncGatherLevel1 (const ArrayIndex &i)
int get_request_size ()
int get_request_size_scatter_level1 ()
int get_request_size_gather_level1 ()
void syncLevel1 ()
Private Attributes
int _length
ArrayList _arrays
ArrayIndexList _arrayIndices
ArrayMap _arrayMap
GhostArrayMap _ghostArrays
GhostArrayMap _ghostArraysLevel1
Detailed Description
Definition at line 17 of file MultiField.h.
Member Typedef Documentation
typedef pair<const Field*, const StorageSite*> MultiField::ArrayIndex
Definition at line 21 of file MultiField.h.
typedef vector<ArrayIndex> MultiField::ArrayIndexList
Definition at line 24 of file MultiField.h.
typedef vector<shared_ptr<ArrayBase> > MultiField::ArrayList
Definition at line 23 of file MultiField.h.
typedef map<ArrayIndex,int> MultiField::ArrayMap
Definition at line 22 of file MultiField.h.
typedef pair<ArrayIndex,ArrayIndex> MultiField::EntryIndex
Definition at line 25 of file MultiField.h.
typedef map<EntryIndex,shared_ptr<ArrayBase> > MultiField::GhostArrayMap
Definition at line 26 of file MultiField.h.
Constructor & Destructor Documentation
MultiField::MultiField ()
Definition at line 17 of file MultiField.cpp.
References logCtor.
Referenced by dotWith(), getOneNorm(), newClone(), and newCopy().
                       :
   IContainer(),
   _length(0),
   _arrays(),
   _arrayIndices(),
   _arrayMap()
 {
   logCtor();
 }
MultiField::~MultiField () virtual
Definition at line 27 of file MultiField.cpp.
References logDtor.
 {
   logDtor();
 }
Member Function Documentation
void MultiField::addArray (const ArrayIndex & aIndex, shared_ptr< ArrayBase > a)
Definition at line 270 of file MultiField.cpp.
References _arrayIndices, _arrayMap, _arrays, and _length.
Referenced by LinearSystem::createCoarse(), dotWith(), ElectricModel< T >::Impl::initChargeTransportLinearization(), FlowModel< T >::Impl::initContinuityLinearization(), PlateModel< T >::Impl::initDeformationLinearization(), StructureModel< T >::Impl::initDeformationLinearization(), ElectricModel< T >::Impl::initElectroStaticsLinearization(), KineticModel< T >::initKineticModelLinearization(), ThermalModel< T >::Impl::initLinearization(), FractureModel< T >::Impl::initLinearization(), VacancyModel< T >::Impl::initLinearization(), SpeciesModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearizationk(), FlowModel< T >::Impl::initMomentumLinearization(), BatteryModel< T >::Impl::initPCLinearization(), PhononModel< T >::initPhononModelLinearization(), BatteryModel< T >::Impl::initPotentialLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), BatteryModel< T >::Impl::initThermalLinearization(), merge(), and MultiFieldMatrix::quadProduct().
 {
   _arrayMap[i] = _length;
   _arrays.push_back(a);
   _arrayIndices.push_back(i);
   ++_length;
 }
void MultiField::copyFrom (const IContainer & oc) virtual
Implements IContainer.
Definition at line 127 of file MultiField.cpp.
References _arrayMap, ArrayBase::copyFrom(), and operator[]().
 {
   const MultiField& ofield = dynamic_cast<const MultiField&>(oc);
   foreach(ArrayMap::value_type& pos, _arrayMap)
   {
       ArrayBase& myArray = operator[](pos.second);
       const ArrayBase& oArray = ofield[pos.first];
       myArray.copyFrom(oArray);
   }
 }
void MultiField::createSyncGatherArrays (const ArrayIndex & i) private
Definition at line 386 of file MultiField.cpp.
References _arrayMap, _arrays, _ghostArrays, StorageSite::getGatherMap(), Array< T >::getLength(), and ArrayBase::newSizedClone().
Referenced by sync().
 {
   ArrayBase& thisArray = *_arrays[_arrayMap[i]];
   const StorageSite& thisSite = *i.second;
   const StorageSite::GatherMap& gatherMap = thisSite.getGatherMap();
   foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
   {
       const StorageSite& oSite = *mpos.first;
       ArrayIndex oIndex(i.first,&oSite);
       EntryIndex eIndex(oIndex,i);
      const Array<int>& toIndices = *(mpos.second);
       if (_ghostArrays.find(eIndex) == _ghostArrays.end()){
          _ghostArrays[eIndex]  = thisArray.newSizedClone(toIndices.getLength());
       }
   }
 }
void MultiField::createSyncGatherArraysLevel1 (const ArrayIndex & i) private
Definition at line 410 of file MultiField.cpp.
References _arrayMap, _arrays, _ghostArraysLevel1, StorageSite::getCountLevel1(), StorageSite::getGatherMapLevel1(), ArrayBase::getLength(), Array< T >::getLength(), and ArrayBase::newSizedClone().
Referenced by syncLevel1().
 {
   ArrayBase& thisArray = *_arrays[_arrayMap[i]];
   const StorageSite& thisSite = *i.second;
   if ( thisArray.getLength() == thisSite.getCountLevel1() ){
      const StorageSite::GatherMap& gatherMap = thisSite.getGatherMapLevel1();
      foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
      {
         const StorageSite& oSite = *mpos.first;
         ArrayIndex oIndex(i.first,&oSite);
         EntryIndex eIndex(oIndex,i);
         const Array<int>& toIndices = *(mpos.second);
         if (_ghostArraysLevel1.find(eIndex) == _ghostArraysLevel1.end()){
           _ghostArraysLevel1[eIndex]  = thisArray.newSizedClone(toIndices.getLength());
         }
      }
   }
 }
MultiField::DEFINE_TYPENAME ("MultiField")
shared_ptr< MultiFieldReduction > MultiField::dotWith (const MultiField & ofield) const
Definition at line 231 of file MultiField.cpp.
References _arrayIndices, _arrays, _length, addArray(), ArrayBase::dotWith(), StorageSite::getSelfCount(), and MultiField().
Referenced by AMG::cycle().
 {
   shared_ptr<MultiField> dotpField(new MultiField());
   for(int i=0; i<_length; i++)
   {
       const  StorageSite& thisSite = *(_arrayIndices[i].second);
       const ArrayBase& myArray = *_arrays[i];
       const ArrayBase& otherArray = ofield[_arrayIndices[i]];
       dotpField->addArray(_arrayIndices[i],
                           myArray.dotWith(otherArray, thisSite.getSelfCount()));
   }
   shared_ptr<MultiFieldReduction> r(dotpField->reduceSum());
   return r;
 }
shared_ptr< MultiField > MultiField::extract (const ArrayIndexList & indices)
Definition at line 304 of file MultiField.cpp.
References getArrayPtr(), and removeArray().
 {
   shared_ptr<MultiField> r(new MultiField);
   foreach(ArrayIndex i,indices)
   {
       r->addArray(i,getArrayPtr(i));
       removeArray(i);
   }
   return r;
 }
int MultiField::get_request_size () private
Definition at line 555 of file MultiField.cpp.
References _arrayIndices, StorageSite::getGatherProcID(), and StorageSite::getScatterMap().
Referenced by sync().
 {
    int indx = 0;
    foreach ( ArrayIndex i, _arrayIndices ){
        const  StorageSite& thisSite = *i.second;
        const StorageSite::ScatterMap& scatterMap = thisSite.getScatterMap();
        foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
            const StorageSite& oSite = *mpos.first;
            ArrayIndex oIndex(i.first,&oSite);
           // arrays are stored with (Sender,receiver) as the key
            if ( oSite.getGatherProcID() != -1 )
               indx++;
        }
     }
    return indx;
 }
int MultiField::get_request_size_gather_level1 () private
Definition at line 663 of file MultiField.cpp.
References _arrayIndices, _arrayMap, _arrays, StorageSite::getCountLevel1(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), and ArrayBase::getLength().
Referenced by syncLevel1().
 {
    int indx = 0;
    foreach ( ArrayIndex i, _arrayIndices ){
        const  StorageSite& thisSite = *i.second;
        const StorageSite::GatherMap& gatherMap = thisSite.getGatherMapLevel1();
        const ArrayBase& thisArray = *_arrays[_arrayMap[i]];
        if ( thisArray.getLength() == thisSite.getCountLevel1() ){
           foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
              const StorageSite& oSite = *mpos.first;
              ArrayIndex oIndex(i.first,&oSite);
              // arrays are stored with (Sender,receiver) as the key
              if ( oSite.getGatherProcID() != -1 )
                 indx++;
           }
        }
     }
    return indx;
 }
int MultiField::get_request_size_scatter_level1 () private
Definition at line 641 of file MultiField.cpp.
References _arrayIndices, _arrayMap, _arrays, StorageSite::getCountLevel1(), StorageSite::getGatherProcID(), ArrayBase::getLength(), and StorageSite::getScatterMapLevel1().
Referenced by syncLevel1().
 {
    int indx = 0;
    foreach ( ArrayIndex i, _arrayIndices ){
        const  StorageSite& thisSite = *i.second;
        const StorageSite::ScatterMap& scatterMap = thisSite.getScatterMapLevel1();
        const ArrayBase& thisArray = *_arrays[_arrayMap[i]];
        if ( thisArray.getLength() == thisSite.getCountLevel1() ){
           foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
              const StorageSite& oSite = *mpos.first;
              ArrayIndex oIndex(i.first,&oSite);
              // arrays are stored with (Sender,receiver) as the key
              if ( oSite.getGatherProcID() != -1 )
                indx++;
           }
        }
     }
    return indx;
 }
const ArrayIndex MultiField::getArrayIndex (const int i) const inline
Definition at line 55 of file MultiField.h.
References _arrayIndices.
Referenced by MultiFieldMatrix::computeResidual(), MultiFieldMatrix::correctSolution(), MultiFieldMatrix::createCoarseConnectivity(), MultiFieldMatrix::createCoarseMatrices(), MultiFieldMatrix::createCoarsening(), MultiFieldMatrix::createCoarseToFineMapping(), MultiFieldMatrix::forwardGS(), MultiFieldMatrix::iluSolve(), MultiFieldMatrix::injectResidual(), MultiFieldMatrix::Jacobi(), MultiFieldMatrix::multiply(), MultiFieldMatrix::multiplyAndAdd(), MultiFieldMatrix::quadProduct(), MultiFieldMatrix::reverseGS(), DirectSolver::solve(), MultiFieldMatrix::solveBoundary(), MultiFieldMatrix::spikeSolve(), and MultiFieldMatrix::syncGhostCoarsening().
 {return _arrayIndices[i];}
const ArrayIndexList& MultiField::getArrayIndices () const inline
Definition at line 68 of file MultiField.h.
References _arrayIndices.
 {return _arrayIndices;}
shared_ptr< ArrayBase > MultiField::getArrayPtr (const ArrayIndex & i)
Definition at line 67 of file MultiField.cpp.
References _arrayMap, and _arrays.
Referenced by LinearSystem::createCoarse(), and extract().
 {
   ArrayMap::const_iterator pos = _arrayMap.find(i);
   if (pos != _arrayMap.end())
   {
       return _arrays[pos->second];
   }
   ostringstream e;
   e << "MultiField::operator[] No array found";
   throw CException(e.str());
 }
int MultiField::getLength () const inline
Definition at line 54 of file MultiField.h.
References _length.
Referenced by MultiFieldMatrix::computeResidual(), MultiFieldMatrix::correctSolution(), MultiFieldMatrix::createCoarseConnectivity(), MultiFieldMatrix::createCoarseMatrices(), MultiFieldMatrix::createCoarsening(), MultiFieldMatrix::createCoarseToFineMapping(), MultiFieldMatrix::forwardGS(), MultiFieldMatrix::iluSolve(), MultiFieldMatrix::injectResidual(), MultiFieldMatrix::Jacobi(), MultiFieldMatrix::multiply(), MultiFieldMatrix::multiplyAndAdd(), MultiFieldMatrix::quadProduct(), MultiFieldMatrix::reverseGS(), DirectSolver::solve(), MultiFieldMatrix::solveBoundary(), MultiFieldMatrix::spikeSolve(), and MultiFieldMatrix::syncGhostCoarsening().
 {return _length;}
shared_ptr< MultiFieldReduction > MultiField::getOneNorm () const
Definition at line 216 of file MultiField.cpp.
References _arrayIndices, _arrays, _length, ArrayBase::getOneNorm(), StorageSite::getSelfCount(), and MultiField().
Referenced by BCGStab::solve(), ILU0Solver::solve(), JacobiSolver::solve(), CG::solve(), SpikeSolver::solve(), DirectSolver::solve(), and AMG::solve().
 {
   shared_ptr<MultiField> c(new MultiField());
   for(int i=0; i<_length; i++)
   {
       const  StorageSite& thisSite = *(_arrayIndices[i].second);
       const ArrayBase& myArray = *_arrays[i];
       c->addArray(_arrayIndices[i],
                   myArray.getOneNorm(thisSite.getSelfCount()));
   }
   shared_ptr<MultiFieldReduction> r(c->reduceSum());
   return r;
 }
bool MultiField::hasArray (const ArrayIndex & i) const
Definition at line 33 of file MultiField.cpp.
References _arrayMap.
 {
   return _arrayMap.find(i) != _arrayMap.end();
 }
void MultiField::merge (const MultiField & other)
Definition at line 316 of file MultiField.cpp.
References _arrayMap, _arrays, and addArray().
 {
   foreach(const ArrayMap::value_type& pos, other._arrayMap)
   {
       addArray(pos.first, other._arrays[pos.second]);
   }
 }
MultiField & MultiField::msaxpy (const MultiFieldReduction & alphaMF, const MultiField & xMF)
Definition at line 177 of file MultiField.cpp.
References _arrayIndices, _arrays, _length, and ArrayBase::msaxpy().
Referenced by BCGStab::solve().
 {
   for(int i=0; i<_length; i++)
   {
       ArrayBase& myArray = *_arrays[i];
       const ArrayBase& alpha = alphaMF[*_arrayIndices[i].first];
       const ArrayBase& x = xMF[_arrayIndices[i]];
       myArray.msaxpy(alpha,x);
   }
   return *this;
 }
shared_ptr< IContainer > MultiField::newClone () const virtual
Implements IContainer.
Definition at line 81 of file MultiField.cpp.
References _arrayIndices, _arrays, _length, MultiField(), and IContainer::newClone().
Referenced by MultiFieldMatrix::Jacobi().
 {
   shared_ptr<MultiField> c(new MultiField());
   for(int i=0; i<_length; i++)
   {
       const ArrayBase& myArray = *_arrays[i];
       shared_ptr<IContainer> aCloneI(myArray.newClone());
       shared_ptr<ArrayBase> aClone(dynamic_pointer_cast<ArrayBase>(aCloneI));
       if (aClone)
         c->addArray(_arrayIndices[i],aClone);
       else
       {
           throw CException("array clone failed");
       }
   }
   return c;
 }
shared_ptr< IContainer > MultiField::newCopy () const virtual
Implements IContainer.
Definition at line 101 of file MultiField.cpp.
References _arrayIndices, _arrays, _length, MultiField(), and IContainer::newCopy().
Referenced by BCGStab::solve(), and CG::solve().
 {
   shared_ptr<MultiField> c(new MultiField());
   for(int i=0; i<_length; i++)
   {
       const ArrayBase& myArray = *_arrays[i];
       shared_ptr<ArrayBase> aCopy(dynamic_pointer_cast<ArrayBase>(myArray.newCopy()));
       c->addArray(_arrayIndices[i],aCopy);
   }
   return c;
 }
MultiField & MultiField::operator*= (const MultiFieldReduction & alpha) virtual
Definition at line 204 of file MultiField.cpp.
References _arrayIndices, _arrays, and _length.
 {
   for(int i=0; i<_length; i++)
   {
       ArrayBase& myArray = *_arrays[i];
       const ArrayBase& alpha = alphaMF[*_arrayIndices[i].first];
       myArray *= alpha;
   }
   return *this;
 }
MultiField & MultiField::operator+= (const MultiField & o) virtual
Definition at line 139 of file MultiField.cpp.
References _arrayIndices, _arrays, and _length.
 {
   for(int i=0; i<_length; i++)
   {
       ArrayBase& myArray = *_arrays[i];
       const ArrayBase& oArray = ofield[_arrayIndices[i]];
       myArray += oArray;
   }
   return *this;
 }
MultiField & MultiField::operator-= (const MultiField & o) virtual
Definition at line 151 of file MultiField.cpp.
References _arrayIndices, _arrays, and _length.
 {
   for(int i=0; i<_length; i++)
   {
       ArrayBase& myArray = *_arrays[i];
       const ArrayBase& oArray = ofield[_arrayIndices[i]];
       myArray -= oArray;
   }
   return *this;
 }
MultiField & MultiField::operator/= (const MultiFieldReduction & alpha) virtual
Definition at line 192 of file MultiField.cpp.
References _arrayIndices, _arrays, and _length.
 {
   for(int i=0; i<_length; i++)
   {
       ArrayBase& myArray = *_arrays[i];
       const ArrayBase& alpha = alphaMF[*_arrayIndices[i].first];
       myArray /= alpha;
   }
   return *this;
 }
const ArrayBase & MultiField::operator[] (const ArrayIndex & i) const
Definition at line 39 of file MultiField.cpp.
References _arrayMap, and _arrays.
Referenced by copyFrom().
 {
   ArrayMap::const_iterator pos = _arrayMap.find(i);
   if (pos != _arrayMap.end())
   {
       return *_arrays[pos->second];
   }
   ostringstream e;
   e << "MultiField::operator[] No array found";
    throw CException(e.str());
 }
ArrayBase & MultiField::operator[] (const ArrayIndex & i)
Definition at line 53 of file MultiField.cpp.
References _arrayMap, and _arrays.
 {
   ArrayMap::const_iterator pos = _arrayMap.find(i);
   if (pos != _arrayMap.end())
   {
       return *_arrays[pos->second];
   }
   ostringstream e;
   e << "MultiField::operator[] No array found";
   throw CException(e.str());
 }
const ArrayBase& MultiField::operator[] (const int i) const inline
Definition at line 38 of file MultiField.h.
References _arrays.
 {return *_arrays[i];}
ArrayBase& MultiField::operator[] (const int i) inline
Definition at line 39 of file MultiField.h.
References _arrays.
 {return *_arrays[i];}
shared_ptr< MultiFieldReduction > MultiField::reduceSum () const
Definition at line 249 of file MultiField.cpp.
References _arrayIndices, _arrays, _length, and IContainer::newCopy().
Referenced by MultiFieldMatrix::quadProduct().
 {
   shared_ptr<MultiFieldReduction> sum(new MultiFieldReduction());
   for(int i=0; i<_length; i++)
   {
       const ArrayBase& myArray = *_arrays[i];
       const Field& fIndex = *_arrayIndices[i].first;
       if (sum->hasArray(fIndex))
         (*sum)[fIndex] += myArray;
       else
         sum->addArray(fIndex,dynamic_pointer_cast<ArrayBase>(myArray.newCopy()));
   }
 #ifdef FVM_PARALLEL
   sum->sync(); //global reduction operation for residual check;
 #endif
   return sum;
 }
void MultiField::removeArray (const ArrayIndex & aIndex)
Definition at line 280 of file MultiField.cpp.
References _arrayIndices, _arrayMap, _arrays, and _length.
Referenced by extract().
 {
   int loc = _arrayMap[aIndex];
   _arrays.erase(_arrays.begin()+loc);
   _arrayIndices.erase(_arrayIndices.begin()+loc);
   _arrayMap.erase(aIndex);
   for(ArrayMap::iterator pos=_arrayMap.begin();
       pos!=_arrayMap.end();
       ++pos)
   {
       int currentValue = pos->second;
       if (currentValue == loc)
         cerr << "Error in removing array" << endl;
       else if (currentValue > loc)
         pos->second = currentValue-1;
   }
   _length = _arrays.size();
 }
MultiField & MultiField::saxpy (const MultiFieldReduction & alphaMF, const MultiField & xMF)
Definition at line 163 of file MultiField.cpp.
References _arrayIndices, _arrays, _length, and ArrayBase::saxpy().
 {
   for(int i=0; i<_length; i++)
   {
       ArrayBase& myArray = *_arrays[i];
       const ArrayBase& alpha = alphaMF[*_arrayIndices[i].first];
       const ArrayBase& x = xMF[_arrayIndices[i]];
       myArray.saxpy(alpha,x);
   }
   return *this;
 }
void MultiField::sync ()
Definition at line 489 of file MultiField.cpp.
References _arrayIndices, _ghostArrays, createSyncGatherArrays(), get_request_size(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMap(), StorageSite::getGatherProcID(), StorageSite::getScatterMap(), StorageSite::getTag(), syncGather(), syncLevel1(), and syncScatter().
Referenced by LinearSystem::createCoarse(), MultiFieldMatrix::forwardGS(), MultiFieldMatrix::iluSolve(), MultiFieldMatrix::Jacobi(), MultiFieldMatrix::multiply(), MultiFieldMatrix::multiplyAndAdd(), MultiFieldMatrix::reverseGS(), AMG::solve(), and MultiFieldMatrix::spikeSolve().
 {
   foreach(ArrayIndex i, _arrayIndices)
     syncScatter(i);
   foreach(ArrayIndex i, _arrayIndices)
         createSyncGatherArrays(i);
 #ifdef FVM_PARALLEL
   //this communication is based on assumption that MPI communication will be only done inside the same field
   //SENDING
    MPI::Request   request_send[ get_request_size() ];
    MPI::Request   request_recv[ get_request_size() ];
    int sendIndx = 0;
    int recvIndx = 0;
    foreach ( ArrayIndex i, _arrayIndices ){
        const  StorageSite& thisSite = *i.second;
        const StorageSite::ScatterMap& scatterMap = thisSite.getScatterMap();
        foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
            const StorageSite& oSite = *mpos.first;
            ArrayIndex oIndex(i.first,&oSite);
           // arrays are stored with (Sender,receiver) as the key
              EntryIndex eIndex(i,oIndex);
              ArrayBase& sendArray = *_ghostArrays[eIndex];
              int to_where  = oSite.getGatherProcID();
              if ( to_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_send[sendIndx++] =
                        MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
              }
        }
      //RECIEVING
       const StorageSite::GatherMap& gatherMap = thisSite.getGatherMap();
       foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
            const StorageSite& oSite = *mpos.first;
            ArrayIndex oIndex(i.first,&oSite);
              EntryIndex eIndex(oIndex,i);
              ArrayBase& recvArray = *_ghostArrays[eIndex];
              int from_where  = oSite.getGatherProcID();
              if ( from_where != -1 ){
                  int mpi_tag = oSite.getTag();
                  request_recv[recvIndx++] =
                        MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
              }
       }
    }
    int count   = get_request_size();
    MPI::Request::Waitall( count, request_recv );
    MPI::Request::Waitall( count, request_send );
 #endif
   foreach(ArrayIndex i, _arrayIndices)
     syncGather(i);
   //syncLevel1
   syncLevel1();
 }
void MultiField::syncGather (const ArrayIndex & i)
Definition at line 436 of file MultiField.cpp.
References _arrayMap, _arrays, _ghostArrays, ArrayBase::gather(), and StorageSite::getGatherMap().
Referenced by MultiFieldMatrix::forwardGS(), MultiFieldMatrix::reverseGS(), and sync().
 {
   ArrayBase& thisArray = *_arrays[_arrayMap[i]];
   const StorageSite& thisSite = *i.second;
   const StorageSite::GatherMap& gatherMap = thisSite.getGatherMap();
   foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
   {
       const StorageSite& oSite = *mpos.first;
       ArrayIndex oIndex(i.first,&oSite);
       const Array<int>& toIndices = *(mpos.second);
       EntryIndex eIndex(oIndex,i);
       if (_ghostArrays.find(eIndex) != _ghostArrays.end()){
           const ArrayBase& ghostArray = *_ghostArrays[eIndex];
           thisArray.gather(ghostArray,toIndices);
       }
   }
 }
void MultiField::syncGatherLevel1 (const ArrayIndex & i) private
Definition at line 461 of file MultiField.cpp.
References _arrayMap, _arrays, _ghostArraysLevel1, ArrayBase::gather(), StorageSite::getCountLevel1(), StorageSite::getGatherMapLevel1(), and ArrayBase::getLength().
Referenced by syncLevel1().
 {
   ArrayBase& thisArray = *_arrays[_arrayMap[i]];
   const StorageSite& thisSite = *i.second;
   if ( thisArray.getLength() == thisSite.getCountLevel1() ){
      const StorageSite::GatherMap& gatherMap = thisSite.getGatherMapLevel1();
      foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap)
      {
         const StorageSite& oSite = *mpos.first;
         ArrayIndex oIndex(i.first,&oSite);
         const Array<int>& toIndices = *(mpos.second);
         EntryIndex eIndex(oIndex,i);
         if (_ghostArraysLevel1.find(eIndex) != _ghostArraysLevel1.end()){
            const ArrayBase& ghostArray = *_ghostArraysLevel1[eIndex];
            thisArray.gather(ghostArray,toIndices);
         }
      }
   }
 }
void MultiField::syncLevel1 () private
Definition at line 575 of file MultiField.cpp.
References _arrayIndices, _arrayMap, _arrays, _ghostArraysLevel1, createSyncGatherArraysLevel1(), get_request_size_gather_level1(), get_request_size_scatter_level1(), StorageSite::getCountLevel1(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), ArrayBase::getLength(), StorageSite::getScatterMapLevel1(), StorageSite::getTag(), syncGatherLevel1(), and syncScatterLevel1().
Referenced by sync().
 {
   foreach(ArrayIndex i, _arrayIndices)
     syncScatterLevel1(i);
   foreach(ArrayIndex i, _arrayIndices)
         createSyncGatherArraysLevel1(i);
 #ifdef FVM_PARALLEL
   //this communication is based on assumption that MPI communication will be only done inside the same field
   //SENDING
    int countScatter   = get_request_size_scatter_level1();
    int countGather    = get_request_size_gather_level1();
    MPI::Request   request_send[ countScatter ];
    MPI::Request   request_recv[ countGather  ];
    int sendIndx = 0;
    int recvIndx = 0;
    foreach ( ArrayIndex i, _arrayIndices ){
        const  StorageSite& thisSite = *i.second;
        const StorageSite::ScatterMap& scatterMap = thisSite.getScatterMapLevel1();
        const ArrayBase& thisArray = *_arrays[_arrayMap[i]];
        if ( thisArray.getLength() == thisSite.getCountLevel1() ){
           foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
              const StorageSite& oSite = *mpos.first;
              ArrayIndex oIndex(i.first,&oSite);
              // arrays are stored with (Sender,receiver) as the key
              EntryIndex eIndex(i,oIndex);
              ArrayBase& sendArray = *_ghostArraysLevel1[eIndex];
              int to_where  = oSite.getGatherProcID();
              if ( to_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_send[sendIndx++] =
                        MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
              }
           }
          //RECIEVING
          const StorageSite::GatherMap& gatherMap = thisSite.getGatherMapLevel1();
          foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
             const StorageSite& oSite = *mpos.first;
             ArrayIndex oIndex(i.first,&oSite);
             EntryIndex eIndex(oIndex,i);
             ArrayBase& recvArray = *_ghostArraysLevel1[eIndex];
             int from_where  = oSite.getGatherProcID();
             if ( from_where != -1 ){
                int mpi_tag = oSite.getTag();
                request_recv[recvIndx++] =
                      MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
            }
          }
      }
    }
    MPI::Request::Waitall( countGather, request_recv );
    MPI::Request::Waitall( countScatter , request_send );
 #endif
   foreach(ArrayIndex i, _arrayIndices)
     syncGatherLevel1(i);
 }
void MultiField::syncScatter (const ArrayIndex & i)
Definition at line 325 of file MultiField.cpp.
References _arrayMap, _arrays, _ghostArrays, Array< T >::getLength(), StorageSite::getScatterMap(), ArrayBase::newSizedClone(), and ArrayBase::scatter().
Referenced by MultiFieldMatrix::forwardGS(), MultiFieldMatrix::reverseGS(), and sync().
 {
   const  ArrayBase& thisArray  = *_arrays[_arrayMap[i]];
   const  StorageSite& thisSite = *i.second;
   const StorageSite::ScatterMap& scatterMap = thisSite.getScatterMap();
   foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap)
   {
       const StorageSite& oSite = *mpos.first;
       ArrayIndex oIndex(i.first,&oSite);
       // skip if the other site is not in this Multifield
       //if (!hasArray(oIndex))
       //  continue;
       // arrays are stored with (Sender,receiver) as the key
       EntryIndex eIndex(i,oIndex);
       const Array<int>& fromIndices = *(mpos.second);
       if (_ghostArrays.find(eIndex) == _ghostArrays.end()){
         _ghostArrays[eIndex] = thisArray.newSizedClone(fromIndices.getLength());
       }
       ArrayBase& ghostArray = *_ghostArrays[eIndex];
       thisArray.scatter(ghostArray,fromIndices);
   }
 }
void MultiField::syncScatterLevel1 (const ArrayIndex & i) private
Definition at line 358 of file MultiField.cpp.
References _arrayMap, _arrays, _ghostArraysLevel1, StorageSite::getCountLevel1(), ArrayBase::getLength(), Array< T >::getLength(), StorageSite::getScatterMapLevel1(), ArrayBase::newSizedClone(), and ArrayBase::scatter().
Referenced by syncLevel1().
 {
   const  ArrayBase& thisArray  = *_arrays[_arrayMap[i]];
   const  StorageSite& thisSite = *i.second;
   if ( thisArray.getLength() == thisSite.getCountLevel1() ){
      const StorageSite::ScatterMap& scatterMap = thisSite.getScatterMapLevel1();
      foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap)
      {
         const StorageSite& oSite = *mpos.first;
         ArrayIndex oIndex(i.first,&oSite);
         // arrays are stored with (Sender,receiver) as the key
         EntryIndex eIndex(i,oIndex);
         const Array<int>& fromIndices = *(mpos.second);
         if (_ghostArraysLevel1.find(eIndex) == _ghostArraysLevel1.end()){
           _ghostArraysLevel1[eIndex] = thisArray.newSizedClone(fromIndices.getLength());
         }
         ArrayBase& ghostArray = *_ghostArraysLevel1[eIndex];
         thisArray.scatter(ghostArray,fromIndices);
      }
   }
 }
void MultiField::zero () virtual
Implements IContainer.
Definition at line 115 of file MultiField.cpp.
References _arrays, _ghostArrays, and _length.
Referenced by StructureModel< T >::Impl::advanceExplicit(), LinearSystem::createCoarse(), AMG::cycle(), and BCGStab::solve().
 {
   for(int i=0; i<_length; i++)
     _arrays[i]->zero();
   foreach(GhostArrayMap::value_type& pos, _ghostArrays)
   {
       pos.second->zero();
   }
 }
Member Data Documentation
ArrayIndexList MultiField::_arrayIndices private
Definition at line 93 of file MultiField.h.
Referenced by addArray(), dotWith(), get_request_size(), get_request_size_gather_level1(), get_request_size_scatter_level1(), getArrayIndex(), getArrayIndices(), getOneNorm(), msaxpy(), newClone(), newCopy(), operator*=(), operator+=(), operator-=(), operator/=(), reduceSum(), removeArray(), saxpy(), sync(), and syncLevel1().
ArrayMap MultiField::_arrayMap private
Definition at line 94 of file MultiField.h.
Referenced by addArray(), copyFrom(), createSyncGatherArrays(), createSyncGatherArraysLevel1(), get_request_size_gather_level1(), get_request_size_scatter_level1(), getArrayPtr(), hasArray(), merge(), operator[](), removeArray(), syncGather(), syncGatherLevel1(), syncLevel1(), syncScatter(), and syncScatterLevel1().
ArrayList MultiField::_arrays private
Definition at line 92 of file MultiField.h.
Referenced by addArray(), createSyncGatherArrays(), createSyncGatherArraysLevel1(), dotWith(), get_request_size_gather_level1(), get_request_size_scatter_level1(), getArrayPtr(), getOneNorm(), merge(), msaxpy(), newClone(), newCopy(), operator*=(), operator+=(), operator-=(), operator/=(), operator[](), reduceSum(), removeArray(), saxpy(), syncGather(), syncGatherLevel1(), syncLevel1(), syncScatter(), syncScatterLevel1(), and zero().
GhostArrayMap MultiField::_ghostArrays private
Definition at line 95 of file MultiField.h.
Referenced by createSyncGatherArrays(), sync(), syncGather(), syncScatter(), and zero().
GhostArrayMap MultiField::_ghostArraysLevel1 private
Definition at line 96 of file MultiField.h.
Referenced by createSyncGatherArraysLevel1(), syncGatherLevel1(), syncLevel1(), and syncScatterLevel1().
int MultiField::_length private
Definition at line 91 of file MultiField.h.
Referenced by addArray(), dotWith(), getLength(), getOneNorm(), msaxpy(), newClone(), newCopy(), operator*=(), operator+=(), operator-=(), operator/=(), reduceSum(), removeArray(), saxpy(), and zero().
The documentation for this class was generated from the following files:
MultiField.h
MultiField.cpp