Memosa-FVM: StorageSite Class Reference
StorageSite Class Reference
#include <StorageSite.h>
Public Types
typedef map< const StorageSite
*, shared_ptr< Array< int > > > ScatterMap
typedef map< const StorageSite
*, shared_ptr< Array< int > > > GatherMap
typedef map< const StorageSite
*, shared_ptr< Array< int > > > CommonMap
typedef map< const StorageSite
*, const Mesh * > MeshMap
typedef map< const StorageSite
*, map< int, int > > ScatterIndex
Public Member Functions
StorageSite (const int selfCount, const int nGhost=0, const int offset=0, const StorageSite *parent=0)
virtual ~StorageSite ()
DEFINE_TYPENAME ("StorageSite")
int getCount () const
int getSelfCount () const
void setCount (const int selfCount, const int nGhost=0)
void setScatterProcID (int proc_id)
void setGatherProcID (int proc_id)
void setTag (int tag)
void setMesh (const Mesh *mesh)
const Mesh & getMesh () const
const ScatterMap & getScatterMap () const
const GatherMap & getGatherMap () const
const CommonMap & getCommonMap () const
const ScatterIndex & getScatterIndex () const
ScatterMap & getScatterMap ()
GatherMap & getGatherMap ()
CommonMap & getCommonMap ()
ScatterIndex & getScatterIndex ()
void setCountLevel1 (const int countLevel1)
int getCountLevel1 () const
const ScatterMap & getScatterMapLevel1 () const
const GatherMap & getGatherMapLevel1 () const
ScatterMap & getScatterMapLevel1 ()
GatherMap & getGatherMapLevel1 ()
void clearGatherScatterMaps ()
int getScatterProcID () const
int getGatherProcID () const
int getTag () const
const StorageSite *const getParent () const
int getOffset () const
Private Member Functions
StorageSite (const StorageSite &)
Private Attributes
int _count
int _selfCount
const int _offset
const StorageSite *const _parent
ScatterMap _scatterMap
GatherMap _gatherMap
CommonMap _commonMap
ScatterIndex _scatterIndex
MeshMap _meshMap
int _countLevel1
ScatterMap _scatterMapLevel1
GatherMap _gatherMapLevel1
int _scatterProcID
int _gatherProcID
int _tag
Detailed Description
Definition at line 18 of file StorageSite.h.
Member Typedef Documentation
typedef map< const StorageSite*, shared_ptr< Array<int> > > StorageSite::CommonMap
Definition at line 25 of file StorageSite.h.
typedef map< const StorageSite*, shared_ptr< Array<int> > > StorageSite::GatherMap
Definition at line 24 of file StorageSite.h.
typedef map< const StorageSite*, const Mesh* > StorageSite::MeshMap
Definition at line 26 of file StorageSite.h.
typedef map< const StorageSite*, map<int,int> > StorageSite::ScatterIndex
Definition at line 29 of file StorageSite.h.
typedef map< const StorageSite*, shared_ptr< Array<int> > > StorageSite::ScatterMap
Definition at line 23 of file StorageSite.h.
Constructor & Destructor Documentation
StorageSite::StorageSite (const int selfCount, const int nGhost = 0, const int offset = 0, const StorageSite * parent = 0)
Definition at line 9 of file StorageSite.cpp.
References _count, and logCtorVerbose.
                                                                      :
   _count(selfCount+nGhost),
   _selfCount(selfCount),
   _offset(offset),
   _parent(parent),
   _countLevel1(_count),
   _scatterProcID(-1),
   _gatherProcID(-1),
   _tag(-1)
 {
   logCtorVerbose("of size %d", _count);
 }
StorageSite::~StorageSite () virtual
Definition at line 23 of file StorageSite.cpp.
References _count, and logDtorVerbose.
 {
   logDtorVerbose("of size %d" ,_count);
 }
StorageSite::StorageSite (const StorageSite &) private
Member Function Documentation
void StorageSite::clearGatherScatterMaps ()
Definition at line 30 of file StorageSite.cpp.
References _gatherMap, and _scatterMap.
 {
   _gatherMap.clear();
   _scatterMap.clear();
 }
StorageSite::DEFINE_TYPENAME ("StorageSite")
const CommonMap& StorageSite::getCommonMap () const inline
Definition at line 60 of file StorageSite.h.
References _commonMap.
Referenced by COMETModel< T >::coarsenInterfaceCells(), Mesh::COMETfindCommonFaces(), MeshPartitioner::extractBoundaryMesh(), Mesh::extractBoundaryMesh(), Mesh::findCommonFaces(), Mesh::findCommonNodes(), PlateDeformationModel< T >::getCommon(), StructureDeformationModel< T >::getCommon(), COMETInterface< T >::makeCoarseCoeffs(), COMETModel< T >::MakeInteriorCoarseMesh(), COMETModel< T >::setLocalScatterMaps(), StructureDeformationModel< T >::updateBoundaryMesh(), COMETInterface< T >::updateOtherGhost(), and COMETInterface< T >::updateResid().
 { return _commonMap; }
CommonMap& StorageSite::getCommonMap () inline
Definition at line 65 of file StorageSite.h.
References _commonMap.
 { return _commonMap; }
int StorageSite::getCount () const inline
Definition at line 39 of file StorageSite.h.
References _count.
Referenced by Field::_create(), AABB::AABB(), MovingMeshModel< T >::advance(), RosselandModel< T >::Impl::advance(), IdealGasDensityModel< T >::Impl::advance(), StructureModel< T >::Impl::applyBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyConvectionBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyDielectricInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyDiffuseWallBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyDirichletBC(), PlateBCS< X, Diag, OffDiag >::applyDirichletBC(), StructureBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyDirichletBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyDirichletBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyExtrapolationBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyFlowBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyFlowBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyFlowBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyInletBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyInterfaceBC(), StructureBCS< X, Diag, OffDiag >::applyInterfaceBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyInterfaceBC(), PhononInterface< X >::applyInterfaceCondition(), StructureBCS< X, Diag, OffDiag >::applyNeumannBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyNeumannBC(), PlateBCS< X, Diag, OffDiag >::applyNeumannBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyNonzeroDiagBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyNonzeroDiagBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyNonzeroDiagBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyNSInterfaceBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyPressureOutletBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), PhononBoundary< X >::applyReflectingWall(), BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationDirichletBC(), BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applySpecularWallBC(), StructureBCS< X, Diag, OffDiag >::applySymmetryBC(), PlateBCS< X, Diag, OffDiag >::applySymmetryBC(), GenericBCS< X, Diag, OffDiag >::applySymmetryBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applySymmetryBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::applySymmetryBC(), GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::applySymmetryBC(), PhononBoundary< X >::applyTemperatureWall(), COMETBoundary< T >::applyTemperatureWallCoarse(), COMETBoundary< T >::applyTemperatureWallFine(), StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC(), PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC(), KineticBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC(), COMETModel< T >::binwiseHeatFluxIntegral(), COMETModel< T >::calcBandFlux(), COMETModel< T >::calcBandRelEnergy(), COMETModel< T >::calcBandTemps(), COMETModel< T >::calcDomainStats(), COMETModel< T >::calcModeFlux(), COMETModel< T >::calcModeTemps(), MeshMetricsCalculator< T >::calculateBoundaryNodeNormal(), MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), MeshMetricsCalculator< T >::calculateFaceAreaMag(), MeshMetricsCalculator< T >::calculateFaceAreas(), MeshMetricsCalculator< T >::calculateFaceCentroids(), MeshMetricsCalculator< T >::calculateNodeCoordinates(), StructureDeformationModel< T >::calculateNodeDisplacement(), PlateDeformationModel< T >::calculateNodeDisplacement(), CellMark_Impl(), COMETModel< T >::coarsenInterfaceCells(), Mesh::COMETfindCommonFaces(), COMETModel< T >::COMETModel(), PhononModel< T >::COMETupdateTL(), GradientModel< Vector< T, 3 > >::compute(), COMETModel< T >::ComputeCoarseMacroparameters(), COMETModel< T >::ComputeCollisionfrequency(), COMETModel< T >::ComputeCOMETMacroparameters(), FlowModel< T >::Impl::computeContinuityResidual(), COMETModel< T >::ComputeFineMacroparameters(), VacancyModel< T >::Impl::computeIBFaceConcentration(), KineticModel< T >::computeIBFaceDsf(), COMETModel< T >::computeIBFaceDsf(), ElectricModel< T >::Impl::computeIBFacePotential(), ThermalModel< T >::Impl::computeIBFaceTemperature(), FlowModel< T >::Impl::computeIBFaceVelocity(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), Grid::computeInterpolatedVelocity(), COMETModel< T >::ComputeMacroparameters(), COMETModel< T >::ComputeMacroparametersESBGK(), MultiFieldMatrix::computeResidual(), KineticModel< T >::computeSolidFaceDsf(), COMETModel< T >::computeSolidFaceDsf(), KineticModel< T >::computeSolidFacePressure(), COMETModel< T >::computeSolidFacePressure(), MeshMetricsCalculator< T >::computeSolidInterpolationMatrices(), ContactModel< T >::Impl::computeSolidSurfaceForce(), ElectricModel< T >::Impl::computeSolidSurfaceForce(), FlowModel< T >::Impl::computeSolidSurfaceForce(), FlowModel< T >::Impl::ComputeStressTensorES(), KineticModel< T >::computeSurfaceForce(), COMETModel< T >::computeSurfaceForce(), StructureModel< T >::Impl::computeVMStress(), KineticModel< T >::ConservationofMassCheck(), COMETModel< T >::ConservationofMassCheck(), KineticModel< T >::ConservationofMFSolid(), COMETModel< T >::ConservationofMFSolid(), BatteryModel< T >::Impl::copyCoupledToSeparate(), BatteryModel< T >::Impl::copyPCDiffusivity(), BatteryModel< T >::Impl::copySeparateToCoupled(), KineticModel< T >::correctMassDeficit(), COMETModel< T >::correctMassDeficit(), FlowModel< T >::Impl::correctMassFluxBoundary(), correctMassFluxInterior(), COMETModel< T >::correctSingleNeighbor(), COMETModel< T >::correctSolution(), FlowModel< T >::Impl::correctVelocityBoundary(), FlowModel< T >::Impl::correctVelocityExplicit(), correctVelocityInterior(), MeshAssembler::countInterfaceNodes(), Octree::Create(), Mesh::createAndGetBNglobalToLocal(), Mesh::createCellColor(), LinearSystem::createCoarse(), CRMatrixRect< T_Coeff, X, B >::createCoarseConnectivity(), Grid::createConnectivity(), IBManager::createIBFaces(), IBManager::createIBInterpolationStencil(), MeshDismantler::createInteriorFaceGroup(), Mesh::createLocalToGlobalNodesArray(), Mesh::createRowColSiteCRConn(), IBManager::createSolidInterpolationStencil(), StructureModel< T >::Impl::creepInit(), MeshPartitioner::DEBUG_cellcells_global(), MeshDismantler::debug_face_cells(), MeshDismantler::debug_face_nodes(), debug_mesh(), StructureDeformationModel< T >::deformMeshStructure(), PlateDeformationModel< T >::deformMeshStructure(), PlateDeformationModel< T >::deformPlate(), StructureDeformationModel< T >::deformStructure(), TrapBandTunnelingDiscretization< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJump< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), DriftDiscretization< X, Diag, OffDiag >::discretize(), GenericIBDiscretization< X, Diag, OffDiag >::discretize(), PhononConvectionDiscretization< X, Diag, OffDiag >::discretize(), BatteryLinearizeThermalInterface< X, Diag, OffDiag >::discretize(), BatteryLinearizePotentialInterface< X, Diag, OffDiag >::discretize(), ConvectionDiscretization< X, Diag, OffDiag >::discretize(), LinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryPCLinearizeInterface_BV< X, Diag, OffDiag, otherMeshDiag >::discretize(), SourceDiscretizationene< X >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), BatteryLinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), LinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), MomentumPressureGradientDiscretization< X >::discretize(), BatteryElectricDiffusionDiscretization< X, Diag, OffDiag >::discretize(), ElecDiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), SourceDiscretizationdissi< X, Diag, OffDiag >::discretize(), InjectionDiscretization< X, Diag, OffDiag >::discretize(), TunnelingDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize(), WallDiscretization< X, Diag, OffDiag >::discretize(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), discretizeMassFluxInterior(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateBoundaryEquations(), COMETModel< T >::EntropyGeneration(), COMETModel< T >::equilibrate(), COMETModel< T >::EquilibriumDistributionBGK(), COMETModel< T >::EquilibriumDistributionESBGK(), MeshPartitioner::extractBoundaryMesh(), Mesh::extractBoundaryMesh(), Mesh::extrude(), MeshDismantler::faceCellsAddBoundaryInterfaces(), MeshDismantler::faceCellsAddInteriorFaces(), MeshDismantler::faceCellsAddMeshInterfaces(), MeshDismantler::faceCellsAddPartitionInterfaces(), MeshDismantler::faceCellsInit(), MeshDismantler::faceNodesAddBoundaryInterfaces(), MeshDismantler::faceNodesAddInteriorFaces(), MeshDismantler::faceNodesAddMeshInterfaces(), MeshDismantler::faceNodesAddPartitionInterfaces(), MeshDismantler::faceNodesInit(), Mesh::findCommonFaces(), Mesh::findCommonNodes(), IBManager::findNearestCellForSolidFaces(), Grid::findNeighborsByCells(), COMETModel< T >::FinishCoarseMesh(), fixedFluxContinuityBC(), fixedPressureContinuityBC(), fixedPressureMomentumBC(), BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), Mesh::getBoundaryNodes(), Mesh::getCellCells2(), Mesh::getFaceCells(), BatteryModel< T >::Impl::getFaceGroupArea(), BatteryModel< T >::Impl::getFaceGroupVoltage(), Mesh::getFaceNodes(), ThermalModel< T >::Impl::getHeatFluxIntegral(), BatteryModel< T >::Impl::getHeatFluxIntegral(), MeshAssembler::getInnerNodesCount(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D(), CRConnectivity::getLocalizedSubsetOfFaceCells(), SpeciesModel< T >::Impl::getMassFluxIntegral(), BatteryModel< T >::Impl::getMassFluxIntegral(), FlowModel< T >::Impl::getMomentumFluxIntegral(), FlowModel< T >::Impl::getMomentumFluxIntegralonIBFaces(), ElectricModel< T >::Impl::getPotentialFluxIntegral(), BatteryModel< T >::Impl::getPotentialFluxIntegral(), FlowModel< T >::Impl::getPressureIntegral(), FlowModel< T >::Impl::getPressureIntegralonIBFaces(), StructureModel< T >::Impl::getStrain(), StructureModel< T >::Impl::getTraction(), Mesh::getUpdatedNodesCoordCoupling(), VacancyModel< T >::Impl::getVacaFluxIntegral(), KeModel< T >::Impl::getViscosity(), COMETModel< T >::getWallArea(), COMETModel< T >::getWallAreaVector(), MeshPartitioner::globalCellID_procID_map(), Grid::Grid(), PhononModel< T >::HeatFluxIntegral(), COMETModel< T >::HeatFluxIntegral(), Octree::Impl(), MeshMetricsCalculator< T >::init(), PartMesh::init(), ThermalModel< T >::Impl::init(), FractureModel< T >::Impl::init(), VacancyModel< T >::Impl::init(), MeshPartitioner::init(), SpeciesModel< T >::Impl::init(), KeModel< T >::Impl::init(), PhononModel< T >::init(), KineticModel< T >::init(), ElectricModel< T >::Impl::init(), FlowModel< T >::Impl::init(), BatteryModel< T >::Impl::init(), COMETModel< T >::init(), PlateDeformationModel< T >::init(), StructureDeformationModel< T >::init(), StructureModel< T >::Impl::init(), PlateModel< T >::Impl::init(), MovingMeshModel< T >::init(), ElectricModel< T >::Impl::initChargeTransportLinearization(), COMETModel< T >::initCoarse(), FlowModel< T >::Impl::initContinuityLinearization(), ElectricModel< T >::Impl::initElectroStaticsLinearization(), COMETModel< T >::initFromOld(), COMETModel< T >::initializeCoarseMaxwellian(), COMETModel< T >::InitializeFgammaCoefficients(), COMETModel< T >::initializeFineMaxwellian(), COMETModel< T >::InitializeMacroparameters(), COMETModel< T >::initializeMaxwellian(), COMETModel< T >::initializeMaxwellianEq(), ThermalModel< T >::Impl::initLinearization(), FractureModel< T >::Impl::initLinearization(), VacancyModel< T >::Impl::initLinearization(), SpeciesModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearizationk(), FlowModel< T >::Impl::initMomentumLinearization(), BatteryModel< T >::Impl::initPCLinearization(), BatteryModel< T >::Impl::initPotentialLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), BatteryModel< T >::Impl::initThermalLinearization(), COMETModel< T >::injectResid(), FlowModel< T >::Impl::interfaceContinuityBC(), MeshPartitioner::level1_scatter_gather_cells(), ThermalModel< T >::Impl::linearize(), FractureModel< T >::Impl::linearize(), VacancyModel< T >::Impl::linearize(), SpeciesModel< T >::Impl::linearize(), FlowModel< T >::Impl::linearizeContinuity(), PlateModel< T >::Impl::linearizeDeformation(), KeModel< T >::Impl::linearizedissipation(), ElectricModel< T >::Impl::linearizeElectroStatics(), KeModel< T >::Impl::linearizeenergy(), KineticModel< T >::linearizeKineticModel(), FlowModel< T >::Impl::linearizeMomentum(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), PhononModel< T >::linearizePhononModel(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), BatteryModel< T >::Impl::linearizeThermal(), CRConnectivity::localize(), KineticModel< T >::MacroparameterIBCell(), COMETModel< T >::makeCellColors(), COMETInterface< T >::makeCoarseCoeffs(), COMETModel< T >::MakeCoarseIndex(), COMETModel< T >::MakeCoarseMesh1(), COMETModel< T >::MakeCoarseMesh2(), COMETModel< T >::MakeCoarseModel(), COMETInterface< T >::makeDMMcoeffs(), COMETModel< T >::MakeIBCoarseModel(), COMETModel< T >::MakeInteriorCoarseMesh(), COMETInterface< T >::makeNoInterfaceCoeffs(), COMETModel< T >::makePlotColors(), IBManager::markFluid(), IBManager::markIntersections(), PartMesh::mesh_file(), MeshPartitioner::mesh_file(), AABB::meshIntersections(), COMETModel< T >::modewiseHeatFluxIntegral(), COMETModel< T >::MomentHierarchy(), CRMatrix< T_Diag, T_OffDiag, X >::multiply(), CRMatrixTranspose< T_Coeff, X, B >::multiplyAndAdd(), CRMatrix< T_Diag, T_OffDiag, X >::multiplyAndAdd(), COMETModel< T >::NewtonsMethodBGK(), COMETModel< T >::NewtonsMethodESBGK(), PhononModel< T >::PhononModel(), pressureBoundaryPostContinuitySolve(), FlowModel< T >::Impl::printMassFluxIntegrals(), BatteryModel< T >::Impl::printMatrixElementsOnFace(), FlowModel< T >::Impl::printMomentumFluxIntegrals(), FlowModel< T >::Impl::printPressureIntegrals(), PhononModel< T >::printTemp(), COMETModel< T >::sameFaceGroup(), MeshPartitioner::set_cellcells_global(), MeshAssembler::setCellsMapper(), MeshAssembler::setCellsSite(), MeshDismantler::setCellsSite(), Mesh::setCommonFacesMap(), MeshAssembler::setCoord(), MeshDismantler::setCoord(), MeshAssembler::setFaceCells(), MeshAssembler::setFaceNodes(), MeshAssembler::setFacesSite(), MeshDismantler::setFacesSite(), COMETDiscretizer< T >::setfgFinder(), COMETESBGKDiscretizer< T >::setfgFinder(), setibFaceCells(), setibFaceParticles(), MeshAssembler::setInterfaceNodes(), COMETModel< T >::setLocalScatterMaps(), MeshAssembler::setMeshCellColor(), PartMesh::setMeshColors(), MeshPartitioner::setMeshColors(), Mesh::setNodeRepeationArrayCoupling(), MeshAssembler::setNodesMapper(), MeshDismantler::setNodesMapper(), MeshDismantler::setNodesSite(), setParticleCells(), COMETModel< T >::setStraightLine(), slipJumpMomentumBC(), CRMatrix< T_Diag, T_OffDiag, X >::solveBoundary(), SpikeStorage::syncCellIDs(), COMETModel< T >::syncGhostCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::transpose(), Mesh::uniqueFaceCells(), IBManager::update(), StructureDeformationModel< T >::updateBoundaryMesh(), PlateDeformationModel< T >::updateBoundaryMesh(), ElectricModel< T >::Impl::updateConvectionFlux(), PhononModel< T >::updatee0(), updateFacePressureBoundary(), updateFacePressureInterior(), StructureModel< T >::Impl::updateForceOnBoundary(), PhononModel< T >::updateHeatFlux(), COMETInterface< T >::updateOtherGhost(), COMETInterface< T >::updateResid(), BatteryModel< T >::Impl::updateShellGhosts(), PhononModel< T >::updateTL(), COMETModel< T >::updateTL(), MovingMeshModel< T >::volChange(), VTKWriter< T >::VTKWriter(), and COMETModel< T >::weightedMaxwellian().
 {return _count;}
int StorageSite::getCountLevel1 () const inline
Definition at line 72 of file StorageSite.h.
References _countLevel1.
Referenced by MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), ElectricModel< T >::Impl::calculateEquilibriumParameters(), PlateModel< T >::Impl::calculatePlateAcceleration(), PlateModel< T >::Impl::calculatePlateVelocity(), KineticModel< T >::ComputeCollisionfrequency(), COMETModel< T >::computeIBFaceDsf(), KineticModel< T >::ComputeMacroparameters(), KineticModel< T >::ComputeMacroparametersESBGK(), VacancyModel< T >::Impl::computePlasticStrainRate(), COMETModel< T >::computeSolidFaceDsf(), KineticModel< T >::ConservationofMassCheck(), COMETModel< T >::ConservationofMassCheck(), FlowModel< T >::Impl::correctPressure(), FlowModel< T >::Impl::correctVelocityExplicit(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseConnectivity(), MultiFieldMatrix::createCoarseToFineMapping(), Mesh::createLocalGlobalArray(), MultiField::createSyncGatherArraysLevel1(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), PlateSourceDiscretization< T, Diag, OffDiag >::discretize(), DistFunctFields< X >::DistFunctFields(), KineticModel< T >::EntropyGeneration(), KineticModel< T >::EquilibriumDistributionBGK(), KineticModel< T >::EquilibriumDistributionESBGK(), ElectricModel< T >::Impl::generateBandDiagram(), MultiField::get_request_size_gather_level1(), MultiField::get_request_size_scatter_level1(), Mesh::getCellCells2(), PlateModel< T >::Impl::getMoment(), MeshMetricsCalculator< T >::init(), ThermalModel< T >::Impl::init(), FractureModel< T >::Impl::init(), VacancyModel< T >::Impl::init(), KineticModel< T >::init(), ElectricModel< T >::Impl::init(), FlowModel< T >::Impl::init(), COMETModel< T >::init(), StructureModel< T >::Impl::init(), PlateModel< T >::Impl::init(), KineticModel< T >::InitializeFgammaCoefficients(), KineticModel< T >::InitializeMacroparameters(), DistFunctFields< X >::initializeMaxwellian(), KineticModel< T >::initializeMaxwellian(), KineticModel< T >::initializeMaxwellianEq(), KineticModel< T >::MacroparameterIBCell(), COMETModel< T >::MakeCoarseMesh2(), IBManager::markIBTypePlus(), KineticModel< T >::MomentHierarchy(), KineticModel< T >::NewtonsMethodBGK(), KineticModel< T >::NewtonsMethodESBGK(), PlateModel< T >::Impl::postPlateSolve(), MeshDismantler::set_local_global(), MeshPartitioner::set_local_global(), MeshPartitioner::setMeshColors(), MultiField::syncGatherLevel1(), COMETModel< T >::syncGhostCoarsening(), MultiField::syncLevel1(), MultiField::syncScatterLevel1(), ElectricModel< T >::Impl::updateElectricField(), ElectricModel< T >::Impl::updateElectronVelocity(), MeshMetricsCalculator< T >::updateTime(), ElectricModel< T >::Impl::updateTime(), FractureModel< T >::Impl::updateTime(), VacancyModel< T >::Impl::updateTime(), ThermalModel< T >::Impl::updateTime(), DistFunctFields< X >::weightedMaxwellian(), and KineticModel< T >::weightedMaxwellian().
 {return _countLevel1;}
const GatherMap& StorageSite::getGatherMap () const inline
Definition at line 59 of file StorageSite.h.
References _gatherMap.
Referenced by Mesh::addCRConn(), Mesh::countCRConn(), MeshAssembler::countInterfaceNodes(), LinearSystem::createCoarse(), Mesh::createDoubleShell(), NcDataReader::createMappers(), FluentReader::createMesh(), Mesh::createRowColSiteCRConn(), Mesh::createScatterGatherCountsBuffer(), Mesh::createScatterGatherIndicesBuffer(), GradientMatrix< T_Scalar >::createScatterGatherValuesBuffer(), Mesh::createShell(), Kspace< T >::createSyncGather(), Field::createSyncGatherArrays(), MultiField::createSyncGatherArrays(), Field::createSyncGatherArraysVectorFields(), COMETModel< T >::FinishCoarseMesh(), FluentReader::getMeshList(), COMETModel< T >::MakeCoarseModel(), COMETModel< T >::makeCoarseScatGath(), COMETModel< T >::MakeIBCoarseModel(), MeshDismantler::partitionInterfaceMappers(), Mesh::recvScatterGatherCountsBufferLocal(), Mesh::recvScatterGatherIndicesBufferLocal(), GradientMatrix< T_Scalar >::recvScatterGatherValuesBufferLocal(), SpikeStorage::setGlobalIndices(), MultiField::sync(), Mesh::syncCounts(), Field::syncGather(), MultiField::syncGather(), Kspace< T >::syncGather(), Field::syncGatherVectorFields(), MultiFieldMatrix::syncGhostCoarsening(), COMETModel< T >::syncGhostCoarsening(), Mesh::syncIndices(), Field::syncLocal(), Kspace< T >::syncLocal(), Field::syncLocalVectorFields(), and GradientMatrix< T_Scalar >::syncValues().
 { return  _gatherMap;}
GatherMap& StorageSite::getGatherMap () inline
Definition at line 64 of file StorageSite.h.
References _gatherMap.
 { return _gatherMap; }
const GatherMap& StorageSite::getGatherMapLevel1 () const inline
Definition at line 74 of file StorageSite.h.
References _gatherMapLevel1.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), Field::createSyncGatherArraysLevel1(), MultiField::createSyncGatherArraysLevel1(), Field::createSyncGatherArraysVectorFieldsLevel1(), MeshPartitioner::DEBUG_level1_scatter_gather_cells(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), Field::get_request_size_gather_level1(), MultiField::get_request_size_gather_level1(), COMETModel< T >::MakeCoarseModel(), COMETModel< T >::MakeIBCoarseModel(), CRMatrix< T_Diag, T_OffDiag, X >::syncCounts(), Field::syncGatherLevel1(), MultiField::syncGatherLevel1(), Field::syncGatherVectorFieldsLevel1(), MultiFieldMatrix::syncGhostCoarsening(), COMETModel< T >::syncGhostCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), MultiField::syncLevel1(), Field::syncLocalLevel1(), Field::syncLocalVectorFieldsLevel1(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx().
 { return _gatherMapLevel1 ;}
GatherMap& StorageSite::getGatherMapLevel1 () inline
Definition at line 77 of file StorageSite.h.
References _gatherMapLevel1.
 { return _gatherMapLevel1 ;}
int StorageSite::getGatherProcID () const inline
Definition at line 83 of file StorageSite.h.
References _gatherProcID.
Referenced by LinearSystem::createCoarse(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), MeshDismantler::debug_gather_mappers(), MeshDismantler::debug_scatter_mappers(), COMETModel< T >::FinishCoarseMesh(), Field::get_request_size(), MultiField::get_request_size(), GradientMatrix< T_Scalar >::get_request_size(), Mesh::get_request_size(), Kspace< T >::get_request_size(), CRMatrix< T_Diag, T_OffDiag, X >::get_request_size(), Field::get_request_size_gather_level1(), MultiField::get_request_size_gather_level1(), Field::get_request_size_level1(), Field::get_request_size_scatter_level1(), MultiField::get_request_size_scatter_level1(), COMETModel< T >::MakeCoarseModel(), COMETModel< T >::makeCoarseScatGath(), COMETModel< T >::MakeIBCoarseModel(), Mesh::recvScatterGatherCountsBufferLocal(), Mesh::recvScatterGatherIndicesBufferLocal(), GradientMatrix< T_Scalar >::recvScatterGatherValuesBufferLocal(), SpikeStorage::setGlobalIndices(), MultiField::sync(), Mesh::syncCounts(), CRMatrix< T_Diag, T_OffDiag, X >::syncCounts(), Mesh::syncIndices(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), MultiField::syncLevel1(), Field::syncLocal(), Kspace< T >::syncLocal(), Field::syncLocalLevel1(), Field::syncLocalVectorFields(), Field::syncLocalVectorFieldsLevel1(), GradientMatrix< T_Scalar >::syncValues(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx().
 { return _gatherProcID; }
const Mesh& StorageSite::getMesh () const inline
Definition at line 56 of file StorageSite.h.
References _meshMap.
Referenced by Mesh::recvScatterGatherCountsBufferLocal(), and Mesh::recvScatterGatherIndicesBufferLocal().
 { return *_meshMap[this]; }
int StorageSite::getOffset () const inline
Definition at line 87 of file StorageSite.h.
References _offset.
Referenced by Field::_create(), COMETDiscretizer< T >::correctInterface(), FluentReader::createMesh(), debug_mesh(), MeshDismantler::faceCellsAddBoundaryInterfaces(), MeshDismantler::faceCellsAddPartitionInterfaces(), MeshDismantler::faceNodesAddBoundaryInterfaces(), MeshDismantler::faceNodesAddPartitionInterfaces(), MeshDismantler::faceNodesInit(), COMETModel< T >::FinishCoarseMesh(), Mesh::getFaceCells(), Mesh::getFaceNodes(), MeshDismantler::getGatherArrays(), MeshDismantler::getScatterArrays(), PhononModel< T >::init(), COMETModel< T >::init(), COMETModel< T >::initCoarse(), COMETModel< T >::initFromOld(), COMETInterface< T >::makeDMMcoeffs(), COMETModel< T >::MakeInteriorCoarseMesh(), COMETModel< T >::sameFaceGroup(), Mesh::setCommonFacesMap(), COMETDiscretizer< T >::setfgFinder(), COMETESBGKDiscretizer< T >::setfgFinder(), MeshAssembler::setInterfaceNodes(), StructureDeformationModel< T >::updateBoundaryMesh(), StructureModel< T >::Impl::updateForceOnBoundary(), FluentDataExporter< T >::writeScalarField(), VTKWriter< T >::writeScalarField(), and VTKWriter< T >::writeVectorField().
 {return _offset;}
const StorageSite* const StorageSite::getParent () const inline
Definition at line 86 of file StorageSite.h.
References _parent.
Referenced by Field::_create(), and Field::hasArray().
 {return _parent;}
const ScatterIndex& StorageSite::getScatterIndex () const inline
Definition at line 61 of file StorageSite.h.
References _scatterIndex.
Referenced by MeshPartitioner::extractBoundaryMesh(), Mesh::getUpdatedNodesCoordCoupling(), Mesh::setCommonFacesMap(), and Mesh::setNodeRepeationArrayCoupling().
 { return _scatterIndex; }
ScatterIndex& StorageSite::getScatterIndex () inline
Definition at line 66 of file StorageSite.h.
References _scatterIndex.
 { return _scatterIndex; }
const ScatterMap& StorageSite::getScatterMap () const inline
Definition at line 58 of file StorageSite.h.
References _scatterMap.
Referenced by MeshAssembler::countInterfaceNodes(), LinearSystem::createCoarse(), Mesh::createDoubleShell(), NcDataReader::createMappers(), FluentReader::createMesh(), Mesh::createScatterGatherCountsBuffer(), Mesh::createScatterGatherIndicesBuffer(), GradientMatrix< T_Scalar >::createScatterGatherValuesBuffer(), Mesh::createShell(), Field::get_request_size(), MultiField::get_request_size(), GradientMatrix< T_Scalar >::get_request_size(), Mesh::get_request_size(), Kspace< T >::get_request_size(), FluentReader::getMeshList(), MeshPartitioner::globalCellID_procID_map(), COMETModel< T >::MakeCoarseModel(), COMETModel< T >::makeCoarseScatGath(), COMETInterface< T >::makeDMMcoeffs(), COMETModel< T >::MakeIBCoarseModel(), MeshDismantler::partitionInterfaceMappers(), MeshAssembler::setCellsSite(), COMETModel< T >::setLocalScatterMaps(), MultiField::sync(), Mesh::syncCounts(), MultiFieldMatrix::syncGhostCoarsening(), COMETModel< T >::syncGhostCoarsening(), Mesh::syncIndices(), Field::syncLocal(), Kspace< T >::syncLocal(), Field::syncLocalVectorFields(), Field::syncScatter(), MultiField::syncScatter(), Kspace< T >::syncScatter(), Field::syncScatterVectorFields(), and GradientMatrix< T_Scalar >::syncValues().
 { return _scatterMap;}
ScatterMap& StorageSite::getScatterMap () inline
Definition at line 63 of file StorageSite.h.
References _scatterMap.
 { return _scatterMap;}
const ScatterMap& StorageSite::getScatterMapLevel1 () const inline
Definition at line 73 of file StorageSite.h.
References _scatterMapLevel1.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), MeshPartitioner::DEBUG_level1_scatter_gather_cells(), CRMatrix< T_Diag, T_OffDiag, X >::get_request_size(), Field::get_request_size_level1(), Field::get_request_size_scatter_level1(), MultiField::get_request_size_scatter_level1(), COMETModel< T >::MakeCoarseModel(), COMETModel< T >::MakeIBCoarseModel(), CRMatrix< T_Diag, T_OffDiag, X >::syncCounts(), MultiFieldMatrix::syncGhostCoarsening(), COMETModel< T >::syncGhostCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), MultiField::syncLevel1(), Field::syncLocalLevel1(), Field::syncLocalVectorFieldsLevel1(), Field::syncScatterLevel1(), MultiField::syncScatterLevel1(), Field::syncScatterVectorFieldsLevel1(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx().
 { return _scatterMapLevel1;}
ScatterMap& StorageSite::getScatterMapLevel1 () inline
Definition at line 76 of file StorageSite.h.
References _scatterMapLevel1.
 { return _scatterMapLevel1;}
int StorageSite::getScatterProcID () const inline
Definition at line 82 of file StorageSite.h.
References _scatterProcID.
Referenced by LinearSystem::createCoarse(), COMETModel< T >::MakeCoarseModel(), COMETModel< T >::makeCoarseScatGath(), and COMETModel< T >::MakeIBCoarseModel().
 { return _scatterProcID;}
int StorageSite::getSelfCount () const inline
Definition at line 40 of file StorageSite.h.
References _selfCount.
Referenced by Mesh::addCRConn(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyInterfaceBC(), StructureBCS< X, Diag, OffDiag >::applyInterfaceBC(), PlateBCS< X, Diag, OffDiag >::applyInterfaceBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyInterfaceBC(), PhononInterface< X >::applyInterfaceCondition(), COMETModel< T >::calcDomainStats(), MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), MeshPartitioner::cellcells_global_extension(), CellMark_Impl(), COMETModel< T >::coarsenInterfaceCells(), COMETModel< T >::coarsenInterior(), COMETModel< T >::COMETModel(), COMETESBGKDiscretizer< T >::COMETSolve(), COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETESBGKDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), MultiFieldMatrix::computeResidual(), CRMatrix< T_Diag, T_OffDiag, X >::computeResidual(), KineticModel< T >::computeSurfaceForce(), COMETModel< T >::computeSurfaceForce(), KineticModel< T >::correctMassDeficit(), COMETModel< T >::correctMassDeficit(), KineticModel< T >::correctMassDeficit2(), COMETModel< T >::correctMassDeficit2(), COMETModel< T >::correctSingleNeighbor(), COMETModel< T >::correctSolution(), correctVelocityInterior(), Mesh::countCRConn(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarsening(), Mesh::createDoubleShell(), Mesh::createRowColSiteCRConn(), Mesh::createShell(), debug_mesh(), SourceDiscretization< X >::discretize(), Underrelaxer< X, Diag, OffDiag >::discretize(), BatteryPCHeatSourceDiscretization< X >::discretize(), PhononCollisionDiscretization< X, Diag, OffDiag >::discretize(), CollisionTermDiscretization< X, Diag, OffDiag >::discretize(), TrapBandTunnelingDiscretization< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJump< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize(), SourceDiscretizationforFracture< T, Diag, OffDiag >::discretize(), BatteryPCTimeDerivativeDiscretization< X, Diag, OffDiag >::discretize(), LinearizeDielectric< X, Diag, OffDiag >::discretize(), TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), IbmDiscretization< X, Diag, OffDiag >::discretize(), BatteryLinearizeThermalInterface< X, Diag, OffDiag >::discretize(), BatteryLinearizePotentialInterface< X, Diag, OffDiag >::discretize(), ConvectionDiscretization< X, Diag, OffDiag >::discretize(), LinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryPCLinearizeInterface_BV< X, Diag, OffDiag, otherMeshDiag >::discretize(), TimeDerivativeStructureDiscretization< X, Diag, OffDiag >::discretize(), BatteryLinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), LinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), MomentumPressureGradientDiscretization< X >::discretize(), TimeDerivativePlateDiscretization< X, Diag, OffDiag >::discretize(), CaptureDiscretization< X, Diag, OffDiag >::discretize(), EmissionDiscretization< X, Diag, OffDiag >::discretize(), InjectionDiscretization< X, Diag, OffDiag >::discretize(), TunnelingDiscretization< X, Diag, OffDiag >::discretize(), PlateSourceDiscretization< T, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), discretizeMassFluxInterior(), MultiField::dotWith(), FlowModel< T >::Impl::dumpContinuityMatrix(), VacancyModel< T >::Impl::dumpMatrix(), ThermalModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), PartMesh::dumpTecplot(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateBoundaryEquations(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), TimeDerivativeStructureDiscretization< X, Diag, OffDiag >::explicitAdvance(), Mesh::extrude(), MeshDismantler::faceCellsAddBoundaryInterfaces(), MeshDismantler::faceCellsAddPartitionInterfaces(), COMETESBGKDiscretizer< T >::findResid(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETESBGKDiscretizer< T >::findResidFine(), COMETDiscretizer< T >::findResidFull(), COMETModel< T >::FinishCoarseMesh(), BatteryFixInterfaceGhost< X, Diag, OffDiag >::fixInterfaces(), MultiFieldMatrix::forwardGS(), CRMatrix< T_Diag, T_OffDiag, X >::forwardGS(), SpikeStorage::gatherCellSizes(), BatteryModel< T >::Impl::getAverageConcentration(), SpeciesModel< T >::Impl::getAverageMassFraction(), COMETModel< T >::getAverageTemperature(), Mesh::getCellCells2(), GradientMatrix< T_Scalar >::getGradient(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D(), CRConnectivity::getLocalizedSubsetOfFaceCells(), BatteryModel< T >::Impl::getMeshVolume(), FlowModel< T >::Impl::getMomentumDerivativeIntegral(), MultiField::getOneNorm(), KSConnectivity< T >::getOtherSize(), StructureModel< T >::Impl::getPlasticDiagStrain(), KSConnectivity< T >::getSelfSize(), FlowModel< T >::Impl::getTraction(), MeshDismantler::global_offset(), MeshPartitioner::global_offset(), MeshPartitioner::globalCellID_procID_map(), SpikeStorage::init(), PartMesh::init(), MeshPartitioner::init(), COMETModel< T >::init(), COMETModel< T >::injectResid(), FlowModel< T >::Impl::interfaceContinuityBC(), MultiFieldMatrix::Jacobi(), CRMatrix< T_Diag, T_OffDiag, X >::Jacobi(), FlowModel< T >::Impl::linearizeContinuity(), CRMatrix< T_Diag, T_OffDiag, X >::lowerSolve(), COMETModel< T >::makeCellColors(), COMETModel< T >::MakeCoarseMesh1(), COMETModel< T >::MakeCoarseMesh2(), COMETModel< T >::MakeInteriorCoarseMesh(), COMETModel< T >::makeNonEqTemp(), COMETModel< T >::makePlotColors(), IBManager::markIBTypePlus(), IBManager::markIntersections(), IBManager::markSolid(), AABB::meshIntersections(), CRMatrixRect< T_Coeff, X, B >::multiply(), CRMatrixRect< T_Coeff, X, B >::multiplyAndAdd(), KSConnectivity< T >::multiplyOther(), KSConnectivity< T >::multiplySelf(), orderCellFacesAndNodes(), PhononModel< T >::PhononModel(), CRMatrix< T_Diag, T_OffDiag, X >::quadProduct(), MultiFieldMatrix::reverseGS(), CRMatrix< T_Diag, T_OffDiag, X >::reverseGS(), MeshDismantler::set_local_global(), MeshPartitioner::set_local_global(), MeshAssembler::setCellsMapper(), MeshDismantler::setCellsMapper(), MeshAssembler::setCellsSite(), MeshDismantler::setCellsSite(), FlowModel< T >::Impl::setDirichlet(), COMETModel< T >::sete0(), MeshAssembler::setFaceCells(), PartMesh::setMeshColors(), MeshPartitioner::setMeshColors(), MeshDismantler::setNodesMapper(), MeshDismantler::setNodesSite(), COMETModel< T >::setStraightLine(), CRMatrix< T_Diag, T_OffDiag, X >::solveBoundary(), SpikeStorage::syncCellIDs(), COMETModel< T >::syncGhostCoarsening(), IBManager::update(), PlateDeformationModel< T >::updateBoundaryMesh(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateeShifted(), BatteryModel< T >::Impl::updateShellGhosts(), ElectricModel< T >::Impl::updateTime(), CRMatrix< T_Diag, T_OffDiag, X >::upperSolve(), MovingMeshModel< T >::volChange(), VTKWriter< T >::VTKWriter(), FluentDataExporter< T >::writeScalarField(), VTKWriter< T >::writeScalarField(), FluentDataExporter< T >::writeVectorField(), and VTKWriter< T >::writeVectorField().
 {return _selfCount;}
int StorageSite::getTag () const inline
Definition at line 84 of file StorageSite.h.
References _tag.
Referenced by LinearSystem::createCoarse(), MeshDismantler::debug_gather_mappers(), MeshDismantler::debug_scatter_mappers(), COMETModel< T >::MakeCoarseModel(), COMETModel< T >::makeCoarseScatGath(), COMETModel< T >::MakeIBCoarseModel(), MultiField::sync(), Mesh::syncCounts(), CRMatrix< T_Diag, T_OffDiag, X >::syncCounts(), COMETModel< T >::syncGhostCoarsening(), Mesh::syncIndices(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), MultiField::syncLevel1(), Field::syncLocal(), Kspace< T >::syncLocal(), Field::syncLocalLevel1(), Field::syncLocalVectorFields(), Field::syncLocalVectorFieldsLevel1(), GradientMatrix< T_Scalar >::syncValues(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx().
 { return _tag; }
void StorageSite::setCount (const int selfCount, const int nGhost = 0) inline
Definition at line 42 of file StorageSite.h.
References _count, _countLevel1, and _selfCount.
Referenced by PartMesh::construct_mesh(), MeshPartitioner::construct_mesh(), Grid::createCellToNodeConnectivity(), Mesh::createDoubleShell(), IBManager::createIBFaces(), FluentReader::createMesh(), Mesh::createShell(), MeshPartitioner::extractBoundaryMesh(), Mesh::extractBoundaryMesh(), Mesh::extrude(), COMETModel< T >::FinishCoarseMesh(), CRConnectivity::getLocalizedSubset(), CRConnectivity::getLocalizedSubsetOfFaceCells(), MPM::getParticles(), Grid::Grid(), MPM::Init(), COMETModel< T >::MakeCoarseMesh2(), markIBFaces(), Mesh::Mesh(), FluentReader::readMesh(), MeshAssembler::setSites(), MeshDismantler::setSites(), and NcDataReader::storage_sites().
   {
     _count = selfCount+nGhost;
     _selfCount = selfCount;
     _countLevel1 = _count;
   }
void StorageSite::setCountLevel1 (const int countLevel1) inline
Definition at line 69 of file StorageSite.h.
References _countLevel1.
Referenced by MeshPartitioner::level1_scatter_gather_cells(), COMETModel< T >::MakeCoarseMesh2(), and MeshDismantler::setSites().
{
     _countLevel1 = countLevel1;
   }
void StorageSite::setGatherProcID (int proc_id) inline
Definition at line 52 of file StorageSite.h.
References _gatherProcID.
Referenced by COMETModel< T >::makeCoarseScatGath().
 { _gatherProcID  = proc_id; }
void StorageSite::setMesh (const Mesh * mesh) inline
Definition at line 55 of file StorageSite.h.
References _meshMap.
Referenced by Mesh::Mesh().
 { _meshMap[this] = mesh; }
void StorageSite::setScatterProcID (int proc_id) inline
Definition at line 51 of file StorageSite.h.
References _scatterProcID.
Referenced by COMETModel< T >::makeCoarseScatGath().
 { _scatterProcID = proc_id; }
void StorageSite::setTag (int tag) inline
Definition at line 53 of file StorageSite.h.
References _tag.
Referenced by COMETModel< T >::makeCoarseScatGath().
 { _tag = tag;}
Member Data Documentation
CommonMap StorageSite::_commonMap private
Definition at line 99 of file StorageSite.h.
Referenced by getCommonMap().
int StorageSite::_count private
Definition at line 92 of file StorageSite.h.
Referenced by getCount(), setCount(), StorageSite(), and ~StorageSite().
int StorageSite::_countLevel1 private
Definition at line 104 of file StorageSite.h.
Referenced by getCountLevel1(), setCount(), and setCountLevel1().
GatherMap StorageSite::_gatherMap private
Definition at line 98 of file StorageSite.h.
Referenced by clearGatherScatterMaps(), and getGatherMap().
GatherMap StorageSite::_gatherMapLevel1 private
Definition at line 106 of file StorageSite.h.
Referenced by getGatherMapLevel1().
int StorageSite::_gatherProcID private
Definition at line 109 of file StorageSite.h.
Referenced by getGatherProcID(), and setGatherProcID().
MeshMap StorageSite::_meshMap mutable private
Definition at line 102 of file StorageSite.h.
Referenced by getMesh(), and setMesh().
const int StorageSite::_offset private
Definition at line 94 of file StorageSite.h.
Referenced by getOffset().
const StorageSite* const StorageSite::_parent private
Definition at line 95 of file StorageSite.h.
Referenced by getParent().
ScatterIndex StorageSite::_scatterIndex private
Definition at line 100 of file StorageSite.h.
Referenced by getScatterIndex().
ScatterMap StorageSite::_scatterMap private
Definition at line 97 of file StorageSite.h.
Referenced by clearGatherScatterMaps(), and getScatterMap().
ScatterMap StorageSite::_scatterMapLevel1 private
Definition at line 105 of file StorageSite.h.
Referenced by getScatterMapLevel1().
int StorageSite::_scatterProcID private
Definition at line 108 of file StorageSite.h.
Referenced by getScatterProcID(), and setScatterProcID().
int StorageSite::_selfCount private
Definition at line 93 of file StorageSite.h.
Referenced by getSelfCount(), and setCount().
int StorageSite::_tag private
Definition at line 110 of file StorageSite.h.
Referenced by getTag(), and setTag().
The documentation for this class was generated from the following files:
StorageSite.h
StorageSite.cpp