Memosa-FVM: PhononCollisionDiscretization< X, Diag, OffDiag > Class Template Reference
PhononCollisionDiscretization< X, Diag, OffDiag > Class Template Reference
#include <PhononCollisionDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
Public Member Functions
PhononCollisionDiscretization (const MeshList &meshes, const GeomFields &geomFields, const Field &varField, const Field &sourceField, const X tau)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
const Field & _varField
const Field & _sourceField
const X _tau
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class PhononCollisionDiscretization< X, Diag, OffDiag >
Definition at line 19 of file PhononCollisionDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler PhononCollisionDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 27 of file PhononCollisionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> PhononCollisionDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 25 of file PhononCollisionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray PhononCollisionDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 26 of file PhononCollisionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar PhononCollisionDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 23 of file PhononCollisionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> PhononCollisionDiscretization< X, Diag, OffDiag >::TArray
Definition at line 30 of file PhononCollisionDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> PhononCollisionDiscretization< X, Diag, OffDiag >::XArray
Definition at line 29 of file PhononCollisionDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > PhononCollisionDiscretization< X, Diag, OffDiag >::PhononCollisionDiscretization (const MeshList & meshes, const GeomFields & geomFields, const Field & varField, const Field & sourceField, const X tau) inline
Definition at line 32 of file PhononCollisionDiscretization.h.
                                             :     //relaxation time
     Discretization(meshes),
       _geomFields(geomFields),
       _varField(varField),
       _sourceField(sourceField),
       _tau(tau)
       {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void PhononCollisionDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & , MultiField & rField) inline virtual
Implements Discretization.
Definition at line 45 of file PhononCollisionDiscretization.h.
References PhononCollisionDiscretization< X, Diag, OffDiag >::_geomFields, PhononCollisionDiscretization< X, Diag, OffDiag >::_sourceField, PhononCollisionDiscretization< X, Diag, OffDiag >::_tau, PhononCollisionDiscretization< X, Diag, OffDiag >::_varField, Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), MultiFieldMatrix::getMatrix(), StorageSite::getSelfCount(), and GeomFields::volume.
     {
       const StorageSite& cells = mesh.getCells();
       const TArray& cellVolume = dynamic_cast<const TArray&>(_geomFields.volume[cells]);
       const XArray& source = dynamic_cast<const XArray&>(_sourceField[cells]);
       const MultiField::ArrayIndex cVarIndex(&_varField, &cells);
       CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(cVarIndex,cVarIndex));
       DiagArray& diag = matrix.getDiag();
       const XArray& x = dynamic_cast<const XArray&>(_varField[cells]);
       TArray& rCell = dynamic_cast<TArray&>(rField[cVarIndex]);
       const int nCells = cells.getSelfCount();
       for(int c=0; c<nCells; c++)
         {
           rCell[c] -= cellVolume[c]*(x[c]-source[c])/_tau;
           diag[c]-=cellVolume[c]/_tau;
         }
     }
Member Data Documentation
template<class X , class Diag , class OffDiag > const GeomFields& PhononCollisionDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 73 of file PhononCollisionDiscretization.h.
Referenced by PhononCollisionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& PhononCollisionDiscretization< X, Diag, OffDiag >::_sourceField private
Definition at line 75 of file PhononCollisionDiscretization.h.
Referenced by PhononCollisionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const X PhononCollisionDiscretization< X, Diag, OffDiag >::_tau private
Definition at line 76 of file PhononCollisionDiscretization.h.
Referenced by PhononCollisionDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const Field& PhononCollisionDiscretization< X, Diag, OffDiag >::_varField private
Definition at line 74 of file PhononCollisionDiscretization.h.
Referenced by PhononCollisionDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
PhononCollisionDiscretization.h