Memosa-FVM: IbmDiscretization< X, Diag, OffDiag > Class Template Reference
IbmDiscretization< X, Diag, OffDiag > Class Template Reference
#include <IbmDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::OffDiagArray OffDiagArray
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
IbmDiscretization (const MeshList &meshes, const GeomFields &geomFields, FlowFields &flowFields)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
FlowFields & _flowFields
const GeomFields & _geomFields
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class IbmDiscretization< X, Diag, OffDiag >
Definition at line 28 of file IbmDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> IbmDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 34 of file IbmDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray IbmDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 35 of file IbmDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::OffDiagArray IbmDiscretization< X, Diag, OffDiag >::OffDiagArray
Definition at line 36 of file IbmDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar IbmDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 32 of file IbmDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> IbmDiscretization< X, Diag, OffDiag >::TArray
Definition at line 39 of file IbmDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> IbmDiscretization< X, Diag, OffDiag >::VectorT3
Definition at line 40 of file IbmDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> IbmDiscretization< X, Diag, OffDiag >::VectorT3Array
Definition at line 41 of file IbmDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> IbmDiscretization< X, Diag, OffDiag >::XArray
Definition at line 38 of file IbmDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > IbmDiscretization< X, Diag, OffDiag >::IbmDiscretization (const MeshList & meshes, const GeomFields & geomFields, FlowFields & flowFields) inline
Definition at line 43 of file IbmDiscretization.h.
                                              :
     Discretization(meshes),
     _geomFields(geomFields),
     _flowFields(flowFields)
 {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void IbmDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 51 of file IbmDiscretization.h.
References IbmDiscretization< X, Diag, OffDiag >::_flowFields, IbmDiscretization< X, Diag, OffDiag >::_geomFields, GeomFields::coordinate, Mesh::getCells(), CRConnectivity::getCol(), CRMatrix< T_Diag, T_OffDiag, X >::getConnectivity(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), MultiFieldMatrix::getMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::getOffDiag(), CRConnectivity::getRow(), StorageSite::getSelfCount(), and FlowFields::velocity.
   {
     const StorageSite& cells = mesh.getCells();
     const MultiField::ArrayIndex vIndex(&_flowFields.velocity,&cells);
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(vIndex,vIndex));
     DiagArray& diag = matrix.getDiag();
     OffDiagArray& offdiag = matrix.getOffDiag();
     const CRConnectivity& conn=matrix.getConnectivity();
     const Array<int>& row=conn.getRow();
     const Array<int>& col=conn.getCol();
     const VectorT3Array& cellCentroid = dynamic_cast<const VectorT3Array&> (_geomFields.coordinate[cells]);
     VectorT3Array& cellVelocity = dynamic_cast<VectorT3Array&> (_flowFields.velocity[cells]);
     const XArray& xCell = dynamic_cast<const XArray&>(xField[vIndex]);
     XArray& rCell = dynamic_cast<XArray&>(rField[vIndex]);
     const int nCells = cells.getSelfCount();
     const VectorT3 zeroVelocity(NumTypeTraits<VectorT3>::getZero());
     VectorT3 dR;        //local variable dR=r[c]-r[j]
     //set up solid cell veloicty to be solidVelocity
     //ofstream fp1, fp2;
     //fp1.open ("/home/linsun/Work/prism/app-memosa/src/fvm/test/ibm_velocity");
     //fp2.open ("/home/linsun/Work/prism/app-memosa/src/fvm/test/solid_velocity");
     // fp=fopen("/home/linsun/Work/prism/app-memosa/src/fvm/test/ibm_velocity","w");
     for (int c=0; c<nCells; c++)
     {
       int cellIBType = mesh.getIBTypeForCell(c);
       if (cellIBType == 2)               //solid cells
       {
         //cout << "cellID" << c << "velocity" << _flowFields.velocity << endl;
         //printf("cellID = %i and velocity is %f\t%f\t%f\n", c,cellVelocity[c][0],cellVelocity[c][1],cellVelocity[c][2]);
         diag[c] = (-1);   //ap=(-1)
         //diag[c] = NumTypeTraits<Diag>::getNegativeUnity;
         cellVelocity[c]=zeroVelocity;     //Cell velocity is set as prescribed
         for (int nbpos=row[c]; nbpos<row[c+1]; nbpos++){
           //const int j=col[nbpos];
           offdiag[nbpos]=0;              //anb=0
           //offdiag[nbpos] = NumTypeTraits<offDiag>::getZero;
         }
         rCell[c]=0;                     //residual is zero
         //rCell[c]= NumTypeTraits<VectorT3>::getZero;
         //fprintf(fp, "%i\t%f\t%f\t%f\n", c,cellVelocity[c][0],cellVelocity[c][1],cellVelocity[c][2]);
         //fp2 << c << cellVelocity[c] << endl;
       }
       //fclose(fp);
       #if 1
       else if (cellIBType == 1)          //immersed boundary cells
       {
         //cout << "cellID" << c << "velocity" << _flowFields.velocity\n;
         diag[c] = (-1);   //aP=-1
         //diag[c] = NumTypeTraits<Diag>::getNegativeUnity;
         double sumCellDist=0;
         //offdiag[nb]=alfa[nb] (distance weight function)
         //r=-v[c]+sum(alfa[nb]*v[nb])
         /*
         for (int nbpos=row[c]; nbpos<row[c+1]; nbpos++){
           const int j=col[nbpos];
           dR=cellCentroid[c]-cellCentroid[j];
           offdiag[nbpos]=1./mag(dR);
           sumCellDist+=offdiag[nbpos];
         }
         */
         for (int nbpos=row[c]; nbpos<row[c+1]; nbpos++){
           //offdiag[nbpos]/=sumCellDist;
           const int j=col[nbpos];
           offdiag[nbpos]=1.0/(row[c+1]-row[c]);
           rCell[c]-=offdiag[nbpos]*cellVelocity[j];
         }
         rCell[c]+=cellVelocity[c];
         //fp1 << c << cellVelocity[c] << endl;
       }
       #endif
     }
  //fp1.close();
  //fp2.close();
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > FlowFields& IbmDiscretization< X, Diag, OffDiag >::_flowFields private
Definition at line 138 of file IbmDiscretization.h.
Referenced by IbmDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > const GeomFields& IbmDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 139 of file IbmDiscretization.h.
Referenced by IbmDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
IbmDiscretization.h