Memosa-FVM: LinearSystem Class Reference
LinearSystem Class Reference
#include <LinearSystem.h>
Public Member Functions
LinearSystem ()
virtual ~LinearSystem ()
void initAssembly ()
void initSolve ()
void postSolve ()
void updateSolution ()
shared_ptr< LinearSystem > createCoarse (const int groupSize, const double weightRatioThreshold)
MultiField & getX ()
MultiField & getB ()
MultiField & getDelta ()
MultiField & getResidual ()
MultiFieldMatrix & getMatrix ()
MultiField & getCoarseIndex ()
shared_ptr< MultiField > getDeltaPtr ()
shared_ptr< MultiField > getBPtr ()
void replaceDelta (shared_ptr< MultiField > newDelta)
void replaceB (shared_ptr< MultiField > newB)
void replaceResidual (shared_ptr< MultiField > newR)
void setCoarseningField (const Field &f)
Public Attributes
bool isSymmetric
Private Attributes
MultiFieldMatrix _matrix
shared_ptr< MultiField > _x
shared_ptr< MultiField > _b
shared_ptr< MultiField > _delta
shared_ptr< MultiField > _residual
MultiField _coarseIndex
const Field * _coarseningField
shared_ptr< MultiField > _xAux
shared_ptr< MultiField > _bAux
shared_ptr< MultiField > _deltaAux
shared_ptr< MultiField > _residualAux
Friends
class LinearSystemMerger
Detailed Description
Definition at line 11 of file LinearSystem.h.
Constructor & Destructor Documentation
LinearSystem::LinearSystem ()
Definition at line 13 of file LinearSystem.cpp.
Referenced by createCoarse().
                            :
   isSymmetric(false),
   _x(new MultiField()),
   _b(),
   _delta(),
   _residual(),
   _coarseIndex(),
   _coarseningField(0)
 {}
LinearSystem::~LinearSystem () virtual
Definition at line 23 of file LinearSystem.cpp.
 {
 }
Member Function Documentation
shared_ptr< LinearSystem > LinearSystem::createCoarse (const int groupSize, const double weightRatioThreshold)
we create only one entry in coarseIndex for each StorageSite even if the site is present in multiple fine ArrayIndices of x. If a coarseningField is specified we will use that otherwise the first one gets used
coarsen the matrices corresponding to the fieldIndices we have selected and then sync ghost cell values. This process will fill up the coarseSizes and coarseGhostSizes variables in the matrix as well create the mappers
now we have the coarse indices, sizes, sites, mappers and * connectivities computed for the fieldIndices we * selected. Before we can create coarse matrices we need to * set these for the other fieldIndices since the matrices of * course need to be created for all the fine matrices * present
Definition at line 67 of file LinearSystem.cpp.
References _b, MultiFieldMatrix::_coarseGatherMaps, MultiFieldMatrix::_coarseGhostSizes, _coarseIndex, MultiFieldMatrix::_coarseMatrices, _coarseningField, MultiFieldMatrix::_coarseScatterMaps, MultiFieldMatrix::_coarseSites, MultiFieldMatrix::_coarseSizes, MultiFieldMatrix::_coarseToFineMappings, _matrix, MultiField::addArray(), MultiFieldMatrix::createCoarseConnectivity(), MultiFieldMatrix::createCoarseMatrices(), MultiFieldMatrix::createCoarsening(), MultiFieldMatrix::createCoarseToFineMapping(), MultiField::getArrayPtr(), StorageSite::getCount(), StorageSite::getGatherMap(), StorageSite::getGatherProcID(), ArrayBase::getLength(), StorageSite::getScatterMap(), StorageSite::getScatterProcID(), StorageSite::getTag(), MultiFieldMatrix::hasMatrix(), LinearSystem(), MultiField::sync(), MultiFieldMatrix::syncGhostCoarsening(), and MultiField::zero().
Referenced by AMG::createCoarseLevels().
 {
   shared_ptr<LinearSystem> coarseLS(new LinearSystem());
   // keep track of which fieldIndex was used for coarsening each site
   map<const StorageSite*, const Field *> sitesCoarsenedWithField;
   const MultiField::ArrayIndexList& arrayIndices = _b->getArrayIndices();
   foreach(MultiField::ArrayIndex ai,arrayIndices)
   {
       const Field *fieldIndex = ai.first;
       const StorageSite *site = ai.second;
       if (!_coarseningField || fieldIndex == _coarseningField)
       {
           if (sitesCoarsenedWithField.find(site) == sitesCoarsenedWithField.end())
           {
               sitesCoarsenedWithField[site] = fieldIndex;
               const ArrayBase& bi = (*_b)[ai];
               shared_ptr<Array<int> > cIndex(new Array<int>(bi.getLength()));
               _coarseIndex.addArray(ai,cIndex);
           }
       }
   }
   _matrix.createCoarsening(_coarseIndex,groupSize,weightRatioThreshold);
   _coarseIndex.sync();
 _matrix.syncGhostCoarsening(_coarseIndex);
   // we can now create the coarse sites for each fine site
   foreach(MultiField::ArrayIndex k,arrayIndices)
   {
       // we will only have entries for indices which were selected to be coarsened
       if (_matrix._coarseSizes.find(k) != _matrix._coarseSizes.end())
       {
           int selfSize = _matrix._coarseSizes[k];
           int ghostSize = _matrix._coarseGhostSizes[k];
           _matrix._coarseSites[k] =
             shared_ptr<StorageSite>(new StorageSite(selfSize,ghostSize));
       }
   }
   // set the mappers in the newly created coarse sites
   foreach(MultiField::ArrayIndex k,arrayIndices)
   {
       if (_matrix._coarseSites.find(k) != _matrix._coarseSites.end())
       {
           const StorageSite& fineSite = *k.second;
           StorageSite& coarseSite = *_matrix._coarseSites[k];
           const StorageSite::ScatterMap& fineScatterMap = fineSite.getScatterMap();
           StorageSite::ScatterMap& coarseScatterMap = coarseSite.getScatterMap();
           foreach(const StorageSite::ScatterMap::value_type& pos, fineScatterMap)
           {
               const StorageSite& fineOSite = *pos.first;
               MultiField::ArrayIndex kO(k.first,&fineOSite);
 #ifdef FVM_PARALLEL
               // the ghost site will not have its corresponding coarse
               // site created yet so we create it here
               if (_matrix._coarseSites.find(kO) == _matrix._coarseSites.end())
               {
                   shared_ptr<StorageSite> ghostSite
                     (new StorageSite(-1));
                   ghostSite->setGatherProcID ( fineOSite.getGatherProcID() );
                   ghostSite->setScatterProcID( fineOSite.getScatterProcID() );
                   ghostSite->setTag( fineOSite.getTag() );
                   _matrix._coarseSites[kO] = ghostSite;
               }
 #endif
               const StorageSite& coarseOSite = *_matrix._coarseSites[kO];
               MultiFieldMatrix::SSPair sskey(&fineSite,&fineOSite);
               coarseScatterMap[&coarseOSite] = _matrix._coarseScatterMaps[sskey];
           }
           const StorageSite::GatherMap& fineGatherMap = fineSite.getGatherMap();
           StorageSite::GatherMap& coarseGatherMap = coarseSite.getGatherMap();
           foreach(const StorageSite::GatherMap::value_type& pos, fineGatherMap)
           {
               const StorageSite& fineOSite = *pos.first;
               MultiField::ArrayIndex kO(k.first,&fineOSite);
               const StorageSite& coarseOSite = *_matrix._coarseSites[kO];
               MultiFieldMatrix::SSPair sskey(&fineSite,&fineOSite);
               coarseGatherMap[&coarseOSite] = _matrix._coarseGatherMaps[sskey];
           }
       }
   }
   // create the connectivities for the coarse matrices
   _matrix.createCoarseToFineMapping(_coarseIndex);
   foreach(MultiField::ArrayIndex k,arrayIndices)
   {
       const StorageSite *site = k.second;
       if (_matrix._coarseSites.find(k) == _matrix._coarseSites.end())
       {
           const Field* fieldIndexUsedForCoarsening = sitesCoarsenedWithField[site];
           MultiField::ArrayIndex indexCoarsened(fieldIndexUsedForCoarsening,site);
           _coarseIndex.addArray(k, _coarseIndex.getArrayPtr(indexCoarsened));
           _matrix._coarseSizes[k] = _matrix._coarseSizes[indexCoarsened];
           _matrix._coarseGhostSizes[k] = _matrix._coarseGhostSizes[indexCoarsened];
           _matrix._coarseSites[k] = _matrix._coarseSites[indexCoarsened];
           _matrix._coarseToFineMappings[k] = _matrix._coarseToFineMappings[indexCoarsened];
       }
   }
   _matrix.createCoarseConnectivity(_coarseIndex);
   _matrix.createCoarseMatrices(_coarseIndex);
   foreach(MultiField::ArrayIndex fineRowIndex,arrayIndices)
   {
       MultiField::ArrayIndex coarseRowIndex (fineRowIndex.first,
                                              _matrix._coarseSites[fineRowIndex].get());
       foreach(MultiField::ArrayIndex fineColIndex,arrayIndices)
       {
           MultiFieldMatrix::EntryIndex fineEntryIndex(fineRowIndex,fineColIndex);
           if (_matrix.hasMatrix(fineRowIndex,fineColIndex))
           {
               MultiField::ArrayIndex coarseColIndex(fineColIndex.first,
                                                     _matrix._coarseSites[fineColIndex].get());
               MultiFieldMatrix::EntryIndex coarseEntryIndex(coarseRowIndex,coarseColIndex);
               coarseLS->_matrix._matrices[coarseEntryIndex] =
                 _matrix._coarseMatrices[fineEntryIndex];
           }
       }
   }
   coarseLS->_b = shared_ptr<MultiField>(new MultiField());
   foreach(MultiField::ArrayIndex k,arrayIndices)
   {
       const StorageSite& coarseSite = *_matrix._coarseSites[k];
       MultiField::ArrayIndex coarseIndex(k.first,&coarseSite);
       coarseLS->_b->addArray(coarseIndex, (*_b)[k].newSizedClone(coarseSite.getCount()));
   }
   coarseLS->_b->zero();
   coarseLS->_delta = dynamic_pointer_cast<MultiField>(coarseLS->_b->newClone());
   coarseLS->_delta->zero();
   coarseLS->_residual = dynamic_pointer_cast<MultiField>(coarseLS->_b->newClone());
   coarseLS->_residual->zero();
   return coarseLS;
 }
MultiField& LinearSystem::getB () inline
Definition at line 33 of file LinearSystem.h.
References _b.
Referenced by StructureModel< T >::Impl::advanceExplicit(), StructureModel< T >::Impl::applyBC(), AMG::cycle(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), ILU0Solver::doSweeps(), JacobiSolver::doSweeps(), SpikeSolver::doSweeps(), AMG::doSweeps(), ThermalModel< T >::Impl::dumpMatrix(), VacancyModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), ThermalModel< T >::Impl::linearize(), FractureModel< T >::Impl::linearize(), VacancyModel< T >::Impl::linearize(), SpeciesModel< T >::Impl::linearize(), ElectricModel< T >::Impl::linearizeChargeTransport(), FlowModel< T >::Impl::linearizeContinuity(), PlateModel< T >::Impl::linearizeDeformation(), StructureModel< T >::Impl::linearizeDeformation(), KeModel< T >::Impl::linearizedissipation(), ElectricModel< T >::Impl::linearizeElectroStatics(), KeModel< T >::Impl::linearizeenergy(), KineticModel< T >::linearizeKineticModel(), FlowModel< T >::Impl::linearizeMomentum(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), PhononModel< T >::linearizePhononModel(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), BatteryModel< T >::Impl::linearizeThermal(), BatteryModel< T >::Impl::printMatrixElementsOnFace(), ILU0Solver::solve(), JacobiSolver::solve(), BCGStab::solve(), CG::solve(), SpikeSolver::solve(), DirectSolver::solve(), and AMG::solve().
 {return *_b;}
shared_ptr<MultiField> LinearSystem::getBPtr () inline
Definition at line 42 of file LinearSystem.h.
References _b.
Referenced by BCGStab::solve(), and CG::solve().
 {return _b;}
MultiField& LinearSystem::getCoarseIndex () inline
Definition at line 39 of file LinearSystem.h.
References _coarseIndex.
Referenced by AMG::cycle().
 {return _coarseIndex;}
MultiField& LinearSystem::getDelta () inline
Definition at line 34 of file LinearSystem.h.
References _delta.
Referenced by StructureModel< T >::Impl::advanceExplicit(), AMG::cycle(), ILU0Solver::doSweeps(), JacobiSolver::doSweeps(), SpikeSolver::doSweeps(), AMG::doSweeps(), FlowModel< T >::Impl::postContinuitySolve(), PlateModel< T >::Impl::postPlateSolve(), BCGStab::solve(), ILU0Solver::solve(), JacobiSolver::solve(), CG::solve(), SpikeSolver::solve(), DirectSolver::solve(), and AMG::solve().
 {return *_delta;}
shared_ptr<MultiField> LinearSystem::getDeltaPtr () inline
Definition at line 41 of file LinearSystem.h.
References _delta.
Referenced by BCGStab::solve(), and CG::solve().
 {return _delta;}
MultiFieldMatrix& LinearSystem::getMatrix () inline
Definition at line 37 of file LinearSystem.h.
References _matrix.
Referenced by StructureModel< T >::Impl::advanceExplicit(), StructureModel< T >::Impl::applyBC(), AMG::createCoarseLevels(), AMG::cycle(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), JacobiSolver::doSweeps(), ILU0Solver::doSweeps(), SpikeSolver::doSweeps(), AMG::doSweeps(), ThermalModel< T >::Impl::dumpMatrix(), VacancyModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), ElectricModel< T >::Impl::initChargeTransportLinearization(), FlowModel< T >::Impl::initContinuityLinearization(), PlateModel< T >::Impl::initDeformationLinearization(), StructureModel< T >::Impl::initDeformationLinearization(), ElectricModel< T >::Impl::initElectroStaticsLinearization(), KineticModel< T >::initKineticModelLinearization(), ThermalModel< T >::Impl::initLinearization(), FractureModel< T >::Impl::initLinearization(), VacancyModel< T >::Impl::initLinearization(), SpeciesModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearizationk(), FlowModel< T >::Impl::initMomentumLinearization(), BatteryModel< T >::Impl::initPCLinearization(), PhononModel< T >::initPhononModelLinearization(), BatteryModel< T >::Impl::initPotentialLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), BatteryModel< T >::Impl::initThermalLinearization(), ThermalModel< T >::Impl::linearize(), FractureModel< T >::Impl::linearize(), VacancyModel< T >::Impl::linearize(), SpeciesModel< T >::Impl::linearize(), ElectricModel< T >::Impl::linearizeChargeTransport(), FlowModel< T >::Impl::linearizeContinuity(), PlateModel< T >::Impl::linearizeDeformation(), StructureModel< T >::Impl::linearizeDeformation(), KeModel< T >::Impl::linearizedissipation(), ElectricModel< T >::Impl::linearizeElectroStatics(), KeModel< T >::Impl::linearizeenergy(), KineticModel< T >::linearizeKineticModel(), FlowModel< T >::Impl::linearizeMomentum(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), PhononModel< T >::linearizePhononModel(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), BatteryModel< T >::Impl::linearizeThermal(), FlowModel< T >::Impl::postContinuitySolve(), BatteryModel< T >::Impl::printMatrixElementsOnFace(), JacobiSolver::solve(), ILU0Solver::solve(), CG::solve(), BCGStab::solve(), SpikeSolver::solve(), DirectSolver::solve(), AMG::solve(), and FlowModel< T >::Impl::solveMomentum().
 {return _matrix;}
MultiField& LinearSystem::getResidual () inline
Definition at line 35 of file LinearSystem.h.
References _residual.
Referenced by AMG::cycle(), JacobiSolver::doSweeps(), ILU0Solver::doSweeps(), SpikeSolver::doSweeps(), AMG::doSweeps(), BCGStab::solve(), ILU0Solver::solve(), JacobiSolver::solve(), CG::solve(), SpikeSolver::solve(), DirectSolver::solve(), and AMG::solve().
 {return *_residual;}
MultiField& LinearSystem::getX () inline
Definition at line 32 of file LinearSystem.h.
References _x.
Referenced by StructureModel< T >::Impl::advanceExplicit(), StructureModel< T >::Impl::applyBC(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), ElectricModel< T >::Impl::initChargeTransportLinearization(), FlowModel< T >::Impl::initContinuityLinearization(), PlateModel< T >::Impl::initDeformationLinearization(), StructureModel< T >::Impl::initDeformationLinearization(), ElectricModel< T >::Impl::initElectroStaticsLinearization(), KineticModel< T >::initKineticModelLinearization(), ThermalModel< T >::Impl::initLinearization(), FractureModel< T >::Impl::initLinearization(), VacancyModel< T >::Impl::initLinearization(), SpeciesModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearization(), KeModel< T >::Impl::initLinearizationk(), FlowModel< T >::Impl::initMomentumLinearization(), BatteryModel< T >::Impl::initPCLinearization(), PhononModel< T >::initPhononModelLinearization(), BatteryModel< T >::Impl::initPotentialLinearization(), BatteryModel< T >::Impl::initSpeciesLinearization(), BatteryModel< T >::Impl::initThermalLinearization(), ThermalModel< T >::Impl::linearize(), FractureModel< T >::Impl::linearize(), VacancyModel< T >::Impl::linearize(), SpeciesModel< T >::Impl::linearize(), ElectricModel< T >::Impl::linearizeChargeTransport(), FlowModel< T >::Impl::linearizeContinuity(), PlateModel< T >::Impl::linearizeDeformation(), StructureModel< T >::Impl::linearizeDeformation(), KeModel< T >::Impl::linearizedissipation(), ElectricModel< T >::Impl::linearizeElectroStatics(), KeModel< T >::Impl::linearizeenergy(), KineticModel< T >::linearizeKineticModel(), FlowModel< T >::Impl::linearizeMomentum(), BatteryModel< T >::Impl::linearizePC(), BatteryModel< T >::Impl::linearizePC_Thermal(), PhononModel< T >::linearizePhononModel(), BatteryModel< T >::Impl::linearizePotential(), BatteryModel< T >::Impl::linearizeSpecies(), BatteryModel< T >::Impl::linearizeThermal(), and BatteryModel< T >::Impl::printMatrixElementsOnFace().
 {return *_x;}
void LinearSystem::initAssembly ()
Definition at line 32 of file LinearSystem.cpp.
References _b, _matrix, _x, and MultiFieldMatrix::initAssembly().
Referenced by FractureModel< T >::Impl::advance(), ThermalModel< T >::Impl::advance(), VacancyModel< T >::Impl::advance(), PhononModel< T >::advance(), SpeciesModel< T >::Impl::advance(), KeModel< T >::Impl::advance(), KineticModel< T >::advance(), BatteryModel< T >::Impl::advanceCoupled(), BatteryModel< T >::Impl::advancePotential(), BatteryModel< T >::Impl::advanceSpecies(), BatteryModel< T >::Impl::advanceThermal(), ThermalModel< T >::Impl::dumpMatrix(), VacancyModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), ElectricModel< T >::Impl::solveChargeTransport(), PlateModel< T >::Impl::solveDeformation(), StructureModel< T >::Impl::solveDeformation(), ElectricModel< T >::Impl::solveElectroStatics(), and FlowModel< T >::Impl::solveMomentum().
 {
   _matrix.initAssembly();
   _b = dynamic_pointer_cast<MultiField>(_x->newClone());
   _b->zero();
 }
void LinearSystem::initSolve ()
Definition at line 40 of file LinearSystem.cpp.
References _b, _bAux, _delta, _deltaAux, _matrix, _residual, _residualAux, _x, _xAux, Matrix::eliminateBoundaryEquations(), MultiFieldMatrix::getMatrix(), MultiFieldMatrix::hasMatrix(), and Matrix::isInvertible().
Referenced by FractureModel< T >::Impl::advance(), ThermalModel< T >::Impl::advance(), VacancyModel< T >::Impl::advance(), PhononModel< T >::advance(), SpeciesModel< T >::Impl::advance(), KeModel< T >::Impl::advance(), KineticModel< T >::advance(), BatteryModel< T >::Impl::advanceCoupled(), BatteryModel< T >::Impl::advancePotential(), BatteryModel< T >::Impl::advanceSpecies(), BatteryModel< T >::Impl::advanceThermal(), ThermalModel< T >::Impl::dumpMatrix(), VacancyModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), ElectricModel< T >::Impl::solveChargeTransport(), PlateModel< T >::Impl::solveDeformation(), StructureModel< T >::Impl::solveDeformation(), ElectricModel< T >::Impl::solveElectroStatics(), and FlowModel< T >::Impl::solveMomentum().
 {
   _delta = dynamic_pointer_cast<MultiField>(_x->newClone());
   _residual = dynamic_pointer_cast<MultiField>(_x->newClone());
   _delta->zero();
   _residual->zero();
   MultiField::ArrayIndexList indicesToRemove;
   const MultiField::ArrayIndexList& arrayIndices = _b->getArrayIndices();
   foreach(MultiField::ArrayIndex i, arrayIndices)
   {
       if (!_matrix.hasMatrix(i,i) || _matrix.getMatrix(i,i).isInvertible())
         indicesToRemove.push_back(i);
       else
         _matrix.getMatrix(i,i).eliminateBoundaryEquations((*_b)[i]);
   }
   _xAux = _x->extract(indicesToRemove);
   _bAux = _b->extract(indicesToRemove);
   _deltaAux = _delta->extract(indicesToRemove);
   _residualAux = _residual->extract(indicesToRemove);
 }
void LinearSystem::postSolve ()
Definition at line 250 of file LinearSystem.cpp.
References _b, _bAux, _delta, _deltaAux, _matrix, _residual, _residualAux, _x, _xAux, and MultiFieldMatrix::solveBoundary().
Referenced by FractureModel< T >::Impl::advance(), ThermalModel< T >::Impl::advance(), VacancyModel< T >::Impl::advance(), PhononModel< T >::advance(), SpeciesModel< T >::Impl::advance(), KeModel< T >::Impl::advance(), KineticModel< T >::advance(), BatteryModel< T >::Impl::advanceCoupled(), StructureModel< T >::Impl::advanceExplicit(), BatteryModel< T >::Impl::advancePotential(), BatteryModel< T >::Impl::advanceSpecies(), BatteryModel< T >::Impl::advanceThermal(), ElectricModel< T >::Impl::solveChargeTransport(), PlateModel< T >::Impl::solveDeformation(), StructureModel< T >::Impl::solveDeformation(), ElectricModel< T >::Impl::solveElectroStatics(), and FlowModel< T >::Impl::solveMomentum().
 {
   _matrix.solveBoundary(*_delta,*_b,*_residual);
   if (_xAux)
   {
       _x->merge(*_xAux);
       _b->merge(*_bAux);
       _delta->merge(*_deltaAux);
       _residual->merge(*_residualAux);
       _matrix.solveBoundary(*_delta,*_b,*_residual);
   }
 }
void LinearSystem::replaceB (shared_ptr< MultiField > newB) inline
Definition at line 45 of file LinearSystem.h.
References _b.
Referenced by BCGStab::solve(), and CG::solve().
 {_b=newB;}
void LinearSystem::replaceDelta (shared_ptr< MultiField > newDelta) inline
Definition at line 44 of file LinearSystem.h.
References _delta.
Referenced by BCGStab::solve(), and CG::solve().
 {_delta=newDelta;}
void LinearSystem::replaceResidual (shared_ptr< MultiField > newR) inline
Definition at line 46 of file LinearSystem.h.
References _residual.
 {_residual=newR;}
void LinearSystem::setCoarseningField (const Field & f) inline
Definition at line 48 of file LinearSystem.h.
References _coarseningField.
 {_coarseningField=&f;}
void LinearSystem::updateSolution ()
Definition at line 265 of file LinearSystem.cpp.
References _delta, and _x.
Referenced by FractureModel< T >::Impl::advance(), ThermalModel< T >::Impl::advance(), VacancyModel< T >::Impl::advance(), PhononModel< T >::advance(), SpeciesModel< T >::Impl::advance(), KeModel< T >::Impl::advance(), KineticModel< T >::advance(), BatteryModel< T >::Impl::advanceCoupled(), StructureModel< T >::Impl::advanceExplicit(), BatteryModel< T >::Impl::advancePotential(), BatteryModel< T >::Impl::advanceSpecies(), BatteryModel< T >::Impl::advanceThermal(), ElectricModel< T >::Impl::solveChargeTransport(), PlateModel< T >::Impl::solveDeformation(), StructureModel< T >::Impl::solveDeformation(), ElectricModel< T >::Impl::solveElectroStatics(), and FlowModel< T >::Impl::solveMomentum().
 {
   *_x += *_delta;
    _x->sync();
 }
Friends And Related Function Documentation
friend class LinearSystemMerger friend
Definition at line 15 of file LinearSystem.h.
Member Data Documentation
shared_ptr<MultiField> LinearSystem::_b private
Definition at line 55 of file LinearSystem.h.
Referenced by createCoarse(), getB(), getBPtr(), initAssembly(), initSolve(), postSolve(), and replaceB().
shared_ptr<MultiField> LinearSystem::_bAux private
Definition at line 61 of file LinearSystem.h.
Referenced by initSolve(), and postSolve().
MultiField LinearSystem::_coarseIndex private
Definition at line 58 of file LinearSystem.h.
Referenced by createCoarse(), and getCoarseIndex().
const Field* LinearSystem::_coarseningField private
Definition at line 59 of file LinearSystem.h.
Referenced by createCoarse(), and setCoarseningField().
shared_ptr<MultiField> LinearSystem::_delta private
Definition at line 56 of file LinearSystem.h.
Referenced by getDelta(), getDeltaPtr(), initSolve(), postSolve(), replaceDelta(), and updateSolution().
shared_ptr<MultiField> LinearSystem::_deltaAux private
Definition at line 62 of file LinearSystem.h.
Referenced by initSolve(), and postSolve().
MultiFieldMatrix LinearSystem::_matrix private
Definition at line 53 of file LinearSystem.h.
Referenced by createCoarse(), getMatrix(), initAssembly(), initSolve(), and postSolve().
shared_ptr<MultiField> LinearSystem::_residual private
Definition at line 57 of file LinearSystem.h.
Referenced by getResidual(), initSolve(), postSolve(), and replaceResidual().
shared_ptr<MultiField> LinearSystem::_residualAux private
Definition at line 63 of file LinearSystem.h.
Referenced by initSolve(), and postSolve().
shared_ptr<MultiField> LinearSystem::_x private
Definition at line 54 of file LinearSystem.h.
Referenced by getX(), initAssembly(), initSolve(), postSolve(), and updateSolution().
shared_ptr<MultiField> LinearSystem::_xAux private
Definition at line 60 of file LinearSystem.h.
Referenced by initSolve(), and postSolve().
bool LinearSystem::isSymmetric
Definition at line 50 of file LinearSystem.h.
Referenced by AMG::createCoarseLevels(), and AMG::cycle().
The documentation for this class was generated from the following files:
LinearSystem.h
LinearSystem.cpp