Memosa-FVM: GenericIBDiscretization< X, Diag, OffDiag > Class Template Reference
GenericIBDiscretization< X, Diag, OffDiag > Class Template Reference
#include <GenericIBDiscretization.h>
Public Types
typedef NumTypeTraits< X >
::T_Scalar T_Scalar
typedef CRMatrix< Diag,
OffDiag, X > CCMatrix
typedef CCMatrix::PairWiseAssembler CCAssembler
typedef CCMatrix::DiagArray DiagArray
typedef CCMatrix::OffDiagArray OffDiagArray
typedef Array< int > IntArray
typedef Array< X > XArray
typedef Array< T_Scalar > TArray
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
Public Member Functions
GenericIBDiscretization (const MeshList &meshes, const GeomFields &geomFields, Field &phiField)
void discretize (const Mesh &mesh, MultiFieldMatrix &mfmatrix, MultiField &xField, MultiField &rField)
Public Member Functions inherited from Discretization
Discretization (const MeshList &meshes)
virtual ~Discretization ()
DEFINE_TYPENAME ("Discretization")
Private Attributes
const GeomFields & _geomFields
Field & _phiField
Additional Inherited Members
Protected Attributes inherited from Discretization
const MeshList & _meshes
Detailed Description
template<class X, class Diag, class OffDiag>
class GenericIBDiscretization< X, Diag, OffDiag >
Definition at line 24 of file GenericIBDiscretization.h.
Member Typedef Documentation
template<class X , class Diag , class OffDiag > typedef CCMatrix::PairWiseAssembler GenericIBDiscretization< X, Diag, OffDiag >::CCAssembler
Definition at line 31 of file GenericIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CRMatrix<Diag,OffDiag,X> GenericIBDiscretization< X, Diag, OffDiag >::CCMatrix
Definition at line 30 of file GenericIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::DiagArray GenericIBDiscretization< X, Diag, OffDiag >::DiagArray
Definition at line 32 of file GenericIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<int> GenericIBDiscretization< X, Diag, OffDiag >::IntArray
Definition at line 35 of file GenericIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef CCMatrix::OffDiagArray GenericIBDiscretization< X, Diag, OffDiag >::OffDiagArray
Definition at line 33 of file GenericIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef NumTypeTraits<X>::T_Scalar GenericIBDiscretization< X, Diag, OffDiag >::T_Scalar
Definition at line 28 of file GenericIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<T_Scalar> GenericIBDiscretization< X, Diag, OffDiag >::TArray
Definition at line 37 of file GenericIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Vector<T_Scalar,3> GenericIBDiscretization< X, Diag, OffDiag >::VectorT3
Definition at line 38 of file GenericIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<VectorT3> GenericIBDiscretization< X, Diag, OffDiag >::VectorT3Array
Definition at line 39 of file GenericIBDiscretization.h.
template<class X , class Diag , class OffDiag > typedef Array<X> GenericIBDiscretization< X, Diag, OffDiag >::XArray
Definition at line 36 of file GenericIBDiscretization.h.
Constructor & Destructor Documentation
template<class X , class Diag , class OffDiag > GenericIBDiscretization< X, Diag, OffDiag >::GenericIBDiscretization (const MeshList & meshes, const GeomFields & geomFields, Field & phiField) inline
Definition at line 41 of file GenericIBDiscretization.h.
                                       :
     Discretization(meshes),
     _geomFields(geomFields),
     _phiField(phiField)
 {}
Member Function Documentation
template<class X , class Diag , class OffDiag > void GenericIBDiscretization< X, Diag, OffDiag >::discretize (const Mesh & mesh, MultiFieldMatrix & mfmatrix, MultiField & xField, MultiField & rField) inline virtual
Implements Discretization.
Definition at line 49 of file GenericIBDiscretization.h.
References GenericIBDiscretization< X, Diag, OffDiag >::_geomFields, GenericIBDiscretization< X, Diag, OffDiag >::_phiField, Mesh::getAllFaceCells(), Mesh::getCells(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff01(), CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler::getCoeff10(), StorageSite::getCount(), Mesh::getFaces(), Mesh::getIBFaces(), MultiFieldMatrix::getMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), GeomFields::ibFaceIndex, GeomFields::ibType, Mesh::IBTYPE_BOUNDARY, Mesh::IBTYPE_FLUID, CRMatrix< T_Diag, T_OffDiag, X >::setDirichlet(), and Array< T >::zero().
   {
     const StorageSite& ibFaces = mesh.getIBFaces();
     if (ibFaces.getCount() == 0)
       return;
     const StorageSite& cells = mesh.getCells();
     const StorageSite& faces = mesh.getFaces();
     const CRConnectivity& faceCells = mesh.getAllFaceCells();
     const MultiField::ArrayIndex vIndex(&_phiField,&cells);
     CCMatrix& matrix = dynamic_cast<CCMatrix&>(mfmatrix.getMatrix(vIndex,vIndex));
     CCAssembler& assembler = matrix.getPairWiseAssembler(faceCells);
     XArray& cellPhi =
       dynamic_cast<XArray&> (_phiField[cells]);
     XArray& rCell = dynamic_cast<XArray&>(rField[vIndex]);
     const XArray& ibPhi =
       dynamic_cast<const XArray&>(_phiField[mesh.getIBFaces()]);
     const IntArray& ibType = dynamic_cast<const IntArray&>(_geomFields.ibType[cells]);
    const IntArray& ibFaceIndex = dynamic_cast<const IntArray&>(_geomFields.ibFaceIndex[faces]);
     // used for computing the average value in IBTYPE_BOUNDARY cells.
     // we can't use the cellPhi storage during the loop below since a
     // cell may have more than one ib face and the current value of
     // phi in the cell is required to correctly impose the dirichlet
     // condition. so we accumulate the boundary cell value and counts
     // in the following arrays and after all the faces have been
     // visited, overwrite any boundary cell values with the average of
     // all the ib faces
     const int nCells = cells.getCount();
     XArray xB(nCells);
     Array<int> wB(nCells);
     xB.zero();
     wB.zero();
     const int nFaces = faces.getCount();
     for(int f=0; f<nFaces; f++)
     {
         const int c0 = faceCells(f,0);
         const int c1 = faceCells(f,1);
         if (((ibType[c0] == Mesh::IBTYPE_FLUID) && (ibType[c1] == Mesh::IBTYPE_BOUNDARY)) ||
             ((ibType[c1] == Mesh::IBTYPE_FLUID) && (ibType[c0] == Mesh::IBTYPE_BOUNDARY)))
         {
             // this is an iBFace, determine which cell is interior and which boundary
             const int ibFace = ibFaceIndex[f];
             if (ibFace < 0)
               throw CException("invalid ib face index");
             const X& facePhi = ibPhi[ibFace];
             if (ibType[c0] == Mesh::IBTYPE_FLUID)
             {
                 rCell[c0] += assembler.getCoeff01(f)*(facePhi-cellPhi[c1]);
                 rCell[c1] = NumTypeTraits<X>::getZero();
                 assembler.getCoeff01(f) = OffDiag(0);
                 matrix.setDirichlet(c1);
                 xB[c1] += facePhi;
                 wB[c1]++;
             }
             else
             {
                 rCell[c1] += assembler.getCoeff10(f)*(facePhi-cellPhi[c0]);
                 rCell[c0] = NumTypeTraits<X>::getZero();
                 assembler.getCoeff10(f) = OffDiag(0);
                 matrix.setDirichlet(c0);
                 xB[c0] += facePhi;
                 wB[c0]++;
             }
         }
         else if ((ibType[c0] == Mesh::IBTYPE_FLUID) &&
             (ibType[c1] == Mesh::IBTYPE_FLUID))
         {
             // leave as  is
         }
         else
         {
             // setup to get zero corrections
             rCell[c0] = NumTypeTraits<X>::getZero();
             rCell[c1] = NumTypeTraits<X>::getZero();
             matrix.setDirichlet(c0);
             matrix.setDirichlet(c1);
         }
     }
     // set the phi for boundary cells as average of the ib face values
     for(int c=0; c<nCells; c++)
     {
         if (wB[c] > 0)
           cellPhi[c] = xB[c] / T_Scalar(wB[c]);
     }
   }
Member Data Documentation
template<class X , class Diag , class OffDiag > const GeomFields& GenericIBDiscretization< X, Diag, OffDiag >::_geomFields private
Definition at line 154 of file GenericIBDiscretization.h.
Referenced by GenericIBDiscretization< X, Diag, OffDiag >::discretize().
template<class X , class Diag , class OffDiag > Field& GenericIBDiscretization< X, Diag, OffDiag >::_phiField private
Definition at line 155 of file GenericIBDiscretization.h.
Referenced by GenericIBDiscretization< X, Diag, OffDiag >::discretize().
The documentation for this class was generated from the following file:
GenericIBDiscretization.h