Memosa-FVM: SquareTensor< T, N > Class Template Reference
SquareTensor< T, N > Class Template Reference
#include <SquareTensor.h>
Public Types
enum { NSQR = N*N }
typedef SquareTensor< T, N > This_T
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef NumTypeTraits< T >
::T_BuiltIn T_BuiltIn
Public Member Functions
SquareTensor ()
SquareTensor (const SquareTensor &o)
SquareTensor (const T &s)
T & operator() (int i, int j)
const T & operator() (int i, int j) const
void printFromC (ostream &os) const
SquareTensor & operator= (const T &s)
SquareTensor & operator= (const SquareTensor &o)
SquareTensor operator- ()
SquareTensor & operator+= (const SquareTensor &o)
SquareTensor & operator+= (const T s)
SquareTensor & operator-= (const SquareTensor &o)
SquareTensor & operator-= (const T s)
SquareTensor & operator/= (const T s)
SquareTensor & operator/= (const SquareTensor &o)
SquareTensor & operator*= (const T s)
SquareTensor & operator*= (const SquareTensor &o)
void zero ()
T mag2 () const
bool operator< (const double tolerance) const
Static Public Member Functions
static string getTypeName ()
static int getDimension ()
static void getShape (int *shp)
static int getDataSize ()
static void write (FILE *fp, const SquareTensor &x)
static SquareTensor getZero ()
static double doubleMeasure (const SquareTensor &x)
static SquareTensor getNegativeUnity ()
static SquareTensor getUnity ()
static void accumulateOneNorm (SquareTensor &sum, const SquareTensor &v)
static void accumulateDotProduct (SquareTensor &sum, const SquareTensor &v0, const SquareTensor &v1)
static void reduceSum (T_Scalar &sum, const This_T &x)
static void safeDivide (SquareTensor &x, const SquareTensor &y)
static void normalize (SquareTensor &x, const SquareTensor &y)
static void setMax (SquareTensor &x, const SquareTensor &y)
Private Attributes
T _data [NSQR]
Detailed Description
template<class T, int N>
class SquareTensor< T, N >
Definition at line 15 of file SquareTensor.h.
Member Typedef Documentation
template<class T, int N> typedef NumTypeTraits<T>::T_BuiltIn SquareTensor< T, N >::T_BuiltIn
Definition at line 23 of file SquareTensor.h.
template<class T, int N> typedef NumTypeTraits<T>::T_Scalar SquareTensor< T, N >::T_Scalar
Definition at line 22 of file SquareTensor.h.
template<class T, int N> typedef SquareTensor<T,N> SquareTensor< T, N >::This_T
Definition at line 21 of file SquareTensor.h.
Member Enumeration Documentation
template<class T, int N> anonymous enum
Enumerator
NSQR
Definition at line 19 of file SquareTensor.h.
 { NSQR = N*N };
Constructor & Destructor Documentation
template<class T, int N> SquareTensor< T, N >::SquareTensor () inline
Definition at line 25 of file SquareTensor.h.
   {}
template<class T, int N> SquareTensor< T, N >::SquareTensor (const SquareTensor< T, N > & o) inline
Definition at line 28 of file SquareTensor.h.
   {
     for(int i=0; i<NSQR; i++)
       _data[i] = o._data[i];
   }
template<class T, int N> SquareTensor< T, N >::SquareTensor (const T & s) inline
Definition at line 34 of file SquareTensor.h.
   {
     for(int i=0; i<N; i++)
       for(int j=0; j<N; j++)
         (*this)(i,j) = (i==j) ? s : 0;
   }
Member Function Documentation
template<class T, int N> static void SquareTensor< T, N >::accumulateDotProduct (SquareTensor< T, N > & sum, const SquareTensor< T, N > & v0, const SquareTensor< T, N > & v1) inline static
Definition at line 224 of file SquareTensor.h.
   {
     for(int i=0; i<NSQR; i++)
       NumTypeTraits<T>::accumulateDotProduct(sum._data[i],v0._data[i],v1._data[i]);
   }
template<class T, int N> static void SquareTensor< T, N >::accumulateOneNorm (SquareTensor< T, N > & sum, const SquareTensor< T, N > & v) inline static
Definition at line 218 of file SquareTensor.h.
   {
     for(int i=0; i<NSQR; i++)
       NumTypeTraits<T>::accumulateOneNorm(sum._data[i],v._data[i]);
   }
template<class T, int N> static double SquareTensor< T, N >::doubleMeasure (const SquareTensor< T, N > & x) inline static
Definition at line 192 of file SquareTensor.h.
   {
     double m=0;
     for (int i=0; i<N; i++)
       m += NumTypeTraits<T>::doubleMeasure(x(i,i));
     return m;
   }
template<class T, int N> static int SquareTensor< T, N >::getDataSize () inline static
Definition at line 52 of file SquareTensor.h.
   {
     return NSQR*NumTypeTraits<T>::getDataSize();
   }
template<class T, int N> static int SquareTensor< T, N >::getDimension () inline static
Definition at line 49 of file SquareTensor.h.
 {return 1;}
template<class T, int N> static SquareTensor SquareTensor< T, N >::getNegativeUnity () inline static
Definition at line 200 of file SquareTensor.h.
   {
     SquareTensor n(getZero());
     for(int i=0; i<N; i++)
       n(i,i) = NumTypeTraits<T>::getNegativeUnity();
     return n;
   }
template<class T, int N> static void SquareTensor< T, N >::getShape (int * shp) inline static
Definition at line 51 of file SquareTensor.h.
 { *shp = NSQR;}
template<class T, int N> static string SquareTensor< T, N >::getTypeName () inline static
Definition at line 42 of file SquareTensor.h.
   {
     return "SquareTensor<" + NumTypeTraits<T>::getTypeName() +
       "," + intAsString(N) +
       ">";
   }
template<class T, int N> static SquareTensor SquareTensor< T, N >::getUnity () inline static
Definition at line 209 of file SquareTensor.h.
   {
     SquareTensor n(getZero());
     for(int i=0; i<N; i++)
       n(i,i) = NumTypeTraits<T>::getUnity();
     return n;
   }
template<class T, int N> static SquareTensor SquareTensor< T, N >::getZero () inline static
Definition at line 185 of file SquareTensor.h.
Referenced by SquareTensor< X, K >::getNegativeUnity(), and SquareTensor< X, K >::getUnity().
   {
     SquareTensor z;
     z.zero();
     return z;
   }
template<class T, int N> T SquareTensor< T, N >::mag2 () const inline
Definition at line 172 of file SquareTensor.h.
Referenced by SquareTensor< X, K >::operator<().
   {
     T r(NumTypeTraits<T>::getZero());
     for(int i=0; i<N; i++)
       r += (*this)(i,i) * (*this)(i,i);
     return r;
   }
template<class T, int N> static void SquareTensor< T, N >::normalize (SquareTensor< T, N > & x, const SquareTensor< T, N > & y) inline static
Definition at line 243 of file SquareTensor.h.
   {
     for(int i=0; i<NSQR; i++)
       NumTypeTraits<T>::normalize(x._data[i],y._data[i]);
   }
template<class T, int N> T& SquareTensor< T, N >::operator() (int i, int j) inline
Definition at line 58 of file SquareTensor.h.
 {return _data[i*N+j];}
template<class T, int N> const T& SquareTensor< T, N >::operator() (int i, int j) const inline
Definition at line 62 of file SquareTensor.h.
 {return _data[i*N+j];}
template<class T, int N> SquareTensor& SquareTensor< T, N >::operator*= (const T s) inline
Definition at line 145 of file SquareTensor.h.
   {
     for(int i=0;i<NSQR;i++)
       _data[i] *= s;
     return *this;
   }
template<class T, int N> SquareTensor& SquareTensor< T, N >::operator*= (const SquareTensor< T, N > & o) inline
Definition at line 152 of file SquareTensor.h.
   {
     SquareTensor p;
     for(int i=0;i<N;i++)
       for(int j=0;j<N;j++)
       {
           p(i,j) = 0;
           for(int k=0;k<N;k++)
             p(i,j) += (*this)(i,k) * o(k,j);
       }
     *this = p;
     return *this;
   }
template<class T, int N> SquareTensor& SquareTensor< T, N >::operator+= (const SquareTensor< T, N > & o) inline
Definition at line 104 of file SquareTensor.h.
   {
     for(int i=0;i<NSQR;i++)
       _data[i] += o._data[i];
     return *this;
   }
template<class T, int N> SquareTensor& SquareTensor< T, N >::operator+= (const T s) inline
Definition at line 111 of file SquareTensor.h.
   {
     for(int i=0;i<N;i++)
       (*this)(i,i) += s;
     return *this;
   }
template<class T, int N> SquareTensor SquareTensor< T, N >::operator- () inline
Definition at line 96 of file SquareTensor.h.
   {
     SquareTensor r;
     for(int i=0;i<NSQR;i++)
       r._data[i]=-_data[i];
     return r;
   }
template<class T, int N> SquareTensor& SquareTensor< T, N >::operator-= (const SquareTensor< T, N > & o) inline
Definition at line 118 of file SquareTensor.h.
   {
     for(int i=0;i<NSQR;i++)
       _data[i] -= o._data[i];
     return *this;
   }
template<class T, int N> SquareTensor& SquareTensor< T, N >::operator-= (const T s) inline
Definition at line 125 of file SquareTensor.h.
   {
     for(int i=0;i<N;i++)
       (*this)(i,i) -= s;
     return *this;
   }
template<class T, int N> SquareTensor& SquareTensor< T, N >::operator/= (const T s) inline
Definition at line 132 of file SquareTensor.h.
   {
     for(int i=0;i<NSQR;i++)
       _data[i] /= s;
     return *this;
   }
template<class T, int N> SquareTensor& SquareTensor< T, N >::operator/= (const SquareTensor< T, N > & o) inline
Definition at line 139 of file SquareTensor.h.
   {
     *this *= inverse(o);
     return *this;
   }
template<class T, int N> bool SquareTensor< T, N >::operator< (const double tolerance) const inline
Definition at line 180 of file SquareTensor.h.
   {
     return mag2() < tolerance*tolerance;
   }
template<class T, int N> SquareTensor& SquareTensor< T, N >::operator= (const T & s) inline
Definition at line 81 of file SquareTensor.h.
   {
     for(int i=0; i<N; i++)
       for(int j=0; j<N; j++)
         (*this)(i,j) = (i==j) ? s : T(0.);
     return *this;
   }
template<class T, int N> SquareTensor& SquareTensor< T, N >::operator= (const SquareTensor< T, N > & o) inline
Definition at line 89 of file SquareTensor.h.
   {
     for(int i=0;i<NSQR;i++)
       _data[i] = o._data[i];
     return *this;
   }
template<class T, int N> void SquareTensor< T, N >::printFromC (ostream & os) const inline
Definition at line 64 of file SquareTensor.h.
Referenced by operator<<().
   {
     os << "[ " ;
     for(int i=0;i<NSQR;i++)
       os << _data[i] << " " ;
     os << "]";
   }
template<class T, int N> static void SquareTensor< T, N >::reduceSum (T_Scalar & sum, const This_T & x) inline static
Definition at line 231 of file SquareTensor.h.
   {
     for(int i=0; i<NSQR; i++)
       NumTypeTraits<T>::reduceSum(sum,x._data[i]);
   }
template<class T, int N> static void SquareTensor< T, N >::safeDivide (SquareTensor< T, N > & x, const SquareTensor< T, N > & y) inline static
Definition at line 237 of file SquareTensor.h.
   {
     for(int i=0; i<NSQR; i++)
       NumTypeTraits<T>::safeDivide(x._data[i],y._data[i]);
   }
template<class T, int N> static void SquareTensor< T, N >::setMax (SquareTensor< T, N > & x, const SquareTensor< T, N > & y) inline static
Definition at line 249 of file SquareTensor.h.
   {
     for(int i=0; i<NSQR; i++)
       NumTypeTraits<T>::setMax(x._data[i],y._data[i]);
   }
template<class T, int N> static void SquareTensor< T, N >::write (FILE * fp, const SquareTensor< T, N > & x) inline static
Definition at line 72 of file SquareTensor.h.
   {
     for(int i=0; i<NSQR; i++)
     {
         NumTypeTraits<T>::write(fp,x[i]);
         fprintf(fp, " ");
     }
   }
template<class T, int N> void SquareTensor< T, N >::zero () inline
Definition at line 167 of file SquareTensor.h.
Referenced by ArrowHeadMatrix< X, K >::ArrowHeadMatrix(), Kspace< T >::getHollandConductivity(), VectorTranspose< X, K >::getTensor(), SquareTensor< X, K >::getZero(), COMETDiscretizer< T >::updateeShifted(), and ArrowHeadMatrix< X, K >::zero().
   {
     for(int i=0;i<NSQR;i++) _data[i] = NumTypeTraits<T>::getZero();
   }
Member Data Documentation
template<class T, int N> T SquareTensor< T, N >::_data[NSQR] private
Definition at line 256 of file SquareTensor.h.
Referenced by SquareTensor< X, K >::accumulateDotProduct(), SquareTensor< X, K >::accumulateOneNorm(), SquareTensor< X, K >::normalize(), SquareTensor< X, K >::operator()(), SquareTensor< X, K >::operator*=(), SquareTensor< X, K >::operator+=(), SquareTensor< X, K >::operator-(), SquareTensor< X, K >::operator-=(), SquareTensor< X, K >::operator/=(), SquareTensor< X, K >::operator=(), SquareTensor< X, K >::printFromC(), SquareTensor< X, K >::reduceSum(), SquareTensor< X, K >::safeDivide(), SquareTensor< X, K >::setMax(), and SquareTensor< X, K >::SquareTensor().
The documentation for this class was generated from the following file:
SquareTensor.h