Memosa-FVM: CRMatrix< T_Diag, T_OffDiag, X > Class Template Reference
CRMatrix< T_Diag, T_OffDiag, X > Class Template Reference
#include <CRMatrix.h>
Classes
class PairWiseAssembler
Public Types
typedef T_Diag Diag
typedef T_OffDiag OffDiag
typedef Array< Diag > DiagArray
typedef Array< int > IntArray
typedef Array< OffDiag > OffDiagArray
typedef Array< X > XArray
typedef shared_ptr< Array< int > > IntArrayPtr
typedef shared_ptr< Array< Diag > > DiagArrayPtr
typedef shared_ptr< Array
< double > > ArrayDblePtr
typedef SpikeMatrix< Diag,
OffDiag, X > T_SpikeMtrx
typedef pair< const
StorageSite *, const
StorageSite * > EntryIndex
typedef map< EntryIndex,
shared_ptr< ArrayBase > > GhostArrayMap
typedef map< const
CRConnectivity
*, PairWiseAssembler * > PairWiseAssemblerMap
Public Member Functions
CRMatrix (const CRConnectivity &conn)
DEFINE_TYPENAME ("CRMatrix<"+NumTypeTraits< Diag >::getTypeName()+","+NumTypeTraits< OffDiag >::getTypeName()+","+NumTypeTraits< X >::getTypeName()+">")
virtual void initAssembly ()
virtual void multiply (IContainer &yB, const IContainer &xB) const
virtual void multiplyAndAdd (IContainer &yB, const IContainer &xB) const
virtual void transpose ()
virtual shared_ptr< ArrayBase > quadProduct (const IContainer &xB) const
virtual void forwardGS (IContainer &xB, IContainer &bB, IContainer &) const
virtual void reverseGS (IContainer &xB, IContainer &bB, IContainer &) const
virtual void Jacobi (IContainer &xnewB, const IContainer &xoldB, const IContainer &bB) const
virtual void iluSolve (IContainer &xB, const IContainer &bB, const IContainer &) const
virtual void spikeSolve (IContainer &xB, const IContainer &bB, const IContainer &, const SpikeStorage &spike_storage) const
virtual void computeResidual (const IContainer &xB, const IContainer &bB, IContainer &rB) const
virtual void solveBoundary (IContainer &xB, IContainer &bB, IContainer &) const
virtual int createCoarsening (IContainer &gCoarseIndex, const int groupSize, const double weightRatioThreshold)
shared_ptr< CRConnectivity > createCoarseConnectivity (const IContainer &gCoarseIndex, const CRConnectivity &coarseToFine, const StorageSite &coarseRowSite, const StorageSite &coarseColSite)
shared_ptr< Matrix > createCoarseMatrix (const IContainer &gCoarseIndex, const CRConnectivity &coarseToFine, const CRConnectivity &coarseConnectivity)
virtual const CRConnectivity & getConnectivity () const
OffDiag & getCoeff (const int i, const int j)
bool hasCoeff (const int i, const int j)
Array< Diag > & getDiag ()
Array< OffDiag > & getOffDiag ()
const Array< Diag > & getDiag () const
const Array< OffDiag > & getOffDiag () const
void * getDiagData () const
void * getOffDiagData () const
int getDiagDataSize () const
int getOffDiagDataSize () const
PairWiseAssembler & getPairWiseAssembler (const CRConnectivity &pairs)
virtual ~CRMatrix ()
void setDirichlet (const int nr)
void eliminateRow (const int j, Array< X > &b)
void eliminateRowGhost (Array< X > &b)
virtual void printRow (const int i) const
void eliminateDirichlet (const int j, Array< X > &b, const X &delta_j, const bool explicitMode=false)
void setBoundary (const int nr)
virtual void eliminateBoundaryEquations (IContainer &bB)
virtual void setFlatMatrix (Matrix &fmg) const
Public Member Functions inherited from Matrix
Matrix ()
virtual ~Matrix ()
DEFINE_TYPENAME ("Matrix")
virtual shared_ptr< Matrix > createMergeMatrix (const LinearSystemMerger &mergeLS)
virtual bool isInvertible ()
Private Member Functions
void syncBndryCoeffs (const Array< X > &b)
void createScatterGatherCountsBuffer ()
void syncCounts ()
void createScatterGatherIndicesBuffer ()
void syncIndices ()
void createScatterGatherValuesCRMtrxBuffer ()
void syncValuesCRMtrx ()
void createScatterGatherValuesBBuffer (const XArray &B)
void syncValuesB ()
int get_request_size ()
void compute_ILU0 () const
void lowerSolve (XArray &y, const XArray &b) const
void upperSolve (XArray &x, const XArray &y) const
Private Attributes
const CRConnectivity & _conn
const Array< int > & _row
const Array< int > & _col
Array< Diag > _diag
Array< OffDiag > _offDiag
PairWiseAssemblerMap _pairWiseAssemblers
Array< bool > _isBoundary
shared_ptr< CRConnectivity > _iluConnPtr
IntArrayPtr _iluDiagIndexPtr
DiagArrayPtr _iluCoeffsPtr
shared_ptr< T_SpikeMtrx > _spikeMtrx
GhostArrayMap _sendCounts
GhostArrayMap _recvCounts
GhostArrayMap _sendIndices
GhostArrayMap _recvIndices
GhostArrayMap _sendValuesCRMtrx
GhostArrayMap _recvValuesCRMtrx
GhostArrayMap _sendValuesB
GhostArrayMap _recvValuesB
map< int, int > _ghostCellBoundayMap
Detailed Description
template<class T_Diag, class T_OffDiag, class X>
class CRMatrix< T_Diag, T_OffDiag, X >
Sparse matrix stored using a compressed row format. The sparsity pattern is provided by a CRConnectivity object that is required at construction time. Note that we assume that diagonal is implicitly always present (i.e., col[row[i]] through col[row[i+1]] do not contain i) and store diagonal and off diagonal entries in separate arrays.
The class is templated with the types of diagonal, off-diagonal and the corresponding x arrays as template parameters.
Definition at line 87 of file CRMatrix.h.
Member Typedef Documentation
template<class T_Diag, class T_OffDiag, class X> typedef shared_ptr< Array<double> > CRMatrix< T_Diag, T_OffDiag, X >::ArrayDblePtr
Definition at line 103 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef T_Diag CRMatrix< T_Diag, T_OffDiag, X >::Diag
Definition at line 93 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef Array<Diag> CRMatrix< T_Diag, T_OffDiag, X >::DiagArray
Definition at line 95 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef shared_ptr< Array<Diag> > CRMatrix< T_Diag, T_OffDiag, X >::DiagArrayPtr
Definition at line 101 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef pair<const StorageSite*, const StorageSite*> CRMatrix< T_Diag, T_OffDiag, X >::EntryIndex
Definition at line 106 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef map<EntryIndex, shared_ptr<ArrayBase> > CRMatrix< T_Diag, T_OffDiag, X >::GhostArrayMap
Definition at line 107 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef Array<int> CRMatrix< T_Diag, T_OffDiag, X >::IntArray
Definition at line 96 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef shared_ptr< Array<int> > CRMatrix< T_Diag, T_OffDiag, X >::IntArrayPtr
Definition at line 100 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef T_OffDiag CRMatrix< T_Diag, T_OffDiag, X >::OffDiag
Definition at line 94 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef Array<OffDiag> CRMatrix< T_Diag, T_OffDiag, X >::OffDiagArray
Definition at line 98 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef map<const CRConnectivity*,PairWiseAssembler*> CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssemblerMap
Definition at line 162 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef SpikeMatrix< Diag, OffDiag, X> CRMatrix< T_Diag, T_OffDiag, X >::T_SpikeMtrx
Definition at line 104 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> typedef Array<X> CRMatrix< T_Diag, T_OffDiag, X >::XArray
Definition at line 99 of file CRMatrix.h.
Constructor & Destructor Documentation
template<class T_Diag, class T_OffDiag, class X> CRMatrix< T_Diag, T_OffDiag, X >::CRMatrix (const CRConnectivity & conn) inline
Definition at line 165 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary, and logCtor.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix().
                                        :
     Matrix(),
     _conn(conn),
     _row(_conn.getRow()),
     _col(_conn.getCol()),
     _diag(_conn.getRowDim()),
     _offDiag(_col.getLength()),
     _pairWiseAssemblers(),
     _isBoundary(_conn.getRowDim()),
     _spikeMtrx()
   {
     logCtor();
     _isBoundary = false;
   }
template<class T_Diag, class T_OffDiag, class X> virtual CRMatrix< T_Diag, T_OffDiag, X >::~CRMatrix () inline virtual
Definition at line 878 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_pairWiseAssemblers, and logDtor.
   {
     for (typename PairWiseAssemblerMap::iterator pos = _pairWiseAssemblers.begin();
          pos != _pairWiseAssemblers.end();
          ++pos)
       delete pos->second;
     logDtor();
   }
Member Function Documentation
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0 () const inline private
Definition at line 1546 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_iluCoeffsPtr, CRMatrix< T_Diag, T_OffDiag, X >::_iluConnPtr, CRMatrix< T_Diag, T_OffDiag, X >::_iluDiagIndexPtr, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, CRConnectivity::add(), CRConnectivity::addCount(), CRConnectivity::finishAdd(), CRConnectivity::finishCount(), CRConnectivity::getCol(), CRConnectivity::getColSite(), Array< T >::getLength(), CRConnectivity::getRow(), CRConnectivity::getRowSite(), StorageSite::getSelfCount(), and CRConnectivity::initCount().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::iluSolve().
   {
     const int nRows = _conn.getRowSite().getSelfCount();
     // create connectivity matrix for the ILU factored matrix; for ILU
     // 0 the only difference from this CRMatrix's connectivity is that
     // the diagonal is explicitly included
     //
     _iluConnPtr = shared_ptr<CRConnectivity>
       (new CRConnectivity(_conn.getRowSite(),_conn.getColSite()));
     CRConnectivity& iluConn = *_iluConnPtr;
     iluConn.initCount();
     for(int nr=0; nr<nRows; nr++)
     {
         // add one for diagonal
         iluConn.addCount(nr,1);
         for(int nb=_row[nr]; nb<_row[nr+1]; nb++)
         {
             // only include neighbours in this matrix
             if (_col[nb] < nRows)
               iluConn.addCount(nr,1);
         }
     }
     iluConn.finishCount();
     const int nnz = iluConn.getCol().getLength();
     _iluCoeffsPtr = DiagArrayPtr(new DiagArray(nnz));
     _iluDiagIndexPtr = IntArrayPtr(new IntArray(nRows));
     DiagArray& iluCoeffs = *_iluCoeffsPtr;
     IntArray& iluDiagIndex = *_iluDiagIndexPtr;
     // now we can fill the iluCoeffs with this matrix's coeffs
     for(int nr=0; nr<nRows; nr++)
     {
         // lower coeffs first
         for(int nb=_row[nr]; nb<_row[nr+1]; nb++)
         {
             const int j = _col[nb];
             if (j < nRows && j < nr)
             {
                 const int pos = iluConn.add(nr,j);
                 iluCoeffs[pos] = _offDiag[nb];
             }
         }
         // add diagonal next
         const int pos = iluConn.add(nr,nr);
         iluCoeffs[pos] = _diag[nr];
         iluDiagIndex[nr] = pos;
         // finally the upper coeffs
         for(int nb=_row[nr]; nb<_row[nr+1]; nb++)
         {
             const int j = _col[nb];
             if (j < nRows && j > nr)
             {
                 const int pos = iluConn.add(nr,j);
                 iluCoeffs[pos] = _offDiag[nb];
             }
         }
     }
     // finalize the iluConnectivity
     iluConn.finishAdd();
     // ilu decomposition
     const IntArray& iluRow = iluConn.getRow();
     const IntArray& iluCol = iluConn.getCol();
     //work array iw(n) and diagonal pointer uptr
     Array<int> iw(nRows);
     Array<int> uptr(nRows);
     iw = 0;
     uptr = 0;
     const Diag unity(NumTypeTraits<Diag>::getUnity());
     //main loop
     for (int k = 0; k < nRows; k++ )
     {
         const int j1 = iluRow[k];
         const int j2 = iluRow[k+1];
         for (int j = j1; j <j2; j++ )
           iw[ iluCol[j] ] = j;
         int j = j1;
         do
         {
             int jrow = iluCol[j];
             if ( jrow < k )
             {
                 const Diag t1 = iluCoeffs[j] * iluCoeffs[ uptr[jrow] ];
                 iluCoeffs[j] = t1;
                 //perform linear combination
                 for (int jj = uptr[jrow]+1; jj < iluRow[jrow+1]; jj++ )
                 {
                     int jw = iw[  iluCol[jj] ];
                     if ( jw != 0 )
                          iluCoeffs[jw] -= t1 * iluCoeffs[jj];
                 }
                 j++;
             }
             else
             {
                 uptr[k] = j;
                 break;
             }
         }
         while( j < j2 );
         //inverting diagonal
         iluCoeffs[j]  = unity / iluCoeffs[j];
         //zeroing iw
         for ( int i = j1; i < j2; i++ )
           iw[ iluCol[i] ] = 0;
     }
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::computeResidual (const IContainer & xB, const IContainer & bB, IContainer & rB) const inline virtual
r = b + this*x
Reimplemented from Matrix.
Definition at line 407 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
   {
     const XArray& x = dynamic_cast<const XArray&>(xB);
     const XArray& b = dynamic_cast<const XArray&>(bB);
     XArray& r = dynamic_cast<XArray&>(rB);
     const int nRows = _conn.getRowSite().getSelfCount();
     for(int nr=0; nr<nRows; nr++)
     {
         r[nr] = b[nr] + _diag[nr]*x[nr];
         for (int nb = _row[nr]; nb<_row[nr+1]; nb++)
         {
             const int j = _col[nb];
             r[nr] += _offDiag[nb]*x[j];
         }
     }
   }
template<class T_Diag, class T_OffDiag, class X> shared_ptr<CRConnectivity> CRMatrix< T_Diag, T_OffDiag, X >::createCoarseConnectivity (const IContainer & gCoarseIndex, const CRConnectivity & coarseToFine, const StorageSite & coarseRowSite, const StorageSite & coarseColSite) inline virtual
Create the connectivity for a coarse level matrix given the coarsening (ie. the fine to coarse index mapping) and its transpose (ie coarse to fine mapping, provided as a CRConnectivity object)
Reimplemented from Matrix.
Definition at line 598 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_row, CRConnectivity::getCount(), and StorageSite::getCountLevel1().
   {
     const Array<int>&  coarseIndex = dynamic_cast<const Array<int>& >(gCoarseIndex);
     const int nCoarseRows = coarseRowSite.getCountLevel1();
     shared_ptr<CRConnectivity> coarseCR(new CRConnectivity(coarseRowSite,coarseColSite));
     coarseCR->initCount();
     Array<bool> coarseCounted(nCoarseRows);
     coarseCounted = false;
     for(int nrCoarse=0; nrCoarse<nCoarseRows; nrCoarse++)
     {
         const int nFine = coarseToFine.getCount(nrCoarse);
         for(int nfr=0; nfr<nFine; nfr++)
         {
             const int nrFine = coarseToFine(nrCoarse,nfr);
             for (int nb = _row[nrFine]; nb<_row[nrFine+1]; nb++)
             {
                 const int nc = _col[nb];
                 const int ncCoarse = coarseIndex[nc];
                 if (ncCoarse>=0 && nrCoarse!=ncCoarse && !coarseCounted[ncCoarse])
                 {
                     coarseCounted[ncCoarse] = true;
                     coarseCR->addCount(nrCoarse,1);
                 }
             }
         }
         // reset counted
         for(int nfr=0; nfr<nFine; nfr++)
         {
             const int nrFine = coarseToFine(nrCoarse,nfr);
             for (int nb = _row[nrFine]; nb<_row[nrFine+1]; nb++)
             {
                 const int nc = _col[nb];
                 const int ncCoarse = coarseIndex[nc];
                 if (ncCoarse>=0)
                   coarseCounted[ncCoarse] = false;
             }
         }
     }
     coarseCR->finishCount();
     for(int nrCoarse=0; nrCoarse<nCoarseRows; nrCoarse++)
     {
         const int nFine = coarseToFine.getCount(nrCoarse);
         for(int nfr=0; nfr<nFine; nfr++)
         {
             const int nrFine = coarseToFine(nrCoarse,nfr);
             for (int nb = _row[nrFine]; nb<_row[nrFine+1]; nb++)
             {
                 const int nc = _col[nb];
                 const int ncCoarse = coarseIndex[nc];
                 if (ncCoarse>=0 && nrCoarse!=ncCoarse && !coarseCounted[ncCoarse])
                 {
                     coarseCounted[ncCoarse] = true;
                     coarseCR->add(nrCoarse,ncCoarse);
                 }
             }
         }
         // reset counted
         for(int nfr=0; nfr<nFine; nfr++)
         {
             const int nrFine = coarseToFine(nrCoarse,nfr);
             for (int nb = _row[nrFine]; nb<_row[nrFine+1]; nb++)
             {
                 const int nc = _col[nb];
                 const int ncCoarse = coarseIndex[nc];
                 if (ncCoarse>=0)
                 coarseCounted[ncCoarse] = false;
             }
         }
     }
     coarseCR->finishAdd();
     return coarseCR;
   }
template<class T_Diag, class T_OffDiag, class X> shared_ptr<Matrix> CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix (const IContainer & gCoarseIndex, const CRConnectivity & coarseToFine, const CRConnectivity & coarseConnectivity) inline virtual
create the coarse matrix given the coarsening and the coarse level connectivity.
Reimplemented from Matrix.
Definition at line 700 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, CRMatrix< T_Diag, T_OffDiag, X >::CRMatrix(), CRConnectivity::getCol(), CRConnectivity::getCount(), CRConnectivity::getRow(), CRConnectivity::getRowDim(), and Array< T >::zero().
   {
     const Array<int>&  coarseIndex = dynamic_cast<const Array<int>& >(gCoarseIndex);
     const int nCoarseRows = coarseConnectivity.getRowDim();
     shared_ptr<CRMatrix> coarseMatrix(new CRMatrix(coarseConnectivity));
     Array<Diag>& coarseDiag = coarseMatrix->getDiag();
     Array<OffDiag>& coarseOffDiag = coarseMatrix->getOffDiag();
     const Array<int>& coarseConnRow = coarseConnectivity.getRow();
     const Array<int>& coarseConnCol = coarseConnectivity.getCol();
     coarseDiag.zero();
     coarseOffDiag.zero();
     //used to avoid searches when inserting coeffs
     Array<int> coarseCoeffPos(nCoarseRows);
     for(int nrCoarse=0; nrCoarse<nCoarseRows; nrCoarse++)
     {
         // for easy indexing when inserting coefficients set col
         // positions into the coarse connectivity
         for(int nb=coarseConnRow[nrCoarse]; nb<coarseConnRow[nrCoarse+1]; nb++)
           coarseCoeffPos[coarseConnCol[nb]] = nb;
         // loop over the fine rows that make up this coarse row
         const int nFine = coarseToFine.getCount(nrCoarse);
         for(int nfr=0; nfr<nFine; nfr++)
         {
             const int nrFine = coarseToFine(nrCoarse,nfr);
             coarseDiag[nrCoarse] += _diag[nrFine];
             for (int nb = _row[nrFine]; nb<_row[nrFine+1]; nb++)
             {
                 const int nc = _col[nb];
                 const int ncCoarse = coarseIndex[nc];
                 if (ncCoarse<0) continue;
                 if (nrCoarse!=ncCoarse)
                 {
                     const int pos = coarseCoeffPos[ncCoarse];
                     coarseOffDiag[pos] += _offDiag[nb];
                 }
                 else
                 {
                     coarseDiag[nrCoarse] += _offDiag[nb];
                 }
             }
         }
     }
     return coarseMatrix;
   }
template<class T_Diag, class T_OffDiag, class X> virtual int CRMatrix< T_Diag, T_OffDiag, X >::createCoarsening (IContainer & gCoarseIndex, const int groupSize, const double weightRatioThreshold) inline virtual
create a matrix coarsening by agglomerating rows with neighbours that have the largest coefficients. groupSize is the approximate number of fine rows grouped in each coarse row and weightRatioThreshold is used to dtermine if the coefficient is large enough.
The coarsening is defined by the coarseIndex array that stores for each fine row the index of the coarse row into which it has been grouped. The function returns the size of the coarse level.
Reimplemented from Matrix.
Definition at line 468 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, fabs(), CRConnectivity::getRowSite(), StorageSite::getSelfCount(), and max().
   {
     Array<int>&  coarseIndex = dynamic_cast<Array<int>& >(gCoarseIndex);
     const int nRows = _conn.getRowSite().getSelfCount();
     coarseIndex = -1;
     // the number of rows in the coarse level matrix
     int nCoarseRows=0;
     // temp storage to keep track of how many in each coarse group
     Array<int> coarseCount(nRows);
     coarseCount = 0;
     for(int nr=0; nr<nRows; nr++)
       if (coarseIndex[nr] == -1 && !_isBoundary[nr])
       {
           // the row that we are going to go through looking for
           // neighbours to group with; it starts off being the current
           // row but for group sizes greater than 2 it will be reset
           // to the ones that we group this one with
           int current = nr;
           int colMaxGrouped=-1; // columnn with largest coeff among grouped ones
           int colMaxUngrouped=-1; // columnn with largest coeff among ungrouped ones
           int nGrouped;
           // assign current row to a new coarse row
           coarseIndex[current] = nCoarseRows;
           for(nGrouped=1; nGrouped<groupSize; nGrouped++)
           {
               // find largest coeff among both grouped and ungrouped columns
               double maxWeightUngrouped = 0;
               double maxWeightGrouped = 0;
               colMaxGrouped = -1;
               colMaxUngrouped = -1;
               for(int nb=_row[current]; nb<_row[current+1]; nb++)
               {
                   const int nc = _col[nb];
                   //skip ghost and boundaries
                   if (nc < nRows  && !_isBoundary[nc])
                   {
                       double diagMeasure0 =
                         NumTypeTraits<Diag>::doubleMeasure(_diag[nr]);
                       double diagMeasure1 =
                         NumTypeTraits<Diag>::doubleMeasure(_diag[nc]);
                       double coeffMeasure =
                         NumTypeTraits<OffDiag>::doubleMeasure(_offDiag[nb]);
                       double thisWeight = fabs(coeffMeasure /
                                                max(diagMeasure0,diagMeasure1));
                       if (coarseIndex[nc] == -1)
                       {
                           if (colMaxUngrouped == -1 || (thisWeight > maxWeightUngrouped))
{
                               colMaxUngrouped = nc;
                               maxWeightUngrouped = thisWeight;
                           }
                       }
                       else if (coarseIndex[nc] != coarseIndex[nr])
                       {
                           if (colMaxGrouped == -1 || (thisWeight > maxWeightGrouped))
{
                               colMaxGrouped = nc;
                               maxWeightGrouped = thisWeight;
                           }
                       }
                   }
               }
               // if we found at least one ungrouped row, group it
               // with the current one as long as it is large
               // enough compared to already grouped ones
               if ( (colMaxUngrouped != -1) &&
                    (colMaxGrouped == -1 ||
                     (maxWeightUngrouped > weightRatioThreshold*maxWeightGrouped)))
               {
                   coarseIndex[colMaxUngrouped] = coarseIndex[current];
                   coarseCount[coarseIndex[current]]++;
                   // next we will look at neighbours of this row
                   current = colMaxUngrouped;
               }
               else
                 // no point trying to find more for the current coarse group
                 break;
           }
           // if we managed to find at least one ungrouped
           // neighbour to group the current row with or if there
           // is no already grouped neighbour that is too crowded
           // then accept the new group
           if (nGrouped > 1 || colMaxGrouped == -1 ||
               coarseCount[coarseIndex[colMaxGrouped]] > groupSize+2)
           {
               coarseCount[coarseIndex[nr]]++;
               nCoarseRows++;
           }
           else
           {
               // put the current row in an existing group
               coarseIndex[nr] = coarseIndex[colMaxGrouped];
               coarseCount[coarseIndex[colMaxGrouped]]++;
           }
       }
     return nCoarseRows;
   }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer () inline private
Definition at line 1117 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary, CRMatrix< T_Diag, T_OffDiag, X >::_recvCounts, CRMatrix< T_Diag, T_OffDiag, X >::_sendCounts, CRConnectivity::getCount(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), Array< T >::getLength(), CRConnectivity::getRowSite(), and StorageSite::getScatterMapLevel1().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::syncBndryCoeffs().
     {
        //SENDING allocation and filling
        const StorageSite& site     = _conn.getRowSite();
        const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
        foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
            const StorageSite&  oSite = *mpos.first;
            //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
            const Array<int>& scatterArray = *mpos.second;
            int boundaryCount = 0;
            vector<int> cellCellsCount;
            for (int i = 0; i < scatterArray.getLength(); i++){
               const int cellID = scatterArray[i];
               if ( _isBoundary[cellID] ){
                  boundaryCount++;
                  cellCellsCount.push_back( _conn.getCount( scatterArray[i] )+1 ); //adding itself
               }
            }
            //key site
            EntryIndex e(&site,&oSite);
            //allocate array
            _sendCounts[e] = shared_ptr< Array<int>   > ( new Array<int> (boundaryCount) );
            //fill send array
            Array<int>& sendArray = dynamic_cast< Array<int>& > ( *_sendCounts[e] );
            for( int i = 0; i < boundaryCount; i++ ){
               sendArray[i] = cellCellsCount[i];
            }
        }
        //RECIEVING allocation (filling will be done by MPI Communication)
        const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
        foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
           const StorageSite&  oSite = *mpos.first;
           EntryIndex e(&oSite,&site);
           //mesh interface can be done know
           if (oSite.getGatherProcID() == - 1) {
              *_recvCounts[e] = *_sendCounts[e];
           }
        }
     }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer () inline private
Definition at line 1214 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary, CRMatrix< T_Diag, T_OffDiag, X >::_recvCounts, CRMatrix< T_Diag, T_OffDiag, X >::_recvIndices, CRMatrix< T_Diag, T_OffDiag, X >::_sendCounts, CRMatrix< T_Diag, T_OffDiag, X >::_sendIndices, CRConnectivity::getCount(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), Array< T >::getLength(), CRConnectivity::getLocalToGlobalMap(), CRConnectivity::getRowSite(), and StorageSite::getScatterMapLevel1().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::syncBndryCoeffs().
     {
        //SENDING allocation and filling
        const StorageSite& site     = _conn.getRowSite();
        const Array<int>&   localToGlobal = _conn.getLocalToGlobalMap();
        const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
        foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
            const StorageSite&  oSite = *mpos.first;
            const Array<int>& scatterArray = *mpos.second;
            //loop over surround indices and itself for sizing
            EntryIndex e(&site,&oSite);
            const Array<int>& send_counts = dynamic_cast< const Array<int>& > (*_sendCounts[e]);
            //allocate array
            int sendSize = 0;
            for ( int i = 0; i < send_counts.getLength(); i++ ){
               sendSize += send_counts[i];
            }
            _sendIndices[e] = shared_ptr< Array<int> > ( new Array<int> (sendSize) );
            //fill send array
            Array<int>& sendArray = dynamic_cast< Array<int>&   > ( *_sendIndices[e] );
            int indx = 0;
            for( int i = 0; i < scatterArray.getLength(); i++ ){
               const int cellID = scatterArray[i];
               if ( _isBoundary[cellID] ){
                  sendArray[indx++] = localToGlobal[cellID];
                  for ( int j = 0; j < _conn.getCount(cellID); j++ ){
                     sendArray[indx] = localToGlobal[ _conn(cellID,j) ];
                     indx++;
                  }
               }
            }
        }
        //RECIEVING allocation (filling will be done by MPI Communication)
        const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
        foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
           const StorageSite&  oSite = *mpos.first;
           EntryIndex e(&oSite,&site);
           const Array<int>& recvCounts   =  dynamic_cast< const Array<int>& > (*_recvCounts[e]);
           int recvSize = 0;
           for ( int i = 0; i < recvCounts.getLength(); i++ ){
              recvSize += recvCounts[i];
           }
           //allocate array
           _recvIndices[e] = shared_ptr< Array<int> > ( new Array<int>     (recvSize) );
           //mesh interface can be done know
           if ( oSite.getGatherProcID() == - 1) {
              *_recvIndices[e] = *_sendIndices[e];
           }
        }
     }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer (const XArray & B) inline private
Definition at line 1434 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary, CRMatrix< T_Diag, T_OffDiag, X >::_recvCounts, CRMatrix< T_Diag, T_OffDiag, X >::_recvValuesB, CRMatrix< T_Diag, T_OffDiag, X >::_sendCounts, CRMatrix< T_Diag, T_OffDiag, X >::_sendValuesB, StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), Array< T >::getLength(), CRConnectivity::getRowSite(), and StorageSite::getScatterMapLevel1().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::syncBndryCoeffs().
     {
        //SENDING allocation and filling
        const StorageSite& site     = _conn.getRowSite();
        const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
        foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
            const StorageSite&  oSite = *mpos.first;
            const Array<int>& scatterArray = *mpos.second;
            //loop over surround indices and itself for sizing
            EntryIndex e(&site,&oSite);
            //decide allocation size
            const Array<int>& send_counts = dynamic_cast< const Array<int>& > (*_sendCounts[e]);
            int sendSize = send_counts.getLength();
            //allocate array
            _sendValuesB[e]  = shared_ptr< Array<X> > ( new Array<X> (sendSize) );
            //fill send array
            XArray& bArray = dynamic_cast< Array<X>& > ( *_sendValuesB[e]  );
            int indx = 0;
            for( int i = 0; i < scatterArray.getLength(); i++ ){
               const int ii = scatterArray[i];
               if ( _isBoundary[ii] ){
                  bArray[indx++] = B[ii];
               }
            }
        }
        //RECIEVING allocation (filling will be done by MPI Communication)
        const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
        foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
           const StorageSite&  oSite = *mpos.first;
           EntryIndex e(&oSite,&site);
           //get recvSize
           const Array<int>& recvCounts  =  dynamic_cast< const Array<int>& > (*_recvCounts[e]);
           int recvSize = recvCounts.getLength();
           //allocate array
           _recvValuesB[e] = shared_ptr< Array<X> > ( new Array<X> (recvSize) );
           //mesh interface can be done know
           if ( oSite.getGatherProcID() == - 1) {
              *_recvValuesB[e] = *_sendValuesB[e];
           }
        }
     }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer () inline private
Definition at line 1331 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary, CRMatrix< T_Diag, T_OffDiag, X >::_recvCounts, CRMatrix< T_Diag, T_OffDiag, X >::_recvValuesCRMtrx, CRMatrix< T_Diag, T_OffDiag, X >::_sendCounts, CRMatrix< T_Diag, T_OffDiag, X >::_sendValuesCRMtrx, DiagToOffDiag(), CRMatrix< T_Diag, T_OffDiag, X >::getCoeff(), CRConnectivity::getCount(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), Array< T >::getLength(), CRConnectivity::getRowSite(), and StorageSite::getScatterMapLevel1().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::syncBndryCoeffs().
     {
        //SENDING allocation and filling
        const StorageSite& site     = _conn.getRowSite();
        const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
        foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
            const StorageSite&  oSite = *mpos.first;
            const Array<int>& scatterArray = *mpos.second;
            //loop over surround indices and itself for sizing
            EntryIndex e(&site,&oSite);
            //decide allocation size
            const Array<int>& send_counts = dynamic_cast< const Array<int>& > (*_sendCounts[e]);
            int sendSize = 0;
            for ( int i = 0; i < send_counts.getLength(); i++ ){
               sendSize += send_counts[i];
            }
            //allocate array
            _sendValuesCRMtrx[e]  = shared_ptr< Array<OffDiag> > ( new Array<OffDiag> (sendSize) );
            //fill send array
            Array<OffDiag>& valueArray = dynamic_cast< Array<OffDiag>& > ( *_sendValuesCRMtrx[e]  );
            int indx = 0;
            for( int i = 0; i < scatterArray.getLength(); i++ ){
               const int ii = scatterArray[i];
               if ( _isBoundary[ii] ){
                  valueArray[indx++] = DiagToOffDiag(_diag[ii]);
                  for ( int j = 0; j < _conn.getCount(ii); j++ ){
                     const int jj = _conn(ii,j);
                     valueArray[indx] = getCoeff(ii,jj);
                     indx++;
                  }
               }
            }
        }
        //RECIEVING allocation (filling will be done by MPI Communication)
        const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
        foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
           const StorageSite&  oSite = *mpos.first;
           EntryIndex e(&oSite,&site);
           //get recvSize
           const Array<int>& recvCounts   =  dynamic_cast< const Array<int>& > (*_recvCounts[e]);
           int recvSize = 0;
           for ( int i = 0; i < recvCounts.getLength(); i++ ){
              recvSize += recvCounts[i];
            }
           //allocate array
           _recvValuesCRMtrx[e] = shared_ptr< Array<OffDiag> > ( new Array<OffDiag> (recvSize) );
           //mesh interface can be done know
           if ( oSite.getGatherProcID() == - 1) {
              *_recvValuesCRMtrx[e] = *_sendValuesCRMtrx[e];
           }
        }
     }
template<class T_Diag, class T_OffDiag, class X> CRMatrix< T_Diag, T_OffDiag, X >::DEFINE_TYPENAME ("CRMatrix<"+NumTypeTraits< Diag >::getTypeName()+","+NumTypeTraits< OffDiag >::getTypeName()+","+NumTypeTraits< X >::getTypeName()+">")
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::eliminateBoundaryEquations (IContainer & bB) inline virtual
Reimplemented from Matrix.
Definition at line 1064 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary, CRConnectivity::CELLCELL2, CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), CRConnectivity::getConnType(), StorageSite::getCount(), CRConnectivity::getRowSite(), StorageSite::getSelfCount(), and CRMatrix< T_Diag, T_OffDiag, X >::syncBndryCoeffs().
   {
     XArray& b = dynamic_cast<XArray&>(bB);
     const int nRowsInterior = _conn.getRowSite().getSelfCount();
     const int nRowsExtra = _conn.getRowSite().getCount();
     for(int nr=nRowsInterior; nr<nRowsExtra; nr++)
       if (_isBoundary[nr])
         eliminateRow(nr,b);
      //syncing coefficients from other processors (or other mesh) to eliminate equations
      //const StorageSite& site = _conn.getRowSite();
      //if (b.getLength() == site.getCountLevel1() && site.getCountLevel1() != site.getCount() ){
 #ifdef FVM_PARALLEL
     //skip nprocs == 1
      if ( _conn.getConnType() == CRConnectivity::CELLCELL2 && MPI::COMM_WORLD.Get_size()  > 1 ){
         syncBndryCoeffs(b);
         eliminateRowGhost(b);
      }
 #endif
   }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::eliminateDirichlet (const int j, Array< X > & b, const X & delta_j, const bool explicitMode = false) inline
Definition at line 1041 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_row, and CRMatrix< T_Diag, T_OffDiag, X >::getCoeff().
Referenced by PlateBCS< X, Diag, OffDiag >::applyDirichletBC(), and StructureBCS< X, Diag, OffDiag >::applyDirichletBC().
   {
     for (int nb = _row[j]; nb<_row[j+1]; nb++)
     {
         const int i = _col[nb];
         OffDiag& a_ij = getCoeff(i,j);
         b[i] += a_ij*delta_j;
         if (!explicitMode)
           a_ij = NumTypeTraits<OffDiag>::getZero();
     }
   }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow (const int j, Array< X > & b) inline
Definition at line 899 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, DiagToOffDiag(), CRMatrix< T_Diag, T_OffDiag, X >::getCoeff(), CRConnectivity::getRowSite(), StorageSite::getSelfCount(), and CRMatrix< T_Diag, T_OffDiag, X >::hasCoeff().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::eliminateBoundaryEquations().
   {
     // in case of problems with an immersed boundary, we might call
     // this function also for interior rows that are marked as
     // Dirichlet but in that case we don't need to do anything since
     // the off diagonal entries are all zero
     const int nRowsInterior = _conn.getRowSite().getSelfCount();
     const bool isInterior = (j<nRowsInterior);
     if (isInterior) return;
     const Diag& a_jj = _diag[j];
     // loop over neighbours of j to determine the rows that will change
     for (int nb = _row[j]; nb<_row[j+1]; nb++)
     {
         const int i = _col[nb];
         OffDiag& a_ij = getCoeff(i,j);
         // for the ith row we need to find the indices k for which the
         // entries will change. we do this by again going through
         // neighbors of j
         for (int nb2 = _row[j]; nb2<_row[j+1]; nb2++)
         {
             const int k = _col[nb2];
             const OffDiag& a_jk = _offDiag[nb2];
             if (i!=k)
             {
                 if (hasCoeff(i,k))
                 {
                     OffDiag& a_ik = getCoeff(i,k);
                     a_ik -= DiagToOffDiag(a_ij*(a_jk/a_jj));
                 }
             }
             else
               _diag[i] -= a_ij*(a_jk/a_jj);
         }
         b[i] -= a_ij*(b[j]/a_jj);
         a_ij = NumTypeTraits<OffDiag>::getZero();
     }
   }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost (Array< X > & b) inline
Definition at line 952 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_recvCounts, CRMatrix< T_Diag, T_OffDiag, X >::_recvIndices, CRMatrix< T_Diag, T_OffDiag, X >::_recvValuesB, CRMatrix< T_Diag, T_OffDiag, X >::_recvValuesCRMtrx, CRMatrix< T_Diag, T_OffDiag, X >::getCoeff(), StorageSite::getGatherMapLevel1(), Array< T >::getLength(), CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::eliminateBoundaryEquations().
   {
      const StorageSite& site = _conn.getRowSite();
      const int nRowsInterior = site.getSelfCount();
      const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
      //looping gathermap indices
      foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
         const StorageSite&  oSite = *mpos.first;
         EntryIndex e(&oSite,&site);
         const Array<int>& recv_counts     = dynamic_cast< const Array<int>& > (*_recvCounts [e]);
         const Array<int>& recv_indices    = dynamic_cast< const Array<int>& > (*_recvIndices [e]);
         const Array<OffDiag>& recv_values_crmtrx = dynamic_cast< const Array<OffDiag>& > (*_recvValuesCRMtrx[e]);
         const Array<X>&       recv_values_b = dynamic_cast< const Array<X>& > (*_recvValuesB[e]);
         //row and col
         Array<int> row( recv_counts.getLength()+1);
         row[0] = 0;
         for ( int i = 1; i < recv_counts.getLength()+1; i++ ){
            row[i] = row[i-1] + recv_counts[i-1] - 1;
         }
         Array<int> boundaryPtr( recv_counts.getLength());
         boundaryPtr[0] = 0;
         for ( int i = 1; i < recv_counts.getLength(); i++ ){
            boundaryPtr[i] = boundaryPtr[i-1] + recv_counts[i-1];
         }
         //col and offDiag
         Array<int> col( row[recv_counts.getLength()] );
         Array<OffDiag> offDiag( row[recv_counts.getLength()] );
         int indx = 0;
         int jj = 0;
         for ( int i=0; i<recv_counts.getLength(); i++ ){
            indx++; //skip first
            for ( int j=1; j<recv_counts[i]; j++ ){
                 col[jj]     = recv_indices[indx];
                 offDiag[jj] = recv_values_crmtrx[indx];
                 jj++; indx++;
            }
         }
         //over boundary cells on ghost
         for ( int rc = 0; rc < recv_counts.getLength(); rc++ ){
            const int pIndx = boundaryPtr[rc]; //point where the boundary location in recv_indices or recv_values_crmtrx
            const int j = recv_indices[pIndx];
            const OffDiag& a_jj = recv_values_crmtrx[pIndx];
            // loop over neighbours of j to determine the rows that will change
            for (int nb = row[rc]; nb<row[rc+1]; nb++)
            {
               const int i = col[nb];
               if ( i < nRowsInterior ){
                  OffDiag& a_ij = getCoeff(i,j);
                  // for the ith row we need to find the indices k for which the
                  // entries will change. we do this by again going through
                  // neighbors of j
                  for (int nb2 = row[rc]; nb2<row[rc+1]; nb2++)
                  {
                     const int k =  col[nb2];
                     const OffDiag& a_jk = offDiag[nb2];
                     if (i!=k)
                     {
                        OffDiag& a_ik = getCoeff(i,k);
                        a_ik -= a_ij*(a_jk/a_jj);
                     }
                     else
                        _diag[i] -= a_ij*(a_jk/a_jj);
                  }
                  b[i] -= a_ij*(recv_values_b[rc]/a_jj);
                  a_ij = NumTypeTraits<OffDiag>::getZero();
               }
            }
         }
     }
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::forwardGS (IContainer & xB, IContainer & bB, IContainer &) const inline virtual
forward GaussSeidel update for this * x = b
Reimplemented from Matrix.
Definition at line 303 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
   {
     XArray& x = dynamic_cast<XArray&>(xB);
     const XArray& b = dynamic_cast<const XArray&>(bB);
     const int nRows = _conn.getRowSite().getSelfCount();
     X sum;
     for(int nr=0; nr<nRows; nr++)
     {
         sum = b[nr];
         for (int nb = _row[nr]; nb<_row[nr+1]; nb++)
         {
             const int j = _col[nb];
             sum += _offDiag[nb]*x[j];
         }
         x[nr] = -sum/_diag[nr];
     }
   }
template<class T_Diag, class T_OffDiag, class X> int CRMatrix< T_Diag, T_OffDiag, X >::get_request_size () inline private
Definition at line 1525 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, StorageSite::getGatherProcID(), CRConnectivity::getRowSite(), and StorageSite::getScatterMapLevel1().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::syncCounts(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx().
     {
         int indx =  0;
         const StorageSite& site = _conn.getRowSite();
         const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
         foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
            const StorageSite&  oSite = *mpos.first;
            //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
            if ( oSite.getGatherProcID() != -1 )
               indx++;
         }
         return indx;
     }
template<class T_Diag, class T_OffDiag, class X> OffDiag& CRMatrix< T_Diag, T_OffDiag, X >::getCoeff (const int i, const int j) inline
Definition at line 836 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, and CRMatrix< T_Diag, T_OffDiag, X >::_row.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), LinearizeInterfaceJump< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), LinearizeDielectric< X, Diag, OffDiag >::discretize(), BatteryLinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryLinearizeThermalInterface< X, Diag, OffDiag >::discretize(), LinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryPCLinearizeInterface_BV< X, Diag, OffDiag, otherMeshDiag >::discretize(), BatteryLinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), LinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateDirichlet(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), and BatteryModel< T >::Impl::printMatrixElementsOnFace().
   {
     for (int nnb = _row[i]; nnb<_row[i+1]; nnb++)
     {
         if (_col[nnb] == j)
           return _offDiag[nnb];
     }
     throw CException("invalid indices");
   }
template<class T_Diag, class T_OffDiag, class X> virtual const CRConnectivity& CRMatrix< T_Diag, T_OffDiag, X >::getConnectivity () const inline virtual
Reimplemented from Matrix.
Definition at line 834 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn.
Referenced by IbmDiscretization< X, Diag, OffDiag >::discretize(), FlowModel< T >::Impl::dumpContinuityMatrix(), VacancyModel< T >::Impl::dumpMatrix(), ThermalModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), FlowModel< T >::Impl::setDirichlet(), and CRMatrix< T_Diag, T_OffDiag, X >::setFlatMatrix().
 {return _conn;}
template<class T_Diag, class T_OffDiag, class X> Array<Diag>& CRMatrix< T_Diag, T_OffDiag, X >::getDiag () inline
Definition at line 856 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_diag.
Referenced by Underrelaxer< X, Diag, OffDiag >::discretize(), CollisionTermDiscretization< X, Diag, OffDiag >::discretize(), PhononCollisionDiscretization< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJump< X, Diag, OffDiag >::discretize(), TrapBandTunnelingDiscretization< X, Diag, OffDiag >::discretize(), LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >::discretize(), TimeDerivativeDiscretization< X, Diag, OffDiag >::discretize(), DriftDiscretization< X, Diag, OffDiag >::discretize(), SourceDiscretizationforFracture< T, Diag, OffDiag >::discretize(), BatteryPCTimeDerivativeDiscretization< X, Diag, OffDiag >::discretize(), LinearizeDielectric< X, Diag, OffDiag >::discretize(), PhononConvectionDiscretization< X, Diag, OffDiag >::discretize(), TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), IbmDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization< X, Diag, OffDiag >::discretize(), BatteryLinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryLinearizeThermalInterface< X, Diag, OffDiag >::discretize(), LinearizePotentialInterface< X, Diag, OffDiag >::discretize(), BatteryPCLinearizeInterface_BV< X, Diag, OffDiag, otherMeshDiag >::discretize(), BatteryLinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), TimeDerivativeStructureDiscretization< X, Diag, OffDiag >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), LinearizeSpeciesInterface< X, Diag, OffDiag >::discretize(), TimeDerivativePlateDiscretization< X, Diag, OffDiag >::discretize(), ElecDiffusionDiscretization< X, Diag, OffDiag >::discretize(), CaptureDiscretization< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), EmissionDiscretization< X, Diag, OffDiag >::discretize(), SourceDiscretizationdissi< X, Diag, OffDiag >::discretize(), TunnelingDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize(), WallDiscretization< X, Diag, OffDiag >::discretize(), PlateSourceDiscretization< T, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), FlowModel< T >::Impl::dumpContinuityMatrix(), ThermalModel< T >::Impl::dumpMatrix(), VacancyModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), BatteryModel< T >::Impl::printMatrixElementsOnFace(), FlowModel< T >::Impl::setDirichlet(), CRMatrix< T_Diag, T_OffDiag, X >::setFlatMatrix(), and FlowModel< T >::Impl::solveMomentum().
 {return _diag;}
template<class T_Diag, class T_OffDiag, class X> const Array<Diag>& CRMatrix< T_Diag, T_OffDiag, X >::getDiag () const inline
Definition at line 859 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_diag.
 {return _diag;}
template<class T_Diag, class T_OffDiag, class X> void* CRMatrix< T_Diag, T_OffDiag, X >::getDiagData () const inline virtual
Reimplemented from Matrix.
Definition at line 862 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_diag, and Array< T >::getData().
 { return _diag.getData(); }
template<class T_Diag, class T_OffDiag, class X> int CRMatrix< T_Diag, T_OffDiag, X >::getDiagDataSize () const inline virtual
Reimplemented from Matrix.
Definition at line 864 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_diag, and Array< T >::getDataSize().
 { return _diag.getDataSize(); }
template<class T_Diag, class T_OffDiag, class X> Array<OffDiag>& CRMatrix< T_Diag, T_OffDiag, X >::getOffDiag () inline
Definition at line 857 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_offDiag.
Referenced by IbmDiscretization< X, Diag, OffDiag >::discretize(), FlowModel< T >::Impl::dumpContinuityMatrix(), VacancyModel< T >::Impl::dumpMatrix(), ThermalModel< T >::Impl::dumpMatrix(), PlateModel< T >::Impl::dumpMatrix(), FlowModel< T >::Impl::setDirichlet(), and CRMatrix< T_Diag, T_OffDiag, X >::setFlatMatrix().
 {return _offDiag;}
template<class T_Diag, class T_OffDiag, class X> const Array<OffDiag>& CRMatrix< T_Diag, T_OffDiag, X >::getOffDiag () const inline
Definition at line 860 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_offDiag.
 {return _offDiag;}
template<class T_Diag, class T_OffDiag, class X> void* CRMatrix< T_Diag, T_OffDiag, X >::getOffDiagData () const inline virtual
Reimplemented from Matrix.
Definition at line 863 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, and Array< T >::getData().
 { return _offDiag.getData(); }
template<class T_Diag, class T_OffDiag, class X> int CRMatrix< T_Diag, T_OffDiag, X >::getOffDiagDataSize () const inline virtual
Reimplemented from Matrix.
Definition at line 865 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, and Array< T >::getDataSize().
 { return _offDiag.getDataSize(); }
template<class T_Diag, class T_OffDiag, class X> PairWiseAssembler& CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler (const CRConnectivity & pairs) inline
Definition at line 867 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_pairWiseAssemblers, and CRConnectivity::getPairToColMapping().
Referenced by DriftDiscretization< X, Diag, OffDiag >::discretize(), GenericIBDiscretization< X, Diag, OffDiag >::discretize(), PhononConvectionDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization< X, Diag, OffDiag >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), ConvectionDiscretization_Kmodel< X, Diag, OffDiag >::discretize(), ElecDiffusionDiscretization< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize(), WallDiscretization< X, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), and PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces().
   {
     if (_pairWiseAssemblers.find(&pairs) == _pairWiseAssemblers.end())
     {
         _pairWiseAssemblers[&pairs] =
           new PairWiseAssembler(_offDiag,
                                 _conn.getPairToColMapping(pairs));
     }
     return *_pairWiseAssemblers[&pairs];
   }
template<class T_Diag, class T_OffDiag, class X> bool CRMatrix< T_Diag, T_OffDiag, X >::hasCoeff (const int i, const int j) inline
Definition at line 846 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, and CRMatrix< T_Diag, T_OffDiag, X >::_row.
Referenced by StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), and CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow().
   {
     for (int nnb = _row[i]; nnb<_row[i+1]; nnb++)
     {
         if (_col[nnb] == j)
           return true;
     }
     return false;
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::iluSolve (IContainer & xB, const IContainer & bB, const IContainer &) const inline virtual
Reimplemented from Matrix.
Definition at line 376 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_iluConnPtr, CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), CRMatrix< T_Diag, T_OffDiag, X >::lowerSolve(), Array< T >::newClone(), and CRMatrix< T_Diag, T_OffDiag, X >::upperSolve().
   {
     XArray& x = dynamic_cast<XArray&>(xB);
     shared_ptr<XArray> y = dynamic_pointer_cast<XArray>(x.newClone());
     const XArray& b = dynamic_cast<const XArray&>(bB);
     if (!_iluConnPtr)
       compute_ILU0();
     lowerSolve(*y,b);
     upperSolve(x,*y);
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::initAssembly () inline virtual
Implements Matrix.
Definition at line 188 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, and Array< T >::zero().
   {
     _diag.zero();
     _offDiag.zero();
     _isBoundary = false;
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::Jacobi (IContainer & xnewB, const IContainer & xoldB, const IContainer & bB) const inline virtual
Jacobi update for this * x = b
Reimplemented from Matrix.
Definition at line 353 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
   {
     XArray& xnew = dynamic_cast<XArray&>(xnewB);
     const XArray& xold = dynamic_cast<const XArray&>(xoldB);
     const XArray& b = dynamic_cast<const XArray&>(bB);
     const int nRows = _conn.getRowSite().getSelfCount();
     X sum;
     for(int nr=0; nr<nRows; nr++)
     {
         sum = b[nr];
         for (int nb = _row[nr]; nb<_row[nr+1]; nb++)
         {
             const int j = _col[nb];
             sum += _offDiag[nb]*xold[j];
         }
         xnew[nr] = -sum/_diag[nr];
     }
   }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::lowerSolve (XArray & y, const XArray & b) const inline private
Definition at line 1676 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_iluCoeffsPtr, CRMatrix< T_Diag, T_OffDiag, X >::_iluConnPtr, CRMatrix< T_Diag, T_OffDiag, X >::_iluDiagIndexPtr, CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::iluSolve().
   {
     const IntArray& iluRow = _iluConnPtr->getRow();
     const IntArray& iluCol = _iluConnPtr->getCol();
     const IntArray& iluDiagIndex = *_iluDiagIndexPtr;
     const DiagArray& iluCoeffs = *_iluCoeffsPtr;
     const int nRows = _conn.getRowSite().getSelfCount();
     for (int j = 0; j < nRows; j++)
     {
         X yj = -b[j];
         for ( int k = iluRow[j]; k < iluDiagIndex[j]; k++ )
         {
             yj -= iluCoeffs[k] * y[ iluCol[k] ];
         }
         y[j] = yj;
     }
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::multiply (IContainer & yB, const IContainer & xB) const inline virtual
y = this * x
Reimplemented from Matrix.
Definition at line 200 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, StorageSite::getCount(), and CRConnectivity::getRowSite().
   {
     XArray& y = dynamic_cast<XArray&>(yB);
     const XArray& x = dynamic_cast<const XArray&>(xB);
     const int nRows = _conn.getRowSite().getCount();
     for(int nr=0; nr<nRows; nr++)
     {
         y[nr] = _diag[nr]*x[nr];
         for (int nb = _row[nr]; nb<_row[nr+1]; nb++)
         {
             const int j = _col[nb];
             y[nr] += _offDiag[nb]*x[j];
         }
     }
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::multiplyAndAdd (IContainer & yB, const IContainer & xB) const inline virtual
y += this * x
Reimplemented from Matrix.
Definition at line 223 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, StorageSite::getCount(), and CRConnectivity::getRowSite().
   {
     XArray& y = dynamic_cast<XArray&>(yB);
     const XArray& x = dynamic_cast<const XArray&>(xB);
     const int nRows = _conn.getRowSite().getCount();
     for(int nr=0; nr<nRows; nr++)
     {
         y[nr] += _diag[nr]*x[nr];
         for (int nb = _row[nr]; nb<_row[nr+1]; nb++)
         {
             const int j = _col[nb];
             y[nr] += _offDiag[nb]*x[j];
         }
     }
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::printRow (const int i) const inline virtual
Reimplemented from Matrix.
Definition at line 1028 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, and CRMatrix< T_Diag, T_OffDiag, X >::_row.
   {
     cout << "coeff (" <<  i << "," << i << ") = " << _diag[i] << endl;
     for (int nb = _row[i]; nb<_row[i+1]; nb++)
     {
         const int j = _col[nb];
         cout << "coeff (" <<  i << "," << j << ") = " << _offDiag[nb] << endl;
     }
   }
template<class T_Diag, class T_OffDiag, class X> virtual shared_ptr<ArrayBase> CRMatrix< T_Diag, T_OffDiag, X >::quadProduct (const IContainer & xB) const inline virtual
compute x^T * this * x; return as a new Array of length 1
Reimplemented from Matrix.
Definition at line 274 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
   {
     X sum( NumTypeTraits<X>::getZero());
     const XArray& x = dynamic_cast<const XArray&>(xB);
     const int nRows = _conn.getRowSite().getSelfCount();
     for(int nr=0; nr<nRows; nr++)
     {
         X sum_n = _diag[nr]*x[nr];
         for (int nb = _row[nr]; nb<_row[nr+1]; nb++)
         {
             const int j = _col[nb];
             sum_n += _offDiag[nb]*x[j];
         }
         sum += sum_n*x[nr];
     }
     XArray  *p = new XArray(1);
     (*p)[0] = sum;
     return shared_ptr<ArrayBase>(p);
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::reverseGS (IContainer & xB, IContainer & bB, IContainer &) const inline virtual
reverse GaussSeidel update for this * x = b
Reimplemented from Matrix.
Definition at line 328 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
   {
     XArray& x = dynamic_cast<XArray&>(xB);
     const XArray& b = dynamic_cast<const XArray&>(bB);
     const int nRows = _conn.getRowSite().getSelfCount();
     X sum;
     for(int nr=nRows-1; nr>=0; nr--)
     {
         sum = b[nr];
         for (int nb = _row[nr]; nb<_row[nr+1]; nb++)
         {
             const int j = _col[nb];
             sum += _offDiag[nb]*x[j];
         }
         x[nr] = -sum/_diag[nr];
     }
   }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::setBoundary (const int nr) inline
Definition at line 1056 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary.
Referenced by PlateBCS< X, Diag, OffDiag >::applyCantileverBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyConvectionBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyDielectricInterfaceBC(), BaseGenericPhononBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericKineticBCS< X, Diag, OffDiag >::applyExtrapolationBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyExtrapolationBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyMixedBC(), StructureBCS< X, Diag, OffDiag >::applyNeumannBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyNeumannBC(), PlateBCS< X, Diag, OffDiag >::applyNeumannBC(), BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applyRadiationBC(), BatteryPC_BCS< X, Diag, OffDiag >::applySingleEquationNeumannBC(), GenericBCS< X, Diag, OffDiag >::applySymmetryBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applySymmetryBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::applySymmetryBC(), GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::applySymmetryBC(), StructureBCS< X, Diag, OffDiag >::applyZeroDerivativeBC(), and PlateBCS< X, Diag, OffDiag >::applyZeroDerivativeBC().
   {
     _isBoundary[nr] = true;
   }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::setDirichlet (const int nr) inline
Definition at line 887 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, and CRMatrix< T_Diag, T_OffDiag, X >::_row.
Referenced by StructureModel< T >::Impl::applyBC(), StructureBCS< X, Diag, OffDiag >::applyDirichletBC(), StructureBCS< X, Diag, OffDiag >::applySymmetryBC(), PlateBCS< X, Diag, OffDiag >::applySymmetryBC(), GenericIBDiscretization< X, Diag, OffDiag >::discretize(), GenericKineticIBDiscretization< X, Diag, OffDiag >::discretize(), PlateModel< T >::Impl::linearizeDeformation(), and KeModel< T >::Impl::linearizedissipation().
   {
     for (int nb = _row[nr]; nb<_row[nr+1]; nb++)
       _offDiag[nb] = NumTypeTraits<OffDiag>::getZero();
     _diag[nr] = NumTypeTraits<Diag>::getNegativeUnity();
     _isBoundary[nr] = true;
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::setFlatMatrix (Matrix & fmg) const inline virtual
Reimplemented from Matrix.
Definition at line 1087 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::getConnectivity(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), CRMatrix< T_Diag, T_OffDiag, X >::getOffDiag(), and setFlatCoeffs().
   {
     CRMatrix<double,double,double>& fm = dynamic_cast<CRMatrix<double,double,double>& >(fmg);
     setFlatCoeffs(fm.getOffDiag(), fm.getConnectivity(),
                   getDiag(), getOffDiag(), getConnectivity());
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::solveBoundary (IContainer & xB, IContainer & bB, IContainer &) const inline virtual
solve rows marked as boundary
Reimplemented from Matrix.
Definition at line 433 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, StorageSite::getCount(), CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
   {
     XArray& x = dynamic_cast<XArray&>(xB);
     const XArray& b = dynamic_cast<const XArray&>(bB);
     const int nRowsInterior = _conn.getRowSite().getSelfCount();
     const int nRowsExtra = _conn.getRowSite().getCount();
     X sum;
     for(int nr=nRowsInterior; nr<nRowsExtra; nr++)
       if (_isBoundary[nr])
       {
           sum = b[nr];
           for (int nb = _row[nr]; nb<_row[nr+1]; nb++)
           {
               const int j = _col[nb];
               sum += _offDiag[nb]*x[j];
           }
           x[nr] = -sum/_diag[nr];
       }
   }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::spikeSolve (IContainer & xB, const IContainer & bB, const IContainer & , const SpikeStorage & spike_storage) const inline virtual
Reimplemented from Matrix.
Definition at line 389 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_diag, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, and CRMatrix< T_Diag, T_OffDiag, X >::_spikeMtrx.
   {
     if (!_spikeMtrx)
        _spikeMtrx = shared_ptr<T_SpikeMtrx>(new T_SpikeMtrx(_conn, _diag, _offDiag, spike_storage));
     XArray& x = dynamic_cast<XArray&>(xB);
     shared_ptr<XArray> y = dynamic_pointer_cast<XArray>(x.newClone());
     const XArray& b = dynamic_cast<const XArray&>(bB);
     _spikeMtrx->solve( b, x);
   }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::syncBndryCoeffs (const Array< X > & b) inline private
Definition at line 1096 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::syncCounts(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::eliminateBoundaryEquations().
     {
        //create recvCounts buffer
        createScatterGatherCountsBuffer();
        //syn counts
        syncCounts();
        //create recvindices buffer
        createScatterGatherIndicesBuffer();
        //sync indices
        syncIndices();
        //create crmtrx buffer
        createScatterGatherValuesCRMtrxBuffer();
        //sync values crmtrx
        syncValuesCRMtrx();
        //create b buffer
        createScatterGatherValuesBBuffer(b);
        //sync values b
        syncValuesB();
     }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::syncCounts () inline private
Definition at line 1158 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_recvCounts, CRMatrix< T_Diag, T_OffDiag, X >::_sendCounts, CRMatrix< T_Diag, T_OffDiag, X >::get_request_size(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), CRConnectivity::getRowSite(), StorageSite::getScatterMapLevel1(), and StorageSite::getTag().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::syncBndryCoeffs().
     {
 #ifdef FVM_PARALLEL
        //SENDING
        const int  request_size = get_request_size();
        MPI::Request   request_send[ request_size ];
        MPI::Request   request_recv[ request_size ];
        int indxSend = 0;
        int indxRecv = 0;
        const StorageSite&    site      = _conn.getRowSite();
        const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
        foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
            const StorageSite&  oSite = *mpos.first;
            EntryIndex e(&site,&oSite);
            //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
            ArrayBase& sendArray = *_sendCounts[e];
            //loop over surround indices and itself
            int to_where  = oSite.getGatherProcID();
           //many interior partiton is not going to have any boundary in cellCell2 so no need to send the data
            if ( to_where != -1 ){
               int mpi_tag = oSite.getTag();
               request_send[indxSend++] =
                    MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
            }
        }
        //RECIEVING
        //getting values from other meshes to fill g
        const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
        foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
           const StorageSite&  oSite = *mpos.first;
           //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
           EntryIndex e(&oSite,&site);
           int from_where       = oSite.getGatherProcID();
           if ( from_where != -1 ){
              int mpi_tag = oSite.getTag();
              MPI::Status recv_status;
              while ( !(recv_status.Get_source() == from_where && recv_status.Get_tag() == mpi_tag) ){
                 if ( MPI::COMM_WORLD.Iprobe(from_where, mpi_tag, recv_status) ){
                    const int recv_count = recv_status.Get_count( MPI::INT );
                    _recvCounts[e] = shared_ptr< Array<int> > ( new Array<int> (recv_count) );
                    ArrayBase& recvArray = *_recvCounts[e];
                    request_recv[indxRecv++] =
                                             MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
                 }
              }
           }
        }
        int count  = get_request_size();
        MPI::Request::Waitall( count, request_recv );
        MPI::Request::Waitall( count, request_send );
 #endif
     }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::syncIndices () inline private
Definition at line 1267 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_recvIndices, CRMatrix< T_Diag, T_OffDiag, X >::_sendIndices, CRMatrix< T_Diag, T_OffDiag, X >::get_request_size(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), Array< T >::getLength(), CRConnectivity::getRowSite(), StorageSite::getScatterMapLevel1(), and StorageSite::getTag().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::syncBndryCoeffs().
     {
 #ifdef FVM_PARALLEL
        //SENDING
        const int  request_size = get_request_size();
        MPI::Request   request_send[ request_size ];
        MPI::Request   request_recv[ request_size ];
        int indxSend = 0;
        int indxRecv = 0;
        const StorageSite&    site      = _conn.getRowSite();
        const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
        foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
            const StorageSite&  oSite = *mpos.first;
            EntryIndex e(&site,&oSite);
            //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
            ArrayBase& sendArray = *_sendIndices[e];
            //loop over surround indices and itself
            int to_where  = oSite.getGatherProcID();
            if ( to_where != -1 ){
               int mpi_tag = oSite.getTag();
               request_send[indxSend++] =
                    MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
            }
        }
        //RECIEVING
        //getting values from other meshes to fill g
        const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
        foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
           const StorageSite&  oSite = *mpos.first;
           EntryIndex e(&oSite,&site);
           ArrayBase& recvArray = *_recvIndices[e];
           int from_where       = oSite.getGatherProcID();
           if ( from_where != -1 ){
              int mpi_tag = oSite.getTag();
              request_recv[indxRecv++] =
                     MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
           }
        }
        int count  = get_request_size();
        MPI::Request::Waitall( count, request_recv );
        MPI::Request::Waitall( count, request_send );
 #endif
 #ifndef FVM_PARALLEL
        const StorageSite&    site      = _conn.getRowSite();
        const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
 #endif
        //globaltolocal
        const map<int,int>&   globalToLocal = _conn. getGlobalToLocalMapper();
        foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
           const StorageSite&  oSite = *mpos.first;
           EntryIndex e(&oSite,&site);
           Array<int>& recv_indices = dynamic_cast< Array<int>&   > (*_recvIndices[e]);
           for( int i=0; i < recv_indices.getLength(); i++ ){
               const int localID = globalToLocal.find( recv_indices[i] )->second;
                  recv_indices[i] = localID;
           }
        }
     }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB () inline private
Definition at line 1478 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_recvValuesB, CRMatrix< T_Diag, T_OffDiag, X >::_sendValuesB, CRMatrix< T_Diag, T_OffDiag, X >::get_request_size(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), CRConnectivity::getRowSite(), StorageSite::getScatterMapLevel1(), and StorageSite::getTag().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::syncBndryCoeffs().
     {
        #ifdef FVM_PARALLEL
           //SENDING
           const int  request_size = get_request_size();
           MPI::Request   request_send[ request_size ];
           MPI::Request   request_recv[ request_size ];
           int indxSend = 0;
           int indxRecv = 0;
           const StorageSite&    site      = _conn.getRowSite();
           const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
           foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
              const StorageSite&  oSite = *mpos.first;
              EntryIndex e(&site,&oSite);
              //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              ArrayBase& sendArray = *_sendValuesB[e];
              //loop over surround indices and itself
              int to_where  = oSite.getGatherProcID();
              if ( to_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_send[indxSend++] =
                     MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
              }
           }
           //RECIEVING
           //getting values from other meshes to fill g
           const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
           foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
              const StorageSite&  oSite = *mpos.first;
              //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              EntryIndex e(&oSite,&site);
              ArrayBase& recvArray = *_recvValuesB[e];
              int from_where       = oSite.getGatherProcID();
              if ( from_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_recv[indxRecv++] =
                       MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
              }
           }
           int count  = get_request_size();
           MPI::Request::Waitall( count, request_recv );
           MPI::Request::Waitall( count, request_send );
 #endif
     }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx () inline private
Definition at line 1386 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_recvValuesCRMtrx, CRMatrix< T_Diag, T_OffDiag, X >::_sendValuesCRMtrx, CRMatrix< T_Diag, T_OffDiag, X >::get_request_size(), ArrayBase::getData(), ArrayBase::getDataSize(), StorageSite::getGatherMapLevel1(), StorageSite::getGatherProcID(), CRConnectivity::getRowSite(), StorageSite::getScatterMapLevel1(), and StorageSite::getTag().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::syncBndryCoeffs().
     {
        #ifdef FVM_PARALLEL
           //SENDING
           const int  request_size = get_request_size();
           MPI::Request   request_send[ request_size ];
           MPI::Request   request_recv[ request_size ];
           int indxSend = 0;
           int indxRecv = 0;
           const StorageSite&    site      = _conn.getRowSite();
           const StorageSite::ScatterMap& scatterMap = site.getScatterMapLevel1();
           foreach(const StorageSite::ScatterMap::value_type& mpos, scatterMap){
              const StorageSite&  oSite = *mpos.first;
              EntryIndex e(&site,&oSite);
              //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              ArrayBase& sendArray = *_sendValuesCRMtrx[e];
              //loop over surround indices and itself
              int to_where  = oSite.getGatherProcID();
              if ( to_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_send[indxSend++] =
                     MPI::COMM_WORLD.Isend( sendArray.getData(), sendArray.getDataSize(), MPI::BYTE, to_where, mpi_tag );
              }
           }
           //RECIEVING
           //getting values from other meshes to fill g
           const StorageSite::GatherMap& gatherMap = site.getGatherMapLevel1();
           foreach(const StorageSite::GatherMap::value_type& mpos, gatherMap){
              const StorageSite&  oSite = *mpos.first;
              //checking if storage site is only site or ghost site, we only communicate ghost site ( oSite.getCount() == -1 )
              EntryIndex e(&oSite,&site);
              ArrayBase& recvArray = *_recvValuesCRMtrx[e];
              int from_where       = oSite.getGatherProcID();
              if ( from_where != -1 ){
                 int mpi_tag = oSite.getTag();
                 request_recv[indxRecv++] =
                       MPI::COMM_WORLD.Irecv( recvArray.getData(), recvArray.getDataSize(), MPI::BYTE, from_where, mpi_tag );
              }
           }
           int count  = get_request_size();
           MPI::Request::Waitall( count, request_recv );
           MPI::Request::Waitall( count, request_send );
 #endif
     }
template<class T_Diag, class T_OffDiag, class X> virtual void CRMatrix< T_Diag, T_OffDiag, X >::transpose () inline virtual
Reimplemented from Matrix.
Definition at line 241 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_col, CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_offDiag, CRMatrix< T_Diag, T_OffDiag, X >::_row, StorageSite::getCount(), and CRConnectivity::getRowSite().
   {
     const int nRows = _conn.getRowSite().getCount();
     for(int i=0; i<nRows; i++)
     {
         for (int nb = _row[i]; nb<_row[i+1]; nb++)
         {
             const int j = _col[nb];
             bool found = false;
             for (int nb2 = _row[j]; nb2<_row[j+1]; nb2++)
             {
                 if (_col[nb2] == i)
                 {
                     const OffDiag coeffIJ = _offDiag[nb];
                     _offDiag[nb] = _offDiag[nb2];
                     _offDiag[nb2] = coeffIJ;
                     found = true;
                 }
             }
             if (!found)
               throw CException("invalid connectivity for transpose");
         }
     }
   }
template<class T_Diag, class T_OffDiag, class X> void CRMatrix< T_Diag, T_OffDiag, X >::upperSolve (XArray & x, const XArray & y) const inline private
Definition at line 1697 of file CRMatrix.h.
References CRMatrix< T_Diag, T_OffDiag, X >::_conn, CRMatrix< T_Diag, T_OffDiag, X >::_iluCoeffsPtr, CRMatrix< T_Diag, T_OffDiag, X >::_iluConnPtr, CRMatrix< T_Diag, T_OffDiag, X >::_iluDiagIndexPtr, CRConnectivity::getRowSite(), and StorageSite::getSelfCount().
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::iluSolve().
   {
     const IntArray& iluRow = _iluConnPtr->getRow();
     const IntArray& iluCol = _iluConnPtr->getCol();
     const IntArray& iluDiagIndex = *_iluDiagIndexPtr;
     const DiagArray& iluCoeffs = *_iluCoeffsPtr;
     const int nRows = _conn.getRowSite().getSelfCount();
     for ( int j = nRows-1; j >= 0; j-- )
     {
         X xj = y[j];
         for ( int k =  iluDiagIndex[j]+1; k <iluRow[j+1]; k++ )
         {
             xj -= iluCoeffs[k] * x[ iluCol[k] ];
         }
         x[j] = iluCoeffs[ iluDiagIndex[j] ]*xj;
     }
   }
Member Data Documentation
template<class T_Diag, class T_OffDiag, class X> const Array<int>& CRMatrix< T_Diag, T_OffDiag, X >::_col private
Definition at line 1720 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), CRMatrix< T_Diag, T_OffDiag, X >::computeResidual(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseConnectivity(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateDirichlet(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow(), CRMatrix< T_Diag, T_OffDiag, X >::forwardGS(), CRMatrix< T_Diag, T_OffDiag, X >::getCoeff(), CRMatrix< T_Diag, T_OffDiag, X >::hasCoeff(), CRMatrix< T_Diag, T_OffDiag, X >::Jacobi(), CRMatrix< T_Diag, T_OffDiag, X >::multiply(), CRMatrix< T_Diag, T_OffDiag, X >::multiplyAndAdd(), CRMatrix< T_Diag, T_OffDiag, X >::printRow(), CRMatrix< T_Diag, T_OffDiag, X >::quadProduct(), CRMatrix< T_Diag, T_OffDiag, X >::reverseGS(), CRMatrix< T_Diag, T_OffDiag, X >::solveBoundary(), and CRMatrix< T_Diag, T_OffDiag, X >::transpose().
template<class T_Diag, class T_OffDiag, class X> const CRConnectivity& CRMatrix< T_Diag, T_OffDiag, X >::_conn private
Definition at line 1718 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), CRMatrix< T_Diag, T_OffDiag, X >::computeResidual(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateBoundaryEquations(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), CRMatrix< T_Diag, T_OffDiag, X >::forwardGS(), CRMatrix< T_Diag, T_OffDiag, X >::get_request_size(), CRMatrix< T_Diag, T_OffDiag, X >::getConnectivity(), CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), CRMatrix< T_Diag, T_OffDiag, X >::Jacobi(), CRMatrix< T_Diag, T_OffDiag, X >::lowerSolve(), CRMatrix< T_Diag, T_OffDiag, X >::multiply(), CRMatrix< T_Diag, T_OffDiag, X >::multiplyAndAdd(), CRMatrix< T_Diag, T_OffDiag, X >::quadProduct(), CRMatrix< T_Diag, T_OffDiag, X >::reverseGS(), CRMatrix< T_Diag, T_OffDiag, X >::solveBoundary(), CRMatrix< T_Diag, T_OffDiag, X >::spikeSolve(), CRMatrix< T_Diag, T_OffDiag, X >::syncCounts(), CRMatrix< T_Diag, T_OffDiag, X >::syncIndices(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB(), CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx(), CRMatrix< T_Diag, T_OffDiag, X >::transpose(), and CRMatrix< T_Diag, T_OffDiag, X >::upperSolve().
template<class T_Diag, class T_OffDiag, class X> Array<Diag> CRMatrix< T_Diag, T_OffDiag, X >::_diag private
Definition at line 1721 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), CRMatrix< T_Diag, T_OffDiag, X >::computeResidual(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), CRMatrix< T_Diag, T_OffDiag, X >::forwardGS(), CRMatrix< T_Diag, T_OffDiag, X >::getDiag(), CRMatrix< T_Diag, T_OffDiag, X >::getDiagData(), CRMatrix< T_Diag, T_OffDiag, X >::getDiagDataSize(), CRMatrix< T_Diag, T_OffDiag, X >::initAssembly(), CRMatrix< T_Diag, T_OffDiag, X >::Jacobi(), CRMatrix< T_Diag, T_OffDiag, X >::multiply(), CRMatrix< T_Diag, T_OffDiag, X >::multiplyAndAdd(), CRMatrix< T_Diag, T_OffDiag, X >::printRow(), CRMatrix< T_Diag, T_OffDiag, X >::quadProduct(), CRMatrix< T_Diag, T_OffDiag, X >::reverseGS(), CRMatrix< T_Diag, T_OffDiag, X >::setDirichlet(), CRMatrix< T_Diag, T_OffDiag, X >::solveBoundary(), and CRMatrix< T_Diag, T_OffDiag, X >::spikeSolve().
template<class T_Diag, class T_OffDiag, class X> map<int,int> CRMatrix< T_Diag, T_OffDiag, X >::_ghostCellBoundayMap private
Definition at line 1748 of file CRMatrix.h.
template<class T_Diag, class T_OffDiag, class X> DiagArrayPtr CRMatrix< T_Diag, T_OffDiag, X >::_iluCoeffsPtr mutable private
Definition at line 1736 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), CRMatrix< T_Diag, T_OffDiag, X >::lowerSolve(), and CRMatrix< T_Diag, T_OffDiag, X >::upperSolve().
template<class T_Diag, class T_OffDiag, class X> shared_ptr<CRConnectivity> CRMatrix< T_Diag, T_OffDiag, X >::_iluConnPtr mutable private
Definition at line 1731 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), CRMatrix< T_Diag, T_OffDiag, X >::iluSolve(), CRMatrix< T_Diag, T_OffDiag, X >::lowerSolve(), and CRMatrix< T_Diag, T_OffDiag, X >::upperSolve().
template<class T_Diag, class T_OffDiag, class X> IntArrayPtr CRMatrix< T_Diag, T_OffDiag, X >::_iluDiagIndexPtr mutable private
Definition at line 1733 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), CRMatrix< T_Diag, T_OffDiag, X >::lowerSolve(), and CRMatrix< T_Diag, T_OffDiag, X >::upperSolve().
template<class T_Diag, class T_OffDiag, class X> Array<bool> CRMatrix< T_Diag, T_OffDiag, X >::_isBoundary private
Definition at line 1724 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::CRMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateBoundaryEquations(), CRMatrix< T_Diag, T_OffDiag, X >::initAssembly(), CRMatrix< T_Diag, T_OffDiag, X >::setBoundary(), CRMatrix< T_Diag, T_OffDiag, X >::setDirichlet(), and CRMatrix< T_Diag, T_OffDiag, X >::solveBoundary().
template<class T_Diag, class T_OffDiag, class X> Array<OffDiag> CRMatrix< T_Diag, T_OffDiag, X >::_offDiag private
Definition at line 1722 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), CRMatrix< T_Diag, T_OffDiag, X >::computeResidual(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow(), CRMatrix< T_Diag, T_OffDiag, X >::forwardGS(), CRMatrix< T_Diag, T_OffDiag, X >::getCoeff(), CRMatrix< T_Diag, T_OffDiag, X >::getOffDiag(), CRMatrix< T_Diag, T_OffDiag, X >::getOffDiagData(), CRMatrix< T_Diag, T_OffDiag, X >::getOffDiagDataSize(), CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), CRMatrix< T_Diag, T_OffDiag, X >::initAssembly(), CRMatrix< T_Diag, T_OffDiag, X >::Jacobi(), CRMatrix< T_Diag, T_OffDiag, X >::multiply(), CRMatrix< T_Diag, T_OffDiag, X >::multiplyAndAdd(), CRMatrix< T_Diag, T_OffDiag, X >::printRow(), CRMatrix< T_Diag, T_OffDiag, X >::quadProduct(), CRMatrix< T_Diag, T_OffDiag, X >::reverseGS(), CRMatrix< T_Diag, T_OffDiag, X >::setDirichlet(), CRMatrix< T_Diag, T_OffDiag, X >::solveBoundary(), CRMatrix< T_Diag, T_OffDiag, X >::spikeSolve(), and CRMatrix< T_Diag, T_OffDiag, X >::transpose().
template<class T_Diag, class T_OffDiag, class X> PairWiseAssemblerMap CRMatrix< T_Diag, T_OffDiag, X >::_pairWiseAssemblers private
Definition at line 1723 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::getPairWiseAssembler(), and CRMatrix< T_Diag, T_OffDiag, X >::~CRMatrix().
template<class T_Diag, class T_OffDiag, class X> GhostArrayMap CRMatrix< T_Diag, T_OffDiag, X >::_recvCounts private
Definition at line 1741 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), and CRMatrix< T_Diag, T_OffDiag, X >::syncCounts().
template<class T_Diag, class T_OffDiag, class X> GhostArrayMap CRMatrix< T_Diag, T_OffDiag, X >::_recvIndices private
Definition at line 1743 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), and CRMatrix< T_Diag, T_OffDiag, X >::syncIndices().
template<class T_Diag, class T_OffDiag, class X> GhostArrayMap CRMatrix< T_Diag, T_OffDiag, X >::_recvValuesB private
Definition at line 1747 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB().
template<class T_Diag, class T_OffDiag, class X> GhostArrayMap CRMatrix< T_Diag, T_OffDiag, X >::_recvValuesCRMtrx private
Definition at line 1745 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRowGhost(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx().
template<class T_Diag, class T_OffDiag, class X> const Array<int>& CRMatrix< T_Diag, T_OffDiag, X >::_row private
Definition at line 1719 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::compute_ILU0(), CRMatrix< T_Diag, T_OffDiag, X >::computeResidual(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseConnectivity(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarseMatrix(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarsening(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateDirichlet(), CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow(), CRMatrix< T_Diag, T_OffDiag, X >::forwardGS(), CRMatrix< T_Diag, T_OffDiag, X >::getCoeff(), CRMatrix< T_Diag, T_OffDiag, X >::hasCoeff(), CRMatrix< T_Diag, T_OffDiag, X >::Jacobi(), CRMatrix< T_Diag, T_OffDiag, X >::multiply(), CRMatrix< T_Diag, T_OffDiag, X >::multiplyAndAdd(), CRMatrix< T_Diag, T_OffDiag, X >::printRow(), CRMatrix< T_Diag, T_OffDiag, X >::quadProduct(), CRMatrix< T_Diag, T_OffDiag, X >::reverseGS(), CRMatrix< T_Diag, T_OffDiag, X >::setDirichlet(), CRMatrix< T_Diag, T_OffDiag, X >::solveBoundary(), and CRMatrix< T_Diag, T_OffDiag, X >::transpose().
template<class T_Diag, class T_OffDiag, class X> GhostArrayMap CRMatrix< T_Diag, T_OffDiag, X >::_sendCounts private
Definition at line 1740 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherCountsBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), and CRMatrix< T_Diag, T_OffDiag, X >::syncCounts().
template<class T_Diag, class T_OffDiag, class X> GhostArrayMap CRMatrix< T_Diag, T_OffDiag, X >::_sendIndices private
Definition at line 1742 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherIndicesBuffer(), and CRMatrix< T_Diag, T_OffDiag, X >::syncIndices().
template<class T_Diag, class T_OffDiag, class X> GhostArrayMap CRMatrix< T_Diag, T_OffDiag, X >::_sendValuesB private
Definition at line 1746 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesBBuffer(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesB().
template<class T_Diag, class T_OffDiag, class X> GhostArrayMap CRMatrix< T_Diag, T_OffDiag, X >::_sendValuesCRMtrx private
Definition at line 1744 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), and CRMatrix< T_Diag, T_OffDiag, X >::syncValuesCRMtrx().
template<class T_Diag, class T_OffDiag, class X> shared_ptr<T_SpikeMtrx> CRMatrix< T_Diag, T_OffDiag, X >::_spikeMtrx mutable private
Definition at line 1738 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::spikeSolve().
The documentation for this class was generated from the following file:
CRMatrix.h