Memosa-FVM: COMETDiscretizer< T > Class Template Reference
COMETDiscretizer< T > Class Template Reference
#include <COMETDiscretizer.h>
Public Types
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef Kspace< T > Tkspace
typedef kvol< T > Tkvol
typedef pmode< T > Tmode
typedef Vector< T_Scalar, 3 > VectorT3
typedef Array< VectorT3 > VectorT3Array
typedef Array< T_Scalar > TArray
typedef MatrixJML< T > TMatrix
typedef ArrowHeadMatrix< T > TArrow
typedef SquareMatrix< T > TSquare
typedef map< int, COMETBC< T > * > COMETBCMap
typedef COMETModelOptions< T > COpts
typedef Array< int > IntArray
typedef Array< bool > BoolArray
typedef Vector< int, 2 > VecInt2
typedef map< int, VecInt2 > FaceToFg
typedef Tmode::Refl_pair Refl_pair
typedef SquareTensor< T, 3 > T3Tensor
typedef KSConnectivity< T > TKConnectivity
typedef TKConnectivity * TKCptr
typedef vector< TKCptr > TKClist
typedef map< int, TKClist > FgTKClistMap
typedef Gradient< T > GradType
typedef Array< GradType > GradArray
typedef GradientModel< T > GradModelType
typedef
GradModelType::GradMatrixType GradMatrix
Public Member Functions
COMETDiscretizer (const Mesh &mesh, const GeomFields &geomfields, PhononMacro &macro, Tkspace &kspace, COMETBCMap &bcMap, const IntArray &BCArray, const IntArray &BCfArray, COpts &options, const FgTKClistMap &FgToKsc)
void COMETSolveFine (const int dir, const int level)
void COMETSolveCoarse (const int dir, const int level)
void COMETSolveFull (const int dir, const int level)
void COMETConvectionFine (const int cell0, TArrow &Amat, TArray &BVec, const GradMatrix &gMat)
void COMETConvectionCoarse (const int cell0, TArrow &Amat, TArray &BVec)
void COMETConvection (const int cell, TSquare &Amat, TArray &BVec)
void COMETCollision (const int cell, TMatrix *Amat, TArray &BVec)
void COMETEquilibrium (const int cell, TMatrix *Amat, TArray &BVec)
void COMETSource (const int cell, TArray &BVec)
void COMETFullScatt (const int cell, TArray &s, TArray &BVec)
void ScatterPhonons (const int cell0)
void COMETShifted (const int cell, TMatrix *Amat, TArray &BVec)
void Distribute (const int cell, TArray &BVec, TArray &Rvec)
void findResidFine ()
void findResidCoarse (const bool plusFAS)
void findResidFull ()
TArray gatherResid (const int c)
T getResidChange ()
T getAveResid ()
void setfgFinder ()
int findFgId (const int faceIndex)
void ArrayAbs (TArray &o)
void makeValueArray (const int c, TArray &o)
void addFAS (const int c, TArray &bVec)
void updatee0 ()
void updatee0 (const int c)
void updateGhostFine (const int cell, const GradMatrix &gMat)
void updateGhostCoarse (const int cell)
void correctInterface (const int cell0, TArray &Bvec)
void updateeShifted ()
void outerProduct (const VectorT3 &v1, const VectorT3 &v2, T3Tensor &out)
T scaledResid (const TArray &de, const int c)
Private Attributes
const Mesh & _mesh
const GeomFields & _geomFields
const StorageSite & _cells
const StorageSite & _faces
const CRConnectivity & _cellFaces
const CRConnectivity & _faceCells
const TArray & _faceAreaMag
const VectorT3Array & _faceArea
const TArray & _cellVolume
const VectorT3Array & _cellCoords
PhononMacro & _macro
Tkspace & _kspace
COMETBCMap & _bcMap
const IntArray & _BCArray
const IntArray & _BCfArray
T _aveResid
T _residChange
FaceToFg _fgFinder
COpts _options
const FgTKClistMap & _FaceToKSC
TArray & _eArray
TArray & _e0Array
TArray & _resArray
Detailed Description
template<class T>
class COMETDiscretizer< T >
Definition at line 31 of file COMETDiscretizer.h.
Member Typedef Documentation
template<class T> typedef Array<bool> COMETDiscretizer< T >::BoolArray
Definition at line 48 of file COMETDiscretizer.h.
template<class T> typedef map<int,COMETBC<T>*> COMETDiscretizer< T >::COMETBCMap
Definition at line 45 of file COMETDiscretizer.h.
template<class T> typedef COMETModelOptions<T> COMETDiscretizer< T >::COpts
Definition at line 46 of file COMETDiscretizer.h.
template<class T> typedef map<int,VecInt2> COMETDiscretizer< T >::FaceToFg
Definition at line 50 of file COMETDiscretizer.h.
template<class T> typedef map<int, TKClist> COMETDiscretizer< T >::FgTKClistMap
Definition at line 56 of file COMETDiscretizer.h.
template<class T> typedef Array<GradType> COMETDiscretizer< T >::GradArray
Definition at line 58 of file COMETDiscretizer.h.
template<class T> typedef GradModelType::GradMatrixType COMETDiscretizer< T >::GradMatrix
Definition at line 60 of file COMETDiscretizer.h.
template<class T> typedef GradientModel<T> COMETDiscretizer< T >::GradModelType
Definition at line 59 of file COMETDiscretizer.h.
template<class T> typedef Gradient<T> COMETDiscretizer< T >::GradType
Definition at line 57 of file COMETDiscretizer.h.
template<class T> typedef Array<int> COMETDiscretizer< T >::IntArray
Definition at line 47 of file COMETDiscretizer.h.
template<class T> typedef Tmode::Refl_pair COMETDiscretizer< T >::Refl_pair
Definition at line 51 of file COMETDiscretizer.h.
template<class T> typedef SquareTensor<T,3> COMETDiscretizer< T >::T3Tensor
Definition at line 52 of file COMETDiscretizer.h.
template<class T> typedef NumTypeTraits<T>::T_Scalar COMETDiscretizer< T >::T_Scalar
Definition at line 35 of file COMETDiscretizer.h.
template<class T> typedef Array<T_Scalar> COMETDiscretizer< T >::TArray
Definition at line 41 of file COMETDiscretizer.h.
template<class T> typedef ArrowHeadMatrix<T> COMETDiscretizer< T >::TArrow
Definition at line 43 of file COMETDiscretizer.h.
template<class T> typedef vector<TKCptr> COMETDiscretizer< T >::TKClist
Definition at line 55 of file COMETDiscretizer.h.
template<class T> typedef KSConnectivity<T> COMETDiscretizer< T >::TKConnectivity
Definition at line 53 of file COMETDiscretizer.h.
template<class T> typedef TKConnectivity* COMETDiscretizer< T >::TKCptr
Definition at line 54 of file COMETDiscretizer.h.
template<class T> typedef Kspace<T> COMETDiscretizer< T >::Tkspace
Definition at line 36 of file COMETDiscretizer.h.
template<class T> typedef kvol<T> COMETDiscretizer< T >::Tkvol
Definition at line 37 of file COMETDiscretizer.h.
template<class T> typedef MatrixJML<T> COMETDiscretizer< T >::TMatrix
Definition at line 42 of file COMETDiscretizer.h.
template<class T> typedef pmode<T> COMETDiscretizer< T >::Tmode
Definition at line 38 of file COMETDiscretizer.h.
template<class T> typedef SquareMatrix<T> COMETDiscretizer< T >::TSquare
Definition at line 44 of file COMETDiscretizer.h.
template<class T> typedef Vector<int,2> COMETDiscretizer< T >::VecInt2
Definition at line 49 of file COMETDiscretizer.h.
template<class T> typedef Vector<T_Scalar,3> COMETDiscretizer< T >::VectorT3
Definition at line 39 of file COMETDiscretizer.h.
template<class T> typedef Array<VectorT3> COMETDiscretizer< T >::VectorT3Array
Definition at line 40 of file COMETDiscretizer.h.
Constructor & Destructor Documentation
template<class T> COMETDiscretizer< T >::COMETDiscretizer (const Mesh & mesh, const GeomFields & geomfields, PhononMacro & macro, Tkspace & kspace, COMETBCMap & bcMap, const IntArray & BCArray, const IntArray & BCfArray, COpts & options, const FgTKClistMap & FgToKsc) inline
Definition at line 62 of file COMETDiscretizer.h.
                                               :
   _mesh(mesh),
     _geomFields(geomfields),
     _cells(mesh.getCells()),
     _faces(mesh.getFaces()),
     _cellFaces(mesh.getCellFaces()),
     _faceCells(mesh.getAllFaceCells()),
     _faceAreaMag((dynamic_cast<const TArray&>(_geomFields.areaMag[_faces]))),
     _faceArea(dynamic_cast<const VectorT3Array&>(_geomFields.area[_faces])),
     _cellVolume(dynamic_cast<const TArray&>(_geomFields.volume[_cells])),
     _cellCoords(dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[_cells])),
     _macro(macro),
     _kspace(kspace),
     _bcMap(bcMap),
     _BCArray(BCArray),
     _BCfArray(BCfArray),
     _aveResid(-1.),
     _residChange(-1.),
     _fgFinder(),
     _options(options),
     _FaceToKSC(FgToKsc),
     _eArray(kspace.geteArray()),
     _e0Array(kspace.gete0Array()),
     _resArray(kspace.getResArray())
     {}
Member Function Documentation
template<class T> void COMETDiscretizer< T >::addFAS (const int c, TArray & bVec) inline
Definition at line 1604 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, Kspace< T >::addFAS(), Kspace< T >::gettotmodes(), and PhononMacro::TlFASCorrection.
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), and COMETDiscretizer< T >::findResidCoarse().
   {
     const int totmodes=_kspace.gettotmodes();
     _kspace.addFAS(c,bVec);
     TArray& fasArray=dynamic_cast<TArray&>(_macro.TlFASCorrection[_cells]);
     bVec[totmodes]-=fasArray[c];
   }
template<class T> void COMETDiscretizer< T >::ArrayAbs (TArray & o) inline
Definition at line 1576 of file COMETDiscretizer.h.
References fabs(), and Array< T >::getLength().
Referenced by COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
   {
     int length=o.getLength();
     for(int i=0;i<length;i++)
       o[i]=fabs(o[i]);
   }
template<class T> void COMETDiscretizer< T >::COMETCollision (const int cell, TMatrix * Amat, TArray & BVec) inline
Definition at line 996 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_cellVolume, COMETDiscretizer< T >::_e0Array, COMETDiscretizer< T >::_eArray, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, pmode< T >::calcde0dT(), MatrixJML< T >::getElement(), Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::getTau(), Kspace< T >::gettotmodes(), and PhononMacro::temperature.
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
   {
     const int klen=_kspace.getlength();
     const int totalmodes=_kspace.gettotmodes();
     const int order=totalmodes+1;
     TArray& Tlold=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     T coeff;
     int cellIndex=_kspace.getGlobalIndex(cell,0);
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             const int count=mode.getIndex();
             const T tau=_kspace.getTau(cellIndex);
             T de0dT=mode.calcde0dT(Tlold[cell]);
             coeff=_cellVolume[cell]/tau;
             Amat->getElement(count,order)-=coeff*de0dT;
             Amat->getElement(count,count)+=coeff;
             BVec[count-1]-=coeff*_eArray[cellIndex];
             BVec[count-1]+=coeff*_e0Array[cellIndex];
             cellIndex++;
           }
       }
   }
template<class T> void COMETDiscretizer< T >::COMETConvection (const int cell, TSquare & Amat, TArray & BVec) inline
Definition at line 867 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_BCfArray, COMETDiscretizer< T >::_bcMap, COMETDiscretizer< T >::_cellFaces, COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_faceArea, COMETDiscretizer< T >::_faceCells, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::findFgId(), CRConnectivity::getCount(), kvol< T >::getdk3(), pmode< T >::getfield(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getReflpair(), and pmode< T >::getv().
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
   {
     const int neibcount=_cellFaces.getCount(cell);
     for(int j=0;j<neibcount;j++)
       {
         const int f=_cellFaces(cell,j);
         int cell2=_faceCells(f,1);
         const int klen=_kspace.getlength();
         VectorT3 Af=_faceArea[f];
         T flux;
         if(cell2==cell)
           {
             Af=Af*(-1.);
             cell2=_faceCells(f,0);
           }
         if(_BCfArray[f]==2) //If the face in question is an implicit reflecting face
           {
             int Fgid=findFgId(f);
             T refl=(*(_bcMap[Fgid]))["specifiedReflection"];
             T oneMinusRefl=1.-refl;
             //first sweep - have to make sumVdotA
             T sumVdotA=0.;
             for(int k=0;k<klen;k++)
               {
                 Tkvol& kvol=_kspace.getkvol(k);
                 T dk3=kvol.getdk3();
                 const int numModes=kvol.getmodenum();
                 for(int m=0;m<numModes;m++)
                   {
                     Tmode& mode=kvol.getmode(m);
                     const int count=mode.getIndex();
                     VectorT3 vg=mode.getv();
                     Field& efield=mode.getfield();
                     TArray& eArray=dynamic_cast<TArray&>(efield[_cells]);
                     flux=vg[0]*Af[0]+vg[1]*Af[1]+vg[2]*Af[2];
                     if(flux>T_Scalar(0))
                       {
                         Amat(count,count)-=flux;
                         BVec[count-1]-=flux*eArray[cell];
                       }
                     else
                       {
                         sumVdotA-=flux*dk3;
                         Refl_pair& rpairs=mode.getReflpair(Fgid);
                         const int kk=rpairs.second.second;
                         Tkvol& kkvol=_kspace.getkvol(kk);
                         const int ccount=kkvol.getmode(m).getIndex();
                         Field& eefield=kkvol.getmode(m).getfield();
                         TArray& eeArray=dynamic_cast<TArray&>(eefield[_cells]);
                         Amat(count,ccount)-=flux*refl;
                         BVec[count-1]-=eeArray[cell]*refl*flux;
                       }
                   }
               }
             T inverseSumVdotA=1./sumVdotA;
             //Second sweep
             for(int k=0;k<klen;k++)
               {
                 Tkvol& kvol=_kspace.getkvol(k);
                 const int numModes=kvol.getmodenum();
                 for(int m=0;m<numModes;m++)
                   {
                     const int count=kvol.getmode(m).getIndex();
                     VectorT3 vg=kvol.getmode(m).getv();
                     flux=vg[0]*Af[0]+vg[1]*Af[1]+vg[2]*Af[2];
                     if(flux<T_Scalar(0))
                       {
                         for(int kk=0;kk<klen;kk++)
{
                             Tkvol& kkvol=_kspace.getkvol(kk);
                             const int numMODES=kkvol.getmodenum();
                             T ddk3=kkvol.getdk3();
                             for(int mm=0;mm<numMODES;mm++)
{
                                 VectorT3 vvg=kkvol.getmode(mm).getv();
                                 T VdotA=vvg[0]*Af[0]+vvg[1]*Af[1]+vvg[2]*Af[2];
                                 if(VdotA>T_Scalar(0))
{
                                     const int ccount=kkvol.getmode(mm).getIndex();
                                     Field& eefield=kkvol.getmode(mm).getfield();
                                     TArray& eeArray=dynamic_cast<TArray&>(eefield[_cells]);
                                     Amat(count,ccount)-=flux*VdotA*ddk3*oneMinusRefl*inverseSumVdotA;
                                     BVec[count-1]-=flux*VdotA*ddk3
                                       *eeArray[cell]*inverseSumVdotA*oneMinusRefl;
                                   }
                               }
                           }
                       }
                   }
               }
           }
         else  //if the face in question is not implicit
           {
             for(int k=0;k<klen;k++)
               {
                 Tkvol& kvol=_kspace.getkvol(k);
                 const int numModes=kvol.getmodenum();
                 for(int m=0;m<numModes;m++)
                   {
                     Tmode& mode=kvol.getmode(m);
                     const int count=mode.getIndex();
                     VectorT3 vg=mode.getv();
                     Field& efield=mode.getfield();
                     TArray& eArray=dynamic_cast<TArray&>(efield[_cells]);
                     flux=vg[0]*Af[0]+vg[1]*Af[1]+vg[2]*Af[2];
                     if(flux>T_Scalar(0))
                       {
                         Amat(count,count)-=flux;
                         BVec[count-1]-=flux*eArray[cell];
                       }
                     else
                       BVec[count-1]-=flux*eArray[cell2];
                   }
               }
           }
       }
   }
template<class T> void COMETDiscretizer< T >::COMETConvectionCoarse (const int cell0, TArrow & Amat, TArray & BVec) inline
Definition at line 819 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cellFaces, COMETDiscretizer< T >::_eArray, COMETDiscretizer< T >::_faceArea, COMETDiscretizer< T >::_faceCells, COMETDiscretizer< T >::_kspace, CRConnectivity::getCount(), ArrowHeadMatrix< X, K >::getElement(), Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), and pmode< T >::getv().
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::findResidCoarse(), and COMETDiscretizer< T >::findResidFull().
   {
     /* This is the COMET discretization for cells that do not
        do not have a face which is a reflecting boundary.  When
        there is a face with a reflecting boundary, we can no longer
        use an arrowhead matrix as the structure becomes unknown a priori.
     */
     const int neibcount=_cellFaces.getCount(cell0);
     for(int j=0;j<neibcount;j++)
       {
         const int f=_cellFaces(cell0,j);
         int cell1=_faceCells(f,1);
         VectorT3 Af=_faceArea[f];
         if(cell1==cell0)
           {
             cell1=_faceCells(f,0);
             Af*=-1.;
           }
         const int klen=_kspace.getlength();
         T flux;
         for(int k=0;k<klen;k++)
           {
             Tkvol& kvol=_kspace.getkvol(k);
             const int numModes=kvol.getmodenum();
             for(int m=0;m<numModes;m++)
               {
                 Tmode& mode=kvol.getmode(m);
                 const int count=mode.getIndex();
                 const VectorT3 vg=mode.getv();
                 flux=vg[0]*Af[0]+vg[1]*Af[1]+vg[2]*Af[2];
                 if(flux>T_Scalar(0))
                   {
                     Amat.getElement(count,count)+=flux;
                     BVec[count-1]-=flux*_eArray[_kspace.getGlobalIndex(cell0,count-1)];
                   }
                 else
                   BVec[count-1]-=flux*_eArray[_kspace.getGlobalIndex(cell1,count-1)];
               }
           }
       }
   }
template<class T> void COMETDiscretizer< T >::COMETConvectionFine (const int cell0, TArrow & Amat, TArray & BVec, const GradMatrix & gMat) inline
Definition at line 579 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_BCfArray, COMETDiscretizer< T >::_cellCoords, COMETDiscretizer< T >::_cellFaces, COMETDiscretizer< T >::_eArray, COMETDiscretizer< T >::_faceArea, COMETDiscretizer< T >::_faceCells, COMETDiscretizer< T >::_faces, COMETDiscretizer< T >::_geomFields, COMETDiscretizer< T >::_kspace, computeLimitCoeff2(), GeomFields::coordinate, GradientMatrix< T_Scalar >::getCoeff(), CRConnectivity::getCount(), ArrowHeadMatrix< X, K >::getElement(), Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::gettotmodes(), pmode< T >::getv(), and Array< T >::zero().
Referenced by COMETDiscretizer< T >::COMETSolveFine(), and COMETDiscretizer< T >::findResidFine().
   {
     const int neibcount=_cellFaces.getCount(cell0);
     GradArray Grads(_kspace.gettotmodes());
     TArray pointMin(_kspace.gettotmodes());
     pointMin=-1;
     TArray pointMax(_kspace.gettotmodes());
     pointMax.zero();
     TArray neibMin(_kspace.gettotmodes());
     neibMin=-1;
     TArray neibMax(_kspace.gettotmodes());
     neibMax.zero();
     TArray pointLim(_kspace.gettotmodes());
     pointLim=100.;
     TArray neibLim(_kspace.gettotmodes());
     neibLim=100.;
     for(int k=0;k<_kspace.gettotmodes();k++)
       Grads[k].zero();
     const VectorT3Array& faceCoords=
       dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[_faces]);
     for(int j=0;j<neibcount;j++)    //first loop to get grad and max/min vals
       {
         const int f=_cellFaces(cell0,j);
         int cell1=_faceCells(f,1);
         if(cell1==cell0)
           cell1=_faceCells(f,0);
         const VectorT3 Gcoeff=gMat.getCoeff(cell0, cell1);
         int c0ind=_kspace.getGlobalIndex(cell0,0);
         int c1ind=_kspace.getGlobalIndex(cell1,0);
         for(int k=0;k<_kspace.gettotmodes();k++)
           {
             const T e1=_eArray[c1ind];
             const T e0=_eArray[c0ind];
             T& curMax=pointMax[k];
             T& curMin=pointMin[k];
             Grads[k].accumulate(Gcoeff, e1-e0);
             if(e1>curMax)
               curMax=e1;
             if(curMin==-1)
               curMin=e1;
             else
               {
                 if(e1<curMin)
                   curMin=e1;
               }
             c0ind++;
             c1ind++;
           }
       }
     for(int j=0;j<neibcount;j++)    //second loop to calculate limiting coeff
       {
         const int f=_cellFaces(cell0,j);
         int cell1=_faceCells(f,1);
         if(cell1==cell0)
           cell1=_faceCells(f,0);
         const VectorT3 dr0(faceCoords[f]-_cellCoords[cell0]);
         int c0ind=_kspace.getGlobalIndex(cell0,0);
         vanLeer lf;
         for(int k=0;k<_kspace.gettotmodes();k++)
           {
             const T minVal=pointMin[k];
             const T maxVal=pointMax[k];
             const T de0(Grads[k]*dr0);
             T& cl=pointLim[k];
             computeLimitCoeff2(cl, _eArray[c0ind], de0, minVal, maxVal, lf);
             c0ind++;
           }
       }
     for(int j=0;j<neibcount;j++)  //loop to construct point matrix
       {
         const int f=_cellFaces(cell0,j);
         int cell1=_faceCells(f,1);
         VectorT3 Af=_faceArea[f];
         if(cell1==cell0)
           {
             cell1=_faceCells(f,0);
             Af*=-1.;
           }
         if(_BCfArray[f]==0)   //interior face
           {
             const int klen=_kspace.getlength();
             GradArray NeibGrads(_kspace.gettotmodes());
             for(int k=0;k<_kspace.gettotmodes();k++)
               NeibGrads[k].zero();
             neibMax.zero();
             neibMin=-1.;
             const int neibcount1=_cellFaces.getCount(cell1);
             for(int nj=0;nj<neibcount1;nj++)  //loop to make gradients and min/max
               {
                 const int f1=_cellFaces(cell1,nj);
                 int cell11=_faceCells(f1,1);
                 if(cell1==cell11)
                   cell11=_faceCells(f1,0);
                 const VectorT3 Gcoeff=gMat.getCoeff(cell1, cell11);
                 int c1ind=_kspace.getGlobalIndex(cell1,0);
                 int c11ind=_kspace.getGlobalIndex(cell11,0);
                 for(int k=0;k<_kspace.gettotmodes();k++)
                   {
                     const T e1=_eArray[c1ind];
                     const T e11=_eArray[c11ind];
                     T& curMax=neibMax[k];
                     T& curMin=neibMin[k];
                     NeibGrads[k].accumulate(Gcoeff,e11-e1);
                     if(e11>curMax)
                       curMax=e11;
                     if(curMin==-1)
                       curMin=e11;
                     else
                       {
                         if(e11<curMin)
                           curMin=e11;
                       }
                     c11ind++;
                     c1ind++;
                   }
               }
             neibLim=100.;
             for(int nj=0;nj<neibcount1;nj++)  //second loop to calculate limiting coeff
               {
                 const int f1=_cellFaces(cell1,nj);
                 int cell11=_faceCells(f1,1);
                 if(cell1==cell11)
                   cell11=_faceCells(f1,0);
                 const VectorT3 dr1(faceCoords[f1]-_cellCoords[cell1]);
                 int c1ind=_kspace.getGlobalIndex(cell1,0);
                 vanLeer lf;
                 for(int k=0;k<_kspace.gettotmodes();k++)
                   {
                     const T minVal=neibMin[k];
                     const T maxVal=neibMax[k];
                     const T de1(NeibGrads[k]*dr1);
                     T& cl=neibLim[k];
                     computeLimitCoeff2(cl, _eArray[c1ind], de1, minVal, maxVal, lf);
                     if(_BCfArray[f]!=0)
                       NeibGrads[k].zero();
                     c1ind++;
                   }
               }
             T flux;
             for(int k=0;k<klen;k++)
               {
                 Tkvol& kvol=_kspace.getkvol(k);
                 const int numModes=kvol.getmodenum();
                 for(int m=0;m<numModes;m++)
                   {
                     Tmode& mode=kvol.getmode(m);
                     const int count=mode.getIndex();
                     VectorT3 vg=mode.getv();
                     //T tau=mode.gettau();
                     flux=vg[0]*Af[0]+vg[1]*Af[1]+vg[2]*Af[2];
                     const int c0ind=_kspace.getGlobalIndex(cell0,count-1);
                     const int c1ind=_kspace.getGlobalIndex(cell1,count-1);
                     const GradType& grad=Grads[count-1];
                     const GradType& neibGrad=NeibGrads[count-1];
                     //vanLeer vl;
                     if(flux>T_Scalar(0))
                       {
                         const VectorT3 rVec=_cellCoords[cell1]-_cellCoords[cell0];
                         const VectorT3 fVec=faceCoords[f]-_cellCoords[cell0];
                         //const T r=gMat.computeR(grad,_eArray,rVec,c0ind,c1ind);
                         T SOU=(fVec[0]*grad[0]+fVec[1]*grad[1]+
                                fVec[2]*grad[2])*pointLim[count-1];
                         Amat.getElement(count,count)-=flux;
                         BVec[count-1]-=flux*_eArray[c0ind]-flux*SOU;
                       }
                     else
                       {
                         const VectorT3 rVec=_cellCoords[cell0]-_cellCoords[cell1];
                         const VectorT3 fVec=faceCoords[f]-_cellCoords[cell1];
                         //const T r=gMat.computeR(grad,_eArray,rVec,c1ind,c0ind);
                         T SOU=(fVec[0]*neibGrad[0]+fVec[1]*neibGrad[1]+
                                fVec[2]*neibGrad[2])*neibLim[count-1];
                         BVec[count-1]-=flux*_eArray[c1ind]-flux*SOU;
                       }
                   }
               }
           }
         else
           {
             const int klen=_kspace.getlength();
             T flux(0);
             for(int k=0;k<klen;k++)
               {
                 Tkvol& kvol=_kspace.getkvol(k);
                 const int numModes=kvol.getmodenum();
                 for(int m=0;m<numModes;m++)
                   {
                     Tmode& mode=kvol.getmode(m);
                     const int count=mode.getIndex();
                     const VectorT3 vg=mode.getv();
                     flux=vg[0]*Af[0]+vg[1]*Af[1]+vg[2]*Af[2];
                     if(flux>T_Scalar(0))
                       Amat.getElement(count,count)-=flux;
                     BVec[count-1]-=flux*_eArray[_kspace.getGlobalIndex(cell1,count-1)];
                   }
               }
           }
       }
   }
template<class T> void COMETDiscretizer< T >::COMETEquilibrium (const int cell, TMatrix * Amat, TArray & BVec) inline
Definition at line 1026 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_e0Array, COMETDiscretizer< T >::_eArray, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, Kspace< T >::getde0taudT(), kvol< T >::getdk3(), Kspace< T >::getDK3(), MatrixJML< T >::getElement(), Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::getTau(), Kspace< T >::gettotmodes(), and PhononMacro::temperature.
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
   {
     const int klen=_kspace.getlength();
     const int totalmodes=_kspace.gettotmodes();
     const int order=totalmodes+1;
     TArray& Tlold=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     const T tauTot=_kspace.getde0taudT(cell,Tlold[cell]);
     T coeff;
     const T DK3=_kspace.getDK3();
     int cellIndex=_kspace.getGlobalIndex(cell,0);
     const T hbar=6.582119e-16;  // (eV s)
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         const T dk3=kvol.getdk3();
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             const int count=mode.getIndex();
             const T tau=_kspace.getTau(cellIndex);
             //const T energy=mode.getomega()*hbar;
             coeff=(dk3/DK3)/tau;
             Amat->getElement(order,count)-=coeff;
             BVec[totalmodes]+=coeff*_eArray[cellIndex];
             BVec[totalmodes]-=coeff*_e0Array[cellIndex];
             cellIndex++;
           }
       }
     Amat->getElement(order,order)=tauTot;
   }
template<class T> void COMETDiscretizer< T >::COMETFullScatt (const int cell, TArray & s, TArray & BVec) inline
Definition at line 1062 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cellVolume, COMETDiscretizer< T >::_kspace, Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::getTau(), and Kspace< T >::gettotmodes().
Referenced by COMETDiscretizer< T >::findResidFull().
   {
     const int klen=_kspace.getlength();
     const int totalmodes=_kspace.gettotmodes();
     //const int order=totalmodes+1;
     //TArray& Tlold=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     //const T DK3=_kspace.getDK3();
     int cellIndex=_kspace.getGlobalIndex(cell,0);
     TArray ds(totalmodes);
     //_kspace.getSourceTerm(cell,s,ds);
     const T relFac(1);
     //const T impl(1e0);
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         //const T dk3=kvol.getdk3();
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             const T tau=_kspace.getTau(cellIndex);
             const int count=mode.getIndex();
             //const T coeff=_cellVolume[cell]/tau;
             BVec[count-1]+=(s[count-1])*_cellVolume[cell];
             //-(_e0Array[cellIndex]-_eArray[cellIndex])/tau)*_cellVolume[cell];
             BVec[count-1]*=relFac;
             cellIndex++;
           }
       }
   }
template<class T> void COMETDiscretizer< T >::COMETShifted (const int cell, TMatrix * Amat, TArray & BVec) inline
Definition at line 1153 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_cellVolume, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, Kspace< T >::getde0taudT(), MatrixJML< T >::getElement(), pmode< T >::geteShifted(), pmode< T >::getfield(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::gettauN(), Kspace< T >::gettotmodes(), and PhononMacro::temperature.
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), and COMETDiscretizer< T >::COMETSolveFull().
   { //adds to collision and equilibrium
     const int klen=_kspace.getlength();
     const int totalmodes=_kspace.gettotmodes();
     const int order=totalmodes+1;
     TArray& Tlold=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     const T tauTot=_kspace.getde0taudT(cell,Tlold[cell]);
     T coeff;
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             const int count=mode.getIndex();
             T tau=mode.gettauN();
             Field& efield=mode.getfield();
             Field& eShiftedfield=mode.geteShifted();
             TArray& eArray=dynamic_cast<TArray&>(efield[_cells]);
             TArray& eShifted=dynamic_cast<TArray&>(eShiftedfield[_cells]);
             coeff=_cellVolume[cell]/tau;
             Amat->getElement(count,count)-=coeff;
             Amat->getElement(order,count)+=coeff/tauTot;
             BVec[count-1]-=coeff*eArray[cell];
             BVec[count-1]+=coeff*eShifted[cell];
             BVec[totalmodes]+=coeff*eArray[cell]/tauTot;
             BVec[totalmodes]-=coeff*eShifted[cell]/tauTot;
           }
       }
   }
template<class T> void COMETDiscretizer< T >::COMETSolveCoarse (const int dir, const int level) inline
Definition at line 244 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_BCArray, COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_FaceToKSC, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, COMETDiscretizer< T >::_options, COMETDiscretizer< T >::addFAS(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETShifted(), COMETDiscretizer< T >::COMETSource(), COMETDiscretizer< T >::correctInterface(), COMETDiscretizer< T >::Distribute(), fabs(), StorageSite::getSelfCount(), Kspace< T >::gettotmodes(), COMETModelOptions< T >::maxNewton, COMETModelOptions< T >::minNewton, COMETModelOptions< T >::NewtonTol, COMETDiscretizer< T >::scaledResid(), SquareMatrix< T, N >::Solve(), ArrowHeadMatrix< X, K >::Solve(), PhononMacro::temperature, COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateGhostCoarse(), COMETModelOptions< T >::withNormal, SquareMatrix< T, N >::zero(), ArrowHeadMatrix< X, K >::zero(), and Array< T >::zero().
Referenced by COMETModel< T >::smooth().
   {
     const int cellcount=_cells.getSelfCount();
     int start;
     if(dir==1)
       start=0;
     if(dir==-1)
       start=cellcount-1;
     const int totalmodes=_kspace.gettotmodes();
     TArray Bvec(totalmodes+1);
     TArray Resid(totalmodes+1);
     TArrow AMat(totalmodes+1);
     const T newTol=_options.NewtonTol;
     const int maxNew=_options.maxNewton;
     const int minNew=_options.minNewton;
     TArray& Tl=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     for(int c=start;((c<cellcount)&&(c>-1));c+=dir)
       {
         if(_BCArray[c]==0)  //no reflections at all--interior cell or temperature boundary
           {
             T dt=1;
             T rscaled=10;
             int NewtonIters=0;
             while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
               {
                 Bvec.zero();
                 Resid.zero();
                 AMat.zero();
                 COMETConvectionCoarse(c,AMat,Bvec);
                 COMETCollision(c,&AMat,Bvec);
                 COMETEquilibrium(c,&AMat,Bvec);
                 COMETSource(c,Bvec);
                 if(_options.withNormal)
                   COMETShifted(c,&AMat,Bvec);
                 if(level>0)
                   addFAS(c,Bvec);
                 Resid=Bvec;
                 AMat.Solve(Bvec);
                 rscaled=scaledResid(Bvec,c);
                 Distribute(c,Bvec,Resid);
                 updatee0(c);
                 if(!_FaceToKSC.empty())
                   correctInterface(c,Bvec);
                 NewtonIters++;
                 dt=0.5*fabs(Bvec[totalmodes]/Tl[c])+rscaled*0.5;
               }
           }
         else if(_BCArray[c]==1) //Implicit reflecting boundary only
           {
             T dt=1;
             int NewtonIters=0;
             while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
               {
                 TSquare AMatS(totalmodes+1);
                 Bvec.zero();
                 Resid.zero();
                 AMatS.zero();
                 COMETConvection(c,AMatS,Bvec);
                 COMETCollision(c,&AMatS,Bvec);
                 COMETEquilibrium(c,&AMatS,Bvec);
                 if(level>0)
                   addFAS(c,Bvec);
                 Resid=Bvec;
                 AMatS.Solve(Bvec);
                 Distribute(c,Bvec,Resid);
                 updatee0(c);
                 NewtonIters++;
                 dt=fabs(Bvec[totalmodes]);
               }
           }
         else if(_BCArray[c]==2)  //Explicit boundary only
           {
             T dt=1;
             T rscaled=10;
             int NewtonIters=0;
             updateGhostCoarse(c);
             while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
               {
                 Bvec.zero();
                 Resid.zero();
                 AMat.zero();
                 COMETConvectionCoarse(c,AMat,Bvec);
                 COMETCollision(c,&AMat,Bvec);
                 COMETEquilibrium(c,&AMat,Bvec);
                 COMETSource(c,Bvec);
                 if(_options.withNormal)
                   COMETShifted(c,&AMat,Bvec);
                 if(level>0)
                   addFAS(c,Bvec);
                 Resid=Bvec;
                 AMat.Solve(Bvec);
                 rscaled=scaledResid(Bvec,c);
                 Distribute(c,Bvec,Resid);
                 dt=0.5*fabs(Bvec[totalmodes]/Tl[c])+0.5*rscaled;
                 updatee0(c);
                 updateGhostCoarse(c);
                 if(!_FaceToKSC.empty())
                   correctInterface(c,Bvec);
                 NewtonIters++;
               }
           }
         else if(_BCArray[c]==3) //Mix Implicit/Explicit reflecting boundary
           {
             T dt=1;
             int NewtonIters=0;
             updateGhostCoarse(c);
             while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
               {
                 TSquare AMatS(totalmodes+1);
                 Bvec.zero();
                 Resid.zero();
                 AMatS.zero();
                 COMETConvection(c,AMatS,Bvec);
                 COMETCollision(c,&AMatS,Bvec);
                 COMETEquilibrium(c,&AMatS,Bvec);
                 if(level>0)
                   addFAS(c,Bvec);
                 Resid=Bvec;
                 AMatS.Solve(Bvec);
                 Distribute(c,Bvec,Resid);
                 updatee0(c);
                 updateGhostCoarse(c);
                 NewtonIters++;
                 dt=fabs(Bvec[totalmodes]);
               }
           }
         else
           throw CException("Unexpected value for boundary cell map.");
       }
   }
template<class T> void COMETDiscretizer< T >::COMETSolveFine (const int dir, const int level) inline
Definition at line 91 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_BCArray, COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_FaceToKSC, COMETDiscretizer< T >::_geomFields, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_mesh, COMETDiscretizer< T >::_options, COMETDiscretizer< T >::addFAS(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETShifted(), COMETDiscretizer< T >::correctInterface(), COMETDiscretizer< T >::Distribute(), fabs(), GradientModel< T >::getGradientMatrix(), StorageSite::getSelfCount(), Kspace< T >::gettotmodes(), COMETModelOptions< T >::maxNewton, COMETModelOptions< T >::minNewton, COMETModelOptions< T >::NewtonTol, SquareMatrix< T, N >::Solve(), ArrowHeadMatrix< X, K >::Solve(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateGhostFine(), COMETModelOptions< T >::withNormal, SquareMatrix< T, N >::zero(), ArrowHeadMatrix< X, K >::zero(), and Array< T >::zero().
Referenced by COMETModel< T >::smooth().
   {
     const int cellcount=_cells.getSelfCount();
     int start;
     if(dir==1)
       start=0;
     if(dir==-1)
       start=cellcount-1;
     const int totalmodes=_kspace.gettotmodes();
     TArray Bvec(totalmodes+1);
     TArray Resid(totalmodes+1);
     TArrow AMat(totalmodes+1);
     const T newTol=_options.NewtonTol;
     const int maxNew=_options.maxNewton;
     const int minNew=_options.minNewton;
     const GradMatrix& gradMatrix=GradModelType::getGradientMatrix(_mesh,_geomFields);
     for(int c=start;((c<cellcount)&&(c>-1));c+=dir)
       {
         if(_BCArray[c]==0)  //no reflections at all--interior cell or temperature boundary
           {
             T dt=1;
             int NewtonIters=0;
             while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
               {
                 Bvec.zero();
                 Resid.zero();
                 AMat.zero();
                 updateGhostFine(c, gradMatrix);
                 COMETConvectionFine(c,AMat,Bvec,gradMatrix);
                 COMETCollision(c,&AMat,Bvec);
                 COMETEquilibrium(c,&AMat,Bvec);
                 if(_options.withNormal)
                   COMETShifted(c,&AMat,Bvec);
                 if(level>0)
                   addFAS(c,Bvec);
                 Resid=Bvec;
                 AMat.Solve(Bvec);
                 Distribute(c,Bvec,Resid);
                 updatee0(c);
                 NewtonIters++;
                 dt=fabs(Bvec[totalmodes]);
               }
           }
         else if(_BCArray[c]==1) //Implicit reflecting boundary only
           {
             T dt=1;
             int NewtonIters=0;
             while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
               {
                 TSquare AMatS(totalmodes+1);
                 Bvec.zero();
                 Resid.zero();
                 AMatS.zero();
                 COMETConvection(c,AMatS,Bvec);
                 COMETCollision(c,&AMatS,Bvec);
                 COMETEquilibrium(c,&AMatS,Bvec);
                 if(level>0)
                   addFAS(c,Bvec);
                 Resid=Bvec;
                 AMatS.Solve(Bvec);
                 Distribute(c,Bvec,Resid);
                 updatee0(c);
                 NewtonIters++;
                 dt=fabs(Bvec[totalmodes]);
               }
           }
         else if(_BCArray[c]==2)  //Explicit boundary only
           {
             T dt=1;
             int NewtonIters=0;
             updateGhostFine(c, gradMatrix);
             //updateGhostCoarse(c);
             while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
               {
                 Bvec.zero();
                 Resid.zero();
                 AMat.zero();
                 COMETConvectionFine(c,AMat,Bvec,gradMatrix);
                 COMETCollision(c,&AMat,Bvec);
                 COMETEquilibrium(c,&AMat,Bvec);
                 if(_options.withNormal)
                   COMETShifted(c,&AMat,Bvec);
                 if(level>0)
                   addFAS(c,Bvec);
                 Resid=Bvec;
                 AMat.Solve(Bvec);
                 Distribute(c,Bvec,Resid);
                 dt=fabs(Bvec[totalmodes]);
                 updatee0(c);
                 updateGhostFine(c, gradMatrix);
                 if(!_FaceToKSC.empty())
                   correctInterface(c,Bvec);
                 NewtonIters++;
               }
           }
         else if(_BCArray[c]==3) //Mix Implicit/Explicit reflecting boundary
           {
             T dt=1;
             int NewtonIters=0;
             updateGhostFine(c,gradMatrix);
             while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
               {
                 TSquare AMatS(totalmodes+1);
                 Bvec.zero();
                 Resid.zero();
                 AMatS.zero();
                 COMETConvection(c,AMatS,Bvec);
                 COMETCollision(c,&AMatS,Bvec);
                 COMETEquilibrium(c,&AMatS,Bvec);
                 if(level>0)
                   addFAS(c,Bvec);
                 Resid=Bvec;
                 AMatS.Solve(Bvec);
                 Distribute(c,Bvec,Resid);
                 updatee0(c);
                 updateGhostFine(c, gradMatrix);
                 NewtonIters++;
                 dt=fabs(Bvec[totalmodes]);
               }
           }
         else
           throw CException("Unexpected value for boundary cell map.");
       }
   }
template<class T> void COMETDiscretizer< T >::COMETSolveFull (const int dir, const int level) inline
Definition at line 403 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_BCArray, COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_FaceToKSC, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_options, COMETDiscretizer< T >::addFAS(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETShifted(), COMETDiscretizer< T >::correctInterface(), COMETDiscretizer< T >::Distribute(), fabs(), StorageSite::getSelfCount(), Kspace< T >::gettotmodes(), COMETModelOptions< T >::maxNewton, COMETModelOptions< T >::minNewton, COMETModelOptions< T >::NewtonTol, COMETDiscretizer< T >::ScatterPhonons(), SquareMatrix< T, N >::Solve(), ArrowHeadMatrix< X, K >::Solve(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateGhostCoarse(), COMETModelOptions< T >::withNormal, SquareMatrix< T, N >::zero(), ArrowHeadMatrix< X, K >::zero(), and Array< T >::zero().
Referenced by COMETModel< T >::smooth().
   {
     const int cellcount=_cells.getSelfCount();
     int start;
     if(dir==1)
       start=0;
     if(dir==-1)
       start=cellcount-1;
     const int totalmodes=_kspace.gettotmodes();
     TArray Bvec(totalmodes+1);
     TArray Resid(totalmodes+1);
     TArray s(totalmodes);
     TArray ds(totalmodes);
     TArrow AMat(totalmodes+1);
     const T newTol=_options.NewtonTol;
     const int maxNew=_options.maxNewton;
     const int minNew=_options.minNewton;
     for(int c=start;((c<cellcount)&&(c>-1));c+=dir)
       {
         if(_BCArray[c]==0)  //no reflections at all--interior cell or temperature boundary
           {
             T dt=1;
             int NewtonIters=0;
             for(int srcIts=0;srcIts<1;srcIts++)
               {
                 s.zero();
                 //_kspace.getSourceTerm(c,s,ds);
                 while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
                   {
                     Bvec.zero();
                     Resid.zero();
                     AMat.zero();
                     COMETConvectionCoarse(c,AMat,Bvec);
                     COMETCollision(c,&AMat,Bvec);
                     COMETEquilibrium(c,&AMat,Bvec);
                     //COMETFullScatt(c,s,Bvec);
                     if(_options.withNormal)
                       COMETShifted(c,&AMat,Bvec);
                     if(level>0)
                       addFAS(c,Bvec);
                     Resid=Bvec;
                     AMat.Solve(Bvec);
                     //AMat.SolveDiag(Bvec);
                     //AMat.smoothGS(Bvec);
                     Distribute(c,Bvec,Resid);
                     updatee0(c);
                     NewtonIters++;
                     dt=fabs(Bvec[totalmodes]);
                   }
                 ScatterPhonons(c);
               }
           }
         else if(_BCArray[c]==1) //Implicit reflecting boundary only
           {
             T dt=1;
             int NewtonIters=0;
             while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
               {
                 TSquare AMatS(totalmodes+1);
                 Bvec.zero();
                 Resid.zero();
                 AMatS.zero();
                 COMETConvection(c,AMatS,Bvec);
                 COMETCollision(c,&AMatS,Bvec);
                 COMETEquilibrium(c,&AMatS,Bvec);
                 if(level>0)
                   addFAS(c,Bvec);
                 Resid=Bvec;
                 AMatS.Solve(Bvec);
                 Distribute(c,Bvec,Resid);
                 updatee0(c);
                 NewtonIters++;
                 dt=fabs(Bvec[totalmodes]);
               }
           }
         else if(_BCArray[c]==2)  //Explicit boundary only
           {
             T dt=1;
             int NewtonIters=0;
             updateGhostCoarse(c);
             for(int srcIts=0;srcIts<1;srcIts++)
               {
                 s.zero();
                 //_kspace.getSourceTerm(c,s,ds);
                 while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
                   {
                     Bvec.zero();
                     Resid.zero();
                     AMat.zero();
                     COMETConvectionCoarse(c,AMat,Bvec);
                     COMETCollision(c,&AMat,Bvec);
                     COMETEquilibrium(c,&AMat,Bvec);
                     //COMETFullScatt(c,s,Bvec);
                     if(_options.withNormal)
                       COMETShifted(c,&AMat,Bvec);
                     if(level>0)
                       addFAS(c,Bvec);
                     Resid=Bvec;
                     AMat.Solve(Bvec);
                     //AMat.SolveDiag(Bvec);
                     //AMat.smoothGS(Bvec);
                     Distribute(c,Bvec,Resid);
                     dt=fabs(Bvec[totalmodes]);
                     updatee0(c);
                     updateGhostCoarse(c);
                     if(!_FaceToKSC.empty())
                       correctInterface(c,Bvec);
                     NewtonIters++;
                   }
                 ScatterPhonons(c);
               }
           }
         else if(_BCArray[c]==3) //Mix Implicit/Explicit reflecting boundary
           {
             T dt=1;
             int NewtonIters=0;
             updateGhostCoarse(c);
             while((dt>newTol && NewtonIters<maxNew) || NewtonIters<minNew)
               {
                 TSquare AMatS(totalmodes+1);
                 Bvec.zero();
                 Resid.zero();
                 AMatS.zero();
                 COMETConvection(c,AMatS,Bvec);
                 COMETCollision(c,&AMatS,Bvec);
                 COMETEquilibrium(c,&AMatS,Bvec);
                 if(level>0)
                   addFAS(c,Bvec);
                 Resid=Bvec;
                 AMatS.Solve(Bvec);
                 Distribute(c,Bvec,Resid);
                 updatee0(c);
                 updateGhostCoarse(c);
                 NewtonIters++;
                 dt=fabs(Bvec[totalmodes]);
               }
           }
         else
           throw CException("Unexpected value for boundary cell map.");
       }
   }
template<class T> void COMETDiscretizer< T >::COMETSource (const int cell, TArray & BVec) inline
Definition at line 1059 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cellVolume, COMETDiscretizer< T >::_kspace, and Kspace< T >::addSource().
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), and COMETDiscretizer< T >::findResidCoarse().
   {_kspace.addSource(cell, BVec,_cellVolume[cell]);}
template<class T> void COMETDiscretizer< T >::correctInterface (const int cell0, TArray & Bvec) inline
Definition at line 2032 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_BCfArray, COMETDiscretizer< T >::_cellFaces, COMETDiscretizer< T >::_faceCells, COMETDiscretizer< T >::_FaceToKSC, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_mesh, COMETDiscretizer< T >::Distribute(), COMETDiscretizer< T >::findFgId(), CRConnectivity::getCount(), Kspace< T >::getDK3(), Mesh::getFaceGroup(), StorageSite::getOffset(), Kspace< T >::gettotmodes(), KSConnectivity< T >::multiplySelf(), FaceGroup::site, and Array< T >::zero().
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), and COMETDiscretizer< T >::COMETSolveFull().
   {
     const int klen=_kspace.gettotmodes();
     const T DK3=_kspace.getDK3();
     TArray Correction(klen+1);
     const int neibcount=_cellFaces.getCount(cell0);
     for(int j=0;j<neibcount;j++)
       {
         const int f=_cellFaces(cell0,j);
         if(_BCfArray[f]==4)
           {
             int Fgid=findFgId(f);
             const FaceGroup& fg=_mesh.getFaceGroup(Fgid);
             const StorageSite& faces0=fg.site;
             const int offset=faces0.getOffset();
             int cell1=_faceCells(f,1);
             if(cell1==cell0)
               cell1=_faceCells(f,0);
             const TKConnectivity& TKC=*(_FaceToKSC.find(Fgid)->second)[f-offset];
             TKC.multiplySelf(Bvec,Correction,DK3);
             Bvec.zero();
             Distribute(cell1,Correction, Bvec);
           }
       }
   }
template<class T> void COMETDiscretizer< T >::Distribute (const int cell, TArray & BVec, TArray & Rvec) inline
Definition at line 1187 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_eArray, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, COMETDiscretizer< T >::_resArray, PhononMacro::deltaT, Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::gettotmodes(), PhononMacro::temperature, and PhononMacro::TlResidual.
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::correctInterface(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
   {
     const int klen=_kspace.getlength();
     const int totalmodes=_kspace.gettotmodes();
     int cellIndex=_kspace.getGlobalIndex(cell,0);
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             const int count=mode.getIndex()-1;
             _eArray[cellIndex]+=BVec[count];
             _resArray[cellIndex]=-Rvec[count];
             cellIndex++;
           }
       }
     TArray& TlArray=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     TlArray[cell]+=BVec[totalmodes];
     TArray& deltaTArray=dynamic_cast<TArray&>(_macro.deltaT[_cells]);
     deltaTArray[cell]=BVec[totalmodes];
     TArray& TlResArray=dynamic_cast<TArray&>(_macro.TlResidual[_cells]);
     TlResArray[cell]=-Rvec[totalmodes];
   }
template<class T> int COMETDiscretizer< T >::findFgId (const int faceIndex) inline
Definition at line 1563 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_fgFinder.
Referenced by COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::correctInterface(), COMETDiscretizer< T >::updateGhostCoarse(), and COMETDiscretizer< T >::updateGhostFine().
   {
     FaceToFg::iterator id;
     for(id=_fgFinder.begin();id!=_fgFinder.end();id++)
       {
         if(id->second[0]<=faceIndex && id->second[1]>faceIndex)
           return id->first;
       }
     cout<<"Face index: "<<faceIndex<<endl;
     throw CException("Didn't find matching FaceGroup!");
     return -1;
   }
template<class T> void COMETDiscretizer< T >::findResidCoarse (const bool plusFAS) inline
Definition at line 1314 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_aveResid, COMETDiscretizer< T >::_BCArray, COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_residChange, COMETDiscretizer< T >::addFAS(), COMETDiscretizer< T >::ArrayAbs(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETSource(), COMETDiscretizer< T >::Distribute(), fabs(), StorageSite::getSelfCount(), Kspace< T >::gettotmodes(), ArrowHeadMatrix< X, K >::getTraceAbs(), SquareMatrix< T, N >::getTraceAbs(), COMETDiscretizer< T >::makeValueArray(), ArrowHeadMatrix< X, K >::multiply(), SquareMatrix< T, N >::multiply(), COMETDiscretizer< T >::updateGhostCoarse(), SquareMatrix< T, N >::zero(), ArrowHeadMatrix< X, K >::zero(), and Array< T >::zero().
Referenced by COMETModel< T >::updateResid().
   {
     const int cellcount=_cells.getSelfCount();
     const int totalmodes=_kspace.gettotmodes();
     TArray ResidSum(totalmodes+1);
     TArray Bsum(totalmodes+1);
     T ResidScalar=0.;
     T traceSum=0.;
     TArray Bvec(totalmodes+1);
     TArray Resid(totalmodes+1);
     TArray Dummy(totalmodes+1);
     TArrow AMat(totalmodes+1);
     ResidSum.zero();
     Bsum.zero();
     Dummy.zero();
     for(int c=0;c<cellcount;c++)
       {
         Bvec.zero();
         Resid.zero();
         Dummy.zero();
         if(_BCArray[c]==0 || _BCArray[c]==2)  //Arrowhead
           {
             if(_BCArray[c]==2)
               updateGhostCoarse(c);
             AMat.zero();
             COMETConvectionCoarse(c,AMat,Bvec);
             COMETCollision(c,&AMat,Bvec);
             COMETEquilibrium(c,&AMat,Bvec);
             COMETSource(c,Bvec);
             if(plusFAS)
               addFAS(c,Bvec);
             traceSum+=AMat.getTraceAbs();
             Resid=Bvec;
             Bvec.zero();
             Distribute(c,Bvec,Resid);
             ArrayAbs(Resid);
             ResidSum+=Resid;
             AMat.multiply(Resid,Bvec);
             Resid=Bvec;
             makeValueArray(c,Bvec);
             AMat.multiply(Bvec,Dummy);
             Bvec=Dummy;
             ArrayAbs(Bvec);
             ArrayAbs(Resid);
             Bsum+=Bvec;
           }
         else if(_BCArray[c]==1 || _BCArray[c]==3) //General Dense
           {
             TSquare AMatS(totalmodes+1);
             AMatS.zero();
             COMETConvection(c,AMatS,Bvec);
             COMETCollision(c,&AMatS,Bvec);
             COMETEquilibrium(c,&AMatS,Bvec);
             if(plusFAS)
               addFAS(c,Bvec);
             traceSum+=AMatS.getTraceAbs();
             Resid=Bvec;
             Bvec.zero();
             Distribute(c,Bvec,Resid);
             AMatS.multiply(Resid,Bvec);
             Resid=Bvec;
             makeValueArray(c,Bvec);
             ArrayAbs(Resid);
             ArrayAbs(Bvec);
             Bsum+=Bvec;
             ResidSum+=Resid;
           }
         else
           throw CException("Unexpected value for boundary cell map.");
       }
     //traceSum=0;  //added
     for(int o=0;o<totalmodes+1;o++)
       {
         ResidScalar+=ResidSum[o];
         //traceSum+=Bsum[o]; //added
       }
     ResidScalar/=traceSum;
     if(_aveResid==-1)
       {_aveResid=ResidScalar;}
     else
       {
         _residChange=fabs(_aveResid-ResidScalar)/_aveResid;
         _aveResid=ResidScalar;
       }
   }
template<class T> void COMETDiscretizer< T >::findResidFine () inline
Definition at line 1215 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_aveResid, COMETDiscretizer< T >::_BCArray, COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_geomFields, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_mesh, COMETDiscretizer< T >::_residChange, COMETDiscretizer< T >::ArrayAbs(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::Distribute(), fabs(), GradientModel< T >::getGradientMatrix(), StorageSite::getSelfCount(), Kspace< T >::gettotmodes(), ArrowHeadMatrix< X, K >::getTraceAbs(), SquareMatrix< T, N >::getTraceAbs(), COMETDiscretizer< T >::makeValueArray(), ArrowHeadMatrix< X, K >::multiply(), SquareMatrix< T, N >::multiply(), SquareMatrix< T, N >::zero(), ArrowHeadMatrix< X, K >::zero(), and Array< T >::zero().
Referenced by COMETModel< T >::updateResid().
   {
     const int cellcount=_cells.getSelfCount();
     const int totalmodes=_kspace.gettotmodes();
     TArray ResidSum(totalmodes+1);
     TArray Bsum(totalmodes+1);
     T ResidScalar=0.;
     T traceSum=0.;
     TArray Bvec(totalmodes+1);
     TArray Resid(totalmodes+1);
     TArray Dummy(totalmodes+1);
     TArrow AMat(totalmodes+1);
     ResidSum.zero();
     Bsum.zero();
     Dummy.zero();
     GradMatrix& gradMatrix=GradModelType::getGradientMatrix(_mesh,_geomFields);
     for(int c=0;c<cellcount;c++)
       {
         Bvec.zero();
         Resid.zero();
         Dummy.zero();
         if(_BCArray[c]==0 || _BCArray[c]==2)  //Arrowhead
           {
             //updateGhostFine(c, gradMatrix);
             //updateGhostCoarse(c);
             AMat.zero();
             COMETConvectionFine(c,AMat,Bvec,gradMatrix);
             COMETCollision(c,&AMat,Bvec);
             COMETEquilibrium(c,&AMat,Bvec);
             traceSum+=AMat.getTraceAbs();
             Resid=Bvec;
             Bvec.zero();
             Distribute(c,Bvec,Resid);
             ArrayAbs(Resid);
             ResidSum+=Resid;
             AMat.multiply(Resid,Bvec);
             Resid=Bvec;
             makeValueArray(c,Bvec);
             AMat.multiply(Bvec,Dummy);
             Bvec=Dummy;
             ArrayAbs(Bvec);
             ArrayAbs(Resid);
             Bsum+=Bvec;
           }
         else if(_BCArray[c]==1 || _BCArray[c]==3) //General Dense
           {
             TSquare AMatS(totalmodes+1);
             AMatS.zero();
             COMETConvection(c,AMatS,Bvec);
             COMETCollision(c,&AMatS,Bvec);
             COMETEquilibrium(c,&AMatS,Bvec);
             traceSum+=AMatS.getTraceAbs();
             Resid=Bvec;
             Bvec.zero();
             Distribute(c,Bvec,Resid);
             AMatS.multiply(Resid,Bvec);
             Resid=Bvec;
             makeValueArray(c,Bvec);
             ArrayAbs(Resid);
             ArrayAbs(Bvec);
             Bsum+=Bvec;
             ResidSum+=Resid;
           }
         else
           throw CException("Unexpected value for boundary cell map.");
       }
     //traceSum=0;  //added
     for(int o=0;o<totalmodes+1;o++)
       {
         ResidScalar+=ResidSum[o];
         //traceSum+=Bsum[o]; //added
       }
     ResidScalar/=traceSum;
     if(_aveResid==-1)
       {_aveResid=ResidScalar;}
     else
       {
         _residChange=fabs(_aveResid-ResidScalar)/_aveResid;
         _aveResid=ResidScalar;
       }
   }
template<class T> void COMETDiscretizer< T >::findResidFull () inline
Definition at line 1417 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_aveResid, COMETDiscretizer< T >::_BCArray, COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_residChange, COMETDiscretizer< T >::ArrayAbs(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETFullScatt(), COMETDiscretizer< T >::Distribute(), fabs(), StorageSite::getSelfCount(), Kspace< T >::getSourceTerm(), Kspace< T >::gettotmodes(), ArrowHeadMatrix< X, K >::getTraceAbs(), SquareMatrix< T, N >::getTraceAbs(), COMETDiscretizer< T >::makeValueArray(), ArrowHeadMatrix< X, K >::multiply(), SquareMatrix< T, N >::multiply(), COMETDiscretizer< T >::updateGhostCoarse(), SquareMatrix< T, N >::zero(), ArrowHeadMatrix< X, K >::zero(), and Array< T >::zero().
Referenced by COMETModel< T >::updateResid().
   {
     const int cellcount=_cells.getSelfCount();
     const int totalmodes=_kspace.gettotmodes();
     TArray ResidSum(totalmodes+1);
     TArray Bsum(totalmodes+1);
     T ResidScalar=0.;
     T traceSum=0.;
     TArray Bvec(totalmodes+1);
     TArray Resid(totalmodes+1);
     TArray Dummy(totalmodes+1);
     TArray s(totalmodes);
     TArray ds(totalmodes);
     TArrow AMat(totalmodes+1);
     ResidSum.zero();
     Bsum.zero();
     Dummy.zero();
     for(int c=0;c<cellcount;c++)
       {
         Bvec.zero();
         Resid.zero();
         Dummy.zero();
         s.zero();
         ds.zero();
         _kspace.getSourceTerm(c,s,ds);
         if(_BCArray[c]==0 || _BCArray[c]==2)  //Arrowhead
           {
             if(_BCArray[c]==2)
               updateGhostCoarse(c);
             AMat.zero();
             COMETConvectionCoarse(c,AMat,Bvec);
             COMETCollision(c,&AMat,Bvec);
             // COMETEquilibrium(c,&AMat,Bvec);
             COMETFullScatt(c,s,Bvec);
             traceSum+=AMat.getTraceAbs();
             Resid=Bvec;
             Bvec.zero();
             Distribute(c,Bvec,Resid);
             ArrayAbs(Resid);
             ResidSum+=Resid;
             AMat.multiply(Resid,Bvec);
             Resid=Bvec;
             makeValueArray(c,Bvec);
             AMat.multiply(Bvec,Dummy);
             Bvec=Dummy;
             ArrayAbs(Bvec);
             ArrayAbs(Resid);
             Bsum+=Bvec;
           }
         else if(_BCArray[c]==1 || _BCArray[c]==3) //General Dense
           {
             TSquare AMatS(totalmodes+1);
             AMatS.zero();
             COMETConvection(c,AMatS,Bvec);
             COMETCollision(c,&AMatS,Bvec);
             COMETEquilibrium(c,&AMatS,Bvec);
             traceSum+=AMatS.getTraceAbs();
             Resid=Bvec;
             Bvec.zero();
             Distribute(c,Bvec,Resid);
             AMatS.multiply(Resid,Bvec);
             Resid=Bvec;
             makeValueArray(c,Bvec);
             ArrayAbs(Resid);
             ArrayAbs(Bvec);
             Bsum+=Bvec;
             ResidSum+=Resid;
           }
         else
           throw CException("Unexpected value for boundary cell map.");
       }
     //traceSum=0;  //added
     for(int o=0;o<totalmodes+1;o++)
       {
         ResidScalar+=ResidSum[o];
         //traceSum+=Bsum[o]; //added
       }
     ResidScalar/=traceSum;
     if(_aveResid==-1)
       {_aveResid=ResidScalar;}
     else
       {
         _residChange=fabs(_aveResid-ResidScalar)/_aveResid;
         _aveResid=ResidScalar;
       }
   }
template<class T> TArray COMETDiscretizer< T >::gatherResid (const int c) inline
Definition at line 1520 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getresid(), Kspace< T >::gettotmodes(), and PhononMacro::TlResidual.
   {
     const int klen=_kspace.getlength();
     const int totalmodes=_kspace.gettotmodes();
     const int order=totalmodes+1;
     TArray rArray(order);
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             const int count=mode.getIndex();
             Field& resfield=mode.getresid();
             TArray& resArray=dynamic_cast<TArray&>(resfield[_cells]);
             rArray[count]=resArray[c];
           }
       }
     rArray[order]=_macro.TlResidual[c];
   }
template<class T> T COMETDiscretizer< T >::getAveResid () inline
Definition at line 1545 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_aveResid.
Referenced by COMETModel< T >::updateResid().
 {return _aveResid;}
template<class T> T COMETDiscretizer< T >::getResidChange () inline
Definition at line 1544 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_residChange.
 {return _residChange;}
template<class T> void COMETDiscretizer< T >::makeValueArray (const int c, TArray & o) inline
Definition at line 1583 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_eArray, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::gettotmodes(), and PhononMacro::temperature.
Referenced by COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
   {
     int klen=_kspace.getlength();
     const int totmodes=_kspace.gettotmodes();
     int cellIndex=_kspace.getGlobalIndex(c,0);
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             const int count=mode.getIndex()-1;
             o[count]=_eArray[cellIndex];
             cellIndex++;
           }
       }
     TArray& Tl=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     o[totmodes]=Tl[c];
   }
template<class T> void COMETDiscretizer< T >::outerProduct (const VectorT3 & v1, const VectorT3 & v2, T3Tensor & out) inline
Definition at line 2124 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::updateeShifted().
   {
     for(int i=0;i<3;i++)
       for(int j=0;j<3;j++)
         out(i,j)=v1[i]*v2[j];
   }
template<class T> T COMETDiscretizer< T >::scaledResid (const TArray & de, const int c) inline
Definition at line 2131 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_eArray, COMETDiscretizer< T >::_kspace, fabs(), Kspace< T >::getGlobalIndex(), and Array< T >::getLength().
Referenced by COMETDiscretizer< T >::COMETSolveCoarse().
   {
     T scaled(0);
     int cellIndex(_kspace.getGlobalIndex(c,0));
     for(int i=0;i<de.getLength()-1;i++)
       {
         scaled+=fabs(de[i])/_eArray[cellIndex];
         cellIndex++;
       }
     return scaled/de.getLength();
   }
template<class T> void COMETDiscretizer< T >::ScatterPhonons (const int cell0) inline
Definition at line 1097 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cellFaces, COMETDiscretizer< T >::_cellVolume, COMETDiscretizer< T >::_e0Array, COMETDiscretizer< T >::_eArray, COMETDiscretizer< T >::_faceArea, COMETDiscretizer< T >::_faceCells, COMETDiscretizer< T >::_kspace, CRConnectivity::getCount(), Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), Kspace< T >::gettotmodes(), pmode< T >::getv(), Kspace< T >::ScatterPhonons(), and Array< T >::zero().
Referenced by COMETDiscretizer< T >::COMETSolveFull().
   {
     TArray C(_kspace.gettotmodes());
     TArray B(_kspace.gettotmodes());
     TArray V(_kspace.gettotmodes());
     TArray newE(_kspace.gettotmodes());
     C.zero();
     B.zero();
     V.zero();
     newE.zero();
     const int neibcount=_cellFaces.getCount(cell0);
     for(int j=0;j<neibcount;j++)
       {
         const int f=_cellFaces(cell0,j);
         int cell1=_faceCells(f,1);
         VectorT3 Af=_faceArea[f];
         if(cell1==cell0)
           {
             cell1=_faceCells(f,0);
             Af*=-1.;
           }
         const int klen=_kspace.getlength();
         T flux;
         for(int k=0;k<klen;k++)
           {
             Tkvol& kvol=_kspace.getkvol(k);
             const int numModes=kvol.getmodenum();
             for(int m=0;m<numModes;m++)
               {
                 Tmode& mode=kvol.getmode(m);
                 const int count=mode.getIndex();
                 const VectorT3 vg=mode.getv();
                 flux=vg[0]*Af[0]+vg[1]*Af[1]+vg[2]*Af[2];
                 if(flux>T_Scalar(0))  //outgoing
                   {
                     V[count-1]+=flux/_cellVolume[cell0];
                     B[count-1]+=flux*_e0Array[_kspace.getGlobalIndex(cell0,count-1)]/_cellVolume[cell0];
                     C[count-1]+=flux*_eArray[_kspace.getGlobalIndex(cell0,count-1)]/_cellVolume[cell0];
                   }
                 else   //incoming
                   C[count-1]+=flux*_eArray[_kspace.getGlobalIndex(cell1,count-1)]/_cellVolume[cell0];
               }
           }
       }
     _kspace.ScatterPhonons(cell0, 50, C, B, V, newE, _cellVolume[cell0]);
   }
template<class T> void COMETDiscretizer< T >::setfgFinder () inline
Definition at line 1547 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_fgFinder, COMETDiscretizer< T >::_mesh, Mesh::getBoundaryFaceGroups(), StorageSite::getCount(), StorageSite::getOffset(), FaceGroup::id, and FaceGroup::site.
Referenced by COMETModel< T >::smooth(), and COMETModel< T >::updateResid().
   {
     foreach(const FaceGroupPtr fgPtr, _mesh.getBoundaryFaceGroups())
       {
         const FaceGroup& fg=*fgPtr;
         const int off=fg.site.getOffset();
         const int cnt=fg.site.getCount();
         const int id=fg.id;
         VecInt2 BegEnd;
         BegEnd[0]=off;
         BegEnd[1]=off+cnt;
         _fgFinder[id]=BegEnd;
       }
   }
template<class T> void COMETDiscretizer< T >::updatee0 () inline
Definition at line 1612 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_e0Array, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, pmode< T >::calce0(), Kspace< T >::getGlobalIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), StorageSite::getSelfCount(), and PhononMacro::temperature.
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), and COMETDiscretizer< T >::COMETSolveFull().
   {
     TArray& Tl=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     const T cellCount=_cells.getSelfCount();
     int klen=_kspace.getlength();
     for(int c=0;c<cellCount;c++)
       {
         int cellIndex=_kspace.getGlobalIndex(c,0);
         for(int k=0;k<klen;k++)
           {
             Tkvol& kvol=_kspace.getkvol(k);
             const int numModes=kvol.getmodenum();
             for(int m=0;m<numModes;m++)
               {
                 Tmode& mode=kvol.getmode(m);
                 _e0Array[cellIndex]=mode.calce0(Tl[c]);
                 cellIndex++;
               }
           }
       }
   }
template<class T> void COMETDiscretizer< T >::updatee0 (const int c) inline
Definition at line 1635 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_e0Array, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, pmode< T >::calce0(), Kspace< T >::getGlobalIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), PhononMacro::temperature, and Kspace< T >::updateTau().
   {
     TArray& Tl=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     int klen=_kspace.getlength();
     int cellIndex=_kspace.getGlobalIndex(c,0);
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             _e0Array[cellIndex]=mode.calce0(Tl[c]);
             _kspace.updateTau(c,Tl[c]);
             cellIndex++;
           }
       }
   }
template<class T> void COMETDiscretizer< T >::updateeShifted () inline
Definition at line 2060 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, kvol< T >::getdk3(), pmode< T >::geteShifted(), pmode< T >::getfield(), kvol< T >::getkvec(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), StorageSite::getSelfCount(), inverse(), PhononMacro::lam, COMETDiscretizer< T >::outerProduct(), PhononMacro::temperature, Vector< T, N >::zero(), and SquareTensor< T, N >::zero().
   {
     const int cellcount=_cells.getSelfCount();
     TArray& Tl=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     VectorT3Array& lam=dynamic_cast<VectorT3Array&>(_macro.lam[_cells]);
     for(int c=0;c<cellcount;c++)
       {
         T3Tensor TensorSum;
         VectorT3 VectorSum;
         VectorT3 lambda;
         T TpreFactor=0.;
         T VpreFactor=0.;
         int klen=_kspace.getlength();
         for(int k=0;k<klen;k++)
           {
             Tkvol& kvol=_kspace.getkvol(k);
             const int numModes=kvol.getmodenum();
             for(int m=0;m<numModes;m++)
               {
                 Tmode& mode=kvol.getmode(m);
                 Field& eField=mode.getfield();
                 TArray& eArray=dynamic_cast<TArray&>(eField[_cells]);
                 TpreFactor+=mode.calcTensorPrefactor(Tl[c]);
                 VpreFactor+=mode.calcVectorPrefactor(Tl[c],eArray[c]);
               }
           }
         TensorSum.zero();
         VectorSum.zero();
         for(int k=0;k<klen;k++)
           {
             Tkvol& kvol=_kspace.getkvol(k);
             T dk3=kvol.getdk3();
             VectorT3 Kvec=kvol.getkvec();
             T3Tensor TempTensor;
             outerProduct(Kvec,Kvec,TempTensor);
             TensorSum+=TempTensor*dk3*TpreFactor;
             VectorSum+=Kvec*dk3*VpreFactor;
           }
         lambda=inverse(TensorSum)*VectorSum;
         lam[c]=lambda;
         for(int k=0;k<klen;k++)
           {
             Tkvol& kvol=_kspace.getkvol(k);
             VectorT3 Kvec=kvol.getkvec();
             T shift=Kvec[0]*lambda[0]+Kvec[1]*lambda[1]+Kvec[2]*lambda[2];
             const int numModes=kvol.getmodenum();
             for(int m=0;m<numModes;m++)
               {
                 Tmode& mode=kvol.getmode(m);
                 Field& eShiftedField=mode.geteShifted();
                 TArray& eShifted=dynamic_cast<TArray&>(eShiftedField[_cells]);
                 eShifted[c]=mode.calcShifted(Tl[c],shift);
               }
           }
       }
   }
template<class T> void COMETDiscretizer< T >::updateGhostCoarse (const int cell) inline
Definition at line 1932 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_BCfArray, COMETDiscretizer< T >::_bcMap, COMETDiscretizer< T >::_cellFaces, COMETDiscretizer< T >::_cells, COMETDiscretizer< T >::_eArray, COMETDiscretizer< T >::_faceArea, COMETDiscretizer< T >::_faceCells, COMETDiscretizer< T >::_kspace, COMETDiscretizer< T >::_macro, pmode< T >::calce0(), Kspace< T >::calcTemp(), COMETDiscretizer< T >::findFgId(), CRConnectivity::getCount(), kvol< T >::getdk3(), Kspace< T >::getDK3(), Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getReflpair(), pmode< T >::getv(), and PhononMacro::temperature.
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::findResidCoarse(), and COMETDiscretizer< T >::findResidFull().
   {
     const int neibcount=_cellFaces.getCount(cell);
     const int klen=_kspace.getlength();
     TArray& Tl=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     T DK3=_kspace.getDK3();
     for(int j=0;j<neibcount;j++)
       {
         const int f=_cellFaces(cell,j);
         if(_BCfArray[f]==3)
           {
             T SumEVdotA(0);
             int Fgid=findFgId(f);
             const T refl=(*(_bcMap[Fgid]))["specifiedReflection"];
             int cell2=_faceCells(f,1);
             VectorT3 Af=_faceArea[f];
             if(cell2==cell)
               {
                 Af=Af*-1.;
                 cell2=_faceCells(f,0);
               }
             const int cellstart=_kspace.getGlobalIndex(cell,0);
             int cellIndex=_kspace.getGlobalIndex(cell,0);
             int cell2Index=_kspace.getGlobalIndex(cell2,0);
             //first loop to sum up the diffuse reflection
             for(int k=0;k<klen;k++)
               {
                 Tkvol& kvol=_kspace.getkvol(k);
                 const int numModes=kvol.getmodenum();
                 T dk3=kvol.getdk3();
                 for(int m=0;m<numModes;m++)
                   {
                     Tmode& mode=kvol.getmode(m);
                     VectorT3 vg=mode.getv();
                     const T VdotA=Af[0]*vg[0]+Af[1]*vg[1]+Af[2]*vg[2];
                     if(VdotA>0)
                       {
                         _eArray[cell2Index]=_eArray[cellIndex]*refl;
                         SumEVdotA+=_eArray[cellIndex]*VdotA*(dk3/DK3);
                       }
                     else
                       {
                         if(refl==1.)
{
                             Refl_pair& rpairs=mode.getReflpair(Fgid);
                             const int kk=rpairs.second.second;
                             Tkvol& kkvol=_kspace.getkvol(kk);
                             Tmode& refMode=kkvol.getmode(m);
                             const int rIndex=cellstart+refMode.getIndex()-1;
                             _eArray[cell2Index]=_eArray[rIndex]*refl;
                           }
                         else
                           _eArray[cell2Index]=0;
                       }
                     cellIndex++;
                     cell2Index++;
                   }
               }
             //second loop to add in the diffuse reflection
             if(refl==0.)
               {
                 T wallTemp=Tl[cell2];
                 T esum=SumEVdotA*DK3;
                 _kspace.calcTemp(wallTemp,esum,Af);
                 SumEVdotA=wallTemp;
                 Tl[cell2]=wallTemp;
                 for(int k=0;k<klen;k++)
                   {
                     Tkvol& kvol=_kspace.getkvol(k);
                     const int numModes=kvol.getmodenum();
                     for(int m=0;m<numModes;m++)
                       {
                         Tmode& mode=kvol.getmode(m);
                         VectorT3 vg=mode.getv();
                         const int Index=mode.getIndex()-1;
                         const int cell2Index=_kspace.getGlobalIndex(cell2,Index);
                         const T oneMinusRefl=1.-refl;
                         //const T VdotA=Af[0]*vg[0]+Af[1]*vg[1]+Af[2]*vg[2];
                         _eArray[cell2Index]+=mode.calce0(Tl[cell2])*oneMinusRefl;
                       }
                   }
               }
           }
       }
   }
template<class T> void COMETDiscretizer< T >::updateGhostFine (const int cell, const GradMatrix & gMat) inline
Definition at line 1655 of file COMETDiscretizer.h.
References COMETDiscretizer< T >::_BCfArray, COMETDiscretizer< T >::_bcMap, COMETDiscretizer< T >::_cellCoords, COMETDiscretizer< T >::_cellFaces, COMETDiscretizer< T >::_eArray, COMETDiscretizer< T >::_faceArea, COMETDiscretizer< T >::_faceCells, COMETDiscretizer< T >::_faces, COMETDiscretizer< T >::_geomFields, COMETDiscretizer< T >::_kspace, computeLimitCoeff2(), GeomFields::coordinate, COMETDiscretizer< T >::findFgId(), GradientMatrix< T_Scalar >::getCoeff(), CRConnectivity::getCount(), Kspace< T >::getGlobalIndex(), pmode< T >::getIndex(), Kspace< T >::getkvol(), Kspace< T >::getlength(), kvol< T >::getmode(), kvol< T >::getmodenum(), pmode< T >::getReflpair(), Kspace< T >::gettotmodes(), pmode< T >::getv(), and Array< T >::zero().
Referenced by COMETDiscretizer< T >::COMETSolveFine().
   {
     const int neibcount=_cellFaces.getCount(cell);
     const int klen=_kspace.getlength();
     //TArray SumEVdotA(neibcount);
     //TArray& Tl=dynamic_cast<TArray&>(_macro.temperature[_cells]);
     //T DK3=_kspace.getDK3();
     //SumEVdotA.zero();
     const VectorT3Array& faceCoords=
       dynamic_cast<const VectorT3Array&>(_geomFields.coordinate[_faces]);
     TArray pointMin(_kspace.gettotmodes());
     pointMin=-1;
     TArray pointMax(_kspace.gettotmodes());
     pointMax.zero();
     TArray pointLim(_kspace.gettotmodes());
     pointLim=100.;
     GradArray Grads(_kspace.gettotmodes());
     Grads.zero();
     VectorT3 Gcoeff;
     for(int j=0;j<neibcount;j++)    //first loop to get grad and max/min vals
       {
         const int f=_cellFaces(cell,j);
         int cell1=_faceCells(f,1);
         if(cell1==cell)
           cell1=_faceCells(f,0);
         const VectorT3 Gcoeff=gMat.getCoeff(cell, cell1);
         int c0ind=_kspace.getGlobalIndex(cell,0);
         int c1ind=_kspace.getGlobalIndex(cell1,0);
         for(int k=0;k<_kspace.gettotmodes();k++)
           {
             const T e1=_eArray[c1ind];
             const T e0=_eArray[c0ind];
             T& curMax=pointMax[k];
             T& curMin=pointMin[k];
             Grads[k].accumulate(Gcoeff, e1-e0);
             if(e1>curMax)
               curMax=e1;
             if(curMin==-1)
               curMin=e1;
             else
               {
                 if(e1<curMin)
                   curMin=e1;
               }
             c0ind++;
             c1ind++;
           }
       }
     for(int j=0;j<neibcount;j++)    //second loop to calculate limiting coeff
       {
         const int f=_cellFaces(cell,j);
         int cell1=_faceCells(f,1);
         if(cell1==cell)
           cell1=_faceCells(f,0);
         const VectorT3 dr0(faceCoords[f]-_cellCoords[cell]);
         int c0ind=_kspace.getGlobalIndex(cell,0);
         vanLeer lf;
         for(int k=0;k<_kspace.gettotmodes();k++)
           {
             const T minVal=pointMin[k];
             const T maxVal=pointMax[k];
             const T de0(Grads[k]*dr0);
             T& cl=pointLim[k];
             computeLimitCoeff2(cl, _eArray[c0ind], de0, minVal, maxVal, lf);
             c0ind++;
           }
       }
     for(int j=0;j<neibcount;j++)
       {
         const int f=_cellFaces(cell,j);
         if(_BCfArray[f]==1)
           {//temperature
             //int Fgid=findFgId(f);
             int cell2=_faceCells(f,1);
             VectorT3 Af=_faceArea[f];
             if(cell2==cell)
               {
                 Af=Af*-1.;
                 cell2=_faceCells(f,0);
               }
             int cellIndex=_kspace.getGlobalIndex(cell,0);
             int cell2Index=_kspace.getGlobalIndex(cell2,0);
             //vanLeer vl;
             for(int k=0;k<klen;k++)
               {
                 Tkvol& kvol=_kspace.getkvol(k);
                 const int numModes=kvol.getmodenum();
                 //T dk3=kvol.getdk3();
                 for(int m=0;m<numModes;m++)
                   {
                     Tmode& mode=kvol.getmode(m);
                     VectorT3 vg=mode.getv();
                     const T VdotA=Af[0]*vg[0]+Af[1]*vg[1]+Af[2]*vg[2];
                     const int count=mode.getIndex();
                     GradType& grad=Grads[count-1];
                     if(VdotA>0)
                       {
                         const VectorT3 fVec=faceCoords[f]-_cellCoords[cell];
                         const VectorT3 rVec=_cellCoords[cell2]-_cellCoords[cell];
                         //const T r=gMat.computeR(grad,_eArray,rVec,cellIndex,cell2Index);
                         T SOU=(fVec[0]*grad[0]+fVec[1]*grad[1]+
                                fVec[2]*grad[2])*pointLim[count-1];
                         _eArray[cell2Index]=_eArray[cellIndex]+SOU;
                       }
                     cellIndex++;
                     cell2Index++;
                   }
               }
           }
         else if(_BCfArray[f]==3)
           {//reflecting
             int Fgid=findFgId(f);
             const T refl=(*(_bcMap[Fgid]))["specifiedReflection"];
             int cell2=_faceCells(f,1);
             VectorT3 Af=_faceArea[f];
             if(cell2==cell)
               {
                 Af=Af*-1.;
                 cell2=_faceCells(f,0);
               }
             //const int cellstart=_kspace.getGlobalIndex(cell,0);
             const int cell2start=_kspace.getGlobalIndex(cell2,0);
             int cellIndex=_kspace.getGlobalIndex(cell,0);
             int cell2Index=_kspace.getGlobalIndex(cell2,0);
             vanLeer vl;
             //first loop to sum up the diffuse reflection
             for(int k=0;k<klen;k++)
               {
                 Tkvol& kvol=_kspace.getkvol(k);
                 const int numModes=kvol.getmodenum();
                 //T dk3=kvol.getdk3();
                 for(int m=0;m<numModes;m++)
                   {
                     Tmode& mode=kvol.getmode(m);
                     VectorT3 vg=mode.getv();
                     const T VdotA=Af[0]*vg[0]+Af[1]*vg[1]+Af[2]*vg[2];
                     const int count=mode.getIndex();
                     GradType& grad=Grads[count-1];
                     if(VdotA>0)
                       {
                         VectorT3 rVec=_cellCoords[cell2]-_cellCoords[cell];
                         VectorT3 fVec=faceCoords[f]-_cellCoords[cell];
                         //T r=gMat.computeR(grad,_eArray,rVec,cellIndex,cell2Index);
                         T SOU=(grad[0]*fVec[0]+grad[1]*fVec[1]+grad[2]*fVec[2])*pointLim[count-1];
                         _eArray[cell2Index]=(_eArray[cellIndex]+SOU)*refl;
                       }
                     cellIndex++;
                     cell2Index++;
                   }
               }
             cellIndex=_kspace.getGlobalIndex(cell,0);
             cell2Index=_kspace.getGlobalIndex(cell2,0);
             //first loop to sum up the diffuse reflection
             for(int k=0;k<klen;k++)
               {
                 Tkvol& kvol=_kspace.getkvol(k);
                 const int numModes=kvol.getmodenum();
                 //T dk3=kvol.getdk3();
                 for(int m=0;m<numModes;m++)
                   {
                     Tmode& mode=kvol.getmode(m);
                     VectorT3 vg=mode.getv();
                     const T VdotA=Af[0]*vg[0]+Af[1]*vg[1]+Af[2]*vg[2];
                     //const int count=mode.getIndex();
                     if(VdotA<0)
                       {
                         Refl_pair& rpairs=mode.getReflpair(Fgid);
                         const int kk=rpairs.second.second;
                         Tkvol& kkvol=_kspace.getkvol(kk);
                         Tmode& refMode=kkvol.getmode(m);
                         const int rIndex=cell2start+refMode.getIndex()-1;
                         _eArray[cell2Index]=_eArray[rIndex]*refl;
                         }
                     cellIndex++;
                     cell2Index++;
                   }
               }
           }
       }
     /*
     T wallTemp(Tl[cell]);
     for(int j=0;j<neibcount;j++)
       {
         const int f=_cellFaces(cell,j);
         if(_BCfArray[f]==3)
           {
             int cell2=_faceCells(f,1);
             VectorT3 Af=_faceArea[f];
             if(cell2==cell)
               {
                 Af=Af*-1.;
                 cell2=_faceCells(f,0);
               }
             T esum=SumEVdotA[j]*DK3;
             _kspace.calcTemp(wallTemp,esum,Af);
             SumEVdotA[j]=wallTemp;
             Tl[cell2]=wallTemp;
           }
       }
     //second loop to add in the diffuse reflection
     for(int k=0;k<klen;k++)
       {
         Tkvol& kvol=_kspace.getkvol(k);
         const int numModes=kvol.getmodenum();
         for(int m=0;m<numModes;m++)
           {
             Tmode& mode=kvol.getmode(m);
             VectorT3 vg=mode.getv();
             Field& eField=mode.getfield();
             TArray& eArray=dynamic_cast<TArray&>(eField[_cells]);
             for(int j=0;j<neibcount;j++)
               {
                 const int f=_cellFaces(cell,j);
                 if(_BCfArray[f]==3)
                   {
                     int Fgid=findFgId(f);
                     const T refl=(*(_bcMap[Fgid]))["specifiedReflection"];
                     const T oneMinusRefl=1.-refl;
                     int cell2=_faceCells(f,1);
                     VectorT3 Af=_faceArea[f];
                     if(cell2==cell)
                       {
                         Af=Af*-1.;
                         cell2=_faceCells(f,0);
                       }
                     const T VdotA=Af[0]*vg[0]+Af[1]*vg[1]+Af[2]*vg[2];
                     if(VdotA<0)
                       eArray[cell2]+=mode.calce0(SumEVdotA[j])*oneMinusRefl;
                     else
                       eArray[cell2]+=mode.calce0(SumEVdotA[j])*oneMinusRefl;
                   }
               }
           }
       }
     */
   }
Member Data Documentation
template<class T> T COMETDiscretizer< T >::_aveResid private
Definition at line 2161 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETDiscretizer< T >::findResidFull(), and COMETDiscretizer< T >::getAveResid().
template<class T> const IntArray& COMETDiscretizer< T >::_BCArray private
Definition at line 2159 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
template<class T> const IntArray& COMETDiscretizer< T >::_BCfArray private
Definition at line 2160 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::correctInterface(), COMETDiscretizer< T >::updateGhostCoarse(), and COMETDiscretizer< T >::updateGhostFine().
template<class T> COMETBCMap& COMETDiscretizer< T >::_bcMap private
Definition at line 2158 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::updateGhostCoarse(), and COMETDiscretizer< T >::updateGhostFine().
template<class T> const VectorT3Array& COMETDiscretizer< T >::_cellCoords private
Definition at line 2155 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETConvectionFine(), and COMETDiscretizer< T >::updateGhostFine().
template<class T> const CRConnectivity& COMETDiscretizer< T >::_cellFaces private
Definition at line 2150 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::correctInterface(), COMETDiscretizer< T >::ScatterPhonons(), COMETDiscretizer< T >::updateGhostCoarse(), and COMETDiscretizer< T >::updateGhostFine().
template<class T> const StorageSite& COMETDiscretizer< T >::_cells private
Definition at line 2148 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::addFAS(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETShifted(), COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::Distribute(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETDiscretizer< T >::findResidFull(), COMETDiscretizer< T >::gatherResid(), COMETDiscretizer< T >::makeValueArray(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateeShifted(), and COMETDiscretizer< T >::updateGhostCoarse().
template<class T> const TArray& COMETDiscretizer< T >::_cellVolume private
Definition at line 2154 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETFullScatt(), COMETDiscretizer< T >::COMETShifted(), COMETDiscretizer< T >::COMETSource(), and COMETDiscretizer< T >::ScatterPhonons().
template<class T> TArray& COMETDiscretizer< T >::_e0Array private
Definition at line 2167 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::ScatterPhonons(), and COMETDiscretizer< T >::updatee0().
template<class T> TArray& COMETDiscretizer< T >::_eArray private
Definition at line 2166 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::Distribute(), COMETDiscretizer< T >::makeValueArray(), COMETDiscretizer< T >::scaledResid(), COMETDiscretizer< T >::ScatterPhonons(), COMETDiscretizer< T >::updateGhostCoarse(), and COMETDiscretizer< T >::updateGhostFine().
template<class T> const VectorT3Array& COMETDiscretizer< T >::_faceArea private
Definition at line 2153 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::ScatterPhonons(), COMETDiscretizer< T >::updateGhostCoarse(), and COMETDiscretizer< T >::updateGhostFine().
template<class T> const TArray& COMETDiscretizer< T >::_faceAreaMag private
Definition at line 2152 of file COMETDiscretizer.h.
template<class T> const CRConnectivity& COMETDiscretizer< T >::_faceCells private
Definition at line 2151 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::correctInterface(), COMETDiscretizer< T >::ScatterPhonons(), COMETDiscretizer< T >::updateGhostCoarse(), and COMETDiscretizer< T >::updateGhostFine().
template<class T> const StorageSite& COMETDiscretizer< T >::_faces private
Definition at line 2149 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETConvectionFine(), and COMETDiscretizer< T >::updateGhostFine().
template<class T> const FgTKClistMap& COMETDiscretizer< T >::_FaceToKSC private
Definition at line 2165 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), and COMETDiscretizer< T >::correctInterface().
template<class T> FaceToFg COMETDiscretizer< T >::_fgFinder private
Definition at line 2163 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::findFgId(), and COMETDiscretizer< T >::setfgFinder().
template<class T> const GeomFields& COMETDiscretizer< T >::_geomFields private
Definition at line 2147 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::updateGhostFine().
template<class T> Tkspace& COMETDiscretizer< T >::_kspace private
Definition at line 2157 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::addFAS(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETConvection(), COMETDiscretizer< T >::COMETConvectionCoarse(), COMETDiscretizer< T >::COMETConvectionFine(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETFullScatt(), COMETDiscretizer< T >::COMETShifted(), COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::COMETSource(), COMETDiscretizer< T >::correctInterface(), COMETDiscretizer< T >::Distribute(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETDiscretizer< T >::findResidFull(), COMETDiscretizer< T >::gatherResid(), COMETDiscretizer< T >::makeValueArray(), COMETDiscretizer< T >::scaledResid(), COMETDiscretizer< T >::ScatterPhonons(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateeShifted(), COMETDiscretizer< T >::updateGhostCoarse(), and COMETDiscretizer< T >::updateGhostFine().
template<class T> PhononMacro& COMETDiscretizer< T >::_macro private
Definition at line 2156 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::addFAS(), COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETEquilibrium(), COMETDiscretizer< T >::COMETShifted(), COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::Distribute(), COMETDiscretizer< T >::gatherResid(), COMETDiscretizer< T >::makeValueArray(), COMETDiscretizer< T >::updatee0(), COMETDiscretizer< T >::updateeShifted(), and COMETDiscretizer< T >::updateGhostCoarse().
template<class T> const Mesh& COMETDiscretizer< T >::_mesh private
Definition at line 2146 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::correctInterface(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::setfgFinder().
template<class T> COpts COMETDiscretizer< T >::_options private
Definition at line 2164 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), and COMETDiscretizer< T >::COMETSolveFull().
template<class T> TArray& COMETDiscretizer< T >::_resArray private
Definition at line 2168 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::Distribute().
template<class T> T COMETDiscretizer< T >::_residChange private
Definition at line 2162 of file COMETDiscretizer.h.
Referenced by COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETDiscretizer< T >::findResidFull(), and COMETDiscretizer< T >::getResidChange().
The documentation for this class was generated from the following file:
COMETDiscretizer.h