Memosa-FVM: DiagonalTensor< T, N > Class Template Reference
DiagonalTensor< T, N > Class Template Reference
#include <DiagonalTensor.h>
Public Types
typedef DiagonalTensor< T, N > This_T
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef NumTypeTraits< T >
::T_BuiltIn T_BuiltIn
Public Member Functions
DiagonalTensor ()
DiagonalTensor (const DiagonalTensor &o)
DiagonalTensor (const T &o)
T & operator[] (int n)
const T & operator[] (int n) const
void printFromC (ostream &os) const
DiagonalTensor & operator= (const T &o)
DiagonalTensor & operator= (const DiagonalTensor &o)
DiagonalTensor operator- ()
DiagonalTensor & operator+= (const DiagonalTensor &o)
DiagonalTensor & operator+= (const T s)
DiagonalTensor & operator-= (const DiagonalTensor &o)
DiagonalTensor & operator-= (const T s)
DiagonalTensor & operator/= (const T s)
DiagonalTensor & operator/= (const DiagonalTensor &o)
DiagonalTensor & operator*= (const T s)
DiagonalTensor & operator*= (const DiagonalTensor &o)
void zero ()
T mag2 () const
bool operator< (const double tolerance) const
Static Public Member Functions
static string getTypeName ()
static int getDimension ()
static void getShape (int *shp)
static int getDataSize ()
static void write (FILE *fp, const DiagonalTensor &x)
static DiagonalTensor getZero ()
static double doubleMeasure (const DiagonalTensor &x)
static DiagonalTensor getNegativeUnity ()
static DiagonalTensor getUnity ()
static void accumulateOneNorm (DiagonalTensor &sum, const DiagonalTensor &v)
static void accumulateDotProduct (DiagonalTensor &sum, const DiagonalTensor &v0, const DiagonalTensor &v1)
static void reduceSum (T_Scalar &sum, const This_T &x)
static void safeDivide (DiagonalTensor &x, const DiagonalTensor &y)
static void normalize (DiagonalTensor &x, const DiagonalTensor &y)
static void setMax (DiagonalTensor &x, const DiagonalTensor &y)
Private Attributes
T _data [N]
Detailed Description
template<class T, int N>
class DiagonalTensor< T, N >
Definition at line 14 of file DiagonalTensor.h.
Member Typedef Documentation
template<class T, int N> typedef NumTypeTraits<T>::T_BuiltIn DiagonalTensor< T, N >::T_BuiltIn
Definition at line 19 of file DiagonalTensor.h.
template<class T, int N> typedef NumTypeTraits<T>::T_Scalar DiagonalTensor< T, N >::T_Scalar
Definition at line 18 of file DiagonalTensor.h.
template<class T, int N> typedef DiagonalTensor<T,N> DiagonalTensor< T, N >::This_T
Definition at line 17 of file DiagonalTensor.h.
Constructor & Destructor Documentation
template<class T, int N> DiagonalTensor< T, N >::DiagonalTensor () inline
Definition at line 21 of file DiagonalTensor.h.
   {}
template<class T, int N> DiagonalTensor< T, N >::DiagonalTensor (const DiagonalTensor< T, N > & o) inline
Definition at line 24 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0; i<N; i++)
       _data[i] = o._data[i];
   }
template<class T, int N> DiagonalTensor< T, N >::DiagonalTensor (const T & o) inline
Definition at line 30 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0; i<N; i++)
       _data[i] = o;
   }
Member Function Documentation
template<class T, int N> static void DiagonalTensor< T, N >::accumulateDotProduct (DiagonalTensor< T, N > & sum, const DiagonalTensor< T, N > & v0, const DiagonalTensor< T, N > & v1) inline static
Definition at line 206 of file DiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::accumulateDotProduct(sum[i],v0[i],v1[i]);
   }
template<class T, int N> static void DiagonalTensor< T, N >::accumulateOneNorm (DiagonalTensor< T, N > & sum, const DiagonalTensor< T, N > & v) inline static
Definition at line 200 of file DiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::accumulateOneNorm(sum[i],v[i]);
   }
template<class T, int N> static double DiagonalTensor< T, N >::doubleMeasure (const DiagonalTensor< T, N > & x) inline static
Definition at line 174 of file DiagonalTensor.h.
   {
     double m=0;
     for (int i=0; i<N; i++)
       m += NumTypeTraits<T>::doubleMeasure(x[i]);
     return m;
   }
template<class T, int N> static int DiagonalTensor< T, N >::getDataSize () inline static
Definition at line 46 of file DiagonalTensor.h.
   {
     return N*NumTypeTraits<T>::getDataSize();
   }
template<class T, int N> static int DiagonalTensor< T, N >::getDimension () inline static
Definition at line 43 of file DiagonalTensor.h.
 {return 1;}
template<class T, int N> static DiagonalTensor DiagonalTensor< T, N >::getNegativeUnity () inline static
Definition at line 182 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     DiagonalTensor n;
     for(int i=0; i<N; i++)
       n._data[i] = NumTypeTraits<T>::getNegativeUnity();
     return n;
   }
template<class T, int N> static void DiagonalTensor< T, N >::getShape (int * shp) inline static
Definition at line 45 of file DiagonalTensor.h.
 { *shp = N;}
template<class T, int N> static string DiagonalTensor< T, N >::getTypeName () inline static
Definition at line 37 of file DiagonalTensor.h.
References intAsString().
   {
     return "DiagonalTensor<" + NumTypeTraits<T>::getTypeName() +
       "," + intAsString(N) +
       ">";
   }
template<class T, int N> static DiagonalTensor DiagonalTensor< T, N >::getUnity () inline static
Definition at line 191 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     DiagonalTensor n;
     for(int i=0; i<N; i++)
       n._data[i] = NumTypeTraits<T>::getUnity();
     return n;
   }
template<class T, int N> static DiagonalTensor DiagonalTensor< T, N >::getZero () inline static
Definition at line 167 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::zero().
   {
     DiagonalTensor z;
     z.zero();
     return z;
   }
template<class T, int N> T DiagonalTensor< T, N >::mag2 () const inline
Definition at line 154 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
Referenced by DiagonalTensor< T, N >::operator<().
   {
     T r(NumTypeTraits<T>::getZero());
     for(int i=0; i<N; i++)
       r+=_data[i]*_data[i];
     return r;
   }
template<class T, int N> static void DiagonalTensor< T, N >::normalize (DiagonalTensor< T, N > & x, const DiagonalTensor< T, N > & y) inline static
Definition at line 225 of file DiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::normalize(x[i],y[i]);
   }
template<class T, int N> DiagonalTensor& DiagonalTensor< T, N >::operator*= (const T s) inline
Definition at line 135 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] *= s;
     return *this;
   }
template<class T, int N> DiagonalTensor& DiagonalTensor< T, N >::operator*= (const DiagonalTensor< T, N > & o) inline
Definition at line 142 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] *= o[i];
     return *this;
   }
template<class T, int N> DiagonalTensor& DiagonalTensor< T, N >::operator+= (const DiagonalTensor< T, N > & o) inline
Definition at line 93 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] += o[i];
     return *this;
   }
template<class T, int N> DiagonalTensor& DiagonalTensor< T, N >::operator+= (const T s) inline
Definition at line 100 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] += s;
     return *this;
   }
template<class T, int N> DiagonalTensor DiagonalTensor< T, N >::operator- () inline
Definition at line 85 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     DiagonalTensor r;
     for(int i=0;i<N;i++)
       r[i]=-_data[i];
     return r;
   }
template<class T, int N> DiagonalTensor& DiagonalTensor< T, N >::operator-= (const DiagonalTensor< T, N > & o) inline
Definition at line 107 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] -= o[i];
     return *this;
   }
template<class T, int N> DiagonalTensor& DiagonalTensor< T, N >::operator-= (const T s) inline
Definition at line 114 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] -= s;
     return *this;
   }
template<class T, int N> DiagonalTensor& DiagonalTensor< T, N >::operator/= (const T s) inline
Definition at line 121 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] /= s;
     return *this;
   }
template<class T, int N> DiagonalTensor& DiagonalTensor< T, N >::operator/= (const DiagonalTensor< T, N > & o) inline
Definition at line 128 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] /= o[i];
     return *this;
   }
template<class T, int N> bool DiagonalTensor< T, N >::operator< (const double tolerance) const inline
Definition at line 162 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::mag2().
   {
     return mag2() < tolerance*tolerance;
   }
template<class T, int N> DiagonalTensor& DiagonalTensor< T, N >::operator= (const T & o) inline
Definition at line 71 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] = o;
     return *this;
   }
template<class T, int N> DiagonalTensor& DiagonalTensor< T, N >::operator= (const DiagonalTensor< T, N > & o) inline
Definition at line 78 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] = o[i];
     return *this;
   }
template<class T, int N> T& DiagonalTensor< T, N >::operator[] (int n) inline
Definition at line 51 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
 {return _data[n];}
template<class T, int N> const T& DiagonalTensor< T, N >::operator[] (int n) const inline
Definition at line 52 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
 {return _data[n];}
template<class T, int N> void DiagonalTensor< T, N >::printFromC (ostream & os) const inline
Definition at line 54 of file DiagonalTensor.h.
References DiagonalTensor< T, N >::_data.
Referenced by operator<<().
   {
     os << "[ " ;
     for(int i=0;i<N;i++)
       os << _data[i] << " " ;
     os << "]";
   }
template<class T, int N> static void DiagonalTensor< T, N >::reduceSum (T_Scalar & sum, const This_T & x) inline static
Definition at line 213 of file DiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::reduceSum(sum,x[i]);
   }
template<class T, int N> static void DiagonalTensor< T, N >::safeDivide (DiagonalTensor< T, N > & x, const DiagonalTensor< T, N > & y) inline static
Definition at line 219 of file DiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::safeDivide(x[i],y[i]);
   }
template<class T, int N> static void DiagonalTensor< T, N >::setMax (DiagonalTensor< T, N > & x, const DiagonalTensor< T, N > & y) inline static
Definition at line 231 of file DiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::setMax(x[i],y[i]);
   }
template<class T, int N> static void DiagonalTensor< T, N >::write (FILE * fp, const DiagonalTensor< T, N > & x) inline static
Definition at line 62 of file DiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
     {
         NumTypeTraits<T>::write(fp,x[i]);
         fprintf(fp, " ");
     }
   }
template<class T, int N> void DiagonalTensor< T, N >::zero () inline
Definition at line 149 of file DiagonalTensor.h.
Referenced by DiagonalTensor< T, N >::getZero().
   {
     for(int i=0;i<N;i++) _data[i] = NumTypeTraits<T>::getZero();
   }
Member Data Documentation
template<class T, int N> T DiagonalTensor< T, N >::_data[N] private
Definition at line 238 of file DiagonalTensor.h.
Referenced by DiagonalTensor< T, N >::DiagonalTensor(), DiagonalTensor< T, N >::getNegativeUnity(), DiagonalTensor< T, N >::getUnity(), DiagonalTensor< T, N >::mag2(), DiagonalTensor< T, N >::operator*=(), DiagonalTensor< T, N >::operator+=(), DiagonalTensor< T, N >::operator-(), DiagonalTensor< T, N >::operator-=(), DiagonalTensor< T, N >::operator/=(), DiagonalTensor< T, N >::operator=(), DiagonalTensor< T, N >::operator[](), and DiagonalTensor< T, N >::printFromC().
The documentation for this class was generated from the following file:
DiagonalTensor.h