Memosa-FVM: ElecDiagonalTensor< T, N > Class Template Reference
ElecDiagonalTensor< T, N > Class Template Reference
#include <ElecDiagonalTensor.h>
Public Types
enum { TN = 3*N+1 }
typedef ElecDiagonalTensor< T, N > This_T
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
typedef NumTypeTraits< T >
::T_BuiltIn T_BuiltIn
Public Member Functions
ElecDiagonalTensor ()
ElecDiagonalTensor (const ElecDiagonalTensor &o)
ElecDiagonalTensor (const T &o)
T & operator[] (int n)
const T & operator[] (int n) const
void printFromC (ostream &os) const
ElecDiagonalTensor & operator= (const T &o)
ElecDiagonalTensor & operator= (const ElecDiagonalTensor &o)
ElecDiagonalTensor & operator= (const ElecOffDiagonalTensor< T, N > &o)
ElecDiagonalTensor operator- ()
ElecDiagonalTensor & operator+= (const ElecDiagonalTensor &o)
ElecDiagonalTensor & operator+= (const ElecOffDiagonalTensor< T, N > &o)
ElecDiagonalTensor & operator+= (const T s)
ElecDiagonalTensor & operator-= (const ElecDiagonalTensor &o)
ElecDiagonalTensor & operator-= (const T s)
ElecDiagonalTensor & operator/= (const T s)
ElecDiagonalTensor & operator/= (const ElecDiagonalTensor &o)
ElecDiagonalTensor & operator*= (const T s)
ElecDiagonalTensor & operator*= (const ElecDiagonalTensor &o)
void zero ()
T mag2 () const
bool operator< (const double tolerance) const
Static Public Member Functions
static string getTypeName ()
static int getDimension ()
static void getShape (int *shp)
static int getDataSize ()
static void write (FILE *fp, const ElecDiagonalTensor &x)
static ElecDiagonalTensor getZero ()
static double doubleMeasure (const ElecDiagonalTensor &x)
static ElecDiagonalTensor getNegativeUnity ()
static ElecDiagonalTensor getUnity ()
static void accumulateOneNorm (ElecDiagonalTensor &sum, const ElecDiagonalTensor &v)
static void accumulateDotProduct (ElecDiagonalTensor &sum, const ElecDiagonalTensor &v0, const ElecDiagonalTensor &v1)
static void reduceSum (T_Scalar &sum, const This_T &x)
static void safeDivide (ElecDiagonalTensor &x, const ElecDiagonalTensor &y)
static void normalize (ElecDiagonalTensor &x, const ElecDiagonalTensor &y)
static void setMax (ElecDiagonalTensor &x, const ElecDiagonalTensor &y)
Private Attributes
T _data [3 *N+1]
Detailed Description
template<class T, int N>
class ElecDiagonalTensor< T, N >
Definition at line 35 of file ElecDiagonalTensor.h.
Member Typedef Documentation
template<class T, int N> typedef NumTypeTraits<T>::T_BuiltIn ElecDiagonalTensor< T, N >::T_BuiltIn
Definition at line 41 of file ElecDiagonalTensor.h.
template<class T, int N> typedef NumTypeTraits<T>::T_Scalar ElecDiagonalTensor< T, N >::T_Scalar
Definition at line 40 of file ElecDiagonalTensor.h.
template<class T, int N> typedef ElecDiagonalTensor<T,N> ElecDiagonalTensor< T, N >::This_T
Definition at line 39 of file ElecDiagonalTensor.h.
Member Enumeration Documentation
template<class T, int N> anonymous enum
Enumerator
TN
Definition at line 38 of file ElecDiagonalTensor.h.
 { TN = 3*N+1 } ;
Constructor & Destructor Documentation
template<class T, int N> ElecDiagonalTensor< T, N >::ElecDiagonalTensor () inline
Definition at line 43 of file ElecDiagonalTensor.h.
   {}
template<class T, int N> ElecDiagonalTensor< T, N >::ElecDiagonalTensor (const ElecDiagonalTensor< T, N > & o) inline
Definition at line 46 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
   {
     for(int i=0; i<TN; i++)
       _data[i] = o._data[i];
   }
template<class T, int N> ElecDiagonalTensor< T, N >::ElecDiagonalTensor (const T & o) inline
Definition at line 52 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
   {
     for(int i=0; i<N; i++)
       _data[i] = o;
     for(int i=N; i<TN; i++)
       _data[i] = 0;
   }
Member Function Documentation
template<class T, int N> static void ElecDiagonalTensor< T, N >::accumulateDotProduct (ElecDiagonalTensor< T, N > & sum, const ElecDiagonalTensor< T, N > & v0, const ElecDiagonalTensor< T, N > & v1) inline static
Definition at line 248 of file ElecDiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::accumulateDotProduct(sum[i],v0[i],v1[i]);
   }
template<class T, int N> static void ElecDiagonalTensor< T, N >::accumulateOneNorm (ElecDiagonalTensor< T, N > & sum, const ElecDiagonalTensor< T, N > & v) inline static
Definition at line 242 of file ElecDiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::accumulateOneNorm(sum[i],v[i]);
   }
template<class T, int N> static double ElecDiagonalTensor< T, N >::doubleMeasure (const ElecDiagonalTensor< T, N > & x) inline static
Definition at line 219 of file ElecDiagonalTensor.h.
   {
       return 0.0;
   }
template<class T, int N> static int ElecDiagonalTensor< T, N >::getDataSize () inline static
Definition at line 71 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::TN.
   {
     return TN*NumTypeTraits<T>::getDataSize();
   }
template<class T, int N> static int ElecDiagonalTensor< T, N >::getDimension () inline static
Definition at line 67 of file ElecDiagonalTensor.h.
 {return 1;}
template<class T, int N> static ElecDiagonalTensor ElecDiagonalTensor< T, N >::getNegativeUnity () inline static
Definition at line 224 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data.
   {
     ElecDiagonalTensor n;
     for(int i=0; i<N; i++)
       n._data[i] = NumTypeTraits<T>::getNegativeUnity();
     return n;
   }
template<class T, int N> static void ElecDiagonalTensor< T, N >::getShape (int * shp) inline static
Definition at line 69 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::TN.
 { *shp = TN;}
template<class T, int N> static string ElecDiagonalTensor< T, N >::getTypeName () inline static
Definition at line 60 of file ElecDiagonalTensor.h.
References intAsString().
   {
     return "ElecDiagonalTensor<" + NumTypeTraits<T>::getTypeName() +
       "," + intAsString(N) +
       ">";
   }
template<class T, int N> static ElecDiagonalTensor ElecDiagonalTensor< T, N >::getUnity () inline static
Definition at line 233 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data.
   {
     ElecDiagonalTensor n;
     for(int i=0; i<N; i++)
       n._data[i] = NumTypeTraits<T>::getUnity();
     return n;
   }
template<class T, int N> static ElecDiagonalTensor ElecDiagonalTensor< T, N >::getZero () inline static
Definition at line 212 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::zero().
   {
     ElecDiagonalTensor z;
     z.zero();
     return z;
   }
template<class T, int N> T ElecDiagonalTensor< T, N >::mag2 () const inline
Definition at line 199 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data.
Referenced by ElecDiagonalTensor< T, N >::operator<().
   {
     T r(NumTypeTraits<T>::getZero());
     for(int i=0; i<N; i++)
       r+=_data[i]*_data[i];
     return r;
   }
template<class T, int N> static void ElecDiagonalTensor< T, N >::normalize (ElecDiagonalTensor< T, N > & x, const ElecDiagonalTensor< T, N > & y) inline static
Definition at line 267 of file ElecDiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::normalize(x[i],y[i]);
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator*= (const T s) inline
Definition at line 180 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
   {
     throw CException("operator not defined for diag *= s");
     for(int i=0;i<TN;i++)
       _data[i] *= s;
     return *this;
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator*= (const ElecDiagonalTensor< T, N > & o) inline
Definition at line 189 of file ElecDiagonalTensor.h.
   {
     throw CException("no operator defined for *= diag");
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator+= (const ElecDiagonalTensor< T, N > & o) inline
Definition at line 129 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
   {
     for(int i=0;i<TN;i++)
       _data[i] += o[i];
     return *this;
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator+= (const ElecOffDiagonalTensor< T, N > & o) inline
Definition at line 137 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data.
   {
     _data[3*N] += o[N];
     return *this;
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator+= (const T s) inline
Definition at line 142 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] += s;
     _data[3*N] += s;
     return *this;
   }
template<class T, int N> ElecDiagonalTensor ElecDiagonalTensor< T, N >::operator- () inline
Definition at line 121 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
   {
     ElecDiagonalTensor r;
     for(int i=0;i<TN;i++)
       r[i]=-_data[i];
     return r;
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator-= (const ElecDiagonalTensor< T, N > & o) inline
Definition at line 150 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
   {
     for(int i=0;i<TN;i++)
       _data[i] -= o[i];
     return *this;
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator-= (const T s) inline
Definition at line 157 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data.
   {
     for(int i=0;i<N;i++)
       _data[i] -= s;
     _data[3*N] -= s;
     return *this;
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator/= (const T s) inline
Definition at line 165 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
   {
     throw CException("operator not defined for diag /= s");
     for(int i=0;i<TN;i++)
       _data[i] /= s;
     return *this;
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator/= (const ElecDiagonalTensor< T, N > & o) inline
Definition at line 174 of file ElecDiagonalTensor.h.
   {
     throw CException("no operator defined for /= diag");
   }
template<class T, int N> bool ElecDiagonalTensor< T, N >::operator< (const double tolerance) const inline
Definition at line 207 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::mag2().
   {
     return mag2() < tolerance*tolerance;
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator= (const T & o) inline
Definition at line 97 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
   {
     for(int i=0;i<N;i++)
       _data[i] = o;
    for(int i=N; i<TN; i++)
       _data[i] = 0;
     return *this;
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator= (const ElecDiagonalTensor< T, N > & o) inline
Definition at line 106 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
   {
     for(int i=0;i<TN;i++)
       _data[i] = o[i];
     return *this;
   }
template<class T, int N> ElecDiagonalTensor& ElecDiagonalTensor< T, N >::operator= (const ElecOffDiagonalTensor< T, N > & o) inline
Definition at line 113 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
   {
     for(int i=0;i<TN;i++)
       _data[i] = 0;
     _data[3*N] = o[N];
     return *this;
   }
template<class T, int N> T& ElecDiagonalTensor< T, N >::operator[] (int n) inline
Definition at line 76 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data.
 {return _data[n];}
template<class T, int N> const T& ElecDiagonalTensor< T, N >::operator[] (int n) const inline
Definition at line 78 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data.
 {return _data[n];}
template<class T, int N> void ElecDiagonalTensor< T, N >::printFromC (ostream & os) const inline
Definition at line 80 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::_data, and ElecDiagonalTensor< T, N >::TN.
Referenced by operator<<().
   {
     os << "[ " ;
     for(int i=0;i<TN;i++)
       os << _data[i] << " " ;
     os << "]";
   }
template<class T, int N> static void ElecDiagonalTensor< T, N >::reduceSum (T_Scalar & sum, const This_T & x) inline static
Definition at line 255 of file ElecDiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::reduceSum(sum,x[i]);
   }
template<class T, int N> static void ElecDiagonalTensor< T, N >::safeDivide (ElecDiagonalTensor< T, N > & x, const ElecDiagonalTensor< T, N > & y) inline static
Definition at line 261 of file ElecDiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::safeDivide(x[i],y[i]);
   }
template<class T, int N> static void ElecDiagonalTensor< T, N >::setMax (ElecDiagonalTensor< T, N > & x, const ElecDiagonalTensor< T, N > & y) inline static
Definition at line 273 of file ElecDiagonalTensor.h.
   {
     for(int i=0; i<N; i++)
       NumTypeTraits<T>::setMax(x[i],y[i]);
   }
template<class T, int N> static void ElecDiagonalTensor< T, N >::write (FILE * fp, const ElecDiagonalTensor< T, N > & x) inline static
Definition at line 88 of file ElecDiagonalTensor.h.
References ElecDiagonalTensor< T, N >::TN.
   {
     for(int i=0; i<TN; i++)
     {
         NumTypeTraits<T>::write(fp,x[i]);
         fprintf(fp, " ");
     }
   }
template<class T, int N> void ElecDiagonalTensor< T, N >::zero () inline
Definition at line 194 of file ElecDiagonalTensor.h.
Referenced by ElecDiagonalTensor< T, N >::getZero().
   {
     for(int i=0;i<TN;i++) _data[i] = NumTypeTraits<T>::getZero();
   }
Member Data Documentation
template<class T, int N> T ElecDiagonalTensor< T, N >::_data[3 *N+1] private
Definition at line 282 of file ElecDiagonalTensor.h.
Referenced by ElecDiagonalTensor< T, N >::ElecDiagonalTensor(), ElecDiagonalTensor< T, N >::getNegativeUnity(), ElecDiagonalTensor< T, N >::getUnity(), ElecDiagonalTensor< T, N >::mag2(), ElecDiagonalTensor< T, N >::operator*=(), ElecDiagonalTensor< T, N >::operator+=(), ElecDiagonalTensor< T, N >::operator-(), ElecDiagonalTensor< T, N >::operator-=(), ElecDiagonalTensor< T, N >::operator/=(), ElecDiagonalTensor< T, N >::operator=(), ElecDiagonalTensor< T, N >::operator[](), and ElecDiagonalTensor< T, N >::printFromC().
The documentation for this class was generated from the following file:
ElecDiagonalTensor.h