Memosa-FVM: OneDConduction< T > Class Template Reference
OneDConduction< T > Class Template Reference
#include <OneDConduction.h>
Public Member Functions
OneDConduction (const int nCells, const T &kConst)
void solve ()
boost::shared_ptr< Array< T > > getSolution ()
Private Attributes
const int _nCells
T _kConst
T _xL
T _xR
boost::shared_ptr< Array< T > > _x
Detailed Description
template<class T>
class OneDConduction< T >
Definition at line 26 of file OneDConduction.h.
Constructor & Destructor Documentation
template<class T> OneDConduction< T >::OneDConduction (const int nCells, const T & kConst) inline
Definition at line 29 of file OneDConduction.h.
                                                     :
     _nCells(nCells),
     _kConst(kConst),
     _xL(0),
     _xR(1),
     _x(new Array<T>(_nCells))
   {}
Member Function Documentation
template<class T> boost::shared_ptr<Array<T> > OneDConduction< T >::getSolution () inline
Definition at line 85 of file OneDConduction.h.
References OneDConduction< T >::_x.
Referenced by main().
 {return _x;}
template<class T> void OneDConduction< T >::solve () inline
Definition at line 37 of file OneDConduction.h.
References OneDConduction< T >::_kConst, OneDConduction< T >::_nCells, OneDConduction< T >::_x, OneDConduction< T >::_xL, OneDConduction< T >::_xR, and TDMA().
Referenced by main().
   {
     Array<T> ae(_nCells);
     Array<T> aw(_nCells);
     Array<T> ap(_nCells);
     Array<T> b(_nCells);
     ae = T(0.);
     aw = T(0.);
     ap = T(0.);
     b = T(0.);
     const T dx = T(1.0)/_nCells;
     for(int nf=0; nf<=_nCells; nf++)
     {
         int c0 = nf-1;
         int c1 = nf;
         const T xf =  dx*nf;
         const T kf = 1.0 + _kConst*xf;
         T coeff = kf/dx;
         if (nf==0)
         {
             coeff *= 2.;
             c0 = 0;
             b[c0] += coeff*_xL;
             ap[c0] -= coeff;
         }
         else if (nf==_nCells)
         {
             coeff *=2;
             b[c0] += coeff*_xR;
             ap[c0] -= coeff;
         }
         else
         {
             ae[c0] = coeff;
             aw[c1] = coeff;
             ap[c0] -= coeff;
             ap[c1] -= coeff;
         }
     }
     cout << " ae[0] " << ae[0] << endl;
     TDMA(ap,ae,aw,b,*_x);
   }
Member Data Documentation
template<class T> T OneDConduction< T >::_kConst private
Definition at line 89 of file OneDConduction.h.
Referenced by OneDConduction< T >::solve().
template<class T> const int OneDConduction< T >::_nCells private
Definition at line 88 of file OneDConduction.h.
Referenced by OneDConduction< T >::solve().
template<class T> boost::shared_ptr<Array<T> > OneDConduction< T >::_x private
Definition at line 92 of file OneDConduction.h.
Referenced by OneDConduction< T >::getSolution(), and OneDConduction< T >::solve().
template<class T> T OneDConduction< T >::_xL private
Definition at line 90 of file OneDConduction.h.
Referenced by OneDConduction< T >::solve().
template<class T> T OneDConduction< T >::_xR private
Definition at line 91 of file OneDConduction.h.
Referenced by OneDConduction< T >::solve().
The documentation for this class was generated from the following file:
OneDConduction.h