Memosa-FVM: SquareMatrix< T, N > Class Template Reference
SquareMatrix< T, N > Class Template Reference
#include <MatrixOperation.h>
Public Types
enum { NSQR = N*N }
typedef Array< T > TArray
typedef shared_ptr< TArray > TArrPtr
typedef Array< int > IntArray
typedef NumTypeTraits< T >
::T_Scalar T_Scalar
Public Types inherited from MatrixJML< T >
typedef Array< T > TArray
Public Member Functions
SquareMatrix ()
~SquareMatrix ()
SquareMatrix (const SquareMatrix &o)
SquareMatrix (const T &s)
T & operator() (int i, int j)
SquareMatrix & operator= (const T &s)
SquareMatrix & operator= (const SquareMatrix &o)
void print ()
SquareMatrix (const int N)
T & getElement (const int i, const int j)
T & operator() (const int i, const int j)
void zero ()
void Solve (TArray &bVec)
void makeCopy (SquareMatrix< T > &o)
void printMatrix ()
T getTraceAbs ()
void multiply (const TArray &x, TArray &b)
void testSolve ()
Public Member Functions inherited from MatrixJML< T >
MatrixJML ()
virtual ~MatrixJML ()
MatrixJML ()
virtual ~MatrixJML ()
Private Attributes
T _data [NSQR]
const int _order
const int _elements
bool _sorted
IntArray _pivotRows
TArray _maxVals
TArray _values
Detailed Description
template<class T, int N>
class SquareMatrix< T, N >
Definition at line 9 of file MatrixOperation.h.
Member Typedef Documentation
template<class T, int N> typedef Array<int> SquareMatrix< T, N >::IntArray
Definition at line 18 of file SquareMatrix.h.
template<class T, int N> typedef NumTypeTraits<T>::T_Scalar SquareMatrix< T, N >::T_Scalar
Definition at line 19 of file SquareMatrix.h.
template<class T, int N> typedef Array<T> SquareMatrix< T, N >::TArray
Definition at line 16 of file SquareMatrix.h.
template<class T, int N> typedef shared_ptr<TArray> SquareMatrix< T, N >::TArrPtr
Definition at line 17 of file SquareMatrix.h.
Member Enumeration Documentation
template<class T, int N> anonymous enum
Enumerator
NSQR
Definition at line 12 of file MatrixOperation.h.
 { NSQR = N*N };
Constructor & Destructor Documentation
template<class T, int N> SquareMatrix< T, N >::SquareMatrix () inline
Definition at line 14 of file MatrixOperation.h.
 {}
template<class T, int N> SquareMatrix< T, N >::~SquareMatrix () inline
Definition at line 15 of file MatrixOperation.h.
 {}
template<class T, int N> SquareMatrix< T, N >::SquareMatrix (const SquareMatrix< T, N > & o) inline
Definition at line 17 of file MatrixOperation.h.
References SquareMatrix< T, N >::_data, and SquareMatrix< T, N >::NSQR.
{
     for ( int i=0; i<NSQR; i++){
       _data[i] = o._data[i];
     }
   }
template<class T, int N> SquareMatrix< T, N >::SquareMatrix (const T & s) inline
Definition at line 23 of file MatrixOperation.h.
{
     for ( int i=0; i<N; i++){
       for ( int j=0; j<N; j++){
         if (i==j)
           (*this)(i,j) = s;
         else
           (*this)(i,j) = T(0);
       }
     }
   }
template<class T, int N> SquareMatrix< T, N >::SquareMatrix (const int N) inline
Definition at line 21 of file SquareMatrix.h.
References SquareMatrix< T, N >::_values, and Array< T >::zero().
                           :
   _order(N),
     _elements(N*N),
     _sorted(false),
     _pivotRows(N),
     _maxVals(N),
     _values(_elements)
     {_values.zero();}
Member Function Documentation
template<class T, int N> T& SquareMatrix< T, N >::getElement (const int i, const int j) inline virtual
Implements MatrixJML< T >.
Definition at line 30 of file SquareMatrix.h.
References SquareMatrix< T, N >::_order, and SquareMatrix< T, N >::_values.
 {return _values[(i-1)*_order+j-1];}
template<class T, int N> T SquareMatrix< T, N >::getTraceAbs () inline
Definition at line 186 of file SquareMatrix.h.
References SquareMatrix< T, N >::_order, and fabs().
Referenced by COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
   {
     T trace=0.;
     for(int i=1;i<_order+1;i++)
       trace+=fabs((*this)(i,i));
     return trace;
   }
template<class T, int N> void SquareMatrix< T, N >::makeCopy (SquareMatrix< T > & o) inline
Definition at line 164 of file SquareMatrix.h.
References SquareMatrix< T, N >::_maxVals, SquareMatrix< T, N >::_order, SquareMatrix< T, N >::_pivotRows, SquareMatrix< T, N >::_sorted, and SquareMatrix< T, N >::_values.
   {
     if(o._order!=this->_order)
       throw CException("Cannot copy matrices of different sizes!");
     o._sorted=this->_sorted;
     o._pivotRows=this->_pivotRows;
     o._maxVals=this->_maxVals;
     o._values=this->_values;
   }
template<class T, int N> void SquareMatrix< T, N >::multiply (const TArray & x, TArray & b) inline virtual
Implements MatrixJML< T >.
Definition at line 194 of file SquareMatrix.h.
References SquareMatrix< T, N >::_order, Array< T >::getLength(), and Array< T >::zero().
Referenced by COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), COMETDiscretizer< T >::findResidFull(), and SquareMatrix< T, N >::testSolve().
     {
       int lenx=x.getLength();
       int lenb=b.getLength();
       if(lenx==_order && lenb==_order)
         {
           b.zero();
           for(int i=1;i<_order+1;i++)
             for(int j=1;j<_order+1;j++)
               b[i-1]+=(*this)(i,j)*x[j-1];
         }
       else
         throw CException("Array length does not match matrix order!");
     }
template<class T, int N> T& SquareMatrix< T, N >::operator() (const int i, const int j) inline
Definition at line 31 of file SquareMatrix.h.
References SquareMatrix< T, N >::_order, and SquareMatrix< T, N >::_values.
 {return _values[(i-1)*_order+j-1];}
template<class T, int N> T& SquareMatrix< T, N >::operator() (int i, int j) inline
Definition at line 34 of file MatrixOperation.h.
References SquareMatrix< T, N >::_data.
 {return _data[i*N+j];}
template<class T, int N> SquareMatrix& SquareMatrix< T, N >::operator= (const T & s) inline
Definition at line 36 of file MatrixOperation.h.
   {
     for(int i=0; i<N; i++)
       for(int j=0; j<N; j++)
         (*this)(i,j) = (i==j) ? s : T(0.);
     return *this;
   }
template<class T, int N> SquareMatrix& SquareMatrix< T, N >::operator= (const SquareMatrix< T, N > & o) inline
Definition at line 44 of file MatrixOperation.h.
References SquareMatrix< T, N >::_data, and SquareMatrix< T, N >::NSQR.
   {
     for(int i=0;i<NSQR;i++)
       _data[i] = o._data[i];
     return *this;
   }
template<class T, int N> void SquareMatrix< T, N >::print () inline
Definition at line 51 of file MatrixOperation.h.
               {
     for(int i=0; i<N; i++){
       for (int j=0; j<N; j++)
         cout << (*this)(i,j) << " ";
       cout << endl;
     }
   }
template<class T, int N> void SquareMatrix< T, N >::printMatrix () inline
Definition at line 175 of file SquareMatrix.h.
References SquareMatrix< T, N >::_order.
   {
     for(int i=1;i<_order+1;i++)
       {
         for(int j=1;j<_order+1;j++)
           cout<<(*this)(i,j)<<" ";
         cout<<endl;
       }
     cout<<endl;
   }
template<class T, int N> void SquareMatrix< T, N >::Solve (TArray & bVec) inline
Definition at line 34 of file SquareMatrix.h.
References SquareMatrix< T, N >::_maxVals, SquareMatrix< T, N >::_order, SquareMatrix< T, N >::_pivotRows, SquareMatrix< T, N >::_sorted, and fabs().
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), and SquareMatrix< T, N >::testSolve().
   {//Gaussian Elimination w/ scaled partial pivoting
    //replaces bVec with the solution vector.
     SquareMatrix<T> LU(_order);
     (*this).makeCopy(LU);
     TArray bCpy(_order);
     IntArray l(_order);
     TArray s(_order);
     //find max values in each row if not done yet
     if(!_sorted)
       {
         for(int i=1;i<_order+1;i++)
           {
             l[i-1]=i;
             s[i-1]=fabs((*this)(i,1));
             for(int j=2;j<_order+1;j++)
               {
                 if(s[i-1]<fabs((*this)(i,j)))
                   s[i-1]=fabs((*this)(i,j));
               }
             if(s[i-1]==0)
               {
                 cout<<"Row: "<<i<<endl;
                 throw CException("Matrix has row of zeros!");
               }
           }
         _maxVals=s;
         //cout<<"Max vals:"<<endl;
         //for(int i=0;i<_order;i++)
         //cout<<s[i]<<endl;
       }
     //Forward sweep
     if(!_sorted)
       {
         for(int i=1;i<_order;i++)
           {
             T rmax=fabs((*this)(l[i-1],i)/s[l[i-1]-1]);
             //  cout<<"rmax: "<<rmax<<endl;
             int newMax=-1;
             for(int j=i+1;j<_order+1;j++)
               {
                 T r=fabs((*this)(l[j-1],i)/s[l[j-1]-1]);
                 if(r>rmax)
                   {
                     //cout<<"switching,i,j,r:"<<i<<","<<j<<","<<r<<endl;
                     //cout<<"factors "<<(*this)(l[j-1],i)<<" "<<s[l[j-1]-1]<<endl;
                     //cout<<"mapped j "<<l[j-1]<<endl;
                     rmax=r;
                     newMax=j;
                   }
               }
             if(newMax!=-1)
               {
                 int temp=l[i-1];
                 l[i-1]=newMax;
                 l[newMax-1]=temp;
               }
             for(int j=i+1;j<_order+1;j++)
               {
                 T factor=LU(l[j-1],i)/LU(l[i-1],i);
                 LU(l[j-1],i)=factor;
                 bVec[l[j-1]-1]-=factor*bVec[l[i-1]-1];
                 for(int k=i+1;k<_order+1;k++)
                   {
                     LU(l[j-1],k)-=LU(l[i-1],k)*factor;
                     T test=LU(l[j-1],k);
                     if(isnan(test)||isinf(test))
                       {
                         cout<<"Denom: "<<LU(l[i-1],i)<<endl;
                         cout<<"Num: "<<LU(l[j-1],i)<<endl;
                         cout<<"first: "<<LU(l[j-1],k)<<endl;
                         cout<<"second: "<<LU(l[i-1],k)<<endl;
                         cout<<"factor: "<<factor<<endl;
                         cout<<"test: "<<test<<endl;
                         throw CException("test is nan");
                       }
                   }
               }
           }
         _pivotRows=l;
         _sorted=true;
         //cout<<"Order"<<endl;
         //for(int i=0;i<_order;i++)
         //  cout<<_pivotRows[i]<<endl;
         //cout<<endl;
       }
     else
       {
         for(int i=1;i<_order;i++)
           {
             for(int j=i+1;j<_order+1;j++)
               {
                 T factor=LU(_pivotRows[j-1],i)/LU(_pivotRows[i-1],i);
                 LU(_pivotRows[j-1],i)=factor;
                 bVec[_pivotRows[j-1]-1]-=factor*bVec[_pivotRows[i-1]-1];
                 for(int k=i+1;k<_order+1;k++)
                   {
                     LU(_pivotRows[j-1],k)=LU(_pivotRows[j-1],k)
                       -LU(_pivotRows[i-1],k)*factor;
                   }
               }
           }
       }
     //back solve
     bVec[_pivotRows[_order-1]-1]=
       bVec[_pivotRows[_order-1]-1]/LU(_pivotRows[_order-1],_order);
     T sum=0.;
     for(int i=_order-1;i>0;i--)
       {
         sum=0.;
         for(int j=i+1;j<_order+1;j++)
           sum-=LU(_pivotRows[i-1],j)*bVec[_pivotRows[j-1]-1];
         bVec[_pivotRows[i-1]-1]+=sum;
         bVec[_pivotRows[i-1]-1]=bVec[_pivotRows[i-1]-1]/LU(_pivotRows[i-1],i);
       }
     //reorder
     bCpy=bVec;
     for(int i=0;i<_order;i++)
       bVec[i]=bCpy[_pivotRows[i]-1];
   }
template<class T, int N> void SquareMatrix< T, N >::testSolve () inline
Definition at line 209 of file SquareMatrix.h.
References SquareMatrix< T, N >::_order, SquareMatrix< T, N >::multiply(), and SquareMatrix< T, N >::Solve().
   {
     TArray x(_order);
     TArray b(_order);
     cout<<"Correct Solution:"<<endl;
     for(int i=0;i<_order;i++)
       {
         x[i]=rand()/1.e9;
         cout<<"x["<<i<<"]="<<x[i]<<endl;
       }
     multiply(x,b);
     cout<<"Before"<<endl;
     for(int i=0;i<_order;i++)
       cout<<"b["<<i<<"]="<<b[i]<<endl;
     Solve(b);
     cout<<"After"<<endl;
     for(int i=0;i<_order;i++)
       cout<<"b["<<i<<"]="<<b[i]<<endl;
     cout<<endl;
     cout<<"Error"<<endl;
     for(int i=0;i<_order;i++)
       cout<<"b["<<i<<"]="<<b[i]-x[i]<<endl;
     cout<<endl;
     throw CException("finished with test");
   }
template<class T, int N> void SquareMatrix< T, N >::zero () inline virtual
Implements MatrixJML< T >.
Definition at line 32 of file SquareMatrix.h.
References SquareMatrix< T, N >::_values, and Array< T >::zero().
Referenced by COMETDiscretizer< T >::COMETSolveCoarse(), COMETDiscretizer< T >::COMETSolveFine(), COMETDiscretizer< T >::COMETSolveFull(), COMETDiscretizer< T >::findResidCoarse(), COMETDiscretizer< T >::findResidFine(), and COMETDiscretizer< T >::findResidFull().
 {_values.zero();}
Member Data Documentation
template<class T, int N> T SquareMatrix< T, N >::_data[NSQR] private
Definition at line 62 of file MatrixOperation.h.
Referenced by SquareMatrix< T, N >::operator()(), SquareMatrix< T, N >::operator=(), and SquareMatrix< T, N >::SquareMatrix().
template<class T, int N> const int SquareMatrix< T, N >::_elements private
Definition at line 246 of file SquareMatrix.h.
template<class T, int N> TArray SquareMatrix< T, N >::_maxVals private
Definition at line 249 of file SquareMatrix.h.
Referenced by SquareMatrix< T, N >::makeCopy(), and SquareMatrix< T, N >::Solve().
template<class T, int N> const int SquareMatrix< T, N >::_order private
Definition at line 245 of file SquareMatrix.h.
Referenced by SquareMatrix< T, N >::getElement(), SquareMatrix< T, N >::getTraceAbs(), SquareMatrix< T, N >::makeCopy(), SquareMatrix< T, N >::multiply(), SquareMatrix< T, N >::operator()(), SquareMatrix< T, N >::printMatrix(), SquareMatrix< T, N >::Solve(), and SquareMatrix< T, N >::testSolve().
template<class T, int N> IntArray SquareMatrix< T, N >::_pivotRows private
Definition at line 248 of file SquareMatrix.h.
Referenced by SquareMatrix< T, N >::makeCopy(), and SquareMatrix< T, N >::Solve().
template<class T, int N> bool SquareMatrix< T, N >::_sorted private
Definition at line 247 of file SquareMatrix.h.
Referenced by SquareMatrix< T, N >::makeCopy(), and SquareMatrix< T, N >::Solve().
template<class T, int N> TArray SquareMatrix< T, N >::_values private
Definition at line 250 of file SquareMatrix.h.
Referenced by SquareMatrix< T, N >::getElement(), SquareMatrix< T, N >::makeCopy(), SquareMatrix< T, N >::operator()(), SquareMatrix< T, N >::SquareMatrix(), and SquareMatrix< T, N >::zero().
The documentation for this class was generated from the following files:
MatrixOperation.h
SquareMatrix.h