Memosa-FVM: IContainer Class Reference
IContainer Class Reference abstract
#include <IContainer.h>
Public Member Functions
IContainer ()
virtual ~IContainer ()
virtual void zero ()=0
IContainer & operator= (const IContainer &oc)
virtual shared_ptr< IContainer > newCopy () const =0
virtual shared_ptr< IContainer > newClone () const =0
virtual void copyFrom (const IContainer &oc)=0
Private Member Functions
IContainer (const IContainer &)
Detailed Description
Definition at line 12 of file IContainer.h.
Constructor & Destructor Documentation
IContainer::IContainer () inline
Definition at line 16 of file IContainer.h.
 {}
virtual IContainer::~IContainer () inline virtual
Definition at line 17 of file IContainer.h.
 {}
IContainer::IContainer (const IContainer &) private
Member Function Documentation
virtual void IContainer::copyFrom (const IContainer & oc) pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, Array< Vector< int, 2 > >, ArrayBase, MultiField, and Field.
Referenced by operator=().
virtual shared_ptr<IContainer> IContainer::newClone () const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, Array< Vector< int, 2 > >, MultiField, and Field.
Referenced by MultiField::newClone().
virtual shared_ptr<IContainer> IContainer::newCopy () const pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, Array< Vector< int, 2 > >, MultiField, and Field.
Referenced by MultiField::newCopy(), and MultiField::reduceSum().
IContainer& IContainer::operator= (const IContainer & oc) inline
Definition at line 25 of file IContainer.h.
References copyFrom().
   {
     copyFrom(oc);
     return *this;
   }
virtual void IContainer::zero () pure virtual
Implemented in Array< T >, Array< Vector< double, 3 > >, Array< VectorTranspose< X, K > >, Array< double >, Array< int >, Array< Vector< T, 3 > >, Array< Vector< T_Scalar, 3 > >, Array< X >, Array< Vector< X, K > >, Array< OffDiag >, Array< bool >, Array< Diag >, Array< Coeff >, Array< Vector< int, 2 > >, MultiField, and Field.
Referenced by MultiFieldMatrix::multiply(), and CRMatrixTranspose< T_Coeff, X, B >::multiply().
The documentation for this class was generated from the following file:
IContainer.h