Memosa-FVM: MatrixJML< T > Class Template Reference
MatrixJML< T > Class Template Reference abstract
#include <MatrixJML.h>
Public Types
typedef Array< T > TArray
Public Member Functions
MatrixJML ()
virtual ~MatrixJML ()
virtual T & getElement (const int i, const int j)=0
virtual void zero ()=0
MatrixJML ()
virtual ~MatrixJML ()
virtual T & getElement (const int i, const int j)=0
virtual void zero ()=0
virtual void multiply (const TArray &x, TArray &b)=0
Detailed Description
template<class T>
class MatrixJML< T >
Definition at line 9 of file esbgkbase/MatrixJML.h.
Member Typedef Documentation
template<class T > typedef Array<T> MatrixJML< T >::TArray
Definition at line 15 of file phononbase/MatrixJML.h.
Constructor & Destructor Documentation
template<class T > MatrixJML< T >::MatrixJML () inline
Definition at line 13 of file esbgkbase/MatrixJML.h.
 {}
template<class T > virtual MatrixJML< T >::~MatrixJML () inline virtual
Definition at line 14 of file esbgkbase/MatrixJML.h.
 {}
template<class T > MatrixJML< T >::MatrixJML () inline
Definition at line 17 of file phononbase/MatrixJML.h.
 {}
template<class T > virtual MatrixJML< T >::~MatrixJML () inline virtual
Definition at line 18 of file phononbase/MatrixJML.h.
 {}
Member Function Documentation
template<class T > virtual T& MatrixJML< T >::getElement (const int i, const int j) pure virtual
Implemented in ArrowHeadMatrix< X, K >, ArrowHeadMatrix< X, K >, CometMatrix< T >, SquareMatrixESBGK< T >, and SquareMatrix< T, N >.
Referenced by COMETDiscretizer< T >::COMETCollision(), COMETDiscretizer< T >::COMETEquilibrium(), and COMETDiscretizer< T >::COMETShifted().
template<class T > virtual T& MatrixJML< T >::getElement (const int i, const int j) pure virtual
Implemented in ArrowHeadMatrix< X, K >, ArrowHeadMatrix< X, K >, CometMatrix< T >, SquareMatrixESBGK< T >, and SquareMatrix< T, N >.
template<class T > virtual void MatrixJML< T >::multiply (const TArray & x, TArray & b) pure virtual
Implemented in ArrowHeadMatrix< X, K >, and SquareMatrix< T, N >.
template<class T > virtual void MatrixJML< T >::zero () pure virtual
Implemented in ArrowHeadMatrix< X, K >, CometMatrix< T >, ArrowHeadMatrix< X, K >, SquareMatrixESBGK< T >, and SquareMatrix< T, N >.
template<class T > virtual void MatrixJML< T >::zero () pure virtual
Implemented in ArrowHeadMatrix< X, K >, CometMatrix< T >, ArrowHeadMatrix< X, K >, SquareMatrixESBGK< T >, and SquareMatrix< T, N >.
The documentation for this class was generated from the following file:
esbgkbase/MatrixJML.h