Memosa-FVM: CRMatrix.h File Reference
CRMatrix.h File Reference
#include "Matrix.h"
#include "CRConnectivity.h"
#include "Array.h"
#include "StorageSite.h"
#include "LinearSystemMerger.h"
#include "SpikeStorage.h"
#include "SpikeMatrix.h"
#include <set>
#include "Vector.h"
#include "DiagonalTensor.h"
Classes
class CRMatrix< T_Diag, T_OffDiag, X >
class CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler
struct MatrixTraitHelper< T >
struct MatrixTraitHelper< Vector< T, N > >
Functions
template<class X >
X DiagToOffDiag (const X &x)
template<class T_Diag , class T_OffDiag >
void setFlatCoeffs (Array< double > &flatCoeffs, const CRConnectivity &flatConnectivity, const Array< T_Diag > &diag, const Array< T_OffDiag > &offDiag, const CRConnectivity &connectivity)
void setFlatCoeffs (Array< double > &flatCoeffs, const CRConnectivity &flatConnectivity, Array< double > &diag, Array< double > &offDiag, const CRConnectivity &connectivity)
Function Documentation
template<class X > X DiagToOffDiag (const X & x)
Definition at line 25 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::createScatterGatherValuesCRMtrxBuffer(), and CRMatrix< T_Diag, T_OffDiag, X >::eliminateRow().
 {
   return x;
 }
template<class T_Diag , class T_OffDiag > void setFlatCoeffs (Array< double > & flatCoeffs, const CRConnectivity & flatConnectivity, const Array< T_Diag > & diag, const Array< T_OffDiag > & offDiag, const CRConnectivity & connectivity)
Definition at line 37 of file CRMatrix.h.
Referenced by CRMatrix< T_Diag, T_OffDiag, X >::setFlatMatrix().
 {
   throw CException("not implemented");
 }
void setFlatCoeffs (Array< double > & flatCoeffs, const CRConnectivity & flatConnectivity, Array< double > & diag, Array< double > & offDiag, const CRConnectivity & connectivity)
Definition at line 47 of file CRMatrix.h.
References CRConnectivity::getCoeffPosition(), CRConnectivity::getCol(), CRConnectivity::getRow(), and CRConnectivity::getRowDim().
 {
     const Array<int>& myRow = connectivity.getRow();
     const Array<int>& myCol = connectivity.getCol();
     const int rowDim = connectivity.getRowDim();
     for(int i=0; i<rowDim; i++)
     {
         const int fp = flatConnectivity.getCoeffPosition(i,i);
         flatCoeffs[fp] = diag[i];
         for(int jp=myRow[i]; jp<myRow[i+1]; jp++)
         {
             const int j = myCol[jp];
             // the flat matrix uses compressed col format so swap i,j
             const int fp = flatConnectivity.getCoeffPosition(j,i);
             flatCoeffs[fp] = offDiag[jp];
         }
     }
 }