Memosa-FVM: DiffusionDiscretization.h File Reference
DiffusionDiscretization.h File Reference
#include "CRMatrix.h"
#include "Field.h"
#include "MultiField.h"
#include "MultiFieldMatrix.h"
#include "Mesh.h"
#include "Discretization.h"
#include "StorageSite.h"
#include "DiagonalMatrix.h"
#include "Gradient.h"
#include "DiagonalTensor.h"
Classes
class DiffusionDiscretization< X, Diag, OffDiag >
Functions
template<class T >
T harmonicAverage (const T &x0, const T &x1)
Function Documentation
template<class T > T harmonicAverage (const T & x0, const T & x1) inline
Definition at line 20 of file DiffusionDiscretization.h.
Referenced by LinearizeDielectric< X, Diag, OffDiag >::discretize(), ElecDiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryElectricDiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), and PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces().
 {
   const T sum = x0+x1;
   if (x0+x1 != NumTypeTraits<T>::getZero())
     return 2.0*x0*x1/sum;
   else
     return sum;
 }