Memosa-FVM: FluxLimiters.h File Reference
FluxLimiters.h File Reference
#include <math.h>
Classes
struct minModLim
struct vanLeer
struct superbee
struct vanAlbada1
struct ospre
Functions
template<class T , class LimitFunc >
void computeLimitCoeff (T &lc, const T x, const T &dx, const T &min, const T &max, const LimitFunc &f)
template<class T , class LimitFunc >
void computeLimitCoeff2 (T &lc, const T x, const T &dx, const T &min, const T &max, const LimitFunc &f)
Function Documentation
template<class T , class LimitFunc > void computeLimitCoeff (T & lc, const T x, const T & dx, const T & min, const T & max, const LimitFunc & f)
Definition at line 72 of file FluxLimiters.h.
Referenced by COMETBoundaryConditions< X, Diag, OffDiag >::applyPressureInletBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyRealWallBC(), COMETBoundaryConditions< X, Diag, OffDiag >::applyZeroGradientBC(), COMETESBGKDiscretizer< T >::COMETConvectionFine(), and COMETESBGKDiscretizer< T >::setBoundaryValFine().
 {
   T thislc = NumTypeTraits<T>::getUnity();
   if (dx>0)
     thislc = f(dx,max-x);
   else
     thislc = f(-dx,x-min);
   if (thislc < lc)
     lc = thislc;
 };
template<class T , class LimitFunc > void computeLimitCoeff2 (T & lc, const T x, const T & dx, const T & min, const T & max, const LimitFunc & f)
Definition at line 85 of file FluxLimiters.h.
Referenced by COMETDiscretizer< T >::COMETConvectionFine(), and COMETDiscretizer< T >::updateGhostFine().
 {
   T thislc = NumTypeTraits<T>::getUnity();
   if (dx>0)
     thislc = f(dx/(max-x));
   else
     thislc = f(-dx/(x-min));
   if (thislc < lc)
     lc = thislc;
 };