var hierarchy =
[
    [ "AABB", "classAABB.html", null ],
    [ "Array2D< T >", "classArray2D.html", null ],
    [ "Array2D< Diag >", "classArray2D.html", null ],
    [ "ArrayScalarTraits< T >", "structArrayScalarTraits.html", null ],
    [ "ArrayScalarTraits< double >", "structArrayScalarTraits_3_01double_01_4.html", null ],
    [ "ArrayScalarTraits< float >", "structArrayScalarTraits_3_01float_01_4.html", null ],
    [ "ArrayScalarTraits< PC< ORDER, DIM > >", "structArrayScalarTraits_3_01PC_3_01ORDER_00_01DIM_01_4_01_4.html", null ],
    [ "ArrayScalarTraits< Vector< T, N > >", "structArrayScalarTraits_3_01Vector_3_01T_00_01N_01_4_01_4.html", null ],
    [ "ArrayWriter", "classArrayWriter.html", [
      [ "ScalarArrayWriter< T >", "classScalarArrayWriter.html", null ],
      [ "VectorArrayWriter< T, N >", "classVectorArrayWriter.html", null ]
    ] ],
    [ "BaseGenericBCS< X, Diag, OffDiag >", "classBaseGenericBCS.html", [
      [ "GenericBCS< X, Diag, OffDiag >", "classGenericBCS.html", null ]
    ] ],
    [ "BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >", "classBaseGenericBCS.html", [
      [ "GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >", "classGenericBCS_3_01Vector_3_01T_00_01N_01_4_00_01DiagonalTensor_3_01T_00_01N_01_4_00_01DiagonalTensor_3_01T_00_01N_01_4_01_4.html", null ]
    ] ],
    [ "BaseGenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >", "classBaseGenericBCS.html", [
      [ "GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >", "classGenericBCS_3_01Vector_3_01T_00_01N_01_4_00_01DiagonalTensor_3_01T_00_01N_01_4_00_01T_01_4.html", null ]
    ] ],
    [ "BaseGenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >", "classBaseGenericBCS.html", [
      [ "GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >", "classGenericBCS_3_01Vector_3_01T_00_01N_01_4_00_01SquareTensor_3_01T_00_01N_01_4_00_01SquareTensor_3_01T_00_01N_01_4_01_4.html", null ]
    ] ],
    [ "BaseGenericKineticBCS< X, Diag, OffDiag >", "classBaseGenericKineticBCS.html", null ],
    [ "BaseGenericPhononBCS< X, Diag, OffDiag >", "classBaseGenericPhononBCS.html", null ],
    [ "BatteryFixInterfaceGhost< X, Diag, OffDiag >", "classBatteryFixInterfaceGhost.html", null ],
    [ "BatteryLinearizePotentialInterface< X, Diag, OffDiag >", "classBatteryLinearizePotentialInterface.html", null ],
    [ "BatteryLinearizeSpeciesInterface< X, Diag, OffDiag >", "classBatteryLinearizeSpeciesInterface.html", null ],
    [ "BatteryLinearizeThermalInterface< X, Diag, OffDiag >", "classBatteryLinearizeThermalInterface.html", null ],
    [ "BatteryModelFields", "structBatteryModelFields.html", null ],
    [ "BatteryPC_BCS< X, Diag, OffDiag >", "classBatteryPC__BCS.html", null ],
    [ "BatteryPCLinearizeInterface_BV< X, Diag, OffDiag, otherMeshDiag >", "classBatteryPCLinearizeInterface__BV.html", null ],
    [ "BatterySpeciesFields", "structBatterySpeciesFields.html", null ],
    [ "Octree::Bounds", "structOctree_1_1Bounds.html", null ],
    [ "Cell< CellTrait >", "classCell.html", null ],
    [ "COMETBoundary< T >", "classCOMETBoundary.html", null ],
    [ "COMETBoundaryConditions< X, Diag, OffDiag >", "classCOMETBoundaryConditions.html", null ],
    [ "COMETDiscretizer< T >", "classCOMETDiscretizer.html", null ],
    [ "COMETESBGKDiscretizer< T >", "classCOMETESBGKDiscretizer.html", null ],
    [ "COMETIC< T >", "structCOMETIC.html", null ],
    [ "COMETInterface< T >", "classCOMETInterface.html", null ],
    [ "ConstAsArray< T >", "classConstAsArray.html", null ],
    [ "Construct_coord_iterator", "structConstruct__coord__iterator.html", null ],
    [ "ContactFields", "structContactFields.html", null ],
    [ "CRConnectivity", "classCRConnectivity.html", null ],
    [ "DefaultLimiter", "structDefaultLimiter.html", null ],
    [ "DensityOfStates< T >", "classDensityOfStates.html", null ],
    [ "DiagonalTensor< T, N >", "classDiagonalTensor.html", null ],
    [ "Discretization", "classDiscretization.html", [
      [ "BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >", "classBatteryBinaryElectrolyteDiscretization.html", null ],
      [ "BatteryElectricDiffusionDiscretization< X, Diag, OffDiag >", "classBatteryElectricDiffusionDiscretization.html", null ],
      [ "BatteryPCBinaryElectrolyteDiscretization< X, Diag, OffDiag >", "classBatteryPCBinaryElectrolyteDiscretization.html", null ],
      [ "BatteryPCDiffusionDiscretization< X, Diag, OffDiag >", "classBatteryPCDiffusionDiscretization.html", null ],
      [ "BatteryPCHeatSourceDiscretization< X >", "classBatteryPCHeatSourceDiscretization.html", null ],
      [ "BatteryPCTimeDerivativeDiscretization< X, Diag, OffDiag >", "classBatteryPCTimeDerivativeDiscretization.html", null ],
      [ "CaptureDiscretization< X, Diag, OffDiag >", "classCaptureDiscretization.html", null ],
      [ "CollisionTermDiscretization< X, Diag, OffDiag >", "classCollisionTermDiscretization.html", null ],
      [ "ConvectionDiscretization< X, Diag, OffDiag >", "classConvectionDiscretization.html", null ],
      [ "ConvectionDiscretization_Kmodel< X, Diag, OffDiag >", "classConvectionDiscretization__Kmodel.html", null ],
      [ "DiffusionDiscretization< X, Diag, OffDiag >", "classDiffusionDiscretization.html", null ],
      [ "DriftDiscretization< X, Diag, OffDiag >", "classDriftDiscretization.html", null ],
      [ "ElecDiffusionDiscretization< X, Diag, OffDiag >", "classElecDiffusionDiscretization.html", null ],
      [ "EmissionDiscretization< X, Diag, OffDiag >", "classEmissionDiscretization.html", null ],
      [ "GenericIBDiscretization< X, Diag, OffDiag >", "classGenericIBDiscretization.html", null ],
      [ "GenericKineticIBDiscretization< X, Diag, OffDiag >", "classGenericKineticIBDiscretization.html", null ],
      [ "IbmDiscretization< X, Diag, OffDiag >", "classIbmDiscretization.html", null ],
      [ "InjectionDiscretization< X, Diag, OffDiag >", "classInjectionDiscretization.html", null ],
      [ "MomentumPressureGradientDiscretization< X >", "classMomentumPressureGradientDiscretization.html", null ],
      [ "PhononCollisionDiscretization< X, Diag, OffDiag >", "classPhononCollisionDiscretization.html", null ],
      [ "PhononConvectionDiscretization< X, Diag, OffDiag >", "classPhononConvectionDiscretization.html", null ],
      [ "PlateSourceDiscretization< T, Diag, OffDiag >", "classPlateSourceDiscretization.html", null ],
      [ "SourceDiscretization< X >", "classSourceDiscretization.html", null ],
      [ "SourceDiscretizationdissi< X, Diag, OffDiag >", "classSourceDiscretizationdissi.html", null ],
      [ "SourceDiscretizationene< X >", "classSourceDiscretizationene.html", null ],
      [ "SourceDiscretizationforFracture< T, Diag, OffDiag >", "classSourceDiscretizationforFracture.html", null ],
      [ "StructurePlasticDiscretization< T, Diag, OffDiag >", "classStructurePlasticDiscretization.html", null ],
      [ "StructureSourceDiscretization< T, Diag, OffDiag >", "classStructureSourceDiscretization.html", null ],
      [ "TimeDerivativeDiscretization< X, Diag, OffDiag >", "classTimeDerivativeDiscretization.html", null ],
      [ "TimeDerivativeDiscretization_Kmodel< X, Diag, OffDiag >", "classTimeDerivativeDiscretization__Kmodel.html", null ],
      [ "TimeDerivativePlateDiscretization< X, Diag, OffDiag >", "classTimeDerivativePlateDiscretization.html", null ],
      [ "TimeDerivativeStructureDiscretization< X, Diag, OffDiag >", "classTimeDerivativeStructureDiscretization.html", null ],
      [ "TrapBandTunnelingDiscretization< X, Diag, OffDiag >", "classTrapBandTunnelingDiscretization.html", null ],
      [ "TunnelingDiscretization< X, Diag, OffDiag >", "classTunnelingDiscretization.html", null ],
      [ "Underrelaxer< X, Diag, OffDiag >", "classUnderrelaxer.html", null ],
      [ "WallDiscretization< X, Diag, OffDiag >", "classWallDiscretization.html", null ]
    ] ],
    [ "Distance", "structDistance.html", null ],
    [ "DistFunctFields< T >", "classDistFunctFields.html", null ],
    [ "DistFunctFields< X >", "classDistFunctFields.html", null ],
    [ "doubleIntStruct", "structdoubleIntStruct.html", null ],
    [ "ElecDiagonalTensor< T, N >", "classElecDiagonalTensor.html", null ],
    [ "ElecOffDiagonalTensor< T, N >", "classElecOffDiagonalTensor.html", null ],
    [ "ElectricFields", "structElectricFields.html", null ],
    [ "FaceGroup", "structFaceGroup.html", null ],
    [ "Factorial< N >", "structFactorial.html", null ],
    [ "Factorial< 0 >", "structFactorial_3_010_01_4.html", null ],
    [ "FieldLabel", "classFieldLabel.html", null ],
    [ "FloatVal< T >", "structFloatVal.html", null ],
    [ "FloatValEvaluator< T >", "classFloatValEvaluator.html", null ],
    [ "FloatValEvaluator< Vector< T, 3 > >", "classFloatValEvaluator_3_01Vector_3_01T_00_013_01_4_01_4.html", null ],
    [ "FlowFields", "structFlowFields.html", null ],
    [ "FluentDataExporter< T >", "classFluentDataExporter.html", null ],
    [ "FluentFacePairs", "structFluentFacePairs.html", null ],
    [ "FluentZone", "structFluentZone.html", [
      [ "FluentCellZone", "structFluentCellZone.html", null ],
      [ "FluentFaceZone", "structFluentFaceZone.html", null ]
    ] ],
    [ "FractureFields", "structFractureFields.html", null ],
    [ "FVMParticles", "classFVMParticles.html", null ],
    [ "GeomFields", "structGeomFields.html", null ],
    [ "GlobalFields", "classGlobalFields.html", null ],
    [ "Gradient< T >", "classGradient.html", null ],
    [ "GradientMatrixBase", "classGradientMatrixBase.html", [
      [ "GradientMatrix< T_Scalar >", "classGradientMatrix.html", null ]
    ] ],
    [ "Grid", "classGrid.html", null ],
    [ "Hex", "structHex.html", null ],
    [ "IBManager", "classIBManager.html", null ],
    [ "IContainer", "classIContainer.html", [
      [ "ArrayBase", "classArrayBase.html", [
        [ "Array< T >", "classArray.html", null ],
        [ "Array< bool >", "classArray.html", null ],
        [ "Array< Coeff >", "classArray.html", null ],
        [ "Array< Diag >", "classArray.html", null ],
        [ "Array< double >", "classArray.html", null ],
        [ "Array< int >", "classArray.html", null ],
        [ "Array< OffDiag >", "classArray.html", null ],
        [ "Array< Vector< double, 3 > >", "classArray.html", null ],
        [ "Array< Vector< int, 2 > >", "classArray.html", null ],
        [ "Array< Vector< T, 3 > >", "classArray.html", null ],
        [ "Array< Vector< T_Scalar, 3 > >", "classArray.html", null ],
        [ "Array< Vector< X, K > >", "classArray.html", null ],
        [ "Array< VectorTranspose< X, K > >", "classArray.html", null ],
        [ "Array< X >", "classArray.html", null ]
      ] ],
      [ "Field", "classField.html", null ],
      [ "MultiField", "classMultiField.html", null ]
    ] ],
    [ "ThermalModel< T >::Impl", "classThermalModel_1_1Impl.html", null ],
    [ "VacancyModel< T >::Impl", "classVacancyModel_1_1Impl.html", null ],
    [ "ContactModel< T >::Impl", "classContactModel_1_1Impl.html", null ],
    [ "IdealGasDensityModel< T >::Impl", "classIdealGasDensityModel_1_1Impl.html", null ],
    [ "KeModel< T >::Impl", "classKeModel_1_1Impl.html", null ],
    [ "ElectricModel< T >::Impl", "classElectricModel_1_1Impl.html", null ],
    [ "PlateModel< T >::Impl", "classPlateModel_1_1Impl.html", null ],
    [ "FlowModel< T >::Impl", "classFlowModel_1_1Impl.html", null ],
    [ "RosselandModel< T >::Impl", "classRosselandModel_1_1Impl.html", null ],
    [ "BatteryModel< T >::Impl", "classBatteryModel_1_1Impl.html", null ],
    [ "SpeciesModel< T >::Impl", "classSpeciesModel_1_1Impl.html", null ],
    [ "FractureModel< T >::Impl", "classFractureModel_1_1Impl.html", null ],
    [ "StructureModel< T >::Impl", "classStructureModel_1_1Impl.html", null ],
    [ "Initializer< X, T_iterator >", "classInitializer.html", null ],
    [ "KeFields", "structKeFields.html", null ],
    [ "CGAL::Kernel_traits< MyPoint >::Kernel", "structCGAL_1_1Kernel__traits_3_01MyPoint_01_4_1_1Kernel.html", null ],
    [ "CGAL::Kernel_traits< MyPoint >", "structCGAL_1_1Kernel__traits_3_01MyPoint_01_4.html", null ],
    [ "KineticBoundaryConditions< X, Diag, OffDiag >", "classKineticBoundaryConditions.html", null ],
    [ "KSConnectivity< T >", "classKSConnectivity.html", null ],
    [ "KSearchTree", "classKSearchTree.html", null ],
    [ "Kspace< T >", "classKspace.html", null ],
    [ "kvol< T >", "classkvol.html", null ],
    [ "LinearizeDielectric< X, Diag, OffDiag >", "classLinearizeDielectric.html", null ],
    [ "LinearizeInterfaceJump< X, Diag, OffDiag >", "classLinearizeInterfaceJump.html", null ],
    [ "LinearizeInterfaceJumpUnconnected< X, Diag, OffDiag >", "classLinearizeInterfaceJumpUnconnected.html", null ],
    [ "LinearizePotentialInterface< X, Diag, OffDiag >", "classLinearizePotentialInterface.html", null ],
    [ "Linearizer", "classLinearizer.html", null ],
    [ "LinearizeSpeciesInterface< X, Diag, OffDiag >", "classLinearizeSpeciesInterface.html", null ],
    [ "LinearSolver", "classLinearSolver.html", [
      [ "AMG", "classAMG.html", null ],
      [ "BCGStab", "classBCGStab.html", null ],
      [ "CG", "classCG.html", null ],
      [ "DirectSolver", "classDirectSolver.html", null ],
      [ "ILU0Solver", "classILU0Solver.html", null ],
      [ "JacobiSolver", "classJacobiSolver.html", null ],
      [ "SpikeSolver", "classSpikeSolver.html", null ]
    ] ],
    [ "LinearSystem", "classLinearSystem.html", null ],
    [ "MacroFields", "structMacroFields.html", null ],
    [ "map", null, [
      [ "FloatVarDict< T >", "classFloatVarDict.html", [
        [ "BatteryModelOptions< T >", "structBatteryModelOptions.html", null ],
        [ "BatteryPotentialBC< T >", "structBatteryPotentialBC.html", null ],
        [ "BatteryPotentialVC< T >", "structBatteryPotentialVC.html", null ],
        [ "BatterySpeciesBC< T >", "structBatterySpeciesBC.html", null ],
        [ "BatterySpeciesVC< T >", "structBatterySpeciesVC.html", null ],
        [ "BatteryThermalBC< T >", "structBatteryThermalBC.html", null ],
        [ "BatteryThermalVC< T >", "structBatteryThermalVC.html", null ],
        [ "COMETBC< T >", "structCOMETBC.html", null ],
        [ "COMETBC< T >", "structCOMETBC.html", null ],
        [ "COMETModelOptions< T >", "structCOMETModelOptions.html", null ],
        [ "COMETModelOptions< T >", "structCOMETModelOptions.html", null ],
        [ "COMETVC< T >", "structCOMETVC.html", null ],
        [ "ContactModelConstants< T >", "structContactModelConstants.html", null ],
        [ "ElectricBC< T >", "structElectricBC.html", null ],
        [ "ElectricModelConstants< T >", "structElectricModelConstants.html", null ],
        [ "ElectricModelOptions< T >", "structElectricModelOptions.html", null ],
        [ "ElectricVC< T >", "structElectricVC.html", null ],
        [ "FlowBC< T >", "structFlowBC.html", null ],
        [ "FlowModelOptions< T >", "structFlowModelOptions.html", null ],
        [ "FlowVC< T >", "structFlowVC.html", null ],
        [ "FractureBC< T >", "structFractureBC.html", null ],
        [ "FractureModelOptions< T >", "structFractureModelOptions.html", null ],
        [ "FractureVC< T >", "structFractureVC.html", null ],
        [ "IdealGasVC< T >", "structIdealGasVC.html", null ],
        [ "KeBC< T >", "structKeBC.html", null ],
        [ "KeModelOptions< T >", "structKeModelOptions.html", null ],
        [ "KeVC< T >", "structKeVC.html", null ],
        [ "KineticBC< T >", "structKineticBC.html", null ],
        [ "KineticModelOptions< T >", "structKineticModelOptions.html", null ],
        [ "KineticVC< T >", "structKineticVC.html", null ],
        [ "MovingMeshModelOptions< T >", "structMovingMeshModelOptions.html", null ],
        [ "PhononBC< T >", "structPhononBC.html", null ],
        [ "PhononModelOptions< T >", "structPhononModelOptions.html", null ],
        [ "PlateBC< T >", "structPlateBC.html", null ],
        [ "PlateModelOptions< T >", "structPlateModelOptions.html", null ],
        [ "PlateVC< T >", "structPlateVC.html", null ],
        [ "RosselandVC< T >", "structRosselandVC.html", null ],
        [ "SpeciesBC< T >", "structSpeciesBC.html", null ],
        [ "SpeciesModelOptions< T >", "structSpeciesModelOptions.html", null ],
        [ "SpeciesVC< T >", "structSpeciesVC.html", null ],
        [ "StructureBC< T >", "structStructureBC.html", null ],
        [ "StructureModelOptions< T >", "structStructureModelOptions.html", null ],
        [ "StructureVC< T >", "structStructureVC.html", null ],
        [ "ThermalBC< T >", "structThermalBC.html", null ],
        [ "ThermalModelOptions< T >", "structThermalModelOptions.html", null ],
        [ "ThermalVC< T >", "structThermalVC.html", null ],
        [ "VacancyBC< T >", "structVacancyBC.html", null ],
        [ "VacancyModelOptions< T >", "structVacancyModelOptions.html", null ],
        [ "VacancyVC< T >", "structVacancyVC.html", null ]
      ] ],
      [ "FloatVarDict< double >", "classFloatVarDict.html", [
        [ "FlowModelOptions< double >", "structFlowModelOptions.html", null ]
      ] ],
      [ "FloatVarDict< T_Scalar >", "classFloatVarDict.html", [
        [ "ElectricModelConstants< T_Scalar >", "structElectricModelConstants.html", null ],
        [ "KeModelOptions< T_Scalar >", "structKeModelOptions.html", null ]
      ] ],
      [ "FloatVarDict< X >", "classFloatVarDict.html", [
        [ "COMETModelOptions< X >", "structCOMETModelOptions.html", null ],
        [ "COMETModelOptions< X >", "structCOMETModelOptions.html", null ],
        [ "KineticModelOptions< X >", "structKineticModelOptions.html", null ],
        [ "PhononModelOptions< X >", "structPhononModelOptions.html", null ]
      ] ]
    ] ],
    [ "Matrix", "classMatrix.html", [
      [ "CRMatrix< T_Diag, T_OffDiag, X >", "classCRMatrix.html", null ],
      [ "CRMatrixRect< T_Coeff, X, B >", "classCRMatrixRect.html", null ],
      [ "CRMatrixTranspose< T_Coeff, X, B >", "classCRMatrixTranspose.html", null ],
      [ "DiagonalMatrix< Diag, X >", "classDiagonalMatrix.html", null ],
      [ "FluxJacobianMatrix< OffDiag, X >", "classFluxJacobianMatrix.html", null ],
      [ "SpikeMatrix< T_Diag, T_OffDiag, X >", "classSpikeMatrix.html", null ]
    ] ],
    [ "MatrixJML< T >", "classMatrixJML.html", [
      [ "ArrowHeadMatrix< X, K >", "classArrowHeadMatrix.html", null ],
      [ "CometMatrix< T >", "classCometMatrix.html", null ],
      [ "SquareMatrix< T, N >", "classSquareMatrix.html", null ],
      [ "SquareMatrixESBGK< T >", "classSquareMatrixESBGK.html", null ]
    ] ],
    [ "MatrixTraitHelper< T >", "structMatrixTraitHelper.html", null ],
    [ "MatrixTraitHelper< Vector< T, N > >", "structMatrixTraitHelper_3_01Vector_3_01T_00_01N_01_4_01_4.html", null ],
    [ "Mesh", "classMesh.html", [
      [ "UMesh", "classUMesh.html", null ]
    ] ],
    [ "MeshAssembler", "classMeshAssembler.html", null ],
    [ "MeshDismantler", "classMeshDismantler.html", null ],
    [ "MeshPartitioner", "classMeshPartitioner.html", null ],
    [ "minModLim", "structminModLim.html", null ],
    [ "Model", "classModel.html", [
      [ "BatteryModel< T >", "classBatteryModel.html", null ],
      [ "COMETModel< T >", "classCOMETModel.html", null ],
      [ "COMETModel< T >", "classCOMETModel.html", null ],
      [ "ContactModel< T >", "classContactModel.html", null ],
      [ "ElectricModel< T >", "classElectricModel.html", null ],
      [ "FlowModel< T >", "classFlowModel.html", null ],
      [ "FractureModel< T >", "classFractureModel.html", null ],
      [ "GradientModelBase", "classGradientModelBase.html", [
        [ "GradientModel< X >", "classGradientModel.html", null ],
        [ "GradientModel< T >", "classGradientModel.html", null ],
        [ "GradientModel< Vector >", "classGradientModel.html", null ],
        [ "GradientModel< Vector< T, 3 > >", "classGradientModel.html", null ]
      ] ],
      [ "IdealGasDensityModel< T >", "classIdealGasDensityModel.html", null ],
      [ "KeModel< T >", "classKeModel.html", null ],
      [ "KineticModel< T >", "classKineticModel.html", null ],
      [ "MeshMetricsCalculator< T >", "classMeshMetricsCalculator.html", null ],
      [ "MovingMeshModel< T >", "classMovingMeshModel.html", null ],
      [ "PhononModel< T >", "classPhononModel.html", null ],
      [ "PlateDeformationModel< T >", "classPlateDeformationModel.html", null ],
      [ "PlateModel< T >", "classPlateModel.html", null ],
      [ "RosselandModel< T >", "classRosselandModel.html", null ],
      [ "SpeciesModel< T >", "classSpeciesModel.html", null ],
      [ "StructureDeformationModel< T >", "classStructureDeformationModel.html", null ],
      [ "StructureModel< T >", "classStructureModel.html", null ],
      [ "ThermalModel< T >", "classThermalModel.html", null ],
      [ "VacancyModel< T >", "classVacancyModel.html", null ]
    ] ],
    [ "MPM", "classMPM.html", null ],
    [ "MultiFieldMatrix", "classMultiFieldMatrix.html", null ],
    [ "MultiFieldReduction", "classMultiFieldReduction.html", null ],
    [ "MyCoords", "structMyCoords.html", null ],
    [ "MyPoint", "structMyPoint.html", null ],
    [ "AABB::MySegmentPrimitive", "structAABB_1_1MySegmentPrimitive.html", null ],
    [ "AABB::MyTriangle", "structAABB_1_1MyTriangle.html", null ],
    [ "AABB::MyTrianglePrimitive", "structAABB_1_1MyTrianglePrimitive.html", null ],
    [ "NcDataReader", "classNcDataReader.html", null ],
    [ "NcDataWriter", "classNcDataWriter.html", null ],
    [ "ContactModel< T >::NearestCell", "classContactModel_1_1NearestCell.html", null ],
    [ "NearestCell", "structNearestCell.html", null ],
    [ "NearestIBFace", "structNearestIBFace.html", null ],
    [ "NumTypeTraits< bool >", "structNumTypeTraits_3_01bool_01_4.html", null ],
    [ "NumTypeTraits< double >", "structNumTypeTraits_3_01double_01_4.html", null ],
    [ "NumTypeTraits< float >", "structNumTypeTraits_3_01float_01_4.html", null ],
    [ "NumTypeTraits< int >", "structNumTypeTraits_3_01int_01_4.html", null ],
    [ "Octree", "classOctree.html", null ],
    [ "OneDConduction< T >", "classOneDConduction.html", null ],
    [ "OneToOneIndexMap", "classOneToOneIndexMap.html", null ],
    [ "ospre", "structospre.html", null ],
    [ "GradientMatrix< T_Scalar >::PairWiseAssembler", "classGradientMatrix_1_1PairWiseAssembler.html", null ],
    [ "CRMatrix< T_Diag, T_OffDiag, X >::PairWiseAssembler", "classCRMatrix_1_1PairWiseAssembler.html", null ],
    [ "CRMatrixRect< T_Coeff, X, B >::PairWiseAssembler", "classCRMatrixRect_1_1PairWiseAssembler.html", null ],
    [ "PartMesh", "classPartMesh.html", null ],
    [ "PC< ORDER, DIM >", "classPC.html", null ],
    [ "PhononBoundary< X >", "classPhononBoundary.html", null ],
    [ "PhononInterface< X >", "classPhononInterface.html", null ],
    [ "PhononMacro", "structPhononMacro.html", null ],
    [ "PlateBCS< X, Diag, OffDiag >", "classPlateBCS.html", null ],
    [ "PlateFields", "structPlateFields.html", null ],
    [ "pmode< T >", "classpmode.html", null ],
    [ "Octree::Point", "structOctree_1_1Point.html", null ],
    [ "Prism", "structPrism.html", null ],
    [ "PyCreatable", null, [
      [ "Connectivity", "classConnectivity.html", null ]
    ] ],
    [ "Pyramid", "structPyramid.html", null ],
    [ "Quad", "structQuad.html", null ],
    [ "Quadrature< T >", "classQuadrature.html", null ],
    [ "Quadrature< X >", "classQuadrature.html", null ],
    [ "Reader", "classReader.html", [
      [ "MMReader", "classMMReader.html", null ],
      [ "SchemeReader", "classSchemeReader.html", [
        [ "FluentReader", "classFluentReader.html", null ]
      ] ]
    ] ],
    [ "RelTimeFun< T >", "structRelTimeFun.html", null ],
    [ "RLogInterface", "classRLogInterface.html", null ],
    [ "runtime_error", null, [
      [ "CException", "classCException.html", null ]
    ] ],
    [ "ScatteringKernel< T >", "classScatteringKernel.html", null ],
    [ "ShockTube< T >", "classShockTube.html", null ],
    [ "SpeciesFields", "structSpeciesFields.html", null ],
    [ "SpeciesModelFields", "structSpeciesModelFields.html", null ],
    [ "SpikeStorage", "classSpikeStorage.html", null ],
    [ "SquareTensor< T, N >", "classSquareTensor.html", null ],
    [ "SquareTensor< X, K >", "classSquareTensor.html", null ],
    [ "StorageSite", "classStorageSite.html", null ],
    [ "StressTensor< T >", "classStressTensor.html", null ],
    [ "StructureBCS< X, Diag, OffDiag >", "classStructureBCS.html", null ],
    [ "StructureFields", "structStructureFields.html", null ],
    [ "superbee", "structsuperbee.html", null ],
    [ "SuperbeeLimiter", "structSuperbeeLimiter.html", null ],
    [ "T", null, [
      [ "NumTypeTraits< T >", "structNumTypeTraits.html", null ]
    ] ],
    [ "Tangent", "classTangent.html", null ],
    [ "Tet", "structTet.html", null ],
    [ "ThermalFields", "structThermalFields.html", null ],
    [ "TractionValEvaluator< T >", "classTractionValEvaluator.html", null ],
    [ "Tri", "structTri.html", null ],
    [ "UnorderedSet", "classUnorderedSet.html", null ],
    [ "VacancyFields", "structVacancyFields.html", null ],
    [ "vanAlbada1", "structvanAlbada1.html", null ],
    [ "vanLeer", "structvanLeer.html", null ],
    [ "Vector< T, N >", "classVector.html", null ],
    [ "Vector< double, 3 >", "classVector.html", null ],
    [ "Vector< int, 2 >", "classVector.html", null ],
    [ "Vector< T, 3 >", "classVector.html", null ],
    [ "Vector< T_Scalar, 3 >", "classVector.html", null ],
    [ "Vector< X, K >", "classVector.html", null ],
    [ "Vector< X, N >", "classVector.html", null ],
    [ "VectorTranspose< T, N >", "classVectorTranspose.html", null ],
    [ "VectorTranspose< X, K >", "classVectorTranspose.html", null ],
    [ "VTKWriter< T >", "classVTKWriter.html", null ]
];