Memosa-FVM: IBManager.cpp File Reference
IBManager.cpp File Reference
#include "IBManager.h"
#include "AABB.h"
#include "KSearchTree.h"
#include "Mesh.h"
#include "GradientModel.h"
#include <stack>
#include <iostream>
#include <fstream>
Functions
void addFluidNeighbors (set< int > &neighbors, const CRConnectivity &cellCells, const Array< int > &ibType)
Function Documentation
void addFluidNeighbors (set< int > & neighbors, const CRConnectivity & cellCells, const Array< int > & ibType)
given a set of cells, add all their fluid ibtype neighbors to the list if they aren't already in it.
Definition at line 575 of file IBManager.cpp.
References CRConnectivity::getCount(), and Mesh::IBTYPE_FLUID.
Referenced by IBManager::createIBInterpolationStencil(), and IBManager::createSolidInterpolationStencil().
 {
   set<int> newNeighbors;
   foreach(int c, neighbors)
   {
       const int neighborCount = cellCells.getCount(c);
       for(int nnb=0; nnb<neighborCount; nnb++)
       {
           const int c_nb = cellCells(c,nnb);
           if (ibType[c_nb] == Mesh::IBTYPE_FLUID)
             newNeighbors.insert(c_nb);
       }
   }
   neighbors.insert(newNeighbors.begin(),newNeighbors.end());
 }