Memosa-FVM: Octree.cpp File Reference
Octree.cpp File Reference
#include "Octree.h"
#include "NumType.h"
Typedefs
typedef Octree::Point Point
typedef Octree::Bounds Bounds
typedef Octree::VectorT3Array VectorT3Array
typedef Octree::VectorT3 VectorT3
Functions
double max (double x, double y)
double min (double x, double y)
Typedef Documentation
typedef Octree::Bounds Bounds
Definition at line 13 of file Octree.cpp.
typedef Octree::Point Point
Definition at line 12 of file Octree.cpp.
typedef Octree::VectorT3 VectorT3
Definition at line 15 of file Octree.cpp.
typedef Octree::VectorT3Array VectorT3Array
Definition at line 14 of file Octree.cpp.
Function Documentation
double max (double x, double y) inline
Definition at line 18 of file Octree.cpp.
Referenced by Octree::calcCubicBounds(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), CRMatrix< T_Diag, T_OffDiag, X >::createCoarsening(), findMax(), CRConnectivity::getLocalizedSubsetOfFaceCells(), MeshPartitioner::level1_scatter_gather_cells(), ArrayScalarTraits< double >::limit(), ArrayScalarTraits< float >::limit(), ArrayScalarTraits< Vector< T, N > >::limit(), ArrayScalarTraits< PC< ORDER, DIM > >::limit(), SpikeMatrix< T_Diag, T_OffDiag, X >::luSolver(), PartMesh::mesh_setup(), MeshPartitioner::mesh_setup(), minModLim::operator()(), superbee::operator()(), PartMesh::order_faceCells_faceNodes(), MeshDismantler::partitionInterfaceMappers(), FlowModel< T >::Impl::setDirichlet(), SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull(), and IBManager::update().
 {
   return (x>y ? x:y);
 }
double min (double x, double y) inline
Definition at line 23 of file Octree.cpp.
Referenced by DensityOfStates< T >::addMode(), Octree::borderDistance(), Octree::calcCubicBounds(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), findMin(), MeshPartitioner::level1_scatter_gather_cells(), ArrayScalarTraits< double >::limit(), ArrayScalarTraits< float >::limit(), ArrayScalarTraits< Vector< T, N > >::limit(), ArrayScalarTraits< PC< ORDER, DIM > >::limit(), SpikeMatrix< T_Diag, T_OffDiag, X >::lu(), SpikeMatrix< T_Diag, T_OffDiag, X >::luSolver(), DensityOfStates< T >::mergeBins(), PartMesh::mesh_setup(), MeshPartitioner::mesh_setup(), minModLim::operator()(), superbee::operator()(), MeshDismantler::partitionInterfaceMappers(), SpikeMatrix< T_Diag, T_OffDiag, X >::setLSpikeMtrx(), SpikeMatrix< T_Diag, T_OffDiag, X >::setRSpikeMtrxFull(), and IBManager::update().
 {
   return (x>y ? y:x);
 }