Memosa-FVM: PC.h File Reference
PC.h File Reference
#include "NumType.h"
#include "misc.h"
#include "PCSet.h"
Classes
class Initializer< X, T_iterator >
struct Factorial< N >
struct Factorial< 0 >
class PC< ORDER, DIM >
struct ArrayScalarTraits< PC< ORDER, DIM > >
Macros
#define PC_RELATIONAL_OPS(opname, _op_)
#define PC_BINARY_OP(opname, _op_)
Functions
PCSet * createPCSet (const int order, const int dim)
PC_BINARY_OP (operator+,+=)
PC_BINARY_OP (operator-,-=)
PC_BINARY_OP (operator*,*=)
PC_BINARY_OP (operator/,/=)
template<int ORDER, int DIM>
PC< ORDER, DIM > operator+ (const PC< ORDER, DIM > &a)
template<int ORDER, int DIM>
PC< ORDER, DIM > operator- (const PC< ORDER, DIM > &a)
template<int ORDER, int DIM>
PC< ORDER, DIM > fabs (const PC< ORDER, DIM > &a)
template<int ORDER, int DIM>
ostream & operator<< (ostream &os, const PC< ORDER, DIM > &a)
template<int ORDER, int DIM>
PC< ORDER, DIM > sqrt (const PC< ORDER, DIM > &a)
template<int ORDER, int DIM>
double stdDev (const PC< ORDER, DIM > &a)
Macro Definition Documentation
#define PC_BINARY_OP (opname, _op_)
Value:
template<int ORDER, int DIM>                                          \
  PC<ORDER,DIM> opname(const PC<ORDER,DIM>& a, const PC<ORDER,DIM>& b)  \
  {                                                                     \
    return PC<ORDER,DIM>(a) _op_ b;                                     \
  }                                                                     \
  template<int ORDER, int DIM>                                          \
  PC<ORDER,DIM> opname(const PC<ORDER,DIM>& a, const double& b)         \
  {                                                                     \
    return PC<ORDER,DIM>(a) _op_ b;                                     \
  }                                                                     \
  template<int ORDER, int DIM>                                          \
  PC<ORDER,DIM> opname(const double& a, const PC<ORDER,DIM>& b)         \
  {                                                                     \
    return PC<ORDER,DIM>(a) _op_ b;                                     \
  }                                                                     \
Definition at line 303 of file PC.h.
#define PC_RELATIONAL_OPS (opname, _op_)
Value:
bool opname(const PC& o) const                \
  {                                             \
    return (_data[0] _op_ o._data[0]);          \
  }                                             \
    bool opname(const double& o) const          \
  {                                             \
    return (_data[0] _op_ o);                   \
  }
Definition at line 191 of file PC.h.
Function Documentation
PCSet* createPCSet (const int order, const int dim)
Definition at line 9 of file PC.cpp.
 {
   PCSet *pc = new PCSet(order,dim,"HG");
   cout << "The number of PC terms in an expansion is "
        << pc->GetNumberPCTerms() << endl;
   pc->SetTaylorTolerance(1.e-15);
   return pc;
 }
template<int ORDER, int DIM> PC<ORDER,DIM> fabs (const PC< ORDER, DIM > & a)
Definition at line 339 of file PC.h.
References PC< ORDER, DIM >::_data, and PC< ORDER, DIM >::fabs().
 {
   PC<ORDER,DIM> x(a);
   x._data[0]=fabs(a._data[0]);
   return x;
 }
template<int ORDER, int DIM> PC<ORDER,DIM> operator+ (const PC< ORDER, DIM > & a)
Definition at line 326 of file PC.h.
 {
   return a;
 }
template<int ORDER, int DIM> PC<ORDER,DIM> operator- (const PC< ORDER, DIM > & a)
Definition at line 332 of file PC.h.
 {
   PC<ORDER,DIM> z;
   return z-a;
 }
template<int ORDER, int DIM> ostream& operator<< (ostream & os, const PC< ORDER, DIM > & a) inline
Definition at line 347 of file PC.h.
References PC< ORDER, DIM >::print().
 {
   a.print(os);
   return os;
 }
PC_BINARY_OP (operator+ , +)
PC_BINARY_OP (operator- , -)
PC_BINARY_OP (operator* , *)
PC_BINARY_OP (operator/ , /)
template<int ORDER, int DIM> PC<ORDER,DIM> sqrt (const PC< ORDER, DIM > & a)
Definition at line 355 of file PC.h.
References PC< ORDER, DIM >::_data.
 {
   PC<ORDER,DIM> r;
   PC<ORDER,DIM>::_pcSet->RPow(a._data,r._data,0.5);
   return r;
 }
template<int ORDER, int DIM> double stdDev (const PC< ORDER, DIM > & a)
Definition at line 363 of file PC.h.
References PC< ORDER, DIM >::_data.
Referenced by main().
 {
   return PC<ORDER,DIM>::_pcSet->StDv(a._data);
 }