Memosa-FVM: SquareTensor.h File Reference
SquareTensor.h File Reference
#include "NumType.h"
#include "Vector.h"
#include <sstream>
#include "CRConnectivity.h"
Classes
class SquareTensor< T, N >
Functions
template<class T , int N>
ostream & operator<< (ostream &os, const SquareTensor< T, N > &v)
template<class T , int N>
SquareTensor< T, N > operator+ (const SquareTensor< T, N > &a, const SquareTensor< T, N > &b)
template<class T , int N>
SquareTensor< T, N > operator- (const SquareTensor< T, N > &a, const SquareTensor< T, N > &b)
template<class T , int N>
SquareTensor< T, N > operator- (const SquareTensor< T, N > &a)
template<class T , int N>
SquareTensor< T, N > operator* (const SquareTensor< T, N > &a, const SquareTensor< T, N > &b)
template<class T , int N>
SquareTensor< T, N > operator* (const T s, const SquareTensor< T, N > &a)
template<class T , int N>
SquareTensor< T, N > operator* (const SquareTensor< T, N > &a, const T s)
template<class T , int N>
Vector< T, N > operator* (const SquareTensor< T, N > &a, const Vector< T, N > &b)
template<class T , int N>
SquareTensor< T, N > operator/ (const SquareTensor< T, N > &a, const T s)
template<class T , int N>
Vector< T, N > operator/ (const Vector< T, N > &a, const SquareTensor< T, N > &b)
template<class T , int N>
SquareTensor< T, N > operator/ (const SquareTensor< T, N > &a, const SquareTensor< T, N > &b)
template<class T , int N>
SquareTensor< T, N > operator/ (const T s, const SquareTensor< T, N > &a)
template<class T >
SquareTensor< T, 2 > inverse (const SquareTensor< T, 2 > &a)
template<class T >
SquareTensor< T, 3 > inverse (const SquareTensor< T, 3 > &a)
template<int N>
void setFlatCoeffs (Array< double > &flatCoeffs, const CRConnectivity &flatConnectivity, const Array< SquareTensor< double, N > > &diag, const Array< SquareTensor< double, N > > &offDiag, const CRConnectivity &connectivity)
Function Documentation
template<class T > SquareTensor<T,2> inverse (const SquareTensor< T, 2 > & a)
Definition at line 358 of file SquareTensor.h.
Referenced by operator/(), and SquareTensor< X, K >::operator/=().
 {
   SquareTensor<T,2> inv;
   T det = a(0,0)*a(1,1)-a(0,1)*a(1,0);
   inv(0,0) = a(1,1) / det;
   inv(0,1) = -a(0,1) / det;
   inv(1,0) = -a(1,0) / det;
   inv(1,1) = a(0,0) / det;
   return inv;
 }
template<class T > SquareTensor<T,3> inverse (const SquareTensor< T, 3 > & a)
Definition at line 373 of file SquareTensor.h.
 {
   SquareTensor<T,3> inv;
   T det = a(0,0)*(a(1,1)*a(2,2)-a(1,2)*a(2,1))
     -a(0,1)*(a(1,0)*a(2,2) - a(1,2)*a(2,0))
     +a(0,2)*(a(1,0)*a(2,1) - a(1,1)*a(2,0));
   inv(0,0) =  (a(1,1)*a(2,2) - a(1,2)*a(2,1)) / det;
   inv(0,1) =  (a(0,2)*a(2,1) - a(0,1)*a(2,2)) / det;
   inv(0,2) =  (a(0,1)*a(1,2) - a(0,2)*a(1,1)) / det;
   inv(1,0) =  (a(1,2)*a(2,0) - a(1,0)*a(2,2)) / det;
   inv(1,1) =  (a(0,0)*a(2,2) - a(0,2)*a(2,0)) / det;
   inv(1,2) =  (a(0,2)*a(1,0) - a(0,0)*a(1,2)) / det;
   inv(2,0) =  (a(1,0)*a(2,1) - a(1,1)*a(2,0)) / det;
   inv(2,1) =  (a(0,1)*a(2,0) - a(0,0)*a(2,1)) / det;
   inv(2,2) =  (a(0,0)*a(1,1) - a(0,1)*a(1,0)) / det;
   return inv;
 }
template<class T , int N> SquareTensor<T,N> operator* (const SquareTensor< T, N > & a, const SquareTensor< T, N > & b)
Definition at line 291 of file SquareTensor.h.
 {
   return SquareTensor<T,N>(a) *= b;
 }
template<class T , int N> SquareTensor<T,N> operator* (const T s, const SquareTensor< T, N > & a)
Definition at line 298 of file SquareTensor.h.
 {
   return SquareTensor<T,N>(a) *= s;
 }
template<class T , int N> SquareTensor<T,N> operator* (const SquareTensor< T, N > & a, const T s)
Definition at line 305 of file SquareTensor.h.
 {
   return SquareTensor<T,N>(a) *= s;
 }
template<class T , int N> Vector<T,N> operator* (const SquareTensor< T, N > & a, const Vector< T, N > & b)
Definition at line 312 of file SquareTensor.h.
 {
   Vector<T,N> r;
   for(int i=0; i<N; i++)
   {
       r[i] = 0;
       for(int j=0; j<N; j++)
         r[i] += a(i,j)*b[j];
   }
   return r;
 }
template<class T , int N> SquareTensor<T,N> operator+ (const SquareTensor< T, N > & a, const SquareTensor< T, N > & b)
Definition at line 270 of file SquareTensor.h.
 {
   return SquareTensor<T,N>(a) += b;
 }
template<class T , int N> SquareTensor<T,N> operator- (const SquareTensor< T, N > & a, const SquareTensor< T, N > & b)
Definition at line 277 of file SquareTensor.h.
 {
   return SquareTensor<T,N>(a) -= b;
 }
template<class T , int N> SquareTensor<T,N> operator- (const SquareTensor< T, N > & a)
Definition at line 284 of file SquareTensor.h.
 {
   return -SquareTensor<T,N>(a);
 }
template<class T , int N> SquareTensor<T,N> operator/ (const SquareTensor< T, N > & a, const T s)
Definition at line 326 of file SquareTensor.h.
 {
   return SquareTensor<T,N>(a) /= s;
 }
template<class T , int N> Vector<T,N> operator/ (const Vector< T, N > & a, const SquareTensor< T, N > & b)
Definition at line 333 of file SquareTensor.h.
References inverse().
 {
   return inverse(b)*a;
 }
template<class T , int N> SquareTensor<T,N> operator/ (const SquareTensor< T, N > & a, const SquareTensor< T, N > & b)
Definition at line 340 of file SquareTensor.h.
References inverse().
 {
   return inverse(b)*a;
 }
template<class T , int N> SquareTensor<T,N> operator/ (const T s, const SquareTensor< T, N > & a)
Definition at line 348 of file SquareTensor.h.
References inverse().
 {
   SquareTensor<T,N> r(0);
   for(int i=0; i<N; i++) r(i,i) = s;
   return inverse(a)*r;
 }
template<class T , int N> ostream& operator<< (ostream & os, const SquareTensor< T, N > & v) inline
Definition at line 260 of file SquareTensor.h.
References SquareTensor< T, N >::printFromC().
 {
   v.printFromC(os);
   return os;
 }
template<int N> void setFlatCoeffs (Array< double > & flatCoeffs, const CRConnectivity & flatConnectivity, const Array< SquareTensor< double, N > > & diag, const Array< SquareTensor< double, N > > & offDiag, const CRConnectivity & connectivity)
Definition at line 396 of file SquareTensor.h.
References CRConnectivity::getCoeffPosition(), CRConnectivity::getCol(), CRConnectivity::getRow(), and CRConnectivity::getRowDim().
 {
     const Array<int>& myRow = connectivity.getRow();
     const Array<int>& myCol = connectivity.getCol();
     const int rowDim = connectivity.getRowDim();
     for(int i=0; i<rowDim; i++)
     {
         for(int ndr=0; ndr<N; ndr++)
           for(int ndc=0; ndc<N; ndc++)
           {
               const int nfr = i*N + ndr;
               const int nfc = i*N + ndc;
               const int fp = flatConnectivity.getCoeffPosition(nfc,nfr);
               flatCoeffs[fp] = diag[i](ndr,ndc);
           }
         for(int jp=myRow[i]; jp<myRow[i+1]; jp++)
         {
             const int j = myCol[jp];
             for(int ndr=0; ndr<N; ndr++)
               for(int ndc=0; ndc<N; ndc++)
               {
                   const int nfr = i*N + ndr;
                   const int nfc = j*N + ndc;
                   const int fp = flatConnectivity.getCoeffPosition(nfc,nfr);
                   flatCoeffs[fp] = offDiag[jp](ndr,ndc);
             }
       }
   }
 }