Memosa-FVM: NumTypeTraits< double > Struct Template Reference
NumTypeTraits< double > Struct Template Reference
#include <NumType.h>
Public Types
typedef double This_T
typedef double T_Scalar
typedef double T_BuiltIn
Static Public Member Functions
static PrimType getPrimType ()
static string getTypeName ()
static int getDimension ()
static void getShape (int *shp)
static int getDataSize ()
static double getZero ()
static double getUnity ()
static double getNegativeUnity ()
static double sqrt (const double x)
static void write (FILE *fp, const double x)
static double doubleMeasure (const double x)
static void accumulateOneNorm (double &sum, const double &v)
static void accumulateDotProduct (double &sum, const double &v0, const double &v1)
static void reduceSum (T_Scalar &sum, const This_T &x)
static void safeDivide (double &x, const double &y)
static void normalize (double &x, const double &y)
static void setMax (double &x, const double &y)
Detailed Description
template<>
struct NumTypeTraits< double >
Definition at line 90 of file NumType.h.
Member Typedef Documentation
typedef double NumTypeTraits< double >::T_BuiltIn
Definition at line 94 of file NumType.h.
typedef double NumTypeTraits< double >::T_Scalar
Definition at line 93 of file NumType.h.
typedef double NumTypeTraits< double >::This_T
Definition at line 92 of file NumType.h.
Member Function Documentation
static void NumTypeTraits< double >::accumulateDotProduct (double & sum, const double & v0, const double & v1) inline static
Definition at line 109 of file NumType.h.
   { sum += v0*v1;}
static void NumTypeTraits< double >::accumulateOneNorm (double & sum, const double & v) inline static
Definition at line 108 of file NumType.h.
References fabs().
 { sum += fabs(v);}
static double NumTypeTraits< double >::doubleMeasure (const double x) inline static
Definition at line 106 of file NumType.h.
References fabs().
 {return fabs(x);}
static int NumTypeTraits< double >::getDataSize () inline static
Definition at line 100 of file NumType.h.
 {return  sizeof(double);}
static int NumTypeTraits< double >::getDimension () inline static
Definition at line 98 of file NumType.h.
 {return 0;}
static double NumTypeTraits< double >::getNegativeUnity () inline static
Definition at line 103 of file NumType.h.
 {return -1.;}
static PrimType NumTypeTraits< double >::getPrimType () inline static
Definition at line 96 of file NumType.h.
References PRIM_TYPE_DOUBLE.
 {return PRIM_TYPE_DOUBLE;}
static void NumTypeTraits< double >::getShape (int * shp) inline static
Definition at line 99 of file NumType.h.
 {}
static string NumTypeTraits< double >::getTypeName () inline static
Definition at line 97 of file NumType.h.
 {return "double";}
static double NumTypeTraits< double >::getUnity () inline static
Definition at line 102 of file NumType.h.
 {return 1.;}
static double NumTypeTraits< double >::getZero () inline static
Definition at line 101 of file NumType.h.
 {return 0;}
static void NumTypeTraits< double >::normalize (double & x, const double & y) inline static
Definition at line 114 of file NumType.h.
 {if (y!=0) x/=y;}
static void NumTypeTraits< double >::reduceSum (T_Scalar & sum, const This_T & x) inline static
Definition at line 112 of file NumType.h.
 {sum+=x;}
static void NumTypeTraits< double >::safeDivide (double & x, const double & y) inline static
Definition at line 113 of file NumType.h.
 {if (y!=0) x/=y;}
static void NumTypeTraits< double >::setMax (double & x, const double & y) inline static
Definition at line 115 of file NumType.h.
 {if (y>x) x=y;}
static double NumTypeTraits< double >::sqrt (const double x) inline static
Definition at line 104 of file NumType.h.
References sqrt().
 {return ::sqrt(x);}
static void NumTypeTraits< double >::write (FILE * fp, const double x) inline static
Definition at line 105 of file NumType.h.
 {fprintf(fp,"%lf",x);}
The documentation for this struct was generated from the following file:
NumType.h