Memosa-FVM: AABB::MyTriangle Struct Reference
AABB::MyTriangle Struct Reference
Public Member Functions
MyTriangle (const int faceIndex_, const int subFaceIndex_, const Array< Vec3D > &coordArray_, const int v0_, const int v1_, const int v2_)
MyTriangle (const int faceIndex_, const Array< Vec3D > &coordArray_, const int v0_, const int v1_)
Point getVertex (const int n) const
Point2D getVertex2D (const int n) const
Triangle getTriangle () const
K::Segment_2 getSegment2D () const
K::Segment_3 getSegment () const
Plane getPlane () const
Line2D getLine2D () const
Public Attributes
const int faceIndex
const int subFaceIndex
const Array< Vec3D > & coordArray
int vertices [3]
Detailed Description
Definition at line 78 of file AABB.h.
Constructor & Destructor Documentation
AABB::MyTriangle::MyTriangle (const int faceIndex_, const int subFaceIndex_, const Array< Vec3D > & coordArray_, const int v0_, const int v1_, const int v2_) inline
Definition at line 85 of file AABB.h.
References vertices.
                               :
       faceIndex(faceIndex_),
       subFaceIndex(subFaceIndex_),
       coordArray(coordArray_)
     {
       vertices[0] = v0_;
       vertices[1] = v1_;
       vertices[2] = v2_;
     }
AABB::MyTriangle::MyTriangle (const int faceIndex_, const Array< Vec3D > & coordArray_, const int v0_, const int v1_) inline
Definition at line 100 of file AABB.h.
References vertices.
                               :
       faceIndex(faceIndex_),
       subFaceIndex(0),
       coordArray(coordArray_)
     {
       vertices[0] = v0_;
       vertices[1] = v1_;
       vertices[2] = -1;
     }
Member Function Documentation
Line2D AABB::MyTriangle::getLine2D () const inline
Definition at line 151 of file AABB.h.
References getVertex2D().
Referenced by AABB::findOrientedSide().
     {
       // CGAL's line orientation is opposite ours in 2d
       return Line2D(getVertex2D(1),
                    getVertex2D(0));
     }
Plane AABB::MyTriangle::getPlane () const inline
Definition at line 144 of file AABB.h.
References getVertex().
Referenced by AABB::findOrientedSide().
     {
       return Plane(getVertex(0),
                    getVertex(1),
                    getVertex(2));
     }
K::Segment_3 AABB::MyTriangle::getSegment () const inline
Definition at line 138 of file AABB.h.
References getVertex().
Referenced by AABB::MySegmentPrimitive::datum().
     {
       return K::Segment_3(getVertex(0),
                           getVertex(1));
     }
K::Segment_2 AABB::MyTriangle::getSegment2D () const inline
Definition at line 132 of file AABB.h.
References getVertex2D().
Referenced by AABB::findOrientedSide().
     {
       return K::Segment_2(getVertex2D(0),
                           getVertex2D(1));
     }
Triangle AABB::MyTriangle::getTriangle () const inline
Definition at line 125 of file AABB.h.
References getVertex().
Referenced by AABB::MyTrianglePrimitive::datum(), and AABB::findOrientedSide().
     {
       return Triangle(getVertex(0),
                       getVertex(1),
                       getVertex(2));
     }
Point AABB::MyTriangle::getVertex (const int n) const inline
Definition at line 113 of file AABB.h.
References coordArray, and vertices.
Referenced by getPlane(), getSegment(), getTriangle(), AABB::MyTrianglePrimitive::reference_point(), and AABB::MySegmentPrimitive::reference_point().
     {
       const Vec3D& v = coordArray[vertices[n]];
       return Point(v[0], v[1], v[2]);
     }
Point2D AABB::MyTriangle::getVertex2D (const int n) const inline
Definition at line 119 of file AABB.h.
References coordArray, and vertices.
Referenced by getLine2D(), and getSegment2D().
     {
       const Vec3D& v = coordArray[vertices[n]];
       return Point2D(v[0], v[1]);
     }
Member Data Documentation
const Array<Vec3D>& AABB::MyTriangle::coordArray
Definition at line 82 of file AABB.h.
Referenced by getVertex(), and getVertex2D().
const int AABB::MyTriangle::faceIndex
Definition at line 80 of file AABB.h.
const int AABB::MyTriangle::subFaceIndex
Definition at line 81 of file AABB.h.
int AABB::MyTriangle::vertices[3]
Definition at line 83 of file AABB.h.
Referenced by getVertex(), getVertex2D(), and MyTriangle().
The documentation for this struct was generated from the following file:
AABB.h