Memosa-FVM: Vector.h File Reference
Vector.h File Reference
#include "NumType.h"
#include <sstream>
Classes
class Vector< T, N >
struct ArrayScalarTraits< Vector< T, N > >
Functions
string intAsString (const int i)
template<class T , int N>
ostream & operator<< (ostream &os, const Vector< T, N > &v)
template<class T >
Vector< T, 3 > cross (const Vector< T, 3 > &a, const Vector< T, 3 > &b)
template<class T >
T dot (const Vector< T, 3 > &a, const Vector< T, 3 > &b)
template<class T >
T mag (const Vector< T, 3 > &a)
template<class T >
T mag2 (const Vector< T, 3 > &a)
template<class T , int N>
Vector< T, N > operator+ (const Vector< T, N > &a, const Vector< T, N > &b)
template<class T , int N>
Vector< T, N > operator- (const Vector< T, N > &a, const Vector< T, N > &b)
template<class T , int N>
Vector< T, N > operator- (const Vector< T, N > &a)
template<class T , int N>
Vector< T, N > operator* (const T s, const Vector< T, N > &a)
template<class T , int N>
Vector< T, N > operator* (const Vector< T, N > &a, const T s)
template<class T , int N>
Vector< T, N > operator* (const Vector< T, N > &a, const Vector< T, N > &b)
template<class T , int N>
Vector< T, N > operator/ (const Vector< T, N > &a, const T s)
template<class T , int N>
Vector< T, N > operator/ (const Vector< T, N > &a, const Vector< T, N > &b)
Function Documentation
template<class T > Vector<T,3> cross (const Vector< T, 3 > & a, const Vector< T, 3 > & b)
Definition at line 242 of file Vector.h.
Referenced by MeshMetricsCalculator< T >::calculateFaceAreas(), MeshMetricsCalculator< T >::calculateFaceCentroids(), Mesh::COMETfindCommonFaces(), Mesh::findCommonFaces(), and MovingMeshModel< T >::volChange().
 {
   Vector<T,3> c;
   c[0] = a[1]*b[2]-a[2]*b[1];
   c[1] = a[2]*b[0]-a[0]*b[2];
   c[2] = a[0]*b[1]-a[1]*b[0];
   return c;
 }
template<class T > T dot (const Vector< T, 3 > & a, const Vector< T, 3 > & b)
Definition at line 253 of file Vector.h.
Referenced by MovingMeshModel< T >::advance(), StructureBCS< X, Diag, OffDiag >::applySymmetryBC(), PlateBCS< X, Diag, OffDiag >::applySymmetryBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, T >::applySymmetryBC(), GenericBCS< Vector< T, N >, DiagonalTensor< T, N >, DiagonalTensor< T, N > >::applySymmetryBC(), GenericBCS< Vector< T, N >, SquareTensor< T, N >, SquareTensor< T, N > >::applySymmetryBC(), MeshMetricsCalculator< T >::calculateCellCentroids(), MeshMetricsCalculator< T >::calculateCellVolumes(), MeshMetricsCalculator< T >::calculateFaceCentroids(), MeshMetricsCalculator< T >::computeGridInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatrices(), MeshMetricsCalculator< T >::computeIBInterpolationMatricesCells(), MeshMetricsCalculator< T >::computeSolidInterpolationMatrices(), ElectricModel< T >::Impl::computeSolidSurfaceForce(), correctVelocityInterior(), BatteryElectricDiffusionDiscretization< X, Diag, OffDiag >::discretize(), ElecDiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), BatteryBinaryElectrolyteDiscretization< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), BatteryPCDiffusionDiscretization< X, Diag, OffDiag >::discretize(), WallDiscretization< X, Diag, OffDiag >::discretize(), StructureSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), StructurePlasticDiscretization< T, Diag, OffDiag >::discretizeFaces(), PlateSourceDiscretization< T, Diag, OffDiag >::discretizeFaces(), discretizeMassFluxInterior(), distanceFromPointToLine(), Grid::findNeighborsByCells(), fixedFluxContinuityBC(), fixedPressureContinuityBC(), inCell(), FlowModel< T >::Impl::linearizeContinuity(), mag(), mag2(), VectorTranspose< X, K >::operator*=(), TractionValEvaluator< T >::operator[](), projectionFromPointToLine(), slipJumpMomentumBC(), ElectricModel< T >::Impl::updateConvectionFlux(), updateFacePressureInterior(), FlowModel< T >::Impl::updateFacePressureInterior(), and MovingMeshModel< T >::volChange().
 {
   return a[0]*b[0]+a[1]*b[1]+a[2]*b[2];
 }
string intAsString (const int i) inline
Definition at line 11 of file Vector.h.
Referenced by VectorTranspose< X, K >::getTypeName(), DiagonalTensor< T, N >::getTypeName(), Vector< int, 2 >::getTypeName(), SquareTensor< X, K >::getTypeName(), ElecOffDiagonalTensor< T, N >::getTypeName(), and ElecDiagonalTensor< T, N >::getTypeName().
 {
   ostringstream osBuffer;
   osBuffer << i;
   return osBuffer.str();
 }
template<class T > T mag (const Vector< T, 3 > & a)
Definition at line 260 of file Vector.h.
References dot(), and sqrt().
Referenced by MovingMeshModel< T >::advance(), MeshMetricsCalculator< T >::calculateFaceAreaMag(), StructureDeformationModel< T >::calculateNodeDisplacement(), PlateDeformationModel< T >::calculateNodeDisplacement(), Mesh::COMETfindCommonFaces(), ElectricModel< T >::Impl::computeSolidSurfaceForce(), correctVelocityInterior(), TrapBandTunnelingDiscretization< X, Diag, OffDiag >::discretize(), LinearizeDielectric< X, Diag, OffDiag >::discretize(), DiffusionDiscretization< X, Diag, OffDiag >::discretize(), EmissionDiscretization< X, Diag, OffDiag >::discretize(), distanceFromPointToLine(), Mesh::findCommonFaces(), Mesh::findCommonNodes(), Grid::findNeighborsByCells(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix2D(), GradientModel< Vector< T, 3 > >::getLeastSquaresGradientMatrix3D(), COMETModel< T >::MakeCoarseMesh1(), projectionFromPointToLine(), MPM::setandwriteParticles(), ElectricModel< T >::Impl::updateElectronVelocity(), and updateFacePressureInterior().
 {
   return sqrt(dot(a,a));
 }
template<class T > T mag2 (const Vector< T, 3 > & a)
Definition at line 267 of file Vector.h.
References dot().
Referenced by Mesh::COMETfindCommonFaces(), IBManager::createIBInterpolationStencil(), IBManager::createSolidInterpolationStencil(), Mesh::findCommonFaces(), IBManager::findNearestCellForSolidFaces(), fixedPressureContinuityBC(), fixedPressureMomentumBC(), Octree::getNode(), Octree::getNodes(), Octree::Naive_getNode(), Octree::Naive_getNodes(), and pressureBoundaryPostContinuitySolve().
 {
   return dot(a,a);
 }
template<class T , int N> Vector<T,N> operator* (const T s, const Vector< T, N > & a)
Definition at line 295 of file Vector.h.
 {
   return Vector<T,N>(a) *= s;
 }
template<class T , int N> Vector<T,N> operator* (const Vector< T, N > & a, const T s)
Definition at line 302 of file Vector.h.
 {
   return Vector<T,N>(a) *= s;
 }
template<class T , int N> Vector<T,N> operator* (const Vector< T, N > & a, const Vector< T, N > & b)
Definition at line 310 of file Vector.h.
 {
   return Vector<T,N>(a) *= b;
 }
template<class T , int N> Vector<T,N> operator+ (const Vector< T, N > & a, const Vector< T, N > & b)
Definition at line 274 of file Vector.h.
 {
   return Vector<T,N>(a) += b;
 }
template<class T , int N> Vector<T,N> operator- (const Vector< T, N > & a, const Vector< T, N > & b)
Definition at line 281 of file Vector.h.
 {
   return Vector<T,N>(a) -= b;
 }
template<class T , int N> Vector<T,N> operator- (const Vector< T, N > & a)
Definition at line 288 of file Vector.h.
 {
   return -Vector<T,N>(a);
 }
template<class T , int N> Vector<T,N> operator/ (const Vector< T, N > & a, const T s)
Definition at line 317 of file Vector.h.
 {
   return Vector<T,N>(a) /= s;
 }
template<class T , int N> Vector<T,N> operator/ (const Vector< T, N > & a, const Vector< T, N > & b)
Definition at line 325 of file Vector.h.
 {
   return Vector<T,N>(a) /= b;
 }
template<class T , int N> ostream& operator<< (ostream & os, const Vector< T, N > & v) inline
Definition at line 233 of file Vector.h.
References Vector< T, N >::printFromC().
 {
   v.printFromC(os);
   return os;
 }