#!/bin/csh
#
# nodes: the number of nodes, max 32
# ppn: number of cpus per node, there are 2 cpus per node
# walltime: requested max wall time for this run
#PBS -l walltime=20:00:00,nodes=1:ppn=1
#
# queue name, use the dedicated queue "class"
#PBS -q prism
#
# export all my environment variables to the job
#PBS -V
#
# job name (default = name of script file)
#
# filename for standard output (default = <job_name>.o<job_id>)
#PBS -o error.o
#
# combine standard output and standard error (optional)
#PBS -j oe
#
# End of embedded QSUB options

set echo               # echo commands before execution; use for debugging

# replace the following "your-working-directory" to your actual working directory
cd $PBS_O_WORKDIR
setenv NPROCS `wc -l <$PBS_NODEFILE`
source /home/ba01/u116/schigull/memosa/env.sh
mpirun -machinefile $PBS_NODEFILE -np $NPROCS  Par_Couette.py --type=quad ../Couette_10.cas
